Repository dotnet/roslyn, pull requests merged in 2018-10, with the labels that each got.

#29794 Add parameter CodefixProvider: Fix argument list handling of local functions
  src/EditorFeatures/CSharpTest/AddParameter/AddParameterTests.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
Labels: Area-IDE, Community

#30225 Update Unix contrib document
  docs/contributing/Building, Debugging, and Testing on Unix.md
Labels: Area-Infrastructure, Documentation

#30173 Fix for InvalidCastException in "Invert If" refactoring
  src/EditorFeatures/CSharpTest/CodeActions/InvertIf/InvertIfTests.cs
  src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions_Negate.cs
Labels: Approved to merge, Area-IDE

#30228 Add some unit-tests
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
  src/Compilers/Test/Utilities/CSharp/SymbolUtilities.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types, Test

#30105 Fix lowering for async-iterator method with type parameter
  docs/features/async-streams.md
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Compilation/ForEachStatementInfo.cs
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncRewriter.AsyncIteratorRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncStateMachine.cs
  src/Compilers/CSharp/Portable/Lowering/IteratorRewriter/IteratorRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/StateMachineRewriter.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberMethodSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncForeachTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs
  src/Compilers/CSharp/Test/Symbol/Compilation/ForEachStatementInfoTests.cs
Labels: Area-Compilers, New Feature - Async Streams

#30166 Updates for running roslyn tests on Mono
  build/scripts/tests.sh
  src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs
  src/Compilers/VisualBasic/Test/Syntax/Syntax/SyntaxFactsTest.vb
  src/Test/Utilities/Portable/Assert/ConditionalFactAttribute.cs
Labels: Area-Infrastructure

#30243 Fixing when keyword recommender in recursive patterns branch
  src/EditorFeatures/CSharpTest2/Recommendations/WhenKeywordRecommenderTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/WhenKeywordRecommender.cs
Labels: Area-IDE, Community, New Language Feature - Pattern Matching

#28780 Merge conditional fact files
  src/Test/Utilities/Portable/Assert/ConditionalFactAttribute.cs
  src/Test/Utilities/Portable/Platform/Desktop/ConditionalFactAttribute.cs
Labels: Area-Compilers, Test

#30274 Merge master into features/recursive-patterns
  build/Targets/Settings.props
  build/scripts/obtain_dotnet.sh
  build/scripts/tests.sh
  docs/contributing/Building, Debugging, and Testing on Unix.md
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitStackAllocInitializer.cs
  src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.IncludeElementExpander.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DeconstructionAssignmentOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TupleBinaryOperator.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Syntax/SyntaxFactory.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_Assembly.cs
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs
  src/Compilers/CSharp/Test/Emit/Attributes/EmitTestStrongNameProvider.cs
  src/Compilers/CSharp/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.cs
  src/Compilers/CSharp/Test/Emit/BreakingChanges.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenCapturing.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenCheckedTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenClosureLambdaTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenDeconstructTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenExplicitImplementationTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenExprLambdaTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenImplicitImplementationTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenInParametersTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOperators.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenStackAllocInitializerTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenStructsAndEnum.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTryFinally.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs
  src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/DesktopStrongNameProviderTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/DeterministicTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/NoPiaEmbedTypes.cs
  src/Compilers/CSharp/Test/Emit/PDB/PDBUsingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
  src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs
  src/Compilers/VisualBasic/Test/Syntax/Syntax/SyntaxFactsTest.vb
  src/EditorFeatures/CSharpTest/AddParameter/AddParameterTests.cs
  src/Features/Core/Portable/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs
  src/Test/Utilities/Portable/Assert/ConditionalFactAttribute.cs
  src/Test/Utilities/Portable/Compilation/IRuntimeEnvironment.cs
  src/Test/Utilities/Portable/CompilationVerifier.cs
  src/Test/Utilities/Portable/FX/CappedStringWriter.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
Labels: Area-Compilers, New Language Feature - Pattern Matching

#30202 Add a overload to AsynchronousViewTaggerProvider for TypeScript
  src/EditorFeatures/Core/Tagging/AsynchronousViewTaggerProvider.cs
Labels: Approved to merge

#30286 Ensure docker stopped on cancel
  .vsts-dnceng.yml
  build/scripts/dockerrun.sh
  build/scripts/dockerstop.sh
Labels: Area-Infrastructure

#30266 Move to Mono Nightly
  build.sh
  build/scripts/docker/Dockerfile
  build/scripts/dockerrun.sh
  build/scripts/tests.sh
Labels: Area-Infrastructure

#30283 'is' operator should not affect StateWhenFalse
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#30155 Add support for displaying reference kind in Find All References window.
  src/EditorFeatures/Core/FindUsages/AbstractFindUsagesService.ProgressAdapter.cs
  src/EditorFeatures/Core/FindUsages/IDefinitionsAndReferencesFactory.cs
  src/Features/Core/Portable/ChangeSignature/DelegateInvokeMethodReferenceFinder.cs
  src/Features/Core/Portable/FindUsages/SourceReferenceItem.cs
  src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs
  src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/AbstractFindUsagesCustomColumnDefinition.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Contexts/AbstractTableDataSourceFindUsagesContext.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Contexts/WithReferencesFindUsagesContext.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Contexts/WithoutReferencesFindUsagesContext.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/DocumentSpanEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/FindUsagesValueUsageInfoColumnDefinition.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/StreamingFindUsagesPresenter.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/Suppression/SuppressionStateColumnDefinition.cs
  src/VisualStudio/Core/Def/ServicesVSResources.Designer.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/Workspaces/CSharp/Portable/Extensions/ExpressionSyntaxExtensions.cs
  src/Workspaces/Core/Portable/Extensions/OperationExtensions.cs
  src/Workspaces/Core/Portable/Extensions/ValueUsageInfo.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/PropertySymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/ReferenceLocation.cs
  src/Workspaces/Core/Portable/Remote/RemoteArguments.cs
  src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs
  src/Workspaces/Core/Portable/WorkspacesResources.Designer.cs
  src/Workspaces/Core/Portable/WorkspacesResources.resx
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.cs.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.de.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.es.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.fr.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.it.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ja.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ko.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.pl.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.pt-BR.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ru.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.tr.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.zh-Hans.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.zh-Hant.xlf
  src/Workspaces/VisualBasic/Portable/Extensions/ExpressionSyntaxExtensions.vb
Labels: Area-IDE

#30290 Enable MS.CA.UnitTests on Mono
  src/Compilers/Core/CodeAnalysisTest/AnalyzerFileReferenceTests.cs
  src/Compilers/Core/CodeAnalysisTest/FileSystem/PathUtilitiesTests.cs
  src/Compilers/Core/CodeAnalysisTest/MetadataReferences/AssemblyIdentityComparerTests.cs
  src/Compilers/Core/CodeAnalysisTest/MetadataReferences/AssemblyIdentityDisplayNameTests.cs
  src/Compilers/Core/CodeAnalysisTest/MetadataReferences/AssemblyIdentityTests.cs
  src/Compilers/Core/CodeAnalysisTest/MetadataReferences/AssemblyPortabilityPolicyTests.cs
  src/Compilers/Core/CodeAnalysisTest/MetadataReferences/FusionAssemblyIdentityTests.cs
  src/Compilers/Core/CodeAnalysisTest/MetadataReferences/ModuleMetadataTests.cs
  src/Compilers/Core/CodeAnalysisTest/StrongNameProviderTests.cs
  src/Compilers/Core/CodeAnalysisTest/Text/TextChangeTests.cs
  src/Compilers/Core/CodeAnalysisTest/Win32Res.cs
  src/Test/Utilities/Portable/Assert/ConditionalFactAttribute.cs
Labels: Area-Compilers

#27094 if FSA is off, make compilation end analyzer build only analyzer.
  src/EditorFeatures/CSharpTest/Diagnostics/DiagnosticAnalyzerDriver/DiagnosticAnalyzerDriverTests.cs
  src/EditorFeatures/Test2/Diagnostics/DiagnosticServiceTests.vb
  src/EditorFeatures/VisualBasicTest/Diagnostics/DiagnosticAnalyzerDriver/DiagnosticAnalyzerDriverTests.vb
  src/Features/Core/Portable/Diagnostics/AnalyzerHelper.cs
  src/Features/Core/Portable/Diagnostics/DiagnosticAnalyzerService.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.ProjectState.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.StateSet.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_BuildSynchronization.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_IncrementalAnalyzer.cs
  src/Features/Core/Portable/Diagnostics/IDiagnosticAnalyzerService.cs
  src/VisualStudio/Core/Def/Implementation/Diagnostics/VisualStudioDiagnosticAnalyzerService.cs
  src/VisualStudio/Core/Def/Implementation/TaskList/ExternalErrorDiagnosticUpdateSource.cs
  src/VisualStudio/Core/Test/Diagnostics/ExternalDiagnosticUpdateSourceTests.vb
  src/VisualStudio/Core/Test/EditAndContinue/EditAndContinueTestHelper.vb
Labels: Area-IDE

#30305 Enable C# scripting on Mono
  build/scripts/tests.sh
  src/Scripting/CSharpTest/CommandLineRunnerTests.cs
  src/Scripting/CSharpTest/InteractiveSessionTests.cs
  src/Scripting/CSharpTest/ObjectFormatterTests.cs
  src/Scripting/CSharpTest/ScriptTests.cs
Labels: Area-Interactive

#30255 Move ILAsm publishing to a project
  build/scripts/build.ps1
  build/scripts/tests.sh
  src/Test/Utilities/Portable/Roslyn.Test.Utilities.csproj
  src/Tools/ILAsm/DeployILAsm.targets
Labels: Area-Compilers

#29307 Allow dispose pattern to be implemented via extension method
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/Binder/UsingStatementBinder.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_UsingStatement.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenUsingStatementTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/UsingStatementTests.cs
Labels: Area-Compilers, New Language Feature - enhanced using

#29934 Change analyzer executor to do an intersection with the given span
  src/EditorFeatures/Test2/Diagnostics/DiagnosticServiceTests.vb
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.Executor.cs
Labels: Approved to merge, Area-IDE, Community

#30342 Skip an integration test and an assert that is firing frequently on d…
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpCodeActions.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpFormatting.cs
Labels: Approved to merge, Area-Infrastructure

#30162 Add thread name to DiagnosticEventTaskScheduler
  src/Features/Core/Portable/Diagnostics/DiagnosticEventTaskScheduler.cs
Labels: Area-IDE, Community

#30332 #30296 Change Signature Dialog update to include VB style.
  src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.cs
Labels: Area-IDE, Community

#30311 Enable C# CommandLine and WinRT tests on Linux
  build/scripts/tests.sh
  src/Compilers/CSharp/Test/CommandLine/CommandLineTestBase.cs
  src/Compilers/CSharp/Test/CommandLine/CommandLineTestResources.Designer.cs
  src/Compilers/CSharp/Test/CommandLine/CommandLineTestResources.resx
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/CommandLine/ErrorLoggerTests.cs
  src/Compilers/CSharp/Test/CommandLine/Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests.csproj
  src/Compilers/CSharp/Test/CommandLine/TouchedFileLoggingTests.cs
  src/Compilers/CSharp/Test/Emit/Resources.Designer.cs
  src/Compilers/CSharp/Test/WinRT/Metadata/WinMdMetadataTests.cs
  src/Compilers/CSharp/Test/WinRT/Microsoft.CodeAnalysis.CSharp.WinRT.UnitTests.csproj
  src/Compilers/CSharp/Test/WinRT/PEParameterSymbolTests.cs
  src/Compilers/CSharp/Test/WinRT/PdbTests.cs
  src/Compilers/Test/Resources/Core/ResourceLoader.cs
  src/Compilers/Test/Utilities/CSharp/MockCSharpCompiler.cs
  src/Compilers/Test/Utilities/VisualBasic/MockVisualBasicCompiler.vb
  src/Test/Utilities/Portable/Compilation/RuntimeUtilities.cs
  src/Test/Utilities/Portable/Roslyn.Test.Utilities.csproj
  src/Tools/BuildBoss/Program.cs
  src/Tools/BuildBoss/ProjectCheckerUtil.cs
Labels: Area-Compilers

#29374 Fix to return attributes of VB.NET enum members when using the code model EnvDTE.CodeVariable.Attributes
  src/VisualStudio/VisualBasic/Impl/CodeModel/VisualBasicCodeModelService.vb
Labels: Area-IDE, Community

#29631 Fix generate field doesn't recognize accessibility modifier configuration
  src/EditorFeatures/CSharpTest/InitializeParameter/InitializeMemberFromParameterTests.cs
  src/EditorFeatures/VisualBasicTest/InitializeParameter/InitializeMemberFromParameterTests.vb
  src/Features/CSharp/Portable/InitializeParameter/CSharpInitializeMemberFromParameterCodeRefactoringProvider.cs
  src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs
  src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicInitializeMemberFromParameterCodeRefactoringProvider.vb
Labels: Area-IDE

#30379 Do not try to convert interpolated string format specifiers into virtual chars
  src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs
  src/EditorFeatures/VisualBasicTest/Classification/SemanticClassifierTests.vb
  src/Workspaces/CSharp/Portable/EmbeddedLanguages/VirtualChars/CSharpVirtualCharService.cs
  src/Workspaces/VisualBasic/Portable/EmbeddedLanguages/VirtualChars/VisualBasicVirtualCharService.vb
Labels: Approved to merge, Area-IDE

#30209 fixed DebugType ArgumentNullException in CommandLineArgumentReader
  src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/CommandLineArgumentReader.cs
  src/Workspaces/CoreTestUtilities/Resources/ProjectFiles/CSharp/ProjectLoadErrorOnMissingDebugType.csproj
  src/Workspaces/CoreTestUtilities/Resources/SolutionFiles/ProjectLoadErrorOnMissingDebugType.sln
  src/Workspaces/CoreTestUtilities/TestFiles/Resources.cs
  src/Workspaces/MSBuildTest/MSBuildWorkspaceTests.cs
Labels: Area-IDE, Bug

#30245 Incorrect "Cast is redundant" code action when casting enum to int
  src/EditorFeatures/CSharpTest/Diagnostics/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs
  src/Workspaces/CSharp/Portable/Utilities/SpeculationAnalyzer.cs
Labels: Area-IDE, Community

#30415 Move to the new agent pool
  .vsts-dnceng.yml
Labels: Area-Infrastructure

#30280 Update IAsyncEnumerator API
  docs/features/async-streams.md
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/ForEachEnumeratorInfo.cs
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Compilation/ForEachStatementInfo.cs
  src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncIteratorInfo.cs
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncMethodToStateMachineRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncRewriter.AsyncIteratorRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncStateMachine.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNameKind.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNames.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncDisposableTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncForeachTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncMainTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs
  src/Compilers/CSharp/Test/Symbol/Compilation/ForEachStatementInfoTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Core/Portable/Symbols/WellKnownMemberNames.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
  src/Test/Utilities/Portable/Assert/AssertEx.cs
Labels: Area-Compilers, New Feature - Async Streams

#30364 Adding QuickInfo for null literal
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
  src/EditorFeatures/Test2/Workspaces/SymbolDescriptionServiceTests.vb
  src/EditorFeatures/VisualBasicTest/QuickInfo/SemanticQuickInfoSourceTests.vb
  src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs
Labels: Area-IDE, Community

#30399 Fix race condition in symbol start action execution
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs
Labels: Approved to merge, Area-Analyzers, Area-Compilers

#30353 Adding CS0267 to OrderModifiers FixableDiagnosticIds
  src/EditorFeatures/CSharpTest/OrderModifiers/OrderModifiersCompilerErrorTests.cs
  src/EditorFeatures/CSharpTest/OrderModifiers/OrderModifiersTests.cs
  src/Features/CSharp/Portable/OrderModifiers/CSharpOrderModifiersCodeFixProvider.cs
  src/Features/Core/Portable/OrderModifiers/AbstractOrderModifiersCodeFixProvider.cs
  src/Features/VisualBasic/Portable/OrderModifiers/VisualBasicOrderModifiersCodeFixProvider.vb
Labels: Area-IDE, Community

#30383 Null check baseDirectory before adding to keyFileSearchPaths
  src/Compilers/CSharp/Portable/CommandLine/CSharpCommandLineParser.cs
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/VisualBasic/Portable/CommandLine/VisualBasicCommandLineParser.vb
  src/Compilers/VisualBasic/Test/CommandLine/CommandLineTests.vb
  src/VisualStudio/VisualBasic/Impl/ProjectSystemShim/VisualBasicProjectOptionsHelper.vb
Labels: Area-Compilers

#29403 Added DotNet global tool for code formatting.
  Roslyn.sln
  THIRD-PARTY-NOTICES.txt
  build/Targets/Imports.targets
  build/Targets/Packages.props
  src/Compilers/Core/Portable/FileSystem/PathUtilities.cs
  src/Compilers/Core/Portable/InternalUtilities/FileNameUtilities.cs
  src/NuGet/VisualStudio/VS.ExternalAPIs.Roslyn.Package.csproj
  src/Setup/Roslyn.ThirdPartyNotices/ThirdPartyNotices.rtf
  src/Tools/dotnet-format/CodeFormatter.cs
  src/Tools/dotnet-format/Logging/SimpleConsoleLogger.cs
  src/Tools/dotnet-format/Logging/SimpleConsoleLoggerFactoryExtensions.cs
  src/Tools/dotnet-format/Logging/SimpleConsoleLoggerProvider.cs
  src/Tools/dotnet-format/MSBuild/MSBuildCoreLoader.cs
  src/Tools/dotnet-format/MSBuild/MSBuildEnvironment.cs
  src/Tools/dotnet-format/MSBuild/MSBuildWorkspaceFinder.cs
  src/Tools/dotnet-format/Options/EditorConfigOptionsApplier.cs
  src/Tools/dotnet-format/Program.cs
  src/Tools/dotnet-format/README.md
  src/Tools/dotnet-format/Resources.Designer.cs
  src/Tools/dotnet-format/Resources.resx
  src/Tools/dotnet-format/dotnet-format.csproj
  src/Tools/dotnet-format/xlf/Resources.cs.xlf
  src/Tools/dotnet-format/xlf/Resources.de.xlf
  src/Tools/dotnet-format/xlf/Resources.es.xlf
  src/Tools/dotnet-format/xlf/Resources.fr.xlf
  src/Tools/dotnet-format/xlf/Resources.it.xlf
  src/Tools/dotnet-format/xlf/Resources.ja.xlf
  src/Tools/dotnet-format/xlf/Resources.ko.xlf
  src/Tools/dotnet-format/xlf/Resources.pl.xlf
  src/Tools/dotnet-format/xlf/Resources.pt-BR.xlf
  src/Tools/dotnet-format/xlf/Resources.ru.xlf
  src/Tools/dotnet-format/xlf/Resources.tr.xlf
  src/Tools/dotnet-format/xlf/Resources.zh-Hans.xlf
  src/Tools/dotnet-format/xlf/Resources.zh-Hant.xlf
  src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj
  src/Workspaces/Core/MSBuild/Host/SimpleAnalyzerAssemblyLoaderService.cs
  src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj
Labels: Approved to merge, Area-IDE

#30435 Fix build definition
  .vsts-ci.yml
  build/scripts/publish-assets.ps1
Labels: Area-Infrastructure

#30404 fixing null ref exception at VisualStudioActiveStatementProvider
  src/VisualStudio/Core/Def/Implementation/EditAndContinue/VisualStudioActiveStatementProvider.cs
Labels: Approved to merge

#30387 First step to move from an attribute based NonNullTypes context to a syntax based context.
  src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/INonNullTypesContext.cs
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Generated/ErrorFacts.Generated.cs
  src/Compilers/CSharp/Portable/Symbols/Attributes/WellKnownAttributeData/EventWellKnownAttributeData.cs
  src/Compilers/CSharp/Portable/Symbols/Attributes/WellKnownAttributeData/FieldWellKnownAttributeData.cs
  src/Compilers/CSharp/Portable/Symbols/Attributes/WellKnownAttributeData/MethodWellKnownAttributeData.cs
  src/Compilers/CSharp/Portable/Symbols/Attributes/WellKnownAttributeData/ModuleWellKnownAttributeData.cs
  src/Compilers/CSharp/Portable/Symbols/Attributes/WellKnownAttributeData/PropertyWellKnownAttributeData.cs
  src/Compilers/CSharp/Portable/Symbols/Attributes/WellKnownAttributeData/TypeWellKnownAttributeData.cs
  src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs
  src/Compilers/CSharp/Portable/Symbols/MissingModuleSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/SignatureOnlyMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/FieldSymbolWithAttributesAndModifiers.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceModuleSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Symbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs
  src/Compilers/CSharp/Portable/Syntax/CSharpSyntaxTree.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_Embedded.cs
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_NonNullTypes.cs
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_Nullable.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/UninitializedNonNullableFieldTests.cs
  src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
  src/Compilers/Core/Portable/Syntax/AbstractWarningStateMap.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
  src/EditorFeatures/CSharpTest/Diagnostics/Nullable/CSharpDeclareAsNullableCodeFixTests.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#28382 Fix System.ArgumentOutOfRangeException in FindLeafNodeAndPartner
  src/EditorFeatures/CSharpTest/EditAndContinue/SyntaxUtilitiesTests.cs
  src/EditorFeatures/VisualBasicTest/EditAndContinue/SyntaxUtilitiesTests.vb
  src/Features/CSharp/Portable/EditAndContinue/SyntaxUtilities.cs
  src/Features/VisualBasic/Portable/EditAndContinue/SyntaxUtilities.vb
Labels: Bug, Interactive-Debugging, Interactive-EnC, Tenet-Reliability

#30395 Add public APIs to easily get ControlFlowGraph for local functions/an…
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IAnonymousFunctionExpression.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_ILocalFunctionStatement.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraph.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphExtensions.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Test/Utilities/Portable/Compilation/ControlFlowGraphVerifier.cs
Labels: Area-Analyzers, Area-Compilers, New Feature - Flow Analysis

#29828 Fixes for integration tests
  Roslyn.sln
  src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticStartAnalysisScope.cs
Labels: Approved to merge, Area-Analyzers, Area-Infrastructure, Contributor Pain, Urgency-Now

#30368 Fix symbol end action not completing for symbols with non-implicit me…
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs
  src/Compilers/Core/Portable/Symbols/ISymbolExtensions.cs
  src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb
  src/Compilers/VisualBasic/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.vb
Labels: Approved to merge, Area-Analyzers, Area-Compilers

#30454 Report AD0001 if an analyzer accidentally provides a null descriptor …
  src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs
  src/Compilers/Core/Portable/CodeAnalysisResources.Designer.cs
  src/Compilers/Core/Portable/CodeAnalysisResources.resx
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.cs.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.de.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.es.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.fr.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.it.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.ja.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.ko.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.pl.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.pt-BR.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.ru.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.tr.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.zh-Hans.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.zh-Hant.xlf
  src/Test/Utilities/Portable/Diagnostics/CommonDiagnosticAnalyzers.cs
Labels: Approved to merge, Area-Analyzers, Area-Compilers

#30465 Update to vs-threading analyzers 15.8.168
  build/Targets/Packages.props
Labels: Area-Infrastructure, Contributor Pain

#30451 adding output window logger
  src/EditorFeatures/Core/Shared/Extensions/IThreadingContextExtensions.cs
  src/VisualStudio/Core/Def/Implementation/Log/LoggerOptions.cs
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/Loggers/OutputWindowLogger.cs
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/OptionPages/PerformanceLoggersPage.cs
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/VisualStudioDiagnosticsWindowPackage.cs
  src/Workspaces/Core/Portable/Log/FunctionId.cs
  src/Workspaces/Core/Portable/Workspace/Workspace_Events.cs
Labels: Area-IDE

#30389 Merge master-vs-deps into master
  build/scripts/publish-assets.ps1
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_InternalsVisibleTo.vb
  src/Features/Core/Portable/Completion/CommonCompletionUtilities.cs
  src/Features/Core/Portable/Completion/Providers/AbstractInternalsVisibleToCompletionProvider.cs
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
Labels: Area-Infrastructure

#30455 Command handler to close block comment on /
  src/EditorFeatures/CSharp/BlockCommentEditing/BlockCommentEditingCommandHandler.cs
  src/EditorFeatures/CSharp/BlockCommentEditing/CloseBlockCommentCommandHandler.cs
  src/EditorFeatures/CSharpTest/BlockCommentEditing/BlockCommentEditingTests.cs
  src/EditorFeatures/CSharpTest/BlockCommentEditing/CloseBlockCommentTests.cs
  src/EditorFeatures/TestUtilities/AbstractTypingCommandHandlerTest.cs
  src/EditorFeatures/Text/Shared/Extensions/ITextSnapshotLineExtensions.cs
  src/EditorFeatures/Text/Shared/Extensions/SnapshotPointExtensions.cs
Labels: Area-IDE, Community

#30470 Fix for UseLocalFunction breaking semantics
  src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs
  src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs
  src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionDiagnosticAnalyzer.cs
Labels: Area-IDE, Community

#29800 Do not remove parentheses from incomplete expressions
  src/EditorFeatures/CSharpTest/RemoveUnnecessaryParentheses/RemoveUnnecessaryParenthesesTests.cs
  src/EditorFeatures/VisualBasicTest/RemoveUnnecessaryParentheses/RemoveUnnecessaryParenthesesTests.vb
  src/Workspaces/CSharp/Portable/Extensions/ParenthesizedExpressionSyntaxExtensions.cs
  src/Workspaces/VisualBasic/Portable/Extensions/ParenthesizedExpressionSyntaxExtensions.vb
Labels: Approved to merge, Area-IDE

#30350 Fix for UseAutoProperty when writing to the field in a nested function in the constructor
  src/EditorFeatures/CSharpTest/UseAutoProperty/UseAutoPropertyTests.cs
  src/EditorFeatures/VisualBasicTest/UseAutoProperty/UseAutoPropertyTests.vb
  src/Features/Core/Portable/CodeFixes/GenerateMember/AbstractGenerateMemberCodeFixProvider.cs
  src/Features/Core/Portable/UseAutoProperty/AbstractUseAutoPropertyCodeFixProvider.cs
  src/Features/VisualBasic/Portable/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb
  src/Workspaces/Core/Portable/LanguageServices/SyntaxFactsService/ISyntaxFactsServiceExtensions.cs
Labels: Area-IDE, Community

#30469 Nest 'introduce variable' code actions to help clean up the lightbulb.
  src/EditorFeatures/CSharpTest/CodeActions/IntroduceVariable/IntroduceVariableTests.cs
  src/EditorFeatures/CSharpTest/Interactive/CodeActions/InteractiveIntroduceVariableTests.cs
  src/EditorFeatures/Test2/Rename/InlineRenameTests.vb
  src/EditorFeatures/TestUtilities/CodeActions/AbstractCodeActionOrUserDiagnosticTest.cs
  src/EditorFeatures/TestUtilities/CodeActions/AbstractCodeActionTest.cs
  src/EditorFeatures/TestUtilities/Diagnostics/AbstractUserDiagnosticTest.cs
  src/EditorFeatures/VisualBasicTest/CodeActions/IntroduceVariable/IntroduceVariableTests.vb
  src/Features/Core/Portable/FeaturesResources.Designer.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.AbstractIntroduceVariableCodeAction.cs
  src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.cs
  src/Features/Core/Portable/IntroduceVariable/IIntroduceVariableService.cs
  src/Features/Core/Portable/IntroduceVariable/IntroduceVariableCodeRefactoringProvider.cs
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
Labels: Area-IDE, Community

#30476 Add links to workitems/test plans
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation

#30479 Add "Nullable" compilation option.
  src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs
  src/Compilers/CSharp/Portable/CSharpCompilationOptions.cs
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/CommandLine/CSharpCommandLineParser.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/PublicAPI.Shipped.txt
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Symbols/Source/SourceModuleSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
  src/Compilers/CSharp/Test/Symbol/Compilation/CSharpCompilationOptionsTests.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#29219 Fixed a bug with Intellisense on Enum
  src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests.vb
  src/Workspaces/VisualBasic/Portable/Extensions/StringExtensions.vb
Labels: Area-IDE, Community

#30456 Parse #nonnull directive
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Generated/Syntax.xml.Internal.Generated.cs
  src/Compilers/CSharp/Portable/Generated/Syntax.xml.Main.Generated.cs
  src/Compilers/CSharp/Portable/Generated/Syntax.xml.Syntax.Generated.cs
  src/Compilers/CSharp/Portable/Parser/DirectiveParser.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
  src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxKindFacts.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Syntax/Generated/Syntax.Test.xml.Generated.cs
  src/Compilers/CSharp/Test/Syntax/LexicalAndXml/PreprocessorTests.cs
Labels: Area-Compilers

#29805 Test loading of analyzer built against netstandard1.3
  build/Targets/Packages.props
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/Test/Resources/Core/TestKeys.cs
  src/Test/Utilities/Portable/Mocks/TestReferences.cs
Labels: Area-Analyzers, Area-Compilers

#30490 Fix exception thrown in MSBuildWorkspace when opening multi-targeted project that references an F# project
  src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.Worker.cs
  src/Workspaces/CoreTestUtilities/DotNetCoreSdk.cs
  src/Workspaces/CoreTestUtilities/DotNetHelper.cs
  src/Workspaces/CoreTestUtilities/Resources/NetCoreMultiTFM_ProjectReferenceToFSharp/Solution.sln
  src/Workspaces/CoreTestUtilities/Resources/NetCoreMultiTFM_ProjectReferenceToFSharp/csharplib/Class1.cs
  src/Workspaces/CoreTestUtilities/Resources/NetCoreMultiTFM_ProjectReferenceToFSharp/csharplib/csharplib.csproj
  src/Workspaces/CoreTestUtilities/Resources/NetCoreMultiTFM_ProjectReferenceToFSharp/fsharplib/Library.fs
  src/Workspaces/CoreTestUtilities/Resources/NetCoreMultiTFM_ProjectReferenceToFSharp/fsharplib/fsharplib.fsproj
  src/Workspaces/CoreTestUtilities/TestFiles/Resources.cs
  src/Workspaces/CoreTestUtilities/WorkspaceTestBase.cs
  src/Workspaces/MSBuildTest/NetCoreTests.cs
  src/Workspaces/MSBuildTest/VisualStudioMSBuildInstalled.cs
Labels: Approved to merge, Area-IDE

#30217 Add IOperation/CFG support for VB ReDim statement
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IConstructorBodyOperation.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_ILockStatement.cs
  src/Compilers/Core/Portable/Generated/Operations.xml.Generated.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/Operations/IReDimClauseOperation.cs
  src/Compilers/Core/Portable/Operations/IReDimOperation.cs
  src/Compilers/Core/Portable/Operations/OperationCloner.cs
  src/Compilers/Core/Portable/Operations/OperationKind.cs
  src/Compilers/Core/Portable/Operations/OperationVisitor.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/VisualBasic/Portable/BoundTree/Statement.vb
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_IParameterReferenceExpression.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_IReDimOperation.vb
  src/EditorFeatures/VisualBasicTest/MakeFieldReadonly/MakeFieldReadonlyTests.vb
  src/Test/Utilities/Portable/Compilation/ControlFlowGraphVerifier.cs
  src/Test/Utilities/Portable/Compilation/OperationTreeVerifier.cs
  src/Test/Utilities/Portable/Compilation/TestOperationVisitor.cs
  src/Workspaces/Core/Portable/Extensions/OperationExtensions.cs
Labels: Area-Compilers, New Feature - Flow Analysis, New Feature - IOperation

#30331 Add fallback to MSBuildProjectLoader when project reference is not backed by metadata reference
  src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.Worker_ResolveReferences.cs
  src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/CommandLineArgumentReader.cs
  src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/Extensions.cs
  src/Workspaces/Core/MSBuild/WorkspaceMSBuildResources.Designer.cs
  src/Workspaces/Core/MSBuild/WorkspaceMSBuildResources.resx
  src/Workspaces/Core/MSBuild/xlf/WorkspaceMSBuildResources.cs.xlf
  src/Workspaces/Core/MSBuild/xlf/WorkspaceMSBuildResources.de.xlf
  src/Workspaces/Core/MSBuild/xlf/WorkspaceMSBuildResources.es.xlf
  src/Workspaces/Core/MSBuild/xlf/WorkspaceMSBuildResources.fr.xlf
  src/Workspaces/Core/MSBuild/xlf/WorkspaceMSBuildResources.it.xlf
  src/Workspaces/Core/MSBuild/xlf/WorkspaceMSBuildResources.ja.xlf
  src/Workspaces/Core/MSBuild/xlf/WorkspaceMSBuildResources.ko.xlf
  src/Workspaces/Core/MSBuild/xlf/WorkspaceMSBuildResources.pl.xlf
  src/Workspaces/Core/MSBuild/xlf/WorkspaceMSBuildResources.pt-BR.xlf
  src/Workspaces/Core/MSBuild/xlf/WorkspaceMSBuildResources.ru.xlf
  src/Workspaces/Core/MSBuild/xlf/WorkspaceMSBuildResources.tr.xlf
  src/Workspaces/Core/MSBuild/xlf/WorkspaceMSBuildResources.zh-Hans.xlf
  src/Workspaces/Core/MSBuild/xlf/WorkspaceMSBuildResources.zh-Hant.xlf
  src/Workspaces/CoreTestUtilities/Resources/Issue29122/Proj1/ClassLibrary1.vbproj
  src/Workspaces/CoreTestUtilities/Resources/Issue29122/Proj2/ClassLibrary2.vbproj
  src/Workspaces/CoreTestUtilities/Resources/Issue29122/TestVB2.sln
  src/Workspaces/CoreTestUtilities/Resources/ProjectFiles/CSharp/ProjectLoadErrorOnMissingDebugType.csproj
  src/Workspaces/CoreTestUtilities/Resources/SolutionFiles/ProjectLoadErrorOnMissingDebugType.sln
  src/Workspaces/CoreTestUtilities/Roslyn.Services.UnitTests.Utilities.csproj
  src/Workspaces/CoreTestUtilities/TestFiles/Resources.cs
  src/Workspaces/CoreTestUtilities/WorkspaceTestBase.cs
  src/Workspaces/MSBuildTest/MSBuildWorkspaceTests.cs
Labels: Approved to merge, Area-IDE

#30473 Fix NullReferenceException for MakeFieldReadonlyCodeFixProvider in Visual Basic.NET
  src/EditorFeatures/VisualBasicTest/MakeFieldReadonly/MakeFieldReadonlyTests.vb
  src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs
Labels: Area-IDE, Community

#29104 Fix removes previous #region
  src/EditorFeatures/CSharpTest/UseAutoProperty/UseAutoPropertyTests.cs
  src/EditorFeatures/VisualBasicTest/UseAutoProperty/UseAutoPropertyTests.vb
  src/Features/Core/Portable/UseAutoProperty/AbstractUseAutoPropertyCodeFixProvider.cs
Labels: Area-IDE, Community

#30486 Show beta label in UpgradeProject code action
  src/EditorFeatures/CSharpTest/Diagnostics/UpgradeProject/UpgradeProjectTests.cs
  src/Features/CSharp/Portable/UpgradeProject/CSharpUpgradeProjectCodeFixProvider.cs
  src/Features/Core/Portable/UpgradeProject/AbstractUpgradeProjectCodeFixProvider.cs
Labels: Approved to merge, Area-IDE

#30340 Adding missing completion for `ref` and `in` after `this`
  src/EditorFeatures/CSharpTest2/Recommendations/InKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/OutKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/RefKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ThisKeywordRecommenderTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/InKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/OutKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/ParamsKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/RefKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/ThisKeywordRecommender.cs
  src/Workspaces/CSharp/Portable/Extensions/ContextQuery/CSharpSyntaxContext.cs
  src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs
  src/Workspaces/CSharp/Portable/Extensions/SyntaxTokenExtensions.cs
Labels: Area-IDE, Community

#30495 Fixed typo ‘should descent’
  src/Compilers/Core/Portable/Syntax/SyntaxWalker.cs
  src/Compilers/Core/Portable/Syntax/SyntaxWalkerDepth.cs
Labels: Area-Compilers, Community

#29727 Method type inference changes for nullability
  docs/features/nullable-reference-types.md
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/BestTypeInferrer.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.ObjectCreationPlaceholderLocal.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Generated/ErrorFacts.Generated.cs
  src/Compilers/CSharp/Portable/Symbols/ArrayTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/DynamicTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/TupleTypeDecoder.cs
  src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PointerTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
Labels: Approved to merge, Area-Compilers, New Language Feature - Nullable Reference Types

#30539 Remove unused diagnostic methods.
  src/Compilers/Core/Portable/DiagnosticAnalyzer/SuppressMessageAttributeState.cs
Labels: Area-Compilers

#30355 Fix code completion showing getter and setter for explicit Interface property implementation
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProviderTests.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs
Labels: Area-IDE, Community

#30537 Move Spanish job to Azure DevOps
  .vsts-dnceng.yml
  netci.groovy
Labels: Area-Infrastructure

#25925 Refactor ISyntaxFactsService.IsQueryKeyword
  src/Workspaces/CSharp/Portable/LanguageServices/CSharpSyntaxFactsService.cs
  src/Workspaces/CSharpTest/CSharpSyntaxFactsServiceTests.cs
  src/Workspaces/VisualBasic/Portable/LanguageServices/VisualBasicSyntaxFactsService.vb
  src/Workspaces/VisualBasicTest/VisualBasicSyntaxFactsServiceTests.vb
Labels: Area-IDE, Community

#30532 Infer return type of bool when generating methods in when clauses
  src/EditorFeatures/CSharpTest/Diagnostics/GenerateMethod/GenerateMethodTests.cs
  src/Workspaces/CSharp/Portable/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs
Labels: Area-IDE, Community

#30560 Ensure that MSBuildWorkspace is resilient against malformed paths
  src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.Worker.cs
  src/Workspaces/Core/MSBuild/MSBuild/PathResolver.cs
  src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/CommandLineArgumentReader.cs
  src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/ProjectFile.cs
  src/Workspaces/CoreTestUtilities/Resources/ProjectFiles/CSharp/MallformedAdditionalFilePath.csproj
  src/Workspaces/CoreTestUtilities/Resources/SourceFiles/Text/ValidAdditionalFile.txt
  src/Workspaces/CoreTestUtilities/TestFiles/Resources.cs
  src/Workspaces/MSBuildTest/MSBuildWorkspaceTests.cs
Labels: Approved to merge

#30525 Async-streams: Update syntax to 'await using' and 'await foreach'
  docs/features/async-streams.md
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/ControlFlowPass.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs
  src/Compilers/CSharp/Portable/Generated/Syntax.xml.Internal.Generated.cs
  src/Compilers/CSharp/Portable/Generated/Syntax.xml.Main.Generated.cs
  src/Compilers/CSharp/Portable/Generated/Syntax.xml.Syntax.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_UsingStatement.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Syntax/ForEachStatementSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/ForEachVariableStatementSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
  src/Compilers/CSharp/Portable/Syntax/UsingStatementSyntax.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAwaitForeachTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAwaitUsingTests.cs
  src/Compilers/CSharp/Test/Semantic/FlowAnalysis/TryLockUsingStatementTests.cs
  src/Compilers/CSharp/Test/Syntax/Generated/Syntax.Test.xml.Generated.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/AsyncStreamsParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/AwaitParsingTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/MakeMethodAsynchronous/MakeMethodAsynchronousTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/MakeMethodSynchronous/MakeMethodSynchronousTests.cs
  src/EditorFeatures/CSharpTest/KeywordHighlighting/AwaitHighlighterTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/AwaitKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ForEachKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/NewKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ReturnKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/UsingKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/VarKeywordRecommenderTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/AwaitKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/ForEachKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/UsingKeywordRecommender.cs
  src/Workspaces/CSharp/Portable/Extensions/ContextQuery/CSharpSyntaxContext.cs
  src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs
Labels: Approved to merge, Area-Compilers, Area-IDE

#30574 Add NullableReferenceTypes msbuild property
  src/Compilers/Core/MSBuildTask/Csc.cs
  src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets
  src/Compilers/Core/MSBuildTaskTests/CscTests.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#30550 add workaround on extract method on https://github.com/dotnet/roslyn/…
  src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs
  src/Features/Core/Portable/ExtractMethod/ExtractMethodMatrix.cs
Labels: Area-Compilers

#30570 Change directive to: #nullable (enable|disable)
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Generated/Syntax.xml.Internal.Generated.cs
  src/Compilers/CSharp/Portable/Generated/Syntax.xml.Main.Generated.cs
  src/Compilers/CSharp/Portable/Generated/Syntax.xml.Syntax.Generated.cs
  src/Compilers/CSharp/Portable/Parser/DirectiveParser.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Symbols/Symbol.cs
  src/Compilers/CSharp/Portable/Syntax/CSharpSyntaxTree.cs
  src/Compilers/CSharp/Portable/Syntax/NullableDirectiveMap.cs
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
  src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxKindFacts.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_NonNullTypes.cs
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_Nullable.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/ForEachTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/UninitializedNonNullableFieldTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/GenericConstraintTests.cs
  src/Compilers/CSharp/Test/Syntax/Generated/Syntax.Test.xml.Generated.cs
  src/Compilers/CSharp/Test/Syntax/LexicalAndXml/PreprocessorTests.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#30242 Include static, readonly, and volatile in tool tips for fields
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
  src/EditorFeatures/Test2/Workspaces/SymbolDescriptionServiceTests.vb
  src/Features/CSharp/Portable/LanguageServices/CSharpSymbolDisplayService.SymbolDescriptionBuilder.cs
  src/Features/Core/Portable/LanguageServices/SymbolDisplayService/AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.cs
  src/Features/VisualBasic/Portable/LanguageServices/VisualBasicSymbolDisplayService.SymbolDescriptionBuilder.vb
Labels: Area-IDE, Community

#30554 Do not crash ExtractMethod when we run into a dataflowanalysis result we didn't account for.
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodBase.cs
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs
  src/EditorFeatures/Core/EditorFeaturesResources.Designer.cs
  src/EditorFeatures/Core/EditorFeaturesResources.resx
  src/EditorFeatures/Core/Implementation/ExtractMethod/AbstractExtractMethodCommandHandler.cs
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.cs.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.de.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.es.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.fr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.it.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ja.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ko.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pl.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pt-BR.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ru.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.tr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hans.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hant.xlf
  src/EditorFeatures/VisualBasicTest/ExtractMethod/ExtractMethodTests.vb
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.cs
  src/Features/Core/Portable/ExtractMethod/ExtractMethodMatrix.cs
  src/Features/Core/Portable/ExtractMethod/ExtractMethodOptions.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Features/Core/Portable/FeaturesResources.Designer.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Workspaces/Core/Portable/Log/FunctionId.cs
Labels: Area-IDE, Community

#30585 Change feature name to 'nullable reference types'
  src/Compilers/CSharp/Portable/Binder/Binder_AnonymousTypes.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/CommandLine/CSharpCommandLineParser.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs
  src/Compilers/CSharp/Portable/Errors/LazyMissingNonNullTypesContextDiagnosticInfo.cs
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs
  src/Compilers/CSharp/Portable/Parser/DirectiveParser.cs
  src/Compilers/CSharp/Portable/Parser/DocumentationCommentParser.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/ForEachTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableTests.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#30564 Set null state on dereference
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
  src/Features/CSharp/Portable/ConvertForEachToFor/CSharpConvertForEachToForCodeRefactoringProvider.cs
Labels: Approved to merge

#30593 Fix for perf issues in CompilationWithAnalyzers found from perf traces
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs
Labels: Approved to merge, Area-Analyzers, Area-Compilers

#29802 Do not convert mutable value type fields to properties
  src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs
  src/EditorFeatures/CSharpTest/UseAutoProperty/UseAutoPropertyTests.cs
  src/EditorFeatures/VisualBasicTest/UseAutoProperty/UseAutoPropertyTests.vb
  src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs
  src/Features/Core/Portable/UseAutoProperty/AbstractUseAutoPropertyAnalyzer.cs
  src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs
Labels: Approved to merge, Area-IDE

#30618 Inject range indexers
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
Labels: Area-Compilers

#30481 Handle extension `ref this` usage via collection initializer
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/DestructorTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefExtensionMethodsTests.cs
Labels: Area-Compilers

#30621 some code clean up on new VisualStudioProject and FileChangeWatcher
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/FileChangeWatcher.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProject.cs
Labels: Approved to merge, Area-IDE

#30039 one click code cleanup
  build/Targets/Packages.props
  src/EditorFeatures/CSharpTest/Formatting/CodeCleanupTests.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs
  src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs
  src/EditorFeatures/Core/Implementation/Formatting/FormatCommandHandler.FormatDocument.cs
  src/EditorFeatures/Test/CodeFixes/CodeFixServiceTests.cs
  src/Features/CSharp/Portable/CodeCleanup/CSharpCodeCleanupService.cs
  src/Features/Core/Portable/CodeCleanup/DiagnosticSet.cs
  src/Features/Core/Portable/CodeCleanup/EnabledDiagnosticOptions.cs
  src/Features/Core/Portable/CodeCleanup/ICodeCleanupService.cs
  src/Features/Core/Portable/CodeCleanup/OrganizeUsingsSettings.cs
  src/Features/Core/Portable/CodeFixes/ICodeFixService.cs
  src/VisualStudio/CSharp/Impl/LanguageService/CSharpCodeCleanupFixer.cs
  src/VisualStudio/Core/Def/Implementation/CodeCleanup/CodeCleanUpFixer.cs
  src/VisualStudio/Core/Def/Implementation/CodeCleanup/CodeCleanupFixerProvider.cs
  src/VisualStudio/Core/Def/RoslynPackage.cs
Labels: Approved to merge, Area-IDE

#30571 MSBuildWorkspace needs to set a property to ensure that project references are built with the correct configuration
  src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs
  src/Workspaces/Core/MSBuild/MSBuild/Constants/PropertyNames.cs
  src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.Worker.cs
  src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.Worker_ResolveReferences.cs
  src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.cs
  src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs
  src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/IProjectFileLoader.cs
  src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/ProjectFileLoader.cs
  src/Workspaces/CoreTestUtilities/Resources/Issue30174/InspectedLibrary/InspectedClass.cs
  src/Workspaces/CoreTestUtilities/Resources/Issue30174/InspectedLibrary/InspectedLibrary.csproj
  src/Workspaces/CoreTestUtilities/Resources/Issue30174/ReferencedLibrary/ReferencedLibrary.csproj
  src/Workspaces/CoreTestUtilities/Resources/Issue30174/ReferencedLibrary/SomeMetadataAttribute.cs
  src/Workspaces/CoreTestUtilities/Resources/Issue30174/Solution.sln
  src/Workspaces/CoreTestUtilities/TestFiles/Resources.cs
  src/Workspaces/CoreTestUtilities/WorkspaceTestBase.cs
  src/Workspaces/MSBuildTest/MSBuildWorkspaceTests.cs
  src/Workspaces/MSBuildTest/NetCoreTests.cs
Labels: Area-IDE

#30638 Fixes issue #30529 "object initializers and csharp_new_line_before_open_brace in editorconfig"
  src/Workspaces/CSharp/Portable/Formatting/CSharpFormattingOptions.Parsers.cs
  src/Workspaces/CSharp/Portable/Formatting/CSharpFormattingOptions.cs
  src/Workspaces/CSharpTest/Formatting/EditorConfigOptionParserTests.cs
Labels: Area-IDE, Community

#30596 Delete "dead" comment.
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
Labels: Area-Compilers, Bug

#30519 Adding code fix for CS0822 (Implicitly-typed variables cannot be constant)
  src/EditorFeatures/CSharpTest/CodeRefactorings/UseExplicitOrImplicitType/UseExplicitTypeRefactoringTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/UseImplicitOrExplicitType/UseExplicitTypeTests.cs
  src/EditorFeatures/CSharpTest/UseExplicitTypeForConst/UseExplicitTypeForConstTests.cs
  src/Features/CSharp/Portable/UseExplicitTypeForConst/UseExplicitTypeForConstCodeFixProvider.cs
  src/Features/Core/Portable/CodeFixes/PredefinedCodeFixProviderNames.cs
  src/Test/Utilities/Portable/Traits/Traits.cs
  src/Workspaces/CSharp/Portable/Utilities/CSharpUseExplicitTypeHelper.cs
Labels: Area-IDE, Community, Feature Request

#30639 Add support for ??= compound operator to the UseCompound fix
  src/EditorFeatures/CSharpTest/UseCompoundAssignment/UseCompoundAssignmentTests.cs
  src/Features/CSharp/Portable/UseCompoundAssignment/CSharpUseCompoundAssignmentDiagnosticAnalyzer.cs
  src/Features/CSharp/Portable/UseCompoundAssignment/Utilities.cs
  src/Features/Core/Portable/UseCompoundAssignment/AbstractUseCompoundAssignmentDiagnosticAnalyzer.cs
  src/Features/VisualBasic/Portable/UseCompoundAssignment/VisualBasicUseCompoundAssignmentDiagnosticAnalyzer.vb
Labels: Area-IDE, Community, Feature Request

#30616 Address a number of issues around generic type substitution and nullability.
  src/Compilers/CSharp/Portable/Binder/Semantics/INonNullTypesContext.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/Emitter/Model/SymbolAdapter.cs
  src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/SynthesizedClosureMethod.cs
  src/Compilers/CSharp/Portable/Lowering/MethodToClassRewriter.cs
  src/Compilers/CSharp/Portable/Symbols/AbstractTypeMap.cs
  src/Compilers/CSharp/Portable/Symbols/AbstractTypeParameterMap.cs
  src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs
  src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs
  src/Compilers/CSharp/Portable/Symbols/ErrorTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/EventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/FieldSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/MemberSignatureComparer.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/MemberRefMetadataDecoder.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/SymbolFactory.cs
  src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/ReducedExtensionMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/SubstitutedMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/SubstitutedNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedContainer.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedImplementationMethod.cs
  src/Compilers/CSharp/Portable/Symbols/Tuples/TupleMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeMap.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
  src/Compilers/Test/Utilities/CSharp/CompilationTestUtils.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EEMethodSymbol.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EENamedTypeSymbol.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#30667 Fix Linux log publish
  .vsts-dnceng.yml
Labels: Area-Infrastructure

#30524 Fix foreach spilling ref field to a local:
  src/Compilers/CSharp/Portable/BoundTree/Constructors.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/ForEachTests.cs
Labels: Area-Compilers

#30002 Reduce set of files copied on official builds
  .vsts-ci.yml
  0
  build/scripts/build-utils.ps1
  build/scripts/vsts-robocopy.ps1
  docs/contributing/Powershell Guidelines.md
Labels: Area-Infrastructure

#30671 Rearranged query to avoid unnecessary allocations
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs
Labels: Area-Analyzers, Community

#30679 set content type for AbstractDebuggerIntelliSenseContext to the original content type
  src/VisualStudio/Core/Def/Implementation/DebuggerIntelliSense/AbstractDebuggerIntelliSenseContext.cs
  src/VisualStudio/Core/Def/Implementation/DebuggerIntelliSense/DebuggerIntellisenseFilter.cs
  src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractLanguageService`2.IVsImmediateStatementCompletion2.cs
Labels: Area-IDE

#30605 Removed CodeCleanup experiment settings and experience.
  src/EditorFeatures/Core/Implementation/Formatting/FormatCommandHandler.FormatDocument.cs
  src/EditorFeatures/Core/Implementation/Formatting/FormatCommandHandler.cs
  src/Features/Core/Portable/CodeCleanup/CodeCleanupABTestOptions.cs
  src/VisualStudio/CSharp/Impl/Options/Formatting/FormattingOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/Formatting/FormattingOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/VSPackage.resx
  src/VisualStudio/CSharp/Impl/xlf/VSPackage.cs.xlf
  src/VisualStudio/CSharp/Impl/xlf/VSPackage.de.xlf
  src/VisualStudio/CSharp/Impl/xlf/VSPackage.es.xlf
  src/VisualStudio/CSharp/Impl/xlf/VSPackage.fr.xlf
  src/VisualStudio/CSharp/Impl/xlf/VSPackage.it.xlf
  src/VisualStudio/CSharp/Impl/xlf/VSPackage.ja.xlf
  src/VisualStudio/CSharp/Impl/xlf/VSPackage.ko.xlf
  src/VisualStudio/CSharp/Impl/xlf/VSPackage.pl.xlf
  src/VisualStudio/CSharp/Impl/xlf/VSPackage.pt-BR.xlf
  src/VisualStudio/CSharp/Impl/xlf/VSPackage.ru.xlf
  src/VisualStudio/CSharp/Impl/xlf/VSPackage.tr.xlf
  src/VisualStudio/CSharp/Impl/xlf/VSPackage.zh-Hans.xlf
  src/VisualStudio/CSharp/Impl/xlf/VSPackage.zh-Hant.xlf
Labels: Approved to merge, Area-IDE

#30680 Remove -implementation package dependencies
  build/Targets/Packages.props
Labels: Approved to merge, Area-Infrastructure

#29306 Remove AbstractPackage.ForegroundObject, and its costly initialization
  src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractPackage.cs
  src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractPackage`2.cs
Labels: Area-IDE

#30675 Fix crash when applying code fixes that modify additional files
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
Labels: Approved to merge, Area-IDE

#30748 Add a SetProperty API for CPS to passing msbuild properties
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/CPS/IWorkspaceProjectContext.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs
Labels: Approved to merge

#30635 Add features to offer using index and range operators.
  src/EditorFeatures/CSharpTest/UseIndexOrRangeOperator/UseIndexOperatorTests.cs
  src/EditorFeatures/CSharpTest/UseIndexOrRangeOperator/UseRangeOperatorTests.cs
  src/Features/CSharp/Portable/UseIndexOrRangeOperator/CSharpUseIndexOperatorCodeFixProvider.cs
  src/Features/CSharp/Portable/UseIndexOrRangeOperator/CSharpUseIndexOperatorDiagnosticAnalyzer.InfoCache.cs
  src/Features/CSharp/Portable/UseIndexOrRangeOperator/CSharpUseIndexOperatorDiagnosticAnalyzer.cs
  src/Features/CSharp/Portable/UseIndexOrRangeOperator/CSharpUseRangeOperatorCodeFixProvider.cs
  src/Features/CSharp/Portable/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.InfoCache.cs
  src/Features/CSharp/Portable/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.Result.cs
  src/Features/CSharp/Portable/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs
  src/Features/CSharp/Portable/UseIndexOrRangeOperator/Helpers.cs
  src/Features/CSharp/Portable/UseIndexOrRangeOperator/MemberInfo.cs
  src/Features/Core/Portable/Diagnostics/Analyzers/IDEDiagnosticIds.cs
  src/Features/Core/Portable/FeaturesResources.Designer.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Test/Utilities/Portable/Traits/Traits.cs
  src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs
  src/VisualStudio/Core/Def/ServicesVSResources.Designer.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/Core/Test/Options/CSharpEditorConfigGeneratorTests.vb
  src/Workspaces/CSharp/Portable/CodeStyle/CSharpCodeStyleOptions.cs
Labels: Area-IDE, Community, Feature Request

#30758 Enable incremental updates of the dependency graph
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectDependencyGraph.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
  src/Workspaces/CoreTest/SolutionTests/ProjectDependencyGraphTests.cs
Labels: Approved to merge, Area-IDE

#30576 Display documentation from associated property/event when showing QuickInfo for get/set and add/remove
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
  src/EditorFeatures/VisualBasicTest/QuickInfo/SemanticQuickInfoSourceTests.vb
  src/Features/Core/Portable/Shared/Extensions/ISymbolExtensions_2.cs
Labels: Area-IDE, Community

#30615 Include GetAwaiter() extension method namespace in AddImport suggestions
  src/EditorFeatures/CSharpTest/AddUsing/AddUsingTests.cs
  src/Features/CSharp/Portable/AddImport/CSharpAddImportFeatureService.cs
  src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs
  src/Features/Core/Portable/AddImport/SymbolReferenceFinder.cs
  src/Features/VisualBasic/Portable/AddImport/VisualBasicAddImportFeatureService.vb
  src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs
Labels: Area-IDE, Community

#30493 Add useful debug information to OptionKey
  src/Workspaces/Core/Portable/Options/OptionKey.cs
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
  src/Workspaces/CoreTest/Options/OptionKeyTests.cs
Labels: Area-IDE, Community

#30578 Correct grammatical errors in contributing.md
  CONTRIBUTING.md
Labels: Area-Infrastructure, Community

#30761 Merge 'features/NullableReferenceTypes' into 'dev16.0.x'
  src/Compilers/CSharp/Portable/Binder/Semantics/INonNullTypesContext.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/Emitter/Model/SymbolAdapter.cs
  src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/SynthesizedClosureMethod.cs
  src/Compilers/CSharp/Portable/Lowering/MethodToClassRewriter.cs
  src/Compilers/CSharp/Portable/Symbols/AbstractTypeMap.cs
  src/Compilers/CSharp/Portable/Symbols/AbstractTypeParameterMap.cs
  src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs
  src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs
  src/Compilers/CSharp/Portable/Symbols/ErrorTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/EventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/FieldSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/MemberSignatureComparer.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/MemberRefMetadataDecoder.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/SymbolFactory.cs
  src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/ReducedExtensionMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/SubstitutedMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/SubstitutedNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedContainer.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedImplementationMethod.cs
  src/Compilers/CSharp/Portable/Symbols/Tuples/TupleMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeMap.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
  src/Compilers/Test/Utilities/CSharp/CompilationTestUtils.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EEMethodSymbol.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EENamedTypeSymbol.cs
Labels: Approved to merge, Area-Compilers, New Language Feature - Nullable Reference Types

#30757 Do not inject attribute types into .Net modules.
  src/Compilers/CSharp/Portable/Symbols/Source/SourceNamespaceSymbol.cs
  src/Compilers/CSharp/Test/Semantic/FlowAnalysis/StructTests.cs
Labels: Approved to merge, Area-Compilers, New Language Feature - Nullable Reference Types

#30771 Revert "Add a SetProperty API for CPS to passing msbuild properties"
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/CPS/IWorkspaceProjectContext.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs
Labels: Approved to merge, Auto-Merge If Tests Pass

#30790 Fix publishing nuget info of dev16.0.x-vs-deps branch
  build/config/PublishData.json
Labels: Area-Infrastructure

#30686 EnsureNonNullTypesAttributeExists not called for NoPIA
  src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
Labels: Approved to merge, Area-Compilers, New Language Feature - Nullable Reference Types

#30768 Correct 15.9 publish data
  build/config/PublishData.json
Labels: Area-Infrastructure

#30770 Compare Nullable modifiers while comparing type symbols by default.
  src/Compilers/CSharp/Portable/Binder/Binder_Constraints.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/BestTypeInferrer.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
  src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/CSharpSymbolMatcher.cs
  src/Compilers/CSharp/Portable/Emitter/Model/SymbolAdapter.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncMethodToStateMachineRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/ExpressionLambdaRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_NullCoalescingOperator.cs
  src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/MethodToStateMachineRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Symbols/ArrayTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs
  src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs
  src/Compilers/CSharp/Portable/Symbols/ConversionSignatureComparer.cs
  src/Compilers/CSharp/Portable/Symbols/DynamicTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/MemberSignatureComparer.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/MetadataDecoder.cs
  src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PointerTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/CustomModifierUtils.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedIntrinsicOperatorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs
  src/Compilers/CSharp/Portable/Symbols/TypeUnification.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/TypeTests.cs
  src/Compilers/Core/Portable/Symbols/TypeCompareKind.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Rewriters/CapturedVariableRewriter.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/ExpressionCompilerTests.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#30595 Remove properties set in BeforeCommonTargets.targets
  build/Targets/BeforeCommonTargets.targets
  build/Targets/Imports.targets
Labels: Area-Infrastructure

#30658 Remove stale comment.
  src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs
  src/Features/Core/Portable/ExtractMethod/ExtractMethodMatrix.cs
Labels: Area-IDE, Community

#30796 fix for PerfWatsonHang: microsoft.visualstudio.languageservices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.EditAndContinue.VsENCRebuildableProjectImpl.GetProjectAnalysisSummary
  src/VisualStudio/Core/Def/Implementation/EditAndContinue/VisualStudioActiveStatementProvider.cs
Labels: Approved to merge, Area-Performance, Bug, Tenet-Reliability

#30587 Ensure that the compilers produce double.NaN values in IEEE canonical form.
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs
  src/Compilers/Core/Portable/ConstantValueSpecialized.cs
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTests.vb
Labels: Area-Compilers, Bug, Concept-Determinism

#30498 Use Arcade bootstrapping scripts
  .gitignore
  build/Targets/Imports.targets
  build/Targets/Packages.props
  build/Targets/RepoToolset/BuildReleasePackages.targets
  build/Targets/RepoToolset/BuildTasks.props
  build/Targets/RepoToolset/RepoLayout.props
  build/Targets/RepoToolset/Version.targets
  build/Targets/Settings.props
  build/ToolsetPackages/RoslynToolset.csproj
  build/scripts/build-utils.ps1
  build/scripts/build.ps1
  build/scripts/build.sh
  build/scripts/check-for-loc-changes.ps1
  build/scripts/edit-designers.ps1
  build/scripts/generate-compiler-code.ps1
  build/scripts/obtain_dotnet.sh
  build/scripts/publish-assets.ps1
  build/scripts/test-build-correctness.ps1
  build/scripts/test-determinism.ps1
  build/scripts/tools.ps1
  build/scripts/tools.sh
  global.json
  src/NuGet/VisualStudio/VS.Tools.Roslyn.Package.csproj
  src/Setup/Installer/Installer.Package.csproj
Labels: Area-Infrastructure

#30805 Invert the binding order of InitializerExpressions and CreationExpressions
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs
Labels: Area-Compilers

#30803 Propagate values from AbstractProject to VisualStudioProjectCreationInfo
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker.cs
Labels: Area-IDE

#30774 User-defined operator checks should ignore differences in tuple member names
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbolBase.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs
Labels: Area-Compilers

#30821 Remove TokenStream._tokenToIndexMap and replace with binary search
  src/Workspaces/Core/Portable/Formatting/Engine/TokenData.cs
  src/Workspaces/Core/Portable/Formatting/Engine/TokenStream.cs
Labels: Approved to merge, Area-IDE, Tenet-Performance

#30820 Use ImmutableInterlocked instead of lock on a highly contended path
  src/Workspaces/Core/Portable/Options/OptionServiceFactory.cs
  src/Workspaces/Core/Portable/Options/WorkspaceOptionSet.cs
Labels: Approved to merge, Area-IDE, Tenet-Performance

#30844 Restore `CreateSignatureHelpItems` overload that an extension was relying on
  src/Features/Core/Portable/SignatureHelp/AbstractSignatureHelpProvider.cs
Labels: Approved to merge, Area-IDE

#30806 Fix bug in 'yield return await'
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AwaitExpressionSpiller.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs
Labels: Area-Compilers, Pending director approval

#30816 Add documentation for the compiler server
  docs/compilers/Compiler Server.md
Labels: Area-Compilers

#30857 Fix compiler benchmarks
  build/Targets/Packages.props
  src/Tools/CompilerBenchmarks/CompilerBenchmarks.csproj
  src/Tools/CompilerBenchmarks/FixedCsProjGenerator.cs
  src/Tools/CompilerBenchmarks/Program.cs
Labels: Area-Compilers
