Repository dotnet/roslyn, pull requests merged in 2018-11, with the labels that each got.

#22871 Add code fix to add 'Shadows' modifier
  src/EditorFeatures/VisualBasicTest/Diagnostics/OverloadBase/OverloadBaseTests.vb
  src/Features/VisualBasic/Portable/CodeFixes/OverloadBase/OverloadBaseCodeFixProvider.AddKeywordAction.vb
  src/Features/VisualBasic/Portable/CodeFixes/OverloadBase/OverloadBaseCodeFixProvider.vb
  src/Features/VisualBasic/Portable/VBFeaturesResources.Designer.vb
  src/Features/VisualBasic/Portable/VBFeaturesResources.resx
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.cs.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.de.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.es.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.fr.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.it.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.ja.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.ko.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.pl.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.pt-BR.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.ru.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.tr.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.zh-Hans.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.zh-Hant.xlf
  src/Test/Utilities/Portable/Traits/Traits.cs
Labels: Area-Compilers, Community, cla-already-signed

#30810 Don't attempt to set up pipe security on Mono as it is not implemented
  src/Compilers/Server/VBCSCompiler/NamedPipeClientConnection.cs
Labels: Area-Compilers

#30074 Command handler to replace `@$"` with `$@"` when typing interpolated verbatim string
  src/EditorFeatures/CSharp/CSharpEditorResources.Designer.cs
  src/EditorFeatures/CSharp/CSharpEditorResources.resx
  src/EditorFeatures/CSharp/FixInterpolatedVerbatimString/FixInterpolatedVerbatimStringCommandHandler.cs
  src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.cs.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.de.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.es.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.fr.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.it.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.ja.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.ko.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.pl.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.pt-BR.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.ru.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.tr.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.zh-Hans.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.zh-Hant.xlf
  src/EditorFeatures/CSharpTest/FixInterpolatedVerbatimString/FixInterpolatedVerbatimStringCommandHandlerTests.cs
  src/EditorFeatures/CSharpTest/SplitStringLiteral/SplitStringLiteralCommandHandlerTests.cs
  src/Test/Utilities/Portable/Traits/Traits.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpAutomaticBraceCompletion.cs
Labels: Area-IDE, Community, Feature Request

#30489 Remove "Make readonly" suggestion from fixed size buffers
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitAddress.cs
  src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs
  src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs
  src/Compilers/CSharp/Portable/Emitter/Model/FieldSymbolAdapter.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/EmptyStructTypeCache.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Field.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PointerElementAccess.cs
  src/Compilers/CSharp/Portable/Symbols/FieldSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEFieldSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/FieldSymbolWithAttributesAndModifiers.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceEnumConstantSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceFixedFieldSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberFieldSymbol.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/FixedSizeBufferTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/FieldTests.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Core/Portable/Symbols/IFieldSymbol.cs
  src/Compilers/VisualBasic/Portable/Symbols/FieldSymbol.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/FieldTests.vb
  src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs
  src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs
  src/Features/Core/Portable/MetadataAsSource/AbstractMetadataAsSourceService.WrappedFieldSymbol.cs
  src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationFieldSymbol.cs
Labels: Area-IDE, Community

#30040 Continuation comments cleanup
  src/Compilers/VisualBasic/Portable/Parser/ParserFeature.vb
  src/Compilers/VisualBasic/Test/Syntax/Parser/ParseDirectives.vb
  src/Compilers/VisualBasic/Test/Syntax/Parser/ParseStatements.vb
  src/Compilers/VisualBasic/Test/Syntax/Scanner/ScannerTests.vb
  src/EditorFeatures/VisualBasicTest/CodeActions/AbstractVisualBasicCodeActionTest.vb
  src/EditorFeatures/VisualBasicTest/CodeActions/InlineTemporary/InlineTemporaryTests.vb
  src/Workspaces/CoreTest/CodeCleanup/RemoveUnnecessaryLineContinuationTests.cs
Labels: Area-Compilers, Community, Language-VB

#30922 Merge 'features/NullableReferenceTypes' into master
  src/Compilers/CSharp/Portable/Binder/Binder_Constraints.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/BestTypeInferrer.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
  src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/CSharpSymbolMatcher.cs
  src/Compilers/CSharp/Portable/Emitter/Model/SymbolAdapter.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncMethodToStateMachineRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/ExpressionLambdaRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_NullCoalescingOperator.cs
  src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/MethodToStateMachineRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Symbols/ArrayTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs
  src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs
  src/Compilers/CSharp/Portable/Symbols/ConversionSignatureComparer.cs
  src/Compilers/CSharp/Portable/Symbols/DynamicTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/MemberSignatureComparer.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/MetadataDecoder.cs
  src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PointerTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/CustomModifierUtils.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedIntrinsicOperatorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs
  src/Compilers/CSharp/Portable/Symbols/TypeUnification.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/TypeTests.cs
  src/Compilers/Core/Portable/Symbols/TypeCompareKind.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Rewriters/CapturedVariableRewriter.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/ExpressionCompilerTests.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#30106 Introduce using statement
  src/EditorFeatures/CSharpTest/IntroduceUsingStatement/IntroduceUsingStatementTests.cs
  src/EditorFeatures/TestUtilities/CodeActions/AbstractCodeActionOrUserDiagnosticTest.cs
  src/EditorFeatures/VisualBasicTest/IntroduceUsingStatement/IntroduceUsingStatementTests.vb
  src/Features/CSharp/Portable/CSharpFeaturesResources.Designer.cs
  src/Features/CSharp/Portable/CSharpFeaturesResources.resx
  src/Features/CSharp/Portable/IntroduceUsingStatement/CSharpIntroduceUsingStatementCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.cs.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.de.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.es.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.fr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.it.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ja.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ko.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pl.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pt-BR.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ru.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.tr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hans.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hant.xlf
  src/Features/Core/Portable/CodeRefactoringHelpers.cs
  src/Features/Core/Portable/CodeRefactorings/PredefinedCodeRefactoringProviderNames.cs
  src/Features/Core/Portable/IntroduceUsingStatement/AbstractIntroduceUsingStatementCodeRefactoringProvider.cs
  src/Features/VisualBasic/Portable/IntroduceUsingStatement/VisualBasicIntroduceUsingStatementCodeRefactoringProvider.vb
  src/Features/VisualBasic/Portable/VBFeaturesResources.Designer.vb
  src/Features/VisualBasic/Portable/VBFeaturesResources.resx
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.cs.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.de.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.es.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.fr.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.it.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.ja.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.ko.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.pl.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.pt-BR.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.ru.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.tr.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.zh-Hans.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.zh-Hant.xlf
  src/Test/Utilities/Portable/Traits/Traits.cs
  src/Workspaces/Core/Portable/Utilities/IReadOnlyListExtensions.cs
Labels: Area-IDE, Community, Feature Request

#30923 Add missing binding redirects to csc.exe.config
  build/Targets/GenerateCompilerExecutableBindingRedirects.targets
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
Labels: Approved to merge

#30818 Add -shared and -keepalive compiler options
  src/Compilers/Core/Portable/CommandLine/CommonCommandLineParser.cs
  src/Compilers/Server/VBCSCompilerTests/CompilerServerTests.cs
  src/Compilers/Server/VBCSCompilerTests/DesktopBuildClientTests.cs
Labels: Area-Compilers

#29149 Improved User Experience with "Navigate to decompiled sources"
  src/EditorFeatures/CSharp/DecompiledSource/AssemblyResolver.cs
  src/EditorFeatures/CSharp/DecompiledSource/CSharpDecompiledSourceService.cs
  src/EditorFeatures/CSharp/DecompiledSource/CSharpDecompiledSourceServiceFactory.cs
  src/EditorFeatures/CSharp/Microsoft.CodeAnalysis.CSharp.EditorFeatures.csproj
  src/EditorFeatures/Core/IDecompiledSourceService.cs
  src/EditorFeatures/Core/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/Features/CSharp/Portable/DocumentationComments/DocCommentConverter.cs
  src/Features/CSharp/Portable/MetadataAsSource/CSharpMetadataAsSourceService.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs
Labels: Area-IDE, Community

#30936 Do not warn for double nullable supression
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types, Test

#30930 Avoid naming collisions in IPC channels
  src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstance.cs
Labels: Area-Infrastructure

#30871 Disallow ref structs in expression trees
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/ArglistTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs
Labels: Area-Compilers

#30670 Specify type inference rules for nullability annotations
  docs/features/nullable-reference-types.md
Labels: Area-Compilers, Documentation, New Language Feature - Nullable Reference Types

#30847 Discard pattern versus symbol named `_`
  docs/compilers/CSharp/Compiler Breaking Changes - Milestone 16.md
  docs/compilers/CSharp/Compiler Breaking Changes - VS2019.md
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs
  src/Compilers/CSharp/Portable/Binder/SwitchBinder_Patterns.cs
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Generated/ErrorFacts.Generated.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenDeconstructTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests2.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs
Labels: Area-Compilers, Feature Request, New Language Feature - Pattern Matching

#30870 Fixing when keyword recommender in recursive patterns branch #2
  src/EditorFeatures/CSharpTest2/Recommendations/WhenKeywordRecommenderTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/WhenKeywordRecommender.cs
Labels: Area-IDE, Community

#30969 Add regression test for attribute with async delegate parameter
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests.cs
  src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests.vb
Labels: Area-Compilers

#30961 Ensure PinnedRemotableDataScope is disposed
  src/Workspaces/Core/Portable/Remote/RemoteHostSessionHelpers.cs
Labels: Approved to merge, Area-IDE

#30991 Fix the lifetime of IntegrationService
  src/VisualStudio/IntegrationTest/IntegrationService/IntegrationService.cs
Labels: Area-IDE, Integration-Test

#30959 Fix paste tracking
  src/EditorFeatures/Core/Implementation/PasteTracking/PasteTrackingPasteCommandHandlercs.cs
  src/EditorFeatures/Test2/PasteTracking/PasteTrackingServiceTests.vb
  src/EditorFeatures/Test2/PasteTracking/PasteTrackingTestState.vb
Labels: Approved to merge, Area-IDE

#30982 Handle event symbols with explicit interface implementation in unused…
  src/EditorFeatures/CSharpTest/RemoveUnusedMembers/RemoveUnusedMembersTests.cs
  src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs
Labels: Approved to merge, Area-IDE

#30916 Allow VisualStudioExperimentationService to initialize on a background thread
  src/VisualStudio/Core/Def/Experimentation/VisualStudioExperimentationService.cs
Labels: Approved to merge, Area-IDE

#30997 Fix IndexOutOfRange exception in InvocationExpressionSignatureHelpProvider
  src/EditorFeatures/CSharpTest/SignatureHelp/InvocationExpressionSignatureHelpProviderTests.cs
  src/Features/CSharp/Portable/SignatureHelp/InvocationExpressionSignatureHelpProvider.cs
  src/Features/CSharp/Portable/SignatureHelp/InvocationExpressionSignatureHelpProvider_MethodGroup.cs
Labels: Approved to merge, Area-IDE

#30980 Workaround in RemoveUnusedMembersDiagnosticAnalyzer for VB handles cl…
  src/EditorFeatures/VisualBasicTest/RemoveUnusedMembers/RemoveUnusedMembersTests.vb
  src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs
  src/Features/VisualBasic/Portable/RemoveUnusedMembers/VisualBasicRemoveUnusedMembersDiagnosticAnalyzer.vb
Labels: Approved to merge, Area-Analyzers, Area-IDE

#31024 Add csharp_prefer_braces to .editorconfig
  .editorconfig
Labels: Approved to merge, Area-IDE

#30804 Use IVsAsyncFileChangeEx throughout Roslyn
  build/Targets/Packages.props
  src/Compilers/Extension/Roslyn.Compilers.Extension.csproj
  src/ExpressionEvaluator/Package/ExpressionEvaluatorPackage.csproj
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/FileChangeTracker.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/FileChangeWatcher.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/FileChangeWatcherProvider.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioRuleSetTests.vb
  src/VisualStudio/RemoteHostClientMock/Roslyn.VisualStudio.RemoteHostClientMock.csproj
  src/VisualStudio/Setup.Dependencies/Roslyn.VisualStudio.Setup.Dependencies.csproj
  src/VisualStudio/TestUtilities2/Microsoft.VisualStudio.LanguageServices.Test.Utilities2.vbproj
  src/VisualStudio/TestUtilities2/MockComponentModel.vb
  src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/MockVsFileChangeEx.vb
  src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb
  src/VisualStudio/Xaml/Impl/Microsoft.VisualStudio.LanguageServices.Xaml.csproj
Labels: Approved to merge, Area-IDE, Auto-Merge If Tests Pass

#30510 Adding new training data and updating training scenarios
  .vsts-ci.yml
  build/Targets/Packages.props
  build/config/optprof.json
  build/scripts/build.ps1
  build/scripts/createrunsettings.ps1
Labels: Approved to merge, Area-Infrastructure

#31036 Add bunch of exclusions to dead code analysis for special methods
  src/EditorFeatures/CSharpTest/RemoveUnusedMembers/RemoveUnusedMembersTests.cs
  src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs
  src/Workspaces/Core/Portable/Shared/Extensions/ICompilationExtensions.cs
  src/Workspaces/Core/Portable/Shared/Extensions/IMethodSymbolExtensions.cs
Labels: Approved to merge

#31033 Add parsing tests to compiler benchmarks
  src/Tools/CompilerBenchmarks/EmitBenchmark.cs
  src/Tools/CompilerBenchmarks/Program.cs
  src/Tools/CompilerBenchmarks/StageBenchmarks.cs
Labels: Area-Compilers

#30864 Simplify construction and updates to DiagnosticAnalysisResult
  src/Features/Core/Portable/Diagnostics/DiagnosticResultSerializer.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.Executor.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.InProcOrRemoteHostAnalyzerRunner.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.ProjectState.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_BuildSynchronization.cs
  src/Workspaces/Core/Portable/Diagnostics/DiagnosticAnalysisResult.cs
  src/Workspaces/Core/Portable/Diagnostics/DiagnosticAnalysisResultBuilder.cs
Labels: Area-IDE

#30865 renamed Column to Character …
  src/EditorFeatures/Core/Shared/Extensions/SnapshotPointExtensions.cs
  src/EditorFeatures/Core/Shared/Extensions/SnapshotSpanExtensions.cs
  src/EditorFeatures/Test/Extensions/ITextSnapshotExtensionsTests.cs
  src/EditorFeatures/Text/Shared/Extensions/ITextSnapshotExtensions.cs
  src/EditorFeatures/VisualBasic/LineCommit/CommitBufferManager.vb
  src/EditorFeatures/VisualBasicTest/EndConstructGeneration/EndConstructTestingHelpers.vb
  src/VisualStudio/Core/Def/Implementation/Extensions/SnapshotSpanExtensions.cs
  src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/Editor_InProc.cs
Labels: Area-IDE

#30866 Code style changes
  src/EditorFeatures/CSharpTest/Diagnostics/DiagnosticAnalyzerDriver/DiagnosticAnalyzerDriverTests.cs
  src/EditorFeatures/Core.Wpf/Diagnostics/UnnecessaryCodeFormatDefinition.cs
  src/EditorFeatures/Test/Diagnostics/DiagnosticsSquiggleTaggerProviderTests.cs
  src/EditorFeatures/Test/Extensions/SourceTextContainerExtensionsTests.cs
  src/EditorFeatures/Test/Workspaces/TextFactoryTests.cs
  src/EditorFeatures/Test2/IntelliSense/IntellisenseQuickInfoBuilderTests.vb
  src/Features/Core/Portable/CodeLens/ReferenceLocationDescriptor.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/FileChangeWatcher.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/Core/Def/Implementation/Venus/ContainedDocument.cs
  src/VisualStudio/Core/Def/Implementation/Venus/ContainedLanguage.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentState.cs
Labels: Area-IDE

#30868 Update ITextBufferCloneService
  src/EditorFeatures/Core.Wpf/InlineRename/InlineRenameSession.OpenTextBufferManager.cs
  src/EditorFeatures/Core/ContentTypeNames.cs
  src/EditorFeatures/Test/Extensions/SourceTextContainerExtensionsTests.cs
  src/EditorFeatures/Test/Workspaces/TextFactoryTests.cs
  src/EditorFeatures/Text/ContentTypeNames.cs
  src/EditorFeatures/Text/Extensions.SnapshotSourceText.cs
  src/EditorFeatures/Text/Implementation/TextBufferFactoryService/ITextBufferCloneService.cs
  src/EditorFeatures/Text/Implementation/TextBufferFactoryService/TextBufferCloneServiceFactory.cs
  src/EditorFeatures/Text/Microsoft.CodeAnalysis.EditorFeatures.Text.csproj
Labels: Area-IDE

#30869 Support document-specific services with IDocumentService
  src/EditorFeatures/TestUtilities/Workspaces/TestHostDocument.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace_XmlConsumption.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProject.cs
  src/Workspaces/Core/Portable/Workspace/Host/DocumentService/IDocumentService.cs
  src/Workspaces/Core/Portable/Workspace/Host/DocumentService/IDocumentServiceProvider.cs
  src/Workspaces/Core/Portable/Workspace/Solution/DefaultTextDocumentServiceProvider.cs
  src/Workspaces/Core/Portable/Workspace/Solution/DocumentInfo.cs
  src/Workspaces/Core/Portable/Workspace/Solution/DocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/TextDocument.cs
  src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
Labels: Area-IDE

#31048 Fix Edit and Continue in CPS projects
  src/VisualStudio/CSharp/Test/ProjectSystemShim/CPS/EditAndContinueTests.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IVsENCRebuildableProjectCfg.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs
Labels: Approved to merge, Area-Interactive

#31013 Remove unused method SerializableBytes.CreateReadableStream
  src/Workspaces/Core/Portable/Utilities/SerializableBytes.cs
  src/Workspaces/CoreTest/UtilityTest/SerializableBytesTests.cs
Labels: Area-IDE, Concept-Continuous Improvement

#31049 Make sure we convert project references back on project removal
  src/VisualStudio/CSharp/Test/ProjectSystemShim/CPS/CSharpReferencesTests.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
Labels: Approved to merge, Area-IDE

#30363 Async-streams: minimal test for IOperation and CFG. Improve diagnostics
  docs/features/async-streams.md
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/Binder/UsingStatementBinder.cs
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAwaitForeachTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAwaitUsingTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IAwaitExpression.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IForEachLoopStatement.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IUsingStatement.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
Labels: Approved to merge, Area-Compilers, New Feature - Async Streams, New Feature - IOperation

#30990 Make nullability inference associative and commutative
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
Labels: Approved to merge, Area-Compilers, New Language Feature - Nullable Reference Types

#31000 Update BoundCall method based on receiver nullability
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
Labels: Approved to merge, Area-Compilers, New Language Feature - Nullable Reference Types

#30527 Implement new interfaces for adding files
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/Interop/IProjectSiteEx.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/Legacy/AbstractLegacyProject.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/Legacy/AbstractLegacyProject_IProjectSiteEx.cs
Labels: Approved to merge, Area-IDE

#31052 Fix up our build badges
  README.md
  build/scripts/generate-badges.ps1
Labels: Area-Infrastructure

#30913 Remove NonNullTypes context and other unnecessary information stored in TypeSymbolWithAnnotations.
  src/Compilers/CSharp/Portable/Binder/Binder_AnonymousTypes.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Constraints.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/BestTypeInferrer.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundExpressionExtensions.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/Emitter/Model/TypeParameterSymbolAdapter.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.VariableIdentifier.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Types.cs
  src/Compilers/CSharp/Portable/Symbols/AbstractTypeMap.cs
  src/Compilers/CSharp/Portable/Symbols/AbstractTypeParameterMap.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.ToStringMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs
  src/Compilers/CSharp/Portable/Symbols/ErrorTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/NullableTypeDecoder.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEEventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEFieldSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEPropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PETypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/TupleTypeDecoder.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ThisParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/SubstitutedTypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
  src/Compilers/Core/Portable/Symbols/TypeCompareKind.cs
Labels: Approved to merge, Area-Compilers, New Language Feature - Nullable Reference Types

#30880 Add Compilers filter for Roslyn
  Compilers.slnf
Labels: Area-Compilers

#30944 Fix gold-bar when an analyzer starts up, but not all references are restored/found
  src/EditorFeatures/CSharpTest/UseIndexOrRangeOperator/UseIndexOperatorTests.cs
  src/EditorFeatures/CSharpTest/UseIndexOrRangeOperator/UseRangeOperatorTests.cs
  src/Features/CSharp/Portable/ExtractMethod/Extensions.cs
  src/Features/CSharp/Portable/UseIndexOrRangeOperator/CSharpUseIndexOperatorDiagnosticAnalyzer.InfoCache.cs
  src/Features/CSharp/Portable/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.InfoCache.cs
  src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs
  src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs
Labels: Approved to merge, Area-IDE, Community

#30733 Added a way to inject dynamic file to workspace for component like ra…
  src/EditorFeatures/Core.Wpf/QuickInfo/ContentControlService.cs
  src/EditorFeatures/Core.Wpf/QuickInfo/Extensions.cs
  src/EditorFeatures/Core.Wpf/QuickInfo/IContentControlService.cs
  src/EditorFeatures/Core.Wpf/QuickInfo/ProjectionBufferContent.cs
  src/EditorFeatures/Core/Implementation/Classification/EditorClassifier.cs
  src/EditorFeatures/Core/Shared/Extensions/SnapshotSpanExtensions.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs
  src/Features/Core/Portable/CodeLens/CodeLensReferencesService.cs
  src/Features/Core/Portable/CodeLens/ReferenceLocationDescriptor.cs
  src/VisualStudio/Core/Def/Implementation/CodeLens/RemoteCodeLensReferencesService.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Contexts/AbstractTableDataSourceFindUsagesContext.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Contexts/WithReferencesFindUsagesContext.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Contexts/WithoutReferencesFindUsagesContext.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/AbstractDocumentSpanEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/DefinitionItemEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/DocumentSpanEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/StreamingFindUsagesPresenter.cs
  src/VisualStudio/Core/Def/Implementation/Venus/ContainedDocument.DocumentServiceProvider.cs
  src/VisualStudio/Core/Def/Implementation/Venus/ContainedDocument.cs
  src/VisualStudio/Core/Def/Implementation/Venus/ContainedLanguage.cs
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/VisualStudio/Core/Test/Venus/DocumentServiceTests.vb
  src/VisualStudio/Core/Test/Venus/DocumentService_IntegrationTests.vb
  src/Workspaces/Core/Portable/Diagnostics/DiagnosticAnalysisResult.cs
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
  src/Workspaces/Core/Portable/Workspace/Host/DocumentService/IDocumentExcerptService.cs
  src/Workspaces/Core/Portable/Workspace/Host/DocumentService/ISpanMappingService.cs
Labels: Area-IDE

#31085 put internal API partner team is using (FSharp) back
  src/Features/Core/Portable/Completion/CommonCompletionItem.cs
Labels: Area-IDE

#30988 Add IVTs to 16.0 version of RemoteLS
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/EditorFeatures/Text/Microsoft.CodeAnalysis.EditorFeatures.Text.csproj
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/VisualStudio/Core/Impl/Microsoft.VisualStudio.LanguageServices.Implementation.csproj
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
Labels: Approved to merge, Area-IDE

#31050 Parse array type in conditional operator
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/NullableParsingTests.cs
Labels: Approved to merge, Area-Compilers, New Language Feature - Nullable Reference Types

#31072 Nullable analysis of yield return
  src/Compilers/CSharp/Portable/Binder/InMethodBinder.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
  src/Test/Utilities/Portable/Traits/CompilerFeature.cs
Labels: Approved to merge, Area-Compilers, New Language Feature - Nullable Reference Types

#31082 Track nullable state in try statements
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
Labels: Approved to merge, Area-Compilers, Bug, New Language Feature - Nullable Reference Types

#31125 Block conversion of references to F# projects from C# projects
  src/VisualStudio/CSharp/Test/ProjectSystemShim/CPS/CSharpReferencesTests.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
Labels: Approved to merge, Area-IDE

#31138 Avoid redundant warnings from explicit cast
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#31147 Fix resource strings missing from #30914
  src/EditorFeatures/Core/EditorFeaturesResources.resx
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.cs.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.de.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.es.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.fr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.it.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ja.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ko.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pl.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pt-BR.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ru.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.tr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hans.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hant.xlf
Labels: Approved to merge, Area-IDE

#31153 Delete a bunch of unused versions from FixedPackages.props
  build/Targets/FixedPackages.props
Labels: Area-Infrastructure

#31155 Use RepoRoot instead of repoDir
  build/scripts/createrunsettings.ps1
Labels: Area-Infrastructure

#31170 Smart indent when users type '{' even if 'format on typing' is off.
  src/EditorFeatures/CSharp/Formatting/CSharpEditorFormattingService.cs
  src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs
  src/EditorFeatures/Core/Implementation/Formatting/FormatCommandHandler.cs
Labels: Area-IDE, Community

#31092 Add a new SuppressMessageAttribute target scope to suppress diagnosti…
  src/Compilers/Core/Portable/DiagnosticAnalyzer/SuppressMessageAttributeState.cs
  src/Test/Utilities/Portable/Diagnostics/SuppressMessageAttributeTests.cs
Labels: Approved to merge, Area-Analyzers, Area-Compilers

#31181 add output paths as one of causes to reanalyze solution cralwer.
  src/EditorFeatures/Test/SolutionCrawler/WorkCoordinatorTests.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.cs
Labels: Approved to merge, Area-IDE

#31162 Add System.Memory reference
  build/Targets/Packages.props
  src/Compilers/Core/CodeAnalysisTest/AnalyzerFileReferenceTests.cs
  src/Compilers/Core/CodeAnalysisTest/StringTableTests.cs
  src/Compilers/Core/Portable/InternalUtilities/Hash.cs
  src/Compilers/Core/Portable/InternalUtilities/StringTable.cs
  src/Compilers/Core/Portable/InternalUtilities/TextKeyedCache.cs
  src/Compilers/Core/Portable/MetadataReader/PEModule.cs
  src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj
  src/Setup/DevDivInsertionFiles/DevDivInsertionFiles.csproj
  src/Test/Utilities/Portable/Platform/Desktop/TestHelpers.cs
  src/Test/Utilities/Portable/Roslyn.Test.Utilities.csproj
Labels: Area-Compilers

#31169 Do not mark a switch expression as erroneous just because it wasn't exhaustive.
  src/Compilers/CSharp/Portable/Binder/SwitchExpressionBinder.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs
Labels: Area-Compilers, New Language Feature - Pattern Matching, Test

#31025 Add CFG based dataflow analysis framework to the Workspaces layer
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Test/Utilities/Portable/Compilation/ControlFlowGraphVerifier.cs
  src/Test/Utilities/Portable/Compilation/FlowAnalysis/BasicBlockReachabilityDataFlowAnalyzer.cs
  src/Test/Utilities/Portable/Roslyn.Test.Utilities.csproj
  src/Workspaces/Core/Portable/Extensions/BasicBlockExtensions.cs
  src/Workspaces/Core/Portable/Extensions/ControlFlowGraphExtensions.cs
  src/Workspaces/Core/Portable/Extensions/ControlFlowRegionExtensions.cs
  src/Workspaces/Core/Portable/Extensions/OperationExtensions.cs
  src/Workspaces/Core/Portable/FlowAnalysis/CustomDataFlowAnalysis.cs
  src/Workspaces/Core/Portable/FlowAnalysis/DataFlowAnalyzer.cs
  src/Workspaces/Core/Portable/FlowAnalysis/LValueFlowCaptureProvider.cs
  src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.AnalysisData.cs
  src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.BasicBlockAnalysisData.cs
  src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.DataFlowAnalyzer.FlowGraphAnalysisData.cs
  src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.DataFlowAnalyzer.cs
  src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.OperationTreeAnalysisData.cs
  src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.Walker.cs
  src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.cs
  src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageResult.cs
Labels: Area-IDE

#31164 Add one more shim and IVT access for Live Share
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/EditorFeatures/Text/Microsoft.CodeAnalysis.EditorFeatures.Text.csproj
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/InvisibleEditor.cs
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/VisualStudio/Core/Impl/Microsoft.VisualStudio.LanguageServices.Implementation.csproj
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
Labels: Approved to merge, Area-IDE

#31188 Extract nullable state operations to extension methods.
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#31223 Revert "Cleanup IVTs for 15.7 and 15.8 since they won't be loaded in 16.0
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/EditorFeatures/Text/Microsoft.CodeAnalysis.EditorFeatures.Text.csproj
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/VisualStudio/Core/Impl/Microsoft.VisualStudio.LanguageServices.Implementation.csproj
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
Labels: Area-IDE

#31214 change build errors to show up at the end rather than at the top.
  src/VisualStudio/Core/Def/Implementation/TableDataSource/VisualStudioBaseDiagnosticListTable.LiveTableDataSource.cs
Labels: Approved to merge, Area-IDE

#31105 Allow multiple calls to GetAsyncEnumerator
  docs/features/async-streams.md
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncRewriter.AsyncIteratorRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncStateMachine.cs
  src/Compilers/CSharp/Portable/Lowering/IteratorRewriter/IteratorConstructor.cs
  src/Compilers/CSharp/Portable/Lowering/IteratorRewriter/IteratorRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/StateMachineRewriter.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs
Labels: Area-Compilers, New Feature - Async Streams

#31168 Don't warn on conversion of error type. Analyze arguments of invocations with errors
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#31236 enable non fatal watson in extract method
  src/Features/Core/Portable/ExtractMethod/ExtractMethodMatrix.cs
Labels: Approved to merge, Area-IDE

#30968 Implement constraints on pointer types as input to pattern-matching.
  src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs
Labels: 4 - In Review, Area-Compilers, New Language Feature - Pattern Matching

#31182 Update metadata references in response to file changes
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/MetadataReferences/VisualStudioMetadataReference.Snapshot.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/MetadataReferences/VisualStudioMetadataReference.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/MetadataReferences/VisualStudioMetadataReferenceManager.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProject.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
Labels: Approved to merge, Area-IDE, Auto-Merge If Tests Pass

#31241 Verify formatting of #nullable
  src/Workspaces/CSharpTest/Formatting/FormattingTriviaTests.cs
Labels: Area-IDE, Test

#30927 Implement NameTupleElement refactoring
  src/EditorFeatures/CSharpTest/NameTupleElement/NameTupleElementTests.cs
  src/EditorFeatures/VisualBasicTest/NameTupleElement/NameTupleElementTests.vb
  src/Features/CSharp/Portable/NameTupleElement/CSharpNameTupleElementCodeRefactoringProvider.cs
  src/Features/Core/Portable/FeaturesResources.Designer.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/NameTupleElement/AbstractNameTupleElementCodeRefactoringProvider.cs
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Features/VisualBasic/Portable/NameTupleElement/VisualBasicNameTupleElementCodeRefactoringProvider.vb
  src/Test/Utilities/Portable/Traits/Traits.cs
Labels: Approved to merge, Area-IDE, Community

#31203 update training branch
  .vsts-ci.yml
  build/scripts/createrunsettings.ps1
Labels: Area-Infrastructure

#31219 verify that optprof scripts are not broken
  build/scripts/createrunsettings.ps1
  build/scripts/test-build-correctness.ps1
Labels: Area-Infrastructure

#31143 Don't have 'Keyword' map to 'ReservedKeyword' and 'ContextualKeyword' it just ends up confusing people with terminology.
  src/EditorFeatures/Core.Wpf/InlineRename/AbstractEditorInlineRenameService.cs
  src/VisualStudio/Core/Impl/CodeModel/FileCodeModel.cs
  src/Workspaces/CSharp/Portable/LanguageServices/CSharpSyntaxFactsService.cs
  src/Workspaces/Core/Portable/LanguageServices/SyntaxFactsService/ISyntaxFactsService.cs
  src/Workspaces/Core/Portable/LanguageServices/SyntaxFactsService/ISyntaxFactsServiceExtensions.cs
  src/Workspaces/Core/Portable/Rename/RenameLocation.ReferenceProcessing.cs
  src/Workspaces/VisualBasic/Portable/CaseCorrection/VisualBasicCaseCorrectionService.Rewriter.vb
  src/Workspaces/VisualBasic/Portable/LanguageServices/VisualBasicSyntaxFactsService.vb
Labels: Approved to merge, Area-IDE, Community

#30647 Fix goto-def and glyph for builtin operators.
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.OperatorSymbols.vb
  src/EditorFeatures/VisualBasicTest/QuickInfo/SemanticQuickInfoSourceTests.vb
  src/Features/Core/Portable/Shared/Extensions/ISymbolExtensions_2.cs
  src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs
  src/Workspaces/Core/Portable/Shared/Utilities/SymbolEquivalenceComparer.EquivalenceVisitor.cs
Labels: Approved to merge, Area-IDE, Community, Feature Request

#31265 Fix up the implementation of IDocumentTrackingService
  src/EditorFeatures/Core.Wpf/NavigateTo/NavigateToItemProvider.Searcher.cs
  src/EditorFeatures/TestUtilities/NavigateTo/AbstractNavigateToTests.cs
  src/Features/Core/Portable/SolutionCrawler/IDocumentTrackingService.cs
  src/Features/Core/Portable/SolutionCrawler/IDocumentTrackingServiceExtensions.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.HighPriorityProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.IncrementalAnalyzerProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs
  src/VisualStudio/Core/Def/Implementation/CallHierarchy/Finders/AbstractCallFinder.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/DocumentProvider.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioActiveDocumentTracker.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentTrackingService.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentTrackingServiceFactory.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioProjectCacheHostServiceFactory.cs
  src/VisualStudio/Core/Def/RoslynPackage.cs
  src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb
Labels: Approved to merge, Area-IDE

#31321 Typos
  src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs
  src/Compilers/Core/MSBuildTask/ManagedToolTask.cs
  src/EditorFeatures/CSharpTest/Diagnostics/GenerateMethod/GenerateDeconstructMethodTests.cs
  src/Features/Core/Portable/ConvertLinq/AbstractConvertLinqQueryToForEachProvider.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/MetadataReferences/VisualStudioFrameworkAssemblyPathResolverFactory.cs
  src/VisualStudio/Core/Def/SymbolSearch/VisualStudioSymbolSearchService.cs
  src/VisualStudio/Core/Def/Telemetry/ProjectTelemetryIncrementalAnalyzerProvider.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicEditAndContinue.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/RegularExpressions/RegexNodes.cs
  src/Workspaces/Core/Portable/Remote/IRemoteHostClientService.cs
Labels: Approved to merge, Area-IDE, Community

#30766 Delete unused packages
  build/Targets/Packages.props
  src/Tools/GenerateSdkPackages/Microsoft.VisualStudio.Debugger.Engine.nuspec
  src/Tools/GenerateSdkPackages/Microsoft.VisualStudio.Debugger.Metadata.nuspec
  src/Tools/GenerateSdkPackages/Microsoft.VisualStudio.Debugger.UI.Interfaces.nuspec
  src/Tools/GenerateSdkPackages/files.txt
  src/Tools/GenerateSdkPackages/make-all.ps1
  src/VisualStudio/CSharp/Impl/Microsoft.VisualStudio.LanguageServices.CSharp.csproj
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/VisualStudio/Core/Impl/Microsoft.VisualStudio.LanguageServices.Implementation.csproj
  src/VisualStudio/Core/SolutionExplorerShim/Microsoft.VisualStudio.LanguageServices.SolutionExplorer.csproj
  src/VisualStudio/Core/Test.Next/Roslyn.VisualStudio.Next.UnitTests.csproj
  src/VisualStudio/Core/Test/Microsoft.VisualStudio.LanguageServices.UnitTests.vbproj
  src/VisualStudio/RemoteHostClientMock/Roslyn.VisualStudio.RemoteHostClientMock.csproj
  src/VisualStudio/TestUtilities2/Microsoft.VisualStudio.LanguageServices.Test.Utilities2.vbproj
  src/VisualStudio/VisualBasic/Impl/Microsoft.VisualStudio.LanguageServices.VisualBasic.vbproj
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/Roslyn.VisualStudio.DiagnosticsWindow.csproj
  src/VisualStudio/Xaml/Impl/Microsoft.VisualStudio.LanguageServices.Xaml.csproj
Labels: Area-Infrastructure

#31154 Create TempPE compiler for new project system
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/CPS/ITempPECompiler.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/TempPECompiler.cs
Labels: Approved to merge, Area-IDE

#31291 fixed a race where solution cralwer used wrong solution for it to pro…
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs
  src/VisualStudio/Core/Def/Implementation/Remote/RemoteSolutionPopulatorProvider.cs
Labels: Approved to merge, Area-IDE

#31254 Add an API to pass additional msbuild properties to workspace
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/CPS/AdditionalPropertyNames.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/CPS/IWorkspaceProjectContext.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs
Labels: Approved to merge, Area-IDE

#31385 Fix IBC data application
  build/Targets/RepoToolset/OptimizationData.targets
  build/Targets/Settings.props
  build/config/optprof.json
  src/Compilers/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.csproj
  src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj
  src/Compilers/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.vbproj
  src/EditorFeatures/CSharp/Microsoft.CodeAnalysis.CSharp.EditorFeatures.csproj
  src/EditorFeatures/Core.Wpf/Microsoft.CodeAnalysis.EditorFeatures.Wpf.csproj
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/EditorFeatures/Text/Microsoft.CodeAnalysis.EditorFeatures.Text.csproj
  src/EditorFeatures/VisualBasic/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.vbproj
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Microsoft.CodeAnalysis.CSharp.ExpressionCompiler.csproj
  src/ExpressionEvaluator/CSharp/Source/ResultProvider/NetFX20/CSharpResultProvider.NetFX20.csproj
  src/ExpressionEvaluator/CSharp/Source/ResultProvider/Portable/Microsoft.CodeAnalysis.CSharp.ResultProvider.csproj
  src/ExpressionEvaluator/Core/Source/ExpressionCompiler/Microsoft.CodeAnalysis.ExpressionCompiler.csproj
  src/ExpressionEvaluator/Core/Source/ResultProvider/NetFX20/ResultProvider.NetFX20.csproj
  src/ExpressionEvaluator/Core/Source/ResultProvider/Portable/Microsoft.CodeAnalysis.ResultProvider.csproj
  src/Features/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.Features.csproj
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/Features/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.Features.vbproj
  src/Interactive/EditorFeatures/CSharp/Microsoft.CodeAnalysis.CSharp.InteractiveEditorFeatures.csproj
  src/Interactive/EditorFeatures/Core/Microsoft.CodeAnalysis.InteractiveEditorFeatures.csproj
  src/Interactive/Features/Microsoft.CodeAnalysis.InteractiveFeatures.csproj
  src/NuGet/Microsoft.Net.Compilers/CompilerArtifacts.targets
  src/Setup/DevDivInsertionFiles/DevDivInsertionFiles.csproj
  src/Setup/DevDivVsix/CompilersPackage/Microsoft.CodeAnalysis.Compilers.Setup.csproj
  src/VisualStudio/CSharp/Impl/Microsoft.VisualStudio.LanguageServices.CSharp.csproj
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/VisualStudio/Core/Impl/Microsoft.VisualStudio.LanguageServices.Implementation.csproj
  src/VisualStudio/Core/SolutionExplorerShim/Microsoft.VisualStudio.LanguageServices.SolutionExplorer.csproj
  src/VisualStudio/VisualBasic/Impl/Microsoft.VisualStudio.LanguageServices.VisualBasic.vbproj
  src/Workspaces/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.Workspaces.csproj
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
  src/Workspaces/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.Workspaces.vbproj
Labels: Area-Infrastructure

#31382 Disallow null coalescing assignment in expression trees.
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenNullCoalescingAssignmentTests.cs
Labels: Area-Compilers

#31372 Move VS MSBuild location to Arcade tools script
  .gitignore
  build/Targets/Tools.props
  build/scripts/build-utils.ps1
  build/scripts/build.ps1
  build/scripts/locate-vs.ps1
  build/scripts/test-machine-setup.ps1
  build/scripts/tools.ps1
  global.json
Labels: Area-Infrastructure

#31392 Copy nullability of non-nullable members
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#31402 Add test to show that pointers are disallowed.
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenNullCoalescingAssignmentTests.cs
Labels: Area-Compilers, Test

#31404 Remove the Code Style dependency on Hash.cs
  src/CodeStyle/Core/Analyzers/Microsoft.CodeAnalysis.CodeStyle.csproj
  src/Compilers/Core/Portable/InternalUtilities/Hash.cs
  src/Workspaces/Core/Portable/CodeStyle/CodeStyleOption.cs
  src/Workspaces/Core/Portable/Options/OptionKey.cs
Labels: Approved to merge, Area-IDE

#31046 Fixing inferred type for yield return in async iterator methods
  src/EditorFeatures/CSharpTest/Diagnostics/GenerateMethod/GenerateMethodTests.cs
  src/EditorFeatures/CSharpTest/GenerateVariable/GenerateVariableTests.cs
  src/EditorFeatures/CSharpTest/TypeInferrer/TypeInferrerTests.cs
  src/Workspaces/CSharp/Portable/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs
Labels: Approved to merge, Area-IDE, Community, New Feature - Async Streams

#31114 Async-iterator method can return `IAsyncEnumerator<T>`
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/InMethodBinder.cs
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncRewriter.AsyncIteratorRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncStateMachine.cs
  src/Compilers/CSharp/Portable/Symbols/MethodSymbolExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
Labels: Area-Compilers, New Feature - Async Streams

#31264 More special handling for unconstrained type parameters in flow analysis
  src/Compilers/CSharp/Portable/Binder/Binder_AnonymousTypes.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
  src/Compilers/CSharp/Portable/Errors/LazyNullAsNonNullableDiagnosticInfo.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.ObjectCreationPlaceholderLocal.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/UnassignedFieldsWalker.cs
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Types.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.ToStringMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ThisParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Symbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
  src/Compilers/Test/Utilities/CSharp/UsesIsNullableVisitor.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#31422 Rename members of the NullableAnnotation enum
  src/Compilers/CSharp/Portable/Binder/Binder_AnonymousTypes.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Constraints.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/BestTypeInferrer.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundExpressionExtensions.cs
  src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.ObjectCreationPlaceholderLocal.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Types.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.ToStringMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/ExtraAnnotations.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PETypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ThisParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#31375 Track "unmanaged generic structs" feature status
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation

#31407 Delete unused linkedhashqueue.cs
  src/Workspaces/Core/Portable/Utilities/CompilerUtilities/linkedhashqueue.cs
Labels: Approved to merge, Area-IDE

#31129 Restore flow graph produced for existing switch statements
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Test/Emit/Emit/ResourceTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_ISwitchOperation.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/Operations/OperationCloner.cs
  src/Compilers/Core/Portable/Operations/OperationNodes.cs
Labels: Area-Compilers, Bug, New Feature - Flow Analysis, New Language Feature - Pattern Matching

#31056 Pattern-matching fixes for ITuple, short tuple patterns, and nulls
  src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/BetterCandidates.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DeconstructionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests2.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs
  src/Workspaces/CSharpTest/EmbeddedLanguages/VirtualChars/CSharpVirtualCharServiceTests.cs
Labels: 4 - In Review, Area-Compilers, New Language Feature - Pattern Matching

#19495 Changed GetContextualKeywordKinds(), always return all contextual keywords
  src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs
Labels: Area-Compilers, Community, cla-already-signed

#31224 Azure support for VS integration tests
  .vsts-dnceng-integration.yml
  build/scripts/build.ps1
  netci.groovy
Labels: Area-Infrastructure, PR For Personal Review Only

#31409 Fix up VisualStudioWorkspace.GetFileCodeModel
  src/VisualStudio/Core/Impl/RoslynVisualStudioWorkspace.cs
  src/VisualStudio/TestUtilities2/CodeModel/Mocks/MockVisualStudioWorkspace.vb
Labels: Approved to merge, Area-IDE

#31445 Move VS integration tests to Azure Dev Ops
  .vsts-dnceng-integration.yml
  build/scripts/build.ps1
  netci.groovy
Labels: Area-Infrastructure

#31449 Fix ApplyPartialNgenOptimization property name
  src/Compilers/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.csproj
  src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj
  src/Compilers/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.vbproj
  src/EditorFeatures/CSharp/Microsoft.CodeAnalysis.CSharp.EditorFeatures.csproj
  src/EditorFeatures/Core.Wpf/Microsoft.CodeAnalysis.EditorFeatures.Wpf.csproj
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/EditorFeatures/Text/Microsoft.CodeAnalysis.EditorFeatures.Text.csproj
  src/EditorFeatures/VisualBasic/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.vbproj
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Microsoft.CodeAnalysis.CSharp.ExpressionCompiler.csproj
  src/ExpressionEvaluator/CSharp/Source/ResultProvider/NetFX20/CSharpResultProvider.NetFX20.csproj
  src/ExpressionEvaluator/CSharp/Source/ResultProvider/Portable/Microsoft.CodeAnalysis.CSharp.ResultProvider.csproj
  src/ExpressionEvaluator/Core/Source/ExpressionCompiler/Microsoft.CodeAnalysis.ExpressionCompiler.csproj
  src/ExpressionEvaluator/Core/Source/ResultProvider/NetFX20/ResultProvider.NetFX20.csproj
  src/ExpressionEvaluator/Core/Source/ResultProvider/Portable/Microsoft.CodeAnalysis.ResultProvider.csproj
  src/Features/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.Features.csproj
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/Features/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.Features.vbproj
  src/Interactive/EditorFeatures/CSharp/Microsoft.CodeAnalysis.CSharp.InteractiveEditorFeatures.csproj
  src/Interactive/EditorFeatures/Core/Microsoft.CodeAnalysis.InteractiveEditorFeatures.csproj
  src/Interactive/Features/Microsoft.CodeAnalysis.InteractiveFeatures.csproj
  src/VisualStudio/CSharp/Impl/Microsoft.VisualStudio.LanguageServices.CSharp.csproj
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/VisualStudio/Core/Impl/Microsoft.VisualStudio.LanguageServices.Implementation.csproj
  src/VisualStudio/Core/SolutionExplorerShim/Microsoft.VisualStudio.LanguageServices.SolutionExplorer.csproj
  src/VisualStudio/VisualBasic/Impl/Microsoft.VisualStudio.LanguageServices.VisualBasic.vbproj
  src/Workspaces/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.Workspaces.csproj
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
  src/Workspaces/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.Workspaces.vbproj
Labels: Approved to merge, Area-Infrastructure

#31438 make sure to VS and OOP to use same file to get mvid of analyzer file…
  src/Workspaces/Core/Portable/Execution/AbstractReferenceSerializationService.cs
Labels: Approved to merge, Area-IDE

#31429 Improve test performance by disposing of the workspace
  src/EditorFeatures/TestUtilities/Completion/AbstractCompletionProviderTests.cs
Labels: Area-IDE

#31111 Use the new IBlankLineIndentationService in the string-splitting feature.
  src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.InterpolatedStringSplitter.cs
  src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.SimpleStringSplitter.cs
  src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.StringSplitter.cs
  src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs
  src/EditorFeatures/CSharpTest/SplitStringLiteral/SplitStringLiteralCommandHandlerTests.cs
Labels: Approved to merge, Area-IDE, Community

#31133 Classify CSharp Discards as Keywords
  src/EditorFeatures/CSharpTest/Classification/SyntacticClassifierTests_Preprocessor.cs
  src/Workspaces/CSharp/Portable/Classification/ClassificationHelpers.cs
Labels: Area-IDE, Community

#31452 Goodbye Jenkins
  README.md
  build/scripts/build.ps1
  build/scripts/generate-badges.ps1
Labels: Area-Infrastructure

#31463 added unit test for analyzer checksum change
  src/Workspaces/CoreTest/Execution/SnapshotSerializationTests.cs
Labels: Area-IDE

#31410 Classify malformed XML Doc comments as XmlDocCommentText
  src/EditorFeatures/CSharpTest/Classification/SyntacticClassifierTests.cs
  src/Workspaces/CSharp/Portable/Classification/Worker_DocumentationComments.cs
Labels: Approved to merge, Area-IDE

#31444 Include Microsoft.VisualStudio.CodingConventions in the Code Style packages
  src/CodeStyle/CSharp/CodeFixes/Microsoft.CodeAnalysis.CSharp.CodeStyle.Fixes.csproj
  src/CodeStyle/VisualBasic/CodeFixes/Microsoft.CodeAnalysis.VisualBasic.CodeStyle.Fixes.vbproj
Labels: Approved to merge, Area-IDE

#31405 Switch calls to GetProjectState if we don't need the snapshot
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
Labels: Approved to merge, Area-IDE

#31213 Add tests to improve code coverage for pattern-matching
  src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/DynamicAnalysis/DynamicAnalysisResourceTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/DynamicAnalysis/DynamicInstrumentationTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/GenericConstraintsTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests2.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/LocalsTests.cs
Labels: Area-Compilers, New Language Feature - Pattern Matching

#31460 some code clean up and added some code instruments to make perf inves…
  src/Features/Core/Portable/IncrementalCaches/SymbolTreeInfoIncrementalAnalyzerProvider.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Serialization.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex.cs
  src/Workspaces/Core/Portable/Log/FunctionId.cs
Labels: Approved to merge, Area-IDE
