Repository dotnet/roslyn, pull requests merged in 2019-08, with the labels that each got.

#37607 Add back typescript gotodef on the client.
  src/Tools/ExternalAccess/LiveShare/GotoDefinition/RoslynGotoDefinitionService.Exports.cs
  src/Tools/ExternalAccess/LiveShare/RoslynLSPClientService.cs
Labels: Area-IDE

#37615 Recognize existing GlobalSuppressions.cs when it has a using directive
  src/EditorFeatures/CSharpTest/Diagnostics/Suppression/SuppressionTests.cs
  src/EditorFeatures/VisualBasicTest/Diagnostics/Suppression/SuppressionTests.vb
  src/Features/CSharp/Portable/CodeFixes/Suppression/CSharpSuppressionCodeFixProvider.cs
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionCodeFixProvider.AbstractGlobalSuppressMessageCodeAction.cs
  src/Features/VisualBasic/Portable/CodeFixes/Suppression/VisualBasicSuppressionCodeFixProvider.vb
Labels: Area-IDE, Community

#37630 Deserialize to VSClientCapabilities
  src/VisualStudio/LiveShare/Impl/FindAllReferencesHandler.cs
  src/VisualStudio/LiveShare/Impl/Shims/AbstractLiveShareHandlerShim.cs
  src/VisualStudio/LiveShare/Impl/Shims/DocumentSymbolsHandlerShim.cs
Labels: Area-IDE

#37537 EE: Do not trim comments from expression preceding a quote
  src/ExpressionEvaluator/CSharp/Source/ResultProvider/CSharpFormatter.cs
  src/ExpressionEvaluator/CSharp/Test/ResultProvider/FullNameTests.cs
  src/ExpressionEvaluator/VisualBasic/Source/ResultProvider/VisualBasicFormatter.vb
  src/ExpressionEvaluator/VisualBasic/Test/ResultProvider/FullNameTests.vb
Labels: Area-IDE

#37609 Fix trailing whitespace and superfluous blank lines in generated GlobalSuppressions.cs
  src/EditorFeatures/CSharpTest/Diagnostics/Suppression/SuppressionTest_FixAllTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/Suppression/SuppressionTests.cs
  src/EditorFeatures/VisualBasicTest/Diagnostics/Suppression/SuppressionTests.vb
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionCodeFixProvider.cs
  src/Workspaces/CSharp/Portable/Formatting/Rules/ElasticTriviaFormattingRule.cs
  src/Workspaces/CSharpTest/CodeGeneration/AddAttributesTests.cs
Labels: Area-IDE, Community

#37640 Fix using statements to use correct copy of PooledObjects
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/RunningDocumentTableEventTracker.cs
Labels: Area-IDE

#37631 Consume the new compiler API for comparing symbols without nullability
  src/EditorFeatures/CSharpTest/Diagnostics/GenerateMethod/GenerateMethodTests.cs
  src/Workspaces/Core/Portable/Utilities/NullableHelpers/AllNullabilityIgnoringSymbolComparer.cs
Labels: Area-IDE

#37628 Update some skip attributes on TypeInferrer tests
  src/EditorFeatures/CSharpTest/TypeInferrer/TypeInferrerTests.cs
Labels: Area-IDE

#37646 Fix our MSB3270 warnings
  azure-pipelines.yml
  eng/build-utils.ps1
  eng/build.ps1
  eng/targets/Bootstrap.props
  eng/targets/Bootstrap.targets
  eng/targets/DiaSymReaderNative.targets
  eng/targets/Imports.targets
  src/Compilers/CSharp/csc/csc.csproj
  src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj
  src/Compilers/Server/VBCSCompiler/VBCSCompiler.csproj
  src/Compilers/VisualBasic/vbc/vbc.csproj
  src/Interactive/csi/csi.csproj
  src/NuGet/Microsoft.Net.Compilers.Toolset/DesktopCompilerArtifacts.targets
  src/Test/PdbUtilities/Roslyn.Test.PdbUtilities.csproj
Labels: Area-Infrastructure

#37594 Add nullable annotations to speculative model creation and update code for bug found
  src/Workspaces/Core/Portable/SemanticModelWorkspaceService/ISemanticModelService.cs
  src/Workspaces/Core/Portable/SemanticModelWorkspaceService/SemanticModelWorkspaceServiceFactory.cs
  src/Workspaces/Core/Portable/Shared/Extensions/DocumentExtensions.cs
Labels: Area-IDE

#37658 Optimize memory allocation of LCS algorithm
  src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs
Labels: Area-IDE

#37598 EnC for nullables editing tests with lambdas
  src/EditorFeatures/CSharpTest/EditAndContinue/StatementEditingTests.cs
Labels: Interactive-EnC, New Language Feature - Nullable Reference Types, Test

#37690 Skip BasicEditAndContinue integration tests that are failing
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicEditAndContinue.cs
Labels: Area-Infrastructure

#37696 Merge release/dev16.3-preview2 into master
  src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj
  src/EditorFeatures/CSharpTest/RefactoringHelpers/RefactoringHelpersTests.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicEditAndContinue.cs
Labels: Area-Infrastructure

#37588 Add tests for RefaHelpers with empty Attributes / empty decls.
  src/EditorFeatures/CSharpTest/RefactoringHelpers/RefactoringHelpersTests.cs
  src/Features/Core/Portable/CodeRefactorings/AbstractRefactoringHelpersService.cs
  src/Features/Core/Portable/CodeRefactorings/IRefactoringHelpersService.cs
Labels: Area-IDE

#37683 Update signing cert used for EE.ResultProvider
  eng/Signing.props
Labels: Area-Infrastructure

#37728 Update signing cert used for EE.ResultProvider - 16.3 P3
  eng/Signing.props
Labels: Area-Infrastructure

#37729 Update signing cert used for EE.ResultProvider - 16.4 P1
  eng/Signing.props
Labels: Area-Infrastructure

#37727 Update signing cert used for EE.ResultProvider - 16.3 P2
  eng/Signing.props
Labels: Area-Infrastructure

#37718 UseExpressionBody cleanup
  src/Features/CSharp/Portable/UseExpressionBody/Helpers/UseExpressionBodyForIndexersHelper.cs
  src/Features/CSharp/Portable/UseExpressionBody/Helpers/UseExpressionBodyForPropertiesHelper.cs
  src/Features/CSharp/Portable/UseExpressionBody/Helpers/UseExpressionBodyHelper.cs
  src/Features/CSharp/Portable/UseExpressionBody/Helpers/UseExpressionBodyHelper`1.cs
  src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs
  src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/UseExpressionBodyForLambda/UseExpressionBodyForLambdaCodeStyleProvider.cs
Labels: Area-IDE, Community

#37723 Update LanguageServices dependencies
  eng/Versions.props
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
Labels: Area-Infrastructure

#37674 Switch to a strongly typed version of anonymous-function syntax nodes for their "body"
  src/Compilers/CSharp/Portable/Generated/Syntax.xml.Internal.Generated.cs
  src/Compilers/CSharp/Portable/Generated/Syntax.xml.Main.Generated.cs
  src/Compilers/CSharp/Portable/Generated/Syntax.xml.Syntax.Generated.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Syntax/AnonymousFunctionExpressionSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/AnonymousMethodExpressionSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/ParenthesizedLambdaExpressionSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/SimpleLambdaExpressionSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
  src/Compilers/CSharp/Portable/Syntax/SyntaxFactory.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxNodeExtensions.cs
  src/Compilers/CSharp/Test/Syntax/Generated/Syntax.Test.xml.Generated.cs
Labels: Area-Compilers, Community

#37641 Move comment to correct line of code
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/RunningDocumentTableEventTracker.cs
Labels: Area-IDE

#37613 Improve error priorities in case of using static class as a generic argument (#36203)
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/QueryTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs
Labels: Area-Compilers, Community

#37622 Formatting updates for C# 8
  src/Workspaces/CSharp/Portable/Formatting/Rules/BaseFormattingRule.cs
  src/Workspaces/CSharp/Portable/Formatting/Rules/TokenBasedFormattingRule.cs
  src/Workspaces/CSharpTest/Formatting/FormattingTests.cs
Labels: Area-IDE, IDE-Formatter, New Language Feature - Nullable Reference Types, New Language Feature - Pattern Matching

#37747 Revert "Full-ngen ResultProvider"
  src/ExpressionEvaluator/Core/Source/ResultProvider/NetFX20/ResultProvider.NetFX20.csproj
  src/ExpressionEvaluator/Core/Source/ResultProvider/Portable/Microsoft.CodeAnalysis.ResultProvider.csproj
Labels: Area-Infrastructure

#37764 Skip tests requiring legacy EditorConfig
  src/VisualStudio/IntegrationTest/TestUtilities/LegacyEditorConfigCondition.cs
Labels: Area-Infrastructure

#37774 Adding Skip to CSharpInteractiveCommands.VerifyPreviousAndNextHistory
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpInteractiveCommands.cs
Labels: Area-Infrastructure

#36146 Add support for Expand Filter
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/TypeImportCompletionProviderTests.cs
  src/EditorFeatures/Core/EditorFeaturesResources.Designer.cs
  src/EditorFeatures/Core/EditorFeaturesResources.resx
  src/EditorFeatures/Core/Implementation/CommentSelection/CommentUncommentSelectionCommandHandler.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CommitManager.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CompletionSource.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/Helpers.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs
  src/EditorFeatures/Core/Shared/Extensions/GlyphExtensions.cs
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.cs.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.de.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.es.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.fr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.it.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ja.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ko.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pl.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pt-BR.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ru.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.tr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hans.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hant.xlf
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_Regex.vb
  src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests_Regex.vb
  src/EditorFeatures/TestUtilities2/Intellisense/LegacyTestState.vb
  src/EditorFeatures/TestUtilities2/Intellisense/MockCompletionPresenter.vb
  src/EditorFeatures/TestUtilities2/Intellisense/ModernCompletionTestState.vb
  src/EditorFeatures/TestUtilities2/Intellisense/TestStateBase.vb
  src/Features/Core/Portable/Completion/CommonCompletionService.cs
  src/Features/Core/Portable/Completion/CompletionContext.cs
  src/Features/Core/Portable/Completion/CompletionHelper.cs
  src/Features/Core/Portable/Completion/CompletionItem.cs
  src/Features/Core/Portable/Completion/CompletionItemFlags.cs
  src/Features/Core/Portable/Completion/CompletionProvider.cs
  src/Features/Core/Portable/Completion/CompletionService.cs
  src/Features/Core/Portable/Completion/CompletionServiceOptions.cs
  src/Features/Core/Portable/Completion/CompletionServiceWithProviders.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionService.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/TypeImportCompletionItem.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpIntelliSense.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicIntelliSense.cs
  src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/VisualStudioWorkspace_OutOfProc.cs
Labels: Approved to merge, Area-IDE, IDE-IntelliSense

#37627 Consume the new IMethodSymbol.Construct overload that takes nullability
  src/EditorFeatures/CSharpTest/TypeInferrer/TypeInferrerTests.cs
  src/Workspaces/CSharp/Portable/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs
  src/Workspaces/Core/Portable/Utilities/NullableHelpers/NullableExtensions.cs
Labels: Area-IDE

#37761 Publish Ngen logs separately
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#37666 Fix our MSB3270 warnings
  azure-pipelines.yml
  eng/build-utils.ps1
  eng/build.ps1
  eng/targets/Bootstrap.props
  eng/targets/Bootstrap.targets
  eng/targets/DiaSymReaderNative.targets
  eng/targets/Imports.targets
  src/Compilers/CSharp/csc/csc.csproj
  src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj
  src/Compilers/Server/VBCSCompiler/VBCSCompiler.csproj
  src/Compilers/VisualBasic/vbc/vbc.csproj
  src/Interactive/csi/csi.csproj
  src/NuGet/Microsoft.Net.Compilers.Toolset/DesktopCompilerArtifacts.targets
  src/Test/PdbUtilities/Roslyn.Test.PdbUtilities.csproj
Labels: Area-Infrastructure

#37516 Handle speculation for AsNewClause by generating an EqualsValue node
  src/EditorFeatures/VisualBasicTest/GenerateConstructor/GenerateConstructorTests.vb
  src/Features/VisualBasic/Portable/GenerateConstructor/VisualBasicGenerateConstructorService.vb
Labels: Area-IDE

#37771 Update CODEOWNERS
  .github/CODEOWNERS
Labels: Area-Infrastructure

#37680 Update syntax document to better indicate when we expect a list to have at least one element in it.
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
Labels: Area-Compilers, Community

#37518 Use MaxSupportedLangVersion in CSharpUpgradeProjectCodeFixProvider
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs
  src/Features/CSharp/Portable/UpgradeProject/CSharpUpgradeProjectCodeFixProvider.cs
  src/Features/Core/Portable/UpgradeProject/AbstractUpgradeProjectCodeFixProvider.cs
  src/VisualStudio/CSharp/Impl/Utilities/CSharpParseOptionsChangingService.cs
  src/VisualStudio/CSharp/Test/ProjectSystemShim/CPS/AdditionalPropertiesTests.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/CPS/AdditionalPropertyNames.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProject.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/Core/Def/Utilities/IParseOptionsChangingService.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs
  src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb
  src/VisualStudio/VisualBasic/Impl/Utilities/VisualBasicParseOptionsChangingService.vb
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
Labels: Area-IDE, IDE-Project

#37726 Explicitly call BindExpression in GetSpeculativeSymbolInfo, instead o…
  src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/NullablePublicAPITests.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
Labels: Approved to merge, Area-Compilers, New Language Feature - Nullable Semantic Model, ask-mode

#37767 VSSDK update
  eng/Versions.props
  src/EditorFeatures/CSharp.Wpf/Microsoft.CodeAnalysis.CSharp.EditorFeatures.Wpf.csproj
  src/EditorFeatures/CSharp/Microsoft.CodeAnalysis.CSharp.EditorFeatures.csproj
  src/EditorFeatures/CSharpTest/Microsoft.CodeAnalysis.CSharp.EditorFeatures.UnitTests.csproj
  src/EditorFeatures/CSharpTest2/Microsoft.CodeAnalysis.CSharp.EditorFeatures2.UnitTests.csproj
  src/EditorFeatures/Core.Wpf/Microsoft.CodeAnalysis.EditorFeatures.Wpf.csproj
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/EditorFeatures/Test/Microsoft.CodeAnalysis.EditorFeatures.UnitTests.csproj
  src/EditorFeatures/Test2/Microsoft.CodeAnalysis.EditorFeatures2.UnitTests.vbproj
  src/EditorFeatures/TestUtilities/Roslyn.Services.Test.Utilities.csproj
  src/EditorFeatures/TestUtilities2/Microsoft.CodeAnalysis.EditorFeatures.Test.Utilities.vbproj
  src/EditorFeatures/Text/Microsoft.CodeAnalysis.EditorFeatures.Text.csproj
  src/EditorFeatures/VisualBasic/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.vbproj
  src/EditorFeatures/VisualBasicTest/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.UnitTests.vbproj
  src/Features/LanguageServer/Protocol/Microsoft.CodeAnalysis.LanguageServer.Protocol.csproj
  src/Setup/DevDivInsertionFiles/DevDivInsertionFiles.csproj
  src/Test/Diagnostics/Roslyn.Hosting.Diagnostics.csproj
  src/Tools/ExternalAccess/FSharp/Microsoft.CodeAnalysis.ExternalAccess.FSharp.csproj
  src/Tools/ExternalAccess/FSharpTest/Microsoft.CodeAnalysis.ExternalAccess.FSharp.UnitTests.csproj
  src/Tools/ExternalAccess/LiveShare/Microsoft.CodeAnalysis.ExternalAccess.LiveShare.csproj
  src/Tools/ExternalAccess/Xamarin.Remote/Microsoft.CodeAnalysis.ExternalAccess.Xamarin.Remote.csproj
  src/VisualStudio/CSharp/Impl/Microsoft.VisualStudio.LanguageServices.CSharp.csproj
  src/VisualStudio/CSharp/Test/Microsoft.VisualStudio.LanguageServices.CSharp.UnitTests.csproj
  src/VisualStudio/CodeLens/Microsoft.VisualStudio.LanguageServices.CodeLens.csproj
  src/VisualStudio/Core/Impl/Microsoft.VisualStudio.LanguageServices.Implementation.csproj
  src/VisualStudio/Core/SolutionExplorerShim/Microsoft.VisualStudio.LanguageServices.SolutionExplorer.csproj
  src/VisualStudio/Core/Test.Next/Roslyn.VisualStudio.Next.UnitTests.csproj
  src/VisualStudio/Core/Test/Microsoft.VisualStudio.LanguageServices.UnitTests.vbproj
  src/VisualStudio/IntegrationTest/TestSetup/Microsoft.VisualStudio.IntegrationTest.Setup.csproj
  src/VisualStudio/IntegrationTest/TestUtilities/Microsoft.VisualStudio.IntegrationTest.Utilities.csproj
  src/VisualStudio/LiveShare/Impl/Microsoft.VisualStudio.LanguageServices.LiveShare.csproj
  src/VisualStudio/RemoteHostClientMock/Roslyn.VisualStudio.RemoteHostClientMock.csproj
  src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj
  src/VisualStudio/TestUtilities2/Microsoft.VisualStudio.LanguageServices.Test.Utilities2.vbproj
  src/VisualStudio/VisualBasic/Impl/Microsoft.VisualStudio.LanguageServices.VisualBasic.vbproj
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/Roslyn.VisualStudio.DiagnosticsWindow.csproj
  src/VisualStudio/Xaml/Impl/Microsoft.VisualStudio.LanguageServices.Xaml.csproj
Labels: Area-Infrastructure

#37770 Fix namespace incremental parsing bug
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Test/Syntax/IncrementalParsing/IncrementalParsingTests.cs
Labels: Area-Compilers, ask-mode

#37804 Clear Major/MinorVersion to keep arcade from overwriting our VersionPrefix
  eng/Versions.props
Labels: Area-Infrastructure

#37684 Make it clear in Syntax.xml when fields are exclusive of each other.
  src/Compilers/CSharp/Portable/Generated/Syntax.xml.Internal.Generated.cs
  src/Compilers/CSharp/Portable/Generated/Syntax.xml.Syntax.Generated.cs
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/AbstractFileWriter.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/Model/AbstractNode.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/Model/Field.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/Model/Node.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/Model/TreeType.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/Program.cs
Labels: Area-Compilers, Community

#37803 Disable interprocedural dataflow analysis for DisposableFieldsShouldB…
  src/Features/Core/Portable/DisposeAnalysis/DisposableFieldsShouldBeDisposedDiagnosticAnalyzer.cs
  src/Features/Core/Portable/DisposeAnalysis/DisposeAnalysisHelper.cs
  src/Features/Core/Portable/DisposeAnalysis/DisposeObjectsBeforeLosingScopeDiagnosticAnalyzer.cs
Labels: Area-Analyzers, Area-IDE

#37679 Delete some dead code in analyzer driver
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs
Labels: Area-Analyzers, Area-Compilers

#37323 Add ref and qualified generic name detection for SpeculativeT completion.
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SpeculativeTCompletionProviderTests.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/SpeculativeTCompletionProvider.cs
  src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs
Labels: Area-IDE, Community

#37826 Make Syntax.xml choices slightly more explicit.
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
Labels: Area-Compilers

#37827 Fix "fixed" keyword formatting (#37031)
  src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs
  src/Workspaces/CSharpTest/Formatting/FormattingTests.cs
Labels: Area-IDE, Community

#37822 Remove inaccessible attributes when generating from the navigation bar
  src/EditorFeatures/Test2/NavigationBar/VisualBasicNavigationBarTests.vb
  src/EditorFeatures/VisualBasic/NavigationBar/GenerateEventHandlerItem.vb
  src/EditorFeatures/VisualBasic/NavigationBar/GenerateMethodItem.vb
Labels: Area-IDE

#37838 Fix bounds in on header attr #37837
  src/EditorFeatures/CSharpTest/RefactoringHelpers/RefactoringHelpersTests.cs
  src/Features/Core/Portable/CodeRefactorings/AbstractRefactoringHelpersService.cs
  src/Workspaces/Core/Portable/LanguageServices/SyntaxFactsService/AbstractSyntaxFactsService.cs
Labels: Area-IDE

#37778 Remove flighting and have a checkbox opt out of new .editorconfig support
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/ServicesVSResources.Designer.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageStrings.vb
  src/Workspaces/Core/Portable/Experiments/IExperimentationService.cs
  src/Workspaces/Core/Portable/Options/EditorConfig/EditorConfigDocumentOptionsProviderFactory.cs
  src/Workspaces/Remote/Core/Services/TemporaryWorkspace.cs
  src/Workspaces/Remote/Core/Services/TemporaryWorkspaceOptionsServiceFactory.cs
Labels: Area-IDE

#37819 Simplify away nullable annotations in non-nullable contexts
  src/EditorFeatures/CSharpTest/Diagnostics/GenerateMethod/GenerateMethodTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/MakeMethodAsynchronous/MakeMethodAsynchronousTests.cs
  src/EditorFeatures/CSharpTest/Microsoft.CodeAnalysis.CSharp.EditorFeatures.UnitTests.csproj
  src/EditorFeatures/CSharpTest/TypeInferrer/TypeInferrerTests.cs
  src/EditorFeatures/Test2/Simplification/NullableAnnotationSimplificationTests.vb
  src/EditorFeatures/TestUtilities/TypeInferrer/TypeInferrerTestBase.cs
  src/EditorFeatures/VisualBasicTest/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.UnitTests.vbproj
  src/EditorFeatures/VisualBasicTest/TypeInferrer/TypeInferrerTests.vb
  src/Workspaces/CSharp/Portable/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs
  src/Workspaces/CSharp/Portable/Simplification/CSharpSimplificationService.cs
  src/Workspaces/CSharp/Portable/Simplification/Reducers/CSharpNullableAnnotationReducer.Rewriter.cs
  src/Workspaces/CSharp/Portable/Simplification/Reducers/CSharpNullableAnnotationReducer.cs
  src/Workspaces/CSharp/Portable/Simplification/Reducers/CSharpParenthesesReducer.cs
  src/Workspaces/Core/Portable/LanguageServices/TypeInferenceService/AbstractTypeInferenceService.AbstractTypeInferrer.cs
Labels: Area-IDE

#37859 UseExplicitTupleName: Avoid NullRefException on Rest field
  src/EditorFeatures/CSharpTest/UseExplicitTupleName/UseExplicitTupleNameTests.cs
  src/Features/Core/Portable/UseExplicitTupleName/UseExplicitTupleNameDiagnosticAnalyzer.cs
Labels: Area-IDE

#37857 don't crash Vs because OOP lost its connection
  src/VisualStudio/Core/Def/Implementation/Remote/ServiceHubRemoteHostClient.cs
Labels: Area-IDE

#37757 Remove module scope from NullableContextAttribute
  docs/features/nullable-metadata.md
Labels: Area-Compilers, Community, Documentation

#37543 Introduce IDisposable to ArrayBuilder.
  src/Compilers/VisualBasic/Portable/Symbols/TypeSubstitution.vb
  src/Dependencies/PooledObjects/PooledHashSet.cs
  src/Dependencies/PooledObjects/PooledStringBuilder.cs
  src/EditorFeatures/Core/FindUsages/IDefinitionsAndReferencesFactory.cs
  src/EditorFeatures/Core/GoToDefinition/GoToDefinitionHelpers.cs
  src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.ProjectCodeFixProvider.cs
  src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs
  src/EditorFeatures/Core/Implementation/EditAndContinue/EditAndContinueDiagnosticUpdateSource.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/SignatureHelp/Controller_TypeChar.cs
  src/EditorFeatures/Core/Implementation/Interactive/Completion/AbstractLoadDirectiveCompletionProvider.cs
  src/EditorFeatures/Core/Implementation/Interactive/Completion/AbstractReferenceDirectiveCompletionProvider.cs
  src/EditorFeatures/Core/Implementation/Interactive/Completion/GlobalAssemblyCacheCompletionHelper.cs
  src/EditorFeatures/Core/Implementation/TodoComment/TodoCommentState.cs
  src/EditorFeatures/Core/Shared/Options/PerformanceFunctionIdOptionsProvider.cs
  src/EditorFeatures/Test/CodeGeneration/CodeGenerationTests.cs
  src/EditorFeatures/Test/Utilities/PatternMatcherTests.cs
  src/Features/CSharp/Portable/ConvertSwitchStatementToExpression/ConvertSwitchStatementToExpressionCodeFixProvider.cs
  src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs
  src/Features/CSharp/Portable/TypeStyle/UseExplicitTypeCodeFixProvider.cs
  src/Features/Core/Portable/AddParameter/AbstractAddParameterCodeFixProvider.cs
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionCodeFixProvider.RemoveSuppressionCodeAction.BatchFixer.cs
  src/Features/Core/Portable/CodeRefactorings/AbstractRefactoringHelpersService.cs
  src/Features/Core/Portable/CodeRefactorings/SyncNamespace/AbstractChangeNamespaceService.cs
  src/Features/Core/Portable/Diagnostics/DiagnosticHelper.cs
  src/Features/Core/Portable/DocumentHighlighting/AbstractDocumentHighlightsService.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/Core/Portable/GenerateMember/GenerateParameterizedMember/AbstractGenerateDeconstructMethodService.State.cs
  src/Features/Core/Portable/Shared/Naming/IdentifierNameParts.cs
  src/Features/Core/Portable/Wrapping/ChainedExpression/AbstractChainedExpressionWrapper.cs
  src/Workspaces/Core/Portable/Utilities/ObjectPools/ArrayBuilder.cs
  src/Workspaces/Core/Portable/Utilities/ObjectPools/IPooled.cs
  src/Workspaces/Core/Portable/Utilities/ObjectPools/PooledDisposer.cs
  src/Workspaces/Core/Portable/Utilities/ObjectPools/PooledHashSet.cs
  src/Workspaces/Core/Portable/Utilities/ObjectPools/PooledStringBuilder.cs
Labels: Area-Compilers, Area-IDE

#37691 UniqueItem is not triggered when completion is initiated by backspace
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/FilterResult.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
Labels: Area-IDE, Bug, IDE-IntelliSense

#36314 Update default naming styles to support 'private protected'
  src/VisualStudio/Core/Test/Options/BasicEditorConfigGeneratorTests.vb
  src/VisualStudio/Core/Test/Options/CSharpEditorConfigGeneratorTests.vb
  src/Workspaces/Core/Portable/NamingStyles/Serialization/NamingStylePreferences.cs
Labels: Area-IDE

#37766 Create a UIContext triggered by projects in the VisualStudioWorkspace
  src/VisualStudio/CSharp/Impl/ProjectSystemShim/CSharpProjectExistsUIContextProviderLanguageService.cs
  src/VisualStudio/Core/Def/Guids.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/IProjectExistsUIContextProviderLanguageService.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectFactory.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpProjectExistsUIContext.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicProjectExistsUIContext.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/Shell_InProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/Shell_OutOfProc.cs
  src/VisualStudio/VisualBasic/Impl/ProjectSystemShim/VisualBasicProjectExistsUIContextProviderLanguageService.vb
Labels: Area-IDE

#37836 Do not go back to syntax to determine if a source-property was an explicit implementation.
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs
Labels: Area-Compilers, Community

#37524 Extract readonly method
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenReadonlyStructTests.cs
  src/Compilers/CSharp/Test/Semantic/FlowAnalysis/FlowDiagnosticTests.cs
  src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs
  src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractMethodTests.cs
  src/EditorFeatures/CSharpTest/ConvertForEachToFor/ConvertForEachToForTests.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.AnalyzerResult.cs
Labels: Area-Compilers, Area-IDE, IDE-CodeStyle

#37395 Add new feature to add assignments for unassigned 'out' parameters.
  src/Compilers/CSharp/Portable/FlowAnalysis/CSharpDataFlowAnalysis.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/DefinitelyAssignedWalker.cs
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
  src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs
  src/Compilers/Core/Portable/Compilation/DataFlowAnalysis.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/DefinitelyAssignedWalker.vb
  src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/VisualBasicDataFlowAnalysis.vb
  src/Compilers/VisualBasic/Test/Semantic/FlowAnalysis/FlowTestBase.vb
  src/Compilers/VisualBasic/Test/Semantic/FlowAnalysis/ImplicitVariableTests.vb
  src/Compilers/VisualBasic/Test/Semantic/FlowAnalysis/RegionAnalysisTests.vb
  src/Compilers/VisualBasic/Test/Semantic/FlowAnalysis/RegionAnalysisTestsWithStaticLocals.vb
  src/EditorFeatures/CSharpTest/AssignOutParameters/AssignOutParametersAboveReturnTests.cs
  src/EditorFeatures/CSharpTest/AssignOutParameters/AssignOutParametersAtStartTests.cs
  src/Features/CSharp/Portable/AssignOutParameters/AbstractAssignOutParametersCodeFixProvider.cs
  src/Features/CSharp/Portable/AssignOutParameters/AssignOutParametersAboveReturnCodeFixProvider.cs
  src/Features/CSharp/Portable/AssignOutParameters/AssignOutParametersAtStartCodeFixProvider.cs
  src/Features/CSharp/Portable/CSharpFeaturesResources.Designer.cs
  src/Features/CSharp/Portable/CSharpFeaturesResources.resx
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.cs.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.de.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.es.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.fr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.it.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ja.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ko.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pl.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pt-BR.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ru.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.tr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hans.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hant.xlf
  src/Test/Utilities/Portable/Traits/Traits.cs
Labels: Area-Compilers, Area-IDE, Community, Feature Request

#37855 Improve syntax recovery for use of `;` instead of `,` in switch expression
  src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs
Labels: Area-Compilers, New Language Feature - Pattern Matching

#37878 Move to new ilasm version
  Compilers.sln
  Roslyn.sln
  eng/Versions.props
  eng/targets/ILTools.targets
  src/Compilers/CSharp/Test/Emit/Microsoft.CodeAnalysis.CSharp.Emit.UnitTests.csproj
  src/Compilers/CSharp/Test/IOperation/Microsoft.CodeAnalysis.CSharp.IOperation.UnitTests.csproj
  src/Compilers/CSharp/Test/Semantic/Microsoft.CodeAnalysis.CSharp.Semantic.UnitTests.csproj
  src/Compilers/CSharp/Test/Symbol/Microsoft.CodeAnalysis.CSharp.Symbol.UnitTests.csproj
  src/Compilers/CSharp/Test/WinRT/Microsoft.CodeAnalysis.CSharp.WinRT.UnitTests.csproj
  src/Compilers/VisualBasic/Test/Emit/Microsoft.CodeAnalysis.VisualBasic.Emit.UnitTests.vbproj
  src/Compilers/VisualBasic/Test/Semantic/Microsoft.CodeAnalysis.VisualBasic.Semantic.UnitTests.vbproj
  src/Compilers/VisualBasic/Test/Symbol/Microsoft.CodeAnalysis.VisualBasic.Symbol.UnitTests.vbproj
  src/EditorFeatures/CSharpTest/Microsoft.CodeAnalysis.CSharp.EditorFeatures.UnitTests.csproj
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/Microsoft.CodeAnalysis.CSharp.ExpressionCompiler.UnitTests.csproj
  src/ExpressionEvaluator/CSharp/Test/ResultProvider/Microsoft.CodeAnalysis.CSharp.ResultProvider.UnitTests.csproj
  src/ExpressionEvaluator/Core/Test/FunctionResolver/Microsoft.CodeAnalysis.FunctionResolver.UnitTests.csproj
  src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/Microsoft.CodeAnalysis.VisualBasic.ExpressionCompiler.UnitTests.vbproj
  src/ExpressionEvaluator/VisualBasic/Test/ResultProvider/Microsoft.CodeAnalysis.VisualBasic.ResultProvider.UnitTests.vbproj
  src/Test/Utilities/Portable/Assert/ConditionalFactAttribute.cs
  src/Test/Utilities/Portable/Metadata/IlasmUtilities.cs
  src/Test/Utilities/Portable/Roslyn.Test.Utilities.csproj
  src/Tools/ILTools/ILTools.proj
Labels: Area-Infrastructure

#37916 Update partial load dialog string to better match task center.
  src/EditorFeatures/Core/EditorFeaturesResources.Designer.cs
  src/EditorFeatures/Core/EditorFeaturesResources.resx
  src/EditorFeatures/Core/Shared/Extensions/ITextSnapshotExtensions.cs
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.cs.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.de.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.es.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.fr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.it.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ja.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ko.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pl.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pt-BR.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ru.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.tr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hans.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hant.xlf
  src/VisualStudio/CSharp/Impl/LanguageService/CSharpCodeCleanupFixer.cs
Labels: Area-IDE

#37839 Update patch version in 16.2
  eng/Versions.props
Labels: Area-Infrastructure

#37918 Moving publish to separate stage
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#37900 Enum member formatting should follow csharp_space_around_declaration_statements
  src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs
  src/Workspaces/CSharpTest/Formatting/FormattingTests.cs
Labels: Area-IDE, Community

#37939 Mark M.VS.LanguageServer.Client as a private package
  eng/Versions.props
Labels: Area-Infrastructure

#37922 Don't synthesize a parameter list out of nowhere.
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
Labels: Area-IDE, Community

#37844 Fix speculation of AsNewClause in Rename Rewriter
  src/EditorFeatures/Test2/Rename/VisualBasic/DeclarationConflictTests.vb
  src/Workspaces/VisualBasic/Portable/Rename/VisualBasicRenameRewriterLanguageService.vb
Labels: Area-IDE

#37906 LOC CHECKIN | dotnet/roslyn master | 20190812
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.de.xlf
Labels: Area-IDE

#37892 Fix use explicit type and nullable-annotated array syntax generation
  src/EditorFeatures/CSharpTest/CodeRefactorings/UseExplicitOrImplicitType/UseExplicitTypeRefactoringTests.cs
  src/Features/CSharp/Portable/TypeStyle/UseExplicitTypeCodeFixProvider.cs
  src/Workspaces/CSharp/Portable/Extensions/ITypeSymbolExtensions.TypeSyntaxGeneratorVisitor.cs
Labels: Area-IDE

#37840 Add a tool which generates a reasonable C# grammar facsimile from our syntactic model.
  eng/generate-compiler-code.ps1
  src/Compilers/CSharp/Portable/Generated/CSharp.Generated.g4
  src/Compilers/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.csproj
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/CSharpSyntaxGenerator.csproj
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/Grammar/GrammarGenerator.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/Model/Field.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/Model/Kind.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/Program.cs
  src/Tools/Source/CompilerGeneratorTools/Source/VisualBasicSyntaxGenerator/Program.vb
Labels: Area-Compilers

#36028 Implement Quick Info support for 'inheritdoc'
  src/Compilers/Core/Portable/InternalUtilities/DocumentationCommentXmlNames.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
  src/EditorFeatures/Test2/IntelliSense/IntellisenseQuickInfoBuilderTests_Inheritdoc.vb
  src/Features/Core/Portable/Completion/Providers/AbstractDocCommentCompletionProvider.cs
  src/Features/Core/Portable/LanguageServices/SymbolDisplayService/AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.cs
  src/Features/Core/Portable/Shared/Extensions/ISymbolExtensions_2.cs
  src/Features/VisualBasic/Portable/Completion/CompletionProviders/CompletionListTagCompletionProvider.vb
  src/Features/VisualBasic/Portable/Completion/KeywordRecommenders/Types/BuiltInTypesKeywordRecommender.vb
  src/VisualStudio/Core/Def/Implementation/Library/ObjectBrowser/AbstractDescriptionBuilder.cs
  src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs
Labels: Area-IDE

#37807 Liveshare Lsp syntax classifications
  src/EditorFeatures/Text/Microsoft.CodeAnalysis.EditorFeatures.Text.csproj
  src/Tools/ExternalAccess/LiveShare/Classification/RoslynClassificationService.Exports.cs
  src/Tools/ExternalAccess/LiveShare/Classification/RoslynClassificationService.cs
  src/Tools/ExternalAccess/LiveShare/Classification/RoslynClassificationServiceFactory.cs
  src/Tools/ExternalAccess/LiveShare/Classification/RoslynSyntaxClassificationService.cs
  src/Tools/ExternalAccess/LiveShare/Classification/RoslynSyntaxClassificationServiceFactory.cs
  src/Tools/ExternalAccess/LiveShare/CodeActions/RoslynCodeActionProvider.cs
  src/Tools/ExternalAccess/LiveShare/LanguageServiceUtils.cs
  src/Tools/ExternalAccess/LiveShare/RoslynLSPClientService.cs
  src/VisualStudio/Core/Def/RoslynPackage.cs
  src/VisualStudio/LiveShare/Impl/AbstractClassificationsHandler.cs
  src/VisualStudio/LiveShare/Impl/ClassificationsHandler.Exports.cs
  src/VisualStudio/LiveShare/Impl/ClassificationsHandler.cs
  src/VisualStudio/LiveShare/Impl/CustomProtocol/RoslynExperimentalCapabilities.cs
  src/VisualStudio/LiveShare/Impl/LexicalClassificationsHandler.cs
  src/VisualStudio/LiveShare/Impl/Shims/InitializeHandlerShim.cs
  src/VisualStudio/LiveShare/Impl/SyntaxClassificationsHandler.cs
  src/Workspaces/Core/Portable/Experiments/IExperimentationService.cs
  src/Workspaces/Core/Portable/Log/FunctionId.cs
  src/Workspaces/Core/Portable/Log/HistogramLogAggregator.cs
  src/Workspaces/Core/Portable/Log/SyntacticLspLogger.cs
Labels: Area-IDE

#37917 added api usage telemetry reporter
  src/VisualStudio/Core/Def/Telemetry/ProjectTelemetryIncrementalAnalyzerProvider.cs
  src/Workspaces/Core/Portable/SolutionCrawler/ExportIncrementalAnalyzerProviderAttribute.cs
  src/Workspaces/Remote/Core/Microsoft.CodeAnalysis.Remote.Workspaces.csproj
  src/Workspaces/Remote/Core/Services/RoslynServices.cs
  src/Workspaces/Remote/Core/Telemetry/ApiUsageIncrementalAnalyzerProvider.cs
  src/Workspaces/Remote/ServiceHub/Services/RemoteHostService.PerformanceReporter.cs
  src/Workspaces/Remote/ServiceHub/Services/RemoteHostService.cs
  src/Workspaces/Remote/ServiceHub/Telemetry/WatsonReporter.cs
Labels: Area-IDE

#37895 Update package heuristic to include other invalid directories.
  src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs
Labels: Area-IDE

#37881 Add nullable API annotations to Project/ProjectInfo and friends
  src/Features/CSharp/Portable/UpgradeProject/CSharpUpgradeProjectCodeFixProvider.cs
  src/Workspaces/Core/Portable/Utilities/ImmutableArrayExtensions.cs
  src/Workspaces/Core/Portable/Workspace/Host/DocumentService/Extensions.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Project.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectId.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectInfo.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
Labels: Area-IDE

#37943 changed our task center status bar to say "low priority background pr…
  src/Features/Core/Portable/SolutionCrawler/ISolutionCrawlerProgressReporter.cs
  src/Features/Core/Portable/SolutionCrawler/SolutionCrawlerProgressReporter.cs
  src/Features/Core/Portable/SolutionCrawler/SolutionCrawlerRegistrationService.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.AsyncWorkItemQueue.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.HighPriorityProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.IncrementalAnalyzerProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.LowPriorityProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs
  src/VisualStudio/Core/Def/Implementation/Diagnostics/DiagnosticProgressReporter.cs
  src/VisualStudio/Core/Def/ServicesVSResources.Designer.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
Labels: Area-IDE

#37914 Allow implementation of virtual interface methods in VB.
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEPropertySymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/ImplementsHelper.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourcePropertySymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/SymbolExtensions.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/DefaultInterfaceImplementationTests.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/SymbolErrorTests.vb
Labels: Area-Compilers, Language-VB, New Language Feature - Default Interface Impl

#37971 Added references to M.VS.LanguageServer.Client to the CSharp and VB client projects
  eng/Versions.props
  src/VisualStudio/CSharp/Impl/Microsoft.VisualStudio.LanguageServices.CSharp.csproj
  src/VisualStudio/VisualBasic/Impl/Microsoft.VisualStudio.LanguageServices.VisualBasic.vbproj
Labels: Area-Infrastructure

#37952 Test ReadOnlySpan initialization from static data (#24621)
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenReadOnlySpanConstructionTest.cs
Labels: Area-Compilers, Community, Test

#37966 Make sure to keep nullability information when generating the new field
  src/EditorFeatures/CSharpTest/ConvertAutoPropertyToFullProperty/ConvertAutoPropertyToFullPropertyTests.cs
  src/Features/Core/Portable/ConvertAutoPropertyToFullProperty/AbstractConvertAutoPropertyToFullPropertyCodeRefactoringProvider.cs
Labels: Area-IDE

#37929 Fix some constructor-related generation refactorings with top-level nullability
  src/EditorFeatures/CSharpTest/GenerateFromMembers/GenerateConstructorFromMembers/GenerateConstructorFromMembersTests.cs
  src/EditorFeatures/CSharpTest/InitializeParameter/InitializeMemberFromParameterTests.cs
  src/Features/Core/Portable/GenerateConstructorFromMembers/GenerateConstructorFromMembersCodeRefactoringProvider.State.cs
  src/Features/Core/Portable/GenerateFromMembers/AbstractGenerateFromMembersCodeRefactoringProvider.cs
  src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs
  src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions.cs
Labels: Area-IDE

#37992 Make CompletionItem.InlineDescription public
  src/Features/Core/Portable/Completion/CompletionItem.cs
  src/Features/Core/Portable/PublicAPI.Unshipped.txt
Labels: Area-IDE, Community

#37965 Don't show nullability analysis for value types or constant values
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
  src/Features/CSharp/Portable/QuickInfo/CSharpSemanticQuickInfoProvider.cs
Labels: Area-IDE, New Language Feature - Nullable Reference Types

#37791 Generate IOperation visitors and simple implementation classes
  Roslyn.sln
  src/Compilers/Core/Portable/Generated/FlowAnalysis.Generated.cs
  src/Compilers/Core/Portable/Generated/Operations.Generated.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/Operations/OperationCloner.cs
  src/Compilers/Core/Portable/Operations/OperationInterfaces.xml
  src/Compilers/Core/Portable/Operations/OperationNodes.cs
  src/Compilers/Core/Portable/Operations/OperationVisitor.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Test/Utilities/Portable/Compilation/OperationTreeVerifier.cs
  src/Test/Utilities/Portable/Compilation/TestOperationVisitor.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/CompilersIOperationGenerator.csproj
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/IOperationClassWriter.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/Model.cs
Labels: Area-Compilers, New Feature - IOperation

#37941 Refactorings ordering report applicableToSpan
  src/EditorFeatures/CSharpTest/CodeActions/Preview/ErrorCases/ExceptionInCodeAction.cs
  src/EditorFeatures/CSharpTest/CodeActions/Preview/PreviewTests.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionSetComparer.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs
  src/EditorFeatures/Test/LinkedFiles/LinkedFileDiffMergingEditorTests.cs
  src/EditorFeatures/TestUtilities/ChangeSignature/AbstractChangeSignatureTests.cs
  src/EditorFeatures/TestUtilities/CodeActions/AbstractCodeActionTest.cs
  src/EditorFeatures/VisualBasicTest/CodeActions/Preview/PreviewTests.vb
  src/Features/CSharp/Portable/CodeRefactorings/ConvertLocalFunctionToMethod/CSharpConvertLocalFunctionToMethodCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/CodeRefactorings/InlineTemporary/InlineTemporaryCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/CodeRefactorings/LambdaSimplifier/LambdaSimplifierCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/CodeRefactorings/PullMemberUp/CSharpPullMemberUpCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/CodeRefactorings/UseExplicitOrImplicitType/AbstractUseTypeCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeRefactoringProvider.cs
  src/Features/Core/Portable/AddFileBanner/AbstractAddFileBannerCodeRefactoringProvider.cs
  src/Features/Core/Portable/CodeRefactorings/AddAwait/AbstractAddAwaitCodeRefactoringProvider.cs
  src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsRefactoringProvider.cs
  src/Features/Core/Portable/CodeRefactorings/CodeRefactoring.cs
  src/Features/Core/Portable/CodeRefactorings/CodeRefactoringService.cs
  src/Features/Core/Portable/CodeRefactorings/ExtractMethod/AbstractExtractMethodCodeRefactoringProvider.cs
  src/Features/Core/Portable/CodeRefactorings/SyncNamespace/AbstractSyncNamespaceCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertAnonymousTypeToClass/AbstractConvertAnonymousTypeToClassCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertAutoPropertyToFullProperty/AbstractConvertAutoPropertyToFullPropertyCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertForEachToFor/AbstractConvertForEachToForCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertForToForEach/AbstractConvertForToForEachCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertIfToSwitch/AbstractConvertIfToSwitchCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertLinq/AbstractConvertLinqQueryToForEachProvider.cs
  src/Features/Core/Portable/ConvertLinq/ConvertForEachToLinqQuery/AbstractConvertForEachToLinqQueryProvider.cs
  src/Features/Core/Portable/ConvertNumericLiteral/AbstractConvertNumericLiteralCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.cs
  src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs
  src/Features/Core/Portable/ConvertTupleToStruct/AbstractConvertTupleToStructCodeRefactoringProvider.cs
  src/Features/Core/Portable/GenerateConstructorFromMembers/GenerateConstructorFromMembersCodeRefactoringProvider.cs
  src/Features/Core/Portable/GenerateOverrides/GenerateOverridesCodeRefactoringProvider.cs
  src/Features/Core/Portable/IntroduceUsingStatement/AbstractIntroduceUsingStatementCodeRefactoringProvider.cs
  src/Features/Core/Portable/IntroduceVariable/IntroduceLocalForExpressionCodeRefactoringProvider.cs
  src/Features/Core/Portable/IntroduceVariable/IntroduceVariableCodeRefactoringProvider.cs
  src/Features/Core/Portable/InvertConditional/AbstractInvertConditionalCodeRefactoringProvider.cs
  src/Features/Core/Portable/InvertIf/AbstractInvertIfCodeRefactoringProvider.cs
  src/Features/Core/Portable/InvertLogical/AbstractInvertLogicalCodeRefactoringProvider.cs
  src/Features/Core/Portable/MoveDeclarationNearReference/AbstractMoveDeclarationNearReferenceCodeRefactoringProvider.cs
  src/Features/Core/Portable/NameTupleElement/AbstractNameTupleElementCodeRefactoringProvider.cs
  src/Features/Core/Portable/PullMemberUp/AbstractPullMemberUpRefactoringProvider.cs
  src/Features/Core/Portable/ReplaceDocCommentTextWithTag/AbstractReplaceDocCommentTextWithTagCodeRefactoringProvider.cs
  src/Features/Core/Portable/ReplaceMethodWithProperty/AbstractReplaceMethodWithPropertyService.cs
  src/Features/Core/Portable/ReplaceMethodWithProperty/ReplaceMethodWithPropertyCodeRefactoringProvider.cs
  src/Features/Core/Portable/ReplacePropertyWithMethods/AbstractReplacePropertyWithMethodsService.cs
  src/Features/Core/Portable/ReplacePropertyWithMethods/ReplacePropertyWithMethodsCodeRefactoringProvider.cs
  src/Features/Core/Portable/SplitOrMergeIfStatements/AbstractMergeIfStatementsCodeRefactoringProvider.cs
  src/Features/Core/Portable/SplitOrMergeIfStatements/AbstractSplitIfStatementCodeRefactoringProvider.cs
  src/Features/Core/Portable/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs
  src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionsHandlerBase.cs
  src/Features/VisualBasic/Portable/CodeRefactorings/InlineTemporary/InlineTemporaryCodeRefactoringProvider.vb
  src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs
  src/Workspaces/CSharpTest/Formatting/FormattingTests.cs
  src/Workspaces/Core/Portable/CodeRefactorings/CodeRefactoringContext.cs
Labels: Area-IDE

#37915 Reduce memory consumption for string concatenation from O(n^2) to O(n)
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/Binder/Binder_TupleOperators.cs
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/ConstantTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs
  src/Compilers/Core/CodeAnalysisTest/Collections/RopeTests.cs
  src/Compilers/Core/Portable/Collections/Rope.cs
  src/Compilers/Core/Portable/ConstantValue.cs
  src/Compilers/Core/Portable/ConstantValueSpecialized.cs
  src/Compilers/Core/Portable/SwitchConstantValueHelper.cs
  src/Compilers/VisualBasic/Portable/Binding/Binder_Operators.vb
  src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_NullableHelpers.vb
  src/Compilers/VisualBasic/Portable/Semantics/Operators.vb
  src/Compilers/VisualBasic/Portable/VBResources.Designer.vb
  src/Compilers/VisualBasic/Portable/VBResources.resx
  src/Compilers/VisualBasic/Portable/xlf/VBResources.cs.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.de.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.es.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.fr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.it.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ja.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ko.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pl.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pt-BR.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ru.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.tr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hans.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hant.xlf
  src/Compilers/VisualBasic/Test/Semantic/Semantics/BinaryOperators.vb
Labels: Area-Compilers, Bug

#37942 Support Go to Base for VB
  src/EditorFeatures/Test2/GoToBase/CSharpGoToBaseTests.vb
  src/EditorFeatures/Test2/GoToBase/GoToBaseTests.vb
  src/EditorFeatures/Test2/GoToBase/GoToBaseTestsBase.vb
  src/EditorFeatures/Test2/GoToBase/VisuaBasicGoToBaseTests.vb
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/BaseTypeFinder.cs
Labels: Area-IDE

#38002 Fix calls to WaitAndGetResult in Peek
  src/EditorFeatures/Core/Implementation/Peek/DefinitionPeekableItem.cs
Labels: Area-IDE

#36931 Adding Null Checks For All Parameters
  src/EditorFeatures/CSharpTest/InitializeParameter/AddParameterCheckTests.cs
  src/EditorFeatures/VisualBasicTest/InitializeParameter/AddParameterCheckTests.vb
  src/Features/Core/Portable/FeaturesResources.Designer.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/InitializeParameter/AbstractAddParameterCheckCodeRefactoringProvider.cs
  src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs
  src/Features/Core/Portable/InitializeParameter/AbstractInitializeParameterCodeRefactoringProvider.cs
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
Labels: Area-IDE

#38037 TypeImportCompletionItem.GetCompletionDescriptionAsync should not return null
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/TypeImportCompletionItem.cs
Labels: Area-IDE, Bug, IDE-IntelliSense

#38027 updating debugger implementation SDK
  eng/Versions.props
Labels: Area-Infrastructure

#37985 VB DIM work
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEMethodSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/ImplementsHelper.vb
  src/Compilers/VisualBasic/Portable/Symbols/SymbolExtensions.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/DefaultInterfaceImplementationTests.vb
Labels: Area-Compilers, Language-VB, New Language Feature - Default Interface Impl

#38046 VSSDK update
  eng/Versions.props
  src/EditorFeatures/CSharp.Wpf/Microsoft.CodeAnalysis.CSharp.EditorFeatures.Wpf.csproj
  src/EditorFeatures/CSharp/Microsoft.CodeAnalysis.CSharp.EditorFeatures.csproj
  src/EditorFeatures/CSharpTest/Microsoft.CodeAnalysis.CSharp.EditorFeatures.UnitTests.csproj
  src/EditorFeatures/CSharpTest2/Microsoft.CodeAnalysis.CSharp.EditorFeatures2.UnitTests.csproj
  src/EditorFeatures/Core.Wpf/Microsoft.CodeAnalysis.EditorFeatures.Wpf.csproj
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/EditorFeatures/Test/Microsoft.CodeAnalysis.EditorFeatures.UnitTests.csproj
  src/EditorFeatures/Test2/Microsoft.CodeAnalysis.EditorFeatures2.UnitTests.vbproj
  src/EditorFeatures/TestUtilities/Roslyn.Services.Test.Utilities.csproj
  src/EditorFeatures/TestUtilities2/Microsoft.CodeAnalysis.EditorFeatures.Test.Utilities.vbproj
  src/EditorFeatures/Text/Microsoft.CodeAnalysis.EditorFeatures.Text.csproj
  src/EditorFeatures/VisualBasic/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.vbproj
  src/EditorFeatures/VisualBasicTest/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.UnitTests.vbproj
  src/Features/LanguageServer/Protocol/Microsoft.CodeAnalysis.LanguageServer.Protocol.csproj
  src/Setup/DevDivInsertionFiles/DevDivInsertionFiles.csproj
  src/Test/Diagnostics/Roslyn.Hosting.Diagnostics.csproj
  src/Tools/ExternalAccess/FSharp/Microsoft.CodeAnalysis.ExternalAccess.FSharp.csproj
  src/Tools/ExternalAccess/FSharpTest/Microsoft.CodeAnalysis.ExternalAccess.FSharp.UnitTests.csproj
  src/Tools/ExternalAccess/LiveShare/Microsoft.CodeAnalysis.ExternalAccess.LiveShare.csproj
  src/Tools/ExternalAccess/Xamarin.Remote/Microsoft.CodeAnalysis.ExternalAccess.Xamarin.Remote.csproj
  src/VisualStudio/CSharp/Impl/Microsoft.VisualStudio.LanguageServices.CSharp.csproj
  src/VisualStudio/CSharp/Test/Microsoft.VisualStudio.LanguageServices.CSharp.UnitTests.csproj
  src/VisualStudio/CodeLens/Microsoft.VisualStudio.LanguageServices.CodeLens.csproj
  src/VisualStudio/Core/Impl/Microsoft.VisualStudio.LanguageServices.Implementation.csproj
  src/VisualStudio/Core/SolutionExplorerShim/Microsoft.VisualStudio.LanguageServices.SolutionExplorer.csproj
  src/VisualStudio/Core/Test.Next/Roslyn.VisualStudio.Next.UnitTests.csproj
  src/VisualStudio/Core/Test/Microsoft.VisualStudio.LanguageServices.UnitTests.vbproj
  src/VisualStudio/IntegrationTest/TestSetup/Microsoft.VisualStudio.IntegrationTest.Setup.csproj
  src/VisualStudio/IntegrationTest/TestUtilities/Microsoft.VisualStudio.IntegrationTest.Utilities.csproj
  src/VisualStudio/LiveShare/Impl/Microsoft.VisualStudio.LanguageServices.LiveShare.csproj
  src/VisualStudio/RemoteHostClientMock/Roslyn.VisualStudio.RemoteHostClientMock.csproj
  src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj
  src/VisualStudio/TestUtilities2/Microsoft.VisualStudio.LanguageServices.Test.Utilities2.vbproj
  src/VisualStudio/VisualBasic/Impl/Microsoft.VisualStudio.LanguageServices.VisualBasic.vbproj
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/Roslyn.VisualStudio.DiagnosticsWindow.csproj
  src/VisualStudio/Xaml/Impl/Microsoft.VisualStudio.LanguageServices.Xaml.csproj
Labels: Area-Infrastructure

#38024 Bump the Roslyn package version to 3.3.1
  eng/Versions.props
Labels: Area-Infrastructure

#37964 Ensure that OriginalXSymbols are copied over when enabling nullability.
  src/Compilers/CSharp/Portable/Binder/Binder_Query.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodeExtensions.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/BoundTree/BoundQueryClause.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundTreeRewriter.cs
  src/Compilers/CSharp/Portable/BoundTree/Constructors.cs
  src/Compilers/CSharp/Portable/BoundTree/NullabilityRewriter.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/NullablePublicAPITests.cs
Labels: Approved to merge, Area-Compilers, New Language Feature - Nullable Semantic Model, ask-mode

#38049 Revert "Adding Null Checks For All Parameters"
  src/EditorFeatures/CSharpTest/InitializeParameter/AddParameterCheckTests.cs
  src/EditorFeatures/VisualBasicTest/InitializeParameter/AddParameterCheckTests.vb
  src/Features/Core/Portable/FeaturesResources.Designer.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/InitializeParameter/AbstractAddParameterCheckCodeRefactoringProvider.cs
  src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs
  src/Features/Core/Portable/InitializeParameter/AbstractInitializeParameterCodeRefactoringProvider.cs
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
Labels: Area-IDE

#37711 Permit stackalloc to be used in an async method as long as it need not be spilled.
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Await.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_NullCoalescingAssignmentOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StackAlloc.cs
  src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs
  src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/StateMachineRewriter.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncLocalsTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncSpillTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/LocalSlotMappingTests.cs
  src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs
Labels: Area-Compilers

#37948 Bail out from emit in presence of warnings reported as errors
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs
  src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs
  src/Compilers/Core/Portable/Compilation/Compilation.cs
  src/Compilers/Core/Portable/Diagnostic/Diagnostic.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs
  src/Compilers/VisualBasic/Test/CommandLine/CommandLineTests.vb
Labels: Approved to merge, Area-Analyzers, Area-Compilers, ask-mode

#36878 Add tests for C# simplification around NRT
  src/EditorFeatures/Test2/Simplification/AbstractSimplificationTests.vb
  src/EditorFeatures/Test2/Simplification/CastSimplificationTests.vb
Labels: Area-IDE

#38008 Fix typo
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
Labels: Area-Compilers, Community, Concept-Continuous Improvement

#37397 Convert To Interpolated Strings refactoring provider should treat cha…
  src/EditorFeatures/CSharpTest/ConvertToInterpolatedString/ConvertConcatenationToInterpolatedStringTests.cs
  src/EditorFeatures/VisualBasicTest/ConvertToInterpolatedString/ConvertConcatenationToInterpolatedStringTests.vb
  src/Features/CSharp/Portable/ConvertToInterpolatedString/CSharpConvertConcatenationToInterpolatedStringRefactoringProvider.cs
  src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.cs
  src/Features/VisualBasic/Portable/ConvertToInterpolatedString/VisualBasicConvertConcatenationToInterpolatedStringRefactoringProvider.vb
  src/Workspaces/CSharp/Portable/LanguageServices/CSharpSyntaxFactsService.cs
  src/Workspaces/Core/Portable/LanguageServices/SyntaxFactsService/ISyntaxFactsService.cs
  src/Workspaces/VisualBasic/Portable/LanguageServices/VisualBasicSyntaxFactsService.vb
Labels: Area-IDE, Community

#38025 Move to a new Windows pool
  azure-pipelines.yml
Labels: Area-Infrastructure

#38056 Add generation for all IOperation nodes
  src/Compilers/CSharp/Portable/CSharpExtensions.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationNodes.cs
  src/Compilers/Core/CodeAnalysisTest/Diagnostics/OperationTests.cs
  src/Compilers/Core/Portable/Generated/Operations.Generated.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/Operations/Operation.cs
  src/Compilers/Core/Portable/Operations/OperationCloner.cs
  src/Compilers/Core/Portable/Operations/OperationInterfaces.xml
  src/Compilers/Core/Portable/Operations/OperationNodes.cs
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationNodes.vb
  src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb
  src/Test/Utilities/Portable/Compilation/OperationTreeVerifier.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/IOperationClassWriter.Verifier.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/IOperationClassWriter.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/Model.cs
Labels: Area-Compilers, New Feature - IOperation

#38103 VB: Support protected access for interface members.
  src/Compilers/Test/Utilities/VisualBasic/MockSymbols.vb
  src/Compilers/VisualBasic/Portable/Binding/BackstopBinder.vb
  src/Compilers/VisualBasic/Portable/Binding/BasesBeingResolvedBinder.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder.vb
  src/Compilers/VisualBasic/Portable/Binding/BinderFactory.BinderFactoryVisitor.vb
  src/Compilers/VisualBasic/Portable/Binding/BinderFactory.NodeUsage.vb
  src/Compilers/VisualBasic/Portable/Binding/BinderFactory.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Lookup.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Symbols.vb
  src/Compilers/VisualBasic/Portable/Binding/IgnoreAccessibilityBinder.vb
  src/Compilers/VisualBasic/Portable/Binding/NamedTypeBinder.vb
  src/Compilers/VisualBasic/Portable/Binding/SourceModuleBinder.vb
  src/Compilers/VisualBasic/Portable/Lowering/LambdaRewriter/LambdaFrame.vb
  src/Compilers/VisualBasic/Portable/Lowering/StateMachineRewriter/SynthesizedContainer.vb
  src/Compilers/VisualBasic/Portable/Semantics/AccessCheck.vb
  src/Compilers/VisualBasic/Portable/Symbols/AnonymousTypes/PublicSymbols/AnonymousTypeOrDelegatePublicSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousTypeOrDelegateTemplateSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/BaseTypeAnalysis.vb
  src/Compilers/VisualBasic/Portable/Symbols/ErrorTypeSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/NamedTypeSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Retargeting/RetargetingNamedTypeSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/ImplicitNamedTypeSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceNamedTypeSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceNamedTypeSymbol_ComClass.vb
  src/Compilers/VisualBasic/Portable/Symbols/SubstitutedNamedType.vb
  src/Compilers/VisualBasic/Portable/Symbols/SynthesizedSymbols/SynthesizedEventDelegateSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Tuples/TupleTypeSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/TypeSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/UnboundGenericType.vb
  src/Compilers/VisualBasic/Test/Semantic/Semantics/AccessCheckTests.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/DefaultInterfaceImplementationTests.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/ImplementsTests.vb
  src/ExpressionEvaluator/VisualBasic/Source/ExpressionCompiler/Symbols/EENamedTypeSymbol.vb
Labels: Area-Compilers, Language-VB, New Language Feature - Default Interface Impl

#38126 Update override completion for nullable reference support
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/LoadDirectiveCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/OverrideCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ReferenceDirectiveCompletionProviderTests.cs
  src/EditorFeatures/TestUtilities/Completion/AbstractCompletionProviderTests.cs
  src/Features/Core/Portable/Completion/Providers/AbstractOverrideCompletionProvider.ItemGetter.cs
  src/Features/Core/Portable/Completion/Providers/AbstractOverrideCompletionProvider.cs
  src/Workspaces/Core/Portable/CodeGeneration/CodeGenerationSymbolFactory.cs
Labels: Area-IDE

#37969 Don't offer to change the set if the parameter nullability is different
  src/EditorFeatures/CSharpTest/CodeActions/ReplaceMethodWithProperty/ReplaceMethodWithPropertyTests.cs
  src/Features/Core/Portable/ReplaceMethodWithProperty/ReplaceMethodWithPropertyCodeRefactoringProvider.cs
Labels: Area-IDE

#38135 Give LangVersion error when type is generic due to parent type
  src/Compilers/CSharp/Portable/Symbols/BaseTypeAnalysis.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/GenericConstraintsTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/UnsafeTests.cs
Labels: Area-Compilers, Bug, Tenet-Compatibility

#38141 Fix indenting
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#38151 Disabling Mono leg
  azure-pipelines.yml
Labels: Area-Infrastructure

#38150 Disabling Mono leg
  azure-pipelines.yml
Labels: Area-Infrastructure, Auto-Merge If Tests Pass, auto-merge

#38144 Remove RuntimeIdentifiers
  eng/targets/Settings.props
  src/Compilers/CSharp/Test/Emit/Microsoft.CodeAnalysis.CSharp.Emit.UnitTests.csproj
  src/Compilers/CSharp/Test/IOperation/Microsoft.CodeAnalysis.CSharp.IOperation.UnitTests.csproj
  src/Compilers/CSharp/Test/Semantic/Microsoft.CodeAnalysis.CSharp.Semantic.UnitTests.csproj
  src/Compilers/CSharp/csc/csc.csproj
  src/Compilers/Core/CodeAnalysisTest/Microsoft.CodeAnalysis.UnitTests.csproj
  src/Compilers/Server/VBCSCompiler/VBCSCompiler.csproj
  src/Compilers/Server/VBCSCompilerTests/VBCSCompiler.UnitTests.csproj
  src/Compilers/VisualBasic/vbc/vbc.csproj
  src/Interactive/csi/csi.csproj
  src/Interactive/vbi/vbi.vbproj
  src/Tools/Source/CompilerGeneratorTools/Source/BoundTreeGenerator/CompilersBoundTreeGenerator.csproj
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpErrorFactsGenerator/CSharpErrorFactsGenerator.csproj
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/CSharpSyntaxGenerator.csproj
  src/Tools/Source/CompilerGeneratorTools/Source/VisualBasicErrorFactsGenerator/VisualBasicErrorFactsGenerator.vbproj
  src/Tools/Source/CompilerGeneratorTools/Source/VisualBasicSyntaxGenerator/VisualBasicSyntaxGenerator.vbproj
Labels: Area-Infrastructure

#38128 Fix generated Equals(object) parameter nullability mismatch
  src/EditorFeatures/CSharpTest/GenerateFromMembers/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersTests.cs
  src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions_CreateEqualsMethod.cs
Labels: Area-IDE, Community

#37818 Handle hoisted temporary variables of the switch expression pattern-matching machinery.
  src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/IteratorAndAsyncCaptureWalker.cs
  src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/MethodToStateMachineRewriter.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncSpillTests.cs
Labels: Area-Compilers, Bug

#38094 Revert test workarounds/skip for IDE diagnostic configuration code fixes
  src/EditorFeatures/CSharpTest/Diagnostics/Configuration/ConfigureCodeStyle/BooleanCodeStyleOptionConfigurationTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/Configuration/ConfigureCodeStyle/EnumCodeStyleOptionConfigurationTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/Configuration/ConfigureCodeStyle/MultipleCodeStyleOptionConfigurationTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/Configuration/ConfigureSeverity/CodeStyleOptionBasedSeverityConfigurationTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/Configuration/ConfigureSeverity/DotNetDiagnosticSeverityBasedSeverityConfigurationTests.cs
  src/EditorFeatures/VisualBasicTest/Diagnostics/Configuration/ConfigureCodeStyle/BooleanCodeStyleOptionConfigurationTests.vb
  src/EditorFeatures/VisualBasicTest/Diagnostics/Configuration/ConfigureSeverity/CodeStyleOptionBasedSeverityConfigurationTests.vb
  src/EditorFeatures/VisualBasicTest/Diagnostics/Configuration/ConfigureSeverity/DotNetDiagnosticSeverityBasedSeverityConfigurationTests.vb
  src/Features/Core/Portable/CodeFixes/Configuration/ConfigureCodeStyle/ConfigureCodeStyleOptionCodeFixProvider.cs
  src/Features/Core/Portable/CodeFixes/Configuration/ConfigureSeverity/ConfigureSeverityLevelCodeFixProvider.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpCodeActions.cs
Labels: Area-IDE

#38136 Do not fade code for IDE0016 (UseThrowExpressionDiagnosticId)
  src/EditorFeatures/CSharpTest/UseThrowExpression/UseThrowExpressionTests.cs
  src/EditorFeatures/CSharpTest/UseThrowExpression/UseThrowExpressionTests_FixAllTests.cs
  src/Features/Core/Portable/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs
Labels: Area-IDE

#38152 Include nullability in symbol comparison for if SymbolsAreCompatibleCore
  src/EditorFeatures/CSharpTest/SimplifyTypeNames/SimplifyTypeNamesTests.cs
  src/Workspaces/Core/Portable/Utilities/AbstractSpeculationAnalyzer.cs
Labels: Area-IDE

#37884 Move some ComputeRefactoringsAsync to common helpers 6/n
  src/EditorFeatures/CSharpTest/CodeActions/IntroduceVariable/IntroduceVariableTests.cs
  src/EditorFeatures/CSharpTest/ConvertToInterpolatedString/ConvertConcatenationToInterpolatedStringTests.cs
  src/EditorFeatures/CSharpTest/ConvertToInterpolatedString/ConvertPlaceholderToInterpolatedStringTests.cs
  src/EditorFeatures/CSharpTest/InvertConditional/InvertConditionalTests.cs
  src/EditorFeatures/CSharpTest/InvertLogical/InvertLogicalTests.cs
  src/EditorFeatures/CSharpTest/RefactoringHelpers/RefactoringHelpersTests.cs
  src/EditorFeatures/VisualBasicTest/CodeActions/IntroduceVariable/IntroduceVariableTests.vb
  src/EditorFeatures/VisualBasicTest/ConvertToInterpolatedString/ConvertConcatenationToInterpolatedStringTests.vb
  src/Features/CSharp/Portable/CodeRefactorings/CSharpRefactoringHelpersService.cs
  src/Features/CSharp/Portable/CodeRefactorings/InlineTemporary/InlineTemporaryCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/ConvertToInterpolatedString/CSharpConvertConcatenationToInterpolatedStringRefactoringProvider.cs
  src/Features/CSharp/Portable/ConvertToInterpolatedString/CSharpConvertPlaceholderToInterpolatedStringRefactoringProvider.cs
  src/Features/CSharp/Portable/InvertConditional/CSharpInvertConditionalCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/UseExpressionBodyForLambda/UseExpressionBodyForLambdaCodeStyleProvider_Refactoring.cs
  src/Features/Core/Portable/CodeRefactoringHelpers.cs
  src/Features/Core/Portable/CodeRefactorings/AbstractRefactoringHelpersService.cs
  src/Features/Core/Portable/ConvertLinq/ConvertForEachToLinqQuery/AbstractConvertForEachToLinqQueryProvider.cs
  src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.cs
  src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs
  src/Features/Core/Portable/ConvertTupleToStruct/AbstractConvertTupleToStructCodeRefactoringProvider.cs
  src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.State.cs
  src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.cs
  src/Features/Core/Portable/InvertConditional/AbstractInvertConditionalCodeRefactoringProvider.cs
  src/Features/Core/Portable/InvertIf/AbstractInvertIfCodeRefactoringProvider.cs
  src/Features/Core/Portable/InvertLogical/AbstractInvertLogicalCodeRefactoringProvider.cs
  src/Features/Core/Portable/MoveDeclarationNearReference/AbstractMoveDeclarationNearReferenceCodeRefactoringProvider.cs
  src/Features/Core/Portable/PullMemberUp/AbstractPullMemberUpRefactoringProvider.cs
  src/Features/Core/Portable/ReplaceMethodWithProperty/ReplaceMethodWithPropertyCodeRefactoringProvider.cs
  src/Features/VisualBasic/Portable/CodeRefactorings/InlineTemporary/InlineTemporaryCodeRefactoringProvider.vb
  src/Features/VisualBasic/Portable/CodeRefactorings/VisualBasicRefactoringHelpersService.vb
  src/Features/VisualBasic/Portable/ConvertToInterpolatedString/VisualBasicConvertConcatenationToInterpolatedStringRefactoringProvider.vb
  src/Features/VisualBasic/Portable/ConvertToInterpolatedString/VisualBasicConvertPlaceholderToInterpolatedStringRefactoringProvider.vb
  src/Features/VisualBasic/Portable/InvertConditional/VisualBasicInvertConditionalCodeRefactoringProvider.vb
Labels: Area-IDE

#38140 Prevent embedding of non-abstract interface members.
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Emitter/NoPia/EmbeddedTypesManager.cs
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/Compilers/VisualBasic/Portable/Emit/NoPia/EmbeddedTypesManager.vb
  src/Compilers/VisualBasic/Portable/Errors/Errors.vb
  src/Compilers/VisualBasic/Portable/VBResources.Designer.vb
  src/Compilers/VisualBasic/Portable/VBResources.resx
  src/Compilers/VisualBasic/Portable/xlf/VBResources.cs.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.de.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.es.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.fr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.it.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ja.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ko.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pl.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pt-BR.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ru.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.tr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hans.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hant.xlf
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/DefaultInterfaceImplementationTests.vb
Labels: Area-Compilers, Language-C#, Language-VB, New Language Feature - Default Interface Impl

#38038 Remove inaccessible attributes when generating code
  src/EditorFeatures/CSharpTest/Diagnostics/UpdateProjectToAllowUnsafe/UpdateProjectToAllowUnsafeTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/UpgradeProject/UpgradeProjectTests.cs
  src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs
  src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests_InternalsVisibleTo.vb
  src/EditorFeatures/TestUtilities/CodeActions/AbstractCodeActionOrUserDiagnosticTest.cs
  src/EditorFeatures/TestUtilities/CodeActions/AbstractCodeActionTest.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace_XmlConsumption.cs
  src/EditorFeatures/VisualBasic/NavigationBar/GenerateEventHandlerItem.vb
  src/EditorFeatures/VisualBasic/NavigationBar/GenerateMethodItem.vb
  src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction_Property.cs
  src/VisualStudio/CSharp/Impl/EventHookup/EventHookupCommandHandler_TabKeyCommand.cs
  src/VisualStudio/CSharp/Test/EventHookup/EventHookupCommandHandlerTests.cs
  src/Workspaces/Core/Portable/CodeGeneration/CodeGenerationSymbolFactory.cs
  src/Workspaces/Core/Portable/Shared/Extensions/IMethodSymbolExtensions.cs
  src/Workspaces/Core/Portable/Shared/Extensions/IParameterSymbolExtensions.cs
  src/Workspaces/Core/Portable/Shared/Extensions/IPropertySymbolExtensions.cs
  src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions.cs
Labels: Area-IDE

#37898 Fixed parsing of generic types in property patterns
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs
Labels: Area-Compilers, Community

#38146 Enable a deconstruction test
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests_Global.cs
Labels: Area-Compilers, New Language Feature - Tuples, Test

#38148 Fix check of BinaryOperatorKind
  src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs
Labels: Area-Compilers

#38045 Handle escaping of ref/out parameters on non-regular CFG exit paths (…
  src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedValueAssignmentTests.cs
  src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs
  src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.DataFlowAnalyzer.FlowGraphAnalysisData.cs
  src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.DataFlowAnalyzer.cs
Labels: Area-IDE

#38185 Remove the 7.3 languageversion from the BindSymbolInOtherFile test
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
Labels: Area-IDE

#37851 Add nullability information to extract method
  src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractMethodTests.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.Analyzer.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.ExpressionResult.cs
  src/Features/Core/Portable/ExtractMethod/Extensions.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.VariableInfo.cs
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.vb
Labels: Area-IDE

#38101 Fix ChangeNamespaceService to handle member access references
  src/EditorFeatures/CSharpTest/CodeActions/SyncNamespace/SyncNamespaceTests_ChangeNamespace.cs
  src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs
  src/Features/Core/Portable/CodeRefactorings/SyncNamespace/AbstractChangeNamespaceService.cs
  src/Features/VisualBasic/Portable/CodeRefactorings/SyncNamespace/VisualBasicChangeNamespaceService.vb
Labels: Area-IDE

#38184 Change unused parameters analyzer configuration to analyze generated …
  src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedParametersTests.cs
  src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs
Labels: Area-IDE

#38199 Skip flaky integration test
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpCodeActions.cs
Labels: Area-Infrastructure, Integration-Test

#38110 Bail out from couple of IDE analyzers in presence of OperationKind.None operations
  src/EditorFeatures/VisualBasicTest/RemoveUnusedMembers/RemoveUnusedMembersTests.vb
  src/EditorFeatures/VisualBasicTest/RemoveUnusedParametersAndValues/RemoveUnusedParametersTests.vb
  src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs
  src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs
Labels: Area-IDE

#37968 Add a tool which generates a reasonable VB grammar facsimile from our syntactic model.
  src/Compilers/VisualBasic/Portable/Declarations/DeclarationModifiers.vb
  src/Compilers/VisualBasic/Portable/Declarations/DeclarationModifiersExtensions.vb
  src/Compilers/VisualBasic/Portable/Generated/VisualBasic.Grammar.g4
  src/Compilers/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.vbproj
  src/Compilers/VisualBasic/Portable/Syntax/Syntax.xml
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/Model/Node.cs
  src/Tools/Source/CompilerGeneratorTools/Source/VisualBasicSyntaxGenerator/Grammar/GrammarGenerator.vb
  src/Tools/Source/CompilerGeneratorTools/Source/VisualBasicSyntaxGenerator/Program.vb
  src/Tools/Source/CompilerGeneratorTools/Source/VisualBasicSyntaxGenerator/VisualBasicSyntaxGenerator.vbproj
  src/Tools/Source/CompilerGeneratorTools/Source/VisualBasicSyntaxGenerator/XML/ParseTreeDescription.vb
Labels: Area-Compilers, Community

#38117 Fix completion of local functions in static methods
  src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs
  src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
Labels: Area-Compilers, Area-IDE, IDE-IntelliSense

#38176 VB: Add tests for consuming operators defined within interfaces.
  src/Compilers/VisualBasic/Portable/Binding/BasesBeingResolvedBinder.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/DefaultInterfaceImplementationTests.vb
Labels: Area-Compilers, Language-VB, New Language Feature - Default Interface Impl

#38177 Prevent static local functions from capturing local functions
  docs/compilers/CSharp/Compiler Breaking Changes - post VS2019.md
  src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs
  src/Compilers/CSharp/Portable/Symbols/Symbol.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
Labels: Area-Compilers, Bug, Tenet-Compatibility

#38214 VB: Adjust merging of lookup result for inaccessible members of different kind, prefer more accessible candidate.
  src/Compilers/Core/Portable/Collections/ArrayBuilderExtensions.cs
  src/Compilers/VisualBasic/Portable/Binding/LookupResult.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/DefaultInterfaceImplementationTests.vb
Labels: Area-Compilers, Language-VB, New Language Feature - Default Interface Impl

#37412 Fix Build badges:
  README.md
  scripts/generate-badges.ps1
Labels: Area-Infrastructure, Documentation

#38154 Adjust sequence point on await foreach and using declaration
  src/Compilers/CSharp/Portable/Lowering/Instrumentation/DebugInfoInjector.cs
  src/Compilers/CSharp/Portable/Lowering/Instrumentation/DebugInfoInjector_SequencePoints.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAwaitForeachTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAwaitUsingTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenUsingDeclarationTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenUsingStatementTests.cs
  src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs
Labels: Area-Compilers, New Feature - Async Streams, New Language Feature - enhanced using

#38175 Revert "Revert "Adding Null Checks For All Parameters""
  src/EditorFeatures/CSharpTest/InitializeParameter/AddParameterCheckTests.cs
  src/EditorFeatures/VisualBasicTest/InitializeParameter/AddParameterCheckTests.vb
  src/Features/Core/Portable/FeaturesResources.Designer.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/InitializeParameter/AbstractAddParameterCheckCodeRefactoringProvider.cs
  src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs
  src/Features/Core/Portable/InitializeParameter/AbstractInitializeParameterCodeRefactoringProvider.cs
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
Labels: Area-IDE

#38202 Add release/dev16.3-vs-deps to publishing
  eng/config/PublishData.json
Labels: auto-merge

#38246 Re-add master-vs-deps to the publish branch list
  eng/config/PublishData.json
Labels: Area-Infrastructure, auto-merge

#37963 Fix IOperation for asynchronous using and foreach statements
  src/Compilers/CSharp/Portable/Binder/ForEachEnumeratorInfo.cs
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/Compilation/ForEachStatementInfo.cs
  src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationNodes.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAwaitForeachTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IForEachLoopStatement.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IUsingStatement.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/ForEachTests.cs
  src/Compilers/CSharp/Test/Symbol/Compilation/ForEachStatementInfoTests.cs
  src/Compilers/Core/Portable/Compilation/Compilation.cs
  src/Compilers/Core/Portable/Generated/Operations.Generated.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/Operations/Loops/ForEachLoopOperationInfo.cs
  src/Compilers/Core/Portable/Operations/OperationCloner.cs
  src/Compilers/Core/Portable/Operations/OperationInterfaces.xml
  src/Compilers/Core/Portable/Operations/OperationNodes.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationNodes.vb
  src/Compilers/VisualBasic/Portable/Symbols/WellKnownMembers.vb
  src/Test/Utilities/Portable/Compilation/OperationTreeVerifier.cs
Labels: Area-Compilers, New Feature - Async Streams

#38222 Minor change to address previous PR comments
  src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs
Labels: Area-IDE

#38000 Writing code to call a function using identifiers that don’t exist yet
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Features/CSharp/Portable/Completion/CompletionProviders/NamedParameterCompletionProvider.cs
Labels: Area-IDE, IDE-IntelliSense, Regression

#38021 Completion Tests: Remove WaitForAsynchronousOperationsAsync from explicit calls in tests
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_InternalsVisibleTo.vb
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_Projections.vb
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_Regex.vb
  src/EditorFeatures/Test2/IntelliSense/CSharpIntelliSenseCommandHandlerTests.vb
  src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests.vb
  src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests_InternalsVisibleTo.vb
  src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests_Projections.vb
  src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests_Regex.vb
  src/EditorFeatures/Test2/IntelliSense/VisualBasicSignatureHelpCommandHandlerTests.vb
  src/EditorFeatures/TestUtilities/AbstractCommandHandlerTestState.cs
  src/EditorFeatures/TestUtilities2/Intellisense/LegacyTestState.vb
  src/EditorFeatures/TestUtilities2/Intellisense/ModernCompletionTestState.vb
  src/EditorFeatures/TestUtilities2/Intellisense/TestStateBase.vb
Labels: Area-IDE, Concept-Continuous Improvement, IDE-IntelliSense, Test

#38109 Restore constraint checking for reduced extension methods.
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs
  src/Compilers/CSharp/Portable/Symbols/BaseTypeAnalysis.cs
  src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs
  src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/ReducedExtensionMethodSymbol.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs
  src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs
  src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/ExtensionMethodTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Retargeting/RetargetingTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
Labels: Approved to merge, Area-Compilers, ask-mode

#38251 Allow static local functions to convert static functions to delegates
  docs/compilers/CSharp/Compiler Breaking Changes - post VS2019.md
  src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs
Labels: Area-Compilers

#38328 Show error every time CallHierarchyView doesn't a find suitable node.
  src/VisualStudio/Core/Def/Implementation/CallHierarchy/CallHierarchyCommandHandler.cs
  src/VisualStudio/Core/Test/CallHierarchy/CallHierarchyTests.vb
Labels: Area-IDE

#38225 Wire-up to text buffers even if there is no RDT DocDataReloaded
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/RunningDocumentTableEventTracker.cs
Labels: Approved to merge, Area-IDE

#38220 Do not report an NFW for analyzer exception diagnostic in IDE
  src/Features/Core/Portable/Diagnostics/AnalyzerHelper.cs
Labels: Approved to merge, Area-Analyzers, Area-IDE, Tenet-Performance
