Repository dotnet/roslyn, pull requests merged in 2019-02, with the labels that each got.

#32952 Avoid unnecessary thread-local variables
  src/Workspaces/Core/Portable/Formatting/Engine/AbstractFormatEngine.cs
Labels: Approved to merge, Area-IDE, IDE-Formatter

#32993 async completion. check if need to support the original completion co…
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
Labels: Approved to merge, Area-IDE

#32941 Add feature to make applicable local functions static.
  src/EditorFeatures/CSharpTest/MakeLocalFunctionStatic/MakeLocalFunctionStaticTests.cs
  src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs
  src/Features/CSharp/Portable/MakeLocalFunctionStatic/MakeLocalFunctionStaticCodeFixProvider.cs
  src/Features/CSharp/Portable/MakeLocalFunctionStatic/MakeLocalFunctionStaticDiagnosticAnalyzer.cs
  src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs
  src/Features/Core/Portable/Diagnostics/Analyzers/IDEDiagnosticIds.cs
  src/Features/Core/Portable/FeaturesResources.Designer.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Test/Utilities/Portable/Traits/Traits.cs
  src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs
  src/VisualStudio/Core/Def/ServicesVSResources.Designer.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/Core/Test/Options/CSharpEditorConfigGeneratorTests.vb
  src/VisualStudio/VisualBasic/Impl/Options/StyleViewModel.vb
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/CSharp/Portable/CodeStyle/CSharpCodeStyleOptions.cs
  src/Workspaces/CSharp/Portable/Execution/CSharpOptionsSerializationService.cs
Labels: Area-IDE, Community, Feature Request

#32947 No nullability warnings in best type and type inference
  docs/features/nullable-reference-types.md
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/BestTypeInferrer.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Portable/Binder/SwitchExpressionBinder.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundExpressionWithNullability.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Generated/ErrorFacts.Generated.cs
  src/Compilers/CSharp/Portable/Symbols/ArrayTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/DynamicTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PointerTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
  src/Tools/Source/CompilerGeneratorTools/Source/BoundTreeGenerator/BoundNodeClassWriter.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#33015 Re-enable csharp symbol tests on mono
  src/Compilers/CSharp/Test/Symbol/Microsoft.CodeAnalysis.CSharp.Symbol.UnitTests.csproj
Labels: Area-Compilers

#33026 LOC CHECKIN | dotnet/roslyn dev16.0-preview3 | 20190131 2
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.cs.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.de.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.es.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.fr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.it.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ja.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ko.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pl.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pt-BR.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ru.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.tr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hans.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hant.xlf
Labels: Approved to merge

#32648 Issue 31304 Check variables in scope when getting name declaration suggestions
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs
  src/Workspaces/Core/Portable/LanguageServices/SemanticsFactsService/AbstractSemanticFactsService.cs
  src/Workspaces/Core/Portable/LanguageServices/SemanticsFactsService/ISemanticFactsService.cs
  src/Workspaces/VisualBasic/Portable/LanguageServices/VisualBasicSemanticFactsService.vb
Labels: Area-IDE

#32841 Updated version to 3.0.0 beta 4
  eng/Versions.props
Labels: Area-Infrastructure

#33013 Work around bug in NamedPipeClientStream.ConnectAsync
  src/Compilers/Shared/BuildServerConnection.cs
Labels: Approved to merge, Area-Compilers

#33042 Do not report unused expression value (IDE0058) for expression body
  src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedValueExpressionStatementTests.cs
  src/Features/CSharp/Portable/RemoveUnusedParametersAndValues/CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs
  src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs
  src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs
  src/Features/VisualBasic/Portable/RemoveUnusedParametersAndValues/VisualBasicRemoveUnusedParametersAndValuesDiagnosticAnalyzer.vb
Labels: Approved to merge, Area-IDE

#32816 If a solution is closed and reopened, still recreate a SolutionId
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectFactory.cs
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioProjectTests/MetadataToProjectReferenceConversionTests.vb
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioProjectTests/SolutionIdTests.vb
Labels: Area-IDE

#33051 Classify keywords in ForEachVariableStatements as ControlKeywords
  src/EditorFeatures/CSharpTest/Classification/SyntacticClassifierTests.cs
  src/Workspaces/CSharp/Portable/Classification/ClassificationHelpers.cs
Labels: Approved to merge, Area-IDE

#33050 don't retain fault result in task center if nuget info download failed.
  src/VisualStudio/Core/Def/Implementation/SymbolSearch/VisualStudioSymbolSearchService.ProgressService.cs
Labels: Approved to merge, Area-IDE

#33024 Updated NuGet package properties
  eng/targets/Settings.props
Labels: Area-Infrastructure

#32509 Disable ngen for System.Numerics.Vectors
  src/NuGet/Microsoft.Net.Compilers/CompilerArtifacts.targets
Labels: Area-Infrastructure

#32960 Default enhanced colors, remove bold statics, and remove experiment
  src/VisualStudio/Core/Def/Implementation/Experimentation/EnhancedColorExperiment.cs
Labels: Approved to merge, Area-IDE

#32374 Add IterationDataAttribute for easy test looping
  src/VisualStudio/IntegrationTest/TestUtilities/IterationDataAttribute.cs
Labels: Area-IDE, Integration-Test

#32930 Ensure we refresh the project output path when the obj path changes
  src/VisualStudio/CSharp/Impl/ProjectSystemShim/CSharpProjectShim.ICSInputSet.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/Legacy/AbstractLegacyProject.cs
  src/VisualStudio/VisualBasic/Impl/ProjectSystemShim/VisualBasicProject.vb
Labels: Approved to merge, Area-IDE

#33067 Handle null reference exception during analyzer execution when cancel…
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs
Labels: Approved to merge, Area-Analyzers, Area-Compilers

#33100 Support running integration tests in VS 2019
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/StartPage_InProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs
Labels: Area-IDE, Integration-Test

#33097 Delete EtwLoggingTests because the test is flawed
  src/Workspaces/CoreTest/UtilityTest/EtwLoggingTests.cs
Labels: Area-IDE, Test

#32630 Enable skipped tests that previously failed on AssertIsForeground
  src/EditorFeatures/Test/LinkedFiles/LinkedFileDiffMergingEditorTests.cs
  src/EditorFeatures/Test2/InteractivePaste/InteractivePasteCommandHandlerTests.vb
Labels: Test

#33053 Updated dotnet-format package description.
  src/Tools/dotnet-format/dotnet-format.csproj
Labels: Area-IDE, Area-Infrastructure

#33102 Bail out for error types from IDE0058 analyzer (unused expression value)
  src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedValueExpressionStatementTests.cs
  src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs
Labels: Approved to merge, Area-IDE

#33109 Disable parallel nuget restore on linux and mac
  eng/build.sh
Labels: Area-Infrastructure

#33104 Disable integration tests with <95% reliability
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicExtractMethod.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicNavigationBar.cs
Labels: Area-IDE, Integration-Test

#32978 Add feature to suggest using a 'simple using statement' when possible.
  src/Compilers/VisualBasic/Portable/OptionStrict.vb
  src/EditorFeatures/CSharpTest/MakeLocalFunctionStatic/MakeLocalFunctionStaticTests.cs
  src/EditorFeatures/CSharpTest/UseSimpleUsingStatement/UseSimpleUsingStatementTests.cs
  src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs
  src/Features/CSharp/Portable/UseSimpleUsingStatement/UseSimpleUsingStatementCodeFixProvider.cs
  src/Features/CSharp/Portable/UseSimpleUsingStatement/UseSimpleUsingStatementDiagnosticAnalyzer.cs
  src/Features/Core/Portable/Diagnostics/Analyzers/IDEDiagnosticIds.cs
  src/Features/Core/Portable/FeaturesResources.Designer.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Test/Utilities/Portable/Traits/Traits.cs
  src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs
  src/VisualStudio/Core/Def/ServicesVSResources.Designer.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/Core/Test/Options/CSharpEditorConfigGeneratorTests.vb
  src/Workspaces/CSharp/Portable/CodeStyle/CSharpCodeStyleOptions.cs
  src/Workspaces/CSharp/Portable/Extensions/SyntaxNodeExtensions_SharedWithCodeStyle.cs
Labels: Area-IDE, Community, Feature Request

#32353 Remove unnecessary test hooks
  src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialog.xaml.cs
  src/VisualStudio/Core/Def/Implementation/ExtractInterface/ExtractInterfaceDialog.xaml.cs
  src/VisualStudio/Core/Def/Implementation/GenerateType/GenerateTypeDialog.xaml.cs
  src/VisualStudio/Core/Def/Implementation/PickMembers/PickMembersDialog.xaml.cs
Labels: Approved to merge, Area-IDE, Concept-Continuous Improvement, Test

#30743 Implement 'Complete Statement' on semicolon
  src/EditorFeatures/CSharp/CSharpEditorResources.Designer.cs
  src/EditorFeatures/CSharp/CSharpEditorResources.resx
  src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.cs.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.de.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.es.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.fr.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.it.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.ja.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.ko.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.pl.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.pt-BR.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.ru.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.tr.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.zh-Hans.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.zh-Hant.xlf
  src/EditorFeatures/CSharpTest/CompleteStatement/CSharpCompleteStatementCommandHandlerTests.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/EditorFeatures/TestUtilities/CompleteStatement/AbstractCompleteStatementTests.cs
  src/EditorFeatures/TestUtilities2/Intellisense/TestState.vb
  src/Test/Utilities/Portable/Traits/Traits.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpAutomaticBraceCompletion.cs
Labels: Area-IDE, Feature Request

#33071 Allow ForEach to For when there are comments
  src/EditorFeatures/CSharpTest/ConvertForEachToFor/ConvertForEachToForTests.cs
  src/EditorFeatures/VisualBasicTest/ConvertForEachToFor/ConvertForEachToForTests.vb
  src/Features/CSharp/Portable/ConvertForEachToFor/CSharpConvertForEachToForCodeRefactoringProvider.cs
  src/Features/VisualBasic/Portable/ConvertForEachToFor/VisualBasicConvertForEachToForCodeRefactoringProvider.vb
Labels: Area-IDE

#33070 Polish on Pull Member Up UI
  src/Features/Core/Portable/PullMemberUp/MembersPuller.cs
  src/VisualStudio/Core/Def/Implementation/PullMemberUp/MainDialog/PullMemberUpDialog.xaml
  src/VisualStudio/Core/Def/Implementation/PullMemberUp/MainDialog/PullMemberUpDialogViewModel.cs
  src/VisualStudio/Core/Def/Implementation/PullMemberUp/WarningDialog/PullMemberUpWarningDialog.xaml
  src/VisualStudio/Core/Def/Implementation/PullMemberUp/WarningDialog/PullMemberUpWarningViewModel.cs
Labels: Area-IDE

#32990 Fix up support for changing rule set files through the Solution Explorer
  src/VisualStudio/CSharp/Test/ProjectSystemShim/CPS/AnalyzersTests.cs
  src/VisualStudio/CSharp/Test/ProjectSystemShim/LegacyProject/AnalyzersTests.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/AbstractProject.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/Legacy/AbstractLegacyProject.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectOptionsProcessor.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs
  src/VisualStudio/Core/SolutionExplorerShim/AnalyzersCommandHandler.cs
  src/VisualStudio/Core/SolutionExplorerShim/SolutionExplorerShim.Designer.cs
  src/VisualStudio/Core/SolutionExplorerShim/SolutionExplorerShim.resx
  src/VisualStudio/Core/SolutionExplorerShim/xlf/SolutionExplorerShim.cs.xlf
  src/VisualStudio/Core/SolutionExplorerShim/xlf/SolutionExplorerShim.de.xlf
  src/VisualStudio/Core/SolutionExplorerShim/xlf/SolutionExplorerShim.es.xlf
  src/VisualStudio/Core/SolutionExplorerShim/xlf/SolutionExplorerShim.fr.xlf
  src/VisualStudio/Core/SolutionExplorerShim/xlf/SolutionExplorerShim.it.xlf
  src/VisualStudio/Core/SolutionExplorerShim/xlf/SolutionExplorerShim.ja.xlf
  src/VisualStudio/Core/SolutionExplorerShim/xlf/SolutionExplorerShim.ko.xlf
  src/VisualStudio/Core/SolutionExplorerShim/xlf/SolutionExplorerShim.pl.xlf
  src/VisualStudio/Core/SolutionExplorerShim/xlf/SolutionExplorerShim.pt-BR.xlf
  src/VisualStudio/Core/SolutionExplorerShim/xlf/SolutionExplorerShim.ru.xlf
  src/VisualStudio/Core/SolutionExplorerShim/xlf/SolutionExplorerShim.tr.xlf
  src/VisualStudio/Core/SolutionExplorerShim/xlf/SolutionExplorerShim.zh-Hans.xlf
  src/VisualStudio/Core/SolutionExplorerShim/xlf/SolutionExplorerShim.zh-Hant.xlf
  src/VisualStudio/TestUtilities2/CodeModel/Mocks/MockVisualStudioWorkspace.vb
Labels: Approved to merge, Area-IDE

#27983 Promote experimental out-of-process features to stable
  src/EditorFeatures/CSharpTest/AddUsing/AddUsingTests.cs
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.vb
  src/EditorFeatures/Test2/ReferenceHighlighting/AbstractReferenceHighlightingTests.vb
  src/EditorFeatures/TestUtilities/NavigateTo/AbstractNavigateToTests.cs
  src/EditorFeatures/VisualBasicTest/Diagnostics/AddImport/AddImportTests.vb
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/ServicesVSResources.Designer.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageStrings.vb
  src/Workspaces/Core/Portable/Experiments/IExperimentationService.cs
  src/Workspaces/Core/Portable/Remote/RemoteFeatureOptions.cs
  src/Workspaces/Core/Portable/Remote/RemoteHostClientExtensions.cs
Labels: Area-IDE

#33106 Require dev16 for integration testing
  azure-pipelines-integration.yml
  global.json
  src/VisualStudio/IntegrationTest/TestUtilities/App.config
  src/VisualStudio/IntegrationTest/TestUtilities/Settings.Designer.cs
  src/VisualStudio/IntegrationTest/TestUtilities/Settings.settings
  src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs
Labels: Area-Infrastructure

#33114 Move MSBuild installation directory to Current
  src/Setup/DevDivVsix/CompilersPackage/Microsoft.CodeAnalysis.Compilers.Setup.csproj
  src/Setup/DevDivVsix/CompilersPackage/roslyn.bat
Labels: Area-Compilers, Area-Infrastructure

#33076 Handle ref variables similarly to non-ref variables
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#33147 Fix documentation tests
  src/Compilers/VisualBasic/Test/Symbol/DocumentationComments/DocCommentTests.vb
Labels: Area-Compilers

#32983 Reparse type after async
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
Labels: Area-Compilers

#33094 Do not offer to remove redundant assignment if it is not parented by …
  src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedValueAssignmentTests.cs
  src/Features/CSharp/Portable/RemoveUnusedParametersAndValues/CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs
  src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs
  src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs
Labels: Approved to merge, Area-IDE

#33149 Updated dotnet-format install instructions
  src/Tools/dotnet-format/README.md
Labels: Approved to merge, Area-IDE

#33132 Avoid a lambda allocation when accessing a cache in a hotpath.
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Metadata.cs
  src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs
Labels: Approved to merge, Area-IDE, Community

#33145 Use Visual Studio 2019 for integration testing
  azure-pipelines-integration.yml
  global.json
  src/VisualStudio/IntegrationTest/TestUtilities/App.config
  src/VisualStudio/IntegrationTest/TestUtilities/Settings.Designer.cs
  src/VisualStudio/IntegrationTest/TestUtilities/Settings.settings
  src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs
Labels: Area-Infrastructure

#33166 Disable Mono CI build
  azure-pipelines.yml
Labels: Area-Infrastructure, PR For Personal Review Only

#33121 Track nullability of static fields
  src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/EmptyStructTypeCache.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/LocalDataFlowPass.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
Labels: Area-Compilers

#33148 Intellisense cannot be shown when the caret is between two dots
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/SnippetCompletionProvider.cs
  src/Workspaces/CSharp/Portable/Extensions/ContextQuery/CSharpSyntaxContext.cs
  src/Workspaces/CSharp/Portable/Extensions/SyntaxTreeExtensions.cs
  src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationService.cs
Labels: Approved to merge, Area-IDE

#33151 Updated city name in test file
  src/EditorFeatures/CSharpTest/Diagnostics/UseImplicitOrExplicitType/UseExplicitTypeTests.cs
Labels: Approved to merge, Area-IDE

#33125 Treat normal using and static usings separately when adding imports.
  src/EditorFeatures/CSharpTest/AddUsing/AddUsingTests.cs
  src/Workspaces/CSharp/Portable/AddImports/CSharpAddImportsService.cs
  src/Workspaces/Core/Portable/AddImports/AbstractAddImportsService.cs
  src/Workspaces/VisualBasic/Portable/AddImports/VisualBasicAddImportsService.vb
Labels: Approved to merge, Area-IDE

#33089 Add Preview langversion and change Default
  src/Compilers/CSharp/Portable/Binder/Binder_Constraints.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/LazyMissingNonNullTypesContextDiagnosticInfo.cs
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/LanguageVersion.cs
  src/Compilers/CSharp/Portable/Parser/Lexer.cs
  src/Compilers/CSharp/Portable/Parser/SyntaxParser.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAwaitForeachTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAwaitUsingTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOperators.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/ForEachTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/IndexAndRangeTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests2.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/UsingDeclarationTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
  src/Compilers/CSharp/Test/Syntax/LexicalAndXml/PreprocessorTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/AsyncStreamsParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ExpressionParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/LanguageVersionTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/LocalFunctionParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs
  src/Compilers/Test/Utilities/CSharp/TestOptions.cs
  src/EditorFeatures/CSharpTest/CodeActions/InlineTemporary/InlineTemporaryTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/GenerateType/GenerateTypeTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/UpgradeProject/UpgradeProjectTests.cs
  src/EditorFeatures/CSharpTest/GenerateFromMembers/AddConstructorParametersFromMembers/AddConstructorParametersFromMembersTests.cs
  src/EditorFeatures/CSharpTest/GenerateVariable/GenerateVariableTests.cs
  src/EditorFeatures/CSharpTest/ImplementAbstractClass/ImplementAbstractClassTests.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Features/CSharp/Portable/UpgradeProject/CSharpUpgradeProjectCodeFixProvider.cs
  src/Features/Core/Portable/UpgradeProject/AbstractUpgradeProjectCodeFixProvider.cs
  src/VisualStudio/Core/Test/CodeModel/CSharp/CodeClassTests.vb
  src/Workspaces/MSBuildTest/MSBuildWorkspaceTests.cs
Labels: Area-Compilers

#32918 Make '^' operation nodes internal
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IBinaryOperatorExpression.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IFromEndIndexOperation_IRangeOperation.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IUnaryOperatorExpression.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/Operations/IIndexOperation.cs
  src/Compilers/Core/Portable/Operations/OperationCloner.cs
  src/Compilers/Core/Portable/Operations/OperationKind.cs
  src/Compilers/Core/Portable/Operations/OperationNodes.cs
  src/Compilers/Core/Portable/Operations/OperationVisitor.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Test/Utilities/Portable/Compilation/ControlFlowGraphVerifier.cs
  src/Test/Utilities/Portable/Compilation/OperationTreeVerifier.cs
  src/Test/Utilities/Portable/Compilation/TestOperationVisitor.cs
Labels: Area-Compilers

#32912 Classify constructor/destructor as containing type
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Members.cs
  src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs
  src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs
  src/EditorFeatures/CSharpTest/Classification/SyntacticClassifierTests.cs
  src/EditorFeatures/CSharpTest/Classification/TotalClassifierTests.cs
  src/EditorFeatures/CSharpTest/Classification/TotalClassifierTests_Dynamic.cs
  src/Workspaces/CSharp/Portable/Classification/ClassificationHelpers.cs
  src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.cs
Labels: Approved to merge, Area-Compilers, Area-IDE

#33133 Use Arcade VS IBC training infrastructure
  .gitignore
  azure-pipelines-official.yml
  eng/Tools.props
  eng/Versions.props
  eng/build-utils.ps1
  eng/build.ps1
  eng/common/PublishBuildAssets.cmd
  eng/common/PublishToPackageFeed.proj
  eng/common/build.ps1
  eng/common/darc-init.ps1
  eng/common/internal/Directory.Build.props
  eng/common/internal/Directory.Build.targets
  eng/common/internal/Tools.csproj
  eng/common/sdk-task.ps1
  eng/common/templates/job/publish-build-assets.yml
  eng/common/templates/phases/publish-build-assets.yml
  eng/common/templates/steps/send-to-helix.yml
  eng/common/templates/steps/telemetry-end.yml
  eng/common/templates/steps/telemetry-start.yml
  eng/common/tools.ps1
  eng/generate-optprof-run-settings.ps1
  eng/internal/Directory.Build.props
  eng/internal/Directory.Build.targets
  eng/publish-assets.ps1
  eng/test-build-correctness.ps1
  global.json
Labels: Area-Infrastructure

#33186 Enable preview version for certain target frameworks
  src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets
Labels: Area-Compilers

#32933 Ignore InvalidOperationException from GetInstalledPackages
  src/VisualStudio/Core/Def/Packaging/PackageInstallerServiceFactory.cs
Labels: Approved to merge, Area-IDE, Tenet-Performance

#33193 Re-enable mono CI build
  azure-pipelines.yml
Labels: Area-Infrastructure

#33188 Remove block comments first if selection exactly matches block. Reso…
  src/EditorFeatures/Core/Implementation/CommentSelection/CommentUncommentSelectionCommandHandler.cs
  src/EditorFeatures/Test/CommentSelection/CommentUncommentSelectionCommandHandlerTests.cs
Labels: Area-IDE

#33178 Make IPropertySubpattern Internal
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationNodes.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IIsPatternExpression.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/Operations/IPropertySubpatternOperation.cs
  src/Compilers/Core/Portable/Operations/IRecursivePatternOperation.cs
  src/Compilers/Core/Portable/Operations/InstanceReferenceKind.cs
  src/Compilers/Core/Portable/Operations/OperationCloner.cs
  src/Compilers/Core/Portable/Operations/OperationNodes.cs
  src/Compilers/Core/Portable/Operations/OperationVisitor.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Test/Utilities/Portable/Compilation/ControlFlowGraphVerifier.cs
  src/Test/Utilities/Portable/Compilation/OperationTreeVerifier.cs
  src/Test/Utilities/Portable/Compilation/TestOperationVisitor.cs
  src/Workspaces/Core/Portable/Extensions/OperationExtensions.cs
Labels: Area-Compilers, New Feature - Flow Analysis, New Feature - IOperation

#33181 removed 3 OptProf tests that kept failing
  eng/config/OptProf.json
Labels: Area-Infrastructure

#33075 Improve method that finds an expression's parent lambda to introduce a local into
  src/EditorFeatures/CSharpTest/CodeActions/IntroduceVariable/IntroduceVariableTests.cs
  src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs
Labels: Area-IDE, Community

#26049 Debugger EE 'Internal error' if DebuggerBrowsable when 'newslot' C# property overrides field
  src/ExpressionEvaluator/CSharp/Test/ResultProvider/DebuggerBrowsableAttributeTests.cs
  src/ExpressionEvaluator/Core/Source/ResultProvider/Helpers/TypeHelpers.cs
  src/ExpressionEvaluator/Core/Test/ResultProvider/Debugger/Engine/DkmClrType.cs
Labels: Area-Interactive, Interactive-Debugging

#33048 Disable nullable analysis for generated files
  src/Compilers/CSharp/Portable/Syntax/CSharpPragmaWarningStateMap.cs
  src/Compilers/CSharp/Portable/Syntax/CSharpSyntaxTree.cs
  src/Compilers/CSharp/Portable/Syntax/NullableDirectiveMap.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
  src/Compilers/Core/Portable/Syntax/AbstractWarningStateMap.cs
  src/Compilers/VisualBasic/Portable/Syntax/VisualBasicWarningStateMap.vb
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#33029 Issue 32399 Fix removable cast suggestion on GetType in VB
  src/EditorFeatures/VisualBasicTest/Diagnostics/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.vb
  src/Workspaces/Core/Portable/Utilities/AbstractSpeculationAnalyzer.cs
Labels: Area-IDE

#32857 Fix dev div insertion files unsigning
  src/Setup/DevDivInsertionFiles/DevDivInsertionFiles.csproj
Labels: Area-Infrastructure

#33165 Handle opening/closing of additional files in VS Workspace open file …
  src/EditorFeatures/CSharpTest/Workspaces/WorkspaceTests.cs
  src/EditorFeatures/Core.Wpf/InlineRename/InlineRenameSession.cs
  src/VisualStudio/Core/Def/Implementation/EditAndContinue/VsReadOnlyDocumentTracker.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProject.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.OpenFileTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/Core/Portable/Workspace/Workspace_Editor.cs
Labels: Approved to merge, Area-IDE

#33214 Show Add Imports first in suggested actions
  src/Features/Core/Portable/AddImport/References/ProjectSymbolReference.cs
Labels: Approved to merge, Area-IDE

#32467 Incorrect IDE0004 "Cast is redundant" when passing enum cast to int as constructor parameter accepting int
  src/EditorFeatures/CSharpTest/Diagnostics/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs
  src/Workspaces/CSharp/Portable/Utilities/SpeculationAnalyzer.cs
Labels: Approved to merge, Area-IDE, Community

#33045 Fix rendering of <see> elements with content
  src/EditorFeatures/Test/DocCommentFormatting/DocCommentFormattingTests.cs
  src/Features/Core/Portable/DocumentationComments/AbstractDocumentationCommentFormattingService.cs
Labels: Approved to merge, Area-IDE

#33222 DebuggerTextView: allow multiple assignments to _innerTextView.Properties[CompletionRoot]
  src/VisualStudio/Core/Def/Implementation/DebuggerIntelliSense/AbstractDebuggerIntelliSenseContext.cs
  src/VisualStudio/Core/Def/Implementation/DebuggerIntelliSense/DebuggerTextView.cs
Labels: Approved to merge, IDE-IntelliSense

#33234 Update ADO config for preview4 snap
  azure-pipelines-integration.yml
  azure-pipelines.yml
Labels: Area-Infrastructure

#33230 Update the publish data with new branch information
  eng/config/PublishData.json
Labels: Area-Infrastructure

#33229 Delete ExceptionHelpers.SuppressFailFast/IsFailFastSuppressed
  src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs
  src/Workspaces/Core/Portable/Utilities/ExceptionHelpers.cs
  src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentState.cs
  src/Workspaces/CoreTest/UtilityTest/ExceptionHelpersTests.cs
Labels: Area-IDE

#32808 Bad code for consecutive interface type tests with a when clause in a switch
  src/Compilers/CSharp/Portable/Binder/SwitchBinder_Patterns.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs
Labels: Area-Compilers, Bug, New Language Feature - Pattern Matching

#33259 Update install x-copy build
  eng/common/tools.ps1
Labels: Area-Infrastructure

#33170 Remove dead code
  src/Workspaces/VisualBasic/Portable/Formatting/DefaultOperationProvider.vb
Labels: Area-IDE

#33297 Wrap parallel file parsing in fatal exception handler
  src/Compilers/CSharp/Portable/CommandLine/CSharpCompiler.cs
  src/Compilers/VisualBasic/Portable/CommandLine/VisualBasicCompiler.vb
Labels: Area-Compilers

#33308 Update install x-copy build (#33259)
  eng/common/tools.ps1
Labels: Area-Infrastructure

#33184 Revert "Add an adapter assembly for MonoDevelop"
  Roslyn.sln
  src/Tools/ExternalAccess/MonoDevelop/Microsoft.CodeAnalysis.ExternalAccess.MonoDevelop.csproj
  src/Tools/ExternalAccess/MonoDevelop/PublicAPI.Shipped.txt
  src/Tools/ExternalAccess/MonoDevelop/PublicAPI.Unshipped.txt
  src/VisualStudio/Setup/AssemblyRedirects.cs
  src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj
Labels: Area-Infrastructure

#33293 Fixes AddUsingExactMatchBeforeRenameTracking integration test
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpCodeActions.cs
Labels: Approved to merge, Area-IDE, Integration-Test

#33261 Nullable constraint checking outside method bodies
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/TypeConversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs
  src/Compilers/CSharp/Portable/Symbols/MethodSymbolExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceConstructorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberFieldSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeParameterSymbol.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/GenericConstraintTests.cs
Labels: Area-Compilers

#33291 Reduce allocations in the formatter
  src/CodeStyle/Core/Analyzers/Microsoft.CodeAnalysis.CodeStyle.csproj
  src/CodeStyle/Core/Analyzers/Options/AnalyzerConfigOptionsExtensions.cs
  src/Compilers/Core/Portable/InternalUtilities/PerformanceSensitiveAttribute.cs
  src/Workspaces/CSharp/Portable/Formatting/Engine/Trivia/TriviaDataFactory.ComplexTrivia.cs
  src/Workspaces/CSharp/Portable/Formatting/Engine/Trivia/TriviaDataFactory.FormattedComplexTrivia.cs
  src/Workspaces/CSharp/Portable/Formatting/Engine/Trivia/TriviaDataFactory.ModifiedComplexTrivia.cs
  src/Workspaces/Core/Portable/Formatting/Engine/AbstractFormatEngine.OperationApplier.cs
  src/Workspaces/Core/Portable/Formatting/Engine/AbstractFormatEngine.Partitioner.cs
  src/Workspaces/Core/Portable/Formatting/Engine/AbstractFormatEngine.cs
  src/Workspaces/Core/Portable/Formatting/Engine/AbstractTriviaDataFactory.FormattedWhitespace.cs
  src/Workspaces/Core/Portable/Formatting/Engine/AbstractTriviaDataFactory.ModifiedWhitespace.cs
  src/Workspaces/Core/Portable/Formatting/Engine/AbstractTriviaDataFactory.Whitespace.cs
  src/Workspaces/Core/Portable/Formatting/Engine/TriviaData.cs
  src/Workspaces/Core/Portable/Options/EditorConfig/EditorConfigStorageLocation`1.cs
  src/Workspaces/Core/Portable/Shared/Extensions/SyntaxTriviaListExtensions.cs
  src/Workspaces/VisualBasic/Portable/Extensions/SyntaxTreeExtensions_SharedWithCodeStyle.vb
  src/Workspaces/VisualBasic/Portable/Formatting/DefaultOperationProvider.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/Trivia/TriviaDataFactory.AbstractLineBreakTrivia.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/Trivia/TriviaDataFactory.ComplexTrivia.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/Trivia/TriviaDataFactory.FormattedComplexTrivia.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/Trivia/TriviaDataFactory.ModifiedComplexTrivia.vb
Labels: Area-IDE, Tenet-Performance

#33198 Reference Microsoft.NetFramework.Analyzers and fix violations
  eng/config/rulesets/Shipping.ruleset
  src/Compilers/CSharp/Test/Emit/PDB/CSharpPDBTestBase.cs
  src/Test/Utilities/Portable/Metadata/ILValidation.cs
Labels: Area-Infrastructure

#33327 Correct assert in CustomModifierUtils
  src/Compilers/CSharp/Portable/Symbols/Source/CustomModifierUtils.cs
Labels: Area-Compilers

#32898 Issue 26640 Fix unnecessary cast warning in conditional expressions when required.
  src/EditorFeatures/CSharpTest/Diagnostics/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs
  src/Workspaces/CSharp/Portable/Utilities/SpeculationAnalyzer.cs
Labels: Area-IDE

#33311 Handle the newly added null coalescing assignment operation in the un…
  src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedParametersTests.cs
  src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedValueAssignmentTests.cs
  src/Features/CSharp/Portable/RemoveUnusedParametersAndValues/CSharpRemoveUnusedValuesCodeFixProvider.cs
  src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs
  src/Features/VisualBasic/Portable/RemoveUnusedParametersAndValues/VisualBasicRemoveUnusedValuesCodeFixProvider.vb
  src/Workspaces/CSharp/Portable/Extensions/SyntaxKindExtensions.cs
  src/Workspaces/Core/Portable/Extensions/OperationExtensions.cs
  src/Workspaces/Core/Portable/FlowAnalysis/LValueFlowCaptureProvider.cs
  src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.Walker.cs
Labels: Area-IDE

#32991 Analyze throw expression and adjust analysis of null-coalescing operator
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Generated/ErrorFacts.Generated.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#33269 Completion List is broken for #r and #load in C# Interactive Window
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CompletionSource.cs
Labels: Approved to merge, IDE-IntelliSense

#33264 Compute relative folder information if we aren't given it
  src/VisualStudio/CSharp/Test/ProjectSystemShim/LegacyProject/SourceFileHandlingTests.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/Legacy/AbstractLegacyProject.cs
Labels: Approved to merge, Area-IDE

#33310 Ensure we don't run off the end of the string when parsing \x1
  src/Workspaces/CSharp/Portable/EmbeddedLanguages/VirtualChars/CSharpVirtualCharService.cs
  src/Workspaces/CSharpTest/EmbeddedLanguages/VirtualChars/CSharpVirtualCharServiceTests.cs
Labels: Approved to merge

#33212 Add EditorFeatures.Cocoa IVTs for MonoDevelop
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/EditorFeatures/Text/Microsoft.CodeAnalysis.EditorFeatures.Text.csproj
  src/Features/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.Features.csproj
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/Features/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.Features.vbproj
  src/Workspaces/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.Workspaces.csproj
  src/Workspaces/Core/Desktop/Microsoft.CodeAnalysis.Workspaces.Desktop.csproj
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
  src/Workspaces/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.Workspaces.vbproj
Labels: Approved to merge, Area-Infrastructure, Community

#33325 Use TaggedTextExtension method for getting ClassificationTypeName
  src/EditorFeatures/Core.Wpf/Completion/Presentation/ToolTipProvider.cs
  src/EditorFeatures/Core.Wpf/WpfClassificationExtensions.cs
  src/EditorFeatures/Core/Implementation/Classification/ClassificationTags.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/AbstractDocumentSpanEntry.cs
Labels: Area-IDE

#33258 Allow file banner comments to be documentation comments
  src/EditorFeatures/CSharpTest/AddFileBanner/AddFileBannerTests.cs
  src/EditorFeatures/CSharpTest/Organizing/OrganizeUsingsTests.cs
  src/EditorFeatures/VisualBasicTest/AddFileBanner/AddFileBannerTests.vb
  src/EditorFeatures/VisualBasicTest/Diagnostics/GenerateType/GenerateTypeTests.vb
  src/EditorFeatures/VisualBasicTest/Organizing/OrganizeImportsTests.vb
  src/Features/CSharp/Portable/AddFileBanner/CSharpAddFileBannerCodeRefactoringProvider.cs
  src/Features/VisualBasic/Portable/AddFileBanner/VisualBasicAddFileBannerCodeRefactoringProvider.vb
  src/Workspaces/CSharp/Portable/LanguageServices/CSharpSyntaxFactsService.cs
  src/Workspaces/Core/Portable/LanguageServices/SyntaxFactsService/AbstractSyntaxFactsService.cs
  src/Workspaces/VisualBasic/Portable/LanguageServices/VisualBasicSyntaxFactsService.vb
Labels: Area-IDE

#33183 Resolve Metadata As Source symbols in their original compilations
  src/EditorFeatures/CSharp/DecompiledSource/CSharpDecompiledSourceService.cs
  src/EditorFeatures/Core/IDecompiledSourceService.cs
  src/EditorFeatures/Core/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs
  src/Features/CSharp/Portable/MetadataAsSource/CSharpMetadataAsSourceService.cs
  src/Features/Core/Portable/MetadataAsSource/AbstractMetadataAsSourceService.cs
  src/Features/Core/Portable/MetadataAsSource/IMetadataAsSourceService.cs
  src/Features/Core/Portable/MetadataAsSource/MetadataAsSourceHelpers.cs
  src/Features/VisualBasic/Portable/MetadataAsSource/VisualBasicMetadataAsSourceService.vb
Labels: Area-IDE

#33366 Add TextManager.Interop.16.0.DesignTime as a Private VS Package.
  eng/Versions.props
Labels: Area-Infrastructure, Tenet-Acquisition

#33362 removed unused parameter
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine_ProjectProcessing.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
Labels: Area-IDE

#33369 Add vsBranch and ibcSourceBranch to PublishData.json
  eng/config/PublishData.json
Labels: Area-Infrastructure

#33389 Correct TFM for EE assemblies
  eng/Signing.props
Labels: Area-Infrastructure

#33377 Use PublishTestResults@2 for SpanishUnitTests
  azure-pipelines-integration.yml
  azure-pipelines-official.yml
  azure-pipelines.yml
Labels: Area-Infrastructure

#33177 Expand RemoveAllComments to have more in depth logic
  src/EditorFeatures/CSharpTest/CodeActions/MoveType/MoveTypeTests.MoveToNewFile.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/CSharp/Portable/Extensions/SyntaxTriviaListExtensions.cs
  src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs
  src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb
Labels: Area-IDE

#32998 Update .editorconfig
  .editorconfig
Labels: Area-Infrastructure, Community

#33000 Add more information on running tests from the command line, and view…
  docs/contributing/Building, Debugging, and Testing on Windows.md
Labels: Area-Infrastructure, Community, Contributor Pain, Documentation

#33300 Bad code for consecutive interface type tests with a when clause in a switch (dev16.0)
  src/Compilers/CSharp/Portable/Binder/SwitchBinder_Patterns.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs
Labels: Area-Compilers, Bug, Needs Shiproom Approval, Tenet-Compatibility

#33396 Update PublishData.json
  eng/config/PublishData.json
Labels: Area-Infrastructure

#32755 Fix compiler crash and remove spurious hidden sequence points for switch expression
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/DynamicAnalysis/DynamicInstrumentationTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs
Labels: Area-Compilers, Needs Shiproom Approval, New Language Feature - Pattern Matching

#33368 Delete unnecessary code around Workspace eventing
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioTaskSchedulerFactory.cs
Labels: Area-IDE

#33221 Call ProjectCodeModel.OnSourceFileRemoved when we remove files
  src/EditorFeatures/VisualBasic/LineCommit/CommitBufferManager.vb
  src/EditorFeatures/VisualBasic/LineCommit/CommitBufferManagerFactory.vb
  src/EditorFeatures/VisualBasicTest/LineCommit/CommitTestData.vb
  src/VisualStudio/Core/Def/Implementation/CodeModel/IProjectCodeModel.cs
  src/VisualStudio/Core/Def/Implementation/CodeModel/IProjectCodeModelFactory.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/InvisibleEditor.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/Legacy/AbstractLegacyProject.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/Core/Impl/CodeModel/AbstractCodeModelObject.cs
  src/VisualStudio/Core/Impl/CodeModel/CodeModelProjectCache.cs
  src/VisualStudio/Core/Impl/CodeModel/FileCodeModel.cs
  src/VisualStudio/Core/Impl/CodeModel/ProjectCodeModel.cs
  src/VisualStudio/Core/Impl/CodeModel/ProjectCodeModelFactory.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs
  src/VisualStudio/Core/Impl/RoslynVisualStudioWorkspace.cs
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualBasicCodeModelLifetimeTests.vb
  src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/MockHierarchy.vb
  src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb
Labels: Approved to merge, Area-IDE

#33281 Add initial support for specifying explicit base type in the base access.
  docs/features/DefaultInterfaceImplementation.md
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/Binder/LookupOptions.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Compiler/MethodBodySynthesizer.cs
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Generated/Syntax.xml.Internal.Generated.cs
  src/Compilers/CSharp/Portable/Generated/Syntax.xml.Main.Generated.cs
  src/Compilers/CSharp/Portable/Generated/Syntax.xml.Syntax.Generated.cs
  src/Compilers/CSharp/Portable/GlobalSuppressions.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DelegateCreationExpression.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Event.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PropertyAccess.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Symbols/Source/SourceCustomEventAccessorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceCustomEventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertyAccessorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Portable/Syntax/BaseExpressionSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
  src/Compilers/CSharp/Portable/Syntax/SyntaxFactory.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/Compilers/CSharp/Test/Syntax/Generated/Syntax.Test.xml.Generated.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ExpressionParsingTests.cs
  src/Test/Utilities/Portable/Assert/ConditionalFactAttribute.cs
  src/Test/Utilities/Portable/TestResource.resx
Labels: Area-Compilers, New Language Feature - Default Interface Implementation

#32805 Remove extra well-known members from Range
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Range.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IBinaryOperatorExpression.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IUnaryOperatorExpression.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/IndexAndRangeTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/Test/Utilities/CSharp/TestSources.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/ExpressionCompilerTests.cs
Labels: Area-Compilers, New Language Feature - Range

#33030 Add long paths support
  eng/config/app.manifest
  eng/targets/Imports.targets
Labels: Area-Compilers

#33168 Fix crash in classification service
  src/EditorFeatures/Core/Implementation/Classification/SyntacticClassificationTaggerProvider.TagComputer.cs
  src/EditorFeatures/Core/Implementation/KeywordHighlighting/HighlighterViewTaggerProvider.cs
  src/EditorFeatures/Core/Implementation/KeywordHighlighting/HighlightingService.cs
  src/VisualStudio/Xaml/Impl/Implementation/XamlTextViewCreationListener.cs
  src/VisualStudio/Xaml/Impl/Implementation/XamlTextViewCreationListener_IVsRunningDocTableEvents3.cs
Labels: Approved to merge, Area-IDE

#33302 Check more classifications for default theme color
  src/VisualStudio/Core/Def/Implementation/Experimentation/EnhancedColorExperiment.cs
Labels: Approved to merge, Area-IDE

#33401 Changes are not allowed while code is running shows while ENC about VB framework app
  src/VisualStudio/CSharp/Impl/ProjectSystemShim/CSharpProjectShim.ICSCompiler.cs
  src/VisualStudio/CSharp/Test/ProjectSystemShim/LegacyProject/CSharpCompilerOptionsTests.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/Legacy/AbstractLegacyProject.cs
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualBasicCompilerOptionsTests.vb
  src/VisualStudio/VisualBasic/Impl/ProjectSystemShim/VisualBasicProject.vb
Labels: Approved to merge, Area-IDE, Bug, IDE-Project, Interactive-EnC

#33438 Merges/dev16.0 to dev16.0 vs deps
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Range.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IBinaryOperatorExpression.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IUnaryOperatorExpression.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/IndexAndRangeTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/Test/Utilities/CSharp/TestSources.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
  src/EditorFeatures/VisualBasic/LineCommit/CommitBufferManager.vb
  src/EditorFeatures/VisualBasic/LineCommit/CommitBufferManagerFactory.vb
  src/EditorFeatures/VisualBasicTest/LineCommit/CommitTestData.vb
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/ExpressionCompilerTests.cs
  src/VisualStudio/Core/Def/Implementation/CodeModel/IProjectCodeModel.cs
  src/VisualStudio/Core/Def/Implementation/CodeModel/IProjectCodeModelFactory.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/InvisibleEditor.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/Legacy/AbstractLegacyProject.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/Core/Impl/CodeModel/AbstractCodeModelObject.cs
  src/VisualStudio/Core/Impl/CodeModel/CodeModelProjectCache.cs
  src/VisualStudio/Core/Impl/CodeModel/FileCodeModel.cs
  src/VisualStudio/Core/Impl/CodeModel/ProjectCodeModel.cs
  src/VisualStudio/Core/Impl/CodeModel/ProjectCodeModelFactory.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs
  src/VisualStudio/Core/Impl/RoslynVisualStudioWorkspace.cs
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualBasicCodeModelLifetimeTests.vb
  src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/MockHierarchy.vb
  src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb
Labels: Area-Infrastructure

#33395 Copy field nullability on assignment for all expressions
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#33336 Nullable tuple constraints in method bodies
  src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/Binder/Binder_TupleOperators.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DeconstructionAssignmentOperator.cs
  src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs
  src/Compilers/CSharp/Portable/Symbols/MethodSymbolExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/Source/CustomModifierUtils.cs
  src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
Labels: Area-Compilers

#31682 Find All References 'Kind' column values for Namespaces and Types.
  src/EditorFeatures/Core/FindUsages/AbstractFindUsagesService.ProgressAdapter.cs
  src/EditorFeatures/Core/FindUsages/IDefinitionsAndReferencesFactory.cs
  src/Features/Core/Portable/ChangeSignature/DelegateInvokeMethodReferenceFinder.cs
  src/Features/Core/Portable/FindUsages/SourceReferenceItem.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/FindUsagesValueUsageInfoColumnDefinition.cs
  src/Workspaces/CSharp/Portable/Extensions/ExpressionSyntaxExtensions.cs
  src/Workspaces/CSharp/Portable/LanguageServices/CSharpSyntaxFactsService.cs
  src/Workspaces/Core/Portable/Extensions/OperationExtensions.cs
  src/Workspaces/Core/Portable/Extensions/SymbolUsageInfo.cs
  src/Workspaces/Core/Portable/Extensions/TypeOrNamespaceUsageInfo.cs
  src/Workspaces/Core/Portable/Extensions/ValueUsageInfo.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/PropertySymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/ReferenceLocation.cs
  src/Workspaces/Core/Portable/LanguageServices/SyntaxFactsService/ISyntaxFactsService.cs
  src/Workspaces/Core/Portable/Remote/RemoteArguments.cs
  src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs
  src/Workspaces/Core/Portable/WorkspacesResources.Designer.cs
  src/Workspaces/Core/Portable/WorkspacesResources.resx
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.cs.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.de.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.es.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.fr.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.it.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ja.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ko.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.pl.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.pt-BR.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ru.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.tr.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.zh-Hans.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.zh-Hant.xlf
  src/Workspaces/VisualBasic/Portable/LanguageServices/VisualBasicSyntaxFactsService.vb
Labels: Area-IDE

#28520 Improvements to the integration test screenshot service
  src/VisualStudio/IntegrationTest/TestUtilities/ScreenshotService.cs
  src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs
Labels: Area-Infrastructure

#33475 Ensure pipename argument quoted
  src/Compilers/Server/VBCSCompilerTests/CompilerServerApiTest.cs
  src/Compilers/Shared/BuildServerConnection.cs
  src/Test/Utilities/Portable/Assert/ConditionalFactAttribute.cs
Labels: Area-Compilers

#33363 made Checksum type to truncate byte array given to it if it is bigger than HashSize
  src/Workspaces/Core/Portable/Workspace/Solution/Checksum.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Checksum_Factory.cs
  src/Workspaces/Remote/ServiceHub/Shared/RoslynJsonConverter.cs
Labels: Area-IDE

#33454 Increase diagnostics in determinism job
  eng/test-determinism.ps1
Labels: Area-Infrastructure

#33408 Correct TFM for EE assemblies (#33389)
  eng/Signing.props
Labels: Approved to merge, Area-Infrastructure

#33440 Add PROTOTYPE comments to follow up on a previous change.
  src/Compilers/CSharp/Portable/Symbols/Source/SourceCustomEventAccessorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceCustomEventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertyAccessorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs
Labels: Area-Compilers, New Language Feature - Default Interface Implementation

#33367 Document ref enumerator disposal compat break
  docs/compilers/CSharp/Compiler Breaking Changes - VS2019.md
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenForEachTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/ForEachTests.cs
Labels: Area-Compilers, Documentation, New Language Feature - enhanced using

#33467 Do not offer to convert object initializers to a compound assignment.
  src/EditorFeatures/CSharpTest/UseCompoundAssignment/UseCompoundAssignmentTests.cs
  src/Features/Core/Portable/UseCompoundAssignment/AbstractUseCompoundAssignmentDiagnosticAnalyzer.cs
Labels: Area-IDE, Community

#33232 enable KeywordsOrSymbolsAfterNamedParameter test
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
Labels: IDE-IntelliSense, Test

#33410 Read IBC and VS bootstrapper info from PublishData.json
  azure-pipelines-official.yml
  eng/build-utils.ps1
  eng/build.ps1
  eng/publish-assets.ps1
  global.json
Labels: Area-Infrastructure

#33409 Don't accidentally share a named semaphore between test processes
  src/Compilers/Core/Portable/InternalUtilities/SemaphoreExtensions.cs
  src/EditorFeatures/TestUtilities/Threading/WpfTestCase.cs
  src/EditorFeatures/TestUtilities/Threading/WpfTestSharedData.cs
  src/EditorFeatures/TestUtilities/Threading/WpfTheoryTestCase.cs
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
Labels: Area-Infrastructure

#33462 Fix issue #33242: ExtractMethodCodeRefactoringProvider throws invalid cast when used within the body of a constructor expression-member body
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs
  src/Workspaces/CSharp/Portable/Extensions/MemberDeclarationSyntaxExtensions.cs
Labels: Area-IDE, Community

#33455 Replace slot watermark
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#33500 Use dotnet-external-vs2019-preview for integration testing
  azure-pipelines-integration.yml
Labels: Area-Infrastructure

#33457 Add FixReturnType fixer
  src/EditorFeatures/CSharpTest/Diagnostics/FixReturnType/FixReturnTypeTests.cs
  src/Features/CSharp/Portable/CSharpFeaturesResources.Designer.cs
  src/Features/CSharp/Portable/CSharpFeaturesResources.resx
  src/Features/CSharp/Portable/CodeFixes/FixReturnType/CSharpFixReturnTypeCodeFixProvider.cs
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.cs.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.de.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.es.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.fr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.it.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ja.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ko.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pl.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pt-BR.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ru.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.tr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hans.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hant.xlf
  src/Features/Core/Portable/CodeFixes/PredefinedCodeFixProviderNames.cs
  src/Test/Utilities/Portable/Traits/Traits.cs
Labels: Area-IDE, Community

#33431 LOC CHECKIN | dotnet/roslyn dev16.0-vs-deps | 20190213
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.cs.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.de.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.es.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.fr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.it.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ja.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ko.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pl.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pt-BR.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ru.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.tr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hans.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hant.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.cs.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.de.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.es.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.fr.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.it.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.ja.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.ko.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.pl.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.pt-BR.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.ru.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.tr.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.zh-Hans.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.zh-Hant.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
Labels: Approved to merge, Area-Infrastructure

#33513 Fix failure to print test results
  src/Tools/Source/RunTests/TestRunner.cs
Labels: Area-Infrastructure

#33413 Add support for virtual properties with a private accessor in an interface
  src/Compilers/CSharp/Portable/CSharpResources.Designer.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Symbols/MemberSymbolExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEPropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ExplicitInterfaceHelpers.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
Labels: Area-Compilers, New Language Feature - Default Interface Implementation

#33435 Move open/closed document checks under the _serializationLock
  src/Workspaces/Core/Portable/Workspace/Workspace_Editor.cs
Labels: Area-IDE

#33501 Bootstrap builds should use ExitingTraceListener
  src/Compilers/CSharp/csc/Program.cs
  src/Compilers/Server/VBCSCompiler/VBCSCompiler.cs
  src/Compilers/Shared/ExitingTraceListener.cs
  src/Compilers/VisualBasic/vbc/Program.cs
Labels: Area-Compilers

#33516 Include the hidden NUL in max path length calculation
  src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs
Labels: Area-Infrastructure

#33517 Do not skip editorconfig integration tests
  src/EditorFeatures/TestUtilities/Threading/CriticalWpfFactAttribute.cs
  src/EditorFeatures/TestUtilities/Threading/CriticalWpfTheoryAttribute.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpCodeActions.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpFormatting.cs
Labels: Area-Infrastructure

#33512 Include RunTests.exe and xunit.console.x86.exe in .NET event collection
  src/VisualStudio/IntegrationTest/TestUtilities/EventLogCollector.cs
  src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs
Labels: Area-Infrastructure

#33432 Document nullable disable for generated code
  docs/features/nullable-reference-types.md
Labels: Area-Compilers, Documentation

#33520 Adjust process logging for applicability to current builds
  src/VisualStudio/IntegrationTest/TestUtilities/EventLogCollector.cs
Labels: Area-Infrastructure, Integration-Test

#33514 Disable broken checksum validation
  src/Workspaces/Remote/Core/Services/SolutionCreator.cs
Labels: Area-Infrastructure

#33196 completion and signature help ordering
  eng/Versions.props
  src/EditorFeatures/CSharp/AutomaticCompletion/AutomaticLineEnderCommandHandler.cs
  src/EditorFeatures/CSharp/BlockCommentEditing/BlockCommentEditingCommandHandler.cs
  src/EditorFeatures/CSharp/DocumentationComments/DocumentationCommentCommandHandler.cs
  src/EditorFeatures/CSharp/DocumentationComments/XmlTagCompletionCommandHandler.cs
  src/EditorFeatures/CSharp/Formatting/Indentation/SmartTokenFormatterCommandHandler.cs
  src/EditorFeatures/Core.Wpf/Interactive/InteractivePasteCommandHandler.cs
  src/EditorFeatures/Core/CommandHandlers/AbstractCompletionCommandHandler.cs
  src/EditorFeatures/Core/CommandHandlers/AbstractIntelliSenseCommandHandler.cs
  src/EditorFeatures/Core/CommandHandlers/AbstractSignatureHelpCommandHandler.cs
  src/EditorFeatures/Core/CommandHandlers/CompletionCommandHandler.cs
  src/EditorFeatures/Core/CommandHandlers/IntelliSenseCommandHandler.cs
  src/EditorFeatures/Core/CommandHandlers/SignatureHelpAfterCompletionCommandHandler.cs
  src/EditorFeatures/Core/CommandHandlers/SignatureHelpBeforeCompletionCommandHandler.cs
  src/EditorFeatures/Core/Extensibility/Commands/PredefinedCommandHandlerNames.cs
  src/EditorFeatures/Core/Implementation/Formatting/FormatCommandHandler.cs
  src/EditorFeatures/Core/Implementation/RenameTracking/RenameTrackingCancellationCommandHandler.cs
  src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests.vb
  src/EditorFeatures/TestUtilities2/Intellisense/LegacyTestState.vb
  src/EditorFeatures/TestUtilities2/Intellisense/ModernCompletionTestState.vb
  src/EditorFeatures/TestUtilities2/Intellisense/TestStateBase.vb
  src/EditorFeatures/VisualBasic/DocumentationComments/DocumentationCommentCommandHandler.vb
  src/EditorFeatures/VisualBasic/DocumentationComments/XmlTagCompletionCommandHandler.vb
  src/EditorFeatures/VisualBasic/ImplementAbstractClass/ImplementAbstractClassCommandHandler.vb
  src/EditorFeatures/VisualBasic/ImplementInterface/ImplementInterfaceCommandHandler.vb
  src/Interactive/EditorFeatures/Core/CommandHandlers/InteractiveCompletionCommandHandler.cs
  src/Interactive/EditorFeatures/Core/CommandHandlers/InteractiveIntelliSenseCommandHandler.cs
  src/VisualStudio/CSharp/Impl/Snippets/SnippetCommandHandler.cs
  src/VisualStudio/Core/Test/DebuggerIntelliSense/TestState.vb
  src/VisualStudio/VisualBasic/Impl/Snippets/SnippetCommandHandler.vb
Labels: Approved to merge, Bug, IDE-IntelliSense

#33494 Convert to struct has errors on uninitiated members
  src/EditorFeatures/CSharpTest/ConvertTupleToStruct/ConvertTupleToStructTests.cs
  src/EditorFeatures/VisualBasicTest/ConvertTupleToStruct/ConvertTupleToStructTests.vb
  src/Workspaces/Core/Portable/CodeGeneration/AbstractCodeGenerationService.cs
Labels: Approved to merge, Bug, IDE-CodeStyle

#33400 set no activation context on provisional tab when navigate to
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs
Labels: Area-IDE, Needs Shiproom Approval

#33515 Do not apply Fix All operations to generated code
  src/CodeStyle/Core/CodeFixes/FixAllContextHelper.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpCodeActions.cs
Labels: Approved to merge, Area-IDE

#33524 SendInput using scan codes when available
  src/VisualStudio/IntegrationTest/TestUtilities/Input/SendKeys.cs
  src/VisualStudio/IntegrationTest/TestUtilities/IntegrationHelper.cs
  src/VisualStudio/IntegrationTest/TestUtilities/Interop/NativeMethods.cs
Labels: Area-Infrastructure, Integration-Test

#33529 Don't make color changes when in high contrast mode
  src/VisualStudio/Core/Def/Implementation/Experimentation/EnhancedColorExperiment.cs
Labels: Approved to merge, Area-IDE

#33505 Subscribe to and process rule set file changes
  src/VisualStudio/CSharp/Test/ProjectSystemShim/LegacyProject/AnalyzersTests.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/FileChangeWatcherProvider.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectOptionsProcessor.cs
  src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb
Labels: Approved to merge, Area-IDE

#33402 Fix up all the test project launchSettings.json to allow F5 again
  src/CodeStyle/CSharp/Tests/Properties/launchSettings.json
  src/CodeStyle/Core/Tests/Properties/launchSettings.json
  src/CodeStyle/VisualBasic/Tests/My Project/launchSettings.json
  src/Compilers/CSharp/Test/CommandLine/Properties/launchSettings.json
  src/Compilers/CSharp/Test/Emit/Properties/launchSettings.json
  src/Compilers/CSharp/Test/Semantic/Properties/launchSettings.json
  src/Compilers/CSharp/Test/Symbol/Properties/launchSettings.json
  src/Compilers/CSharp/Test/Syntax/Properties/launchSettings.json
  src/Compilers/CSharp/Test/WinRT/Properties/launchSettings.json
  src/Compilers/Core/CodeAnalysisTest/Properties/launchSettings.json
  src/Compilers/Core/MSBuildTaskTests/Properties/launchSettings.json
  src/Compilers/Server/VBCSCompilerTests/Properties/launchSettings.json
  src/Compilers/VisualBasic/Test/CommandLine/My Project/launchSettings.json
  src/Compilers/VisualBasic/Test/Emit/My Project/launchSettings.json
  src/Compilers/VisualBasic/Test/IOperation/My Project/launchSettings.json
  src/Compilers/VisualBasic/Test/Semantic/My Project/launchSettings.json
  src/Compilers/VisualBasic/Test/Symbol/My Project/launchSettings.json
  src/Compilers/VisualBasic/Test/Syntax/My Project/launchSettings.json
  src/EditorFeatures/CSharpTest2/Properties/launchSettings.json
  src/EditorFeatures/Test/Properties/launchSettings.json
  src/EditorFeatures/Test2/My Project/launchSettings.json
  src/EditorFeatures/VisualBasicTest/My Project/launchSettings.json
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/Properties/launchSettings.json
  src/ExpressionEvaluator/CSharp/Test/ResultProvider/Properties/launchSettings.json
  src/ExpressionEvaluator/Core/Test/FunctionResolver/Properties/launchSettings.json
  src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/My Project/launchSettings.json
  src/ExpressionEvaluator/VisualBasic/Test/ResultProvider/My Project/launchSettings.json
  src/Interactive/HostTest/Properties/launchSettings.json
  src/Scripting/CSharpTest.Desktop/Properties/launchSettings.json
  src/Scripting/CSharpTest/Properties/launchSettings.json
  src/Scripting/CoreTest.Desktop/Properties/launchSettings.json
  src/Scripting/CoreTest/Properties/launchSettings.json
  src/Scripting/VisualBasicTest.Desktop/My Project/launchSettings.json
  src/Scripting/VisualBasicTest/My Project/launchSettings.json
  src/VisualStudio/CSharp/Test/Properties/launchSettings.json
  src/VisualStudio/Core/Test.Next/Properties/launchSettings.json
  src/VisualStudio/Core/Test/My Project/launchSettings.json
  src/VisualStudio/IntegrationTest/IntegrationTests/Properties/launchSettings.json
  src/Workspaces/CSharpTest/Properties/launchSettings.json
  src/Workspaces/CoreTest/Properties/launchSettings.json
  src/Workspaces/MSBuildTest/Properties/launchSettings.json
  src/Workspaces/VisualBasicTest/My Project/launchSettings.json
Labels: Area-Infrastructure

#33227 Update the FindImplementationsForInterfaceMember
  src/Test/Utilities/Portable/TestBase.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_Hierarchy.cs
  src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs
  src/Workspaces/CoreTest/FindReferencesTests.cs
Labels: Area-IDE

#33563 Revert "set no activation context on provisional tab when navigate to"
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs
Labels: Area-Infrastructure
