Repository dotnet/roslyn, pull requests merged in 2020-10, with the labels that each got.

#47914 Initial draft of LSP pull diagnostics for documents.
  src/EditorFeatures/CSharpTest/CodeActions/EncapsulateField/EncapsulateFieldTests.cs
  src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractLocalFunctionTests.cs
  src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractMethodTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/OverrideCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SpeculativeTCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/GenerateDefaultConstructors/GenerateDefaultConstructorsTests.cs
  src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/AsyncKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/InKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ReadOnlyKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/VoidKeywordRecommenderTests.cs
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.LocalSymbols.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.ParameterSymbol.vb
  src/EditorFeatures/Test2/Rename/RenameNonRenameableSymbols.vb
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/EditorFeatures/TestUtilities/SolutionCrawler/TestDocumentTrackingService.cs
  src/EditorFeatures/VisualBasicTest/CodeActions/ExtractMethod/ExtractMethodTests.vb
  src/Features/LanguageServer/Protocol/Extensions/Extensions.cs
  src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/Features/LanguageServer/Protocol/Handler/BufferedProgress.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DocumentPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Initialize/InitializeHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Symbols/WorkspaceSymbolsHandler.cs
  src/Features/LanguageServer/Protocol/ILspSolutionProvider.cs
  src/Features/LanguageServer/ProtocolUnitTests/CodeActions/CodeActionsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/RazorLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/VisualStudioLspSolutionProvider.cs
  src/VisualStudio/Core/Test.Next/Services/LspDiagnosticsTests.cs
  src/Workspaces/CoreTestUtilities/Roslyn.Services.UnitTests.Utilities.csproj
Labels: Area-IDE, auto-merge

#48183 Replace function with property change to Retain in line comment
  src/EditorFeatures/CSharpTest/CodeActions/ReplaceMethodWithProperty/ReplaceMethodWithPropertyTests.cs
  src/Features/Core/Portable/ReplaceMethodWithProperty/AbstractReplaceMethodWithPropertyService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxKinds.vb
Labels: Area-IDE, Community

#48199 Update IsImplicitlyDeclared doc
  src/Compilers/Core/Portable/Symbols/ISymbol.cs
Labels: Area-Compilers, Community

#48212 RegexPatternDetector detects implicit object creation
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexPatternDetector.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionTests.cs
Labels: Area-IDE, Community

#48201 IServiceBroker/MessagePack/OOP fix roll-up
  azure-pipelines-integration.yml
  src/Workspaces/Remote/Core/BrokeredServiceConnection.cs
  src/Workspaces/Remote/Core/RemoteCallback.cs
  src/Workspaces/Remote/Core/RemoteHostAssetSerialization.cs
  src/Workspaces/Remote/Core/ServiceDescriptor.cs
  src/Workspaces/Remote/Core/SolutionAssetProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/SolutionAssetSource.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.FactoryBase.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.ServiceConstructionArguments.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs
  src/Workspaces/Remote/ServiceHub/Services/DesignerAttributeDiscovery/RemoteDesignerAttributeIncrementalAnalyzer.cs
  src/Workspaces/Remote/ServiceHub/Services/ProjectTelemetry/RemoteProjectTelemetryIncrementalAnalyzer.cs
  src/Workspaces/Remote/ServiceHub/Services/TodoCommentsDiscovery/RemoteTodoCommentsIncrementalAnalyzer.cs
Labels: Approved to merge, Area-IDE

#48173 Don't offer generate parameter/field/property for top-level programs
  src/EditorFeatures/CSharpTest/GenerateVariable/GenerateVariableTests.cs
  src/Features/Core/Portable/GenerateMember/GenerateVariable/AbstractGenerateVariableService.State.cs
Labels: Area-IDE, Community

#48182 Update SG cookbook
  docs/features/source-generators.cookbook.md
Labels: Area-Compilers, New Feature - Source Generators

#48228 Revert "Merge pull request #47914 from CyrusNajmabadi/lspDiagnostics"
  src/EditorFeatures/CSharpTest/CodeActions/EncapsulateField/EncapsulateFieldTests.cs
  src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractLocalFunctionTests.cs
  src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractMethodTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/OverrideCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SpeculativeTCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/GenerateDefaultConstructors/GenerateDefaultConstructorsTests.cs
  src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/AsyncKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/InKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ReadOnlyKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/VoidKeywordRecommenderTests.cs
  src/EditorFeatures/Test/SolutionCrawler/TestDocumentTrackingService.cs
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.LocalSymbols.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.ParameterSymbol.vb
  src/EditorFeatures/Test2/Rename/RenameNonRenameableSymbols.vb
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/EditorFeatures/VisualBasicTest/CodeActions/ExtractMethod/ExtractMethodTests.vb
  src/Features/LanguageServer/Protocol/Extensions/Extensions.cs
  src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/Features/LanguageServer/Protocol/Handler/BufferedProgress.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DocumentPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Initialize/InitializeHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Symbols/WorkspaceSymbolsHandler.cs
  src/Features/LanguageServer/Protocol/ILspSolutionProvider.cs
  src/Features/LanguageServer/ProtocolUnitTests/CodeActions/CodeActionsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/RazorLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/VisualStudioLspSolutionProvider.cs
  src/VisualStudio/Core/Test.Next/Services/LspDiagnosticsTests.cs
  src/Workspaces/CoreTestUtilities/Roslyn.Services.UnitTests.Utilities.csproj
Labels: Area-IDE, Area-Infrastructure, auto-merge

#48234 Flow master to master-vs-deps
  azure-pipelines-integration.yml
  docs/features/source-generators.cookbook.md
  src/EditorFeatures/CSharpTest/GenerateVariable/GenerateVariableTests.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexPatternDetector.cs
  src/Features/Core/Portable/GenerateMember/GenerateVariable/AbstractGenerateVariableService.State.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionTests.cs
  src/Workspaces/Remote/Core/BrokeredServiceConnection.cs
  src/Workspaces/Remote/Core/RemoteCallback.cs
  src/Workspaces/Remote/Core/RemoteHostAssetSerialization.cs
  src/Workspaces/Remote/Core/ServiceDescriptor.cs
  src/Workspaces/Remote/Core/SolutionAssetProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/SolutionAssetSource.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.FactoryBase.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.ServiceConstructionArguments.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs
  src/Workspaces/Remote/ServiceHub/Services/DesignerAttributeDiscovery/RemoteDesignerAttributeIncrementalAnalyzer.cs
  src/Workspaces/Remote/ServiceHub/Services/ProjectTelemetry/RemoteProjectTelemetryIncrementalAnalyzer.cs
  src/Workspaces/Remote/ServiceHub/Services/TodoCommentsDiscovery/RemoteTodoCommentsIncrementalAnalyzer.cs
Labels: auto-merge

#46816 Update Clashing Enum Members.md
  docs/compilers/Visual Basic/Clashing Enum Members.md
Labels: Area-Compilers, Community, Documentation

#48256 Update Nerdbank.Streams to 2.6.81
  eng/Versions.props
  src/Workspaces/CoreTestUtilities/Roslyn.Services.UnitTests.Utilities.csproj
Labels: auto-merge

#48186 Pass span to register refactorings in initialize parameter refactorin…
  src/Features/Core/Portable/CodeRefactorings/CodeRefactoringContextExtensions.cs
  src/Features/Core/Portable/InitializeParameter/AbstractInitializeParameterCodeRefactoringProvider.cs
Labels: Area-IDE

#48096 Update CSharpSyntaxGenerator for records
  src/CodeStyle/Core/Analyzers/PublicAPI.Unshipped.txt
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/Core/Portable/Editing/DeclarationKind.cs
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
Labels: Area-IDE, Community

#48266 More native integer tests
  src/Compilers/CSharp/Test/Semantic/Semantics/NativeIntegerTests.cs
Labels: Area-Compilers, New Language Feature - Native Int

#48313 Fix code generation for records with semi-colon
  src/EditorFeatures/CSharpTest/GenerateOverrides/GenerateOverridesTests.cs
  src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/TypeDeclarationSyntaxExtensions.cs
Labels: Area-IDE, New Language Feature - Records

#48205 Ensure initial binding always binds to natural type
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IObjectCreationExpression.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/ConditionalOperatorTests.cs
Labels: Area-Compilers, Feature - IOperation, Needs Shiproom Approval

#48168 Handle indexers in nested object initializers
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs
  src/Compilers/CSharp/Portable/Lowering/MethodToClassRewriter.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs
  src/Compilers/CSharp/Portable/Symbols/PropertySymbolExtensions.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IPropertyReferenceExpression.cs
Labels: Area-Compilers, Feature - IOperation, Submitted to Shiproom

#48081 Improve error when named argument is used with function pointer
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/FunctionPointerTests.cs
Labels: Area-Compilers, Community, New Feature - Function Pointers

#48331 Stop publishing nightly builds of VSIX packages
  eng/config/PublishData.json
  eng/config/PublishVsix.MyGet.config
  eng/publish-assets.ps1
Labels: Area-Infrastructure

#48316 Don't crash on nullable value types
  src/Analyzers/CSharp/Tests/RemoveRedundantEquality/RemoveRedundantEqualityTests.cs
  src/Analyzers/Core/Analyzers/RemoveRedundantEquality/AbstractRemoveRedundantEqualityDiagnosticAnalyzer.cs
Labels: Area-IDE

#47332 Fix obsolete warning for delegate creation
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests.cs
Labels: Area-Compilers, Community

#46850 Fix F1 help link for error messages
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Test/CommandLine/SarifV1ErrorLoggerTests.cs
  src/Compilers/CSharp/Test/CommandLine/SarifV2ErrorLoggerTests.cs
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs
  src/Compilers/VisualBasic/Portable/Errors/ErrorFactories.vb
  src/Compilers/VisualBasic/Test/CommandLine/SarifV1ErrorLoggerTests.vb
  src/Compilers/VisualBasic/Test/CommandLine/SarifV2ErrorLoggerTests.vb
  src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_ObsoleteAttribute.vb
  src/EditorFeatures/CSharpTest/Squiggles/ErrorSquiggleProducerTests.cs
  src/EditorFeatures/VisualBasicTest/Squiggles/ErrorSquiggleProducerTests.vb
Labels: Area-Compilers, Community

#48345 Remove infra for legacy OptProf
  azure-pipelines-official.yml
  eng/Versions.props
  eng/build.ps1
  eng/test-build-correctness.ps1
Labels: Area-Infrastructure, auto-merge

#48333 Pass along option to diagnostic analyzer.
  src/EditorFeatures/Test/Diagnostics/IDEDiagnosticIDConfigurationTests.cs
  src/Features/CSharp/Portable/UsePatternMatching/CSharpIsAndCastCheckWithoutNameDiagnosticAnalyzer.cs
Labels: auto-merge

#48343 Make sure GlobalHubClientPackage is loaded
  src/VisualStudio/Core/Def/Guids.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioWorkspaceStatusServiceFactory.cs
Labels: auto-merge

#48341 Switch to immutable arrays.
  src/Features/CSharp/Portable/InlineParameterNameHints/CSharpInlineParameterNameHintsService.cs
  src/Features/Core/Portable/InlineParameterNameHints/AbstractInlineParameterNameHintsService.cs
  src/Features/Core/Portable/InlineParameterNameHints/IInlineParameterNameHintsService.cs
  src/Features/VisualBasic/Portable/InlineParameterNameHints/VisualBasicInlineParameterNameHintsService.vb
Labels: auto-merge

#47249 Separate build and test into separate jobs
  Compilers.sln
  Roslyn.sln
  azure-pipelines.yml
  eng/build.cmd
  eng/cibuild.cmd
  eng/dev-rehydrate-tests.ps1
  eng/pipelines/build-unix-job.yml
  eng/pipelines/build-windows-job.yml
  eng/pipelines/publish-logs.yml
  eng/pipelines/test-unix-job.yml
  eng/pipelines/test-windows-job.yml
  eng/prepare-tests.cmd
  eng/prepare-tests.ps1
  eng/rehydrate-tests.cmd
  eng/rehydrate-tests.ps1
  src/Tools/PrepareTests/MinimizeUtil.cs
  src/Tools/PrepareTests/PrepareTests.csproj
  src/Tools/PrepareTests/Program.cs
  src/Tools/PrepareTests/README.md
Labels: Area-Infrastructure

#48264 Fix VB XML Literal CData color
  src/VisualStudio/Core/Def/ColorSchemes/VisualStudio2019.pkgdef
  src/VisualStudio/Core/Def/Implementation/ColorSchemes/ColorSchemeApplier.cs
Labels: Approved to merge, Area-IDE

#47882 Send back icons for FAR via LSP
  eng/Versions.props
  src/EditorFeatures/Core/Shared/Extensions/GlyphExtensions.cs
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/LanguageServer/Protocol/CustomProtocol/FindUsagesLSPContext.cs
  src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Completion/CompletionResolveHandler.cs
  src/Features/LanguageServer/Protocol/Handler/References/FindAllReferencesHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/References/FindAllReferencesHandlerTests.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Completion/CompletionHandler.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Completion/CompletionResolveHandler.cs
  src/Workspaces/Remote/ServiceHub/Services/LanguageServer/LanguageServer.cs
Labels: Area-IDE, auto-merge

#48355 Track asynchronous operations running in ServiceHub
  eng/targets/Services.props
  src/EditorFeatures/Test/Preview/PreviewWorkspaceTests.cs
  src/EditorFeatures/Test/RenameTracking/RenameTrackingTestState.cs
  src/EditorFeatures/Test2/NavigationBar/NavigationBarPresenterTests.vb
  src/EditorFeatures/Test2/Rename/RenameTestHelpers.vb
  src/EditorFeatures/TestUtilities/AbstractCommandHandlerTestState.cs
  src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs
  src/Test/Diagnostics/TestingOnly_WaitingService.cs
  src/Tools/ExternalAccess/Apex/ApexAsynchronousOperationListenerProviderAccessor.cs
  src/Tools/ExternalAccess/Apex/Microsoft.CodeAnalysis.ExternalAccess.Apex.csproj
  src/VisualStudio/Core/Def/Implementation/Remote/VisualStudioRemoteHostClientProvider.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/VisualStudioWorkspace_InProc.cs
  src/Workspaces/Core/Portable/Shared/TestHooks/IAsynchronousOperationListenerProvider.cs
  src/Workspaces/Core/Portable/Shared/TestHooks/IRemoteAsynchronousOperationListenerService.cs
  src/Workspaces/CoreTest/Remote/ServiceDescriptorTests.cs
  src/Workspaces/CoreTestUtilities/AsynchronousOperationListenerExtensions.cs
  src/Workspaces/CoreTestUtilities/MEF/UseExportProviderAttribute.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemostHostClient.cs
  src/Workspaces/Remote/Core/RemoteWorkspacesResources.resx
  src/Workspaces/Remote/Core/ServiceDescriptors.cs
  src/Workspaces/Remote/Core/ServiceHubRemoteHostClient.cs
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.cs.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.de.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.es.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.fr.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.it.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ja.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ko.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.pl.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.pt-BR.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ru.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.tr.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.zh-Hans.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.zh-Hant.xlf
  src/Workspaces/Remote/ServiceHub/Services/Host/RemoteAsynchronousOperationListenerService.cs
Labels: auto-merge

#48361 Update IDE0044 to ignore ThreadStaticAttribute
  src/Analyzers/CSharp/Tests/MakeFieldReadonly/MakeFieldReadonlyTests.cs
  src/Analyzers/Core/Analyzers/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs
  src/Analyzers/VisualBasic/Tests/MakeFieldReadonly/MakeFieldReadonlyTests.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ICompilationExtensions.cs
Labels: Area-IDE, Community

#48369 Use PowerShell directly in YML
  azure-pipelines-integration.yml
  azure-pipelines-official.yml
  azure-pipelines-richnav.yml
  eng/build.cmd
  eng/cibuild.cmd
  eng/pipelines/build-windows-job.yml
  eng/pipelines/test-windows-job.yml
  eng/prepare-tests.cmd
  eng/rehydrate-tests.cmd
Labels: Area-Infrastructure

#47967 Fix refactorings for target-typed conditionals
  src/Analyzers/CSharp/Tests/UseConditionalExpression/UseConditionalExpressionForAssignmentTests.cs
  src/Analyzers/CSharp/Tests/UseConditionalExpression/UseConditionalExpressionForReturnTests.cs
  src/EditorFeatures/CSharpTest/CodeActions/InlineTemporary/InlineTemporaryTests.cs
  src/EditorFeatures/Test2/Simplification/CastSimplificationTests.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Simplification/Simplifiers/CastSimplifier.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/SpeculationAnalyzer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/AbstractSpeculationAnalyzer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ExpressionSyntaxExtensions.cs
Labels: Area-IDE, auto-merge

#48413 Add null vsix entries to publish data to unblock older builds
  eng/config/PublishData.json
Labels: Area-Infrastructure

#48403 Merge vs-deps back into master
  eng/Versions.props
  src/EditorFeatures/Core/Shared/Extensions/GlyphExtensions.cs
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/LanguageServer/Protocol/CustomProtocol/FindUsagesLSPContext.cs
  src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Completion/CompletionResolveHandler.cs
  src/Features/LanguageServer/Protocol/Handler/References/FindAllReferencesHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/References/FindAllReferencesHandlerTests.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Completion/CompletionHandler.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Completion/CompletionResolveHandler.cs
  src/Workspaces/Remote/ServiceHub/Services/LanguageServer/LanguageServer.cs
Labels: Area-Infrastructure

#48311 Module constructors can't have accessibility modifiers
  src/Analyzers/VisualBasic/Tests/AddAccessibilityModifiers/AddAccessibilityModifiersTests.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE, Community

#48384 No "implement implicitly" when class implements no interface
  src/EditorFeatures/CSharpTest/ImplementInterface/ImplementImplicitlyTests.cs
  src/Features/CSharp/Portable/ImplementInterface/CSharpImplementImplicitlyCodeRefactoringProvider.cs
Labels: Area-IDE, Community

#48303 Test records in extract interface
  src/EditorFeatures/CSharpTest/ExtractInterface/ExtractInterfaceTests.cs
  src/Features/Core/Portable/ExtractInterface/AbstractExtractInterfaceService.cs
Labels: Area-IDE, Community

#48308 Use '++' and '--' in IDE0054
  src/Analyzers/CSharp/Analyzers/UseCompoundAssignment/CSharpUseCompoundAssignmentDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/UseCompoundAssignment/CSharpUseCompoundAssignmentCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseCompoundAssignment/UseCompoundAssignmentTests.cs
  src/Analyzers/Core/Analyzers/AnalyzersResources.resx
  src/Analyzers/Core/Analyzers/UseCompoundAssignment/AbstractUseCompoundAssignmentDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseCompoundAssignment/UseCompoundAssignmentUtilities.cs
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.cs.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.de.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.es.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.fr.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.it.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.ja.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.ko.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.pl.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.pt-BR.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.ru.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.tr.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.zh-Hans.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.zh-Hant.xlf
  src/Analyzers/Core/CodeFixes/UseCompoundAssignment/AbstractUseCompoundAssignmentCodeFixProvider.cs
  src/Analyzers/VisualBasic/Analyzers/UseCompoundAssignment/VisualBasicUseCompoundAssignmentDiagnosticAnalyzer.vb
  src/Analyzers/VisualBasic/CodeFixes/UseCompoundAssignment/VisualBasicUseCompoundAssignmentCodeFixProvider.vb
Labels: Area-IDE, Community

#48421 Update documentation for new minimum dependencies
  docs/contributing/Building, Debugging, and Testing on Windows.md
Labels: Area-IDE

#48393 Ensure that tokens are re-fetched to the position in the reset point in SyntaxParser.Reset
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Parser/SyntaxParser.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/TopLevelStatementsTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/UpgradeProject/UpgradeProjectTests.cs
  src/Features/CSharp/Portable/UpgradeProject/CSharpUpgradeProjectCodeFixProvider.cs
Labels: Area-Compilers, Tenet-Reliability

#48456 Get VS Color ThemeId without using dynamic
  src/VisualStudio/Core/Def/Implementation/ColorSchemes/ColorSchemeApplier.cs
Labels: Area-IDE

#48484 CI workarounds for 16.8 Preview 3
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs
  src/Tools/Source/RunTests/Program.cs
  src/VisualStudio/IntegrationTest/TestUtilities/ActivityLogCollector.cs
  src/VisualStudio/IntegrationTest/TestUtilities/EventLogCollector.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/TextViewWindow_InProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs
  src/Workspaces/Remote/ServiceHub/Services/Host/RemoteHostService.cs
  src/Workspaces/Remote/ServiceHub/Services/Host/ThrowingTraceListener.cs
Labels: Approved to merge, Area-IDE

#48401 Avoid binding the world looking for target-typed new
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
Labels: Approved to merge, Area-IDE, Area-Performance

#48411 Add a ctrl-alt shortcut one can hold to have all inline-hints show up.
  src/EditorFeatures/Core.Wpf/InlineHints/InlineHintsKeyProcessorProvider.cs
  src/EditorFeatures/Core.Wpf/InlineHints/InlineParameterNameHintsTagger.cs
  src/EditorFeatures/Core.Wpf/InlineHints/InlineParameterNameHintsTaggerProvider.cs
  src/EditorFeatures/Core/InlineHints/InlineParameterNameHintsDataTaggerProvider.cs
  src/Features/Core/Portable/InlineHints/AbstractInlineParameterNameHintsService.cs
  src/Features/Core/Portable/InlineHints/InlineHintsOptions.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageStrings.vb
Labels: Area-IDE, auto-merge

#48402 Bind less when finding implicit object construction for FindReferences
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.ConstructorSymbols.vb
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ConstructorSymbolReferenceFinder.cs
Labels: Area-IDE, New Language Feature - Target-Typed New, auto-merge

#48371 Provide options to disable inline hints in some commonly recognized patterns.
  Roslyn.sln
  src/EditorFeatures/Core.Wpf/InlineHints/InlineParameterNameHintsTaggerProvider.cs
  src/EditorFeatures/Core/InlineHints/InlineParameterNameHintsDataTaggerProvider.cs
  src/EditorFeatures/Test2/InlineHints/AbstractInlineParameterNameHintsTests.vb
  src/EditorFeatures/Test2/InlineHints/CSharpInlineParameterNameHintsTests.vb
  src/EditorFeatures/Test2/InlineHints/VisualBasicInlineParameterNameHintsTests.vb
  src/Features/CSharp/Portable/InlineHints/CSharpInlineParameterNameHintsService.cs
  src/Features/Core/Portable/InlineHints/AbstractInlineParameterNameHintsService.cs
  src/Features/Core/Portable/InlineHints/IInlineParameterNameHintsService.cs
  src/Features/Core/Portable/InlineHints/InlineHintsOptions.cs
  src/Features/Core/Portable/InlineHints/InlineParameterHint.cs
  src/Features/Core/Portable/InlineHints/InlineParameterHintKind.cs
  src/Features/VisualBasic/Portable/InlineParameterNameHints/VisualBasicInlineParameterNameHintsService.vb
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageStrings.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ExpressionSyntaxExtensions.vb
Labels: auto-merge

#48438 Enable nullable reference types in SQLite v2 implementation
  src/Tools/IdeBenchmarks/SQLitePersistentStorageBenchmark.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/AbstractPersistentStorageTests.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/SQLiteV2PersistentStorageTests.cs
  src/Workspaces/Core/Portable/Storage/PersistenceStorageServiceFactory.cs
  src/Workspaces/Core/Portable/Storage/SQLite/AbstractSQLitePersistentStorageService.cs
  src/Workspaces/Core/Portable/Storage/SQLite/Interop/NativeMethods.cs
  src/Workspaces/Core/Portable/Storage/SQLite/Interop/OpenFlags.cs
  src/Workspaces/Core/Portable/Storage/SQLite/Interop/Result.cs
  src/Workspaces/Core/Portable/Storage/SQLite/Interop/SqlException.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v1/SQLitePersistentStorage_DocumentSerialization.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v1/SQLitePersistentStorage_ProjectSerialization.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/Database.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/Interop/ResettableSqlStatement.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/Interop/SqlConnection.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/Interop/SqlStatement.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/PooledConnection.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.Accessor.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_BulkPopulateIds.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_DocumentSerialization.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_FlushWrites.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_Helpers.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_ProjectSerialization.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_SolutionSerialization.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_StringIds.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_Threading.cs
  src/Workspaces/Core/Portable/Storage/StorageDatabase.cs
  src/Workspaces/Core/Portable/Storage/StorageDatabaseLogger.cs
  src/Workspaces/Core/Portable/Storage/StorageOptions.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/AbstractPersistentStorage.cs
  src/Workspaces/CoreTestUtilities/MEF/UseExportProviderAttribute.cs
Labels: Area-IDE

#48427 Improve error messages for error list tests
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpErrorListCommon.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicErrorListCommon.cs
Labels: Area-IDE

#48153 Remove unnecessary workaround for WithMultiplexingStream
  src/Workspaces/Remote/Core/ServiceDescriptor.cs
Labels: Area-IDE

#48424 Add timeout to IApexAsynchronousOperationListenerProviderAccessor.WaitAllAsync
  src/Tools/ExternalAccess/Apex/ApexAsynchronousOperationListenerProviderAccessor.cs
  src/Tools/ExternalAccess/Apex/IApexAsynchronousOperationListenerProviderAccessor.cs
Labels: Area-IDE

#48437 Remove the X86 platform from Roslyn.sln
  Roslyn.sln
Labels: Area-Infrastructure

#48429 Remove unused method
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/LanguageServer/Protocol/Extensions/Extensions.cs
  src/Features/LanguageServer/Protocol/ILspSolutionProvider.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/VisualStudioLspSolutionProvider.cs
Labels: Area-IDE

#48297 Add destructor intellisense test for record
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/CSharpSyntaxContext.cs
Labels: Area-IDE, Community

#48485 Update PreRelease version for Preview 5
  eng/Versions.props
Labels: Area-Infrastructure

#48348 Fix Go to Definition to a source-generated file
  src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs
Labels: Approved to merge, Area-IDE

#48451 Fix graph query for records
  src/VisualStudio/CSharp/Impl/Progression/CSharpProgressionLanguageService.cs
  src/VisualStudio/Core/Test/Progression/ContainsGraphQueryTests.vb
Labels: Area-IDE, Community, New Language Feature - Records

#48253 Merge pull request #46393 from ryzngard/issue/46192_nre_save_rename
  azure-pipelines-integration.yml
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
Labels: Approved to merge

#48471 Hook up doc links to IDExxxx rules
  src/Analyzers/CSharp/Analyzers/RemoveConfusingSuppression/CSharpRemoveConfusingSuppressionDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/AbstractBuiltInCodeStyleDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/AbstractBuiltInCodeStyleDiagnosticAnalyzer_Core.cs
  src/Analyzers/Core/Analyzers/AbstractCodeQualityDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/AbstractParenthesesDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/Analyzers.projitems
  src/Analyzers/Core/Analyzers/Helpers/DiagnosticHelper.cs
  src/Analyzers/Core/Analyzers/RemoveUnnecessaryParentheses/AbstractRemoveUnnecessaryParenthesesDiagnosticAnalyzer.cs
  src/CodeStyle/Core/Analyzers/AbstractFormattingAnalyzer.cs
  src/EditorFeatures/Test/Diagnostics/IDEDiagnosticIDConfigurationTests.cs
Labels: auto-merge

#48420 Refactor ChangedText.Merge and add fuzz testing
  src/Compilers/Core/CodeAnalysisTest/Text/TextChangeTests.cs
  src/Compilers/Core/Portable/Text/ChangedText.cs
  src/Compilers/Core/Portable/Text/TextChange.cs
  src/Compilers/Core/Portable/Text/TextChangeRange.cs
Labels: Area-Compilers

#48528 Add contributing doc for IDE code style analyzer documentation
  .github/ISSUE_TEMPLATE/analyzer-suggestion.md
  docs/contributing/Documentation for IDE CodeStyle analyzers.md
Labels: Area-IDE, auto-merge

#48394 Make db lock static to investigate issue.
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.Accessor.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_FlushWrites.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_Threading.cs
Labels: Area-IDE, auto-merge

#48524 Adjust ERR_PartialMisplaced diagnostic message
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/RecordTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/UserDefinedOperatorErrorTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ParserErrorMessageTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ParserRegressionTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ScriptParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/TopLevelStatementsParsingTests.cs
Labels: Area-Compilers

#38138 Handle disabled UndoManager during InlineRename
  src/VisualStudio/Core/Def/Implementation/InlineRename/InlineRenameUndoManager.cs
Labels: Approved to merge, Area-IDE

#48503 Default constructor suggestion between members (#48318)
  src/EditorFeatures/CSharpTest/GenerateDefaultConstructors/GenerateDefaultConstructorsTests.cs
  src/Features/CSharp/Portable/GenerateMember/GenerateDefaultConstructors/CSharpGenerateDefaultConstructorsService.cs
Labels: Area-IDE, Community

#48500 Update F1 Keywords to differentiate between semantics of default keyword
  src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs
  src/VisualStudio/CSharp/Test/F1Help/F1HelpTests.cs
Labels: Area-IDE, Community

#48372 Move asset synchronization to IRemoteAssetSynchronizationService
  eng/targets/Services.props
  src/VisualStudio/Core/Test.Next/Services/LanguageServiceTests.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemostHostClient.cs
  src/Workspaces/Remote/Core/IRemoteAssetSynchronizationService.cs
  src/Workspaces/Remote/Core/IRemoteHostService.cs
  src/Workspaces/Remote/Core/RemoteWorkspacesResources.resx
  src/Workspaces/Remote/Core/ServiceDescriptors.cs
  src/Workspaces/Remote/Core/SolutionChecksumUpdater.cs
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.cs.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.de.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.es.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.fr.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.it.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ja.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ko.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.pl.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.pt-BR.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ru.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.tr.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.zh-Hans.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.zh-Hant.xlf
  src/Workspaces/Remote/ServiceHub/Services/Host/RemoteAssetSynchronizationService.cs
  src/Workspaces/Remote/ServiceHub/Services/Host/RemoteHostService.cs
Labels: Approved to merge, Area-IDE

#48375 Delete the CachedProximityExpressionsGetter and all the support code
  src/EditorFeatures/CSharpTest/Debugging/ProximityExpressionsGetterTests_Caching.cs
  src/EditorFeatures/Core/Implementation/Debugging/CachedProximityExpressionsGetter.cs
  src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractLanguageService`2.IVsDebuggerEvents.cs
  src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractLanguageService`2.VsLanguageDebugInfo.cs
  src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractLanguageService`2.cs
Labels: Area-IDE

#48529 Expose inline-hints through an external-access layer for F#.
  src/Tools/ExternalAccess/FSharp/InlineHints/FSharpInlineHint.cs
  src/Tools/ExternalAccess/FSharp/InlineHints/IFSharpInlineHintsService.cs
  src/Tools/ExternalAccess/FSharp/Internal/InlineHints/FSharpInlineHintsService.cs
Labels: auto-merge

#48428 Extract MEF-shared helper SQLiteConnectionPoolService
  src/Tools/IdeBenchmarks/SQLitePersistentStorageBenchmark.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/AbstractPersistentStorageTests.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/SQLiteV1PersistentStorageTests.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/SQLiteV2PersistentStorageTests.cs
  src/Workspaces/Core/Portable/Storage/PersistenceStorageServiceFactory.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v1/Interop/SqlConnection.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/Interop/SqlConnection.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/Interop/SqlStatement.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPool+PooledConnection.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPool.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.Accessor.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorageService.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_BulkPopulateIds.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_FlushWrites.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_Threading.cs
Labels: Approved to merge, Area-IDE

#48536 Make GreenNode.CreateList static
  src/Compilers/Core/Portable/Syntax/GreenNode.cs
  src/Compilers/Core/Portable/Syntax/SyntaxList`1.cs
  src/Compilers/Core/Portable/Syntax/SyntaxNodeOrTokenList.cs
  src/Compilers/Core/Portable/Syntax/SyntaxToken.cs
  src/Compilers/Core/Portable/Syntax/SyntaxTokenList.cs
  src/Compilers/Core/Portable/Syntax/SyntaxTriviaList.cs
Labels: Area-Compilers, Community

#48359 Fixed documentation comment ID handling for dynamic and tuples
  src/Compilers/Core/CodeAnalysisTest/Diagnostics/SuppressMessageAttributeCompilerTests.cs
  src/Compilers/Core/CodeAnalysisTest/Symbols/DocumentationCommentIdTests.cs
  src/Compilers/Core/Portable/DocumentationCommentId.cs
  src/Compilers/Core/Portable/Symbols/SymbolEqualityComparer.cs
  src/Test/Utilities/Portable/Diagnostics/SuppressMessageAttributeTests.cs
Labels: Area-Compilers, Community

#48506 Update F1 keywords to disambiguate `class`
  src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs
  src/VisualStudio/CSharp/Test/F1Help/F1HelpTests.cs
Labels: Area-IDE, Community

#48562 Process lsp diagnostic requests serially to prevent state corruption
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs
  src/VisualStudio/Core/Test.Next/Services/LspDiagnosticsTests.cs
Labels: auto-merge

#48576 RPS Workaround
  src/Workspaces/Remote/Core/ServiceHubRemoteHostClient.cs
Labels: Area-Infrastructure, auto-merge

#48558 Move the IDocumentationCommentSnippetService down to the Features layer
  src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs
  src/EditorFeatures/Core/Shared/Options/FeatureOnOffOptions.cs
  src/EditorFeatures/TestUtilities/DocumentationComments/AbstractDocumentationCommentTests.cs
  src/Features/CSharp/Portable/DocumentationComments/DocumentationCommentSnippetService.cs
  src/Features/Core/Portable/DocumentationComments/AbstractDocumentationCommentSnippetService.cs
  src/Features/Core/Portable/DocumentationComments/DocumentationCommentOptions.cs
  src/Features/Core/Portable/DocumentationComments/DocumentationCommentSnippet.cs
  src/Features/Core/Portable/DocumentationComments/IDocumentationCommentSnippetService.cs
  src/Features/LanguageServer/Protocol/Handler/OnAutoInsert/OnAutoInsertHandler.cs
  src/Features/VisualBasic/Portable/DocumentationComments/DocumentationCommentSnippetService.vb
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/AutomationObject.cs
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/VisualStudio/VisualBasic/Impl/Options/AutomationObject.vb
Labels: Area-IDE

#48467 Add support for LSP code action grouping
  eng/Versions.props
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs
  src/Features/Core/Portable/CodeFixes/AbstractConfigurationActionWithNestedActions.cs
  src/Features/Core/Portable/CodeFixes/Configuration/ConfigureSeverity/ConfigureSeverityLevelCodeFixProvider.TopLevelBulkConfigureSeverityCodeAction.cs
  src/Features/Core/Portable/CodeFixes/Suppression/NestedSuppressionCodeAction.cs
  src/Features/Core/Portable/UnifiedSuggestions/UnifiedSuggestedActionSetPriority.cs
  src/Features/Core/Portable/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs
  src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionHelpers.cs
  src/Features/LanguageServer/ProtocolUnitTests/CodeActions/CodeActionResolveTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/CodeActions/CodeActionsTests.cs
  src/Workspaces/Core/Portable/CodeActions/CodeActionPriority.cs
Labels: Area-IDE, CloudEnv

#48555 Do not start a new comment when hitting enter before an existing comment
  src/EditorFeatures/CSharpTest/SplitComment/SplitCommentCommandHandlerTests.cs
  src/EditorFeatures/Core/Implementation/SplitComment/SplitCommentCommandHandler.cs
  src/EditorFeatures/VisualBasicTest/SplitComment/SplitCommentCommandHandlerTests.vb
Labels: Area-IDE, auto-merge

#48137 Support init accessor in CSharpSyntaxFacts
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
Labels: Area-IDE, Community

#48560 Update sqlite experiment name.
  src/Workspaces/Core/Portable/Experiments/IExperimentationService.cs
  src/Workspaces/Core/Portable/Storage/PersistenceStorageServiceFactory.cs
Labels: Approved to merge, Area-IDE

#48514 Add support for `init` accessor in debugging
  src/EditorFeatures/CSharpTest/Debugging/ProximityExpressionsGetterTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/BreakpointSpansTests.cs
  src/Features/CSharp/Portable/Debugging/CSharpProximityExpressionsService.Worker.cs
  src/Features/CSharp/Portable/EditAndContinue/BreakpointSpans.cs
Labels: Area-IDE, Community

#48544 Update config file
  eng/Versions.props
  eng/config/PublishData.json
Labels: Area-Infrastructure

#48390 Make sure to yield when waiting in SetActiveTreeAnalysisTaskAsync
  src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs
  src/Compilers/Core/Portable/InternalUtilities/ConfiguredYieldAwaitable.cs
  src/Compilers/Core/Portable/InternalUtilities/YieldAwaitableExtensions.cs
Labels: Area-Compilers, Urgency-Soon

#48226 IOperation Refactor Pt 1
  Compilers.slnf
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs
  src/Analyzers/Core/Analyzers/SimplifyInterpolation/Helpers.cs
  src/Analyzers/Core/CodeFixes/PopulateSwitch/AbstractPopulateSwitchExpressionCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/PopulateSwitch/AbstractPopulateSwitchStatementCodeFixProvider.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs
  src/Compilers/Core/Portable/Generated/Operations.Generated.cs
  src/Compilers/Core/Portable/Operations/IOperation.cs
  src/Compilers/Core/Portable/Operations/Operation.cs
  src/Compilers/Core/Portable/Operations/OperationNodes.cs
  src/Compilers/Core/Portable/Operations/OperationOld.cs
  src/Features/CSharp/Portable/ConvertIfToSwitch/CSharpConvertIfToSwitchCodeRefactoringProvider.Rewriting.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/CompilersIOperationGenerator.csproj
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/IOperationClassWriter.PortedTypes.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/IOperationClassWriter.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/Model.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/Program.cs
Labels: Area-Compilers

#48589 Merge release/dev16.9 into release/dev16.9-vs-deps
  eng/targets/Services.props
  src/Tools/IdeBenchmarks/SQLitePersistentStorageBenchmark.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/AbstractPersistentStorageTests.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/SQLiteV1PersistentStorageTests.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/SQLiteV2PersistentStorageTests.cs
  src/VisualStudio/Core/Test.Next/Services/LanguageServiceTests.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/Workspaces/Core/Portable/Storage/PersistenceStorageServiceFactory.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v1/Interop/SqlConnection.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/Interop/SqlConnection.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/Interop/SqlStatement.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPool+PooledConnection.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPool.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.Accessor.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorageService.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_BulkPopulateIds.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_FlushWrites.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_Threading.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemostHostClient.cs
  src/Workspaces/Remote/Core/IRemoteAssetSynchronizationService.cs
  src/Workspaces/Remote/Core/IRemoteHostService.cs
  src/Workspaces/Remote/Core/RemoteWorkspacesResources.resx
  src/Workspaces/Remote/Core/ServiceDescriptors.cs
  src/Workspaces/Remote/Core/ServiceHubRemoteHostClient.cs
  src/Workspaces/Remote/Core/SolutionChecksumUpdater.cs
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.cs.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.de.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.es.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.fr.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.it.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ja.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ko.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.pl.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.pt-BR.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ru.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.tr.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.zh-Hans.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.zh-Hant.xlf
  src/Workspaces/Remote/ServiceHub/Services/Host/RemoteAssetSynchronizationService.cs
  src/Workspaces/Remote/ServiceHub/Services/Host/RemoteHostService.cs
Labels: Area-Infrastructure, auto-merge

#48585 Correct IL for `ptr is null`
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_FixedStatement.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/FunctionPointerTests.cs
Labels: Area-Compilers

#48570 Apply MemberNotNull
  src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StringConcat.cs
  src/Compilers/CSharp/Portable/Symbols/Attributes/AttributeData.cs
  src/Compilers/CSharp/Portable/Symbols/Attributes/PEAttributeData.cs
  src/Compilers/CSharp/Portable/Symbols/Attributes/SourceAttributeData.cs
  src/Compilers/CSharp/Portable/Symbols/TypeWithState.cs
  src/Compilers/CSharp/Portable/Symbols/TypedConstantExtensions.cs
  src/Compilers/Core/Portable/ConstantValue.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs
  src/Compilers/Core/Portable/ReferenceManager/CommonReferenceManager.State.cs
  src/Compilers/Core/Portable/Symbols/Attributes/CommonAttributeData.cs
  src/Compilers/Core/Portable/Symbols/IFieldSymbol.cs
  src/Compilers/Core/Portable/Syntax/ChildSyntaxList.Enumerator.cs
  src/Compilers/Core/Portable/Syntax/ChildSyntaxList.Reversed.cs
Labels: Area-Compilers, Concept-Null Annotations

#48554 Fix crash in Extract Method
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodBase.cs
  src/EditorFeatures/CSharpTest/ExtractMethod/SelectionValidatorTests.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionValidator.cs
Labels: Area-IDE

#48400 Don't crash if you reference a generator built against .NET Framework
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Errors/MessageProvider.cs
  src/Compilers/CSharp/Portable/Generated/ErrorFacts.Generated.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
  src/Compilers/Core/CodeAnalysisTest/Analyzers/AnalyzerFileReferenceTests.cs
  src/Compilers/Core/Portable/CommandLine/CommandLineArguments.cs
  src/Compilers/Core/Portable/Diagnostic/CommonMessageProvider.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs
  src/Compilers/VisualBasic/Portable/Errors/MessageProvider.vb
  src/EditorFeatures/Test/Diagnostics/AnalyzerLoadFailureTests.cs
  src/Features/Core/Portable/Diagnostics/AnalyzerHelper.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Test/Utilities/Portable/Mocks/TestMessageProvider.cs
Labels: Approved to merge, Area-IDE

#48583 Add skipped regression test for asset synchronization failure
  src/VisualStudio/Core/Test.Next/Mocks/SimpleAssetSource.cs
  src/VisualStudio/Core/Test.Next/Services/AssetProviderTests.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/VisualStudio/Core/Test.Next/Services/SolutionServiceTests.cs
  src/Workspaces/CSharp/Portable/Serialization/CSharpOptionsSerializationService.cs
  src/Workspaces/VisualBasic/Portable/Serialization/VisualBasicOptionsSerializationService.vb
Labels: Area-IDE

#48460 Null annotate VBCSCompiler
  src/Compilers/CSharp/Portable/CommandLine/CSharpCompiler.cs
  src/Compilers/Core/CommandLine/BuildProtocol.cs
  src/Compilers/Core/MSBuildTask/ManagedCompiler.cs
  src/Compilers/Core/Portable/AdditionalTextFile.cs
  src/Compilers/Core/Portable/CommandLine/AnalyzerConfig.cs
  src/Compilers/Core/Portable/CommandLine/CommonCompiler.LoggingStrongNameProvider.cs
  src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs
  src/Compilers/Core/Portable/StrongName/StrongNameFileSystem.cs
  src/Compilers/Server/VBCSCompiler/AnalyzerConsistencyChecker.cs
  src/Compilers/Server/VBCSCompiler/Assembly.cs
  src/Compilers/Server/VBCSCompiler/BuildProtocolUtil.cs
  src/Compilers/Server/VBCSCompiler/BuildServerController.cs
  src/Compilers/Server/VBCSCompiler/CSharpCompilerServer.cs
  src/Compilers/Server/VBCSCompiler/CompilerRequestHandler.cs
  src/Compilers/Server/VBCSCompiler/DiagnosticListener.cs
  src/Compilers/Server/VBCSCompiler/ICompilerServerHost.cs
  src/Compilers/Server/VBCSCompiler/MemoryHelper.cs
  src/Compilers/Server/VBCSCompiler/MetadataCache.cs
  src/Compilers/Server/VBCSCompiler/VBCSCompiler.cs
  src/Compilers/Server/VBCSCompiler/VisualBasicCompilerServer.cs
  src/Compilers/Server/VBCSCompilerTests/BuildClientTests.cs
  src/Compilers/Server/VBCSCompilerTests/ServerUtil.cs
  src/Compilers/Server/VBCSCompilerTests/TouchedFileLoggingTests.cs
  src/Compilers/Server/VBCSCompilerTests/VBCSCompilerServerTests.cs
  src/Compilers/Shared/BuildClient.cs
  src/Compilers/Shared/BuildServerConnection.cs
  src/Compilers/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.vbproj
  src/Compilers/VisualBasic/Test/CommandLine/TouchedFileLoggingTests.vb
Labels: Area-Compilers, Concept-Null Annotations

#48626 Fix link
  .github/ISSUE_TEMPLATE/analyzer-suggestion.md
Labels: Area-IDE, Community

#48306 Don't trigger naming style violation for prefixed numbers.
  src/Analyzers/CSharp/Tests/NamingStyles/NamingStylesTests.cs
  src/Analyzers/Core/Analyzers/NamingStyle/NamingStyleDiagnosticAnalyzerBase.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ISymbolExtensions.cs
Labels: Area-IDE, Community, auto-merge

#48648 Fix UnmanagedCallingConventions test reliability
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs
Labels: Area-Compilers, auto-merge

#48459 Fix XAML LSP by switching to regular documents
  src/VisualStudio/Xaml/Impl/Diagnostics/Analyzers/XamlDocumentDiagnosticAnalyzer.cs
  src/VisualStudio/Xaml/Impl/Extensions.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageClient/XamlLanguageServerClient.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Extensions/SymbolExtensions.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Completion/CompletionHandler.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Completion/CompletionResolveHandler.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Hover/HoverHandler.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/OnAutoInsert/OnAutoInsertHandler.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/XamlSolutionProvider.cs
  src/VisualStudio/Xaml/Impl/Implementation/XamlProjectService.cs
  src/VisualStudio/Xaml/Impl/Implementation/XamlProjectService_IVsRunningDocTableEvents3.cs
  src/VisualStudio/Xaml/Impl/Implementation/XamlProjectService_IVsSolutionEvents.cs
  src/VisualStudio/Xaml/Impl/Implementation/XamlTextViewCreationListener.cs
Labels: Area-IDE

#48608 IOperation Node Porting: Leaf Nodes
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IIsPatternExpression.cs
  src/Compilers/Core/Portable/Generated/FlowAnalysis.Generated.cs
  src/Compilers/Core/Portable/Generated/Operations.Generated.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.ImplicitInstanceInfo.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/Operations/Operation.cs
  src/Compilers/Core/Portable/Operations/OperationCloner.cs
  src/Compilers/Core/Portable/Operations/OperationInterfaces.xml
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/IOperationClassWriter.PortedTypes.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/IOperationClassWriter.Verifier.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/IOperationClassWriter.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/Model.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/Program.cs
Labels: Area-Compilers, Feature - IOperation, auto-merge

#48289 implement remove 'Shared' from VB module members codefix
  src/EditorFeatures/VisualBasicTest/RemoveSharedFromModuleMembers/RemoveSharedFromModuleMembersTests.vb
  src/Features/VisualBasic/Portable/RemoveSharedFromModuleMembers/VisualBasicRemoveSharedFromModuleMembersCodeFixProvider.vb
  src/Features/VisualBasic/Portable/VBFeaturesResources.resx
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.cs.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.de.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.es.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.fr.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.it.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.ja.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.ko.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.pl.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.pt-BR.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.ru.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.tr.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.zh-Hans.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.zh-Hant.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE, Community, Feature Request

#48606 Remove active view infobars
  src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs
  src/EditorFeatures/Core/Implementation/EditorLayerExtensionManager.cs
  src/EditorFeatures/Core/Implementation/InfoBar/EditorInfoBarService.cs
  src/EditorFeatures/Core/Implementation/Workspaces/EditorErrorReportingService.cs
  src/VisualStudio/Core/Def/Implementation/Diagnostics/FxCopAnalyzersSuggestedActionCallback.cs
  src/VisualStudio/Core/Def/Implementation/Experimentation/KeybindingResetDetector.cs
  src/VisualStudio/Core/Def/Implementation/InfoBar/VisualStudioInfoBarService.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/AnalyzerConfigDocumentAsSolutionItemHandler.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioErrorReportingService.cs
  src/Workspaces/Core/Portable/ExtensionManager/IErrorReportingService.cs
  src/Workspaces/Core/Portable/ExtensionManager/IInfoBarService.cs
  src/Workspaces/CoreTestUtilities/TestErrorReportingService.cs
Labels: Area-IDE, auto-merge

#48623 Handle unchanged value in SerializableOptionSet.WithChangedOption
  src/VisualStudio/Core/Test.Next/Services/SolutionServiceTests.cs
  src/Workspaces/Core/Portable/Options/SerializableOptionSet.cs
Labels: Area-IDE, auto-merge

#48660 Update F1 keywords to detect `using static` combination
  src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs
  src/VisualStudio/CSharp/Test/F1Help/F1HelpTests.cs
Labels: Area-IDE, Community

#48538 Report error for native integer token as using name or alias target
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NativeIntegerTests.cs
Labels: Area-Compilers, New Language Feature - Native Int

#48625 Clean up build configuration
  Roslyn.sln
Labels: Area-Infrastructure

#48580 Make the ':severity' suffix in editorconfig code style value optional
  src/Analyzers/CSharp/Tests/UseExpressionBody/UseExpressionBodyForMethodsAnalyzerTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/Configuration/ConfigureCodeStyle/BooleanCodeStyleOptionConfigurationTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/Configuration/ConfigureCodeStyle/EnumCodeStyleOptionConfigurationTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/Configuration/ConfigureCodeStyle/MultipleCodeStyleOptionConfigurationTests.cs
  src/EditorFeatures/Test/Diagnostics/IDEDiagnosticIDConfigurationTests.cs
  src/EditorFeatures/VisualBasicTest/Diagnostics/Configuration/ConfigureCodeStyle/BooleanCodeStyleOptionConfigurationTests.vb
  src/Features/Core/Portable/CodeFixes/Configuration/ConfigurationUpdater.cs
  src/Features/Core/Portable/CodeFixes/Configuration/ConfigureCodeStyle/ConfigureCodeStyleOptionCodeFixProvider.cs
  src/VisualStudio/Core/Test/Options/BasicEditorConfigGeneratorTests.vb
  src/VisualStudio/Core/Test/Options/CSharpEditorConfigGeneratorTests.vb
  src/Workspaces/CSharpTest/CodeStyle/CSharpEditorConfigCodeStyleParserTests.cs
  src/Workspaces/CoreTest/CodeStyle/EditorConfigCodeStyleParserTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeStyle/CSharpCodeStyleOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeStyle/CSharpCodeStyleOptions_Parsing.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/CodeStyleHelpers.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/CodeStyleOptions2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/OperatorPlacementWhenWrappingPreference.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/StringExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Options/EditorConfig/EditorConfigStorageLocation.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/CodeStyle/VisualBasicCodeStyleOptions.vb
Labels: Area-IDE

#48642 More static local function tests
  src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs
Labels: Area-Compilers, Test

#48624 Use vs-mef for OOP compositions
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/Workspaces/CoreTestUtilities/MEF/TestComposition.cs
  src/Workspaces/CoreTestUtilities/Roslyn.Services.UnitTests.Utilities.csproj
  src/Workspaces/Remote/Core/Microsoft.CodeAnalysis.Remote.Workspaces.csproj
  src/Workspaces/Remote/Core/VisualStudioMefHostServices.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspaceManager.cs
Labels: Area-IDE

#48650 Ensure WaitUntilFullyLoadedAsync can make progress from a background thread
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioWorkspaceStatusServiceFactory.cs
Labels: Area-IDE

#48678 Avoid realizing the entire solution snapshot in the Sql layer.
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_BulkPopulateIds.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_DocumentIds.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_ProjectIds.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/ProjectKey.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/SolutionKey.cs
Labels: Area-IDE, auto-merge

#48695 Remove unused myget token
  azure-pipelines-official.yml
Labels: Area-Infrastructure, auto-merge

#48614 Support running official build in dnceng
  azure-pipelines-official.yml
  eng/build.ps1
  eng/update-build-number.ps1
Labels: Area-Infrastructure

#48690 Add official build pipeline in dnceng for 16.7 branch
  azure-pipelines-official.yml
  eng/build.ps1
  eng/update-build-number.ps1
Labels: Area-Infrastructure

#48691 Add official build pipeline in dnceng for 16.8 branch
  azure-pipelines-official.yml
  eng/build.ps1
  eng/update-build-number.ps1
Labels: Area-Infrastructure

#48692 Add official build pipeline in dnceng for 16.9 branch
  azure-pipelines-official.yml
  eng/build.ps1
  eng/update-build-number.ps1
Labels: Area-Infrastructure

#48677 Enable nullable reference types for shared utilities
  src/EditorFeatures/Core/Implementation/SplitComment/SplitCommentCommandHandler.cs
  src/EditorFeatures/Core/Shared/Utilities/AutomaticCodeChangeMergePolicy.cs
  src/EditorFeatures/Core/Shared/Utilities/CaretPreservingEditTransaction.cs
  src/EditorFeatures/Core/Shared/Utilities/ClassificationTypeMap.cs
  src/EditorFeatures/Core/Shared/Utilities/CommonFormattingHelpers.cs
  src/EditorFeatures/Core/Shared/Utilities/ForegroundThreadAffinitizedObject.cs
  src/EditorFeatures/Core/Shared/Utilities/HACK_TextUndoTransactionThatRollsBackProperly.cs
  src/EditorFeatures/Core/Shared/Utilities/LinkedEditsTracker.cs
  src/EditorFeatures/Core/Shared/Utilities/NativeMethods.cs
  src/EditorFeatures/Core/Shared/Utilities/ProgressTrackerAdapter.cs
  src/EditorFeatures/Core/Shared/Utilities/RenameTrackingDismisser.cs
  src/EditorFeatures/Core/Shared/Utilities/ResettableDelay.cs
  src/EditorFeatures/Core/Shared/Utilities/VirtualTreePoint.cs
Labels: Area-IDE, Concept-Null Annotations

#48699 Disable LSP package manager code actions
  src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionHelpers.cs
Labels: Area-IDE, CloudEnv

#47077 Raise the default warning level in tests
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_IsUnmanaged.cs
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_Synthesized.cs
  src/Compilers/CSharp/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncMainTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenDisplayClassOptimisationTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOptimizedNullableOperators.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs
  src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/DeterministicTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs
  src/Compilers/CSharp/Test/Semantic/FlowAnalysis/StructTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/ArglistTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DynamicTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NameCollisionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests2.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/StackAllocInitializerTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/StackAllocSpanExpressionsTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/TopLevelStatementsTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/WarningVersionTests.cs
  src/Compilers/CSharp/Test/Symbol/Compilation/CompilationAPITests.cs
  src/Compilers/CSharp/Test/Symbol/Compilation/ReferenceManagerTests.cs
  src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs
  src/Compilers/CSharp/Test/Symbol/DeclarationTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/AssemblyAndNamespaceTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/ExtensionMethodTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/GenericConstraintTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Metadata/MetadataMemberTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/ExternAliasTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/PropertyTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ParserErrorMessageTests.cs
  src/Compilers/CSharp/Test/WinRT/Metadata/WinMdEventTests.cs
  src/Compilers/Core/CodeAnalysisTest/Analyzers/AnalyzerFileReferenceAppDomainTests.cs
  src/Compilers/Core/CodeAnalysisTest/CorLibTypesTests.cs
  src/Compilers/Core/CodeAnalysisTest/Diagnostics/CompilationWithAnalyzersTests.cs
  src/Compilers/Core/CodeAnalysisTest/ShadowCopyAnalyzerAssemblyLoaderTests.cs
  src/Compilers/Core/Portable/Diagnostic/Diagnostic.cs
  src/Compilers/Server/VBCSCompilerTests/AnalyzerConsistencyCheckerTests.cs
  src/Compilers/Test/Utilities/CSharp/TestOptions.cs
Labels: Area-Compilers, Community

#48577 Fix null-annotatation of ISerializerService.Deserialize
  src/Compilers/Core/Portable/InternalUtilities/Debug.cs
  src/VisualStudio/Core/Test.Next/Mocks/SimpleAssetSource.cs
  src/VisualStudio/Core/Test.Next/Remote/SerializationValidator.cs
  src/Workspaces/Core/Portable/Remote/ISerializerService.cs
  src/Workspaces/Remote/Core/RemoteHostAssetSerialization.cs
  src/Workspaces/Remote/ServiceHub/Host/AssetProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/ChecksumSynchronizer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Contract.cs
Labels: Area-Compilers, Area-IDE

#47081 Call AsyncIteratorMethodBuilder.Complete before SetResult
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncIteratorMethodToStateMachineRewriter.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs
Labels: Area-Compilers, New Feature - Async Streams

#48710 Enable nullable reference types in EditorFeatures.Text
  src/EditorFeatures/Core.Wpf/InlineRename/InlineRenameService.cs
  src/EditorFeatures/Text/ContentTypeNames.cs
  src/EditorFeatures/Text/Extensions.SnapshotSourceText.cs
  src/EditorFeatures/Text/Extensions.TextBufferContainer.cs
  src/EditorFeatures/Text/Implementation/TextBufferFactoryService/ITextBufferCloneService.cs
  src/EditorFeatures/Text/Implementation/TextBufferFactoryService/TextBufferCloneServiceFactory.cs
  src/EditorFeatures/Text/PublicAPI.Shipped.txt
  src/EditorFeatures/Text/Shared/Extensions/ITextSnapshotExtensions.cs
  src/EditorFeatures/Text/Shared/Extensions/ITextSnapshotLineExtensions.cs
  src/EditorFeatures/Text/Shared/Extensions/SnapshotPointExtensions.cs
  src/EditorFeatures/Text/Shared/Extensions/TextSpanExtensions.cs
  src/EditorFeatures/Text/TextEditorResources.resx
  src/EditorFeatures/Text/xlf/TextEditorResources.cs.xlf
  src/EditorFeatures/Text/xlf/TextEditorResources.de.xlf
  src/EditorFeatures/Text/xlf/TextEditorResources.es.xlf
  src/EditorFeatures/Text/xlf/TextEditorResources.fr.xlf
  src/EditorFeatures/Text/xlf/TextEditorResources.it.xlf
  src/EditorFeatures/Text/xlf/TextEditorResources.ja.xlf
  src/EditorFeatures/Text/xlf/TextEditorResources.ko.xlf
  src/EditorFeatures/Text/xlf/TextEditorResources.pl.xlf
  src/EditorFeatures/Text/xlf/TextEditorResources.pt-BR.xlf
  src/EditorFeatures/Text/xlf/TextEditorResources.ru.xlf
  src/EditorFeatures/Text/xlf/TextEditorResources.tr.xlf
  src/EditorFeatures/Text/xlf/TextEditorResources.zh-Hans.xlf
  src/EditorFeatures/Text/xlf/TextEditorResources.zh-Hant.xlf
Labels: Area-IDE, Concept-Null Annotations

#48277 Remove unneeded suppression
  src/Scripting/CoreTestUtilities/ObjectFormatterFixtures/MockDesktopSpinLock.cs
Labels: Area-IDE, Community

#48502 Refactoring provider to convert regular string to interpolated string
  src/EditorFeatures/CSharpTest/ConvertToInterpolatedString/ConvertRegularStringToInterpolatedStringTests.cs
  src/EditorFeatures/VisualBasicTest/ConvertToInterpolatedString/ConvertRegularStringToInterpolatedStringTests.vb
  src/Features/CSharp/Portable/ConvertBetweenRegularAndVerbatimString/ConvertBetweenRegularAndVerbatimInterpolatedStringCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/ConvertBetweenRegularAndVerbatimString/ConvertBetweenRegularAndVerbatimStringCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertToInterpolatedString/ConvertRegularStringToInterpolatedStringRefactoringProvider.cs
Labels: Area-IDE, Community, Feature Request

#48685 Add support for an lsp language client to specify which capabilities they support.
  src/Features/LanguageServer/Protocol/Handler/Initialize/InitializeHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Initialize/InitializeTests.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/AbstractInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/DefaultCapabilitiesProvider.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/LiveShareInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/RazorInProcLanguageClient.cs
  src/VisualStudio/Core/Test.Next/Services/LspDiagnosticsTests.cs
  src/VisualStudio/LiveShare/Impl/Shims/TypeScriptHandlerShims.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageClient/XamlInProcLanguageClient.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Initialize/InitializeHandler.cs
Labels: auto-merge

#48725 fix invalid code snippet in "Adding optional parameters to public methods
  docs/Adding Optional Parameters in Public API.md
Labels: Area-IDE, Community

#48747 Fix the initialize contract assertion
  src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs
Labels: Area-IDE, auto-merge

#48748 Add an abstraction for either reporting an array or results, or streaming them in LSP scenarios.
  src/Features/LanguageServer/Protocol/Handler/BufferedProgress.cs
Labels: auto-merge

#48531 Update ExtractMethod to work correctly for records
  src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractMethodTests.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.CallSiteContainerRewriter.cs
Labels: Area-IDE, Community, New Language Feature - Records

#48647 Warn on uninitialized fields for struct constructor with `: this()` clause
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/UninitializedNonNullableFieldTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/NullablePublicAPITests.cs
  src/Compilers/Core/Portable/Collections/SmallDictionary.cs
  src/Workspaces/Core/Portable/Rename/ConflictResolution.cs
Labels: Area-Compilers

#48342 Add ValueTaskFactory helpers
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AsyncQueue.cs
  src/Compilers/Core/Portable/InternalUtilities/ValueTaskFactory.cs
  src/EditorFeatures/CSharpTest/AddUsing/AddUsingNuGetTests.cs
  src/EditorFeatures/Core/GoToBase/FindBaseHelpers.cs
  src/EditorFeatures/Core/SymbolSearch/SymbolSearchUpdateEngine.cs
  src/EditorFeatures/Core/SymbolSearch/SymbolSearchUpdateEngineFactory.cs
  src/EditorFeatures/VisualBasicTest/Diagnostics/AddImport/AddImportTests_NuGet.vb
  src/Features/Core/Portable/Diagnostics/AnalyzerHelper.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.ProjectState.cs
  src/Features/VisualBasic/Portable/SignatureHelp/AddRemoveHandlerSignatureHelpProvider.vb
  src/Features/VisualBasic/Portable/SignatureHelp/CastExpressionSignatureHelpProvider.vb
  src/Features/VisualBasic/Portable/SignatureHelp/ConditionalExpressionSignatureHelpProvider.vb
  src/Features/VisualBasic/Portable/SignatureHelp/MidAssignmentSignatureHelpProvider.vb
  src/VisualStudio/Core/Def/Implementation/DesignerAttribute/VisualStudioDesignerAttributeService.cs
  src/VisualStudio/Core/Def/Implementation/ProjectTelemetry/VisualStudioProjectTelemetryService.cs
  src/VisualStudio/Core/Def/Implementation/Remote/VisualStudioRemoteHostClientProvider.cs
  src/VisualStudio/Core/Test.Next/Mocks/SimpleAssetSource.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamedTypeSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/SymbolSearch/ISymbolSearchService.cs
  src/Workspaces/CoreTest/UtilityTest/SpecializedTasksTests.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemostHostClient.cs
  src/Workspaces/Remote/Core/SolutionAssetProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/SpecializedTasks.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Utilities/AsyncSymbolVisitor`1.cs
Labels: Area-Compilers

#48689 Add null check for _proximityExpressionsService
  src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractLanguageService`2.VsLanguageDebugInfo.cs
Labels: Area-IDE

#48397 Fix WarningLevel for hidden diagnostics
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Test/Symbol/Compilation/GetUnusedImportDirectivesTests.cs
  src/Compilers/Core/Portable/Diagnostic/Diagnostic.cs
Labels: Area-Compilers, Community

#48763 Support inline hints for declaration expressions.
  src/EditorFeatures/Test2/InlineHints/AbstractInlineHintsTests.vb
  src/EditorFeatures/Test2/InlineHints/CSharpInlineTypeHintsTests.vb
  src/Features/CSharp/Portable/InlineHints/CSharpInlineTypeHintsService.cs
Labels: Area-IDE, auto-merge

#48717 Remove custom handling of back and forward buttons
  src/VisualStudio/Core/Def/Implementation/AbstractOleCommandTarget.Execute.cs
  src/VisualStudio/Core/Def/Implementation/AbstractOleCommandTarget.Query.cs
Labels: Area-IDE, Concept-Continuous Improvement

#47678 fix link to proposal in csharplang
  docs/features/DefaultInterfaceImplementation.md
Labels: Area-Compilers, Documentation

#48768 Remove unnecessary ConditionalWeakTable from SemanticClassificationUtilities
  src/EditorFeatures/Core/Implementation/Classification/SemanticClassificationUtilities.cs
Labels: Area-IDE

#48465 Run a few FindAllDeclarations tests OOP.
  Roslyn.sln
  src/Workspaces/CoreTest/FindAllDeclarationsTests.TestSolutionsAndProject.cs
  src/Workspaces/CoreTest/FindAllDeclarationsTests.cs
Labels: Area-IDE

#48709 Disallow completion keywords after numeric literal
  src/EditorFeatures/CSharpTest2/Recommendations/AsKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/IsKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/SwitchKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/WithKeywordRecommenderTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs
Labels: Area-IDE, CloudEnv

#48556 Remove #nullable-disable from part of the workspace
  src/Features/CSharp/Portable/MakeLocalFunctionStatic/MakeLocalFunctionStaticCodeFixHelper.cs
  src/Features/Core/Portable/ImplementAbstractClass/ImplementAbstractClassData.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/ExpressionGenerator.cs
  src/Workspaces/Core/Portable/CodeGeneration/AbstractCodeGenerationService.cs
  src/Workspaces/Core/Portable/CodeGeneration/AbstractCodeGenerationService_FindDeclaration.cs
  src/Workspaces/Core/Portable/CodeGeneration/AbstractFlagsEnumGenerator.cs
  src/Workspaces/Core/Portable/CodeGeneration/CodeGenerationDestination.cs
  src/Workspaces/Core/Portable/CodeGeneration/CodeGenerationHelpers.cs
  src/Workspaces/Core/Portable/CodeGeneration/CodeGenerationOperatorKind.cs
  src/Workspaces/Core/Portable/CodeGeneration/CodeGenerationOptions.cs
  src/Workspaces/Core/Portable/CodeGeneration/CodeGenerationSymbolFactory.cs
  src/Workspaces/Core/Portable/CodeGeneration/CodeGenerator.cs
  src/Workspaces/Core/Portable/CodeGeneration/ICodeGenerationService.cs
  src/Workspaces/Core/Portable/CodeGeneration/INamedTypeSymbolExtensions.cs
  src/Workspaces/Core/Portable/CodeGeneration/LiteralSpecialValues.cs
  src/Workspaces/Core/Portable/CodeGeneration/NullableSyntaxAnnotation.cs
  src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationEventSymbol.cs
  src/Workspaces/Core/Portable/CodeGeneration/SyntaxAnnotationExtensions.cs
  src/Workspaces/Core/Portable/CodeGeneration/TypeGenerator.cs
  src/Workspaces/VisualBasic/Portable/CodeGeneration/ExpressionGenerator.vb
Labels: Area-IDE, auto-merge

#48349 Type unification of native integer types and underlying types
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Bases.cs
  src/Compilers/CSharp/Portable/Symbols/TypeUnification.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NativeIntegerTests.cs
Labels: Area-Compilers, New Language Feature - Native Int

#48753 Update LSP handlers to make streaming results optional, or possible
  src/Features/LanguageServer/Protocol/CustomProtocol/FindUsagesLSPContext.cs
  src/Features/LanguageServer/Protocol/Handler/BufferedProgress.cs
  src/Features/LanguageServer/Protocol/Handler/References/FindAllReferencesHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Symbols/WorkspaceSymbolsHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/References/FindAllReferencesHandlerTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Symbols/WorkspaceSymbolsTests.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs
  src/VisualStudio/Core/Test.Next/Services/RemoteLanguageServerTests.cs
  src/Workspaces/Remote/ServiceHub/Services/RemoteLanguageServer/RemoteLanguageServer.cs
Labels: Area-IDE

#48770 Upgrade to .NET SDK 5.0 RC 2
  docs/contributing/Building, Debugging, and Testing on Windows.md
  eng/build.ps1
  global.json
  src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs
  src/Workspaces/MSBuildTest/Resources/global.json
Labels: Area-Infrastructure

#48777 Fix official build yaml for dnceng pipeline
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#48683 IOperation Node Porting: Non-Leaf Non-Hierarchy Nodes Pt1
  src/Analyzers/Core/Analyzers/UseSystemHashCode/Analyzer.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationNodes.cs
  src/Compilers/Core/CodeAnalysisTest/Diagnostics/OperationTests.cs
  src/Compilers/Core/Portable/Generated/Operations.Generated.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/Operations/Operation.cs
  src/Compilers/Core/Portable/Operations/OperationCloner.cs
  src/Compilers/Core/Portable/Operations/OperationInterfaces.xml
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationNodes.vb
  src/Features/CSharp/Portable/ConvertIfToSwitch/CSharpConvertIfToSwitchCodeRefactoringProvider.Rewriting.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/IOperationClassWriter.PortedTypes.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/IOperationClassWriter.cs
Labels: Area-Compilers, Feature - IOperation

#48627 Use MEF for callback dispatcher discovery
  src/Features/Core/Portable/AddImport/Remote/AbstractAddImportFeatureService_Remote.cs
  src/Features/Core/Portable/FindUsages/IRemoteFindUsagesService.cs
  src/VisualStudio/Core/Def/Implementation/Remote/VisualStudioRemoteHostClientProvider.cs
  src/Workspaces/Core/Portable/DesignerAttribute/IRemoteDesignerAttributeDiscoveryService.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder.CallbackDispatcher.cs
  src/Workspaces/Core/Portable/ProjectTelemetry/IRemoteProjectTelemetryService.cs
  src/Workspaces/Core/Portable/Remote/ExportRemoteServiceCallbackDispatcherAttribute.cs
  src/Workspaces/Core/Portable/Remote/RemoteServiceCallbackDispatcher.cs
  src/Workspaces/Core/Portable/Remote/RemoteServiceCallbackDispatchers.cs
  src/Workspaces/Core/Portable/Remote/RemoteServiceCallbackId.cs
  src/Workspaces/Core/Portable/SymbolSearch/SymbolSearchCallbackDispatcher.cs
  src/Workspaces/Core/Portable/TodoComments/IRemoteTodoCommentsService.cs
  src/Workspaces/CoreTest/Remote/ServiceDescriptorTests.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemostHostClient.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemoteHostClientProvider.cs
  src/Workspaces/Remote/Core/BrokeredServiceConnection.cs
  src/Workspaces/Remote/Core/ServiceDescriptor.cs
  src/Workspaces/Remote/Core/ServiceDescriptors.cs
  src/Workspaces/Remote/Core/ServiceHubRemoteHostClient.cs
Labels: Area-IDE

#48801 Remove unexpected exception from test
  src/EditorFeatures/CSharpTest/Squiggles/ErrorSquiggleProducerTests.cs
Labels: Area-IDE, auto-merge

#48805 [LSP] Disable snippets in Nexus
  src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetCommandHandler.cs
Labels: Area-IDE, CloudEnv, auto-merge

#48814 Generate constructor support implicit object creation
  src/EditorFeatures/CSharpTest/GenerateConstructor/GenerateConstructorTests.cs
  src/Features/CSharp/Portable/GenerateConstructor/CSharpGenerateConstructorService.cs
  src/Features/CSharp/Portable/GenerateConstructor/GenerateConstructorCodeFixProvider.cs
  src/Features/Core/Portable/GenerateMember/GenerateConstructor/AbstractGenerateConstructorService.State.cs
  src/Features/Core/Portable/GenerateMember/GenerateConstructor/AbstractGenerateConstructorService.cs
  src/Features/VisualBasic/Portable/GenerateConstructor/VisualBasicGenerateConstructorService.vb
Labels: Area-IDE

#48800 Use an iterative wait in DiagnosticTaggerWrapper
  src/EditorFeatures/TestUtilities/Diagnostics/DiagnosticTaggerWrapper.cs
Labels: Area-IDE, auto-merge

#44514 Move to thread pool after yield in WaitAllAsync
  src/Workspaces/Core/Portable/Shared/TestHooks/IAsynchronousOperationListenerProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
Labels: Area-IDE, auto-merge

#48809 Fix official build in dnceng
  azure-pipelines-official.yml
Labels: Area-Infrastructure, auto-merge

#48812 Restore retry on integration tests
  eng/build.ps1
  src/Tools/Source/RunTests/ITestExecutor.cs
  src/Tools/Source/RunTests/Options.cs
  src/Tools/Source/RunTests/ProcessTestExecutor.cs
  src/Tools/Source/RunTests/Program.cs
Labels: Area-Infrastructure, auto-merge

#48662 Move VisualStudioTaskSchedulerProvider to the EditorFeatures layer
  src/EditorFeatures/Core/Shared/Utilities/IThreadingContext.cs
  src/EditorFeatures/Core/Shared/Utilities/ThreadingContext.cs
  src/EditorFeatures/Core/Shared/Utilities/ThreadingContextTaskSchedulerProvider.cs
Labels: Area-IDE
