Repository dotnet/roslyn, pull requests merged in 2020-11, with the labels that each got.

#48215 Log telemetry item when parse or compilation options change
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProject.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-IDE

#49093 Update .github\CODEOWNERS to reflect EditorFeatures.Cocoa moving
  .github/CODEOWNERS
Labels: Area-Infrastructure

#48999 Add CodeStyle layer to SourceBuild
  src/CodeStyle/Directory.Build.props
Labels: Area-Infrastructure, Source-Build

#48892 IOperation Node Porting: Non-Leaf Non-Hierarchy Nodes Pt3
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundSwitchSection.cs
  src/Compilers/CSharp/Portable/BoundTree/IBoundSwitchSection.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationNodes.cs
  src/Compilers/Core/Portable/Generated/Operations.Generated.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/Operations/Operation.cs
  src/Compilers/Core/Portable/Operations/OperationCloner.cs
  src/Compilers/Core/Portable/Operations/OperationFactory.cs
  src/Compilers/Core/Portable/Operations/OperationInterfaces.xml
  src/Compilers/Core/Portable/Operations/OperationNodes.cs
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationNodes.vb
  src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb
  src/Features/CSharp/Portable/ConvertIfToSwitch/CSharpConvertIfToSwitchCodeRefactoringProvider.Rewriting.cs
  src/Features/Core/Portable/InlineMethod/AbstractInlineMethodRefactoringProvider.MethodParametersInfo.cs
  src/Features/Core/Portable/InlineMethod/AbstractInlineMethodRefactoringProvider.cs
  src/Test/Utilities/Portable/Compilation/OperationTreeVerifier.cs
  src/Test/Utilities/Portable/Compilation/TestOperationVisitor.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/IOperationClassWriter.PortedTypes.cs
Labels: Area-Compilers, Feature - IOperation

#48930 Nullable enable rest of CommandLine
  src/Compilers/Core/Portable/CommandLine/AnalyzerConfig.SectionNameMatching.cs
  src/Compilers/Core/Portable/CommandLine/CommonCompiler.CompilerEmitStreamProvider.cs
  src/Compilers/Core/Portable/CommandLine/CommonCompiler.ExistingReferencesResolver.cs
  src/Compilers/Core/Portable/CommandLine/CommonCompiler.LoggingMetadataFileReferenceResolver.cs
  src/Compilers/Core/Portable/CommandLine/CommonCompiler.LoggingSourceFileResolver.cs
  src/Compilers/Core/Portable/CommandLine/CommonCompiler.LoggingXmlFileResolver.cs
  src/Compilers/Core/Portable/CommandLine/CommonCompiler.SuppressionDiagnostic.cs
  src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs
  src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs
  src/Compilers/Core/Portable/CommandLine/TouchedFileLogger.cs
  src/Compilers/Core/Portable/Compilation.EmitStreamProvider.cs
  src/Compilers/Core/Portable/SourceFileResolver.cs
Labels: Area-Compilers, Concept-Null Annotations

#49130 Change our test run process
  azure-pipelines-integration.yml
  eng/build.ps1
  eng/pipelines/publish-logs.yml
  eng/pipelines/test-windows-job.yml
  src/Tools/Source/RunTests/Options.cs
  src/Tools/Source/RunTests/ProcDumpUtil.cs
  src/Tools/Source/RunTests/ProcessTestExecutor.cs
  src/Tools/Source/RunTests/Program.cs
Labels: Area-Infrastructure, auto-merge

#48949 Further optimize FindValidCloneMethod
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncStateMachine.cs
  src/Compilers/CSharp/Portable/Lowering/ClosureConversion/SynthesizedClosureEnvironment.cs
  src/Compilers/CSharp/Portable/Lowering/IteratorRewriter/IteratorStateMachine.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/DynamicSiteContainer.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/PublicSymbols/AnonymousType.TypePublicSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.TemplateSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/ErrorTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/NativeIntegerTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceFixedFieldSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/SubstitutedNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordClone.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedDelegateSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedEmbeddedAttributeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedEmbeddedNativeIntegerAttributeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedEmbeddedNullableAttributeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedEmbeddedNullableContextAttributeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedEmbeddedNullablePublicOnlyAttributeSymbol.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MockNamedTypeSymbol.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EENamedTypeSymbol.cs
Labels: Area-Compilers

#48321 Handle substring in string itself in IDE0057
  src/Analyzers/CSharp/CodeFixes/UseIndexOrRangeOperator/CSharpUseRangeOperatorCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs
Labels: Area-IDE, Community

#48275 Handle array bounds of VB in IDE0032
  src/Analyzers/VisualBasic/Tests/UseAutoProperty/UseAutoPropertyTests.vb
  src/Features/VisualBasic/Portable/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb
Labels: Area-IDE, Community

#49091 Log paths to HTML test results when present
  eng/build.ps1
  src/Tools/Source/RunTests/ITestExecutor.cs
  src/Tools/Source/RunTests/ProcessTestExecutor.cs
  src/Tools/Source/RunTests/Program.cs
  src/Tools/Source/RunTests/TestRunner.cs
Labels: Area-Infrastructure

#49069 Move OOP lsp server in proc and unify search implementations
  src/EditorFeatures/Core.Wpf/NavigateTo/NavigateToItemProvider.Callback.cs
  src/EditorFeatures/Core.Wpf/NavigateTo/NavigateToItemProvider.Searcher.cs
  src/EditorFeatures/Core.Wpf/NavigateTo/NavigateToItemProvider.cs
  src/EditorFeatures/Core.Wpf/NavigateTo/WrappedNavigateToSearchService.cs
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/Core/Portable/NavigateTo/INavigateToSearchCallback.cs
  src/Features/Core/Portable/NavigateTo/NavigateToSearcher.cs
  src/Features/Core/Portable/NavigateTo/WrappedNavigateToSearchService.cs
  src/Features/LanguageServer/Protocol/Handler/Symbols/DocumentSymbolsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Symbols/WorkspaceSymbolsHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Symbols/DocumentSymbolsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Symbols/WorkspaceSymbolsTests.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/AlwaysActivateInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/AlwaysActiveLanguageClientEventListener.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/RazorInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/VisualStudioOOPConnectionLanguageClient.cs
  src/VisualStudio/Core/Test.Next/Services/RemoteLanguageServerTests.cs
  src/VisualStudio/LiveShare/Impl/Shims/TypeScriptHandlerShims.cs
  src/Workspaces/Core/Portable/Remote/RemoteServiceName.cs
  src/Workspaces/Core/Portable/Remote/WellKnownServiceHubService.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemostHostClient.cs
  src/Workspaces/Remote/ServiceHub/Services/RemoteLanguageServer/RemoteLanguageServer.cs
Labels: Area-IDE, CloudEnv

#49141 Add feature to remove unnecessary discards.
  src/Analyzers/CSharp/Analyzers/CSharpAnalyzers.projitems
  src/Analyzers/CSharp/Analyzers/CSharpAnalyzersResources.resx
  src/Analyzers/CSharp/Analyzers/RemoveUnnecessaryDiscardDesignation/CSharpRemoveUnnecessaryDiscardDesignationDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.cs.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.de.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.es.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.fr.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.it.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.ja.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.ko.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.pl.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.pt-BR.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.ru.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.tr.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.zh-Hans.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.zh-Hant.xlf
  src/Analyzers/CSharp/CodeFixes/CSharpCodeFixes.projitems
  src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryDiscardDesignation/CSharpRemoveUnnecessaryDiscardDesignationCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/CSharpAnalyzers.UnitTests.projitems
  src/Analyzers/CSharp/Tests/RemoveUnnecessaryDiscardDesignation/RemoveUnnecessaryDiscardDesignationTests.cs
  src/Analyzers/Core/Analyzers/IDEDiagnosticIds.cs
  src/Compilers/Test/Core/Traits/Traits.cs
  src/EditorFeatures/Test/Diagnostics/IDEDiagnosticIDConfigurationTests.cs
Labels: Area-IDE, auto-merge

#49128 Fixed overwriting of generated sources
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs
Labels: Area-Compilers

#48426 Initial text synchronization support in LSP
  src/Features/LanguageServer/Protocol/Extensions/Extensions.cs
  src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/Features/LanguageServer/Protocol/Handler/DocumentChanges/DidChangeHandler.cs
  src/Features/LanguageServer/Protocol/Handler/DocumentChanges/DidCloseHandler.cs
  src/Features/LanguageServer/Protocol/Handler/DocumentChanges/DidOpenHandler.cs
  src/Features/LanguageServer/Protocol/Handler/RequestContext.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.DocumentChangeTracker.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs
  src/Features/LanguageServer/ProtocolUnitTests/DocumentChanges/DocumentChangesTests.LinkedDocuments.cs
  src/Features/LanguageServer/ProtocolUnitTests/DocumentChanges/DocumentChangesTests.WithFindAllReferences.cs
  src/Features/LanguageServer/ProtocolUnitTests/DocumentChanges/DocumentChangesTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Ordering/FailingMutatingRequestHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Ordering/MutatingRequestHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Ordering/RequestOrderingTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/References/FindAllReferencesHandlerTests.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/DefaultCapabilitiesProvider.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs
  src/VisualStudio/LiveShare/Impl/Shims/TypeScriptHandlerShims.cs
Labels: Area-IDE

#49159 Update License for Roslyn compilers to MIT in ThirdPartyNotices
  src/NuGet/ThirdPartyNotices.rtf
  src/Setup/Roslyn.ThirdPartyNotices/ThirdPartyNotices.rtf
Labels: Area-Infrastructure

#49168 Test insert when merging to master
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#49161 Enable nullable reference types for ISyntaxFacts
  src/Analyzers/Core/Analyzers/UseObjectInitializer/AbstractUseObjectInitializerDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/ValidateFormatString/AbstractValidateFormatStringDiagnosticAnalyzer.cs
  src/Analyzers/Core/CodeFixes/UseNullPropagation/AbstractUseNullPropagationCodeFixProvider.cs
  src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs
  src/Features/Core/Portable/CodeRefactorings/AbstractRefactoringHelpersService.cs
  src/Features/Core/Portable/EmbeddedLanguages/DateAndTime/LanguageServices/DateAndTimePatternDetector.cs
  src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider.cs
  src/Features/Core/Portable/QuickInfo/CommonSemanticQuickInfoProvider.cs
  src/Features/Core/Portable/ReplacePropertyWithMethods/AbstractReplacePropertyWithMethodsService.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ParameterSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/PropertySymbolReferenceFinder.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ArgumentSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/StatementSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxNodeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTreeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/AbstractSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFactsExtensions.cs
Labels: Area-IDE, Concept-Null Annotations

#48447 Fix nullable type pattern parsing for better error recovery
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests2.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs
Labels: Area-Compilers, Community

#48491 Revert the workaround in 73b5cb4
  eng/targets/Imports.targets
Labels: Area-Infrastructure, Community

#43286 Fix broken links and some grammatical errors in FixAllProvider.md
  docs/analyzers/FixAllProvider.md
Labels: Area-Infrastructure, Community, Documentation

#49178 Increase unexpected delay timeout
  src/EditorFeatures/Test/Utilities/AsynchronousOperationListenerTests.cs
Labels: Area-Infrastructure

#49183 Disable workspace diagnostics for the razor client.
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
Labels: Area-IDE

#48752 Report an error and alert the user if something goes wrong.
  src/EditorFeatures/Core.Wpf/EditorFeaturesWpfResources.resx
  src/EditorFeatures/Core.Wpf/InlineRename/Dashboard/Dashboard.xaml.cs
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.cs.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.de.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.es.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.fr.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.it.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ja.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ko.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.pl.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.pt-BR.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ru.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.tr.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.zh-Hans.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.zh-Hant.xlf
Labels: Area-IDE

#49164 Use lazy cancellation in RemoteEndPoint.InvokeAsync<T>
  src/Workspaces/Remote/Core/RemoteEndPoint.cs
Labels: Area-IDE

#49167 Completion for enum members in is expressions
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs
Labels: Area-IDE, auto-merge

#49162 Implement IEquatable on Microsoft.Cci.DefinitionWithLocation structure
  src/Compilers/Core/Portable/PEWriter/Units.cs
Labels: Area-Compilers, Concept-Continuous Improvement

#49150 Consolidate conditional compilation
  src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/EventSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/FieldSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/FunctionPointerTypeSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/MethodSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/NamedTypeSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/NamespaceSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs
  src/Compilers/CSharp/Portable/Emitter/Model/ParameterSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/PointerTypeSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/PropertySymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/SymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/TypeParameterSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/NoPia/EmbeddedEvent.cs
  src/Compilers/CSharp/Portable/Emitter/NoPia/EmbeddedField.cs
  src/Compilers/CSharp/Portable/Emitter/NoPia/EmbeddedMethod.cs
  src/Compilers/CSharp/Portable/Emitter/NoPia/EmbeddedParameter.cs
  src/Compilers/CSharp/Portable/Emitter/NoPia/EmbeddedProperty.cs
  src/Compilers/CSharp/Portable/Emitter/NoPia/EmbeddedType.cs
  src/Compilers/CSharp/Portable/Emitter/NoPia/EmbeddedTypeParameter.cs
  src/Compilers/CSharp/Portable/Emitter/NoPia/EmbeddedTypesManager.cs
  src/Compilers/VisualBasic/Portable/Emit/ArrayTypeSymbolAdapter.vb
  src/Compilers/VisualBasic/Portable/Emit/EventSymbolAdapter.vb
  src/Compilers/VisualBasic/Portable/Emit/FieldSymbolAdapter.vb
  src/Compilers/VisualBasic/Portable/Emit/MethodSymbolAdapter.vb
  src/Compilers/VisualBasic/Portable/Emit/NamedTypeSymbolAdapter.vb
  src/Compilers/VisualBasic/Portable/Emit/NamespaceSymbolAdapter.vb
  src/Compilers/VisualBasic/Portable/Emit/ParameterSymbolAdapter.vb
  src/Compilers/VisualBasic/Portable/Emit/PropertySymbolAdapter.vb
  src/Compilers/VisualBasic/Portable/Emit/SymbolAdapter.vb
  src/Compilers/VisualBasic/Portable/Emit/SynthesizedStaticLocalBackingFieldAdapter.vb
  src/Compilers/VisualBasic/Portable/Emit/TypeParameterSymbolAdapter.vb
Labels: Area-Compilers

#49181 Convert .ruleset to .globalconfig
  eng/config/globalconfigs/Common.globalconfig
  eng/config/globalconfigs/NonShipping.globalconfig
  eng/config/globalconfigs/Shipping.globalconfig
  eng/config/rulesets/NonShipping.ruleset
  eng/config/rulesets/Shipping.ruleset
  eng/targets/Imports.targets
Labels: Area-Infrastructure

#48776 UnitTesting and Razor External Access wrappers for ISB services
  eng/targets/GeneratePkgDef.targets
  eng/targets/Services.props
  src/Tools/ExternalAccess/Razor/Microsoft.CodeAnalysis.ExternalAccess.Razor.csproj
  src/Tools/ExternalAccess/Razor/RazorRemoteHostClient.cs
  src/Tools/ExternalAccess/Razor/Remote/RazorRemoteCallbackWrapper.cs
  src/Tools/ExternalAccess/Razor/Remote/RazorRemoteHostClient.cs
  src/Tools/ExternalAccess/Razor/Remote/RazorRemoteServiceCallbackDispatcher.cs
  src/Tools/ExternalAccess/Razor/Remote/RazorRemoteServiceCallbackDispatcherRegistry.cs
  src/Tools/ExternalAccess/Razor/Remote/RazorRemoteServiceCallbackIdWrapper.cs
  src/Tools/ExternalAccess/Razor/Remote/RazorRemoteServiceConnectionWrapper.cs
  src/Tools/ExternalAccess/Razor/Remote/RazorServiceDescriptorsWrapper.cs
  src/VisualStudio/Core/Def/Implementation/Watson/WatsonReporter.cs
  src/Workspaces/Core/Portable/ExternalAccess/UnitTesting/Api/UnitTestingRemoteHostClientWrapper.cs
  src/Workspaces/Core/Portable/ExternalAccess/UnitTesting/Api/UnitTestingRemoteServiceConnectionWrapper.cs
  src/Workspaces/Core/Portable/ExternalAccess/UnitTesting/Api/UnitTestingServiceHubService.cs
  src/Workspaces/Core/Portable/Remote/IRemoteServiceCallbackDispatcherProvider.cs
  src/Workspaces/Core/Portable/Remote/RemoteServiceCallbackDispatcher.cs
  src/Workspaces/Core/Portable/Remote/RemoteServiceCallbackDispatchers.cs
  src/Workspaces/CoreTest/Remote/ServiceDescriptorTests.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemostHostClient.cs
  src/Workspaces/Remote/Core/BrokeredServiceConnection.cs
  src/Workspaces/Remote/Core/ExternalAccess/UnitTesting/Api/UnitTestingRemoteCallbackWrapper.cs
  src/Workspaces/Remote/Core/ExternalAccess/UnitTesting/Api/UnitTestingRemoteHostClient.cs
  src/Workspaces/Remote/Core/ExternalAccess/UnitTesting/Api/UnitTestingRemoteServiceCallbackDispatcher.cs
  src/Workspaces/Remote/Core/ExternalAccess/UnitTesting/Api/UnitTestingRemoteServiceCallbackDispatcherRegistry.cs
  src/Workspaces/Remote/Core/ExternalAccess/UnitTesting/Api/UnitTestingRemoteServiceCallbackIdWrapper.cs
  src/Workspaces/Remote/Core/ExternalAccess/UnitTesting/Api/UnitTestingRemoteServiceConnectionWrapper.cs
  src/Workspaces/Remote/Core/ExternalAccess/UnitTesting/Api/UnitTestingServiceDescriptorsWrapper.cs
  src/Workspaces/Remote/Core/Microsoft.CodeAnalysis.Remote.Workspaces.csproj
  src/Workspaces/Remote/Core/RemoteWorkspacesResources.resx
  src/Workspaces/Remote/Core/Serialization/MessagePackFormatters.cs
  src/Workspaces/Remote/Core/ServiceDescriptor.cs
  src/Workspaces/Remote/Core/ServiceDescriptors.cs
  src/Workspaces/Remote/Core/ServiceHubRemoteHostClient.cs
  src/Workspaces/Remote/Core/SolutionAssetProvider.cs
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.cs.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.de.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.es.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.fr.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.it.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ja.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ko.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.pl.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.pt-BR.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ru.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.tr.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.zh-Hans.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.zh-Hant.xlf
  src/Workspaces/Remote/ServiceHub/ExternalAccess/UnitTesting/Api/UnitTestingBrokeredServiceImplementation.cs
  src/Workspaces/Remote/ServiceHub/ExternalAccess/UnitTesting/Api/UnitTestingServiceBase.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.FactoryBase.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs
  src/Workspaces/Remote/ServiceHub/Services/WorkspaceSolutionProvider/IRemoteWorkspaceSolutionProviderService.cs
  src/Workspaces/Remote/ServiceHub/Services/WorkspaceSolutionProvider/RemoteWorkspaceSolutionProviderService.cs
Labels: Area-IDE

#49184 Fix extract local function crash
  src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractLocalFunctionTests.cs
  src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractMethodTests.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/AbstractCodeActionOrUserDiagnosticTest.cs
  src/Features/Core/Portable/ExtractMethod/InsertionPoint.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/OperationStatus_Statics.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
Labels: Area-IDE

#48227 Extend make type abstract to include records
  src/Compilers/Test/Core/Traits/Traits.cs
  src/EditorFeatures/CSharpTest/MakeTypeAbstract/MakeTypeAbstractTests.cs
  src/EditorFeatures/VisualBasicTest/MakeTypeAbstract/MakeTypeAbstractTests.vb
  src/Features/CSharp/Portable/MakeTypeAbstract/CSharpMakeTypeAbstractCodeFixProvider.cs
  src/Features/Core/Portable/MakeClassAbstract/AbstractMakeTypeAbstractCodeFixProvider.cs
  src/Features/VisualBasic/Portable/MakeTypeAbstract/VisualBasicMakeTypeAbstractCodeFixProvider.vb
Labels: Area-IDE, Community, New Language Feature - Records

#49188 Clean up of EditorFeatures.Cocoa.Snippets
  src/EditorFeatures/Core.Cocoa/Snippets/AbstractSnippetCommandHandler.cs
  src/EditorFeatures/Core.Cocoa/Snippets/AbstractSnippetExpansionClient.cs
  src/EditorFeatures/Core.Cocoa/Snippets/AbstractSnippetInfoService.cs
  src/EditorFeatures/Core.Cocoa/Snippets/CSharpSnippets/SnippetCommandHandler.cs
  src/EditorFeatures/Core.Cocoa/Snippets/CSharpSnippets/SnippetExpansionClient.cs
  src/EditorFeatures/Core.Cocoa/Snippets/CSharpSnippets/SnippetFunctions/SnippetFunctionClassName.cs
  src/EditorFeatures/Core.Cocoa/Snippets/CSharpSnippets/SnippetFunctions/SnippetFunctionGenerateSwitchCases.cs
  src/EditorFeatures/Core.Cocoa/Snippets/CSharpSnippets/SnippetFunctions/SnippetFunctionSimpleTypeName.cs
  src/EditorFeatures/Core.Cocoa/Snippets/SnippetFunctions/AbstractSnippetFunction.cs
  src/EditorFeatures/Core.Cocoa/Snippets/SnippetFunctions/AbstractSnippetFunctionClassName.cs
  src/EditorFeatures/Core.Cocoa/Snippets/SnippetFunctions/AbstractSnippetFunctionGenerateSwitchCases.cs
  src/EditorFeatures/Core.Cocoa/Snippets/SnippetFunctions/AbstractSnippetFunctionSimpleTypeName.cs
Labels: Area-IDE, Concept-Continuous Improvement

#49070 [LSP] Re-enable folding range provider
  src/EditorFeatures/Core.Cocoa/RoslynOutliningWorkaround/AbstractStructureTaggerProvider.cs
  src/EditorFeatures/Core.Wpf/Structure/AbstractStructureTaggerProvider.cs
  src/EditorFeatures/Core/Shared/Extensions/DocumentExtensions.cs
  src/Features/LanguageServer/Protocol/Handler/FoldingRanges/FoldingRangesHandler.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/DefaultCapabilitiesProvider.cs
Labels: Area-IDE, CloudEnv

#49204 Minor cleanup in code action handlers
  src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionResolveData.cs
  src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionResolveHandler.cs
  src/Features/LanguageServer/Protocol/Handler/CodeActions/RunCodeActionHandler.cs
Labels: Area-IDE

#49138 Fix MemberNames API for records
  src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs
Labels: Area-Compilers, New Language Feature - Records

#49193 Change select/deselect all checkbox to buttons in Pull Members Up
  src/VisualStudio/Core/Def/Implementation/CommonControls/MemberSelection.xaml
  src/VisualStudio/Core/Def/Implementation/CommonControls/MemberSelection.xaml.cs
  src/VisualStudio/Core/Def/Implementation/CommonControls/MemberSelectionViewModel.cs
  src/VisualStudio/Core/Def/Implementation/CommonControls/SelectAllCheckBox.cs
  src/VisualStudio/Core/Def/Implementation/PullMemberUp/MainDialog/PullMemberUpDialog.xaml
  src/VisualStudio/Core/Def/Implementation/PullMemberUp/MainDialog/PullMemberUpDialogViewModel.cs
  src/VisualStudio/Core/Def/Implementation/PullMemberUp/VisualStudioPullMemberUpService.cs
  src/VisualStudio/Core/Test/CommonControls/MemberSelectionViewModelTests.vb
  src/VisualStudio/Core/Test/PullMemberUp/PullMemberUpViewModelTest.vb
Labels: Area-IDE, Tenet-User Friendly, auto-merge

#49217 Fix RazorRemoteHostClient to maintain binary back-compat
  src/Tools/ExternalAccess/Razor/Remote/RazorRemoteHostClient.cs
Labels: Area-IDE, auto-merge

#49213 Further tweak rendering of inline hints
  src/EditorFeatures/Core.Wpf/InlineHints/InlineHintsTag.cs
Labels: Area-IDE

#48434 Fix FAR counting for target-typed new
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.ConstructorSymbols.vb
Labels: Area-IDE, Blocked, Community, New Language Feature - Target-Typed New

#49228 Cache RegexPatternDetector per compilation
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/AbstractRegexDiagnosticAnalyzer.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexPatternDetector.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexSyntaxClassifier.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/RegexEmbeddedLanguage.cs
Labels: Area-IDE

#49236 Add test for with expression in F1 help service
  src/VisualStudio/CSharp/Test/F1Help/F1HelpTests.cs
Labels: Area-IDE, Community

#49145 Enable LSP pull model diagnostic for XAML.
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/VisualStudio/Xaml/Impl/Features/Diagnostics/IXamlPullDiagnosticService.cs
  src/VisualStudio/Xaml/Impl/Features/Diagnostics/XamlDiagnostic.cs
  src/VisualStudio/Xaml/Impl/Features/Diagnostics/XamlDiagnosticReport.cs
  src/VisualStudio/Xaml/Impl/Features/Diagnostics/XamlDiagnosticSeverity.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageClient/XamlInProcLanguageClient.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Extensions/SolutionExtensions.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Diagnostics/DocumentPullDiagnosticHandler.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
Labels: Area-IDE, Community

#49246 Remove workaround in PEMethodSymbol.ExplicitInterfaceImplementations
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs
Labels: Area-Compilers

#49092 Remove duplicated implementations of C# event hookup
  src/EditorFeatures/CSharp/CSharpEditorResources.resx
  src/EditorFeatures/CSharp/EventHookup/EventHookupCommandHandler.cs
  src/EditorFeatures/CSharp/EventHookup/EventHookupCommandHandler_SessionCancellingCommands.cs
  src/EditorFeatures/CSharp/EventHookup/EventHookupCommandHandler_TabKeyCommand.cs
  src/EditorFeatures/CSharp/EventHookup/EventHookupCommandHandler_TypeCharCommand.cs
  src/EditorFeatures/CSharp/EventHookup/EventHookupSessionManager.cs
  src/EditorFeatures/CSharp/EventHookup/EventHookupSessionManager_EventHookupSession.cs
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.cs.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.de.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.es.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.fr.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.it.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.ja.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.ko.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.pl.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.pt-BR.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.ru.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.tr.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.zh-Hans.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.zh-Hant.xlf
  src/EditorFeatures/CSharpTest/EventHookup/EventHookupCommandHandlerTests.cs
  src/EditorFeatures/CSharpTest/EventHookup/EventHookupTestState.cs
  src/EditorFeatures/Core.Cocoa/EventHookup/EventHookupCommandHandler.cs
  src/EditorFeatures/Core.Cocoa/EventHookup/EventHookupCommandHandler_SessionCancellingCommands.cs
  src/EditorFeatures/Core.Cocoa/EventHookup/EventHookupCommandHandler_TabKeyCommand.cs
  src/EditorFeatures/Core.Cocoa/EventHookup/EventHookupCommandHandler_TypeCharCommand.cs
  src/EditorFeatures/Core.Cocoa/EventHookup/EventHookupSessionManager.cs
  src/EditorFeatures/Core.Cocoa/EventHookup/EventHookupSessionManager_EventHookupSession.cs
  src/VisualStudio/CSharp/Impl/CSharpVSResources.resx
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.cs.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.de.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.es.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.fr.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.it.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.ja.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.ko.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.pl.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.pt-BR.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.ru.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.tr.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.zh-Hans.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.zh-Hant.xlf
Labels: Area-IDE

#49132 IOperation Node Porting: Hierarchy and Flow Analysis Nodes
  src/Compilers/CSharp/Portable/CSharpExtensions.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationNodes.cs
  src/Compilers/Core/CodeAnalysisTest/Diagnostics/OperationTests.cs
  src/Compilers/Core/Portable/Generated/FlowAnalysis.Generated.cs
  src/Compilers/Core/Portable/Generated/Operations.Generated.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/Operations/Operation.cs
  src/Compilers/Core/Portable/Operations/OperationCloner.cs
  src/Compilers/Core/Portable/Operations/OperationInterfaces.xml
  src/Compilers/Core/Portable/Operations/OperationNodes.cs
  src/Compilers/VisualBasic/Portable/BoundTree/BoundDoLoop.vb
  src/Compilers/VisualBasic/Portable/BoundTree/BoundWhileStatement.vb
  src/Compilers/VisualBasic/Portable/BoundTree/IBoundConditionalLoop.vb
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationNodes.vb
  src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb
  src/Features/Core/Portable/InlineMethod/AbstractInlineMethodRefactoringProvider.MethodParametersInfo.cs
  src/Test/Utilities/Portable/Compilation/OperationTreeVerifier.cs
  src/Test/Utilities/Portable/Compilation/TestOperationVisitor.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/IOperationClassWriter.PortedTypes.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/IOperationClassWriter.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/Model.cs
Labels: Area-Compilers

#49220 Fix mapping in razor x-file codespaces
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionResolveHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Rename/RenameHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Rename/RenameTests.cs
Labels: Area-IDE, CloudEnv

#49242 Do not convert an unconstrained generic to a nullable struct.
  src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ITypeSymbolExtensions.TypeSyntaxGeneratorVisitor.cs
Labels: Area-IDE

#48598 Fix property parsing when it contains parantheses
  src/Compilers/VisualBasic/Portable/Parser/Parser.vb
  src/Compilers/VisualBasic/Test/Syntax/Parser/ParserRegressionTests.vb
Labels: Area-Compilers, Community, Language-VB

#49255 Enable analyzers in Mac build
  eng/build.sh
Labels: Area-Infrastructure

#49085 Add to and update TS external access to avoid AbstractProject
  src/VisualStudio/Core/Def/ExternalAccess/VSTypeScript/Api/IVsTypeScriptVisualStudioProjectFactory.cs
  src/VisualStudio/Core/Def/ExternalAccess/VSTypeScript/Api/VSTypeScriptContainedDocumentWrapper.cs
  src/VisualStudio/Core/Def/ExternalAccess/VSTypeScript/Api/VSTypeScriptContainedLanguageWrapper.cs
  src/VisualStudio/Core/Def/ExternalAccess/VSTypeScript/Api/VSTypeScriptVisualStudioProjectWrapper.LSPContainedDocumentServiceProvider.cs
  src/VisualStudio/Core/Def/ExternalAccess/VSTypeScript/Api/VSTypeScriptVisualStudioProjectWrapper.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectFactory.cs
Labels: Area-IDE, auto-merge

#49273 [LSP] Fix FAR namespace bug + re-enable FAR tests
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/LanguageServer/Protocol/CustomProtocol/FindUsagesLSPContext.cs
  src/Features/LanguageServer/ProtocolUnitTests/References/FindAllReferencesHandlerTests.cs
Labels: Area-IDE, CloudEnv

#49233 Don't offer to use an object initializer in a using declaration
  src/Analyzers/CSharp/Analyzers/UseObjectInitializer/CSharpUseObjectInitializerDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/UseObjectInitializer/UseObjectInitializerTests.cs
  src/Analyzers/Core/Analyzers/UseObjectInitializer/AbstractUseObjectInitializerDiagnosticAnalyzer.cs
  src/Analyzers/VisualBasic/Analyzers/UseObjectInitializer/VisualBasicUseObjectInitializerDiagnosticAnalyzer.vb
Labels: Area-IDE

#49232 Correctly use langword for this and base keywords
  src/EditorFeatures/CSharpTest/ReplaceDocCommentTextWithTag/ReplaceDocCommentTextWithTagTests.cs
  src/EditorFeatures/VisualBasicTest/ReplaceDocCommentTextWithTag/ReplaceDocCommentTextWithTagTests.vb
  src/Features/CSharp/Portable/ReplaceDocCommentTextWithTag/CSharpReplaceDocCommentTextWithTagCodeRefactoringProvider.cs
  src/Features/VisualBasic/Portable/ReplaceDocCommentTextWithTag/VisualBasicReplaceDocCommentTextWithTagCodeRefactoringProvider.vb
Labels: Area-IDE

#49139 VB generators
  src/Compilers/CSharp/Portable/SourceGeneration/CSharpGeneratorDriver.cs
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/AdditionalSourcesCollectionTests.cs
  src/Compilers/Core/CodeAnalysisTest/Analyzers/AnalyzerFileReferenceTests.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerReference.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Core/Portable/SourceGeneration/AdditionalSourcesCollection.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorAttribute.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorContexts.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs
  src/Compilers/Test/Core/SourceGeneration/TestGenerators.cs
  src/Compilers/VisualBasic/Portable/CommandLine/VisualBasicCompiler.vb
  src/Compilers/VisualBasic/Portable/Errors/Errors.vb
  src/Compilers/VisualBasic/Portable/Errors/MessageProvider.vb
  src/Compilers/VisualBasic/Portable/Generated/ErrorFacts.Generated.vb
  src/Compilers/VisualBasic/Portable/PublicAPI.Unshipped.txt
  src/Compilers/VisualBasic/Portable/SourceGeneration/VisualBasicGeneratorDriver.vb
  src/Compilers/VisualBasic/Portable/VBResources.resx
  src/Compilers/VisualBasic/Portable/xlf/VBResources.cs.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.de.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.es.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.fr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.it.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ja.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ko.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pl.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pt-BR.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ru.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.tr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hans.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hant.xlf
  src/Compilers/VisualBasic/Test/CommandLine/CommandLineTests.vb
  src/Compilers/VisualBasic/Test/Semantic/SourceGeneration/GeneratorDriverTests.vb
  src/Features/Core/Portable/Diagnostics/AnalyzerHelper.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/AnalyzerItem/AnalyzerItemSource.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationAndGeneratorDriverTranslationAction_Actions.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
  src/Workspaces/VisualBasic/Portable/Workspace/LanguageServices/VisualBasicCompilationFactoryService.vb
Labels: Area-Compilers, New Feature - Source Generators

#49265 Use release packages for S.R.MD and S.C.I
  docs/contributing/Building, Debugging, and Testing on Windows.md
  eng/Versions.props
  global.json
Labels: Area-Infrastructure

#49256 Ensure we always get up to date diagnostics when getting pull diagnostics.
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestHostDocument.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs
  src/Features/LanguageServer/Protocol/Extensions/Extensions.cs
  src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DocumentPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/RequestContext.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.DocumentChangeTracker.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs
  src/Features/LanguageServer/ProtocolUnitTests/CodeActions/CodeActionsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/References/FindImplementationsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Rename/RenameTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/AbstractSemanticTokensTests.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/AlwaysActivateInProcLanguageClient.cs
  src/VisualStudio/LiveShare/Impl/Shims/TypeScriptHandlerShims.cs
  src/Workspaces/CSharpTest/OrganizeImports/OrganizeUsingsTests.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/DocumentExtensions.cs
Labels: Area-IDE, auto-merge

#48978 Couple of uses of a PooledHashSet(Of Symbol)
  src/Compilers/VisualBasic/Portable/Compilation/SemanticModel.vb
Labels: Area-Compilers, Community

#49303 Don't offer use-compound-assignment with implicit object creation.
  src/Analyzers/CSharp/Tests/UseCompoundAssignment/UseCompoundAssignmentTests.cs
  src/Analyzers/Core/Analyzers/UseCompoundAssignment/AbstractUseCompoundAssignmentDiagnosticAnalyzer.cs
  src/EditorFeatures/CSharpTest/CodeActions/ReplaceMethodWithProperty/ReplaceMethodWithPropertyTests.cs
  src/EditorFeatures/CSharpTest/CodeActions/ReplacePropertyWithMethods/ReplacePropertyWithMethodsTests.cs
  src/EditorFeatures/CSharpTest/GenerateVariable/GenerateVariableTests.cs
  src/Features/Core/Portable/GenerateMember/AbstractGenerateMemberService.cs
  src/Features/Core/Portable/GenerateMember/GenerateVariable/AbstractGenerateVariableService.State.cs
  src/Features/Core/Portable/ReplacePropertyWithMethods/ReplacePropertyWithMethodsCodeRefactoringProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/SyntaxNodeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE, auto-merge

#49278 Turn off text sync for Xaml
  src/VisualStudio/Xaml/Impl/Implementation/LanguageClient/XamlInProcLanguageClient.cs
Labels: Area-IDE

#47252 Allow CSharpSyntaxGenerator to be used as a source generator
  .editorconfig
  .vscode/tasks.json
  Compilers.sln
  Roslyn.sln
  eng/Versions.props
  eng/build-utils.ps1
  eng/build.ps1
  eng/build.sh
  eng/config/globalconfigs/Common.globalconfig
  eng/generate-compiler-code.ps1
  eng/targets/Imports.targets
  eng/targets/Settings.props
  scripts/vscode-build.ps1
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Internal.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Main.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Syntax.Generated.cs
  src/Compilers/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.csproj
  src/Tools/BuildBoss/ProjectCheckerUtil.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/AbstractFileWriter.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/CSharpSyntaxGenerator.csproj
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/Grammar/GrammarGenerator.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/Program.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/SourceGenerator.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/SourceWriter.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/TestWriter.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/TreeFlattening.cs
  src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj
Labels: Area-Compilers

#49343 Make each request id for doc and workspace diagnostics unique.
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
Labels: Area-IDE, auto-merge

#49339 Use VisualStudioTestCompositions.LanguageServices in F1HelpTests
  src/VisualStudio/CSharp/Test/F1Help/F1HelpTests.cs
Labels: Area-IDE

#49328 Add muscle-memory tests for braces
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpAutomaticBraceCompletion.cs
  src/VisualStudio/IntegrationTest/TestUtilities/Input/VirtualKey.cs
Labels: Area-IDE

#49306 Add source generator support to the LSIF indexer
  Roslyn.sln
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs
  src/Features/Lsif/Generator/CompilerInvocation.cs
  src/Features/Lsif/Generator/Generator.cs
  src/Features/Lsif/Generator/Graph/LsifDocument.cs
  src/Features/Lsif/GeneratorTest/CompilerInvocationTests.vb
  src/Features/Lsif/GeneratorTest/Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.UnitTests.vbproj
  src/Features/Lsif/GeneratorTest/ProjectStructureTests.vb
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpSourceGenerators.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/Microsoft.VisualStudio.LanguageServices.IntegrationTests.csproj
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
  src/Workspaces/CoreTestUtilities/TestGeneratorReference.cs
  src/Workspaces/TestSourceGenerator/HelloWorldGenerator.cs
  src/Workspaces/TestSourceGenerator/Microsoft.CodeAnalysis.TestSourceGenerator.csproj
Labels: Area-IDE

#49359 Fix split comment exporting for VB.
  src/EditorFeatures/Core/Implementation/SplitComment/SplitCommentCommandHandler.cs
Labels: Area-IDE, auto-merge

#47305 Enable source generator integration test
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpSourceGenerators.cs
Labels: Area-IDE, Test

#48980 Use .Any extension of ImmutableArray(Of Symbol)
  src/Compilers/VisualBasic/Portable/Compilation/SemanticModel.vb
Labels: Area-Compilers

#49337 Rewrite AnalyzeFileReference.GetSupportedLanguages without LINQ
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs
Labels: Area-Analyzers

#49355 Overwrite xunit's app domain handling to not call AppDomain.Unload
  Roslyn.sln
  src/EditorFeatures/TestUtilities/Microsoft.CodeAnalysis.EditorFeatures.Test.Utilities.csproj
  src/EditorFeatures/TestUtilities/Threading/StaTaskScheduler.cs
  src/EditorFeatures/XunitHook/Microsoft.CodeAnalysis.XunitHook.csproj
  src/EditorFeatures/XunitHook/XunitDisposeHook.cs
Labels: Area-Infrastructure

#49357 Backport #48420 to release/dev16.8
  src/Compilers/Core/CodeAnalysisTest/Text/TextChangeTests.cs
  src/Compilers/Core/Portable/Text/ChangedText.cs
  src/Compilers/Core/Portable/Text/TextChange.cs
  src/Compilers/Core/Portable/Text/TextChangeRange.cs
Labels: Approved to merge, Area-Compilers

#49363 fix 'remove unnecessary cast' when doing bitwise ops on unsigned values.
  src/Analyzers/CSharp/Tests/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Simplification/Simplifiers/CastSimplifier.cs
Labels: Area-IDE, auto-merge

#48851 Add semicolon as a commit character for object creation and symbol completion
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ExtensionMethodImportCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ObjectCreationCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/TypeImportCompletionProviderTests.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/EditorFeatures/TestUtilities/Completion/AbstractCompletionProviderTests.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/ImportCompletion/ExtensionMethodImportCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/ImportCompletion/TypeImportCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/ObjectCreationCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/SymbolCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/AbstractRecommendationServiceBasedCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractImportCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs
  src/Features/Core/Portable/Completion/Providers/SymbolCompletionItem.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionTests.cs
  src/Features/VisualBasic/Portable/Completion/CompletionProviders/ImportCompletionProvider/ExtensionMethodImportCompletionProvider.vb
  src/Features/VisualBasic/Portable/Completion/CompletionProviders/ImportCompletionProvider/TypeImportCompletionProvider.vb
Labels: Area-IDE

#49305 Reuse LSP solutions if they don't need re-forking
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs
  src/Features/LanguageServer/ProtocolUnitTests/Ordering/MutatingRequestHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Ordering/NonMutatingRequestHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Ordering/RequestOrderingTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Ordering/TestRequest.cs
  src/Features/LanguageServer/ProtocolUnitTests/Ordering/TestResponse.cs
Labels: Area-IDE

#49370 Use deterministic metadata names for emitted anonymous type fields.
  src/Compilers/VisualBasic/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType_PropertyBackingFieldSymbol.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/AnonymousTypes/AnonymousTypesEmittedSymbolsTests.vb
Labels: Area-Compilers, Concept-Determinism

#48884 Revert RPS workaround
  src/Workspaces/Remote/Core/ServiceHubRemoteHostClient.cs
Labels: Area-IDE, auto-merge

#49271 Nullable enable Operation files
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_ICoalesceAssignmentOperation.cs
  src/Compilers/Core/Portable/Operations/ArgumentKind.cs
  src/Compilers/Core/Portable/Operations/BasicBlock.cs
  src/Compilers/Core/Portable/Operations/BinaryOperatorKind.cs
  src/Compilers/Core/Portable/Operations/BranchKind.cs
  src/Compilers/Core/Portable/Operations/CaseKind.cs
  src/Compilers/Core/Portable/Operations/CommonConversion.cs
  src/Compilers/Core/Portable/Operations/ControlFlowBranch.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraph.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.BasicBlockBuilder.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.CaptureIdDispenser.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.Context.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.RegionBuilder.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphExtensions.cs
  src/Compilers/Core/Portable/Operations/ControlFlowRegion.cs
  src/Compilers/Core/Portable/Operations/ControlFlowRegionKind.cs
  src/Compilers/Core/Portable/Operations/IConvertibleConversion.cs
  src/Compilers/Core/Portable/Operations/InstanceReferenceKind.cs
  src/Compilers/Core/Portable/Operations/Loops/ForEachLoopOperationInfo.cs
  src/Compilers/Core/Portable/Operations/Loops/ForToLoopOperationInfo.cs
  src/Compilers/Core/Portable/Operations/Loops/LoopKind.cs
  src/Compilers/Core/Portable/Operations/OperationExtensions.cs
  src/Compilers/Core/Portable/Operations/OperationNodes.cs
  src/Compilers/Core/Portable/Operations/OperationVisitor.cs
  src/Compilers/Core/Portable/Operations/OperationWalker.cs
  src/Compilers/Core/Portable/Operations/PlaceholderKind.cs
  src/Compilers/Core/Portable/Operations/UnaryOperatorKind.cs
  src/Compilers/Test/Core/Compilation/OperationTreeVerifier.cs
  src/Compilers/Test/Core/Compilation/TestOperationVisitor.cs
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb
  src/Features/Core/Portable/InlineMethod/AbstractInlineMethodRefactoringProvider.InlineContext.cs
Labels: Area-Compilers, Feature - IOperation

#49377 Remove unnecessary ArrayBuilder in MakeCallWithNoExplicitArgument
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_UsingStatement.cs
Labels: Area-Compilers

#49402 Revert "Skip binary for determinism checking"
  eng/test-determinism.ps1
Labels: Area-Infrastructure, auto-merge

#49371 Use lazy cancellation in RemoteEndPoint.InvokeAsync<T>
  src/Workspaces/Remote/Core/RemoteEndPoint.cs
Labels: Approved to merge, Area-IDE

#49422 Remove unwanted DataContract attribute
  src/Compilers/Core/Portable/Text/TextChange.cs
Labels: Area-Compilers

#49408 Document diagnostics supersede workspace diagnostics
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DocumentPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
Labels: Area-IDE, auto-merge

#49419 Avoid duplicate GetHashCode() values in TokenMap (#48897)
  src/Compilers/CSharp/Test/Semantic/Semantics/OverloadResolutionPerfTests.cs
  src/Compilers/Core/Portable/IReferenceOrISignature.cs
Labels: Area-Compilers

#49424 Add telemetry of parenthesis completion using semicolon
  src/Features/CSharp/Portable/Completion/CompletionProviders/ObjectCreationCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/SymbolCompletionProvider.cs
  src/Features/Core/Portable/Completion/Log/CompletionProvidersLogger.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractImportCompletionProvider.cs
Labels: Area-IDE

#49450 Collect nfw information for a crash we're seeing.
  src/Workspaces/Core/Portable/SemanticModelReuse/AbstractSemanticModelReuseLanguageService.cs
Labels: Area-IDE, auto-merge

#49436 Set an encoding on source text
  src/Features/LanguageServer/Protocol/Handler/DocumentChanges/DidOpenHandler.cs
Labels: Area-IDE

#49197 Add outlining support to LsifGenerator
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/Core/Portable/Structure/BlockStructureServiceWithProviders.cs
  src/Features/LanguageServer/Protocol/Handler/FoldingRanges/FoldingRangesHandler.cs
  src/Features/LanguageServer/Protocol/Microsoft.CodeAnalysis.LanguageServer.Protocol.csproj
  src/Features/Lsif/Generator/CompilerInvocation.cs
  src/Features/Lsif/Generator/Generator.cs
  src/Features/Lsif/Generator/Graph/FoldingRangeResult.cs
  src/Features/Lsif/Generator/Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.csproj
  src/Features/Lsif/Generator/Program.cs
  src/Features/Lsif/GeneratorTest/FoldingRangeTests.vb
  src/Features/Lsif/GeneratorTest/OutputFormatTests.vb
  src/Features/Lsif/GeneratorTest/Utilities/TestLsifOutput.vb
Labels: Area-IDE, auto-merge

#49389 Create an unsafe method from a local function when necessary
  src/EditorFeatures/CSharpTest/CodeActions/ConvertLocalFunctionToMethod/ConvertLocalFunctionToMethodTests.cs
  src/Features/CSharp/Portable/CodeRefactorings/ConvertLocalFunctionToMethod/CSharpConvertLocalFunctionToMethodCodeRefactoringProvider.cs
Labels: Area-IDE

#49435 Fix module-level SkipLocalsInit with top-level statements
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbol.cs
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs
Labels: Area-Compilers, Community

#48680 Avoid using the main thread within CodeAction.GetOperationsAsync
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs
  src/Features/Core/Portable/AddImport/CodeActions/AssemblyReferenceCodeAction.cs
  src/Features/Core/Portable/AddImport/CodeActions/MetadataSymbolReferenceCodeAction.cs
  src/Features/Core/Portable/AddImport/CodeActions/ProjectSymbolReferenceCodeAction.cs
  src/Features/Core/Portable/AddImport/CodeActions/SymbolReference.SymbolReferenceCodeAction.cs
  src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/MetadataReferences/VisualStudioFrameworkAssemblyPathResolverFactory.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/Workspaces/Core/Portable/Workspace/Host/Metadata/FrameworkAssemblyPathResolverFactory.cs
  src/Workspaces/Core/Portable/Workspace/Host/Metadata/IFrameworkAssemblyPathResolver.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
Labels: Area-IDE

#49467 Determinism fixes for AnonymousTypes in VB
  src/Compilers/VisualBasic/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousDelegate_TemplateSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousTypeOrDelegateTemplateSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousTypeOrDelegate_ParameterSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType_ConstructorSymbol.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/AnonymousTypes/AnonymousTypesEmittedSymbolsTests.vb
Labels: Area-Compilers, Bug, Concept-Determinism

#49459 Additional usage of a PooledHashset.
  src/Compilers/VisualBasic/Portable/Compilation/SemanticModel.vb
Labels: Area-Compilers, Community

#49501 Preserve annotation on comment trivia when performing formatting.
  src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Engine/Trivia/CSharpTriviaFormatter.cs
Labels: Area-IDE, auto-merge

#49360 Simplify and reduce amount of work performed by SourcePropertySymbolBase constructor.
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs
  src/Compilers/CSharp/Portable/Symbols/CompletionPart.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedBackingFieldSymbol.cs
  src/Compilers/CSharp/Test/Emit/Emit/EmitMetadataTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/RecordTests.cs
Labels: Area-Compilers, Concept-Continuous Improvement

#49483 Determinism test needs to use bootstrap compiler
  eng/test-determinism.ps1
  src/Compilers/Server/VBCSCompiler/AnalyzerConsistencyChecker.cs
  src/Compilers/Server/VBCSCompilerTests/AnalyzerConsistencyCheckerTests.cs
Labels: Area-Compilers, Area-Infrastructure

#49479 Collect nfw information for a crash we're seeing.
  src/Workspaces/Core/Portable/SemanticModelReuse/AbstractSemanticModelReuseLanguageService.cs
Labels: Approved to merge, Area-IDE

#49505 Split Document/Workspace handler into only handling open/closed documents respectively.
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DocumentPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
Labels: Area-IDE

#49499 Validate arguments to IAsyncCompletionSource methods
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CompletionSource.cs
Labels: Area-IDE, auto-merge

#49510 Report an error for ref-returning auto-properties declared in an interface.
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
Labels: Area-Compilers, New Language Feature - Default Interface Impl

#49518 Handle removed project in ExternalErrorDiagnosticUpdateSource
  src/VisualStudio/Core/Def/Implementation/TaskList/ExternalErrorDiagnosticUpdateSource.cs
Labels: Area-IDE, auto-merge

#48557 Make compiler server logging explicit
  src/Compilers/CSharp/csc/Program.cs
  src/Compilers/Core/CommandLine/BuildProtocol.cs
  src/Compilers/Core/CommandLine/CompilerServerLogger.cs
  src/Compilers/Core/MSBuildTask/ManagedCompiler.cs
  src/Compilers/Server/VBCSCompiler/AnalyzerConsistencyChecker.cs
  src/Compilers/Server/VBCSCompiler/BuildServerController.cs
  src/Compilers/Server/VBCSCompiler/ClientConnectionHandler.cs
  src/Compilers/Server/VBCSCompiler/CompilerRequestHandler.cs
  src/Compilers/Server/VBCSCompiler/ICompilerServerHost.cs
  src/Compilers/Server/VBCSCompiler/MemoryHelper.cs
  src/Compilers/Server/VBCSCompiler/NamedPipeClientConnection.cs
  src/Compilers/Server/VBCSCompiler/NamedPipeClientConnectionHost.cs
  src/Compilers/Server/VBCSCompiler/ServerDispatcher.cs
  src/Compilers/Server/VBCSCompiler/VBCSCompiler.cs
  src/Compilers/Server/VBCSCompilerTests/AnalyzerConsistencyCheckerTests.cs
  src/Compilers/Server/VBCSCompilerTests/BuildClientTests.cs
  src/Compilers/Server/VBCSCompilerTests/BuildServerControllerTests.cs
  src/Compilers/Server/VBCSCompilerTests/CompilerServerApiTest.cs
  src/Compilers/Server/VBCSCompilerTests/CompilerServerTests.cs
  src/Compilers/Server/VBCSCompilerTests/EndToEndDeterminismTest.cs
  src/Compilers/Server/VBCSCompilerTests/NamedPipeClientConnectionHostTests.cs
  src/Compilers/Server/VBCSCompilerTests/ServerUtil.cs
  src/Compilers/Server/VBCSCompilerTests/TestableCompilerServerHost.cs
  src/Compilers/Server/VBCSCompilerTests/VBCSCompilerServerTests.cs
  src/Compilers/Server/VBCSCompilerTests/XunitCompilerServerLogger.cs
  src/Compilers/Shared/BuildClient.cs
  src/Compilers/Shared/BuildServerConnection.cs
  src/Compilers/VisualBasic/vbc/Program.cs
Labels: Area-Compilers

#49453 Remove IOperation laziness from SemanticModel
  src/Compilers/CSharp/Portable/Compilation/InitializerSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/Operations/Operation.cs
  src/Compilers/Core/Portable/Operations/OperationMapBuilder.cs
  src/Compilers/Core/Portable/Operations/OperationNodes.cs
  src/Compilers/Core/Portable/Operations/OperationWalker.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Test/Core/CommonTestBase.cs
  src/Compilers/VisualBasic/Portable/Binding/MemberSemanticModel.vb
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb
Labels: Area-Compilers, Feature - IOperation

#49198 Add a Workspace API to represent source generated documents
  docs/ide/api-designs/Workspace and Source Generated Documents.md
  src/EditorFeatures/Core/FindUsages/IDefinitionsAndReferencesFactory.cs
  src/Features/Core/Portable/FindUsages/IRemoteFindUsagesService.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpSourceGenerators.cs
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
  src/Workspaces/Core/Portable/Workspace/Solution/DocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Project.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationAndGeneratorDriverTranslationAction.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationAndGeneratorDriverTranslationAction_Actions.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.State.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.TrackedGeneratorDriver.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratedDocument.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratedDocumentState.cs
  src/Workspaces/Core/Portable/WorkspacesResources.resx
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.cs.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.de.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.es.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.fr.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.it.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ja.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ko.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.pl.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.pt-BR.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ru.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.tr.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.zh-Hans.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.zh-Hant.xlf
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
  src/Workspaces/CoreTest/WorkspaceTests/AdhocWorkspaceTests.cs
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassification/RemoteSemanticClassificationService.cs
Labels: Area-IDE

#49365 Update build references to 3.8.0
  docs/contributing/Building, Debugging, and Testing on Windows.md
  eng/Versions.props
  eng/targets/Imports.targets
  global.json
  src/Interactive/HostProcess/InteractiveHost64.csproj
  src/Interactive/HostTest/InteractiveHost.UnitTests.csproj
  src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj
  src/Workspaces/CoreTestUtilities/Microsoft.CodeAnalysis.Workspaces.Test.Utilities.csproj
Labels: Area-Infrastructure

#49457 Run Razor LSP on host only
  eng/Versions.props
  src/Compilers/Extension/Roslyn.Compilers.Extension.csproj
  src/ExpressionEvaluator/Package/ExpressionEvaluatorPackage.csproj
  src/Setup/DevDivInsertionFiles/DevDivInsertionFiles.csproj
  src/VisualStudio/Core/Def/Implementation/LanguageClient/AbstractInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/RazorInProcLanguageClient.cs
  src/VisualStudio/Setup.Dependencies/Roslyn.VisualStudio.Setup.Dependencies.csproj
Labels: Area-IDE, CloudEnv

#49556 Add CallerMemberNameAttributeWithImplicitObjectCreation test
  src/Compilers/CSharp/Test/Semantic/Semantics/ImplicitObjectCreationTests.cs
Labels: Area-Compilers, Community, Test

#49394 VSMac: Make QuickFix preview resizable and add title
  src/EditorFeatures/Core.Cocoa/PreviewPane/PreviewPane.cs
  src/EditorFeatures/Core.Cocoa/Suggestions/FixAll/FixAllGetFixesService.cs
Labels: Area-IDE

#49102 Support warning numbers in Quick Info for suppressions
  src/EditorFeatures/CSharpTest/QuickInfo/DiagnosticAnalyzerQuickInfoSourceTests.cs
  src/Features/CSharp/Portable/QuickInfo/CSharpDiagnosticAnalyzerQuickInfoProvider.cs
Labels: Area-IDE, Community

#49523 parallel restore on mac/linux
  eng/build.sh
Labels: Area-Infrastructure

#49514 [LSP] Add support for FAR highlighting
  src/EditorFeatures/Core/FindUsages/FindUsagesHelpers.cs
  src/Features/LanguageServer/Protocol/CustomProtocol/FindUsagesLSPContext.cs
  src/Features/LanguageServer/ProtocolUnitTests/References/FindAllReferencesHandlerTests.cs
Labels: Area-IDE, CloudEnv

#49574 Fix the ability to expand the list of analyzers in a reference
  src/EditorFeatures/TestUtilities/Diagnostics/TestAnalyzerReferenceByLanguage.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/DiagnosticItem/BaseDiagnosticItemSource.cs
  src/VisualStudio/Core/Test/SolutionExplorer/CpsDiagnosticItemSourceTests.vb
Labels: Area-Analyzers, auto-merge

#49586 Update Versions.props and PublishData.json for 16.9p2 snap
  eng/Versions.props
  eng/config/PublishData.json
Labels: Area-Infrastructure, auto-merge

#49452 Remove steps from test jobs
  .vscode/launch.json
  azure-pipelines.yml
  eng/Versions.props
  eng/build.ps1
  eng/build.sh
  eng/pipelines/build-unix-job.yml
  eng/pipelines/test-unix-job.yml
  eng/pipelines/test-windows-job.yml
  eng/prepare-tests.ps1
  eng/prepare-tests.sh
  eng/rehydrate-tests.ps1
  src/Tools/PrepareTests/MinimizeUtil.cs
  src/Tools/PrepareTests/README.md
  src/Tools/Source/RunTests/ITestExecutor.cs
  src/Tools/Source/RunTests/Logger.cs
  src/Tools/Source/RunTests/Options.cs
  src/Tools/Source/RunTests/ProcDumpUtil.cs
  src/Tools/Source/RunTests/ProcessTestExecutor.cs
  src/Tools/Source/RunTests/Program.cs
  src/Tools/Source/RunTests/RunTests.csproj
  src/Tools/Source/RunTests/TestRunner.cs
Labels: Area-Infrastructure

#49449 /warnaserror-:DiagnosticId should not nullify editorconfig diagnostic…
  src/Compilers/CSharp/Portable/Compilation/CSharpDiagnosticFilter.cs
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/VisualBasic/Portable/Compilation/VisualBasicDiagnosticFilter.vb
  src/Compilers/VisualBasic/Test/CommandLine/CommandLineTests.vb
Labels: Area-Analyzers, Area-Compilers

#49592 Revert changes from https://github.com/dotnet/roslyn/pull/49220/ to t…
  src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionResolveHandler.cs
Labels: Approved to merge, Area-IDE

#49577 Fix sporadic OptProf failure
  eng/config/OptProf.json
Labels: Approved to merge, Area-Infrastructure

#49588 Resolve follow-up comments in PR "Create default arguments during binding"
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs
Labels: Area-Compilers

#49610 AddSynthesizedRecordMembersIfNecessary - avoid touching members that are known to have no effect on the outcome of the function.
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/RecordTests.cs
Labels: Area-Compilers, New Language Feature - Records

#49655 Preserve parens required by C# when simplifying interpolation
  src/Analyzers/CSharp/Analyzers/SimplifyInterpolation/CSharpSimplifyInterpolationDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/SimplifyInterpolation/CSharpSimplifyInterpolationCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/SimplifyInterpolation/SimplifyInterpolationTests.cs
  src/Analyzers/Core/Analyzers/SimplifyInterpolation/AbstractSimplifyInterpolationDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/SimplifyInterpolation/Helpers.cs
  src/Analyzers/Core/CodeFixes/SimplifyInterpolation/AbstractSimplifyInterpolationCodeFixProvider.cs
  src/Analyzers/VisualBasic/Analyzers/SimplifyInterpolation/VisualBasicSimplifyInterpolationDiagnosticAnalyzer.vb
  src/Analyzers/VisualBasic/CodeFixes/SimplifyInterpolation/VisualBasicSimplifyInterpolationCodeFixProvider.vb
Labels: Area-IDE

#49625 Fix bug for opening files if a generator produces multiple outputs
  src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs
Labels: Area-IDE, auto-merge

#49229 [Refactoring] ConvertConcatenationToInterpolatedString: Support inlineing of other interpolated strings
  src/EditorFeatures/CSharpTest/ConvertToInterpolatedString/ConvertConcatenationToInterpolatedStringTests.cs
  src/EditorFeatures/VisualBasicTest/ConvertToInterpolatedString/ConvertConcatenationToInterpolatedStringTests.vb
  src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFactsExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxKinds.vb
Labels: Area-IDE, Community

#49646 Show proper progress dialog when performing 'fix all in solution'
  src/EditorFeatures/Core.Cocoa/Suggestions/SuggestedActions/FixAllSuggestedAction.FixAllCodeAction.cs
  src/Features/Core/Portable/CodeFixes/FixAllOccurrences/FixSomeCodeAction.cs
  src/VisualStudio/Core/Def/Implementation/Utilities/VisualStudioWaitContext.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.DiagnosticProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/DocumentBasedFixAllProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/SyntaxEditorBasedCodeFixProvider.FixAllProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Utilities/IProgressTracker.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Utilities/NoOpProgressTracker.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensionsResources.resx
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.cs.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.de.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.es.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.fr.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.it.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.ja.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.ko.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.pl.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.pt-BR.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.ru.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.tr.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.zh-Hans.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.zh-Hant.xlf
Labels: Area-IDE

#49120 Do not cast when refactoring 'foreach var'
  src/EditorFeatures/CSharpTest/ConvertForEachToFor/ConvertForEachToForTests.cs
  src/Features/CSharp/Portable/ConvertForEachToFor/CSharpConvertForEachToForCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertForEachToFor/AbstractConvertForEachToForCodeRefactoringProvider.cs
Labels: Area-Analyzers, Community
