Repository dotnet/roslyn, pull requests merged in 2021-08, with the labels that each got.

#55307 Track "raw string literals" feature
  docs/Language Feature Status.md
Labels: Area-Compilers

#55295 Revert "Merge pull request #54323 from dotnet/darc-release/dev16.11-8…
  azure-pipelines-official.yml
  azure-pipelines-pr-validation.yml
  azure-pipelines.yml
  docs/contributing/Building, Debugging, and Testing on Windows.md
  eng/Tools.props
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/SetupNugetSources.ps1
  eng/common/SetupNugetSources.sh
  eng/common/build.ps1
  eng/common/cross/arm64/tizen-fetch.sh
  eng/common/cross/build-rootfs.sh
  eng/common/dotnet-install.sh
  eng/common/generate-locproject.ps1
  eng/common/internal-feed-operations.ps1
  eng/common/internal-feed-operations.sh
  eng/common/msbuild.ps1
  eng/common/performance/blazor_perf.proj
  eng/common/performance/crossgen_perf.proj
  eng/common/performance/microbenchmarks.proj
  eng/common/performance/performance-setup.ps1
  eng/common/performance/performance-setup.sh
  eng/common/post-build/sourcelink-validation.ps1
  eng/common/post-build/symbols-validation.ps1
  eng/common/sdk-task.ps1
  eng/common/sdl/configure-sdl-tool.ps1
  eng/common/sdl/execute-all-sdl-tools.ps1
  eng/common/sdl/extract-artifact-archives.ps1
  eng/common/sdl/init-sdl.ps1
  eng/common/sdl/run-sdl.ps1
  eng/common/templates/job/execute-sdl.yml
  eng/common/templates/job/onelocbuild.yml
  eng/common/templates/job/performance.yml
  eng/common/templates/job/source-build.yml
  eng/common/templates/job/source-index-stage1.yml
  eng/common/templates/post-build/channels/generic-internal-channel.yml
  eng/common/templates/post-build/channels/generic-public-channel.yml
  eng/common/templates/steps/perf-send-to-helix.yml
  eng/common/templates/steps/source-build.yml
  eng/common/tools.ps1
  eng/common/tools.sh
  eng/test-build-correctness.ps1
  eng/test-determinism.ps1
  eng/test-rebuild.ps1
  global.json
Labels: Area-Infrastructure

#55168 Enable rollforward
  global.json
Labels: Area-Infrastructure

#55340 Make interface imports of debugger interfaces lazy
  src/EditorFeatures/Core/Implementation/EditAndContinue/ManagedEditAndContinueLanguageService.cs
  src/EditorFeatures/Core/Implementation/EditAndContinue/ManagedHotReloadLanguageService.cs
Labels: Area-Interactive

#52805 Cleaning up compiler server interface
  src/Compilers/CSharp/csc/Program.cs
  src/Compilers/Core/CommandLine/BuildProtocol.cs
  src/Compilers/Core/MSBuildTask/ManagedCompiler.cs
  src/Compilers/Server/VBCSCompiler/BuildServerController.cs
  src/Compilers/Server/VBCSCompilerTests/BuildClientTests.cs
  src/Compilers/Server/VBCSCompilerTests/BuildServerConnectionTests.cs
  src/Compilers/Server/VBCSCompilerTests/CompilerServerTests.cs
  src/Compilers/Server/VBCSCompilerTests/ServerUtil.cs
  src/Compilers/Server/VBCSCompilerTests/VBCSCompilerServerTests.cs
  src/Compilers/Shared/BuildClient.cs
  src/Compilers/Shared/BuildServerConnection.cs
  src/Compilers/VisualBasic/vbc/Program.cs
Labels: Area-Compilers

#55355 Add back loc changes from arcade that were reverted
  eng/common/generate-locproject.ps1
  eng/common/templates/job/onelocbuild.yml
Labels: Area-Infrastructure

#55364 Fix crash with convert namespace
  src/Analyzers/CSharp/CodeFixes/ConvertNamespace/ConvertNamespaceCodeFixProvider.cs
  src/Dependencies/PooledObjects/Microsoft.CodeAnalysis.PooledObjects.Package.csproj
  src/EditorFeatures/CSharpTest/ConvertNamespace/ConvertToBlockScopedNamespaceAnalyzerTests.cs
  src/EditorFeatures/CSharpTest/ConvertNamespace/ConvertToFileScopedNamespaceAnalyzerTests.cs
Labels: Area-IDE

#55352 Update PooledObjects.Package with NETFramework.ReferenceAssemblies dependency
  src/Dependencies/PooledObjects/Microsoft.CodeAnalysis.PooledObjects.Package.csproj
Labels: Area-Infrastructure

#55290 Fix 'quick info' and 'use explicit type' for implicit lambdas
  src/Analyzers/CSharp/Tests/UseImplicitOrExplicitType/UseExplicitTypeTests.cs
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Types.cs
  src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
  src/Features/Core/Portable/LanguageServices/SymbolDisplayService/AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ISymbolExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ITypeSymbolExtensions.cs
Labels: Area-IDE, Needs Shiproom Approval

#55380 Only prefer interpolated string handler conversions in C# 10
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
Labels: Area-Compilers

#55354 Add IFieldSymbol.FixedSize API
  src/Compilers/CSharp/Portable/Symbols/PublicModel/FieldSymbol.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/FieldTests.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Core/Portable/Symbols/IFieldSymbol.cs
  src/Compilers/VisualBasic/Portable/Symbols/FieldSymbol.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/FieldTests.vb
  src/Features/Core/Portable/MetadataAsSource/AbstractMetadataAsSourceService.WrappedFieldSymbol.cs
  src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationFieldSymbol.cs
Labels: Area-Compilers

#55259 Inline Hints Perf
  src/EditorFeatures/Core.Wpf/InlineHints/InlineHintsTag.cs
  src/EditorFeatures/Core.Wpf/InlineHints/InlineHintsTagger.cs
Labels: Area-IDE, New Feature - Inline Parameter Hints

#55002 List patterns: Fix pattern lookup on nullable types
  src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests_ListPatterns.cs
Labels: Area-Compilers

#55294 Report telemetry for HotReload sessions
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/EditorFeatures/Test/EditAndContinue/TraceLogTests.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSession.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSessionTelemetry.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/Core/Portable/EditAndContinue/EditSessionTelemetry.cs
  src/Features/Core/Portable/EditAndContinue/SolutionUpdate.cs
  src/Features/Core/Portable/EditAndContinue/TraceLog.cs
Labels: Area-Interactive

#55365 Fix emit of synthesized types nested in a reloadable type
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/DeltaMetadataWriter.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/SymbolChanges.cs
Labels: Area-Compilers

#55299 Inline Diagnostics Hyperlink Color
  src/EditorFeatures/Core.Wpf/InlineDiagnostics/InlineDiagnosticsTag.cs
  src/EditorFeatures/Core.Wpf/InlineDiagnostics/InlineDiagnosticsTaggerProvider.cs
Labels: Area-IDE, New Feature - Inline Errors

#55386 Apply reference update operation in ReferenceCleanupService
  src/VisualStudio/Core/Def/Implementation/UnusedReferences/VisualStudioReferenceCleanupService.cs
Labels: Approved to merge, Area-IDE

#55296 Add GoToDefinition for XAML LSP
  src/VisualStudio/Xaml/Impl/Features/Definitions/IXamlGoToDefinitionService.cs
  src/VisualStudio/Xaml/Impl/Features/Definitions/XamlDefinition.cs
  src/VisualStudio/Xaml/Impl/Features/Definitions/XamlSourceDefinition.cs
  src/VisualStudio/Xaml/Impl/Features/Definitions/XamlSymbolDefinition.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageClient/XamlCapabilities.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Definitions/GoToDefinitionHandler.cs
Labels: Area-IDE

#55409 Use FixedSize API
  src/Features/CSharp/Portable/EditAndContinue/CSharpEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
  src/Features/VisualBasic/Portable/EditAndContinue/VisualBasicEditAndContinueAnalyzer.vb
Labels: Area-Interactive

#55408 Update package references
  src/Dependencies/CodeAnalysis.Debugging/Microsoft.CodeAnalysis.Debugging.Package.csproj
  src/Dependencies/PooledObjects/Microsoft.CodeAnalysis.PooledObjects.Package.csproj
  src/ExpressionEvaluator/Core/Source/FunctionResolver/Microsoft.CodeAnalysis.FunctionResolver.csproj
Labels: Area-Infrastructure

#55274 Add incremental generator specification
  docs/features/incremental-generators.md
Labels: Area-Compilers, Documentation

#55405 More tests for lambda expressions with explicit return type
  src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/LambdaReturnTypeParsingTests.cs
Labels: Area-Compilers, Test

#55363 Make dynamic path map case insensitive to match source files
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProject.cs
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioProjectTests/DynamicFileTests.vb
Labels: Area-IDE

#55424 Fix matchnamespacetofolder analyzer/codefix
  src/Analyzers/CSharp/Tests/MatchFolderAndNamespace/CSharpMatchFolderAndNamespaceTests.cs
  src/Analyzers/Core/CodeFixes/MatchFolderAndNamespace/AbstractChangeNamespaceToMatchFolderCodeFixProvider.cs
  src/Features/Core/Portable/CodeRefactorings/SyncNamespace/AbstractSyncNamespaceCodeRefactoringProvider.State.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/PathMetadataUtilities.cs
Labels: Area-IDE

#55318 Move IAddMissingImportsFeatureService to use OOP
  src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs
  src/Features/Core/Portable/AddImport/IAddImportFeatureService.cs
  src/Features/Core/Portable/AddImport/Remote/IRemoteMissingImportDiscoveryService.cs
  src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs
  src/Workspaces/Remote/ServiceHub/Services/MissingImportDiscovery/RemoteMissingImportDiscoveryService.cs
Labels: Area-IDE

#55447 prevent Editor's typing responsiveness canceling the rename operation
  src/EditorFeatures/Core/Implementation/InlineRename/CommandHandlers/AbstractRenameCommandHandler_ReturnHandler.cs
Labels: Area-IDE

#55448 MEF import completion providers in background
  src/Features/Core/Portable/Completion/CompletionServiceWithProviders.cs
  src/VisualStudio/CSharp/Impl/LanguageService/CSharpCreateServicesOnTextViewConnection.cs
  src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractCreateServicesOnTextViewConnection.cs
  src/VisualStudio/VisualBasic/Impl/LanguageService/VisualBasicCreateServicesOnTextViewConnection.vb
Labels: Area-IDE

#55449 ValueTracking: Don't wrap TreeView in ScrollViewer
  src/VisualStudio/Core/Def/ValueTracking/ValueTrackingTree.xaml
Labels: Area-IDE, Feature - IDE Value Tracking

#55368 Use speakable type for top-level statements
  docs/compilers/CSharp/Compiler Breaking Changes - post DotNet 5.md
  src/Compilers/CSharp/Portable/Binder/BinderFactory.BinderFactoryVisitor.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs
  src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs
  src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.cs
  src/Compilers/CSharp/Portable/Declarations/DeclarationKind.cs
  src/Compilers/CSharp/Portable/Declarations/DeclarationTreeBuilder.cs
  src/Compilers/CSharp/Portable/Declarations/SingleTypeDeclaration.cs
  src/Compilers/CSharp/Portable/Lowering/SynthesizedMethodBaseSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/EnumConversions.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SimpleProgramNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceNamespaceSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedBackingFieldSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedContainer.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedFieldSymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedSimpleProgramEntryPointSymbol.cs
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/UnsafeTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/DynamicAnalysis/DynamicInstrumentationTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueClosureTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/FunctionPointerTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/GlobalUsingDirectiveTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternSwitchTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/TopLevelStatementsTests.cs
  src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs
  src/Compilers/Core/Portable/PublicAPI.Shipped.txt
  src/Compilers/Core/Portable/Symbols/WellKnownMemberNames.cs
  src/Compilers/Test/Core/Compilation/ControlFlowGraphVerifier.cs
  src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_CallerArgumentExpression.vb
  src/EditorFeatures/CSharpTest/EditAndContinue/TopLevelEditingTests.cs
  src/EditorFeatures/CSharpTest/GenerateVariable/GenerateVariableTests.cs
  src/Features/Core/Portable/GenerateMember/GenerateVariable/AbstractGenerateVariableService.State.cs
Labels: Area-Compilers, New Language Feature - Simple Programs

#55419 Make vsix's compatible with vs 2022
  src/Compilers/Extension/source.extension.vsixmanifest
  src/Deployment/source.extension.vsixmanifest
  src/ExpressionEvaluator/Package/source.extension.vsixmanifest
  src/VisualStudio/Setup.Dependencies/source.extension.vsixmanifest
  src/VisualStudio/Setup/source.extension.vsixmanifest
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/source.extension.vsixmanifest
Labels: Area-IDE, Area-Infrastructure

#55464 Background import
  src/VisualStudio/CSharp/Impl/LanguageService/CSharpCreateServicesOnTextViewConnection.cs
  src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractCreateServicesOnTextViewConnection.cs
  src/VisualStudio/VisualBasic/Impl/LanguageService/VisualBasicCreateServicesOnTextViewConnection.vb
Labels: Area-IDE

#55445 Add help link to pull diagnostics errors
  src/VisualStudio/Xaml/Impl/Features/Diagnostics/XamlDiagnostic.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
Labels: Area-IDE, Concept-Continuous Improvement, LSP

#55454 Fix GetSolutionDiagnostics for ChangeNamespace FixAllProvider
  src/Analyzers/Core/CodeFixes/MatchFolderAndNamespace/AbstractChangeNamespaceToMatchFolderCodeFixProvider.CustomFixAllProvider.cs
Labels: Area-IDE

#55425 Try to fix the analyzer path when loading in OOP
  src/Workspaces/Remote/ServiceHub/Host/RemoteAnalyzerAssemblyLoaderService.cs
Labels: Area-IDE

#55480 Remove analyzer entries which contains no analzyers from vsix manifest
  src/VisualStudio/Setup/source.extension.vsixmanifest
Labels: Area-IDE

#55430 Fix LSP semantic tokens algorithm
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/SemanticTokensEditsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/SemanticTokensTests.cs
Labels: Area-IDE, LSP

#54787 EnC - add tests for attributes on events
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/TopLevelEditingTests.cs
Labels: Area-Interactive

#55495 Remove unneeded `Shared` attribute
  src/Features/CSharp/Portable/UsePatternMatching/CSharpIsAndCastCheckWithoutNameDiagnosticAnalyzer.cs
Labels: Area-IDE

#55238 Remove unnecessary "run-nullable-analysis=never"
  azure-pipelines.yml
Labels: Area-Infrastructure

#55450 Change VB Code Generators to use entire block when reusing method syntax
  src/EditorFeatures/Test/CodeGeneration/CodeGenerationTests.CSharp.cs
  src/EditorFeatures/Test/CodeGeneration/CodeGenerationTests.VisualBasic.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Extensions/SyntaxNodeExtensions.vb
  src/Workspaces/VisualBasic/Portable/CodeGeneration/EventGenerator.vb
  src/Workspaces/VisualBasic/Portable/CodeGeneration/MethodGenerator.vb
  src/Workspaces/VisualBasic/Portable/CodeGeneration/PropertyGenerator.vb
Labels: Area-IDE

#55481 include help link uri in lsp pull diagnostics
  src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
Labels: Area-IDE, LSP

#55382 remove ".editorconfig added to solution" yellow bar
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/AnalyzerConfigDocumentAsSolutionItemHandler.cs
  src/VisualStudio/Core/Def/RoslynPackage.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
Labels: Area-IDE

#55490 Register missing encoding providers for core host
  src/Workspaces/Remote/ServiceHub/Services/Host/RemoteHostService.cs
Labels: Area-IDE

#52336 Don't include analyzers in compilers solution
  Compilers.sln
  Compilers.slnf
Labels: Area-Compilers, Community

#55468 Fix link for lambda improvements
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation

#55463 Use new document formatting service when generating types
  src/Analyzers/CSharp/CodeFixes/MisplacedUsingDirectives/MisplacedUsingDirectivesCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/FileHeaders/AbstractFileHeaderCodeFixProvider.cs
  src/EditorFeatures/CSharpTest/Diagnostics/GenerateType/GenerateTypeTests.cs
  src/EditorFeatures/CSharpTest/Formatting/CSharpNewDocumentFormattingServiceTests.cs
  src/EditorFeatures/TestUtilities/Formatting/AbstractNewDocumentFormattingServiceTests.cs
  src/EditorFeatures/VisualBasicTest/Formatting/VisualBasicNewDocumentFormattingServiceTests.vb
  src/Features/CSharp/Portable/AddFileBanner/CSharpAddFileBannerNewDocumentFormattingProvider.cs
  src/Features/CSharp/Portable/Formatting/CSharpAccessibilityModifiersNewDocumentFormattingProvider.cs
  src/Features/CSharp/Portable/Formatting/CSharpNewDocumentFormattingService.cs
  src/Features/CSharp/Portable/Formatting/CSharpOrganizeUsingsNewDocumentFormattingProvider.cs
  src/Features/Core/Portable/AddFileBanner/AbstractAddFileBannerNewDocumentFormattingProvider.cs
  src/Features/Core/Portable/Formatting/AbstractNewDocumentFormattingService.cs
  src/Features/Core/Portable/Formatting/ExportNewDocumentFormattingProviderAttribute.cs
  src/Features/Core/Portable/Formatting/INewDocumentFormattingProvider.cs
  src/Features/Core/Portable/Formatting/INewDocumentFormattingService.cs
  src/Features/Core/Portable/GenerateType/AbstractGenerateTypeService.Editor.cs
  src/Features/VisualBasic/Portable/AddFileBanner/VisualBasicAddFileBannerNewDocumentFormattingProvider.vb
  src/Features/VisualBasic/Portable/Formatting/VisualBasicNewDocumentFormattingService.vb
  src/Features/VisualBasic/Portable/Formatting/VisualBasicOrganizeUsingsNewDocumentFormattingProvider.vb
  src/VisualStudio/CSharp/Impl/LanguageService/CSharpEditorFactory.cs
  src/VisualStudio/Core/Def/Implementation/AbstractEditorFactory.cs
  src/VisualStudio/VisualBasic/Impl/LanguageService/VisualBasicEditorFactory.vb
Labels: Area-IDE

#55504 Format new document namespace declarations
  src/EditorFeatures/CSharpTest/Formatting/CSharpNewDocumentFormattingServiceTests.cs
  src/EditorFeatures/TestUtilities/Formatting/AbstractNewDocumentFormattingServiceTests.cs
  src/EditorFeatures/VisualBasicTest/Formatting/VisualBasicNewDocumentFormattingServiceTests.vb
  src/Features/CSharp/Portable/Formatting/CSharpNamespaceDeclarationNewDocumentFormattingProvider.cs
Labels: Area-IDE

#55204 Move static members to a New Type
  src/Compilers/Test/Core/Traits/Traits.cs
  src/EditorFeatures/CSharpTest/MoveStaticMembers/CSharpMoveStaticMembersTests.cs
  src/EditorFeatures/TestUtilities/MoveStaticMembers/TestMoveStaticMembersService.cs
  src/EditorFeatures/VisualBasicTest/MoveStaticMembers/VisualBasicMoveStaticMembersTests.vb
  src/Features/CSharp/Portable/CodeRefactorings/MoveStaticMembers/CSharpMoveStaticMembersRefactoringProvider.cs
  src/Features/Core/Portable/CodeRefactorings/PredefinedCodeRefactoringProviderNames.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/MoveStaticMembers/AbstractMoveStaticMembersRefactoringProvider.cs
  src/Features/Core/Portable/MoveStaticMembers/IMoveStaticMembersOptionsService.cs
  src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersOptions.cs
  src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Features/VisualBasic/Portable/CodeRefactorings/MoveStaticMembers/VisualBasicMoveStaticMembersRefactoringProvider.vb
  src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb
  src/VisualStudio/Core/Def/Implementation/MoveStaticMembers/MoveStaticMembersDialog.xaml
  src/VisualStudio/Core/Def/Implementation/MoveStaticMembers/MoveStaticMembersDialog.xaml.cs
  src/VisualStudio/Core/Def/Implementation/MoveStaticMembers/MoveStaticMembersDialogViewModel.cs
  src/VisualStudio/Core/Def/Implementation/MoveStaticMembers/StaticMemberSelection.xaml
  src/VisualStudio/Core/Def/Implementation/MoveStaticMembers/StaticMemberSelection.xaml.cs
  src/VisualStudio/Core/Def/Implementation/MoveStaticMembers/StaticMemberSelectionViewModel.cs
  src/VisualStudio/Core/Def/Implementation/MoveStaticMembers/VisualStudioMoveStaticMembersOptionsService.cs
  src/VisualStudio/Core/Def/Implementation/PullMemberUp/SymbolDependentsBuilder.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/Core/Test/MoveStaticMembers/MoveStaticMembersViewModelTest.vb
Labels: Area-IDE, New Feature - Move Static Members

#55520 Try to fix the analyzer path when loading in OOP
  src/Workspaces/Remote/ServiceHub/Host/RemoteAnalyzerAssemblyLoaderService.cs
Labels: Area-IDE

#55509 Annotate SyntaxFacts.IsValidIdentifier
  src/Compilers/CSharp/Portable/Parser/CharacterInfo.cs
Labels: Area-Compilers

#55482 Protect baseline readers from disposal while in use
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSession.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
Labels: Area-Interactive

#55494 Fix reversed output in interpolation concatenation
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperator.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
Labels: Area-Compilers, New Feature - Interpolated String Improvements

#55484 Remove obsolete UnitTesting and Razor External Access APIs
  Roslyn.sln
  src/NuGet/VisualStudio/VS.ExternalAPIs.Roslyn.Package.csproj
  src/Tools/ExternalAccess/Razor/Remote/RazorRemoteHostClient.cs
  src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj
  src/Workspaces/Core/Desktop/Microsoft.CodeAnalysis.Workspaces.Desktop.csproj
  src/Workspaces/Core/Portable/ExternalAccess/UnitTesting/Api/UnitTestingRemoteHostClientWrapper.cs
  src/Workspaces/Core/Portable/ExternalAccess/UnitTesting/Api/UnitTestingRemoteServiceConnectionWrapper.cs
  src/Workspaces/Core/Portable/ExternalAccess/UnitTesting/Api/UnitTestingServiceHubService.cs
  src/Workspaces/Core/Portable/ExternalAccess/UnitTesting/Api/UnitTestingWellKnownExperimentNamesAccessor.cs
  src/Workspaces/Core/Portable/ExternalAccess/UnitTesting/Api/UnitTestingWorkspaceKindUtilities.cs
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
  src/Workspaces/Core/Portable/Remote/RemoteServiceName.cs
  src/Workspaces/Core/Portable/Remote/WellKnownServiceHubService.cs
  src/Workspaces/Remote/Core/Microsoft.CodeAnalysis.Remote.Workspaces.csproj
  src/Workspaces/Remote/Razor/Microsoft.CodeAnalysis.Remote.Razor.ServiceHub.csproj
  src/Workspaces/Remote/Razor/PublicAPI.Shipped.txt
  src/Workspaces/Remote/Razor/PublicAPI.Unshipped.txt
  src/Workspaces/Remote/Razor/ServiceHubServiceBase.cs
  src/Workspaces/Remote/ServiceHub/Microsoft.CodeAnalysis.Remote.ServiceHub.csproj
Labels: Area-IDE

#54856 Allow parameter renames in Edit and Continue
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/CSharpSymbolMatcher.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/SymbolMatcherTests.cs
  src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/VisualBasicSymbolMatcher.vb
  src/Compilers/VisualBasic/Test/Emit/Emit/EditAndContinue/EditAndContinueTestBase.vb
  src/Compilers/VisualBasic/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.vb
  src/Compilers/VisualBasic/Test/Emit/Emit/EditAndContinue/SymbolMatcherTests.vb
  src/EditorFeatures/CSharpTest/EditAndContinue/ActiveStatementTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/StatementEditingTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/StatementMatchingTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/TopLevelEditingTests.cs
  src/EditorFeatures/TestUtilities/EditAndContinue/EditAndContinueTestHelpers.cs
  src/EditorFeatures/VisualBasicTest/EditAndContinue/TopLevelEditingTests.vb
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueCapabilities.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueDiagnosticDescriptors.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/RudeEditKind.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
Labels: Area-Compilers, Area-Interactive

#55039 Mark record struct generated methods as readonly where possible
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordBaseEquals.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordClone.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordDeconstruct.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEquals.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordGetHashCode.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordObjEquals.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordObjectMethod.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordOrdinaryMethod.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPrintMembers.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordToString.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/TopLevelEditingTests.cs
Labels: Area-Compilers

#53031 Extract Method Bug With Method Directly in Namespace
  src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractLocalFunctionTests.cs
  src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractMethodTests.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.CallSiteContainerRewriter.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionValidator.cs
  src/Features/CSharp/Portable/ExtractMethod/Extensions.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Features/VisualBasic/Portable/ExtractMethod/Extensions.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicSelectionValidator.vb
Labels: Area-IDE

#55202 More generic attributes tests
  docs/contributing/Compiler Test Plan.md
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LookupTests.cs
Labels: Area-Compilers, Test

#55530 Ignore modules with bad metadata in function resolver
  src/ExpressionEvaluator/Core/Source/FunctionResolver/FunctionResolver.cs
  src/ExpressionEvaluator/Core/Source/FunctionResolver/FunctionResolverBase.cs
  src/ExpressionEvaluator/Core/Test/FunctionResolver/CSharpFunctionResolverTests.cs
  src/ExpressionEvaluator/Core/Test/FunctionResolver/FunctionResolverTestBase.cs
  src/ExpressionEvaluator/Core/Test/FunctionResolver/Module.cs
  src/ExpressionEvaluator/Core/Test/FunctionResolver/Resolver.cs
Labels: Area-Interactive

#55428 Test adding nested namespaces
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/CSharpSymbolMatcher.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/VisualBasicSymbolMatcher.vb
  src/Compilers/VisualBasic/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.vb
Labels: Area-Interactive

#55514 Add ISB External Access APIs for IntelliCode
  src/Workspaces/Core/Portable/ExternalAccess/Pythia/Api/PythiaRemoteHostClient.cs
  src/Workspaces/Remote/Core/ExternalAccess/Pythia/Api/PythiaPinnedSolutionInfoWrapper.cs
  src/Workspaces/Remote/Core/ExternalAccess/Pythia/Api/PythiaRemoteHostClient.cs
  src/Workspaces/Remote/Core/ExternalAccess/Pythia/Api/PythiaRemoteServiceCallbackDispatcher.cs
  src/Workspaces/Remote/Core/ExternalAccess/Pythia/Api/PythiaRemoteServiceCallbackDispatcherRegistry.cs
  src/Workspaces/Remote/Core/ExternalAccess/Pythia/Api/PythiaRemoteServiceCallbackIdWrapper.cs
  src/Workspaces/Remote/Core/ExternalAccess/Pythia/Api/PythiaRemoteServiceConnectionWrapper.cs
  src/Workspaces/Remote/Core/ExternalAccess/Pythia/Api/PythiaServiceDescriptorsWrapper.cs
  src/Workspaces/Remote/ServiceHub/ExternalAccess/Pythia/Api/PythiaBrokeredServiceImplementation.cs
Labels: Area-IDE

#55559 Fix MatchFolderAndNamespace codefix for documents in project root
  src/Analyzers/CSharp/Tests/MatchFolderAndNamespace/CSharpMatchFolderAndNamespaceTests.cs
  src/Analyzers/Core/CodeFixes/MatchFolderAndNamespace/AbstractChangeNamespaceToMatchFolderCodeFixProvider.cs
Labels: Area-IDE

#55538 Align the Inheritance margin's header
  src/VisualStudio/Core/Def/Implementation/InheritanceMargin/MarginGlyph/InheritanceMargin.xaml
Labels: Area-IDE

#55407 Emit EnC info for methods with no sequence points
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueClosureTests.cs
  src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs
  src/Compilers/Core/Portable/NativePdbWriter/PdbWriter.cs
  src/Compilers/Core/Portable/PEWriter/CustomDebugInfoWriter.cs
  src/Compilers/Core/Portable/PEWriter/MetadataWriter.PortablePdb.cs
  src/Compilers/VisualBasic/Test/Emit/PDB/PDBExternalSourceDirectiveTests.vb
Labels: Area-Interactive

#55551 Merge Inline Diagnostics to Main
  src/EditorFeatures/Core.Wpf/Adornments/AbstractAdornmentManager.cs
  src/EditorFeatures/Core.Wpf/InlineDiagnostics/InlineDiagnosticsAdornmentManager.cs
  src/EditorFeatures/Core.Wpf/InlineDiagnostics/InlineDiagnosticsAdornmentManagerProvider.cs
  src/EditorFeatures/Core.Wpf/InlineDiagnostics/InlineDiagnosticsFormatDefinition.cs
  src/EditorFeatures/Core.Wpf/InlineDiagnostics/InlineDiagnosticsLocations.cs
  src/EditorFeatures/Core.Wpf/InlineDiagnostics/InlineDiagnosticsOptions.cs
  src/EditorFeatures/Core.Wpf/InlineDiagnostics/InlineDiagnosticsTag.cs
  src/EditorFeatures/Core.Wpf/InlineDiagnostics/InlineDiagnosticsTaggerProvider.cs
  src/EditorFeatures/Core.Wpf/LineSeparators/LineSeparatorAdornmentManager.cs
  src/EditorFeatures/Core/EditorFeaturesResources.resx
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.cs.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.de.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.es.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.fr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.it.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ja.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ko.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pl.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pt-BR.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ru.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.tr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hans.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hant.xlf
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/ColorSchemes/VisualStudio2017.xml
  src/VisualStudio/Core/Def/ColorSchemes/VisualStudio2019.xml
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageStrings.vb
  src/Workspaces/Core/Portable/Shared/TestHooks/FeatureAttribute.cs
Labels: Area-IDE, New Feature - Inline Errors

#55565 Fix issue where we return diagnostics typescript diagnostics from the C# LSP server
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/LanguageServer/Protocol/AbstractRequestDispatcherFactory.cs
  src/Features/LanguageServer/Protocol/CSharpVisualBasicLanguageServerFactory.cs
  src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionsHandlerProvider.cs
  src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandlerProvider.cs
  src/Features/LanguageServer/Protocol/Handler/Definitions/GoToDefinitionHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Definitions/GoToTypeDefinitionHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DocumentPullDiagonsticHandlerProvider.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandlerProvider.cs
  src/Features/LanguageServer/Protocol/Handler/DocumentChanges/DidChangeHandler.cs
  src/Features/LanguageServer/Protocol/Handler/DocumentChanges/DidCloseHandler.cs
  src/Features/LanguageServer/Protocol/Handler/DocumentChanges/DidOpenHandler.cs
  src/Features/LanguageServer/Protocol/Handler/ExportLspRequestHandlerProviderAttribute.cs
  src/Features/LanguageServer/Protocol/Handler/FoldingRanges/FoldingRangesHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Formatting/FormatDocumentHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Formatting/FormatDocumentOnTypeHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Formatting/FormatDocumentRangeHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Highlights/DocumentHighlightHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Hover/HoverHandler.cs
  src/Features/LanguageServer/Protocol/Handler/OnAutoInsert/OnAutoInsertHandler.cs
  src/Features/LanguageServer/Protocol/Handler/ProjectContext/GetTextDocumentWithContextHandler.cs
  src/Features/LanguageServer/Protocol/Handler/References/FindAllReferencesHandler.cs
  src/Features/LanguageServer/Protocol/Handler/References/FindImplementationsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Rename/RenameHandler.cs
  src/Features/LanguageServer/Protocol/Handler/RequestContext.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.QueueItem.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs
  src/Features/LanguageServer/Protocol/Handler/RequestHandlerProviderMetadataView.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHandlerProvider.cs
  src/Features/LanguageServer/Protocol/Handler/SignatureHelp/SignatureHelpHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Symbols/DocumentSymbolsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Symbols/WorkspaceSymbolsHandler.cs
  src/Features/LanguageServer/Protocol/LanguageServerTarget.cs
  src/Features/LanguageServer/Protocol/ProtocolConstants.cs
  src/Features/LanguageServer/Protocol/RequestDispatcher.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/DocumentChanges/DocumentChangesTests.LinkedDocuments.cs
  src/Features/LanguageServer/ProtocolUnitTests/Ordering/FailingMutatingRequestHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Ordering/FailingRequestHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Ordering/MutatingRequestHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Ordering/NonLSPSolutionRequestHandlerProvider.cs
  src/Features/LanguageServer/ProtocolUnitTests/Ordering/NonMutatingRequestHandler.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/AbstractInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/AlwaysActivateInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/LiveShareInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/RazorInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/VisualStudioInProcLanguageServer.cs
  src/VisualStudio/Core/Test.Next/Services/LspDiagnosticsTests.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageClient/XamlInProcLanguageClient.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageClient/XamlInProcLanguageClientDisableUX.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/XamlRequestDispatcherFactory.cs
Labels: Area-IDE, LSP

#54404 Align controls on the PullMembersUp Dialog
  src/VisualStudio/Core/Def/Implementation/CommonControls/MemberSelection.xaml
  src/VisualStudio/Core/Def/Implementation/PullMemberUp/MainDialog/PullMemberUpDialog.xaml
Labels: Area-IDE

#55556 Move generic-attributes to preview LangVersion
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/BindingTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs
Labels: Area-Compilers

#55429 Adds a SolutionExplorer context menu command for syncing namespaces
  src/Analyzers/CSharp/Analyzers/MatchFolderAndNamespace/CSharpMatchFolderAndNamespaceDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/MatchFolderAndNamespace/CSharpChangeNamespaceToMatchFolderCodeFixProvider.cs
  src/Compilers/Test/Core/Traits/Traits.cs
  src/EditorFeatures/Test2/Microsoft.CodeAnalysis.EditorFeatures2.UnitTests.vbproj
  src/EditorFeatures/Test2/SyncNamespaces/SyncNamespacesServiceTests.vb
  src/Features/CSharp/Portable/SyncNamespaces/CSharpSyncNamespacesService.cs
  src/Features/Core/Portable/SyncNamespaces/AbstractSyncNamespacesSevice.cs
  src/Features/Core/Portable/SyncNamespaces/ISyncNamespacesService.cs
  src/VisualStudio/Core/Def/Commands.vsct
  src/VisualStudio/Core/Def/ID.RoslynCommands.cs
  src/VisualStudio/Core/Def/Implementation/SyncNamespaces/SyncNamespacesCommandHandler.cs
  src/VisualStudio/Core/Def/RoslynPackage.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/Commands.vsct.cs.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.de.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.es.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.fr.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.it.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.ja.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.ko.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.pl.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.ru.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.tr.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.zh-Hant.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
Labels: Area-IDE

#55558 Generated names refactoring & support for function breakpoints on local functions
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/CSharpDefinitionMap.cs
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/PEDeltaAssemblyBuilder.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNameConstants.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNameKind.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNameParser.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNames.cs
  src/Compilers/Core/Portable/InternalUtilities/StringExtensions.cs
  src/Compilers/VisualBasic/Portable/Binding/Binder_Query.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Utils.vb
  src/Compilers/VisualBasic/Portable/BoundTree/GroupTypeInferenceLambda.vb
  src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/PEDeltaAssemblyBuilder.vb
  src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/VisualBasicDefinitionMap.vb
  src/Compilers/VisualBasic/Portable/Lowering/AsyncRewriter/AsyncRewriter.vb
  src/Compilers/VisualBasic/Portable/Lowering/LambdaRewriter/LambdaCapturedVariable.vb
  src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Query.vb
  src/Compilers/VisualBasic/Portable/Lowering/StateMachineRewriter/StateMachineRewriter.vb
  src/Compilers/VisualBasic/Portable/Lowering/StateMachineRewriter/SynthesizedContainer.vb
  src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb
  src/Compilers/VisualBasic/Portable/StringConstants.vb
  src/Compilers/VisualBasic/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousDelegate_TemplateSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType_TemplateSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceEventSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/SynthesizedSymbols/GeneratedNameConstants.vb
  src/Compilers/VisualBasic/Portable/Symbols/SynthesizedSymbols/GeneratedNameKind.vb
  src/Compilers/VisualBasic/Portable/Symbols/SynthesizedSymbols/GeneratedNameParser.vb
  src/Compilers/VisualBasic/Portable/Symbols/SynthesizedSymbols/GeneratedNames.vb
  src/Compilers/VisualBasic/Portable/Symbols/SynthesizedSymbols/SynthesizedEventDelegateSymbol.vb
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Binders/EEMethodBinder.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CSharpInstructionDecoder.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationExtensions.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/DisplayClassInstance.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/DisplayClassVariable.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EEMethodSymbol.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/HoistedThisTests.cs
  src/ExpressionEvaluator/Core/Source/FunctionResolver/FunctionResolverBase.cs
  src/ExpressionEvaluator/Core/Source/FunctionResolver/MetadataResolver.cs
  src/ExpressionEvaluator/Core/Source/FunctionResolver/Microsoft.CodeAnalysis.FunctionResolver.csproj
  src/ExpressionEvaluator/Core/Test/FunctionResolver/CSharpFunctionResolverTests.cs
  src/ExpressionEvaluator/Core/Test/FunctionResolver/Module.cs
  src/ExpressionEvaluator/VisualBasic/Source/ExpressionCompiler/Binders/ParametersAndLocalsBinder.vb
  src/ExpressionEvaluator/VisualBasic/Source/ExpressionCompiler/CompilationContext.vb
  src/ExpressionEvaluator/VisualBasic/Source/ExpressionCompiler/CompilationExtensions.vb
  src/ExpressionEvaluator/VisualBasic/Source/ExpressionCompiler/EvaluationContext.vb
  src/ExpressionEvaluator/VisualBasic/Source/ExpressionCompiler/Rewriters/CapturedVariableRewriter.vb
  src/ExpressionEvaluator/VisualBasic/Source/ExpressionCompiler/SymbolExtensions.vb
  src/ExpressionEvaluator/VisualBasic/Source/ExpressionCompiler/VisualBasicInstructionDecoder.vb
  src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/HoistedMeTests.vb
  src/Scripting/CSharp/Hosting/ObjectFormatter/CSharpTypeNameFormatter.cs
Labels: Area-Compilers

#55522 Call new document formatting service from extract type
  src/EditorFeatures/CSharpTest/ExtractClass/ExtractClassTests.cs
  src/EditorFeatures/CSharpTest/ExtractInterface/ExtractInterfaceTests.cs
  src/EditorFeatures/TestUtilities/ExtractInterface/AbstractExtractInterfaceTests.cs
  src/Features/Core/Portable/ExtractClass/ExtractClassWithDialogCodeAction.cs
  src/Features/Core/Portable/ExtractInterface/AbstractExtractInterfaceService.cs
  src/Features/Core/Portable/Shared/Utilities/ExtractTypeHelpers.cs
Labels: Area-IDE

#55586 Test framework movement
  src/EditorFeatures/CSharpTest/MoveStaticMembers/CSharpMoveStaticMembersTests.cs
  src/EditorFeatures/TestUtilities/MoveStaticMembers/TestMoveStaticMembersService.cs
  src/EditorFeatures/VisualBasicTest/MoveStaticMembers/VisualBasicMoveStaticMembersTests.vb
  src/Features/CSharp/Portable/CodeRefactorings/MoveStaticMembers/CSharpMoveStaticMembersRefactoringProvider.cs
  src/Features/Core/Portable/MoveStaticMembers/AbstractMoveStaticMembersRefactoringProvider.cs
  src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs
  src/Features/Core/Portable/PullMemberUp/MembersPuller.cs
  src/Features/VisualBasic/Portable/CodeRefactorings/MoveStaticMembers/VisualBasicMoveStaticMembersRefactoringProvider.vb
  src/VisualStudio/Core/Test/MoveStaticMembers/MoveStaticMembersViewModelTest.vb
Labels: Area-IDE, New Feature - Move Static Members

#55585 Avoid delegate allocations in SQLite code
  src/Workspaces/Core/Portable/Storage/SQLite/v2/Interop/SqlConnection.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_FlushWrites.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_Threading.cs
Labels: Area-IDE

#55584 Add C++/CLI to test plan
  docs/contributing/Compiler Test Plan.md
Labels: Area-Compilers, Documentation

#55598 Offer add imports for generic extension methods that match non-generic instance methods
  src/EditorFeatures/CSharpTest/AddUsing/AddUsingTests_ExtensionMethods.cs
  src/Features/CSharp/Portable/AddImport/CSharpAddImportFeatureService.cs
Labels: Area-IDE

#55603 Prevent resetting the color when mouse is hovering over inheritance margin
  src/VisualStudio/Core/Def/Implementation/InheritanceMargin/InheritanceMarginTaggerProvider.cs
  src/VisualStudio/Core/Def/Implementation/InheritanceMargin/MarginGlyph/InheritanceMargin.xaml.cs
Labels: Area-IDE

#55549 Record structs have no copy constructors
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordCopyCtor.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs
Labels: Area-Compilers

#55552 Microsoft.Net.Compilers.Toolset.props make available for outerbuild targets
  src/NuGet/Microsoft.Net.Compilers.Toolset/Microsoft.Net.Compilers.Toolset.Package.csproj
  src/NuGet/Microsoft.Net.Compilers.Toolset/buildMultiTargeting/Microsoft.Net.Compilers.Toolset.props
Labels: Area-Infrastructure

#55599 Shutdown LSP server on streamjsonrpc disconnect
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.DocumentChangeTracker.cs
  src/Features/LanguageServer/Protocol/LanguageServerTarget.cs
  src/Features/LanguageServer/ProtocolUnitTests/LanguageServerTargetTests.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/VisualStudioInProcLanguageServer.cs
Labels: Area-IDE, LSP

#55615 Enforce non-mutating LSP requests to run in parallel.
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs
  src/Features/LanguageServer/ProtocolUnitTests/Ordering/LongRunningNonMutatingRequestHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Ordering/RequestOrderingTests.cs
Labels: Area-IDE

#55465 Avoid logging analyzer telemetry during shutdown
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs
Labels: Area-IDE

#55614 Move NonRemappableRegions, Capabilities to EditSession
  src/EditorFeatures/CSharpTest/EditAndContinue/CSharpEditAndContinueAnalyzerTests.cs
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueCapabilitiesTests.cs
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/EditorFeatures/Test/EditAndContinue/EditSessionActiveStatementsTests.cs
  src/EditorFeatures/TestUtilities/EditAndContinue/EditAndContinueTestHelpers.cs
  src/EditorFeatures/TestUtilities/EditAndContinue/MockManagedEditAndContinueDebuggerService.cs
  src/EditorFeatures/VisualBasicTest/EditAndContinue/VisualBasicEditAndContinueAnalyzerTests.vb
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSession.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueCapabilities.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueDocumentAnalysesCache.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/Core/Portable/EditAndContinue/IEditAndContinueAnalyzer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/AsyncLazy`1.cs
Labels: Area-Interactive, Interactive-EnC

#55618 Fix incorrectly flagged comment
  src/Features/LanguageServer/ProtocolUnitTests/Ordering/RequestOrderingTests.cs
Labels: Area-IDE, LSP

#55617 Fix regression with conversion to FormattableString
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/TypeConversions.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
Labels: Area-Compilers, New Feature - Interpolated String Improvements

#55640 Exclude binaries provided by runtime from vsix
  src/Workspaces/Remote/ServiceHub.CoreComponents/Microsoft.CodeAnalysis.Remote.ServiceHub.CoreComponents.csproj
Labels: Area-IDE

#55426 Allow OOP features to sync only the subset of projects they need for functioning
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs
  src/Features/Core/Portable/DocumentHighlighting/AbstractDocumentHighlightsService.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.cs
  src/Features/Core/Portable/NavigationBar/AbstractNavigationBarItemService.cs
  src/VisualStudio/Core/Def/Implementation/SemanticClassificationCache/SemanticClassificationCacheIncrementalAnalyzerProvider.cs
  src/VisualStudio/Core/Test.Next/Remote/JsonConverterTests.cs
  src/VisualStudio/Core/Test.Next/Services/AssetProviderTests.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/VisualStudio/Core/Test.Next/Services/SolutionServiceTests.cs
  src/Workspaces/Core/Portable/Classification/AbstractClassificationService.cs
  src/Workspaces/Core/Portable/Options/SerializableOptionSet.cs
  src/Workspaces/Core/Portable/Remote/PinnedSolutionInfo.cs
  src/Workspaces/Core/Portable/Remote/RemoteHostClient.cs
  src/Workspaces/Core/Portable/Remote/RemoteServiceConnection.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState_Checksum.cs
  src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs
  src/Workspaces/Remote/Core/BrokeredServiceConnection.cs
  src/Workspaces/Remote/Core/Serialization/RoslynJsonConverter.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspaceManager.cs
  src/Workspaces/Remote/ServiceHub/Host/TestUtils.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs
  src/Workspaces/Remote/ServiceHub/Services/ServiceBase.cs
Labels: Area-IDE

#55335 Generate minimal canonical records from tuples
  src/EditorFeatures/CSharpTest/ConvertTupleToStruct/ConvertTupleToStructTests.cs
  src/Features/Core/Portable/ConvertTupleToStruct/AbstractConvertTupleToStructCodeRefactoringProvider.cs
Labels: Area-IDE

#55573 Inline Hints: Option added for array indexing
  src/EditorFeatures/Core/InlineHints/InlineHintsDataTaggerProvider.cs
  src/EditorFeatures/Test2/InlineHints/CSharpInlineParameterNameHintsTests.vb
  src/Features/CSharp/Portable/InlineHints/CSharpInlineParameterNameHintsService.cs
  src/Features/Core/Portable/InlineHints/AbstractInlineParameterNameHintsService.cs
  src/Features/Core/Portable/InlineHints/InlineHintsOptions.cs
  src/Features/VisualBasic/Portable/InlineHints/VisualBasicInlineParameterNameHintsService.vb
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageStrings.vb
Labels: Area-IDE, New Feature - Inline Parameter Hints

#55521 Fix interpolated string refactoring to work for Console.Write*
  src/EditorFeatures/CSharpTest/ConvertToInterpolatedString/ConvertPlaceholderToInterpolatedStringTests.cs
  src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs
Labels: Area-IDE

#55646 Update codestyle analyzer
  dotnet-tools.json
  eng/Versions.props
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordCopyCtor.cs
Labels: Area-Compilers

#55675 Avoid conflicting values of DkmEvaluationFlags
  src/ExpressionEvaluator/CSharp/Test/ResultProvider/ResultProviderTests.cs
  src/ExpressionEvaluator/Core/Source/ResultProvider/ResultProvider.cs
Labels: Area-Interactive

#52789 ✨ Support a solution-specific analysis scope set through Solution Explorer
  src/EditorFeatures/Test/SolutionCrawler/WorkCoordinatorTests.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_IncrementalAnalyzer.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.cs
  src/Features/Core/Portable/Workspace/BackgroundCompiler.cs
  src/Features/Core/Portable/Workspace/BackgroundParser.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
  src/VisualStudio/Core/Def/Commands.vsct
  src/VisualStudio/Core/Def/ID.RoslynCommands.cs
  src/VisualStudio/Core/Def/Implementation/Diagnostics/VisualStudioDiagnosticAnalyzerService.cs
  src/VisualStudio/Core/Def/Implementation/Options/PackageSettingsPersister.cs
  src/VisualStudio/Core/Def/Implementation/Options/PackageSettingsPersisterProvider.cs
  src/VisualStudio/Core/Def/PackageRegistration.pkgdef
  src/VisualStudio/Core/Def/RoslynPackage.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/ValueTracking/ValueTrackingCommandHandler.cs
  src/VisualStudio/Core/Def/xlf/Commands.vsct.cs.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.de.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.es.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.fr.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.it.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.ja.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.ko.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.pl.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.ru.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.tr.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.zh-Hant.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/Workspaces/Core/Portable/Options/SerializableOptionSet.cs
  src/Workspaces/Core/Portable/SolutionCrawler/BackgroundAnalysisScope.cs
  src/Workspaces/Core/Portable/SolutionCrawler/SolutionCrawlerOnOffOptionsProvider.cs
  src/Workspaces/Core/Portable/SolutionCrawler/SolutionCrawlerOptions.cs
Labels: Area-IDE

#55357 Treat overload with Delegate parameter as not applicable if lambda delegate type cannot be inferred
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/LambdaConversionResult.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleEqualityTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
Labels: Area-Compilers

#55684 Remove unused interface
  src/EditorFeatures/Core.Wpf/Suggestions/ISuggestedActionCallback.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActions/SuggestedAction.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSourceProvider.cs
Labels: Area-IDE

#55642 Use string.Format when an interpolated string part is dynamic
  src/Compilers/CSharp/Portable/Binder/Binder_InterpolatedString.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
Labels: Area-Compilers

#55693 fixed broken link
  docs/features/ExpressionVariables.md
Labels: Area-Compilers, Documentation

#55383 Add two more icons to the inheritance margin.
  eng/Versions.props
  src/EditorFeatures/Core.Wpf/Suggestions/AsyncSuggestedActionsSource.cs
  src/VisualStudio/Core/Def/Implementation/InheritanceMargin/InheritanceMarginHelpers.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/VisualStudioLogHubLoggerFactory.cs
  src/VisualStudio/Core/Test/InheritanceMargin/InheritanceMarginViewModelTests.vb
Labels: Area-IDE

#55344 🐇 Store weak references in s_structuresTable
  src/Compilers/CSharp/Portable/Syntax/InternalSyntax/CSharpSyntaxNode.cs
  src/Compilers/VisualBasic/Portable/Syntax/InternalSyntax/SyntaxNode.vb
Labels: Area-Compilers

#55735 Allow the integration CI pipeline to specify a build pool
  azure-pipelines-integration.yml
Labels: Area-Infrastructure

#55681 Update Arcade and require .NET 6 Preview 7 SDK
  docs/contributing/Building, Debugging, and Testing on Windows.md
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/cross/arm/sources.list.trusty
  eng/common/cross/arm/trusty-lttng-2.4.patch
  eng/common/cross/arm/trusty.patch
  eng/common/cross/arm64/sources.list.trusty
  eng/common/cross/build-rootfs.sh
  eng/common/cross/x86/sources.list.trusty
  eng/common/templates/job/publish-build-assets.yml
  eng/common/templates/phases/base.yml
  eng/common/templates/phases/publish-build-assets.yml
  eng/common/templates/steps/source-build.yml
  eng/test-build-correctness.ps1
  global.json
  src/CodeStyle/VisualBasic/CodeFixes/Microsoft.CodeAnalysis.VisualBasic.CodeStyle.Fixes.vbproj
  src/CodeStyle/VisualBasic/Tests/Microsoft.CodeAnalysis.VisualBasic.CodeStyle.UnitTests.vbproj
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/Test/Utilities/VisualBasic/Microsoft.CodeAnalysis.VisualBasic.Test.Utilities.vbproj
  src/Compilers/VisualBasic/Test/Emit/Microsoft.CodeAnalysis.VisualBasic.Emit.UnitTests.vbproj
  src/Compilers/VisualBasic/Test/Semantic/Microsoft.CodeAnalysis.VisualBasic.Semantic.UnitTests.vbproj
  src/Compilers/VisualBasic/Test/Symbol/Microsoft.CodeAnalysis.VisualBasic.Symbol.UnitTests.vbproj
  src/EditorFeatures/VisualBasic/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.vbproj
  src/Features/Lsif/GeneratorTest/Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.UnitTests.vbproj
  src/VisualStudio/IntegrationTest/IntegrationTests/AbstractEditorTest.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpErrorListNetCore.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpSquigglesCommon.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpSquigglesDesktop.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpSquigglesNetCore.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpWinForms.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicErrorListNetCore.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicSquigglesNetCore.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/Workspace/WorkspacesNetCore.cs
  src/VisualStudio/IntegrationTest/TestUtilities/WellKnownProjectTemplates.cs
  src/Workspaces/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.Workspaces.vbproj
Labels: Area-Infrastructure

#55709 🐛 Implement PackageSettingsPersister.TryFetch
  src/VisualStudio/Core/Def/Implementation/Options/PackageSettingsPersister.cs
Labels: Area-IDE

#55713 Don't add accessibility modifiers to partial classes in new documents
  src/Analyzers/CSharp/Tests/AddAccessibilityModifiers/AddAccessibilityModifiersTests.cs
  src/EditorFeatures/CSharpTest/Formatting/CSharpNewDocumentFormattingServiceTests.cs
  src/Features/CSharp/Portable/Formatting/CSharpAccessibilityModifiersNewDocumentFormattingProvider.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpWinForms.cs
Labels: Area-IDE

#55718 EnC - Parameterless struct constructors
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/ActiveStatementTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/TopLevelEditingTests.cs
Labels: Area-Compilers, Interactive-EnC

#55696 Have inheritance-margin hold onto data that does *not* point back at Solution instances.
  src/EditorFeatures/Core/GoToDefinition/GoToDefinitionHelpers.cs
  src/EditorFeatures/Core/Host/IStreamingFindReferencesPresenter.cs
  src/EditorFeatures/Core/InheritanceMargin/InheritanceTargetItem.cs
  src/EditorFeatures/Test/InheritanceMargin/InheritanceMarginTests.cs
  src/Features/Core/Portable/DocumentIdSpan.cs
  src/Features/Core/Portable/DocumentSpanExtensions.cs
  src/Features/Core/Portable/FindUsages/DefinitionItem.DefaultDefinitionItem.cs
  src/Features/Core/Portable/FindUsages/DefinitionItem.DetachedDefinitionItem.cs
  src/Features/Core/Portable/FindUsages/IRemoteFindUsagesService.cs
  src/VisualStudio/Core/Def/Implementation/InheritanceMargin/InheritanceGlyphFactory.cs
  src/VisualStudio/Core/Def/Implementation/InheritanceMargin/InheritanceGlyphFactoryProvider.cs
  src/VisualStudio/Core/Def/Implementation/InheritanceMargin/MarginGlyph/InheritanceMargin.xaml.cs
  src/VisualStudio/Core/Def/Implementation/InheritanceMargin/MarginGlyph/TargetMenuItemViewModel.cs
Labels: Area-IDE

#55710 Change the head of inheritance margin background to InActiveTextBox
  src/VisualStudio/Core/Def/Implementation/InheritanceMargin/MarginGlyph/InheritanceMargin.xaml
Labels: Area-IDE

#55207 Update to latest async lightbulb api
  src/EditorFeatures/Core.Wpf/Suggestions/AsyncSuggestedActionsSource.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSourceProvider.cs
Labels: Area-IDE

#55694 Specify paths and shell on Windows
  .vscode/tasks.json
Labels: Area-Infrastructure

#55739 EnC - Allow changing names of previously synthesized record member parameters
  src/EditorFeatures/CSharpTest/EditAndContinue/TopLevelEditingTests.cs
  src/Features/CSharp/Portable/EditAndContinue/CSharpEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
Labels: Area-IDE

#55760 Avoid enumerator allocations for DiagnosticDescriptor.CustomTags
  src/Analyzers/CSharp/Tests/RemoveUnnecessaryParentheses/RemoveUnnecessaryExpressionParenthesesTests.cs
  src/Analyzers/CSharp/Tests/RemoveUnnecessaryParentheses/RemoveUnnecessaryPatternParenthesesTests.cs
  src/Analyzers/Core/CodeFixes/UseCoalesceExpression/UseCoalesceExpressionCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseCoalesceExpression/UseCoalesceExpressionForNullableCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseCollectionInitializer/AbstractUseCollectionInitializerCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseNullPropagation/AbstractUseNullPropagationCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseObjectInitializer/AbstractUseObjectInitializerCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseThrowExpression/UseThrowExpressionCodeFixProvider.cs
  src/Analyzers/VisualBasic/Tests/RemoveUnnecessaryParentheses/RemoveUnnecessaryParenthesesTests.vb
  src/Compilers/Core/Portable/CommandLine/SarifDiagnosticComparer.cs
  src/Compilers/Core/Portable/CommandLine/SarifErrorLogger.cs
  src/Compilers/Core/Portable/CommandLine/SarifV1ErrorLogger.cs
  src/Compilers/Core/Portable/CommandLine/SarifV2ErrorLogger.cs
  src/Compilers/Core/Portable/Diagnostic/CustomObsoleteDiagnosticInfo.cs
  src/Compilers/Core/Portable/Diagnostic/Diagnostic.cs
  src/Compilers/Core/Portable/Diagnostic/DiagnosticDescriptor.cs
  src/Compilers/Core/Portable/Diagnostic/DiagnosticWithInfo.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerOptionsExtensions.cs
  src/Compilers/Test/Core/Diagnostics/DiagnosticDescription.cs
  src/EditorFeatures/Core/Shared/Extensions/TelemetryExtensions.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/AbstractCodeActionOrUserDiagnosticTest.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/CodeFixVerifierHelper.cs
  src/EditorFeatures/DiagnosticsTestUtilities/Diagnostics/AbstractDiagnosticProviderBasedUserDiagnosticTest.cs
  src/Features/Core/Portable/CodeFixes/Suppression/SuppressionHelpers.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_BuildSynchronization.cs
  src/Tools/BuildActionTelemetryTable/BuildActionTelemetryTable.csproj
  src/VisualStudio/Core/Impl/SolutionExplorer/AnalyzersCommandHandler.cs
  src/VisualStudio/Core/Test.Next/Services/LspDiagnosticsTests.cs
  src/Workspaces/Core/Portable/Diagnostics/DiagnosticAnalyzerInfoCache.cs
  src/Workspaces/Core/Portable/Diagnostics/DiagnosticData.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/DiagnosticDescriptorExtensions.cs
Labels: Area-Analyzers

#55699 Pass updated types to the debugger
  eng/Versions.props
  src/EditorFeatures/Core/Implementation/EditAndContinue/ManagedHotReloadLanguageService.cs
Labels: Area-Interactive

#55706 Skip flaky test
  src/Scripting/CSharpTest/InteractiveSessionTests.cs
Labels: Area-Interactive

#55479 Add test for FixAll in ChangeNamespaceToMatchFolder
  src/Analyzers/CSharp/Tests/MatchFolderAndNamespace/CSharpMatchFolderAndNamespaceTests.cs
Labels: Area-IDE

#55747 Prefer symbol references in InlineRename
  src/EditorFeatures/Test2/Rename/InlineRenameTests.vb
  src/Workspaces/Core/Portable/Rename/RenameLocations.cs
Labels: Area-IDE

#55446 Bug fix extract local function errors C#7 and below
  src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractLocalFunctionTests.cs
  src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractMethodTests.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.VariableInfo.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.VariableSymbol.cs
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.vb
Labels: Area-IDE

#55724 Region analysis of nameof
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractRegionDataFlowPass.cs
  src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs
Labels: Area-Compilers

#55692 [LSP] Add semantic tokens caching case
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/SemanticTokensEditsTests.cs
Labels: Area-IDE

#55801 Split 'generate default constructor' in a codefix and coderefactoring
  src/Analyzers/Core/CodeFixes/PredefinedCodeFixProviderNames.cs
  src/EditorFeatures/CSharpTest/GenerateDefaultConstructors/GenerateDefaultConstructorsTests.cs
  src/EditorFeatures/VisualBasicTest/GenerateDefaultConstructors/GenerateDefaultConstructorsTests.vb
  src/Features/CSharp/Portable/GenerateDefaultConstructors/CSharpGenerateDefaultConstructorsCodeFixProvider.cs
  src/Features/CSharp/Portable/GenerateDefaultConstructors/CSharpGenerateDefaultConstructorsService.cs
  src/Features/Core/Portable/GenerateDefaultConstructors/AbstractGenerateDefaultConstructorCodeFixProvider.cs
  src/Features/Core/Portable/GenerateDefaultConstructors/AbstractGenerateDefaultConstructorsService.AbstractCodeAction.cs
  src/Features/Core/Portable/GenerateDefaultConstructors/AbstractGenerateDefaultConstructorsService.CodeAction.cs
  src/Features/Core/Portable/GenerateDefaultConstructors/AbstractGenerateDefaultConstructorsService.CodeActionAll.cs
  src/Features/Core/Portable/GenerateDefaultConstructors/AbstractGenerateDefaultConstructorsService.State.cs
  src/Features/Core/Portable/GenerateDefaultConstructors/AbstractGenerateDefaultConstructorsService.cs
  src/Features/Core/Portable/GenerateDefaultConstructors/GenerateDefaultConstructorsCodeRefactoringProvider.cs
  src/Features/Core/Portable/GenerateDefaultConstructors/IGenerateDefaultConstructorsService.cs
  src/Features/VisualBasic/Portable/GenerateDefaultConstructors/VisualBasicGenerateDefaultConstructorsCodeFixProvider.vb
  src/Features/VisualBasic/Portable/GenerateDefaultConstructors/VisualBasicGenerateDefaultConstructorsService.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE

#55773 Drop active statements when exiting break mode
  src/EditorFeatures/Core/Implementation/EditAndContinue/ManagedEditAndContinueLanguageService.cs
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/EditorFeatures/Test/EditAndContinue/RemoteEditAndContinueServiceTests.cs
  src/EditorFeatures/TestUtilities/EditAndContinue/MockEditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSession.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/IEditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/Remote/IRemoteEditAndContinueService.cs
  src/Features/Core/Portable/EditAndContinue/Remote/RemoteDebuggingSessionProxy.cs
  src/Workspaces/Remote/ServiceHub/Services/EditAndContinue/RemoteEditAndContinueService.cs
Labels: Area-Interactive, Interactive-EnC

#55671 Switch to installing/uninstalling nuget packages in the BG instead of the UI thread
  src/EditorFeatures/CSharpTest/AddUsing/AddUsingNuGetTests.cs
  src/EditorFeatures/Core/Implementation/UIThreadOperationContextProgressTracker.cs
  src/EditorFeatures/VisualBasicTest/Diagnostics/AddImport/AddImportTests_NuGet.vb
  src/Features/Core/Portable/AddPackage/InstallPackageDirectlyCodeActionOperation.cs
  src/VisualStudio/Core/Def/Packaging/PackageInstallerServiceFactory.cs
  src/VisualStudio/Core/Def/Packaging/PackageInstallerServiceFactory_UndoRedo.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/Workspaces/Core/Portable/Packaging/IPackageInstallerService.cs
Labels: Area-IDE

#55098 Use directory-scoped ALCs to load analyzers in .NET Core
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/Core/CodeAnalysisTest/Analyzers/AnalyzerFileReferenceTests.cs
  src/Compilers/Core/CodeAnalysisTest/AssemblyUtilitiesTests.cs
  src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs
  src/Compilers/Core/CodeAnalysisTest/ShadowCopyAnalyzerAssemblyLoaderTests.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/ShadowCopyAnalyzerAssemblyLoader.cs
  src/Compilers/Server/VBCSCompilerTests/AnalyzerConsistencyCheckerTests.cs
  src/Compilers/Test/Core/AssemblyLoadTestFixture.cs
  src/Compilers/Test/Resources/Core/Analyzers/FaultyAnalyzer.cs
  src/Compilers/Test/Resources/Core/Analyzers/FaultyAnalyzer.dll
  src/Compilers/Test/Resources/Core/AssemblyLoadTests/Alpha.cs
  src/Compilers/Test/Resources/Core/AssemblyLoadTests/Alpha.dll
  src/Compilers/Test/Resources/Core/AssemblyLoadTests/Beta.cs
  src/Compilers/Test/Resources/Core/AssemblyLoadTests/Beta.dll
  src/Compilers/Test/Resources/Core/AssemblyLoadTests/Delta.cs
  src/Compilers/Test/Resources/Core/AssemblyLoadTests/Delta.dll
  src/Compilers/Test/Resources/Core/AssemblyLoadTests/Gamma.cs
  src/Compilers/Test/Resources/Core/AssemblyLoadTests/Gamma.dll
  src/Compilers/Test/Resources/Core/Microsoft.CodeAnalysis.Compiler.Test.Resources.csproj
  src/Compilers/Test/Resources/Core/TestResources.cs
  src/VisualStudio/CSharp/Test/ProjectSystemShim/CPS/CSharpReferencesTests.cs
  src/VisualStudio/Core/Test.Next/Remote/SnapshotSerializationTests.cs
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioAnalyzerTests.vb
  src/Workspaces/Remote/ServiceHub/Host/RemoteAnalyzerAssemblyLoaderService.cs
Labels: Area-Compilers

#55679 Run dotnet-format on Roslyn
  src/Compilers/CSharp/Portable/Symbols/Attributes/WellKnownAttributeData/TypeWellKnownEarlyAttributeData.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/InterpolatedStringBuilderLocalSymbol.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.RequestTelemetryLogger.cs
Labels: Area-Compilers

#55826 Fix generate type with file-scoped namespaces
  src/EditorFeatures/CSharpTest/Diagnostics/GenerateType/GenerateTypeTests_Dialog.cs
  src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs
  src/Features/CSharp/Portable/GenerateType/CSharpGenerateTypeService.cs
  src/Features/Core/Portable/GenerateType/AbstractGenerateTypeService.Editor.cs
Labels: Area-IDE

#54891 Create a test help for writing simpler metadata tests
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTest.GenerationInfo.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTest.GenerationVerifier.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTest.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTestBase.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/SemanticEditDescription.cs
Labels: Area-Interactive

#55399 🐇 Ensure recoverable syntax trees are pushed to temporary storage
  src/Workspaces/Core/Portable/Workspace/Solution/DocumentState.cs
Labels: Area-IDE

#55775 Change preview pane to hide unusable options
  src/VisualStudio/Core/Def/Implementation/Preview/PreviewEngine.cs
Labels: Area-IDE

#55828 Report an error for a misplaced `::` token.
  docs/compilers/CSharp/Compiler Breaking Changes - post DotNet 5.md
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs
Labels: Area-Compilers

#55835 Update status for generic attributes
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation

#55824 Dealing with more than one parameterless constructor
  src/Compilers/CSharp/Portable/Symbols/MemberSymbolExtensions.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenConstructorInitTests.cs
Labels: Area-Compilers

#55827 Directly reference theme keys
  src/EditorFeatures/Core.Wpf/CodeAnalysisColors.cs
  src/EditorFeatures/Core.Wpf/Microsoft.CodeAnalysis.EditorFeatures.Wpf.csproj
  src/VisualStudio/Core/Def/RoslynPackage.cs
Labels: Area-IDE

#55804 EnC - Test mixed declaration in deconstruction
  src/EditorFeatures/CSharpTest/EditAndContinue/StatementEditingTests.cs
Labels: Area-IDE, Interactive-EnC

#55849 Remove capabilities fallback
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/Core/Portable/EditAndContinue/ManagedEditAndContinueDebuggerServiceExtensions_REMOVE.cs
Labels: Area-Interactive

#55736 Add a preview option for ServiceHub Core host
  src/VisualStudio/Core/Def/PackageRegistration.pkgdef
Labels: Area-IDE

#55851 Simplify some code around top-level statements in SourceMemberContainerTypeSymbol
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
Labels: Area-Compilers

#55841 Remove CallerArgumentExpression feature flag
  src/Compilers/VisualBasic/Portable/Binding/Binder_Invocation.vb
  src/Compilers/VisualBasic/Portable/Parser/ParserFeature.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceComplexParameterSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceParameterSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceSimpleParameterSymbol.vb
  src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_CallerArgumentExpression.vb
Labels: Area-Compilers, Feature - CallerArgumentExpressionAttribute

#55562 Consider MatchPriority when comparing CompletionItems when filter text is lowercase only
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Features/CSharp/Portable/Completion/CompletionProviders/OperatorsAndIndexer/UnnamedSymbolCompletionProvider_Conversions.cs
  src/Features/Core/Portable/Completion/CommonCompletionService.cs
  src/Features/Core/Portable/Completion/CompletionHelper.cs
  src/Features/Core/Portable/Completion/CompletionService.cs
Labels: Area-IDE

#55744 Update Build_Linux job to run on CoreEng build pool
  azure-pipelines.yml
Labels: Area-Infrastructure

#55427 Fixes #50462
  src/Analyzers/CSharp/Analyzers/CSharpAnalyzersResources.resx
  src/Analyzers/CSharp/Analyzers/UsePatternCombinators/CSharpUsePatternCombinatorsDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.cs.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.de.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.es.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.fr.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.it.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.ja.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.ko.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.pl.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.pt-BR.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.ru.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.tr.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.zh-Hans.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.zh-Hant.xlf
  src/EditorFeatures/CSharpTest/UsePatternCombinators/CSharpUsePatternCombinatorsDiagnosticAnalyzerTests.cs
  src/Features/CSharp/Portable/UsePatternCombinators/CSharpUsePatternCombinatorsCodeFixProvider.cs
Labels: Area-IDE, Community

#55850 Ignore stale active statements.
  src/EditorFeatures/Test/EditAndContinue/ActiveStatementsMapTests.cs
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/EditorFeatures/Test/EditAndContinue/EditSessionActiveStatementsTests.cs
  src/Features/Core/Portable/EditAndContinue/ActiveStatement.cs
  src/Features/Core/Portable/EditAndContinue/ActiveStatementsMap.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
Labels: Area-Interactive

#55865 Restore intent of some top-level statement tests
  src/Compilers/CSharp/Test/Semantic/Semantics/TopLevelStatementsTests.cs
Labels: Area-Compilers, Test

#55814 Relax the induced GC strategy in ServerDispatcher
  src/Compilers/Server/VBCSCompiler/ServerDispatcher.cs
Labels: Area-Compilers

#55910 Freeze semantics for all branches when asked
  src/Workspaces/Core/Portable/Workspace/Solution/BranchId.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Document.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTestHelpers.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
Labels: Area-IDE

#55979 Fix navigation in findrefs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/DocumentSpanEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/Entry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/MetadataDefinitionItemEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/SimpleMessageEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/FindReferencesTableControlEventProcessorProvider.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/ISupportsNavigation.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/RoslynDefinitionBucket.cs
Labels: Area-IDE

#55995 Remove redundant code.
  src/Features/VisualBasic/Portable/Structure/Providers/ConstructorDeclarationStructureProvider.vb
Labels: Area-IDE

#55656 Prevent exception if their is no else block.
  src/EditorFeatures/VisualBasicTest/InvertIf/InvertMultiLineIfTests.vb
  src/Features/VisualBasic/Portable/InvertIf/VisualBasicInvertIfCodeRefactoringProvider.MultiLine.vb
Labels: Area-IDE, Community

#55980 Handle XamlDefinition with line and column
  src/VisualStudio/Xaml/Impl/Features/Definitions/XamlSourceDefinition.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageClient/XamlCapabilities.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Definitions/GoToDefinitionHandler.cs
Labels: Area-IDE

#55982 Specify forbidden zone for foreach deconstruction variables.
  src/Compilers/CSharp/Portable/Symbols/Source/SourceLocalSymbol.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DeconstructionTests.cs
Labels: Area-Compilers

#55745 Use document with partial semantic for completion
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ExtensionMethodImportCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/OverrideCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/OverrideCompletionProviderTests_ExpressionBody.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/TypeImportCompletionProviderTests.cs
  src/EditorFeatures/TestUtilities/Completion/AbstractCompletionProviderTests.cs
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/ExtensionMethodImportCompletionProviderTests.vb
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/TypeImportCompletionProviderTests.vb
  src/Features/CSharp/Portable/Completion/CompletionProviders/ImportCompletion/ExtensionMethodImportCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/ImportCompletion/ImportCompletionProviderHelper.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/ImportCompletion/TypeImportCompletionProvider.cs
  src/Features/CSharp/Portable/Debugging/DataTipInfoGetter.cs
  src/Features/Core/Portable/Completion/CompletionServiceOptions.cs
  src/Features/Core/Portable/Completion/CompletionServiceWithProviders.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractImportCompletionProvider.cs
  src/Features/VisualBasic/Portable/Completion/CompletionProviders/ImportCompletionProvider/ExtensionMethodImportCompletionProvider.vb
  src/Features/VisualBasic/Portable/Completion/CompletionProviders/ImportCompletionProvider/ImportCompletionProviderHelper.vb
  src/Features/VisualBasic/Portable/Completion/CompletionProviders/ImportCompletionProvider/TypeImportCompletionProvider.vb
  src/Workspaces/Core/Portable/Shared/Extensions/DocumentExtensions.cs
Labels: Area-IDE

#55929 Move more code to async gotodef helpers
  src/EditorFeatures/CSharpTest/QuickInfo/SyntacticQuickInfoSourceTests.cs
  src/EditorFeatures/Core.Wpf/InlineHints/InlineHintsTag.cs
  src/EditorFeatures/Core.Wpf/InlineHints/InlineHintsTaggerProvider.cs
  src/EditorFeatures/Core/GoToDefinition/GoToDefinitionHelpers.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CompletionSource.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CompletionSourceProvider.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/Helpers.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilderContext.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/QuickInfoSourceProvider.QuickInfoSource.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/QuickInfoSourceProvider.cs
  src/EditorFeatures/Core/InlineHints/InlineHintsDataTaggerProvider.cs
  src/EditorFeatures/Test2/IntelliSense/AbstractIntellisenseQuickInfoBuilderTests.vb
  src/Features/LanguageServer/Protocol/Handler/Hover/HoverHandler.cs
  src/VisualStudio/CSharp/Impl/ObjectBrowser/ObjectBrowserLibraryManager.cs
  src/VisualStudio/Core/Def/Implementation/Library/AbstractObjectList.cs
  src/VisualStudio/Core/Def/Implementation/Library/ObjectBrowser/AbstractObjectBrowserLibraryManager.cs
  src/VisualStudio/Core/Def/Implementation/Library/ObjectBrowser/ObjectList.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs
  src/VisualStudio/Core/Def/PublicAPI.Unshipped.txt
  src/VisualStudio/Core/Impl/RoslynVisualStudioWorkspace.cs
  src/VisualStudio/Core/Test/GoToDefinition/GoToDefinitionApiTests.vb
  src/VisualStudio/TestUtilities2/CodeModel/Mocks/MockVisualStudioWorkspace.vb
  src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb
  src/Workspaces/Core/Portable/Shared/TestHooks/FeatureAttribute.cs
Labels: Area-IDE

#55729 Warm up ImportCompletion cache in background when opening a document
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Features/CSharp/Portable/Completion/CompletionProviders/ImportCompletion/TypeImportCompletionServiceFactory.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionService.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.ExtensionMethodSymbolComputer.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/IRemoteExtensionMethodImportCompletionService.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ITypeImportCompletionService.cs
  src/Features/VisualBasic/Portable/Completion/CompletionProviders/ImportCompletionProvider/TypeImportCompletionServiceFactory.vb
  src/VisualStudio/CSharp/Impl/LanguageService/CSharpCreateServicesOnTextViewConnection.cs
  src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractCreateServicesOnTextViewConnection.cs
  src/Workspaces/Remote/ServiceHub/Services/ExtensionMethodImportCompletion/RemoteExtensionMethodImportCompletionService.cs
Labels: Area-IDE

#55224 EnC - Tests for lambda improvements
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/CSharpSymbolMatcher.cs
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/EmitHelpers.cs
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/PEDeltaAssemblyBuilder.cs
  src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeManager.Templates.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNames.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/RefKindVector.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/SymbolMatcherTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
  src/Compilers/Core/Portable/Collections/BitVector.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/DeltaMetadataWriter.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/EmitBaseline.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/IPEDeltaAssemblyBuilder.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/SymbolMatcher.cs
  src/Compilers/Core/Portable/Emit/SynthesizedDelegateKey.cs
  src/Compilers/Core/Portable/Emit/SynthesizedDelegateValue.cs
  src/Compilers/Test/Core/Compilation/CompilationDifference.cs
  src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/PEDeltaAssemblyBuilder.vb
  src/EditorFeatures/CSharpTest/EditAndContinue/StatementEditingTests.cs
  src/EditorFeatures/TestUtilities/EditAndContinue/EditAndContinueTestHelpers.cs
Labels: Area-Interactive

#56011 React to string comparison changing on .NET Core
  src/Compilers/Test/Utilities/VisualBasic/CompilationTestUtils.vb
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenVBCore.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_IForLoopStatement.vb
  src/Compilers/VisualBasic/Test/Semantic/Binding/BindingErrorTests.vb
  src/Compilers/VisualBasic/Test/Semantic/Compilation/SemanticModelLookupSymbolsAPITests.vb
  src/Compilers/VisualBasic/Test/Semantic/ExtensionMethods/SemanticModelTests.vb
  src/Compilers/VisualBasic/Test/Semantic/Semantics/GetExtendedSemanticInfoTests.vb
  src/Compilers/VisualBasic/Test/Semantic/Semantics/NameLengthTests.vb
  src/Compilers/VisualBasic/Test/Semantic/Semantics/TooLongNameTests.vb
  src/Compilers/VisualBasic/Test/Semantic/Semantics/UserDefinedForToLoop.vb
  src/Compilers/VisualBasic/Test/Symbol/DocumentationComments/DocCommentTests.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/ComClassTests.vb
Labels: Area-Compilers, Test
