Repository dotnet/roslyn, pull requests merged in 2021-11, with the labels that each got.

#57487 Fix 'simplify conditional expression' with VB value equality
  src/Analyzers/CSharp/CodeFixes/RemoveConfusingSuppression/CSharpRemoveConfusingSuppressionCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/SimplifyBooleanExpression/SimplifyConditionalCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseConditionalExpression/AbstractUseConditionalExpressionCodeFixProvider.cs
  src/Analyzers/VisualBasic/Tests/SimplifyBooleanExpression/SimplifyConditionalTests.vb
  src/EditorFeatures/VisualBasicTest/InvertIf/InvertMultiLineIfTests.vb
  src/Features/Core/Portable/InvertConditional/AbstractInvertConditionalCodeRefactoringProvider.cs
  src/Features/Core/Portable/InvertLogical/AbstractInvertLogicalCodeRefactoringProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpSyntaxGeneratorInternal.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions_Negate.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/SyntaxGeneratorInternalExtensions/SyntaxGeneratorInternal.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/LanguageServices/VisualBasicSyntaxGeneratorInternal.vb
Labels: Area-IDE

#57410 Classify method group assignments as methods
  src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs
  src/EditorFeatures/CSharpTest/Classification/TotalClassifierTests.cs
  src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.cs
  src/Workspaces/Core/Portable/Classification/SyntaxClassification/AbstractNameSyntaxClassifier.cs
  src/Workspaces/VisualBasic/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.vb
Labels: Area-IDE

#57479 Reference VS Debugger.Contracts in DebuggerContractVersionCheck
  global.json
  src/EditorFeatures/Core/Implementation/EditAndContinue/DebuggerContractVersionCheck.cs
Labels: Area-Interactive

#57188 Move search under tabs
  src/VisualStudio/Core/Def/EditorConfigSettings/Analyzers/View/AnalyzerSettingsView.xaml
  src/VisualStudio/Core/Def/EditorConfigSettings/Analyzers/View/AnalyzerSettingsView.xaml.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/Analyzers/View/ColumnDefinitions/AnalyzerLocationColumnDefinition.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/Analyzers/View/ColumnDefinitions/AnalyzerSeverityColumnDefinition.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/Analyzers/View/SeverityControl.xaml
  src/VisualStudio/Core/Def/EditorConfigSettings/Analyzers/View/SeverityControl.xaml.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/Analyzers/ViewModel/SeverityViewModel.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/CodeStyle/View/CodeStyleSettingsView.xaml
  src/VisualStudio/Core/Def/EditorConfigSettings/CodeStyle/View/CodeStyleSettingsView.xaml.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/CodeStyle/View/CodeStyleSeverityControl.xaml
  src/VisualStudio/Core/Def/EditorConfigSettings/CodeStyle/View/CodeStyleSeverityControl.xaml.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/CodeStyle/View/CodeStyleValueControl.xaml
  src/VisualStudio/Core/Def/EditorConfigSettings/CodeStyle/View/CodeStyleValueControl.xaml.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/CodeStyle/View/ColumnDefinitions/CodeStyleLocationColumnDefinition.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/CodeStyle/View/ColumnDefinitions/CodeStyleSeverityColumnDefinition.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/CodeStyle/View/ColumnDefinitions/CodeStyleValueColumnDefinition.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/CodeStyle/ViewModel/CodeStyleSeverityViewModel.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/CodeStyle/ViewModel/CodeStyleValueViewModel.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/Common/EnumPropertyView.xaml
  src/VisualStudio/Core/Def/EditorConfigSettings/Common/EnumPropertyView.xaml.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/Common/EnumSettingViewModel.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/Common/IEnumSettingViewModel.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/Extensions/ServiceProviderExtensions.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/SettingsEditorControl.xaml
  src/VisualStudio/Core/Def/EditorConfigSettings/SettingsEditorControl.xaml.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/SettingsEditorPane.SearchHandler.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/SettingsEditorPane.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/Styles/TabControlStyles.xaml
  src/VisualStudio/Core/Def/EditorConfigSettings/Whitespace/View/ColumnDefnitions/WhitespaceLocationColumnDefinition.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/Whitespace/View/ColumnDefnitions/WhitespaceValueColumnDefinition.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/Whitespace/View/WhitespaceBoolSettingView.xaml
  src/VisualStudio/Core/Def/EditorConfigSettings/Whitespace/View/WhitespaceBoolSettingView.xaml.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/Whitespace/View/WhitespaceSettingsView.xaml
  src/VisualStudio/Core/Def/EditorConfigSettings/Whitespace/View/WhitespaceSettingsView.xaml.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/Whitespace/ViewModel/WhitespaceSettingBoolViewModel.cs
Labels: Area-IDE, Needs UX Triage

#57473 Fix inline diagnostics location issue in VB
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
Labels: Area-IDE, UX Review Not Required

#57480 Run net6.0-windows unit tests in CI
  eng/build.ps1
Labels: Area-Infrastructure

#57414 Do not normalize leading whitespace in code comments
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
  src/Workspaces/Core/Portable/Shared/Utilities/DocumentationComment.cs
  src/Workspaces/CoreTest/UtilityTest/DocumentationCommentTests.cs
Labels: Area-IDE, Community

#57509 Update PublishData.json
  eng/config/PublishData.json
Labels: Area-Infrastructure

#57375 Fix param-nullchecking build/test failures
  src/Compilers/CSharp/Portable/Binder/Binder.QueryUnboundLambdaState.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Lambda.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_NullChecking.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Symbols/Source/LambdaParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ParameterHelpers.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceDelegateMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberMethodSymbol.cs
  src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenNullCheckedParameterTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_NullCheckedParameters.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullCheckedParameterTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/LambdaParameterParsingTests.cs
  src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
Labels: Area-Compilers

#57511 Avoid recomputing expensive persistence location data that does not change.
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/IPersistentStorageConfiguration.cs
Labels: Area-IDE

#56860 Build CodeAction description into table and only generate Dev17 hash
  Roslyn.sln
  src/Tools/BuildActionTelemetryTable/BuildActionTelemetryTable.csproj
  src/Tools/BuildActionTelemetryTable/Program.cs
Labels: Area-Infrastructure

#57458 Update SymReader packages to the latest
  eng/Versions.props
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs
  src/Compilers/Test/Core/ModuleInitializer.cs
  src/Compilers/VisualBasic/Test/Emit/PDB/PDBTests.vb
  src/Test/PdbUtilities/Reader/PdbValidationOptions.cs
Labels: Area-Compilers

#57138 Add Visual Studio 2022 Editor Color Scheme
  src/EditorFeatures/Core/ColorSchemes/SchemeName.cs
  src/EditorFeatures/Core/Options/ColorSchemeOptions.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/ColorSchemes/VisualStudio2022.xml
  src/VisualStudio/Core/Def/Implementation/ColorSchemes/ColorSchemeApplier.Settings.cs
  src/VisualStudio/Core/Def/Implementation/ColorSchemes/ColorSchemeApplier.cs
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageStrings.vb
Labels: Area-IDE, UX Review Not Required

#57514 Cache the stale syntax-indices we load prior to OOP being fully hydrated.
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.CachedSearch.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.InProcess.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Persistence.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/DocumentKey.cs
  src/Workspaces/Remote/ServiceHub/Services/NavigateToSearch/RemoteNavigateToSearchService.cs
Labels: Area-IDE

#57534 Simplify nav-to implementation.
  src/EditorFeatures/CSharpTest/NavigateTo/NavigateToSearcherTests.cs
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/VSTypeScriptNavigateToSearchService.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.cs
  src/Features/Core/Portable/NavigateTo/INavigateToSearchService.cs
  src/Features/Core/Portable/NavigateTo/NavigateToSearcher.cs
  src/Tools/ExternalAccess/FSharp/Internal/NavigateTo/FSharpNavigateToSearchService.cs
  src/Tools/IdeCoreBenchmarks/NavigateToBenchmarks.cs
Labels: Area-IDE

#57537 Simplify PDB reading code
  src/EditorFeatures/CSharpTest/PdbSourceDocument/PdbSourceDocumentTests.cs
  src/Features/Core/Portable/PdbSourceDocument/PdbFileLocatorService.cs
Labels: Area-IDE

#57502 Localized missing warning message #57296
  src/Features/CSharp/Portable/CSharpFeaturesResources.resx
  src/Features/CSharp/Portable/CodeRefactorings/LambdaSimplifier/LambdaSimplifierCodeRefactoringProvider.Rewriter.cs
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.cs.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.de.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.es.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.fr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.it.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ja.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ko.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pl.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pt-BR.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ru.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.tr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hans.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hant.xlf
Labels: Area-IDE, Community

#57557 Revert move to VS2022 for official build.
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#57559 Revert move to VS2022 for official build.
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#57558 Revert move to VS2022 for official build.
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#57520 Track AbstractFlowPass.PendingBranches by label
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.PendingBranchesCollection.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/AlwaysAssignedWalker.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/ControlFlowAnalysis.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/ControlFlowPass.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/ExitPointsWalker.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OverloadResolutionPerfTests.cs
Labels: Area-Compilers

#57191 Fix for "Function pointer invocation has "None" IOperation"
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/FunctionPointerOperations.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IInterpolatedStringOperation.cs
  src/Compilers/Core/Portable/Generated/OperationKind.Generated.cs
  src/Compilers/Core/Portable/Generated/Operations.Generated.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/Operations/OperationExtensions.cs
  src/Compilers/Core/Portable/Operations/OperationInterfaces.xml
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Test/Core/Compilation/ControlFlowGraphVerifier.cs
  src/Compilers/Test/Core/Compilation/OperationTreeVerifier.cs
  src/Compilers/Test/Core/Compilation/TestOperationVisitor.cs
Labels: Area-Compilers, Community

#57535 Adjust the order of evaluation for implicit Index/Range support to follow the recent LDM decision.
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs
Labels: Area-Compilers, New Language Feature - Range

#56957 StackFrame Parser/Lexer as EmbeddedLanguage
  src/EditorFeatures/Test/EmbeddedLanguages/StackFrame/StackFrameParserTests.Utilities.cs
  src/EditorFeatures/Test/EmbeddedLanguages/StackFrame/StackFrameParserTests.cs
  src/EditorFeatures/Test/EmbeddedLanguages/StackFrame/StackFrameSyntaxFactory.cs
  src/Features/Core/Portable/EmbeddedLanguages/StackFrame/IStackFrameNodeVisitor.cs
  src/Features/Core/Portable/EmbeddedLanguages/StackFrame/Result.cs
  src/Features/Core/Portable/EmbeddedLanguages/StackFrame/StackFrameCompilationUnit.cs
  src/Features/Core/Portable/EmbeddedLanguages/StackFrame/StackFrameExtensions.cs
  src/Features/Core/Portable/EmbeddedLanguages/StackFrame/StackFrameKind.cs
  src/Features/Core/Portable/EmbeddedLanguages/StackFrame/StackFrameLexer.cs
  src/Features/Core/Portable/EmbeddedLanguages/StackFrame/StackFrameNodeDefinitions.cs
  src/Features/Core/Portable/EmbeddedLanguages/StackFrame/StackFrameParser.cs
  src/Features/Core/Portable/EmbeddedLanguages/StackFrame/StackFrameTree.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/EmbeddedLanguages/Common/EmbeddedSeparatedSyntaxNodeList.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/EmbeddedLanguages/Common/EmbeddedSyntaxNode.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/EmbeddedLanguages/Common/EmbeddedSyntaxNodeOrToken.cs
Labels: Area-IDE

#57538 Have navto only search generated-documents after doing the search of regular documents.
  src/EditorFeatures/CSharpTest/NavigateTo/NavigateToSearcherTests.cs
  src/EditorFeatures/Core.Wpf/NavigateTo/NavigateToItemProvider.cs
  src/EditorFeatures/Core/Implementation/LanguageServer/Handlers/Symbols/WorkspaceSymbolsHandler.cs
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/VSTypeScriptNavigateToSearchService.cs
  src/Features/Core/Portable/FindUsages/IRemoteFindUsagesService.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.CachedDocumentSearch.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.GeneratedDocumentSearch.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.InProcess.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.NormalSearch.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.cs
  src/Features/Core/Portable/NavigateTo/INavigateToSearchService.cs
  src/Features/Core/Portable/NavigateTo/IRemoteNavigateToSearchService.cs
  src/Features/Core/Portable/NavigateTo/NavigateToSearcher.cs
  src/Features/Core/Portable/ValueTracking/ValueTracker.FindReferencesProgress.cs
  src/Tools/ExternalAccess/FSharp/Internal/NavigateTo/FSharpNavigateToSearchService.cs
  src/Tools/IdeCoreBenchmarks/NavigateToBenchmarks.cs
  src/VisualStudio/Core/Def/Implementation/Progression/GraphQueries/SearchGraphQuery.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/NoOpStreamingFindReferencesProgress.cs
  src/Workspaces/Core/Portable/FindSymbols/IRemoteSymbolFinderService.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder.CallbackDispatcher.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder.FindLiteralsServerCallback.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder.FindReferencesServerCallback.cs
  src/Workspaces/Core/Portable/Shared/Utilities/IStreamingProgressTracker.cs
  src/Workspaces/Core/Portable/Shared/Utilities/IStreamingProgressTrackerExtensions.cs
  src/Workspaces/Core/Portable/Shared/Utilities/StreamingProgressTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectDependencyGraph.cs
  src/Workspaces/Remote/ServiceHub/Services/FindUsages/RemoteFindUsagesService.cs
  src/Workspaces/Remote/ServiceHub/Services/NavigateToSearch/RemoteNavigateToSearchService.cs
  src/Workspaces/Remote/ServiceHub/Services/SymbolFinder/RemoteSymbolFinderService.cs
Labels: Area-IDE

#57579 Use DocumentOptionSet in AutomaticLineEnderCommandHandler
  src/EditorFeatures/CSharp/AutomaticCompletion/AutomaticLineEnderCommandHandler.cs
  src/EditorFeatures/CSharp/AutomaticCompletion/AutomaticLineEnderCommandHandler_Helpers.cs
  src/EditorFeatures/CSharpTest/AutomaticCompletion/AutomaticLineEnderTests.cs
  src/EditorFeatures/TestUtilities/AutomaticCompletion/AbstractAutomaticLineEnderTests.cs
Labels: Area-IDE

#57004 Codefix for CS1591: Add ///<inheritdoc/>
  src/Analyzers/Core/CodeFixes/PredefinedCodeFixProviderNames.cs
  src/Compilers/Test/Core/Traits/Traits.cs
  src/EditorFeatures/CSharpTest/Diagnostics/AddInheritdoc/AddInheritdocTests.cs
  src/Features/CSharp/Portable/CodeFixes/AddInheritdoc/AddInheritdocCodeFixProvider.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
Labels: Area-IDE, Community

#57593 Fix flaky issue in the SourceGeneratorItemTests
  src/VisualStudio/Core/Impl/SolutionExplorer/SourceGeneratedFileItems/SourceGeneratedFileItemSource.cs
Labels: Area-IDE

#57582 Clean up VsCodeWindowManager
  src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractLanguageService`2.VsCodeWindowManager.cs
Labels: Area-IDE

#57541 Validate the checksum of source on disk
  src/EditorFeatures/CSharpTest/PdbSourceDocument/PdbSourceDocumentTests.cs
  src/Features/Core/Portable/PdbSourceDocument/DocumentDebugInfoReader.cs
  src/Features/Core/Portable/PdbSourceDocument/PdbSourceDocumentLoaderService.cs
  src/Features/Core/Portable/PdbSourceDocument/PdbSourceDocumentMetadataAsSourceFileProvider.cs
Labels: Area-IDE

#57445 Benchmark for Inheritance Margin
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/Tools/IdeBenchmarks/IdeBenchmarks.csproj
  src/Tools/IdeBenchmarks/InheritanceMargin/BenchmarksHelpers.cs
  src/Tools/IdeBenchmarks/InheritanceMargin/InheritanceMarginGlyphBenchmarks.cs
  src/Tools/IdeBenchmarks/InheritanceMargin/InheritanceMarginServiceBenchmarks.cs
  src/Tools/IdeBenchmarks/Program.cs
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
Labels: Area-IDE

#57571 Don't crash Use ExpressionBody on local functions in top level statements
  src/Analyzers/CSharp/CodeFixes/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseExpressionBody/UseExpressionBodyForLocalFunctionsAnalyzerTests.cs
Labels: Area-IDE

#57606 Ensure we select a 'VB WithEvents' member in the navbar list when the user enters that member in the editor.
  src/EditorFeatures/Core/Extensibility/NavigationBar/AbstractEditorNavigationBarItemService.cs
  src/EditorFeatures/Core/Extensibility/NavigationBar/NavigationBarItem.cs
  src/EditorFeatures/Core/Extensibility/NavigationBar/NavigationBarProjectItem.cs
  src/EditorFeatures/Core/Extensibility/NavigationBar/SimpleNavigationBarItem.cs
  src/EditorFeatures/Core/Extensibility/NavigationBar/WrappedNavigationBarItem.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptNavigationBarItemService.cs
  src/Tools/ExternalAccess/FSharp/Internal/Editor/FSharpNavigationBarItemService.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicNavigationBar.cs
Labels: Area-IDE

#55123 Minor refactoring in SettingsUpdateHelper
  src/EditorFeatures/Core/EditorConfigSettings/Updater/SettingsUpdateHelper.cs
Labels: Area-IDE, Community

#54601 Fix spacing when generating editorconfig options from UI
  src/EditorFeatures/CSharpTest/EditorConfigSettings/Updater/SettingsUpdaterTests.cs
  src/EditorFeatures/Core/EditorConfigSettings/Updater/SettingsUpdateHelper.cs
Labels: Area-IDE, Community

#57601 Update VS editor package version
  eng/Versions.props
Labels: Area-Infrastructure

#57584 Re-enable BuildWithCommandLine test
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpBuild.cs
Labels: Area-Infrastructure, Test

#57588 [LSP]Re-enable information level logging in loghub now that VS supports de…
  src/VisualStudio/Core/Def/Implementation/LanguageClient/VisualStudioLogHubLoggerFactory.cs
Labels: Area-IDE, LSP

#57481 Switch to 1ES R&D pools on main
  azure-pipelines-integration-corehost.yml
  azure-pipelines-integration-lsp.yml
  azure-pipelines-integration.yml
  azure-pipelines-official.yml
  azure-pipelines-richnav.yml
  azure-pipelines.yml
  eng/pipelines/build-unix-job.yml
  eng/pipelines/build-windows-job.yml
  eng/pipelines/test-unix-job-single-machine.yml
  eng/pipelines/test-windows-job-single-machine.yml
Labels: Area-Infrastructure

#57612 AbstractFlowPass - VisitArrayCreation should use the regular way for visiting `initializer`.
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs
  src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs
Labels: Area-Compilers

#57567 Target executable projects and remote workspaces to net6.0
  src/CodeStyle/CSharp/CodeFixes/Microsoft.CodeAnalysis.CSharp.CodeStyle.Fixes.csproj
  src/CodeStyle/Tools/CodeStyleConfigFileGenerator.csproj
  src/CodeStyle/VisualBasic/CodeFixes/Microsoft.CodeAnalysis.VisualBasic.CodeStyle.Fixes.vbproj
  src/Compilers/CSharp/csc/csc.csproj
  src/Compilers/Core/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.csproj
  src/Compilers/Core/MSBuildTask/RCWForCurrentContext.cs
  src/Compilers/Core/MSBuildTask/Utilities.cs
  src/Compilers/Core/Rebuild/CompilationOptionsReader.cs
  src/Compilers/Core/Rebuild/Microsoft.CodeAnalysis.Rebuild.csproj
  src/Compilers/Server/VBCSCompiler/VBCSCompiler.csproj
  src/Compilers/Shared/BuildServerConnection.cs
  src/Compilers/Shared/NamedPipeUtil.cs
  src/Compilers/VisualBasic/vbc/vbc.csproj
  src/Interactive/csi/csi.csproj
  src/Interactive/vbi/vbi.vbproj
  src/NuGet/Microsoft.NETCore.Compilers/Microsoft.NETCore.Compilers.Package.csproj
  src/NuGet/Microsoft.Net.Compilers.Toolset/CoreClrCompilerArtifacts.targets
  src/NuGet/Microsoft.Net.Compilers.Toolset/Microsoft.Net.Compilers.Toolset.Package.csproj
  src/NuGet/Microsoft.Net.Compilers.Toolset/build/Microsoft.Net.Compilers.Toolset.props
  src/Tools/AnalyzerRunner/AnalyzerRunner.csproj
  src/Tools/BuildActionTelemetryTable/BuildActionTelemetryTable.csproj
  src/Tools/BuildBoss/CompilerNuGetCheckerUtil.cs
  src/Workspaces/Remote/Core/Microsoft.CodeAnalysis.Remote.Workspaces.csproj
  src/Workspaces/Remote/ServiceHub.CoreComponents/Microsoft.CodeAnalysis.Remote.ServiceHub.CoreComponents.csproj
  src/Workspaces/Remote/ServiceHub/Host/ThrowingTraceListener.cs
  src/Workspaces/Remote/ServiceHub/Microsoft.CodeAnalysis.Remote.ServiceHub.csproj
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.FactoryBase.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs
Labels: Area-Infrastructure

#57628 Tiny simplification to the compilation tracker.
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.GeneratedFileReplacingCompilationTracker.cs
Labels: Area-IDE

#57483 Interpolated string handlers in the CFG
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IInterpolatedStringOperation.cs
  src/Compilers/Core/Portable/Generated/FlowAnalysis.Generated.cs
  src/Compilers/Core/Portable/Generated/Operations.Generated.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.InterpolatedStringContext.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/Operations/OperationInterfaces.xml
  src/Compilers/Core/Portable/Operations/OperationNodes.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Test/Core/Compilation/ControlFlowGraphVerifier.cs
  src/Compilers/Test/Core/Compilation/OperationTreeVerifier.cs
Labels: Area-Compilers

#57573 Bump dependencies and version for GA
  eng/Versions.props
Labels: Area-Infrastructure

#57406 Telemetry improvements
  src/EditorFeatures/Core.Wpf/InlineRename/CommandHandlers/RenameCommandHandler.cs
  src/EditorFeatures/Core.Wpf/InlineRename/Dashboard/Dashboard.xaml.cs
  src/EditorFeatures/Core/Implementation/EditorLayerExtensionManager.cs
  src/EditorFeatures/Core/Implementation/Workspaces/EditorErrorReportingService.cs
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/Features/Core/Portable/CodeFixes/CodeFixService.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSessionTelemetry.cs
  src/Features/Core/Portable/EditAndContinue/EditSessionTelemetry.cs
  src/Features/LanguageServer/Protocol/ExternalAccess/VSCode/API/VSCodeTelemetryLogger.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.RequestTelemetryLogger.cs
  src/VisualStudio/Core/Def/ExternalAccess/LegacyCodeAnalysis/LegacyCodeAnalysisVisualStudioSuppressionFixServiceAccessor.cs
  src/VisualStudio/Core/Def/Implementation/VirtualMemoryNotificationListener.cs
  src/VisualStudio/Core/Def/Implementation/Watson/WatsonReporter.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioErrorReportingService.cs
  src/VisualStudio/Core/Def/Telemetry/IVsSQM.cs
  src/VisualStudio/Core/Def/Telemetry/VSTelemetryLogger.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllLogger.cs
  src/Workspaces/Core/Portable/ExtensionManager/IErrorReportingService.cs
  src/Workspaces/Core/Portable/Log/KeyValueLogMessage.cs
  src/Workspaces/Core/Portable/Log/PiiValue.cs
  src/Workspaces/Core/Portable/Telemetry/TelemetryFeatureName.cs
  src/Workspaces/CoreTest/Remote/ServiceDescriptorTests.cs
  src/Workspaces/CoreTestUtilities/TestErrorReportingService.cs
  src/Workspaces/Remote/Core/BrokeredServiceConnection.cs
  src/Workspaces/Remote/Core/ServiceDescriptor.cs
  src/Workspaces/Remote/Core/ServiceDescriptors.cs
  src/Workspaces/Remote/Core/SolutionAssetProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-Interactive, UX Review Not Required

#57632 Move hte dependent checksum computation directly into the CompilationTracker component
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Project.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.GeneratedFileReplacingCompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.ICompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
Labels: Area-IDE

#57346 adding draft of detailed spec
  docs/ide/specs/semantic_snippets.md
Labels: Area-IDE

#57556 Fix line delta calculation for top-level code
  src/EditorFeatures/CSharpTest/EditAndContinue/LineEditTests.cs
  src/Features/CSharp/Portable/EditAndContinue/BreakpointSpans.cs
  src/Features/CSharp/Portable/EditAndContinue/CSharpEditAndContinueAnalyzer.cs
  src/Features/CSharp/Portable/EditAndContinue/SyntaxUtilities.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
  src/Features/VisualBasic/Portable/EditAndContinue/VisualBasicEditAndContinueAnalyzer.vb
Labels: Area-Interactive

#57633 Overload resolution was ignoring HasTypeArgumentInferredFromFunctionType for calls in expanded form
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MemberResolutionResult.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
Labels: Area-Compilers

#57518 proposed document pull diagnostics implementation
  src/Features/Core/Portable/Diagnostics/DocumentAnalysisExecutor.cs
  src/Features/LanguageServer/Protocol/CSharpVisualBasicLanguageServerFactory.cs
  src/Features/LanguageServer/Protocol/ExternalAccess/VSCode/API/VSCodeAnalyzerLoader.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DocumentPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Experimental/ExperimentalDiagnosticsTypes.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Experimental/ExperimentalDocumentPullDiagnosticHandlerProvider.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Experimental/ExperimentalDocumentPullDiagnosticsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Experimental/ExperimentalWorkspacePullDiagnosticHandlerProvider.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Experimental/ExperimentalWorkspacePullDiagnosticsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/LanguageServerTarget.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/IsExternalInit.cs
Labels: Area-IDE

#57656 Fix issues in compilation tracker reported in prior PR
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.GeneratedFileReplacingCompilationTracker.cs
Labels: Area-IDE

#57669 Add editor features + rename tracking code action to telemetry table
  src/Tools/BuildActionTelemetryTable/BuildActionTelemetryTable.csproj
  src/Tools/BuildActionTelemetryTable/Program.cs
Labels: Area-Infrastructure

#57631 Don't throw when delay is expedited in tests
  src/Workspaces/Core/Portable/Shared/TestHooks/AsynchronousOperationListener.cs
  src/Workspaces/Core/Portable/Shared/TestHooks/TaskExtensions.cs
Labels: Area-IDE

#57676 Don't suggest simplification for positional patterns
  src/Analyzers/CSharp/Analyzers/SimplifyPropertyPattern/SimplifyPropertyPatternHelpers.cs
  src/EditorFeatures/CSharpTest/SimplifyPropertyPattern/SimplifyPropertyPatternTests.cs
Labels: Area-IDE, Community

#57668 Only offer nullable reference types for C# 8 and newer
  src/EditorFeatures/CSharpTest/CodeActions/EnableNullable/EnableNullableTests.cs
  src/Features/CSharp/Portable/CodeRefactorings/EnableNullable/EnableNullableCodeRefactoringProvider.cs
Labels: Area-IDE

#57655 Cleanup how we create skeleton assemblies.
  src/Workspaces/Core/Portable/Workspace/Solution/CachedSkeletonReferences.cs
  src/Workspaces/Core/Portable/Workspace/Solution/MetadataOnlyImage.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.GeneratedFileReplacingCompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.ICompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.SkeletonReferenceCache.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
Labels: Area-IDE

#57680 Mitigate the GeneratorDriver missync issue while capturing dumps
  src/Compilers/Core/Portable/InternalUtilities/FatalError.cs
  src/VisualStudio/Core/Def/Implementation/TaskList/ProjectExternalErrorReporter.cs
  src/VisualStudio/Core/Def/Implementation/Watson/WatsonReporter.cs
  src/VisualStudio/Core/Def/Interactive/VsInteractiveWindowPackage.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationAndGeneratorDriverTranslationAction_Actions.cs
  src/Workspaces/Remote/ServiceHub/Services/ServiceHubDocumentTrackingService.cs
Labels: Area-IDE, Approved to merge

#57648 Fix race condition in computing _hostAnalyzerStateMap
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.StateManager.HostStates.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.StateManager.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.cs
Labels: Area-IDE, Approved to merge

#57711 Modify timeout to avoid flaky integration tests
  src/VisualStudio/IntegrationTest/TestUtilities/Helper.cs
Labels: Area-Infrastructure

#57714 Don't capture dumps for out-of-sync generator drivers
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationAndGeneratorDriverTranslationAction_Actions.cs
Labels: Area-IDE, Approved to merge

#57043 Error when ref is used on a parameter or return type of an UnmanagedCallersOnly method
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 6.md
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs
Labels: Area-Compilers

#57626 Port BasicAddMissingReference.InvokeSomeFixesInVisualBasicThenVerifyReferences to the new test framework
  Roslyn.sln
  azure-pipelines-integration-corehost.yml
  azure-pipelines-integration-lsp.yml
  azure-pipelines-integration.yml
  eng/Versions.props
  eng/build.ps1
  src/EditorFeatures/Core.Wpf/Microsoft.CodeAnalysis.EditorFeatures.Wpf.csproj
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/VisualStudio/IntegrationTest/IntegrationTests/AbstractEditorTest.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/AbstractEditorTest.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/AbstractIntegrationTest.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorVerifierInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/ErrorListInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/Helper.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/InProcComponent.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/LightBulbHelper.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionVerifierInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/TestServices.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/WorkspaceInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/Microsoft.VisualStudio.LanguageServices.New.IntegrationTests.csproj
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicAddMissingReference.cs
  src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
Labels: Area-IDE

#57658 Remove CWT from skeleton caching and simplify impl
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.SkeletonReferenceCache.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
Labels: Area-IDE

#57723 Fix featureflag name for .net 6 host in UI
  src/VisualStudio/Core/Def/PackageRegistration.pkgdef
Labels: Area-IDE

#57739 update error code to fix main break
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
Labels: Area-Compilers

#57623 Don't analyze local function bodies as though they are top level code
  src/EditorFeatures/CSharpTest/EditAndContinue/StatementEditingTests.cs
  src/Features/CSharp/Portable/EditAndContinue/CSharpEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
  src/Features/VisualBasic/Portable/EditAndContinue/VisualBasicEditAndContinueAnalyzer.vb
Labels: Area-IDE

#57725 Remove extra EnsureEditableDocuments calls
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
Labels: Area-IDE

#57678 Adjust tests for Windows 11 changes
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/Core/Portable/CommandLine/CommandLineParser.cs
  src/Compilers/Test/Core/Assert/ConditionalFactAttribute.cs
  src/Compilers/VisualBasic/Test/CommandLine/CommandLineTests.vb
Labels: Area-Compilers

#57744 Don't show nullable annotation in completion items of static field/property
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/EnumAndCompletionListTagCompletionProviderTests.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/EnumAndCompletionListTagCompletionProvider.cs
Labels: Area-IDE

#57050 Check constraints on lifted operator types
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/UserDefinedExplicitConversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/UserDefinedImplicitConversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/BinaryOperatorOverloadResolution.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/UnaryOperatorOverloadResolution.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/UserDefinedConversionTests.cs
Labels: Area-Compilers

#57427 Fix C# language name in spec
  docs/features/pdb-compilation-options.md
Labels: Area-Compilers

#57617 Move the task completion source for a queue item into the queue item itself.
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.DocumentChangeTracker.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.QueueItem.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs
  src/Features/LanguageServer/Protocol/LanguageServerTarget.cs
  src/Features/LanguageServer/ProtocolUnitTests/Ordering/RequestOrderingTests.cs
  src/VisualStudio/Core/Test.Next/Services/LspDiagnosticsTests.cs
Labels: Area-IDE, LSP

#57664 Include a type for NoneOperations in VB, print the type in tests
  src/Compilers/CSharp/Test/IOperation/IOperation/FunctionPointerOperations.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IAddressOfOperation.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IArgument.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IDynamicIndexerAccessExpression.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IFieldReferenceExpression.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IFixedStatement.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IForEachLoopStatement.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IFromEndIndexOperation_IRangeOperation.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IInterpolatedStringOperation.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IInvocationOperation.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_INoneOperation.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IParameterReferenceExpression.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IPointerIndirectionReferenceOperation.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IPropertyReferenceExpression.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IUnaryOperatorExpression.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IVariableDeclaration.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_InvalidExpression.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_InvalidStatement.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_StackAllocArrayCreationAndInitializer.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DeconstructionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/AnonymousTypesSemanticsTests.cs
  src/Compilers/Test/Core/Compilation/OperationTreeVerifier.cs
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_IConditionalAccessExpression.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_IConversionExpression.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_IDelegateCreationExpression.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_IFieldReferenceExpression.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_IInterpolatedStringExpression.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_INoneOperation.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_IParameterReferenceExpression.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_IWhileUntilLoopStatement.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_InvalidExpression.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_InvalidStatement.vb
  src/Compilers/VisualBasic/Test/Semantic/Semantics/AnonymousTypesTests.vb
Labels: Area-Compilers

#57776 Ensure that getting the checksum for a project cone is resilient to its project references being missing
  src/VisualStudio/Core/Test.Next/Services/SolutionServiceTests.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState_Checksum.cs
Labels: Area-IDE

#57778 Fix null ref in navbars
  src/EditorFeatures/Core/Extensibility/NavigationBar/NavigationBarSelectedItems.cs
  src/EditorFeatures/Core/Implementation/NavigationBar/NavigationBarController.cs
  src/EditorFeatures/Core/Implementation/NavigationBar/NavigationBarController_ModelComputation.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs
  src/EditorFeatures/Test2/NavigationBar/NavigationBarControllerTests.vb
Labels: Area-IDE

#57765 Load SVsShellDebugger before calling IVsSolution.CreateSolution
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerInProcess.cs
Labels: Area-Infrastructure

#57783 Avoid accessing current assembly identity while reporting an accessibility diagnostics for an inaccessible internal symbol.
  src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs
  src/Compilers/CSharp/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.cs
  src/Compilers/VisualBasic/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.vb
Labels: Area-Compilers

#57782 Don't throw exceptions for file changes after a project is unloaded
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProject.cs
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioProjectTests/FileChangeTests.vb
  src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/MockVsFileChangeEx.vb
  src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb
Labels: Area-IDE

#57727 Fix ValueTracking for index parameters
  src/EditorFeatures/Test/ValueTracking/CSharpValueTrackingTests.cs
  src/EditorFeatures/Test/ValueTracking/VisualBasicValueTrackingTests.cs
  src/Features/Core/Portable/ValueTracking/ValueTracker.FindReferencesProgress.cs
  src/Features/Core/Portable/ValueTracking/ValueTracker.cs
Labels: Area-IDE

#57737 [17.0] Overload resolution was ignoring HasTypeArgumentInferredFromFunctionType for calls in expanded form
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MemberResolutionResult.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
Labels: Area-Compilers, Needs Shiproom Approval

#57713 Ignore function types in return type inference
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/BestTypeInferrer.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
Labels: Area-Compilers, Needs Shiproom Approval

#57864 Bypass IBCMerge for EditorFeatures.Wpf
  src/EditorFeatures/Core.Wpf/Microsoft.CodeAnalysis.EditorFeatures.Wpf.csproj
Labels: Area-IDE

#57615 Use helpers in param-nullchecking emit
  src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_NullChecking.cs
  src/Compilers/CSharp/Portable/Lowering/MethodToClassRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Portable/Symbols/MemberSymbolExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ParameterHelpers.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedThrowIfNullMethod.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedThrowMethod.cs
  src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenNullCheckedParameterTests.cs
  src/Compilers/Core/Portable/CodeGen/PrivateImplementationDetails.cs
Labels: Area-Compilers

#57832 Remove handling of certain BCL binaries from our build
  eng/Signing.props
  eng/config/OptProf.json
  src/NuGet/Microsoft.Net.Compilers.Toolset/DesktopCompilerArtifacts.targets
  src/Setup/DevDivInsertionFiles/DevDivInsertionFiles.csproj
Labels: Area-Infrastructure

#57824 [LSP] Use test accessor task instead of async operation to wait for LSP server shutdown in tests
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.DocumentChangeTracker.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs
  src/Features/LanguageServer/Protocol/LanguageServerTarget.cs
  src/Features/LanguageServer/ProtocolUnitTests/LanguageServerTargetTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Ordering/RequestOrderingTests.cs
Labels: Area-IDE, LSP

#57878 Backport integration test fixes to dev17.0-vs-deps
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActions/SuggestedAction.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/TextViewWindow_InProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/VisualStudio_InProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/IntegrationHelper.cs
  src/VisualStudio/IntegrationTest/TestUtilities/LightBulbHelper.cs
Labels: Area-Infrastructure

#57637 Use the .NET 6.0 SDK for building (Arcade7)
  docs/contributing/Building, Debugging, and Testing on Unix.md
  docs/contributing/Building, Debugging, and Testing on Windows.md
  eng/Version.Details.xml
  eng/common/msbuild.ps1
  eng/common/native/init-compiler.sh
  eng/common/post-build/sourcelink-validation.ps1
  eng/common/post-build/symbols-validation.ps1
  eng/common/sdl/configure-sdl-tool.ps1
  eng/common/sdl/execute-all-sdl-tools.ps1
  eng/common/templates/job/execute-sdl.yml
  eng/common/templates/job/onelocbuild.yml
  eng/common/templates/job/source-build.yml
  eng/common/templates/job/source-index-stage1.yml
  eng/common/templates/jobs/jobs.yml
  eng/common/templates/steps/send-to-helix.yml
  eng/common/tools.ps1
  eng/common/tools.sh
  global.json
Labels: Area-Infrastructure

#57822 Use the .NET 6.0 SDK for building (Arcade7)
  docs/contributing/Building, Debugging, and Testing on Unix.md
  docs/contributing/Building, Debugging, and Testing on Windows.md
  eng/Version.Details.xml
  eng/common/sdl/execute-all-sdl-tools.ps1
  eng/common/tools.ps1
  eng/common/tools.sh
  global.json
Labels: Area-Infrastructure

#57318 List-patterns: factor binding logic
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder_ListPatterns.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundCall.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundDagEvaluation.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundIndexOrRangePatternIndexerAccess.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundIndexerAccess.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/BoundTree/Expression.cs
  src/Compilers/CSharp/Portable/BoundTree/NullabilityRewriter.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.NodeMapBuilder.cs
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.DebugVerifier.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PlaceholderReplacer.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IIsPatternExpression.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests_ListPatterns.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests_ListPatterns.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
Labels: Area-Compilers, New Feature - List Patterns

#57001 Don't offer to simply to an alias if it has a different meaning
  src/EditorFeatures/CSharpTest/SimplifyTypeNames/SimplifyTypeNamesTests.cs
  src/Workspaces/CSharp/Portable/Simplification/Simplifiers/AbstractCSharpSimplifier.cs
Labels: Area-IDE

#57835 Fix add-braces crash in top-level
  src/Analyzers/CSharp/CodeFixes/AddBraces/CSharpAddBracesCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/AddBraces/AddBracesTests.cs
Labels: Area-IDE

#57836 Simplify sqlite authoring now that we're 64bit only
  src/VisualStudio/CSharp/Test/Microsoft.VisualStudio.LanguageServices.CSharp.UnitTests.csproj
  src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorageService.cs
Labels: Area-IDE

#57890 Search less files when searching in global suppressions.
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.AliasSymbols.vb
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder_GlobalSuppressions.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ConstructorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/EventSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/FieldSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamedTypeSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamespaceSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/OperatorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/OrdinaryMethodReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/PropertyAccessorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/PropertySymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex.ContextInfo.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Create.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Forwarders.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Persistence.cs
Labels: Area-IDE

#57795 Change the title of configure severity to resources file
  src/Features/Core/Portable/CodeFixes/Configuration/ConfigureSeverity/ConfigureSeverityLevelCodeFixProvider.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
Labels: Area-IDE

#57891 Fix replace-prop-with-method (and the opposite) when references are in linked files.
  src/EditorFeatures/CSharpTest/CodeActions/ReplaceMethodWithProperty/ReplaceMethodWithPropertyTests.cs
  src/EditorFeatures/CSharpTest/CodeActions/ReplacePropertyWithMethods/ReplacePropertyWithMethodsTests.cs
  src/Features/Core/Portable/ReplaceMethodWithProperty/ReplaceMethodWithPropertyCodeRefactoringProvider.cs
  src/Features/Core/Portable/ReplacePropertyWithMethods/ReplacePropertyWithMethodsCodeRefactoringProvider.cs
Labels: Area-IDE

#57683 [SourceLink] Use correct encoding for embedded text
  src/EditorFeatures/CSharpTest/PdbSourceDocument/PdbSourceDocumentTests.cs
  src/Features/Core/Portable/PdbSourceDocument/DocumentDebugInfoReader.cs
  src/Features/Core/Portable/PdbSourceDocument/IPdbSourceDocumentLoaderService.cs
  src/Features/Core/Portable/PdbSourceDocument/PdbSourceDocumentLoaderService.cs
  src/Features/Core/Portable/PdbSourceDocument/PdbSourceDocumentMetadataAsSourceFileProvider.cs
Labels: Area-IDE

#57861 Switch go-to-impl to be entirely async/non-blocking.
  src/EditorFeatures/Core/CommandHandlers/AbstractGoToCommandHandler.cs
  src/EditorFeatures/Core/CommandHandlers/AbstractGoToCommandHandler`2.cs
  src/EditorFeatures/Core/CommandHandlers/BufferedFindUsagesContext.cs
  src/EditorFeatures/Core/EditorFeaturesResources.resx
  src/EditorFeatures/Core/FindUsages/AbstractFindUsagesService.DefinitionTrackingContext.cs
  src/EditorFeatures/Core/FindUsages/AbstractFindUsagesService_FindImplementations.cs
  src/EditorFeatures/Core/FindUsages/FindUsagesContext.cs
  src/EditorFeatures/Core/GoToBase/GoToBaseCommandHandler.cs
  src/EditorFeatures/Core/GoToImplementation/GoToImplementationCommandHandler.cs
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.cs.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.de.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.es.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.fr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.it.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ja.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ko.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pl.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pt-BR.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ru.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.tr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hans.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hant.xlf
  src/Features/Core/Portable/FindUsages/IFindUsagesContext.cs
  src/Features/Core/Portable/FindUsages/IRemoteFindUsagesService.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Contexts/AbstractTableDataSourceFindUsagesContext.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Contexts/WithReferencesFindUsagesContext.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Contexts/WithoutReferencesFindUsagesContext.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/StreamingFindUsagesPresenter.cs
  src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/Editor_OutOfProc.cs
  src/Workspaces/Core/Portable/Shared/TestHooks/FeatureAttribute.cs
  src/Workspaces/Remote/ServiceHub/Services/FindUsages/RemoteFindUsagesService.cs
Labels: Area-IDE

#57913 Handle trivia better when converting to file scoped namespaces
  src/Analyzers/CSharp/CodeFixes/ConvertNamespace/ConvertNamespaceTransform.cs
  src/EditorFeatures/CSharpTest/ConvertNamespace/ConvertNamespaceRefactoringTests.cs
Labels: Area-IDE

#57889 Properly support TableEntryNavigateEventArgs.ShouldActivate
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/DocumentSpanEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/MetadataDefinitionItemEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/SimpleMessageEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/FindReferencesTableControlEventProcessorProvider.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/ISupportsNavigation.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/RoslynDefinitionBucket.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpFindReferences.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpSourceGenerators.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicFindReferences.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/Editor_InProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/FindReferencesWindow_InProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/Editor_OutOfProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/FindReferencesWindow_OutOfProc.cs
Labels: Area-IDE

#57738 Port BasicNavigationBar.CodeSpit to the new test harness
  src/VisualStudio/IntegrationTest/New.IntegrationTests/AbstractIntegrationTest.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorVerifierInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/InputInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/ShellInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/StateResetInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/TestServices.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/Microsoft.VisualStudio.LanguageServices.New.IntegrationTests.csproj
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicAddMissingReference.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicNavigationBar.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/XunitAssemblyInfo.cs
  src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/Editor_OutOfProc.cs
Labels: Area-IDE

#57838 Avoid eagerly running formatting or simplification for Extract Method
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodBase.cs
  src/EditorFeatures/Core/Implementation/ExtractMethod/AbstractExtractMethodCommandHandler.cs
  src/EditorFeatures/VisualBasicTest/ExtractMethod/ExtractMethodTests.vb
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.cs
  src/Features/Core/Portable/CodeRefactorings/ExtractMethod/AbstractExtractMethodCodeRefactoringProvider.cs
  src/Features/Core/Portable/ExtractMethod/AbstractExtractMethodService.cs
  src/Features/Core/Portable/ExtractMethod/ExtractMethodResult.cs
  src/Features/Core/Portable/ExtractMethod/ExtractMethodService.cs
  src/Features/Core/Portable/ExtractMethod/FailedExtractMethodResult.cs
  src/Features/Core/Portable/ExtractMethod/IExtractMethodService.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.cs
  src/Features/Core/Portable/ExtractMethod/SimpleExtractMethodResult.cs
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.vb
Labels: Area-IDE

#57808 Add back option to allow users to disable async lightbulbs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSourceProvider.cs
  src/EditorFeatures/Core/Implementation/Suggestions/SuggestionsOptions.cs
  src/EditorFeatures/Core/Implementation/Suggestions/SuggestionsOptionsProvider.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageStrings.vb
Labels: Area-IDE, Needs UX Triage

#57829 Fix deadlock during solution load
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
Labels: Area-IDE

#57831 Tweak SemaphoreDisposer to null out the held semaphore
  src/Compilers/Core/Portable/InternalUtilities/SemaphoreSlimExtensions.cs
Labels: Area-Compilers

#57833 Fix deadlock switching the project context dropdown
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
Labels: Area-IDE

#57549 Enable dumps for hung tests
  eng/pipelines/publish-logs.yml
  src/Tools/Source/RunTests/ProcessTestExecutor.cs
  src/Tools/Source/RunTests/TestRunner.cs
Labels: Area-Infrastructure

#57883 Merge FixIdDefinition with the same name
  src/VisualStudio/CSharp/Impl/LanguageService/CSharpCodeCleanupFixer_DiagnosticIds.cs
  src/VisualStudio/Core/Def/Implementation/CodeCleanup/AbstractCodeCleanUpFixer.cs
  src/VisualStudio/Core/Def/Implementation/CodeCleanup/CommonCodeCleanUpFixerDiagnosticIds.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/VisualBasic/Impl/LanguageService/VisualBasicCodeCleanupFixer_DiagnosticIds.vb
Labels: Area-IDE

#57813 Do not call IsFullyLoadedAsync from JTF
  src/VisualStudio/Core/Def/EditorConfigSettings/SettingsEditorFactory.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/SettingsEditorPane.cs
Labels: Area-IDE

#57691 Simplify implementation of SourceGeneratedFileItemSource
  src/VisualStudio/Core/Impl/SolutionExplorer/SourceGeneratedFileItems/SourceGeneratedFileItemSource.cs
  src/Workspaces/Core/Portable/Utilities/CancellationSeries.cs
Labels: Area-IDE

#57922 Fixes Introduce Parameter Replacing File Content Bug
  src/EditorFeatures/CSharpTest/CodeActions/IntroduceParameter/IntroduceParameterTests.cs
  src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceParameterService.cs
Labels: Area-IDE

#57936 use RTM version of nuget packages
  eng/Versions.props
Labels: Area-Infrastructure

#57816 Use InvariantCulture for generated log file name in FileLogger ctor
  src/Workspaces/Core/Portable/Log/FileLogger.cs
Labels: Area-IDE

#57930 Fix remove-unused-variable for top-level-statements
  src/Analyzers/Core/CodeFixes/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs
  src/EditorFeatures/CSharpTest/RemoveUnusedVariable/RemoveUnusedVariableTests.cs
Labels: Area-IDE

#57933 Add test for unique FixIdDefinition exports
  src/VisualStudio/CSharp/Impl/LanguageService/CSharpCodeCleanupFixer.cs
  src/VisualStudio/CSharp/Impl/LanguageService/CSharpCodeCleanupFixerDiagnosticIds.cs
  src/VisualStudio/Core/Def/Implementation/CodeCleanup/CommonCodeCleanUpFixerDiagnosticIds.cs
  src/VisualStudio/Core/Test/CodeCleanupExportTests.vb
  src/VisualStudio/VisualBasic/Impl/LanguageService/VisualBasicCodeCleanupFixer.vb
  src/VisualStudio/VisualBasic/Impl/LanguageService/VisualBasicCodeCleanupFixerDiagnosticIds.vb
Labels: Area-IDE

#57950 Correctly specify our target folder
  .vscode/settings.json
  eng/pipelines/publish-logs.yml
Labels: Area-Infrastructure

#57887 Unify the namespace for our FatalError type
  src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs
  src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/MetadataDecoder.cs
  src/Compilers/Core/Portable/Compilation/SemanticModel.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs
  src/Compilers/Core/Portable/InternalUtilities/FatalError.cs
  src/Compilers/Core/Portable/InternalUtilities/RoslynParallel.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraph.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs
  src/Compilers/Core/Portable/SourceGeneration/UserFunction.cs
  src/Compilers/Server/VBCSCompiler/BuildServerController.cs
  src/Compilers/Shared/Csc.cs
  src/Compilers/Shared/Vbc.cs
  src/Compilers/VisualBasic/Portable/Compilation/ClsComplianceChecker.vb
  src/Compilers/VisualBasic/Portable/Compilation/MethodCompiler.vb
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/MetadataDecoder.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceModuleSymbol.vb
  src/ExpressionEvaluator/Core/Source/ExpressionCompiler/ExpressionEvaluatorFatalError.cs
  src/VisualStudio/Core/Def/Implementation/Watson/WatsonReporter.cs
Labels: Area-Compilers

#57918 Unify representation of an implicit `Index` indexer over an array and non-array types.
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundArrayAccess.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundDagEvaluation.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundIndexOrRangePatternIndexerAccess.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests_ListPatterns.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefLocalsAndReturnsTests.cs
Labels: Area-Compilers, New Feature - List Patterns

#57721 Transform the GeneratorDriver even if the Compilation was GCed
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationAndGeneratorDriverTranslationAction_Actions.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
Labels: Area-IDE

#57932 Add IXamlEditAndContinueSolutionProvider for XAML Language Service
  src/VisualStudio/Xaml/Impl/Implementation/IXamlEditAndContinueSolutionProvider.cs
  src/VisualStudio/Xaml/Impl/Implementation/XamlEditAndContinueSolutionProvider.cs
Labels: Area-IDE

#57958 Treat doc comments line regular comments in metadata as source
  src/EditorFeatures/CSharpTest/Structure/MetadataAsSource/TypeDeclarationStructureTests.cs
  src/Features/CSharp/Portable/Structure/CSharpStructureHelpers.cs
  src/Features/CSharp/Portable/Structure/Providers/DocumentationCommentStructureProvider.cs
Labels: Area-IDE

#57914 List-patterns: add a few tests and add HasValidate flag
  docs/contributing/Compiler Test Plan.md
  eng/test-build-correctness.ps1
  src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs
  src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder_ListPatterns.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundDagEvaluation.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundImplicitIndexerAccess.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundListPattern.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xsd
  src/Compilers/CSharp/Portable/BoundTree/BoundSlicePattern.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests_ListPatterns.cs
  src/Compilers/Test/Utilities/CSharp/TestSources.cs
  src/Tools/Source/CompilerGeneratorTools/Source/BoundTreeGenerator/BoundNodeClassWriter.cs
Labels: Area-Compilers, New Feature - List Patterns

#57945 Simplify the code around parsing interpolated string literals.
  src/Compilers/CSharp/Portable/Parser/LanguageParser_InterpolatedString.cs
  src/Compilers/CSharp/Portable/Parser/Lexer.Interpolation.cs
  src/Compilers/CSharp/Portable/Parser/Lexer_StringLiteral.cs
Labels: Area-Compilers

#57868 Clean-up/enhance completion telemetry
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/AsyncCompletionLogger.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CommitManager.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CompletionSource.cs
  src/Features/Core/Portable/Completion/Log/CompletionProvidersLogger.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractExtensionMethodImportCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractImportCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/IRemoteExtensionMethodImportCompletionService.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/SerializableUnimportedExtensionMethods.cs
  src/Features/Core/Portable/SpellCheck/AbstractSpellCheckCodeFixProvider.cs
  src/VisualStudio/Core/Def/RoslynPackage.cs
  src/Workspaces/Remote/ServiceHub/Services/ExtensionMethodImportCompletion/RemoteExtensionMethodImportCompletionService.cs
Labels: Area-IDE, IDE-IntelliSense

#57985 Update OneOffInsertion.ps1 file path
  eng/pipelines/insert.yml
Labels: Area-Infrastructure

#57951 Share '$' logic with the normal lexer and the interpolated string scanner.
  src/Compilers/CSharp/Portable/Binder/Binder_InterpolatedString.cs
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser_InterpolatedString.cs
  src/Compilers/CSharp/Portable/Parser/Lexer.cs
  src/Compilers/CSharp/Portable/Parser/Lexer_StringLiteral.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ParserErrorMessageTests.cs
Labels: Area-Compilers, Community

#57888 Ensure we cache the previous item when two items are considered equal
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/StateTableTests.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs
Labels: Area-Compilers

#57988 Simplify creation of interpolation text tokens.
  src/Compilers/CSharp/Portable/Parser/LanguageParser_InterpolatedString.cs
Labels: Area-Compilers

#57688 Move Default VB Version to 16.9
  src/Compilers/VisualBasic/Portable/LanguageVersion.vb
Labels: Area-Compilers

#57925 Require definite assignment of all fields if struct includes any field initializers
  src/Compilers/CSharp/Portable/FlowAnalysis/FlowAnalysisPass.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/StructConstructorTests.cs
  src/Features/Core/Portable/StackTraceExplorer/StackFrameParserHelpers.cs
Labels: Area-Compilers

#57959 [LSP] Switch to exclusively using semantic tokens range handling
  src/EditorFeatures/Core/Implementation/LanguageServer/AlwaysActivateInProcLanguageClient.cs
  src/Features/LanguageServer/Protocol/DefaultCapabilitiesProvider.cs
  src/Features/LanguageServer/Protocol/Handler/AbstractRequestHandlerProvider.cs
  src/Features/LanguageServer/Protocol/Handler/FoldingRanges/FoldingRangesHandler.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/DiffEdit.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/RoslynSemanticTokensDelta.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensCache.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsDiffer.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHandler.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHandlerProvider.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHelpers.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensRangeHandler.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/TextDiffer.cs
  src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/AbstractSemanticTokensTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/SemanticTokensEditsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/SemanticTokensRangeTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/SemanticTokensTests.cs
  src/Tools/IdeCoreBenchmarks/LSPSemanticTokensBenchmarks.cs
Labels: Area-IDE, LSP

#57946 Share '@'-sign logic with the normal lexer and the interpolated string scanner.
  src/Compilers/CSharp/Portable/Parser/Lexer.cs
  src/Compilers/CSharp/Portable/Parser/Lexer_StringLiteral.cs
Labels: Area-Compilers

#57805 Add missing test for CallerArgumentExpression
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_CallerInfoAttributes.cs
  src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_CallerArgumentExpression.vb
Labels: Area-Compilers

#56432 When we're loading dependencies, don't require exact versions
  src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/ShadowCopyAnalyzerAssemblyLoader.cs
  src/Compilers/Test/Core/AssemblyLoadTestFixture.cs
  src/Tools/ExternalAccess/OmniSharp/Analyzers/OmnisharpAnalyzerLoaderFactory.cs
  src/VisualStudio/Core/Test.Next/Remote/SnapshotSerializationTests.cs
Labels: Area-Analyzers

#57966 Simplify 'interpolation' data, and move to an easier to consume System.Range approach for it
  src/Compilers/CSharp/Portable/Parser/LanguageParser_InterpolatedString.cs
  src/Compilers/CSharp/Portable/Parser/Lexer.Interpolation.cs
  src/Compilers/CSharp/Portable/Parser/Lexer.cs
  src/Compilers/CSharp/Portable/Parser/Lexer_StringLiteral.cs
Labels: Area-Compilers

#58009 Hold Receiver directly in bound node for implicit indexer access
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundArrayAccess.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundCall.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundDagEvaluation.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundImplicitIndexerAccess.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundIndexerAccess.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundInterpolatedStringArgumentPlaceholder.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/BoundTree/Expression.cs
  src/Compilers/CSharp/Portable/BoundTree/NullabilityRewriter.cs
  src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.NodeMapBuilder.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.DebugVerifier.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs
Labels: Area-Compilers

#58018 Add Roslyn.VisualStudio.Setup as a build dependency for integration tests
  Roslyn.sln
Labels: Area-Infrastructure

#58020 Fix typo in XML doc for GeneratorExtensions
  src/Compilers/Core/Portable/SourceGeneration/GeneratorExtensions.cs
Labels: Area-Compilers, Community

#57917 Attempt to mark EqualityContract property accessor as not auto-implemented
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertyAccessorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/RecordTests.cs
Labels: Area-Compilers, Community, New Language Feature - Records

#58031 Enable nullable reference types for TableDataSource
  src/EditorFeatures/Core/Implementation/CodeActions/CodeActionEditHandlerService.cs
  src/EditorFeatures/Core/Implementation/CodeActions/ICodeActionEditHandlerService.cs
  src/EditorFeatures/Core/Implementation/TodoComment/TodoItemsUpdatedArgs.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/AbstractRoslynTableDataSource.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/AbstractTable.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/AbstractTableControlEventProcessorProvider.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/AbstractTableDataSource.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/AbstractTableEntriesSnapshot.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/AbstractTableEntriesSource.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/DiagnosticTableControlEventProcessorProvider.AggregateDiagnosticTableControlEventProcessor.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/DiagnosticTableControlEventProcessorProvider.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/DiagnosticTableItem.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/Extensions.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/MiscDiagnosticTableControlEventProcessorProvider.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/MiscTodoListTableControlEventProcessorProvider.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/MiscellaneousDiagnosticListTable.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/MiscellaneousTodoListTable.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/OpenDocumentTracker.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/Suppression/DiagnosticTableControlEventProcessorProvider.SuppressionStateProcessor.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/Suppression/IVisualStudioDiagnosticListSuppressionStateService.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/Suppression/VisualStudioDiagnosticListSuppressionStateService.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/Suppression/VisualStudioDiagnosticListTableCommandHandler.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/Suppression/VisualStudioSuppressionFixService.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/TableEntriesFactory.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/TableItem.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/TodoListTableControlEventProcessorProvider.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/TodoTableItem.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/ValueTypeCache.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/VisualStudioBaseDiagnosticListTable.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/VisualStudioBaseTodoListTable.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/VisualStudioDiagnosticListTable.BuildTableDataSource.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/VisualStudioDiagnosticListTable.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/VisualStudioTodoListTable.cs
  src/VisualStudio/Core/Test/Diagnostics/DiagnosticTableDataSourceTests.vb
Labels: Area-IDE

#58035 Skip flaky test Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.BinaryOperators.TestLargeStringConcatenation
  src/Compilers/CSharp/Test/Semantic/Semantics/ConstantTests.cs
Labels: Area-Compilers
