Repository dotnet/roslyn, pull requests merged in 2021-05, with the labels that each got.

#53057 Update the prerelease version.
  eng/Versions.props
Labels: Area-Infrastructure, auto-merge

#52737 Handle records in documentation comments in IDE side
  src/EditorFeatures/CSharpTest/DocumentationComments/DocumentationCommentTests.cs
  src/Features/CSharp/Portable/DocumentationComments/DocumentationCommentSnippetService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/MemberDeclarationSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxNodeExtensions.cs
Labels: Area-IDE, Community

#53097 Obsolete importing constructor
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpRemoveUnnecessaryImportsService.cs
  src/Workspaces/VisualBasic/Portable/Indentation/VisualBasicIndentationService.vb
Labels: Area-IDE

#53098 Don't instantiate workspace service directly
  src/Workspaces/Core/Portable/LinkedFileDiffMerging/DefaultDocumentTextDifferencingService.cs
  src/Workspaces/Core/Portable/LinkedFileDiffMerging/LinkedFileDiffMergingSession.cs
Labels: Area-IDE

#52987 Correct closure info for bound sequence points
  src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs
  src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs
Labels: Area-Compilers

#53058 Introduce a common base type for SourceOrdinaryMethodSymbolBase and SourceUserDefinedOperatorSymbolBase to prepare for explicit implementations of operators
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodOrUserDefinedOperatorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbolBase.cs
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_Nullable.cs
Labels: Area-Compilers, New Feature - StaticAbstractMembersInInterfaces

#52846 Track variable declarations as well as assignments
  src/EditorFeatures/Core/ValueTracking/ValueTrackingService.Visitor.cs
  src/EditorFeatures/Core/ValueTracking/ValueTrackingService.cs
  src/EditorFeatures/Test/ValueTracking/CSharpValueTrackingTests.cs
  src/EditorFeatures/Test/ValueTracking/VisualBasicValueTrackingTests.cs
Labels: Area-IDE, Feature - IDE Value Tracking

#53114 Simplify interfaces for codefixes and coderefactorings
  src/Features/Core/Portable/CodeFixes/CodeFixService.cs
  src/Features/Core/Portable/CodeFixes/ICodeFixService.cs
  src/Features/Core/Portable/CodeRefactorings/CodeRefactoringService.cs
  src/Features/Core/Portable/CodeRefactorings/ICodeRefactoringService.cs
Labels: Area-IDE

#53122 Refactor CleanUpDeadObjectsAsync
  src/VisualStudio/Core/Def/Implementation/Interop/CleanableWeakComHandleTable.cs
  src/VisualStudio/Core/Def/Implementation/Utilities/TimeSlice.cs
  src/VisualStudio/Core/Impl/CodeModel/FileCodeModel_Events.cs
  src/VisualStudio/Core/Impl/CodeModel/ProjectCodeModelFactory.cs
Labels: Area-IDE

#53038 Support syntax for explicit implementation of operators
  src/Compilers/CSharp/Portable/Generated/CSharp.Generated.g4
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Internal.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Main.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Syntax.Generated.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Syntax/OperatorDeclarationSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
  src/Compilers/CSharp/Portable/Syntax/SyntaxFactory.cs
  src/Compilers/CSharp/Test/Syntax/Generated/Syntax.Test.xml.Generated.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/TopLevelStatementsParsingTests.cs
Labels: Area-Compilers, New Feature - StaticAbstractMembersInInterfaces

#52815 Remove the IForegroundNotificationService
  src/EditorFeatures/Core/IForegroundNotificationService.cs
  src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs
  src/EditorFeatures/Core/Tagging/AsynchronousViewTaggerProvider.cs
  src/EditorFeatures/Test/Threading/ForegroundNotificationServiceTests.cs
  src/VisualStudio/CSharp/Test/CodeModel/FileCodeModelTestHelpers.cs
  src/VisualStudio/Core/Impl/CodeModel/ProjectCodeModelFactory.cs
  src/VisualStudio/Core/Test/Diagnostics/DefaultDiagnosticUpdateSourceTests.vb
  src/VisualStudio/TestUtilities2/CodeModel/CodeModelTestHelpers.vb
  src/Workspaces/CoreTestUtilities/MEF/UseExportProviderAttribute.cs
Labels: Area-IDE

#52907 Add OmniSharp ExternalAccess
  Roslyn.sln
  docs/ide/external-access.md
  eng/config/PublishData.json
  eng/targets/Settings.props
  src/Compilers/Test/Core/Microsoft.CodeAnalysis.Test.Utilities.csproj
  src/Features/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.Features.csproj
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/Tools/ExternalAccess/OmniSharp.CSharp/Completion/OmniSharpCompletionProviderNames.cs
  src/Tools/ExternalAccess/OmniSharp.CSharp/DocumentationComments/OmniSharpDocCommentConverter.cs
  src/Tools/ExternalAccess/OmniSharp.CSharp/Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.CSharp.csproj
  src/Tools/ExternalAccess/OmniSharp.CSharp/PublicAPI.Shipped.txt
  src/Tools/ExternalAccess/OmniSharp.CSharp/PublicAPI.Unshipped.txt
  src/Tools/ExternalAccess/OmniSharp/CodeActions/OmniSharpCodeAction.cs
  src/Tools/ExternalAccess/OmniSharp/CodeRefactorings/WorkspaceServices/IOmniSharpSymbolRenamedCodeActionOperationFactoryWorkspaceService.cs
  src/Tools/ExternalAccess/OmniSharp/Completion/OmniSharpCompletionService.cs
  src/Tools/ExternalAccess/OmniSharp/DocumentationComments/OmniSharpDocumentationCommentsSnippetService.cs
  src/Tools/ExternalAccess/OmniSharp/ExtractClass/IOmniSharpExtractClassOptionsService.cs
  src/Tools/ExternalAccess/OmniSharp/ExtractInterface/IOmniSharpExtractInterfaceOptionsService.cs
  src/Tools/ExternalAccess/OmniSharp/ImplementType/OmniSharpImplementTypeOptions.cs
  src/Tools/ExternalAccess/OmniSharp/Internal/CodeRefactorings/WorkspaceServices/OmniSharpSymbolRenamedCodeActionOperationFactoryWorkspaceService.cs
  src/Tools/ExternalAccess/OmniSharp/Internal/ExtractClass/OmniSharpExtractClassOptionsService.cs
  src/Tools/ExternalAccess/OmniSharp/Internal/ExtractInterface/OmniSharpExtractInterfaceOptionsService.cs
  src/Tools/ExternalAccess/OmniSharp/Internal/PickMembers/OmniSharpPickMembersService.cs
  src/Tools/ExternalAccess/OmniSharp/MetadataAsSource/OmniSharpMetadataAsSourceHelpers.cs
  src/Tools/ExternalAccess/OmniSharp/MetadataAsSource/OmniSharpMetadataAsSourceService.cs
  src/Tools/ExternalAccess/OmniSharp/Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.csproj
  src/Tools/ExternalAccess/OmniSharp/PickMembers/IOmniSharpPickMembersService.cs
  src/Tools/ExternalAccess/OmniSharp/PublicAPI.Shipped.txt
  src/Tools/ExternalAccess/OmniSharp/PublicAPI.Unshipped.txt
  src/Tools/ExternalAccess/OmniSharp/Structure/OmniSharpBlockSpan.cs
  src/Tools/ExternalAccess/OmniSharp/Structure/OmniSharpBlockStructure.cs
  src/Tools/ExternalAccess/OmniSharp/Structure/OmniSharpBlockStructureOptions.cs
  src/Tools/ExternalAccess/OmniSharp/Structure/OmniSharpBlockStructureService.cs
  src/Tools/ExternalAccess/OmniSharp/Structure/OmniSharpBlockTypes.cs
  src/Tools/ExternalAccess/OmniSharpTest/EnumTests.cs
  src/Tools/ExternalAccess/OmniSharpTest/Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.UnitTests.csproj
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
Labels: Area-IDE

#53099 Delete dead test code files
  src/EditorFeatures/CSharpTest/Interactive/CommandArgumentsParsingTest.cs
  src/EditorFeatures/CSharpTest/Microsoft.CodeAnalysis.CSharp.EditorFeatures.UnitTests.csproj
  src/EditorFeatures/CSharpTest/ReorderParameters/ReorderParametersTests.Cascading.cs
  src/EditorFeatures/CSharpTest/ReorderParameters/ReorderParametersTests.InvocationErrors.cs
  src/EditorFeatures/CSharpTest/ReorderParameters/ReorderParametersTests.InvocationLocation.cs
  src/EditorFeatures/CSharpTest/ReorderParameters/ReorderParametersTests.cs
Labels: Area-IDE, Community

#50219 Don't report unused parameter for GetInstance of ICustomMarshaler
  src/Analyzers/CSharp/Tests/RemoveUnusedParametersAndValues/RemoveUnusedParametersTests.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs
Labels: Area-IDE

#48135 Format init accessor on typing '}'
  src/EditorFeatures/CSharpTest/Formatting/Indentation/SmartTokenFormatterFormatRangeTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/FormattingRangeHelper.cs
Labels: Area-IDE, Community

#52913 Fix syntax code generation to account for kinds specified in parent
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Main.Generated.cs
  src/Compilers/CSharp/Test/Syntax/Generated/Syntax.Test.xml.Generated.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/AbstractFileWriter.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/SourceWriter.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/TestWriter.cs
Labels: Area-Compilers, Community

#53127 Workaround bug in LSP client in 16.10p2 in integration tests
  src/VisualStudio/IntegrationTest/IntegrationTests/AbstractEditorTest.cs
  src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs
Labels: Approved to merge, Area-IDE

#53142 Improve error recovery in parser around explicit interface specifier in operators.
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs
Labels: Area-Compilers, New Feature - StaticAbstractMembersInInterfaces

#49051 Wrap state in SuggestedActionsSource to avoid race conditions with Dispose
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs
Labels: Area-IDE

#53146 Update proposal URL in StaticAbstractMembersInInterfaces.md
  docs/features/StaticAbstractMembersInInterfaces.md
Labels: Area-Compilers, Documentation

#48131 Support InitAccessorDeclaration in UseExpressionBodyForAccessors
  src/Analyzers/CSharp/Analyzers/UseExpressionBody/Helpers/UseExpressionBodyForAccessorsHelper.cs
  src/Analyzers/CSharp/Tests/UseExpressionBody/UseExpressionBodyForAccessorsAnalyzerTests.cs
Labels: Area-IDE, Community

#53101 Revert dotnet watch
  Roslyn.sln
  eng/targets/Settings.props
  src/EditorFeatures/Test/EditAndContinue/RemoteEditAndContinueServiceTests.cs
  src/EditorFeatures/TestUtilities/EditAndContinue/MockEditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/IEditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/Remote/RemoteEditAndContinueServiceProxy.cs
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/Tools/ExternalAccess/DotNetWatch/DotNetWatchEditAndContinueWorkspaceService.cs
  src/Tools/ExternalAccess/DotNetWatch/DotNetWatchManagedModuleUpdateStatus.cs
  src/Tools/ExternalAccess/DotNetWatch/DotNetWatchManagedModuleUpdateWrapper.cs
  src/Tools/ExternalAccess/DotNetWatch/DotNetWatchManagedModuleUpdatesWrapper.cs
  src/Tools/ExternalAccess/DotNetWatch/Microsoft.CodeAnalysis.ExternalAccess.DotNetWatch.csproj
  src/Tools/ExternalAccess/DotNetWatch/PublicAPI.Shipped.txt
  src/Tools/ExternalAccess/DotNetWatch/PublicAPI.Unshipped.txt
  src/Tools/ExternalAccess/DotNetWatch/StubManagedEditAndContinueDebuggerService.cs
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
  src/Workspaces/Remote/ServiceHub/Services/EditAndContinue/RemoteEditAndContinueService.cs
Labels: Area-Interactive

#53156 Merge release/dev16.11-vs-deps to release/dev17.0-preview1-nopia-vs-deps
  azure-pipelines-official.yml
  azure-pipelines.yml
  eng/common/generate-locproject.ps1
  eng/common/templates/job/onelocbuild.yml
  src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs
  src/Compilers/CSharp/Portable/Symbols/ConstructedNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/SubstitutedNamedTypeSymbol.cs
  src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/GenericConstraintTests.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/GenericConstraintTests.vb
  src/EditorFeatures/Core.Wpf/QuickInfo/LazyToolTip.cs
  src/EditorFeatures/Core/InheritanceMargin/InheritanceMarginServiceHelpers.cs
  src/EditorFeatures/Core/ReferenceHighlighting/ReferenceHighlightingViewTaggerProvider.cs
  src/EditorFeatures/Core/Shared/Tagging/EventSources/TaggerConstants.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs
  src/EditorFeatures/Test/InheritanceMargin/InheritanceMarginTests.cs
  src/EditorFeatures/TestUtilities/EditAndContinue/MockManagedEditAndContinueDebuggerService.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/ExternalAccess/Watch/Api/WatchHotReloadService.cs
  src/Features/Core/Portable/Workspace/CompileTimeSolutionProvider.cs
  src/Tools/ExternalAccess/DotNetWatch/StubManagedEditAndContinueDebuggerService.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/SettingsEditorFactory.cs
  src/VisualStudio/Core/Def/Implementation/EditAndContinue/ManagedHotReloadLanguageService.cs
  src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/Telemetry/VisualStudioWorkspaceTelemetryService.cs
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpArgumentProvider.cs
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageStrings.vb
  src/Workspaces/Core/Portable/CodeActions/CodeAction.cs
  src/Workspaces/Core/Portable/Diagnostics/InternalDiagnosticsOptions.cs
  src/Workspaces/Core/Portable/Log/FileLogger.cs
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/CustomCodeActions.cs
Labels: Area-Infrastructure, auto-merge

#53023 Cleanup docs and impl around FindReferences cleanup.
  src/VisualStudio/Core/Def/Implementation/FindReferences/Contexts/AbstractTableDataSourceFindUsagesContext.cs
Labels: Area-IDE

#53159 Convert tests to the new test framework
  src/Analyzers/CSharp/Tests/UseExpressionBody/UseExpressionBodyForAccessorsAnalyzerTests.cs
Labels: Area-IDE

#52680 Fix switch-expression and pattern printing in SyntaxNormalizer
  src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs
  src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs
Labels: Area-Compilers, Community

#53148 Add telemetry to Value Tracking
  src/EditorFeatures/Core/ValueTracking/ValueTrackingService.FindReferencesProgress.cs
  src/EditorFeatures/Core/ValueTracking/ValueTrackingService.cs
  src/VisualStudio/Core/Def/ValueTracking/ValueTrackingCommandHandler.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/Logger.cs
Labels: Area-IDE

#53154 Avoid NullReferenceException in MissingMetadataTypeSymbol if it doesn't have containing module.
  src/Compilers/CSharp/Portable/Symbols/MissingMetadataTypeSymbol.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/ErrorTypeSymbolTests.cs
  src/Compilers/VisualBasic/Portable/Symbols/MissingMetadataTypeSymbol.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/SymbolErrorTests.vb
Labels: Area-Compilers

#53131 Use a sentinel value in the lightbulb code to simplify logic.
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.State.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs
  src/Workspaces/Core/Portable/Workspace/Host/Status/IWorkspaceStatusService.cs
Labels: Area-IDE

#53048 Ensure that an ObjectDisposed exception cannot happen during tagging
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSourceState.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ReferenceCounting.cs
Labels: Area-IDE

#53029 Move the ConvertTupleToStruct tests to the sdk test harness
  src/Analyzers/Core/CodeFixes/UseSystemHashCode/UseSystemHashCodeCodeFixProvider.cs
  src/EditorFeatures/CSharpTest/ConvertTupleToStruct/ConvertTupleToStructTests.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/CSharpCodeRefactoringVerifier`1+Test.cs
  src/Features/CSharp/Portable/ConvertTupleToStruct/CSharpConvertTupleToStructCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertTupleToStruct/AbstractConvertTupleToStructCodeRefactoringProvider.cs
  src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/AbstractGenerateEqualsAndGetHashCodeService.cs
  src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeAction.cs
  src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions_CreateEqualsMethod.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpSyntaxGeneratorInternal.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions_CreateGetHashCodeMethod.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/SyntaxGeneratorInternalExtensions/SyntaxGeneratorInternal.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/LanguageServices/VisualBasicSyntaxGeneratorInternal.vb
Labels: Area-IDE

#53167 Catch and report errors in LegacyCodeAnalysisVisualStudioSuppressionFixServiceAccessor
  src/VisualStudio/Core/Def/ExternalAccess/LegacyCodeAnalysis/LegacyCodeAnalysisVisualStudioSuppressionFixServiceAccessor.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/Suppression/IVisualStudioSuppressionFixService.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
Labels: Area-IDE

#52139 Implement extended property patterns
  eng/targets/Settings.props
  src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs
  src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/BoundTree/BoundSubpattern.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharp.Generated.g4
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Internal.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Main.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Syntax.Generated.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Syntax/InternalSyntax/NameColonSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/InternalSyntax/SubpatternSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/NameColonSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/SubpatternSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
  src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests5.cs
  src/Compilers/CSharp/Test/Syntax/Generated/Syntax.Test.xml.Generated.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests2.cs
  src/Compilers/Test/Core/TestResource.resx
  src/Compilers/Test/Utilities/CSharp/TestOptions.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/PropertySubPatternCompletionProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs
Labels: Area-Compilers

#53126 Bump Nuget and debugger packages version
  eng/Versions.props
  src/ExpressionEvaluator/Core/Test/ResultProvider/Debugger/MemberInfo/TypeImpl.cs
Labels: Area-Infrastructure

#53168 Port ExternalAccess.OmniSharp to 16.11
  Roslyn.sln
  docs/ide/external-access.md
  eng/config/PublishData.json
  eng/targets/Settings.props
  src/Compilers/Test/Core/Microsoft.CodeAnalysis.Test.Utilities.csproj
  src/Features/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.Features.csproj
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/Tools/ExternalAccess/OmniSharp.CSharp/Completion/OmniSharpCompletionProviderNames.cs
  src/Tools/ExternalAccess/OmniSharp.CSharp/DocumentationComments/OmniSharpDocCommentConverter.cs
  src/Tools/ExternalAccess/OmniSharp.CSharp/Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.CSharp.csproj
  src/Tools/ExternalAccess/OmniSharp.CSharp/PublicAPI.Shipped.txt
  src/Tools/ExternalAccess/OmniSharp.CSharp/PublicAPI.Unshipped.txt
  src/Tools/ExternalAccess/OmniSharp/CodeActions/OmniSharpCodeAction.cs
  src/Tools/ExternalAccess/OmniSharp/CodeRefactorings/WorkspaceServices/IOmniSharpSymbolRenamedCodeActionOperationFactoryWorkspaceService.cs
  src/Tools/ExternalAccess/OmniSharp/Completion/OmniSharpCompletionService.cs
  src/Tools/ExternalAccess/OmniSharp/DocumentationComments/OmniSharpDocumentationCommentsSnippetService.cs
  src/Tools/ExternalAccess/OmniSharp/ExtractClass/IOmniSharpExtractClassOptionsService.cs
  src/Tools/ExternalAccess/OmniSharp/ExtractInterface/IOmniSharpExtractInterfaceOptionsService.cs
  src/Tools/ExternalAccess/OmniSharp/ImplementType/OmniSharpImplementTypeOptions.cs
  src/Tools/ExternalAccess/OmniSharp/Internal/CodeRefactorings/WorkspaceServices/OmniSharpSymbolRenamedCodeActionOperationFactoryWorkspaceService.cs
  src/Tools/ExternalAccess/OmniSharp/Internal/ExtractClass/OmniSharpExtractClassOptionsService.cs
  src/Tools/ExternalAccess/OmniSharp/Internal/ExtractInterface/OmniSharpExtractInterfaceOptionsService.cs
  src/Tools/ExternalAccess/OmniSharp/Internal/PickMembers/OmniSharpPickMembersService.cs
  src/Tools/ExternalAccess/OmniSharp/MetadataAsSource/OmniSharpMetadataAsSourceHelpers.cs
  src/Tools/ExternalAccess/OmniSharp/MetadataAsSource/OmniSharpMetadataAsSourceService.cs
  src/Tools/ExternalAccess/OmniSharp/Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.csproj
  src/Tools/ExternalAccess/OmniSharp/PickMembers/IOmniSharpPickMembersService.cs
  src/Tools/ExternalAccess/OmniSharp/PublicAPI.Shipped.txt
  src/Tools/ExternalAccess/OmniSharp/PublicAPI.Unshipped.txt
  src/Tools/ExternalAccess/OmniSharp/Structure/OmniSharpBlockSpan.cs
  src/Tools/ExternalAccess/OmniSharp/Structure/OmniSharpBlockStructure.cs
  src/Tools/ExternalAccess/OmniSharp/Structure/OmniSharpBlockStructureOptions.cs
  src/Tools/ExternalAccess/OmniSharp/Structure/OmniSharpBlockStructureService.cs
  src/Tools/ExternalAccess/OmniSharp/Structure/OmniSharpBlockTypes.cs
  src/Tools/ExternalAccess/OmniSharpTest/EnumTests.cs
  src/Tools/ExternalAccess/OmniSharpTest/Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.UnitTests.csproj
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
Labels: Area-Infrastructure

#53157 Revert dotnet watch (#53101)
  Roslyn.sln
  eng/targets/Settings.props
  src/EditorFeatures/Test/EditAndContinue/RemoteEditAndContinueServiceTests.cs
  src/EditorFeatures/TestUtilities/EditAndContinue/MockEditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/IEditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/Remote/RemoteEditAndContinueServiceProxy.cs
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/Tools/ExternalAccess/DotNetWatch/DotNetWatchEditAndContinueWorkspaceService.cs
  src/Tools/ExternalAccess/DotNetWatch/DotNetWatchManagedModuleUpdateStatus.cs
  src/Tools/ExternalAccess/DotNetWatch/DotNetWatchManagedModuleUpdateWrapper.cs
  src/Tools/ExternalAccess/DotNetWatch/DotNetWatchManagedModuleUpdatesWrapper.cs
  src/Tools/ExternalAccess/DotNetWatch/Microsoft.CodeAnalysis.ExternalAccess.DotNetWatch.csproj
  src/Tools/ExternalAccess/DotNetWatch/PublicAPI.Shipped.txt
  src/Tools/ExternalAccess/DotNetWatch/PublicAPI.Unshipped.txt
  src/Tools/ExternalAccess/DotNetWatch/StubManagedEditAndContinueDebuggerService.cs
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
  src/Workspaces/Remote/ServiceHub/Services/EditAndContinue/RemoteEditAndContinueService.cs
Labels: Approved to merge, Area-Infrastructure

#53162 Fix quick info LSP tests to wait for the quick info session
  azure-pipelines-integration-lsp.yml
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/TextViewWindow_InProc.cs
Labels: Area-IDE

#53180 Simplify suggested action computation.
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs
  src/Features/Core/Portable/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs
  src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionHelpers.cs
Labels: Area-IDE

#53110 Adhere to new lines for braces formatting option in property pattern clauses
  src/Workspaces/CSharpTest/Formatting/FormattingTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs
Labels: Area-IDE, Community

#53060 Bump compilation options version in PDB for 16.10
  src/Compilers/Core/Portable/PEWriter/MetadataWriter.PortablePdb.cs
  src/Compilers/Test/Core/PDB/DeterministicBuildCompilationTestHelpers.cs
Labels: Approved to merge, Area-Compilers, New Language Feature - Rebuild

#53196 Update publish data for 16.11
  eng/config/PublishData.json
Labels: Area-Infrastructure

#53208 Do not offer use-coalesce-expression in target typing scenarios
  src/Analyzers/CSharp/Analyzers/UseCoalesceExpression/CSharpUseCoalesceExpressionDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/UseCoalesceExpression/UseCoalesceExpressionTests.cs
  src/Analyzers/Core/Analyzers/UseCoalesceExpression/AbstractUseCoalesceExpressionDiagnosticAnalyzer.cs
  src/Analyzers/VisualBasic/Analyzers/UseCoalesceExpression/VisualBasicUseCoalesceExpressionDiagnosticAnalyzer.vb
Labels: Area-IDE

#53130 Add support for implementations of interface static abstract operators in classes and structures
  src/Compilers/CSharp/Portable/Binder/BinderFactory.BinderFactoryVisitor.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs
  src/Compilers/CSharp/Portable/Declarations/DeclarationTreeBuilder.cs
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Members.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ExplicitInterfaceHelpers.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedConversionSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityOperatorBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedExplicitImplementationForwardingMethod.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedImplementationMethod.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenInterfaceImplementation.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
Labels: Area-Compilers, New Feature - StaticAbstractMembersInInterfaces

#52999 Apply changes for source build and remove patches
  eng/SourceBuild.props
  eng/build.sh
  eng/source-build-patches/0001-Conditionally-remove-net472-from-TargetFrameworks.patch
  eng/source-build-patches/0002-Do-not-build-NET-Fx-binaries-in-source-build.patch
  eng/source-build-patches/0004-Include-Compilers-package-projects-in-source-build.patch
  eng/source-build-patches/0005-Don-t-restore-tools-in-source-build.patch
  eng/source-build-patches/0006-Dirty-revert-of-https-github.com-dotnet-roslyn-issue.patch
  eng/source-build-patches/0008-Update-a-S.IO.Pipes.AccessControl-to-use-reference-p.patch
  eng/source-build-patches/0008-remove-RichCodeNav.EnvVarDump-on-source-build.patch
  eng/source-build-patches/0009-Don-t-build-VBCSCompiler-for-net472.patch
  eng/source-build-patches/0011-Build-Microsoft.CodeAnalysis-for-source-build.patch
  eng/source-build-patches/0012-Build-Roslyn-as-net6.0-in-source-build.patch
  eng/source-build-patches/0014-Update-CSharpSyntaxGenerator.csproj-to-build-with-.N.patch
  eng/source-build-patches/0015-Remove-reference-to-System.Runtime.InteropServices.W.patch
  eng/source-build-patches/0016-Comment-out-AsSpan-call.-Extension-method-doesn-t-se.patch
  eng/source-build-patches/0017-Rename-IReadOnlySet-and-ReferenceEqualityComparer-Ro.patch
  eng/targets/Settings.props
  src/Compilers/Core/CommandLine/CompilerServerLogger.cs
  src/Compilers/Server/VBCSCompiler/ClientConnectionHandler.cs
  src/Interactive/Directory.Build.props
  src/Interactive/Host/Microsoft.CodeAnalysis.InteractiveHost.csproj
  src/Interactive/HostProcess/InteractiveHost32.csproj
  src/Interactive/HostProcess/InteractiveHost64.csproj
  src/NuGet/Directory.Build.props
  src/NuGet/Microsoft.CodeAnalysis.Compilers.Package.csproj
  src/NuGet/Microsoft.CodeAnalysis.EditorFeatures.Package.csproj
  src/NuGet/Microsoft.CodeAnalysis.Scripting.Package.csproj
  src/NuGet/Microsoft.Net.Compilers.Toolset/DesktopCompilerArtifacts.targets
  src/NuGet/Microsoft.Net.Compilers/Microsoft.Net.Compilers.Package.csproj
  src/Scripting/CoreTestUtilities/Microsoft.CodeAnalysis.Scripting.TestUtilities.csproj
  src/Scripting/Directory.Build.props
Labels: Area-Infrastructure, Source-Build

#49237 Don't offer "introduce local constant" for constants
  src/EditorFeatures/CSharpTest/CodeActions/IntroduceVariable/IntroduceVariableTests.cs
  src/EditorFeatures/VisualBasicTest/CodeActions/IntroduceVariable/IntroduceVariableTests.vb
  src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.State.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFactsExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxKinds.vb
Labels: Area-IDE, Community

#53204 Add code-remote-base to c# and vb content type definitions
  src/EditorFeatures/CSharp/ContentType/ContentTypeDefinitions.cs
  src/EditorFeatures/VisualBasic/ContentType/ContentTypeDefinitions.vb
Labels: Area-IDE, LSP

#53214 Remove bridge interface now that TS has moved to their new EA interface.
  src/EditorFeatures/CSharp/NavigationBar/CSharpEditorNavigationBarItemService.cs
  src/EditorFeatures/Core/Extensibility/NavigationBar/AbstractEditorNavigationBarItemService.cs
  src/EditorFeatures/Core/Extensibility/NavigationBar/INavigationBarItemService.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptNavigationBarItemService.cs
  src/EditorFeatures/Core/Implementation/NavigationBar/NavigationBarController.cs
  src/EditorFeatures/Core/Implementation/NavigationBar/NavigationBarController_ModelComputation.cs
  src/EditorFeatures/Core/Implementation/NavigationBar/NavigationBarModel.cs
  src/EditorFeatures/Test2/NavigationBar/TestHelpers.vb
  src/EditorFeatures/VisualBasic/NavigationBar/VisualBasicEditorNavigationBarItemService.vb
  src/Tools/ExternalAccess/FSharp/Internal/Editor/FSharpNavigationBarItemService.cs
Labels: Area-IDE

#52728 Remove NotImplementedExvception from being thrown.
  src/EditorFeatures/Core.Cocoa/Preview/PreviewPaneService.cs
Labels: Area-IDE

#53239 Remove useRawWin32Resource parameter
  src/Compilers/CSharp/Test/Emit/PDB/PDBSourceLinkTests.cs
  src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs
  src/Compilers/Core/Portable/Compilation/Compilation.cs
  src/Compilers/Core/Rebuild/CompilationFactory.cs
  src/Compilers/Test/Core/Compilation/CompilationExtensions.cs
  src/Compilers/Test/Core/Compilation/IRuntimeEnvironment.cs
Labels: Area-Compilers

#52959 MonoOnlyFact -> Fact
  src/Compilers/Test/Core/Assert/ClrOnlyFactAttribute.cs
  src/Scripting/CoreTest.Desktop/GlobalAssemblyCacheTests.cs
Labels: Area-Compilers, Area-Interactive, Test

#53246 Null annotate and add some checks for SymbolFinder.cs
  src/EditorFeatures/Core.Wpf/Peek/PeekableItemSource.cs
  src/Features/CSharp/Portable/MakeLocalFunctionStatic/MakeLocalFunctionStaticCodeFixHelper.cs
  src/Features/Core/Portable/InlineMethod/AbstractInlineMethodRefactoringProvider.MethodParametersInfo.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_Callers.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_FindReferences_Current.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_FindReferences_Legacy.cs
  src/Workspaces/Core/Portable/Rename/ConflictEngine/ConflictResolver.Session.cs
Labels: Area-IDE

#51035 Switch pattern matching to use TemporaryArray
  src/EditorFeatures/Test/Utilities/PatternMatcherTests.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.NameGenerator.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.InProcess.cs
  src/Features/Core/Portable/Shared/Naming/IdentifierNameParts.cs
  src/Workspaces/Core/Portable/PatternMatching/AllLowerCamelCaseMatcher.cs
  src/Workspaces/Core/Portable/PatternMatching/CamelCaseResult.cs
  src/Workspaces/Core/Portable/PatternMatching/ContainerPatternMatcher.cs
  src/Workspaces/Core/Portable/PatternMatching/PatternMatcher.PatternSegment.cs
  src/Workspaces/Core/Portable/PatternMatching/PatternMatcher.TextChunk.cs
  src/Workspaces/Core/Portable/PatternMatching/PatternMatcher.cs
  src/Workspaces/Core/Portable/PatternMatching/PatternMatcherExtensions.cs
  src/Workspaces/Core/Portable/PatternMatching/SimplePatternMatcher.cs
  src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions_CreateEqualsMethod.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/TemporaryArray`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyle.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/StringBreaker.cs
Labels: Area-IDE

#53147 Syntax inputs and preview flag
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/SourceGeneration/CSharpGeneratorDriver.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/SyntaxAwareGeneratorTests.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Core/Portable/SourceGeneration/GeneratorAdaptor.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorContexts.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriverState.cs
  src/Compilers/Core/Portable/SourceGeneration/IncrementalContexts.cs
  src/Compilers/Core/Portable/SourceGeneration/IncrementalGeneratorSyntaxWalker.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/BatchTransformNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/DriverStateTable.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/IIncrementalGeneratorNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/IncrementalValueSources.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/InputNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/JoinNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SourceOutputNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxTransformNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueSources.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/TransformNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/ValueSourceExtensions.cs
  src/Compilers/Test/Core/SourceGeneration/TestGenerators.cs
  src/Compilers/VisualBasic/Portable/SourceGeneration/VisualBasicGeneratorDriver.vb
  src/Compilers/VisualBasic/Test/Semantic/SourceGeneration/GeneratorDriverTests.vb
Labels: Area-Compilers, New Feature - Source Generators

#53250 Combine duplicate private methods by one method having base class as parameter
  src/Features/CSharp/Portable/MakeMethodAsynchronous/CSharpMakeMethodAsynchronousCodeFixProvider.cs
Labels: Area-IDE, Community

#53259 Remove EnC completion flag
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/OverrideCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/TypeImportCompletionProviderTests.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CommitManager.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CompletionSource.cs
  src/EditorFeatures/TestUtilities/Completion/AbstractCompletionProviderTests.cs
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/SuggestionModeCompletionProviderTests.vb
  src/Features/CSharp/Portable/Completion/CompletionProviders/OperatorsAndIndexer/UnnamedSymbolCompletionProvider.cs
  src/Features/Core/Portable/Completion/CompletionProvider.cs
  src/Features/Core/Portable/Completion/CompletionService.cs
  src/Features/Core/Portable/Completion/CompletionServiceOptions.cs
  src/Features/Core/Portable/Completion/CompletionServiceWithProviders.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractExtensionMethodImportCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractImportCompletionProvider.cs
  src/Features/Core/Portable/SpellCheck/AbstractSpellCheckCodeFixProvider.cs
  src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandler.cs
Labels: Area-IDE

#53225 Merge features/source-build to main
  azure-pipelines.yml
  eng/SourceBuild.props
  eng/SourceBuildPrebuiltBaseline.xml
  eng/Version.Details.xml
  eng/build.sh
  eng/targets/Settings.props
  src/Compilers/Core/CommandLine/CompilerServerLogger.cs
  src/Compilers/Core/Portable/InternalUtilities/PlatformAttributes.cs
  src/Compilers/Server/VBCSCompiler/ClientConnectionHandler.cs
  src/Interactive/Directory.Build.props
  src/Interactive/Host/Microsoft.CodeAnalysis.InteractiveHost.csproj
  src/Interactive/HostProcess/InteractiveHost32.csproj
  src/Interactive/HostProcess/InteractiveHost64.csproj
  src/NuGet/Directory.Build.props
  src/NuGet/Microsoft.CodeAnalysis.Compilers.Package.csproj
  src/NuGet/Microsoft.CodeAnalysis.EditorFeatures.Package.csproj
  src/NuGet/Microsoft.CodeAnalysis.Scripting.Package.csproj
  src/NuGet/Microsoft.Net.Compilers.Toolset/DesktopCompilerArtifacts.targets
  src/NuGet/Microsoft.Net.Compilers/Microsoft.Net.Compilers.Package.csproj
  src/Scripting/CoreTestUtilities/Microsoft.CodeAnalysis.Scripting.TestUtilities.csproj
  src/Scripting/Directory.Build.props
Labels: Area-Infrastructure

#48415 Add records to C# declaration comparer
  src/EditorFeatures/CSharpTest/Diagnostics/GenerateMethod/GenerateDeconstructMethodTests.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpDeclarationComparer.cs
Labels: Area-IDE, Community

#53249 Don't suggest to add null checks to nullable reference types
  src/EditorFeatures/CSharpTest/InitializeParameter/AddParameterCheckTests.cs
  src/Features/Core/Portable/InitializeParameter/AbstractAddParameterCheckCodeRefactoringProvider.cs
Labels: Approved to merge, Area-IDE

#53264 Add additional info to contract call
  src/Workspaces/Core/Portable/FindSymbols/IStreamingFindReferencesProgress.cs
Labels: Area-IDE

#53287 Use NRT
  src/Features/Core/Portable/AddAnonymousTypeMemberName/AbstractAddAnonymousTypeMemberNameCodeFixProvider.cs
  src/Features/Core/Portable/AddConstructorParametersFromMembers/AddConstructorParametersFromMembersCodeRefactoringProvider.AddConstructorParametersCodeAction.cs
  src/Features/Core/Portable/AddConstructorParametersFromMembers/AddConstructorParametersFromMembersCodeRefactoringProvider.ConstructorCandidate.cs
  src/Features/Core/Portable/AddConstructorParametersFromMembers/AddConstructorParametersFromMembersCodeRefactoringProvider.State.cs
  src/Features/Core/Portable/AddConstructorParametersFromMembers/AddConstructorParametersFromMembersCodeRefactoringProvider.cs
  src/Features/Core/Portable/AddMissingReference/AbstractAddMissingReferenceCodeFixProvider.cs
  src/Features/Core/Portable/AddMissingReference/AddMissingReferenceCodeAction.cs
  src/Features/Core/Portable/AddObsoleteAttribute/AbstractAddObsoleteAttributeCodeFixProvider.cs
  src/Features/Core/Portable/AddParameter/AbstractAddParameterCodeFixProvider.cs
  src/Features/Core/Portable/AddParameter/AddParameterService.cs
  src/Features/Core/Portable/AddParameter/ArgumentInsertPositionData.cs
  src/Features/Core/Portable/AddParameter/IAddParameterService.cs
  src/Features/Core/Portable/AddParameter/RegisterFixData.cs
  src/Features/Core/Portable/AliasAmbiguousType/AbstractAliasAmbiguousTypeCodeFixProvider.cs
  src/Features/Core/Portable/CodeCleanup/ICodeCleanupService.cs
  src/Features/Core/Portable/CommentSelection/AbstractCommentSelectionService.cs
  src/Features/Core/Portable/CommentSelection/CommentSelectionInfo.cs
  src/Features/Core/Portable/CommentSelection/ICommentSelectionService.cs
  src/Features/Core/Portable/ConvertAutoPropertyToFullProperty/AbstractConvertAutoPropertyToFullPropertyCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertForEachToFor/AbstractConvertForEachToForCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertForToForEach/AbstractConvertForToForEachCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertLinq/AbstractConvertLinqQueryToForEachProvider.cs
  src/Features/Core/Portable/ConvertLinq/ConvertForEachToLinqQuery/AbstractConvertForEachToLinqQueryProvider.cs
  src/Features/Core/Portable/ConvertLinq/ConvertForEachToLinqQuery/ExtendedSyntaxNode.cs
  src/Features/Core/Portable/ConvertLinq/ConvertForEachToLinqQuery/IConverter.cs
  src/Features/Core/Portable/ConvertNumericLiteral/AbstractConvertNumericLiteralCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs
  src/Features/Core/Portable/ConvertTupleToStruct/AbstractConvertTupleToStructCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertTupleToStruct/DocumentToUpdate.cs
  src/Features/Core/Portable/ConvertTupleToStruct/IConvertTupleToStructCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertTupleToStruct/IRemoteConvertTupleToStructCodeRefactoringService.cs
  src/Features/Core/Portable/ConvertTupleToStruct/Scope.cs
  src/Features/Core/Portable/DocumentHighlighting/AbstractDocumentHighlightsService.cs
  src/Features/Core/Portable/DocumentHighlighting/IDocumentHighlightsService.cs
  src/Features/Core/Portable/DocumentHighlighting/IRemoteDocumentHighlightsService.cs
  src/Features/Core/Portable/GenerateConstructorFromMembers/AbstractGenerateConstructorFromMembersCodeRefactoringProvider.ConstructorDelegatingCodeAction.cs
  src/Features/Core/Portable/GenerateConstructorFromMembers/AbstractGenerateConstructorFromMembersCodeRefactoringProvider.FieldDelegatingCodeAction.cs
  src/Features/Core/Portable/GenerateConstructorFromMembers/AbstractGenerateConstructorFromMembersCodeRefactoringProvider.State.cs
  src/Features/Core/Portable/GenerateDefaultConstructors/GenerateDefaultConstructorsCodeRefactoringProvider.cs
  src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/AbstractGenerateEqualsAndGetHashCodeService.cs
  src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/FormatLargeBinaryExpressionRule.cs
  src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/IGenerateEqualsAndGetHashCodeService.cs
  src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/IGenerateEqualsAndGetHashCodeServiceExtensions.cs
  src/Features/Core/Portable/GenerateFromMembers/AbstractGenerateFromMembersCodeRefactoringProvider.SelectedMemberInfo.cs
  src/Features/Core/Portable/GenerateFromMembers/AbstractGenerateFromMembersCodeRefactoringProvider.cs
  src/Features/Core/Portable/GenerateOverrides/GenerateOverridesCodeRefactoringProvider.cs
  src/Features/Core/Portable/InitializeParameter/AbstractAddParameterCheckCodeRefactoringProvider.cs
  src/Features/Core/Portable/InlineTemporary/AbstractInlineTemporaryCodeRefactoringProvider.cs
  src/Features/Core/Portable/IntroduceUsingStatement/AbstractIntroduceUsingStatementCodeRefactoringProvider.cs
  src/Features/Core/Portable/InvertConditional/AbstractInvertConditionalCodeRefactoringProvider.cs
  src/Features/Core/Portable/MakeMemberStatic/AbstractMakeMemberStaticCodeFixProvider.cs
  src/Features/Core/Portable/MoveDeclarationNearReference/AbstractMoveDeclarationNearReferenceCodeRefactoringProvider.cs
  src/Features/Core/Portable/NameTupleElement/AbstractNameTupleElementCodeRefactoringProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ISymbolExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFactsExtensions.cs
Labels: Area-IDE

#53289 Use separate equivalence keys for pattern matching fixes.
  src/Analyzers/CSharp/CodeFixes/UsePatternMatching/CSharpAsAndNullCheckCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UsePatternMatching/CSharpIsAndCastCheckCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UsePatternMatching/CSharpUseNotPatternCodeFixProvider.cs
  src/Features/CSharp/Portable/UsePatternCombinators/CSharpUsePatternCombinatorsCodeFixProvider.cs
  src/Features/CSharp/Portable/UsePatternMatching/CSharpIsAndCastCheckWithoutNameCodeFixProvider.cs
Labels: Area-IDE

#53281 Improve far multi-targetting grouping for one more case.
  src/VisualStudio/Core/Def/Implementation/FindReferences/Contexts/WithReferencesFindUsagesContext.cs
Labels: Area-IDE

#53288 Use the `not` pattern
  src/Analyzers/Core/Analyzers/ConvertTypeofToNameof/AbstractConvertTypeOfToNameOfDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/PopulateSwitch/AbstractPopulateSwitchDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/PopulateSwitch/PopulateSwitchStatementHelpers.cs
  src/Analyzers/Core/Analyzers/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseAutoProperty/AbstractUseAutoPropertyAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseCoalesceExpression/AbstractUseCoalesceExpressionForNullableDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/AbstractObjectCreationExpressionAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/ObjectCreationExpressionAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseCompoundAssignment/AbstractUseCompoundAssignmentDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseConditionalExpression/AbstractUseConditionalExpressionDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseConditionalExpression/ForReturn/UseConditionalExpressionForReturnHelpers.cs
  src/Analyzers/Core/Analyzers/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseObjectInitializer/ObjectCreationExpressionAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseSystemHashCode/Analyzer.cs
  src/Analyzers/Core/Analyzers/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs
  src/Analyzers/Core/CodeFixes/ConvertAnonymousTypeToTuple/AbstractConvertAnonymousTypeToTupleCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseConditionalExpression/ForAssignment/AbstractUseConditionalExpressionForAssignmentCodeFixProvider.cs
  src/Features/Core/Portable/CodeFixes/CodeFixService.cs
  src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.State.cs
  src/Features/Core/Portable/Common/AbstractProjectExtensionProvider`2.cs
  src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/AbstractPartialTypeCompletionProvider.cs
  src/Features/Core/Portable/ConvertIfToSwitch/AbstractConvertIfToSwitchCodeRefactoringProvider.Analyzer.cs
  src/Features/Core/Portable/Diagnostics/AbstractHostDiagnosticUpdateSource.cs
  src/Features/Core/Portable/Diagnostics/AnalyzerHelper.cs
  src/Features/Core/Portable/Diagnostics/BuildToolId.cs
  src/Features/Core/Portable/Diagnostics/DefaultDiagnosticAnalyzerService.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs
  src/Features/Core/Portable/Diagnostics/LiveDiagnosticUpdateArgsId.cs
  src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Features/Core/Portable/Formatting/FormattingDiagnosticAnalyzer.cs
  src/Features/Core/Portable/GenerateType/AbstractGenerateTypeService.State.cs
  src/Features/Core/Portable/ImplementAbstractClass/ImplementAbstractClassData.cs
  src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.cs
  src/Features/Core/Portable/MetadataAsSource/SymbolMappingServiceFactory.cs
  src/Features/Core/Portable/PreferFrameworkType/PreferFrameworkTypeDiagnosticAnalyzerBase.cs
  src/Features/Core/Portable/ReplaceMethodWithProperty/ReplaceMethodWithPropertyCodeRefactoringProvider.cs
  src/Features/Core/Portable/SimplifyThisOrMe/AbstractSimplifyThisOrMeDiagnosticAnalyzer.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.IncrementalAnalyzerProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.cs
  src/Features/Core/Portable/SplitOrMergeIfStatements/Nested/AbstractMergeNestedIfStatementsCodeRefactoringProvider.cs
  src/Features/Core/Portable/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs
  src/Features/Core/Portable/Wrapping/BinaryExpression/AbstractBinaryExpressionWrapper.cs
Labels: Area-IDE

#53082 Extended property patterns: IOperation and Symbols
  src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs
  src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/BoundTree/BoundSubpattern.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncSpillTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IIsPatternExpression.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTestBase.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests5.cs
Labels: Area-Compilers, Community

#53181 Use segmented dictionaries in SyntaxNodeExtensions.CurrentNodes
  src/Compilers/Core/Portable/Syntax/SyntaxNodeExtensions_Tracking.cs
Labels: Approved to merge, Area-Compilers

#53267 Backporting fixes to dev16.11
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/OverrideCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/TypeImportCompletionProviderTests.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CommitManager.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CompletionSource.cs
  src/EditorFeatures/TestUtilities/Completion/AbstractCompletionProviderTests.cs
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/SuggestionModeCompletionProviderTests.vb
  src/Features/CSharp/Portable/Completion/CompletionProviders/OperatorsAndIndexer/UnnamedSymbolCompletionProvider.cs
  src/Features/Core/Portable/Completion/CompletionProvider.cs
  src/Features/Core/Portable/Completion/CompletionService.cs
  src/Features/Core/Portable/Completion/CompletionServiceOptions.cs
  src/Features/Core/Portable/Completion/CompletionServiceWithProviders.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractExtensionMethodImportCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractImportCompletionProvider.cs
  src/Features/Core/Portable/SpellCheck/AbstractSpellCheckCodeFixProvider.cs
  src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandler.cs
  src/Tools/ExternalAccess/OmniSharp/Completion/OmniSharpCompletionService.cs
Labels: Approved to merge, Area-IDE

#52756 Pool background threads used for trampolines
  src/Compilers/Core/Portable/Serialization/ObjectReader.cs
  src/Compilers/Core/Portable/Serialization/ObjectWriter.cs
  src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
Labels: Approved to merge, Area-Compilers

#53205 Fix NavBars for TS (aka: TypeScript and F# are different languages).
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptNavigationBarItemService.cs
Labels: Approved to merge, Area-IDE

#53320 Add missing AspNetCoreKey
  eng/targets/Settings.props
Labels: Area-Infrastructure

#53279 Update LSP tooltips to better support markdown
  src/EditorFeatures/Core/Implementation/IntelliSense/Helpers.cs
  src/Features/Core/Portable/Common/TaggedText.cs
  src/Features/Core/Portable/Common/TextTags.cs
  src/Features/Core/Portable/LanguageServices/SymbolDisplayService/AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.cs
  src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/Features/LanguageServer/Protocol/Handler/Completion/CompletionResolveHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Hover/HoverHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionResolveTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Hover/HoverTests.cs
Labels: Area-IDE, LSP

#53324 Fix collapse to definitions for top-level statements
  src/EditorFeatures/CSharpTest/Structure/BlockSyntaxStructureTests.cs
  src/Features/CSharp/Portable/Structure/Providers/BlockSyntaxStructureProvider.cs
Labels: Area-IDE, Community

#53334 Update version for 16.10 preview 4
  eng/Versions.props
Labels: Area-Infrastructure

#53253 Bugfixes for the OmniSharp ExternalAcces layer
  src/Features/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.Features.csproj
  src/Tools/ExternalAccess/OmniSharp/Internal/PickMembers/OmniSharpPickMembersService.cs
Labels: Approved to merge, Area-IDE

#53364 Update VSSDK.BuildTools version
  eng/Versions.props
Labels: Area-Infrastructure

#53360 Use dotnet certificate
  eng/Signing.props
Labels: Area-Infrastructure

#53347 Fix Razor rename issue by returning a minimal diff
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Tools/ExternalAccess/Razor/RazorSpanMappingServiceWrapper.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/Core/Def/Implementation/Venus/ContainedDocument.DocumentServiceProvider.cs
  src/VisualStudio/Core/Test/Venus/DocumentService_IntegrationTests.vb
  src/Workspaces/Core/Portable/Workspace/Host/DocumentService/AbstractSpanMappingService.cs
  src/Workspaces/Core/Portable/Workspace/Host/DocumentService/ISpanMappingService.cs
  src/Workspaces/CoreTestUtilities/TestDocumentServiceProvider.cs
Labels: Area-IDE

#53365 Update SDK.BuildTool version
  eng/Versions.props
Labels: Area-Infrastructure

#53262 Move from calling Create to calling a specific constructor
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_InterpolatedString.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/BoundTree/InterpolatedStringHandlerData.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StringInterpolation.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/Portable/SynthesizedLocalKind.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/Core/Portable/WellKnownTypes.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
Labels: Area-Compilers

#53379 Add endpoint for public semantic tokens LSP API
  src/Features/LanguageServer/Protocol/LanguageServerTarget.cs
Labels: Area-IDE, LSP

#53369 Update vssdk version
  eng/Versions.props
Labels: Area-Infrastructure

#53378 Reduce nestingLevel in EndToEndTests.DeeplyNestedGeneric
  src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs
Labels: Approved to merge, Area-Compilers

#53394 Disable flaky tests
  src/Interactive/HostTest/InteractiveHostCoreTests.cs
  src/Interactive/HostTest/InteractiveHostDesktopTests.cs
Labels: Area-Infrastructure

#50270 Remove block on editing switch expressions
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueClosureTests.cs
  src/Compilers/CSharp/Test/Emit/PDB/PDBLambdaTests.cs
  src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/ActiveStatementTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/StatementEditingTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/StatementMatchingTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/TopLevelEditingTests.cs
  src/Features/CSharp/Portable/EditAndContinue/CSharpEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueDiagnosticDescriptors.cs
  src/Features/Core/Portable/EditAndContinue/RudeEditKind.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
Labels: Area-Compilers

#53399 Move off of the legacy IVsPackageInstallerServices.IsPackageInstalled API.
  src/VisualStudio/Core/Def/Packaging/PackageInstallerServiceFactory.cs
  src/VisualStudio/Core/Def/Packaging/PackageInstallerServiceFactory_UndoRedo.cs
Labels: Area-IDE

#53395 Package update for dev17
  eng/Versions.props
  eng/config/OptProf.json
  src/ExpressionEvaluator/Package/ExpressionEvaluatorPackage.csproj
  src/VisualStudio/Core/Def/Implementation/DebuggerIntelliSense/DebuggerTextView.cs
Labels: Area-Infrastructure

#53338 Correctly find enum members in case labels
  src/EditorFeatures/Test/Extensions/ISemanticSnapshotExtensionTests.cs
  src/EditorFeatures/Test/SymbolFinder/FindSymbolAtPositionTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SemanticFacts/CSharpSemanticFacts.cs
Labels: Approved to merge, Area-IDE

#52989 EnC - Support record structs
  src/EditorFeatures/CSharpTest/EditAndContinue/CSharpEditAndContinueAnalyzerTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/TopLevelEditingTests.cs
  src/Features/CSharp/Portable/CSharpFeaturesResources.resx
  src/Features/CSharp/Portable/EditAndContinue/CSharpEditAndContinueAnalyzer.cs
  src/Features/CSharp/Portable/EditAndContinue/SyntaxComparer.cs
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.cs.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.de.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.es.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.fr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.it.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ja.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ko.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pl.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pt-BR.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ru.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.tr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hans.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hant.xlf
Labels: Area-Interactive

#53380 Don't attempt to edit source generated files during rename
  src/EditorFeatures/Test2/Rename/CSharp/SourceGeneratorTests.vb
  src/EditorFeatures/Test2/Rename/RenameEngineResult.vb
  src/Workspaces/Core/Portable/Rename/RenameLocation.ReferenceProcessing.cs
Labels: Approved to merge, Area-IDE

#53381 Fix OOP tests around Find References and Rename
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.FieldSymbols.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.IndexerSymbols.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.LabelSymbols.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.LocalFunctions.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.NamedTypeSymbols.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.OperatorSymbols.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.OrdinaryMethodSymbols.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.ParameterSymbol.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.PropertySymbols.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.RangeVariableSymbol.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.Tuples.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.XmlDocSymbols.vb
  src/EditorFeatures/Test2/Rename/RenameEngineResult.vb
  src/Workspaces/Core/Portable/Remote/RemoteArguments.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService_Asset.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService_Reference.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemoteHostClientProvider.cs
  src/Workspaces/CoreTestUtilities/Remote/TestSerializerService.cs
  src/Workspaces/CoreTestUtilities/TestGeneratorReference.cs
Labels: Approved to merge, Area-IDE

#53412 Preserve trailing trivia on open brace
  src/Analyzers/CSharp/CodeFixes/ConvertSwitchStatementToExpression/ConvertSwitchStatementToExpressionCodeFixProvider.Rewriter.cs
  src/Analyzers/CSharp/Tests/ConvertSwitchStatementToExpression/ConvertSwitchStatementToExpressionTests.cs
Labels: Area-IDE

#53393 Add support for abstract `==`/`!=` operators in interfaces.
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/BinaryOperatorOverloadResolution.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbolBase.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
Labels: Area-Compilers, New Feature - StaticAbstractMembersInInterfaces

#53425 Item with prefix causes out of range exception
  src/Features/LanguageServer/Protocol/Handler/Completion/CompletionResolveHandler.cs
Labels: Area-IDE

#53427 Have add-using respect EditorBrowsable attributes.
  src/EditorFeatures/CSharpTest/AddUsing/AddUsingTests.cs
  src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs
  src/Features/Core/Portable/AddImport/SymbolReferenceFinder.cs
Labels: Area-IDE

#53435 Fix out of memory exception in SyntaxEditor
  src/Workspaces/Core/Portable/Editing/SyntaxEditor.cs
Labels: Approved to merge, Area-IDE

#53441 Fix IDE0047: discard pattern parentheses
  src/Analyzers/CSharp/Tests/RemoveUnnecessaryParentheses/RemoveUnnecessaryPatternParenthesesTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs
Labels: Area-IDE

#53327 Fix typo: Carrage -> Carriage
  src/VisualStudio/Core/Def/EditorConfigSettings/Formatting/ViewModel/NewLineViewModel.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
Labels: Approved to merge, Area-IDE, Community

#53416 Fix dead test code
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs
Labels: Area-Compilers, Community

#53414 Keep trailing trivia so single line if statements don't get badly formatted
  src/Analyzers/CSharp/CodeFixes/InvokeDelegateWithConditionalAccess/InvokeDelegateWithConditionalAccessCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/InvokeDelegateWithConditionalAccess/InvokeDelegateWithConditionalAccessTests.cs
Labels: Area-IDE

#53432 Update to P2
  eng/Versions.props
  eng/config/PublishData.json
Labels: Area-Infrastructure

#49154 Don't generate nullable type when applying value type with unconstrained nullable generic
  src/EditorFeatures/CSharpTest/ImplementAbstractClass/ImplementAbstractClassTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ITypeSymbolExtensions.TypeSyntaxGeneratorVisitor.cs
Labels: Area-IDE, Community

#53424 Update integration tests for Visual Studio 2022
  src/VisualStudio/IntegrationTest/TestSetup/Microsoft.VisualStudio.IntegrationTest.Setup.csproj
  src/VisualStudio/IntegrationTest/TestSetup/source.extension.vsixmanifest
  src/VisualStudio/IntegrationTest/TestUtilities/App.config
  src/VisualStudio/IntegrationTest/TestUtilities/Settings.Designer.cs
  src/VisualStudio/IntegrationTest/TestUtilities/Settings.settings
  src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs
Labels: Area-Infrastructure

#53457 Update PublishData.json
  eng/config/PublishData.json
Labels: Area-Infrastructure

#53280 Extended property patterns: main IDE scenarios
  src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/NotKeywordRecommenderTests.cs
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.AccessorSymbols.vb
  src/EditorFeatures/Test2/GoToDefinition/CSharpGoToDefinitionTests.vb
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Features/CSharp/Portable/Completion/CompletionProviders/PropertySubPatternCompletionProvider.cs
  src/Workspaces/CSharpTest/Formatting/FormattingTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/TokenBasedFormattingRule.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs
Labels: Area-IDE, New Language Feature - Pattern Matching

#53465 Revert an error in PublishData.json
  eng/config/PublishData.json
Labels: Area-Infrastructure

#53217 EnC - Tell the debugger about updated type def tokens
  src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/EmitHelpers.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/AssemblyReferencesTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueStateMachineTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/LocalSlotMappingTests.cs
  src/Compilers/Core/Portable/Compilation/Compilation.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/DeltaMetadataWriter.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/EmitDifferenceResult.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Test/Core/Compilation/CompilationDifference.cs
  src/Compilers/Test/Core/Compilation/CompilationExtensions.cs
  src/Compilers/Test/Core/Metadata/MetadataReaderUtils.cs
  src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb
  src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/EmitHelpers.vb
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
Labels: Area-Compilers

#53471 Don't do partial ngen for codelens
  src/VisualStudio/CodeLens/Microsoft.VisualStudio.LanguageServices.CodeLens.csproj
Labels: Area-Infrastructure

#53406 Remove unnecessary property
  eng/targets/Imports.targets
Labels: Area-Infrastructure

#53326 Fix syntax normalizer to add space around before colon in constructor initializer
  src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs
  src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
Labels: Area-Compilers, Community

#53429 Adjust doc comment for NullableWalker.VisitConversion
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
Labels: Area-Compilers, Documentation, New Language Feature - Nullable Reference Types

#53420 Update Compiler Test Plan.md
  docs/contributing/Compiler Test Plan.md
Labels: Area-Compilers, Documentation

#53480 Pass the updated type tokens to the debugger
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
Labels: Area-IDE

#53102 Refactor automation object and add missing options.
  src/VisualStudio/CSharp/Impl/Options/AutomationObject.cs
  src/VisualStudio/CSharp/Impl/Options/AutomationObject/AutomationObject.BraceCompletion.cs
  src/VisualStudio/CSharp/Impl/Options/AutomationObject/AutomationObject.Completion.cs
  src/VisualStudio/CSharp/Impl/Options/AutomationObject/AutomationObject.DocumentationComment.cs
  src/VisualStudio/CSharp/Impl/Options/AutomationObject/AutomationObject.ExtractMethod.cs
  src/VisualStudio/CSharp/Impl/Options/AutomationObject/AutomationObject.Formatting.cs
  src/VisualStudio/CSharp/Impl/Options/AutomationObject/AutomationObject.Generation.cs
  src/VisualStudio/CSharp/Impl/Options/AutomationObject/AutomationObject.Naming.cs
  src/VisualStudio/CSharp/Impl/Options/AutomationObject/AutomationObject.ObsoleteAndUnused.cs
  src/VisualStudio/CSharp/Impl/Options/AutomationObject/AutomationObject.OnOff.cs
  src/VisualStudio/CSharp/Impl/Options/AutomationObject/AutomationObject.Style.cs
  src/VisualStudio/CSharp/Impl/Options/AutomationObject/AutomationObject.SymbolSearch.cs
  src/VisualStudio/CSharp/Impl/Options/AutomationObject/AutomationObject.cs
  src/VisualStudio/Core/Impl/Options/AbstractAutomationObject.cs
  src/VisualStudio/VisualBasic/Impl/Microsoft.VisualStudio.LanguageServices.VisualBasic.vbproj
  src/VisualStudio/VisualBasic/Impl/Options/AutomationObject.vb
  src/VisualStudio/VisualBasic/Impl/Options/AutomationObject/AutomationObject.Completion.vb
  src/VisualStudio/VisualBasic/Impl/Options/AutomationObject/AutomationObject.DocumentationComment.vb
  src/VisualStudio/VisualBasic/Impl/Options/AutomationObject/AutomationObject.ExtractMethod.vb
  src/VisualStudio/VisualBasic/Impl/Options/AutomationObject/AutomationObject.Generation.vb
  src/VisualStudio/VisualBasic/Impl/Options/AutomationObject/AutomationObject.Obsolete.vb
  src/VisualStudio/VisualBasic/Impl/Options/AutomationObject/AutomationObject.OnOff.vb
  src/VisualStudio/VisualBasic/Impl/Options/AutomationObject/AutomationObject.Style.vb
  src/VisualStudio/VisualBasic/Impl/Options/AutomationObject/AutomationObject.SymbolSearch.vb
  src/VisualStudio/VisualBasic/Impl/Options/AutomationObject/AutomationObject.vb
Labels: Area-IDE, Community

#53477 Update InteractiveWindow version
  eng/Versions.props
Labels: Area-Infrastructure

#53495 Fix out of bound crash in lsp navto.
  src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/Features/LanguageServer/Protocol/Handler/Definitions/AbstractGoToDefinitionHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Symbols/WorkspaceSymbolsHandler.cs
Labels: Area-IDE

#53492 Update interop versions
  eng/Versions.props
  src/EditorFeatures/CSharpTest/Microsoft.CodeAnalysis.CSharp.EditorFeatures.UnitTests.csproj
  src/EditorFeatures/Test/Microsoft.CodeAnalysis.EditorFeatures.UnitTests.csproj
  src/EditorFeatures/Test2/Microsoft.CodeAnalysis.EditorFeatures2.UnitTests.vbproj
  src/EditorFeatures/TestUtilities/Microsoft.CodeAnalysis.EditorFeatures.Test.Utilities.csproj
  src/EditorFeatures/TestUtilities2/Microsoft.CodeAnalysis.EditorFeatures.Test.Utilities2.vbproj
  src/EditorFeatures/VisualBasicTest/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.UnitTests.vbproj
  src/Tools/ExternalAccess/FSharpTest/Microsoft.CodeAnalysis.ExternalAccess.FSharp.UnitTests.csproj
  src/VisualStudio/Core/Impl/Microsoft.VisualStudio.LanguageServices.Implementation.csproj
  src/VisualStudio/Core/Test.Next/Roslyn.VisualStudio.Next.UnitTests.csproj
  src/VisualStudio/Core/Test/Microsoft.VisualStudio.LanguageServices.UnitTests.vbproj
  src/VisualStudio/IntegrationTest/TestUtilities/Microsoft.VisualStudio.IntegrationTest.Utilities.csproj
  src/VisualStudio/LiveShare/Impl/Microsoft.VisualStudio.LanguageServices.LiveShare.csproj
  src/VisualStudio/TestUtilities2/Microsoft.VisualStudio.LanguageServices.Test.Utilities2.vbproj
  src/VisualStudio/Xaml/Impl/Microsoft.VisualStudio.LanguageServices.Xaml.csproj
Labels: Area-Infrastructure

#53383 State Table Cleanup
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/StateTableTests.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorAdaptor.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorState.cs
  src/Compilers/Core/Portable/SourceGeneration/IncrementalContexts.cs
  src/Compilers/Core/Portable/SourceGeneration/IncrementalGeneratorSyntaxWalker.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/BatchTransformNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/DriverStateTable.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/ISyntaxInputNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/IncrementalValueSources.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/InputNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/JoinNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SourceOutputNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxInputNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxReceiverInputNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxTransformNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueSources.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/TransformNode.cs
  src/Compilers/Test/Core/SourceGeneration/LambdaComparer.cs
Labels: Area-Compilers, New Feature - Source Generators

#53494 Only require telemetry validation in CI
  eng/build.ps1
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/VisualStudio_InProc_Telemetry.cs
  src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstance.cs
Labels: Area-Infrastructure

#53498 Revert changes to TypeScriptWaitContext wrappers
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/VSTypeScriptWaitContextWrapper.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/VSTypeScriptWaitIndicatorWrapper.cs
Labels: Area-IDE

#53434 Enable declaration of conversion operators in interfaces.
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedConversionSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbolBase.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs
Labels: Area-Compilers, New Feature - StaticAbstractMembersInInterfaces

#53500 Port 'Fix out of bound crash in lsp navto' to dev 16.11
  src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/Features/LanguageServer/Protocol/Handler/Definitions/AbstractGoToDefinitionHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Symbols/WorkspaceSymbolsHandler.cs
Labels: Approved to merge, Area-IDE

#53485 Fix locked comment
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
Labels: Area-IDE, Community

#53504 Update contrib documentation
  docs/contributing/Building, Debugging, and Testing on Windows.md
Labels: Area-Infrastructure

#53487 Fix global state corruption in EditorConfig UI
  src/EditorFeatures/CSharpTest/EditorConfigSettings/Updater/SettingsUpdaterTests.TestAnalyzerConfigOptions.cs
  src/EditorFeatures/CSharpTest/EditorConfigSettings/Updater/SettingsUpdaterTests.cs
  src/EditorFeatures/Core/EditorConfigSettings/Data/AnalyzerSetting.cs
  src/EditorFeatures/Core/EditorConfigSettings/Data/CodeStyle/CodeStyleSetting.BooleanCodeStyleSetting.cs
  src/EditorFeatures/Core/EditorConfigSettings/Data/CodeStyle/CodeStyleSetting.EnumCodeStyleSetting.cs
  src/EditorFeatures/Core/EditorConfigSettings/Data/CodeStyle/CodeStyleSetting.PerLanguageBooleanCodeStyleSetting.cs
  src/EditorFeatures/Core/EditorConfigSettings/Data/CodeStyle/CodeStyleSetting.PerLanguageEnumCodeStyleSetting.cs
  src/EditorFeatures/Core/EditorConfigSettings/Data/Formatting/FormattingSetting`1.cs
  src/EditorFeatures/Core/EditorConfigSettings/Data/Formatting/PerLanguageFormattingSetting.cs
  src/EditorFeatures/Core/EditorConfigSettings/Updater/ISettingUpdater.cs
  src/EditorFeatures/Core/EditorConfigSettings/Updater/SettingsUpdaterBase.cs
  src/EditorFeatures/Test/EditorConfigSettings/Data/CodeStyleSettingsTest.cs
  src/Workspaces/Core/Portable/CodeStyle/CodeStyleOption.cs
  src/Workspaces/Core/Portable/CodeStyle/CodeStyleOption2_operators.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/CodeStyleOption2`1.cs
Labels: Approved to merge, Area-IDE

#53001 Maintain the same parse option when add symbol to destination
  src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpCodeGenerationHelpers.cs
  src/Workspaces/Core/Portable/CodeGeneration/AbstractCodeGenerationService.cs
Labels: Area-IDE

#53513 Only generate build number on first run
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#53371 Check the workspace supports ApplyChangesKind.ChangeDocumentInfo
  src/Analyzers/Core/CodeFixes/MatchFolderAndNamespace/AbstractChangeNamespaceToMatchFolderCodeFixProvider.cs
Labels: Area-IDE

#53206 Add progress bar to the top of value tracking
  src/EditorFeatures/Core/ValueTracking/ValueTrackingService.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/ValueTracking/ComputingTreeViewItem.cs
  src/VisualStudio/Core/Def/ValueTracking/TreeItemViewModel.cs
  src/VisualStudio/Core/Def/ValueTracking/TreeViewItemBase.cs
  src/VisualStudio/Core/Def/ValueTracking/ValueTrackedTreeItemViewModel.cs
  src/VisualStudio/Core/Def/ValueTracking/ValueTrackingCommandHandler.cs
  src/VisualStudio/Core/Def/ValueTracking/ValueTrackingToolWindow.cs
  src/VisualStudio/Core/Def/ValueTracking/ValueTrackingTree.xaml
  src/VisualStudio/Core/Def/ValueTracking/ValueTrackingTree.xaml.cs
  src/VisualStudio/Core/Def/ValueTracking/ValueTrackingTreeViewModel.cs
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
Labels: Area-IDE, Feature - IDE Value Tracking

#53530 Fix dnceng build by forcing the use of xcopy msbuild
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#53517 VS SDK update
  eng/Versions.props
Labels: Area-Infrastructure

#53544 Ensure no navbar IO on the UI thread
  src/EditorFeatures/Core/Implementation/NavigationBar/NavigationBarController_ModelComputation.cs
Labels: Approved to merge, Area-IDE

#53538 Report diagnostic on correct node
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IArrayElementReferenceExpression.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/IndexAndRangeTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/AddExplicitCast/AddExplicitCastTests.cs
Labels: Area-Compilers, Community

#53529 Add support for implementations of interface static abstract user-defined conversions in classes and structures
  src/Compilers/CSharp/Portable/Binder/BinderFactory.BinderFactoryVisitor.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/OperatorFacts.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs
  src/Compilers/CSharp/Portable/Declarations/DeclarationTreeBuilder.cs
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Members.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedConversionSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbolBase.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
Labels: Area-Compilers, New Feature - StaticAbstractMembersInInterfaces

#53248 Allow `with` on anonymous types
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_WithExpression.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectCreationExpression.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs
  src/Compilers/Core/Portable/Operations/CaptureId.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Test/Core/Compilation/ControlFlowGraphVerifier.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs
Labels: Area-Compilers, Area-IDE, New Language Feature - Records

#53584 Add searchbox in generate overrides dialog
  src/VisualStudio/Core/Def/Implementation/PickMembers/PickMembersDialog.xaml
  src/VisualStudio/Core/Def/Implementation/PickMembers/PickMembersDialog.xaml.cs
  src/VisualStudio/Core/Def/Implementation/PickMembers/PickMembersDialogViewModel.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicGenerateConstructorDialog.cs
Labels: Area-IDE

#53463 Report obsoletion diagnostics for slice and indexer
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs
Labels: Area-Compilers, Community, New Language Feature - Range

#53511 Update BenchmarkDotNet to 0.13.0
  eng/Versions.props
Labels: Area-Infrastructure

#53520 Expose a way to call into C#/VB quick info providers directly, bypassing the workspace.
  src/Features/CSharp/Portable/QuickInfo/CSharpDiagnosticAnalyzerQuickInfoProvider.cs
  src/Features/CSharp/Portable/QuickInfo/CSharpSyntacticQuickInfoProvider.cs
  src/Features/Core/Portable/QuickInfo/CommonQuickInfoContext.cs
  src/Features/Core/Portable/QuickInfo/CommonQuickInfoProvider.cs
  src/Features/Core/Portable/QuickInfo/CommonSemanticQuickInfoProvider.cs
  src/Features/Core/Portable/QuickInfo/QuickInfoServiceWithProviders.cs
  src/Features/VisualBasic/Portable/QuickInfo/VisualBasicSemanticQuickInfoProvider.vb
Labels: Area-IDE

#53447 Introduce resx for BuildValidator and MS.CA.Rebuild to allow localization
  src/Compilers/Core/Rebuild/CompilationFactory.cs
  src/Compilers/Core/Rebuild/CompilationOptionsReader.cs
  src/Compilers/Core/Rebuild/Extensions.cs
  src/Compilers/Core/Rebuild/MetadataCompilationOptions.cs
  src/Compilers/Core/Rebuild/Microsoft.CodeAnalysis.Rebuild.csproj
  src/Compilers/Core/Rebuild/RebuildResources.resx
  src/Compilers/Core/Rebuild/VisualBasicCompilationFactory.cs
  src/Compilers/Core/Rebuild/xlf/RebuildResources.cs.xlf
  src/Compilers/Core/Rebuild/xlf/RebuildResources.de.xlf
  src/Compilers/Core/Rebuild/xlf/RebuildResources.es.xlf
  src/Compilers/Core/Rebuild/xlf/RebuildResources.fr.xlf
  src/Compilers/Core/Rebuild/xlf/RebuildResources.it.xlf
  src/Compilers/Core/Rebuild/xlf/RebuildResources.ja.xlf
  src/Compilers/Core/Rebuild/xlf/RebuildResources.ko.xlf
  src/Compilers/Core/Rebuild/xlf/RebuildResources.pl.xlf
  src/Compilers/Core/Rebuild/xlf/RebuildResources.pt-BR.xlf
  src/Compilers/Core/Rebuild/xlf/RebuildResources.ru.xlf
  src/Compilers/Core/Rebuild/xlf/RebuildResources.tr.xlf
  src/Compilers/Core/Rebuild/xlf/RebuildResources.zh-Hans.xlf
  src/Compilers/Core/Rebuild/xlf/RebuildResources.zh-Hant.xlf
  src/Tools/BuildValidator/BuildValidator.csproj
  src/Tools/BuildValidator/BuildValidatorResources.resx
  src/Tools/BuildValidator/IldasmUtilities.cs
  src/Tools/BuildValidator/Program.cs
  src/Tools/BuildValidator/xlf/BuildValidatorResources.cs.xlf
  src/Tools/BuildValidator/xlf/BuildValidatorResources.de.xlf
  src/Tools/BuildValidator/xlf/BuildValidatorResources.es.xlf
  src/Tools/BuildValidator/xlf/BuildValidatorResources.fr.xlf
  src/Tools/BuildValidator/xlf/BuildValidatorResources.it.xlf
  src/Tools/BuildValidator/xlf/BuildValidatorResources.ja.xlf
  src/Tools/BuildValidator/xlf/BuildValidatorResources.ko.xlf
  src/Tools/BuildValidator/xlf/BuildValidatorResources.pl.xlf
  src/Tools/BuildValidator/xlf/BuildValidatorResources.pt-BR.xlf
  src/Tools/BuildValidator/xlf/BuildValidatorResources.ru.xlf
  src/Tools/BuildValidator/xlf/BuildValidatorResources.tr.xlf
  src/Tools/BuildValidator/xlf/BuildValidatorResources.zh-Hans.xlf
  src/Tools/BuildValidator/xlf/BuildValidatorResources.zh-Hant.xlf
Labels: Area-Compilers

#53598 Merge release/dev16.9 to release/dev16.9-vs-deps
  azure-pipelines-official.yml
Labels: auto-merge

#53606 Merge release/dev16.9-vs-deps to release/dev16.10-vs-deps
  azure-pipelines-official.yml
Labels: Area-Infrastructure, auto-merge

#53543 Update Building, Debugging, and Testing on Windows.md
  docs/contributing/Building, Debugging, and Testing on Windows.md
Labels: Area-Infrastructure

#53634 Display 'readonly' for record structs
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Types.cs
  src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
Labels: Area-Compilers

#53614 Remove SyntaxKind.DataKeyword
  src/Compilers/CSharp/Portable/Declarations/DeclarationModifiers.cs
  src/Compilers/CSharp/Portable/Generated/CSharp.Generated.g4
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Symbols/Source/ModifierUtils.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxKindFacts.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ClassKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/StructKeywordRecommenderTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/RecordKeywordRecommender.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTreeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs
Labels: Area-Compilers

#53643 Keep casts when necessary to prefer a constant pattern over a type pattern
  src/Analyzers/CSharp/Analyzers/RemoveUnnecessaryParentheses/CSharpRemoveUnnecessaryExpressionParenthesesDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/RemoveUnnecessaryParentheses/CSharpRemoveUnnecessaryPatternParenthesesDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryParentheses/CSharpRemoveUnnecessaryParenthesesCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/RemoveUnnecessaryParentheses/RemoveUnnecessaryExpressionParenthesesTests.cs
  src/Analyzers/Core/Analyzers/RemoveUnnecessaryParentheses/AbstractRemoveUnnecessaryParenthesesDiagnosticAnalyzer.cs
  src/Analyzers/Core/CodeFixes/RemoveUnnecessaryParentheses/AbstractRemoveUnnecessaryParenthesesCodeFixProvider.cs
  src/Analyzers/VisualBasic/Analyzers/RemoveUnnecessaryParentheses/VisualBasicRemoveUnnecessaryParenthesesDiagnosticAnalyzer.vb
  src/Analyzers/VisualBasic/CodeFixes/RemoveUnnecessaryParentheses/VisualBasicRemoveUnnecessaryParenthesesCodeFixProvider.vb
  src/Workspaces/CSharp/Portable/Simplification/Reducers/CSharpParenthesizedExpressionReducer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs
Labels: Area-IDE

#53510 Correctly disable OK button in pull members dialog
  src/VisualStudio/Core/Def/Implementation/PullMemberUp/MainDialog/PullMemberUpDialogViewModel.cs
  src/VisualStudio/Core/Test/PullMemberUp/PullMemberUpViewModelTest.vb
Labels: Area-IDE, Community

#53645 Update comment
  src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs
Labels: Area-Compilers, Community

#50222 Move IEditorFormattingService to the Features layer
  src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/VSTypeScriptEditorFormattingServiceWrapper.cs
  src/EditorFeatures/Core/Implementation/Formatting/FormatCommandHandler.FormatDocument.cs
  src/EditorFeatures/Core/Implementation/Formatting/FormatCommandHandler.FormatSelection.cs
  src/EditorFeatures/Core/Implementation/Formatting/FormatCommandHandler.Paste.cs
  src/EditorFeatures/Core/Implementation/Formatting/FormatCommandHandler.cs
  src/EditorFeatures/Core/Implementation/Formatting/IEditorFormattingService.cs
  src/EditorFeatures/Core/Implementation/Indentation/EditorLayerInferredIndentationService.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CommitManager.cs
  src/EditorFeatures/Core/Shared/Extensions/InferredIndentationExtensions.cs
  src/EditorFeatures/Core/Shared/Options/FeatureOnOffOptions.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/EditorFeatures/VisualBasic/LineCommit/CommitCommandHandler.vb
  src/EditorFeatures/VisualBasic/LineCommit/CommitFormatter.vb
  src/EditorFeatures/VisualBasicTest/LineCommit/CommitTestData.vb
  src/Features/CSharp/Portable/Formatting/CSharpFormattingInteractionService.PasteFormattingRule.cs
  src/Features/CSharp/Portable/Formatting/CSharpFormattingInteractionService.cs
  src/Features/CSharp/Portable/Formatting/TypingFormattingRule.cs
  src/Features/Core/Portable/Formatting/IFormattingInterationService.cs
  src/Features/LanguageServer/Protocol/Handler/Formatting/AbstractFormatDocumentHandlerBase.cs
  src/Features/LanguageServer/Protocol/Handler/Formatting/FormatDocumentOnTypeHandler.cs
  src/Tools/ExternalAccess/FSharp/Internal/Editor/FSharpEditorFormattingService.cs
  src/VisualStudio/CSharp/Impl/Options/AutomationObject/AutomationObject.Formatting.cs
  src/VisualStudio/CSharp/Impl/Options/AutomationObject/AutomationObject.OnOff.cs
  src/VisualStudio/CSharp/Impl/Options/Formatting/FormattingOptionPageControl.xaml.cs
  src/VisualStudio/VisualBasic/Impl/Options/AutomationObject/AutomationObject.Formatting.vb
  src/VisualStudio/VisualBasic/Impl/Options/AutomationObject/AutomationObject.OnOff.vb
  src/Workspaces/Core/Portable/Indentation/DefaultInferredIndentationService.cs
  src/Workspaces/Core/Portable/Indentation/IInferredIndentationService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/FormattingOptions2.cs
Labels: Area-IDE

#53630 Move language version check for syntax node action to compilation start
  src/Analyzers/CSharp/Analyzers/MakeLocalFunctionStatic/MakeLocalFunctionStaticDiagnosticAnalyzer.cs
Labels: Area-IDE

#53633 AddAccessibilityModifiers: record struct support
  src/Analyzers/CSharp/Analyzers/AddAccessibilityModifiers/CSharpAddAccessibilityModifiersDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/AddAccessibilityModifiers/AddAccessibilityModifiersTests.cs
Labels: Area-IDE

#53662 Move initial part of LSP loading off the UI thread.
  src/VisualStudio/Core/Def/Implementation/LanguageClient/AlwaysActiveLanguageClientEventListener.cs
Labels: Area-IDE
