Repository dotnet/roslyn, pull requests merged in 2021-09, with the labels that each got.

#56048 Update version for preview 5
  eng/Versions.props
Labels: Area-Infrastructure

#55905 Track duplicate hintNames as they are added
  src/Compilers/CSharp/Portable/SourceGeneration/CSharpGeneratorDriver.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/AdditionalSourcesCollectionTests.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs
  src/Compilers/Core/Portable/SourceGeneration/AdditionalSourcesCollection.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorAdaptor.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorContexts.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs
  src/Compilers/Core/Portable/SourceGeneration/IncrementalContexts.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SourceOutputNode.cs
  src/Compilers/VisualBasic/Portable/SourceGeneration/VisualBasicGeneratorDriver.vb
Labels: Bug, Area-Compilers, New Feature - Source Generators

#56067 Remove OneLoc job from dev16.11
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#56063 Update OneLoc build branch
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#56021 esnure path to global config file is correctly cased
  src/CodeStyle/Tools/Program.cs
Labels: Area-Infrastructure

#56029 Instrumenting flaky TupleWithElementNamedWithDefaultName
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs
Labels: Area-Compilers, Test

#56078 Update publish data for P4 and change main to draft until VS snaps
  eng/config/PublishData.json
Labels: Area-Infrastructure

#56082 Remove use of WaitAndGetResult from FAR
  src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs
  src/Features/Core/Portable/ChangeSignature/DelegateInvokeMethodReferenceFinder.cs
Labels: Area-IDE

#56084 remove WaitAndGetResult from Preview generation code.
  src/EditorFeatures/CSharpTest/CodeActions/Preview/PreviewTests.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActions/SuggestedAction.cs
  src/EditorFeatures/Core/Implementation/CodeActions/CodeActionEditHandlerService.cs
  src/EditorFeatures/Core/Implementation/CodeRefactorings/ICodeActionEditHandlerService.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/AbstractCodeActionOrUserDiagnosticTest_TestAddDocument.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/AbstractCodeActionTest.cs
  src/EditorFeatures/VisualBasicTest/CodeActions/Preview/PreviewTests.vb
Labels: Area-IDE

#56079 remove WaitAndGetResult calls from tests
  src/EditorFeatures/Test2/Diagnostics/DiagnosticServiceTests.vb
Labels: Area-IDE

#56080 Remove deprecated indentation APIs.
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/VSTypeScriptIndentationResultWrapper.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/VSTypeScriptIndentationServiceWrapper.cs
  src/EditorFeatures/Core/Implementation/SmartIndent/IIndentationService.cs
  src/EditorFeatures/Core/Implementation/SmartIndent/SmartIndent.cs
Labels: Area-IDE

#56077 Track duplicate hintNames as they are added (#55905)
  src/Compilers/CSharp/Portable/SourceGeneration/CSharpGeneratorDriver.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/AdditionalSourcesCollectionTests.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs
  src/Compilers/Core/Portable/SourceGeneration/AdditionalSourcesCollection.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorAdaptor.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorContexts.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs
  src/Compilers/Core/Portable/SourceGeneration/IncrementalContexts.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SourceOutputNode.cs
  src/Compilers/VisualBasic/Portable/SourceGeneration/VisualBasicGeneratorDriver.vb
Labels: Area-Compilers

#55991 Report and catch error on renaming
  src/EditorFeatures/Core.Wpf/InlineRename/CommandHandlers/RenameCommandHandler.cs
  src/EditorFeatures/Core/Implementation/InlineRename/CommandHandlers/AbstractRenameCommandHandler_ReturnHandler.cs
Labels: Area-IDE, Community

#56103 Remove file health indicator from preview
  src/VisualStudio/Core/Def/Implementation/Preview/PreviewEngine.cs
Labels: Area-IDE

#56081 Avoid blocking wait in lsif generator.
  src/Features/Lsif/Generator/Generator.cs
  src/Features/Lsif/Generator/Program.cs
  src/Features/Lsif/GeneratorTest/Utilities/TestLsifOutput.vb
Labels: Area-IDE

#56091 NRT enable our analzyers lib.
  src/Analyzers/CSharp/Analyzers/ConvertNamespace/ConvertToBlockScopedNamespaceDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/ConvertNamespace/ConvertToFileScopedNamespaceDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseIsNullCheck/CSharpUseIsNullCheckForCastAndEqualityOperatorDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UsePatternCombinators/CSharpUsePatternCombinatorsDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/AbstractCodeQualityDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/AbstractParenthesesDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/AddRequiredParentheses/AbstractAddRequiredParenthesesDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/AddRequiredParentheses/AddRequiredParenthesesConstants.cs
  src/Analyzers/Core/Analyzers/Helpers/DeserializationConstructorCheck.cs
  src/Analyzers/Core/Analyzers/Helpers/DiagnosticHelper.cs
  src/Analyzers/Core/Analyzers/IDEDiagnosticIdToOptionMappingHelper.cs
  src/Analyzers/Core/Analyzers/IDEDiagnosticIds.cs
  src/Analyzers/Core/Analyzers/NamingStyle/NamingStyleDiagnosticAnalyzerBase.cs
  src/Analyzers/Core/Analyzers/OrderModifiers/AbstractOrderModifiersDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/OrderModifiers/OrderModifiersHelpers.cs
  src/Analyzers/Core/Analyzers/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/RemoveUnnecessaryImports/AbstractRemoveUnnecessaryImportsDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs
  src/Analyzers/Core/Analyzers/SimplifyBooleanExpression/AbstractSimplifyConditionalDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/SimplifyInterpolation/AbstractSimplifyInterpolationDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/ObjectCreationExpressionAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseCompoundAssignment/AbstractUseCompoundAssignmentDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseCompoundAssignment/UseCompoundAssignmentUtilities.cs
  src/Analyzers/Core/Analyzers/UseConditionalExpression/ForAssignment/AbstractUseConditionalExpressionForAssignmentDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseExplicitTupleName/UseExplicitTupleNameDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseInferredMemberName/AbstractUseInferredMemberNameDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseIsNullCheck/AbstractUseIsNullForReferenceEqualsDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseIsNullCheck/UseIsNullConstants.cs
  src/Analyzers/Core/Analyzers/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseSystemHashCode/UseSystemHashCodeDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs
  src/Features/Core/Portable/AddConstructorParametersFromMembers/AddConstructorParametersFromMembersCodeRefactoringProvider.State.cs
  src/Features/Core/Portable/SimplifyThisOrMe/AbstractSimplifyThisOrMeDiagnosticAnalyzer.cs
  src/Features/Core/Portable/SimplifyTypeNames/SimplifyTypeNamesDiagnosticAnalyzerBase.cs
Labels: Area-IDE

#56104 Share classification format types with VS Mac
  src/EditorFeatures/Core.Cocoa/Microsoft.CodeAnalysis.EditorFeatures.Cocoa.csproj
  src/EditorFeatures/Core.Cocoa/RoslynClassificationFormatDefinitions.cs
  src/EditorFeatures/Core.Wpf/Classification/ClassificationTypeFormatDefinitions.cs
  src/EditorFeatures/Core.Wpf/EditorFeaturesWpfResources.resx
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.cs.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.de.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.es.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.fr.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.it.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ja.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ko.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.pl.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.pt-BR.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ru.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.tr.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.zh-Hans.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.zh-Hant.xlf
  src/EditorFeatures/Core/EditorFeaturesResources.resx
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.cs.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.de.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.es.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.fr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.it.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ja.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ko.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pl.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pt-BR.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ru.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.tr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hans.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hant.xlf
Labels: Area-IDE

#56090 Disallow converting a lambda with attributes to an expression tree.
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs
Labels: Area-Compilers, New Feature - Lambda Improvements

#56015 Remove obsolete APIs
  src/VisualStudio/Core/Def/Implementation/Watson/WatsonReporter.cs
  src/Workspaces/Core/Portable/ExternalAccess/Pythia/Api/PythiaRemoteHostClient.cs
  src/Workspaces/Core/Portable/Remote/RemoteServiceName.cs
  src/Workspaces/Core/Portable/Remote/WellKnownServiceHubService.cs
  src/Workspaces/Remote/Core/ExternalAccess/Pythia/Api/PythiaRemoteHostClient.cs
  src/Workspaces/Remote/ServiceHub/ExternalAccess/Pythia/Api/PythiaServiceBase.cs
Labels: Area-IDE

#55964 Merge Move Static Members feature to 17.1
  src/Compilers/Test/Core/Traits/Traits.cs
  src/EditorFeatures/CSharpTest/MoveStaticMembers/CSharpMoveStaticMembersTests.cs
  src/EditorFeatures/TestUtilities/MoveStaticMembers/TestMoveStaticMembersService.cs
  src/EditorFeatures/VisualBasicTest/MoveStaticMembers/VisualBasicMoveStaticMembersTests.vb
  src/Features/CSharp/Portable/CodeRefactorings/MoveStaticMembers/CSharpMoveStaticMembersRefactoringProvider.cs
  src/Features/Core/Portable/CodeRefactorings/PredefinedCodeRefactoringProviderNames.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/MoveStaticMembers/AbstractMoveStaticMembersRefactoringProvider.cs
  src/Features/Core/Portable/MoveStaticMembers/IMoveStaticMembersOptionsService.cs
  src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersOptions.cs
  src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs
  src/Features/Core/Portable/PullMemberUp/MembersPuller.cs
  src/Features/Core/Portable/Shared/Utilities/ExtractTypeHelpers.cs
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Features/VisualBasic/Portable/CodeRefactorings/MoveStaticMembers/VisualBasicMoveStaticMembersRefactoringProvider.vb
  src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb
  src/VisualStudio/Core/Def/Implementation/MoveStaticMembers/MoveStaticMembersDialog.xaml
  src/VisualStudio/Core/Def/Implementation/MoveStaticMembers/MoveStaticMembersDialog.xaml.cs
  src/VisualStudio/Core/Def/Implementation/MoveStaticMembers/MoveStaticMembersDialogViewModel.cs
  src/VisualStudio/Core/Def/Implementation/MoveStaticMembers/StaticMemberSelection.xaml
  src/VisualStudio/Core/Def/Implementation/MoveStaticMembers/StaticMemberSelection.xaml.cs
  src/VisualStudio/Core/Def/Implementation/MoveStaticMembers/StaticMemberSelectionViewModel.cs
  src/VisualStudio/Core/Def/Implementation/MoveStaticMembers/VisualStudioMoveStaticMembersOptionsService.cs
  src/VisualStudio/Core/Def/Implementation/PullMemberUp/SymbolDependentsBuilder.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/Core/Test/MoveStaticMembers/MoveStaticMembersViewModelTest.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE, New Feature - Move Static Members

#53175 Disable severity combobox for non-configurable rules
  src/EditorFeatures/Core/EditorConfigSettings/Data/AnalyzerSetting.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/Analyzers/View/SeverityControl.xaml.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
Labels: Area-IDE, Community, Needs Shiproom Approval

#55963 Move compiler test ref assemblies to NuPkg
  eng/Versions.props
  src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/CorLibrary/CorTypes.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Retargeting/NoPia.cs
  src/Compilers/Core/CodeAnalysisTest/Analyzers/AnalyzerFileReferenceAppDomainTests.cs
  src/Compilers/Core/CodeAnalysisTest/CorLibTypesTests.cs
  src/Compilers/Core/RebuildTest/RebuildCommandLineTests.cs
  src/Compilers/Server/VBCSCompilerTests/AnalyzerConsistencyCheckerTests.cs
  src/Compilers/Server/VBCSCompilerTests/CompilerServerTests.cs
  src/Compilers/Test/Core/AssemblyLoadTestFixture.cs
  src/Compilers/Test/Core/Generate.ps1
  src/Compilers/Test/Core/Generated.cs
  src/Compilers/Test/Core/Generated.targets
  src/Compilers/Test/Core/Microsoft.CodeAnalysis.Test.Utilities.csproj
  src/Compilers/Test/Core/Platform/Desktop/TestHelpers.cs
  src/Compilers/Test/Core/TargetFrameworkUtil.cs
  src/Compilers/Test/Core/TestBase.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/AttributeTests_UnmanagedCallersOnly.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/CorLibrary/CorTypes.vb
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace_XmlConsumption.cs
Labels: Area-Compilers

#56073 Obsolete Solution.GetIsolatedSolution
  src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.GeneratedFileReplacingCompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.ICompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
Labels: Area-IDE

#56130 MoveStatic Members: Remove nullable suppression
  src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs
Labels: Area-IDE

#56122 Delete unused UnitTesting API
  src/VisualStudio/Core/Def/ExternalAccess/UnitTesting/Api/UnitTestingRemoteHostOptionsAccessor.cs
Labels: Area-IDE

#56124 Wait for the workspace to be initialized
  src/VisualStudio/Core/Def/EditorConfigSettings/SettingsEditorPane.cs
Labels: Area-IDE

#56112 Minor cleanup
  src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs
  src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.cs
Labels: Area-Compilers

#56128 Only attempt to show the settings from the workspace if the editorcon…
  src/VisualStudio/Core/Def/EditorConfigSettings/SettingsEditorFactory.cs
Labels: Area-IDE

#56134 Remove dead code in the compilation tracker.
  src/EditorFeatures/Test2/Compilation/CompilationTests.vb
  src/Workspaces/Core/Portable/Workspace/Solution/Project.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.GeneratedFileReplacingCompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.ICompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
Labels: Area-IDE

#56140 Remove legacy progression search
  src/VisualStudio/Core/Def/Implementation/Progression/GraphQueries/SearchGraphQuery.cs
  src/VisualStudio/Core/Def/Implementation/Progression/ProgressionOptions.cs
  src/VisualStudio/Core/Def/Implementation/Progression/ProgressionOptionsProvider.cs
  src/VisualStudio/Core/Test/Progression/SearchGraphQueryTests.vb
  src/VisualStudio/Core/Test/Progression/SearchGraphQueryTests_NavigateTo.vb
Labels: Area-IDE

#55781 Inline Hints: Option to suppress hints where the parameter name and argument name are the same
  src/EditorFeatures/Core/InlineHints/InlineHintsDataTaggerProvider.cs
  src/Features/CSharp/Portable/InlineHints/CSharpInlineParameterNameHintsService.cs
  src/Features/Core/Portable/InlineHints/AbstractInlineParameterNameHintsService.cs
  src/Features/Core/Portable/InlineHints/InlineHintsOptions.cs
  src/Features/VisualBasic/Portable/InlineHints/VisualBasicInlineParameterNameHintsService.vb
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageStrings.vb
Labels: Area-IDE

#55892 Source generators/timing
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/StateTableTests.cs
  src/Compilers/Core/Portable/CodeAnalysisEventSource.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriverState.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorState.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorTimerExtensions.cs
  src/Compilers/Core/Portable/SourceGeneration/RunResults.cs
Labels: Area-Compilers, New Feature - Source Generators

#56156 Wire up the feature flag properly for opening source generated files
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs
Labels: Area-IDE

#56154 Remove unused ServiceComponentOnOffOptions.DiagnosticProvider
  src/EditorFeatures/Core/Implementation/Diagnostics/DiagnosticsClassificationTaggerProvider.cs
  src/EditorFeatures/Core/Implementation/Diagnostics/DiagnosticsSquiggleTaggerProvider.cs
  src/EditorFeatures/Core/Implementation/Diagnostics/DiagnosticsSuggestionTaggerProvider.cs
  src/EditorFeatures/Test2/Diagnostics/DiagnosticProviderTests.vb
  src/Features/Core/Portable/Diagnostics/DefaultDiagnosticAnalyzerService.cs
  src/Features/Core/Portable/Diagnostics/DiagnosticAnalyzerService_IncrementalAnalyzer.cs
  src/Features/Core/Portable/Shared/Options/ServiceComponentOnOffOptions.cs
  src/Features/Core/Portable/Shared/Options/ServiceComponentOnOffOptionsProvider.cs
Labels: Area-IDE

#55686 Options refactoring
  src/EditorFeatures/Core/Implementation/EditorLayerExtensionManager.cs
  src/VisualStudio/Core/Def/Experimentation/IExperiment.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/StreamingFindUsagesPresenter.cs
  src/VisualStudio/Core/Def/Implementation/InfoBar/VisualStudioInfoBarService.cs
  src/VisualStudio/Core/Def/Implementation/InfoBar/VisualStudioInfoBarWorkspaceService.cs
  src/VisualStudio/Core/Def/Implementation/KeybindingReset/KeybindingResetDetector.cs
  src/VisualStudio/Core/Def/Implementation/KeybindingReset/KeybindingResetOptions.cs
  src/VisualStudio/Core/Def/Implementation/KeybindingReset/KeybindingsResetLogger.cs
  src/VisualStudio/Core/Def/Implementation/KeybindingReset/ReSharperStatus.cs
  src/VisualStudio/Core/Def/RoslynPackage.cs
  src/Workspaces/Core/Portable/Options/GlobalOptionService.cs
  src/Workspaces/Core/Portable/Options/IGlobalOptionService.cs
  src/Workspaces/Core/Portable/Options/OptionChangedEventArgs.cs
  src/Workspaces/CoreTest/Host/WorkspaceServices/TestOptionService.cs
  src/Workspaces/CoreTest/WorkspaceServiceTests/OptionServiceTests.cs
Labels: Area-IDE

#56045 Don't reference VS Shell binaries in EditorFeatures.Wpf
  src/EditorFeatures/Core.Wpf/CodeAnalysisColors.cs
  src/EditorFeatures/Core.Wpf/InlineRename/Dashboard/Dashboard.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/Dashboard/DashboardAdornmentManager.cs
  src/EditorFeatures/Core.Wpf/InlineRename/Dashboard/DashboardAdornmentProvider.cs
  src/EditorFeatures/Core.Wpf/InlineRename/Dashboard/DashboardColors.cs
  src/EditorFeatures/Core.Wpf/InlineRename/Dashboard/DashboardColors.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/Dashboard/IDashboardColorUpdater.cs
  src/EditorFeatures/Core.Wpf/Microsoft.CodeAnalysis.EditorFeatures.Wpf.csproj
  src/VisualStudio/Core/Def/Implementation/InlineRename/DashboardColorUpdater.cs
Labels: Area-IDE

#50536 Change 'convert anonymous type to tuple' into a refactoring
  src/Analyzers/CSharp/Analyzers/CSharpAnalyzers.projitems
  src/Analyzers/CSharp/Analyzers/ConvertAnonymousTypeToTuple/CSharpConvertAnonymousTypeToTupleDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/CSharpCodeFixes.projitems
  src/Analyzers/CSharp/Tests/CSharpAnalyzers.UnitTests.projitems
  src/Analyzers/Core/Analyzers/Analyzers.projitems
  src/Analyzers/Core/Analyzers/AnalyzersResources.resx
  src/Analyzers/Core/Analyzers/ConvertAnonymousTypeToTuple/AbstractConvertAnonymousTypeToTupleDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/IDEDiagnosticIds.cs
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.cs.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.de.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.es.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.fr.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.it.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.ja.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.ko.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.pl.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.pt-BR.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.ru.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.tr.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.zh-Hans.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.zh-Hant.xlf
  src/Analyzers/Core/CodeFixes/CodeFixes.projitems
  src/Analyzers/Core/CodeFixes/ConvertAnonymousTypeToTuple/AbstractConvertAnonymousTypeToTupleCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/PredefinedCodeFixProviderNames.cs
  src/Analyzers/VisualBasic/Analyzers/ConvertAnonymousTypeToTuple/VisualBasicConvertAnonymousTypeToTupleDiagnosticAnalyzer.vb
  src/Analyzers/VisualBasic/Analyzers/VisualBasicAnalyzers.projitems
  src/Analyzers/VisualBasic/CodeFixes/VisualBasicCodeFixes.projitems
  src/Analyzers/VisualBasic/Tests/VisualBasicAnalyzers.UnitTests.projitems
  src/EditorFeatures/CSharpTest/ConvertAnonymousType/ConvertAnonymousTypeToClassTests.cs
  src/EditorFeatures/CSharpTest/ConvertAnonymousType/ConvertAnonymousTypeToTupleTests.cs
  src/EditorFeatures/Test/Diagnostics/IDEDiagnosticIDConfigurationTests.cs
  src/EditorFeatures/VisualBasicTest/ConvertAnonymousType/ConvertAnonymousTypeToClassTests.vb
  src/EditorFeatures/VisualBasicTest/ConvertAnonymousType/ConvertAnonymousTypeToTupleTests.vb
  src/Features/CSharp/Portable/ConvertAnonymousType/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/ConvertAnonymousType/CSharpConvertAnonymousTypeToTupleCodeRefactoringProvider.cs
  src/Features/Core/Portable/CodeRefactorings/PredefinedCodeRefactoringProviderNames.cs
  src/Features/Core/Portable/ConvertAnonymousType/AbstractConvertAnonymousTypeCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertAnonymousType/AbstractConvertAnonymousTypeToClassCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertAnonymousType/AbstractConvertAnonymousTypeToTupleCodeRefactoringProvider.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Features/VisualBasic/Portable/ConvertAnonymousType/VisualBasicConvertAnonymousTypeToClassCodeRefactoringProvider.vb
  src/Features/VisualBasic/Portable/ConvertAnonymousType/VisualBasicConvertAnonymousTypeToTupleCodeRefactoringProvider.vb
  src/Tools/ExternalAccess/Razor/RazorPredefinedCodeFixProviderNames.cs
Labels: Area-IDE

#56196 Fix await completion provider to handle non-"true" local function declarations
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_AwaitCompletion.vb
  src/Features/CSharp/Portable/Completion/CompletionProviders/AwaitCompletionProvider.cs
Labels: Area-IDE

#56215 New feature: Detect variable swaps and suggest using the new tuple-idiomatic-form if available.
  src/Analyzers/CSharp/Analyzers/CSharpAnalyzers.projitems
  src/Analyzers/CSharp/Analyzers/CSharpAnalyzersResources.resx
  src/Analyzers/CSharp/Analyzers/UseLocalFunction/CSharpUseLocalFunctionDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseTupleSwap/CSharpUseTupleSwapDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.cs.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.de.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.es.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.fr.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.it.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.ja.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.ko.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.pl.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.pt-BR.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.ru.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.tr.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.zh-Hans.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.zh-Hant.xlf
  src/Analyzers/CSharp/CodeFixes/CSharpCodeFixes.projitems
  src/Analyzers/CSharp/CodeFixes/UseTupleSwap/CSharpUseTupleSwapCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/CSharpAnalyzers.UnitTests.projitems
  src/Analyzers/CSharp/Tests/UseTupleSwap/UseTupleSwapTests.cs
  src/Analyzers/Core/Analyzers/EnforceOnBuildValues.cs
  src/Analyzers/Core/Analyzers/IDEDiagnosticIds.cs
  src/Analyzers/Core/CodeFixes/PredefinedCodeFixProviderNames.cs
  src/EditorFeatures/Test/Diagnostics/IDEDiagnosticIDConfigurationTests.cs
  src/VisualStudio/CSharp/Impl/Options/AutomationObject/AutomationObject.Style.cs
  src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/Core/Test/Options/CSharpEditorConfigGeneratorTests.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeStyle/CSharpCodeStyleOptions.cs
Labels: Area-IDE, Feature Request

#56089 More options refactoring
  src/EditorFeatures/Core/Implementation/SplitComment/SplitCommentCommandHandler.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.cs
  src/EditorFeatures/DiagnosticsTestUtilities/SplitComments/AbstractSplitCommentCommandHandlerTests.cs
  src/EditorFeatures/Test/Diagnostics/DiagnosticAnalyzerServiceTests.cs
  src/EditorFeatures/Test/EditAndContinue/RemoteEditAndContinueServiceTests.cs
  src/EditorFeatures/Test/Preview/PreviewWorkspaceTests.cs
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/EditorFeatures/TestUtilities/Squiggles/TestDiagnosticTagProducer.cs
  src/EditorFeatures/VisualBasicTest/ImplementInterface/ImplementInterfaceCommandHandlerTests.vb
  src/Features/Core/Portable/Diagnostics/DiagnosticModeExtensions.cs
  src/Features/Core/Portable/Diagnostics/DiagnosticService.cs
  src/Features/Core/Portable/Diagnostics/DiagnosticsUpdatedArgs.cs
  src/Features/LanguageServer/Protocol/CSharpVisualBasicLanguageServerFactory.cs
  src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandlerProvider.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/RequestContext.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs
  src/Features/LanguageServer/Protocol/LanguageServerTarget.cs
  src/Features/LanguageServer/ProtocolUnitTests/LanguageServerTargetTests.cs
  src/VisualStudio/Core/Def/Implementation/CallHierarchy/CallHierarchyDetail.cs
  src/VisualStudio/Core/Def/Implementation/CallHierarchy/CallHierarchyProvider.cs
  src/VisualStudio/Core/Def/Implementation/ColorSchemes/ColorSchemeApplier.Settings.cs
  src/VisualStudio/Core/Def/Implementation/ColorSchemes/ColorSchemeApplier.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/DocumentSpanEntry.cs
  src/VisualStudio/Core/Def/Implementation/KeybindingReset/KeybindingResetDetector.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/AbstractInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/AlwaysActivateInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/LiveShareInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/RazorInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/VisualStudioInProcLanguageServer.cs
  src/VisualStudio/Core/Def/Implementation/Remote/VisualStudioRemoteHostClientProvider.cs
  src/VisualStudio/Core/Def/Implementation/Remote/VisualStudioWorkspaceServiceHubConnector.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/AbstractTableEntriesSnapshot.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/MiscellaneousDiagnosticListTable.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/VisualStudioBaseDiagnosticListTable.LiveTableDataSource.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/VisualStudioDiagnosticListTable.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioWorkspaceStatusServiceFactory.cs
  src/VisualStudio/Core/Def/ValueTracking/TreeItemViewModel.cs
  src/VisualStudio/Core/Def/ValueTracking/ValueTrackedTreeItemViewModel.cs
  src/VisualStudio/Core/Test.Next/Remote/RemoteHostClientServiceFactoryTests.cs
  src/VisualStudio/Core/Test.Next/Services/LspDiagnosticsTests.cs
  src/VisualStudio/Core/Test/Diagnostics/DiagnosticTableDataSourceTests.vb
  src/VisualStudio/Core/Test/Diagnostics/ExternalDiagnosticUpdateSourceTests.vb
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioAnalyzerTests.vb
  src/VisualStudio/LiveShare/Impl/Client/RemoteDiagnosticListTable.cs
  src/VisualStudio/LiveShare/Impl/Client/RemoteLanguageServiceWorkspace.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageClient/XamlInProcLanguageClient.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageClient/XamlInProcLanguageClientDisableUX.cs
  src/Workspaces/Core/Portable/Options/IGlobalOptionService.cs
  src/Workspaces/CoreTest/WorkspaceServiceTests/OptionServiceTests.cs
  src/Workspaces/Remote/Core/RemoteHostOptions.cs
  src/Workspaces/Remote/Core/ServiceHubRemoteHostClient.cs
  src/Workspaces/Remote/Core/SolutionChecksumUpdater.cs
Labels: Area-IDE

#56187 Add External Access options for TypeScript
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/Api/VSTypeScriptOptions.cs
  src/Features/LanguageServer/Protocol/Extensions/Extensions.cs
  src/Tools/ExternalAccess/FSharp/Completion/FSharpCompletionOptions.cs
  src/VisualStudio/Core/Def/ExternalAccess/VSTypeScript/Api/VSTypeScriptContainedLanguageWrapper.cs
  src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractLanguageService`2.VsCodeWindowManager.cs
  src/VisualStudio/Core/Def/Implementation/Options/LanguageSettingsPersister.cs
Labels: Area-IDE

#56019 Add readme.md listing breaking changes doc chronologically
  docs/compilers/CSharp/readme.md
Labels: Area-Compilers, Documentation

#56173 Provide real implementation for RuntimeSupportsStaticAbstractMembersInInterfaces property.
  eng/Versions.props
  src/Compilers/CSharp/Portable/Symbols/AssemblySymbol.cs
  src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
  src/Compilers/Core/Portable/SpecialMember.cs
  src/Compilers/Core/Portable/SpecialMembers.cs
  src/Compilers/Test/Core/Microsoft.CodeAnalysis.Test.Utilities.csproj
  src/Compilers/Test/Core/TargetFrameworkUtil.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
  src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs
Labels: Area-Compilers, New Feature - StaticAbstractMembersInInterfaces

#56132 Remove the HasCompilation flag.
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.GeneratedFileReplacingCompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.ICompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
Labels: Area-IDE

#56189 Don't try to rename references in source generated files
  src/EditorFeatures/Test2/Rename/CSharp/SourceGeneratorTests.vb
  src/Workspaces/Core/Portable/Rename/RenameLocation.ReferenceProcessing.cs
Labels: Area-IDE

#56145 Native Int: constant folding is executed at runtime rather than compile-time if the result depends on the size of native integers
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/CodeGen/EmitOperators.cs
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Generated/ErrorFacts.Generated.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/NativeIntegerTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
Labels: Area-Compilers, New Language Feature - Native Int

#56188 Fix doubleclick for Value Tracking
  src/VisualStudio/Core/Def/ValueTracking/ValueTrackingTree.xaml
  src/VisualStudio/Core/Def/ValueTracking/ValueTrackingTree.xaml.cs
Labels: Area-IDE, Feature - IDE Value Tracking

#56223 Rework our netstandard1.3 test references
  eng/Versions.props
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/CommandLine/Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests.csproj
  src/Compilers/Test/Core/Mocks/TestReferences.cs
  src/Compilers/Test/Core/Platform/Desktop/TestHelpers.cs
  src/Compilers/Test/Core/TestBase.cs
  src/Scripting/CSharpTest/InteractiveSessionTests.cs
  src/Scripting/CoreTestUtilities/Microsoft.CodeAnalysis.Scripting.TestUtilities.csproj
  src/Scripting/CoreTestUtilities/TestCompilationFactory.cs
Labels: Area-Compilers

#56221 Avoid telemetry for unavoidable XmlException
  src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs
Labels: Area-IDE

#56227 Stop marking main-vs-deps insertion PR as draft
  eng/config/PublishData.json
Labels: Area-Infrastructure

#56252 Fix crash when comparing tuples in symbolequivalence
  src/EditorFeatures/Test/Utilities/SymbolEquivalenceComparerTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/SymbolEquivalenceComparer.EquivalenceVisitor.cs
Labels: Area-IDE

#56250 Flip driver cache from opt-out to opt-in
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs
Labels: Area-Compilers, New Feature - Source Generators

#56257 Null annotate IDocumentNavigationService
  src/EditorFeatures/Core.Wpf/Interactive/InteractiveDocumentNavigationService.cs
  src/EditorFeatures/Core/Extensibility/NavigationBar/AbstractEditorNavigationBarItemService.cs
  src/Features/Core/Portable/Navigation/DefaultDocumentNavigationService.cs
  src/Features/Core/Portable/Navigation/IDocumentNavigationService.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs
  src/VisualStudio/LiveShare/Test/MockDocumentNavigationServiceFactory.cs
Labels: Area-IDE

#56139 Remove declaration-only-compilation from CompilationTracker
  src/EditorFeatures/Test2/Compilation/CompilationTests.vb
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.InProcess.cs
  src/Workspaces/CSharp/Portable/FindSymbols/CSharpDeclaredSymbolInfoFactoryService.cs
  src/Workspaces/Core/Portable/FindSymbols/Declarations/DeclarationFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/DeclaredSymbolInfo.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Persistence.cs
  src/Workspaces/Core/Portable/LanguageServices/DeclaredSymbolFactoryService/AbstractDeclaredSymbolInfoFactoryService.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Project.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.CompilationTrackerState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.ICompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/VisualBasic/Portable/FindSymbols/VisualBasicDeclaredSymbolInfoFactoryService.vb
Labels: Area-IDE

#56265 Fix crash in FindReferences
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.OrdinaryMethodSymbols.vb
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.BidirectionalSymbolSet.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.SymbolSet.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.UnidirectionalSymbolSet.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/MetadataUnifyingSymbolHashSet.cs
Labels: Area-IDE

#56233 Include ref info for parameters > 16 in synthesized delegate type name
  src/Compilers/CSharp/Portable/Symbols/Synthesized/RefKindVector.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
Labels: Area-Compilers, New Feature - Lambda Improvements

#56258 Null annotate preview generation
  src/EditorFeatures/Core.Cocoa/Preview/PreviewFactoryService.cs
  src/EditorFeatures/Core.Wpf/Preview/PreviewFactoryService.cs
  src/EditorFeatures/Core/Implementation/CodeActions/CodeActionEditHandlerService.cs
  src/EditorFeatures/Core/Implementation/CodeActions/ICodeActionEditHandlerService.cs
  src/EditorFeatures/Core/Implementation/IPreviewFactoryService.cs
  src/EditorFeatures/Core/Implementation/SolutionChangeSummary.cs
  src/EditorFeatures/Core/Implementation/SolutionPreviewItem.cs
  src/EditorFeatures/Core/Implementation/SolutionPreviewResult.cs
  src/EditorFeatures/Core/Preview/AbstractPreviewFactoryService.cs
  src/Workspaces/Core/Portable/CodeActions/Operations/PreviewOperation.cs
Labels: Area-IDE

#56251 Expose C# formatting service to Razor via external access
  src/Tools/ExternalAccess/Razor/RazorCSharpFormattingInteractionService.cs
Labels: Area-IDE, LSP

#56266 Handle projects added during break state
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/Features/Core/Portable/EditAndContinue/CommittedSolution.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSession.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentStates.cs
Labels: Area-Interactive

#55472 Set analyzers `global_level` to `-99`.
  src/CodeStyle/Tools/Program.cs
Labels: Area-Infrastructure

#56273 Enable NRT in another project.
  src/Analyzers/CSharp/Analyzers/AddBraces/CSharpAddBracesDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/ConvertSwitchStatementToExpression/ConvertSwitchStatementToExpressionConstants.cs
  src/Analyzers/CSharp/Analyzers/ConvertSwitchStatementToExpression/ConvertSwitchStatementToExpressionDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/ConvertSwitchStatementToExpression/ConvertSwitchStatementToExpressionHelpers.cs
  src/Analyzers/CSharp/Analyzers/InvokeDelegateWithConditionalAccess/InvokeDelegateWithConditionalAccessAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/MakeStructFieldsWritable/CSharpMakeStructFieldsWritableDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/OrderModifiers/CSharpOrderModifiersDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/OrderModifiers/CSharpOrderModifiersHelper.cs
  src/Analyzers/CSharp/Analyzers/QualifyMemberAccess/CSharpQualifyMemberAccessDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/RemoveUnreachableCode/CSharpRemoveUnreachableCodeDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/RemoveUnreachableCode/RemoveUnreachableCodeHelpers.cs
  src/Analyzers/CSharp/Analyzers/RemoveUnusedMembers/CSharpRemoveUnusedMembersDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/RemoveUnusedParametersAndValues/CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/SimplifyBooleanExpression/CSharpSimplifyConditionalDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/SimplifyInterpolation/CSharpSimplifyInterpolationDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCompoundAssignment/CSharpUseCompoundCoalesceAssignmentDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForAssignmentDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseDeconstruction/CSharpUseDeconstructionDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseDefaultLiteral/CSharpUseDefaultLiteralDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseExpressionBody/UseExpressionBodyDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseImplicitOrExplicitType/CSharpTypeStyleDiagnosticAnalyzerBase.cs
  src/Analyzers/CSharp/Analyzers/UseImplicitOrExplicitType/CSharpUseExplicitTypeDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseImplicitOrExplicitType/CSharpUseImplicitTypeDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseIndexOperatorDiagnosticAnalyzer.InfoCache.cs
  src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseIndexOperatorDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.InfoCache.cs
  src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.Result.cs
  src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/Helpers.cs
  src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/MemberInfo.cs
  src/Analyzers/CSharp/Analyzers/UseLocalFunction/CSharpUseLocalFunctionDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseSimpleUsingStatement/UseSimpleUsingStatementDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseThrowExpression/CSharpUseThrowExpressionDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/UseIndexOrRangeOperator/CSharpUseRangeOperatorCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/AddRequiredParentheses/AddRequiredParenthesesCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/ConvertTypeOfToNameOf/AbstractConvertTypeOfToNameOfCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/NamingStyle/NamingStyleCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/OrderModifiers/AbstractOrderModifiersCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/QualifyMemberAccess/AbstractQualifyMemberAccessCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/RemoveRedundantEquality/RemoveRedundantEqualityCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/RemoveUnnecessaryImports/AbstractRemoveUnnecessaryImportsCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/RemoveUnnecessaryParentheses/AbstractRemoveUnnecessaryParenthesesCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/RemoveUnusedMembers/AbstractRemoveUnusedMembersCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UpdateLegacySuppressions/UpdateLegacySuppressionsCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseCoalesceExpression/UseCoalesceExpressionCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseCoalesceExpression/UseCoalesceExpressionForNullableCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseCollectionInitializer/AbstractUseCollectionInitializerCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseConditionalExpression/UseConditionalExpressionHelpers.cs
  src/Analyzers/Core/CodeFixes/UseExplicitTupleName/UseExplicitTupleNameCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseInferredMemberName/AbstractUseInferredMemberNameCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseIsNullCheck/AbstractUseIsNullForReferenceEqualsCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseObjectInitializer/AbstractUseObjectInitializerCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseThrowExpression/UseThrowExpressionCodeFixProvider.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/MetadataUnifyingSymbolHashSet.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/SemanticModelExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
Labels: Area-IDE

#56296 Increase the number of cases that 'use range operator' detects
  src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs
Labels: Area-IDE

#56255 Fix access violation when MemoryMappedFile is disposed
  src/Workspaces/Core/Portable/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs
Labels: Area-IDE

#56237 Options persistent storage
  src/EditorFeatures/Core.Wpf/InlineHints/InlineHintsTagger.cs
  src/EditorFeatures/Core.Wpf/Suggestions/AsyncSuggestedActionsSource.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSourceProvider.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SyncSuggestedActionsSource.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.SemanticChangeProcessor.cs
  src/Features/LanguageServer/Protocol/Handler/Rename/RenameHandler.cs
  src/Tools/AnalyzerRunner/PersistentStorageConfiguration.cs
  src/Tools/IdeBenchmarks/SQLitePersistentStorageBenchmark.cs
  src/Tools/IdeCoreBenchmarks/CloudCache/IdeCoreBenchmarksCloudCacheServiceProvider.cs
  src/Tools/IdeCoreBenchmarks/FindReferencesBenchmarks.cs
  src/Tools/IdeCoreBenchmarks/NavigateToBenchmarks.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/AbstractPersistentStorageTests.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/CloudCachePersistentStorageTests.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/Mocks/MockCloudCachePersistentStorageService.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/SQLiteV2PersistentStorageTests.cs
  src/VisualStudio/Core/Def/Storage/AbstractCloudCachePersistentStorageService.cs
  src/VisualStudio/Core/Def/Storage/VisualStudioCloudCacheStorageService.cs
  src/VisualStudio/Core/Def/Storage/VisualStudioCloudCacheStorageServiceFactory.cs
  src/VisualStudio/Core/Def/Storage/VisualStudioPersistentStorageLocationService.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/VisualStudioWorkspace_InProc.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Serialization.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Persistence.cs
  src/Workspaces/Core/Portable/Storage/AbstractPersistentStorageService.cs
  src/Workspaces/Core/Portable/Storage/CloudCache/ICloudCacheStorageServiceFactory.cs
  src/Workspaces/Core/Portable/Storage/DefaultPersistenceStorageServiceFactory.cs
  src/Workspaces/Core/Portable/Storage/SQLite/AbstractSQLitePersistentStorageService.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorageService.cs
  src/Workspaces/Core/Portable/Storage/StorageOptions.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/DefaultPersistentStorageServiceFactory.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/IChecksummedPersistentStorageService.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/IPersistentStorageConfiguration.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/NoOpPersistentStorage.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/NoOpPersistentStorageService.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/SolutionKey.cs
  src/Workspaces/CoreTest/Host/WorkspaceServices/TestPersistenceService.cs
  src/Workspaces/CoreTest/TestCompositionTests.cs
  src/Workspaces/Remote/ServiceHub/Host/Storage/RemoteCloudCacheStorageServiceFactory.cs
  src/Workspaces/Remote/ServiceHub/Host/Storage/RemotePersistentStorageLocationService.cs
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassificationCache/RemoteSemanticClassificationCacheService.cs
Labels: Area-IDE

#56218 Eliminate 75GB allocations during binding in a performance trace
  src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs
  src/Compilers/CSharp/Portable/Symbols/NamespaceOrTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/Core/Portable/Compilation/Compilation.cs
  src/Compilers/Core/Portable/Syntax/SyntaxNodeLocationComparer.cs
  src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb
  src/Compilers/VisualBasic/Portable/Symbols/LexicalSortKey.vb
Labels: Area-Compilers

#56275 Report syntax error from Hot Reload service
  src/EditorFeatures/Core/Implementation/EditAndContinue/ManagedEditAndContinueLanguageService.cs
  src/EditorFeatures/Core/Implementation/EditAndContinue/ManagedHotReloadLanguageService.cs
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/EditorFeatures/Test/EditAndContinue/EmitSolutionUpdateResultsTests.cs
  src/EditorFeatures/Test/EditAndContinue/RemoteEditAndContinueServiceTests.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSession.cs
  src/Features/Core/Portable/EditAndContinue/DocumentAnalysisResults.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueDiagnosticDescriptors.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/Core/Portable/EditAndContinue/EmitSolutionUpdateResults.cs
  src/Features/Core/Portable/EditAndContinue/Remote/RemoteDebuggingSessionProxy.cs
  src/Features/Core/Portable/EditAndContinue/SolutionUpdate.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Workspaces/Remote/ServiceHub/Services/EditAndContinue/RemoteEditAndContinueService.cs
Labels: Area-Interactive

#56310 Move semantic classification caching down to Editor layer
  src/EditorFeatures/Core/Implementation/Classification/SemanticClassificationUtilities.cs
  src/Features/Core/Portable/SemanticClassificationCache/SemanticClassificationCacheService.cs
  src/Features/Core/Portable/SemanticClassificationCache/SemanticClassificationCacheUtilities.cs
  src/Workspaces/Core/Portable/Classification/ISemanticClassificationCacheService.cs
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassificationCache/RemoteSemanticClassificationCacheService.cs
Labels: Area-IDE

#56320 Expose ServiceHub Core remote options to UnitTesing
  src/Workspaces/Remote/Core/ExternalAccess/UnitTesting/Api/UnitTestingRemoteHostClient.cs
Labels: Area-IDE

#56325 Workaround for XamlOptions loading regression
  src/VisualStudio/Core/Def/Implementation/Options/XamlOptions.cs
Labels: Area-IDE

#56143 Add vscode workspace settings to the gitignore
  .gitignore
Labels: Area-Infrastructure

#56326 Support find refs on global aliases.
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.AliasSymbols.vb
  src/EditorFeatures/VisualBasicTest/Diagnostics/AddImport/AddImportTests.vb
  src/Features/Core/Portable/AddImport/SymbolReferenceFinder.cs
  src/Features/Core/Portable/ChangeSignature/DelegateInvokeMethodReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractMemberScopedReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ConstructorInitializerSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ConstructorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/DestructorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/EventSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ExplicitConversionSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ExplicitInterfaceMethodReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/FieldSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/IReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/LabelSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/LocalSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/MethodTypeParameterSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamedTypeSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamespaceSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/OperatorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/OrdinaryMethodReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ParameterSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/PropertyAccessorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/PropertySymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/RangeVariableSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/TypeParameterSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Create.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Forwarders.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Persistence.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE

#56353 Update generate-compiler-code.ps1
  eng/generate-compiler-code.ps1
Labels: Area-Infrastructure

#56307 Read StorageOptions from solution snapshot.
  src/EditorFeatures/Core/Implementation/Classification/SemanticClassificationUtilities.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.InProcess.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.cs
  src/Features/Core/Portable/NavigateTo/IRemoteNavigateToSearchService.cs
  src/Features/Core/Portable/SemanticClassificationCache/SemanticClassificationCacheService.cs
  src/Features/Core/Portable/SemanticClassificationCache/SemanticClassificationCacheUtilities.cs
  src/Tools/AnalyzerRunner/PersistentStorageConfiguration.cs
  src/Tools/IdeBenchmarks/SQLitePersistentStorageBenchmark.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/AbstractPersistentStorageTests.cs
  src/VisualStudio/Core/Def/Storage/AbstractCloudCachePersistentStorageService.cs
  src/VisualStudio/Core/Def/Storage/CloudCachePersistentStorage.cs
  src/VisualStudio/Core/Def/Storage/ProjectContainerKeyCache.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/VisualStudioWorkspace_InProc.cs
  src/Workspaces/Core/Portable/Classification/IRemoteSemanticClassificationCacheService.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Metadata.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Serialization.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Source.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Persistence.cs
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
  src/Workspaces/Core/Portable/Storage/AbstractPersistentStorageService.cs
  src/Workspaces/Core/Portable/Storage/DefaultPersistenceStorageServiceFactory.cs
  src/Workspaces/Core/Portable/Storage/ISQLiteStorageServiceFactory.cs
  src/Workspaces/Core/Portable/Storage/LegacyPersistentStorageService.cs
  src/Workspaces/Core/Portable/Storage/PersistentStorageExtensions.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorageConstants.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorageService.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_DocumentIds.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_DocumentSerialization.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_ProjectIds.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_ProjectSerialization.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/AbstractPersistentStorage.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/DocumentKey.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/IChecksummedPersistentStorage.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/IChecksummedPersistentStorageService.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/IPersistentStorageConfiguration.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/IPersistentStorageService.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/NoOpPersistentStorage.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/NoOpPersistentStorageService.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/ProjectKey.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/SolutionKey.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs
  src/Workspaces/Remote/ServiceHub/Services/NavigateToSearch/RemoteNavigateToSearchService.cs
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassificationCache/RemoteSemanticClassificationCacheService.cs
Labels: Area-IDE

#56350 Remove ErrorTypeException from native int decoder
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/NativeIntegerTypeDecoder.cs
Labels: Area-Compilers

#56365 Don't restrict allowed values
  src/VisualStudio/CSharp/Impl/Options/AutomationObject/AutomationObject.Formatting.cs
Labels: Area-IDE

#56359 Introduce Parameter Priority
  src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceParameterService.cs
Labels: Area-IDE

#56378 Add missing using directive
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Persistence.cs
Labels: Area-IDE

#56293 Control exposure of tuple fields
  src/Compilers/CSharp/Portable/FlowAnalysis/LocalDataFlowPass.cs
  src/Compilers/CSharp/Portable/Symbols/ErrorTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/SubstitutedNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPrintMembers.cs
  src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs
Labels: Area-Compilers

#56366 Update P4 packages
  eng/Versions.props
Labels: Area-Infrastructure

#56200 Support implicit conversions of lambda expressions to LambdaExpression
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
Labels: Area-Compilers, New Feature - Lambda Improvements

#56236 Infer delegate type from lambda expression with explicit return statements without expressions
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
Labels: Area-Compilers, New Feature - Lambda Improvements

#56321 Fix equals operator with split state on right
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs
  src/Compilers/CSharp/Test/Semantic/FlowAnalysis/FlowTests.cs
Labels: Area-Compilers

#56383 Force tpl antecedent work to run asynchronously to prevent stack overflows
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
Labels: Area-IDE

#55395 Remove redundant check in `IsGlobalMain`
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
Labels: Area-Interactive, Community

#56393 Add test to cover pointer to unmanaged T pattern matching
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs
Labels: Area-Compilers

#55913 Add ISymbol.MetadataToken
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEAssemblySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEEventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEFieldSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEPropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PETypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/PreprocessingSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/Symbol.cs
  src/Compilers/CSharp/Portable/Symbols/Symbol.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Metadata/PE/LoadingMetadataTokens.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Core/Portable/Symbols/ISymbol.cs
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEAssemblySymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEEventSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEFieldSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEMethodSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEParameterSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEPropertySymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PETypeParameterSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Symbol.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Metadata/PE/LoadingMetadataTokens.vb
  src/Features/Core/Portable/MetadataAsSource/AbstractMetadataAsSourceService.AbstractWrappedSymbol.cs
  src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationSymbol.cs
Labels: Area-Compilers

#56387 Add service for all functions related to FileBanners today in SyntaxFacts
  src/Analyzers/CSharp/CodeFixes/MisplacedUsingDirectives/MisplacedUsingDirectivesCodeFixProvider.cs
  src/Features/CSharp/Portable/AddImport/CSharpAddImportFeatureService.cs
  src/Features/CSharp/Portable/ConvertToInterpolatedString/CSharpConvertPlaceholderToInterpolatedStringRefactoringProvider.cs
  src/Features/CSharp/Portable/Structure/Providers/DocumentationCommentStructureProvider.cs
  src/Features/Core/Portable/AddFileBanner/AbstractAddFileBannerCodeRefactoringProvider.cs
  src/Features/Core/Portable/AddFileBanner/AbstractAddFileBannerNewDocumentFormattingProvider.cs
  src/Features/Core/Portable/AddImport/SymbolReferenceFinder.cs
  src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.MoveTypeEditor.cs
  src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs
  src/Features/Core/Portable/EmbeddedLanguages/DateAndTime/LanguageServices/DateAndTimePatternDetector.cs
  src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceParameterDocumentRewriter.cs
  src/Features/Core/Portable/UseAutoProperty/AbstractUseAutoPropertyCodeFixProvider.cs
  src/Features/VisualBasic/Portable/ConvertToInterpolatedString/VisualBasicConvertPlaceholderToInterpolatedStringRefactoringProvider.vb
  src/Features/VisualBasic/Portable/Structure/Providers/DocumentationCommentStructureProvider.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CSharpCompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxNodeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpFileBannerFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/AbstractFileBannerFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/AbstractSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/IFileBannerFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/IFileBannerFactsExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFactsExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Extensions/SyntaxNodeExtensions.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicFileBannerFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxKinds.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/VisualBasicCompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CSharpWorkspaceExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpFileBannerFactsService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/MoveDeclarationNearReference/AbstractMoveDeclarationNearReferenceService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/SyntaxFactsService/IFileBannerFactsService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/SyntaxFactsService/ISyntaxFactsService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/LanguageServices/VisualBasicFileBannerFactsService.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/VisualBasicWorkspaceExtensions.projitems
  src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicCodeGenerationService.vb
Labels: Area-IDE

#56422 Fix nullable annotations
  src/Compilers/CSharp/Portable/Syntax/ForStatementSyntax.cs
Labels: Area-Compilers

#56425 Add reproducer for pattern matching crash
  src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs
Labels: Area-Compilers, Test

#56418 Fix cases where we were showing 'nint/nuint' in preprocessor directives.
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/BoolKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ByteKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/CharKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ConstKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/DecimalKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/DoubleKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/DynamicKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ExternKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/FloatKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/IntKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/LongKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/NativeIntegerKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/NewKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ObjectKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/SByteKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ShortKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/StaticKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/StringKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/UIntKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ULongKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/UShortKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/VoidKeywordRecommenderTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/VoidKeywordRecommender.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTreeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/CSharpSyntaxContext.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTokenExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Utilities/SyntaxKindSet.cs
Labels: Area-IDE

#56434 Fix api violations in ISyntaxFacts
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/AbstractObjectCreationExpressionAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseObjectInitializer/ObjectCreationExpressionAnalyzer.cs
  src/EditorFeatures/Core/Implementation/AutomaticCompletion/AbstractAutomaticLineEnderCommandHandler.cs
  src/Features/CSharp/Portable/CodeRefactorings/CSharpRefactoringHelpersService.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSyntaxTriviaService.cs
  src/Features/CSharp/Portable/GenerateDefaultConstructors/CSharpGenerateDefaultConstructorsService.cs
  src/Features/Core/Portable/AddParameter/AbstractAddParameterCodeFixProvider.cs
  src/Features/Core/Portable/CodeRefactorings/AbstractRefactoringHelpersService.cs
  src/Features/Core/Portable/CodeRefactorings/IRefactoringHelpersService.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexPatternDetector.cs
  src/Features/Core/Portable/ExtractMethod/AbstractSyntaxTriviaService.cs
  src/Features/Core/Portable/GenerateComparisonOperators/GenerateComparisonOperatorsCodeRefactoringProvider.cs
  src/Features/Core/Portable/GenerateConstructorFromMembers/AbstractGenerateConstructorFromMembersCodeRefactoringProvider.cs
  src/Features/Core/Portable/GenerateDefaultConstructors/AbstractGenerateDefaultConstructorCodeFixProvider.cs
  src/Features/Core/Portable/GenerateDefaultConstructors/AbstractGenerateDefaultConstructorsService.State.cs
  src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider.cs
  src/Features/Core/Portable/GenerateOverrides/GenerateOverridesCodeRefactoringProvider.cs
  src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceParameterDocumentRewriter.cs
  src/Features/Core/Portable/SignatureHelp/CommonSignatureHelpUtilities.cs
  src/Features/VisualBasic/Portable/CodeRefactorings/VisualBasicRefactoringHelpersService.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicSyntaxTriviaService.vb
  src/Features/VisualBasic/Portable/GenerateDefaultConstructors/VisualBasicGenerateDefaultConstructorsService.vb
  src/VisualStudio/Core/Impl/CodeModel/FileCodeModel.cs
  src/Workspaces/Core/Portable/CodeCleanup/AbstractCodeCleanerService.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/Indentation/AbstractIndentationService.Indenter.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CSharpCompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Engine/CSharpFormatEngine.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Engine/CSharpStructuredTriviaFormatEngine.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpHeaderFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/BottomUpBaseIndentationFinder.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Context/FormattingContext.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Engine/AbstractFormatEngine.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/FormattingExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/FileBannerFacts/AbstractFileBannerFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/FileBannerFacts/IFileBannerFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/FileBannerFacts/IFileBannerFactsExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/HeaderFacts/AbstractHeaderFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/HeaderFacts/IHeaderFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/HeaderFacts/IHeaderFactsExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/AbstractSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFactsExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicHeaderFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/VisualBasicCompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CSharpWorkspaceExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpHeaderFactsService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/SyntaxFactsService/IHeaderFactsService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/LanguageServices/VisualBasicHeaderFactsService.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/VisualBasicWorkspaceExtensions.projitems
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/VisualBasicFormatEngine.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/VisualBasicStructuredTriviaFormatEngine.vb
Labels: Area-IDE

#56396 Verify xmldoc for cref to positional property
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs
Labels: Test, New Language Feature - Records

#53891 List patterns: subsumption checking
  src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs
  src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs
  src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder_ListPatterns.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundDagEvaluation.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundDagTemp.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundDagTest.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.DecisionDagRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IsPatternOperator.cs
  src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.NonNegativeIntTC.cs
  src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.NonNegativeIntValueSetFactory.cs
  src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.NumericValueSet.cs
  src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTestBase.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests_ListPatterns.cs
  src/Compilers/CSharp/Test/Semantic/Utilities/ValueSetTests.cs
  src/Compilers/Test/Utilities/CSharp/TestSources.cs
Labels: Area-Compilers, New Feature - List Patterns

#56433 Only allow Contract.ThrowIfNull() to be called on nullable types
  src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs
  src/Interactive/Host/Interactive/Core/InteractiveHost.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/SourceGeneratedFileItems/SourceGeneratedFileItemSource.cs
  src/VisualStudio/Core/Test.Next/Remote/SerializationValidator.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/OnTypeRename/OnTypeRenameHandler.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Metadata.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Contract.cs
Labels: Area-IDE

#56426 Remove legacy RPC
  src/EditorFeatures/Core/Implementation/Workspaces/EditorErrorReportingService.cs
  src/EditorFeatures/TestUtilities/Remote/WatsonReporter.cs
  src/VisualStudio/Core/Def/Implementation/Watson/WatsonReporter.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioErrorReportingService.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/Core/Test.Next/Remote/RemoteHostClientServiceFactoryTests.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/VisualStudio/Core/Test.Next/Services/VisualStudioDiagnosticAnalyzerExecutorTests.cs
  src/Workspaces/Core/Portable/ExtensionManager/IErrorReportingService.cs
  src/Workspaces/Core/Portable/Remote/RemoteHostClient.cs
  src/Workspaces/Core/Portable/Remote/RemoteServiceConnection.cs
  src/Workspaces/Core/Portable/Remote/RemoteServiceName.cs
  src/Workspaces/Core/Portable/Remote/WellKnownServiceHubService.cs
  src/Workspaces/CoreTestUtilities/MEF/TestComposition.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemostHostClient.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemoteHostClientProvider.cs
  src/Workspaces/CoreTestUtilities/TestErrorReportingService.cs
  src/Workspaces/Remote/Core/IPooledConnectionReclamation.cs
  src/Workspaces/Remote/Core/IRemoteHostService.cs
  src/Workspaces/Remote/Core/IRemoteHostServiceCallback.cs
  src/Workspaces/Remote/Core/JsonRpcConnection.cs
  src/Workspaces/Remote/Core/RemoteEndPoint.cs
  src/Workspaces/Remote/Core/RemoteHostAssetSerialization.cs
  src/Workspaces/Remote/Core/ServiceDescriptors.cs
  src/Workspaces/Remote/Core/ServiceHubRemoteHostClient.ConnectionPools.cs
  src/Workspaces/Remote/Core/ServiceHubRemoteHostClient.cs
  src/Workspaces/Remote/ServiceHub/ExternalAccess/UnitTesting/Api/UnitTestingServiceBase.cs
  src/Workspaces/Remote/ServiceHub/Host/ProcessExtensions.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteHostTestData.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspaceManager.cs
  src/Workspaces/Remote/ServiceHub/Host/ThrowingTraceListener.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.FactoryBase.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs
  src/Workspaces/Remote/ServiceHub/Services/Host/RemoteHostService.cs
  src/Workspaces/Remote/ServiceHub/Services/ServiceBase.cs
Labels: Area-IDE

#56462 More instrumentation on flaky test TupleWithElementNamedWithDefaultName
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs
Labels: Area-Compilers, Test

#56464 Clean up props/targets
  eng/targets/Services.props
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
Labels: Area-Infrastructure

#56465 Remove JSON serialization helpers
  src/VisualStudio/Core/Test.Next/Remote/JsonConverterTests.cs
  src/Workspaces/Remote/Core/Serialization/RoslynJsonConverter.RoslynOnly.cs
  src/Workspaces/Remote/Core/Serialization/RoslynJsonConverter.SolutionIdConverters.cs
  src/Workspaces/Remote/Core/Serialization/RoslynJsonConverter.cs
Labels: Area-IDE

#56379 Update UnitTesting Hot Reload API to consider syntax errors
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/API/UnitTestingHotReloadService.cs
Labels: Area-IDE

#56458 Migrate to consistent pattern for ISyntaxFacts
  src/Analyzers/CSharp/Analyzers/AddAccessibilityModifiers/CSharpAddAccessibilityModifiers.cs
  src/Analyzers/CSharp/Analyzers/AddAccessibilityModifiers/CSharpAddAccessibilityModifiersDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/AddAccessibilityModifiers/AbstractAddAccessibilityModifiers.cs
  src/Analyzers/Core/Analyzers/AddAccessibilityModifiers/IAddAccessibilityModifiersService.cs
  src/Analyzers/Core/Analyzers/MatchFolderAndNamespace/AbstractMatchFolderAndNamespaceDiagnosticAnalyzer.cs
  src/Analyzers/VisualBasic/Analyzers/AddAccessibilityModifiers/VisualBasicAddAccessibilityModifiers.vb
  src/Analyzers/VisualBasic/Analyzers/AddAccessibilityModifiers/VisualBasicAddAccessibilityModifiersDiagnosticAnalyzer.vb
  src/Features/CSharp/Portable/AddImport/CSharpAddImportFeatureService.cs
  src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs
  src/Features/CSharp/Portable/Formatting/CSharpAccessibilityModifiersNewDocumentFormattingProvider.cs
  src/Features/CSharp/Portable/Formatting/CSharpNamespaceDeclarationNewDocumentFormattingProvider.cs
  src/Features/CSharp/Portable/Wrapping/SeparatedSyntaxList/CSharpArgumentWrapper.cs
  src/Features/Core/Portable/ChangeSignature/DelegateInvokeMethodReferenceFinder.cs
  src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.MoveTypeNamespaceScopeEditor.cs
  src/Features/Core/Portable/CodeRefactorings/SyncNamespace/AbstractChangeNamespaceService.cs
  src/Features/Core/Portable/ConvertForToForEach/AbstractConvertForToForEachCodeRefactoringProvider.cs
  src/Features/Core/Portable/InitializeParameter/AbstractInitializeParameterCodeRefactoringProvider.cs
  src/Features/Core/Portable/InlineMethod/AbstractInlineMethodRefactoringProvider.InlineContext.cs
  src/Features/Core/Portable/InlineMethod/AbstractInlineMethodRefactoringProvider.cs
  src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceParameterDocumentRewriter.cs
  src/Features/Core/Portable/PullMemberUp/MembersPuller.cs
  src/Features/Core/Portable/ReplacePropertyWithMethods/AbstractReplacePropertyWithMethodsService.cs
  src/Features/Core/Portable/SignatureHelp/CommonSignatureHelpUtilities.cs
  src/Features/Core/Portable/ValueTracking/ValueTracker.FindReferencesProgress.cs
  src/Features/Core/Portable/Wrapping/ChainedExpression/AbstractChainedExpressionWrapper.cs
  src/Features/VisualBasic/Portable/CodeRefactorings/SyncNamespace/VisualBasicChangeNamespaceService.vb
  src/Features/VisualBasic/Portable/Wrapping/SeparatedSyntaxList/VisualBasicArgumentWrapper.vb
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/Core/Portable/DesignerAttribute/DesignerAttributeHelpers.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CSharpCompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxNodeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpAccessibilityFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/AbstractSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/IAccessibilityFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFactsExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicAccessibilityFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxKinds.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/VisualBasicCompilerExtensions.projitems
  src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb
Labels: Area-IDE

#56373 Fix merge if in top level statements
  src/EditorFeatures/CSharpTest/SplitOrMergeIfStatements/MergeNestedIfStatementsTests_WithNested.cs
  src/Features/Core/Portable/SplitOrMergeIfStatements/Nested/AbstractMergeNestedIfStatementsCodeRefactoringProvider.cs
Labels: Area-IDE

#56397 Don't offer to generate parameters in lambdas
  src/EditorFeatures/CSharpTest/GenerateVariable/GenerateVariableTests.cs
  src/Features/Core/Portable/GenerateMember/GenerateVariable/AbstractGenerateVariableService.State.cs
Labels: Area-IDE

#56474 Fix UseAutoProperty for record structs
  src/Analyzers/CSharp/Analyzers/UseAutoProperty/CSharpUseAutoPropertyAnalyzer.cs
  src/Analyzers/CSharp/Tests/UseAutoProperty/UseAutoPropertyTests.cs
Labels: Area-IDE

#56450 Implement INamespaceTypeReference.GetUnit for RootModuleType
  src/Compilers/CSharp/Test/Symbol/Symbols/ModuleInitializers/ModuleInitializersTests.cs
  src/Compilers/Core/Portable/Emit/CommonPEModuleBuilder.cs
  src/Compilers/Core/Portable/PEWriter/RootModuleType.cs
Labels: Area-Compilers

#56484 Fix features using ISyntaxFacts as a place to store C# specific questions
  src/EditorFeatures/CSharp/InlineRename/CSharpEditorInlineRenameService.cs
  src/EditorFeatures/Core/Implementation/InlineRename/AbstractEditorInlineRenameService.cs
  src/EditorFeatures/Core/Implementation/InlineRename/CSharpEditorInlineRenameService.cs
  src/EditorFeatures/Core/Implementation/InlineRename/VisualBasicEditorInlineRenameService.cs
  src/EditorFeatures/VisualBasic/InlineRename/VisualBasicEditorInlineRenameService.vb
  src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTokenExtensions.cs
Labels: Area-IDE

#56375 Handle interaction of VB with Static Abstract Members in interfaces
  src/Compilers/VisualBasic/Portable/Binding/Binder.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Attributes.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Conversions.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Delegates.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Expressions.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Invocation.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_ObjectInitializer.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Statements.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Symbols.vb
  src/Compilers/VisualBasic/Portable/Errors/Errors.vb
  src/Compilers/VisualBasic/Portable/Symbols/EventSignatureComparer.vb
  src/Compilers/VisualBasic/Portable/Symbols/PropertySignatureComparer.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberContainerTypeSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberMethodSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/SymbolExtensions.vb
  src/Compilers/VisualBasic/Portable/VBResources.resx
  src/Compilers/VisualBasic/Portable/xlf/VBResources.cs.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.de.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.es.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.fr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.it.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ja.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ko.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pl.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pt-BR.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ru.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.tr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hans.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hant.xlf
  src/Compilers/VisualBasic/Test/Semantic/Semantics/NameOfTests.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/StaticAbstractMembersInInterfacesTests.vb
Labels: Area-Compilers, New Feature - StaticAbstractMembersInInterfaces

#56473 Fix MakeLocalFunctionStatic for top-level local function
  src/Analyzers/CSharp/Tests/MakeLocalFunctionStatic/MakeLocalFunctionStaticTests.cs
  src/EditorFeatures/CSharpTest/MakeLocalFunctionStatic/MakeLocalFunctionStaticRefactoringTests.cs
  src/Features/CSharp/Portable/MakeLocalFunctionStatic/MakeLocalFunctionStaticCodeFixProvider.cs
Labels: Area-IDE

#56491 Make method extensions
  src/Features/CSharp/Portable/InitializeParameter/InitializeParameterHelpers.cs
  src/Features/Core/Portable/AddImport/SymbolReferenceFinder.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/BlockSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/AbstractSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFactsExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
  src/Workspaces/VisualBasic/Portable/CodeCleanup/VisualBasicCodeCleanerService.vb
Labels: Area-IDE

#56488 Make abstract type actually implement interface.
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/AbstractSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFactsExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE

#56519 Do not commit rename session when debugging starts
  src/EditorFeatures/Core/Implementation/InlineRename/InlineRenameSession.cs
  src/EditorFeatures/Test2/Rename/InlineRenameTests.vb
Labels: Area-IDE

#56471 Optimize InheritanceMarginGlyph construction
  src/VisualStudio/Core/Def/Implementation/InheritanceMargin/MarginGlyph/InheritanceMarginContextMenu.xaml
  src/VisualStudio/Core/Def/Implementation/InheritanceMargin/MarginGlyph/InheritanceMarginContextMenu.xaml.cs
  src/VisualStudio/Core/Def/Implementation/InheritanceMargin/MarginGlyph/InheritanceMarginGlyph.xaml
  src/VisualStudio/Core/Def/Implementation/InheritanceMargin/MarginGlyph/InheritanceMarginGlyph.xaml.cs
  src/VisualStudio/Core/Def/Implementation/InheritanceMargin/MarginGlyph/InheritanceMarginGlyphViewModel.cs
  src/VisualStudio/Core/Test/InheritanceMargin/InheritanceMarginViewModelTests.vb
Labels: Area-IDE

#56545 Separate the process of performing nullable analysis on attribute applications from the process of filling the attribute bag with data.
  src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs
  src/Compilers/CSharp/Portable/Binder/EarlyWellKnownAttributeBinder.cs
  src/Compilers/CSharp/Portable/Symbols/Source/FieldSymbolWithAttributesAndModifiers.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs
  src/Compilers/Core/Portable/Symbols/Attributes/CommonMethodEarlyWellKnownAttributeData.cs
Labels: Area-Compilers, New Language Feature - Nullable Reference Types

#56553 Avoid switching to UI thread in some option persisters
  src/VisualStudio/Core/Def/Implementation/Options/FeatureFlagPersisterProvider.cs
  src/VisualStudio/Core/Def/Implementation/Options/LocalUserRegistryOptionPersister.cs
  src/VisualStudio/Core/Def/Implementation/Options/LocalUserRegistryOptionPersisterProvider.cs
  src/VisualStudio/Core/Def/Implementation/Options/RoamingVisualStudioProfileOptionPersister.cs
  src/VisualStudio/Core/Def/Implementation/Options/RoamingVisualStudioProfileOptionPersisterProvider.cs
Labels: Area-IDE

#56569 Only produce suppressions/config for the normal priority group.
  src/EditorFeatures/CSharpTest/Diagnostics/Suppression/SuppressionTests.cs
  src/EditorFeatures/Core.Wpf/Suggestions/AsyncSuggestedActionsSource.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs
  src/EditorFeatures/Test/CodeFixes/CodeFixServiceTests.cs
  src/EditorFeatures/Test2/CodeFixes/CodeFixServiceTests.vb
  src/Features/Core/Portable/CodeFixes/ICodeFixService.cs
  src/Features/Core/Portable/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs
  src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionHelpers.cs
Labels: Area-IDE

#56424 EnC/HR interface unification
  src/EditorFeatures/Core/Implementation/EditAndContinue/EditAndContinueDiagnosticAnalyzer.cs
  src/EditorFeatures/Core/Implementation/EditAndContinue/EditAndContinueLanguageService.cs
  src/EditorFeatures/Core/Implementation/EditAndContinue/ManagedEditAndContinueLanguageService.cs
  src/EditorFeatures/Core/Implementation/EditAndContinue/ManagedHotReloadLanguageService.cs
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/EditorFeatures/Test/EditAndContinue/RemoteEditAndContinueServiceTests.cs
  src/EditorFeatures/TestUtilities/EditAndContinue/MockEditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/Debugging/DebuggingState.cs
  src/Features/Core/Portable/Debugging/DebuggingStateChangedEventArgs.cs
  src/Features/Core/Portable/Debugging/DebuggingWorkspaceService.cs
  src/Features/Core/Portable/Debugging/DebuggingWorkspaceServiceFactory.cs
  src/Features/Core/Portable/Debugging/IDebuggingWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSession.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/Core/Portable/EditAndContinue/ManagedModuleUpdateStatusEx.cs
  src/Features/Core/Portable/EditAndContinue/Remote/RemoteDebuggingSessionProxy.cs
  src/Features/Core/Portable/EditAndContinue/SolutionUpdate.cs
Labels: Area-Interactive, Interactive-EnC

#56578 Enable nullable analysis in some parts of the code
  src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.LocalFunctions.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs
  src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs
  src/Compilers/CSharp/Portable/Symbols/Symbol.cs
Labels: Area-Compilers

#54969 Don't skip suppressors with /skipAnalyzers
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/Core/Portable/CommandLine/CommandLineArguments.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs
Labels: Area-Analyzers, Area-Compilers

#56357 Fix DefaultAnalyzerAssemblyLoader
  src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs
  src/Compilers/Test/Core/AssemblyLoadTestFixture.cs
  src/VisualStudio/Setup/source.extension.vsixmanifest
Labels: Area-Analyzers

#56583 Backport 56569 to 17.0
  src/EditorFeatures/Core.Wpf/Suggestions/AsyncSuggestedActionsSource.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs
  src/Features/Core/Portable/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs
  src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionHelpers.cs
Labels: Area-IDE

#56584 Implement capabilities changed handler
  src/EditorFeatures/Core/Implementation/EditAndContinue/EditAndContinueLanguageService.cs
  src/EditorFeatures/Core/Implementation/EditAndContinue/ManagedEditAndContinueLanguageService.cs
  src/EditorFeatures/Core/Implementation/EditAndContinue/ManagedHotReloadLanguageService.cs
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/EditorFeatures/Test/EditAndContinue/RemoteEditAndContinueServiceTests.cs
  src/EditorFeatures/TestUtilities/EditAndContinue/MockEditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSession.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/Core/Portable/EditAndContinue/IEditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/Remote/IRemoteEditAndContinueService.cs
  src/Features/Core/Portable/EditAndContinue/Remote/RemoteDebuggingSessionProxy.cs
  src/Workspaces/Remote/ServiceHub/Services/EditAndContinue/RemoteEditAndContinueService.cs
Labels: Area-Interactive

#56419 Fix partial method doc comments
  src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs
  src/Compilers/CSharp/Test/Symbol/DocumentationComments/PartialTypeDocumentationCommentTests.cs
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
Labels: Area-Compilers

#56443 Guard against updates with no type changes
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
Labels: Area-IDE

#56460 Set CompilerApiVersion in Microsoft.Managed.Core.targets
  src/Compilers/Core/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.csproj
  src/Compilers/Core/MSBuildTask/Microsoft.Managed.Core.targets
  src/Compilers/Core/MSBuildTaskTests/Microsoft.Build.Tasks.CodeAnalysis.UnitTests.csproj
  src/Compilers/Core/MSBuildTaskTests/TargetTests.cs
  src/NuGet/Microsoft.Net.Compilers.Toolset/DesktopCompilerArtifacts.targets
Labels: Area-Compilers

#56490 Add more tests around case sensitivity and project reference conversion
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProject.cs
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioProjectTests/MetadataToProjectReferenceConversionTests.vb
Labels: Area-IDE

#56593 Add test to ensure completion won't trigger execution of source generator
  src/EditorFeatures/CSharpTest/Completion/CompletionServiceTests.cs
  src/Workspaces/CoreTest/SolutionTests/ProjectSemanticVersionTests.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTestHelpers.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
  src/Workspaces/CoreTestUtilities/SolutionUtilities.cs
  src/Workspaces/CoreTestUtilities/WorkspaceTestUtilities.cs
Labels: Area-IDE

#56554 Fix formatting of overload with new
  src/Workspaces/CSharpTest/Formatting/FormattingTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/TokenBasedFormattingRule.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE

#56605 Fix test
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
Labels: Area-Interactive, auto-merge

#56564 When "assigned", a `discard` doesn't escape out of the current expression.
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundDiscardExpression.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SpanStackSafetyTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/StackAllocInitializerTests.cs
Labels: Area-Compilers

#56551 Enable async lightbulbs by default
  src/EditorFeatures/Core.Wpf/Suggestions/AsyncSuggestedActionsSource.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSourceProvider.cs
  src/EditorFeatures/Core/Implementation/Suggestions/SuggestionsOptions.cs
  src/EditorFeatures/Core/Implementation/Suggestions/SuggestionsOptionsProvider.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/Commands.vsct.cs.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.de.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.es.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.fr.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.it.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.ja.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.ko.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.pl.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.ru.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.tr.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.zh-Hant.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpCodeActions.cs
  src/VisualStudio/IntegrationTest/TestUtilities/Helper.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/TextViewWindow_InProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/LightBulbHelper.cs
  src/VisualStudio/IntegrationTest/TestUtilities/TestUtilities.cs
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageStrings.vb
Labels: Area-IDE

#56603 Only move the focus back to editor for Inheritance Margin when ESC is pressed
  src/VisualStudio/Core/Def/Implementation/InheritanceMargin/MarginGlyph/InheritanceMarginGlyph.cs
Labels: Area-IDE

#56614 Log gold bars to the activity log
  src/EditorFeatures/Core.Wpf/InlineRename/CommandHandlers/RenameCommandHandler.cs
  src/EditorFeatures/Core.Wpf/InlineRename/Dashboard/Dashboard.xaml.cs
  src/EditorFeatures/Core/Implementation/EditorLayerExtensionManager.cs
  src/EditorFeatures/Core/Implementation/Workspaces/EditorErrorReportingService.cs
  src/Features/Core/Portable/CodeFixes/CodeFixService.cs
  src/VisualStudio/Core/Def/ExternalAccess/LegacyCodeAnalysis/LegacyCodeAnalysisVisualStudioSuppressionFixServiceAccessor.cs
  src/VisualStudio/Core/Def/Implementation/VirtualMemoryNotificationListener.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioErrorReportingService.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioErrorReportingServiceFactory.cs
  src/Workspaces/Core/Portable/ExtensionManager/IErrorReportingService.cs
  src/Workspaces/CoreTestUtilities/TestErrorReportingService.cs
Labels: Area-IDE

#56333 Add support for all parenthesized binary additions of interpolated strings
  src/Compilers/CSharp/Portable/Binder/Binder_InterpolatedString.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodeExtensions.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperator.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IInterpolatedStringOperation.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
Labels: Area-Compilers, New Feature - Interpolated String Improvements

#56341 Avoid several breaking changes in overload resolution from inferred types of lambda expressions and method groups
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 6.md
  docs/compilers/CSharp/Compiler Breaking Changes - post DotNet 5.md
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MemberResolutionResult.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
Labels: Area-Compilers, New Feature - Lambda Improvements

#56546 Add missing releases to NuGet documentation
  docs/wiki/NuGet-packages.md
Labels: Area-Infrastructure, Documentation

#56371 Fix the condition on passing BuildWithSkipAnalyzers marker file to FUTD
  src/Compilers/Core/MSBuildTask/Microsoft.Managed.Core.targets
  src/Compilers/Core/MSBuildTaskTests/TargetTests.cs
Labels: Area-Analyzers, Area-Compilers

#56606 Allow user to change the nuget.org feed name without breaking Nuget suggestions
  src/EditorFeatures/CSharpTest/AddUsing/AddUsingNuGetTests.cs
  src/EditorFeatures/Core/SymbolSearch/SymbolSearchUpdateEngine.Update.cs
  src/EditorFeatures/Core/SymbolSearch/SymbolSearchUpdateEngine.cs
  src/EditorFeatures/VisualBasicTest/Diagnostics/AddImport/AddImportTests_NuGet.vb
  src/Features/Core/Portable/AddImport/PackageSourceHelper.cs
  src/Features/Core/Portable/AddImport/SymbolReferenceFinder_PackageAssemblySearch.cs
  src/Features/Core/Portable/AddPackage/AbstractAddPackageCodeFixProvider.cs
  src/VisualStudio/Core/Def/SymbolSearch/VisualStudioSymbolSearchService.cs
  src/VisualStudio/Core/Test/SymbolSearch/SymbolSearchUpdateEngineTests.vb
Labels: Area-IDE

#56634 Don't inline lightbulb actions if the total count would be too high
  src/EditorFeatures/Core.Wpf/Suggestions/AsyncSuggestedActionsSource.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs
  src/EditorFeatures/Core/Implementation/LanguageServer/Handlers/CodeActions/CodeActionHelpers.cs
  src/Features/Core/Portable/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpCodeActions.cs
Labels: Area-IDE

#54240 Fix WithAsyncKeyword to not drop existing modifiers
  src/Compilers/CSharp/Portable/Syntax/AnonymousFunctionExpressionSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/AnonymousMethodExpressionSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/ParenthesizedLambdaExpressionSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/SimpleLambdaExpressionSyntax.cs
  src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNodeTests.cs
Labels: Area-Compilers, Community

#56611 Avoid unnecessary up-front captures to temps while lowering indexer access that uses “Index Pattern”
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs
Labels: Area-Compilers, New Language Feature - Range

#56652 Implement val escape checks for BoundFromEndIndexExpression and BoundRangeExpression nodes.
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/IndexAndRangeTests.cs
Labels: Area-Compilers, New Language Feature - Range

#56647 Handle potentially-null IVsActivityLog
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioErrorReportingService.cs
Labels: Area-IDE

#56559 Clean up loc strings
  src/EditorFeatures/CSharp/CSharpEditorResources.resx
  src/EditorFeatures/CSharp/EditorConfigSettings/DataProvider/Whitespace/CSharpWhitespaceSettingsProvider.cs
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.cs.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.de.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.es.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.fr.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.it.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.ja.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.ko.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.pl.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.pt-BR.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.ru.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.tr.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.zh-Hans.xlf
  src/EditorFeatures/CSharp/xlf/CSharpEditorResources.zh-Hant.xlf
  src/EditorFeatures/Core/EditorFeaturesResources.resx
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.cs.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.de.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.es.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.fr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.it.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ja.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ko.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pl.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pt-BR.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ru.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.tr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hans.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hant.xlf
  src/VisualStudio/CSharp/Impl/EditorConfigSettings/DataProvider/CodeStyle/CSharpCodeStyleSettingsLanguageServiceFactory.cs
  src/VisualStudio/CSharp/Impl/EditorConfigSettings/DataProvider/CodeStyle/CSharpCodeStyleSettingsProvider.cs
  src/VisualStudio/CSharp/Impl/EditorConfigSettings/DataProvider/CodeStyle/CSharpCodeStyleSettingsProviderFactory.cs
  src/VisualStudio/CSharp/Impl/EditorConfigSettings/DataProvider/Whitespace/CSharpWhitespaceSettingsLanguageServiceFactory.cs
  src/VisualStudio/CSharp/Impl/EditorConfigSettings/DataProvider/Whitespace/CSharpWhitespaceSettingsProvider.cs
  src/VisualStudio/CSharp/Impl/EditorConfigSettings/DataProvider/Whitespace/CSharpWhitespaceSettingsProviderFactory.cs
  src/VisualStudio/CSharp/Test/EditorConfigSettings/Aggregator/SettingsAggregatorTests.cs
  src/VisualStudio/CSharp/Test/EditorConfigSettings/DataProvider/DataProviderTests.MockAnalyzerReference.cs
  src/VisualStudio/CSharp/Test/EditorConfigSettings/DataProvider/DataProviderTests.TestViewModel.cs
  src/VisualStudio/CSharp/Test/EditorConfigSettings/DataProvider/DataProviderTests.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/DataProvider/CodeStyle/CommonCodeStyleSettingsProvider.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/DataProvider/CodeStyle/CommonCodeStyleSettingsProviderFactory.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/DataProvider/CodeStyle/CommonCodeStyleSettingsWorkspaceServiceFactory.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/DataProvider/Whitespace/CommonWhitespaceSettingsProvider.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/DataProvider/Whitespace/CommonWhitespaceSettingsProviderFactory.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/DataProvider/Whitespace/CommonWhitespaceSettingsWorkspaceServiceFactory.cs
Labels: Area-IDE

#56586 Fix crash lowering property pattern where override lacks a get accessor
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/ITuplePatternTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs
Labels: Area-Compilers

#56633 Refactor ClassificationOptions
  src/EditorFeatures/Core/Implementation/Classification/SemanticClassificationUtilities.cs
  src/EditorFeatures/Core/Implementation/Classification/SemanticClassificationViewTaggerProvider.cs
  src/EditorFeatures/Test2/Classification/ClassificationTests.vb
  src/EditorFeatures/TestUtilities/Classification/AbstractClassifierTests.cs
  src/Tools/ExternalAccess/FSharp/Internal/Classification/FSharpClassificationService.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/Workspaces/Core/Portable/Classification/AbstractClassificationService.cs
  src/Workspaces/Core/Portable/Classification/ClassificationOptions.cs
  src/Workspaces/Core/Portable/Classification/ClassifierHelper.cs
  src/Workspaces/Core/Portable/Classification/IClassificationService.cs
  src/Workspaces/Core/Portable/Classification/IRemoteSemanticClassificationService.cs
  src/Workspaces/Core/Portable/Classification/ReassignedVariableOptions.cs
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassification/RemoteSemanticClassificationService.cs
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassificationCache/RemoteSemanticClassificationCacheService.cs
Labels: Area-IDE

#56314 Create misc files workspace for LSP
  src/EditorFeatures/Core/Implementation/LanguageServer/LspWorkspaceRegistrationEventListener.cs
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/Workspace/MiscellaneousFileUtilities.cs
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Features/LanguageServer/Protocol/Handler/RequestContext.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.DocumentChangeTracker.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs
  src/Features/LanguageServer/Protocol/ILspLogger.cs
  src/Features/LanguageServer/Protocol/LanguageServerTarget.cs
  src/Features/LanguageServer/Protocol/LspMiscellaneousFilesWorkspace.cs
  src/Features/LanguageServer/ProtocolUnitTests/Miscellaneous/LspMiscellaneousFilesWorkspaceTests.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/LogHubLspLogger.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/MiscellaneousFilesWorkspace.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
Labels: Area-IDE

#56402 Store information about special attributes in the decl table to avoid going back to source unnecessarily.
  src/Compilers/CSharp/Portable/Declarations/DeclarationTreeBuilder.cs
  src/Compilers/CSharp/Portable/Declarations/MergedTypeDeclaration.cs
  src/Compilers/CSharp/Portable/Declarations/RootSingleNamespaceDeclaration.cs
  src/Compilers/CSharp/Portable/Declarations/SingleTypeDeclaration.cs
  src/Compilers/CSharp/Portable/Symbols/Source/QuickAttributeChecker.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs
  src/Compilers/CSharp/Test/Symbol/Compilation/CompilationAPITests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/NamedTypeTests.cs
  src/Compilers/VisualBasic/Portable/Declarations/DeclarationTreeBuilder.vb
  src/Compilers/VisualBasic/Portable/Declarations/MergedTypeDeclaration.vb
  src/Compilers/VisualBasic/Portable/Declarations/SingleTypeDeclaration.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/QuickAttributeChecker.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceNamedTypeSymbol.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/NamedTypeTests.vb
Labels: Area-Compilers

#56534 Method type inference should make inference from explicit lambda return type
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LoweredDynamicOperationFactory.cs
  src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs
Labels: Area-Compilers, New Feature - Lambda Improvements

#56654 Remove option state that is redundant with existing field
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/Workspaces/Core/Portable/Options/GlobalOptionService.cs
  src/Workspaces/Core/Portable/Options/SerializableOptionSet.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
Labels: Area-IDE

#56591 Add comment on usage of SLocalRegistry service on background thread
  src/VisualStudio/Core/Def/Implementation/Options/LocalUserRegistryOptionPersister.cs
Labels: Area-IDE

#56626 Update references for public 17.0 Preview 4 release
  eng/Versions.props
  src/Features/Core/Portable/UnusedReferences/ProjectAssets/ProjectAssetsReader.cs
  src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionResolveHandler.cs
  src/Features/LanguageServer/Protocol/Handler/CodeActions/RunCodeActionHandler.cs
  src/Features/Lsif/Generator/CompilerInvocation.cs
  src/Features/Lsif/Generator/Writing/LsifConverter.cs
  src/Tools/BuildValidator/Program.cs
  src/Tools/Source/RunTests/TestRunner.cs
  src/VisualStudio/Core/Test.Next/Services/LspDiagnosticsTests.cs
  src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/MockVsFileChangeEx.vb
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Completion/CompletionResolveHandler.cs
Labels: Area-Infrastructure
