Repository dotnet/roslyn, pull requests merged in 2021-01, with the labels that each got.

#50210 Handle implicit object creation in inline temp. refactoring
  src/EditorFeatures/CSharpTest/CodeActions/InlineTemporary/InlineTemporaryTests.cs
  src/Features/CSharp/Portable/CodeRefactorings/InlineTemporary/InlineTemporaryCodeRefactoringProvider.cs
Labels: Area-IDE, Community

#50217 Extract code into helper type
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/TextChangeMerger.cs
Labels: Area-IDE

#50209 Unify solution-wide fix-all code.
  src/Analyzers/CSharp/CodeFixes/RemoveConfusingSuppression/CSharpRemoveConfusingSuppressionFixAllProvider.cs
  src/EditorFeatures/Core.Cocoa/Suggestions/SuggestedActionsSource.cs
  src/Features/Core/Portable/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.DiagnosticProvider.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/AbstractDocumentBasedFixAllProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/DocumentBasedFixAllProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAll/FixAllState.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/SyntaxEditorBasedCodeFixProvider.FixAllProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Utilities/IProgressTracker.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensionsResources.resx
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.cs.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.de.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.es.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.fr.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.it.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.ja.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.ko.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.pl.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.pt-BR.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.ru.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.tr.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.zh-Hans.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.zh-Hant.xlf
Labels: Area-IDE

#50178 Always use hard links when building in CI
  eng/build.ps1
  eng/build.sh
Labels: Area-Infrastructure

#50228 Add doc comment explaining difference between ProtectedAndInternal vs ProtectedOrInternal
  src/Compilers/Core/Portable/Symbols/Accessibility.cs
Labels: Area-Compilers, Community

#50169 Improve cycle detection while evaluating values of a constant fields
  src/Compilers/CSharp/Portable/Symbols/Source/ConstantEvaluationHelpers.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/ConstantTests.cs
  src/Compilers/Core/Portable/InternalUtilities/EnumerableExtensions.cs
  src/Compilers/VisualBasic/Portable/Binding/BackstopBinder.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Expressions.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Initializers.vb
  src/Compilers/VisualBasic/Portable/Binding/ConstantFieldsInProgress.vb
  src/Compilers/VisualBasic/Portable/Binding/ConstantFieldsInProgressBinder.vb
  src/Compilers/VisualBasic/Portable/Binding/SymbolsInProgress.vb
  src/Compilers/VisualBasic/Portable/BoundTree/BoundFieldAccess.vb
  src/Compilers/VisualBasic/Portable/BoundTree/BoundNodes.xml
  src/Compilers/VisualBasic/Portable/CodeGen/Optimizer/StackScheduler.Analyzer.vb
  src/Compilers/VisualBasic/Portable/Generated/BoundNodes.xml.Generated.vb
  src/Compilers/VisualBasic/Portable/Lowering/AsyncRewriter/AsyncRewriter.AsyncMethodToClassRewriter.Expressions.vb
  src/Compilers/VisualBasic/Portable/Lowering/AsyncRewriter/AsyncRewriter.AsyncMethodToClassRewriter.Spilling.vb
  src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_FieldAccess.vb
  src/Compilers/VisualBasic/Portable/Lowering/MethodToClassRewriter/MethodToClassRewriter.vb
  src/Compilers/VisualBasic/Portable/Lowering/UseTwiceRewriter.vb
  src/Compilers/VisualBasic/Portable/Symbols/ConstantValueUtils.vb
  src/Compilers/VisualBasic/Portable/Symbols/FieldSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEFieldSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Retargeting/RetargetingFieldSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceEnumConstantSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceFieldSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberFieldSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SynthesizedFieldSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/SubstitutedFieldSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/SynthesizedSymbols/SynthesizedBackingFieldBase.vb
  src/Compilers/VisualBasic/Portable/Symbols/Wrapped/WrappedFieldSymbol.vb
  src/Compilers/VisualBasic/Test/Semantic/Binding/Binder_Expressions_Tests.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Metadata/PE/LoadingFields.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Retargeting/RetargetCustomModifiers.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/EnumTests.vb
  src/ExpressionEvaluator/VisualBasic/Source/ExpressionCompiler/Symbols/DisplayClassVariable.vb
Labels: Area-Compilers

#50223 Expose a real DocumentBasedFixAllProvider for users to use
  src/Analyzers/CSharp/CodeFixes/RemoveConfusingSuppression/CSharpRemoveConfusingSuppressionFixAllProvider.cs
  src/Analyzers/Core/CodeFixes/FileHeaders/AbstractFileHeaderCodeFixProvider.cs
  src/CodeStyle/Core/CodeFixes/FormattingCodeFixProvider.cs
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionCodeFixProvider.RemoveSuppressionCodeAction.BatchFixer.cs
  src/Features/Core/Portable/ConflictMarkerResolution/ConflictMarkerFixAllProvider.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllProvider.cs
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/RoslynDocumentBasedFixAllProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/SyntaxEditorBasedCodeFixProvider.FixAllProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/SyntaxEditorBasedCodeFixProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensions.projitems
Labels: Area-IDE, auto-merge

#50237 Delete dev-rehydrate-tests.ps1
  eng/dev-rehydrate-tests.ps1
Labels: Area-Infrastructure

#50225 Remove unused value that was passed along but never read
  src/VisualStudio/Core/Def/Implementation/Utilities/VisualStudioWaitContext.cs
  src/Workspaces/Core/Portable/Notification/AbstractGlobalOperationNotificationService.cs
  src/Workspaces/Core/Portable/Notification/GlobalOperationEventArgs.cs
  src/Workspaces/Core/Portable/Notification/GlobalOperationNotificationService.cs
  src/Workspaces/Core/Portable/Notification/GlobalOperationRegistration.cs
  src/Workspaces/Remote/Core/GlobalNotificationRemoteDeliveryService.cs
  src/Workspaces/Remote/Core/IRemoteGlobalNotificationDeliveryService.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteGlobalOperationNotificationService.cs
  src/Workspaces/Remote/ServiceHub/Services/GlobalNotificationDelivery/RemoteGlobalNotificationDeliveryService.cs
Labels: Area-IDE

#50216 Improve behavior and performance of the builtin BatchFixAllProvider
  src/Analyzers/CSharp/CodeFixes/CSharpCodeFixes.projitems
  src/Analyzers/CSharp/CodeFixes/RemoveConfusingSuppression/CSharpRemoveConfusingSuppressionCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/RemoveConfusingSuppression/CSharpRemoveConfusingSuppressionFixAllProvider.cs
  src/Analyzers/Core/CodeFixes/FileHeaders/AbstractFileHeaderCodeFixProvider.cs
  src/CodeStyle/Core/CodeFixes/FormattingCodeFixProvider.cs
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionBatchFixAllProvider.cs
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionCodeFixProvider.PragmaWarningBatchFixAllProvider.cs
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionCodeFixProvider.RemoveSuppressionCodeAction.BatchFixer.cs
  src/Features/Core/Portable/ConflictMarkerResolution/AbstractConflictMarkerCodeFixProvider.cs
  src/Features/Core/Portable/ConflictMarkerResolution/ConflictMarkerFixAllProvider.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/DefaultFixAllProviderHelpers.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/RoslynDocumentBasedFixAllProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensionsResources.resx
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.cs.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.de.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.es.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.fr.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.it.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.ja.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.ko.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.pl.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.pt-BR.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.ru.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.tr.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.zh-Hans.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/xlf/WorkspaceExtensionsResources.zh-Hant.xlf
Labels: Area-IDE, auto-merge

#50243 Add a working internal progress system for codeactions
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActions/SuggestedAction.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActions/UIThreadOperationContextProgressTracker.cs
Labels: Area-IDE, auto-merge

#48101 Create RecordDeclarationOrganizer
  src/EditorFeatures/CSharpTest/Organizing/OrganizeModifiersTests.cs
  src/EditorFeatures/CSharpTest/Organizing/OrganizeTypeDeclarationTests.cs
  src/Features/CSharp/Portable/Organizing/Organizers/MemberDeclarationsOrganizer.Comparer.cs
  src/Features/CSharp/Portable/Organizing/Organizers/RecordDeclarationOrganizer.cs
Labels: Area-IDE, Community

#48252 Fixes IDE0059 (Remove redundant assignment) incorrectly copies leading trivia
  src/Analyzers/CSharp/Tests/RemoveUnusedParametersAndValues/RemoveUnusedValueAssignmentTests.cs
  src/Analyzers/Core/CodeFixes/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs
  src/Analyzers/VisualBasic/Tests/RemoveUnusedParametersAndValues/RemoveUnusedValueAssignmentTests.vb
Labels: Area-IDE, Community

#50246 Link to correct issue
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs
Labels: Area-IDE

#50256 Move to latest Microsoft.CodeAnalysis.NetAnalyzers package
  eng/Versions.props
Labels: Area-Analyzers, auto-merge

#49134 Put record parameters in scope of xml docs
  src/Compilers/CSharp/Portable/Binder/BinderFactory.BinderFactoryVisitor.cs
  src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs
Labels: Area-Compilers, New Language Feature - Records

#49336 Add note to inform MSBuild team of version changes to S.C.I or S.R.M
  eng/Versions.props
Labels: Area-Infrastructure

#50266 Fix regression where unchecking changes in fix all didn't preview right
  src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs
Labels: Area-IDE

#44147 Add comments
  src/Workspaces/Remote/Core/GlobalNotificationRemoteDeliveryService.cs
Labels: Area-IDE

#50238 Fix Sarif Version parser error message
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/Core/Portable/CommandLine/CommandLineParser.cs
  src/Compilers/VisualBasic/Test/CommandLine/CommandLineTests.vb
Labels: Area-Compilers, Community

#50031 Ban DiagnosticDescriptor ctor in CodeStyle layer
  src/Analyzers/Core/Analyzers/AbstractBuiltInCodeStyleDiagnosticAnalyzer_Core.cs
  src/Analyzers/Core/Analyzers/AbstractCodeQualityDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/RemoveUnnecessaryImports/AbstractRemoveUnnecessaryImportsDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/ValidateFormatString/AbstractValidateFormatStringDiagnosticAnalyzer.cs
  src/CodeStyle/BannedSymbols.txt
  src/EditorFeatures/CSharpTest/Squiggles/ErrorSquiggleProducerTests.cs
  src/EditorFeatures/VisualBasicTest/Squiggles/ErrorSquiggleProducerTests.vb
Labels: Area-IDE, Community, auto-merge

#50236 Add unit test recipe to the cookbook
  docs/features/source-generators.cookbook.md
Labels: Area-Compilers, Documentation, New Feature - Source Generators

#50277 Fix IDE0079 (unnecessary suppression) false positive
  src/Analyzers/Core/Analyzers/RemoveUnnecessarySuppressions/AbstractRemoveUnnecessaryPragmaSuppressionsDiagnosticAnalyzer.cs
  src/EditorFeatures/CSharpTest/Diagnostics/Suppression/RemoveUnnecessaryPragmaSuppressionsTests.cs
Labels: Area-IDE, auto-merge

#50285 Log errors from MSBuildWorkspace during LSIF indexing
  src/Features/Lsif/Generator/Program.cs
Labels: Area-IDE, auto-merge

#50288 Update version number for 16.10 p1 branch
  eng/Versions.props
Labels: Area-Infrastructure, auto-merge

#50306 Remove unused values in EnforceOnBuildValues
  src/Analyzers/Core/Analyzers/EnforceOnBuildValues.cs
Labels: Area-IDE, auto-merge

#50305 Validate help links
  src/EditorFeatures/CSharpTest/Squiggles/ErrorSquiggleProducerTests.cs
  src/EditorFeatures/Test/Diagnostics/IDEDiagnosticIDConfigurationTests.cs
  src/EditorFeatures/VisualBasicTest/Squiggles/ErrorSquiggleProducerTests.vb
  src/Features/Core/Portable/SimplifyTypeNames/SimplifyTypeNamesDiagnosticAnalyzerBase.cs
Labels: Area-IDE, auto-merge

#50289 Remove completion in argument list experiment
  src/Features/CSharp/Portable/Completion/CompletionProviders/SymbolCompletionProvider.cs
  src/Features/Core/Portable/Completion/CompletionOptions.cs
  src/VisualStudio/CSharp/Impl/CSharpVSResources.resx
  src/VisualStudio/CSharp/Impl/Options/IntelliSenseOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/IntelliSenseOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.cs.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.de.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.es.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.fr.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.it.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.ja.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.ko.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.pl.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.pt-BR.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.ru.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.tr.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.zh-Hans.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.zh-Hant.xlf
  src/Workspaces/Core/Portable/Experiments/IExperimentationService.cs
Labels: Area-IDE

#50304 Delete gold bar recommending FxCopAnalyzers install
  src/Features/Core/Portable/Diagnostics/Analyzers/FxCopAnalyzersInstallLogger.cs
  src/Features/Core/Portable/Diagnostics/Analyzers/FxCopAnalyzersInstallOptions.cs
  src/Features/Core/Portable/Diagnostics/Analyzers/FxCopAnalyzersInstallStatus.cs
  src/VisualStudio/Core/Def/Implementation/Diagnostics/FxCopAnalyzersSuggestedActionCallback.cs
  src/VisualStudio/Core/Test/Diagnostics/FxCopAnalyzersSuggestedActionCallbackTests.vb
Labels: Area-IDE

#50303 Delete IDE dispose analyzers
  src/Analyzers/Core/Analyzers/EnforceOnBuildValues.cs
  src/Analyzers/Core/Analyzers/IDEDiagnosticIds.cs
  src/EditorFeatures/CSharpTest/DisposeAnalysis/DisposableFieldsShouldBeDisposedTests.cs
  src/EditorFeatures/CSharpTest/DisposeAnalysis/DisposeObjectsBeforeLosingScopeTests.cs
  src/EditorFeatures/Test/Diagnostics/IDEDiagnosticIDConfigurationTests.cs
  src/EditorFeatures/VisualBasicTest/DisposeAnalysis/DisposableFieldsShouldBeDisposedTests.vb
  src/EditorFeatures/VisualBasicTest/DisposeAnalysis/DisposeObjectsBeforeLosingScopeTests.vb
  src/Features/Core/Portable/DisposeAnalysis/DisposableFieldsShouldBeDisposedDiagnosticAnalyzer.cs
  src/Features/Core/Portable/DisposeAnalysis/DisposeAnalysisHelper.cs
  src/Features/Core/Portable/DisposeAnalysis/DisposeObjectsBeforeLosingScopeDiagnosticAnalyzer.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
Labels: Area-IDE

#49899 Code lens: Constructor invocations should count as references of class declarations
  src/EditorFeatures/CSharpTest/CodeLens/CSharpCodeLensTests.cs
  src/Features/Core/Portable/CodeLens/CodeLensFindReferenceProgress.cs
Labels: Area-IDE, Community

#50292 Avoid unnecessary call to type inferer in target typed completion
  src/Features/CSharp/Portable/Completion/CompletionProviders/SymbolCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/AbstractRecommendationServiceBasedCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs
Labels: Area-IDE, auto-merge

#49661 Allow workspaces to opt in to LSP support
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/LanguageServer/Protocol/AbstractRequestHandlerProvider.cs
  src/Features/LanguageServer/Protocol/Extensions/Extensions.cs
  src/Features/LanguageServer/Protocol/Handler/CodeActions/RunCodeActionHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Commands/ExecuteWorkspaceCommandHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Commands/IExecuteWorkspaceCommandHandler.cs
  src/Features/LanguageServer/Protocol/Handler/IRequestHandler.cs
  src/Features/LanguageServer/Protocol/Handler/ProjectContext/GetTextDocumentWithContextHandler.cs
  src/Features/LanguageServer/Protocol/Handler/RequestContext.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.DocumentChangeTracker.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs
  src/Features/LanguageServer/Protocol/ILspSolutionProvider.cs
  src/Features/LanguageServer/Protocol/ILspWorkspaceRegistrationService.cs
  src/Features/LanguageServer/ProtocolUnitTests/CodeActions/CodeActionsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/References/FindImplementationsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Rename/RenameTests.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/AbstractInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/AlwaysActivateInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/LiveShareInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/RazorInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/VisualStudioLspSolutionProvider.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/VisualStudioLspWorkspaceRegistrationService.cs
  src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractPackage`2.cs
  src/VisualStudio/Core/Test.Next/Services/LspDiagnosticsTests.cs
  src/VisualStudio/LiveShare/Impl/AbstractGoToDefinitionWithFindUsagesServiceHandler.cs
  src/VisualStudio/LiveShare/Impl/GotoDefinitionWithFindUsagesServiceHandler.Exports.cs
  src/VisualStudio/LiveShare/Impl/Shims/TypeScriptHandlerShims.cs
  src/VisualStudio/LiveShare/Test/AbstractLiveShareRequestHandlerTests.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageClient/XamlInProcLanguageClient.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Diagnostics/DocumentPullDiagnosticHandler.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/XamlSolutionProvider.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/XamlLanguageServerProtocol.cs
Labels: Area-IDE

#50320 Use enum member instead of casting number
  src/Compilers/Core/Portable/Compilation/Compilation.cs
Labels: Area-Compilers

#50111 IOperation Test Hook Pt 1
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Symbols/Tuples/TupleErrorFieldSymbol.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IIsPatternExpression.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IObjectCreationExpression.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/NullablePublicAPITests.cs
  src/Compilers/Test/Core/Compilation/ControlFlowGraphVerifier.cs
  src/Compilers/Test/Core/Compilation/TestOperationVisitor.cs
Labels: Area-Compilers, auto-merge

#50251 Disallow setting init-only properties before C# 9
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InitOnlyMemberTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs
Labels: Area-Compilers, New Language Feature - Records

#50325 Automatically use ReleaseExe when top-level statements are present in a compilation and no options are specified.
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IObjectCreationExpression.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IPropertyReferenceExpression.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs
  src/Compilers/CSharp/Test/Symbol/DeclarationTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/RecordTests.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
Labels: Area-Compilers

#50326 Remove boosting logic.
  src/Features/Core/Portable/Diagnostics/DefaultDiagnosticAnalyzerService.cs
  src/Features/Core/Portable/Diagnostics/DiagnosticArguments.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.InProcOrRemoteHostAnalyzerRunner.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.cs
  src/VisualStudio/Core/Test.Next/Remote/JsonConverterTests.cs
  src/VisualStudio/Core/Test.Next/Services/VisualStudioDiagnosticAnalyzerExecutorTests.cs
  src/Workspaces/Remote/ServiceHub/ProcessExtensions.cs
  src/Workspaces/Remote/ServiceHub/Services/ConvertTupleToStructCodeRefactoringProvider/RemoteConvertTupleToStructCodeRefactoringService.cs
  src/Workspaces/Remote/ServiceHub/Services/DependentTypeFinder/RemoteDependentTypeFinderService.cs
  src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/RemoteDiagnosticAnalyzerService.cs
  src/Workspaces/Remote/ServiceHub/Services/EncapsulateField/RemoteEncapsulateFieldService.cs
  src/Workspaces/Remote/ServiceHub/Services/ExtensionMethodImportCompletion/RemoteExtensionMethodImportCompletionService.cs
  src/Workspaces/Remote/ServiceHub/Services/FindUsages/RemoteFindUsagesService.cs
  src/Workspaces/Remote/ServiceHub/Services/Host/RemoteHostService.cs
  src/Workspaces/Remote/ServiceHub/Services/MissingImportDiscovery/RemoteMissingImportDiscoveryService.cs
  src/Workspaces/Remote/ServiceHub/Services/NavigateToSearch/RemoteNavigateToSearchService.cs
  src/Workspaces/Remote/ServiceHub/Services/Renamer/RemoteRenamerService.cs
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassification/RemoteSemanticClassificationService.cs
  src/Workspaces/Remote/ServiceHub/Services/SymbolFinder/RemoteSymbolFinderService.cs
  src/Workspaces/Remote/ServiceHub/UserOperationBooster.cs
Labels: Area-IDE

#50310 [Change Signature] Ensure correct parameter is pre-selected upon dialog launch
  src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialog.xaml.cs
Labels: Area-IDE

#50299 Fix invalid cast exception for ctor member when getting Enum declaration
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
  src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs
  src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb
  src/Workspaces/VisualBasicTest/CodeGeneration/SyntaxGeneratorTests.vb
Labels: Area-IDE, Community

#49566 Ignore explicit interface implementation in naming style
  src/Analyzers/CSharp/Analyzers/NamingStyle/CSharpNamingStyleDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/NamingStyles/NamingStylesTests.cs
Labels: Area-IDE, Community

#50346 Remove (unpublished) public APIs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DefaultFixAllProviderHelpers.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllProvider.cs
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensions.projitems
Labels: Area-IDE, auto-merge

#50353 Pick better defaults when adding missing accessibility modifiers to members.
  src/Analyzers/CSharp/Tests/AddAccessibilityModifiers/AddAccessibilityModifiersTests.cs
  src/Analyzers/Core/CodeFixes/AddAccessibilityModifiers/AbstractAddAccessibilityModifiersCodeFixProvider.cs
  src/Analyzers/VisualBasic/Tests/AddAccessibilityModifiers/AddAccessibilityModifiersTests.vb
Labels: Area-IDE

#50354 Run Spanish tests in release mode
  azure-pipelines.yml
Labels: Area-Infrastructure

#50201 Results of running https://github.com/dotnet/roslyn-analyzers/pull/4647
  src/Analyzers/Core/Analyzers/ConvertTypeofToNameof/AbstractConvertTypeOfToNameOfDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/RemoveRedundantEquality/AbstractRemoveRedundantEqualityDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs
  src/Analyzers/Core/CodeFixes/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs
  src/Dependencies/CodeAnalysis.Debugging/CustomDebugInfoEncoder.cs
  src/Dependencies/CodeAnalysis.Debugging/CustomDebugInfoReader.cs
  src/EditorFeatures/Core/Implementation/Classification/SyntacticClassificationTaggerProvider.TagComputer.cs
  src/EditorFeatures/Core/Implementation/CommentSelection/AbstractToggleBlockCommentBase.cs
  src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CommitManager.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CompletionSource.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/Helpers.cs
  src/EditorFeatures/Core/Implementation/TextBufferAssociatedViewService.cs
  src/EditorFeatures/Core/Shared/Extensions/IProjectionBufferFactoryServiceExtensions.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs
  src/Features/Core/Portable/AddConstructorParametersFromMembers/AddConstructorParametersFromMembersCodeRefactoringProvider.cs
  src/Features/Core/Portable/AddParameter/AbstractAddParameterCodeFixProvider.cs
  src/Features/Core/Portable/AliasAmbiguousType/AbstractAliasAmbiguousTypeCodeFixProvider.cs
  src/Features/Core/Portable/CodeFixes/CodeFixService.cs
  src/Features/Core/Portable/CodeFixes/Configuration/ConfigurationUpdater.cs
  src/Features/Core/Portable/CodeLens/LocationComparer.cs
  src/Features/Core/Portable/CodeRefactorings/AbstractRefactoringHelpersService.cs
  src/Features/Core/Portable/CodeRefactorings/SyncNamespace/AbstractChangeNamespaceService.cs
  src/Features/Core/Portable/CodeRefactorings/SyncNamespace/AbstractSyncNamespaceCodeRefactoringProvider.MoveFileCodeAction.cs
  src/Features/Core/Portable/Completion/CompletionServiceWithProviders.cs
  src/Features/Core/Portable/ConvertForEachToFor/AbstractConvertForEachToForCodeRefactoringProvider.cs
  src/Features/Core/Portable/Diagnostics/AnalyzerHelper.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/RegexCharClass.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/RegexParser.cs
  src/Features/Core/Portable/QuickInfo/CommonSemanticQuickInfoProvider.cs
  src/Features/Core/Portable/Shared/Extensions/SyntaxTokenListExtensions.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.cs
  src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs
  src/VisualStudio/Core/Def/Implementation/Diagnostics/VisualStudioDiagnosticAnalyzerService.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/RoslynDefinitionBucket.cs
  src/VisualStudio/Core/Def/Implementation/Options/LocalUserRegistryOptionPersister.cs
  src/VisualStudio/Core/Def/Interactive/VsInteractiveWindowProvider.cs
  src/Workspaces/Core/Portable/Diagnostics/Extensions.cs
  src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs
  src/Workspaces/Core/Portable/Options/EditorConfig/EditorConfigFileGenerator.cs
  src/Workspaces/Core/Portable/Shared/Extensions/INamespaceSymbolExtensions.cs
  src/Workspaces/Core/Portable/SymbolKey/SymbolKey.NamespaceSymbolKey.cs
  src/Workspaces/Core/Portable/SymbolKey/SymbolKey.ParameterSymbolKey.cs
  src/Workspaces/Core/Portable/SymbolKey/SymbolKey.SymbolKeyReader.cs
  src/Workspaces/Core/Portable/Workspace/Solution/DocumentState.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/CodeStyleOption2`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/FlowAnalysis/CustomDataFlowAnalysis.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.Walker.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyle.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/Serialization/SymbolSpecification.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/EditDistance.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/StringEscapeEncoder.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/TaskExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs
Labels: Area-IDE

#50369 Remove CA1821 suppressions
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/InvisibleEditor.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/GlobalUndoServiceFactory.WorkspaceGlobalUndoTransaction.cs
Labels: Area-IDE, Community

#50367 Remove IDE0055 suppression
  src/Compilers/CSharp/Portable/Symbols/NullableFlowStateExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/TypeParameterSymbol.cs
Labels: Area-Compilers

#50200 Disallow setting init-only property in nested initializer
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_WithExpression.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InitOnlyMemberTests.cs
Labels: Area-Compilers, New Language Feature - Records

#50366 Remove suppression
  src/Compilers/Core/Portable/InternalUtilities/ImmutableArrayExtensions.cs
Labels: Area-Compilers

#50184 Add regression test for relative indentation
  src/EditorFeatures/CSharpTest/Formatting/Indentation/SmartIndenterTests.cs
Labels: Area-IDE

#50387 Use IEventListener to register workspaces for LSP instead of inside AbstractPackage
  src/VisualStudio/Core/Def/Implementation/LanguageClient/VisualStudioLspWorkspaceRegistrationEventListener.cs
  src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractPackage`2.cs
Labels: Area-IDE, CloudEnv, auto-merge

#50388 [LSP] In brace completion only add a new line between the braces if none exist
  src/Features/CSharp/Portable/BraceCompletion/CurlyBraceCompletionService.cs
  src/Features/LanguageServer/ProtocolUnitTests/OnAutoInsert/OnAutoInsertTests.cs
Labels: Area-IDE, CloudEnv, auto-merge

#50392 Switch to using deconstruction for KeyValuePair
  src/Analyzers/Core/Analyzers/AbstractBuiltInCodeStyleDiagnosticAnalyzer.cs
  src/Analyzers/Core/CodeFixes/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs
  src/EditorFeatures/DiagnosticsTestUtilities/MoveToNamespace/AbstractMoveToNamespaceTests.cs
  src/EditorFeatures/Test/CodeGeneration/CodeGenerationTests.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionBatchFixAllProvider.cs
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionCodeFixProvider.GlobalSuppressMessageFixAllCodeAction.cs
  src/Features/Core/Portable/LanguageServices/SymbolDisplayService/AbstractSymbolDisplayService.AnonymousTypes.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/Suppression/VisualStudioSuppressionFixService.cs
  src/VisualStudio/Core/Test.Next/Mocks/TestOptionSet.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine_ProjectProcessing.cs
  src/Workspaces/Core/Portable/FindSymbols/StreamingProgressCollector.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Metadata.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Source.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex.ExtensionMethodInfo.cs
  src/Workspaces/Core/Portable/Options/SerializableOptionSet.WorkspaceOptionSet.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_BulkPopulateIds.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectDependencyGraph.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/CoreTest/SolutionTests/ProjectDependencyGraphTests.cs
  src/Workspaces/MSBuildTest/FileSet.cs
  src/Workspaces/Remote/ServiceHub/Host/SolutionAssetCache.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/FlowAnalysis/LValueFlowCaptureProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.BasicBlockAnalysisData.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/BKTree.Builder.cs
Labels: Area-IDE

#50397 Support parenthesized expressions in IDE0031
  src/Analyzers/CSharp/Tests/UseNullPropagation/UseNullPropagationTests.cs
  src/Analyzers/Core/Analyzers/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs
  src/Analyzers/Core/CodeFixes/UseNullPropagation/AbstractUseNullPropagationCodeFixProvider.cs
Labels: Area-IDE

#50344 Rename SyntaxPartKind.RecordName to RecordClassName
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Types.cs
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.cs
  src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Core/Portable/SymbolDisplay/SymbolDisplayPartKind.cs
  src/Features/Core/Portable/CodeLens/CodeLensReferencesService.cs
  src/Features/Core/Portable/Common/SymbolDisplayPartKindTags.cs
  src/Workspaces/Core/Portable/Classification/Classifier.cs
Labels: Area-Compilers

#50385 Throw a better exception when reading past the end of a stream
  src/Workspaces/Remote/Core/RemoteHostAssetSerialization.cs
Labels: Area-IDE

#50402 Dispose pooled object
  src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/ItemManager.cs
Labels: Area-IDE, auto-merge

#50404 Remove client role from C# interactive
  src/VisualStudio/CSharp/Impl/Interactive/Commands.vsct
Labels: Area-IDE, CloudEnv

#50405 Add ProjectOperationBenchmarks
  src/Tools/IdeCoreBenchmarks/ProjectOperationBenchmarks.cs
Labels: Area-IDE

#50156 Implement SegmentedDictionary<TKey, TValue>
  src/Dependencies/Collections/Internal/HashHelpers.cs
  src/Dependencies/Collections/Internal/IDictionaryDebugView`2.cs
  src/Dependencies/Collections/Internal/InsertionBehavior.cs
  src/Dependencies/Collections/Internal/RoslynUnsafe.cs
  src/Dependencies/Collections/Microsoft.CodeAnalysis.Collections.projitems
  src/Dependencies/Collections/SegmentedArray.cs
  src/Dependencies/Collections/SegmentedDictionary`2.cs
Labels: Area-IDE

#50291 Test classification spans when testing signature help items
  src/EditorFeatures/CSharpTest/SignatureHelp/GenericNameSignatureHelpProviderTests.cs
  src/EditorFeatures/TestUtilities/SignatureHelp/AbstractSignatureHelpProviderTests.cs
  src/EditorFeatures/TestUtilities/SignatureHelp/SignatureHelpTestItem.cs
  src/Features/Core/Portable/Common/TaggedText.cs
Labels: Area-IDE, auto-merge

#50412 Update lsp version
  eng/Versions.props
Labels: Area-Infrastructure

#49863 Add one more commit character
  src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ExtensionMethodImportCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ObjectCreationCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/TypeImportCompletionProviderTests.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/EditorFeatures/TestUtilities2/Intellisense/TestState.vb
  src/Features/CSharp/Portable/Completion/CompletionProviders/ImportCompletion/ExtensionMethodImportCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/ImportCompletion/TypeImportCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/ObjectCreationCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/SymbolCompletionProvider.cs
  src/Features/Core/Portable/Completion/Log/CompletionProvidersLogger.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractImportCompletionProvider.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionTests.cs
Labels: Area-IDE

#50355 Add a couple of generator tests
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs
Labels: Area-Compilers, New Feature - Source Generators, Test

#50442 Reduce usage of WaitAndGetResult_CodeModel
  src/Features/Core/Portable/Shared/Extensions/DocumentExtensions.cs
  src/VisualStudio/CSharp/Impl/CodeModel/CSharpCodeModelService.cs
  src/VisualStudio/Core/Impl/CodeModel/AbstractCodeModelService.cs
  src/VisualStudio/Core/Impl/CodeModel/CodeModelTaskExtensions.cs
  src/VisualStudio/Core/Impl/CodeModel/FileCodeModel.cs
  src/VisualStudio/Core/Impl/CodeModel/FileCodeModel_Events.cs
  src/VisualStudio/VisualBasic/Impl/CodeModel/VisualBasicCodeModelService.vb
Labels: Area-IDE

#49194 Implement IVsEditorFactory4
  eng/Versions.props
  src/VisualStudio/CSharp/Impl/Microsoft.VisualStudio.LanguageServices.CSharp.csproj
  src/VisualStudio/Core/Def/Implementation/AbstractEditorFactory.cs
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/VisualStudio/VisualBasic/Impl/Microsoft.VisualStudio.LanguageServices.VisualBasic.vbproj
Labels: Area-IDE

#50449 Add InternalsVisibleTo for VS Mac
  src/EditorFeatures/Core.Cocoa/Microsoft.CodeAnalysis.EditorFeatures.Cocoa.csproj
Labels: Area-Infrastructure

#50176 Don't check initializer on static record ctor
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs
Labels: Area-Compilers, New Language Feature - Records

#49268 Enable test scenarios now supported by CLR
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
Labels: Area-Compilers, Test, Test-Scenario

#50446 Run Windows release builds using AzDO windows-2019 image
  azure-pipelines.yml
  eng/pipelines/build-windows-job.yml
Labels: Area-Infrastructure

#50436 Add an entry for the master branch to PublishData.json
  eng/config/PublishData.json
Labels: Area-Infrastructure

#50488 Add missing cocoa package to publish data
  eng/config/PublishData.json
Labels: Area-Infrastructure

#50480 Avoid thread pool starvation in IDiagnosticUpdateSource.GetDiagnostics
  src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs
  src/EditorFeatures/Test/Diagnostics/DiagnosticServiceTests.cs
  src/EditorFeatures/Test/Diagnostics/MockDiagnosticService.cs
  src/EditorFeatures/TestUtilities/Squiggles/TestDiagnosticTagProducer.cs
  src/Features/Core/Portable/Diagnostics/AbstractHostDiagnosticUpdateSource.cs
  src/Features/Core/Portable/Diagnostics/DefaultDiagnosticAnalyzerService.cs
  src/Features/Core/Portable/Diagnostics/DiagnosticAnalyzerService_UpdateSource.cs
  src/Features/Core/Portable/Diagnostics/DiagnosticService.cs
  src/Features/Core/Portable/Diagnostics/IDiagnosticService.cs
  src/Features/Core/Portable/Diagnostics/IDiagnosticServiceExtensions.cs
  src/Features/Core/Portable/Diagnostics/IDiagnosticUpdateSource.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueDiagnosticUpdateSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/VisualStudioBaseDiagnosticListTable.LiveTableDataSource.cs
  src/VisualStudio/Core/Def/Implementation/TaskList/ExternalErrorDiagnosticUpdateSource.cs
  src/VisualStudio/Core/Test.Next/Services/LspDiagnosticsTests.cs
  src/VisualStudio/Core/Test/Diagnostics/DefaultDiagnosticUpdateSourceTests.vb
  src/VisualStudio/Core/Test/Diagnostics/DiagnosticTableDataSourceTests.vb
  src/VisualStudio/Core/Test/Diagnostics/ExternalDiagnosticUpdateSourceTests.vb
Labels: Area-IDE

#49776 Update DSRN to 16.9.0
  eng/Versions.props
Labels: Area-Infrastructure

#50416 Add tracing support to LSP
  eng/Versions.props
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DocumentPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/RequestContext.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.QueueItem.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs
  src/Features/LanguageServer/Protocol/ILspLogger.cs
  src/Setup/DevDivInsertionFiles/DevDivInsertionFiles.csproj
  src/VisualStudio/Core/Def/Implementation/LanguageClient/AbstractInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/AlwaysActivateInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/LiveShareInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/LogHubLspLogger.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/RazorInProcLanguageClient.cs
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/VisualStudio/Core/Test.Next/Services/LspDiagnosticsTests.cs
  src/VisualStudio/LiveShare/Impl/AbstractGoToDefinitionWithFindUsagesServiceHandler.cs
  src/VisualStudio/LiveShare/Impl/Shims/TypeScriptHandlerShims.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageClient/XamlInProcLanguageClient.cs
Labels: Area-IDE, auto-merge

#50509 Insert `static` when fully qualifying in a `using` declaration
  src/EditorFeatures/CSharpTest/FullyQualify/FullyQualifyTests.cs
  src/Features/CSharp/Portable/FullyQualify/CSharpFullyQualifyCodeFixProvider.cs
  src/Features/Core/Portable/FullyQualify/AbstractFullyQualifyCodeFixProvider.SymbolResult.cs
  src/Features/Core/Portable/FullyQualify/AbstractFullyQualifyCodeFixProvider.cs
  src/Features/VisualBasic/Portable/FullyQualify/VisualBasicFullyQualifyCodeFixProvider.vb
Labels: Area-IDE, auto-merge

#50322 Ensure that query expressions fully bind expressions
  docs/compilers/CSharp/Compiler Breaking Changes - post VS2019.md
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Query.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/QueryTests.cs
Labels: Area-Compilers

#48097 Update CSharpSyntaxFacts for records
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
Labels: Area-IDE, Community

#50510 Handle ImplicitObjectCreationExpressionSyntax in some places where ObjectCreationExpressionSyntax has special treatment.
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/CSharpExtensions.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxFacts.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/ImplicitObjectCreationTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs
  src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetSemanticInfoTests.cs
Labels: Area-Compilers

#50350 Some improvement to target type completion
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/AbstractCSharpCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ExtensionMethodImportCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/EditorFeatures/TestUtilities/Completion/AbstractCompletionProviderTests.cs
  src/Features/Core/Portable/Completion/Providers/AbstractRecommendationServiceBasedCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/CompletionUtilities.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractExtensionMethodImportCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/IRemoteExtensionMethodImportCompletionService.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/SerializableImportCompletionItem.cs
  src/Features/Core/Portable/Completion/Providers/SymbolCompletionItem.cs
  src/Workspaces/Remote/ServiceHub/Services/ExtensionMethodImportCompletion/RemoteExtensionMethodImportCompletionService.cs
Labels: Area-IDE

#50414 Enable consumption of init-only properties in VB.
  src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InitOnlyMemberTests.cs
  src/Compilers/Test/Utilities/VisualBasic/MockSymbols.vb
  src/Compilers/Test/Utilities/VisualBasic/TestOptions.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Attributes.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Invocation.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_ObjectInitializer.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Statements.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_XmlLiterals.vb
  src/Compilers/VisualBasic/Portable/Errors/Errors.vb
  src/Compilers/VisualBasic/Portable/LanguageVersion.vb
  src/Compilers/VisualBasic/Portable/Parser/ParserFeature.vb
  src/Compilers/VisualBasic/Portable/PublicAPI.Unshipped.txt
  src/Compilers/VisualBasic/Portable/Symbols/ErrorMethodSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEMethodSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/MethodSignatureComparer.vb
  src/Compilers/VisualBasic/Portable/Symbols/MethodSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/PropertySignatureComparer.vb
  src/Compilers/VisualBasic/Portable/Symbols/PropertySymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/ReducedExtensionMethodSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Retargeting/RetargetingMethodSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/SignatureOnlyMethodSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/CustomModifierUtils.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/ImplementsHelper.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/LambdaSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/OverrideHidingHelper.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberContainerTypeSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMethodSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceNamedTypeSymbol_ComClass.vb
  src/Compilers/VisualBasic/Portable/Symbols/SubstitutedMethodSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Symbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/SynthesizedSymbols/SynthesizedDelegateMethodSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/SynthesizedSymbols/SynthesizedGlobalMethodBase.vb
  src/Compilers/VisualBasic/Portable/Symbols/SynthesizedSymbols/SynthesizedMethodBase.vb
  src/Compilers/VisualBasic/Portable/Symbols/TypeSymbolExtensions.vb
  src/Compilers/VisualBasic/Portable/Symbols/Wrapped/WrappedMethodSymbol.vb
  src/Compilers/VisualBasic/Portable/VBResources.resx
  src/Compilers/VisualBasic/Portable/xlf/VBResources.cs.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.de.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.es.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.fr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.it.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ja.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ko.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pl.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pt-BR.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ru.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.tr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hans.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hant.xlf
  src/Compilers/VisualBasic/Test/CommandLine/CommandLineTests.vb
  src/Compilers/VisualBasic/Test/Semantic/Semantics/InitOnlyMemberTests.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/CustomModifiersTests.vb
  src/ExpressionEvaluator/VisualBasic/Source/ExpressionCompiler/Symbols/EEMethodSymbol.vb
Labels: Area-Compilers, New Language Feature - Records

#50541 Report an attempt to handle an event of a shared WithEvents variable in derived type.
  src/Compilers/VisualBasic/Portable/Errors/Errors.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberMethodSymbol.vb
  src/Compilers/VisualBasic/Portable/VBResources.resx
  src/Compilers/VisualBasic/Portable/xlf/VBResources.cs.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.de.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.es.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.fr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.it.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ja.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ko.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pl.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pt-BR.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ru.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.tr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hans.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hant.xlf
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/SymbolErrorTests.vb
Labels: Area-Compilers, Tenet-Reliability

#50356 Find references in generated documents
  src/EditorFeatures/Core/FindUsages/IDefinitionsAndReferencesFactory.cs
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.FieldSymbols.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.IndexerSymbols.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.LabelSymbols.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.Literals.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.LocalFunctions.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.NamedTypeSymbols.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.NamespaceSymbols.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.OperatorSymbols.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.OrdinaryMethodSymbols.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.ParameterSymbol.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.PropertySymbols.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.RangeVariableSymbol.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.Tuples.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.XmlDocSymbols.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.vb
  src/EditorFeatures/Test2/Rename/RenameEngineResult.vb
  src/EditorFeatures/TestUtilities/Workspaces/TestHostDocument.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestHostProject.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace_Create.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace_XmlConsumption.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/ContainingTypeColumnDefinition.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Contexts/AbstractTableDataSourceFindUsagesContext.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Contexts/WithReferencesFindUsagesContext.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Contexts/WithoutReferencesFindUsagesContext.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/AbstractDocumentSpanEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/AbstractItemEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/DefinitionItemEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/DocumentSpanEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/Entry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/MetadataDefinitionItemEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/SimpleMessageEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/FindReferencesTableControlEventProcessorProvider.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/FindUsagesOptions.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/IFindAllReferencesWindowExtensions.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/ISupportsNavigation.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/NameMetadata.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/RoslynDefinitionBucket.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/StreamingFindUsagesPresenter.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/TableEntriesSnapshot.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/VisualStudioDefinitionsAndReferencesFactory.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpSourceGenerators.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/FindReferencesWindow_InProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/FindReferencesWindow_OutOfProc.cs
  src/Workspaces/Core/Portable/FindSymbols/FindLiterals/FindLiteralsSearchEngine.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Project.cs
  src/Workspaces/TestSourceGenerator/HelloWorldGenerator.cs
Labels: Area-IDE, auto-merge

#50540 Make analyzer non-configurable
  src/Analyzers/Core/Analyzers/ConvertAnonymousTypeToTuple/AbstractConvertAnonymousTypeToTupleDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/EnforceOnBuildValues.cs
Labels: Area-Analyzers

#50318 Simplify common linq invocation patterns
  src/Analyzers/CSharp/Analyzers/CSharpAnalyzers.projitems
  src/Analyzers/CSharp/Analyzers/SimplifyLinqExpression/CSharpSimplifyLinqExpressionDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/CSharpCodeFixes.projitems
  src/Analyzers/CSharp/CodeFixes/SimplifyLinqExpression/CSharpSimplifyLinqExpressionCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/CSharpAnalyzers.UnitTests.projitems
  src/Analyzers/CSharp/Tests/SimplifyLinqExpression/CSharpSimplifyLinqExpressionFixAllTests.cs
  src/Analyzers/CSharp/Tests/SimplifyLinqExpression/CSharpSimplifyLinqExpressionTests.cs
  src/Analyzers/Core/Analyzers/Analyzers.projitems
  src/Analyzers/Core/Analyzers/AnalyzersResources.resx
  src/Analyzers/Core/Analyzers/EnforceOnBuildValues.cs
  src/Analyzers/Core/Analyzers/IDEDiagnosticIds.cs
  src/Analyzers/Core/Analyzers/SimplifyLinqExpression/AbstractSimplifyLinqExpressionDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.cs.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.de.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.es.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.fr.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.it.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.ja.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.ko.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.pl.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.pt-BR.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.ru.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.tr.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.zh-Hans.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.zh-Hant.xlf
  src/Analyzers/Core/CodeFixes/CodeFixes.projitems
  src/Analyzers/Core/CodeFixes/PredefinedCodeFixProviderNames.cs
  src/Analyzers/Core/CodeFixes/SimplifyLinqExpression/AbstractSimplifyLinqExpressionCodeFixProvider`3.cs
  src/Analyzers/VisualBasic/Analyzers/SimplifyLinqExpression/VisualBasicSimplifyLinqExpressionDiagnosticAnalyzer.vb
  src/Analyzers/VisualBasic/Analyzers/VisualBasicAnalyzers.projitems
  src/Analyzers/VisualBasic/CodeFixes/SimplifyLinqExpression/VisualBasicSimplifyLinqExpressionCodeFixProvider.vb
  src/Analyzers/VisualBasic/CodeFixes/VisualBasicCodeFixes.projitems
  src/Analyzers/VisualBasic/Tests/SimplifyLinqExpression/VisualBasicSimplifyLinqExpressionFixAllTests.vb
  src/Analyzers/VisualBasic/Tests/SimplifyLinqExpression/VisualBasicSimplifyLinqExpressionTests.vb
  src/Analyzers/VisualBasic/Tests/VisualBasicAnalyzers.UnitTests.projitems
  src/Compilers/Test/Core/Traits/Traits.cs
  src/EditorFeatures/Test/Diagnostics/IDEDiagnosticIDConfigurationTests.cs
Labels: Area-IDE

#50452 Include underlying type in enum decl syntax when generating it from a symbol
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
  src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs
  src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb
  src/Workspaces/VisualBasicTest/CodeGeneration/SyntaxGeneratorTests.vb
Labels: Area-IDE, Community

#50212 Consider types having a valid GetEnumerator for pluralization
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs
Labels: Area-IDE, Community

#49632 Enum values completion provider for C#
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/EnumAndCompletionListTagCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/TypeInferrer/TypeInferrerTests.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/EditorFeatures/TestUtilities2/Intellisense/TestState.vb
  src/Features/CSharp/Portable/Completion/CompletionProviders/EnumAndCompletionListTagCompletionProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/IntegerUtilities.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs
Labels: Area-IDE, Community

#50308 Show inline type hint for implicit object creation
  src/EditorFeatures/Core/InlineHints/InlineHintsDataTaggerProvider.cs
  src/EditorFeatures/Test2/InlineHints/CSharpInlineTypeHintsTests.vb
  src/Features/CSharp/Portable/InlineHints/CSharpInlineTypeHintsService.cs
  src/Features/Core/Portable/InlineHints/AbstractInlineTypeHintsService.cs
  src/Features/Core/Portable/InlineHints/InlineHintsOptions.cs
  src/Features/Core/Portable/InlineHints/TypeHint.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
Labels: Area-IDE, Community

#50590 Add test showing working behavior.
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.LocalSymbols.vb
Labels: Area-IDE, auto-merge

#50564 move language specific methods to common base class
  src/Analyzers/CSharp/Analyzers/SimplifyLinqExpression/CSharpSimplifyLinqExpressionDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/SimplifyLinqExpression/AbstractSimplifyLinqExpressionDiagnosticAnalyzer.cs
  src/Analyzers/VisualBasic/Analyzers/SimplifyLinqExpression/VisualBasicSimplifyLinqExpressionDiagnosticAnalyzer.vb
Labels: Area-IDE

#50554 Support converting anon types to records in C# 9 and up.
  src/EditorFeatures/CSharpTest/ConvertAnonymousTypeToClass/ConvertAnonymousTypeToClassTests.cs
  src/Features/Core/Portable/ConvertAnonymousTypeToClass/AbstractConvertAnonymousTypeToClassCodeRefactoringProvider.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Workspaces/CSharp/Portable/CodeGeneration/NamedTypeGenerator.cs
  src/Workspaces/Core/Portable/CodeGeneration/CodeGenerationSymbolFactory.cs
  src/Workspaces/Core/Portable/CodeGeneration/INamedTypeSymbolExtensions.cs
  src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationConstructorInfo.cs
  src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationConstructorSymbol.cs
  src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationNamedTypeSymbol.cs
  src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationTypeSymbol.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE

#50583 Extract common code in completion providers.
  src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceTypeCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/KeywordCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/ObjectCreationCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/PartialTypeCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/PreprocessorCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/SymbolCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/AbstractKeywordCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/AbstractObjectCreationCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/AbstractPartialTypeCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/AbstractPreprocessorCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/AbstractRecommendationServiceBasedCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs
  src/Features/VisualBasic/Portable/Completion/CompletionProviders/CompletionListTagCompletionProvider.vb
  src/Features/VisualBasic/Portable/Completion/CompletionProviders/EnumCompletionProvider.vb
  src/Features/VisualBasic/Portable/Completion/CompletionProviders/HandlesClauseCompletionProvider.vb
  src/Features/VisualBasic/Portable/Completion/CompletionProviders/ImplementsClauseCompletionProvider.vb
  src/Features/VisualBasic/Portable/Completion/CompletionProviders/KeywordCompletionProvider.vb
  src/Features/VisualBasic/Portable/Completion/CompletionProviders/ObjectCreationCompletionProvider.vb
  src/Features/VisualBasic/Portable/Completion/CompletionProviders/PartialTypeCompletionProvider.vb
  src/Features/VisualBasic/Portable/Completion/CompletionProviders/PreprocessorCompletionProvider.vb
  src/Features/VisualBasic/Portable/Completion/CompletionProviders/SymbolCompletionProvider.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CSharpWorkspaceExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/CSharpSyntaxContextService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/ContextQuery/ISyntaxContextService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/VisualBasicSyntaxContextService.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/VisualBasicWorkspaceExtensions.projitems
Labels: Area-IDE, auto-merge

#50547 Make SourceGeneratedDocument.SourceGenerator internal
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratedDocument.cs
Labels: Area-IDE

#50545 Error on malformed IAsyncEnumerable await foreach
  docs/compilers/CSharp/Compiler Breaking Changes - post VS2019.md
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAwaitForeachTests.cs
Labels: Area-Compilers

#50132 Extract IFindDefinitionService into to the features layer
  src/EditorFeatures/CSharp/GoToDefinition/CSharpGoToDefinitionService.cs
  src/EditorFeatures/CSharp/GoToDefinition/CSharpGoToSymbolService.cs
  src/EditorFeatures/Core.Wpf/Peek/PeekableItemSource.cs
  src/EditorFeatures/Core/GoToDefinition/AbstractGoToDefinitionService.cs
  src/EditorFeatures/Core/GoToDefinition/AbstractGoToSymbolService.cs
  src/EditorFeatures/Core/GoToDefinition/IGoToDefinitionService.cs
  src/EditorFeatures/Core/GoToDefinition/IGoToSymbolService.cs
  src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionCommandHandlerTests.vb
  src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionTests.vb
  src/EditorFeatures/VisualBasic/GoToDefinition/VisualBasicGoToDefinitionService.vb
  src/Features/CSharp/Portable/GoToDefinition/CSharpFindDefinitionService.cs
  src/Features/CSharp/Portable/GoToDefinition/CSharpGoToDefinitionSymbolService.cs
  src/Features/Core/Portable/GoToDefinition/AbstractFindDefinitionService.cs
  src/Features/Core/Portable/GoToDefinition/AbstractGoToDefinitionSymbolService.cs
  src/Features/Core/Portable/GoToDefinition/IFindDefinitionService.cs
  src/Features/Core/Portable/GoToDefinition/IGoToDefinitionSymbolService.cs
  src/Features/Core/Portable/Navigation/NavigableItemFactory.cs
  src/Features/LanguageServer/Protocol/Handler/Definitions/AbstractGoToDefinitionHandler.cs
  src/Features/VisualBasic/Portable/GoToDefinition/VisualBasicFindDefinitionService.vb
  src/Features/VisualBasic/Portable/GoToDefinition/VisualBasicGoToDefinitionSymbolService.vb
  src/Tools/ExternalAccess/FSharp/GoToDefinition/IFSharpFindDefinitionService.cs
  src/Tools/ExternalAccess/FSharp/Internal/GoToDefinition/FSharpFindDefinitionService.cs
Labels: Area-IDE

#50544 Fix cancellation behavior for source generator callbacks
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs
Labels: Area-Compilers

#50287 Add config to publish data for 16.10 branch
  eng/config/PublishData.json
Labels: Area-Infrastructure, auto-merge

#50620 Fix nullable bool option converter
  src/VisualStudio/Core/Impl/Options/Converters/NullableBoolOptionConverter.cs
Labels: Area-IDE

#50593 Make navigation cancellable
  src/EditorFeatures/Core.Wpf/InlineRename/InlineRenameService.cs
  src/EditorFeatures/Core.Wpf/Interactive/InteractiveDocumentNavigationService.cs
  src/EditorFeatures/Core.Wpf/NavigableSymbols/NavigableSymbolService.NavigableSymbol.cs
  src/EditorFeatures/Core.Wpf/NavigateTo/NavigateToItemDisplay.cs
  src/EditorFeatures/Core.Wpf/Peek/PeekableItemSource.cs
  src/EditorFeatures/Core/CommandHandlers/AbstractGoToCommandHandler.cs
  src/EditorFeatures/Core/Extensibility/NavigationBar/AbstractNavigationBarItemService.cs
  src/EditorFeatures/Core/GoToDefinition/AbstractGoToDefinitionService.cs
  src/EditorFeatures/Core/GoToDefinition/AbstractGoToSymbolService.cs
  src/EditorFeatures/Core/GoToDefinition/GoToDefinitionHelpers.cs
  src/EditorFeatures/Core/Host/IStreamingFindReferencesPresenter.cs
  src/EditorFeatures/Core/Implementation/CodeActions/CodeActionEditHandlerService.cs
  src/EditorFeatures/Core/Implementation/ExtractInterface/AbstractExtractInterfaceCommandHandler.cs
  src/EditorFeatures/TestUtilities2/Utilities/GoToHelpers/MockDocumentNavigationService.vb
  src/EditorFeatures/TestUtilities2/Utilities/MockDocumentNavigationServiceProvider.vb
  src/EditorFeatures/VisualBasic/NavigationBar/VisualBasicNavigationBarItemService.vb
  src/Features/Core/Portable/Common/NavigationOperation.cs
  src/Features/Core/Portable/DocumentSpanExtensions.cs
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/Api/VSTypeScriptDocumentNavigationServiceWrapper.cs
  src/Features/Core/Portable/FindUsages/DefinitionItem.DocumentLocationDefinitionItem.cs
  src/Features/Core/Portable/FindUsages/DefinitionItem.cs
  src/Features/Core/Portable/Navigation/DefaultDocumentNavigationService.cs
  src/Features/Core/Portable/Navigation/IDocumentNavigationService.cs
  src/Tools/ExternalAccess/FSharp/Internal/Editor/FSharpNavigationBarItemService.cs
  src/Tools/ExternalAccess/FSharp/Navigation/FSharpDocumentNavigationService.cs
  src/Tools/ExternalAccess/FSharp/Navigation/IFSharpDocumentNavigationService.cs
  src/VisualStudio/Core/Def/Implementation/CallHierarchy/CallHierarchyDetail.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/DocumentSpanEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/MetadataDefinitionItemEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/FindReferencesTableControlEventProcessorProvider.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/ISupportsNavigation.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/RoslynDefinitionBucket.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/VisualStudioDefinitionsAndReferencesFactory.cs
  src/VisualStudio/Core/Def/Implementation/Progression/GraphNavigatorExtension.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/AbstractTableControlEventProcessorProvider.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/AbstractTableEntriesSnapshot.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/TableEntriesFactory.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/VisualStudioBaseDiagnosticListTable.LiveTableDataSource.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/VisualStudioBaseTodoListTable.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/VisualStudioDiagnosticListTable.BuildTableDataSource.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/SourceGeneratedFileItems/SourceGeneratedFileItem.cs
  src/VisualStudio/LiveShare/Test/MockDocumentNavigationServiceFactory.cs
Labels: Area-IDE, auto-merge

#50516 Fix code error in markdown file
  docs/wiki/New-Language-Features-in-VB-14.md
Labels: Area-Compilers, Documentation

#50517 Update Contributing-Code.md
  docs/wiki/Contributing-Code.md
Labels: Area-Compilers, Documentation

#50647 Ignore invalid constants in PatternExplainer
  src/Compilers/CSharp/Portable/Binder/PatternExplainer.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs
Labels: Area-Compilers

#50622 Fix parsing of generatedfilesout option
  src/Compilers/CSharp/Portable/CommandLine/CSharpCommandLineParser.cs
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
Labels: Area-Compilers

#49557 Update AugmentingGenerator missing }
  docs/features/source-generators.cookbook.md
Labels: Area-Compilers, Documentation

#50640 Binder.DecodeTextBinary - handle an invalid syntax.
  src/Compilers/VisualBasic/Portable/Binding/Binder_Utils.vb
  src/Compilers/VisualBasic/Test/Semantic/Semantics/OptionApis.vb
Labels: Area-Compilers

#50621 Don't include namespace symbol in LSP goto definition result
  src/Features/LanguageServer/Protocol/Handler/Definitions/AbstractGoToDefinitionHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Definitions/GoToDefinitionTests.cs
Labels: Area-IDE, CloudEnv

#50648 log which workspace we find documents in
  .gitignore
  src/Features/LanguageServer/Protocol/Handler/RequestContext.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/VisualStudioLspWorkspaceRegistrationService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-IDE

#50644 Uses the TryGetHistory of undo history registry
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioTextUndoHistoryWorkspaceServiceFactory.cs
Labels: Area-IDE, auto-merge

#50674 Fix VB legacy project system interop definition
  src/VisualStudio/VisualBasic/Impl/ProjectSystemShim/Interop/VBCompilerOptions.vb
Labels: Area-IDE

#50553 Fix bug in the logic we have that extracts paths for CPS analyzer nodes
  src/VisualStudio/Core/Impl/SolutionExplorer/DiagnosticItem/CpsUtilities.cs
  src/VisualStudio/Core/Test/SolutionExplorer/CpsUtilitiesTests.vb
Labels: Area-IDE

#50652 Fix cursor location on enter inside razor brace completion
  src/Features/CSharp/Portable/BraceCompletion/CurlyBraceCompletionService.cs
  src/Features/LanguageServer/ProtocolUnitTests/OnAutoInsert/OnAutoInsertTests.cs
Labels: Area-IDE, CloudEnv

#50683 Revert "Merge pull request #49194 from Mohit-Chakraborty/dev/mohitc/ImplementIVsEF4"
  eng/Versions.props
  src/VisualStudio/CSharp/Impl/Microsoft.VisualStudio.LanguageServices.CSharp.csproj
  src/VisualStudio/Core/Def/Implementation/AbstractEditorFactory.cs
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/VisualStudio/VisualBasic/Impl/Microsoft.VisualStudio.LanguageServices.VisualBasic.vbproj
Labels: Area-IDE, auto-merge

#50632 Fix link
  docs/wiki/Runtime-code-generation-using-Roslyn-compilations-in-.NET-Core-App.md
Labels: Area-Infrastructure, Community

#50616 Attribute lock time to analyzers
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs
Labels: Area-Analyzers

#50692 Move to .NET SDK 5.0.102
  docs/contributing/Building, Debugging, and Testing on Windows.md
  global.json
Labels: Area-Infrastructure

#49626 Run tests on Helix
  .vscode/launch.json
  eng/Version.Details.xml
  eng/build.ps1
  eng/build.sh
  eng/pipelines/test-unix-job.yml
  eng/pipelines/test-windows-job.yml
  eng/prepare-tests.ps1
  eng/prepare-tests.sh
  global.json
  src/Tools/PrepareTests/MinimizeUtil.cs
  src/Tools/PrepareTests/PrepareTests.csproj
  src/Tools/PrepareTests/Program.cs
  src/Tools/PrepareTests/README.md
  src/Tools/Source/RunTests/AssemblyScheduler.cs
  src/Tools/Source/RunTests/Options.cs
  src/Tools/Source/RunTests/ProcessRunner.cs
  src/Tools/Source/RunTests/ProcessTestExecutor.cs
  src/Tools/Source/RunTests/Program.cs
  src/Tools/Source/RunTests/RunTests.csproj
  src/Tools/Source/RunTests/TestRunner.cs
Labels: Area-Infrastructure

#50703 Add a incrementing session id to our loghub logs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs
Labels: Area-IDE, auto-merge

#50707 Trace information in our logs indicating if we were/weren't able to map an lsp request to a document.
  src/Features/LanguageServer/Protocol/Handler/RequestContext.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.QueueItem.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs
  src/Features/LanguageServer/Protocol/ILspLogger.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/LogHubLspLogger.cs
  src/VisualStudio/LiveShare/Impl/AbstractGoToDefinitionWithFindUsagesServiceHandler.cs
  src/VisualStudio/LiveShare/Impl/Shims/TypeScriptHandlerShims.cs
Labels: Area-IDE, auto-merge

#49083 Remove workarounds for fixed MessagePack bugs
  eng/Versions.props
  src/Setup/DevDivInsertionFiles/DevDivInsertionFiles.csproj
  src/Workspaces/Remote/Core/Serialization/ImmutableCollectionMessagePackResolver.cs
  src/Workspaces/Remote/Core/Serialization/MessagePackFormatters.cs
Labels: Area-IDE

#50705 Revert "Revert "Merge pull request #49194 from Mohit-Chakraborty/dev/…
  eng/Versions.props
  src/VisualStudio/CSharp/Impl/Microsoft.VisualStudio.LanguageServices.CSharp.csproj
  src/VisualStudio/Core/Def/Implementation/AbstractEditorFactory.cs
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/VisualStudio/VisualBasic/Impl/Microsoft.VisualStudio.LanguageServices.VisualBasic.vbproj
Labels: Area-IDE

#50709 Link ExternalAccess folder for TypeScript
  src/EditorFeatures/Core.Cocoa/Microsoft.CodeAnalysis.EditorFeatures.Cocoa.csproj
Labels: Area-IDE

#50725 Fix formatting for tuple pointers
  src/Workspaces/CSharpTest/Formatting/FormattingTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/TokenBasedFormattingRule.cs
Labels: Area-IDE

#50743 Some more logging around request queue initialization, shutdown, errors, and finding documents
  src/Features/LanguageServer/Protocol/Handler/DocumentChanges/DidChangeHandler.cs
  src/Features/LanguageServer/Protocol/Handler/RequestContext.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs
  src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs
Labels: Area-IDE

#50697 Add report-ci-times.ps1
  scripts/all-ci-times.xlsx
  scripts/report-ci-times.ps1
Labels: Area-Infrastructure

#50716 respond to LSP protocol breaking change
  eng/Versions.props
Labels: Area-IDE, CloudEnv

#50680 Fix generator related asserts
  src/EditorFeatures/Core.Cocoa/InlineRename/AbstractEditorInlineRenameService.cs
  src/EditorFeatures/Core.Wpf/InlineRename/AbstractEditorInlineRenameService.cs
  src/EditorFeatures/Test2/Rename/RenameNonRenameableSymbols.vb
  src/Features/Core/Portable/DocumentHighlighting/AbstractDocumentHighlightsService.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder.cs
Labels: Area-IDE

#50722 VB: Make behavior of FindImplementationForInterfaceMember API on an interface consistent across source and metadata
  src/Compilers/CSharp/Test/Symbol/Symbols/InterfaceImplementationTests.cs
  src/Compilers/VisualBasic/Portable/Symbols/TypeSymbol.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/DefaultInterfaceImplementationTests.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/InterfaceImplementationTests.vb
Labels: Area-Compilers

#50615 Order PDB document table to match compiler arguments
  src/Compilers/CSharp/Test/Emit/PDB/CSharpDeterministicBuildCompilationTests.cs
  src/Compilers/CSharp/Test/Emit/PDB/CheckSumTest.cs
  src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs
  src/Compilers/Core/Portable/PEWriter/CompilationOptionNames.cs
  src/Compilers/Core/Portable/PEWriter/MetadataWriter.PortablePdb.cs
  src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs
  src/Compilers/Test/Core/PDB/DeterministicBuildCompilationTestHelpers.cs
  src/Compilers/VisualBasic/Test/Emit/Emit/EditAndContinue/EditAndContinuePdbTests.vb
  src/Compilers/VisualBasic/Test/Emit/PDB/ChecksumTests.vb
  src/Compilers/VisualBasic/Test/Emit/PDB/PDBExternalSourceDirectiveTests.vb
  src/Compilers/VisualBasic/Test/Emit/PDB/PDBLambdaTests.vb
Labels: Area-Compilers

#50172 Avoid recomputing generated sources for the same input
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/CachingSourceGenerator.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/IsExternalInit.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/SourceGenerator.cs
Labels: Area-Compilers

#50768 Ensure generate method doesn't generate into source generated files
  src/EditorFeatures/CSharpTest/Diagnostics/GenerateMethod/GenerateMethodTests.cs
  src/Workspaces/Core/Portable/CodeGeneration/AbstractCodeGenerationService_FindDeclaration.cs
Labels: Area-IDE

#50650 Fix race condition in records
  src/Compilers/CSharp/Portable/Symbols/FieldOrPropertyInitializer.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SimpleProgramNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs
Labels: Area-Compilers, New Language Feature - Records

#50431 Add threading context to CodeModel
  src/VisualStudio/CSharp/Impl/CodeModel/CSharpCodeModelService.cs
  src/VisualStudio/CSharp/Impl/CodeModel/CSharpCodeModelServiceFactory.cs
  src/VisualStudio/Core/Impl/CodeModel/AbstractCodeModelService.cs
  src/VisualStudio/Core/Impl/CodeModel/CodeModelTaskExtensions.cs
  src/VisualStudio/Core/Impl/CodeModel/FileCodeModel.cs
  src/VisualStudio/Core/Impl/CodeModel/FileCodeModel_CodeGen.cs
  src/VisualStudio/Core/Impl/CodeModel/InternalElements/AbstractCodeElement.cs
  src/VisualStudio/TestUtilities2/CodeModel/Mocks/MockTextManagerAdapter.vb
  src/VisualStudio/VisualBasic/Impl/CodeModel/VisualBasicCodeModelService.vb
  src/VisualStudio/VisualBasic/Impl/CodeModel/VisualBasicCodeModelServiceFactory.vb
Labels: Area-IDE

#50776 Change storage api to not expose checksums directly
  src/VisualStudio/CSharp/Test/PersistentStorage/AbstractPersistentStorageTests.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Persistence.cs
  src/Workspaces/Core/Portable/Storage/AbstractPersistentStorageService.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.Accessor.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_DocumentSerialization.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_ProjectSerialization.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_SolutionSerialization.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/AbstractPersistentStorage.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/IChecksummedPersistentStorage.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/NoOpPersistentStorage.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Checksum.cs
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassificationCache/RemoteSemanticClassificationCacheService.cs
Labels: Area-IDE, auto-merge

#50643 EnC OOP - part 2: Switch to Debugger.Contracts
  eng/Versions.props
  src/EditorFeatures/Core/Implementation/EditAndContinue/EditAndContinueDiagnosticAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/Contracts/ActiveStatementFlags.cs
  src/Features/Core/Portable/EditAndContinue/Contracts/DebugSessionFlags.cs
  src/Features/Core/Portable/EditAndContinue/Contracts/IManagedEditAndContinueDebuggerService.cs
  src/Features/Core/Portable/EditAndContinue/Contracts/ManagedActiveStatementDebugInfo.cs
  src/Features/Core/Portable/EditAndContinue/Contracts/ManagedActiveStatementUpdate.cs
  src/Features/Core/Portable/EditAndContinue/Contracts/ManagedEditAndContinueAvailability.cs
  src/Features/Core/Portable/EditAndContinue/Contracts/ManagedEditAndContinueAvailabilityStatus.cs
  src/Features/Core/Portable/EditAndContinue/Contracts/ManagedExceptionRegionUpdate.cs
  src/Features/Core/Portable/EditAndContinue/Contracts/ManagedInstructionId.cs
  src/Features/Core/Portable/EditAndContinue/Contracts/ManagedMethodId.cs
  src/Features/Core/Portable/EditAndContinue/Contracts/ManagedModuleMethodId.cs
  src/Features/Core/Portable/EditAndContinue/Contracts/ManagedModuleUpdate.cs
  src/Features/Core/Portable/EditAndContinue/Contracts/ManagedModuleUpdateStatus.cs
  src/Features/Core/Portable/EditAndContinue/Contracts/ManagedModuleUpdates.cs
  src/Features/Core/Portable/EditAndContinue/Contracts/SequencePointUpdates.cs
  src/Features/Core/Portable/EditAndContinue/Contracts/SourceLineUpdate.cs
  src/Features/Core/Portable/EditAndContinue/Contracts/SourceSpan.cs
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/VisualStudio/Core/Def/Implementation/EditAndContinue/ManagedEditAndContinueLanguageService.cs
  src/VisualStudio/Core/Def/Implementation/EditAndContinue/ModuleUtilities.cs
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/VisualStudio/Core/Test.Next/EditAndContinue/ModuleUtilitiesTests.cs
Labels: Area-Interactive, Interactive-EnC

#50715 Check the nameof context when commit using semicolon
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/EditorFeatures/TestUtilities2/Intellisense/TestState.vb
  src/Features/CSharp/Portable/Completion/CompletionProviders/SymbolCompletionProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ITypeSymbolExtensions.cs
Labels: Area-IDE, auto-merge

#50794 Handle deeply nested field pattern in NullableWalker
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesVsPatterns.cs
Labels: Area-Compilers

#50754 Add IXamlLanguageServerFeedbackService interface
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/XamlLanguageServerProtocol.cs
  src/VisualStudio/Xaml/Impl/Implementation/XamlProjectService.cs
  src/VisualStudio/Xaml/Impl/Telemetry/IRequestScope.cs
  src/VisualStudio/Xaml/Impl/Telemetry/IXamlLanguageServerFeedbackService.cs
Labels: Area-IDE

#50662 Support finding generated documents in Navigate To
  src/Compilers/Core/Portable/Collections/ImmutableArrayExtensions.cs
  src/EditorFeatures/CSharpTest/NavigateTo/NavigateToTests.cs
  src/Features/Core/Portable/FindUsages/IRemoteFindUsagesService.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.InProcess.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.cs
  src/Features/Core/Portable/Remote/RemoteArguments.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpSourceGenerators.cs
Labels: Area-IDE

#50791 Record VB 16.9 work
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation, Language-VB

#50789 Record shipping versions for C# 9
  docs/wiki/NuGet-packages.md
Labels: Area-Compilers, Documentation

#50801 Optimize the synchronous fast path in SymbolTreeInfoIncrementalAnalyzer
  src/Features/Core/Portable/IncrementalCaches/SymbolTreeInfoIncrementalAnalyzer.cs
Labels: Area-IDE

#50419 Allow access to semantic model during syntax walk
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/SyntaxAwareGeneratorTests.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Core/Portable/SourceGeneration/GeneratorContexts.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorInfo.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorState.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorSyntaxWalker.cs
  src/Compilers/Core/Portable/SourceGeneration/ISyntaxReceiver.cs
  src/Compilers/Core/Portable/SourceGeneration/SyntaxContextReceiverAdaptor.cs
Labels: Area-Compilers, New Feature - Source Generators

#50805 Fix tab traversal in ExtractBase/ExtractInterface
  src/VisualStudio/Core/Def/Implementation/CommonControls/NewTypeDestinationSelection.xaml
  src/VisualStudio/Core/Def/Implementation/CommonControls/NewTypeDestinationSelection.xaml.cs
  src/VisualStudio/Core/Def/Implementation/CommonControls/NewTypeDestinationSelectionViewModel.cs
  src/VisualStudio/Core/Def/Implementation/ExtractClass/ExtractClassDialog.xaml
  src/VisualStudio/Core/Def/Implementation/ExtractClass/ExtractClassDialog.xaml.cs
  src/VisualStudio/Core/Def/Implementation/ExtractInterface/ExtractInterfaceDialog.xaml
  src/VisualStudio/Core/Def/Implementation/ExtractInterface/ExtractInterfaceDialog.xaml.cs
Labels: Area-IDE, auto-merge

#50809 Fix merge of 16.10 branch into master
  src/EditorFeatures/TestUtilities2/Intellisense/TestState.vb
Labels: Area-IDE, Area-Infrastructure, auto-merge

#50772 Make IPersistentStorage acquisition async.
  src/EditorFeatures/Test/Diagnostics/DiagnosticDataSerializerTests.cs
  src/EditorFeatures/Test/Preview/PreviewWorkspaceTests.cs
  src/Features/Core/Portable/SolutionCrawler/State/AbstractAnalyzerState.cs
  src/Tools/AnalyzerRunner/IncrementalAnalyzerRunner.cs
  src/Tools/IdeBenchmarks/SQLitePersistentStorageBenchmark.cs
  src/Tools/IdeCoreBenchmarks/FindReferencesBenchmarks.cs
  src/Tools/IdeCoreBenchmarks/NavigateToBenchmarks.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/AbstractPersistentStorageTests.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/SQLiteV2PersistentStorageTests.cs
  src/Workspaces/Core/Portable/Diagnostics/DiagnosticDataSerializer.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Serialization.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Persistence.cs
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
  src/Workspaces/Core/Portable/Storage/AbstractPersistentStorageService.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorageService.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/IChecksummedPersistentStorageService.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/IPersistentStorageService.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/NoOpPersistentStorageService.cs
  src/Workspaces/CoreTest/Host/WorkspaceServices/TestPersistenceService.cs
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassificationCache/RemoteSemanticClassificationCacheService.cs
Labels: Area-IDE, auto-merge

#50189 Implement ImmutableSegmentedDictionary<TKey, TValue>
  src/Compilers/Core/CodeAnalysisTest/Collections/BadHasher.cs
  src/Compilers/Core/CodeAnalysisTest/Collections/DebuggerAttributes.cs
  src/Compilers/Core/CodeAnalysisTest/Collections/EverythingEqual.cs
  src/Compilers/Core/CodeAnalysisTest/Collections/GenericParameterHelper.cs
  src/Compilers/Core/CodeAnalysisTest/Collections/ImmutableDictionaryBuilderTestBase.cs
  src/Compilers/Core/CodeAnalysisTest/Collections/ImmutableDictionaryBuilderTestBase.nonnetstandard.cs
  src/Compilers/Core/CodeAnalysisTest/Collections/ImmutableDictionaryTestBase.cs
  src/Compilers/Core/CodeAnalysisTest/Collections/ImmutableDictionaryTestBase.nonnetstandard.cs
  src/Compilers/Core/CodeAnalysisTest/Collections/ImmutableSegmentedDictionaryBuilderTest.cs
  src/Compilers/Core/CodeAnalysisTest/Collections/ImmutableSegmentedDictionaryTest.cs
  src/Compilers/Core/CodeAnalysisTest/Collections/ImmutableSegmentedDictionaryTest.nonnetstandard.cs
  src/Compilers/Core/CodeAnalysisTest/Collections/ImmutablesTestBase.cs
  src/Compilers/Core/CodeAnalysisTest/Collections/ImmutablesTestBase.nonnetstandard.cs
  src/Compilers/Core/CodeAnalysisTest/Collections/TestExtensionsMethods.cs
  src/Compilers/Core/CodeAnalysisTest/Collections/TestExtensionsMethods.nonnetstandard.cs
  src/Dependencies/Collections/ImmutableSegmentedDictionary.cs
  src/Dependencies/Collections/ImmutableSegmentedDictionary`2+Builder+KeyCollection.cs
  src/Dependencies/Collections/ImmutableSegmentedDictionary`2+Builder+ValueCollection.cs
  src/Dependencies/Collections/ImmutableSegmentedDictionary`2+Builder.cs
  src/Dependencies/Collections/ImmutableSegmentedDictionary`2+Enumerator.cs
  src/Dependencies/Collections/ImmutableSegmentedDictionary`2+KeyCollection+Enumerator.cs
  src/Dependencies/Collections/ImmutableSegmentedDictionary`2+KeyCollection.cs
  src/Dependencies/Collections/ImmutableSegmentedDictionary`2+PrivateInterlocked.cs
  src/Dependencies/Collections/ImmutableSegmentedDictionary`2+ValueCollection+Enumerator.cs
  src/Dependencies/Collections/ImmutableSegmentedDictionary`2+ValueCollection.cs
  src/Dependencies/Collections/ImmutableSegmentedDictionary`2.cs
  src/Dependencies/Collections/Microsoft.CodeAnalysis.Collections.projitems
  src/Dependencies/Collections/RoslynImmutableInterlocked.cs
Labels: Area-Compilers, Area-IDE

#50810 VB init-only: add tests for ReDim, Erase and dictionary access.
  src/Compilers/VisualBasic/Test/Semantic/Semantics/InitOnlyMemberTests.vb
Labels: Area-Compilers, Test

#50827 Use server logging on source build job
  eng/build.sh
Labels: Area-Infrastructure

#50813 Allow access to semantic model during syntax walk (#50419)
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/SyntaxAwareGeneratorTests.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Core/Portable/SourceGeneration/GeneratorContexts.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorInfo.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorState.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorSyntaxWalker.cs
  src/Compilers/Core/Portable/SourceGeneration/ISyntaxReceiver.cs
  src/Compilers/Core/Portable/SourceGeneration/SyntaxContextReceiverAdaptor.cs
Labels: Area-Compilers
