Repository dotnet/roslyn, pull requests merged in 2022-04, with the labels that each got.

#60500 Introduce a better system for keeping track if a buffer is visible or not in tagging
  azure-pipelines.yml
  src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs
  src/EditorFeatures/CSharpTest/Interactive/BraceMatching/InteractiveBraceHighlightingTests.cs
  src/EditorFeatures/Core.Cocoa/Structure/StructureTaggerProvider.cs
  src/EditorFeatures/Core.Wpf/InlineDiagnostics/InlineDiagnosticsTaggerProvider.cs
  src/EditorFeatures/Core.Wpf/LineSeparators/LineSeparatorTaggerProvider.cs
  src/EditorFeatures/Core.Wpf/StringIndentation/StringIndentationTaggerProvider.cs
  src/EditorFeatures/Core.Wpf/Structure/StructureTaggerProvider.cs
  src/EditorFeatures/Core.Wpf/Workspaces/WpfTextBufferVisibilityTracker.cs
  src/EditorFeatures/Core/BraceMatching/BraceHighlightingViewTaggerProvider.cs
  src/EditorFeatures/Core/Classification/Semantic/AbstractSemanticOrEmbeddedClassificationViewTaggerProvider.cs
  src/EditorFeatures/Core/Classification/Semantic/EmbeddedLanguageClassificationViewTaggerProvider.cs
  src/EditorFeatures/Core/Classification/Semantic/SemanticClassificationViewTaggerProvider.cs
  src/EditorFeatures/Core/Diagnostics/AbstractDiagnosticsAdornmentTaggerProvider.cs
  src/EditorFeatures/Core/Diagnostics/AbstractDiagnosticsTaggerProvider.cs
  src/EditorFeatures/Core/Diagnostics/DiagnosticsClassificationTaggerProvider.cs
  src/EditorFeatures/Core/Diagnostics/DiagnosticsSquiggleTaggerProvider.cs
  src/EditorFeatures/Core/Diagnostics/DiagnosticsSuggestionTaggerProvider.cs
  src/EditorFeatures/Core/EditAndContinue/ActiveStatementTaggerProvider.cs
  src/EditorFeatures/Core/Editor/ITextBufferAssociatedViewService.cs
  src/EditorFeatures/Core/Editor/TextBufferAssociatedViewService.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/VSTypeScriptAsynchronousTaggerProvider.cs
  src/EditorFeatures/Core/InlineHints/InlineHintsDataTaggerProvider.cs
  src/EditorFeatures/Core/KeywordHighlighting/HighlighterViewTaggerProvider.cs
  src/EditorFeatures/Core/NavigationBar/NavigationBarController.cs
  src/EditorFeatures/Core/NavigationBar/NavigationBarControllerFactoryService.cs
  src/EditorFeatures/Core/NavigationBar/NavigationBarController_ModelComputation.cs
  src/EditorFeatures/Core/ReferenceHighlighting/ReferenceHighlightingViewTaggerProvider.cs
  src/EditorFeatures/Core/Shared/Tagging/EventSources/TaggerEventSources.ViewSpanChangedEventSource.cs
  src/EditorFeatures/Core/Structure/AbstractStructureTaggerProvider.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.cs
  src/EditorFeatures/Core/Tagging/AsynchronousTaggerProvider.cs
  src/EditorFeatures/Core/Tagging/AsynchronousViewTaggerProvider.cs
  src/EditorFeatures/Core/Workspaces/ITextBufferVisibilityTracker.cs
  src/EditorFeatures/Test/Diagnostics/DiagnosticsSquiggleTaggerProviderTests.cs
  src/EditorFeatures/Test/Preview/PreviewWorkspaceTests.cs
  src/EditorFeatures/Test/Tagging/AsynchronousTaggerTests.cs
  src/EditorFeatures/Test2/Classification/ClassificationTests.vb
  src/EditorFeatures/Test2/KeywordHighlighting/AbstractKeywordHighlightingTests.vb
  src/EditorFeatures/Test2/ReferenceHighlighting/AbstractReferenceHighlightingTests.vb
  src/EditorFeatures/TestUtilities/BraceHighlighting/AbstractBraceHighlightingTests.cs
  src/EditorFeatures/VisualBasicTest/BraceMatching/BraceHighlightingTests.vb
  src/Features/Core/Portable/SolutionCrawler/IDocumentTrackingServiceExtensions.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_IncrementalAnalyzer.cs
  src/VisualStudio/Core/Def/InheritanceMargin/InheritanceMarginTaggerProvider.cs
Labels: Area-IDE

#60492 Enable NRT in AbstractSyncNamespaceCodeRefactoringProvider
  src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpSyncNamespaceCodeRefactoringProvider.cs
  src/Features/Core/Portable/CodeRefactorings/SyncNamespace/AbstractSyncNamespaceCodeRefactoringProvider.MoveFileCodeAction.cs
  src/Features/Core/Portable/CodeRefactorings/SyncNamespace/AbstractSyncNamespaceCodeRefactoringProvider.State.cs
  src/Features/Core/Portable/CodeRefactorings/SyncNamespace/AbstractSyncNamespaceCodeRefactoringProvider.cs
Labels: Area-IDE

#60371 Pause taggers when they are not visible.
  src/EditorFeatures/Core/NavigationBar/NavigationBarController_ModelComputation.cs
  src/EditorFeatures/Core/Shared/Tagging/EventSources/AbstractTaggerEventSource.cs
  src/EditorFeatures/Core/Shared/Tagging/EventSources/TaggerEventSources.CompositionEventSource.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs
  src/EditorFeatures/Core/Tagging/CompilationAvailableTaggerEventSource.cs
  src/EditorFeatures/Core/Tagging/ITaggerEventSource.cs
Labels: Area-IDE

#60482 Update Language Feature Status.md
  docs/Language Feature Status.md
Labels: Area-Compilers

#60297 Check accessibility before offering "Implement interface" codefix
  src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs
  src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.AccessibilityHelper.cs
  src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs
  src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.cs
Labels: Area-IDE, Community

#60480 Use provider type name for CodeAction telemetry for code actions...
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActions/CodeFixSuggestedAction.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActions/FixAllSuggestedAction.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActions/SuggestedAction.cs
  src/EditorFeatures/Core/LanguageServer/Handlers/CodeActions/CodeActionHelpers.cs
  src/Features/CSharp/Portable/ImplementInterface/AbstractChangeImplementionCodeRefactoringProvider.cs
  src/Features/Core/Portable/AddConstructorParametersFromMembers/AddConstructorParametersFromMembersCodeRefactoringProvider.cs
  src/Features/Core/Portable/AddImport/CodeActions/InstallPackageAndAddImportCodeAction.cs
  src/Features/Core/Portable/AddParameter/AbstractAddParameterCodeFixProvider.cs
  src/Features/Core/Portable/AliasAmbiguousType/AbstractAliasAmbiguousTypeCodeFixProvider.cs
  src/Features/Core/Portable/CodeFixes/AddExplicitCast/AbstractAddExplicitCastCodeFixProvider.cs
  src/Features/Core/Portable/CodeFixes/Configuration/ConfigureCodeStyle/ConfigureCodeStyleOptionCodeFixProvider.cs
  src/Features/Core/Portable/CodeFixes/Configuration/ConfigureSeverity/ConfigureSeverityLevelCodeFixProvider.cs
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionBatchFixAllProvider.cs
  src/Features/Core/Portable/CodeRefactorings/CodeRefactoringService.cs
  src/Features/Core/Portable/ConvertAnonymousType/AbstractConvertAnonymousTypeToTupleCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertTupleToStruct/AbstractConvertTupleToStructCodeRefactoringProvider.cs
  src/Features/Core/Portable/GenerateComparisonOperators/GenerateComparisonOperatorsCodeRefactoringProvider.cs
  src/Features/Core/Portable/InlineMethod/AbstractInlineMethodRefactoringProvider.cs
  src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceParameterService.cs
  src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.cs
  src/Features/Core/Portable/PullMemberUp/AbstractPullMemberUpRefactoringProvider.cs
  src/Features/Core/Portable/PullMemberUp/MembersPuller.cs
  src/Features/Core/Portable/Wrapping/AbstractCodeActionComputer.cs
  src/Features/LanguageServer/Protocol/Features/CodeFixes/CodeFixService.cs
  src/Features/LanguageServer/Protocol/Features/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs
  src/Tools/BuildActionTelemetryTable/BuildActionTelemetryTable.csproj
  src/Tools/BuildActionTelemetryTable/Program.cs
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/Panels/TelemetryPanel.xaml.cs
  src/Workspaces/Core/Portable/CodeActions/CodeAction.cs
  src/Workspaces/Core/Portable/Shared/Extensions/TelemetryExtensions.cs
  src/Workspaces/CoreTest/Shared/Extensions/TelemetryExtensions/TelemetryExtensionTests.cs
Labels: Area-IDE

#60554 Cleanup unused resources in Features layer
  src/EditorFeatures/CSharpTest/Diagnostics/GenerateType/GenerateTypeTests.cs
  src/EditorFeatures/VisualBasicTest/Diagnostics/GenerateType/GenerateTypeTests.vb
  src/Features/CSharp/Portable/CSharpFeaturesResources.resx
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.cs.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.de.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.es.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.fr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.it.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ja.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ko.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pl.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pt-BR.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ru.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.tr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hans.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hant.xlf
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Features/VisualBasic/Portable/VBFeaturesResources.resx
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.cs.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.de.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.es.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.fr.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.it.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.ja.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.ko.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.pl.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.pt-BR.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.ru.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.tr.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.zh-Hans.xlf
  src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.zh-Hant.xlf
Labels: Area-IDE, Community

#60556 Update Roslyn.Diagnostics.Analyzers and remove RS0005 suppressions
  .editorconfig
  eng/Versions.props
  eng/config/globalconfigs/NonShipping.globalconfig
  eng/config/globalconfigs/Shipping.globalconfig
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionCodeFixProvider.PragmaBatchFixHelpers.cs
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionCodeFixProvider.RemoveSuppressionCodeAction.BatchFixer.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DefaultFixAllProviderHelpers.cs
Labels: Area-IDE, Community

#60538 Remove unnecessary `<Compile Remove`
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/Roslyn.VisualStudio.DiagnosticsWindow.csproj
Labels: Area-Infrastructure, Community

#60501 Support parsing for Unsigned Right Shift operator
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/Binder/EarlyWellKnownAttributeBinder.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/OperatorFacts.cs
  src/Compilers/CSharp/Portable/Generated/CSharp.Generated.g4
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Internal.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Main.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Syntax.Generated.cs
  src/Compilers/CSharp/Portable/Parser/Blender.Reader.cs
  src/Compilers/CSharp/Portable/Parser/DocumentationCommentParser.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/Parser/Lexer.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
  src/Compilers/CSharp/Portable/Syntax/SyntaxFacts.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxKindFacts.cs
  src/Compilers/CSharp/Test/Syntax/IncrementalParsing/BinaryExpression.cs
  src/Compilers/CSharp/Test/Syntax/IncrementalParsing/CompoundAssignment.cs
  src/Compilers/CSharp/Test/Syntax/LexicalAndXml/CrefLexerTests.cs
  src/Compilers/CSharp/Test/Syntax/LexicalAndXml/NameAttributeValueLexerTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/CrefParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ExpressionParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ImplicitObjectCreationParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/NameParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ParsingErrorRecoveryTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/TypeArgumentListParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs
  src/Compilers/Test/Core/TestResource.resx
Labels: Area-Compilers, New Feature - UnsignedRightShift

#60564 Note auto-default merged in feature status doc
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation

#60559 Update PublishData.json for 17.3 P1
  azure-pipelines-integration-corehost.yml
  azure-pipelines-integration.yml
  azure-pipelines.yml
  eng/config/PublishData.json
Labels: Area-Infrastructure

#60298 Add Rebuild badge to README
  README.md
Labels: Area-Infrastructure

#60561 Avoid using --blame-crash with CollectDumps
  src/Tools/Source/RunTests/ITestExecutor.cs
  src/Tools/Source/RunTests/ProcessTestExecutor.cs
  src/Tools/Source/RunTests/Program.cs
Labels: Area-Infrastructure

#60573 Make NotificationOption2 a serializable struct
  src/Workspaces/Core/Portable/CodeStyle/CodeStyleOption.cs
  src/Workspaces/Core/Portable/CodeStyle/CodeStyleOption2_operators.cs
  src/Workspaces/Core/Portable/CodeStyle/NotificationOption2_operators.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/CodeStyleHelpers.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/CodeStyleOption2`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/CodeStyleOptions2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/NotificationOption2.cs
Labels: Area-IDE

#60580 Fix the Compiler VSIX extension so it works with CPS projects again
  eng/Versions.props
  src/Compilers/Extension/Roslyn.Compilers.Extension.csproj
  src/Compilers/Extension/SetGlobalGlobalPropertiesForCPS.cs
Labels: Area-Compilers

#60587 Update status for UTF8 literals and checked operators
  docs/Language Feature Status.md
Labels: Area-Compilers

#60484 [LSP] Modify semanticTokens `isFinalized` logic
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHelpers.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensRangeHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/SemanticTokensRangeTests.cs
Labels: Area-IDE, Approved to merge, LSP

#60335 [semi-auto-props]: Support lambdas and local functions, eliminate duplicate code
  src/Compilers/CSharp/Portable/Binder/BinderFactory.BinderFactoryVisitor.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Compilation/AttributeSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/InitializerSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/MethodBodySemanticModel.cs
  src/Compilers/CSharp/Portable/Symbols/MemberSymbolExtensions.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PropertyFieldKeywordTests.cs
Labels: Area-Compilers, Community

#59683 Add support for yield return to CompleteStatementCommandHandler
  src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs
  src/EditorFeatures/CSharpTest/CompleteStatement/CSharpCompleteStatementCommandHandlerTests.cs
Labels: Area-IDE, Community

#59790 Workspace config options
  src/EditorFeatures/Core/Diagnostics/AbstractDiagnosticsTaggerProvider.cs
  src/EditorFeatures/Core/Remote/RemoteHostOptions.cs
  src/EditorFeatures/Core/Shared/Options/InternalFeatureOnOffOptions.cs
  src/EditorFeatures/Test/Diagnostics/DiagnosticAnalyzerServiceTests.cs
  src/EditorFeatures/Test/Preview/PreviewWorkspaceTests.cs
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/EditorFeatures/TestUtilities/LanguageServer/TestWorkspaceConfigurationService.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.CachedDocumentSearch.cs
  src/Features/Core/Portable/NavigateTo/IRemoteNavigateToSearchService.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.cs
  src/Features/Core/Portable/Workspace/ProjectCacheService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.ProjectState.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_IncrementalAnalyzer.cs
  src/Features/LanguageServer/Protocol/Features/Options/WorkspaceConfigurationOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/WorkspaceConfigurationService.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Microsoft.CodeAnalysis.LanguageServer.Protocol.csproj
  src/Tools/AnalyzerRunner/AnalyzerRunnerWorkspaceConfigurationService.cs
  src/Tools/AnalyzerRunner/IncrementalAnalyzerRunner.cs
  src/Tools/IdeBenchmarks/SQLitePersistentStorageBenchmark.cs
  src/Tools/IdeCoreBenchmarks/ClassificationBenchmarks.cs
  src/Tools/IdeCoreBenchmarks/FindReferencesBenchmarks.cs
  src/Tools/IdeCoreBenchmarks/NavigateToBenchmarks.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/Core/Def/Telemetry/VisualStudioSyntaxTreeConfigurationService.cs
  src/VisualStudio/Core/Def/Workspace/SourceGeneratedFileManager.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpSourceGenerators.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/StateResetInProcess.cs
  src/VisualStudio/IntegrationTest/TestUtilities/WellKnownGlobalOptions.cs
  src/VisualStudio/LiveShare/Test/AbstractLiveShareRequestHandlerTests.cs
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/Workspaces/Core/Portable/Classification/AbstractClassificationService.cs
  src/Workspaces/Core/Portable/Classification/IRemoteSemanticClassificationService.cs
  src/Workspaces/Core/Portable/FindSymbols/Shared/AbstractSyntaxIndex_Persistence.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Metadata.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Serialization.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Source.cs
  src/Workspaces/Core/Portable/Storage/PersistentStorageExtensions.cs
  src/Workspaces/Core/Portable/Storage/StorageOptions.cs
  src/Workspaces/Core/Portable/Telemetry/IRemoteProcessTelemetryService.cs
  src/Workspaces/Core/Portable/Workspace/ISyntaxTreeConfigurationService.cs
  src/Workspaces/Core/Portable/Workspace/IWorkspaceConfigurationService.cs
  src/Workspaces/Remote/Core/ServiceHubRemoteHostClient.cs
  src/Workspaces/Remote/ServiceHub/Services/NavigateToSearch/RemoteNavigateToSearchService.cs
  src/Workspaces/Remote/ServiceHub/Services/ProcessTelemetry/RemoteProcessTelemetryService.cs
  src/Workspaces/Remote/ServiceHub/Services/ProcessTelemetry/RemoteSyntaxTreeConfigurationService.cs
  src/Workspaces/Remote/ServiceHub/Services/ProcessTelemetry/RemoteWorkspaceConfigurationService.cs
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassification/RemoteSemanticClassificationService.Caching.cs
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassification/RemoteSemanticClassificationService.cs
Labels: Area-IDE

#60575 Ensure current OOP calls for the same solution-checksum can share the same OOP solution computation
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/VisualStudio/Core/Test.Next/Services/SolutionServiceTests.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspaceManager.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs
  src/Workspaces/Remote/ServiceHub/Services/CodeLensReferences/RemoteCodeLensReferencesService.cs
  src/Workspaces/Remote/ServiceHub/Services/ConvertTupleToStructCodeRefactoringProvider/RemoteConvertTupleToStructCodeRefactoringService.cs
  src/Workspaces/Remote/ServiceHub/Services/DependentTypeFinder/RemoteDependentTypeFinderService.cs
  src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/RemoteDiagnosticAnalyzerService.cs
  src/Workspaces/Remote/ServiceHub/Services/DocumentHighlights/RemoteDocumentHighlightsService.cs
  src/Workspaces/Remote/ServiceHub/Services/EditAndContinue/RemoteEditAndContinueService.cs
  src/Workspaces/Remote/ServiceHub/Services/EncapsulateField/RemoteEncapsulateFieldService.cs
  src/Workspaces/Remote/ServiceHub/Services/ExtensionMethodImportCompletion/RemoteExtensionMethodImportCompletionService.cs
  src/Workspaces/Remote/ServiceHub/Services/FindUsages/RemoteFindUsagesService.cs
  src/Workspaces/Remote/ServiceHub/Services/InheritanceMargin/RemoteInheritanceMarginService.cs
  src/Workspaces/Remote/ServiceHub/Services/MissingImportDiscovery/RemoteMissingImportDiscoveryService.cs
  src/Workspaces/Remote/ServiceHub/Services/NavigateToSearch/RemoteNavigateToSearchService.cs
  src/Workspaces/Remote/ServiceHub/Services/NavigationBar/RemoteNavigationBarItemService.cs
  src/Workspaces/Remote/ServiceHub/Services/Renamer/RemoteRenamerService.cs
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassification/RemoteSemanticClassificationService.cs
  src/Workspaces/Remote/ServiceHub/Services/StackTraceExplorer/RemoteStackTraceExplorerService.cs
  src/Workspaces/Remote/ServiceHub/Services/SymbolFinder/RemoteSymbolFinderService.cs
  src/Workspaces/Remote/ServiceHub/Services/Tagging/RemoteTaggerCompilationAvailableService.cs
  src/Workspaces/Remote/ServiceHub/Services/UnusedReferences/RemoteUnusedReferenceAnalysisService.cs
  src/Workspaces/Remote/ServiceHub/Services/ValueTracking/RemoteValueTrackingService.cs
Labels: Area-IDE

#59297 Add support for unsafe local functions in IDE0062 code fix
  src/Analyzers/CSharp/Tests/MakeLocalFunctionStatic/MakeLocalFunctionStaticTests.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
Labels: Area-IDE, Community

#60579 Track "numeric IntPtr" feature
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation

#60558 Colorize `async` as keyword in some cases
  src/EditorFeatures/CSharpTest/Classification/TotalClassifierTests.cs
  src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.cs
Labels: Area-IDE, Community

#60611 Merge main-vs-deps to main
  src/EditorFeatures/CSharpTest/Classification/TotalClassifierTests.cs
  src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.cs
Labels: Area-Infrastructure

#60610 Change insertion branch
  eng/config/PublishData.json
Labels: Area-Infrastructure

#60560 Support built-in unsigned right shift operators.
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/BinaryOperatorEasyOut.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/BinaryOperatorOverloadResolution.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/OperatorFacts.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/OperatorKind.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/OperatorKindExtensions.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitOperators.cs
  src/Compilers/CSharp/Portable/Compilation/BuiltInOperators.cs
  src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperator.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxFacts.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxKindFacts.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IBinaryOperatorExpression.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NativeIntegerTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/UnsignedRightShiftTests.cs
  src/Compilers/Core/Portable/Operations/BinaryOperatorKind.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
Labels: Area-Compilers, New Feature - UnsignedRightShift

#59410 Implement handling of rename intent
  src/EditorFeatures/CSharpTest/Intents/GenerateConstructorIntentTests.cs
  src/EditorFeatures/CSharpTest/Intents/IntentTestsBase.cs
  src/EditorFeatures/CSharpTest/Intents/RenameIntentTests.cs
  src/EditorFeatures/Core/ExternalAccess/IntelliCode/Api/IIntentSourceProvider.cs
  src/EditorFeatures/Core/ExternalAccess/IntelliCode/IntentProcessor.cs
  src/EditorFeatures/Core/Intents/RenameIntentProvider.cs
  src/Features/Core/Portable/AddConstructorParametersFromMembers/AddConstructorParametersFromMembersCodeRefactoringProvider.cs
  src/Features/Core/Portable/GenerateConstructorFromMembers/AbstractGenerateConstructorFromMembersCodeRefactoringProvider.cs
  src/Features/Core/Portable/Intents/IntentResult.cs
  src/Features/Core/Portable/Intents/WellKnownIntents.cs
  src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
Labels: Area-IDE

#60622 Fix attribute arguments crash in main
  src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs
Labels: Area-Compilers

#60607 Pause computation of navbar items when a buffer is not visible
  src/EditorFeatures/Core/NavigationBar/NavigationBarController.cs
  src/EditorFeatures/Core/NavigationBar/NavigationBarController_ModelComputation.cs
Labels: Area-IDE

#60466 Always use text edits in completion for correctness
  src/EditorFeatures/Core/LanguageServer/Handlers/Completion/CompletionHandler.cs
  src/Features/LanguageServer/Protocol/LspOptions.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionTests.cs
  src/Tools/IdeBenchmarks/Lsp/LspCompletionBenchmarks.cs
  src/VisualStudio/Core/Def/PackageRegistration.pkgdef
Labels: Area-IDE, LSP

#60585 Instrument ReferenceCachingCS for flakiness
  src/Compilers/Server/VBCSCompilerTests/CompilerServerTests.cs
Labels: Area-Compilers

#60637 Fix our INavigableSymbol to not root an entire solution-snapshot
  src/EditorFeatures/Core.Wpf/NavigableSymbols/NavigableSymbolService.NavigableSymbol.cs
  src/EditorFeatures/Core.Wpf/NavigableSymbols/NavigableSymbolService.NavigableSymbolSource.cs
Labels: Area-IDE

#40525 Extend scope of type parameters in attributes
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md
  src/Compilers/CSharp/Portable/Binder/Binder.WithQueryLambdaParametersBinder.cs
  src/Compilers/CSharp/Portable/Binder/Binder.cs
  src/Compilers/CSharp/Portable/Binder/BinderFactory.BinderFactoryVisitor.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/Binder/BuckStopsHereBinder.cs
  src/Compilers/CSharp/Portable/Binder/ContextualAttributeBinder.cs
  src/Compilers/CSharp/Portable/Binder/HostObjectModeBinder.cs
  src/Compilers/CSharp/Portable/Binder/InContainerBinder.cs
  src/Compilers/CSharp/Portable/Binder/InMethodBinder.cs
  src/Compilers/CSharp/Portable/Binder/InSubmissionClassBinder.cs
  src/Compilers/CSharp/Portable/Binder/LocalBinderFactory.cs
  src/Compilers/CSharp/Portable/Binder/LocalScopeBinder.cs
  src/Compilers/CSharp/Portable/Binder/NameofBinder.cs
  src/Compilers/CSharp/Portable/Binder/WithClassTypeParametersBinder.cs
  src/Compilers/CSharp/Portable/Binder/WithCrefTypeParametersBinder.cs
  src/Compilers/CSharp/Portable/Binder/WithExternAliasesBinder.cs
  src/Compilers/CSharp/Portable/Binder/WithExternAndUsingAliasesBinder.cs
  src/Compilers/CSharp/Portable/Binder/WithLambdaParametersBinder.cs
  src/Compilers/CSharp/Portable/Binder/WithMethodTypeParametersBinder.cs
  src/Compilers/CSharp/Portable/Binder/WithParametersBinder.cs
  src/Compilers/CSharp/Portable/Binder/WithUsingNamespacesAndTypesBinder.cs
  src/Compilers/CSharp/Portable/Compilation/AttributeSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxNodeExtensions.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Binders/EEMethodBinder.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Binders/PlaceholderLocalBinder.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Binders/WithTypeArgumentsBinder.cs
Labels: Area-Compilers

#60650 Update versions for preview4
  eng/Versions.props
Labels: Area-Infrastructure

#60636 Pull feature-specific APIs out of ISyntaxFacts
  src/Analyzers/Core/CodeFixes/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs
  src/Features/CSharp/Portable/RemoveUnusedVariable/CSharpRemoveUnusedVariableCodeFixProvider.cs
  src/Features/Core/Portable/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs
  src/Features/Core/Portable/SplitOrMergeIfStatements/AbstractMergeIfStatementsCodeRefactoringProvider.cs
  src/Features/Core/Portable/SplitOrMergeIfStatements/Consecutive/AbstractMergeConsecutiveIfStatementsCodeRefactoringProvider.cs
  src/Features/Core/Portable/SplitOrMergeIfStatements/Consecutive/AbstractSplitIntoConsecutiveIfStatementsCodeRefactoringProvider.cs
  src/Features/Core/Portable/SplitOrMergeIfStatements/Nested/AbstractMergeNestedIfStatementsCodeRefactoringProvider.cs
  src/Features/VisualBasic/Portable/RemoveUnusedVariable/VisualBasicRemoveUnusedVariableCodeFixProvider.vb
  src/VisualStudio/CSharp/Impl/Venus/CSharpVenusBraceMatchingService.cs
  src/VisualStudio/Core/Def/Venus/ContainedDocument.cs
  src/VisualStudio/Core/Def/Venus/IVenusBraceMatchingService.cs
  src/VisualStudio/VisualBasic/Impl/Venus/VisualBasicContainedLanguage.vb
  src/VisualStudio/VisualBasic/Impl/Venus/VisualBasicVenusBraceMatchingService.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CSharpCompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpBlockFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/BlockFacts/AbstractBlockFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/BlockFacts/IBlockFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/BlockFacts/IBlockFactsExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFactsExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicBlockFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/VisualBasicCompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CSharpWorkspaceExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpBlockFactsService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpSemanticFactsService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/MoveDeclarationNearReference/AbstractMoveDeclarationNearReferenceService.State.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/SemanticsFactsService/AbstractSemanticFactsService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/SyntaxFactsService/IBlockFactsService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/LanguageServices/VisualBasicBlockFactsService.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/LanguageServices/VisualBasicSemanticFactsService.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/VisualBasicWorkspaceExtensions.projitems
Labels: Area-IDE

#60648 Fixed adding a redundant blank line when suppressing with local attribute
  src/EditorFeatures/CSharpTest/Diagnostics/Suppression/SuppressionTests.cs
  src/Features/CSharp/Portable/CodeFixes/Suppression/CSharpSuppressionCodeFixProvider.cs
Labels: Area-IDE, Community

#60604 Add ServiceHub helpers recommended in previous PR
  src/Workspaces/Remote/ServiceHub/ExternalAccess/Pythia/Api/PythiaBrokeredServiceImplementation.cs
  src/Workspaces/Remote/ServiceHub/ExternalAccess/Razor/Api/RazorBrokeredServiceImplementation.cs
  src/Workspaces/Remote/ServiceHub/ExternalAccess/UnitTesting/Api/UnitTestingBrokeredServiceImplementation.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspaceManager.cs
  src/Workspaces/Remote/ServiceHub/Services/CodeLensReferences/RemoteCodeLensReferencesService.cs
  src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/RemoteDiagnosticAnalyzerService.cs
Labels: Area-IDE

#60653 Run continuation to dispose of cancellation token source
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs
Labels: Area-IDE, LSP

#60635 Update Typescript VS interface
  src/Features/Core/Portable/Completion/CommonCompletionService.cs
  src/Features/Core/Portable/Completion/CompletionServiceWithProviders.cs
Labels: Area-IDE, Approved to merge, Community

#60667 Restore CodeStyle test projects
  Roslyn.sln
  src/CodeStyle/CSharp/Analyzers/Microsoft.CodeAnalysis.CSharp.CodeStyle.csproj
  src/CodeStyle/CSharp/CodeFixes/Microsoft.CodeAnalysis.CSharp.CodeStyle.Fixes.csproj
  src/CodeStyle/CSharp/Tests/AbstractCSharpDiagnosticProviderBasedUserDiagnosticTest_OptionHelpers.cs
  src/CodeStyle/CSharp/Tests/Microsoft.CodeAnalysis.CSharp.CodeStyle.UnitTests.csproj
  src/CodeStyle/Core/Analyzers/Microsoft.CodeAnalysis.CodeStyle.csproj
  src/CodeStyle/Core/CodeFixes/Microsoft.CodeAnalysis.CodeStyle.Fixes.csproj
  src/CodeStyle/Core/Tests/Directory.Build.props
  src/CodeStyle/Core/Tests/Microsoft.CodeAnalysis.CodeStyle.LegacyTestFramework.UnitTestUtilities.csproj
  src/CodeStyle/Core/Tests/Microsoft.CodeAnalysis.CodeStyle.UnitTestUtilities.csproj
  src/CodeStyle/VisualBasic/Analyzers/Microsoft.CodeAnalysis.VisualBasic.CodeStyle.vbproj
  src/CodeStyle/VisualBasic/CodeFixes/Microsoft.CodeAnalysis.VisualBasic.CodeStyle.Fixes.vbproj
  src/CodeStyle/VisualBasic/Tests/AbstractVisualBasicDiagnosticProviderBasedUserDiagnosticTest_OptionHelpers.vb
  src/CodeStyle/VisualBasic/Tests/Microsoft.CodeAnalysis.VisualBasic.CodeStyle.UnitTests.vbproj
  src/Compilers/Test/Core/Microsoft.CodeAnalysis.Test.Utilities.csproj
  src/EditorFeatures/DiagnosticsTestUtilities/Microsoft.CodeAnalysis.EditorFeatures.DiagnosticsTests.Utilities.csproj
  src/EditorFeatures/TestUtilities/Microsoft.CodeAnalysis.EditorFeatures.Test.Utilities.csproj
  src/Features/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.Features.csproj
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/Features/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.Features.vbproj
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
Labels: Area-Infrastructure, Community

#60654 Delay starting the work to scan for todo-items
  src/EditorFeatures/Core/TodoComment/TodoItemsUpdatedArgs.cs
  src/Features/Core/Portable/TodoComments/AbstractTodoCommentsIncrementalAnalyzer.cs
  src/Features/LanguageServer/Protocol/Features/TodoComments/InProcTodoCommentsIncrementalAnalyzer.cs
  src/Features/LanguageServer/Protocol/Features/TodoComments/InProcTodoCommentsIncrementalAnalyzerProvider.cs
  src/Features/LanguageServer/Protocol/Features/TodoComments/TodoCommentsListener.cs
  src/VisualStudio/Core/Def/TableDataSource/AbstractTable.cs
  src/VisualStudio/Core/Def/TableDataSource/VisualStudioBaseTodoListTable.cs
  src/VisualStudio/Core/Def/TodoComments/VisualStudioTodoCommentsService.cs
  src/VisualStudio/Core/Test/Diagnostics/TodoListTableDataSourceTests.vb
  src/Workspaces/Remote/ServiceHub/Services/TodoCommentsDiscovery/RemoteTodoCommentsIncrementalAnalyzerProvider.cs
Labels: Area-IDE

#60672 Trim unnessasary leading lines when removing usings
  src/Analyzers/CSharp/Tests/RemoveUnnecessaryImports/RemoveUnnecessaryImportsTests.cs
  src/Analyzers/VisualBasic/Tests/RemoveUnnecessaryImports/RemoveUnnecessaryImportsTests.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpRemoveUnnecessaryImportsService.Rewriter.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/LanguageServices/VisualBasicRemoveUnnecessaryImportsService.Rewriter.vb
Labels: Area-IDE, Community

#60658 Remove duplicate package references
  eng/Tools.props
  src/Compilers/Test/Core/Microsoft.CodeAnalysis.Test.Utilities.csproj
  src/ExpressionEvaluator/Package/ExpressionEvaluatorPackage.csproj
  src/VisualStudio/Core/Impl/Microsoft.VisualStudio.LanguageServices.Implementation.csproj
  src/VisualStudio/Core/Test.Next/Roslyn.VisualStudio.Next.UnitTests.csproj
  src/VisualStudio/Setup.Dependencies/Roslyn.VisualStudio.Setup.Dependencies.csproj
Labels: Area-Infrastructure

#60616 Support declaration and consumption of user-defined Unsigned Right Shift operator.
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/Binder_TupleOperators.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/OperatorFacts.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/OperatorKind.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/CodeGen/EmitOperators.cs
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Parser/DocumentationCommentParser.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbolBase.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxKindFacts.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IBinaryOperatorExpression.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_ICompoundAssignmentOperation.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/CheckedUserDefinedOperatorsTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/UnsignedRightShiftTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs
Labels: Area-Compilers, New Feature - UnsignedRightShift

#60531 Remove IDynamicFileInfo-added syntax trees to attempt to improve perf
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
Labels: Area-IDE, Approved to merge

#60687 Add TS external access API for ICommentSelectionService
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/Api/IVSTypeScriptCommentSlectionServiceImplementation.cs
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/Api/VSTypeScriptCommentSelectionInfo.cs
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/VSTypeScriptCommentSelectionService.cs
Labels: Area-IDE

#60577 Check val escape for initializers of fields with ref-like type
  src/Compilers/CSharp/Portable/Binder/Binder_Initializers.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/StructConstructorTests.cs
Labels: Area-Compilers

#60590 Fix crash when combining reordered arguments with params array
  src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs
Labels: Area-Compilers, Approved to merge

#60712 Use VS2022 for official build
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#60693 Share the indices we create for files that do not have PP directives in them
  src/Tools/IdeCoreBenchmarks/NavigateToBenchmarks.cs
  src/Workspaces/Core/Portable/FindSymbols/Shared/AbstractSyntaxIndex.cs
  src/Workspaces/Core/Portable/FindSymbols/Shared/AbstractSyntaxIndex_Persistence.cs
  src/Workspaces/Core/Portable/Storage/PersistentStorageExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxKinds.vb
Labels: Area-IDE

#60706 Fix flaky VSTypeScriptHandlerTests
  src/Features/LanguageServer/ProtocolUnitTests/VSTypeScriptHandlerTests.cs
Labels: Area-Infrastructure

#60494 Fix the KeybindingResetDetector
  src/VisualStudio/Core/Def/KeybindingReset/KeybindingResetDetector.cs
  src/VisualStudio/Core/Def/RoslynPackage.cs
Labels: Area-IDE

#60691 Stop switching /langver to preview for generator tests
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
Labels: Area-IDE

#60697 Allow code actions to retrieve options for any language
  src/EditorFeatures/CSharpTest/Diagnostics/Suppression/SuppressionTests.cs
  src/EditorFeatures/CSharpTest/Formatting/CodeCleanupTests.cs
  src/EditorFeatures/Core.Wpf/Suggestions/AsyncSuggestedActionsSource.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs
  src/EditorFeatures/Core/CodeActions/CodeActionOptionsStorage.cs
  src/EditorFeatures/Core/LanguageServer/Handlers/CodeActions/CodeActionHelpers.cs
  src/EditorFeatures/Core/LanguageServer/Handlers/CodeActions/CodeActionResolveHandler.cs
  src/EditorFeatures/Core/LanguageServer/Handlers/CodeActions/CodeActionsHandler.cs
  src/EditorFeatures/Core/LanguageServer/Handlers/CodeActions/RunCodeActionHandler.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/AbstractCodeActionTest.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/CSharpCodeFixVerifier`2+Test.cs
  src/EditorFeatures/DiagnosticsTestUtilities/Diagnostics/AbstractUserDiagnosticTest.cs
  src/EditorFeatures/Test/CodeFixes/CodeFixServiceTests.cs
  src/EditorFeatures/Test/CodeRefactorings/CodeRefactoringServiceTest.cs
  src/EditorFeatures/Test2/CodeFixes/CodeFixServiceTests.vb
  src/EditorFeatures/Test2/SyncNamespaces/SyncNamespacesServiceTests.vb
  src/EditorFeatures/VisualBasicTest/Formatting/CodeCleanUpTests.vb
  src/Features/CSharp/Portable/ImplementInterface/CSharpImplementInterfaceCodeFixProvider.cs
  src/Features/Core/Portable/AddImport/AbstractAddImportCodeFixProvider.cs
  src/Features/Core/Portable/AddPackage/AbstractAddPackageCodeFixProvider.cs
  src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsRefactoringProvider.cs
  src/Features/Core/Portable/CodeRefactorings/CodeRefactoringService.cs
  src/Features/Core/Portable/CodeRefactorings/ExtractMethod/AbstractExtractMethodCodeRefactoringProvider.cs
  src/Features/Core/Portable/CodeRefactorings/ICodeRefactoringService.cs
  src/Features/Core/Portable/FullyQualify/AbstractFullyQualifyCodeFixProvider.cs
  src/Features/Core/Portable/ImplementAbstractClass/AbstractImplementAbstractClassCodeFixProvider.cs
  src/Features/Core/Portable/SpellCheck/AbstractSpellCheckCodeFixProvider.cs
  src/Features/Core/Portable/SyncNamespaces/AbstractSyncNamespacesSevice.cs
  src/Features/Core/Portable/SyncNamespaces/ISyncNamespacesService.cs
  src/Features/Core/Portable/Wrapping/AbstractWrappingCodeRefactoringProvider.cs
  src/Features/LanguageServer/Protocol/Features/CodeCleanup/AbstractCodeCleanupService.cs
  src/Features/LanguageServer/Protocol/Features/CodeCleanup/ICodeCleanupService.cs
  src/Features/LanguageServer/Protocol/Features/CodeFixes/CodeFixService.cs
  src/Features/LanguageServer/Protocol/Features/CodeFixes/ICodeFixService.cs
  src/Features/LanguageServer/Protocol/Features/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs
  src/Features/VisualBasic/Portable/ImplementInterface/VisualBasicImplementInterfaceCodeFixProvider.vb
  src/Tools/ExternalAccess/OmniSharp/CodeActions/OmniSharpCodeFixContextFactory.cs
  src/VisualStudio/Core/Def/CodeCleanup/AbstractCodeCleanUpFixer.cs
  src/VisualStudio/Core/Def/SyncNamespaces/SyncNamespacesCommandHandler.cs
  src/Workspaces/Core/Portable/CodeFixes/CodeFixContext.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs
  src/Workspaces/Core/Portable/CodeRefactorings/CodeRefactoringContext.cs
  src/Workspaces/Core/Portable/ExternalAccess/VSTypeScript/Api/VSTypeScriptCodeFixContextExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/SyntaxEditorBasedCodeFixProvider.cs
Labels: Area-IDE

#60599 Grab bag of UTF8 string support in IDE features
  src/EditorFeatures/CSharp/BraceMatching/StringLiteralBraceMatcher.cs
  src/EditorFeatures/CSharp/TextStructureNavigation/CSharpTextStructureNavigatorProvider.cs
  src/EditorFeatures/CSharpTest/BraceMatching/CSharpBraceMatcherTests.cs
  src/EditorFeatures/CSharpTest/ConvertNamespace/ConvertToFileScopedNamespaceAnalyzerTests.cs
  src/EditorFeatures/CSharpTest/SplitStringLiteral/SplitStringLiteralCommandHandlerTests.cs
  src/EditorFeatures/CSharpTest/TextStructureNavigation/TextStructureNavigatorTests.cs
  src/Features/CSharp/Portable/SplitStringLiteral/SimpleStringSplitter.cs
  src/Features/CSharp/Portable/SplitStringLiteral/StringSplitter.cs
  src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs
  src/VisualStudio/CSharp/Test/F1Help/F1HelpTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTreeExtensions.cs
Labels: Area-IDE

#60663 Update csc.dll path in launch.json
  .vscode/launch.json
Labels: Area-Infrastructure

#60719 Add implement interface support for checked operators and cast operators
  src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/ConversionGenerator.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/OperatorGenerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/INamedTypeSymbolExtensions.cs
Labels: Area-IDE

#60698 Fix FAR on checked operators
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.OperatorSymbols.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/IMethodSymbolExtensions.cs
Labels: Area-IDE

#60562 handle null compilations in entry point finder
  src/VisualStudio/CSharp/Impl/ProjectSystemShim/CSharpProjectShim.ICSharpProjectSite.cs
  src/VisualStudio/CSharp/Impl/ProjectSystemShim/EntryPointFinder.cs
  src/VisualStudio/VisualBasic/Impl/ProjectSystemShim/EntryPointFinder.vb
  src/VisualStudio/VisualBasic/Impl/ProjectSystemShim/VisualBasicProject.vb
Labels: Area-IDE

#60618 Generate static abstract interface members correctly
  src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractMethodTests.cs
  src/EditorFeatures/Test/MetadataAsSource/AbstractMetadataAsSourceTests.TestContext.cs
  src/EditorFeatures/Test/MetadataAsSource/AbstractMetadataAsSourceTests.cs
  src/EditorFeatures/Test/MetadataAsSource/MetadataAsSourceTests.CSharp.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
  src/Features/Core/Portable/PullMemberUp/MembersPuller.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpCodeGenerationService.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/ConversionGenerator.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/EventGenerator.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/MethodGenerator.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/OperatorGenerator.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/PropertyGenerator.cs
  src/Workspaces/Core/Portable/CodeGeneration/CodeGenerationSymbolFactory.cs
Labels: Area-IDE

#60716 NRT enable C# EditorFeatures project.
  src/Analyzers/CSharp/Analyzers/ConvertSwitchStatementToExpression/ConvertSwitchStatementToExpressionDiagnosticAnalyzer.Analyzer.cs
  src/Analyzers/CSharp/Analyzers/InlineDeclaration/CSharpInlineDeclarationDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCompoundAssignment/Utilities.cs
  src/Analyzers/CSharp/Analyzers/UsePatternMatching/CSharpAsAndNullCheckDiagnosticAnalyzer.Analyzer.cs
  src/Analyzers/CSharp/Analyzers/UsePatternMatching/CSharpIsAndCastCheckDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/AddBraces/CSharpAddBracesCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/AddObsoleteAttribute/CSharpAddObsoleteAttributeCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/AliasAmbiguousType/CSharpAliasAmbiguousTypeCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/HideBase/HideBaseCodeFixProvider.AddNewKeywordAction.cs
  src/Analyzers/CSharp/CodeFixes/HideBase/HideBaseCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/Iterator/CSharpChangeToIEnumerableCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/MakeFieldReadonly/CSharpMakeFieldReadonlyCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/MakeStatementAsynchronous/CSharpMakeStatementAsynchronousCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/MakeStructFieldsWritable/CSharpMakeStructFieldsWritableCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/OrderModifiers/CSharpOrderModifiersCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/QualifyMemberAccess/CSharpQualifyMemberAccessCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/QualifyMemberAccess/AbstractQualifyMemberAccessCodeFixProvider.cs
  src/EditorFeatures/CSharp/BlockCommentEditing/CloseBlockCommentCommandHandler.cs
  src/EditorFeatures/CSharp/BraceMatching/AbstractCSharpBraceMatcher.cs
  src/EditorFeatures/CSharp/BraceMatching/CSharpDirectiveTriviaBraceMatcher.cs
  src/EditorFeatures/CSharp/BraceMatching/CSharpEmbeddedLanguageBraceMatcher.cs
  src/EditorFeatures/CSharp/BraceMatching/LessThanGreaterThanBraceMatcher.cs
  src/EditorFeatures/CSharp/BraceMatching/OpenCloseBraceBraceMatcher.cs
  src/EditorFeatures/CSharp/BraceMatching/OpenCloseBracketBraceMatcher.cs
  src/EditorFeatures/CSharp/BraceMatching/OpenCloseParenBraceMatcher.cs
  src/EditorFeatures/CSharp/BraceMatching/StringLiteralBraceMatcher.cs
  src/EditorFeatures/CSharp/ChangeSignature/CSharpChangeSignatureCommandHandler.cs
  src/EditorFeatures/CSharp/CommentSelection/CSharpToggleBlockCommentCommandHandler.cs
  src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs
  src/EditorFeatures/CSharp/ContentType/ContentTypeDefinitions.cs
  src/EditorFeatures/CSharp/DocumentationComments/XmlTagCompletionCommandHandler.cs
  src/EditorFeatures/CSharp/EncapsulateField/EncapsulateFieldCommandHandler.cs
  src/EditorFeatures/CSharp/EndConstruct/CSharpEndConstructGenerationService.cs
  src/EditorFeatures/CSharp/ExtractInterface/ExtractInterfaceCommandHandler.cs
  src/EditorFeatures/CSharp/ExtractMethod/ExtractMethodCommandHandler.cs
  src/EditorFeatures/CSharp/FixInterpolatedVerbatimString/FixInterpolatedVerbatimStringCommandHandler.cs
  src/EditorFeatures/CSharp/Interactive/CSharpSendToInteractiveSubmissionProvider.cs
  src/EditorFeatures/CSharp/LanguageServices/CSharpContentTypeLanguageService.cs
  src/EditorFeatures/CSharp/RenameTracking/CSharpRenameTrackingLanguageHeuristicsService.cs
  src/EditorFeatures/CSharp/SplitStringLiteral/SplitStringLiteralCommandHandler.cs
  src/Features/CSharp/Portable/AddAnonymousTypeMemberName/CSharpAddAnonymousTypeMemberNameCodeFixProvider.cs
  src/Features/CSharp/Portable/AddFileBanner/CSharpAddFileBannerCodeRefactoringProvider.cs
  src/Features/Core/Portable/AddAnonymousTypeMemberName/AbstractAddAnonymousTypeMemberNameCodeFixProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/SemanticModelExtensions.cs
Labels: Area-IDE

#60692 Fix "top-level statements" feature name to match published name
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
Labels: Area-IDE

#60707 Address PROTOTYPE comments
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md
  src/Compilers/CSharp/Portable/Binder/EarlyWellKnownAttributeBinder.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/UnsignedRightShiftTests.cs
Labels: Area-Compilers, New Feature - UnsignedRightShift

#60721 Make heading levels for warning waves documentation consistent
  docs/compilers/CSharp/Warnversion Warning Waves.md
Labels: Area-Compilers, Documentation, Community

#60689 IDE changes for "Unsigned Right Shift" feature, plus tests.
  src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxKindFacts.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/ImplicitObjectCreationTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/TargetTypedDefaultTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/UnsafeTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/UnsignedRightShiftTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/UserDefinedOperatorErrorTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/TypeArgumentListParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs
  src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxTests.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/UnsignedRightShiftTests.vb
  src/EditorFeatures/CSharpTest/Classification/SyntacticClassifierTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/OperatorCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs
  src/EditorFeatures/CSharpTest/Formatting/Indentation/SmartIndenterTests.cs
  src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
  src/EditorFeatures/CSharpTest/TypeInferrer/TypeInferrerTests.cs
  src/EditorFeatures/Test/MetadataAsSource/MetadataAsSourceTests.CSharp.cs
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.OperatorSymbols.vb
  src/EditorFeatures/Test2/GoToImplementation/GoToImplementationTests.vb
  src/EditorFeatures/TestUtilities/Classification/FormattedClassifications.Operators.cs
  src/EditorFeatures/TestUtilities/Classification/FormattedClassifications.OverloadedOperators.cs
  src/EditorFeatures/TestUtilities/Classification/FormattedClassifications.Punctuation.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/OperatorsAndIndexer/UnnamedSymbolCompletionProvider_Operators.cs
  src/VisualStudio/CSharp/Test/F1Help/F1HelpTests.cs
  src/Workspaces/CSharp/Portable/Classification/ClassificationHelpers.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpDeclarationComparer.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner_Operators.cs
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
  src/Workspaces/Core/Portable/CodeGeneration/CodeGenerationOperatorKind.cs
  src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationOperatorSymbol.cs
  src/Workspaces/Core/Portable/Editing/OperatorKind.cs
  src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/IMethodSymbolExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/PredefinedOperator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs
Labels: Area-Compilers, New Feature - UnsignedRightShift

#60713 Fix 'move to namespace' with file scoped namespaces.
  src/EditorFeatures/CSharpTest/MoveToNamespace/MoveToNamespaceTests.cs
  src/Features/CSharp/Portable/MoveToNamespace/CSharpMoveToNamespaceService.cs
Labels: Area-IDE

#60715 Support checked operators in explicit interface implementation
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProviderTests.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.CompletionSymbolDisplay.cs
Labels: Area-IDE

#60727 add more miscellaneous tests for checked operators
  src/EditorFeatures/Test/MetadataAsSource/MetadataAsSourceTests.CSharp.cs
  src/EditorFeatures/Test2/NavigationBar/CSharpNavigationBarTests.vb
  src/VisualStudio/Core/Test/ObjectBrowser/CSharp/ObjectBrowerTests.vb
Labels: Area-IDE

#60746 Delay symbol-search index updating until solution is fully loaded.
  src/VisualStudio/Core/Def/Packaging/PackageInstallerServiceFactory.cs
  src/VisualStudio/Core/Def/SymbolSearch/AbstractDelayStartedService.cs
  src/VisualStudio/Core/Def/SymbolSearch/VisualStudioSymbolSearchService.cs
Labels: Area-IDE

#60684 Allow generating variable with contextual keyword name in return statements
  src/EditorFeatures/CSharpTest/GenerateVariable/GenerateVariableTests.cs
  src/Features/CSharp/Portable/GenerateMember/GenerateVariable/CSharpGenerateVariableService.cs
Labels: Area-IDE, Community

#60723 Clean up IDiagnosticService extension methods
  src/Features/Core/Portable/Diagnostics/DiagnosticBucket.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/IDiagnosticService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/IDiagnosticServiceExtensions.cs
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioProjectTests/AnalyzerReferenceTests.vb
Labels: Area-IDE

#60496 Add integration test to flag MEF composition breaks
  src/VisualStudio/IntegrationTest/New.IntegrationTests/MefCompositionTests.cs
Labels: Area-Infrastructure

#56530 Fix #55183: Add SymbolVisitor<TArgument, TResult>
  src/Compilers/CSharp/Portable/Symbols/PublicModel/AliasSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/ArrayTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/AssemblySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/DiscardSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/DynamicTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/EventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/FieldSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/FunctionPointerTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/LabelSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/LocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/MethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/ModuleSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/NamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/NamespaceSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/ParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/PointerTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/PreprocessingSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/PropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/RangeVariableSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/Symbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/TypeParameterSymbol.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
  src/Compilers/CSharp/Test/Symbol/Compilation/SymbolVisitorTests.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Core/Portable/Symbols/ISymbol.cs
  src/Compilers/Core/Portable/Symbols/SymbolVisitor`2.cs
  src/Compilers/VisualBasic/Portable/Symbols/AliasSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/ArrayTypeSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/AssemblySymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/EventSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/FieldSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/LabelSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/MethodSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/ModuleSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/NamedTypeSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/NamespaceSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/ParameterSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/PreprocessingSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/PropertySymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/LocalSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/RangeVariableSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Symbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/TypeParameterSymbol.vb
  src/Features/Core/Portable/MetadataAsSource/AbstractMetadataAsSourceService.AbstractWrappedSymbol.cs
  src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationAbstractMethodSymbol.cs
  src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationAbstractNamedTypeSymbol.cs
  src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationArrayTypeSymbol.cs
  src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationEventSymbol.cs
  src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationFieldSymbol.cs
  src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationNamespaceSymbol.cs
  src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationParameterSymbol.cs
  src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationPointerTypeSymbol.cs
  src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationPropertySymbol.cs
  src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationSymbol.cs
  src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationTypeParameterSymbol.cs
Labels: Area-Compilers, Community

#60753 Do not try to refcount solution syncing when communicating with OOP
  src/Workspaces/Remote/Core/SolutionAssetStorage.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
Labels: Area-IDE

#60754 Remove duplicated asset
  src/VisualStudio/Setup/source.extension.vsixmanifest
Labels: Area-IDE

#60642 Add parameters in scope in nameof in certain attributes
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md
  src/Compilers/CSharp/Portable/Binder/LocalBinderFactory.cs
  src/Compilers/CSharp/Portable/Binder/NameofBinder.cs
  src/Compilers/CSharp/Portable/Binder/WithParametersBinder.cs
  src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs
Labels: Area-Compilers

#60768 Add ReplacementTextChange to OmniSharpInlineHint
  src/Tools/ExternalAccess/OmniSharp/InlineHints/OmniSharpInlineHintsService.cs
Labels: Area-IDE

#60758 Reenable concurrent OOP sync sharing.
  src/VisualStudio/Core/Test.Next/Remote/SnapshotSerializationTests.cs
  src/Workspaces/CoreTestUtilities/Fakes/SimpleAssetSource.cs
  src/Workspaces/Remote/Core/SolutionAssetProvider.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.Scope.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.cs
  src/Workspaces/Remote/Core/SolutionAssetStorageProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/AssetProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
Labels: Area-IDE

#60761 Simplify the constructs we use to sync changes between client and OOP.
  src/EditorFeatures/Core/Remote/SolutionChecksumUpdater.cs
  src/VisualStudio/Core/Test.Next/Remote/SnapshotSerializationTests.cs
  src/VisualStudio/Core/Test.Next/Services/AssetProviderTests.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/VisualStudio/Core/Test.Next/Services/SolutionServiceTests.cs
  src/Workspaces/Core/Portable/Remote/PinnedSolutionInfo.cs
  src/Workspaces/CoreTestUtilities/Fakes/SimpleAssetSource.cs
  src/Workspaces/Remote/Core/IRemoteAssetSynchronizationService.cs
  src/Workspaces/Remote/Core/ISolutionAssetProvider.cs
  src/Workspaces/Remote/Core/RemoteHostAssetSerialization.cs
  src/Workspaces/Remote/Core/SolutionAssetProvider.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.cs
  src/Workspaces/Remote/ServiceHub/Host/AssetProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/IAssetSource.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
  src/Workspaces/Remote/ServiceHub/Host/SolutionAssetSource.cs
  src/Workspaces/Remote/ServiceHub/Services/AssetSynchronization/RemoteAssetSynchronizationService.cs
Labels: Area-IDE

#60779 Simplify client/OOP asset sync more.
  src/VisualStudio/Core/Test.Next/Remote/SerializationValidator.cs
  src/VisualStudio/Core/Test.Next/Remote/SnapshotSerializationTests.cs
  src/Workspaces/Core/Portable/Serialization/SolutionReplicationContext.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Checksum_Factory.cs
  src/Workspaces/CoreTestUtilities/Fakes/SimpleAssetSource.cs
  src/Workspaces/Remote/Core/SolutionAssetProvider.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.Scope.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/ObjectPools/Extensions.cs
Labels: Area-IDE

#60392 Support SetsRequiredMembersAttribute
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Initializers.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Compilation/MethodBodySemanticModel.cs
  src/Compilers/CSharp/Portable/Compiler/AnonymousTypeMethodBodySynthesizer.cs
  src/Compilers/CSharp/Portable/Compiler/MethodBodySynthesizer.Lowered.cs
  src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Lowering/IteratorRewriter/IteratorFinallyMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.SynthesizedMethodBase.cs
  src/Compilers/CSharp/Portable/Symbols/ErrorMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/FunctionPointers/FunctionPointerMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/ReducedExtensionMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/SignatureOnlyMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceConstructorSymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs
  src/Compilers/CSharp/Portable/Symbols/SymbolExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordCopyCtor.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedDelegateSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedEntryPointSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedGlobalMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedImplementationMethod.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedInstanceConstructor.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedInteractiveInitializerMethod.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedIntrinsicOperatorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedStaticConstructor.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/Wrapped/WrappedMethodSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/RequiredMembersTests.cs
  src/Compilers/Core/Portable/Binding/BindingDiagnosticBag.cs
  src/Compilers/Core/Portable/Symbols/Attributes/AttributeDescription.cs
  src/Compilers/Core/Portable/Symbols/Attributes/CommonMethodEarlyWellKnownAttributeData.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/Core/Portable/WellKnownTypes.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EEMethodSymbol.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/PlaceholderMethodSymbol.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/SynthesizedContextMethodSymbol.cs
Labels: Area-Compilers

#60772 Fixed false positive "Remove unnecessary parentheses" on tuples when applying change result in broken code
  src/Analyzers/CSharp/Tests/RemoveUnnecessaryParentheses/RemoveUnnecessaryExpressionParenthesesTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs
Labels: Area-IDE, Community

#60785 Bump Humanizer.Core version to 2.14.1
  eng/Versions.props
Labels: Area-Infrastructure

#60749 Reorder synchronization code for clarity
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/VisualStudio/Core/Test.Next/Services/SolutionServiceTests.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.Scope.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
Labels: Area-IDE

#60752 Suggestion after comparison operators in is pattern matching
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs
Labels: Area-IDE, Community

#60793 Fixed crash when moving type from System namespace
  src/EditorFeatures/CSharpTest/MoveToNamespace/MoveToNamespaceTests.cs
  src/Features/Core/Portable/MoveToNamespace/AbstractMoveToNamespaceService.cs
Labels: Area-IDE, Community

#60671 Extract base class extracting generic type parameter now (#55871)
  src/EditorFeatures/CSharpTest/ExtractClass/ExtractClassTests.cs
  src/Features/Core/Portable/ExtractClass/ExtractClassWithDialogCodeAction.cs
  src/Features/Core/Portable/Shared/Utilities/ExtractTypeHelpers.cs
Labels: Area-IDE, Community

#60787 Simplify the communication between the VS client and OOP further.
  src/EditorFeatures/Core/Remote/SolutionChecksumUpdater.cs
  src/Features/Core/Portable/AddImport/Remote/IRemoteMissingImportDiscoveryService.cs
  src/Features/Core/Portable/CodeLens/IRemoteCodeLensReferencesService.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/IRemoteExtensionMethodImportCompletionService.cs
  src/Features/Core/Portable/ConvertTupleToStruct/IRemoteConvertTupleToStructCodeRefactoringService.cs
  src/Features/Core/Portable/Diagnostics/IRemoteDiagnosticAnalyzerService.cs
  src/Features/Core/Portable/DocumentHighlighting/IRemoteDocumentHighlightsService.cs
  src/Features/Core/Portable/EditAndContinue/Remote/IRemoteEditAndContinueService.cs
  src/Features/Core/Portable/EncapsulateField/IRemoteEncapsulateFieldService.cs
  src/Features/Core/Portable/FindUsages/IRemoteFindUsagesService.cs
  src/Features/Core/Portable/InheritanceMargin/IRemoteInheritanceMarginService.cs
  src/Features/Core/Portable/NavigateTo/IRemoteNavigateToSearchService.cs
  src/Features/Core/Portable/NavigationBar/IRemoteNavigationBarItemService.cs
  src/Features/Core/Portable/StackTraceExplorer/IStackTraceExplorerService.cs
  src/Features/Core/Portable/UnusedReferences/IUnusedReferenceAnalysisService.cs
  src/Features/Core/Portable/ValueTracking/IValueTrackingService.cs
  src/Features/Core/Portable/Workspace/IRemoteCompilationAvailableService.cs
  src/Tools/ExternalAccess/Razor/Remote/RazorPinnedSolutionInfoWrapper.cs
  src/VisualStudio/Core/Test.Next/Remote/SerializationValidator.cs
  src/VisualStudio/Core/Test.Next/Remote/SnapshotSerializationTests.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/Workspaces/Core/Portable/Classification/IRemoteSemanticClassificationService.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/IRemoteDependentTypeFinderService.cs
  src/Workspaces/Core/Portable/FindSymbols/IRemoteSymbolFinderService.cs
  src/Workspaces/Core/Portable/Remote/PinnedSolutionInfo.cs
  src/Workspaces/Core/Portable/Remote/RemoteHostClient.cs
  src/Workspaces/Core/Portable/Remote/RemoteServiceConnection.cs
  src/Workspaces/Core/Portable/Rename/IRemoteRenamerService.cs
  src/Workspaces/Remote/Core/BrokeredServiceConnection.cs
  src/Workspaces/Remote/Core/ExternalAccess/Pythia/Api/PythiaPinnedSolutionInfoWrapper.cs
  src/Workspaces/Remote/Core/ExternalAccess/UnitTesting/Api/UnitTestingPinnedSolutionInfoWrapper.cs
  src/Workspaces/Remote/Core/IRemoteAssetSynchronizationService.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.Scope.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspaceManager.cs
  src/Workspaces/Remote/ServiceHub/Services/AssetSynchronization/RemoteAssetSynchronizationService.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs
  src/Workspaces/Remote/ServiceHub/Services/CodeLensReferences/RemoteCodeLensReferencesService.cs
  src/Workspaces/Remote/ServiceHub/Services/ConvertTupleToStructCodeRefactoringProvider/RemoteConvertTupleToStructCodeRefactoringService.cs
  src/Workspaces/Remote/ServiceHub/Services/DependentTypeFinder/RemoteDependentTypeFinderService.cs
  src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/RemoteDiagnosticAnalyzerService.cs
  src/Workspaces/Remote/ServiceHub/Services/DocumentHighlights/RemoteDocumentHighlightsService.cs
  src/Workspaces/Remote/ServiceHub/Services/EditAndContinue/RemoteEditAndContinueService.cs
  src/Workspaces/Remote/ServiceHub/Services/EncapsulateField/RemoteEncapsulateFieldService.cs
  src/Workspaces/Remote/ServiceHub/Services/ExtensionMethodImportCompletion/RemoteExtensionMethodImportCompletionService.cs
  src/Workspaces/Remote/ServiceHub/Services/FindUsages/RemoteFindUsagesService.cs
  src/Workspaces/Remote/ServiceHub/Services/InheritanceMargin/RemoteInheritanceMarginService.cs
  src/Workspaces/Remote/ServiceHub/Services/MissingImportDiscovery/RemoteMissingImportDiscoveryService.cs
  src/Workspaces/Remote/ServiceHub/Services/NavigateToSearch/RemoteNavigateToSearchService.cs
  src/Workspaces/Remote/ServiceHub/Services/NavigationBar/RemoteNavigationBarItemService.cs
  src/Workspaces/Remote/ServiceHub/Services/Renamer/RemoteRenamerService.cs
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassification/RemoteSemanticClassificationService.cs
  src/Workspaces/Remote/ServiceHub/Services/StackTraceExplorer/RemoteStackTraceExplorerService.cs
  src/Workspaces/Remote/ServiceHub/Services/SymbolFinder/RemoteSymbolFinderService.cs
  src/Workspaces/Remote/ServiceHub/Services/Tagging/RemoteTaggerCompilationAvailableService.cs
  src/Workspaces/Remote/ServiceHub/Services/UnusedReferences/RemoteUnusedReferenceAnalysisService.cs
  src/Workspaces/Remote/ServiceHub/Services/ValueTracking/RemoteValueTrackingService.cs
Labels: Area-IDE

#60789 Fix up handling for partially written generics
  src/EditorFeatures/CSharpTest/SignatureHelp/GenericNamePartiallyWrittenSignatureHelpProviderTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/SyntaxTreeExtensions.cs
Labels: Area-IDE

#60686 Expose new Recommender API
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
  src/Workspaces/Core/Portable/Recommendations/Recommender.cs
Labels: Area-IDE

#60815 Do not suggest where keyword in generic constraints when accessing members
  src/EditorFeatures/CSharpTest2/Recommendations/WhereKeywordRecommenderTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/WhereKeywordRecommender.cs
Labels: Area-IDE, Community

#60821 Update status of "Unsigned Right Shift" feature
  docs/Language Feature Status.md
Labels: Area-Compilers

#60820 Add file types to feature status doc
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation

#60588 Convert Visual Basic error list tests to the new framework
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicErrorListCommon.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicErrorListDesktop.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicErrorListNetCore.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicErrorListCommon.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicErrorListDesktop.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicErrorListNetCore.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/ErrorList_InProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/ErrorList_OutOfProc.cs
Labels: Area-IDE

#60828 Add OptProf.json to CI excluded files
  azure-pipelines-integration-corehost.yml
  azure-pipelines-integration.yml
Labels: Area-Infrastructure

#60829 Fix TypeScript code actions and Xaml remove unused usings
  src/EditorFeatures/Core/Organizing/OrganizeDocumentCommandHandler.cs
  src/VisualStudio/Xaml/Impl/CodeFixes/RemoveUnnecessaryUsings/XamlRemoveUnnecessaryUsingsCodeFixProvider.cs
  src/VisualStudio/Xaml/Impl/Features/OrganizeImports/XamlRemoveUnnecessaryImportsService.cs
  src/Workspaces/Core/Portable/CodeActions/CodeAction.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpRemoveUnnecessaryImportsService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/RemoveUnnecessaryImports/AbstractRemoveUnnecessaryImportsService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/RemoveUnnecessaryImports/IRemoveUnnecessaryImportsService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/LanguageServices/VisualBasicRemoveUnnecessaryImportsService.vb
Labels: Area-IDE

#60830 Avoid artificial tagging delay when called by consumer that is explicitly blocking for results.
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs
Labels: Area-IDE

#60827 Exclude System.Text.Encoding.CodePages from OptProf
  azure-pipelines.yml
  eng/config/OptProf.json
Labels: Area-Infrastructure

#60856 Assume buffer is visible if we can't find any views for it at all
  src/EditorFeatures/Core.Wpf/Workspaces/WpfTextBufferVisibilityTracker.cs
Labels: Area-IDE

#60851 Revert "Don't complete quotes if they complete a valid string (#60227)"
  src/EditorFeatures/CSharpTest/AutomaticCompletion/AutomaticLiteralCompletionTests.cs
  src/Features/CSharp/Portable/BraceCompletion/StringLiteralBraceCompletionService.cs
Labels: Area-IDE, Approved to merge

#60845 Ensure idle-processing (like solution syncing) does not execute while paused due to global operations (like msbuild compiles)
  src/EditorFeatures/Core/Remote/SolutionChecksumUpdater.cs
  src/Features/Core/Portable/SolutionCrawler/GlobalOperationAwareIdleProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/IdleProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.AbstractPriorityProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.HighPriorityProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.LowPriorityProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.SemanticChangeProcessor.cs
  src/Features/Core/Portable/Workspace/ProjectCacheService.SimpleMRUCache.cs
  src/VisualStudio/Core/Def/RoslynPackage.cs
  src/VisualStudio/Core/Def/SolutionEventMonitor.cs
  src/Workspaces/Core/Portable/Notification/AbstractGlobalOperationNotificationService.cs
  src/Workspaces/Core/Portable/Notification/GlobalOperationEventArgs.cs
  src/Workspaces/Core/Portable/Notification/GlobalOperationNotificationService.GlobalOperationRegistration.cs
  src/Workspaces/Core/Portable/Notification/GlobalOperationNotificationService.cs
  src/Workspaces/Core/Portable/Notification/GlobalOperationNotificationServiceFactory.cs
  src/Workspaces/Core/Portable/Notification/IGlobalOperationNotificationService.cs
  src/Workspaces/Core/Portable/Notification/IGlobalOperationRegistration.cs
  src/Workspaces/Remote/Core/GlobalNotificationRemoteDeliveryService.cs
  src/Workspaces/Remote/Core/IRemoteGlobalNotificationDeliveryService.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteGlobalOperationNotificationService.cs
  src/Workspaces/Remote/ServiceHub/Services/GlobalNotificationDelivery/RemoteGlobalNotificationDeliveryService.cs
  src/Workspaces/Remote/ServiceHub/Services/ProcessTelemetry/RemoteProcessTelemetryService.PerformanceReporter.cs
Labels: Area-IDE

#60474 Show generator produced diagnostics
  src/Compilers/Test/Core/Microsoft.CodeAnalysis.Test.Utilities.csproj
  src/Compilers/Test/Core/SourceGeneration/TestGenerators.cs
  src/EditorFeatures/Test/Diagnostics/DiagnosticAnalyzerServiceTests.cs
  src/Features/Core/Portable/Diagnostics/DiagnosticAnalyzerExtensions.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DocumentAnalysisExecutor.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DocumentAnalysisExecutor_Helpers.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.Executor.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.StateManager.HostStates.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.StateManager.ProjectStates.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.StateManager.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_IncrementalAnalyzer.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
  src/Workspaces/Core/Portable/Diagnostics/DiagnosticAnalysisResult.cs
  src/Workspaces/Core/Portable/Diagnostics/DiagnosticAnalysisResultBuilder.cs
  src/Workspaces/Core/Portable/Diagnostics/GeneratorDiagnosticsPlaceholderAnalyzer.cs
  src/Workspaces/Core/Portable/Utilities/GeneratorDriverRunResultExtensions.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Project.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectDependencyGraph.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.GeneratedFileReplacingCompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.ICompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
Labels: Area-IDE

#60832 Cherry-pick 60493 to 17.2
  src/VisualStudio/Core/Def/InheritanceMargin/InheritanceMarginLogger.cs
  src/VisualStudio/Core/Def/InheritanceMargin/InheritanceMarginTaggerProvider.cs
  src/VisualStudio/Core/Def/InheritanceMargin/MarginGlyph/InheritanceMarginContextMenu.xaml.cs
  src/VisualStudio/Core/Def/InheritanceMargin/MarginGlyph/InheritanceMarginGlyph.cs
  src/VisualStudio/Core/Def/RoslynPackage.cs
Labels: Area-IDE

#60861 Revert diasymreader version update due to cloudbuild failures
  eng/Versions.props
Labels: Area-Infrastructure

#60847 Fix the color key for rename hint text at the bottom
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/InlineRenameAdornment.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/InlineRenameColors.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/InlineRenameColors.xaml
  src/VisualStudio/Core/Def/InlineRename/DashboardColorUpdater.cs
Labels: Area-IDE, auto-merge

#60854 Cleanup brace completion code.
  src/EditorFeatures/CSharpTest/AutomaticCompletion/AutomaticLiteralCompletionTests.cs
  src/EditorFeatures/Core/AutomaticCompletion/BraceCompletionSessionProvider.BraceCompletionSession.cs
  src/Features/CSharp/Portable/BraceCompletion/AbstractCSharpBraceCompletionService.cs
  src/Features/CSharp/Portable/BraceCompletion/AbstractCurlyBraceOrBracketCompletionService.cs
  src/Features/CSharp/Portable/BraceCompletion/CharLiteralBraceCompletionService.cs
  src/Features/CSharp/Portable/BraceCompletion/InterpolatedStringBraceCompletionService.cs
  src/Features/CSharp/Portable/BraceCompletion/InterpolationBraceCompletionService.cs
  src/Features/CSharp/Portable/BraceCompletion/LessAndGreaterThanBraceCompletionService.cs
  src/Features/CSharp/Portable/BraceCompletion/ParenthesisBraceCompletionService.cs
  src/Features/CSharp/Portable/BraceCompletion/StringLiteralBraceCompletionService.cs
  src/Features/Core/Portable/BraceCompletion/AbstractBraceCompletionService.cs
  src/Features/VisualBasic/Portable/BraceCompletion/AbstractVisualBasicBraceCompletionService.vb
  src/Features/VisualBasic/Portable/BraceCompletion/BracketBraceCompletionService.vb
  src/Features/VisualBasic/Portable/BraceCompletion/CurlyBraceCompletionService.vb
  src/Features/VisualBasic/Portable/BraceCompletion/InterpolatedStringBraceCompletionService.vb
  src/Features/VisualBasic/Portable/BraceCompletion/InterpolationBraceCompletionService.vb
  src/Features/VisualBasic/Portable/BraceCompletion/LessAndGreaterThanCompletionService.vb
  src/Features/VisualBasic/Portable/BraceCompletion/ParenthesisBraceCompletionService.vb
  src/Features/VisualBasic/Portable/BraceCompletion/StringLiteralBraceCompletionService.vb
Labels: Area-IDE

#60866 Cleanup global notification code more.
  src/EditorFeatures/Test/SolutionCrawler/WorkCoordinatorTests.cs
  src/VisualStudio/Core/Def/SolutionEventMonitor.cs
  src/Workspaces/Core/Portable/Notification/GlobalOperationNotificationService.GlobalOperationRegistration.cs
  src/Workspaces/Core/Portable/Notification/GlobalOperationNotificationService.cs
  src/Workspaces/Core/Portable/Notification/IGlobalOperationNotificationService.cs
  src/Workspaces/Core/Portable/Notification/IGlobalOperationRegistration.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteGlobalOperationNotificationService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-IDE

#60809 [semi-auto-props]: Remove an already-fixed prototype
  src/Compilers/CSharp/Test/Semantic/Semantics/PropertyFieldKeywordTests.cs
Labels: Area-Compilers, Community

#60839 Remove deprecated NuPkg projects
  Compilers.sln
  Compilers.slnf
  Roslyn.sln
  eng/config/PublishData.json
  src/NuGet/Microsoft.NETCore.Compilers/.gitattributes
  src/NuGet/Microsoft.NETCore.Compilers/Microsoft.NETCore.Compilers.Package.csproj
  src/NuGet/Microsoft.NETCore.Compilers/build/Microsoft.NETCore.Compilers.props
  src/NuGet/Microsoft.Net.Compilers/Microsoft.Net.Compilers.Package.csproj
  src/NuGet/Microsoft.Net.Compilers/build/Microsoft.Net.Compilers.props
  src/Tools/BuildBoss/CompilerNuGetCheckerUtil.cs
Labels: Area-Infrastructure

#60853 Fix typo in Stack Trace Explorer text
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
Labels: Area-IDE

#60865 Remove unused method `Binder.CheckViability<TSymbol>()`
  src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs
Labels: Area-Compilers

#60852 Fix infinite loop introduced with https://github.com/dotnet/roslyn/pull/60227
  src/Features/CSharp/Portable/BraceCompletion/StringLiteralBraceCompletionService.cs
Labels: Area-IDE

#60887 Fix shift binding for preview on new rename UI
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/InlineRenameAdornment.xaml.cs
Labels: Area-IDE

#60886 Respect test requests to expedite processing in solution crawler.
  src/Features/Core/Portable/SolutionCrawler/IdleProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.AbstractPriorityProcessor.cs
Labels: Area-IDE

#60895 Verify conversion kinds in native int conversion tests
  src/Compilers/CSharp/Test/Semantic/Semantics/NativeIntegerTests.cs
Labels: Area-Compilers, Test

#60824 [LSP] Implement support for `workspace/semanticTokens/refresh` notifications
  eng/Versions.props
  src/EditorFeatures/Core/LanguageServer/AbstractInProcLanguageClient.cs
  src/EditorFeatures/Core/LanguageServer/RazorInProcLanguageClient.cs
  src/Features/LanguageServer/Protocol/AbstractLanguageClientMiddleLayer.cs
  src/Features/LanguageServer/Protocol/Handler/LanguageServerNotificationManager.cs
  src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensRefreshListener.cs
  src/Features/LanguageServer/Protocol/ILanguageServerNotificationManager.cs
  src/Features/LanguageServer/Protocol/LanguageServerTarget.cs
  src/Features/LanguageServer/Protocol/Microsoft.CodeAnalysis.LanguageServer.Protocol.csproj
  src/Features/LanguageServer/Protocol/Workspaces/LspWorkspaceManager.cs
  src/Tools/ExternalAccess/Razor/IRazorCSharpInterceptionMiddleLayer.cs
  src/Tools/ExternalAccess/Razor/RazorCSharpInterceptionMiddleLayer.cs
  src/Tools/ExternalAccess/Razor/RazorLanguageServerFactoryWrapper.cs
Labels: Area-IDE, LSP

#60688 Fill out test plan for auto-default structs
  docs/contributing/Compiler Test Plan.md
  src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/FlowAnalysisPass.cs
  src/Compilers/CSharp/Test/Emit2/FlowAnalysis/FlowDiagnosticTests.cs
  src/Compilers/CSharp/Test/Emit2/FlowAnalysis/LocalFunctions.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/StructConstructorTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/WarningVersionTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/UpgradeProject/UpgradeProjectTests.cs
  src/Features/CSharp/Portable/UpgradeProject/CSharpUpgradeProjectCodeFixProvider.cs
Labels: Area-IDE, Area-Compilers

#60916 Fix CI in main
  src/Compilers/CSharp/Test/Semantic/Semantics/StructConstructorTests.cs
Labels: Area-Compilers, Test

#60917 Use dotnet bot instead of vslsnap for insertions
  azure-pipelines-official.yml
  azure-pipelines-pr-validation.yml
  eng/pipelines/insert.yml
Labels: Area-Infrastructure

#60932 Add back deprecated packages to arcade publishing config.
  eng/config/PublishData.json
Labels: Area-Infrastructure

#60802 Add IDE tests for nameof(parameter) and mitigation for speculation issue
  docs/Language Feature Status.md
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/AbstractCSharpCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/CrefCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/LoadDirectiveCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ReferenceDirectiveCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests_NoInteractive.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
  src/EditorFeatures/TestUtilities/Completion/AbstractCompletionProviderTests.cs
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/AbstractVisualBasicCompletionProviderTests.vb
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/ObjectInitializerCompletionProviderTests.vb
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/XmlDocCommentCompletionProviderTests.vb
Labels: Area-IDE, Area-Compilers

#60899 Correctly set the TemplateSelector of inheritance margin.
  src/VisualStudio/Core/Def/InheritanceMargin/MarginGlyph/InheritanceMarginContextMenu.xaml
Labels: Area-IDE, UX Review Not Required

#60923 Consolidate and simplify visibility checks in the tagger.
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_TagsChanged.cs
Labels: Area-IDE

#60901 Optimize allocations in batch queue processing
  src/Dependencies/Collections/ImmutableSegmentedListExtensions.cs
  src/Dependencies/Collections/Microsoft.CodeAnalysis.Collections.projitems
  src/EditorFeatures/Core.Wpf/BackgroundWorkIndicator/BackgroundWorkIndicatorContext.cs
  src/EditorFeatures/Core/Classification/Syntactic/SyntacticClassificationTaggerProvider.TagComputer.cs
  src/EditorFeatures/Core/LanguageServer/Handlers/References/FindUsagesLSPContext.cs
  src/EditorFeatures/Core/NavigationBar/NavigationBarController_ModelComputation.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_TagsChanged.cs
  src/Features/Core/Portable/Completion/Providers/CompletionUtilities.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractImportCompletionCacheServiceFactory.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionService.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs
  src/Features/LanguageServer/Protocol/Features/TodoComments/TodoCommentsListener.cs
  src/VisualStudio/Core/Def/DesignerAttribute/VisualStudioDesignerAttributeService.cs
  src/VisualStudio/Core/Def/FindReferences/Contexts/AbstractTableDataSourceFindUsagesContext.cs
  src/VisualStudio/Core/Def/Packaging/PackageInstallerServiceFactory.cs
  src/VisualStudio/Core/Def/PdbSourceDocument/PdbSourceDocumentOutputWindowLogger.cs
  src/VisualStudio/Core/Def/ProjectSystem/FileChangeWatcher.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioProject.BatchingDocumentCollection.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioProject.cs
  src/VisualStudio/Core/Def/ProjectTelemetry/VisualStudioProjectTelemetryService.cs
  src/VisualStudio/Core/Impl/CodeModel/ProjectCodeModelFactory.cs
  src/Workspaces/Core/Portable/Shared/Utilities/AsyncBatchingWorkQueue`0.cs
  src/Workspaces/Core/Portable/Shared/Utilities/AsyncBatchingWorkQueue`1.cs
  src/Workspaces/Core/Portable/Shared/Utilities/AsyncBatchingWorkQueue`2.cs
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassification/RemoteSemanticClassificationService.Caching.cs
Labels: Area-IDE

#60900 Store incremental data in AVL tree instead of array
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.CompilationTrackerState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
Labels: Area-IDE

#60825 Handle unexpected keyword rather than identifier for lambda parameter name
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/LambdaParameterParsingTests.cs
Labels: Area-Compilers

#60870 Correctly return E_NOTIMPL when asked for file code models for non-source
  src/VisualStudio/Core/Impl/CodeModel/CodeModelProjectCache.cs
  src/VisualStudio/Core/Test/CodeModel/CSharp/FileCodeModelTests.vb
  src/VisualStudio/TestUtilities2/CodeModel/CodeModelTestHelpers.vb
  src/VisualStudio/TestUtilities2/CodeModel/CodeModelTestState.vb
Labels: Area-IDE

#60942 Add configs for 17.3 branch and update main version
  eng/Versions.props
  eng/config/PublishData.json
Labels: Area-Infrastructure

#60943 Allow VSMac to access LSP options
  src/Features/LanguageServer/Protocol/Microsoft.CodeAnalysis.LanguageServer.Protocol.csproj
Labels: Area-IDE

#60947 Remove non-servicing branches from our PublishData
  eng/config/PublishData.json
  eng/publish-assets.ps1
Labels: Area-Infrastructure

#60936 Update 'convert to raw string' to help cleanup strings with leading whitespace
  src/EditorFeatures/CSharpTest/ConvertToRawString/ConvertToRegularStringToRawStringStringTests.cs
  src/Features/CSharp/Portable/CSharpFeaturesResources.resx
  src/Features/CSharp/Portable/ConvertToRawString/ConvertRegularStringToRawStringCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/ConvertToRawString/ConvertToRawStringHelpers.cs
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.cs.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.de.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.es.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.fr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.it.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ja.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ko.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pl.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pt-BR.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ru.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.tr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hans.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hant.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/EmbeddedLanguages/VirtualChars/VirtualChar.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/EmbeddedLanguages/VirtualChars/VirtualCharSequence.Enumerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/EmbeddedLanguages/VirtualChars/VirtualCharSequence.cs
Labels: Area-IDE

#60722 Update details on "numeric IntPtr"
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation

#60717 Relax requirements around second parameter of a user-defined shift operator.
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/BinaryOperatorOverloadResolution.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbolBase.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/RelaxedShiftOperatorTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/UnsignedRightShiftTests.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/RelaxedShiftOperatorTests.vb
Labels: Area-Compilers

#60973 Don't initialize the StackTraceExplorer tool window until it is invoked
  src/VisualStudio/Core/Def/RoslynPackage.cs
  src/VisualStudio/Core/Def/StackTraceExplorer/StackTraceExplorerCommandHandler.cs
Labels: Area-IDE

#60974 Delete unused RPC streaming code from our OOP impl.
  src/Workspaces/Core/Portable/Remote/RemoteHostClient.cs
  src/Workspaces/Core/Portable/Remote/RemoteServiceConnection.cs
  src/Workspaces/Remote/Core/BrokeredServiceConnection.cs
Labels: Area-IDE

#60979 Fix exceptions for non-VS hosting of Roslyn
  src/Features/Core/Portable/PdbSourceDocument/PdbFileLocatorService.cs
  src/Features/Core/Portable/PdbSourceDocument/PdbSourceDocumentLoaderService.cs
Labels: Area-IDE

#60970 Update Language Feature Status.md
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation

#60989 Update main to generate draft insertions
  eng/config/PublishData.json
Labels: Area-Infrastructure

#60810 Fix generate event handler with invalid name (#59935)
  src/EditorFeatures/CSharp/EventHookup/EventHookupSessionManager_EventHookupSession.cs
  src/EditorFeatures/CSharpTest/EventHookup/EventHookupCommandHandlerTests.cs
Labels: Area-IDE, Community

#60881 Update source-generators.cookbook.md
  docs/features/source-generators.cookbook.md
Labels: Area-Compilers, Community

#60950 Move the load of project completion providers to background
  src/Features/Core/Portable/Completion/CompletionServiceWithProviders.ProviderManager.cs
  src/Features/Core/Portable/Completion/CompletionServiceWithProviders.cs
  src/VisualStudio/Core/Def/LanguageService/AbstractCreateServicesOnTextViewConnection.cs
  src/VisualStudio/VisualBasic/Impl/LanguageService/VisualBasicCreateServicesOnTextViewConnection.vb
Labels: Area-IDE

#60555 Fix typo in `#if` directive
  src/Compilers/Shared/BuildServerConnection.cs
Labels: Area-Compilers, Community

#60788 Forbid types with required members from substituting for where T : new()
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs
  src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordCopyCtor.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Symbol/Symbols/RequiredMembersTests.cs
Labels: Area-Compilers

#60770 Merge "extended nameof scope" feature
  docs/Language Feature Status.md
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md
  src/Compilers/CSharp/Portable/Binder/Binder.WithQueryLambdaParametersBinder.cs
  src/Compilers/CSharp/Portable/Binder/Binder.cs
  src/Compilers/CSharp/Portable/Binder/BinderFactory.BinderFactoryVisitor.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/Binder/BuckStopsHereBinder.cs
  src/Compilers/CSharp/Portable/Binder/ContextualAttributeBinder.cs
  src/Compilers/CSharp/Portable/Binder/HostObjectModeBinder.cs
  src/Compilers/CSharp/Portable/Binder/InContainerBinder.cs
  src/Compilers/CSharp/Portable/Binder/InMethodBinder.cs
  src/Compilers/CSharp/Portable/Binder/InSubmissionClassBinder.cs
  src/Compilers/CSharp/Portable/Binder/LocalBinderFactory.cs
  src/Compilers/CSharp/Portable/Binder/LocalScopeBinder.cs
  src/Compilers/CSharp/Portable/Binder/NameofBinder.cs
  src/Compilers/CSharp/Portable/Binder/WithClassTypeParametersBinder.cs
  src/Compilers/CSharp/Portable/Binder/WithCrefTypeParametersBinder.cs
  src/Compilers/CSharp/Portable/Binder/WithExternAliasesBinder.cs
  src/Compilers/CSharp/Portable/Binder/WithExternAndUsingAliasesBinder.cs
  src/Compilers/CSharp/Portable/Binder/WithLambdaParametersBinder.cs
  src/Compilers/CSharp/Portable/Binder/WithMethodTypeParametersBinder.cs
  src/Compilers/CSharp/Portable/Binder/WithParametersBinder.cs
  src/Compilers/CSharp/Portable/Binder/WithUsingNamespacesAndTypesBinder.cs
  src/Compilers/CSharp/Portable/Compilation/AttributeSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxNodeExtensions.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/AbstractCSharpCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/CrefCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/LoadDirectiveCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ReferenceDirectiveCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests_NoInteractive.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
  src/EditorFeatures/TestUtilities/Completion/AbstractCompletionProviderTests.cs
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/AbstractVisualBasicCompletionProviderTests.vb
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/ObjectInitializerCompletionProviderTests.vb
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/XmlDocCommentCompletionProviderTests.vb
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Binders/EEMethodBinder.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Binders/PlaceholderLocalBinder.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Binders/WithTypeArgumentsBinder.cs
Labels: Area-Compilers

#60997 insert into main for 17.3 before VS snap
  eng/config/PublishData.json
Labels: Area-Infrastructure

#60998 Cherry-Pick 60973 To 17.3
  src/VisualStudio/Core/Def/RoslynPackage.cs
  src/VisualStudio/Core/Def/StackTraceExplorer/StackTraceExplorerCommandHandler.cs
Labels: Area-IDE, Approved to merge, auto-merge

#61001 Adjust timeout on helix runs to 15 minutes to ensure dumps are captur…
  src/Tools/Source/RunTests/ProcessTestExecutor.cs
  src/Tools/Source/RunTests/TestRunner.cs
Labels: Area-Infrastructure

#61000 Merge 'RelaxingShiftOperator' into 'main'
  docs/Language Feature Status.md
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/BinaryOperatorOverloadResolution.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbolBase.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/RelaxedShiftOperatorTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/UnsignedRightShiftTests.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/RelaxedShiftOperatorTests.vb
Labels: Area-Compilers, auto-merge
