Repository dotnet/roslyn, pull requests merged in 2022-06, with the labels that each got.

#61549 Update 'Rename's commit behavior to be async.
  src/EditorFeatures/Core/ExtractMethod/ExtractMethodCommandHandler.cs
  src/EditorFeatures/Core/IInlineRenameSession.cs
  src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs
  src/EditorFeatures/Core/InlineRename/InlineRenameSessionOptionsStorage.cs
  src/EditorFeatures/Core/RenameTracking/RenameTrackingTaggerProvider.RenameTrackingCodeAction.cs
  src/EditorFeatures/Core/RenameTracking/RenameTrackingTaggerProvider.RenameTrackingCommitter.cs
  src/EditorFeatures/Core/RenameTracking/RenameTrackingTaggerProvider.StateMachine.cs
  src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb
  src/EditorFeatures/VisualBasicTest/LineCommit/CommitTestData.vb
  src/Tools/IdeCoreBenchmarks/IncrementalSourceGeneratorBenchmarks.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageStrings.vb
Labels: Area-IDE

#61491 Semantic Snippets - Remove reflection and call the LanguageServerSnippetExpander directly
  eng/Versions.props
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/AbstractCSharpSnippetCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/TestRoslynLanguageServerSnippetExpander.cs
  src/EditorFeatures/Core.Wpf/AsyncCompletion/LanguageServerSnippetExpanderAdapter.cs
  src/EditorFeatures/Core.Wpf/Microsoft.CodeAnalysis.EditorFeatures.Wpf.csproj
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/CommitManager.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/CommitManagerProvider.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/ILanguageServerSnippetExpander.cs
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/EditorFeatures/Core/Snippets/RoslynLSPSnippetExpander.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/Snippets/CSharpSnippetCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs
  src/VisualStudio/LiveShare/Impl/Client/RemoteLanguageServiceWorkspace.cs
Labels: Area-IDE

#61613 Add an option to control if compilations are cloned when making skeletons
  src/Features/LanguageServer/Protocol/Features/Options/WorkspaceConfigurationOptionsStorage.cs
  src/Workspaces/Core/Portable/Workspace/IWorkspaceConfigurationService.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.SkeletonReferenceCache.cs
Labels: Area-IDE

#61619 Update config file for 17.3 P2 snapping
  eng/Versions.props
  eng/config/PublishData.json
Labels: Area-Infrastructure

#61608 Remove weak references in skeleton reference cache.
  src/VisualStudio/Core/Def/Remote/VisualStudioWorkspaceServiceHubConnector.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.SkeletonPortableExecutableReference.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.SkeletonReferenceCache.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.SkeletonReferenceSet.cs
Labels: Area-IDE

#61632 Update PublishData.json
  eng/config/PublishData.json
Labels: Area-Infrastructure

#61592 Move the semantics checks of Inheritance margin to OOP
  src/EditorFeatures/Test/InheritanceMargin/InheritanceMarginTests.cs
  src/Features/Core/Portable/InheritanceMargin/AbstractInheritanceMarginService.cs
  src/Features/Core/Portable/InheritanceMargin/AbstractInheritanceMarginService_Helpers.cs
  src/Features/Core/Portable/InheritanceMargin/IInheritanceMarginService.cs
  src/Features/Core/Portable/InheritanceMargin/IRemoteInheritanceMarginService.cs
  src/Tools/IdeBenchmarks/InheritanceMargin/BenchmarksHelpers.cs
  src/VisualStudio/Core/Def/InheritanceMargin/InheritanceMarginTaggerProvider.cs
  src/VisualStudio/Core/Test/InheritanceMargin/InheritanceMarginViewModelTests.vb
  src/Workspaces/Remote/ServiceHub/Services/InheritanceMargin/RemoteInheritanceMarginService.cs
Labels: Area-IDE

#61601 Perform language version check for an implicit implementation of a static virtual member
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
Labels: Area-Compilers, New Feature - StaticAbstractMembersInInterfaces

#61607 Report a warning for multiple matches for implicit interface implementation of static member
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
Labels: Area-Compilers, New Feature - StaticAbstractMembersInInterfaces

#61644 Emit error when function pointer invocation is encountered in an expression tree
  src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs
Labels: Area-Compilers, Feature - Function Pointers

#61637 Mention sharplab in bug template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: Area-Infrastructure, Documentation

#61633 Semantic Snippets - Fix bug where trigger character and start of snippet intersect
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/CommitManager.cs
  src/EditorFeatures/Test/Snippets/RoslynLSPSnippetConvertTests.cs
  src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs
  src/Features/Core/Portable/Snippets/RoslynLSPSnippetConverter.cs
Labels: Area-IDE

#61656 Remove documents as a batch instead of individually
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs
Labels: Area-IDE

#61664 Move crash to NFW in assignment-underlining
  src/Workspaces/Core/Portable/ReassignedVariable/AbstractReassignedVariableService.cs
Labels: Area-IDE

#61673 Add AspNetCoreCSharpVirtualCharService
  src/Tools/ExternalAccess/AspNetCore/EmbeddedLanguages/AspNetCoreCSharpVirtualCharService.cs
  src/Tools/ExternalAccess/AspNetCore/EmbeddedLanguages/AspNetCoreEmbeddedLanguageClassificationContext.cs
  src/Tools/ExternalAccess/AspNetCore/EmbeddedLanguages/AspNetCoreVirtualChar.cs
  src/Tools/ExternalAccess/AspNetCore/Internal/EmbeddedLanguages/AspNetCoreEmbeddedLanguageClassifier.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/EmbeddedLanguages/VirtualChars/VirtualChar.cs
Labels: Area-IDE

#61671 Switch backing store for callback-array to an immutable structure so it cannot change as we are enumerating over it.
  src/EditorFeatures/Core.Wpf/Workspaces/WpfTextBufferVisibilityTracker.cs
  src/EditorFeatures/Test2/Workspaces/WpfTextBufferVisibilityTrackerTests.vb
Labels: Area-IDE

#61667 Allow SyntaxOffset in EnC state machine map to be negative
  eng/Versions.props
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueStateMachineTests.cs
  src/Compilers/Core/Portable/Emit/EditAndContinueMethodDebugInformation.cs
Labels: Area-Interactive

#61682 do not attempt to add ErrorCode.WRN_ShouldNotReturn twice in ErrorFacts
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
Labels: Area-Compilers, Community

#61584 Fixed collection and object initializer usage analysis not working in top-level code
  src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests.cs
  src/Analyzers/CSharp/Tests/UseObjectInitializer/UseObjectInitializerTests.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/UseCollectionInitializerAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseObjectInitializer/UseNamedMemberInitializerAnalyzer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE

#61685 Utilize behaviour for unexisting features of syntax facts in VB
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE

#48161 Extend TypeDeclarationStructureTests with records
  src/EditorFeatures/CSharpTest/Structure/TypeDeclarationStructureTests.cs
Labels: Area-IDE, Community

#39006 F# External Access - Removed loc entries that are not used.
  src/Tools/ExternalAccess/FSharp/ExternalAccessFSharpResources.Designer.cs
  src/Tools/ExternalAccess/FSharp/ExternalAccessFSharpResources.resx
  src/Tools/ExternalAccess/FSharp/xlf/ExternalAccessFSharpResources.cs.xlf
  src/Tools/ExternalAccess/FSharp/xlf/ExternalAccessFSharpResources.de.xlf
  src/Tools/ExternalAccess/FSharp/xlf/ExternalAccessFSharpResources.es.xlf
  src/Tools/ExternalAccess/FSharp/xlf/ExternalAccessFSharpResources.fr.xlf
  src/Tools/ExternalAccess/FSharp/xlf/ExternalAccessFSharpResources.it.xlf
  src/Tools/ExternalAccess/FSharp/xlf/ExternalAccessFSharpResources.ja.xlf
  src/Tools/ExternalAccess/FSharp/xlf/ExternalAccessFSharpResources.ko.xlf
  src/Tools/ExternalAccess/FSharp/xlf/ExternalAccessFSharpResources.pl.xlf
  src/Tools/ExternalAccess/FSharp/xlf/ExternalAccessFSharpResources.pt-BR.xlf
  src/Tools/ExternalAccess/FSharp/xlf/ExternalAccessFSharpResources.ru.xlf
  src/Tools/ExternalAccess/FSharp/xlf/ExternalAccessFSharpResources.tr.xlf
  src/Tools/ExternalAccess/FSharp/xlf/ExternalAccessFSharpResources.zh-Hans.xlf
  src/Tools/ExternalAccess/FSharp/xlf/ExternalAccessFSharpResources.zh-Hant.xlf
Labels: Area-IDE, Community

#61689 Classify Throw as a control keyword in VB
  src/EditorFeatures/VisualBasicTest/Classification/SyntacticClassifierTests.vb
  src/Workspaces/VisualBasic/Portable/Classification/ClassificationHelpers.vb
Labels: Area-IDE, Community

#61649 Cache the AssemblyMetadata produced for any given compilation
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.SkeletonPortableExecutableReference.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.SkeletonReferenceCache.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.SkeletonReferenceSet.cs
Labels: Area-IDE

#51476 Remove unneeded IVTs in Interactive layer
  src/Interactive/vbi/vbi.vbproj
Labels: Area-Interactive

#51474 Remove unneeded ProjectReferences in ExpressionEvaluator layer
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/Microsoft.CodeAnalysis.CSharp.ExpressionCompiler.UnitTests.csproj
  src/ExpressionEvaluator/CSharp/Test/ResultProvider/Microsoft.CodeAnalysis.CSharp.ResultProvider.UnitTests.csproj
  src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/Microsoft.CodeAnalysis.VisualBasic.ExpressionCompiler.UnitTests.vbproj
  src/ExpressionEvaluator/VisualBasic/Test/ResultProvider/Microsoft.CodeAnalysis.VisualBasic.ResultProvider.UnitTests.vbproj
Labels: Area-Interactive

#61630 Update compiler to supported UnmanagedMemoryStream when creating ModuleMetadata.
  src/Compilers/Core/CodeAnalysisTest/MetadataReferences/ModuleMetadataTests.cs
  src/Compilers/Core/Portable/MetadataReference/ModuleMetadata.cs
  src/Workspaces/Core/Portable/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.SkeletonPortableExecutableReference.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.SkeletonReferenceCache.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.SkeletonReferenceSet.cs
Labels: Area-IDE

#53966 Updates based on Visual Studio 2019 Version 16.10
  docs/wiki/EnC-Supported-Edits.md
Labels: Area-Infrastructure

#61696 Change target branch for release/dev17.3
  eng/config/PublishData.json
Labels: Area-Infrastructure

#46349 Update xunit.analyzers
  eng/Versions.props
  eng/targets/XUnit.targets
  src/Compilers/CSharp/Test/Emit/Emit/EmitMetadataTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/CorLibrary/CorTypes.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/ExtensionMethodTests.cs
  src/Compilers/Core/CodeAnalysisTest/Text/TextSpanTest.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/OperatorCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest2/EmbeddedLanguages/RegularExpressions/CSharpRegexParserTests_RealWorld.cs
  src/EditorFeatures/DiagnosticsTestUtilities/ChangeSignature/AbstractChangeSignatureTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/DeclarationTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/DynamicTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/ExpressionCompilerTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/TupleTests.cs
  src/ExpressionEvaluator/CSharp/Test/ResultProvider/ExpansionTests.cs
  src/Workspaces/CoreTest/UtilityTest/EditDistanceTests.cs
Labels: Area-Analyzers

#61683 Fixed nullability of enums in switches
  src/Analyzers/CSharp/CodeFixes/PopulateSwitch/CSharpPopulateSwitchExpressionCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/PopulateSwitch/PopulateSwitchExpressionTests.cs
  src/Analyzers/CSharp/Tests/PopulateSwitch/PopulateSwitchStatementTests.cs
  src/Analyzers/Core/Analyzers/PopulateSwitch/PopulateSwitchExpressionHelpers.cs
  src/Analyzers/Core/Analyzers/PopulateSwitch/PopulateSwitchStatementHelpers.cs
  src/Analyzers/Core/CodeFixes/PopulateSwitch/AbstractPopulateSwitchCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/PopulateSwitch/AbstractPopulateSwitchExpressionCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/PopulateSwitch/AbstractPopulateSwitchStatementCodeFixProvider.cs
Labels: Area-IDE, Community

#61688 Nullable annotate the lexer and a few related files
  src/Compilers/CSharp/Portable/Errors/SyntaxDiagnosticInfo.cs
  src/Compilers/CSharp/Portable/Errors/XmlSyntaxDiagnosticInfo.cs
  src/Compilers/CSharp/Portable/Parser/AbstractLexer.cs
  src/Compilers/CSharp/Portable/Parser/Directives.cs
  src/Compilers/CSharp/Portable/Parser/DocumentationCommentXmlTokens.cs
  src/Compilers/CSharp/Portable/Parser/Lexer.cs
  src/Compilers/CSharp/Portable/Parser/Lexer_StringLiteral.cs
  src/Compilers/CSharp/Portable/Parser/QuickScanner.cs
  src/Compilers/CSharp/Portable/Parser/SlidingTextWindow.cs
Labels: Area-Compilers, Community

#61568 Include local-functions in the go-to index.
  src/EditorFeatures/CSharpTest/NavigateTo/NavigateToTests.cs
  src/Workspaces/CSharp/Portable/FindSymbols/CSharpDeclaredSymbolInfoFactoryService.cs
  src/Workspaces/Core/Portable/FindSymbols/Shared/AbstractSyntaxIndex_Persistence.cs
  src/Workspaces/Core/Portable/LanguageServices/DeclaredSymbolFactoryService/AbstractDeclaredSymbolInfoFactoryService.cs
  src/Workspaces/VisualBasic/Portable/FindSymbols/VisualBasicDeclaredSymbolInfoFactoryService.vb
Labels: Area-IDE

#61701 Suggest `return` keyword for regular top-level statements
  src/EditorFeatures/CSharpTest2/Recommendations/ReturnKeywordRecommenderTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/ReturnKeywordRecommender.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/CSharpSyntaxContext.cs
Labels: Area-IDE, Community

#61702 Fixed empty types section shown in quick info
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
  src/EditorFeatures/TestUtilities/QuickInfo/AbstractSemanticQuickInfoSourceTests.cs
  src/EditorFeatures/VisualBasicTest/QuickInfo/SemanticQuickInfoSourceTests.vb
  src/Features/Core/Portable/LanguageServices/AnonymousTypeDisplayService/AbstractStructuralTypeDisplayService.cs
  src/Features/Core/Portable/LanguageServices/SymbolDisplayService/AbstractSymbolDisplayService.AnonymousTypes.cs
Labels: Area-IDE, Community

#61590 Add collapsedText to foldingRange
  src/Features/LanguageServer/Protocol/Handler/FoldingRanges/FoldingRangesHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/FoldingRanges/FoldingRangesTests.cs
  src/Features/Lsif/GeneratorTest/FoldingRangeTests.vb
Labels: Area-IDE

#61712 Remove usage of IOptionService from WorkCoordinator
  src/EditorFeatures/CSharpTest/Workspaces/WorkspaceTests.cs
  src/EditorFeatures/Core.Wpf/InlineDiagnostics/InlineDiagnosticsTaggerProvider.cs
  src/EditorFeatures/Core/Classification/Semantic/AbstractSemanticOrEmbeddedClassificationViewTaggerProvider.cs
  src/EditorFeatures/Core/InlineHints/InlineHintsDataTaggerProvider.cs
  src/EditorFeatures/Core/Shared/Tagging/EventSources/TaggerEventSources.OptionChangedEventSource.cs
  src/EditorFeatures/Core/Shared/Tagging/EventSources/TaggerEventSources.cs
  src/EditorFeatures/Core/Structure/AbstractStructureTaggerProvider.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource.cs
  src/EditorFeatures/Test/SolutionCrawler/WorkCoordinatorTests.cs
  src/EditorFeatures/Test/Workspaces/ProjectCacheHostServiceFactoryTests.cs
  src/EditorFeatures/TestUtilities/TestOptionsServiceFactory.cs
  src/EditorFeatures/TestUtilities/TestOptionsServiceWithSharedGlobalOptionsServiceFactory.cs
  src/Features/Core/Portable/SolutionCrawler/AggregateIncrementalAnalyzer.cs
  src/Features/Core/Portable/SolutionCrawler/IncrementalAnalyzerBase.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.AbstractPriorityProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DefaultDiagnosticAnalyzerService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.cs
  src/VisualStudio/Core/Def/InheritanceMargin/InheritanceMarginTaggerProvider.cs
  src/VisualStudio/Core/Def/StackTraceExplorer/StackTraceExplorerCommandHandler.cs
  src/Workspaces/Core/Portable/ExternalAccess/UnitTesting/Api/IUnitTestingIncrementalAnalyzerImplementation.cs
  src/Workspaces/Core/Portable/ExternalAccess/UnitTesting/Api/UnitTestingOptionChangedEventArgsWrapper.cs
  src/Workspaces/Core/Portable/ExternalAccess/UnitTesting/UnitTestingIncrementalAnalyzer.cs
  src/Workspaces/Core/Portable/Options/IOptionService.cs
  src/Workspaces/Core/Portable/Options/IWorkspaceOptionService.cs
  src/Workspaces/Core/Portable/Options/OptionServiceFactory.cs
  src/Workspaces/Core/Portable/SolutionCrawler/IIncrementalAnalyzer.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
  src/Workspaces/CoreTest/Host/WorkspaceServices/TestOptionService.cs
  src/Workspaces/CoreTest/Host/WorkspaceServices/TestOptionsServiceFactory.cs
  src/Workspaces/Remote/ServiceHub/Services/ProjectTelemetry/ApiUsageIncrementalAnalyzerProvider.cs
Labels: Area-IDE

#61657 Fixed incorrect discard suggestion in var pattern
  src/Analyzers/CSharp/CodeFixes/RemoveUnusedParametersAndValues/CSharpRemoveUnusedValuesCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/RemoveUnusedParametersAndValues/RemoveUnusedValueAssignmentTests.cs
  src/Analyzers/Core/CodeFixes/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs
  src/Analyzers/VisualBasic/CodeFixes/RemoveUnusedParametersAndValues/VisualBasicRemoveUnusedValuesCodeFixProvider.vb
Labels: Area-IDE, Community

#61406 Remove solution options OOP serialization
  src/VisualStudio/Core/Test.Next/Remote/SerializationValidator.cs
  src/VisualStudio/Core/Test.Next/Remote/SnapshotSerializationTests.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/VisualStudio/Core/Test.Next/Services/SolutionServiceTests.cs
  src/Workspaces/Core/Portable/Remote/ISerializerService.cs
  src/Workspaces/Core/Portable/Remote/WellKnownSynchronizationKind.cs
  src/Workspaces/Core/Portable/Serialization/SerializationExtensions.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService_OptionSet.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState_Checksum.cs
  src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
  src/Workspaces/CoreTest/WorkspaceServiceTests/OptionServiceTests.cs
  src/Workspaces/Remote/Core/AbstractAssetProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
  src/Workspaces/Remote/ServiceHub/Host/TestUtils.cs
Labels: Area-IDE

#61690 Use fast in-proc heuristic to implement HasChangesAsync
  src/EditorFeatures/Core/EditAndContinue/EditAndContinueLanguageService.cs
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/EditorFeatures/Test/EditAndContinue/RemoteEditAndContinueServiceTests.cs
  src/EditorFeatures/TestUtilities/EditAndContinue/MockEditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/CommittedSolution.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueDocumentAnalysesCache.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/Core/Portable/EditAndContinue/IEditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/Remote/IRemoteEditAndContinueService.cs
  src/Features/Core/Portable/EditAndContinue/Remote/RemoteDebuggingSessionProxy.cs
  src/Tools/ExternalAccess/Debugger/GlassTestsHotReloadService.cs
  src/Workspaces/Remote/ServiceHub/Services/EditAndContinue/RemoteEditAndContinueService.cs
Labels: Interactive-EnC

#61675 Add a hack to remove output from the Razor generator if suppressed
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
Labels: Area-IDE, Approved to merge

#61519 Add Move Static Member To Existing Type
  src/EditorFeatures/CSharpTest/MoveStaticMembers/CSharpMoveStaticMembersTests.cs
  src/EditorFeatures/TestUtilities/MoveStaticMembers/TestMoveStaticMembersService.cs
  src/EditorFeatures/VisualBasicTest/MoveStaticMembers/VisualBasicMoveStaticMembersTests.vb
  src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersOptions.cs
  src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs
  src/VisualStudio/Core/Def/MoveStaticMembers/MoveStaticMembersDialog.xaml
  src/VisualStudio/Core/Def/MoveStaticMembers/MoveStaticMembersDialogViewModel.cs
  src/VisualStudio/Core/Def/MoveStaticMembers/TypeNameItem.cs
  src/VisualStudio/Core/Def/MoveStaticMembers/VisualStudioMoveStaticMembersOptionsService.cs
  src/VisualStudio/Core/Test/MoveStaticMembers/MoveStaticMembersViewModelTest.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE

#59739 View call hierarchy fix (#57856)
  src/VisualStudio/CSharp/Test/CallHierarchy/CSharpCallHierarchyTests.cs
  src/VisualStudio/Core/Test/CallHierarchy/CallHierarchyTests.vb
  src/VisualStudio/TestUtilities2/CallHierarchy/CallHierarchyTestState.vb
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_Callers.cs
Labels: Area-IDE, Community

#61725 Fix crash with embedded lang detection in VB
  src/EditorFeatures/VisualBasicTest/Classification/SemanticClassifierTests.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE

#61722 Change LOC branch for VS 17.3
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#61697 Replace conditional with assignment
  src/EditorFeatures/CSharpTest/ReplaceConditionalWithStatements/ReplaceConditionalWithStatementsTests.cs
  src/EditorFeatures/VisualBasicTest/ReplaceConditionalWithStatements/ReplaceConditionalWithStatementsTests.vb
  src/Features/CSharp/Portable/ReplaceConditionalWithStatements/CSharpReplaceConditionalWithStatementsCodeRefactoringProvider.cs
  src/Features/Core/Portable/CodeRefactorings/PredefinedCodeRefactoringProviderNames.cs
  src/Features/Core/Portable/ConvertForToForEach/AbstractConvertForToForEachCodeRefactoringProvider.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/ReplaceConditionalWithStatements/AbstractReplaceConditionalWithStatementsCodeRefactoringProvider.cs
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Features/VisualBasic/Portable/ReplaceConditionalWithStatementsCodeRefactoringProvider/VisualBasicReplaceConditionalWithStatementsCodeRefactoringProvider.vb
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFactsExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxKinds.vb
  src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb
Labels: Area-IDE

#61728 Insert braces for field and event in SmartBreakLine
  src/EditorFeatures/CSharp/AutomaticCompletion/AutomaticLineEnderCommandHandler.cs
  src/EditorFeatures/CSharp/AutomaticCompletion/AutomaticLineEnderCommandHandler_Helpers.cs
  src/EditorFeatures/CSharpTest/AutomaticCompletion/AutomaticLineEnderTests.cs
Labels: Area-IDE

#61720 Correctly add parameter when represented as a method group
  src/EditorFeatures/CSharpTest/AddParameter/AddParameterTests.cs
  src/Features/CSharp/Portable/AddParameter/CSharpAddParameterCodeFixProvider.cs
  src/Features/Core/Portable/AddParameter/AbstractAddParameterCodeFixProvider.cs
  src/Features/VisualBasic/Portable/AddParameter/VisualBasicAddParameterCodeFixProvider.vb
Labels: Area-IDE, Community

#61731 PR feedback on the 'replace conditional with statements' PR.
  src/Features/Core/Portable/ReplaceConditionalWithStatements/AbstractReplaceConditionalWithStatementsCodeRefactoringProvider.cs
Labels: Area-IDE

#61684 Unwrap unexpected AggregateException for clarity
  src/Compilers/Core/Portable/Serialization/ObjectReader.cs
Labels: Area-Compilers

#61730 Avoid double typechecks in simple code checks
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Members.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/CompilationCreationTests.cs
  src/Features/CSharp/Portable/Debugging/CSharpProximityExpressionsService.Worker.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.ExpressionCodeGenerator.cs
  src/VisualStudio/Core/Impl/CodeModel/ExternalElements/ExternalCodeClass.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ISymbolExtensions.cs
Labels: Area-Compilers

#61739 Don't bubble up linked token cancellation to the batching work queue
  src/EditorFeatures/Core/Remote/SolutionChecksumUpdater.cs
  src/Features/Core/Portable/Workspace/BackgroundCompiler.cs
  src/Workspaces/Core/Portable/Shared/Utilities/AsyncBatchingWorkQueue`2.cs
Labels: Area-IDE

#61650 Tweak UTF-8 string literal analyzer and code fix after language change
  src/Analyzers/CSharp/Analyzers/CSharpAnalyzersResources.resx
  src/Analyzers/CSharp/Analyzers/UseUTF8StringLiteral/UseUTF8StringLiteralDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.cs.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.de.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.es.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.fr.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.it.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.ja.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.ko.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.pl.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.pt-BR.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.ru.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.tr.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.zh-Hans.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.zh-Hant.xlf
  src/Analyzers/CSharp/CodeFixes/UseUTF8StringLiteral/UseUTF8StringLiteralCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseUTF8StringLiteral/UseUTF8StringLiteralTests.cs
  src/EditorFeatures/CSharp/CodeCleanup/CSharpCodeCleanupService.cs
  src/EditorFeatures/CSharpTest/Formatting/CodeCleanupTests.cs
  src/Features/CSharp/Portable/CSharpFeaturesResources.resx
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.cs.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.de.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.es.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.fr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.it.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ja.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ko.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pl.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pt-BR.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ru.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.tr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hans.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hant.xlf
  src/VisualStudio/CSharp/Impl/Options/AutomationObject/AutomationObject.Style.cs
  src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs
Labels: Area-IDE

#61670 Prefer stack storage for highly-contended temporary array
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/BinaryOperatorOverloadResolution.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs
  src/Compilers/Core/CodeAnalysisTest/Collections/TemporaryArrayTests.cs
  src/Compilers/Core/Portable/Collections/TemporaryArrayExtensions.cs
  src/Compilers/Core/Portable/Collections/TemporaryArray`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
Labels: Area-Compilers

#61729 Avoid delegate allocations for ImmutableArray<T>.Any
  src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/UserDefinedExplicitConversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/UserDefinedImplicitConversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Portable/Binder/SwitchBinder_Patterns.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundDecisionDag.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/CSharpCompilationOptions.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitArrayInitializer.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs
  src/Compilers/CSharp/Portable/Compilation/SyntaxAndDeclarationManager.cs
  src/Compilers/CSharp/Portable/Emitter/Model/GenericTypeInstanceReference.cs
  src/Compilers/CSharp/Portable/Emitter/Model/SpecializedGenericNestedTypeInstanceReference.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncRewriter.AsyncIteratorRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.DecisionDagRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Types.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeManager.Templates.cs
  src/Compilers/CSharp/Portable/Symbols/MemberSymbolExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEFieldSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEPropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/ReducedExtensionMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/CustomModifierUtils.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordDeconstruct.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPrintMembers.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedInteractiveInitializerMethod.cs
  src/Compilers/CSharp/Portable/Symbols/TypeMap.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/VarianceSafety.cs
  src/Compilers/Core/Portable/Compilation/Compilation.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerImageReference.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/EmitBaseline.cs
  src/Compilers/Core/Portable/MetadataReader/MetadataDecoder.cs
  src/Compilers/Core/Portable/Operations/OperationExtensions.cs
  src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs
  src/Compilers/Core/Portable/StrongName/DesktopStrongNameProvider.cs
  src/Compilers/Core/Portable/Syntax/LineDirectiveMap.cs
  src/Compilers/Core/Rebuild/CompilationOptionsReader.cs
Labels: Area-Compilers

#61745 Simplify nested lambda
  src/Compilers/CSharp/Portable/Binder/SwitchBinder_Patterns.cs
Labels: Area-Compilers

#61250 EditorFeatures.Cocoa: Bump macos workload to RC3
  eng/Versions.props
  src/EditorFeatures/Core.Cocoa/Microsoft.CodeAnalysis.EditorFeatures.Cocoa.csproj
Labels: Area-IDE

#61620 Reducing allocations in completion
  eng/config/BannedSymbols.txt
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/AbstractCSharpCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ObjectInitializerCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/OverrideCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests_NoInteractive.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/TypeImportCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionServiceTests.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/CompletionSource.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/ItemManager.CompletionListUpdater.cs
  src/EditorFeatures/Core/LanguageServer/Handlers/Completion/CompletionHandler.cs
  src/EditorFeatures/Core/LanguageServer/Handlers/Completion/CompletionResolveHandler.cs
  src/EditorFeatures/Test/Completion/CompletionServiceTests.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/EditorFeatures/Test2/IntelliSense/CompletionServiceTests.vb
  src/EditorFeatures/Test2/IntelliSense/CompletionServiceTests_Exclusivitiy.vb
  src/EditorFeatures/TestUtilities/Completion/AbstractCompletionProviderTests.cs
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/AbstractVisualBasicCompletionProviderTests.vb
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/ImplementsClauseCompletionProviderTests.vb
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/OverrideCompletionProviderTests.vb
  src/Features/Core/Portable/Completion/CommonCompletionService.cs
  src/Features/Core/Portable/Completion/CompletionContext.cs
  src/Features/Core/Portable/Completion/CompletionList.cs
  src/Features/Core/Portable/Completion/CompletionService.cs
  src/Features/Core/Portable/Completion/CompletionServiceWithProviders.cs
  src/Features/Core/Portable/Completion/MatchResult.cs
  src/Features/Core/Portable/SpellCheck/AbstractSpellCheckCodeFixProvider.cs
  src/Workspaces/Core/Portable/PatternMatching/PatternMatch.cs
  src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ICompilationExtensions.cs
Labels: Area-IDE

#61761 Include IndentBlockFormattingRule in AddMissingImportsService
  src/Features/CSharp/Portable/AddImport/CSharpAddMissingImportsFeatureService.cs
  src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs
  src/Features/VisualBasic/Portable/AddImport/VisualBasicAddMissingImportsFeatureService.vb
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpAddMissingUsingsOnPaste.cs
Labels: Area-IDE

#61377 Add opened and closed event handling for non-source documents
  src/EditorFeatures/CSharpTest/Workspaces/WorkspaceTests.cs
  src/EditorFeatures/Test/SolutionCrawler/WorkCoordinatorTests.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestHostDocument.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.cs
  src/Workspaces/Core/Portable/ExternalAccess/UnitTesting/Api/UnitTestingTextDocumentEventArgsWrapper.cs
  src/Workspaces/Core/Portable/ExternalAccess/UnitTesting/Api/UnitTestingWorkspaceExtensions.cs
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
  src/Workspaces/Core/Portable/Workspace/TextDocumentEventArgs.cs
  src/Workspaces/Core/Portable/Workspace/Workspace_Editor.cs
  src/Workspaces/Core/Portable/Workspace/Workspace_Events.cs
Labels: Area-IDE

#61693 Remove ISupportDirectMemoryAccess.
  src/Compilers/Core/CodeAnalysisTest/MetadataReferences/ModuleMetadataTests.cs
  src/Compilers/Core/Portable/MetadataReference/ModuleMetadata.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/EditorFeatures/Test/Workspaces/TextFactoryTests.cs
  src/VisualStudio/Core/Def/ProjectSystem/MetadataReferences/VisualStudioMetadataReferenceManager.Factory.cs
  src/VisualStudio/Core/Def/ProjectSystem/MetadataReferences/VisualStudioMetadataReferenceManager.RecoverableMetadataValueSource.cs
  src/VisualStudio/Core/Def/ProjectSystem/MetadataReferences/VisualStudioMetadataReferenceManager.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService_Reference.cs
  src/Workspaces/Core/Portable/TemporaryStorage/TemporaryStorageService.Factory.cs
  src/Workspaces/Core/Portable/TemporaryStorage/TemporaryStorageService.MemoryMappedInfo.cs
  src/Workspaces/Core/Portable/TemporaryStorage/TemporaryStorageServiceFactory.cs
  src/Workspaces/Core/Portable/Workspace/Host/TemporaryStorage/ISupportDirectMemoryAccess.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
  src/Workspaces/CoreTest/WorkspaceServiceTests/TemporaryStorageServiceTests.cs
Labels: Area-IDE, Area-Compilers

#61396 [LSP] Disable sln crawler diagnostics when LSP pull is enabled
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.State.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSourceProvider.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptPullDiagnosticHandlerProvider.cs
  src/Features/Core/Portable/SolutionCrawler/IncrementalAnalyzerBase.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DefaultDiagnosticAnalyzerService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DiagnosticAnalyzerService_IncrementalAnalyzer.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DocumentPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DocumentPullDiagnosticHandlerFactory.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Experimental/ExperimentalDocumentPullDiagnosticHandlerFactory.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Experimental/ExperimentalDocumentPullDiagnosticsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Experimental/ExperimentalWorkspacePullDiagnosticHandlerFactory.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Experimental/ExperimentalWorkspacePullDiagnosticsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandlerFactory.cs
  src/Features/LanguageServer/Protocol/Handler/PullHandlers/VersionedPullCache`2.cs
Labels: Area-IDE

#61766 Mark parameter that cannot be null as non-nullable
  src/Workspaces/Core/Portable/Classification/SyntaxClassification/AbstractNameSyntaxClassifier.cs
Labels: Area-IDE, Community

#61755 Update DartLab pipeline to use new agent template
  azure-pipelines-integration-dartlab.yml
Labels: Area-Infrastructure

#61751 Add explanation of IDE design process and include template
  .github/ISSUE_TEMPLATE/feature-suggestion.md
  docs/contributing/ide_design_process.md
Labels: Area-IDE

#61781 Remove LogPositionChanged, it's not needed for data anymore
  src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs
Labels: Area-IDE

#61526 Find implementation assemblies for reference assemblies in the .NET SDK
  src/EditorFeatures/CSharpTest/PdbSourceDocument/AbstractPdbSourceDocumentTests.cs
  src/EditorFeatures/CSharpTest/PdbSourceDocument/ImplementationAssemblyLookupServiceTests.cs
  src/EditorFeatures/CSharpTest/PdbSourceDocument/PdbSourceDocumentTests.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/MetadataAsSource/DecompilationMetadataAsSourceFileProvider.cs
  src/Features/Core/Portable/MetadataAsSource/MetadataAsSourceHelpers.cs
  src/Features/Core/Portable/PdbSourceDocument/DocumentDebugInfoReader.cs
  src/Features/Core/Portable/PdbSourceDocument/IImplementationAssemblyLookupService.cs
  src/Features/Core/Portable/PdbSourceDocument/ImplementationAssemblyLookupService.cs
  src/Features/Core/Portable/PdbSourceDocument/PdbSourceDocumentMetadataAsSourceFileProvider.cs
  src/Features/Core/Portable/PdbSourceDocument/SymbolSourceDocumentFinder.cs
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
Labels: Area-IDE

#61750 Add experimental option to semantic snippet experience
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/AbstractCSharpSnippetCompletionProviderTests.cs
  src/EditorFeatures/TestUtilities/Completion/AbstractCompletionProviderTests.cs
  src/Features/Core/Portable/Completion/CompletionOptions.cs
  src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs
  src/Features/LanguageServer/Protocol/Features/Options/CompletionOptionsStorage.cs
  src/VisualStudio/CSharp/Impl/CSharpVSResources.resx
  src/VisualStudio/CSharp/Impl/Options/IntelliSenseOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/IntelliSenseOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/IntelliSenseOptionPageStrings.cs
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.cs.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.de.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.es.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.fr.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.it.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.ja.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.ko.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.pl.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.pt-BR.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.ru.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.tr.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.zh-Hans.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.zh-Hant.xlf
Labels: Area-IDE

#61786 Revert "Add Move Static Member To Existing Type (#61519)"
  src/EditorFeatures/CSharpTest/MoveStaticMembers/CSharpMoveStaticMembersTests.cs
  src/EditorFeatures/TestUtilities/MoveStaticMembers/TestMoveStaticMembersService.cs
  src/EditorFeatures/VisualBasicTest/MoveStaticMembers/VisualBasicMoveStaticMembersTests.vb
  src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersOptions.cs
  src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs
  src/VisualStudio/Core/Def/MoveStaticMembers/MoveStaticMembersDialog.xaml
  src/VisualStudio/Core/Def/MoveStaticMembers/MoveStaticMembersDialogViewModel.cs
  src/VisualStudio/Core/Def/MoveStaticMembers/TypeNameItem.cs
  src/VisualStudio/Core/Def/MoveStaticMembers/VisualStudioMoveStaticMembersOptionsService.cs
  src/VisualStudio/Core/Test/MoveStaticMembers/MoveStaticMembersViewModelTest.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE

#61779 Add asp.net extensibility hooks for embedded language brace matching
  src/EditorFeatures/Core/BraceMatching/AbstractEmbeddedLanguageBraceMatcher.cs
  src/EditorFeatures/Core/BraceMatching/IEmbeddedLanguageBraceMatcher.cs
  src/EditorFeatures/Core/EmbeddedLanguages/Json/AbstractJsonEmbeddedLanguageBraceMatcher.cs
  src/EditorFeatures/Core/EmbeddedLanguages/RegularExpressions/AbstractRegexEmbeddedLanguageBraceMatcher.cs
  src/EditorFeatures/Core/Extensibility/BraceMatching/IBraceMatcher.cs
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/Tools/ExternalAccess/AspNetCore/EmbeddedLanguages/BraceMatching/AspNetBraceMatchingResult.cs
  src/Tools/ExternalAccess/AspNetCore/EmbeddedLanguages/BraceMatching/AspNetCoreBraceMatcherExtensionProvider.cs
  src/Tools/ExternalAccess/AspNetCore/EmbeddedLanguages/BraceMatching/ExportAspNetCoreEmbeddedLanguageBraceMatcherAttribute.cs
  src/Tools/ExternalAccess/AspNetCore/EmbeddedLanguages/BraceMatching/IAspNetCoreEmbeddedLanguageBraceMatcher.cs
  src/Tools/ExternalAccess/AspNetCore/EmbeddedLanguages/Classification/AspNetCoreClassifierExtensionProvider.cs
  src/Tools/ExternalAccess/AspNetCore/EmbeddedLanguages/Classification/AspNetCoreEmbeddedLanguageClassificationContext.cs
  src/Tools/ExternalAccess/AspNetCore/EmbeddedLanguages/Classification/ExportAspNetCoreEmbeddedLanguageClassifierAttribute.cs
  src/Tools/ExternalAccess/AspNetCore/EmbeddedLanguages/Classification/IAspNetCoreEmbeddedLanguageClassifier.cs
  src/Tools/ExternalAccess/AspNetCore/Internal/EmbeddedLanguages/AspNetCoreEmbeddedLanguageBraceMatcher.cs
  src/Tools/ExternalAccess/AspNetCore/Microsoft.CodeAnalysis.ExternalAccess.AspNetCore.csproj
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
Labels: Area-IDE

#61738 Check 'scoped' differences in overrides and interface implementations
  src/Compilers/CSharp/Portable/Binder/Binder_AnonymousTypes.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Query.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Lowering/ClosureConversion/SynthesizedClosureMethod.cs
  src/Compilers/CSharp/Portable/Lowering/SynthesizedMethodBaseSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeDescriptor.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeField.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeManager.Templates.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/PublicSymbols/AnonymousType.DelegatePublicSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.DelegateTemplateSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ParameterHelpers.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceCustomEventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodOrUserDefinedOperatorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedDelegateSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedIntrinsicOperatorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_LifetimeAnnotation.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_NativeInteger.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EEMethodSymbol.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/ObjectIdLocalSymbol.cs
Labels: Area-Compilers, New Language Feature - Ref Fields

#61801 Rename EA type for aspnetcore
  src/Tools/ExternalAccess/AspNetCore/EmbeddedLanguages/BraceMatching/AspNetCoreBraceMatchingResult.cs
  src/Tools/ExternalAccess/AspNetCore/EmbeddedLanguages/BraceMatching/IAspNetCoreEmbeddedLanguageBraceMatcher.cs
Labels: Area-IDE

#61804 Show rename flyout only on active view
  src/EditorFeatures/Core.Wpf/InlineRename/UI/InlineRenameAdornmentManager.cs
Labels: Area-IDE

#61782 Fix lexing of the end of pp directives
  src/Compilers/CSharp/Portable/Parser/DirectiveParser.cs
  src/Compilers/CSharp/Portable/Parser/Lexer.cs
  src/Compilers/CSharp/Test/Syntax/LexicalAndXml/PreprocessorTests.cs
Labels: Area-Compilers

#61760 [LSP] Filter out tracked document changes in semantic tokens handler
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensRangeHandler.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensRangeHandlerFactory.cs
Labels: Area-IDE, LSP

#61818 Change telemetry on solution option change action to be by provider
  src/Features/CSharp/Portable/UpdateProjectToAllowUnsafe/CSharpUpdateProjectToAllowUnsafeCodeFixProvider.cs
  src/Features/Core/Portable/UpgradeProject/AbstractUpgradeProjectCodeFixProvider.cs
  src/Workspaces/Core/Portable/CodeActions/CodeAction.cs
Labels: Area-IDE

#61827 Fix typo
  src/Features/CSharp/Portable/SyncNamespaces/CSharpSyncNamespacesService.cs
  src/Features/Core/Portable/SyncNamespaces/AbstractSyncNamespacesService.cs
Labels: Area-IDE, Community

#61821 Use the complete branch name in DartLab yml
  azure-pipelines-integration-dartlab.yml
Labels: Area-Infrastructure

#61408 Organize contributing notes and add WSL testing section
  docs/contributing/Building, Debugging, and Testing on Windows.md
Labels: Area-Compilers, Documentation

#61686 Require spaces within line span directives and relax LangVer check
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Parser/DirectiveParser.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Syntax/Parsing/LineSpanDirectiveParsingTests.cs
Labels: Area-Compilers

#61477 Switch AsyncCompletion to new pooled CompletionItemList based APIs
  eng/Versions.props
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/CompletionSessionData.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/CompletionSource.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/ItemManager.CompletionListUpdater.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/ItemManager.cs
  src/EditorFeatures/TestUtilities2/Intellisense/MockCompletionPresenter.vb
  src/VisualStudio/Core/Test/DebuggerIntelliSense/TestState.vb
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/LightBulbHelper.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/Editor_InProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/LightBulbHelper.cs
  src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb
  src/VisualStudio/VisualBasic/Impl/LanguageService/VisualBasicPackage.vb
Labels: Area-IDE, Needs Shiproom Approval

#61754 Adjust implementation of user-defined conversion resolution according to the latest LDM decision
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/UserDefinedConversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/UserDefinedExplicitConversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/UserDefinedImplicitConversions.cs
  src/Compilers/CSharp/Portable/Symbols/TypeParameterSymbol.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
Labels: Area-Compilers, New Feature - StaticAbstractMembersInInterfaces

#61817 Update document highlighting to follow new pattern for embedded language extensibility.
  src/EditorFeatures/CSharp/EmbeddedLanguages/CSharpJsonBraceMatcher.cs
  src/EditorFeatures/CSharp/EmbeddedLanguages/CSharpRegexBraceMatcher.cs
  src/EditorFeatures/Core/EmbeddedLanguages/Json/AbstractJsonBraceMatcher.cs
  src/EditorFeatures/Core/EmbeddedLanguages/RegularExpressions/AbstractRegexBraceMatcher.cs
  src/EditorFeatures/VisualBasic/EmbeddedLanguages/VisualBasicJsonBraceMatcher.vb
  src/EditorFeatures/VisualBasic/EmbeddedLanguages/VisualBasicRegexBraceMatcher.vb
  src/Features/CSharp/Portable/DocumentHighlighting/CSharpDocumentHighlightsService.cs
  src/Features/CSharp/Portable/EmbeddedLanguages/CSharpJsonClassifier.cs
  src/Features/CSharp/Portable/EmbeddedLanguages/CSharpRegexClassifier.cs
  src/Features/CSharp/Portable/EmbeddedLanguages/CSharpRegexDocumentHighlighter.cs
  src/Features/Core/Portable/DocumentHighlighting/AbstractDocumentHighlightsService.cs
  src/Features/Core/Portable/DocumentHighlighting/ExportEmbeddedLanguageDocumentHighlighterAttribute.cs
  src/Features/Core/Portable/DocumentHighlighting/IEmbeddedLanguageDocumentHighlighter.cs
  src/Features/Core/Portable/EmbeddedLanguages/IEmbeddedLanguageFeatures.cs
  src/Features/Core/Portable/EmbeddedLanguages/Json/LanguageServices/AbstractJsonClassifier.cs
  src/Features/Core/Portable/EmbeddedLanguages/Json/LanguageServices/JsonEmbeddedLanguage.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/AbstractRegexClassifier.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/AbstractRegexDocumentHighlighter.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexEmbeddedLanguage.cs
  src/Features/VisualBasic/Portable/DocumentHighlighting/VisualBasicDocumentHighlightsService.vb
  src/Features/VisualBasic/Portable/EmbeddedLanguages/VisualBasicJsonClassifier.vb
  src/Features/VisualBasic/Portable/EmbeddedLanguages/VisualBasicRegexClassifier.vb
  src/Features/VisualBasic/Portable/EmbeddedLanguages/VisualBasicRegexDocumentHighlighter.vb
  src/Workspaces/Core/Portable/Classification/EmbeddedLanguages/PredefinedEmbeddedLanguageClassifierNames.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/ExportEmbeddedLanguageFeatureServiceAttribute.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/PredefinedEmbeddedLanguageClassifierNames.cs
Labels: Area-IDE

#61795 Fix BuildActionTelemetryTable tool
  src/Tools/BuildActionTelemetryTable/BuildActionTelemetryTable.csproj
  src/Tools/BuildActionTelemetryTable/Program.cs
Labels: Area-Infrastructure

#61717 Report an error for an implicit implementation of an inaccessible interface members
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/UpgradeProject/UpgradeProjectTests.cs
Labels: Area-Compilers, New Language Feature - Default Interface Impl, New Feature - StaticAbstractMembersInInterfaces

#61862 Simplify embedded language export system.
  src/EditorFeatures/CSharp/EmbeddedLanguages/CSharpJsonBraceMatcher.cs
  src/EditorFeatures/CSharp/EmbeddedLanguages/CSharpRegexBraceMatcher.cs
  src/EditorFeatures/Core/BraceMatching/ExportEmbeddedLanguageBraceMatcherAttribute.cs
  src/EditorFeatures/Core/EmbeddedLanguages/Json/JsonBraceMatcher.cs
  src/EditorFeatures/Core/EmbeddedLanguages/RegularExpressions/RegexBraceMatcher.cs
  src/EditorFeatures/VisualBasic/EmbeddedLanguages/VisualBasicJsonBraceMatcher.vb
  src/EditorFeatures/VisualBasic/EmbeddedLanguages/VisualBasicRegexBraceMatcher.vb
  src/Features/CSharp/Portable/EmbeddedLanguages/CSharpJsonClassifier.cs
  src/Features/CSharp/Portable/EmbeddedLanguages/CSharpRegexClassifier.cs
  src/Features/CSharp/Portable/EmbeddedLanguages/CSharpRegexDocumentHighlighter.cs
  src/Features/Core/Portable/DocumentHighlighting/ExportEmbeddedLanguageDocumentHighlighterAttribute.cs
  src/Features/Core/Portable/EmbeddedLanguages/AbstractEmbeddedLanguagesFeaturesProvider.cs
  src/Features/Core/Portable/EmbeddedLanguages/Json/LanguageServices/JsonClassifier.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexClassifier.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexDocumentHighlighter.cs
  src/Features/VisualBasic/Portable/EmbeddedLanguages/VisualBasicJsonClassifier.vb
  src/Features/VisualBasic/Portable/EmbeddedLanguages/VisualBasicRegexClassifier.vb
  src/Features/VisualBasic/Portable/EmbeddedLanguages/VisualBasicRegexDocumentHighlighter.vb
  src/Tools/ExternalAccess/AspNetCore/Internal/EmbeddedLanguages/AspNetCoreEmbeddedLanguageBraceMatcher.cs
  src/Tools/ExternalAccess/AspNetCore/Internal/EmbeddedLanguages/AspNetCoreEmbeddedLanguageClassifier.cs
  src/Workspaces/CSharp/Portable/EmbeddedLanguages/LanguageServices/CSharpEmbeddedLanguagesProvider.cs
  src/Workspaces/Core/Portable/Classification/EmbeddedLanguages/AbstractEmbeddedLanguageClassificationService.cs
  src/Workspaces/Core/Portable/Classification/EmbeddedLanguages/EmbeddedLanguageClassifierContext.cs
  src/Workspaces/Core/Portable/Classification/EmbeddedLanguages/ExportEmbeddedLanguageClassifier.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/AbstractEmbeddedLanguageFeatureService.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/AbstractEmbeddedLanguagesProvider.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/EmbeddedLanguageInfo.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/EmbeddedLanguageMetadata.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/ExportEmbeddedLanguageFeatureServiceAttribute.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/IEmbeddedLanguagesProvider.cs
  src/Workspaces/VisualBasic/Portable/EmbeddedLanguages/LanguageServices/VisualBasicEmbeddedLanguagesProvider.vb
Labels: Area-IDE

#61864 Add Asp.net extensibility point for document highlighting.
  src/Tools/ExternalAccess/AspNetCore/EmbeddedLanguages/DocumentHighlighting/AspNetCoreClassifierExtensionProvider.cs
  src/Tools/ExternalAccess/AspNetCore/EmbeddedLanguages/DocumentHighlighting/ExportAspNetCoreEmbeddedLanguageClassifierAttribute.cs
  src/Tools/ExternalAccess/AspNetCore/EmbeddedLanguages/DocumentHighlighting/IEmbeddedLanguageDocumentHighlighter.cs
  src/Tools/ExternalAccess/AspNetCore/Internal/EmbeddedLanguages/AspNetCoreEmbeddedLanguageDocumentHighlighter.cs
Labels: Area-IDE

#61867 Sort the generated CodeAction telemetry table.
  src/Tools/BuildActionTelemetryTable/Program.cs
Labels: Area-Infrastructure

#59631 allow third party codfixers to be run in code cleanup
  src/Analyzers/Core/Analyzers/IDEDiagnosticIdToOptionMappingHelper.cs
  src/EditorFeatures/CSharp/CodeCleanup/CSharpCodeCleanupService.cs
  src/EditorFeatures/CSharpTest/Formatting/CodeCleanupTests.TestFixers.cs
  src/EditorFeatures/CSharpTest/Formatting/CodeCleanupTests.cs
  src/EditorFeatures/Test/EditAndContinue/Helpers/MockDiagnosticAnalyzerService.cs
  src/EditorFeatures/VisualBasic/CodeCleanup/VisualBasicCodeCleanupService.vb
  src/EditorFeatures/VisualBasicTest/Formatting/CodeCleanUpTests.vb
  src/Features/Core/Portable/CodeFixes/DiagnosticExtensions.cs
  src/Features/Core/Portable/Diagnostics/IDiagnosticAnalyzerService.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Features/LanguageServer/Protocol/Features/CodeCleanup/AbstractCodeCleanupService.cs
  src/Features/LanguageServer/Protocol/Features/CodeCleanup/EnabledDiagnosticOptions.cs
  src/Features/LanguageServer/Protocol/Features/CodeFixes/CodeFixService.cs
  src/Features/LanguageServer/Protocol/Features/CodeFixes/ICodeFixService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DiagnosticAnalyzerService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs
  src/VisualStudio/Core/Def/CodeCleanup/AbstractCodeCleanUpFixer.cs
  src/VisualStudio/Core/Def/CodeCleanup/CommonCodeCleanUpFixerDiagnosticIds.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/Core/Test/Diagnostics/ExternalDiagnosticUpdateSourceTests.vb
Labels: Area-IDE

#61875 Fix Rune access issue on AspNetCoreVirtualChar
  src/Tools/ExternalAccess/AspNetCore/EmbeddedLanguages/AspNetCoreVirtualChar.cs
Labels: Area-Infrastructure

#61840 Polish async suggestions
  src/Features/CSharp/Portable/Completion/CompletionProviders/EnumAndCompletionListTagCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/SnippetCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/SpeculativeTCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/AbstractNativeIntegerKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/AbstractSpecialTypePreselectingKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/DynamicKeywordRecommender.cs
  src/Features/Core/Portable/Completion/Providers/AbstractRecommendationServiceBasedCompletionProvider.cs
  src/Features/VisualBasic/Portable/Completion/KeywordRecommenders/Types/BuiltInTypesKeywordRecommender.vb
  src/VisualStudio/VisualBasic/Impl/Snippets/SnippetCompletionProvider.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/CSharpSyntaxContext.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/ContextQuery/SyntaxContext.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/VisualBasicSyntaxContext.vb
Labels: Area-IDE, Community

#61107 Use auto-properties for PropertyOverrides
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Tools/Source/CompilerGeneratorTools/Source/BoundTreeGenerator/BoundNodeClassWriter.cs
Labels: Area-Compilers, Community

#61669 Cleanups for our logging helpers
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/AsyncCompletionLogger.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/CompletionSource.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/ItemManager.cs
  src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs
  src/Features/Core/Portable/ChangeSignature/ChangeSignatureTelemetryLogger.cs
  src/Features/Core/Portable/Completion/Log/CompletionProvidersLogger.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractExtensionMethodImportCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/SerializableUnimportedExtensionMethods.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSession.cs
  src/Features/Core/Portable/SolutionCrawler/SolutionCrawlerLogger.cs
  src/Features/Core/Portable/SolutionCrawler/SolutionCrawlerRegistrationService.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.IncrementalAnalyzerProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DiagnosticAnalyzerService_IncrementalAnalyzer.cs
  src/Features/LanguageServer/Protocol/Handler/RequestTelemetryLogger.cs
  src/VisualStudio/Core/Def/InheritanceMargin/InheritanceMarginLogger.cs
  src/Workspaces/Core/Portable/CodeFixesAndRefactorings/CommonFixAllState.cs
  src/Workspaces/Core/Portable/Log/CorrelationIdFactory.cs
  src/Workspaces/Core/Portable/Log/HistogramLogAggregator.cs
  src/Workspaces/Core/Portable/Log/StatisticLogAggregator.cs
  src/Workspaces/Core/Portable/Log/StatisticResult.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionLogger.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Log/AbstractLogAggregator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Log/CountLogAggregator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensions.projitems
Labels: Area-IDE

#61643 Calculate containing type effective accessibility for required member enforcement
  src/Compilers/CSharp/Portable/Symbols/Source/ModifierUtils.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceConstructorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceFieldSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertyAccessorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/RequiredMembersTests.cs
Labels: Area-Compilers, New Feature - Required Members

#61293 Add helper for source generators to filter to nodes with attribute matching an attribute name
  src/Compilers/CSharp/Portable/SourceGeneration/CSharpGeneratorDriver.cs
  src/Compilers/CSharp/Portable/SourceGeneration/CSharpSyntaxHelper.cs
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Types.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_SimpleName.cs
  src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Core/Portable/SourceGeneration/GeneratorContexts.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorSyntaxWalker.cs
  src/Compilers/Core/Portable/SourceGeneration/GlobalAliases.cs
  src/Compilers/Core/Portable/SourceGeneration/ISyntaxHelper.cs
  src/Compilers/Core/Portable/SourceGeneration/IncrementalContexts.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/ISyntaxStrategy.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/PredicateSyntaxStrategy.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SharedInputNodes.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxNodeGrouping.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxReceiverStrategy.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider.ImmutableArrayValueComparer.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithSimpleName.cs
  src/Compilers/Core/Portable/SourceGeneration/WellKnownGeneratorInputs.cs
  src/Compilers/Core/Portable/SymbolDisplay/SymbolDisplayCompilerInternalOptions.cs
  src/Compilers/Core/Portable/SymbolDisplay/SymbolDisplayFormat.cs
  src/Compilers/VisualBasic/Portable/SourceGeneration/VisualBasicGeneratorDriver.vb
  src/Compilers/VisualBasic/Portable/SourceGeneration/VisualBasicSyntaxHelper.vb
  src/Compilers/VisualBasic/Portable/SymbolDisplay/SymbolDisplayVisitor.Types.vb
  src/Compilers/VisualBasic/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.vb
  src/Compilers/VisualBasic/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_SimpleName.vb
  src/Dependencies/PooledObjects/ArrayBuilder.cs
  src/Tools/IdeCoreBenchmarks/IncrementalSourceGeneratorBenchmarks.cs
Labels: Area-Compilers

#61894 Fix build CodeAction telemetry project
  src/Tools/BuildActionTelemetryTable/BuildActionTelemetryTable.csproj
Labels: Area-Infrastructure

#61891 Remove unused function
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexEmbeddedLanguage.cs
Labels: Area-IDE

#61785 Use inline rename session options for all checkboxes directly
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyoutViewModel.cs
Labels: Area-IDE

#61889 Disallow required members in scripts and submissions
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Symbol/Symbols/RequiredMembersTests.cs
Labels: Area-Compilers, New Feature - Required Members

#60657 Re-enable Code Definition Window integration tests
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpCodeDefinitionWindow.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicCodeDefinitionWindow.cs
Labels: Area-IDE

#61898 Add paranoia checks and more logging for a failure case
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/SymbolKey/SymbolKey.MethodSymbolKey.cs
Labels: Area-IDE

#61874 Add FixAll support to ConvertIfToSwitch refactoring
  src/EditorFeatures/CSharpTest/CodeActions/ConvertIfToSwitch/ConvertIfToSwitchFixAllTests.cs
  src/EditorFeatures/VisualBasicTest/CodeActions/ConvertIfToSwitch/ConvertIfToSwitchFixAllTests.vb
  src/Features/CSharp/Portable/ConvertIfToSwitch/CSharpConvertIfToSwitchCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertIfToSwitch/AbstractConvertIfToSwitchCodeRefactoringProvider.cs
Labels: Area-IDE

#61919 Update version for 17.4 branch
  eng/Versions.props
Labels: Area-Infrastructure

#61886 Let VS fix Compilers.sln
  Compilers.sln
Labels: Area-Compilers

#61915 Add FixAll support of UseRecursivePattern refactoring
  src/EditorFeatures/CSharpTest/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsRefactoringFixAllTests.cs
  src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs
Labels: Area-IDE

#61932 Allow resizing DetailedErrorInfoDialog
  src/VisualStudio/Core/Def/ErrorReporting/DetailedErrorInfoDialog.xaml
Labels: Area-IDE, Needs UX Triage

#61933 Simplify FAR impl wrt searching for global namespaces
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferenceCache.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ConstructorInitializerSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamespaceSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/Shared/AbstractSyntaxIndex_Persistence.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex.ContextInfo.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Create.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Forwarders.cs
Labels: Area-IDE

#61931 Avoid NullReferenceException in Pick Members dialog
  src/VisualStudio/Core/Def/Utilities/AutomationDelegatingListView.cs
  src/VisualStudio/IntegrationTest/TestUtilities/Input/ComboBoxExtensions.cs
Labels: Area-IDE

#61938 Actually return filtered items for default implementation
  src/Features/Core/Portable/Completion/CompletionService.cs
Labels: Area-IDE

#61921 NRT enable symbolfinder/find-refs code.
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.CachedDocumentSearch.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/IEmbeddedLanguagesProvider.cs
  src/Workspaces/Core/Portable/FindSymbols/Declarations/DeclarationFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/Declarations/DeclarationFinder_AllDeclarations.cs
  src/Workspaces/Core/Portable/FindSymbols/Declarations/DeclarationFinder_SourceDeclarations.cs
  src/Workspaces/Core/Portable/FindSymbols/Extensions.cs
  src/Workspaces/Core/Portable/FindSymbols/FindLiterals/FindLiteralsSearchEngine.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/BaseTypeFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/DependentTypeFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/DependentTypesKind.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferenceCache.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesProgress.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/IRemoteDependentTypeFinderService.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/MetadataUnifyingEquivalenceComparer.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/NoOpStreamingFindReferencesProgress.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/StreamingFindReferencesProgress.cs
  src/Workspaces/Core/Portable/FindSymbols/IFindReferencesProgress.cs
  src/Workspaces/Core/Portable/FindSymbols/IRemoteSymbolFinderService.cs
  src/Workspaces/Core/Portable/FindSymbols/ReferenceLocation.cs
  src/Workspaces/Core/Portable/FindSymbols/ReferenceLocationExtensions.cs
  src/Workspaces/Core/Portable/FindSymbols/SearchKind.cs
  src/Workspaces/Core/Portable/FindSymbols/SearchQuery.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolCallerInfo.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder.FindReferencesServerCallback.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_Declarations_AllDeclarations.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_Declarations_CustomQueries.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_Declarations_SourceDeclarations.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_FindLiteralReferences.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_Helpers.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_Hierarchy.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/ISymbolTreeInfoCacheService.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo.FirstEntityHandleProvider.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo.Node.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Metadata.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Source.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex.IdentifierInfo.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex.LiteralInfo.cs
  src/Workspaces/Core/Portable/PatternMatching/PatternMatcher.cs
  src/Workspaces/Core/Portable/PatternMatching/PatternMatcherExtensions.cs
  src/Workspaces/Core/Portable/Remote/RemoteArguments.cs
Labels: Area-IDE

#61792 Convert connection lost exceptions to cancellations to avoid overreporting NFE
  src/Compilers/Core/Portable/InternalUtilities/FatalError.cs
  src/Workspaces/Remote/Core/RemoteCallback.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
  src/Workspaces/Remote/ServiceHub/Host/SolutionAssetSource.cs
Labels: Area-IDE

#61928 Avoid accessing Document from formatter services
  src/EditorFeatures/CSharp/Formatting/CSharpFormattingInteractionService.cs
  src/EditorFeatures/CSharpTest/Formatting/Indentation/CSharpFormatterTestsBase.cs
  src/EditorFeatures/CSharpTest/Formatting/Indentation/SmartTokenFormatterFormatRangeTests.cs
  src/EditorFeatures/Core/Formatting/FormatCommandHandler.Paste.cs
  src/EditorFeatures/Core/Formatting/FormatCommandHandler.cs
  src/EditorFeatures/Core/Shared/Extensions/ITextSnapshotExtensions.cs
  src/EditorFeatures/TestUtilities/Formatting/CoreFormatterTestsBase.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestFormattingRuleFactoryServiceFactory.cs
  src/EditorFeatures/VisualBasic/LineCommit/CommitCommandHandler.vb
  src/EditorFeatures/VisualBasic/LineCommit/CommitFormatter.vb
  src/EditorFeatures/VisualBasicTest/Formatting/Indentation/SmartTokenFormatter_FormatTokenTests.vb
  src/EditorFeatures/VisualBasicTest/Formatting/VisualBasicFormatterTestBase.vb
  src/Features/CSharp/Portable/BraceCompletion/AbstractCurlyBraceOrBracketCompletionService.cs
  src/Features/CSharp/Portable/BraceCompletion/BracketBraceCompletionService.cs
  src/Features/CSharp/Portable/BraceCompletion/CurlyBraceCompletionService.cs
  src/Features/Core/Portable/Formatting/FormattingRuleUtilities.cs
  src/Features/Core/Portable/Shared/Extensions/DocumentExtensions.cs
  src/Features/LanguageServer/Protocol/Handler/Formatting/FormatDocumentOnTypeHandler.cs
  src/Tools/ExternalAccess/Razor/RazorCSharpFormattingInteractionService.cs
  src/VisualStudio/Core/Def/LanguageService/AbstractLanguageService`2.IVsLanguageTextOps.cs
  src/VisualStudio/Core/Def/Workspace/VisualStudioFormattingRuleFactoryServiceFactory.cs
  src/Workspaces/CSharp/Portable/Formatting/CSharpSyntaxFormattingService.cs
  src/Workspaces/Core/Portable/Formatting/Formatter.cs
  src/Workspaces/Core/Portable/Formatting/ISyntaxFormattingService.cs
  src/Workspaces/Core/Portable/Formatting/Rules/DefaultFormattingRuleFactoryServiceFactory.cs
  src/Workspaces/Core/Portable/Formatting/Rules/IHostDependentFormattingRuleFactoryService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Indentation/CSharpSmartTokenFormatter.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Indentation/AbstractIndentation.Indenter.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Indentation/AbstractIndentation.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Indentation/ISmartTokenFormatter.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Indentation/VisualBasicSmartTokenFormatter.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Indentation/CSharpIndentationService.Indenter.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Indentation/AbstractIndentationService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Utilities/ParsedDocument.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Utilities/SemanticDocument.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Utilities/SyntacticDocument.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Indentation/VisualBasicIndentationService.Indenter.vb
  src/Workspaces/VisualBasic/Portable/Formatting/VisualBasicSyntaxFormattingService.vb
Labels: Area-IDE

#61948 Don't use exceptions for flow control
  src/EditorFeatures/CSharp/DecompiledSource/CSharpDecompiledSourceService.cs
  src/Features/Core/Portable/DecompiledSource/IDecompiledSourceService.cs
  src/Features/Core/Portable/MetadataAsSource/DecompilationMetadataAsSourceFileProvider.cs
Labels: Area-IDE

#61952 Use 'Clear' to empty a CWT when on .net core
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.CompilationManager.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.cs
Labels: Area-IDE

#61967 Improve error message for lookup on a type parameter.
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Query.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/IndexerTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
Labels: Area-Compilers, New Feature - StaticAbstractMembersInInterfaces

#61839 SerializableOptionSet and IOptionService cleanup
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/OverrideCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/OverrideCompletionProviderTests_ExpressionBody.cs
  src/EditorFeatures/CSharpTest/ConvertNamespace/ConvertNamespaceCommandHandlerTests.cs
  src/EditorFeatures/CSharpTest/Workspaces/WorkspaceTests_EditorFeatures.cs
  src/EditorFeatures/Core/Options/LegacyGlobalOptionsWorkspaceService.cs
  src/EditorFeatures/DiagnosticsTestUtilities/SplitComments/AbstractSplitCommentCommandHandlerTests.cs
  src/EditorFeatures/Test/Workspaces/ProjectCacheHostServiceFactoryTests.cs
  src/EditorFeatures/TestUtilities/AutomaticCompletion/AbstractAutomaticLineEnderTests.cs
  src/EditorFeatures/TestUtilities/Completion/AbstractArgumentProviderTests`1.cs
  src/EditorFeatures/TestUtilities/Completion/AbstractCompletionProviderTests.cs
  src/EditorFeatures/TestUtilities/Extensions/SolutionExtensions.cs
  src/EditorFeatures/TestUtilities/ExtractInterface/ExtractInterfaceTestState.cs
  src/EditorFeatures/TestUtilities/TestOptionsServiceFactory.cs
  src/EditorFeatures/TestUtilities/TestOptionsServiceWithSharedGlobalOptionsServiceFactory.cs
  src/EditorFeatures/VisualBasicTest/EndConstructGeneration/EndConstructCommandHandlerTests.vb
  src/Features/Core/Portable/Diagnostics/AnalyzerConfigOptionSet.cs
  src/Tools/ExternalAccess/Razor/RazorCSharpFormattingInteractionService.cs
  src/Tools/ExternalAccess/Razor/RazorGlobalOptions.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/Mocks/OptionServiceMock.cs
  src/VisualStudio/Core/Impl/Options/AbstractOptionPage.cs
  src/VisualStudio/Core/Impl/Options/AbstractOptionPreviewViewModel.cs
  src/VisualStudio/Core/Test.Next/Remote/SnapshotSerializationTests.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/VisualStudioWorkspace_InProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/VisualStudioWorkspace_OutOfProc.cs
  src/Workspaces/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.Workspaces.csproj
  src/Workspaces/Core/Portable/CodeStyle/CodeStyleOption.cs
  src/Workspaces/Core/Portable/Formatting/Formatter.cs
  src/Workspaces/Core/Portable/Options/DocumentOptionSet.cs
  src/Workspaces/Core/Portable/Options/GlobalOptionService.cs
  src/Workspaces/Core/Portable/Options/IGlobalOptionService.cs
  src/Workspaces/Core/Portable/Options/ILegacyGlobalOptionsWorkspaceService.cs
  src/Workspaces/Core/Portable/Options/ILegacyWorkspaceOptionService.cs
  src/Workspaces/Core/Portable/Options/IOptionService.cs
  src/Workspaces/Core/Portable/Options/OptionServiceFactory.cs
  src/Workspaces/Core/Portable/Options/OptionSet+AnalyzerConfigOptionsImpl.cs
  src/Workspaces/Core/Portable/Options/OptionSet.cs
  src/Workspaces/Core/Portable/Options/SerializableOptionSet.WorkspaceOptionSet.cs
  src/Workspaces/Core/Portable/Options/SerializableOptionSet.cs
  src/Workspaces/Core/Portable/Options/SolutionOptionSet.cs
  src/Workspaces/Core/Portable/Simplification/Simplifier.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionInfo.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
  src/Workspaces/CoreTest/Formatter/FormatterTests.cs
  src/Workspaces/CoreTest/Host/WorkspaceServices/TestOptionService.cs
  src/Workspaces/CoreTest/Host/WorkspaceServices/TestOptionsServiceFactory.cs
  src/Workspaces/CoreTest/Options/OptionsTestHelpers.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
  src/Workspaces/CoreTest/TestCompositionTests.cs
  src/Workspaces/CoreTest/WorkspaceServiceTests/GlobalOptionServiceTests.cs
  src/Workspaces/CoreTest/WorkspaceTests/WorkspaceReferenceTests.cs
  src/Workspaces/CoreTest/WorkspaceTests/WorkspaceTests.cs
  src/Workspaces/CoreTestUtilities/OptionsCollection.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/CodeStyleOption2`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/Serialization/NamingStylePreferences.cs
Labels: Area-IDE

#61890 Bind switch expression with checked-aware binder
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/LocalBinderFactory.cs
  src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxNodeExtensions.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenCheckedTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/CheckedUserDefinedOperatorsTests.cs
Labels: Area-Compilers

#61951 Support embedded languages on named attribute arguments
  src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs
  src/EditorFeatures/VisualBasicTest/Classification/SemanticClassifierTests.vb
  src/Workspaces/Core/Portable/EmbeddedLanguages/EmbeddedLanguageDetector.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SemanticFacts/CSharpSemanticFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SemanticFacts/ISemanticFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SemanticFacts/VisualBasicSemanticFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/SemanticsFactsService/AbstractSemanticFactsService.cs
Labels: Area-IDE

#61972 Fix logic issue in find-refs that could fail to find related symbols in inheritance
  src/EditorFeatures/Test/SymbolFinder/DependentTypeFinderTests.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/DependentTypeFinder.cs
Labels: Area-IDE

#61958 Fix race condition in FixAll tests based off TrackNodes functionality
  src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertIfToSwitch/AbstractConvertIfToSwitchCodeRefactoringProvider.cs
Labels: Area-IDE

#61809 Do not report populate switch diagnostic when switch type is unknown
  src/Analyzers/CSharp/Tests/PopulateSwitch/PopulateSwitchStatementTests.cs
  src/Analyzers/Core/Analyzers/PopulateSwitch/AbstractPopulateSwitchDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/PopulateSwitch/AbstractPopulateSwitchExpressionDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/PopulateSwitch/AbstractPopulateSwitchStatementDiagnosticAnalyzer.cs
Labels: Area-IDE, Community

#61970 Fix reported accessibility issues with StackTrace Explorer
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/StackTraceExplorer/StackTraceExplorer.xaml
  src/VisualStudio/Core/Def/StackTraceExplorer/StackTraceExplorerRoot.xaml
  src/VisualStudio/Core/Def/StackTraceExplorer/StackTraceExplorerViewModel.cs
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
Labels: Area-IDE

#61984 Support embedded lang features when overload resolution fails
  src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs
  src/EditorFeatures/VisualBasicTest/Classification/SemanticClassifierTests.vb
  src/Features/Core/Portable/EmbeddedLanguages/Json/LanguageServices/JsonLanguageDetector.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexLanguageDetector.cs
  src/Features/VisualBasic/Portable/InlineHints/VisualBasicInlineParameterNameHintsService.vb
  src/Workspaces/Core/Portable/EmbeddedLanguages/EmbeddedLanguageDetector.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ArgumentSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/AttributeArgumentSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SemanticFacts/CSharpSemanticFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SemanticFacts/ISemanticFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SemanticFacts/ISemanticFactsExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Extensions/ArgumentSyntaxExtensions.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SemanticFacts/VisualBasicSemanticFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/SemanticsFactsService/AbstractSemanticFactsService.cs
Labels: Area-IDE

#61953 Add all references when finding symbols in implementation assemblies
  src/EditorFeatures/CSharpTest/PdbSourceDocument/PdbSourceDocumentTests.cs
  src/Features/Core/Portable/PdbSourceDocument/PdbSourceDocumentMetadataAsSourceFileProvider.cs
Labels: Area-IDE

#61968 Read editorconfig options from the editor in GetInferredFormattingOptions
  src/EditorFeatures/CSharp/Formatting/CSharpFormattingInteractionService.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptFormattingInteractionService.cs
  src/EditorFeatures/Core/Formatting/FormatCommandHandler.FormatDocument.cs
  src/EditorFeatures/Core/Formatting/FormatCommandHandler.FormatSelection.cs
  src/EditorFeatures/Core/Formatting/FormatCommandHandler.Paste.cs
  src/EditorFeatures/Core/Formatting/FormatCommandHandler.cs
  src/EditorFeatures/Core/Formatting/IFormattingInteractionService.cs
  src/EditorFeatures/Core/Formatting/IndentationManagerExtensions.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/CommitManager.cs
  src/EditorFeatures/Core/Options/EditorAnalyzerConfigOptions.cs
  src/EditorFeatures/VisualBasic/LineCommit/CommitFormatter.vb
  src/Tools/ExternalAccess/FSharp/Internal/Editor/FSharpEditorFormattingService.cs
Labels: Area-IDE

#61969 Do not add cast to object when converting string.Format to interpolated string
  src/Analyzers/CSharp/Tests/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs
  src/EditorFeatures/CSharpTest/ConvertToInterpolatedString/ConvertPlaceholderToInterpolatedStringTests.cs
  src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Simplification/Simplifiers/CastSimplifier.cs
Labels: Area-IDE, Community

#61988 Point workitems to the PR & clarification comment
  src/Analyzers/CSharp/Tests/PopulateSwitch/PopulateSwitchStatementTests.cs
Labels: Area-IDE, Community

#61995 Add a fast exit check for type-argument-list brace completion to help avoid semantic work when unnecessary
  src/Features/CSharp/Portable/BraceCompletion/LessAndGreaterThanBraceCompletionService.cs
Labels: Area-IDE

#62001 Fix deadlock during the startup of diagnostics
  src/VisualStudio/Core/Def/TableDataSource/VisualStudioDiagnosticListTable.cs
Labels: Area-IDE

#61965 Use native azdo command for checkout
  azure-pipelines.yml
  eng/pipelines/build-unix-job.yml
  eng/pipelines/build-windows-job.yml
  eng/pipelines/checkout-task.yml
  eng/pipelines/checkout-unix-task.yml
  eng/pipelines/checkout-windows-task.yml
  eng/pipelines/test-integration-job.yml
Labels: Area-Infrastructure

#61941 Simplify implementation of the FindRefsCache helper type
  src/Features/Core/Portable/ChangeSignature/DelegateInvokeMethodReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/Extensions.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferenceCache.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractMemberScopedReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ConstructorInitializerSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ConstructorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/DestructorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/EventSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ExplicitConversionSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ExplicitInterfaceMethodReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/FieldSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/IReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/MethodTypeParameterSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamedTypeSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamespaceSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/OperatorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/OrdinaryMethodReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ParameterSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/PropertyAccessorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/PropertySymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/TypeParameterSymbolReferenceFinder.cs
Labels: Area-IDE

#62011 Merge common find-refs data into its own type.
  src/Features/Core/Portable/ChangeSignature/DelegateInvokeMethodReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/Extensions.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesDocumentState.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractMemberScopedReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractMethodOrPropertyOrEventSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder_GlobalSuppressions.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ConstructorInitializerSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ConstructorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/DestructorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/EventSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ExplicitConversionSymbolReferenceFinder.UnderlyingNamedTypeVisitor.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ExplicitConversionSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ExplicitInterfaceMethodReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/FieldSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/IReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/LabelSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/LocalSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/MethodTypeParameterSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamedTypeSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamespaceSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/OperatorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/OrdinaryMethodReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ParameterSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/PropertyAccessorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/PropertySymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/RangeVariableSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/TypeParameterSymbolReferenceFinder.cs
Labels: Area-IDE

#62017 Move to more static lambdas in find-references to prevent captures.
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractMemberScopedReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ConstructorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamedTypeSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ParameterSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/PropertySymbolReferenceFinder.cs
Labels: Area-IDE

#61978 Fix stack overflow in CSharpStringIndentationService
  src/EditorFeatures/CSharpTest/StringIndentation/StringIndentationTests.cs
  src/Features/CSharp/Portable/StringIndentation/CSharpStringIndentationService.cs
Labels: Area-IDE

#61994 Simplify embedded languages type hierarchy
  src/Features/CSharp/Portable/EmbeddedLanguages/CSharpEmbeddedLanguageFeaturesProvider.cs
  src/Features/CSharp/Portable/EmbeddedLanguages/CSharpEmbeddedLanguagesProvider.cs
  src/Features/CSharp/Portable/EmbeddedLanguages/Classification/CSharpEmbeddedLanguageClassificationServiceFactory.cs
  src/Features/CSharp/Portable/EmbeddedLanguages/Classification/CSharpFallbackEmbeddedLanguageClassifier.cs
  src/Features/Core/Portable/Completion/Providers/AbstractAggregateEmbeddedLanguageCompletionProvider.cs
  src/Features/Core/Portable/EmbeddedLanguages/AbstractEmbeddedLanguageFeatureService.cs
  src/Features/Core/Portable/EmbeddedLanguages/AbstractEmbeddedLanguagesProvider.cs
  src/Features/Core/Portable/EmbeddedLanguages/Classification/AbstractEmbeddedLanguageClassificationService.cs
  src/Features/Core/Portable/EmbeddedLanguages/Classification/AbstractFallbackEmbeddedLanguageClassifier.cs
  src/Features/Core/Portable/EmbeddedLanguages/Classification/EmbeddedLanguageClassifierContext.cs
  src/Features/Core/Portable/EmbeddedLanguages/Classification/ExportEmbeddedLanguageClassifier.cs
  src/Features/Core/Portable/EmbeddedLanguages/Classification/IEmbeddedLanguageClassifier.cs
  src/Features/Core/Portable/EmbeddedLanguages/DateAndTime/DateAndTimeEmbeddedCompletionProvider.cs
  src/Features/Core/Portable/EmbeddedLanguages/DateAndTime/DateAndTimeEmbeddedLanguageFeatures.cs
  src/Features/Core/Portable/EmbeddedLanguages/DateAndTime/LanguageServices/DateAndTimeEmbeddedLanguage.cs
  src/Features/Core/Portable/EmbeddedLanguages/EmbeddedLanguageCommentDetector.cs
  src/Features/Core/Portable/EmbeddedLanguages/EmbeddedLanguageCommentOptions.cs
  src/Features/Core/Portable/EmbeddedLanguages/EmbeddedLanguageDetector.cs
  src/Features/Core/Portable/EmbeddedLanguages/EmbeddedLanguageInfo.cs
  src/Features/Core/Portable/EmbeddedLanguages/EmbeddedLanguageMetadata.cs
  src/Features/Core/Portable/EmbeddedLanguages/ExportEmbeddedLanguageFeatureServiceAttribute.cs
  src/Features/Core/Portable/EmbeddedLanguages/IEmbeddedLanguage.cs
  src/Features/Core/Portable/EmbeddedLanguages/IEmbeddedLanguageFeatureService.cs
  src/Features/Core/Portable/EmbeddedLanguages/IEmbeddedLanguagesProvider.cs
  src/Features/Core/Portable/EmbeddedLanguages/Json/LanguageServices/JsonEmbeddedLanguage.cs
  src/Features/Core/Portable/EmbeddedLanguages/PredefinedEmbeddedLanguageClassifierNames.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexEmbeddedLanguage.cs
  src/Features/VisualBasic/Portable/EmbeddedLanguages/Classification/VisualBasicEmbeddedLanguageClassificationServiceFactory.vb
  src/Features/VisualBasic/Portable/EmbeddedLanguages/Classification/VisualBasicFallbackEmbeddedLanguageClassifier.vb
  src/Features/VisualBasic/Portable/EmbeddedLanguages/VisualBasicEmbeddedLanguageFeaturesProvider.vb
  src/Features/VisualBasic/Portable/EmbeddedLanguages/VisualBasicEmbeddedLanguagesProvider.vb
  src/Workspaces/Core/Portable/Classification/IEmbeddedLanguageClassificationService.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/AbstractEmbeddedLanguagesProvider.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/IEmbeddedLanguage.cs
Labels: Area-IDE

#62027 Remove more delegates from FindRefs.
  src/Features/Core/Portable/ChangeSignature/DelegateInvokeMethodReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractMemberScopedReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ConstructorInitializerSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ConstructorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/EventSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ExplicitConversionSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ExplicitInterfaceMethodReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/FieldSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/IReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/LabelSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/LocalSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/MethodTypeParameterSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamedTypeSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamespaceSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/OperatorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/OrdinaryMethodReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ParameterSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/PropertyAccessorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/PropertySymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/RangeVariableSymbolReferenceFinder.cs
Labels: Area-IDE

#62040 Create VS insertions after artifacts have been published.
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#62019 Add FixAll support for ConvertNamespace refactoring
  src/EditorFeatures/CSharpTest/ConvertNamespace/ConvertNamespaceRefactoringFixAllTests.cs
  src/Features/CSharp/Portable/ConvertNamespace/ConvertNamespaceCodeRefactoringProvider.cs
Labels: Area-IDE

#61899 Separate IEditorConfigOptionMappingService from IGlobalOptionService
  src/EditorFeatures/Core.Wpf/InlineRename/InlineRenameExperimentationOptions.cs
  src/EditorFeatures/Core/Logging/FunctionIdOptions.cs
  src/EditorFeatures/Core/Options/NavigationBarViewOptions.cs
  src/EditorFeatures/Test/Workspaces/ProjectCacheHostServiceFactoryTests.cs
  src/Features/Core/Portable/Diagnostics/AnalyzerConfigOptionSet+AnalyzerConfigOptionsImpl.cs
  src/Features/Core/Portable/Diagnostics/AnalyzerConfigOptionSet.cs
  src/VisualStudio/Core/Impl/Options/AbstractOptionPage.cs
  src/VisualStudio/Core/Impl/Options/AbstractOptionPreviewViewModel.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/StateResetInProcess.cs
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/OptionPages/ForceLowMemoryModePage.cs
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/OptionPages/InternalComponentsOnOffPage.cs
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/OptionPages/InternalOptionsControl.cs
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/OptionPages/PerformanceFunctionIdPage.cs
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/OptionPages/PerformanceLoggersPage.cs
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/PackageRegistration.pkgdef
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/VisualStudioDiagnosticsWindowPackage.cs
  src/Workspaces/Core/Portable/Formatting/Formatter.cs
  src/Workspaces/Core/Portable/Options/DocumentOptionSet.cs
  src/Workspaces/Core/Portable/Options/EditorConfigOptionMappingService.cs
  src/Workspaces/Core/Portable/Options/GlobalOptionService.cs
  src/Workspaces/Core/Portable/Options/IEditorConfigOptionMappingService.cs
  src/Workspaces/Core/Portable/Options/IGlobalOptionService.cs
  src/Workspaces/Core/Portable/Options/OptionSet+AnalyzerConfigOptionsImpl.cs
  src/Workspaces/Core/Portable/Options/OptionSet.cs
  src/Workspaces/Core/Portable/Simplification/Simplifier.cs
  src/Workspaces/CoreTest/WorkspaceServiceTests/GlobalOptionServiceTests.cs
  src/Workspaces/CoreTestUtilities/OptionsCollection.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Simplification/SimplifierOptionsProviders.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensions.projitems
Labels: Area-IDE

#62026 Add nuget reference to fix ide benchmarks
  eng/Versions.props
  src/Tools/IdeCoreBenchmarks/IdeCoreBenchmarks.csproj
  src/Tools/IdeCoreBenchmarks/IncrementalSourceGeneratorBenchmarks.cs
Labels: Area-IDE

#62058 Add NFW report to FindRefs to help track down an issue.
  src/Features/Core/Portable/FindUsages/IRemoteFindUsagesService.cs
  src/VisualStudio/Core/Def/FindReferences/Contexts/AbstractTableDataSourceFindUsagesContext.cs
Labels: Area-IDE

#61872 Global options tests
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/AbstractUseCollectionInitializerDiagnosticAnalyzer.cs
  src/EditorFeatures/Core/InlineHints/InlineHintsOptionsStorage.cs
  src/EditorFeatures/Core/QuickInfo/QuickInfoOptionsStorage.cs
  src/EditorFeatures/Core/SymbolDisplay/SymbolDescriptionOptionsStorage.cs
  src/EditorFeatures/Test/Options/GlobalOptionsTests.cs
  src/EditorFeatures/Test2/InlineHints/AbstractInlineHintsTests.vb
  src/EditorFeatures/TestUtilities/Structure/AbstractSyntaxStructureProviderTests.cs
  src/EditorFeatures/VisualBasicTest/Structure/CompilationUnitStructureTests.vb
  src/EditorFeatures/VisualBasicTest/Structure/RegionDirectiveStructureTests.vb
  src/Features/Core/Portable/InlineHints/InlineHintsOptions.cs
  src/Features/Core/Portable/InlineHints/InlineParameterHintsOptions.cs
  src/Features/Core/Portable/InlineHints/InlineTypeHintsOptions.cs
  src/Features/Core/Portable/LanguageServices/SymbolDisplayService/SymbolDescriptionOptions.cs
  src/Features/Core/Portable/MetadataAsSource/MetadataAsSourceOptions.cs
  src/Features/Core/Portable/QuickInfo/QuickInfoOptions.cs
  src/Features/Core/Portable/SignatureHelp/SignatureHelpOptions.cs
  src/Features/Core/Portable/Structure/BlockStructureOptions.cs
  src/Features/LanguageServer/Protocol/Features/Options/BlockStructureOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/ClassificationOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/DocumentationCommentOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/IdeAnalyzerOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/MetadataAsSourceOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/SignatureHelpOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Handler/OnAutoInsert/OnAutoInsertHandler.cs
  src/Tools/ExternalAccess/OmniSharp/InlineHints/OmniSharpInlineHintsOptions.cs
  src/Workspaces/Core/Portable/Classification/ClassificationOptions.cs
  src/Workspaces/Core/Portable/Options/IGlobalOptionService.cs
  src/Workspaces/Core/Portable/OrganizeImports/OrganizeImportsOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/CodeStyleOptions2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Diagnostics/IdeAnalyzerOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/AutoFormattingOptions.cs
Labels: Area-IDE

#62044 Implement concatenation operator for "u8" literals.
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/BinaryOperatorOverloadResolution.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/OperatorKind.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Compilation/BuiltInOperators.cs
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IUTF8StringOperation.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/Utf8StringsLiteralsTests.cs
Labels: Area-Compilers, New Feature - Utf8StringLiterals

#61911 Filter symbol first before creating InheritanceMargin target
  src/EditorFeatures/Test/InheritanceMargin/InheritanceMarginTests.cs
  src/Features/Core/Portable/InheritanceMargin/AbstractInheritanceMarginService_Helpers.cs
  src/Features/Core/Portable/InheritanceMargin/InheritanceMarginItem.cs
Labels: Area-IDE

#61195 Ref fields escape analysis
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Members.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeManager.Templates.cs
  src/Compilers/CSharp/Portable/Symbols/AssemblySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/FunctionPointers/FunctionPointerParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ParameterHelpers.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceLocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceParameterSymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenRefReadonlyReturnTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenRefReturnTests.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_LifetimeAnnotation.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RawInterpolationTests_Handler.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefLocalsAndReturnsTests.cs
  src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/Portable/SpecialMember.cs
  src/Compilers/Core/Portable/SpecialMembers.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolDisplay/SymbolDisplayTests.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
Labels: Area-Compilers, New Language Feature - Ref Fields

#62136 Separate out connection failures
  src/Compilers/Core/CommandLine/BuildProtocol.cs
  src/Compilers/Core/MSBuildTask/ManagedCompiler.cs
  src/Compilers/Core/MSBuildTask/ValidateBootstrap.cs
  src/Compilers/Server/VBCSCompilerTests/BuildServerConnectionTests.cs
  src/Compilers/Shared/BuildClient.cs
  src/Compilers/Shared/BuildServerConnection.cs
Labels: Area-Compilers, Area-Infrastructure

#62076 Adjust spec quotes in ConversionBase.AddTypesParticipatingInUserDefinedConversion to incorporate abstract statics in interfaces
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/UserDefinedConversions.cs
Labels: Area-Compilers, New Feature - StaticAbstractMembersInInterfaces

#61811 IOperation: expose information about the type parameter that is going to be used as the ".constrained" type for invoking abstract static methods
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversion.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
  src/Compilers/Core/Portable/Generated/Operations.Generated.cs
  src/Compilers/Core/Portable/Operations/CommonConversion.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/Operations/OperationFactory.cs
  src/Compilers/Core/Portable/Operations/OperationInterfaces.xml
  src/Compilers/Core/Portable/Operations/OperationNodes.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Test/Core/Compilation/OperationTreeVerifier.cs
  src/Compilers/Test/Core/Compilation/TestOperationVisitor.cs
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb
  src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/IOperationClassWriter.Verifier.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/IOperationClassWriter.cs
  src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/Model.cs
Labels: Concept-API, Area-Compilers, New Feature - StaticAbstractMembersInInterfaces

#62118 Add members to PythiaCompletionProviderBase to move IntelliCode off internal APIs
  src/Features/Core/Portable/ExternalAccess/Pythia/Api/PythiaCompletionProviderBase.cs
Labels: Area-IDE

#62134 Move to a shared stopwatch in the incremental generator
  src/Compilers/Core/Portable/SourceGeneration/SyntaxStore.cs
  src/Tools/IdeCoreBenchmarks/IncrementalSourceGeneratorBenchmarks.cs
Labels: Area-Compilers
