Repository dotnet/roslyn, pull requests merged in 2022-03, with the labels that each got.

#59824 Update config for snap
  eng/Versions.props
  eng/config/PublishData.json
Labels: Area-Infrastructure

#59779 Merge features/rename_ui_rework into main
  src/EditorFeatures/Core.Cocoa/Microsoft.CodeAnalysis.EditorFeatures.Cocoa.csproj
  src/EditorFeatures/Core.Wpf/EditorFeaturesWpfResources.resx
  src/EditorFeatures/Core.Wpf/InlineRename/InlineRenameExperimentationOptions.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/InlineRenameAdornment.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/InlineRenameAdornment.xaml.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/InlineRenameAdornmentViewModel.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Dashboard/Dashboard.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Dashboard/Dashboard.xaml.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Dashboard/DashboardAutomationPeer.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Dashboard/DashboardSeverity.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Dashboard/DashboardViewModel.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Dashboard/Images/ErrorIcon.png
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Dashboard/Images/InfoIcon.png
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Dashboard/RenameShortcutKeys.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/IInlineRenameColorUpdater.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/InlineRenameAdornmentManager.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/InlineRenameAdornmentProvider.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/InlineRenameColors.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/InlineRenameColors.xaml
  src/EditorFeatures/Core.Wpf/Microsoft.CodeAnalysis.EditorFeatures.Wpf.csproj
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.cs.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.de.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.es.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.fr.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.it.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ja.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ko.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.pl.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.pt-BR.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ru.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.tr.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.zh-Hans.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.zh-Hant.xlf
  src/VisualStudio/Core/Def/Implementation/InlineRename/DashboardColorUpdater.cs
  src/VisualStudio/Core/Def/PackageRegistration.pkgdef
Labels: Area-IDE

#59622 Produce specific error for misplaced 'record' keyword
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/RecordParsing.cs
Labels: Area-Compilers, New Language Feature - Records

#59806 Disallow converted string as default argument value
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md
  src/Compilers/CSharp/Portable/Symbols/Source/ParameterHelpers.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NamedAndOptionalTests.cs
Labels: Area-Compilers

#59821 Remove inaccurate section of doc comment
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs
Labels: Area-Compilers

#59798 Change navigation helpers to operate in two steps.
  src/EditorFeatures/Core.Wpf/Interactive/InteractiveDocumentNavigationService.cs
  src/EditorFeatures/TestUtilities2/Utilities/GoToHelpers/MockDocumentNavigationService.vb
  src/EditorFeatures/TestUtilities2/Utilities/MockDocumentNavigationServiceProvider.vb
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/Api/VSTypeScriptDocumentNavigationServiceWrapper.cs
  src/Features/Core/Portable/Navigation/DefaultDocumentNavigationService.cs
  src/Features/Core/Portable/Navigation/IDocumentNavigationService.cs
  src/Features/Core/Portable/Navigation/INavigableDocumentLocation.cs
  src/Tools/ExternalAccess/FSharp/Navigation/IFSharpDocumentNavigationService.cs
  src/VisualStudio/Core/Def/Implementation/Extensions/VsTextSpanExtensions.cs
  src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractLanguageService`2.VsLanguageDebugInfo.cs
  src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractLanguageService`2.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs
  src/VisualStudio/LiveShare/Test/MockDocumentNavigationServiceFactory.cs
Labels: Area-IDE

#59813 Don't get nullable slot if property sub-pattern has error
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesVsPatterns.cs
Labels: Area-Compilers

#59783 Port more tests
  src/Tools/Source/RunTests/ProcessTestExecutor.cs
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpGoToImplementation.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicGoToImplementation.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpAddMissingReference.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpF1Help.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpFindReferences.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpGoToBase.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpGoToImplementation.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpOrganizing.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpUpdateProjectToAllowUnsafe.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpUpgradeProject.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/FindReferencesWindowInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/ShellInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerVerifierInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/Microsoft.VisualStudio.LanguageServices.New.IntegrationTests.csproj
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicF1Help.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicGoToImplementation.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/WellKnownCommands.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/Editor_InProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/SolutionExplorer_InProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/Editor_OutOfProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/SolutionExplorer_OutOfProc.Verifier.cs
  src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/SolutionExplorer_OutOfProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/WellKnownCommandNames.cs
Labels: Area-Infrastructure

#59612 Produce a specific error for 'enum' as constraint
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs
Labels: Area-Compilers

#59825 Remove unnecessary components from devcontainer
  .devcontainer/Dockerfile
Labels: Area-Infrastructure

#59588 Backport "Remove handling of certain BCL binaries from our build" to 17.0
  eng/Signing.props
  eng/config/OptProf.json
  src/NuGet/Microsoft.Net.Compilers.Toolset/DesktopCompilerArtifacts.targets
  src/Setup/DevDivInsertionFiles/DevDivInsertionFiles.csproj
Labels: Area-Infrastructure

#59782 Add OmniSharpCompletionService.GetDescriptionAsync
  src/Tools/ExternalAccess/OmniSharp/Completion/OmniSharpCompletionService.cs
Labels: Area-IDE

#59822 Unify our test artifacts directory to upload more stuff on failure
  eng/pipelines/test-integration-job.yml
  src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs
Labels: Area-Infrastructure

#59652 Add feature to fixup code when user transposes 'record' in a declaration
  src/Analyzers/CSharp/CodeFixes/CSharpCodeFixes.projitems
  src/Analyzers/CSharp/CodeFixes/CSharpCodeFixesResources.resx
  src/Analyzers/CSharp/CodeFixes/TransposeRecordKeyword/CSharpTransposeRecordKeywordCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.cs.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.de.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.es.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.fr.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.it.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.ja.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.ko.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.pl.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.pt-BR.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.ru.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.tr.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.zh-Hans.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.zh-Hant.xlf
  src/Analyzers/Core/CodeFixes/PredefinedCodeFixProviderNames.cs
  src/EditorFeatures/CSharpTest/TransposeRecordKeyword/TransposeRecordKeywordTests.cs
Labels: Area-Compilers

#59793 Removed navigation target and navigation hint from namespaces
  src/EditorFeatures/Test2/IntelliSense/IntellisenseQuickInfoBuilderTests.vb
  src/Features/Core/Portable/Common/TaggedText.cs
Labels: Area-IDE, Community

#59857 Update PublishData for 17.3
  eng/config/PublishData.json
Labels: Area-Infrastructure

#59849 Use ExceptionUtilities.UnexpectedValue instead of Unreachable
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
Labels: Area-Compilers

#59856 Address layering of navigation action in code actions
  src/EditorFeatures/Core/Implementation/CodeActions/CodeActionEditHandlerService.cs
  src/Features/Core/Portable/Common/DocumentNavigationOperation.cs
Labels: Area-IDE

#59842 Account for possible cache invalidation on a different thread in assert.
  src/Compilers/Core/Portable/Compilation/Compilation.cs
Labels: Area-Compilers

#59848 Fix issues pressing 'enter' in a raw string literal
  src/EditorFeatures/CSharp/RawStringLiteral/RawStringLiteralCommandHandler_Return.cs
  src/EditorFeatures/CSharpTest/RawStringLiteral/RawStringLiteralCommandHandlerTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTreeExtensions.cs
Labels: Area-IDE

#59844 Notify docs team for new breaking change documentation
  .github/CODEOWNERS
Labels: Area-Compilers, Documentation

#59882 Revert accidental prerelease version bump.
  eng/Versions.props
Labels: Area-Infrastructure

#59847 Disallow string null constant as pattern for Span<char>
  src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs
Labels: Area-Compilers

#59801 Update go-to-def handler to support entirely async go-to-def operation.
  src/EditorFeatures/CSharp/GoToDefinition/CSharpAsyncGoToDefinitionService.cs
  src/EditorFeatures/Core.Wpf/Interactive/InteractiveDocumentNavigationService.cs
  src/EditorFeatures/Core.Wpf/NavigableSymbols/NavigableSymbolService.NavigableSymbol.cs
  src/EditorFeatures/Core/CommandHandlers/AbstractGoToCommandHandler`2.cs
  src/EditorFeatures/Core/GoToDefinition/AbstractGoToDefinitionService.cs
  src/EditorFeatures/Core/GoToDefinition/GoToDefinitionCommandHandler.cs
  src/EditorFeatures/Core/GoToDefinition/GoToDefinitionHelpers.cs
  src/EditorFeatures/Core/GoToDefinition/IAsyncGoToDefinitionService.cs
  src/EditorFeatures/Core/Host/IStreamingFindReferencesPresenter.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/Helpers.cs
  src/EditorFeatures/Test2/GoToDefinition/CSharpGoToDefinitionTests.vb
  src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionCommandHandlerTests.vb
  src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionTestsBase.vb
  src/EditorFeatures/Test2/GoToDefinition/VisualBasicGoToDefinitionTests.vb
  src/EditorFeatures/VisualBasic/GoToDefinition/VisualBasicAsyncGoToDefinitionService.vb
  src/Features/Core/Portable/Navigation/INavigableLocation.cs
  src/VisualStudio/Core/Def/Implementation/InheritanceMargin/MarginGlyph/InheritanceMarginContextMenu.xaml.cs
  src/VisualStudio/Core/Impl/RoslynVisualStudioWorkspace.cs
  src/VisualStudio/Core/Test/GoToDefinition/GoToDefinitionApiTests.vb
Labels: Area-IDE

#59854 Port additional tests to the new integration test harness
  src/EditorFeatures/Core.Wpf/NavigateTo/NavigateToItemProvider.cs
  src/Features/Core/Portable/NavigateTo/NavigateToSearcher.cs
  src/Tools/Source/RunTests/ProcessTestExecutor.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpGoToDefinition.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpSourceGenerators.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/Microsoft.VisualStudio.LanguageServices.IntegrationTests.csproj
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicFindReferences.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicGoToDefinition.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpGoToDefinition.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpSourceGenerators.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/FindReferencesWindowInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/InputInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/LightBulbHelper.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/StateResetInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/WorkspaceInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/Microsoft.VisualStudio.LanguageServices.New.IntegrationTests.csproj
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicFindReferences.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicGoToDefinition.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/Editor_InProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/FindReferencesWindow_InProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/Editor_OutOfProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/FindReferencesWindow_OutOfProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstance.cs
  src/VisualStudio/IntegrationTest/TestUtilities/WellKnownCommandNames.cs
Labels: Area-IDE

#59892 Remove unnecessary conditional logic from FlowAnalysisPass
  src/Compilers/CSharp/Portable/FlowAnalysis/FlowAnalysisPass.cs
Labels: Area-Compilers

#59900 Revert "Notify docs team for new breaking change documentation"
  .github/CODEOWNERS
Labels: Area-Compilers

#59864 Simplify the simplification code.
  src/Workspaces/CSharp/Portable/Simplification/CSharpSimplificationService.NodesAndTokensToReduceComputer.cs
  src/Workspaces/Core/Portable/Simplification/AbstractSimplificationService.cs
  src/Workspaces/Core/Portable/Simplification/NodeOrTokenToReduce.cs
  src/Workspaces/VisualBasic/Portable/Simplification/VisualBasicSimplificationService.NodesAndTokensToReduceComputer.vb
Labels: Area-IDE

#59906 If we delete dump files, log as such
  src/Tools/Source/RunTests/Program.cs
Labels: Area-Infrastructure

#59902 Try to get dumps for VS hanging during initialization
  src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs
Labels: Area-Infrastructure

#59233 Clean up diagnostic and solution crawler options - take 2
  src/EditorFeatures/Core.Cocoa/Preview/PreviewFactoryService.cs
  src/EditorFeatures/Core.Wpf/Interactive/InteractiveEvaluator.cs
  src/EditorFeatures/Core.Wpf/Interactive/InteractiveWindowWorkspace.cs
  src/EditorFeatures/Core.Wpf/Preview/PreviewFactoryService.cs
  src/EditorFeatures/Core/Interactive/InteractiveWorkspace.cs
  src/EditorFeatures/Core/Preview/AbstractPreviewFactoryService.cs
  src/EditorFeatures/Core/Shared/Preview/PreviewSolutionCrawlerRegistrationService.cs
  src/EditorFeatures/Core/Shared/Preview/PreviewWorkspace.cs
  src/EditorFeatures/Core/SolutionCrawler/HostSolutionCrawlerWorkspaceEventListener.cs
  src/EditorFeatures/Test/Preview/PreviewWorkspaceTests.cs
  src/EditorFeatures/Test/SolutionCrawler/WorkCoordinatorTests.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_BuildSynchronization.cs
  src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_IncrementalAnalyzer.cs
  src/Features/Core/Portable/Diagnostics/IRemoteDiagnosticAnalyzerService.cs
  src/Features/Core/Portable/Diagnostics/InternalDiagnosticsOptionsProvider.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/UnitTestingSolutionCrawlerServiceAccessor.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/UnitTestingSolutionCrawlerServiceAccessorFactory.cs
  src/Features/Core/Portable/SolutionCrawler/InternalSolutionCrawlerOptions.cs
  src/Features/Core/Portable/SolutionCrawler/InternalSolutionCrawlerOptionsProvider.cs
  src/Features/Core/Portable/SolutionCrawler/MiscSolutionCrawlerWorkspaceEventListener.cs
  src/Features/Core/Portable/SolutionCrawler/SolutionCrawlerLogger.cs
  src/Features/Core/Portable/SolutionCrawler/SolutionCrawlerService.cs
  src/Features/Core/Portable/SolutionCrawler/SolutionCrawlerTimeSpan.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.SemanticChangeProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.cs
  src/VisualStudio/CSharp/Impl/Interactive/CSharpVsInteractiveWindowProvider.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/Core/Def/Implementation/Remote/VisualStudioRemoteHostClientProvider.cs
  src/VisualStudio/Core/Def/Implementation/TaskList/ExternalErrorDiagnosticUpdateSource.cs
  src/VisualStudio/Core/Def/Interactive/VsInteractiveWindowProvider.cs
  src/VisualStudio/Core/Def/Telemetry/FileLogger.cs
  src/VisualStudio/Core/Def/Telemetry/VisualStudioLoggingOptionsMetadata.cs
  src/VisualStudio/Core/Impl/CodeModel/ProjectCodeModelFactory.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/VisualStudio/Core/Test.Next/Services/SolutionServiceTests.cs
  src/VisualStudio/Core/Test/Diagnostics/DiagnosticTableDataSourceTests.vb
  src/VisualStudio/Core/Test/Diagnostics/ExternalDiagnosticUpdateSourceTests.vb
  src/VisualStudio/LiveShare/Impl/Client/RemoteLanguageServiceWorkspace.cs
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/OptionPages/InternalSolutionCrawlerPage.cs
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/VisualStudioDiagnosticsWindowPackage.cs
  src/Workspaces/Core/Portable/Diagnostics/InternalDiagnosticsOptions.cs
  src/Workspaces/Remote/Core/RemoteProcessConfiguration.cs
  src/Workspaces/Remote/Core/ServiceHubRemoteHostClient.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
  src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/RemoteDiagnosticAnalyzerService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-IDE

#59928 Add quotes in string for clarity
  src/Tools/Source/RunTests/Program.cs
Labels: Area-Infrastructure

#59740 Bind declarations of checked conversion operators
  src/Compilers/CSharp/Portable/Binder/Binder_Crefs.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/OperatorFacts.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Members.cs
  src/Compilers/CSharp/Portable/Symbols/ConversionSignatureComparer.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedConversionSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbolBase.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxKindFacts.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Symbol/Symbols/CheckedUserDefinedOperatorsTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Core/Portable/Symbols/WellKnownMemberNames.cs
Labels: Area-Compilers, New Feature - CheckedUserDefinedOperators

#59750 Create attribute default arguments during binding
  src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/Compilation/AttributeSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_WellKnownAttributes.cs
Labels: Area-Compilers

#59730 Allow generate ctor intent to specify accessibility
  src/EditorFeatures/CSharpTest/Intents/AddConstructorParameterIntentTests.cs
  src/EditorFeatures/CSharpTest/Intents/GenerateConstructorIntentTests.cs
  src/EditorFeatures/CSharpTest/Intents/IntentTestsBase.cs
  src/EditorFeatures/Core/ExternalAccess/IntelliCode/IntentProcessor.cs
  src/Features/Core/Portable/AddConstructorParametersFromMembers/AddConstructorParametersFromMembersCodeRefactoringProvider.cs
  src/Features/Core/Portable/Completion/Providers/AbstractOverrideCompletionProvider.cs
  src/Features/Core/Portable/GenerateConstructorFromMembers/AbstractGenerateConstructorFromMembersCodeRefactoringProvider.ConstructorDelegatingCodeAction.cs
  src/Features/Core/Portable/GenerateConstructorFromMembers/AbstractGenerateConstructorFromMembersCodeRefactoringProvider.FieldDelegatingCodeAction.cs
  src/Features/Core/Portable/GenerateConstructorFromMembers/AbstractGenerateConstructorFromMembersCodeRefactoringProvider.GenerateConstructorWithDialogCodeAction.cs
  src/Features/Core/Portable/GenerateConstructorFromMembers/AbstractGenerateConstructorFromMembersCodeRefactoringProvider.State.cs
  src/Features/Core/Portable/GenerateConstructorFromMembers/AbstractGenerateConstructorFromMembersCodeRefactoringProvider.cs
  src/Features/Core/Portable/GenerateMember/GenerateConstructor/AbstractGenerateConstructorService.State.cs
  src/Features/Core/Portable/GenerateType/AbstractGenerateTypeService.GenerateNamedType.cs
  src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction_Method.cs
  src/Features/Core/Portable/Intents/IIntentProvider.cs
  src/Features/Core/Portable/Intents/IntentDataProvider.cs
  src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions.cs
Labels: Area-IDE, Approved to merge

#59903 Update CodeStyle/format/SDK versions
  dotnet-tools.json
  eng/Versions.props
  global.json
  src/Compilers/VisualBasic/Portable/Scanner/QuickTokenAccumulator.vb
  src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.vb
  src/Compilers/VisualBasic/Test/Emit/Emit/CompilationEmitTests.vb
  src/Compilers/VisualBasic/Test/Syntax/Syntax/SyntaxNormalizerTests.vb
Labels: Area-Infrastructure

#59599 Use the same codepath for computing light-bulb actions to determine if hte lightbulb shoudl appear at all.
  src/EditorFeatures/Core.Wpf/Suggestions/AsyncSuggestedActionsSource.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSourceProvider.cs
  src/EditorFeatures/Test/CodeFixes/CodeFixServiceTests.cs
  src/EditorFeatures/Test/EditAndContinue/Helpers/MockDiagnosticAnalyzerService.cs
  src/EditorFeatures/Test/SuggestedActions/SuggestedActionSourceProviderTests.cs
  src/EditorFeatures/Test2/Diagnostics/DiagnosticServiceTests.vb
  src/Features/Core/Portable/CodeFixes/CodeFixService.cs
  src/Features/Core/Portable/CodeFixes/FirstDiagnosticResult.cs
  src/Features/Core/Portable/CodeFixes/FirstFixResult.cs
  src/Features/Core/Portable/CodeFixes/ICodeFixService.cs
  src/Features/Core/Portable/Diagnostics/DiagnosticAnalyzerService.cs
  src/Features/Core/Portable/Diagnostics/IDiagnosticAnalyzerService.cs
  src/VisualStudio/Core/Test/Diagnostics/ExternalDiagnosticUpdateSourceTests.vb
Labels: Area-IDE

#59896 Break out embedded language classification entirely from normal classification
  src/Features/Core/Portable/EmbeddedLanguages/DateAndTime/LanguageServices/DateAndTimeEmbeddedLanguage.cs
  src/Features/Core/Portable/EmbeddedLanguages/Json/LanguageServices/JsonEmbeddedLanguage.cs
  src/Features/Core/Portable/EmbeddedLanguages/Json/LanguageServices/JsonEmbeddedLanguageClassifier.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexEmbeddedLanguage.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexEmbeddedLanguageClassifier.cs
  src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/CSharpEmbeddedLanguageClassificationServiceFactory.cs
  src/Workspaces/Core/Portable/Classification/ClassifiedSpan.cs
  src/Workspaces/Core/Portable/Classification/Classifier.cs
  src/Workspaces/Core/Portable/Classification/SyntaxClassification/EmbeddedLanguageClassificationService.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/LanguageServices/EmbeddedLanguageClassifierContext.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/LanguageServices/FallbackEmbeddedLanguage.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/LanguageServices/FallbackEmbeddedLanguageClassifier.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/LanguageServices/IEmbeddedLanguage.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/LanguageServices/IEmbeddedLanguageClassifier.cs
  src/Workspaces/VisualBasic/Portable/Classification/SyntaxClassification/VisualBasicEmbeddedLanguageClassificationServiceFactory.vb
Labels: Area-IDE

#59802 Push the two-step navigation system further through roslyn.
  src/EditorFeatures/Core.Wpf/Interactive/InteractiveDocumentNavigationService.cs
  src/EditorFeatures/Core.Wpf/NavigableSymbols/NavigableSymbolService.NavigableSymbol.cs
  src/EditorFeatures/Core/CommandHandlers/AbstractGoToCommandHandler`2.cs
  src/EditorFeatures/Core/Extensibility/NavigationBar/AbstractEditorNavigationBarItemService.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/IVSTypeScriptFindUsagesContext.cs
  src/EditorFeatures/Core/GoToDefinition/AbstractGoToDefinitionService.cs
  src/EditorFeatures/Core/GoToDefinition/GoToDefinitionCommandHandler.cs
  src/EditorFeatures/Core/Host/IStreamingFindReferencesPresenter.cs
  src/EditorFeatures/Core/Implementation/CodeActions/CodeActionEditHandlerService.cs
  src/EditorFeatures/Core/Implementation/IntelliSense/Helpers.cs
  src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionTestsBase.vb
  src/EditorFeatures/TestUtilities2/Utilities/GoToHelpers/MockDocumentNavigationService.vb
  src/EditorFeatures/TestUtilities2/Utilities/GoToHelpers/MockSymbolNavigationService.vb
  src/EditorFeatures/TestUtilities2/Utilities/MockDocumentNavigationServiceProvider.vb
  src/EditorFeatures/TestUtilities2/Utilities/MockSymbolNavigationServiceProvider.vb
  src/Features/Core/Portable/DocumentSpanExtensions.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/UnitTestingStackTraceServiceAccessor.cs
  src/Features/Core/Portable/FindUsages/DefinitionItem.DefaultDefinitionItem.cs
  src/Features/Core/Portable/FindUsages/DefinitionItem.cs
  src/Features/Core/Portable/Navigation/DefaultDocumentNavigationService.cs
  src/Features/Core/Portable/Navigation/DefaultSymbolNavigationService.cs
  src/Features/Core/Portable/Navigation/IDocumentNavigationService.cs
  src/Features/Core/Portable/Navigation/INavigableLocation.cs
  src/Features/Core/Portable/Navigation/ISymbolNavigationService.cs
  src/VisualStudio/Core/Def/Implementation/CallHierarchy/CallHierarchyProvider.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/MetadataDefinitionItemEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/RoslynDefinitionBucket.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/VisualStudioDefinitionsAndReferencesFactory.cs
  src/VisualStudio/Core/Def/Implementation/InheritanceMargin/MarginGlyph/InheritanceMarginContextMenu.xaml.cs
  src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractLanguageService`2.VsLanguageDebugInfo.cs
  src/VisualStudio/Core/Def/Implementation/Progression/GraphNavigatorExtension.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs
  src/VisualStudio/Core/Def/StackTraceExplorer/StackFrameViewModel.cs
  src/VisualStudio/Core/Impl/RoslynVisualStudioWorkspace.cs
  src/VisualStudio/Core/Test/GoToDefinition/GoToDefinitionApiTests.vb
  src/VisualStudio/LiveShare/Test/MockDocumentNavigationServiceFactory.cs
Labels: Area-IDE

#59941 Add back OmniSharpInlineHints
  .github/CODEOWNERS
  src/Tools/ExternalAccess/OmniSharp/InlineHints/OmniSharpInlineHintsOptions.cs
  src/Tools/ExternalAccess/OmniSharp/InlineHints/OmniSharpInlineHintsService.cs
Labels: Area-Compilers

#59876 Additional tests for pattern matching on `Span<char>`
  docs/contributing/Compiler Test Plan.md
  src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs
Labels: Area-Compilers

#59839 Ignore documents from projects that do not support EnC when calculating active statements
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSession.cs
Labels: Area-Interactive, Approved to merge

#59910 Avoid deadlock while loading ExtensionManagerPackage for integration tests
  src/VisualStudio/IntegrationTest/TestSetup/IntegrationTestServiceCommands.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InProcComponent.cs
Labels: Area-Infrastructure

#59952 Insert 17.2-p2 to VS rel/d17.2
  eng/config/PublishData.json
Labels: Area-Infrastructure

#59889 Add new feature to fix invalid constraints.
  src/Analyzers/CSharp/CodeFixes/CSharpCodeFixes.projitems
  src/Analyzers/CSharp/CodeFixes/CSharpCodeFixesResources.resx
  src/Analyzers/CSharp/CodeFixes/FixIncorrectConstraint/CSharpFixIncorrectConstraintCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.cs.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.de.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.es.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.fr.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.it.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.ja.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.ko.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.pl.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.pt-BR.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.ru.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.tr.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.zh-Hans.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.zh-Hant.xlf
  src/Analyzers/Core/CodeFixes/PredefinedCodeFixProviderNames.cs
  src/EditorFeatures/CSharpTest/FixIncorrectConstraint/FixIncorrectConstraintTests.cs
Labels: Area-IDE, Feature Request

#59905 Break out embedded language classification (MEF side)
  src/EditorFeatures/Core/EmbeddedLanguages/AbstractEmbeddedLanguageEditorFeaturesProvider.cs
  src/EditorFeatures/Core/EmbeddedLanguages/Json/JsonEmbeddedLanguageEditorFeatures.cs
  src/Features/CSharp/Portable/EmbeddedLanguages/CSharpJsonEmbeddedLanguageClassifier.cs
  src/Features/CSharp/Portable/EmbeddedLanguages/CSharpRegexEmbeddedLanguageClassifier.cs
  src/Features/Core/Portable/EmbeddedLanguages/AbstractEmbeddedLanguagesFeaturesProvider.cs
  src/Features/Core/Portable/EmbeddedLanguages/DateAndTime/LanguageServices/DateAndTimeEmbeddedLanguage.cs
  src/Features/Core/Portable/EmbeddedLanguages/Json/LanguageServices/AbstractJsonEmbeddedLanguageClassifier.cs
  src/Features/Core/Portable/EmbeddedLanguages/Json/LanguageServices/JsonEmbeddedLanguage.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/AbstractRegexEmbeddedLanguageClassifier.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexEmbeddedLanguage.cs
  src/Features/VisualBasic/Portable/EmbeddedLanguages/VisualBasicJsonEmbeddedLanguageClassifier.vb
  src/Features/VisualBasic/Portable/EmbeddedLanguages/VisualBasicRegexEmbeddedLanguageClassifier.vb
  src/Workspaces/CSharp/Portable/Classification/EmbeddedLanguages/CSharpEmbeddedLanguageClassificationServiceFactory.cs
  src/Workspaces/CSharp/Portable/Classification/EmbeddedLanguages/CSharpFallbackEmbeddedLanguageClassifier.cs
  src/Workspaces/CSharp/Portable/EmbeddedLanguages/LanguageServices/CSharpEmbeddedLanguagesProvider.cs
  src/Workspaces/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.Workspaces.csproj
  src/Workspaces/Core/Portable/Classification/EmbeddedLanguages/AbstractEmbeddedLanguageClassificationService.cs
  src/Workspaces/Core/Portable/Classification/EmbeddedLanguages/AbstractFallbackEmbeddedLanguageClassifier.cs
  src/Workspaces/Core/Portable/Classification/EmbeddedLanguages/EmbeddedLanguageClassifierContext.cs
  src/Workspaces/Core/Portable/Classification/EmbeddedLanguages/ExportEmbeddedLanguageClassifier.cs
  src/Workspaces/Core/Portable/Classification/EmbeddedLanguages/IEmbeddedLanguageClassificationService.cs
  src/Workspaces/Core/Portable/Classification/EmbeddedLanguages/IEmbeddedLanguageClassifier.cs
  src/Workspaces/Core/Portable/Classification/EmbeddedLanguages/PredefinedEmbeddedLanguageClassifierNames.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/LanguageServices/AbstractEmbeddedLanguagesProvider.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/LanguageServices/FallbackEmbeddedLanguage.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/LanguageServices/IEmbeddedLanguage.cs
  src/Workspaces/VisualBasic/Portable/Classification/EmbeddedLanguages/VisualBasicEmbeddedLanguageClassificationServiceFactory.vb
  src/Workspaces/VisualBasic/Portable/Classification/EmbeddedLanguages/VisualBasicFallbackEmbeddedLanguageClassifier.vb
  src/Workspaces/VisualBasic/Portable/Classification/SyntaxClassification/VisualBasicEmbeddedLanguageClassificationServiceFactory.vb
  src/Workspaces/VisualBasic/Portable/EmbeddedLanguages/LanguageServices/VisualBasicEmbeddedLanguagesProvider.vb
Labels: Area-IDE

#59846 Annotate BreakpointSpans and fix NREs
  src/EditorFeatures/CSharpTest/EditAndContinue/BreakpointSpansTests.cs
  src/Features/CSharp/Portable/Debugging/CSharpBreakpointResolutionService.cs
  src/Features/CSharp/Portable/EditAndContinue/BreakpointSpans.cs
  src/Features/CSharp/Portable/EditAndContinue/SyntaxUtilities.cs
  src/Features/VisualBasic/Portable/Debugging/VisualBasicBreakpointService.vb
  src/Tools/ExternalAccess/Razor/RazorBreakpointSpans.cs
Labels: Area-IDE

#59884 Exclude object's methods from ref struct completion list
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs
Labels: Area-IDE, Community

#59987 Refactor the embedded-language-detector components to make them reusable for any languages.
  src/EditorFeatures/CSharp/EmbeddedLanguages/CSharpEmbeddedLanguageEditorFeaturesProvider.cs
  src/EditorFeatures/Core/BraceMatching/AbstractEmbeddedLanguageBraceMatcher.cs
  src/EditorFeatures/Core/EmbeddedLanguages/AbstractEmbeddedLanguageEditorFeaturesProvider.cs
  src/EditorFeatures/Core/EmbeddedLanguages/DateAndTime/DateAndTimeEmbeddedLanguageEditorFeatures.cs
  src/EditorFeatures/Core/EmbeddedLanguages/Json/JsonEmbeddedBraceMatcher.cs
  src/EditorFeatures/Core/EmbeddedLanguages/Json/JsonEmbeddedLanguageEditorFeatures.cs
  src/EditorFeatures/Core/EmbeddedLanguages/RegularExpressions/RegexEmbeddedLanguageEditorFeatures.cs
  src/EditorFeatures/Test/EmbeddedLanguages/Json/LanguageServices/JsonLanguageDetectorTests.cs
  src/EditorFeatures/Test/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexPatternDetectorTests.cs
  src/EditorFeatures/VisualBasic/EmbeddedLanguages/VisualBasicEmbeddedLanguageEditorFeaturesProvider.vb
  src/Features/CSharp/Portable/Completion/CompletionProviders/EnumAndCompletionListTagCompletionProvider.cs
  src/Features/CSharp/Portable/EmbeddedLanguages/CSharpEmbeddedLanguageFeaturesProvider.cs
  src/Features/CSharp/Portable/EmbeddedLanguages/CSharpRegexEmbeddedLanguageClassifier.cs
  src/Features/Core/Portable/Completion/Providers/AbstractAggregateEmbeddedLanguageCompletionProvider.cs
  src/Features/Core/Portable/DocumentHighlighting/AbstractDocumentHighlightsService.cs
  src/Features/Core/Portable/EmbeddedLanguages/AbstractEmbeddedLanguagesFeaturesProvider.cs
  src/Features/Core/Portable/EmbeddedLanguages/AbstractLanguageDetector.cs
  src/Features/Core/Portable/EmbeddedLanguages/DateAndTime/DateAndTimeEmbeddedCompletionProvider.cs
  src/Features/Core/Portable/EmbeddedLanguages/DateAndTime/DateAndTimeEmbeddedLanguageFeatures.cs
  src/Features/Core/Portable/EmbeddedLanguages/DateAndTime/LanguageServices/DateAndTimeEmbeddedLanguage.cs
  src/Features/Core/Portable/EmbeddedLanguages/DateAndTime/LanguageServices/DateAndTimeLanguageDetector.cs
  src/Features/Core/Portable/EmbeddedLanguages/IEmbeddedLanguageFeatures.cs
  src/Features/Core/Portable/EmbeddedLanguages/Json/LanguageServices/AbstractJsonDetectionAnalyzer.cs
  src/Features/Core/Portable/EmbeddedLanguages/Json/LanguageServices/AbstractJsonDetectionCodeFixProvider.cs
  src/Features/Core/Portable/EmbeddedLanguages/Json/LanguageServices/AbstractJsonDiagnosticAnalyzer.cs
  src/Features/Core/Portable/EmbeddedLanguages/Json/LanguageServices/AbstractJsonEmbeddedLanguageClassifier.cs
  src/Features/Core/Portable/EmbeddedLanguages/Json/LanguageServices/JsonLanguageDetector.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/AbstractRegexDiagnosticAnalyzer.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/AbstractRegexEmbeddedLanguageClassifier.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexEmbeddedLanguage.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexLanguageDetector.cs
  src/Features/VisualBasic/Portable/EmbeddedLanguages/VisualBasicEmbeddedLanguageFeaturesProvider.vb
  src/Features/VisualBasic/Portable/EmbeddedLanguages/VisualBasicRegexEmbeddedLanguageClassifier.vb
  src/Workspaces/CSharp/Portable/Classification/EmbeddedLanguages/CSharpEmbeddedLanguageClassificationServiceFactory.cs
  src/Workspaces/CSharp/Portable/EmbeddedLanguages/LanguageServices/CSharpEmbeddedLanguagesProvider.cs
  src/Workspaces/Core/Portable/Classification/EmbeddedLanguages/AbstractFallbackEmbeddedLanguageClassifier.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/AbstractEmbeddedLanguagesProvider.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/EmbeddedLanguageCommentDetector.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/EmbeddedLanguageCommentOptions.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/EmbeddedLanguageDetector.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/EmbeddedLanguageInfo.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/IEmbeddedLanguage.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/IEmbeddedLanguagesProvider.cs
  src/Workspaces/VisualBasic/Portable/Classification/SyntaxClassification/VisualBasicSyntaxClassificationService.vb
  src/Workspaces/VisualBasic/Portable/EmbeddedLanguages/LanguageServices/VisualBasicEmbeddedLanguagesProvider.vb
Labels: Area-IDE

#59962 Merge features/patterns-span-char to release/dev17.3
  docs/Language Feature Status.md
  docs/contributing/Compiler Test Plan.md
  src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs
  src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs
  src/Compilers/CSharp/Portable/Compiler/MethodBodySynthesizer.Lowered.cs
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.DecisionDagRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedStringHashFunctionSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs
  src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/Portable/CodeGen/PrivateImplementationDetails.cs
  src/Compilers/Core/Portable/MemberDescriptor.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/Core/Portable/WellKnownTypes.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
  src/Compilers/Test/Utilities/CSharp/TestSources.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
Labels: Area-Compilers

#59938 Capability tracking
  src/EditorFeatures/CSharpTest/EditAndContinue/ActiveStatementTests.Methods.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/ActiveStatementTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/ActiveStatementTrackingServiceTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/Helpers/CSharpEditAndContinueTestHelpers.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/Helpers/EditAndContinueValidation.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/LineEditTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/StatementEditingTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/TopLevelEditingTests.cs
  src/EditorFeatures/Test/EditAndContinue/RemoteEditAndContinueServiceTests.cs
  src/EditorFeatures/Test/EditAndContinue/RudeEditDiagnosticTests.cs
  src/EditorFeatures/TestUtilities/EditAndContinue/EditAndContinueTestHelpers.cs
  src/EditorFeatures/VisualBasicTest/EditAndContinue/ActiveStatementTests.vb
  src/EditorFeatures/VisualBasicTest/EditAndContinue/ActiveStatementTrackingServiceTests.vb
  src/EditorFeatures/VisualBasicTest/EditAndContinue/Helpers/EditAndContinueValidation.vb
  src/EditorFeatures/VisualBasicTest/EditAndContinue/Helpers/VisualBasicEditAndContinueTestHelpers.vb
  src/EditorFeatures/VisualBasicTest/EditAndContinue/LineEditTests.vb
  src/EditorFeatures/VisualBasicTest/EditAndContinue/StatementEditingTests.vb
  src/EditorFeatures/VisualBasicTest/EditAndContinue/TopLevelEditingTests.vb
  src/Features/CSharp/Portable/EditAndContinue/CSharpEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/Contracts/EditAndContinue/ManagedModuleUpdate.cs
  src/Features/Core/Portable/EditAndContinue/DocumentAnalysisResults.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueCapabilitiesGrantor.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueDiagnosticDescriptors.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/Core/Portable/EditAndContinue/ProjectChanges.cs
  src/Features/Core/Portable/EditAndContinue/RudeEditKind.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
Labels: Area-Interactive

#59887 Fix pattern based arguments in ForEachLoopOperationInfo without binding assumptions
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IForEachLoopStatement.cs
Labels: Area-Compilers, Community

#60007 Add build triggers to azure pipeline yaml
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#59958 Expose ForceExpandedCompletionIndexCreation option to O#
  src/Tools/ExternalAccess/OmniSharp/Completion/OmniSharpCompletionOptions.cs
Labels: Area-IDE

#60001 Update version number for our 17.3 Preview 1 builds
  eng/Versions.props
Labels: Area-Infrastructure

#60009 Add build triggers to azure pipeline yaml
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#59957 SyntaxContext's GlobalStatementContext changes
  src/EditorFeatures/CSharpTest2/Recommendations/NewKeywordRecommenderTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/CSharpSyntaxContext.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTokenExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/ContextQuery/SyntaxContext.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/VisualBasicSyntaxContext.vb
Labels: Area-IDE

#59947 CSharpImportAdder should be able to add the intended import if the identifier is a var
  src/EditorFeatures/CSharpTest/Diagnostics/GenerateMethod/GenerateDeconstructMethodTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/GenerateMethod/GenerateMethodTests.cs
  src/Workspaces/CSharp/Portable/Editing/CSharpImportAdder.cs
Labels: Area-IDE

#59956 Update integration tests to support both possible Go To Implementation results
  src/EditorFeatures/Core/CommandHandlers/AbstractGoToCommandHandler`2.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpGoToImplementation.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/AsyncNavigationKind.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/ErrorListExtensions.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/StateResetInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicGoToImplementation.cs
Labels: Area-Infrastructure

#59997 Always enable breakable range LSP handler
  src/EditorFeatures/Core/LanguageServer/AlwaysActivateInProcLanguageClient.cs
Labels: Area-IDE, Needs Shiproom Approval

#59838 Simplify consumption side of the new async navigation helpers.
  src/EditorFeatures/Core.Wpf/NavigableSymbols/NavigableSymbolService.NavigableSymbol.cs
  src/EditorFeatures/Core.Wpf/NavigateTo/NavigateToItemDisplay.cs
  src/EditorFeatures/Core/CodeActions/CodeActionEditHandlerService.cs
  src/EditorFeatures/Core/CommandHandlers/AbstractGoToCommandHandler`2.cs
  src/EditorFeatures/Core/Extensibility/NavigationBar/AbstractEditorNavigationBarItemService.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptNavigationBarItemService.cs
  src/EditorFeatures/Core/ExtractInterface/AbstractExtractInterfaceCommandHandler.cs
  src/EditorFeatures/Core/GoToDefinition/GoToDefinitionCommandHandler.cs
  src/EditorFeatures/Core/GoToDefinition/GoToDefinitionHelpers.cs
  src/EditorFeatures/Core/Host/IStreamingFindReferencesPresenter.cs
  src/EditorFeatures/Core/IntelliSense/Helpers.cs
  src/EditorFeatures/Core/Navigation/IDocumentNavigationServiceExtensions.cs
  src/Features/Core/Portable/DocumentSpanExtensions.cs
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/Api/VSTypeScriptDocumentNavigationServiceWrapper.cs
  src/Features/Core/Portable/Navigation/IDocumentNavigationService.cs
  src/Tools/ExternalAccess/FSharp/Navigation/FSharpDocumentNavigationService.cs
  src/VisualStudio/Core/Def/Implementation/CallHierarchy/CallHierarchyDetail.cs
  src/VisualStudio/Core/Def/Implementation/CallHierarchy/CallHierarchyProvider.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Contexts/AbstractTableDataSourceFindUsagesContext.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Contexts/WithReferencesFindUsagesContext.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Contexts/WithoutReferencesFindUsagesContext.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/DocumentSpanEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/MetadataDefinitionItemEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/RoslynDefinitionBucket.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/StreamingFindUsagesPresenter.cs
  src/VisualStudio/Core/Def/Implementation/InheritanceMargin/MarginGlyph/InheritanceMarginContextMenu.xaml.cs
  src/VisualStudio/Core/Def/Implementation/Progression/GraphNavigatorExtension.cs
  src/VisualStudio/Core/Def/Implementation/TableDataSource/AbstractTableEntriesSnapshot.cs
  src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs
  src/VisualStudio/Core/Def/StackTraceExplorer/StackFrameViewModel.cs
  src/VisualStudio/Core/Def/ValueTracking/TreeItemViewModel.cs
  src/VisualStudio/Core/Def/ValueTracking/ValueTrackedTreeItemViewModel.cs
  src/VisualStudio/Core/Impl/RoslynVisualStudioWorkspace.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/SourceGeneratedFileItems/SourceGeneratedFileItem.cs
Labels: Area-IDE

#59752 Filter to exact test class names in RunTests
  src/Tools/Source/RunTests/ProcessTestExecutor.cs
Labels: Area-Infrastructure

#59977 Fix !! incremental parsing
  src/Compilers/CSharp/Portable/Parser/Blender.Reader.cs
  src/Compilers/CSharp/Test/Syntax/IncrementalParsing/IncrementalParsingTests.cs
Labels: Area-Compilers, Community

#59862 Check for prototype comments in separate job
  azure-pipelines.yml
  eng/test-build-correctness.ps1
  eng/todo-check.ps1
Labels: Area-Infrastructure

#59985 ColorSchemes namespace refactoring
  src/EditorFeatures/Core/Options/ColorSchemeOptions.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/ColorSchemes/ColorSchemeApplier.ClassificationVerifier.cs
  src/VisualStudio/Core/Def/ColorSchemes/ColorSchemeApplier.ColorScheme.cs
  src/VisualStudio/Core/Def/ColorSchemes/ColorSchemeApplier.ColorSchemeReader.cs
  src/VisualStudio/Core/Def/ColorSchemes/ColorSchemeApplier.RegistryItem.cs
  src/VisualStudio/Core/Def/ColorSchemes/ColorSchemeApplier.RegistryItemConverter.cs
  src/VisualStudio/Core/Def/ColorSchemes/ColorSchemeApplier.Settings.cs
  src/VisualStudio/Core/Def/ColorSchemes/ColorSchemeApplier.cs
  src/VisualStudio/Core/Def/Implementation/ColorSchemes/ColorSchemeName.cs
  src/VisualStudio/Core/Def/Implementation/ColorSchemes/ColorSchemeOptions.cs
  src/VisualStudio/Core/Def/RoslynPackage.cs
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageStrings.vb
Labels: Area-IDE

#59981 Clean up info bar and error reporting service
  src/EditorFeatures/CSharpTest/CodeActions/Preview/PreviewExceptionTests.cs
  src/EditorFeatures/Core/ErrorReporting/EditorErrorReportingService.cs
  src/EditorFeatures/Core/Extensions/EditorLayerExtensionManager.cs
  src/EditorFeatures/Core/InfoBar/EditorInfoBarService.cs
  src/EditorFeatures/Core/Workspaces/EditorErrorReportingServiceFactory.cs
  src/EditorFeatures/Test/CodeFixes/CodeFixServiceTests.cs
  src/EditorFeatures/Test/CodeRefactorings/CodeRefactoringServiceTest.cs
  src/Features/Core/Portable/CodeFixes/CodeFixService.cs
  src/VisualStudio/Core/Def/ErrorReporting/DetailedErrorInfoDialog.xaml
  src/VisualStudio/Core/Def/ErrorReporting/DetailedErrorInfoDialog.xaml.cs
  src/VisualStudio/Core/Def/ErrorReporting/VisualStudioErrorReportingService.ExceptionFormatting.cs
  src/VisualStudio/Core/Def/ErrorReporting/VisualStudioErrorReportingService.cs
  src/VisualStudio/Core/Def/ErrorReporting/VisualStudioInfoBar.cs
  src/VisualStudio/Core/Def/ExternalAccess/LegacyCodeAnalysis/LegacyCodeAnalysisVisualStudioSuppressionFixServiceAccessor.cs
  src/VisualStudio/Core/Def/Implementation/VirtualMemoryNotificationListener.cs
  src/VisualStudio/Core/Def/InfoBar/VisualStudioInfoBarService.cs
  src/VisualStudio/Core/Def/InfoBar/VisualStudioInfoBarWorkspaceService.cs
  src/VisualStudio/Core/Def/KeybindingReset/KeybindingResetDetector.cs
  src/VisualStudio/Core/Def/Workspace/VisualStudioErrorReportingServiceFactory.cs
  src/Workspaces/Core/Portable/ErrorReporting/IErrorReportingService.cs
  src/Workspaces/Core/Portable/ErrorReporting/InfoBarUI.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemostHostClient.cs
  src/Workspaces/CoreTestUtilities/TestErrorReportingService.cs
Labels: Area-IDE

#60026 Preserve trivia from first using in file scoped namespace
  src/Analyzers/CSharp/Tests/RemoveUnnecessaryImports/RemoveUnnecessaryImportsTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpRemoveUnnecessaryImportsService.Rewriter.cs
Labels: Area-IDE

#60023 Preserve the lack of trivia at the end of the file
  src/EditorFeatures/CSharpTest/ConvertNamespace/ConvertNamespaceCommandHandlerTests.cs
  src/EditorFeatures/CSharpTest/ConvertNamespace/ConvertToFileScopedNamespaceAnalyzerTests.cs
  src/EditorFeatures/CSharpTest/Formatting/CSharpNewDocumentFormattingServiceTests.cs
  src/Features/CSharp/Portable/ConvertNamespace/ConvertNamespaceTransform.cs
Labels: Area-IDE

#60028 Format whitespace in interpolations
  src/EditorFeatures/CSharpTest/CodeActions/IntroduceVariable/IntroduceVariableTests.cs
  src/EditorFeatures/CSharpTest/ConvertToInterpolatedString/ConvertPlaceholderToInterpolatedStringTests.cs
  src/Workspaces/CSharpTest/Formatting/FormattingTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/SpacingFormattingRule.cs
Labels: Area-IDE

#60000 Simplify code with helper method
  src/Features/Core/Portable/CodeFixes/CodeFixService.cs
Labels: Area-IDE

#60021 Fixing up bits of PR feedback.
  src/EditorFeatures/Core.Wpf/NavigableSymbols/NavigableSymbolService.NavigableSymbol.cs
  src/EditorFeatures/Core.Wpf/NavigateTo/NavigateToItemDisplay.cs
  src/EditorFeatures/Core/CommandHandlers/AbstractGoToCommandHandler`2.cs
  src/EditorFeatures/Core/GoToDefinition/GoToDefinitionCommandHandler.cs
  src/EditorFeatures/Core/GoToDefinition/GoToDefinitionHelpers.cs
  src/EditorFeatures/Core/Host/IStreamingFindReferencesPresenter.cs
  src/EditorFeatures/Core/IntelliSense/Helpers.cs
  src/EditorFeatures/Core/Navigation/IDocumentNavigationServiceExtensions.cs
  src/VisualStudio/Core/Def/Implementation/CallHierarchy/CallHierarchyProvider.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/MetadataDefinitionItemEntry.cs
  src/VisualStudio/Core/Def/Implementation/FindReferences/RoslynDefinitionBucket.cs
  src/VisualStudio/Core/Def/Implementation/InheritanceMargin/MarginGlyph/InheritanceMarginContextMenu.xaml.cs
  src/VisualStudio/Core/Def/StackTraceExplorer/StackFrameViewModel.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/SourceGeneratedFileItems/SourceGeneratedFileItem.cs
Labels: Area-IDE

#60013 Inline Diagnostics Multi-Line Errors
  src/EditorFeatures/Core.Wpf/Adornments/AbstractAdornmentManager.cs
  src/EditorFeatures/Core.Wpf/InlineDiagnostics/InlineDiagnosticsAdornmentManager.cs
Labels: Area-IDE

#59693 Add LSP spell checking support.
  src/EditorFeatures/CSharpTest/SpellCheck/SpellCheckSpanTests.cs
  src/EditorFeatures/Core/LanguageServer/AlwaysActivateInProcLanguageClient.cs
  src/EditorFeatures/TestUtilities/SpellCheck/AbstractSpellCheckSpanTests.cs
  src/EditorFeatures/VisualBasic/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.vbproj
  src/EditorFeatures/VisualBasicTest/SpellCheck/SpellCheckSpanTests.vb
  src/Features/CSharp/Portable/SpellCheck/CSharpSpellCheckSpanService.cs
  src/Features/Core/Portable/SpellCheck/AbstractSpellCheckSpanService.cs
  src/Features/Core/Portable/SpellCheck/ISpellCheckingSpanService.cs
  src/Features/Core/Portable/SpellCheck/SpellCheckKind.cs
  src/Features/Core/Portable/SpellCheck/SpellCheckSpan.cs
  src/Features/LanguageServer/Protocol/DefaultCapabilitiesProvider.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/PullHandlers/VersionedPullCache`1.cs
  src/Features/LanguageServer/Protocol/Handler/PullHandlers/VersionedPullCache`2.cs
  src/Features/LanguageServer/Protocol/Handler/SpellCheck/AbstractSpellCheckingHandler.cs
  src/Features/LanguageServer/Protocol/Handler/SpellCheck/DocumentSpellCheckHandler.cs
  src/Features/LanguageServer/Protocol/Handler/SpellCheck/DocumentSpellCheckHandlerProvider.cs
  src/Features/LanguageServer/Protocol/Handler/SpellCheck/WorkspaceSpellCheckHandler.cs
  src/Features/LanguageServer/Protocol/Handler/SpellCheck/WorkspaceSpellCheckHandlerProvider.cs
  src/Features/LanguageServer/Protocol/LanguageServerTarget.cs
  src/Features/LanguageServer/ProtocolUnitTests/SpellCheck/SpellCheckTests.cs
  src/Features/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.Features.vbproj
  src/Features/VisualBasic/Portable/SpellCheck/VisualBasicSpellCheckSpanService.vb
  src/Workspaces/CSharp/Portable/Classification/ClassificationHelpers.cs
  src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/CSharpSyntaxClassificationService.cs
  src/Workspaces/CSharp/Portable/Classification/Worker.cs
  src/Workspaces/CSharp/Portable/Classification/Worker_DocumentationComments.cs
  src/Workspaces/CSharp/Portable/Classification/Worker_Preprocesser.cs
  src/Workspaces/Core/Portable/Classification/SyntaxClassification/AbstractSyntaxClassificationService.cs
  src/Workspaces/Core/Portable/Classification/SyntaxClassification/ISyntaxClassificationService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxKinds.vb
  src/Workspaces/VisualBasic/Portable/Classification/ClassificationHelpers.vb
  src/Workspaces/VisualBasic/Portable/Classification/SyntaxClassification/VisualBasicSyntaxClassificationService.vb
Labels: Area-IDE

#59874 Analyze flow in receiver of extension method group in delegate creation
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs
  src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs
Labels: Area-Compilers

#59937 Require a matching regular operator for a checked operator
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/CheckedUserDefinedOperatorsTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
Labels: Area-Compilers, New Feature - CheckedUserDefinedOperators

#60015 Clarify breaking change documentation for struct initialization and correct link
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 6.md
Labels: Area-Compilers

#59994 Fix typo in CodeGenDifferences.md
  docs/compilers/CSharp/CodeGen Differences.md
Labels: Documentation, Area-SDK and Samples

#59638 Fix more lock contention
  src/Tools/ExternalAccess/FSharp/Internal/VisualStudio/FSharpProjectExternalErrorReporterFactory.cs
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/VisualStudio/Core/Def/ProjectSystem/Legacy/AbstractLegacyProject.cs
  src/VisualStudio/Core/Def/ProjectSystem/Readme.md
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioProject.BatchingDocumentCollection.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioProject.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioProjectFactory.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.OpenFileTracker.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProjectFactory.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/TaskExtensions.cs
Labels: Area-IDE

#60012 Handle optional exclamations in conditional access in RecommendationServiceRunner
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxNodeExtensions.cs
Labels: Area-IDE

#59999 KeyOriginatorFile is input to csc task
  src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets
  src/Compilers/Core/MSBuildTask/Microsoft.VisualBasic.Core.targets
Labels: Area-Compilers

#60024 Make call-hierarchy navigation cancellable
  src/VisualStudio/Core/Def/Implementation/CallHierarchy/CallHierarchyCommandHandler.cs
  src/VisualStudio/Core/Def/Implementation/CallHierarchy/CallHierarchyDetail.cs
  src/VisualStudio/Core/Def/Implementation/CallHierarchy/CallHierarchyItem.cs
  src/VisualStudio/Core/Def/Implementation/CallHierarchy/CallHierarchyProvider.cs
  src/VisualStudio/Core/Def/Implementation/CallHierarchy/Finders/AbstractCallFinder.cs
  src/VisualStudio/Core/Def/Implementation/CallHierarchy/Finders/ImplementerFinder.cs
  src/VisualStudio/Core/Def/Implementation/CallHierarchy/Finders/OverridingMemberFinder.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
Labels: Area-IDE

#60039 Inline Diagnostics: Call dispose and removed event handler that was unnnecessary
  src/EditorFeatures/Core.Wpf/InlineDiagnostics/InlineDiagnosticsAdornmentManager.cs
  src/EditorFeatures/Core.Wpf/InlineDiagnostics/InlineDiagnosticsTag.cs
Labels: Area-IDE

#59944 Avoid Large Object Heap allocations in GetPrioritizedPendingDocuments
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs
Labels: Area-IDE

#60037 Add back logic for main-vs-deps branch
  eng/config/PublishData.json
Labels: Area-Infrastructure

#59995 [LSP] Allow Razor to utilize C# LSP server in tests
  src/EditorFeatures/TestUtilities/LanguageServer/TestWorkspaceRegistrationService.cs
  src/Features/LanguageServer/Protocol/ILanguageServerFactory.cs
  src/Features/LanguageServer/Protocol/Microsoft.CodeAnalysis.LanguageServer.Protocol.csproj
  src/Tools/ExternalAccess/Razor/IRazorCapabilitiesProvider.cs
  src/Tools/ExternalAccess/Razor/IRazorLanguageServerFactory.cs
  src/Tools/ExternalAccess/Razor/IRazorLanguageServerTarget.cs
  src/Tools/ExternalAccess/Razor/Microsoft.CodeAnalysis.ExternalAccess.Razor.csproj
  src/Tools/ExternalAccess/Razor/RazorLanguageServerFactoryWrapper.cs
  src/Tools/ExternalAccess/Razor/RazorLanguageServerTargetWrapper.cs
  src/Tools/ExternalAccess/Razor/RazorTestWorkspaceRegistrationService.cs
Labels: Area-IDE, LSP

#59983 Enable embedded languages to export the identifier they should be associated with in comments/attributes
  src/Features/CSharp/Portable/EmbeddedLanguages/CSharpJsonEmbeddedLanguageClassifier.cs
  src/Features/CSharp/Portable/EmbeddedLanguages/CSharpRegexEmbeddedLanguageClassifier.cs
  src/Features/Core/Portable/EmbeddedLanguages/AbstractLanguageDetector.cs
  src/Features/Core/Portable/EmbeddedLanguages/DateAndTime/LanguageServices/DateAndTimeLanguageDetector.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexLanguageDetector.cs
  src/Features/VisualBasic/Portable/EmbeddedLanguages/VisualBasicJsonEmbeddedLanguageClassifier.vb
  src/Features/VisualBasic/Portable/EmbeddedLanguages/VisualBasicRegexEmbeddedLanguageClassifier.vb
  src/Workspaces/CSharp/Portable/Classification/EmbeddedLanguages/CSharpEmbeddedLanguageClassificationServiceFactory.cs
  src/Workspaces/CSharp/Portable/Classification/EmbeddedLanguages/CSharpFallbackEmbeddedLanguageClassifier.cs
  src/Workspaces/Core/Portable/Classification/EmbeddedLanguages/AbstractEmbeddedLanguageClassificationService.cs
  src/Workspaces/Core/Portable/Classification/EmbeddedLanguages/ExportEmbeddedLanguageClassifier.cs
  src/Workspaces/Core/Portable/Classification/EmbeddedLanguages/PredefinedEmbeddedLanguageClassifierNames.cs
  src/Workspaces/Core/Portable/EmbeddedLanguages/EmbeddedLanguageMetadata.cs
  src/Workspaces/VisualBasic/Portable/Classification/EmbeddedLanguages/VisualBasicEmbeddedLanguageClassificationServiceFactory.vb
  src/Workspaces/VisualBasic/Portable/Classification/EmbeddedLanguages/VisualBasicFallbackEmbeddedLanguageClassifier.vb
Labels: Area-IDE

#59993 Trim leading blank lines in IDE0017
  src/Analyzers/CSharp/CodeFixes/UseCollectionInitializer/CSharpUseCollectionInitializerCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseObjectInitializer/CSharpUseObjectInitializerCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests.cs
  src/Analyzers/CSharp/Tests/UseObjectInitializer/UseObjectInitializerTests.cs
Labels: Area-IDE, Community

#59787 Codeaction diagnostics
  src/EditorFeatures/Core/LanguageServer/Handlers/CodeActions/CodeActionHelpers.cs
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/CodeActions/CodeActionsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
  src/VisualStudio/Setup.Dependencies/Roslyn.VisualStudio.Setup.Dependencies.csproj
Labels: Area-IDE, LSP

#60043 Fix PoliCheck warning
  src/EditorFeatures/CSharpTest/EditAndContinue/BreakpointSpansTests.cs
Labels: Area-Interactive

#60041 Fix reporting Hot Reload diagnostics for cshtml files
  src/EditorFeatures/Test/EditAndContinue/CompileTimeSolutionProviderTests.cs
  src/Features/Core/Portable/EditAndContinue/Remote/RemoteEditAndContinueServiceProxy.cs
  src/Features/Core/Portable/Workspace/CompileTimeSolutionProvider.cs
Labels: Area-Interactive

#58344 Update incremental generator docs
  docs/features/incremental-generators.md
Labels: Area-Compilers, Documentation, New Feature - Source Generators

#60034 Fix transition for cancelled light bulb in integration tests
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/LightBulbHelper.cs
Labels: Area-IDE

#60063 Move json serializer options out of mef constructed part to avoid loa…
  src/EditorFeatures/Core/ExternalAccess/IntelliCode/IntentProcessor.cs
  src/Features/Core/Portable/Intents/IntentDataProvider.cs
Labels: Area-IDE

#60074 Update the standalone template file name for 17.2
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/SolutionExplorer_InProc.cs
Labels: Area-Infrastructure

#60008 Add details on validation related to EnC
  docs/contributing/Compiler Test Plan.md
  docs/contributing/Testing for Interactive readiness.md
Labels: Area-Compilers

#60087 Revert "Analyze flow in receiver of extension method group in delegate creation"
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs
  src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs
Labels: Area-Compilers

#60051 Suppress file change notifications for VSFILECHG_Attr
  src/VisualStudio/Core/Def/ProjectSystem/FileChangeTracker.cs
  src/VisualStudio/Core/Def/ProjectSystem/FileChangeWatcher.cs
Labels: Area-IDE

#60016 Fix support for OOP reporting diagnostics in source generated files
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.InProcOrRemoteHostAnalyzerRunner.cs
Labels: Area-Analyzers

#60032 Support consumption scenarios for checked user-defined operators
  src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/UserDefinedExplicitConversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/BinaryOperatorOverloadResolution.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/OperatorFacts.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/UnaryOperatorOverloadResolution.cs
  src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs
  src/Compilers/CSharp/Portable/Compilation/BuiltInOperators.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs
  src/Compilers/CSharp/Portable/Compiler/MethodBodySynthesizer.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/FlowAnalysisPass.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncExceptionHandlerRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.cs
  src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ExpressionLambdaRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs
  src/Compilers/CSharp/Portable/Lowering/InitializerRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_NullCoalescingOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StringInterpolation.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_SwitchExpression.cs
  src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedEntryPointSymbol.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NativeIntegerTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs
  src/Compilers/CSharp/Test/Symbol/Compilation/GetSemanticInfoTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/CheckedUserDefinedOperatorsTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
  src/Compilers/Test/Utilities/CSharp/Extensions.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EEConstructorSymbol.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EEMethodSymbol.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/PlaceholderLocalSymbol.cs
Labels: Area-Compilers, New Feature - CheckedUserDefinedOperators

#60094 Remove unnecessary test method overrides
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpSquigglesCommon.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpSquigglesDesktop.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpSquigglesNetCore.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicSquigglesCommon.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicSquigglesDesktop.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicSquigglesNetCore.cs
Labels: Area-IDE

#60061 Update Language Feature Status for ref fields
  docs/Language Feature Status.md
Labels: Area-Compilers

#60105 Fix NRE in VSTypeScriptGoToDefinitionServiceFactory
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/IVSTypeScriptGoToDefinitionServiceFactoryImplementation.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptGoToDefinitionServiceFactory.cs
Labels: Area-IDE

#60113 Keep track of when a file code model is created.
  src/VisualStudio/Core/Impl/CodeModel/FileCodeModel.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-IDE

#59303 Semantic Snippets: Console snippet first look
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/CompletionProviderOrderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpConsoleSnippetCompletionProviderTests.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/Scripting/LoadDirectiveCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/Snippets/CSharpSnippetCompletionProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpConsoleSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpSnippetService.cs
  src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/Snippets/SnippetCompletionItem.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/Snippets/AbstractConsoleSnippetProvider.cs
  src/Features/Core/Portable/Snippets/AbstractSnippetProvider.cs
  src/Features/Core/Portable/Snippets/AbstractSnippetService.cs
  src/Features/Core/Portable/Snippets/ExportSnippetProviderAttribute.cs
  src/Features/Core/Portable/Snippets/ISnippetProvider.cs
  src/Features/Core/Portable/Snippets/ISnippetService.cs
  src/Features/Core/Portable/Snippets/SnippetChange.cs
  src/Features/Core/Portable/Snippets/SnippetData.cs
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE

#60019 Fix path to readme.md
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
Labels: Area-IDE

#60131 Do not show top-level-symbols inside type declarations
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs
Labels: Area-IDE

#60104 Update Light Bulb workarounds for 17.2 CI machines
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/LightBulbHelper.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/WorkaroundsInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/WorkspaceInProcess.cs
Labels: Area-IDE

#60081 Respond with updated diagnostics when EnC diagnostics state is different
  src/Features/Core/Portable/EditAndContinue/EditAndContinueDiagnosticUpdateSource.cs
  src/Features/Core/Portable/EditAndContinue/Remote/RemoteDebuggingSessionProxy.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DocumentPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DocumentPullDiagnosticHandlerProvider.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Experimental/ExperimentalDocumentPullDiagnosticHandlerProvider.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Experimental/ExperimentalDocumentPullDiagnosticsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Experimental/ExperimentalWorkspacePullDiagnosticHandlerProvider.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Experimental/ExperimentalWorkspacePullDiagnosticsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandlerProvider.cs
  src/Features/LanguageServer/Protocol/Handler/PullHandlers/VersionedPullCache`2.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
Labels: Area-IDE

#60138 Fixed codefix "Use discard pattern" incorrectly applied to foreach in top-level statements
  src/Analyzers/CSharp/CodeFixes/RemoveUnusedParametersAndValues/CSharpRemoveUnusedValuesCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/RemoveUnusedParametersAndValues/RemoveUnusedValueAssignmentTests.cs
  src/Analyzers/Core/CodeFixes/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs
Labels: Area-IDE, Community

#60146 Support converting to interpolated string for constants if language version is cpable of this
  src/EditorFeatures/CSharpTest/ConvertToInterpolatedString/ConvertRegularStringToInterpolatedStringTests.cs
  src/EditorFeatures/VisualBasic/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.vbproj
  src/EditorFeatures/VisualBasicTest/ConvertToInterpolatedString/ConvertRegularStringToInterpolatedStringTests.vb
  src/Features/CSharp/Portable/ConvertToInterpolatedString/CSharpConvertConcatenationToInterpolatedStringRefactoringProvider.cs
  src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.cs
  src/Features/Core/Portable/ConvertToInterpolatedString/ConvertRegularStringToInterpolatedStringRefactoringProvider.cs
  src/Features/VisualBasic/Portable/ConvertToInterpolatedString/VisualBasicConvertConcatenationToInterpolatedStringRefactoringProvider.vb
  src/Features/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.Features.vbproj
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE, Community

#60092 Adjust delegate caching logic for abstract statics.
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/DelegateCacheContainer.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/DelegateCacheRewriter.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
Labels: Area-Compilers, New Feature - StaticAbstractMembersInInterfaces

#60139 Run two attempts of new integration tests using harness functionality
  eng/Versions.props
  src/Tools/Source/RunTests/ProcessTestExecutor.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/AbstractIntegrationTest.cs
Labels: Area-Infrastructure

#60151 Support property initializer statement completion
  src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs
  src/EditorFeatures/CSharpTest/CompleteStatement/CSharpCompleteStatementCommandHandlerTests.cs
Labels: Area-IDE, Community

#60116 Fixed compound assignment
  src/Analyzers/CSharp/CodeFixes/UseCompoundAssignment/CSharpUseCompoundAssignmentCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseCompoundAssignment/UseCompoundAssignmentTests.cs
  src/Analyzers/Core/CodeFixes/UseCompoundAssignment/AbstractUseCompoundAssignmentCodeFixProvider.cs
  src/Analyzers/VisualBasic/CodeFixes/UseCompoundAssignment/VisualBasicUseCompoundAssignmentCodeFixProvider.vb
  src/Analyzers/VisualBasic/Tests/UseCompoundAssignment/UseCompoundAssignmentTests.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTriviaListExtensions.cs
Labels: Area-IDE, Community

#60111 Report a "better" error for an unmatched checked user-defined operator.
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Symbol/Symbols/CheckedUserDefinedOperatorsTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
Labels: Area-Compilers, New Feature - CheckedUserDefinedOperators

#60102 Provide keywords in completion list in certain CastExpression context
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/AwaitCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/KeywordCompletionProviderTests.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/AwaitCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/BaseKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/FalseKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/NameOfKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/NewKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/NullKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/SizeOfKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/ThisKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/TrueKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/TypeOfKeywordRecommender.cs
  src/Features/Core/Portable/Completion/Providers/AbstractAwaitCompletionProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTokenExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/SyntaxTokenExtensions.cs
Labels: Area-IDE

#60165 Remove enableRoslynAnalyzers from settings.json
  .vscode/settings.json
Labels: Area-Infrastructure

#59978 Remove unneeded `isPartial` check
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordOrdinaryMethod.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
Labels: Area-Compilers, Community

#59698 Use a longer timeout if we previously had a successful Source Link result
  src/EditorFeatures/CSharpTest/PdbSourceDocument/PdbSourceDocumentLoaderServiceTests.cs
  src/Features/Core/Portable/PdbSourceDocument/IPdbSourceDocumentLoaderService.cs
  src/Features/Core/Portable/PdbSourceDocument/PdbSourceDocumentLoaderService.cs
  src/Features/Core/Portable/PdbSourceDocument/PdbSourceDocumentMetadataAsSourceFileProvider.cs
Labels: Area-IDE

#60119 Disable IntelliCode RepositoryAttachedModels in CI
  eng/build.ps1
  src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs
Labels: Area-Infrastructure

#60121 Add accessor to Razor test registration service
  src/Tools/ExternalAccess/Razor/RazorTestWorkspaceRegistrationService.cs
Labels: Area-IDE

#60010 Remove obsolete helpers
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/IVSTypeScriptFindUsagesContext.cs
  src/EditorFeatures/Core/GoToDefinition/AbstractGoToSymbolService.cs
  src/EditorFeatures/Core/Host/IStreamingFindReferencesPresenter.cs
  src/EditorFeatures/TestUtilities2/Utilities/GoToHelpers/MockDocumentNavigationService.vb
  src/Features/Core/Portable/FindUsages/DefinitionItem.DefaultDefinitionItem.cs
  src/Features/Core/Portable/FindUsages/DefinitionItem.cs
  src/VisualStudio/Core/Def/FindReferences/VisualStudioDefinitionsAndReferencesFactory.cs
  src/VisualStudio/Core/Def/StackTraceExplorer/StackFrameViewModel.cs
Labels: Area-IDE

#58727 Apply source-build patches
  eng/Tools.props
  src/Interactive/csi/csi.csproj
  src/Interactive/vbi/vbi.vbproj
Labels: Area-Infrastructure

#60022 Fix binding order for Dispose in async foreach
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/Binder/UsingStatementBinder.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAwaitForeachTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAwaitUsingTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenForEachTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IForEachLoopStatement.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/ForEachTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/UsingStatementTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/AsyncStreamsParsingTests.cs
Labels: Area-Compilers, New Feature - Async Streams

#59836 only include entry points defined in source
  src/VisualStudio/CSharp/Impl/ProjectSystemShim/EntryPointFinder.cs
  src/VisualStudio/VisualBasic/Impl/ProjectSystemShim/EntryPointFinder.vb
Labels: Area-IDE

#60162 Port encapsulate field tests to new harness
  src/Tools/Source/RunTests/ProcessTestExecutor.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpEncapsulateField.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicEncapsulateField.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpEncapsulateField.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/AutomationElementExtensions.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/DialogHelpers.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EncapsulateFieldInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/Helper.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/InputInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/PreviewChangesDialogInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/ShellInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/StateResetInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InfrastructureTests.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/Microsoft.VisualStudio.LanguageServices.New.IntegrationTests.csproj
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicEncapsulateField.cs
  src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/EncapsulateField_OutOfProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/PreviewChangesDialog_OutOfProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstance.cs
Labels: Area-IDE

#60186 Added aditional test to "ForeachToFor" refactoring
  src/EditorFeatures/CSharpTest/ConvertForEachToFor/ConvertForEachToForTests.cs
Labels: Area-IDE, Community

#60190 Add syntax normalizer tests for checked user-defined operators.
  src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs
Labels: Area-Compilers, New Feature - CheckedUserDefinedOperators

#60156 Handle more cases in F1 help service
  src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs
  src/VisualStudio/CSharp/Test/F1Help/F1HelpTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
Labels: Area-IDE, Community

#60152 Ensure declaring compilation can be located for source symbols created during compilation for EE evaluation.
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.PlaceholderLocal.cs
  src/Compilers/CSharp/Portable/Lowering/ClosureConversion/SynthesizedClosureMethod.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceLocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/SubstitutedTypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Symbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedLocal.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/TypeSubstitutedLocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/UpdatedContainingSymbolLocal.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Binders/EEMethodBinder.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EECompilationContextMethod.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EEMethodSymbol.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/DynamicTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/ExpressionCompilerTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/HoistedThisTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/LocalFunctionTests.cs
Labels: Area-Compilers

#60191 Add SyntacticClassifier and SemanticQuickInfo tests for checked user-defined operators.
  src/EditorFeatures/CSharpTest/Classification/SyntacticClassifierTests.cs
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
Labels: Area-Compilers, New Feature - CheckedUserDefinedOperators

#53045 Respect ReportSuppressedDiagnostics option for DiagnosticSuppressor
  src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticSuppressorTests.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs
  src/Compilers/Test/Core/Diagnostics/DiagnosticExtensions.cs
Labels: Area-Analyzers, Area-Compilers, Community

#60052 Validate with `-testUsedAssemblies` in a CI leg
  azure-pipelines.yml
  eng/build.ps1
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs
  src/Compilers/CSharp/Test/Emit/PDB/PDBUsingTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_ICoalesceOperation.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableContextTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs
  src/Tools/Source/RunTests/TestRunner.cs
Labels: Area-Compilers

#59763 Allow creating doc comments around existing comments
  src/EditorFeatures/CSharpTest/DocumentationComments/DocumentationCommentTests.cs
  src/EditorFeatures/TestUtilities/DocumentationComments/AbstractDocumentationCommentTests.cs
  src/EditorFeatures/VisualBasicTest/DocumentationComments/DocumentationCommentTests.vb
  src/Features/CSharp/Portable/DocumentationComments/CSharpDocumentationCommentSnippetService.cs
  src/Features/Core/Portable/DocumentationComments/AbstractDocumentationCommentSnippetService.cs
  src/Features/LanguageServer/ProtocolUnitTests/OnAutoInsert/OnAutoInsertTests.cs
  src/Features/VisualBasic/Portable/DocumentationComments/VisualBasicDocumentationCommentSnippetService.vb
Labels: Area-IDE

#60118 Update Roslyn.Diagnostics.Analyzers to 3.3.4-beta1.22160.2
  eng/Versions.props
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/TemporaryArray`1.cs
Labels: Area-Infrastructure

#60065 use 4.2 version of the compiler to build
  eng/Versions.props
Labels: Area-Infrastructure

#60198 Add auto-default feature status
  docs/Language Feature Status.md
Labels: Area-Compilers

#60093 Analyze flow in receiver of extension method group in delegate creation
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs
  src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs
Labels: Area-Compilers

#60193 Add SymbolMatcher tests for checked user-defined operators.
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/SymbolMatcherTests.cs
Labels: Area-Compilers, New Feature - CheckedUserDefinedOperators

#60217 Fix typo in OmniSharp ExternalAccess
  src/Tools/ExternalAccess/OmniSharp/InlineHints/OmniSharpInlineHintsService.cs
Labels: Area-Infrastructure

#60106 Initialize default capabilities before switching to the UI thread
  src/EditorFeatures/Core/LanguageServer/AbstractInProcLanguageClient.cs
  src/EditorFeatures/Core/LanguageServer/AlwaysActivateInProcLanguageClient.cs
  src/EditorFeatures/Core/LanguageServer/LiveShareInProcLanguageClient.cs
  src/EditorFeatures/Core/LanguageServer/RazorInProcLanguageClient.cs
  src/Features/LanguageServer/Protocol/DefaultCapabilitiesProvider.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageClient/XamlInProcLanguageClient.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageClient/XamlInProcLanguageClientDisableUX.cs
Labels: Area-IDE

#60196 Normalize values for `ROSLYN_TEST_*` in `TestRunner`
  src/Tools/Source/RunTests/TestRunner.cs
Labels: Area-Compilers

#60222 Add link to doc for VS insertion process
  docs/contributing/Building, Debugging, and Testing on Windows.md
Labels: Area-Compilers, Documentation

#59759 Initial implementation of a new 'lightweight' background-work-indicator that we can use in-situ in the editor.
  eng/Versions.props
  src/EditorFeatures/Core.Wpf/BackgroundWorkIndicator/BackgroundWorkIndicatorContext.cs
  src/EditorFeatures/Core.Wpf/BackgroundWorkIndicator/BackgroundWorkIndicatorScope.cs
  src/EditorFeatures/Core.Wpf/BackgroundWorkIndicator/WpfBackgroundWorkIndicatorFactory.cs
  src/EditorFeatures/Core/BackgroundWorkIndicator/DefaultBackgroundWorkIndicatorFactory.cs
  src/EditorFeatures/Core/BackgroundWorkIndicator/IBackgroundWorkIndicatorContext.cs
  src/EditorFeatures/Core/BackgroundWorkIndicator/IBackgroundWorkIndicatorFactory.cs
  src/EditorFeatures/Core/EditorFeaturesResources.resx
  src/EditorFeatures/Core/GoToDefinition/AbstractGoToDefinitionService.cs
  src/EditorFeatures/Core/GoToDefinition/GoToDefinitionCommandHandler.cs
  src/EditorFeatures/Core/GoToDefinition/GoToDefinitionHelpers.cs
  src/EditorFeatures/Core/Shared/Options/FeatureOnOffOptions.cs
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.cs.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.de.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.es.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.fr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.it.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ja.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ko.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pl.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pt-BR.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ru.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.tr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hans.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hant.xlf
  src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionCommandHandlerTests.vb
  src/EditorFeatures/TestUtilities/Utilities/TestUIThreadOperationContext.cs
  src/Features/Core/Portable/Navigation/IDocumentNavigationService.cs
  src/Features/Core/Portable/Navigation/INavigableLocation.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/CSharp/Impl/Options/AutomationObject/AutomationObject.OnOff.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageStrings.vb
  src/Workspaces/Core/Portable/Shared/TestHooks/FeatureAttribute.cs
Labels: Area-IDE

#60122 Use frozen partial semantics for syntax classification
  src/EditorFeatures/Core/Classification/Semantic/ClassificationUtilities.cs
  src/EditorFeatures/Core/Extensibility/NavigationBar/AbstractEditorNavigationBarItemService.cs
  src/EditorFeatures/Core/Extensibility/NavigationBar/INavigationBarItemService.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptNavigationBarItemService.cs
  src/EditorFeatures/Core/LanguageServer/Handlers/Symbols/DocumentSymbolsHandler.cs
  src/EditorFeatures/Core/NavigationBar/NavigationBarController_ModelComputation.cs
  src/EditorFeatures/Test2/NavigationBar/TestHelpers.vb
  src/Features/Core/Portable/NavigationBar/AbstractNavigationBarItemService.cs
  src/Features/Core/Portable/NavigationBar/INavigationBarItemService.cs
  src/Features/Core/Portable/NavigationBar/IRemoteNavigationBarItemService.cs
  src/Tools/ExternalAccess/FSharp/Internal/Editor/FSharpNavigationBarItemService.cs
  src/Workspaces/Core/Portable/Classification/ClassificationOptions.cs
  src/Workspaces/Remote/ServiceHub/Services/NavigationBar/RemoteNavigationBarItemService.cs
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassification/RemoteSemanticClassificationService.cs
Labels: Area-IDE

#60183 Adjust CheckedKeywordRecommender for checked user-defined operators.
  src/EditorFeatures/CSharpTest2/Recommendations/CheckedKeywordRecommenderTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/CheckedKeywordRecommender.cs
Labels: Area-IDE, New Feature - CheckedUserDefinedOperators

#59969 Fixed simple signature help bugs
  src/EditorFeatures/CSharpTest/SignatureHelp/InvocationExpressionSignatureHelpProviderTests.cs
  src/Features/CSharp/Portable/SignatureHelp/InvocationExpressionSignatureHelpProviderBase_MethodGroup.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpArgumentProvider.cs
Labels: Area-IDE, Community

#60101 Error when required members are not set
  src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/SymbolExtensions.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Symbol/Symbols/RequiredMembersTests.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
Labels: Area-Compilers, New Feature - Required Members

#60204 Inline hints: Double click to insert hint can overwrite buffer of previous inserted hint if done too quickly
  src/EditorFeatures/Core.Wpf/InlineHints/InlineHintsTag.cs
  src/EditorFeatures/Core.Wpf/InlineHints/InlineHintsTagger.cs
Labels: Area-IDE

#59963 Remove unused local
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_IncrementalAnalyzer.cs
Labels: Area-IDE
