Repository dotnet/roslyn, pull requests merged in 2022-12, with the labels that each got.

#65689 Simplify and clarify code around diagnostic modes.
  src/EditorFeatures/Core/Diagnostics/AbstractPushOrPullDiagnosticsTaggerProvider.PushDiagnosticsTaggerProvider.cs
  src/EditorFeatures/Core/Diagnostics/AbstractPushOrPullDiagnosticsTaggerProvider.SingleDiagnosticKindPullTaggerProvider.cs
  src/EditorFeatures/Core/Diagnostics/DiagnosticsClassificationTaggerProvider.cs
  src/EditorFeatures/Core/Diagnostics/DiagnosticsSquiggleTaggerProvider.cs
  src/EditorFeatures/Core/Diagnostics/DiagnosticsSuggestionTaggerProvider.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptDiagnosticService.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptInProcLanguageClient.cs
  src/EditorFeatures/Core/LanguageServer/AlwaysActivateInProcLanguageClient.cs
  src/EditorFeatures/Core/LanguageServer/LiveShareInProcLanguageClient.cs
  src/EditorFeatures/Test/Diagnostics/DiagnosticAnalyzerServiceTests.cs
  src/EditorFeatures/Test/Diagnostics/DiagnosticServiceTests.cs
  src/EditorFeatures/Test/Diagnostics/MockDiagnosticService.cs
  src/EditorFeatures/Test/EditAndContinue/RemoteEditAndContinueServiceTests.cs
  src/EditorFeatures/Test/Preview/PreviewWorkspaceTests.cs
  src/EditorFeatures/TestUtilities/Squiggles/TestDiagnosticTagProducer.cs
  src/Features/Core/Portable/Diagnostics/DiagnosticsUpdatedArgs.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DefaultDiagnosticAnalyzerService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DiagnosticAnalyzerService_IncrementalAnalyzer.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DiagnosticService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/IDiagnosticService.cs
  src/Features/LanguageServer/Protocol/Features/Options/DiagnosticModeExtensions.cs
  src/Features/LanguageServer/Protocol/Features/TaskList/TaskListListener.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/AbstractPullDiagnosticTestsBase.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/VSTypeScriptHandlerTests.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/Core/Def/TableDataSource/VisualStudioBaseDiagnosticListTable.LiveTableDataSource.cs
  src/VisualStudio/Core/Test/Diagnostics/DefaultDiagnosticUpdateSourceTests.vb
  src/VisualStudio/Core/Test/Diagnostics/DiagnosticTableDataSourceTests.vb
  src/VisualStudio/Core/Test/Diagnostics/ExternalDiagnosticUpdateSourceTests.vb
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioAnalyzerTests.vb
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioProjectTests/AnalyzerReferenceTests.vb
  src/Workspaces/Core/Portable/Diagnostics/DiagnosticMode.cs
Labels: Area-IDE

#65587 Move IDS_FeatureXXX checks out of the parser
  src/Compilers/CSharp/Portable/Binder/Binder_Lambda.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/Declarations/DeclarationTreeBuilder.cs
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ModifierUtils.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceConstructorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceDestructorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberFieldSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertyAccessorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbolBase.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxNodeExtensions.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ParserErrorMessageTests.cs
Labels: Area-Compilers

#65664 Cleanup keyword recommender tests
  src/EditorFeatures/CSharpTest2/Recommendations/ManagedKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/UnmanagedKeywordRecommenderTests.cs
Labels: Area-IDE, Community

#65701 Project system relayering
  src/VisualStudio/Core/Def/ProjectSystem/FileChangeWatcher.cs
  src/VisualStudio/Core/Def/ProjectSystem/FileChangeWatcherProvider.cs
  src/VisualStudio/Core/Def/ProjectSystem/RuleSets/VisualStudioRuleSetManager.RuleSetFile.cs
  src/VisualStudio/Core/Def/ProjectSystem/RuleSets/VisualStudioRuleSetManager.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioProject.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/FileWatchedPortableExecutableReferenceFactory.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/IFileChangeWatcher.cs
Labels: Area-IDE

#65698 Update Language Feature Status for Primary Constructors
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation

#65679 Move IDS_FeatureTuples checks out of the parser.
  src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenExprLambdaTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ParserErrorMessageTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ParsingErrorRecoveryTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/SeparatedSyntaxListParsingTests.cs
  src/EditorFeatures/CSharpTest/CodeActions/InlineTemporary/InlineTemporaryTests.cs
Labels: Area-Compilers

#65705 Switch from HostWorkspaceServices to SolutionServices
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/FileWatchedPortableExecutableReferenceFactory.cs
Labels: Area-IDE

#65709 Switch to having the IFileChangeWatcher return IDisposable tokens
  src/VisualStudio/Core/Def/ProjectSystem/FileChangeWatcher.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioProject.BatchingDocumentCollection.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioProject.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/FileWatchedPortableExecutableReferenceFactory.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/IFileChangeWatcher.cs
Labels: Area-IDE

#65706 Turn on NRT for the parser.
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxFactory.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs
  src/Compilers/Core/Portable/Syntax/InternalSyntax/SyntaxListBuilder`1.cs
  src/VisualStudio/CSharp/Impl/CodeModel/CSharpCodeModelService.cs
Labels: Area-Compilers

#65715 Remove unused constructor
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/ValuesSources/WeaklyCachedRecoverableValueSource.cs
Labels: Area-IDE

#65571 Fix stale inline diagnostics
  src/EditorFeatures/Core.Wpf/Adornments/AbstractAdornmentManager.cs
  src/EditorFeatures/Core.Wpf/InlineDiagnostics/InlineDiagnosticsAdornmentManager.cs
  src/EditorFeatures/Core.Wpf/InlineDiagnostics/InlineDiagnosticsTag.cs
  src/EditorFeatures/Core.Wpf/LineSeparators/LineSeparatorAdornmentManager.cs
  src/EditorFeatures/Core.Wpf/StringIndentation/StringIndentationAdornmentManager.cs
Labels: Area-IDE

#65716 Delete unnecessary code that was for recoverable trees
  src/Workspaces/Core/Portable/Workspace/Solution/DocumentState.cs
Labels: Area-IDE

#65712 editorconfig UI accessibility bugs
  src/EditorFeatures/Core/EditorConfigSettings/Updater/NamingStyles/NamingStyleSettingsUpdater.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/Analyzers/View/ColumnDefinitions/AnalyzerCategoryColumnDefinition.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/CodeStyle/View/ColumnDefinitions/CodeStyleCategoryColumnDefinition.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/Common/SettingsViewModelBase.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/NamingStyle/View/ColumnDefinitions/NamingStylesLocationColumnDefinition.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/NamingStyle/View/ColumnDefinitions/NamingStylesSeverityColumnDefinition.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/NamingStyle/View/ColumnDefinitions/NamingStylesStyleColumnDefinition.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/NamingStyle/View/ColumnDefinitions/NamingStylesTypeColumnDefinition.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/SettingsEditorControl.xaml
  src/VisualStudio/Core/Def/EditorConfigSettings/Styles/TabControlStyles.xaml
  src/VisualStudio/Core/Def/EditorConfigSettings/Whitespace/View/ColumnDefnitions/WhitespaceCategoryColumnDefinition.cs
Labels: Area-IDE

#65702 Introduce simpler pattern for managing reset points in the parser.
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs
Labels: Area-Compilers

#65726 Move CSharpTyping test to new framework
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpTyping.cs
Labels: Area-IDE

#65710 Move IDS_FeatureRefLocalsReturns out of the parser
  src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Lambda.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/ForLoopBinder.cs
  src/Compilers/CSharp/Portable/BoundTree/VariablePendingInference.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/Symbols/Source/GlobalExpressionVariable.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceDelegateMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceLocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberFieldSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxFacts.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxNodeExtensions.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenRefReturnTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers

#65745 Remove redundant null check
  src/Features/Core/Portable/MoveStaticMembers/AbstractMoveStaticMembersRefactoringProvider.cs
Labels: Area-IDE, Community

#65737 Move repo to newer version of Public Api analyzers
  NuGet.config
  eng/Versions.props
  src/Compilers/CSharp/Portable/PublicAPI.Shipped.txt
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/Core/Desktop/PublicAPI.Unshipped.txt
  src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/IFileChangeWatcher.cs
  src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb
Labels: Area-Analyzers

#65018 Add "Make type partial" codefix
  src/Analyzers/CSharp/CodeFixes/CSharpCodeFixes.projitems
  src/Analyzers/CSharp/CodeFixes/MakeTypePartial/CSharpMakeTypePartialCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/CSharpAnalyzers.UnitTests.projitems
  src/Analyzers/CSharp/Tests/MakeTypePartial/MakeTypePartialTests.cs
  src/Analyzers/Core/CodeFixes/CodeFixes.projitems
  src/Analyzers/Core/CodeFixes/CodeFixesResources.resx
  src/Analyzers/Core/CodeFixes/MakeTypePartial/AbstractMakeTypePartialCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/PredefinedCodeFixProviderNames.cs
  src/Analyzers/Core/CodeFixes/xlf/CodeFixesResources.cs.xlf
  src/Analyzers/Core/CodeFixes/xlf/CodeFixesResources.de.xlf
  src/Analyzers/Core/CodeFixes/xlf/CodeFixesResources.es.xlf
  src/Analyzers/Core/CodeFixes/xlf/CodeFixesResources.fr.xlf
  src/Analyzers/Core/CodeFixes/xlf/CodeFixesResources.it.xlf
  src/Analyzers/Core/CodeFixes/xlf/CodeFixesResources.ja.xlf
  src/Analyzers/Core/CodeFixes/xlf/CodeFixesResources.ko.xlf
  src/Analyzers/Core/CodeFixes/xlf/CodeFixesResources.pl.xlf
  src/Analyzers/Core/CodeFixes/xlf/CodeFixesResources.pt-BR.xlf
  src/Analyzers/Core/CodeFixes/xlf/CodeFixesResources.ru.xlf
  src/Analyzers/Core/CodeFixes/xlf/CodeFixesResources.tr.xlf
  src/Analyzers/Core/CodeFixes/xlf/CodeFixesResources.zh-Hans.xlf
  src/Analyzers/Core/CodeFixes/xlf/CodeFixesResources.zh-Hant.xlf
  src/Analyzers/VisualBasic/CodeFixes/MakeTypePartial/VisualBasicMakeTypePartialCodeFixProvider.vb
  src/Analyzers/VisualBasic/CodeFixes/VisualBasicCodeFixes.projitems
  src/Analyzers/VisualBasic/Tests/MakeTypePartial/MakeTypePartialTests.vb
  src/Analyzers/VisualBasic/Tests/VisualBasicAnalyzers.UnitTests.projitems
  src/Compilers/Test/Core/Traits/Traits.cs
Labels: Area-IDE, Community

#62242 Rules missing documentation
  Roslyn.sln
  azure-pipelines.yml
  eng/validate-rules-missing-documentation.cmd
  eng/validate-rules-missing-documentation.ps1
  src/Analyzers/Core/Analyzers/Analyzers.projitems
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/Features/RulesMissingDocumentation.md
  src/Tools/GenerateRulesMissingDocumentation/GenerateRulesMissingDocumentation.csproj
  src/Tools/GenerateRulesMissingDocumentation/Program.cs
Labels: Area-Infrastructure, Community

#65606 Display standalone parameter names by default
  src/Compilers/CSharp/Portable/Binder/Binder.WithQueryLambdaParametersBinder.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Members.cs
  src/Compilers/CSharp/Portable/Symbols/SymbolDistinguisher.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IInterpolatedStringOperation.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RawInterpolationTests_Handler.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/CSharpCompilerFeatureRequiredTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs
  src/Compilers/Core/Portable/SymbolDisplay/SymbolDisplayCompilerInternalOptions.cs
  src/Compilers/Core/Portable/SymbolDisplay/SymbolDisplayFormat.cs
  src/EditorFeatures/CSharpTest/ConvertTupleToStruct/ConvertTupleToStructTests.cs
Labels: Area-Compilers

#65579 Consider delegate default parameter values and `params` in symbol matcher
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/CSharpSymbolMatcher.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/SymbolMatcherTests.cs
Labels: Area-Compilers

#65732 Fix potential race where we're expecting a moniker to be attached
  src/Features/Core/Portable/LanguageServiceIndexFormat/SymbolMoniker.cs
  src/Features/Lsif/Generator/Generator.cs
  src/Features/Lsif/Generator/Graph/HoverResult.cs
  src/Features/Lsif/Generator/ResultSetTracking/DelegatingResultSetTracker.cs
  src/Features/Lsif/Generator/ResultSetTracking/IResultSetTracker.cs
  src/Features/Lsif/Generator/ResultSetTracking/IResultSetTrackerExtensions.cs
  src/Features/Lsif/Generator/ResultSetTracking/SymbolHoldingResultSetTracker.cs
Labels: Area-IDE

#65743 Remove "Top Level statement attribute" from language feature status
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation, Community

#64892 Revert "Revert "Read required project properties from evaluation data""
  eng/build.ps1
  src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets
  src/Compilers/Core/MSBuildTask/Microsoft.VisualBasic.Core.targets
  src/Tools/ExternalAccess/FSharp/VS/IFSharpWorkspaceProjectContextFactory.cs
  src/VisualStudio/CSharp/Test/ProjectSystemShim/CSharpHelpers.cs
  src/VisualStudio/CSharp/Test/ProjectSystemShim/TestEvaluationData.cs
  src/VisualStudio/Core/Def/ProjectSystem/BuildPropertyNames.cs
  src/VisualStudio/Core/Def/ProjectSystem/CPS/IWorkspaceProjectContextFactory.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProjectFactory.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs
Labels: Area-IDE

#61414 Use RuntimeHelpers.CreateSpan for array initialization with relevant primitives
  src/Compilers/CSharp/Portable/CodeGen/EmitArrayInitializer.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitConversion.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitStackAllocInitializer.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenReadOnlySpanConstructionTest.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RawInterpolationTests_Handler.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/Portable/CodeGen/ILBuilderEmit.cs
  src/Compilers/Core/Portable/CodeGen/ITokenDeferral.cs
  src/Compilers/Core/Portable/CodeGen/PrivateImplementationDetails.cs
  src/Compilers/Core/Portable/Emit/CommonPEModuleBuilder.cs
  src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/Test/Core/CompilationVerifier.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
  src/Compilers/VisualBasic/Portable/CodeGen/EmitArrayInitializer.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
Labels: Area-Compilers

#65729 Add fixer to offer to use `nameof(parameter)` in attributes now that the language allows that.
  src/Analyzers/CSharp/Analyzers/CSharpAnalyzers.projitems
  src/Analyzers/CSharp/Analyzers/CSharpAnalyzersResources.resx
  src/Analyzers/CSharp/Analyzers/UseNameofInNullableAttribute/CSharpUseNameofInNullableAttributeDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.cs.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.de.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.es.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.fr.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.it.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.ja.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.ko.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.pl.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.pt-BR.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.ru.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.tr.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.zh-Hans.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.zh-Hant.xlf
  src/Analyzers/CSharp/CodeFixes/CSharpCodeFixes.projitems
  src/Analyzers/CSharp/CodeFixes/UseNameofInAttribute/CSharpUseNameofInAttributeCodeFixProvider.cs
  src/Analyzers/Core/Analyzers/EnforceOnBuildValues.cs
  src/Analyzers/Core/Analyzers/IDEDiagnosticIds.cs
  src/Analyzers/Core/CodeFixes/PredefinedCodeFixProviderNames.cs
  src/EditorFeatures/CSharpTest/Formatting/CodeCleanupTests.cs
  src/EditorFeatures/CSharpTest/UseNameofInAttribute/UseNameofInAttributeTests.cs
  src/EditorFeatures/Test/Diagnostics/IDEDiagnosticIDConfigurationTests.cs
Labels: Area-IDE

#65725 Unskip quick info tests
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpQuickInfo.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpQuickInfo.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicQuickInfo.cs
Labels: Area-IDE

#65789 Fix correctness build
  src/Features/RulesMissingDocumentation.md
Labels: Area-IDE

#65642 Ensure proper receiver value is used for a constrained call invocation
  src/Compilers/CSharp/Portable/BoundTree/BoundExpressionExtensions.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs
  src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.PlaceholderLocal.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DeconstructionAssignmentOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_FunctionPointerInvocation.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_NullCoalescingAssignmentOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectCreationExpression.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_UnaryOperator.cs
  src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Portable/Symbols/LocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceLocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/InterpolatedStringBuilderLocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedLocal.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/TypeSubstitutedLocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/UpdatedContainingSymbolLocal.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOperators.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs
  src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenCallTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/GenericConstraintTests.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EEDisplayClassFieldLocalSymbol.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EELocalConstantSymbol.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EELocalSymbol.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/PlaceholderLocalSymbol.cs
Labels: Area-Compilers

#65720 Implement parsing changes for Primary Constructors feature
  src/Compilers/CSharp/Portable/Generated/CSharp.Generated.g4
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Internal.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Main.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Syntax.Generated.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Syntax/ClassDeclarationSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/StructDeclarationSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
  src/Compilers/CSharp/Portable/Syntax/SyntaxFactory.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/RecordTests.cs
  src/Compilers/CSharp/Test/Syntax/Generated/Syntax.Test.xml.Generated.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationScopeParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/RecordParsing.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/TopLevelStatementsParsingTests.cs
Labels: Area-Compilers, New Feature - Primary Constructors

#65708 Move to using ToListAndFree in more places in the parser.
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/Syntax/InternalSyntax/SyntaxListPoolExtensions.cs
  src/Compilers/Core/Portable/Syntax/InternalSyntax/SyntaxListPool.cs
Labels: Area-Compilers

#65782 Remove unused methods
  src/Workspaces/CSharp/Portable/Workspace/LanguageServices/CSharpSyntaxTreeFactoryService.cs
  src/Workspaces/Core/Portable/Workspace/Host/SyntaxTreeFactory/AbstractSyntaxTreeFactoryService.cs
  src/Workspaces/Core/Portable/Workspace/Host/SyntaxTreeFactory/ISyntaxTreeFactoryService.cs
  src/Workspaces/VisualBasic/Portable/Workspace/LanguageServices/VisualBasicSyntaxTreeFactoryService.vb
Labels: Area-IDE

#65675 [LSP] Find refs - Remove bogus assert and add test
  src/EditorFeatures/Test/Options/GlobalOptionsTests.cs
  src/EditorFeatures/TestUtilities/EditorTestCompositions.cs
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/LanguageServer/Protocol/Handler/References/FindAllReferencesHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/DocumentChanges/DocumentChangesTests.WithFindAllReferences.cs
  src/Features/LanguageServer/ProtocolUnitTests/References/FindAllReferencesHandlerFeaturesTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/References/FindAllReferencesHandlerTests.cs
  src/VisualStudio/CSharp/Test/DocumentOutline/DocumentOutlineTestsBase.cs
Labels: Area-IDE, LSP

#65785 Remove unused method
  src/Analyzers/Core/Analyzers/Analyzers.projitems
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
Labels: Area-IDE

#65799 Extract a few more interfaces from the VS layer project system
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DocumentAnalysisExecutor_Helpers.cs
  src/VisualStudio/Core/Def/Diagnostics/VisualStudioDiagnosticAnalyzerProvider.cs
  src/VisualStudio/Core/Def/LanguageService/AbstractLanguageService`2.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioAnalyzer.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioProject.cs
  src/VisualStudio/Core/Def/TaskList/HostDiagnosticUpdateSource.cs
  src/VisualStudio/VisualBasic/Impl/LanguageService/VisualBasicPackage.IVbCompiler.vb
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/FileWatchedPortableExecutableReferenceFactory.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/IHostDiagnosticAnalyzerProvider.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/IProjectSystemDiagnosticSource.cs
Labels: Area-IDE

#65813 Link compiler analysis scope to solution-specific override
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DocumentAnalysisExecutor_Helpers.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_IncrementalAnalyzer.cs
  src/Features/LanguageServer/Protocol/Features/Options/SolutionCrawlerOptionsStorage.cs
Labels: Area-IDE

#65791 Make main-vs-deps PRs non-draft
  eng/config/PublishData.json
Labels: Area-Infrastructure

#65817 Skip tests on 32bit debug due to messagepack issue
  src/Compilers/Test/Core/Assert/ConditionalFactAttribute.cs
  src/EditorFeatures/CSharpTest/FullyQualify/FullyQualifyTests.cs
  src/EditorFeatures/VisualBasicTest/Diagnostics/FullyQualify/FullyQualifyTests.vb
Labels: Area-IDE

#65820 Ensure we recompute top level semantic versions, even when making frozen documents
  src/Workspaces/Core/Portable/SemanticModelReuse/AbstractSemanticModelReuseLanguageService.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-IDE

#65723 Cleanup unused generated code
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Internal.Generated.cs
  src/Compilers/VisualBasic/Portable/Generated/Syntax.xml.Internal.Generated.vb
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/SourceWriter.cs
  src/Tools/Source/CompilerGeneratorTools/Source/VisualBasicSyntaxGenerator/GreenNodes/GreenNodeFactoryWriter.vb
Labels: Area-Compilers, Community

#65717 Simplify WeaklyCachedRecoverableValueSource
  src/Workspaces/Core/Portable/Shared/TestHooks/TaskExtensions.cs
  src/Workspaces/Core/Portable/Workspace/Solution/RecoverableTextAndVersion.cs
  src/Workspaces/Core/Portable/Workspace/Solution/WeaklyCachedRecoverableValueSource.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/AddImport/AddImportPlacementOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeCleanup/CodeCleanupOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeGeneration/CleanCodeGenerationOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeGeneration/CodeGenerationOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/IdeCodeStyleOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Diagnostics/IdeAnalyzerOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/SyntaxFormattingOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Indentation/IndentationOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyleOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/TestHooks/TaskExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/ValuesSources/WeaklyCachedRecoverableValueSource.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Indentation/VisualBasicSmartTokenFormatter.vb
Labels: Area-IDE

#65748 Adding support for positional patterns to GenerateDeconstructMethodFixProvider.cs
  src/Compilers/Core/Portable/InternalUtilities/EnumerableExtensions.cs
  src/EditorFeatures/CSharpTest/Diagnostics/GenerateMethod/GenerateDeconstructMethodTests.cs
  src/Features/CSharp/Portable/CodeFixes/GenerateMethod/GenerateDeconstructMethodCodeFixProvider.cs
  src/Features/CSharp/Portable/GenerateMember/GenerateParameterizedMember/CSharpGenerateDeconstructMethodService.cs
  src/Features/Core/Portable/GenerateMember/GenerateParameterizedMember/AbstractGenerateDeconstructMethodService.State.cs
  src/Features/Core/Portable/GenerateMember/GenerateParameterizedMember/AbstractGenerateDeconstructMethodService.cs
Labels: Area-IDE, Community

#65821 Add 17.6 branch to config
  eng/config/PublishData.json
Labels: Area-Infrastructure

#65742 Remove dotnet5 feed
  NuGet.config
  eng/Versions.props
Labels: Area-Infrastructure, Community

#65781 Port "Incremental generator nodes must run when no result history" to 17.4
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/StateTableTests.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/BatchNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/CombineNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/DriverStateTable.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/IIncrementalGeneratorNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/InputNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SourceOutputNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/StateTableStore.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxInputNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxReceiverStrategy.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/TransformNode.cs
Labels: Area-Compilers

#65783 Force arrow cursor for inline rename flayout
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml.cs
Labels: Area-IDE, Community

#65730 Create DkmCustomUIVisualizerInfo instances with ExtensionPartId field
  eng/Versions.props
  src/ExpressionEvaluator/CSharp/Test/ResultProvider/DebuggerVisualizerAttributeTests.cs
  src/ExpressionEvaluator/Core/Source/ResultProvider/Helpers/TypeHelpers.cs
  src/ExpressionEvaluator/Core/Test/ResultProvider/Debugger/Engine/DkmClrDebuggerVisualizerAttribute.cs
  src/ExpressionEvaluator/Core/Test/ResultProvider/Debugger/Engine/DkmClrType.cs
  src/ExpressionEvaluator/Core/Test/ResultProvider/Debugger/Engine/DkmCustomUIVisualizerInfo.cs
  src/ExpressionEvaluator/Core/Test/ResultProvider/ResultProviderTestBase.cs
Labels: Area-Interactive, Community

#65846 Switch to non-preview queue to use 17.4.1 instead of 17.4 Preview 5
  azure-pipelines-integration.yml
Labels: Area-Infrastructure

#65856 Change to release/dev17.6-vs-deps
  eng/config/PublishData.json
Labels: Area-Infrastructure

#59735 Classify pattern variables
  src/EditorFeatures/CSharpTest/Classification/SyntacticClassifierTests.cs
  src/EditorFeatures/CSharpTest/Classification/TotalClassifierTests.cs
  src/Workspaces/CSharp/Portable/Classification/ClassificationHelpers.cs
Labels: Area-IDE, Community

#65838 Fix Regex features in raw-string-literals.
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_Regex.vb
  src/EditorFeatures/Test2/ReferenceHighlighting/CSharpReferenceHighlightingTests.vb
  src/Features/CSharp/Portable/EmbeddedLanguages/EmbeddedLanguageUtilities.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/EmbeddedLanguages/VirtualChars/VirtualCharSequence.Chunks.cs
Labels: Area-IDE

#65847 Add ExecuteCommandAsync overloads which accept arguments
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/ShellInProcess.cs
Labels: Area-IDE

#65516 Cleanup `SyntaxNormalizerTests`
  src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs
Labels: Area-Compilers, Test, Community

#65832 Avoid emitting redundant locals in deconstruction assignment
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DeconstructionAssignmentOperator.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenDeconstructTests.cs
  src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenCallTests.cs
Labels: Area-Compilers, Community

#65724 Move to more consistent patterns in the parser.
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs
Labels: Area-Compilers

#65805 Ensure lvalue struct receivers are not copied by value by implicit Range indexer rewrite
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs
  src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenCallTests.cs
Labels: Area-Compilers

#65688 Disable document outline
  src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineOptionsMetadata.cs
  src/VisualStudio/Core/Def/LanguageService/AbstractLanguageService`2.VsCodeWindowManager.cs
Labels: Area-IDE, OnDeckForServicing

#65887 Move Generate from usage tests to new framework
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpRenameFileToMatchTypeRefactoring.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicGenerateFromUsage.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpGenerateFromUsage.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicGenerateFromUsage.cs
Labels: Area-IDE, Area-Infrastructure

#65734 Move classification tests to new framework
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpClassification.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicClassification.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpClassification.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicClassification.cs
Labels: Area-IDE

#65898 Fix XAML LSP by using a queue provider instead of subclassing
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptRequestExecutionQueueProvider.cs
  src/Features/LanguageServer/Protocol/IRequestExecutionQueueProvider.cs
  src/Features/LanguageServer/Protocol/RequestExecutionQueueProvider.cs
  src/Features/LanguageServer/Protocol/RoslynLanguageServer.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageClient/XamlInProcLanguageClient.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/XamlRequestExecutionQueueProvider.cs
Labels: Area-IDE, LSP

#65823 Log ServiceHub process exit code on failure
  src/Workspaces/Core/Portable/Telemetry/IRemoteProcessTelemetryService.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemostHostClient.cs
  src/Workspaces/Remote/Core/BrokeredServiceConnection.cs
  src/Workspaces/Remote/Core/ServiceHubRemoteHostClient.cs
  src/Workspaces/Remote/ServiceHub/Services/ProcessTelemetry/RemoteProcessTelemetryService.cs
Labels: Area-IDE

#65896 (main) disable document outline by default
  src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineOptionsMetadata.cs
  src/VisualStudio/Core/Def/LanguageService/AbstractLanguageService`2.VsCodeWindowManager.cs
Labels: Area-IDE

#61879 Add FixAll in Solution support for Enable nullable refactoring
  src/EditorFeatures/CSharpTest/CodeActions/EnableNullable/EnableNullableFixAllTests.cs
  src/Features/CSharp/Portable/CSharpFeaturesResources.resx
  src/Features/CSharp/Portable/CodeRefactorings/EnableNullable/EnableNullableCodeRefactoringProvider.FixAllProvider.cs
  src/Features/CSharp/Portable/CodeRefactorings/EnableNullable/EnableNullableCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.cs.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.de.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.es.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.fr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.it.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ja.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ko.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pl.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pt-BR.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ru.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.tr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hans.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hant.xlf
Labels: Area-Analyzers

#65890 Relayer our project system
  src/VisualStudio/CSharp/Impl/ProjectSystemShim/CSharpProjectShim.ICSInputSet.cs
  src/VisualStudio/CSharp/Impl/ProjectSystemShim/CSharpProjectShim.ICSharpProjectSite.cs
  src/VisualStudio/CSharp/Impl/ProjectSystemShim/CSharpProjectShim.ICSharpVenusProjectSite.cs
  src/VisualStudio/CSharp/Impl/ProjectSystemShim/CSharpProjectShim.OptionsProcessor.cs
  src/VisualStudio/CSharp/Impl/ProjectSystemShim/CSharpProjectShim.cs
  src/VisualStudio/CSharp/Test/ProjectSystemShim/LegacyProject/CSharpCompilerOptionsTests.cs
  src/VisualStudio/Core/Def/ExternalAccess/VSTypeScript/Api/VSTypeScriptVisualStudioProjectWrapper.cs
  src/VisualStudio/Core/Def/LanguageService/AbstractLanguageService`2.IVsContainedLanguageFactory.cs
  src/VisualStudio/Core/Def/LanguageService/AbstractLanguageService`2.cs
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/VisualStudio/Core/Def/ProjectSystem/AbstractProject.cs
  src/VisualStudio/Core/Def/ProjectSystem/Legacy/AbstractLegacyProject.cs
  src/VisualStudio/Core/Def/ProjectSystem/Legacy/AbstractLegacyProject_IAnalyzerConfigFileHost.cs
  src/VisualStudio/Core/Def/ProjectSystem/Legacy/AbstractLegacyProject_IAnalyzerHost.cs
  src/VisualStudio/Core/Def/ProjectSystem/Legacy/AbstractLegacyProject_IProjectSiteEx.cs
  src/VisualStudio/Core/Def/ProjectSystem/Legacy/AbstractLegacyProject_IVsHierarchyEvents.cs
  src/VisualStudio/Core/Def/ProjectSystem/Legacy/SolutionEventsBatchScopeCreator.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioProjectCreationInfo.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioProjectFactory.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioProjectOptionsProcessor.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.OpenFileTracker.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.SolutionAnalyzerSetterService.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/Core/Def/TaskList/HostDiagnosticUpdateSource.cs
  src/VisualStudio/Core/Def/Venus/ContainedDocument.cs
  src/VisualStudio/Core/Def/Venus/ContainedLanguage.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IProjectCodeModelProvider.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualBasicCompilerOptionsTests.vb
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioAnalyzerTests.vb
  src/VisualStudio/VisualBasic/Impl/LanguageService/VisualBasicLanguageService.vb
  src/VisualStudio/VisualBasic/Impl/ProjectSystemShim/VisualBasicCodeModelInstanceFactory.vb
  src/VisualStudio/VisualBasic/Impl/ProjectSystemShim/VisualBasicProject.OptionsProcessor.vb
  src/VisualStudio/VisualBasic/Impl/ProjectSystemShim/VisualBasicProject.vb
  src/VisualStudio/VisualBasic/Impl/Venus/VisualBasicContainedLanguage.vb
  src/VisualStudio/Xaml/Impl/Implementation/XamlProjectService.cs
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/IProjectSystemDiagnosticSource.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.BatchingDocumentCollection.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectCreationInfo.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectFactory.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectHostInfo.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/Readme.md
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/SolutionChangeAccumulator.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/VisualStudioAnalyzer.cs
  src/Workspaces/Core/Portable/Workspace/Workspace_Editor.cs
Labels: Area-IDE

#65818 Fix inline rename in MAUI
  src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-IDE

#65839 Upgrade to .net 7 release version
  global.json
Labels: Area-Infrastructure

#65450 Minor cleanup in OptionStore
  src/VisualStudio/CSharp/Impl/Options/Formatting/SpacingViewModel.cs
  src/VisualStudio/CSharp/Test/Options/OptionViewModelTests.cs
  src/VisualStudio/Core/Impl/Options/AbstractOptionPage.cs
  src/VisualStudio/Core/Impl/Options/OptionStore.cs
Labels: Area-IDE, Community

#65922 Move `CSharpMakeStatementAsynchronousCodeFixTests` to `VerifyCS`
  src/Analyzers/CSharp/CodeFixes/MakeStatementAsynchronous/CSharpMakeStatementAsynchronousCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/MakeStatementAsynchronous/CSharpMakeStatementAsynchronousCodeFixTests.cs
Labels: Area-IDE, Community

#65582 Allow optional and `params` parameters in synthesized delegate templates
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/CSharpSymbolMatcher.cs
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/EmitHelpers.cs
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/PEDeltaAssemblyBuilder.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeManager.Templates.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.DelegateTemplateSymbol.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenExprLambdaTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/SymbolMatcherTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/DeltaMetadataWriter.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/EmitBaseline.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/IPEDeltaAssemblyBuilder.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/SymbolMatcher.cs
  src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/PEDeltaAssemblyBuilder.vb
Labels: Area-Compilers

#65430 Fix wrong symbol comparisons
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs
  src/Compilers/CSharp/Portable/DocumentationComments/DocumentationCommentIDVisitor.PartVisitor.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs
  src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentIDTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/ClsComplianceTests.cs
Labels: Area-Compilers, Community

#65928 Fix embedded language classificatino in Find-Refs results.
  src/Compilers/Core/Portable/Text/TextSpan.cs
  src/EditorFeatures/Test2/Classification/ClassificationTests.vb
  src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/SemanticTokensRangeTests.cs
  src/Workspaces/Core/Portable/Classification/ClassifiedSpan.cs
  src/Workspaces/Core/Portable/Classification/ClassifiedSpanIntervalIntrospector.cs
  src/Workspaces/Core/Portable/Classification/ClassifierHelper.cs
Labels: Area-IDE

#65941 Skip OverflowOnFluentCall on 32bit debug CI runs
  src/Compilers/CSharp/Test/EndToEnd/EndToEndTests.cs
Labels: Area-Compilers

#65842 Remove code for cloning compilations for skeleton references
  src/Features/LanguageServer/Protocol/Features/Options/WorkspaceConfigurationOptionsStorage.cs
  src/Workspaces/Core/Portable/Workspace/IWorkspaceConfigurationService.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.SkeletonReferenceCache.cs
Labels: Area-IDE

#65943 Merge main into features/SharedSyntaxTrees
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitArrayInitializer.cs
  src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs
  src/Compilers/CSharp/Portable/DocumentationComments/DocumentationCommentIDVisitor.PartVisitor.cs
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/CSharpSymbolMatcher.cs
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/EmitHelpers.cs
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/PEDeltaAssemblyBuilder.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeManager.Templates.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.DelegateTemplateSymbol.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenExprLambdaTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenReadOnlySpanConstructionTest.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/SymbolMatcherTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs
  src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentIDTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/ClsComplianceTests.cs
  src/Compilers/Core/Portable/CodeGen/ILBuilderEmit.cs
  src/Compilers/Core/Portable/CodeGen/PrivateImplementationDetails.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/DeltaMetadataWriter.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/EmitBaseline.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/IPEDeltaAssemblyBuilder.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/SymbolMatcher.cs
  src/Compilers/VisualBasic/Portable/CodeGen/EmitArrayInitializer.vb
  src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/PEDeltaAssemblyBuilder.vb
Labels: Area-Compilers

#65929 Avoid inlining ILanguageClientBroker initialization
  src/EditorFeatures/Core/LanguageServer/AlwaysActiveLanguageClientEventListener.cs
Labels: Area-IDE

#65875 Pass cancellation token consistently through lsif generator.
  src/EditorFeatures/Core/Classification/Syntactic/SyntacticClassificationTaggerProvider.TagComputer.cs
  src/Features/Lsif/Generator/.editorconfig
  src/Features/Lsif/Generator/Generator.cs
  src/Features/Lsif/Generator/Program.cs
  src/Features/Lsif/GeneratorTest/Utilities/TestLsifOutput.vb
  src/Workspaces/Core/Portable/Classification/Classifier.cs
Labels: Area-IDE

#65178 Semantic Snippets - else snippet
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpElseSnippetCompletionProviderTests.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/SnippetCompletionProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpElseSnippetProvider.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractConditionalBlockSnippetProvider.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractConsoleSnippetProvider.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractElseSnippetProvider.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractForEachLoopSnippetProvider.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractStatementSnippetProvider.cs
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFactsExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxKinds.vb
Labels: Area-IDE

#65944 Simplify how semantic-tokens works with text tokens
  src/EditorFeatures/Core/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs
  src/EditorFeatures/Test2/Classification/ClassificationTests.vb
  src/Features/Core/Portable/ClassifiedSpansAndHighlightSpanFactory.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHelpers.cs
  src/VisualStudio/Core/Def/Venus/ContainedDocument.DocumentServiceProvider.cs
  src/Workspaces/Core/Portable/Classification/ClassifierHelper.cs
Labels: Area-IDE

#65950 Switch some code from HostWorkspaceServices to SolutionServices
  src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.Worker.cs
  src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.Worker_ResolveReferences.cs
  src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.cs
  src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs
  src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/ProjectFileLoader.cs
  src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/ProjectFileLoaderRegistry.cs
  src/Workspaces/Core/Portable/Workspace/Host/SolutionServices.cs
Labels: Area-IDE

#65794 Add new API to easily tell if a node contains conditional directives (without allocations).
  src/Compilers/CSharp/Portable/CSharpExtensions.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNodeTests.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Core/Portable/Syntax/SyntaxNode.cs
  src/Compilers/VisualBasic/Portable/PublicAPI.Unshipped.txt
  src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb
  src/Compilers/VisualBasic/Test/Syntax/TestSyntaxNodes.vb
Labels: Area-Compilers

#65966 Delete duplicate test
  src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs
Labels: Area-Compilers, Community

#65947 Use newer msbuild versions
  global.json
Labels: Area-Infrastructure

#65889 Move BasicBuild to new integration test framework and implement
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicBuild.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicEditAndContinue.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicExpressionEvaluator.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicBuild.cs
Labels: Area-IDE, Area-Infrastructure

#65957 Service broker interface changes
  src/VisualStudio/Core/Def/ProjectSystem/BrokeredService/WorkspaceProject.cs
  src/Workspaces/Remote/Core/ProjectSystem/IWorkspaceProject.cs
Labels: Area-IDE

#65981 Localize 17.5 shipping branch
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#65860 Add support for draft of semantic tokens LSIF spec to LSIF generator
  src/Features/Lsif/Generator/Generator.cs
  src/Features/Lsif/Generator/Graph/Capabilities.cs
  src/Features/Lsif/Generator/Graph/SemanticTokensCapabilities.cs
  src/Features/Lsif/Generator/Graph/SemanticTokensResult.cs
  src/Features/Lsif/GeneratorTest/OutputFormatTests.vb
  src/Features/Lsif/GeneratorTest/SemanticTokensTests.vb
  src/Features/Lsif/GeneratorTest/Utilities/TestLsifOutput.vb
Labels: Area-IDE, Community

#65897 Remove a bunch of compatibility shims for TypeScript
  src/Tools/ExternalAccess/FSharp/InternalAPI.Unshipped.txt
  src/Tools/ExternalAccess/FSharp/LanguageServices/FSharpVisualStudioWorkspaceExtensions.cs
  src/VisualStudio/Core/Def/ExternalAccess/VSTypeScript/Api/VSTypeScriptContainedDocumentWrapper.cs
  src/VisualStudio/Core/Def/ProjectSystem/AbstractProject.cs
  src/VisualStudio/Core/Def/ProjectSystem/DocumentProvider.cs
  src/VisualStudio/Core/Def/ProjectSystem/IVisualStudioHostDocument.cs
  src/VisualStudio/Core/Def/ProjectSystem/IVisualStudioHostProject.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioProjectTracker.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/Core/Def/Venus/AbstractContainedLanguage.cs
  src/VisualStudio/Core/Def/Venus/ContainedDocument.cs
Labels: Area-IDE

#65974 Improve sharing of trees when changing project configuration
  src/Workspaces/Core/Portable/Workspace/Solution/DocumentState.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
Labels: Area-IDE

#65985 Add support for distinct LSP diagnostic categories in LSP Pull Diagnostics.
  src/EditorFeatures/Core/LanguageServer/AlwaysActivateInProcLanguageClient.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/AbstractDocumentDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/DocumentDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/TaskListDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/WorkspaceDocumentDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DocumentPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Public/PublicDocumentPullDiagnosticsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Public/PublicWorkspacePullDiagnosticsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/PullDiagnosticCategories.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/AbstractPullDiagnosticTestsBase.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
Labels: Area-IDE

#65945 Delete unused type
  src/Workspaces/Core/Portable/Workspace/Solution/MetadataReferenceManager.cs
Labels: Area-IDE

#65939 Avoid boxing in BoundDagTest.GetHashCode
  eng/config/BannedSymbols.txt
  src/Compilers/CSharp/Portable/BoundTree/BoundDagTest.cs
  src/Compilers/CSharp/Portable/CSharpCompilationOptions.cs
  src/Compilers/CSharp/Portable/Symbols/FunctionPointers/FunctionPointerMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/FunctionPointers/FunctionPointerParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/SignatureOnlyParameterSymbol.cs
  src/Compilers/Core/Portable/CommandLine/SarifDiagnosticComparer.cs
  src/Compilers/Core/Portable/ConstantValue.cs
  src/Compilers/Core/Portable/Diagnostic/DiagnosticDescriptor.cs
  src/Compilers/Core/Portable/MetadataReference/MetadataReferenceProperties.cs
  src/Compilers/Core/Portable/Symbols/Attributes/AttributeUsageInfo.cs
  src/Compilers/Core/Portable/Symbols/NullabilityInfo.cs
  src/Compilers/Core/Portable/Text/SourceTextComparer.cs
  src/Compilers/Test/Core/Diagnostics/DiagnosticDescription.cs
  src/VisualStudio/Core/Def/TableDataSource/DiagnosticTableItem.cs
  src/VisualStudio/Core/Impl/CodeModel/CodeModelEvent.cs
  src/Workspaces/Core/Portable/Rename/ConflictEngine/RelatedLocation.cs
  src/Workspaces/Core/Portable/Workspace/Solution/LoadTextOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/SymbolUsageInfo.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/SymbolEquivalenceComparer.GetHashCodeVisitor.cs
Labels: Area-Compilers

#65395 Allow multiline override
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/OverrideCompletionProviderTests.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/OverrideCompletionProvider.cs
Labels: Area-IDE, Community

#65984 Adding AsPublicInterfaceImplementation ability to handle expression-bodied
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
Labels: Area-IDE, Community

#65930 Ban usage of public options in Roslyn
  eng/config/BannedSymbols.txt
  src/CodeStyle/BannedSymbols.txt
  src/EditorFeatures/CSharp/BlockCommentEditing/BlockCommentEditingCommandHandler.cs
  src/EditorFeatures/Core/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs
  src/EditorFeatures/DiagnosticsTestUtilities/SplitComments/AbstractSplitCommentCommandHandlerTests.cs
  src/Features/BannedSymbols.txt
  src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs
  src/Tools/ExternalAccess/FSharp/Navigation/FSharpNavigationOptions.cs
  src/Tools/ExternalAccess/Razor/RazorGlobalOptions.cs
  src/VisualStudio/CSharp/Impl/Options/Formatting/IndentationViewModel.cs
  src/VisualStudio/CSharp/Impl/Options/Formatting/NewLinesViewModel.cs
  src/VisualStudio/CSharp/Impl/Options/Formatting/WrappingViewModel.cs
  src/VisualStudio/Core/Impl/Options/CheckBoxWithComboViewModel.cs
  src/VisualStudio/Core/Impl/Options/NotificationOptionViewModel.cs
  src/VisualStudio/Core/Impl/Options/OptionPreviewControl.xaml
  src/VisualStudio/Core/Impl/Options/OptionPreviewControl.xaml.cs
  src/VisualStudio/Core/Impl/Options/Style/AbstractCodeStyleOptionViewModel.cs
  src/VisualStudio/Core/Impl/Options/Style/BooleanCodeStyleOptionViewModel.cs
  src/VisualStudio/Core/Impl/Options/Style/EnumCodeStyleOptionViewModel.cs
  src/VisualStudio/Core/Impl/Options/Style/NamingPreferences/NamingStyleOptionPageControl.xaml.cs
  src/VisualStudio/Core/Impl/Options/Style/NamingPreferences/NamingStyleOptionPageViewModel.cs
  src/Workspaces/CSharp/Portable/Formatting/CSharpFormattingOptions.cs
  src/Workspaces/Core/Portable/CodeStyle/CodeStyleOption.cs
  src/Workspaces/Core/Portable/CodeStyle/CodeStyleOption2_operators.cs
  src/Workspaces/Core/Portable/CodeStyle/CodeStyleOptions.cs
  src/Workspaces/Core/Portable/CodeStyle/NotificationOption.cs
  src/Workspaces/Core/Portable/CodeStyle/NotificationOption2_operators.cs
  src/Workspaces/Core/Portable/Formatting/FormattingOptions.cs
  src/Workspaces/Core/Portable/Options/DocumentOptionSet.cs
  src/Workspaces/Core/Portable/Options/Option2`1_operators.cs
  src/Workspaces/Core/Portable/Options/OptionSet.cs
  src/Workspaces/Core/Portable/Options/Option`1.cs
  src/Workspaces/Core/Portable/Options/OptionsExtensions.cs
  src/Workspaces/Core/Portable/Options/OptionsHelpers.cs
  src/Workspaces/Core/Portable/Options/PerLanguageOption.cs
  src/Workspaces/Core/Portable/Options/PerLanguageOption2_operators.cs
  src/Workspaces/Core/Portable/Recommendations/RecommendationOptions.cs
  src/Workspaces/Core/Portable/Rename/RenameOptions.cs
  src/Workspaces/Core/Portable/Simplification/SimplificationOptions.cs
  src/Workspaces/CoreTest/Options/OptionKeyTests.cs
  src/Workspaces/CoreTest/WorkspaceServiceTests/GlobalOptionServiceTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/CodeStyleOption2`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Options/Option2`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Options/OptionDefinition.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Options/OptionStorageLocation2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Options/PerLanguageOption2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Indentation/SpecialFormattingOperation.vb
Labels: Area-IDE

#66002 Bump nuget version to ensure the correct version for .NET7 gets deplo…
  eng/Versions.props
Labels: Area-Infrastructure

#65989 Merge main-vs-deps back into main
  eng/Versions.props
  src/EditorFeatures/CSharpTest/NavigateTo/NavigateToSearcherTests.cs
  src/EditorFeatures/Core.Wpf/NavigateTo/NavigateToItemDisplay.cs
  src/EditorFeatures/Core.Wpf/NavigateTo/NavigateToItemProvider.Callback.cs
  src/EditorFeatures/Core/LanguageServer/AlwaysActivateInProcLanguageClient.cs
  src/EditorFeatures/Core/NavigateTo/NavigateToHelpers.cs
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/VSTypeScriptNavigateToSearchService.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.InProcess.cs
  src/Features/Core/Portable/NavigateTo/INavigateToSearchCallback.cs
  src/Features/Core/Portable/NavigateTo/INavigateToSearchResult.cs
  src/Features/Core/Portable/NavigateTo/NavigateToSearcher.cs
  src/Features/Core/Portable/NavigateTo/RoslynNavigateToItem.cs
  src/Features/LanguageServer/Protocol/DefaultCapabilitiesProvider.cs
  src/Features/LanguageServer/Protocol/ExternalAccess/VSCode/API/VSCodeAnalyzerLoader.cs
  src/Features/LanguageServer/Protocol/Handler/BufferedProgress.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/AbstractDocumentDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/DocumentDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/TaskListDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/WorkspaceDocumentDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DocumentPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Experimental/ExperimentalDiagnosticsTypes.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Experimental/ExperimentalWorkspacePullDiagnosticsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Public/PublicDocumentPullDiagnosticHandlerFactory.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Public/PublicDocumentPullDiagnosticsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Public/PublicWorkspacePullDiagnosticHandlerFactory.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Public/PublicWorkspacePullDiagnosticsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/PullDiagnosticCategories.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/References/FindAllReferencesHandler.cs
  src/Features/LanguageServer/Protocol/Handler/SpellCheck/AbstractSpellCheckingHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Symbols/WorkspaceSymbolsHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/AbstractPullDiagnosticTestsBase.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/References/FindAllReferencesHandlerTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/SpellCheck/SpellCheckTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Symbols/WorkspaceSymbolsTests.cs
  src/Setup/DevDivInsertionFiles/DevDivInsertionFiles.csproj
  src/Tools/ExternalAccess/FSharp/Internal/NavigateTo/InternalFSharpNavigateToSearchResult.cs
  src/Tools/ExternalAccess/OmniSharp/NavigateTo/OmniSharpNavigateToSearchService.cs
  src/Tools/IdeBenchmarks/IdeBenchmarks.csproj
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/VisualStudio/Core/Def/NavigateTo/RoslynCodeSearchResult.cs
  src/VisualStudio/Core/Def/NavigateTo/RoslynNavigateToSearchCallback.cs
  src/VisualStudio/Core/Def/NavigateTo/RoslynSearchItemsSource.cs
  src/VisualStudio/Core/Def/NavigateTo/RoslynSearchItemsSourceProvider.cs
  src/VisualStudio/Core/Def/NavigateTo/RoslynSearchResultPreviewPanel.cs
  src/VisualStudio/Core/Def/NavigateTo/RoslynSearchResultView.cs
  src/VisualStudio/Core/Def/NavigateTo/RoslynSearchResultViewFactory.cs
  src/VisualStudio/Core/Def/NavigateTo/VisualStudioNavigateToItemProviderFactory.cs
  src/VisualStudio/Core/Def/Progression/GraphQueries/ProgressionNavigateToSearchCallback.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpQuickInfo.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicQuickInfo.cs
  src/VisualStudio/Setup.Dependencies/Roslyn.VisualStudio.Setup.Dependencies.csproj
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Workspaces/Core/Portable/PatternMatching/PatternMatch.cs
Labels: Area-Infrastructure, auto-merge

#65990 Remove main-vs-deps
  eng/config/PublishData.json
Labels: Area-Infrastructure

#65991 Merge 17.6-vs-deps back into release/dev17.6
  eng/Versions.props
  src/EditorFeatures/CSharpTest/NavigateTo/NavigateToSearcherTests.cs
  src/EditorFeatures/Core.Wpf/NavigateTo/NavigateToItemDisplay.cs
  src/EditorFeatures/Core.Wpf/NavigateTo/NavigateToItemProvider.Callback.cs
  src/EditorFeatures/Core/NavigateTo/NavigateToHelpers.cs
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/VSTypeScriptNavigateToSearchService.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.InProcess.cs
  src/Features/Core/Portable/NavigateTo/INavigateToSearchCallback.cs
  src/Features/Core/Portable/NavigateTo/INavigateToSearchResult.cs
  src/Features/Core/Portable/NavigateTo/NavigateToSearcher.cs
  src/Features/Core/Portable/NavigateTo/RoslynNavigateToItem.cs
  src/Features/LanguageServer/Protocol/DefaultCapabilitiesProvider.cs
  src/Features/LanguageServer/Protocol/ExternalAccess/VSCode/API/VSCodeAnalyzerLoader.cs
  src/Features/LanguageServer/Protocol/Handler/BufferedProgress.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/AbstractDocumentDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/DocumentDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/WorkspaceDocumentDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DocumentPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Experimental/ExperimentalDiagnosticsTypes.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Experimental/ExperimentalWorkspacePullDiagnosticsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Public/PublicDocumentPullDiagnosticHandlerFactory.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Public/PublicDocumentPullDiagnosticsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Public/PublicWorkspacePullDiagnosticHandlerFactory.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Public/PublicWorkspacePullDiagnosticsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/References/FindAllReferencesHandler.cs
  src/Features/LanguageServer/Protocol/Handler/SpellCheck/AbstractSpellCheckingHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Symbols/WorkspaceSymbolsHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/AbstractPullDiagnosticTestsBase.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/References/FindAllReferencesHandlerTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/SpellCheck/SpellCheckTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Symbols/WorkspaceSymbolsTests.cs
  src/Setup/DevDivInsertionFiles/DevDivInsertionFiles.csproj
  src/Tools/ExternalAccess/FSharp/Internal/NavigateTo/InternalFSharpNavigateToSearchResult.cs
  src/Tools/ExternalAccess/OmniSharp/NavigateTo/OmniSharpNavigateToSearchService.cs
  src/Tools/IdeBenchmarks/IdeBenchmarks.csproj
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/VisualStudio/Core/Def/NavigateTo/RoslynCodeSearchResult.cs
  src/VisualStudio/Core/Def/NavigateTo/RoslynNavigateToSearchCallback.cs
  src/VisualStudio/Core/Def/NavigateTo/RoslynSearchItemsSource.cs
  src/VisualStudio/Core/Def/NavigateTo/RoslynSearchItemsSourceProvider.cs
  src/VisualStudio/Core/Def/NavigateTo/RoslynSearchResultPreviewPanel.cs
  src/VisualStudio/Core/Def/NavigateTo/RoslynSearchResultView.cs
  src/VisualStudio/Core/Def/NavigateTo/RoslynSearchResultViewFactory.cs
  src/VisualStudio/Core/Def/NavigateTo/VisualStudioNavigateToItemProviderFactory.cs
  src/VisualStudio/Core/Def/Progression/GraphQueries/ProgressionNavigateToSearchCallback.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpQuickInfo.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicQuickInfo.cs
  src/VisualStudio/Setup.Dependencies/Roslyn.VisualStudio.Setup.Dependencies.csproj
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Workspaces/Core/Portable/PatternMatching/PatternMatch.cs
Labels: Area-Infrastructure

#66013 Attempt to reenable tests disabled because of messagepack issue.
  src/Compilers/Test/Core/Assert/ConditionalFactAttribute.cs
  src/EditorFeatures/CSharpTest/AddUsing/AddUsingTests.cs
  src/EditorFeatures/CSharpTest/AddUsing/AddUsingTests_ExtensionMethods.cs
  src/EditorFeatures/CSharpTest/AddUsing/AddUsingTests_Queries.cs
  src/EditorFeatures/CSharpTest/AddUsing/AddUsingTests_Razor.cs
  src/EditorFeatures/CSharpTest/FullyQualify/FullyQualifyTests.cs
  src/EditorFeatures/Test/EditAndContinue/RemoteEditAndContinueServiceTests.cs
  src/EditorFeatures/VisualBasicTest/Diagnostics/AddImport/AddImportTests.vb
  src/EditorFeatures/VisualBasicTest/Diagnostics/FullyQualify/FullyQualifyTests.vb
  src/VisualStudio/Core/Test.Next/Services/VisualStudioDiagnosticAnalyzerExecutorTests.cs
Labels: Area-IDE

#65973 Breaking change: Disallow raw-string-literal interpolations at start of line when indentation-whitespace is present.
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md
  src/Compilers/CSharp/Portable/Parser/LanguageParser_InterpolatedString.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RawInterpolationTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/RawInterpolatedStringLiteralCompilingTests.cs
Labels: Area-Compilers

#66020 Consolidate IsExternalInit definitions
  Roslyn.sln
  src/Compilers/Core/Portable/InternalUtilities/CompilerFeatureRequiredAttribute.cs
  src/Compilers/Core/Portable/InternalUtilities/IsExternalInit.cs
  src/Compilers/Core/Portable/InternalUtilities/RequiredMemberAttribute.cs
  src/Compilers/Core/Portable/InternalUtilities/SetsRequiredMembersAttribute.cs
  src/Compilers/Core/RebuildTest/Microsoft.CodeAnalysis.Rebuild.UnitTests.csproj
  src/Compilers/Test/Core/IsExternalInit.cs
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/EditorFeatures/TestUtilities/IsExternalInit.cs
  src/EditorFeatures/TestUtilities/Microsoft.CodeAnalysis.EditorFeatures.Test.Utilities.csproj
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/IsExternalInit.cs
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/Microsoft.CommonLanguageServerProtocol.Framework.csproj
  src/Features/LanguageServer/Protocol/IsExternalInit.cs
  src/Features/LanguageServer/ProtocolUnitTests/IsExternalInit.cs
  src/Features/LanguageServer/ProtocolUnitTests/Microsoft.CodeAnalysis.LanguageServer.Protocol.UnitTests.csproj
  src/Tools/ExternalAccess/AspNetCore/Microsoft.CodeAnalysis.ExternalAccess.AspNetCore.csproj
  src/Tools/ExternalAccess/FSharp/Microsoft.CodeAnalysis.ExternalAccess.FSharp.csproj
  src/Tools/ExternalAccess/Razor/Microsoft.CodeAnalysis.ExternalAccess.Razor.csproj
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
Labels: Area-Compilers

#65956 Update PublicAPI.Shipped for 17.4
  src/Compilers/CSharp/Portable/PublicAPI.Shipped.txt
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Core/Portable/PublicAPI.Shipped.txt
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/VisualBasic/Portable/PublicAPI.Shipped.txt
  src/Compilers/VisualBasic/Portable/PublicAPI.Unshipped.txt
  src/EditorFeatures/Core.Cocoa/PublicAPI.Shipped.txt
  src/EditorFeatures/Core.Cocoa/PublicAPI.Unshipped.txt
  src/Features/Core/Portable/PublicAPI.Shipped.txt
  src/Features/Core/Portable/PublicAPI.Unshipped.txt
  src/Tools/ExternalAccess/AspNetCore/PublicAPI.Unshipped.txt
  src/Workspaces/Core/Portable/PublicAPI.Shipped.txt
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
Labels: Area-Compilers, Area-Infrastructure, Needs API Review

#66023 Improve performance of Document-Highlight-Refs
  src/EditorFeatures/Test2/ReferenceHighlighting/CSharpReferenceHighlightingTests.vb
  src/EditorFeatures/Test2/ReferenceHighlighting/VisualBasicReferenceHighlightingTests.vb
  src/Features/CSharp/Portable/DocumentHighlighting/CSharpDocumentHighlightsService.cs
  src/Features/Core/Portable/DocumentHighlighting/AbstractDocumentHighlightsService.cs
  src/Features/Core/Portable/DocumentHighlighting/IDocumentHighlightsService.cs
  src/Features/Core/Portable/DocumentHighlighting/IRemoteDocumentHighlightsService.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.SymbolSet.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine_FindReferencesInDocuments.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractMemberScopedReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/PropertySymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_FindReferences_Current.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ISymbolExtensions.cs
Labels: Area-IDE

#66033 Create initial subscription to roslyn analyzer updates
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#66040 Additional perf improvements for document highlights
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.BidirectionalSymbolSet.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.SymbolSet.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine_FindReferencesInDocuments.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_Hierarchy.cs
Labels: Area-IDE

#65987 Support MemberNotNull on required members in nullable analysis
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/RequiredMembersTests.cs
  src/Compilers/Core/Portable/Collections/ImmutableArrayExtensions.cs
  src/Compilers/Core/Portable/InternalUtilities/EnumerableExtensions.cs
Labels: Area-Compilers, New Feature - Required Members

#66041 Avoid using Solution.Options in ConfigureCodeStyleOptionCodeFixProvider
  src/EditorFeatures/CSharp/BlockCommentEditing/BlockCommentEditingCommandHandler.cs
  src/EditorFeatures/CSharp/BlockCommentEditing/CloseBlockCommentCommandHandler.cs
  src/EditorFeatures/CSharpTest/Diagnostics/Configuration/ConfigureSeverity/VarForBuiltInTypesSeverityConfigurationTests.cs
  src/EditorFeatures/CSharpTest/QuickInfo/SyntacticQuickInfoSourceTests.cs
  src/EditorFeatures/Core.Wpf/InlineHints/InlineHintsTag.cs
  src/EditorFeatures/Core.Wpf/InlineHints/InlineHintsTagger.cs
  src/EditorFeatures/Core.Wpf/InlineHints/InlineHintsTaggerProvider.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/CompletionSource.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/CompletionSourceProvider.cs
  src/EditorFeatures/Core/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs
  src/EditorFeatures/Core/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilderContext.cs
  src/EditorFeatures/Core/IntelliSense/QuickInfo/QuickInfoSourceProvider.QuickInfoSource.cs
  src/EditorFeatures/Core/IntelliSense/QuickInfo/QuickInfoSourceProvider.cs
  src/EditorFeatures/Core/LanguageServer/EditorHoverCreationService.cs
  src/EditorFeatures/Test2/IntelliSense/AbstractIntellisenseQuickInfoBuilderTests.vb
  src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs
  src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs
  src/Features/Core/Portable/CodeFixes/Configuration/ConfigurationUpdater.cs
  src/Features/Core/Portable/CodeFixes/Configuration/ConfigureCodeStyle/ConfigureCodeStyleOptionCodeFixProvider.cs
  src/Features/Core/Portable/Completion/CompletionOptions.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/AbstractDocumentDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/DocumentDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/TaskListDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/WorkspaceDocumentDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DocumentPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Public/PublicDocumentPullDiagnosticsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
  src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb
  src/Workspaces/Core/Portable/Recommendations/RecommendationOptions.cs
  src/Workspaces/Core/Portable/Recommendations/Recommender.cs
Labels: Area-IDE

#66034 Suppress semantic diagnostics from being reported by pull-diag-taggers until the project has fully loaded.
  src/EditorFeatures/Core/Diagnostics/AbstractPushOrPullDiagnosticsTaggerProvider.SingleDiagnosticKindPullTaggerProvider.cs
Labels: Area-IDE

#65899 Bind and emit Primary Constructor
  src/Compilers/CSharp/CSharpAnalyzerDriver/CSharpDeclarationComputer.cs
  src/Compilers/CSharp/Portable/Binder/BinderFactory.BinderFactoryVisitor.cs
  src/Compilers/CSharp/Portable/Binder/BinderFactory.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Initializers.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/LocalBinderFactory.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Compilation/MethodBodySemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs
  src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs
  src/Compilers/CSharp/Portable/Declarations/DeclarationTreeBuilder.cs
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Internal.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Syntax.Generated.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Symbols/Source/SourceConstructorSymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Bases.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordConstructor.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordDeconstruct.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs
  src/Compilers/CSharp/Portable/Syntax/ClassDeclarationSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/InterfaceDeclarationSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/RecordDeclarationSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/StructDeclarationSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
  src/Compilers/CSharp/Portable/Syntax/TypeDeclarationSyntax.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LookupPositionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/RecordTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/RecordParsing.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/TopLevelStatementsParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs
Labels: Area-Compilers, New Feature - Primary Constructors

#66061 Fix crash while deserializing DiagnosticDataLocation
  src/EditorFeatures/Test/EditAndContinue/EmitSolutionUpdateResultsTests.cs
  src/VisualStudio/Core/Def/TableDataSource/Suppression/VisualStudioDiagnosticListSuppressionStateService.cs
  src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs
  src/Workspaces/Core/Portable/Diagnostics/DiagnosticDataLocation.cs
Labels: Area-IDE

#65916 Add tests for CheckInvocationArgMixing
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers

#65693 Avoid reporting ref safety errors for discard assignments
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundDiscardExpression.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundExpressionExtensions.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/BoundTree/OutDeconstructVarPendingInference.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers

#65857 Adjust calculation of invocation escape when return type is ref to ref struct
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers

#65878 Use the inner pattern to recreate the decision DAG for is-expressions
  src/Compilers/CSharp/Portable/BoundTree/BoundIsPatternExpression.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests_ListPatterns.cs
Labels: Area-Compilers, Community

#66094 Fix typo in error message
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfoCacheService.cs
Labels: Area-IDE, Community

#65965 Produce error when static local function captures a local with extension method method group conversion
  src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs
Labels: Area-Compilers, Community

#66082 Add unique color scheme for high contrast mode
  src/VisualStudio/Core/Def/EditorConfigSettings/Whitespace/View/WhitespaceBoolSettingView.xaml
Labels: Area-IDE, Needs UX Triage

#66119 Do not treat enum base list as type context for completions
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/DelegateKeywordRecommenderTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/CSharpSyntaxContext.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs
Labels: Area-IDE, Community

#66048 Keep the block of else-if statement in "Use null propogation" codefix
  src/Analyzers/CSharp/CodeFixes/UseNullPropagation/CSharpUseNullPropagationCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseNullPropagation/UseNullPropagationTests.cs
  src/Analyzers/Core/CodeFixes/UseNullPropagation/AbstractUseNullPropagationCodeFixProvider.cs
  src/Analyzers/VisualBasic/CodeFixes/UseNullPropagation/VisualBasicUseNullPropagationCodeFixProvider.vb
  src/Analyzers/VisualBasic/Tests/UseNullPropagation/UseNullPropagationTests.vb
Labels: Area-IDE, Community

#66142 Remove unnecessary `ToList` calls
  src/VisualStudio/Core/Def/Implementation/AbstractVsTextViewFilter.cs
Labels: Area-IDE, Community

#66125 Fix for `return new …` statement differs between `Task` and `ValueTask` methods
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ObjectCreationCompletionProviderTests.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs
Labels: Area-IDE, Community

#66052 Cleanup dead MSBuild conditions
  src/Compilers/Core/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.csproj
Labels: Area-Compilers, Community

#66140 Enable disabled test
  src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractMethodTests.cs
Labels: Area-IDE

#66139 Fix Inline Rename Flyout Positioning
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyoutViewModel.cs
Labels: Area-IDE

#66043 Only examine a PEReference once when walking projects to produce inheritance tree
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/DependentTypeFinder.cs
Labels: Area-IDE

#66030 Correctly parse local function with several async modifiers
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/LocalFunctionParsingTests.cs
Labels: Area-Compilers, Community

#66137 Reduce amount of stack used by CodeGenerator.EmitInstanceCallExpression
  src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs
  src/Compilers/CSharp/Test/EndToEnd/EndToEndTests.cs
Labels: Area-Compilers

#65925 Adding support for the nullability of generic parameters of method parameters when using ExtractMethod
  src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractMethodTests.cs
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.AnalyzerResult.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.VariableInfo.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.cs
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.vb
Labels: Area-IDE, Community

#66145 Update StreamJsonRpc
  eng/Versions.props
Labels: Area-Infrastructure

#66149 Fix Extract Base When Class Has Base
  src/EditorFeatures/CSharpTest/ExtractClass/ExtractClassTests.cs
  src/Features/Core/Portable/ExtractClass/AbstractExtractClassRefactoringProvider.cs
Labels: Area-IDE
