Repository dotnet/roslyn, pull requests merged in 2022-10, with the labels that each got.

#64285 Update SymbolDisplay API to include scoped for parameters and locals
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Members.cs
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_LifetimeAnnotation.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SpanStackSafetyTests.cs
  src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Core/Portable/SymbolDisplay/SymbolDisplayCompilerInternalOptions.cs
  src/Compilers/Core/Portable/SymbolDisplay/SymbolDisplayLocalOptions.cs
  src/Compilers/Core/Portable/SymbolDisplay/SymbolDisplayParameterOptions.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolDisplay/SymbolDisplayTests.vb
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
Labels: Area-Compilers, New Language Feature - Ref Fields

#64432 Fix 'invert if' mishandling of lifted nullable operators
  src/EditorFeatures/CSharpTest/InvertIf/InvertIfTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions_Negate.cs
Labels: Area-IDE, Community

#64451 Insert release/dev17.4 to rel/d17.4
  eng/config/PublishData.json
Labels: Area-Infrastructure

#64445 Log errors for Non-mutating requests
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/RequestExecutionQueue.cs
  src/Features/LanguageServer/Protocol/RoslynLanguageServer.cs
  src/Features/LanguageServer/Protocol/RoslynRequestExecutionQueue.cs
Labels: Area-IDE

#64449 Update to use new internal API
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/AbstractUnitTestingDocumentDifferenceService.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingSolutionCrawlerLogger.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingWorkCoordinator.UnitTestingAsyncDocumentWorkItemQueue.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingWorkCoordinator.UnitTestingAsyncProjectWorkItemQueue.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingWorkCoordinator.UnitTestingAsyncWorkItemQueue.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingWorkCoordinator.UnitTestingIncrementalAnalyzerProcessor.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingWorkCoordinator.UnitTestingLowPriorityProcessor.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingWorkCoordinator.UnitTestingNormalPriorityProcessor.cs
Labels: Area-IDE

#64442 Update Microsoft.VisualStudio.Cache to 17.3.26-alpha
  eng/Versions.props
Labels: Area-Infrastructure

#64452 Fix integration tests
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpBuild.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpErrorListCommon.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpFindReferences.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpGoToDefinition.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpGoToImplementation.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/ShellInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicErrorListCommon.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicFindReferences.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicGoToDefinition.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicGoToImplementation.cs
Labels: Area-Infrastructure

#64454 Fix out of bounds error when doing speculative operations
  src/Workspaces/CoreTest/SemanticModelReuse/SemanticModelReuseTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/VisualBasicSyntaxContext.vb
Labels: Area-IDE

#64446 Improve CLaSP doc comments
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/AbstractLanguageServer.cs
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/ILifeCycleManager.cs
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/IMethodHandler.cs
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/IRequestContextFactory.cs
Labels: Area-IDE

#64438 Update help link URI for code style diagnostics
  src/Analyzers/Core/Analyzers/Helpers/DiagnosticHelper.cs
  src/EditorFeatures/CSharpTest/Squiggles/ErrorSquiggleProducerTests.cs
  src/EditorFeatures/Test/Diagnostics/IDEDiagnosticIDConfigurationTests.cs
  src/EditorFeatures/VisualBasicTest/Squiggles/ErrorSquiggleProducerTests.vb
  src/VisualStudio/CSharp/Impl/LanguageService/CSharpCodeCleanupFixerDiagnosticIds.cs
  src/VisualStudio/Core/Def/CodeCleanup/CommonCodeCleanUpFixerDiagnosticIds.cs
  src/VisualStudio/VisualBasic/Impl/LanguageService/VisualBasicCodeCleanupFixerDiagnosticIds.vb
Labels: Area-IDE

#64460 Fix LSIF handling of extension methods
  src/Features/Lsif/Generator/Generator.cs
  src/Features/Lsif/GeneratorTest/RangeResultSetTests.vb
Labels: Area-IDE

#64408 Add tests to verify bug is fixed
  src/Compilers/CSharp/Test/Symbol/Symbols/RequiredMembersTests.cs
Labels: Area-Compilers, New Feature - Required Members

#64476 Move to simplified helper extension for reading data from a stream
  src/Workspaces/Remote/Core/RemoteHostAssetSerialization.cs
  src/Workspaces/Remote/Core/SolutionAssetProvider.cs
Labels: Area-IDE

#64479 Add back accidentally deleted activity id correlation
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/RequestExecutionQueue.cs
Labels: Area-IDE, LSP

#64480 Do not inline fault-helper
  src/Compilers/Core/Portable/InternalUtilities/FatalError.cs
Labels: Area-Compilers

#64477 Add "target type match" filter support to enum and static members providers
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/EnumAndCompletionListTagCompletionProviderTests.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests.vb
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/CompletionListTagCompletionProviderTests.vb
  src/Features/CSharp/Portable/Completion/CompletionProviders/EnumAndCompletionListTagCompletionProvider.cs
  src/Features/VisualBasic/Portable/Completion/CompletionProviders/CompletionListTagCompletionProvider.vb
  src/Features/VisualBasic/Portable/Completion/CompletionProviders/EnumCompletionProvider.vb
Labels: Area-IDE

#64485 Add analyzer info for detecting IntPtr/UintPtr behavioral changes
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md
Labels: Area-Compilers

#64481 Remove dependency on ms.extensions.dependencyinjection from roslyn lsp
  src/Features/LanguageServer/Protocol/Handler/ServerLifetime/ExitHandler.cs
  src/Features/LanguageServer/Protocol/Handler/ServerLifetime/InitializeHandler.cs
  src/Features/LanguageServer/Protocol/Handler/ServerLifetime/InitializedHandler.cs
  src/Features/LanguageServer/Protocol/Handler/ServerLifetime/ShutdownHandler.cs
  src/Features/LanguageServer/Protocol/LspServices/AbstractLspServiceProvider.cs
  src/Features/LanguageServer/Protocol/LspServices/LspServices.cs
  src/Features/LanguageServer/Protocol/Microsoft.CodeAnalysis.LanguageServer.Protocol.csproj
  src/Features/LanguageServer/Protocol/RoslynLanguageServer.cs
  src/Setup/DevDivInsertionFiles/DevDivInsertionFiles.csproj
Labels: Area-IDE, LSP

#64475 Add additional information to help F# with navigating to symbols
  src/Features/Core/Portable/Navigation/ICrossLanguageSymbolNavigationService.cs
  src/Tools/ExternalAccess/FSharp/Internal/Navigation/FSharpCrossLanguageSymbolNavigationService.cs
  src/Tools/ExternalAccess/FSharp/Navigation/IFSharpCrossLanguageSymbolNavigationService.cs
  src/VisualStudio/Core/Def/Workspace/VisualStudioSymbolNavigationService.cs
Labels: Area-IDE

#64459 Semantic snippets - change filter to keep old snippets in if replacement does not exist
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SnippetCompletionProviderTests.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/SnippetCompletionProvider.cs
  src/VisualStudio/Core/Test/Completion/CSharpCompletionSnippetNoteTests.vb
Labels: Area-IDE

#64450 Enable CodeQL on official builds
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#64412 Do not report a secondary NFW exception after already reporting one earlier.
  src/Workspaces/Remote/Core/RemoteCallback.cs
Labels: Area-IDE

#64506 Do not suggest `struct` after `record` with `abstract` or `sealed` modifiers
  src/EditorFeatures/CSharpTest2/Recommendations/StructKeywordRecommenderTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/ClassKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/StructKeywordRecommender.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTreeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/CSharpSyntaxContext.cs
Labels: Area-IDE, Community

#64496 Only get the associated symbol, not the containing symbol
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/SymbolChanges.cs
Labels: Area-Interactive

#64240 Add a new Location.Create overload for external file location with a different mappedLineSpan
  src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/LocationsTests.cs
  src/Compilers/Core/Portable/Diagnostic/ExternalFileLocation.cs
  src/Compilers/Core/Portable/Diagnostic/Location.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisResultBuilder.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisScope.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.AnalyzerDiagnosticReporter.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/VisualBasic/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.vb
Labels: Area-Analyzers

#64484 Fix Union to match the semantics of GetApplicableAnalyzers
  src/EditorFeatures/Test/SolutionCrawler/WorkCoordinatorTests.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.WorkItem.cs
Labels: Area-IDE

#64276 Update ref `foreach` tests
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers, Test

#58409 Fix "Build Only" diagnostics content in error list
  src/VisualStudio/Core/Def/TableDataSource/AbstractTableEntriesSnapshot.cs
  src/VisualStudio/Core/Def/TableDataSource/VisualStudioBaseDiagnosticListTable.LiveTableDataSource.cs
  src/VisualStudio/Core/Def/TableDataSource/VisualStudioDiagnosticListTable.BuildTableDataSource.cs
  src/VisualStudio/Core/Def/TaskList/ExternalErrorDiagnosticUpdateSource.cs
  src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs
  src/Workspaces/Core/Portable/Diagnostics/DiagnosticAnalyzerInfoCache.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/DiagnosticDescriptorExtensions.cs
Labels: Area-IDE

#64404 Add instrumentation to investigate flakiness in `ConstantFolding_01`
  src/Compilers/CSharp/Test/Emit2/Emit/NumericIntPtrTests.cs
  src/Compilers/Test/Core/CommonTestBase.cs
  src/Compilers/Test/Core/CompilationVerifier.cs
Labels: Test, Flaky

#64486 Move to a simpler model of writing assets out to OOP
  src/Workspaces/Remote/Core/BrokeredServiceConnection.cs
  src/Workspaces/Remote/Core/ISolutionAssetProvider.cs
  src/Workspaces/Remote/Core/RemoteHostAssetSerialization.cs
  src/Workspaces/Remote/Core/SolutionAssetProvider.cs
Labels: Area-IDE

#64543 Only start scanning for task-list items once the Task-List window is actually open.
  src/VisualStudio/Core/Def/TaskList/VisualStudioTaskListService.cs
Labels: Area-IDE

#64537 Replace recursion with iteration in convert-if-to-switch
  src/Features/Core/Portable/ConvertIfToSwitch/AbstractConvertIfToSwitchCodeRefactoringProvider.Analyzer.cs
Labels: Area-IDE

#64521 Create a .NET Core build of the LSIF generator
  src/Features/Lsif/Generator/Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.csproj
  src/Features/Lsif/Generator/ResultSetTracking/SymbolHoldingResultSetTracker.cs
Labels: Area-IDE

#64520 Fix negation of is true and is false patterns with non-Boolean values
  src/Analyzers/CSharp/Tests/UsePatternMatching/CSharpUseNotPatternTests.cs
  src/EditorFeatures/CSharpTest/InvertLogical/InvertLogicalTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions_Negate.cs
Labels: Area-IDE, Community

#64490 Add and use TargetFramework.Net70
  eng/Versions.props
  src/Compilers/CSharp/Portable/Symbols/AssemblySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/MetadataOrSourceAssemblySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/MissingCorLibrarySymbol.cs
  src/Compilers/CSharp/Test/Emit2/Emit/NumericIntPtrTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/Compilers/Test/Core/CompilationVerifier.cs
  src/Compilers/Test/Core/Microsoft.CodeAnalysis.Test.Utilities.csproj
  src/Compilers/Test/Core/TargetFrameworkUtil.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
Labels: Area-Compilers

#64559 Update publish data to test PR validation fix
  eng/config/PublishData.json
Labels: Area-Infrastructure

#64532 Remove assert that fires for old CodeStyle NuGet packages
  src/EditorFeatures/Core/Diagnostics/DiagnosticsClassificationTaggerProvider.cs
Labels: Area-IDE

#64420 Add symbol key tests
  src/Workspaces/Core/Portable/Remote/RemoteArguments.cs
  src/Workspaces/CoreTest/SymbolKeyTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/SymbolKey/SymbolKey.SymbolKeyComparer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/SymbolKey/SymbolKey.SymbolKeyReader.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/SymbolKey/SymbolKey.cs
Labels: Area-IDE

#64379 Set starting size for changed text builder using old text
  src/Compilers/Core/Portable/Text/ChangedText.cs
Labels: Area-Compilers

#64494 Simpler bidirectional streaming invocation in OOP.
  src/Workspaces/Remote/Core/BrokeredServiceConnection.cs
  src/Workspaces/Remote/Core/RemoteCallback.cs
  src/Workspaces/Remote/Core/RemoteHostAssetSerialization.cs
  src/Workspaces/Remote/Core/SolutionAssetProvider.cs
Labels: Area-IDE

#64571 Publish additional packages to vssdk feed
  eng/config/PublishData.json
Labels: Area-Infrastructure

#64572 Cherry-picking perfepic commits back into main
  src/Compilers/Core/Portable/Text/ChangedText.cs
Labels: Area-Compilers

#64574 Revert "Remove unused TS brace completion code"
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/IVSTypeScriptBraceMatcherImplementation.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptBraceMatcher.cs
Labels: Area-IDE

#64557 Enable diagnostics token tor solution crawler in code action test
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/WorkspaceInProcess.cs
Labels: Area-IDE

#64554 Publish pr validation packages
  azure-pipelines-pr-validation.yml
Labels: Area-Infrastructure

#64565 Simplify SymbolKey implementation
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/SymbolKey/SymbolKey.cs
Labels: Area-IDE

#64603 Enable already-fixed test
  src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs
Labels: Area-Compilers

#64578 Utility for uploading artifact on test failure
  src/Compilers/Core/MSBuildTaskTests/DotNetSdkTests.cs
  src/Compilers/Core/MSBuildTaskTests/TestUtilities/DotNetSdkTestBase.cs
  src/Compilers/Test/Core/Assert/ArtifactUploadUtil.cs
Labels: Area-Compilers

#64580 Enable rich LSIF hover information.
  src/EditorFeatures/Core/LanguageServer/Handlers/Hover/HoverHandler.cs
  src/Features/Lsif/Generator/Generator.cs
  src/Features/Lsif/GeneratorTest/HoverTests.vb
Labels: Area-IDE

#64055 Use the source-built version of ref packs and don't use app host when building in source-build
  Directory.Build.targets
Labels: Area-Infrastructure

#64553 Fix regex detection for StringSyntax attribute on params parameters
  src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs
  src/Features/Core/Portable/EmbeddedLanguages/EmbeddedLanguageDetector.cs
  src/Features/Core/Portable/EmbeddedLanguages/Json/LanguageServices/JsonLanguageDetector.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexLanguageDetector.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SemanticFacts/CSharpSemanticFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SemanticFacts/ISemanticFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SemanticFacts/ISemanticFactsExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SemanticFacts/VisualBasicSemanticFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/SemanticsFactsService/AbstractSemanticFactsService.cs
Labels: Area-IDE

#64593 Fix symbol completions after `required` keyword
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/BoolKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ByteKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/CharKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/DecimalKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/DoubleKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/FloatKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/IntKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/LongKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/NativeIntegerKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ObjectKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/SByteKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ShortKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/StringKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/UIntKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ULongKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/UShortKeywordRecommenderTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTreeExtensions.cs
Labels: Area-IDE, Community

#64405 Use required members for option types
  eng/Versions.props
  src/Compilers/Core/Portable/InternalUtilities/CompilerFeatureRequiredAttribute.cs
  src/Compilers/Core/Portable/InternalUtilities/RequiredMemberAttribute.cs
  src/Compilers/Core/Portable/InternalUtilities/SetsRequiredMembersAttribute.cs
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodBase.cs
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/EditorFeatures/TestUtilities/Utilities/CSharpCodeActionOptions.cs
  src/EditorFeatures/TestUtilities/Utilities/VisualBasicCodeActionOptions.cs
  src/EditorFeatures/VisualBasicTest/ExtractMethod/ExtractMethodTests.vb
  src/Features/Core/Portable/MetadataAsSource/AbstractMetadataAsSourceService.cs
  src/Features/LanguageServer/Protocol/Features/Options/CodeActionOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/CodeCleanupOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/CodeGenerationOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/ExtractMethodOptionsStorage.cs
  src/Tools/ExternalAccess/OmniSharp.CSharp/Formatting/OmniSharpSyntaxFormattingOptionsFactory.cs
  src/Tools/ExternalAccess/OmniSharp/MetadataAsSource/OmniSharpMetadataAsSourceService.cs
  src/VisualStudio/Core/Test.Next/Services/VisualStudioDiagnosticAnalyzerExecutorTests.cs
  src/Workspaces/Core/Portable/ExtractMethod/ExtractMethodOptions.cs
  src/Workspaces/CoreTestUtilities/VBOptionsFactory.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeCleanup/CodeCleanupOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeGeneration/CleanCodeGenerationOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeGeneration/CodeGenerationOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/CodeActionOptions.cs
Labels: Area-IDE

#64575 Treat *.g.i.cs|vb files as design-time-only in EnC
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/Features/Core/Portable/EditAndContinue/Extensions.cs
Labels: Area-Interactive, Interactive-EnC

#64555 Beef up resiliency of DeclareAsNullable fixer
  src/Analyzers/CSharp/CodeFixes/Nullable/CSharpDeclareAsNullableCodeFixProvider.cs
Labels: Area-IDE

#64583 [LSP] Fix race during shutdown and exit
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework.Example/ExampleLanguageServer.cs
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/AbstractLanguageServer.cs
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/Handlers/ExitHandler.cs
  src/Features/LanguageServer/Protocol/Handler/ServerLifetime/ExitHandler.cs
  src/Features/LanguageServer/Protocol/RoslynLanguageServer.cs
Labels: Area-IDE, LSP

#64349 Fix DecodeForwardIteratorRecord to accept strings w/o null terminator
  src/Compilers/Core/CodeAnalysisTest/PDB/CustomDebugInfoReaderTests.cs
  src/Dependencies/CodeAnalysis.Debugging/CustomDebugInfoReader.cs
Labels: Area-Interactive

#64487 Track EA APIs
  docs/ide/external-access.md
  eng/Versions.props
  src/Tools/ExternalAccess/.editorconfig
  src/Tools/ExternalAccess/Apex/InternalAPI.Shipped.txt
  src/Tools/ExternalAccess/Apex/InternalAPI.Unshipped.txt
  src/Tools/ExternalAccess/Apex/Microsoft.CodeAnalysis.ExternalAccess.Apex.csproj
  src/Tools/ExternalAccess/AspNetCore/InternalAPI.Shipped.txt
  src/Tools/ExternalAccess/AspNetCore/InternalAPI.Unshipped.txt
  src/Tools/ExternalAccess/AspNetCore/Microsoft.CodeAnalysis.ExternalAccess.AspNetCore.csproj
  src/Tools/ExternalAccess/Debugger/InternalAPI.Shipped.txt
  src/Tools/ExternalAccess/Debugger/InternalAPI.Unshipped.txt
  src/Tools/ExternalAccess/Debugger/Microsoft.CodeAnalysis.ExternalAccess.Debugger.csproj
  src/Tools/ExternalAccess/FSharp/InternalAPI.Shipped.txt
  src/Tools/ExternalAccess/FSharp/InternalAPI.Unshipped.txt
  src/Tools/ExternalAccess/FSharp/Microsoft.CodeAnalysis.ExternalAccess.FSharp.csproj
  src/Tools/ExternalAccess/FSharp/Navigation/IFSharpDocumentNavigationService.cs
  src/Tools/ExternalAccess/FSharp/Structure/FSharpBlockSpan.cs
  src/Tools/ExternalAccess/OmniSharp.CSharp/InternalAPI.Shipped.txt
  src/Tools/ExternalAccess/OmniSharp.CSharp/InternalAPI.Unshipped.txt
  src/Tools/ExternalAccess/OmniSharp.CSharp/Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.CSharp.csproj
  src/Tools/ExternalAccess/OmniSharp/CodeRefactorings/WorkspaceServices/IOmniSharpSymbolRenamedCodeActionOperationFactoryWorkspaceService.cs
  src/Tools/ExternalAccess/OmniSharp/InternalAPI.Shipped.txt
  src/Tools/ExternalAccess/OmniSharp/InternalAPI.Unshipped.txt
  src/Tools/ExternalAccess/OmniSharp/Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.csproj
  src/Tools/ExternalAccess/OmniSharp/Structure/OmniSharpBlockSpan.cs
  src/Tools/ExternalAccess/OmniSharp/Structure/OmniSharpBlockTypes.cs
  src/Tools/ExternalAccess/Razor/InternalAPI.Shipped.txt
  src/Tools/ExternalAccess/Razor/InternalAPI.Unshipped.txt
  src/Tools/ExternalAccess/Razor/Microsoft.CodeAnalysis.ExternalAccess.Razor.csproj
  src/Tools/ExternalAccess/Xamarin.Remote/InternalAPI.Shipped.txt
  src/Tools/ExternalAccess/Xamarin.Remote/InternalAPI.Unshipped.txt
  src/Tools/ExternalAccess/Xamarin.Remote/Microsoft.CodeAnalysis.ExternalAccess.Xamarin.Remote.csproj
Labels: Area-Infrastructure

#64582 Update NavigateTo tests to support AllInOneSearch
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpNavigateTo.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpSourceGenerators.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/InputInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/ShellInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicNavigateTo.cs
Labels: Area-IDE

#64470 Catch deconstruction ref escape errors in invocation escape analysis
  src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/BoundTree/OutDeconstructVarPendingInference.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers, New Language Feature - Ref Fields

#64414 Set val escape on expression variables
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceLocalSymbol.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers

#64231 Remove TextDocumentState.sourceText
  src/Workspaces/Core/Portable/Workspace/Solution/AdditionalDocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/AnalyzerConfigDocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/DocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratedDocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Workspace_Editor.cs
Labels: Area-IDE

#64627 Revert "Set val escape on expression variables"
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceLocalSymbol.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers

#64352 Load CompletionProvider from references in background
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/CrefCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SuggestionModeCompletionProviderTests.cs
  src/EditorFeatures/Core/Interactive/Completion/InteractiveCommandCompletionService.cs
  src/EditorFeatures/Test/Completion/CompletionServiceTests.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/EditorFeatures/Test2/IntelliSense/CompletionServiceTests.vb
  src/EditorFeatures/Test2/IntelliSense/CompletionServiceTests_Exclusivitiy.vb
  src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests.vb
  src/EditorFeatures/TestUtilities/Completion/AbstractCompletionProviderTests.cs
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/CrefCompletionProviderTests.vb
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/SuggestionModeCompletionProviderTests.vb
  src/Features/CSharp/Portable/Completion/CSharpCompletionService.cs
  src/Features/Core/Portable/Common/AbstractProjectExtensionProvider.cs
  src/Features/Core/Portable/Completion/CommonCompletionService.cs
  src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs
  src/Features/Core/Portable/Completion/CompletionService.cs
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/Api/VSTypeScriptCompletionServiceWithProviders.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionResolveTests.cs
  src/Features/VisualBasic/Portable/Completion/VisualBasicCompletionService.vb
  src/Tools/ExternalAccess/FSharp/Completion/FSharpCompletionServiceWithProviders.cs
  src/VisualStudio/CSharp/Impl/LanguageService/CSharpCreateServicesOnTextViewConnection.cs
  src/VisualStudio/Core/Def/LanguageService/AbstractCreateServicesOnTextViewConnection.cs
Labels: Area-IDE, OnDeckForQB

#64622 Workaround crash in spellchecking in snippet layer
  src/EditorFeatures/CSharpTest/Diagnostics/SpellCheck/SpellCheckTests.cs
  src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs
Labels: Area-IDE

#64620 Remove lock from MAS code to prevent UI delays
  src/EditorFeatures/CSharpTest/PdbSourceDocument/NullResultMetadataAsSourceFileProvider.cs
  src/EditorFeatures/Test/MetadataAsSource/MetadataAsSourceTests.cs
  src/Features/Core/Portable/MetadataAsSource/DecompilationMetadataAsSourceFileProvider.cs
  src/Features/Core/Portable/MetadataAsSource/IMetadataAsSourceFileProvider.cs
  src/Features/Core/Portable/MetadataAsSource/MetadataAsSourceFileService.cs
  src/Features/Core/Portable/PdbSourceDocument/PdbSourceDocumentMetadataAsSourceFileProvider.cs
Labels: Area-IDE

#64637 Log exception directly at the point where it occurs
  src/Features/Core/Portable/SymbolSearch/Windows/SymbolSearchUpdateEngine.Update.cs
Labels: Area-IDE

#64619 Catch deconstruction ref escape errors in invocation escape analysis (#64470)
  src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/BoundTree/OutDeconstructVarPendingInference.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers, New Language Feature - Ref Fields, OnDeckForQB

#64633 Revert: Revert "Set val escape on expression variables (#64414)"
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/BoundTree/OutDeconstructVarPendingInference.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceLocalSymbol.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers, New Language Feature - Ref Fields

#64636 update Microsoft.CodeAnalysis.Testing version
  eng/Versions.props
Labels: Area-Infrastructure

#64618 Include preview version when installing .NET runtime
  eng/pipelines/test-windows-job-single-machine.yml
Labels: Area-Infrastructure

#64643 Update NuGet Package history
  docs/wiki/NuGet-packages.md
Labels: Area-Infrastructure

#64641 Don't suggest name after unbound yield identifier
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs
Labels: Area-IDE

#64642 [LSP] Pass in Razor language server kind
  src/EditorFeatures/Core/LanguageServer/AbstractInProcLanguageClient.cs
  src/Features/LanguageServer/Protocol/CSharpVisualBasicLanguageServerFactory.cs
  src/Features/LanguageServer/Protocol/ILanguageServerFactory.cs
  src/Tools/ExternalAccess/Razor/RazorLanguageServerFactoryWrapper.cs
Labels: Area-IDE

#64594 Change operator when negating relational patterns with numeric values
  src/EditorFeatures/CSharpTest/InvertLogical/InvertLogicalTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFactsExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxKinds.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpSyntaxGeneratorInternal.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions_Negate.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/SyntaxGeneratorInternalExtensions/SyntaxGeneratorInternal.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/LanguageServices/VisualBasicSyntaxGeneratorInternal.vb
Labels: Area-IDE, Community

#64648 Revert "Load CompletionProvider from references in background"
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/CrefCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SuggestionModeCompletionProviderTests.cs
  src/EditorFeatures/Core/Interactive/Completion/InteractiveCommandCompletionService.cs
  src/EditorFeatures/Test/Completion/CompletionServiceTests.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/EditorFeatures/Test2/IntelliSense/CompletionServiceTests.vb
  src/EditorFeatures/Test2/IntelliSense/CompletionServiceTests_Exclusivitiy.vb
  src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests.vb
  src/EditorFeatures/TestUtilities/Completion/AbstractCompletionProviderTests.cs
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/CrefCompletionProviderTests.vb
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/SuggestionModeCompletionProviderTests.vb
  src/Features/CSharp/Portable/Completion/CSharpCompletionService.cs
  src/Features/Core/Portable/Common/AbstractProjectExtensionProvider.cs
  src/Features/Core/Portable/Completion/CommonCompletionService.cs
  src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs
  src/Features/Core/Portable/Completion/CompletionService.cs
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/Api/VSTypeScriptCompletionServiceWithProviders.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionResolveTests.cs
  src/Features/VisualBasic/Portable/Completion/VisualBasicCompletionService.vb
  src/Tools/ExternalAccess/FSharp/Completion/FSharpCompletionServiceWithProviders.cs
  src/VisualStudio/CSharp/Impl/LanguageService/CSharpCreateServicesOnTextViewConnection.cs
  src/VisualStudio/Core/Def/LanguageService/AbstractCreateServicesOnTextViewConnection.cs
Labels: Area-IDE

#64650 Use the source-built version of ref packs and don't use app host when building in source-build.
  Directory.Build.targets
Labels: Area-Infrastructure

#63850 Update DefiniteAssignment Pass to Account for Local Default Parameter Values
  src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs
  src/Compilers/CSharp/Test/Emit2/FlowAnalysis/FlowTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs
Labels: Area-Compilers

#64662 Handle implicit object creation in remove unused values code fixer
  src/Analyzers/CSharp/CodeFixes/RemoveUnusedParametersAndValues/CSharpRemoveUnusedValuesCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/RemoveUnusedParametersAndValues/RemoveUnusedValueAssignmentTests.cs
  src/Analyzers/Core/CodeFixes/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs
Labels: Area-IDE

#64621 Set val escape on expression variables (#64414)
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/BoundTree/OutDeconstructVarPendingInference.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceLocalSymbol.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers

#64561 Check value scopes match in ref reassignment
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Generated/ErrorFacts.Generated.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
Labels: Area-Compilers, New Language Feature - Ref Fields

#64651 Do not yield the UI thread between an undo unit being created and committed
  src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs
Labels: Area-IDE

#64472 Move to new image
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#64635 Improve GenerateMethod for VB implicit call case
  src/EditorFeatures/VisualBasicTest/Diagnostics/GenerateMethod/GenerateMethodTests.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Extensions/ExpressionSyntaxExtensions.vb
  src/Workspaces/VisualBasic/Portable/Extensions/SemanticModelExtensions.vb
Labels: Area-IDE

#64612 Fix early attribute decoding when an argument is interpolated string
  src/Compilers/CSharp/Portable/Binder/EarlyWellKnownAttributeBinder.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_WellKnownAttributes.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Project.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeGeneration/CodeGenerationOptions.cs
Labels: Area-Compilers, Community

#64675 Make packed LSIF generator behave more like a tool.
  src/Features/Lsif/Generator/Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.csproj
Labels: Area-IDE

#64673 Skip Workspace ProjectProperties integration test
  src/VisualStudio/IntegrationTest/New.IntegrationTests/Workspace/WorkspaceBase.cs
Labels: Area-IDE

#64488 Revert "Revert "Implement IAttributeOperation (#59369)""
  src/Analyzers/Core/Analyzers/RemoveUnnecessarySuppressions/SuppressMessageAttributeState.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs
  src/Compilers/CSharp/Portable/Binder/ContextualAttributeBinder.cs
  src/Compilers/CSharp/Portable/Compilation/AttributeSemanticModel.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IArgument.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IAttributeOperation.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IFieldReferenceExpression.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs
  src/Compilers/Core/Portable/Generated/OperationKind.Generated.cs
  src/Compilers/Core/Portable/Generated/Operations.Generated.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraph.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/Operations/OperationInterfaces.xml
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Test/Core/Compilation/ControlFlowGraphVerifier.cs
  src/Compilers/Test/Core/Compilation/OperationTreeVerifier.cs
  src/Compilers/Test/Core/Compilation/TestOperationVisitor.cs
  src/Compilers/VisualBasic/Portable/Binding/AttributeSemanticModel.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Attributes.vb
  src/Compilers/VisualBasic/Portable/BoundTree/BoundNodes.xml
  src/Compilers/VisualBasic/Portable/Generated/BoundNodes.xml.Generated.vb
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb
  src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_IAttributeOperation.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_IFieldReferenceExpression.vb
  src/Compilers/VisualBasic/Test/Semantic/Semantics/GetSemanticInfoTests.vb
Labels: Area-Compilers

#64649 Save CustomAttributesBag before post decoding well known attributes.
  src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs
  src/Compilers/VisualBasic/Test/Semantic/Semantics/LambdaTests.vb
Labels: Area-Compilers

#64683 Fix crash in MetadataAsSource when opening loose (misc) files
  src/Features/Core/Portable/MetadataAsSource/MetadataAsSourceFileService.cs
Labels: Area-IDE, OnDeckForQB

#64686 Update references to ref fields spec
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceLocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers

#64685 Make titles for IDE0029 and IDE0030 unique
  src/Analyzers/Core/Analyzers/AnalyzersResources.resx
  src/Analyzers/Core/Analyzers/UseCoalesceExpression/AbstractUseCoalesceExpressionDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseCoalesceExpression/AbstractUseCoalesceExpressionForNullableDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.cs.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.de.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.es.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.fr.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.it.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.ja.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.ko.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.pl.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.pt-BR.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.ru.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.tr.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.zh-Hans.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.zh-Hant.xlf
  src/Analyzers/Core/CodeFixes/UseCoalesceExpression/UseCoalesceExpressionCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseCoalesceExpression/UseCoalesceExpressionForNullableCodeFixProvider.cs
Labels: Area-IDE, Community

#63835 Add support for Suppression/Configuration fixes for build-only diagno…
  src/EditorFeatures/Test/Diagnostics/DiagnosticAnalyzerServiceTests.cs
  src/Features/Core/Portable/Diagnostics/BuildOnlyDiagnosticsService.cs
  src/Features/Core/Portable/Diagnostics/IBuildOnlyDiagnosticsService.cs
  src/Features/LanguageServer/Protocol/Features/CodeFixes/CodeFixService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_BuildSynchronization.cs
  src/VisualStudio/Core/Def/TableDataSource/Suppression/VisualStudioDiagnosticListSuppressionStateService.cs
  src/VisualStudio/Core/Def/TableDataSource/Suppression/VisualStudioSuppressionFixService.cs
  src/VisualStudio/Core/Def/TaskList/ExternalErrorDiagnosticUpdateSource.cs
  src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs
  src/VisualStudio/Core/Test/Diagnostics/ExternalDiagnosticUpdateSourceTests.vb
Labels: Area-IDE

#64380 Support `scoped` keyword in declaration expressions.
  src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/BoundTree/VariablePendingInference.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/Symbols/Source/GlobalExpressionVariable.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceLocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberFieldSymbol.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxFacts.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxNodeExtensions.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefLocalsAndReturnsTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationScopeParsingTests.cs
Labels: Area-Compilers, New Language Feature - Ref Fields

#64668 Create source texts for open buffers with the new default source hash algorithm
  src/Compilers/Core/Portable/Text/SourceHashAlgorithms.cs
  src/EditorFeatures/Text/Extensions.SnapshotSourceText.cs
  src/Features/LanguageServer/Protocol/Handler/DocumentChanges/DidOpenHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Workspaces/LspWorkspaceManagerTests.cs
Labels: Area-IDE

#64684 Update M.CA.Testing version to 1.1.2-beta1.22512.1
  eng/Versions.props
Labels: Area-Infrastructure

#64708 Fix static virtual interface members not included in type parameter completion
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs
Labels: Area-IDE, Community, OnDeckForQB

#64695 Allow packages to be not published
  eng/publish-assets.ps1
Labels: Area-Infrastructure

#64709 Add EE and VS impl packages to PublishData.json
  eng/config/PublishData.json
Labels: Area-Infrastructure

#64647 VB ConvertTupleToStruct should not include NullableAttributes in it
  src/EditorFeatures/CSharpTest/ConvertTupleToStruct/ConvertTupleToStructTests.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/VisualBasicCodeRefactoringVerifier`1+Test.cs
  src/EditorFeatures/Test/MetadataAsSource/MetadataAsSourceTests.cs
  src/EditorFeatures/VisualBasicTest/ConvertTupleToStruct/ConvertTupleToStructTests.vb
  src/Workspaces/CSharp/Portable/CodeGeneration/AttributeGenerator.cs
  src/Workspaces/Core/Portable/CodeGeneration/AbstractCodeGenerationService.cs
  src/Workspaces/Core/Portable/CodeGeneration/CodeGenerationHelpers.cs
  src/Workspaces/VisualBasic/Portable/CodeGeneration/AttributeGenerator.vb
  src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicCodeGenerationService.vb
Labels: Area-IDE

#64221 Remove exportProvider parameter from TestWorkspace ctor
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/AbstractCSharpCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/AbstractInteractiveCSharpCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/CrefCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ObjectInitializerCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/OverrideCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/PartialMethodCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SuggestionModeCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/CSharpEditAndContinueAnalyzerTests.cs
  src/EditorFeatures/CSharpTest/Interactive/NavigateTo/InteractiveNavigateToTests.cs
  src/EditorFeatures/CSharpTest/NavigateTo/NavigateToTests.cs
  src/EditorFeatures/CSharpTest/Workspaces/WorkspaceTests_EditorFeatures.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/AbstractCodeActionOrUserDiagnosticTest.cs
  src/EditorFeatures/Test/Diagnostics/DiagnosticAnalyzerServiceTests.cs
  src/EditorFeatures/Test2/IntelliSense/SignatureHelpControllerTests.vb
  src/EditorFeatures/Test2/PasteTracking/PasteTrackingTestState.vb
  src/EditorFeatures/TestUtilities/Completion/AbstractArgumentProviderTests`1.cs
  src/EditorFeatures/TestUtilities/Completion/AbstractCompletionProviderTests.cs
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/EditorFeatures/TestUtilities/NavigateTo/AbstractNavigateToTests.cs
  src/EditorFeatures/TestUtilities/Workspaces/CSharpTestWorkspaceFixture.cs
  src/EditorFeatures/TestUtilities/Workspaces/InteractiveCSharpTestWorkspaceFixture.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspaceFixture.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace_Create.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace_XmlConsumption.cs
  src/EditorFeatures/TestUtilities/Workspaces/VisualBasicTestWorkspaceFixture.cs
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/AbstractVisualBasicCompletionProviderTests.vb
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/CrefCompletionProviderTests.vb
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/ImplementsClauseCompletionProviderTests.vb
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/ObjectInitializerCompletionProviderTests.vb
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/OverrideCompletionProviderTests.vb
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/SuggestionModeCompletionProviderTests.vb
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/SymbolCompletionProviderTests.vb
  src/EditorFeatures/VisualBasicTest/NavigateTo/NavigateToTests.vb
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/AbstractPullDiagnosticTestsBase.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/AdditionalFileDiagnosticsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/WorkspaceProjectDiagnosticsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Miscellaneous/LspMiscellaneousFilesWorkspaceTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/VSTypeScriptHandlerTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Workspaces/LspWorkspaceManagerTests.cs
  src/VisualStudio/CSharp/Test/DocumentOutline/DocumentOutlineTestsBase.cs
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioAnalyzerTests.vb
Labels: Area-IDE

#64716 Fix static virtual interface members not included in type parameter completion
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs
Labels: Area-IDE, OnDeckForQB

#64718 Do not offer name completion after dotted expressions which do not bind to types
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.DeclarationInfo.cs
Labels: Area-IDE

#64719 Revert "Revert "Load CompletionProvider from references in background""
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/CrefCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SuggestionModeCompletionProviderTests.cs
  src/EditorFeatures/Core/Interactive/Completion/InteractiveCommandCompletionService.cs
  src/EditorFeatures/Test/Completion/CompletionServiceTests.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/EditorFeatures/Test2/IntelliSense/CompletionServiceTests.vb
  src/EditorFeatures/Test2/IntelliSense/CompletionServiceTests_Exclusivitiy.vb
  src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests.vb
  src/EditorFeatures/TestUtilities/Completion/AbstractCompletionProviderTests.cs
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/CrefCompletionProviderTests.vb
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/SuggestionModeCompletionProviderTests.vb
  src/Features/CSharp/Portable/Completion/CSharpCompletionService.cs
  src/Features/Core/Portable/Common/AbstractProjectExtensionProvider.cs
  src/Features/Core/Portable/Completion/CommonCompletionService.cs
  src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs
  src/Features/Core/Portable/Completion/CompletionService.cs
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/Api/VSTypeScriptCompletionServiceWithProviders.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionResolveTests.cs
  src/Features/VisualBasic/Portable/Completion/VisualBasicCompletionService.vb
  src/Tools/ExternalAccess/FSharp/Completion/FSharpCompletionServiceWithProviders.cs
  src/VisualStudio/CSharp/Impl/LanguageService/CSharpCreateServicesOnTextViewConnection.cs
  src/VisualStudio/Core/Def/LanguageService/AbstractCreateServicesOnTextViewConnection.cs
Labels: Area-IDE

#64513 Respond to missed feedback
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/RequestExecutionQueue.cs
  src/Features/LanguageServer/Protocol/RoslynRequestExecutionQueue.cs
Labels: Area-IDE

#64694 Inline Hints - ArgumentOutOfRangeException
  src/EditorFeatures/Core.Wpf/InlineHints/InlineHintsTagger.cs
Labels: Area-IDE, OnDeckForQB

#64726 Skip csharpsourcegenerators.findreferencesforfilewithdefinitioninsourcegeneratedfile
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpSourceGenerators.cs
Labels: Area-Infrastructure

#64722 Ensure we include a projectId along with our ProjectChanged notification
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
Labels: Area-IDE, OnDeckForQB

#64623 Do not use CWT for Task<Compilation>
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/SpecializedTasks.cs
Labels: Area-IDE

#64689 [LSP] Write lsp logs to xunit output during tests
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/EditorFeatures/TestUtilities/LanguageServer/TestOutputLspLogger.cs
  src/Features/LanguageServer/ProtocolUnitTests/CodeActions/CodeActionResolveTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/CodeActions/CodeActionsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/CodeActions/RunCodeActionsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionResolveTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Definitions/GoToDefinitionTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Definitions/GoToTypeDefinitionTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/AbstractPullDiagnosticTestsBase.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/AdditionalFileDiagnosticsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/WorkspaceProjectDiagnosticsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/DocumentChanges/DocumentChangesTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/FoldingRanges/FoldingRangesTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Formatting/FormatDocumentOnTypeTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Formatting/FormatDocumentRangeTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Formatting/FormatDocumentTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Highlights/DocumentHighlightTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Hover/HoverTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/InlineCompletions/InlineCompletionsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/LanguageServerTargetTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Miscellaneous/LspMiscellaneousFilesWorkspaceTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/OnAutoInsert/OnAutoInsertTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Ordering/RequestOrderingTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/ProjectContext/GetTextDocumentWithContextHandlerTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/References/FindAllReferencesHandlerTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/References/FindImplementationsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Rename/RenameTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/AbstractSemanticTokensTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/SemanticTokensRangeTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/SignatureHelp/SignatureHelpTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/SpellCheck/SpellCheckTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Symbols/DocumentSymbolsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Symbols/WorkspaceSymbolsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/VSTypeScriptHandlerTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/ValidateBreakableRange/ValidateBreakableRangeTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Workspaces/LspWorkspaceManagerTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Workspaces/LspWorkspaceRegistrationServiceTests.cs
  src/Tools/IdeBenchmarks/Lsp/LspCompletionBenchmarks.cs
  src/VisualStudio/CSharp/Test/DocumentOutline/DocumentOutlineTests.cs
  src/VisualStudio/CSharp/Test/DocumentOutline/DocumentOutlineTestsBase.cs
  src/VisualStudio/LiveShare/Test/AbstractLiveShareRequestHandlerTests.cs
  src/VisualStudio/LiveShare/Test/ProjectsHandlerTests.cs
Labels: Area-IDE, LSP

#64691 Fix ArgumentOutOfRangeException from using speculative semantic model
  src/Workspaces/CSharp/Portable/SemanticModelReuse/CSharpSemanticModelReuseLanguageService.cs
  src/Workspaces/Core/Portable/SemanticModelReuse/AbstractSemanticModelReuseLanguageService.cs
  src/Workspaces/CoreTest/SemanticModelReuse/SemanticModelReuseTests.cs
  src/Workspaces/VisualBasic/Portable/SemanticModelReuse/VisualBasicSemanticModelReuseLanguageService.vb
Labels: Area-IDE

#64734 Correct package names in PublishData.json
  eng/config/PublishData.json
Labels: Area-Infrastructure

#64729 Generate different DocumentIds for duplicate generators
  src/VisualStudio/Core/Def/Workspace/SourceGeneratedFileManager.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/DiagnosticItem/SourceGeneratorItem.cs
  src/Workspaces/Core/Portable/SourceGeneratorTelemetry/ISourceGeneratorTelemetryCollectorWorkspaceService.cs
  src/Workspaces/Core/Portable/SourceGeneratorTelemetry/SourceGeneratorTelemetryCollectorWorkspaceService.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationAndGeneratorDriverTranslationAction_Actions.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratedDocumentIdentity.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratorIdentity.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
  src/Workspaces/CoreTestUtilities/TestGeneratorReference.cs
Labels: Area-IDE

#64735 Update solution using existing helper
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
Labels: Area-IDE

#64736 Add new helper to allow more code to use consistent transformer
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
Labels: Area-IDE

#64738 Use the required keyword and newer attributes
  src/Workspaces/Core/Portable/SourceGeneratorTelemetry/SourceGeneratorTelemetryCollectorWorkspaceService.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratorIdentity.cs
Labels: Area-IDE

#64667 Update VS Platform NuGet package version
  eng/Versions.props
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/TextViewWindow_InProc.cs
Labels: Area-Infrastructure, OnDeckForQB

#64158 Use workspace services to implement test hooks
  src/EditorFeatures/Test2/Diagnostics/AbstractCrossLanguageUserDiagnosticTest.vb
  src/EditorFeatures/Test2/Diagnostics/GenerateFromUsage/GenerateMethodCrossLanguageTests.vb
  src/EditorFeatures/Test2/Diagnostics/GenerateFromUsage/GenerateVariableCrossLanguageTests.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.vb
  src/EditorFeatures/Test2/Rename/RenameEngineResult.vb
  src/EditorFeatures/Test2/Workspaces/TryFindSourceDefinitionTests.vb
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs
  src/EditorFeatures/TestUtilities/Workspaces/WorkspaceTestLogger.cs
  src/VisualStudio/Core/Def/DebuggerIntelliSense/DebuggerIntellisenseWorkspace.cs
  src/VisualStudio/Core/Def/Utilities/VisualStudioWorkpacePartialSolutionsTestHook.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/VisualStudioWorkspace_InProc.cs
  src/Workspaces/Core/Portable/Workspace/Host/IWorkpacePartialSolutionsTestHook.cs
  src/Workspaces/Core/Portable/Workspace/Host/IWorkspaceTestLogger.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
  src/Workspaces/CoreTestUtilities/WorkpacePartialSolutionsTestHook.cs
Labels: Area-IDE

#64740 Add binding redirects for compiler binaries for the LSIF tool
  src/Features/Lsif/Generator/Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.csproj
Labels: Area-IDE

#64634 Speculative semantic model - create child member models for attributes and parameter default values.
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/Compilation/AttributeSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/InitializerSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.SpeculativeMemberSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/MethodBodySemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/PublicSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/SpeculativeSemanticModelWithMemberModel.cs
  src/Compilers/CSharp/Portable/Compilation/SpeculativeSyntaxTreeSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs
  src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel_RegionAnalysisContext.cs
  src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs
  src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs
  src/Compilers/Core/Portable/Operations/Operation.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
Labels: Area-Compilers

#64745 Upgrade our compiler to 4.4.0-2.final
  eng/Versions.props
Labels: Area-Infrastructure

#64742 Cache indices against our PEReference object, not the underlying metadata ID
  src/EditorFeatures/Test/FindSymbols/SymbolTreeInfoTests.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.SymbolComputer.cs
  src/Workspaces/Core/Portable/FindSymbols/Declarations/DeclarationFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/DependentTypeFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfoCacheService.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Metadata.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Serialization.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Source.cs
Labels: Area-IDE

#64746 Recover from the Exception in IdleProcessor
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingIdleProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/IdleProcessor.cs
Labels: Area-IDE

#64604 Name anonymous delegate parameters
  src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNames.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedDelegateSymbol.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_LifetimeAnnotation.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
Labels: Area-Compilers, New Feature - Lambda Improvements

#64660 Track local constant usage in attributes
  src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs
  src/Compilers/CSharp/Test/Emit2/FlowAnalysis/FlowTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs
Labels: Area-Compilers

#64760 Move the SymbolTree index cache off of the incremental-analyzer subsystem
  src/EditorFeatures/Test2/Diagnostics/AbstractCrossLanguageUserDiagnosticTest.vb
  src/EditorFeatures/Test2/Diagnostics/AddImport/AddImportCrossLanguageTests.vb
  src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs
  src/Features/Core/Portable/AddImport/SearchScopes/MetadataSymbolsSearchScope.cs
  src/Features/Core/Portable/AddImport/SearchScopes/SourceSymbolsProjectSearchScope.cs
  src/Features/Core/Portable/AddImport/SymbolReferenceFinder.cs
  src/Features/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfoIncrementalAnalyzer.cs
  src/Features/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfoIncrementalAnalyzerProvider.cs
  src/Tools/AnalyzerRunner/IncrementalAnalyzerRunner.cs
  src/Workspaces/Core/Portable/FindSymbols/IRemoteSymbolFinderService.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/ISymbolTreeInfoCacheService.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/MetadataInfo.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfoCacheService.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfoCacheServiceFactory.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Serialization.cs
  src/Workspaces/Remote/ServiceHub/Services/SymbolFinder/RemoteSymbolFinderService.cs
Labels: Area-IDE

#64752 Refactor LSP server exit / shutdown / dispose logic for resiliency and clarity
  src/EditorFeatures/Core/LanguageServer/AbstractInProcLanguageClient.cs
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework.Example/ExampleLanguageServer.cs
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework.UnitTests/RequestExecutionQueueTests.cs
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework.UnitTests/TestExampleLanguageServer.cs
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/AbstractLanguageServer.cs
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/Handlers/ShutdownHandler.cs
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/ILifeCycleManager.cs
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/Microsoft.CommonLanguageServerProtocol.Framework.csproj
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/RequestExecutionQueue.cs
  src/Features/LanguageServer/Protocol/Handler/ServerLifetime/LspServiceLifeCycleManager.cs
  src/Features/LanguageServer/Protocol/Handler/ServerLifetime/ShutdownHandler.cs
  src/Features/LanguageServer/Protocol/RoslynLanguageServer.cs
  src/Features/LanguageServer/Protocol/RoslynRequestExecutionQueue.cs
  src/Features/LanguageServer/ProtocolUnitTests/LanguageServerTargetTests.cs
  src/Tools/ExternalAccess/Razor/IRazorLanguageServerTarget.cs
  src/Tools/ExternalAccess/Razor/RazorLanguageServerTargetWrapper.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageClient/XamlInProcLanguageClient.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/XamlLanguageServer.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/XamlRequestDispatcherFactory.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/XamlRequestExecutionQueue.cs
Labels: Area-IDE, LSP

#64680 Scoped implicitly-typed lambda parameters
  src/Compilers/CSharp/Portable/BoundTree/NullabilityRewriter.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/Symbols/MethodSymbolExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LambdaParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceParameterSymbol.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers, New Language Feature - Ref Fields

#64576 Use IAsyncEnumerable in NavigateTo OOP calls.
  eng/Versions.props
  src/EditorFeatures/CSharpTest/NavigateTo/NavigateToSearcherTests.cs
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/VSTypeScriptNavigateToSearchService.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.CachedDocumentSearch.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.GeneratedDocumentSearch.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.InProcess.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.NormalSearch.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.cs
  src/Features/Core/Portable/NavigateTo/INavigateToSearchService.cs
  src/Features/Core/Portable/NavigateTo/IRemoteNavigateToSearchService.cs
  src/Features/Core/Portable/NavigateTo/NavigateToSearcher.cs
  src/Features/Core/Portable/NavigateTo/RoslynNavigateToItem.cs
  src/Setup/DevDivInsertionFiles/DevDivInsertionFiles.csproj
  src/Tools/ExternalAccess/FSharp/Internal/NavigateTo/FSharpNavigateToSearchService.cs
  src/Tools/IdeCoreBenchmarks/NavigateToBenchmarks.cs
  src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
  src/Workspaces/Core/Portable/Remote/RemoteHostClient.cs
  src/Workspaces/Core/Portable/Remote/RemoteServiceConnection.cs
  src/Workspaces/Core/Portable/Shared/Extensions/IAsyncEnumerableExtensions.cs
  src/Workspaces/CoreTest/Remote/ServiceDescriptorTests.cs
  src/Workspaces/Remote/Core/BrokeredServiceConnection.cs
  src/Workspaces/Remote/Core/ServiceDescriptors.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.PinnedSolution.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs
  src/Workspaces/Remote/ServiceHub/Services/NavigateToSearch/RemoteNavigateToSearchService.cs
Labels: Area-IDE

#64626 Unskip CSharpSoruceGenerators.InvokeNavigateToForGeneratedFile test
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpSourceGenerators.cs
Labels: Area-IDE

#64786 Trigger background analyzer load when document open
  src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs
  src/Features/Core/Portable/Completion/CompletionService.cs
  src/VisualStudio/Core/Def/LanguageService/AbstractCreateServicesOnTextViewConnection.cs
Labels: Area-IDE

#64749 Read required project properties from evaluation data
  src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets
  src/Compilers/Core/MSBuildTask/Microsoft.VisualBasic.Core.targets
  src/VisualStudio/CSharp/Test/ProjectSystemShim/CSharpHelpers.cs
  src/VisualStudio/CSharp/Test/ProjectSystemShim/TestEvaluationData.cs
  src/VisualStudio/Core/Def/ProjectSystem/BuildPropertyNames.cs
  src/VisualStudio/Core/Def/ProjectSystem/CPS/IWorkspaceProjectContextFactory.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProjectFactory.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs
Labels: Area-IDE

#64781 Fix MSBuild tests and run them in CI again
  eng/Versions.props
  src/Workspaces/MSBuildTest/Resources/SolutionFiles/VisualBasic.sln
  src/Workspaces/MSBuildTest/TestFiles/Resources.cs
  src/Workspaces/MSBuildTest/Utilities/VisualStudioMSBuildInstalled.cs
  src/Workspaces/MSBuildTest/VisualStudioMSBuildWorkspaceTests.cs
  src/Workspaces/MSBuildTest/WorkspaceTestBase.cs
Labels: Area-Infrastructure

#64707 Additional tests for ref fields
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/RefFieldParsingTests.cs
  src/EditorFeatures/CSharpTest/Classification/SyntacticClassifierTests.cs
Labels: Area-Compilers, New Language Feature - Ref Fields

#62703 Improve SyntaxTree/Node.Dump()
  src/Compilers/CSharp/Portable/Syntax/CSharpSyntaxNode.cs
  src/Compilers/CSharp/Portable/Syntax/CSharpSyntaxTree.cs
  src/Compilers/Test/Utilities/CSharp/SyntaxTreeExtensions.cs
Labels: Area-Compilers

#64551 Don't format regions inside inactive conditionals
  src/Analyzers/CSharp/Tests/Formatting/FormattingAnalyzerTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Engine/Trivia/CSharpTriviaFormatter.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/TriviaEngine/AbstractTriviaFormatter.cs
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/Trivia/VisualBasicTriviaFormatter.vb
Labels: Area-IDE, Community

#64790 Add more symbol publishing packages to PublishData.json
  eng/config/PublishData.json
Labels: Area-Infrastructure

#64791 Make `TargetFramework.NetCoreApp` use `Net70`
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_CallerInfoAttributes.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RawInterpolationTests_Handler.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/Compilers/Test/Core/Compilation/CompilationExtensions.cs
  src/Compilers/Test/Core/TargetFrameworkUtil.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
  src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_CallerArgumentExpression.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/AttributeTests_UnmanagedCallersOnly.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/DefaultInterfaceImplementationTests.vb
Labels: Area-Compilers

#64588 "Generate method" codefix supports 'in' parameters
  src/EditorFeatures/CSharpTest/Diagnostics/GenerateMethod/GenerateMethodTests.cs
  src/Features/CSharp/Portable/GenerateMember/GenerateParameterizedMember/CSharpGenerateParameterizedMemberService.cs
Labels: Area-IDE, Community

#64808 Ensure we include a projectId along with our ProjectChanged notifications
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
Labels: Area-IDE, OnDeckForQB

#64810 Snippets - turn feature off by default for 17.4
  src/Features/Core/Portable/Completion/CompletionOptions.cs
Labels: Area-IDE, OnDeckForQB

#64805 Move parts of official build onto new vm images
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#64799 Export correct type for VisualStudioWorkpacePartialSolutionsTestHook.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs
  src/VisualStudio/Core/Def/Utilities/VisualStudioWorkpacePartialSolutionsTestHook.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/VisualStudioWorkspace_InProc.cs
  src/Workspaces/Core/Portable/Workspace/Host/IWorkpacePartialSolutionsTestHook.cs
  src/Workspaces/Core/Portable/Workspace/Host/WorkpacePartialSolutionsTestHook.cs
Labels: Area-IDE

#64616 Use IAsyncEnumerable in DesignerAttributeScanning as well.
  src/Features/Core/Portable/DesignerAttribute/AbstractDesignerAttributeIncrementalAnalyzer.cs
  src/Features/Core/Portable/DesignerAttribute/DesignerAttributeData.cs
  src/Features/Core/Portable/DesignerAttribute/DesignerAttributeHelpers.cs
  src/Features/Core/Portable/DesignerAttribute/IDesignerAttributeDiscoveryService.cs
  src/Features/Core/Portable/DesignerAttribute/IRemoteDesignerAttributeDiscoveryService.cs
  src/VisualStudio/CSharp/Test/DesignerAttribute/DesignerAttributeServiceTests.cs
  src/VisualStudio/Core/Def/DesignerAttribute/VisualStudioDesignerAttributeService.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/Workspaces/Core/Portable/Shared/Extensions/IAsyncEnumerableExtensions.cs
  src/Workspaces/Remote/Core/ServiceDescriptors.cs
  src/Workspaces/Remote/ServiceHub/Services/DesignerAttributeDiscovery/RemoteDesignerAttributeDiscoveryService.cs
  src/Workspaces/Remote/ServiceHub/Services/NavigateToSearch/RemoteNavigateToSearchService.cs
Labels: Area-IDE

#64802 Implement equality semantics for async tagger tags.
  src/EditorFeatures/Core.Wpf/InlineDiagnostics/InlineDiagnosticsTaggerProvider.cs
  src/EditorFeatures/Core.Wpf/LineSeparators/LineSeparatorTaggerProvider.cs
  src/EditorFeatures/Core.Wpf/StringIndentation/StringIndentationTag.cs
  src/EditorFeatures/Core.Wpf/StringIndentation/StringIndentationTaggerProvider.cs
  src/EditorFeatures/Core/BraceMatching/BraceHighlightTag.cs
  src/EditorFeatures/Core/BraceMatching/BraceHighlightingViewTaggerProvider.cs
  src/EditorFeatures/Core/Classification/Semantic/AbstractSemanticOrEmbeddedClassificationViewTaggerProvider.cs
  src/EditorFeatures/Core/Diagnostics/AbstractDiagnosticsAdornmentTaggerProvider.RoslynErrorTag.cs
  src/EditorFeatures/Core/Diagnostics/AbstractDiagnosticsAdornmentTaggerProvider.cs
  src/EditorFeatures/Core/Diagnostics/DiagnosticsClassificationTaggerProvider.cs
  src/EditorFeatures/Core/Diagnostics/DiagnosticsSquiggleTaggerProvider.cs
  src/EditorFeatures/Core/Diagnostics/DiagnosticsSuggestionTaggerProvider.cs
  src/EditorFeatures/Core/EditAndContinue/ActiveStatementTaggerProvider.cs
  src/EditorFeatures/Core/InlineHints/InlineHintDataTag.cs
  src/EditorFeatures/Core/InlineHints/InlineHintsDataTaggerProvider.cs
  src/EditorFeatures/Core/KeywordHighlighting/HighlighterViewTaggerProvider.cs
  src/EditorFeatures/Core/KeywordHighlighting/KeywordHighlightTag.cs
  src/EditorFeatures/Core/ReferenceHighlighting/ReferenceHighlightingViewTaggerProvider.cs
  src/EditorFeatures/Core/Structure/AbstractStructureTaggerProvider.cs
  src/EditorFeatures/Core/Structure/StructureTag.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_IEqualityComparer.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.cs
  src/EditorFeatures/Test/Tagging/AsynchronousTaggerTests.cs
  src/Features/Core/Portable/Common/TaggedText.cs
  src/Features/Core/Portable/FindUsages/DefinitionItem.DetachedDefinitionItem.cs
  src/Features/Core/Portable/InheritanceMargin/InheritanceMarginItem.cs
  src/Features/Core/Portable/InheritanceMargin/InheritanceTargetItem.cs
  src/VisualStudio/Core/Def/InheritanceMargin/InheritanceMarginTag.cs
  src/VisualStudio/Core/Def/InheritanceMargin/InheritanceMarginTaggerProvider.cs
Labels: Area-IDE

#64801 Revert "Read required project properties from evaluation data"
  src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets
  src/Compilers/Core/MSBuildTask/Microsoft.VisualBasic.Core.targets
  src/VisualStudio/CSharp/Test/ProjectSystemShim/CSharpHelpers.cs
  src/VisualStudio/CSharp/Test/ProjectSystemShim/TestEvaluationData.cs
  src/VisualStudio/Core/Def/ProjectSystem/BuildPropertyNames.cs
  src/VisualStudio/Core/Def/ProjectSystem/CPS/IWorkspaceProjectContextFactory.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProjectFactory.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs
Labels: Area-IDE

#64824 Additional tests for UTF-8 string literals feature
  src/Compilers/CSharp/Test/Semantic/Semantics/Utf8StringsLiteralsTests.cs
Labels: Area-Compilers, New Feature - Utf8StringLiterals

#64832 Update 17.4 PreReleaseVersionLabel to 4 for preview 4
  eng/Versions.props
Labels: Area-Infrastructure

#64829 Snippets - turn on by default in 17.5
  src/Features/Core/Portable/Completion/CompletionOptions.cs
Labels: Area-IDE

#64834 Fix Color Contrast For STE Close Button
  src/VisualStudio/Core/Def/StackTraceExplorer/StackTraceExplorerRoot.xaml
Labels: Area-IDE, UX Review Not Required
