Repository dotnet/roslyn, pull requests merged in 2022-08, with the labels that each got.

#63106 Hot Reload: Fix reloadable type regression
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueClosureTests.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/DeltaMetadataWriter.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/SymbolChanges.cs
Labels: Area-Interactive

#63122 Wait for reverse oop-to-host asset-sync calls to finish before the last oop call returns back to the host.
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.InFlightSolution.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
Labels: Area-IDE

#63110 Use ToImmutableAndClear when using a pooled builder with a known length
  src/Analyzers/CSharp/CodeFixes/ConvertSwitchStatementToExpression/ConvertSwitchStatementToExpressionCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseImplicitOrExplicitType/UseExplicitTypeCodeFixProvider.cs
  src/Analyzers/Core/Analyzers/Helpers/DiagnosticHelper.cs
  src/Features/Core/Portable/AddParameter/AbstractAddParameterCodeFixProvider.cs
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionCodeFixProvider.RemoveSuppressionCodeAction.BatchFixer.cs
  src/Features/Core/Portable/CodeRefactorings/SyncNamespace/AbstractChangeNamespaceService.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.SymbolComputer.cs
  src/Features/Core/Portable/DocumentHighlighting/AbstractDocumentHighlightsService.cs
  src/Features/Core/Portable/ExtractClass/ExtractClassWithDialogCodeAction.cs
  src/Features/Core/Portable/GenerateMember/GenerateParameterizedMember/AbstractGenerateDeconstructMethodService.State.cs
  src/Features/Core/Portable/GenerateType/AbstractGenerateTypeService.cs
  src/Features/Core/Portable/Wrapping/ChainedExpression/AbstractChainedExpressionWrapper.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DocumentAnalysisExecutor.cs
  src/Features/LanguageServer/Protocol/Features/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs
  src/Workspaces/Core/Portable/Diagnostics/DiagnosticData.cs
  src/Workspaces/Core/Portable/Rename/IRemoteRenamerService.cs
  src/Workspaces/Remote/ServiceHub/Host/AssetProvider.cs
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassification/RemoteSemanticClassificationService.Caching.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ImmutableArrayExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ObjectWriterExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Utilities/NameGenerator.cs
Labels: Area-IDE

#63112 Simplify construction of hte RemoteWorkspace
  src/VisualStudio/Core/Test.Next/Services/AssetProviderTests.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/VisualStudio/Core/Test.Next/Services/SolutionServiceTests.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemoteHostClientProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspaceManager.cs
Labels: Area-IDE

#62865 FindMethodSymbolInType - handle the case when a type definition is resolved to a type in a different module.
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/MemberRefMetadataDecoder.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/MetadataDecoder.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Metadata/PE/NoPia.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Metadata/PE/NoPiaLocalHideAndTypeSubstitutionTests.cs
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/MemberRefMetadataDecoder.vb
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/MetadataDecoder.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Metadata/PE/NoPia.vb
Labels: Area-Compilers

#63109 Avoid intermediary array allocation when computing checksums
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState_Checksum.cs
  src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs
  src/Workspaces/CoreTest/UtilityTest/SpecializedTasksTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/SpecializedTasks.cs
Labels: Area-IDE

#63010 Record C# 11 status
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation

#63121 Use snapshot services
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/DocumentExtensions.cs
Labels: Area-IDE

#63132 Ensure we don't call out into arbitrary code directly when setting up our cache state
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.InFlightSolution.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace_SolutionCaching.cs
Labels: Area-IDE

#62854 Keep the host solution pinned on the remote workspace side while performing an inline-rename session
  src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs
  src/Workspaces/Core/Portable/Rename/IRemoteRenamerService.cs
  src/Workspaces/Core/Portable/Rename/Renamer.cs
  src/Workspaces/Remote/ServiceHub/Services/Renamer/RemoteRenamerService.cs
Labels: Area-IDE

#62897 Issue delete and insert edits when changing parameters
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/TopLevelEditingTests.cs
  src/EditorFeatures/VisualBasicTest/EditAndContinue/TopLevelEditingTests.vb
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueDiagnosticDescriptors.cs
  src/Features/Core/Portable/EditAndContinue/RudeEditKind.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
Labels: Area-Interactive

#63006 Check the right matches in lambdas
  src/EditorFeatures/CSharpTest/EditAndContinue/ActiveStatementTests.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
Labels: Area-Interactive

#63133 Add checks to ensure that we don't have any unexpected exceptions corrupting state
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
Labels: Area-IDE

#63141 Do not count a cached solution as causing us to think it is sitll alive on teh host side
  src/Workspaces/Remote/Core/SolutionAssetStorage.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.InFlightSolution.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace_SolutionCaching.cs
Labels: Area-IDE

#63153 Remove solution crawler pre-indexing of documents
  src/Features/Core/Portable/IncrementalCaches/SyntaxTreeInfoIncrementalAnalyzerProvider.cs
  src/Tools/IdeCoreBenchmarks/NavigateToBenchmarks.cs
  src/Workspaces/Core/Portable/FindSymbols/Shared/AbstractSyntaxIndex_Persistence.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex.cs
  src/Workspaces/Core/Portable/FindSymbols/TopLevelSyntaxTree/TopLevelSyntaxTreeIndex_Persistence.cs
Labels: Area-IDE

#63162 [dev17.4-vs-deps port of #63161] Revert "When we're removing the last project, fire SolutionRemoved"
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioProject.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioProjectFactory.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioProjectTests/WorkspaceChangedEventTests.vb
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpFindReferences.cs
Labels: Area-Analyzers, Needs Shiproom Approval

#62845 ci build cleanup
  azure-pipelines.yml
  eng/pipelines/build-windows-job.yml
Labels: Area-Infrastructure

#63084 Put correct function call for Return Attributes
  src/Workspaces/Core/Portable/Editing/SyntaxEditorExtensions.cs
  src/Workspaces/CoreTest/Editing/SyntaxEditorTests.cs
Labels: Area-IDE

#63118 Avoid cases in OOP of accessing .Solution.Workspace
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/VisualStudio/Core/Test.Next/Services/SolutionServiceTests.cs
  src/Workspaces/Core/Portable/Shared/Extensions/DocumentExtensions.cs
  src/Workspaces/Core/Portable/Shared/Extensions/ProjectExtensions.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Document.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/ProjectExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Workspace/Mef/MefLanguageServices.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Workspace/Mef/MefWorkspaceServices.cs
Labels: Area-IDE

#63165 Semantic Snippets - Add logging
  src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-IDE

#63173 Fix usage of unshared mscorlib ref in numeric IntPtr tests
  src/Compilers/CSharp/Test/Emit2/Emit/NumericIntPtrTests.cs
Labels: Area-Compilers, Test, Flaky

#63123 Select SuggestionItem if there's no match in the list
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/ItemManager.CompletionListUpdater.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/EditorFeatures/TestUtilities2/Intellisense/TestState.vb
Labels: Area-IDE

#63185 Revert "Rename `LifetimeAnnotationAttribute` to `ScopedRefAttribute` and simplify (#63009)"
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/Emitter/Model/PEAssemblyBuilder.cs
  src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs
  src/Compilers/CSharp/Portable/Lowering/ClosureConversion/SynthesizedClosureMethod.cs
  src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs
  src/Compilers/CSharp/Portable/Symbols/DeclarationScope.cs
  src/Compilers/CSharp/Portable/Symbols/EmbeddableAttributes.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ParameterHelpers.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceConstructorSymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceDelegateMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodOrUserDefinedOperatorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceParameterSymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedEmbeddedLifetimeAnnotationAttributeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_LifetimeAnnotation.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/Portable/MetadataReader/PEModule.cs
  src/Compilers/Core/Portable/Symbols/Attributes/AttributeDescription.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/Core/Portable/WellKnownTypes.cs
  src/Compilers/Test/Utilities/CSharp/LifetimeAnnotationAttributesVisitor.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
Labels: Area-Compilers

#63179 Skip rethrow
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DocumentAnalysisExecutor.cs
Labels: Area-IDE

#62952 Move "generic attributes" feature into C# 11
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/BindingTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs
Labels: Area-Compilers

#63161 Revert "When we're removing the last project, fire SolutionRemoved"
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioProject.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioProjectFactory.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioProjectTests/WorkspaceChangedEventTests.vb
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpFindReferences.cs
Labels: Area-Analyzers, Needs Shiproom Approval

#63196 Revert "Merge pull request #62854 from CyrusNajmabadi/renameOOP5"
  src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs
  src/Workspaces/Core/Portable/Rename/IRemoteRenamerService.cs
  src/Workspaces/Core/Portable/Rename/Renamer.cs
  src/Workspaces/Remote/ServiceHub/Services/Renamer/RemoteRenamerService.cs
Labels: Area-IDE, Area-Infrastructure

#63083 Handle scenario where initial completion list contains only a single non-roslyn item
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/ItemManager.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_HandleNonRoslynCompletionSources.vb
Labels: Area-IDE

#62956 Enable source build for ASP.NET external access project
  src/Tools/ExternalAccess/AspNetCore/Microsoft.CodeAnalysis.ExternalAccess.AspNetCore.csproj
Labels: Area-Infrastructure

#62941 Ref fields feature requires ByRefFields runtime flag
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Symbols/AssemblySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/MetadataOrSourceAssemblySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/MissingCorLibrarySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberFieldSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
  src/Compilers/VisualBasic/Test/Semantic/Semantics/RefFieldTests.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolDisplay/SymbolDisplayTests.vb
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/ExpressionCompilerTests.cs
Labels: Area-Compilers, New Language Feature - Ref Fields

#63146 Remove bogus assert around C# import scopes.
  src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs
  src/Compilers/Core/Portable/Compilation/IImportScope.cs
  src/Scripting/CSharpTest/InteractiveSessionTests.cs
Labels: Area-Compilers

#63175 Disable flakey tests
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpArgumentProvider.cs
Labels: Area-IDE

#63180 Remove one of our out of proc analyzers
  src/VisualStudio/Core/Def/Telemetry/AbstractWorkspaceTelemetryService.cs
  src/Workspaces/Core/Portable/Telemetry/IWorkspaceTelemetryService.cs
  src/Workspaces/Remote/ServiceHub/Services/ProjectTelemetry/ApiUsageIncrementalAnalyzerProvider.cs
Labels: Area-IDE

#60219 New hot reload interfaces
  eng/Versions.props
  src/EditorFeatures/Core/EditAndContinue/Contracts/ContractWrappers.cs
  src/EditorFeatures/Core/EditAndContinue/DebuggerContractVersionCheck.cs
  src/EditorFeatures/Core/EditAndContinue/EditAndContinueLanguageService.cs
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/EditorFeatures/Test/EditAndContinue/EmitSolutionUpdateResultsTests.cs
  src/EditorFeatures/Test/EditAndContinue/RemoteEditAndContinueServiceTests.cs
  src/Features/Core/Portable/EditAndContinue/Contracts/EditAndContinue/ManagedModuleUpdate.cs
  src/Features/Core/Portable/EditAndContinue/Contracts/EditAndContinue/ManagedModuleUpdateStatus.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSession.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueCapabilities.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/Core/Portable/EditAndContinue/EmitSolutionUpdateResults.cs
  src/Features/Core/Portable/EditAndContinue/ModuleUpdate.cs
  src/Features/Core/Portable/EditAndContinue/ModuleUpdateStatus.cs
  src/Features/Core/Portable/EditAndContinue/PendingSolutionUpdate.cs
  src/Features/Core/Portable/EditAndContinue/Remote/RemoteDebuggingSessionProxy.cs
  src/Features/Core/Portable/EditAndContinue/SolutionUpdate.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/API/UnitTestingHotReloadService.cs
  src/Features/Core/Portable/ExternalAccess/Watch/Api/WatchHotReloadService.cs
  src/Tools/ExternalAccess/Debugger/GlassTestsHotReloadService.cs
  src/Workspaces/Remote/ServiceHub/Services/EditAndContinue/RemoteEditAndContinueService.cs
Labels: Area-Interactive

#63218 Todo settings
  src/EditorFeatures/TestUtilities/TodoComments/AbtractTodoCommentTests.cs
  src/Features/Core/Portable/TodoComments/AbstractTodoCommentsIncrementalAnalyzer.cs
  src/Features/Core/Portable/TodoComments/TodoCommentDescriptor.cs
  src/Features/LanguageServer/Protocol/Features/TodoComments/TodoCommentOptionsStorage.cs
  src/VisualStudio/Core/Def/Options/VisualStudioSettingsOptionPersister.cs
  src/VisualStudio/Core/Def/TaskList/CommentTaskTokenSerializer.cs
  src/VisualStudio/Core/Def/TaskList/CommentTaskTokenSerializerProvider.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/Workspaces/Core/Portable/TodoComments/TodoCommentOptions.cs
Labels: Area-IDE

#63168 Use syntaxkinds pattern in more places
  src/Features/Core/Portable/DocumentHighlighting/AbstractDocumentHighlightsService.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/PropertySymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Create.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFactsExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxKinds.vb
Labels: Area-IDE

#62958 Structural Error Cases for Lambda Default Parameters
  src/Compilers/CSharp/Portable/Binder/Binder.QueryUnboundLambdaState.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Lambda.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LambdaParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ParameterHelpers.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/LambdaDiscardParametersTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ParserErrorMessageTests.cs
Labels: Area-Compilers

#63243 create regular PRs for main-vs-deps insertion
  eng/config/PublishData.json
Labels: Area-Infrastructure

#63217 Additional filter texts
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/CommitManager.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/Helpers.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/ItemManager.CompletionListUpdater.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/RecentItemsManager.cs
  src/EditorFeatures/Core/LanguageServer/Handlers/Completion/CompletionHandler.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/EditorFeatures/Test2/IntelliSense/CompletionRulesTests.vb
  src/EditorFeatures/TestUtilities2/Intellisense/TestState.vb
  src/Features/Core/Portable/Completion/CompletionHelper.cs
  src/Features/Core/Portable/Completion/CompletionItem.cs
  src/Features/Core/Portable/Completion/CompletionService.cs
  src/Features/Core/Portable/Completion/MatchResult.cs
  src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/Snippets/SnippetCompletionItem.cs
  src/Features/Core/Portable/Snippets/SnippetData.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractConsoleSnippetProvider.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractSnippetProvider.cs
  src/Workspaces/Core/Portable/PatternMatching/PatternMatch.cs
Labels: Area-IDE

#63169 Emit MetadataUpdateOriginalTypeAttribute
  src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTestBase.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/SymbolChanges.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/Core/Portable/WellKnownTypes.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
Labels: Area-Compilers

#63183 Remove one of our out of proc analyzers.
  src/VisualStudio/Core/Def/ProjectTelemetry/VisualStudioProjectTelemetryService.cs
  src/Workspaces/Core/Portable/ProjectTelemetry/IProjectTelemetryListener.cs
  src/Workspaces/Core/Portable/ProjectTelemetry/IRemoteProjectTelemetryService.cs
  src/Workspaces/Core/Portable/ProjectTelemetry/ProjectTelemetryData.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemostHostClient.cs
  src/Workspaces/Remote/Core/ServiceDescriptors.cs
  src/Workspaces/Remote/ServiceHub/Services/ProjectTelemetry/RemoteProjectTelemetryIncrementalAnalyzer.cs
  src/Workspaces/Remote/ServiceHub/Services/ProjectTelemetry/RemoteProjectTelemetryIncrementalAnalyzerProvider.cs
  src/Workspaces/Remote/ServiceHub/Services/ProjectTelemetry/RemoteProjectTelemetryService.cs
Labels: Area-IDE

#63261 Move PatternMatching*Tests to Emit2
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTestBase.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests2.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests3.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests4.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests5.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests_Global.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests_ListPatterns.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests_Scope.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternSwitchTests.cs
Labels: Area-Compilers

#62945 Fix SyntaxGenerator not working correctly with 'required'
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpAccessibilityFacts.cs
Labels: Area-IDE, Community

#63236 Make bootstrap failures easier to debug
  src/Compilers/Core/MSBuildTask/ManagedCompiler.cs
  src/Compilers/Core/MSBuildTask/ValidateBootstrap.cs
Labels: Area-Compilers

#63062 Upgrade to .NET 7 P6 SDK
  eng/Versions.props
  eng/targets/Imports.targets
  global.json
  src/Compilers/VisualBasic/Test/Semantic/Semantics/CompoundAssignment.vb
Labels: Area-Infrastructure

#63268 Document build correctness leg
  docs/compilers/Bootstrap Builds.md
  docs/compilers/images/bootstrap-logs.png
  eng/test-build-correctness.ps1
Labels: Area-Infrastructure

#63046 Disallow using ScopedRef in source
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Symbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_LifetimeAnnotation.cs
Labels: Area-Compilers, New Language Feature - Ref Fields

#63206 Fix analyzer action state tracking for partial analysis
  src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.SyntaxReferenceAnalyzerStateData.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs
  src/Compilers/Test/Core/Diagnostics/CommonDiagnosticAnalyzers.cs
Labels: Area-Analyzers, Area-Compilers

#63244 Mark shipped APIs
  src/Compilers/CSharp/Portable/PublicAPI.Shipped.txt
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Core/Portable/PublicAPI.Shipped.txt
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Features/Core/Portable/PublicAPI.Shipped.txt
  src/Features/Core/Portable/PublicAPI.Unshipped.txt
  src/Workspaces/Core/Portable/PublicAPI.Shipped.txt
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
Labels: Area-Infrastructure, api-approved

#63065 Auto-default ref fields with a null ref-assignment
  src/Compilers/CSharp/Portable/FlowAnalysis/FlowAnalysisPass.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_FixedStatement.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/StructConstructorTests.cs
Labels: Area-Compilers

#62869 Derive type names analyzer from AbstractBuiltInCodeStyleDiagnosticAnalyzer
  src/Analyzers/Core/Analyzers/AbstractBuiltInCodeStyleDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/Analyzers.projitems
  src/Analyzers/Core/Analyzers/AnalyzersResources.resx
  src/Analyzers/Core/Analyzers/SimplifyTypeNames/SimplifyTypeNamesDiagnosticAnalyzerBase.cs
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.cs.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.de.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.es.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.fr.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.it.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.ja.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.ko.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.pl.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.pt-BR.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.ru.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.tr.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.zh-Hans.xlf
  src/Analyzers/Core/Analyzers/xlf/AnalyzersResources.zh-Hant.xlf
  src/EditorFeatures/CSharpTest/Squiggles/ErrorSquiggleProducerTests.cs
  src/EditorFeatures/VisualBasicTest/Squiggles/ErrorSquiggleProducerTests.vb
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/SimplifyThisOrMe/AbstractSimplifyThisOrMeDiagnosticAnalyzer.cs
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Workspaces/Core/Portable/WorkspacesResources.resx
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.cs.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.de.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.es.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.fr.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.it.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ja.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ko.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.pl.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.pt-BR.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ru.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.tr.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.zh-Hans.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.zh-Hant.xlf
Labels: Area-IDE, Community

#63275 Fix value usage info for VB 'For .. To'
  src/Analyzers/VisualBasic/Tests/MakeFieldReadonly/MakeFieldReadonlyTests.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/OperationExtensions.cs
Labels: Area-IDE, Community

#63271 Fix capability granting for auto-properties
  src/EditorFeatures/CSharpTest/EditAndContinue/TopLevelEditingTests.cs
  src/EditorFeatures/VisualBasicTest/EditAndContinue/TopLevelEditingTests.vb
  src/Features/CSharp/Portable/EditAndContinue/SyntaxUtilities.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
  src/Features/VisualBasic/Portable/EditAndContinue/SyntaxUtilities.vb
Labels: Area-Interactive, Interactive-EnC

#63209 Consider types with ref fields as managed
  src/Compilers/CSharp/Portable/Symbols/BaseTypeAnalysis.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers, New Language Feature - Ref Fields

#62670 Support renaming multiple symbols in RenameLanguageService
  src/EditorFeatures/Test/Rename/RenameRewriterTests.Verifier.cs
  src/EditorFeatures/Test/Rename/RenameRewriterTests.cs
  src/Workspaces/CSharp/Portable/Rename/CSharpRenameRewriterLanguageService.cs
  src/Workspaces/Core/Portable/Rename/ConflictEngine/ConflictResolver.Session.cs
  src/Workspaces/Core/Portable/Rename/ConflictEngine/LocationRenameContextOverlappingException.cs
  src/Workspaces/Core/Portable/Rename/ConflictEngine/StringOrCommentReplacementTextConflictException.cs
  src/Workspaces/Core/Portable/Rename/IRenameRewriterLanguageService.cs
  src/Workspaces/Core/Portable/Rename/LocationRenameContext.cs
  src/Workspaces/Core/Portable/Rename/RenameRewriterParameters.cs
  src/Workspaces/Core/Portable/Rename/RenameSymbolContext.cs
  src/Workspaces/Core/Portable/Rename/RenameUtilities.cs
  src/Workspaces/Core/Portable/Rename/Renamer.cs
  src/Workspaces/Core/Portable/Rename/SymbolicRenameLocations.ReferenceProcessing.cs
  src/Workspaces/Core/Portable/Rename/SymbolicRenameLocations.cs
  src/Workspaces/VisualBasic/Portable/Rename/VisualBasicRenameRewriterLanguageService.vb
Labels: Area-IDE

#63245 Move options subsystem over to using SolutionService snapshots.
  src/Analyzers/Core/CodeFixes/UseConditionalExpression/AbstractUseConditionalExpressionCodeFixProvider.cs
  src/EditorFeatures/VisualBasic/Utilities/CommandHandlers/AbstractImplementAbstractClassOrInterfaceCommandHandler.vb
  src/Features/CSharp/Portable/CodeRefactorings/InlineTemporary/InlineTemporaryCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/ImplementInterface/CSharpImplementInterfaceCodeFixProvider.cs
  src/Features/Core/Portable/AddImport/AbstractAddImportCodeFixProvider.cs
  src/Features/Core/Portable/AddPackage/AbstractAddPackageCodeFixProvider.cs
  src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsRefactoringProvider.cs
  src/Features/Core/Portable/ConvertTupleToStruct/AbstractConvertTupleToStructCodeRefactoringProvider.cs
  src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs
  src/Features/Core/Portable/FullyQualify/AbstractFullyQualifyCodeFixProvider.cs
  src/Features/Core/Portable/ImplementAbstractClass/AbstractImplementAbstractClassCodeFixProvider.cs
  src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.DisposePatternCodeAction.cs
  src/Features/Core/Portable/SpellCheck/AbstractSpellCheckCodeFixProvider.cs
  src/Features/Core/Portable/Wrapping/AbstractWrappingCodeRefactoringProvider.cs
  src/Features/LanguageServer/Protocol/Features/Options/CodeActionOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/GlobalCodeActionOptionsProvider.cs
  src/Features/LanguageServer/Protocol/Features/Options/ImplementTypeOptionsStorage.cs
  src/Features/VisualBasic/Portable/ImplementInterface/VisualBasicImplementInterfaceCodeFixProvider.vb
  src/Tools/ExternalAccess/FSharp/Internal/Editor/FSharpSmartIndentProvider.cs
  src/Tools/ExternalAccess/OmniSharp/CodeActions/OmniSharpCodeActionOptions.cs
  src/Tools/ExternalAccess/OmniSharp/Options/OmnisharpLegacyGlobalOptionsWorkspaceService.cs
  src/Workspaces/Core/Portable/ExtractMethod/ExtractMethodOptions.cs
  src/Workspaces/Core/Portable/OrganizeImports/OrganizeImportsOptions.cs
  src/Workspaces/Core/Portable/Remote/RemoteOptionsProvider.cs
  src/Workspaces/Core/Portable/Rename/ConflictEngine/ConflictResolver.cs
  src/Workspaces/Core/Portable/Rename/LightweightRenameLocations.cs
  src/Workspaces/Core/Portable/Rename/Renamer.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Project.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
  src/Workspaces/Remote/ServiceHub/Services/ClientOptionProviders.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/AddImport/AddImportPlacementOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeCleanup/CodeCleanupOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeGeneration/CleanCodeGenerationOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeGeneration/CodeGenerationOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/DocumentFormattingOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/LineFormattingOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/SyntaxFormattingOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyleOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Simplification/SimplifierOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CodeActions/CSharpCodeFixOptionsProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeActions/CodeFixOptionsProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/CodeActionOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Options/OptionsProvider.cs
Labels: Area-IDE

#63142 Avoid resolving parameter.Type in ReportParameterErrors()
  src/Compilers/CSharp/Portable/Symbols/Source/ParameterHelpers.cs
  src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers

#63263 Check interpolated string arguments in Binder.GetValEscape()
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
Labels: Area-Compilers

#62999 Convert to record
  src/Compilers/Test/Core/Traits/Traits.cs
  src/EditorFeatures/CSharpTest/ConvertToRecord/ConvertToRecordTests.cs
  src/Features/CSharp/Portable/CSharpFeaturesResources.resx
  src/Features/CSharp/Portable/CodeRefactorings/ConvertToRecord/CSharpConvertToRecordRefactoringProvider.cs
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.cs.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.de.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.es.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.fr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.it.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ja.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ko.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pl.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pt-BR.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ru.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.tr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hans.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hant.xlf
  src/Features/Core/Portable/CodeRefactorings/PredefinedCodeRefactoringProviderNames.cs
Labels: Area-IDE, New Language Feature - Records

#63269 EnC: Log deltas and messages to disk
  src/EditorFeatures/Test/EditAndContinue/TraceLogTests.cs
  src/Features/Core/Portable/Debugging/DebugInformationReaderProvider.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSession.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSessionId.cs
  src/Features/Core/Portable/EditAndContinue/DocumentAnalysisResults.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/Core/Portable/EditAndContinue/TraceLog.cs
  src/Features/Core/Portable/Emit/CompilationOutputs.cs
Labels: Area-Interactive

#63038 Test PDB checksums emitted for source generated files
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs
  src/Compilers/Test/Core/SourceGeneration/TestSourceGenerator.cs
  src/EditorFeatures/Test/EditAndContinue/TestSourceGenerator.cs
  src/Test/PdbUtilities/Reader/PdbValidation.cs
Labels: Area-Compilers

#63297 Fix key for VisualFSharp.UnitTests IVT
  src/Tools/ExternalAccess/FSharp/Microsoft.CodeAnalysis.ExternalAccess.FSharp.csproj
Labels: Area-Infrastructure

#62939 Remove prefer system hash code from EditorConfig UI
  src/VisualStudio/CSharp/Test/EditorConfigSettings/DataProvider/DataProviderTests.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/DataProvider/CodeStyle/CommonCodeStyleSettingsProvider.cs
Labels: Area-IDE, Community

#63298 Resolve nuget warnings
  src/Workspaces/MSBuildTest/Resources/NuGet.Config
Labels: Area-Infrastructure

#63277 Semantic Snippets - Fix how snippets appear in the completion list
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpConsoleSnippetCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpIfSnippetCompletionProviderTests.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Features/Core/Portable/Completion/CompletionService_GetCompletions.cs
  src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/Snippets/SnippetCompletionItem.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/Snippets/SnippetData.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractConsoleSnippetProvider.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractIfSnippetProvider.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractSnippetProvider.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/ISnippetProvider.cs
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
Labels: Area-IDE

#63130 Add support for incremental analysis for method body editing scenario…
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DocumentAnalysisExecutor.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.ActiveFileState.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer_MemberSpans.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs
  src/Features/LanguageServer/Protocol/Features/Options/DiagnosticOptionsStorage.cs
  src/VisualStudio/Core/Def/TableDataSource/Suppression/VisualStudioSuppressionFixService.cs
  src/Workspaces/Core/Portable/Diagnostics/DiagnosticData.cs
  src/Workspaces/Core/Portable/Diagnostics/DiagnosticDataLocation.cs
Labels: Area-Analyzers

#62680 Use the correct option for splitting comments
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
Labels: Area-IDE, Community

#63300 Backport some integration test skips to 17.3
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpUpdateProjectToAllowUnsafe.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpUpgradeProject.cs
Labels: Area-IDE

#63330 Fix required completion in records
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/KeywordCompletionProviderTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/RequiredKeywordRecommender.cs
Labels: Area-IDE, Community

#63352 Skip flaky test AnalyzerConfigDocumentOpenedClosedEvents
  src/EditorFeatures/Test/SolutionCrawler/WorkCoordinatorTests.cs
Labels: Area-Analyzers

#63344 Revert "Merge pull request #61568 from CyrusNajmabadi/localFuncindexing"
  src/EditorFeatures/CSharpTest/NavigateTo/NavigateToTests.cs
  src/Workspaces/CSharp/Portable/FindSymbols/CSharpDeclaredSymbolInfoFactoryService.cs
  src/Workspaces/Core/Portable/FindSymbols/Shared/AbstractSyntaxIndex_Persistence.cs
  src/Workspaces/Core/Portable/LanguageServices/DeclaredSymbolFactoryService/AbstractDeclaredSymbolInfoFactoryService.cs
  src/Workspaces/VisualBasic/Portable/FindSymbols/VisualBasicDeclaredSymbolInfoFactoryService.vb
Labels: Area-IDE, Needs Shiproom Approval

#63347 Fix generator error on command line
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_SimpleName.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SharedInputNodes.cs
  src/Compilers/Test/Utilities/CSharp/TestOptions.cs
  src/Compilers/Test/Utilities/CSharp/ThrowingMetadataReferenceResolver.cs
Labels: Area-Compilers

#63343 Update the job names used in report ci times script
  scripts/report-ci-times.ps1
Labels: Area-Infrastructure

#63345 Allow passing a reference type field by reference when spilling to temps
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs
Labels: Area-Compilers

#63342 Don't provide refactoring for VB Move Static Members when IncompleteMemberSyntax is found
  src/EditorFeatures/VisualBasicTest/MoveStaticMembers/VisualBasicMoveStaticMembersTests.vb
  src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb
Labels: Area-IDE

#62797 correctness build optimizations
  azure-pipelines.yml
  eng/build.sh
  eng/evaluate-changed-paths.sh
  eng/pipelines/evaluate-changed-files-group.yml
  eng/pipelines/evaluate-changed-files.yml
  src/VisualStudio/IntegrationTest/TestUtilities/Microsoft.VisualStudio.IntegrationTest.Utilities.csproj
Labels: Area-Infrastructure

#63364 remove -vs-deps branches from publishing
  eng/config/PublishData.json
Labels: Area-Infrastructure

#63356 Merge release/dev17.4-vs-deps to release/dev17.4
  eng/Versions.props
  eng/targets/GenerateServiceHubConfigurationFiles.targets
  src/EditorFeatures/CSharpTest/SpellCheck/SpellCheckFixerProviderTests.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/CompletionSessionData.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/CompletionSource.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/ItemManager.CompletionListUpdater.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/ItemManager.cs
  src/EditorFeatures/Core/SpellCheck/RoslynSpellCheckFixerProvider.cs
  src/EditorFeatures/TestUtilities/SpellCheck/AbstractSpellCheckFixerProviderTests.cs
  src/EditorFeatures/TestUtilities/SpellCheck/AbstractSpellCheckSpanTests.cs
  src/EditorFeatures/TestUtilities2/Intellisense/MockCompletionPresenter.vb
  src/EditorFeatures/TestUtilities2/Microsoft.CodeAnalysis.EditorFeatures.Test.Utilities2.vbproj
  src/Tools/BuildBoss/StructuredLoggerCheckerUtil.cs
  src/VisualStudio/Core/Test/DebuggerIntelliSense/TestState.vb
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/LightBulbHelper.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/Editor_InProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/LightBulbHelper.cs
  src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb
  src/VisualStudio/VisualBasic/Impl/LanguageService/VisualBasicPackage.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-Infrastructure

#63367 Revert "Consider types with ref fields as managed (#63209)"
  src/Compilers/CSharp/Portable/Symbols/BaseTypeAnalysis.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers

#63355 Merge main-vs-deps to main
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/ItemManager.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_HandleNonRoslynCompletionSources.vb
Labels: Area-Infrastructure

#63386 Add ExternalAccess for INavigateToSearcherService
  src/Tools/ExternalAccess/OmniSharp/NavigateTo/OmniSharpNavigateToSearchResult.cs
  src/Tools/ExternalAccess/OmniSharp/NavigateTo/OmniSharpNavigateToSearchService.cs
  src/Tools/ExternalAccess/OmniSharpTest/EnumTests.cs
Labels: Area-IDE

#63379 Simplify TypeKind condition
  src/Features/Core/Portable/GenerateType/AbstractGenerateTypeService.GenerateNamedType.cs
Labels: Area-IDE, Community

#63354 Merge release/dev17.3-vs-deps to release/dev17.3
  azure-pipelines-integration-corehost.yml
  azure-pipelines-integration-lsp.yml
  azure-pipelines-integration.yml
  eng/Versions.props
  eng/pipelines/test-windows-job-single-machine.yml
  eng/targets/Imports.targets
  global.json
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs
  src/Compilers/Core/CodeAnalysisTest/ShadowCopyAnalyzerAssemblyLoaderTests.cs
  src/Compilers/VisualBasic/Test/Semantic/Semantics/CompoundAssignment.vb
  src/EditorFeatures/CSharpTest/SpellCheck/SpellCheckFixerProviderTests.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/CompletionSessionData.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/CompletionSource.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/ItemManager.CompletionListUpdater.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/ItemManager.cs
  src/EditorFeatures/Core/SpellCheck/RoslynSpellCheckFixerProvider.cs
  src/EditorFeatures/TestUtilities/SpellCheck/AbstractSpellCheckFixerProviderTests.cs
  src/EditorFeatures/TestUtilities/SpellCheck/AbstractSpellCheckSpanTests.cs
  src/EditorFeatures/TestUtilities2/Intellisense/MockCompletionPresenter.vb
  src/EditorFeatures/TestUtilities2/Microsoft.CodeAnalysis.EditorFeatures.Test.Utilities2.vbproj
  src/VisualStudio/Core/Test/DebuggerIntelliSense/TestState.vb
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/LightBulbHelper.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/Editor_InProc.cs
  src/VisualStudio/IntegrationTest/TestUtilities/LightBulbHelper.cs
  src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb
  src/VisualStudio/VisualBasic/Impl/LanguageService/VisualBasicPackage.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-Infrastructure, auto-merge

#63314 Remove GenerateSdkPackages
  scripts/GenerateSdkPackages/README.md
  scripts/GenerateSdkPackages/base.nuspec
  scripts/GenerateSdkPackages/files.txt
  scripts/GenerateSdkPackages/make-all.ps1
Labels: Area-Infrastructure

#63405 only publish build validation logs on failure
  azure-pipelines.yml
Labels: Area-Infrastructure

#63407 Improve classification test harness output
  src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs
  src/EditorFeatures/CSharpTest/Classification/TotalClassifierTests.cs
  src/EditorFeatures/TestUtilities/Classification/FormattedClassification.cs
  src/EditorFeatures/TestUtilities/Classification/FormattedClassifications.cs
Labels: Area-IDE, Community

#63403 Relax assert in CodeGenerator.EmitConversion()
  src/Compilers/CSharp/Portable/CodeGen/EmitConversion.cs
  src/Compilers/CSharp/Test/Emit2/Emit/NumericIntPtrTests.cs
Labels: Area-Compilers

#63369 Install a .NET 6 runtime for the MSBuild Workspace unit tests.
  eng/pipelines/test-windows-job-single-machine.yml
Labels: Area-Infrastructure

#63267 Dont throw on null return
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs
  src/Compilers/Core/Portable/SourceGeneration/UserFunction.cs
Labels: Area-Compilers

#63374 Use non-recursive DFS when visit binary expression
  src/Features/Core/Portable/Wrapping/BinaryExpression/AbstractBinaryExpressionWrapper.cs
Labels: Area-IDE

#63398 Pass SolutionServices in more places
  src/EditorFeatures/Test/Diagnostics/DiagnosticAnalyzerServiceTests.cs
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/EditorFeatures/Test/Preview/PreviewWorkspaceTests.cs
  src/EditorFeatures/Test/SolutionCrawler/WorkCoordinatorTests.cs
  src/EditorFeatures/TestUtilities/Diagnostics/TestDiagnosticAnalyzerDriver.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/API/UnitTestingHotReloadService.cs
  src/Features/Core/Portable/ExternalAccess/Watch/Api/WatchHotReloadService.cs
  src/Features/Core/Portable/Workspace/MiscellaneousFileUtilities.cs
  src/Features/LanguageServer/Protocol/Workspaces/LspMiscellaneousFilesWorkspace.cs
  src/Tools/AnalyzerRunner/IncrementalAnalyzerRunner.cs
  src/Tools/IdeCoreBenchmarks/FindReferencesBenchmarks.cs
  src/Tools/IdeCoreBenchmarks/NavigateToBenchmarks.cs
  src/VisualStudio/CSharp/Impl/ProjectSystemShim/CSharpProjectShim.OptionsProcessor.cs
  src/VisualStudio/CSharp/Impl/ProjectSystemShim/CSharpProjectShim.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/AbstractPersistentStorageTests.cs
  src/VisualStudio/Core/Def/ProjectSystem/MiscellaneousFilesWorkspace.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioProjectOptionsProcessor.cs
  src/VisualStudio/Core/Def/Remote/VisualStudioRemoteHostClientProvider.cs
  src/VisualStudio/Core/Def/Remote/VisualStudioWorkspaceServiceHubConnector.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs
  src/VisualStudio/Core/Test.Next/Remote/RemoteHostClientServiceFactoryTests.cs
  src/VisualStudio/VisualBasic/Impl/ProjectSystemShim/VisualBasicProject.OptionsProcessor.vb
  src/VisualStudio/VisualBasic/Impl/ProjectSystemShim/VisualBasicProject.vb
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/OptionPages/PerformanceLoggersPage.cs
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/VisualStudioDiagnosticsWindowPackage.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService.cs
  src/Workspaces/Core/Portable/Storage/PersistentStorageExtensions.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.GeneratedFileReplacingCompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.ICompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/CoreTest/WorkspaceServiceTests/GlobalOptionServiceTests.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemostHostClient.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemoteHostClientProvider.cs
  src/Workspaces/CoreTestUtilities/Remote/TestSerializerService.cs
  src/Workspaces/Remote/Core/GlobalNotificationRemoteDeliveryService.cs
  src/Workspaces/Remote/Core/ServiceHubRemoteHostClient.cs
  src/Workspaces/Remote/Core/SolutionAssetProvider.cs
  src/Workspaces/Remote/ServiceHub/Services/AsynchronousOperationListener/RemoteAsynchronousOperationListenerService.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs
Labels: Area-IDE

#63419 Remove bogus assert
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassification/RemoteSemanticClassificationService.Caching.cs
Labels: Area-IDE

#63197 Keep the host solution pinned on the remote workspace side while performing an inline-rename session
  src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs
  src/Workspaces/Core/Portable/Rename/IRemoteRenameKeepAliveSession.cs
  src/Workspaces/Core/Portable/Rename/IRemoteRenamerService.cs
  src/Workspaces/Core/Portable/Rename/Renamer.cs
  src/Workspaces/Remote/ServiceHub/Services/Renamer/RemoteRenamerService.cs
Labels: Area-IDE

#63190 Move DesignerAttribute scanning off of SolutionCrawler
  src/EditorFeatures/Core/Remote/SolutionChecksumUpdater.cs
  src/Features/Core/Portable/DesignerAttribute/AbstractDesignerAttributeIncrementalAnalyzer.cs
  src/Features/Core/Portable/DesignerAttribute/DesignerAttributeData.cs
  src/Features/Core/Portable/DesignerAttribute/DesignerAttributeHelpers.cs
  src/Features/Core/Portable/DesignerAttribute/IDesignerAttributeDiscoveryService.cs
  src/Features/Core/Portable/DesignerAttribute/IRemoteDesignerAttributeDiscoveryService.cs
  src/Features/Core/Portable/Workspace/BackgroundCompiler.cs
  src/VisualStudio/Core/Def/DesignerAttribute/InProcDesignerAttributeIncrementalAnalyzer.cs
  src/VisualStudio/Core/Def/DesignerAttribute/InProcDesignerAttributeIncrementalAnalyzerProvider.cs
  src/VisualStudio/Core/Def/DesignerAttribute/VisualStudioDesignerAttributeService.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/Workspaces/Core/Portable/DesignerAttribute/IDesignerAttributeListener.cs
  src/Workspaces/Core/Portable/Shared/Utilities/AsyncBatchingWorkQueue`0.cs
  src/Workspaces/Core/Portable/Shared/Utilities/AsyncBatchingWorkQueue`2.cs
  src/Workspaces/Remote/ServiceHub/Services/DesignerAttributeDiscovery/RemoteDesignerAttributeDiscoveryService.cs
  src/Workspaces/Remote/ServiceHub/Services/DesignerAttributeDiscovery/RemoteDesignerAttributeIncrementalAnalyzer.cs
  src/Workspaces/Remote/ServiceHub/Services/DesignerAttributeDiscovery/RemoteDesignerAttributeIncrementalAnalyzerProvider.cs
Labels: Area-IDE

#63412 Add 'cancel current batch' capabilities to async-batching-work-queus.
  src/EditorFeatures/Core/Remote/SolutionChecksumUpdater.cs
  src/Features/Core/Portable/Workspace/BackgroundCompiler.cs
  src/Workspaces/Core/Portable/Shared/Utilities/AsyncBatchingWorkQueue`0.cs
  src/Workspaces/Core/Portable/Shared/Utilities/AsyncBatchingWorkQueue`2.cs
Labels: Area-IDE

#63414 Fix crash in ref escape around missing this param
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
Labels: Area-Compilers

#63427 Remove obsoleted unit-testing EA type that is no longer in use.
  src/Workspaces/Core/Portable/ExternalAccess/UnitTesting/UnitTestingIncrementalAnalyzerProvider.cs
Labels: Area-IDE

#63286 Restore nullable warnings for unset required members from base types
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/RequiredMembersTests.cs
Labels: Area-Compilers, New Feature - Required Members

#63293 Integrate Lambda Default Parameters into Synthesized Delegate Types and Lowering Pass
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/Lowering/SynthesizedMethodBaseSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeDescriptor.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeField.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeManager.Templates.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/PublicSymbols/AnonymousType.DelegatePublicSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.DelegateTemplateSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LambdaParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedDelegateSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EEMethodSymbol.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/ObjectIdLocalSymbol.cs
Labels: Area-Compilers

#59369 Implement IAttributeOperation
  src/Analyzers/Core/Analyzers/RemoveUnnecessarySuppressions/SuppressMessageAttributeState.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs
  src/Compilers/CSharp/Portable/Binder/ContextualAttributeBinder.cs
  src/Compilers/CSharp/Portable/Compilation/AttributeSemanticModel.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IArgument.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IAttributeOperation.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IFieldReferenceExpression.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs
  src/Compilers/Core/Portable/Generated/OperationKind.Generated.cs
  src/Compilers/Core/Portable/Generated/Operations.Generated.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraph.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/Operations/OperationInterfaces.xml
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Test/Core/Compilation/ControlFlowGraphVerifier.cs
  src/Compilers/Test/Core/Compilation/OperationTreeVerifier.cs
  src/Compilers/Test/Core/Compilation/TestOperationVisitor.cs
  src/Compilers/VisualBasic/Portable/Binding/AttributeSemanticModel.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Attributes.vb
  src/Compilers/VisualBasic/Portable/BoundTree/BoundNodes.xml
  src/Compilers/VisualBasic/Portable/Generated/BoundNodes.xml.Generated.vb
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb
  src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_IAttributeOperation.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_IFieldReferenceExpression.vb
  src/Compilers/VisualBasic/Test/Semantic/Semantics/GetSemanticInfoTests.vb
Labels: Area-Compilers, Community, Feature - IOperation

#63426 Remove portion of incremental-analyzer-infrastructure that has no usage.
  src/Features/Core/Portable/SolutionCrawler/AggregateIncrementalAnalyzer.cs
  src/Features/Core/Portable/SolutionCrawler/Extensibility/ExportPerLanguageIncrementalAnalyzerProviderAttribute.cs
  src/Features/Core/Portable/SolutionCrawler/Extensibility/IPerLanguageIncrementalAnalyzerProvider.cs
  src/Features/Core/Portable/SolutionCrawler/Extensibility/PerLanguageIncrementalAnalyzerProviderMetadata.cs
  src/Features/Core/Portable/SolutionCrawler/IncrementalAnalyzerProviderBase.cs
Labels: Area-IDE

#63431 Fix compilation of exe RefFieldTests
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers

#63392 Share a DiagnosticAnalyzerInfoCache between DiagnosticAnalyzerService and DiagnosticAnalyzerServiceQuickInfoProvider
  src/EditorFeatures/CSharpTest/QuickInfo/DiagnosticAnalyzerQuickInfoSourceTests.cs
  src/Features/CSharp/Portable/QuickInfo/CSharpDiagnosticAnalyzerQuickInfoProvider.cs
  src/Features/CSharp/Portable/QuickInfo/CSharpDiagnosticAnalyzerQuickInfoProviderExtensions.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DiagnosticAnalyzerService.cs
  src/Workspaces/Core/Portable/Diagnostics/DiagnosticAnalyzerInfoCache.cs
Labels: Area-IDE

#63420 [LSP] Fix fading diagnostics
  src/EditorFeatures/Core/Diagnostics/DiagnosticsClassificationTaggerProvider.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DiagnosticDataExtensions.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/AbstractPullDiagnosticTestsBase.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
Labels: Area-IDE, LSP

#63432 Ensure all ref local and field value access are dereferenced
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md
  src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenRefLocalTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenRefReadonlyReturnTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers

#63443 Enable UTF8 raw multiline column guides
  src/EditorFeatures/CSharpTest/StringIndentation/StringIndentationTests.cs
  src/Features/CSharp/Portable/StringIndentation/CSharpStringIndentationService.cs
Labels: Area-IDE, Community

#63274 Fix moving nested type to another file from an interface
  src/EditorFeatures/CSharpTest/CodeActions/MoveType/MoveTypeTests.MoveToNewFile.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
Labels: Area-IDE, Community

#63276 Use existing Program class declaration in "Convert to 'Program.Main'" refactoring when possible
  src/EditorFeatures/CSharpTest/ConvertProgram/ConvertToProgramMainAnalyzerTests.cs
  src/Features/CSharp/Portable/ConvertProgram/ConvertProgramTransform_ProgramMain.cs
Labels: Area-IDE, Community

#63292 Enable adding attributes to generic types
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
  src/Workspaces/CoreTest/Editing/SyntaxEditorTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxNodeExtensions.cs
Labels: Area-IDE

#63155 Fetch the recoverable tree length option more lazily
  src/Workspaces/Core/Portable/Workspace/Host/SyntaxTreeFactory/AbstractSyntaxTreeFactoryService.cs
Labels: Area-IDE

#62138 Partition helix test runs using historical execution time data
  eng/Versions.props
  eng/build.sh
  eng/prepare-tests.ps1
  eng/prepare-tests.sh
  src/Compilers/CSharp/Test/EndToEnd/Microsoft.CodeAnalysis.CSharp.EndToEnd.UnitTests.csproj
  src/Compilers/CSharp/Test/WinRT/Microsoft.CodeAnalysis.CSharp.WinRT.UnitTests.csproj
  src/Compilers/Test/Core/RunInSinglePartitionAssemblyAttribute.cs
  src/Tools/PrepareTests/PrepareTests.csproj
  src/Tools/PrepareTests/Program.cs
  src/Tools/PrepareTests/TestDiscovery.cs
  src/Tools/Source/RunTests/AssemblyInfo.cs
  src/Tools/Source/RunTests/AssemblyScheduler.cs
  src/Tools/Source/RunTests/ITestExecutor.cs
  src/Tools/Source/RunTests/Options.cs
  src/Tools/Source/RunTests/ProcDumpUtil.cs
  src/Tools/Source/RunTests/ProcessRunner.cs
  src/Tools/Source/RunTests/ProcessTestExecutor.cs
  src/Tools/Source/RunTests/Program.cs
  src/Tools/Source/RunTests/RunTests.csproj
  src/Tools/Source/RunTests/TestHistoryManager.cs
  src/Tools/Source/RunTests/TestRunner.cs
Labels: Area-Infrastructure

#63467 Added missing backtick to breaking changes
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md
Labels: Area-Compilers, Community

#63456 Simplify File-Rename code
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/VSTypeScriptInlineRenameInfo.cs
  src/EditorFeatures/Core/InlineRename/AbstractEditorInlineRenameService.FailureInlineRenameInfo.cs
  src/EditorFeatures/Core/InlineRename/AbstractEditorInlineRenameService.SymbolRenameInfo.cs
  src/EditorFeatures/Core/InlineRename/IEditorInlineRenameService.cs
  src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs
  src/Tools/ExternalAccess/FSharp/Editor/InlineRename/FSharpInlineRenameInfo.cs
  src/Tools/ExternalAccess/FSharp/Internal/Editor/FSharpEditorInlineRenameService.cs
  src/VisualStudio/Xaml/Impl/Features/InlineRename/XamlEditorInlineRenameService.cs
Labels: Area-IDE

#63459 Delete broken median calculation
  src/Workspaces/Core/Portable/Log/StatisticLogAggregator.cs
  src/Workspaces/Core/Portable/Log/StatisticResult.cs
Labels: Area-IDE

#63471 Remove unused variable
  src/Analyzers/Core/Analyzers/ForEachCast/AbstractForEachCastDiagnosticAnalyzer.cs
Labels: Area-IDE, Community

#63473 Revert and fix the stackoverflow when search local function.
  src/EditorFeatures/CSharpTest/NavigateTo/NavigateToTests.cs
  src/Workspaces/CSharp/Portable/FindSymbols/CSharpDeclaredSymbolInfoFactoryService.cs
  src/Workspaces/Core/Portable/FindSymbols/Shared/AbstractSyntaxIndex_Persistence.cs
  src/Workspaces/Core/Portable/LanguageServices/DeclaredSymbolFactoryService/AbstractDeclaredSymbolInfoFactoryService.cs
  src/Workspaces/VisualBasic/Portable/FindSymbols/VisualBasicDeclaredSymbolInfoFactoryService.vb
Labels: Area-IDE

#63474 Revert "Pass SolutionServices in more places"
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/API/UnitTestingHotReloadService.cs
  src/Features/Core/Portable/ExternalAccess/Watch/Api/WatchHotReloadService.cs
Labels: Area-IDE

#63480 Break out src/Tools in the CODEOWNERs file for more granular ownership
  .github/CODEOWNERS
Labels: Area-Infrastructure

#63451 Inline local in Program.Main refactoring
  src/Features/CSharp/Portable/ConvertProgram/ConvertProgramTransform_ProgramMain.cs
Labels: Area-IDE, Community

#63437 Add assert back
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs
Labels: Area-Compilers, Community

#63468 Fix regression in analyzer partial analysis state tracking
  src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.SyntaxReferenceAnalyzerStateData.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs
Labels: Area-Analyzers, Area-Compilers

#63485 Revert "Implement IAttributeOperation (#59369)"
  src/Analyzers/Core/Analyzers/RemoveUnnecessarySuppressions/SuppressMessageAttributeState.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs
  src/Compilers/CSharp/Portable/Binder/ContextualAttributeBinder.cs
  src/Compilers/CSharp/Portable/Compilation/AttributeSemanticModel.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IArgument.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IAttributeOperation.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IFieldReferenceExpression.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs
  src/Compilers/Core/Portable/Generated/OperationKind.Generated.cs
  src/Compilers/Core/Portable/Generated/Operations.Generated.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraph.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Core/Portable/Operations/OperationInterfaces.xml
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Test/Core/Compilation/ControlFlowGraphVerifier.cs
  src/Compilers/Test/Core/Compilation/OperationTreeVerifier.cs
  src/Compilers/Test/Core/Compilation/TestOperationVisitor.cs
  src/Compilers/VisualBasic/Portable/Binding/AttributeSemanticModel.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Attributes.vb
  src/Compilers/VisualBasic/Portable/BoundTree/BoundNodes.xml
  src/Compilers/VisualBasic/Portable/Generated/BoundNodes.xml.Generated.vb
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb
  src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_IAttributeOperation.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_IFieldReferenceExpression.vb
  src/Compilers/VisualBasic/Test/Semantic/Semantics/GetSemanticInfoTests.vb
Labels: Area-Infrastructure

#63320 ConvertToRecord: Property and Method analysis
  src/Analyzers/Core/Analyzers/Analyzers.projitems
  src/Analyzers/Core/Analyzers/Helpers/HashCodeAnalyzer/HashCodeAnalyzer.OperationDeconstructor.cs
  src/Analyzers/Core/Analyzers/Helpers/HashCodeAnalyzer/HashCodeAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseSystemHashCode/UseSystemHashCodeDiagnosticAnalyzer.cs
  src/Analyzers/Core/CodeFixes/UseSystemHashCode/UseSystemHashCodeCodeFixProvider.cs
  src/EditorFeatures/CSharpTest/ConvertToRecord/ConvertToRecordTests.cs
  src/Features/CSharp/Portable/CSharpFeaturesResources.resx
  src/Features/CSharp/Portable/CodeRefactorings/ConvertToRecord/CSharpConvertToRecordRefactoringProvider.cs
  src/Features/CSharp/Portable/CodeRefactorings/ConvertToRecord/ConvertToRecordHelpers.cs
  src/Features/CSharp/Portable/CodeRefactorings/ConvertToRecord/PositionalParameterInfo.cs
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.cs.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.de.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.es.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.fr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.it.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ja.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ko.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pl.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pt-BR.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ru.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.tr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hans.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hant.xlf
Labels: Area-IDE, New Language Feature - Records

#63491 Remove explicit ownership of LiveShare
  .github/CODEOWNERS
Labels: Area-Infrastructure

#63415 Regression test for ref struct in iterator
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
Labels: Area-Compilers

#63358 Remove unused GetLanguageName methods
  src/Analyzers/CSharp/Analyzers/QualifyMemberAccess/CSharpQualifyMemberAccessDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/SimplifyTypeNames/SimplifyTypeNamesDiagnosticAnalyzerBase.cs
  src/Analyzers/VisualBasic/Analyzers/QualifyMemberAccess/VisualBasicQualifyMemberAccessDiagnosticAnalyzer.vb
  src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpPreferFrameworkTypeDiagnosticAnalyzer.cs
  src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpSimplifyTypeNamesDiagnosticAnalyzer.cs
  src/Features/Core/Portable/PreferFrameworkType/PreferFrameworkTypeDiagnosticAnalyzerBase.cs
  src/Features/VisualBasic/Portable/Diagnostics/Analyzers/VisualBasicPreferFrameworkTypeDiagnosticAnalyzer.vb
  src/Features/VisualBasic/Portable/Diagnostics/Analyzers/VisualBasicSimplifyTypeNamesDiagnosticAnalyzer.vb
Labels: Area-IDE, Community

#63458 When we're removing the last project, fire SolutionRemoved
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioProject.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioProjectFactory.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioProjectTests/WorkspaceChangedEventTests.vb
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpFindReferences.cs
Labels: Area-IDE

#63381 Classify 'u8' in Utf8 string literals as keyword
  src/EditorFeatures/CSharpTest/Classification/SyntacticClassifierTests.cs
  src/Workspaces/CSharp/Portable/Classification/Worker.cs
Labels: Area-IDE, Community

#63454 Remove unused argument
  src/EditorFeatures/CSharp/EventHookup/EventHookupSessionManager_EventHookupSession.cs
  src/EditorFeatures/CSharpTest/AddUsing/AddUsingNuGetTests.cs
  src/EditorFeatures/Core/Extensibility/NavigationBar/AbstractEditorNavigationBarItemService.cs
  src/EditorFeatures/Core/Extensibility/NavigationBar/INavigationBarItemService.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptNavigationBarItemService.cs
  src/EditorFeatures/Core/Formatting/FormatCommandHandler.Paste.cs
  src/EditorFeatures/Core/NavigationBar/NavigationBarController_ModelComputation.cs
  src/EditorFeatures/Test2/NavigationBar/TestHelpers.vb
  src/EditorFeatures/VisualBasicTest/Diagnostics/AddImport/AddImportTests_NuGet.vb
  src/Features/CSharp/Portable/Completion/CompletionProviders/AttributeNamedParameterCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/SnippetCompletionProvider.cs
  src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs
  src/Features/Core/Portable/CodeRefactorings/ExtractMethod/AbstractExtractMethodCodeRefactoringProvider.cs
  src/Features/LanguageServer/Protocol/Features/CodeFixes/CodeFixService.cs
  src/Features/VisualBasic/Portable/Completion/CompletionProviders/CrefCompletionProvider.vb
  src/Tools/ExternalAccess/FSharp/Internal/Editor/FSharpNavigationBarItemService.cs
  src/VisualStudio/Core/Def/Packaging/PackageInstallerServiceFactory.cs
  src/Workspaces/Core/Portable/Packaging/IPackageInstallerService.cs
Labels: Area-IDE

#63371 Constructor ordering, defaults, and overloads
  src/EditorFeatures/CSharpTest/ConvertToRecord/ConvertToRecordTests.cs
  src/Features/CSharp/Portable/CSharpFeaturesResources.resx
  src/Features/CSharp/Portable/CodeRefactorings/ConvertToRecord/CSharpConvertToRecordRefactoringProvider.cs
  src/Features/CSharp/Portable/CodeRefactorings/ConvertToRecord/ConvertToRecordHelpers.cs
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.cs.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.de.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.es.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.fr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.it.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ja.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ko.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pl.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pt-BR.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ru.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.tr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hans.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hant.xlf
Labels: Area-IDE, New Language Feature - Records

#63518 Do not nominate project for restore
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerInProcess.cs
Labels: Area-IDE

#63523 Skip integration tests on PRs for compiler-only changes
  azure-pipelines-integration.yml
Labels: Area-Infrastructure

#63435 Handle nested non-deconstruction conversions in DeconstructionInfo
  src/Compilers/CSharp/Portable/Compilation/DeconstructionInfo.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DeconstructionTests.cs
Labels: Area-Compilers

#63438 Move symbol-cache incremental-analyzer out of oop.
  src/EditorFeatures/Test2/Diagnostics/AddImport/AddImportCrossLanguageTests.vb
  src/Features/Core/Portable/AddImport/SearchScopes/MetadataSymbolsSearchScope.cs
  src/Features/Core/Portable/AddImport/SearchScopes/SourceSymbolsProjectSearchScope.cs
  src/Features/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfoIncrementalAnalyzer.cs
  src/Features/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfoIncrementalAnalyzerProvider.cs
  src/Features/Core/Portable/IncrementalCaches/SymbolTreeInfoCacheService.cs
  src/Features/Core/Portable/IncrementalCaches/SymbolTreeInfoIncrementalAnalyzer.cs
  src/Tools/AnalyzerRunner/IncrementalAnalyzerRunner.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpErrorListCommon.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpSquigglesCommon.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicSquigglesCommon.cs
  src/Workspaces/Core/Portable/FindSymbols/IRemoteSymbolFinderService.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/ISymbolTreeInfoCacheService.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfoCacheService.MetadataInfo.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfoCacheService.cs
  src/Workspaces/Remote/Core/ServiceDescriptors.cs
  src/Workspaces/Remote/ServiceHub/Services/SymbolFinder/RemoteSymbolFinderService.cs
Labels: Area-IDE

#63134 Handle `[UnscopedRef] scoped` in source and metadata
  src/Compilers/CSharp/Portable/Binder/Binder_Lambda.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeManager.Templates.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/ParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ParameterHelpers.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceSimpleParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers, New Language Feature - Ref Fields

#63439 Do symbol mapping in Go To Def
  src/EditorFeatures/Core/GoToDefinition/AbstractGoToDefinitionService.cs
  src/EditorFeatures/Core/GoToDefinition/AbstractGoToSymbolService.cs
  src/Features/Core/Portable/GoToDefinition/AbstractFindDefinitionService.cs
  src/Features/Core/Portable/GoToDefinition/AbstractGoToDefinitionSymbolService.cs
  src/Features/Core/Portable/GoToDefinition/IGoToDefinitionSymbolService.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpGoToDefinition.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/Microsoft.VisualStudio.LanguageServices.New.IntegrationTests.csproj
Labels: Area-IDE

#63510 Trigger keyword completions in compiler directives when typing
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Features/CSharp/Portable/Completion/CompletionProviders/CompletionUtilities.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/KeywordCompletionProvider.cs
Labels: Area-IDE, Community

#63527 Fix the LSIF indexer's ability to load MSBuild projects and solutions
  eng/Versions.props
  src/Features/Lsif/Generator/Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.csproj
  src/Features/Lsif/Generator/Program.cs
Labels: Area-IDE

#63531 Implement lowering for ref field assignment in object initializers
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers, New Language Feature - Ref Fields

#63536 Avoid accessing the Workspaec off of a Solution in features that want to know if they can make a change.
  src/Analyzers/Core/CodeFixes/MatchFolderAndNamespace/AbstractChangeNamespaceToMatchFolderCodeFixProvider.cs
  src/EditorFeatures/Core/Formatting/FormatCommandHandler.Paste.cs
  src/EditorFeatures/Core/InlineRename/AbstractEditorInlineRenameService.SymbolRenameInfo.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/SnippetCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractImportCompletionProvider.cs
  src/Features/Core/Portable/ExtractClass/AbstractExtractClassRefactoringProvider.cs
  src/Features/Core/Portable/GenerateType/AbstractGenerateTypeService.cs
  src/VisualStudio/CSharp/Impl/Snippets/SnippetCommandHandler.cs
  src/VisualStudio/Core/Def/Snippets/AbstractSnippetCommandHandler.cs
  src/Workspaces/Core/Portable/Workspace/Host/ISupportedChangesService.cs
  src/Workspaces/Core/Portable/Workspace/Host/IWorkspaceService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixesAndRefactorings/CodeFixContextExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixesAndRefactorings/CodeRefactoringExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensions.projitems
Labels: Area-IDE

#63449 Improve cross-project add-using results
  src/Features/Core/Portable/AddImport/SearchScopes/MetadataSymbolsSearchScope.cs
  src/Features/Core/Portable/AddImport/SearchScopes/SourceSymbolsProjectSearchScope.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionService.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.SymbolComputer.cs
  src/Tools/AnalyzerRunner/IncrementalAnalyzerRunner.cs
  src/Workspaces/Core/Portable/FindSymbols/Declarations/DeclarationFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/DependentTypeFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfoCacheService.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Metadata.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Serialization.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Source.cs
  src/Workspaces/Core/Portable/Utilities/SpellChecker.cs
Labels: Area-IDE

#63528 Extract Base Record Pass 1
  src/EditorFeatures/CSharpTest/ExtractClass/ExtractClassTests.cs
  src/Features/Core/Portable/ExtractClass/ExtractClassWithDialogCodeAction.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/PullMemberUp/MemberAndDestinationValidator.cs
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/VisualStudio/Core/Def/ExtractClass/ExtractClassDialog.xaml.cs
  src/VisualStudio/Core/Def/ExtractClass/ExtractClassViewModel.cs
  src/VisualStudio/Core/Def/ExtractClass/VisualStudioExtractClassOptionsService.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
Labels: Area-IDE

#63535 Update xcopy msbuild version for .net7p7
  global.json
Labels: Area-Infrastructure

#63541 Fix version check
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/LanguageVersionExtensions.cs
Labels: Area-IDE

#63495 Cherry-pick 62946 to 17.3
  src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs
Labels: Area-IDE, Approved to merge

#63538 Remove unused extension method
  src/Features/LanguageServer/Protocol/Features/Diagnostics/IDiagnosticService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/IDiagnosticServiceExtensions.cs
Labels: Area-IDE

#63537 Do not access Workspace off of a Solution instance.
  src/Features/Core/Portable/MetadataAsSource/SymbolMappingServiceFactory.cs
Labels: Area-IDE

#63540 Avoid linq overhead and having to create secondary result
  src/EditorFeatures/Core/KeywordHighlighting/HighlighterViewTaggerProvider.cs
  src/EditorFeatures/Core/ReferenceHighlighting/ReferenceHighlightingViewTaggerProvider.cs
  src/EditorFeatures/Core/Shared/Tagging/Utilities/TagSpanIntervalTree.cs
  src/EditorFeatures/Core/Tagging/TaggerContext.cs
Labels: Area-IDE

#63498 Move Windows builds to new images
  azure-pipelines-integration-lsp.yml
  azure-pipelines-integration.yml
  azure-pipelines-official.yml
  azure-pipelines-richnav.yml
  azure-pipelines.yml
  eng/pipelines/test-windows-job-single-machine.yml
Labels: Area-Infrastructure

#63550 Don't report an issue for predictable failures
  src/Features/Core/Portable/MetadataAsSource/DecompilationMetadataAsSourceFileProvider.cs
Labels: Area-IDE
