Repository dotnet/roslyn, pull requests merged in 2023-09, with the labels that each got.

#69778 Update the severity combo boxes in EditorConfig UX to reflect the correct semantics
  src/EditorFeatures/CSharpTest/EditorConfigSettings/Updater/SettingsUpdaterTests.cs
  src/EditorFeatures/Core/EditorConfigSettings/Data/AnalyzerSetting.cs
  src/EditorFeatures/Core/EditorConfigSettings/Data/CodeStyleSetting.cs
  src/EditorFeatures/Core/EditorConfigSettings/DataProvider/Analyzer/AnalyzerSettingsProvider.cs
  src/EditorFeatures/Core/EditorConfigSettings/Updater/AnalyzerSettingsUpdater.cs
  src/EditorFeatures/Core/EditorConfigSettings/Updater/SettingsUpdateHelper.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/Analyzers/View/ColumnDefinitions/AnalyzerSeverityColumnDefinition.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/Analyzers/ViewModel/SeverityViewModel.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/CodeStyle/ViewModel/CodeStyleSeverityViewModel.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/NamingStyle/View/ColumnDefinitions/NamingStylesSeverityColumnDefinition.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/NamingStyle/ViewModel/ColumnViewModels/NamingStylesSeverityViewModel.cs
Labels: Area-IDE, untriaged, Feature - Editor Config UI

#69786 Pack our language server in a separate package for each platform
  eng/config/PublishData.json
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Microsoft.CodeAnalysis.LanguageServer.csproj
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/PackAllRids.targets
  src/Tools/ExternalAccess/CompilerDeveloperSDK/Microsoft.CodeAnalysis.ExternalAccess.CompilerDeveloperSDK.csproj
  src/VisualStudio/DevKit/Impl/Microsoft.VisualStudio.LanguageServices.DevKit.csproj
Labels: Area-Infrastructure, untriaged

#69765 Remove EditorFeatures.Cocoa and VSMac IVTs
  .github/CODEOWNERS
  Roslyn.sln
  eng/Versions.props
  eng/config/PublishData.json
  eng/targets/Settings.props
  src/EditorFeatures/CSharp/Microsoft.CodeAnalysis.CSharp.EditorFeatures.csproj
  src/EditorFeatures/Core.Cocoa/CommandHandlers/GoToMatchingBraceCommandHandler.cs
  src/EditorFeatures/Core.Cocoa/Lsp/VSMacLspLoggerFactoryWrapper.cs
  src/EditorFeatures/Core.Cocoa/Lsp/VSMacWorkspaceRegistrationService.cs
  src/EditorFeatures/Core.Cocoa/Microsoft.CodeAnalysis.EditorFeatures.Cocoa.csproj
  src/EditorFeatures/Core.Cocoa/NavigationCommandHandlers/AbstractNavigationCommandHandler.cs
  src/EditorFeatures/Core.Cocoa/NavigationCommandHandlers/FindBaseSymbolsCommandHandler.cs
  src/EditorFeatures/Core.Cocoa/NavigationCommandHandlers/FindDerivedSymbolsCommandHandler.cs
  src/EditorFeatures/Core.Cocoa/NavigationCommandHandlers/FindExtensionMethodsCommandHandler.cs
  src/EditorFeatures/Core.Cocoa/NavigationCommandHandlers/FindImplementingMembersCommandHandler.cs
  src/EditorFeatures/Core.Cocoa/NavigationCommandHandlers/FindMemberOverloadsCommandHandler.cs
  src/EditorFeatures/Core.Cocoa/NavigationCommandHandlers/FindReferencesOfOverloadsCommandHandler.cs
  src/EditorFeatures/Core.Cocoa/Options/VisualStudioMacOptionsStorage.cs
  src/EditorFeatures/Core.Cocoa/Preview/ICocoaDifferenceViewerExtensions.cs
  src/EditorFeatures/Core.Cocoa/Preview/PreviewFactoryService.cs
  src/EditorFeatures/Core.Cocoa/Preview/PreviewPane.cs
  src/EditorFeatures/Core.Cocoa/Preview/PreviewPaneService.cs
  src/EditorFeatures/Core.Cocoa/PublicAPI.Shipped.txt
  src/EditorFeatures/Core.Cocoa/PublicAPI.Unshipped.txt
  src/EditorFeatures/Core.Cocoa/Snippets/AbstractSnippetCommandHandler.cs
  src/EditorFeatures/Core.Cocoa/Snippets/AbstractSnippetExpansionClient.cs
  src/EditorFeatures/Core.Cocoa/Snippets/CSharpSnippets/SnippetCommandHandler.cs
  src/EditorFeatures/Core.Cocoa/Snippets/CSharpSnippets/SnippetExpansionClient.cs
  src/EditorFeatures/Core.Cocoa/Snippets/CSharpSnippets/SnippetFunctions/SnippetFunctionClassName.cs
  src/EditorFeatures/Core.Cocoa/Snippets/CSharpSnippets/SnippetFunctions/SnippetFunctionGenerateSwitchCases.cs
  src/EditorFeatures/Core.Cocoa/Snippets/CSharpSnippets/SnippetFunctions/SnippetFunctionSimpleTypeName.cs
  src/EditorFeatures/Core.Cocoa/Snippets/SnippetFunctions/AbstractSnippetFunction.IExpansionFunction.cs
  src/EditorFeatures/Core.Cocoa/Snippets/SnippetFunctions/AbstractSnippetFunction.cs
  src/EditorFeatures/Core.Cocoa/Snippets/SnippetFunctions/AbstractSnippetFunctionClassName.cs
  src/EditorFeatures/Core.Cocoa/Snippets/SnippetFunctions/AbstractSnippetFunctionGenerateSwitchCases.cs
  src/EditorFeatures/Core.Cocoa/Snippets/SnippetFunctions/AbstractSnippetFunctionSimpleTypeName.cs
  src/EditorFeatures/Core.Cocoa/Structure/StructureTaggerProvider.cs
  src/EditorFeatures/Core.Cocoa/Utilities/NavigateToLinkService.cs
  src/EditorFeatures/Core.Cocoa/Workspaces/CocoaTextBufferVisibilityTracker.cs
  src/EditorFeatures/Core.Wpf/InlineRename/CommandHandlers/RenameCommandHandler.cs
  src/EditorFeatures/Core.Wpf/InlineRename/HighlightTags/RenameFieldBackgroundAndBorderTagDefinition.cs
  src/EditorFeatures/Core.Wpf/Suggestions/FixAll/FixAllGetFixesService.cs
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/EditorFeatures/Text/Microsoft.CodeAnalysis.EditorFeatures.Text.csproj
  src/Features/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.Features.csproj
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/Features/LanguageServer/Protocol/Microsoft.CodeAnalysis.LanguageServer.Protocol.csproj
  src/Features/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.Features.vbproj
  src/Workspaces/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.Workspaces.csproj
  src/Workspaces/Core/Desktop/Microsoft.CodeAnalysis.Workspaces.Desktop.csproj
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
  src/Workspaces/Remote/Core/Microsoft.CodeAnalysis.Remote.Workspaces.csproj
  src/Workspaces/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.Workspaces.vbproj
Labels: Area-IDE, untriaged

#69799 Update configs after 17.8p2 snap
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#69669 Update TFM in tests to net8.0
  src/Compilers/CSharp/Test/CommandLine/Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests.csproj
  src/Compilers/CSharp/Test/EndToEnd/Microsoft.CodeAnalysis.CSharp.EndToEnd.UnitTests.csproj
  src/Compilers/CSharp/Test/IOperation/Microsoft.CodeAnalysis.CSharp.IOperation.UnitTests.csproj
  src/Compilers/CSharp/Test/Symbol/Microsoft.CodeAnalysis.CSharp.Symbol.UnitTests.csproj
  src/Compilers/CSharp/Test/Syntax/Microsoft.CodeAnalysis.CSharp.Syntax.UnitTests.csproj
  src/Compilers/Core/MSBuildTaskTests/Microsoft.Build.Tasks.CodeAnalysis.UnitTests.csproj
  src/Compilers/Core/RebuildTest/Microsoft.CodeAnalysis.Rebuild.UnitTests.csproj
  src/Compilers/Server/VBCSCompilerTests/VBCSCompiler.UnitTests.csproj
  src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.vb
  src/Compilers/VisualBasic/Test/Emit/Microsoft.CodeAnalysis.VisualBasic.Emit.UnitTests.vbproj
  src/Compilers/VisualBasic/Test/IOperation/Roslyn.Compilers.VisualBasic.IOperation.UnitTests.vbproj
  src/Compilers/VisualBasic/Test/Semantic/Microsoft.CodeAnalysis.VisualBasic.Semantic.UnitTests.vbproj
  src/Compilers/VisualBasic/Test/Symbol/Microsoft.CodeAnalysis.VisualBasic.Symbol.UnitTests.vbproj
  src/Compilers/VisualBasic/Test/Syntax/Microsoft.CodeAnalysis.VisualBasic.Syntax.UnitTests.vbproj
  src/Interactive/HostTest/InteractiveHost.UnitTests.csproj
  src/Scripting/CSharpTest/Microsoft.CodeAnalysis.CSharp.Scripting.UnitTests.csproj
  src/Scripting/CoreTest/Microsoft.CodeAnalysis.Scripting.UnitTests.csproj
  src/Tools/ExternalAccess/RazorCompilerTest/Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.UnitTests.csproj
Labels: Area-Compilers, Area-Infrastructure, untriaged

#69723 Trim ToString calls when converting to interpolated strings when there are interpolated string handlers available.
  src/Features/CSharp/Portable/ConvertToInterpolatedString/CSharpConvertConcatenationToInterpolatedStringRefactoringProvider.cs
  src/Features/CSharpTest/ConvertToInterpolatedString/ConvertConcatenationToInterpolatedStringTests.cs
  src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.cs
  src/Features/VisualBasic/Portable/ConvertToInterpolatedString/VisualBasicConvertConcatenationToInterpolatedStringRefactoringProvider.vb
Labels: Area-IDE, untriaged

#69815 Don't hit the file cache multiple times unnecessarily
  src/Compilers/Core/Portable/FileSystem/FileUtilities.cs
  src/Workspaces/Core/Portable/Workspace/Solution/FileTextLoader.cs
Labels: Area-Compilers, untriaged

#69787 Remove well known implicit conversion method
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
Labels: Area-Compilers, untriaged

#69824 Bump NuGet version
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#69828 Allow Razor to not supply dynamic file info if they don't want to.
  src/Tools/ExternalAccess/Razor/IRazorDynamicFileInfoProvider.cs
  src/Tools/ExternalAccess/Razor/InternalAPI.Unshipped.txt
  src/Tools/ExternalAccess/Razor/RazorDynamicFileInfoProviderWrapper.cs
Labels: Area-IDE, untriaged

#69791 Slightly fewer allocations in PENamespaceSymbol.GetMembers()
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamespaceSymbol.cs
Labels: Area-Compilers, untriaged

#69794 Add analysis and emit difference time spans to EnC telemetry
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSessionTelemetry.cs
  src/Features/Core/Portable/EditAndContinue/DocumentAnalysisResults.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/Core/Portable/EditAndContinue/EditSessionTelemetry.cs
  src/Features/Core/Portable/EditAndContinue/TraceLog.cs
Labels: Area-Interactive, untriaged

#69821 Modify the test to cover the scenario
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpRename.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/InlineRenameInProcess.cs
Labels: Area-IDE, untriaged

#68903 Add fuzzer for incremental generators
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverFuzzTests.cs
  src/Compilers/Test/Core/SourceGeneration/TestGenerators.cs
Labels: Area-Compilers, Test

#69836 Fix test after merge
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs
Labels: Area-IDE, Area-Compilers, Area-Infrastructure, untriaged

#69795 Make completion handler more resilient
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/LanguageServer/Protocol/Handler/Completion/AbstractLspCompletionResultCreationService.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionFeaturesTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions.cs
Labels: Area-IDE, untriaged

#61197 Provide dedicated classifications for embedded C# in test code.
  src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs
  src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests_Json.cs
  src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests_Regex.cs
  src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests_StringEscapes.cs
  src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests_TestMarkup.cs
  src/EditorFeatures/Core.Wpf/Classification/ClassificationTypeFormatDefinitions.cs
  src/EditorFeatures/Core/Classification/ClassificationTypeDefinitions.cs
  src/EditorFeatures/Core/EditorFeaturesResources.resx
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.cs.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.de.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.es.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.fr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.it.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ja.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ko.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pl.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pt-BR.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ru.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.tr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hans.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hant.xlf
  src/EditorFeatures/Test/Workspaces/ClassificationTypeNamesTests.cs
  src/EditorFeatures/TestUtilities/Classification/AbstractClassifierTests.cs
  src/EditorFeatures/TestUtilities/Classification/FormattedClassifications.cs
  src/EditorFeatures/TestUtilities/EmbeddedLanguages/EmbeddedLanguagesTestConstants.cs
  src/Features/CSharp/Portable/EmbeddedLanguages/CSharpTestEmbeddedLanguageClassifier.cs
  src/Features/Core/Portable/EmbeddedLanguages/Classification/AbstractEmbeddedLanguageClassificationService.cs
  src/Features/Core/Portable/EmbeddedLanguages/Classification/EmbeddedLanguageClassifierContext.cs
  src/Features/Core/Portable/EmbeddedLanguages/PredefinedEmbeddedLanguageClassifierNames.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/CustomLspSemanticTokenNames.cs
  src/Features/Lsif/GeneratorTest/OutputFormatTests.vb
  src/Tools/ExternalAccess/Razor/RazorClassifierAccessor.cs
  src/VisualStudio/Core/Def/ColorSchemes/VisualStudio2017.xml
  src/VisualStudio/Core/Def/ColorSchemes/VisualStudio2019.pkgdef
  src/VisualStudio/Core/Def/ColorSchemes/VisualStudio2019.xml
  src/VisualStudio/Core/Def/HACK_ThemeColorFixer.cs
  src/Workspaces/Core/Portable/Classification/ClassificationTypeNames.cs
  src/Workspaces/Core/Portable/Classification/Classifier.cs
  src/Workspaces/Core/Portable/Classification/IEmbeddedLanguageClassificationService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/NormalizedTextSpanCollection.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/EmbeddedLanguages/VirtualChars/VirtualChar.cs
Labels: Area-IDE

#69825 Only sync selection when text identifier has focus in rename flyout
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpRename.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs
Labels: Area-IDE, untriaged

#69772 Bump decompiler for debugger
  eng/Versions.props
  src/EditorFeatures/Test/MetadataAsSource/AbstractMetadataAsSourceTests.cs
  src/EditorFeatures/Test/MetadataAsSource/MetadataAsSourceTests.CSharp.cs
  src/EditorFeatures/Test/MetadataAsSource/MetadataAsSourceTests.VisualBasic.cs
  src/EditorFeatures/Test/MetadataAsSource/MetadataAsSourceTests.cs
Labels: Area-Infrastructure, untriaged

#69835 Fix some issues with the MSBuild NuGet packaging
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Microsoft.CodeAnalysis.LanguageServer.csproj
  src/Features/Lsif/Generator/Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.csproj
  src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj
  src/Workspaces/MSBuildTest/Microsoft.CodeAnalysis.Workspaces.MSBuild.UnitTests.csproj
Labels: Area-IDE, untriaged

#69812 Bail out from remove unused member analyzer for ??= operator
  src/Analyzers/CSharp/Tests/RemoveUnusedMembers/RemoveUnusedMembersTests.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs
Labels: Area-Analyzers, untriaged

#69800 Reduce allocations during ToDisplayString
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplay.cs
  src/Compilers/Core/Portable/SymbolDisplay/SymbolDisplayExtensions.cs
  src/Compilers/VisualBasic/Portable/SymbolDisplay/SymbolDisplay.vb
  src/Workspaces/CSharp/Portable/Simplification/CSharpSimplificationService.Expander.cs
  src/Workspaces/VisualBasic/Portable/Simplification/VisualBasicSimplificationService.Expander.vb
Labels: Area-Compilers, untriaged

#69756 Lazily build a case-insensitive comparison for performance
  src/Compilers/Core/Portable/MetadataReader/PEModule.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Metadata/PE/TypeForwarders.vb
Labels: Area-Compilers, untriaged

#69851 Fix 'use compound coalesce' analyzer in the presence of pp directives
  src/Analyzers/CSharp/Analyzers/UseCompoundAssignment/CSharpUseCompoundCoalesceAssignmentDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/UseCompoundAssignment/CSharpUseCompoundCoalesceAssignmentCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseCompoundAssignment/UseCompoundCoalesceAssignmentTests.cs
Labels: Area-IDE, untriaged

#69792 Add support for reading runsettings passed by the client
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/LanguageServerResources.resx
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Testing/RunTestsHandler.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Testing/TestDiscoverer.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Testing/TestRunner.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.cs.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.de.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.es.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.fr.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.it.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.ja.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.ko.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.pl.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.pt-BR.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.ru.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.tr.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.zh-Hans.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.zh-Hant.xlf
  src/Features/LanguageServer/Protocol/Handler/CodeLens/CodeLensHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Testing/RunTestsParams.cs
Labels: Area-IDE, untriaged

#69810 Mark export attributes as Inherited = false
  src/Features/Core/Portable/Completion/ExportCompletionProviderAttribute.cs
  src/Tools/ExternalAccess/AspNetCore/EmbeddedLanguages/BraceMatching/ExportAspNetCoreEmbeddedLanguageBraceMatcherAttribute.cs
  src/Tools/ExternalAccess/AspNetCore/EmbeddedLanguages/Classification/ExportAspNetCoreEmbeddedLanguageClassifierAttribute.cs
  src/Tools/ExternalAccess/AspNetCore/EmbeddedLanguages/DocumentHighlighting/ExportAspNetCoreEmbeddedLanguageClassifierAttribute.cs
  src/Workspaces/Core/Portable/CodeFixes/ExportCodeFixProviderAttribute.cs
  src/Workspaces/Core/Portable/CodeRefactorings/ExportCodeRefactoringProviderAttribute.cs
Labels: Area-Analyzers, untriaged

#69750 Update "Current Document" background analysis semantics and fix Full Solution analysis with project config changes
  src/EditorFeatures/Test/Diagnostics/DiagnosticAnalyzerServiceTests.cs
  src/EditorFeatures/Test/SolutionCrawler/WorkCoordinatorTests.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.Executor.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.ProjectState.cs
  src/Features/LanguageServer/Protocol/Features/Options/SolutionCrawlerOptionsStorage.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/AbstractPullDiagnosticTestsBase.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/Diagnostics/VisualStudioDiagnosticAnalyzerService.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpCodeActions.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/WorkspaceInProcess.cs
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageStrings.vb
  src/Workspaces/Core/Portable/Shared/Extensions/BackgroundAnalysisScopeExtensions.cs
  src/Workspaces/Core/Portable/SolutionCrawler/BackgroundAnalysisScope.cs
  src/Workspaces/Core/Portable/SolutionCrawler/CompilerDiagnosticsScope.cs
Labels: Area-IDE, untriaged

#69854 Fix source build trying to consume StreamJsonRpc
  src/Workspaces/Core/MSBuild.BuildHost/IRemoteProjectFile.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/Logging/DiagnosticLogItem.cs
  src/Workspaces/Core/MSBuild.BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj
  src/Workspaces/Core/MSBuild.BuildHost/Program.cs
Labels: Area-IDE, untriaged

#69850 Emit BeforeFieldInit flag on interfaces
  src/Compilers/CSharp/Portable/Emitter/Model/NamedTypeSymbolAdapter.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
Labels: Area-Compilers, New Language Feature - Default Interface Impl, untriaged

#69845 Ensure location of a "simple program" type refers to a source tree
  src/Compilers/CSharp/Portable/Declarations/DeclarationTreeBuilder.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/TopLevelStatementsTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/TopLevelStatementsParsingTests.cs
Labels: Area-Compilers, New Language Feature - Simple Programs, untriaged

#69838 Randomize analyzer instantiation to avoid static constructor/jit contention
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs
  src/Workspaces/Core/Portable/Diagnostics/HostDiagnosticAnalyzers.cs
Labels: Area-Analyzers, untriaged

#69849 Properly support (and reject) a limited set of preprocessor directive scenarios for 'use expression body'.
  src/Analyzers/CSharp/Analyzers/UseExpressionBody/Helpers/UseExpressionBodyForIndexersHelper.cs
  src/Analyzers/CSharp/Analyzers/UseExpressionBody/Helpers/UseExpressionBodyForPropertiesHelper.cs
  src/Analyzers/CSharp/Analyzers/UseExpressionBody/Helpers/UseExpressionBodyHelper.cs
  src/Analyzers/CSharp/Analyzers/UseExpressionBody/Helpers/UseExpressionBodyHelper`1.cs
  src/Analyzers/CSharp/Analyzers/UseExpressionBody/UseExpressionBodyDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseExpressionBodyForLambda/UseExpressionBodyForLambdaDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseExpressionBodyForLambda/UseExpressionBodyForLambdaHelpers.cs
  src/Analyzers/CSharp/CodeFixes/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseExpressionBodyForLambda/UseExpressionBodyForLambdaCodeActionHelpers.cs
  src/Analyzers/CSharp/CodeFixes/UseExpressionBodyForLambda/UseExpressionBodyForLambdaCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseExpressionBody/UseExpressionBodyForMethodsAnalyzerTests.cs
  src/Features/CSharp/Portable/ConvertAutoPropertyToFullProperty/CSharpConvertAutoPropertyToFullPropertyCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/ReplaceMethodWithProperty/CSharpReplaceMethodWithPropertyService.cs
  src/Features/CSharp/Portable/ReplacePropertyWithMethods/CSharpReplacePropertyWithMethodsService.cs
  src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/UseExpressionBodyForLambda/UseExpressionBodyForLambdaCodeRefactoringProvider.cs
  src/Features/Core/Portable/ConvertAutoPropertyToFullProperty/AbstractConvertAutoPropertyToFullPropertyCodeRefactoringProvider.cs
  src/Features/Core/Portable/ReplaceMethodWithProperty/IReplaceMethodWithPropertyService.cs
  src/Features/Core/Portable/ReplaceMethodWithProperty/ReplaceMethodWithPropertyCodeRefactoringProvider.cs
  src/Features/VisualBasic/Portable/ConvertAutoPropertyToFullProperty/VisualBasicConvertAutoPropertyToFullProperty.vb
  src/Features/VisualBasic/Portable/ReplaceMethodWithProperty/VisualBasicReplaceMethodWithPropertyService.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/BlockSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/DirectiveSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CodeGeneration/ConstructorGenerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CodeGeneration/ConversionGenerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CodeGeneration/MethodGenerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CodeGeneration/OperatorGenerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CodeGeneration/PropertyGenerator.cs
Labels: Area-IDE, untriaged

#69842 Collection expressions: interface target types should be limited to specific System.Collections.Generic interfaces
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, New Feature - Collection Expressions

#69862 Simplify diagnostic squiggling code
  global.json
  src/EditorFeatures/Core/Diagnostics/AbstractDiagnosticsAdornmentTaggerProvider.cs
  src/EditorFeatures/Core/Diagnostics/AbstractDiagnosticsTaggerProvider.SingleDiagnosticKindPullTaggerProvider.cs
  src/EditorFeatures/Core/Diagnostics/AbstractDiagnosticsTaggerProvider.cs
  src/EditorFeatures/Core/Diagnostics/DiagnosticsClassificationTaggerProvider.cs
Labels: Area-IDE, untriaged

#69770 Collection expressions: support builder methods returning derived or implementing types
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged

#69855 Handle non-member-overriding context in OverrideCompletion
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/OverrideCompletionProviderTests.cs
  src/Features/Core/Portable/Completion/Providers/AbstractOverrideCompletionProvider.ItemGetter.cs
Labels: Area-IDE, untriaged

#69866 Reduce work done in operator overload syntax classifier.
  src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/DiscardSyntaxClassifier.cs
  src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.cs
  src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/OperatorOverloadSyntaxClassifier.cs
  src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/SyntaxTokenClassifier.cs
  src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/UsingDirectiveSyntaxClassifier.cs
  src/Workspaces/Core/Portable/Classification/SyntaxClassification/AbstractSyntaxClassificationService.Worker.cs
  src/Workspaces/Core/Portable/Classification/SyntaxClassification/AbstractSyntaxClassifier.cs
  src/Workspaces/Core/Portable/Classification/SyntaxClassification/ISyntaxClassifier.cs
  src/Workspaces/VisualBasic/Portable/Classification/SyntaxClassification/IdentifierNameSyntaxClassifier.vb
  src/Workspaces/VisualBasic/Portable/Classification/SyntaxClassification/ImportAliasClauseSyntaxClassifier.vb
  src/Workspaces/VisualBasic/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.vb
  src/Workspaces/VisualBasic/Portable/Classification/SyntaxClassification/OperatorOverloadSyntaxClassifier.vb
Labels: Area-IDE, untriaged

#69871 Fix braces issue fixed locally from last PR but accidentally not pushed before merge
  src/Workspaces/VisualBasic/Portable/Classification/SyntaxClassification/OperatorOverloadSyntaxClassifier.vb
Labels: Area-IDE, untriaged

#69888 Change commented-code priority to always beat semantic classification
  src/EditorFeatures/Core.Wpf/Classification/ClassificationTypeFormatDefinitions.cs
Labels: Area-IDE, untriaged

#69890 Localize 17.8
  azure-pipelines-official.yml
Labels: Area-Infrastructure, untriaged

#69889 Minor tweaks to SG generation in the compilation tracker.
  src/VisualStudio/Core/Def/Workspace/VisualStudioSourceGeneratorTelemetryCollectorWorkspaceServiceFactory.cs
  src/Workspaces/Core/Portable/SourceGeneratorTelemetry/ISourceGeneratorTelemetryCollectorWorkspaceService.cs
  src/Workspaces/Core/Portable/SourceGeneratorTelemetry/SourceGeneratorTelemetryCollectorWorkspaceService.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
Labels: Area-IDE, untriaged

#69856 Collection expressions: type inference from spread elements
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged, New Feature - Collection Expressions

#69910 Add SkipApplyOptimizationData option to pr-validation CI pipeline
  azure-pipelines-pr-validation.yml
Labels: Area-Infrastructure, untriaged

#69802 Collection expressions: synthesize readonly list type for IEnumerable<T>, IReadOnlyCollection<T>, IReadOnlyList<T>
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundCollectionExpression.cs
  src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs
  src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNameKind.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNames.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/ReadOnlyListType/SynthesizedReadOnlyListConstructor.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/ReadOnlyListType/SynthesizedReadOnlyListMethod.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/ReadOnlyListType/SynthesizedReadOnlyListProperty.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/ReadOnlyListType/SynthesizedReadOnlyListTypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/ReadOnlyListType/SynthesizedReadOnlyListTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedImplementationMethod.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedInlineArrayTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
  src/Compilers/Core/Portable/CodeGen/PrivateImplementationDetails.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
Labels: Area-Compilers, untriaged, New Feature - Collection Expressions

#69540 Avoid treating methods as SymbolCategory.Other
  src/VisualStudio/Core/Impl/Options/Style/NamingPreferences/SymbolSpecification/SymbolSpecificationViewModel.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/Serialization/SymbolSpecification.cs
Labels: Area-IDE, untriaged

#69814 Sign content of .tgz files
  eng/Signing.props
Labels: Area-Infrastructure, untriaged

#69864 Fix issue with stale cached data in LSP pull diagnostics
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs
Labels: Area-IDE, untriaged

#69901 Update SBRP dependency
  eng/Version.Details.xml
Labels: Area-Infrastructure, untriaged

#69925 [Hackathon experiment] Add ICopilotConfigService and CodeAnalysisSuggestionsCodeRefactoringProvider
  src/Features/Core/Portable/CodeAnalysisSuggestions/CodeAnalysisSuggestionsCodeRefactoringProvider.cs
  src/Features/Core/Portable/Copilot/CopilotConfigFeatures.cs
  src/Features/Core/Portable/Copilot/ICopilotConfigService.cs
  src/Features/Core/Portable/Copilot/ICopilotServiceProvider.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/VisualStudio/Core/Def/Copilot/VisualStudioCopilotConfigService.cs
  src/VisualStudio/Core/Def/Copilot/VisualStudioCopilotServiceProvider.cs
Labels: Area-Analyzers, untriaged

#69924 Use .NET 8 crossgen2's opt-cross-module option
  eng/Versions.props
  src/Workspaces/Remote/ServiceHub.CoreComponents/CoreComponents.Shared.targets
Labels: Area-IDE, untriaged

#69893 Fix escaping and wrapping in vscode hover
  src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionResolveTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Hover/HoverTests.cs
  src/Features/Lsif/GeneratorTest/HoverTests.vb
Labels: Area-IDE, untriaged

#69918 Update LanguageServerHost to use NamedPipeServerStream
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/NamedPipeInformation.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Program.cs
Labels: Area-IDE, untriaged

#69817 Fix folding range bug in C# extension
  src/Features/LanguageServer/Protocol/Handler/FoldingRanges/FoldingRangesHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/FoldingRanges/FoldingRangesTests.cs
Labels: Area-IDE, untriaged

#69927 Fix torn write of struct causing crash in symbol finder.
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Serialization.cs
  src/Workspaces/Core/Portable/Utilities/SpellChecker.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/BKTree.Serialization.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/BKTree.cs
Labels: Area-IDE, untriaged

#69935 Relax remote host APIs so they can work on workspace-green nodes
  src/Workspaces/Core/Portable/Remote/RemoteServiceConnection.cs
  src/Workspaces/Remote/Core/BrokeredServiceConnection.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.cs
Labels: Area-IDE, untriaged

#69921 Document outline updates
  src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineView.xaml
  src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineView.xaml.cs
  src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineViewModel.cs
  src/VisualStudio/Core/Def/LanguageService/AbstractLanguageService`2.VsCodeWindowManager.cs
Labels: Area-IDE, untriaged, OnDeckForServicing

#69930 Add Quick Info test for 'see cref'
  src/EditorFeatures/Test2/IntelliSense/IntellisenseQuickInfoBuilderTests_Links.vb
Labels: Area-IDE, untriaged

#69939 Remove diagnostic source name field
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
Labels: Area-IDE, untriaged

#69878 Allow Razor to format a new document it wants to create
  src/EditorFeatures/Core/LanguageServer/RazorInProcLanguageClient.cs
  src/Features/LanguageServer/Protocol/ExternalAccess/Razor/FormatNewFileHandler.cs
  src/Features/LanguageServer/Protocol/ExternalAccess/Razor/FormatNewFileParams.cs
  src/Features/LanguageServer/ProtocolUnitTests/FormatNewFile/FormatNewFileTests.cs
Labels: Area-IDE, untriaged

#69934 Ensure tuple conversions involved into a tuple binary operator are properly lowered.
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TupleBinaryOperator.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleEqualityTests.cs
Labels: Area-Compilers, untriaged

#69852 Nullable conversion of collection expressions
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/UseCollectionExpressionHelpers.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForBuilderTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForCreateTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForEmptyTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForFluentTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForStackAllocTests.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged, New Feature - Collection Expressions

#69922 Ensure Endfilter basic block is preserved even if technically unreachable.
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTryFinally.cs
  src/Compilers/Core/Portable/CodeGen/ILBuilder.cs
  src/Compilers/Core/Portable/CodeGen/LocalScopeManager.cs
Labels: Area-Compilers, untriaged

#69877 Colorize unbound `partial` identifier as a keyword
  src/EditorFeatures/CSharpTest/Classification/TotalClassifierTests.cs
  src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.cs
Labels: Area-IDE, Community, untriaged

#69953 Provide capacities up front when synchronizing assets.
  src/Workspaces/Remote/Core/AbstractAssetProvider.cs
Labels: Area-IDE, untriaged

#69882 Lazily populate FileIdentifier fields
  src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs
  src/Compilers/CSharp/Portable/Symbols/FileIdentifier.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/SubstitutedNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedEmbeddedAttributeSymbol.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MockNamedTypeSymbol.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/FileModifierTests.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EENamedTypeSymbol.cs
Labels: Area-Compilers, untriaged

#69954 O# ExternalAccess: Provide InlineHint ranking to OmniSharp
  src/Tools/ExternalAccess/OmniSharp/InlineHints/OmniSharpInlineHintsService.cs
  src/Tools/ExternalAccess/OmniSharp/InternalAPI.Unshipped.txt
Labels: Area-IDE, untriaged

#69951 Publish Optprof config for PR validation build
  azure-pipelines-pr-validation.yml
Labels: Area-Infrastructure, untriaged

#69952 Include a bit in DocumentId to indicate if it corresponds to a SG document or not
  src/Workspaces/Core/Portable/FindSymbols/Shared/AbstractSyntaxIndex_Persistence.cs
  src/Workspaces/Core/Portable/Shared/Extensions/ProjectExtensions.cs
  src/Workspaces/Core/Portable/Workspace/Solution/DocumentId.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Project.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratedDocumentIdentity.cs
Labels: Area-IDE, untriaged

#69917 Do source-generation only in our OOP process.
  eng/targets/Services.props
  src/Compilers/Test/Core/SourceGeneration/TestGenerators.cs
  src/Features/LanguageServer/Protocol/Features/Options/WorkspaceConfigurationOptionsStorage.cs
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/DiagnosticItem/SourceGeneratorItem.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/Workspaces/Core/Portable/SourceGeneration/IRemoteSourceGenerationService.cs
  src/Workspaces/Core/Portable/SourceGeneratorTelemetry/SourceGeneratorTelemetryCollectorWorkspaceService.cs
  src/Workspaces/Core/Portable/Workspace/IWorkspaceConfigurationService.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker_Generators.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratedDocumentIdentity.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratedDocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratorIdentity.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTestHelpers.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemostHostClient.cs
  src/Workspaces/CoreTestUtilities/WorkspaceTestUtilities.cs
  src/Workspaces/Remote/Core/RemoteWorkspacesResources.resx
  src/Workspaces/Remote/Core/ServiceDescriptors.cs
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.cs.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.de.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.es.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.fr.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.it.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ja.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ko.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.pl.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.pt-BR.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ru.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.tr.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.zh-Hans.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.zh-Hant.xlf
  src/Workspaces/Remote/ServiceHub/Services/SourceGeneration/RemoteSourceGenerationService.cs
Labels: Area-IDE, untriaged

#69782 Refactoring of synthesized types tracking across EnC generations
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/CSharpSymbolMatcher.cs
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/EmitHelpers.cs
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/PEDeltaAssemblyBuilder.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeManager.Templates.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNames.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/SymbolMatcherTests.cs
  src/Compilers/Core/CodeAnalysisTest/Collections/ImmutableSegmentedDictionaryTest.cs
  src/Compilers/Core/Portable/Emit/AnonymousTypeValue.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/DeltaMetadataWriter.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/EmitBaseline.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/IPEDeltaAssemblyBuilder.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/SymbolMatcher.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/SynthesizedTypeMaps.cs
  src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/EmitHelpers.vb
  src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/PEDeltaAssemblyBuilder.vb
  src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/VisualBasicSymbolMatcher.vb
  src/Compilers/VisualBasic/Portable/Symbols/AnonymousTypes/AnonymousTypeManager_Templates.vb
  src/Compilers/VisualBasic/Test/Emit/Emit/EditAndContinue/EditAndContinueTestBase.vb
  src/Compilers/VisualBasic/Test/Emit/Emit/EditAndContinue/SymbolMatcherTests.vb
  src/Dependencies/Collections/ImmutableSegmentedDictionary`2+KeyCollection.cs
  src/Dependencies/Collections/ImmutableSegmentedDictionary`2+ValueCollection.cs
Labels: Area-Interactive, untriaged

#69966 Temp fix to bring vsmac package
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#69848 Replace InterceptorsPreview with InterceptorsPreviewNamespaces=global
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/EndToEnd/EndToEndTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs
Labels: Area-Compilers, untriaged

#69896 Dev/toddgrun/revert 769dfa13624dae1bbba1afbdfaeb85f928843004 and use multi dictionary pool
  src/Compilers/CSharp/Portable/Symbols/ReferenceManager.cs
  src/Compilers/Core/Portable/InternalUtilities/MultiDictionary.cs
  src/Compilers/Core/Portable/MetadataReference/AssemblyIdentityExtensions.cs
  src/Compilers/Core/Portable/ReferenceManager/AssemblyData.cs
  src/Compilers/Core/Portable/ReferenceManager/AssemblyDataForAssemblyBeingBuilt.cs
  src/Compilers/Core/Portable/ReferenceManager/CommonReferenceManager.Binding.cs
  src/Compilers/Core/Portable/ReferenceManager/CommonReferenceManager.Resolution.cs
  src/Compilers/VisualBasic/Portable/Symbols/ReferenceManager.vb
Labels: Area-Compilers, untriaged

#69959 Speicfy System.Private.Uri and System.Net.Http versions
  eng/Versions.props
  src/Compilers/Test/Core/Microsoft.CodeAnalysis.Test.Utilities.csproj
  src/EditorFeatures/CSharpTest/Microsoft.CodeAnalysis.CSharp.EditorFeatures.UnitTests.csproj
  src/EditorFeatures/Test/Microsoft.CodeAnalysis.EditorFeatures.UnitTests.csproj
  src/EditorFeatures/Test2/Microsoft.CodeAnalysis.EditorFeatures2.UnitTests.vbproj
  src/EditorFeatures/TestUtilities/Microsoft.CodeAnalysis.EditorFeatures.Test.Utilities.csproj
  src/EditorFeatures/TestUtilities2/Microsoft.CodeAnalysis.EditorFeatures.Test.Utilities2.vbproj
  src/EditorFeatures/VisualBasicTest/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.UnitTests.vbproj
  src/Features/TestUtilities/Microsoft.CodeAnalysis.Features.Test.Utilities.csproj
  src/Tools/ExternalAccess/FSharpTest/Microsoft.CodeAnalysis.ExternalAccess.FSharp.UnitTests.csproj
  src/Tools/IdeCoreBenchmarks/IdeCoreBenchmarks.csproj
  src/Tools/TestDiscoveryWorker/TestDiscoveryWorker.csproj
  src/VisualStudio/Core/Test.Next/Roslyn.VisualStudio.Next.UnitTests.csproj
  src/VisualStudio/TestUtilities2/Microsoft.VisualStudio.LanguageServices.Test.Utilities2.vbproj
Labels: Area-Infrastructure, untriaged

#70001 Update ICSharpCode.Decompiler to consume important bug fix
  eng/Versions.props
  src/EditorFeatures/Test/MetadataAsSource/AbstractMetadataAsSourceTests.cs
Labels: Area-Infrastructure, untriaged

#69998 Do not offer 'make struct readonly' when events are present
  src/Analyzers/CSharp/Analyzers/MakeStructReadOnly/CSharpMakeStructReadOnlyDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/MakeStructReadOnly/MakeStructReadOnlyTests.cs
Labels: Area-IDE, untriaged

#69635 [17.7] Cache substituted base type
  src/Compilers/CSharp/Portable/Symbols/SubstitutedNamedTypeSymbol.cs
  src/Compilers/CSharp/Test/EndToEnd/EndToEndTests.cs
Labels: Area-Compilers, untriaged

#69973 [Performance] Avoid 500MB of HashSet enumerator allocations calling `Any`
  src/Compilers/Core/Portable/Collections/HashSetExtensions.cs
Labels: Area-Compilers, Community

#69999 Move methods to more appropriate file
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker_Generators.cs
Labels: Area-IDE, untriaged

#69239 Exclude BCL binaries in Roslyn ServiceHub vsix
  src/Workspaces/Remote/ServiceHub.CoreComponents/CoreComponents.Shared.targets
Labels: Area-IDE, untriaged

#69972 [Performance] Avoid 1GB of Enumerator boxing allocations
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
Labels: Area-Compilers, Community

#70020 Add support for navigating to the definition of the target label of a `goto`
  src/EditorFeatures/Test2/GoToDefinition/CSharpGoToDefinitionTests.vb
  src/EditorFeatures/Test2/GoToDefinition/VisualBasicGoToDefinitionTests.vb
  src/Features/CSharp/Portable/GoToDefinition/CSharpGoToDefinitionSymbolService.cs
  src/Features/VisualBasic/Portable/GoToDefinition/VisualBasicGoToDefinitionSymbolService.vb
Labels: Area-IDE, Community, untriaged

#69983 Support converting collection-initializers to collection-expressions in more cases.
  src/Analyzers/CSharp/CodeFixes/UseCollectionInitializer/CSharpUseCollectionInitializerCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests_CollectionExpression.cs
  src/Analyzers/CSharp/Tests/UseObjectInitializer/UseObjectInitializerTests.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/AbstractObjectCreationExpressionAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/AbstractUseCollectionInitializerAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/AbstractUseCollectionInitializerDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/UpdateExpressionState.cs
  src/Analyzers/Core/Analyzers/UseObjectInitializer/UseNamedMemberInitializerAnalyzer.cs
  src/Analyzers/Core/CodeFixes/UseCollectionInitializer/AbstractUseCollectionInitializerCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseObjectInitializer/AbstractUseObjectInitializerCodeFixProvider.cs
  src/Analyzers/VisualBasic/CodeFixes/UseCollectionInitializer/VisualBasicUseCollectionInitializerCodeFixProvider.vb
  src/Features/Core/Portable/IntroduceParameter/IntroduceParameterDocumentRewriter.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFactsExtensions.cs
Labels: Area-IDE, untriaged

#69946 Add new endpoint in roslyn to get token for multiple ranges
  src/EditorFeatures/Core/LanguageServer/RazorInProcLanguageClient.cs
  src/Features/LanguageServer/Protocol/ExternalAccess/Razor/SemanticTokensRangesHandler.cs
  src/Features/LanguageServer/Protocol/ExternalAccess/Razor/SemanticTokensRangesParams.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHelpers.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensRangeHandler.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensRangesHandlerFactory.cs
  src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/AbstractSemanticTokensTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/SemanticTokensRangeTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/SemanticTokensRangesTests.cs
  src/Features/Lsif/Generator/Generator.cs
Labels: Area-IDE, Community, untriaged

#70017 Optimize allocations in TextReader.ReadToEnd utilized by SourceText.From
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Utilities/TextReaderWithLength.cs
Labels: Area-IDE, untriaged

#70030 Move to latest 8.0 preview version of MS.CA.NetAnalyzers package
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Analyzers, untriaged

#70038 Update msbuild locator to pick up fix to probe more SDK locations
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#70028 Fix crash in 'use object/collection initializer' in VB.
  src/Analyzers/CSharp/Analyzers/CSharpAnalyzers.projitems
  src/Analyzers/CSharp/Analyzers/UseCollectionInitializer/CSharpObjectCreationHelpers.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionInitializer/CSharpUseCollectionInitializerAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionInitializer/CSharpUseCollectionInitializerDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseObjectInitializer/CSharpUseNamedMemberInitializerAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseObjectInitializer/CSharpUseObjectInitializerDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionInitializer/CSharpUseCollectionInitializerCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseObjectInitializer/CSharpUseObjectInitializerCodeFixProvider.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/AbstractObjectCreationExpressionAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/AbstractUseCollectionInitializerAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/AbstractUseCollectionInitializerDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseObjectInitializer/AbstractUseObjectInitializerDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseObjectInitializer/UseNamedMemberInitializerAnalyzer.cs
  src/Analyzers/Core/CodeFixes/UseCollectionInitializer/AbstractUseCollectionInitializerCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseObjectInitializer/AbstractUseObjectInitializerCodeFixProvider.cs
  src/Analyzers/VisualBasic/Analyzers/UseCollectionInitializer/VisualBasicCollectionInitializerAnalyzer.vb
  src/Analyzers/VisualBasic/Analyzers/UseCollectionInitializer/VisualBasicObjectCreationHelpers.vb
  src/Analyzers/VisualBasic/Analyzers/UseCollectionInitializer/VisualBasicUseCollectionInitializerDiagnosticAnalyzer.vb
  src/Analyzers/VisualBasic/Analyzers/UseObjectInitializer/VisualBasicUseNamedMemberInitializerAnalyzer.vb
  src/Analyzers/VisualBasic/Analyzers/UseObjectInitializer/VisualBasicUseObjectInitializerDiagnosticAnalyzer.vb
  src/Analyzers/VisualBasic/Analyzers/VisualBasicAnalyzers.projitems
  src/Analyzers/VisualBasic/CodeFixes/UseCollectionInitializer/VisualBasicUseCollectionInitializerCodeFixProvider.vb
  src/Analyzers/VisualBasic/CodeFixes/UseObjectInitializer/VisualBasicUseObjectInitializerCodeFixProvider.vb
  src/Analyzers/VisualBasic/Tests/UseCollectionInitializer/UseCollectionInitializerTests.vb
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/AbstractCodeActionOrUserDiagnosticTest.cs
Labels: Area-IDE, untriaged

#70023 Bump the NuGet.Frameworks version
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#70026 Add Primary Constructor tests for some scenarios from Test Plan
  src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs
Labels: Area-Compilers, untriaged, New Feature - Primary Constructors

#69673 Avoid static overhead for switch-over-string optimization
  src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
  src/Compilers/CSharp/Portable/Symbols/FunctionPointers/FunctionPointerMethodSymbol.cs
  src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.EnumeratedValueSet.cs
  src/Compilers/Core/Portable/Collections/ImmutableHashSetExtensions.cs
  src/Compilers/Core/Portable/Diagnostic/ProgrammaticSuppressionInfo.cs
  src/Dependencies/PooledObjects/ArrayBuilder.cs
  src/Tools/IdeCoreBenchmarks/IdeCoreBenchmarks.csproj
  src/Tools/IdeCoreBenchmarks/SwitchStatementBenchmarks.cs
Labels: Area-Compilers, untriaged

#69970 [Performance] Reduce array allocations of BadArguments
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MemberAnalysisResult.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs
Labels: Area-Compilers, Community

#70051 Update Microsoft.DevDiv.Optimization.Data.PowerShell to 1.0803
  eng/Versions.props
  eng/build.ps1
Labels: Area-Infrastructure, untriaged

#70009 Handle property without accessors in `Binder.ReceiverIsSubjectToCloning`
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers, untriaged

#69947 Remove indexer filtering from lookup
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs
Labels: Area-Compilers, untriaged, New Feature - Primary Constructors

#69957 Perform a null check for a pattern-based fixed statement over nullable value type.
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_FixedStatement.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/UnsafeTests.cs
Labels: Area-Compilers, untriaged

#70047 Prevent infinite lookup cycle through bases of a containing type of an enum or a delegate type.
  src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Bases.cs
  src/Compilers/CSharp/Portable/Utilities/TypeSymbolExtensions.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/BindingTests.cs
Labels: Area-Compilers, untriaged

#69874 Fix declaration snippets after `partial` keyword
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpClassSnippetCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpEnumSnippetCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpInterfaceSnippetCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpStructSnippetCompletionProviderTests.cs
  src/Features/CSharp/Portable/Snippets/AbstractCSharpTypeSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpClassSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpEnumSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpInterfaceSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpStructSnippetProvider.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractTypeSnippetProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTreeExtensions.cs
Labels: Area-IDE, Community, untriaged

#70002 Update Razor to 8.0.0-preview.23465.2
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#69475 Add BuildOnlyDiagnosticIds LSP request handler
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/CSharp/Portable/Diagnostics/LanguageServer/CSharpLspBuildOnlyDiagnostics.cs
  src/Features/Core/Portable/Diagnostics/LanguageServer/ILspBuildOnlyDiagnostics.cs
  src/Features/Core/Portable/Diagnostics/LanguageServer/ILspBuildOnlyDiagnosticsMetadata.cs
  src/Features/Core/Portable/Diagnostics/LanguageServer/LspBuildOnlyDiagnosticsAttribute.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/BuildOnlyDiagnosticIdsHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/BuildOnlyDiagnosticIdsHandlerTests.cs
  src/Features/VisualBasic/Portable/Diagnostics/LanguageServer/VisualBasicLspBuildOnlyDiagnostics.vb
  src/Features/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.Features.vbproj
  src/Workspaces/Core/Portable/Diagnostics/DiagnosticAnalyzerInfoCache.cs
Labels: Area-IDE, untriaged

#70064 Deflect blame away from Roslyn.Utilities.Contract on failures
  src/VisualStudio/Core/Def/Watson/FaultReporter.cs
Labels: Area-IDE, untriaged

#70068 Fix PullDiagnosticCategories to DiagnosticKind mapping in DocumentPullDiagnosticHandler
  src/EditorFeatures/TestUtilities/Diagnostics/TestAnalyzerReferenceByLanguage.cs
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DocumentPullDiagnosticHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/AbstractPullDiagnosticTestsBase.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
Labels: Area-Analyzers, untriaged

#70050 Add "Primary Constructors" to Compiler Test Plan.md
  docs/contributing/Compiler Test Plan.md
Labels: Area-Compilers, untriaged

#70062 Remove unused member
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeStyle/CSharpIdeCodeStyleOptions.cs
Labels: Area-IDE, Community, untriaged

#70078 By default queue speedometer when insert Roslyn
  eng/pipelines/insert.yml
Labels: Area-Infrastructure, untriaged

#70073 Remove usage of elastic trivia when rewriting collections
  src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpCollectionExpressionRewriter.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForBuilderTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForCreateTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForEmptyTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForFluentTests.cs
Labels: Area-IDE, untriaged

#70083 Avoid iterator allocations when creating bloom filters
  src/EditorFeatures/Test/Utilities/BloomFilterTests.cs
  src/Workspaces/Core/Portable/Shared/Utilities/BloomFilter.cs
Labels: Area-IDE, untriaged

#70086 Do not offer 'delegate' inside an attribute
  src/EditorFeatures/CSharpTest2/Recommendations/DelegateKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/MethodKeywordRecommenderTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/DelegateKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/MethodKeywordRecommender.cs
Labels: Area-IDE, untriaged

#70085 Move code to simpler type for interval trees
  src/Analyzers/CSharp/Analyzers/RemoveUnnecessaryNullableDirective/CSharpRemoveUnnecessaryNullableDirectiveDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/RemoveUnnecessaryNullableDirective/NullableImpactingSpanWalker.cs
  src/Analyzers/Core/Analyzers/SimplifyTypeNames/SimplifyTypeNamesDiagnosticAnalyzerBase.cs
  src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpSimplifyTypeNamesDiagnosticAnalyzer.cs
  src/Features/CSharp/Portable/Diagnostics/Analyzers/TypeSyntaxSimplifierWalker.cs
  src/Features/VisualBasic/Portable/Diagnostics/Analyzers/TypeSyntaxSimplifierWalker.vb
  src/Features/VisualBasic/Portable/Diagnostics/Analyzers/VisualBasicSimplifyTypeNamesDiagnosticAnalyzer.vb
  src/Workspaces/Core/Portable/Editing/ImportAdderService.cs
  src/Workspaces/Core/Portable/Simplification/AbstractSimplificationService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/CSharpSyntaxFormatting.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Engine/AggregatedFormattingResult.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Engine/FormattingResult.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Engine/Trivia/TriviaRewriter.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/TextSpanIntervalIntrospector.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/SimpleIntervalTreeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/AbstractSyntaxFormatting.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Engine/AbstractAggregatedFormattingResult.cs
  src/Workspaces/VisualBasic/Portable/CodeCleanup/Providers/AbstractTokensCodeCleanupProvider.vb
  src/Workspaces/VisualBasic/Portable/CodeCleanup/Providers/NormalizeModifiersOrOperatorsCodeCleanupProvider.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/AggregatedFormattingResult.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/FormattingResult.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/Trivia/TriviaDataFactory.TriviaRewriter.vb
  src/Workspaces/VisualBasic/Portable/Formatting/VisualBasicSyntaxFormatting.vb
Labels: Area-IDE, untriaged

#70090 Workaround the deployment issue in Arcade
  src/VisualStudio/Setup.ServiceHub/arm64/Roslyn.VisualStudio.ServiceHub.Setup.arm64.csproj
Labels: Area-Infrastructure, untriaged

#70065 Revert "Merge pull request #69917 from CyrusNajmabadi/sgOOP2"
  eng/targets/Services.props
  src/Compilers/Test/Core/SourceGeneration/TestGenerators.cs
  src/Features/LanguageServer/Protocol/Features/Options/WorkspaceConfigurationOptionsStorage.cs
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/DiagnosticItem/SourceGeneratorItem.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/Workspaces/Core/Portable/SourceGeneration/IRemoteSourceGenerationService.cs
  src/Workspaces/Core/Portable/SourceGeneratorTelemetry/SourceGeneratorTelemetryCollectorWorkspaceService.cs
  src/Workspaces/Core/Portable/Workspace/IWorkspaceConfigurationService.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker_Generators.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratedDocumentIdentity.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratedDocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratorIdentity.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTestHelpers.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemostHostClient.cs
  src/Workspaces/CoreTestUtilities/WorkspaceTestUtilities.cs
  src/Workspaces/Remote/Core/RemoteWorkspacesResources.resx
  src/Workspaces/Remote/Core/ServiceDescriptors.cs
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.cs.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.de.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.es.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.fr.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.it.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ja.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ko.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.pl.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.pt-BR.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ru.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.tr.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.zh-Hans.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.zh-Hant.xlf
  src/Workspaces/Remote/ServiceHub/Services/SourceGeneration/RemoteSourceGenerationService.cs
Labels: Area-IDE, untriaged

#70100 Do not show `and` or `or` keywords after arrow of pointer access expression in patterns
  src/EditorFeatures/CSharpTest2/Recommendations/AndKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/OrKeywordRecommenderTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs
Labels: Area-IDE, Community, untriaged

#70087 Change AssemblyData.AvailableSymbols to ImmutableArray instead of IEnumerable
  src/Compilers/CSharp/Portable/Symbols/ReferenceManager.cs
  src/Compilers/Core/Portable/ReferenceManager/AssemblyData.cs
  src/Compilers/Core/Portable/ReferenceManager/AssemblyDataForAssemblyBeingBuilt.cs
  src/Compilers/Core/Portable/ReferenceManager/Compilation_MetadataCache.cs
  src/Compilers/VisualBasic/Portable/Symbols/ReferenceManager.vb
Labels: Area-Compilers, untriaged

#70104 Do not show `nint` and `nuint` in attribute name context
  src/EditorFeatures/CSharpTest2/Recommendations/NativeIntegerKeywordRecommenderTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/AbstractNativeIntegerKeywordRecommender.cs
Labels: Area-IDE, Community, untriaged

#70082 Add a struct enumerator for NodeStateTable<T>
  src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs
Labels: Area-Compilers, untriaged

#70098 Use raw strings in regex tests
  src/EditorFeatures/CSharpTest2/EmbeddedLanguages/RegularExpressions/CSharpRegexParserTests_BasicTests.cs
  src/EditorFeatures/CSharpTest2/EmbeddedLanguages/RegularExpressions/CSharpRegexParserTests_DotnetNegativeTests.cs
  src/EditorFeatures/CSharpTest2/EmbeddedLanguages/RegularExpressions/CSharpRegexParserTests_ReferenceTests.cs
Labels: Area-IDE, untriaged

#70110 Fix signature-help/completion with primary constructors
  src/EditorFeatures/CSharpTest/SignatureHelp/PrimaryConstructorBaseTypeSignatureHelpProviderTests.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Features/CSharp/Portable/Completion/CompletionProviders/NamedParameterCompletionProvider.cs
  src/Features/CSharp/Portable/SignatureHelp/PrimaryConstructorBaseTypeSignatureHelpProvider.cs
Labels: Area-IDE, untriaged

#69458 Don't treat user-defined casts as constants in analyzers for "use pattern matching" and "convert if to switch"
  src/Analyzers/CSharp/Analyzers/UsePatternCombinators/CSharpUsePatternCombinatorsAnalyzer.cs
  src/Features/CSharpTest/UsePatternCombinators/CSharpUsePatternCombinatorsDiagnosticAnalyzerTests.cs
  src/Features/Core/Portable/ConvertIfToSwitch/AbstractConvertIfToSwitchCodeRefactoringProvider.Analyzer.cs
Labels: Area-IDE, Community, untriaged

#70102 Do not offer to convert AsSpan on lvalues to collection expressions
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForFluentDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForFluentTests.cs
Labels: Area-IDE, untriaged

#70096 Fallback gracefully when running on runtimes that only support the Invariant culture
  src/Features/Core/Portable/Completion/PatternMatchHelper.cs
Labels: Area-IDE, untriaged

#69936 Use no-op global assembly cache helper when running under .net core
  src/Compilers/Shared/GlobalAssemblyCacheHelpers/ClrGlobalAssemblyCache.cs
  src/Compilers/Shared/GlobalAssemblyCacheHelpers/DotNetCoreGlobalAssemblyCache.cs
  src/Compilers/Shared/GlobalAssemblyCacheHelpers/GlobalAssemblyCache.cs
  src/Scripting/Core/Microsoft.CodeAnalysis.Scripting.csproj
Labels: Area-Compilers, untriaged

#70036 Initialize usage of ProjectDependencyGraph.Empty to start with a null reverseReferencesMap
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectDependencyGraph.cs
Labels: Area-IDE, untriaged

#70097 Don't recreate whole completion item upon calculation of properties.
  src/Features/Core/Portable/Completion/Providers/SymbolCompletionItem.cs
Labels: Area-IDE, untriaged

#70125 Update config file
  eng/Versions.props
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#70126 Always respond to the 'cycle through references' command
  src/EditorFeatures/Core/ReferenceHighlighting/NagivateToHighlightReferenceCommandHandler.StartComparer.cs
  src/EditorFeatures/Core/ReferenceHighlighting/NavigateToHighlightReferenceCommandHandler.cs
Labels: Area-IDE, untriaged

#70031 Consolidate exception stack trace reporting from analyzers
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/SyntaxAwareGeneratorTests.cs
  src/Compilers/Core/CodeAnalysisTest/Diagnostics/AnalysisContextInfoTests.cs
  src/Compilers/Core/CodeAnalysisTest/Diagnostics/SuppressMessageAttributeCompilerTests.cs
  src/Compilers/Core/Portable/CodeAnalysisResources.resx
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.cs.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.de.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.es.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.fr.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.it.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.ja.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.ko.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.pl.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.pt-BR.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.ru.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.tr.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.zh-Hans.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.zh-Hant.xlf
  src/Compilers/VisualBasic/Portable/VBResources.resx
  src/Compilers/VisualBasic/Portable/xlf/VBResources.cs.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.de.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.es.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.fr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.it.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ja.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ko.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pl.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pt-BR.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ru.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.tr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hans.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hant.xlf
  src/Compilers/VisualBasic/Test/Semantic/SourceGeneration/GeneratorDriverTests.vb
Labels: Area-Compilers, New Feature - Source Generators

#70136 [17.8] Consolidate exception stack trace reporting from analyzers
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/SyntaxAwareGeneratorTests.cs
  src/Compilers/Core/CodeAnalysisTest/Diagnostics/AnalysisContextInfoTests.cs
  src/Compilers/Core/CodeAnalysisTest/Diagnostics/SuppressMessageAttributeCompilerTests.cs
  src/Compilers/Core/Portable/CodeAnalysisResources.resx
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.cs.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.de.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.es.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.fr.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.it.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.ja.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.ko.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.pl.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.pt-BR.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.ru.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.tr.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.zh-Hans.xlf
  src/Compilers/Core/Portable/xlf/CodeAnalysisResources.zh-Hant.xlf
  src/Compilers/VisualBasic/Portable/VBResources.resx
  src/Compilers/VisualBasic/Portable/xlf/VBResources.cs.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.de.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.es.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.fr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.it.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ja.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ko.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pl.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pt-BR.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ru.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.tr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hans.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hant.xlf
  src/Compilers/VisualBasic/Test/Semantic/SourceGeneration/GeneratorDriverTests.vb
Labels: Area-Compilers, untriaged

#70118 Fix 'make member readonly' with inline array fields
  src/Analyzers/CSharp/Tests/MakeStructMemberReadOnly/MakeStructMemberReadOnlyTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ExpressionSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ITypeSymbolExtensions.cs
Labels: Area-IDE, untriaged

#70103 Change completion sorting to use ArrayBuilder instead of SegmentedList
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/ItemManager.cs
Labels: Area-IDE, untriaged

#69981 Collection expressions: verify element type when reporting conversion error to CollectionBuilder type
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged

#69774 EnC: Parameter and property analysis
  SpellingExclusions.dic
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/CSharpSymbolMatcher.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/DeletedEventDefinition.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/DeletedPropertyDefinition.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/DeltaMetadataWriter.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/SymbolChanges.cs
  src/Compilers/Core/Portable/Emit/SemanticEdit.cs
  src/Compilers/Core/Portable/InternalUtilities/OneOrMany.cs
  src/Compilers/Core/Portable/PEWriter/ReferenceIndexerBase.cs
  src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/VisualBasicSymbolMatcher.vb
  src/Compilers/VisualBasic/Test/Emit/Emit/EditAndContinue/EditAndContinueClosureTests.vb
  src/Compilers/VisualBasic/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.vb
  src/EditorFeatures/CSharpTest/EditAndContinue/ActiveStatementTests.Methods.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/ActiveStatementTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/Helpers/EditingTestBase.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/LineEditTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/StatementEditingTests.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/TopLevelEditingTests.cs
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/EditorFeatures/Test/Utilities/SymbolEquivalenceComparerTests.cs
  src/EditorFeatures/TestUtilities/EditAndContinue/EditAndContinueTestHelpers.cs
  src/EditorFeatures/VisualBasicTest/EditAndContinue/ActiveStatementTests.vb
  src/EditorFeatures/VisualBasicTest/EditAndContinue/LineEditTests.vb
  src/EditorFeatures/VisualBasicTest/EditAndContinue/TopLevelEditingTests.vb
  src/Features/CSharp/Portable/EditAndContinue/CSharpEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueDiagnosticDescriptors.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/Core/Portable/EditAndContinue/RudeEditKind.cs
  src/Features/Core/Portable/EditAndContinue/SemanticEditInfo.cs
  src/Features/Core/Portable/EditAndContinue/Utilities/Extensions.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Features/VisualBasic/Portable/EditAndContinue/VisualBasicEditAndContinueAnalyzer.vb
  src/Workspaces/CoreTest/SymbolKeyTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/SymbolKey/SymbolKey.ParameterSymbolKey.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/SymbolKey/SymbolKey.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/IDictionaryExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/SymbolEquivalenceComparer.SignatureTypeSymbolEquivalenceComparer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/SymbolEquivalenceComparer.cs
Labels: Area-Compilers, Area-Interactive, untriaged

#69806 EnC: Generate correct state mapping for methods containing await foreach
  src/Compilers/CSharp/Portable/Binder/Binder_Await.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundAwaitExpressionDebugInfo.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncIteratorMethodToStateMachineRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncMethodToStateMachineRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/IteratorRewriter/IteratorMethodToStateMachineRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Await.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_UsingStatement.cs
  src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs
  src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/MethodToStateMachineRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/ResumableStateMachineStateAllocator.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncLocalsTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAwaitForeachTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueStateMachineTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/LocalSlotMappingTests.cs
  src/Compilers/Core/CodeAnalysisTest/Emit/CustomDebugInfoTests.cs
  src/Compilers/Core/Portable/CodeGen/AwaitDebugId.cs
  src/Compilers/Core/Portable/CodeGen/DebugId.cs
  src/Compilers/Core/Portable/CodeGen/StateMachineStateDebugInfo.cs
  src/Compilers/Core/Portable/CodeGen/VariableSlotAllocator.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/DefinitionMap.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/EncVariableSlotAllocator.cs
  src/Compilers/Core/Portable/Emit/EditAndContinueMethodDebugInformation.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
  src/Compilers/VisualBasic/Portable/CodeGen/ResumableStateMachineStateAllocator.vb
  src/Compilers/VisualBasic/Portable/Lowering/StateMachineRewriter/StateMachineRewriter.StateMachineMethodToClassRewriter.vb
  src/Compilers/VisualBasic/Test/Emit/PDB/PDBAsyncTests.vb
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/EEAssemblyBuilder.cs
  src/ExpressionEvaluator/VisualBasic/Source/ExpressionCompiler/EEAssemblyBuilder.vb
Labels: Area-Compilers, untriaged

#70075 Add a struct enumerator for WeakList<T>
  src/Compilers/Core/CodeAnalysisTest/InternalUtilities/WeakListTests.cs
  src/Compilers/Core/Portable/InternalUtilities/WeakList.cs
Labels: Area-Compilers, untriaged

#70140 Alternate approach to checksums for @toddgrun
  src/Workspaces/Remote/ServiceHub/Host/ChecksumSynchronizer.cs
Labels: Area-IDE, untriaged

#69968 Add support for collection expressions in attributes
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, New Feature - Collection Expressions

#70144 Localize "Not Applicable"
  src/VisualStudio/Core/Def/FindReferences/Entries/SimpleMessageEntry.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
Labels: Area-IDE, untriaged

#70143 Fall back to using .NET Core MSBuild if no VS is installed
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/BuildHostProcessManager.cs
  src/Workspaces/Core/MSBuild.BuildHost/BuildHost.cs
  src/Workspaces/Core/MSBuild.BuildHost/IBuildHost.cs
Labels: Area-IDE, untriaged

#70111 PERF: CompletionService.MergeAndPruneCompletionLists doesn't need to always sort
  src/EditorFeatures/CSharpTest/Completion/CompletionServiceTests.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/CompletionSource.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Features/Core/Portable/Completion/CompletionOptions.cs
  src/Features/Core/Portable/Completion/CompletionService_GetCompletions.cs
Labels: Area-IDE, untriaged

#70112 Port accessibility fix for the text view control in lightbulb preview
  src/EditorFeatures/Core.Wpf/Preview/DifferenceViewerPreview.NavigationalCommandTarget.cs
  src/EditorFeatures/Core.Wpf/Preview/DifferenceViewerPreview.cs
  src/EditorFeatures/Core.Wpf/Preview/PreviewFactoryService.cs
  src/EditorFeatures/Core/Preview/AbstractPreviewFactoryService.cs
  src/EditorFeatures/Core/Preview/DifferenceViewerPreview.cs
  src/EditorFeatures/Core/Preview/IDifferenceViewerPreview.cs
  src/VisualStudio/Core/Def/PreviewPane/PreviewPane.xaml
  src/VisualStudio/Core/Def/PreviewPane/PreviewPane.xaml.cs
Labels: Area-Analyzers, untriaged

#70130 Address test feedback
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.InitializationOptions.cs
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/AbstractPullDiagnosticTestsBase.cs
Labels: Area-Analyzers, untriaged

#70147 [Backport] Port accessibility fix for the text view control in lightbulb preview
  src/EditorFeatures/Core.Wpf/Preview/DifferenceViewerPreview.NavigationalCommandTarget.cs
  src/EditorFeatures/Core.Wpf/Preview/DifferenceViewerPreview.cs
  src/EditorFeatures/Core.Wpf/Preview/PreviewFactoryService.cs
  src/EditorFeatures/Core/Preview/AbstractPreviewFactoryService.cs
  src/EditorFeatures/Core/Preview/DifferenceViewerPreview.cs
  src/EditorFeatures/Core/Preview/IDifferenceViewerPreview.cs
  src/VisualStudio/Core/Def/PreviewPane/PreviewPane.xaml
  src/VisualStudio/Core/Def/PreviewPane/PreviewPane.xaml.cs
Labels: Area-Analyzers, untriaged

#68892 Add effective severities custom property array to error log
  docs/compilers/Error Log Format.md
  src/Compilers/CSharp/Test/CommandLine/SarifErrorLoggerTests.cs
  src/Compilers/CSharp/Test/CommandLine/SarifV1ErrorLoggerTests.cs
  src/Compilers/CSharp/Test/CommandLine/SarifV2ErrorLoggerTests.cs
  src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs
  src/Compilers/Core/Portable/CommandLine/SarifV2ErrorLogger.cs
  src/Compilers/Core/Portable/Diagnostic/DiagnosticDescriptor.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs
  src/Compilers/Test/Core/Diagnostics/CommonDiagnosticAnalyzers.cs
Labels: Area-Analyzers, Area-Compilers, untriaged

#70089 Fix issue where change namespace throws if there are duplicate Progra…
  src/Features/CSharpTest/SyncNamespace/SyncNamespaceTests_ChangeNamespace.cs
  src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.MoveTypeEditor.cs
  src/Features/Core/Portable/CodeRefactorings/SyncNamespace/AbstractChangeNamespaceService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SemanticFacts/CSharpSemanticFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SemanticFacts/ISemanticFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SemanticFacts/VisualBasicSemanticFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/SemanticsFactsService/AbstractSemanticFactsService.cs
Labels: Area-IDE, untriaged

#70060 Support 'wrapping' for collection expressions.
  src/Features/CSharp/Portable/Wrapping/CSharpWrappingCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/Wrapping/SeparatedSyntaxList/CSharpCollectionExpressionWrapper.cs
  src/Features/CSharp/Portable/Wrapping/SeparatedSyntaxList/CSharpParameterWrapper.cs
  src/Features/CSharpTest/Wrapping/CollectionExpressionWrappingTests.cs
  src/Features/CSharpTest/Wrapping/InitializerExpressionWrappingTests.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/Wrapping/AbstractCodeActionComputer.cs
  src/Features/Core/Portable/Wrapping/AbstractWrapper.cs
  src/Features/Core/Portable/Wrapping/AbstractWrappingCodeRefactoringProvider.cs
  src/Features/Core/Portable/Wrapping/ICodeActionComputer.cs
  src/Features/Core/Portable/Wrapping/SeparatedSyntaxList/SeparatedSyntaxListCodeActionComputer.cs
  src/Features/Core/Portable/Wrapping/WrapItemsAction.cs
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Features/VisualBasic/Portable/Wrapping/SeparatedSyntaxList/VisualBasicParameterWrapper.vb
  src/Features/VisualBasicTest/Wrapping/InitializerExpressionWrappingTests.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/IndentBlockFormattingRule.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/SuppressFormattingRule.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/CommonFormattingHelpers.cs
Labels: Area-IDE, untriaged

#70120 Allow only ordinary member method calls to be intercepted
  src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_FunctionPointerInvocation.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
  src/Features/CSharp/Portable/Diagnostics/LanguageServer/CSharpLspBuildOnlyDiagnostics.cs
Labels: Area-Compilers, untriaged

#70127 Set C# InteractiveWindow default to .NET Core
  src/EditorFeatures/Core.Wpf/EditorFeaturesWpfResources.resx
  src/EditorFeatures/Core.Wpf/Interactive/InteractiveEvaluator.cs
  src/EditorFeatures/Core.Wpf/Interactive/InteractiveWindowResetCommand.cs
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.cs.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.de.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.es.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.fr.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.it.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ja.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ko.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.pl.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.pt-BR.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ru.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.tr.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.zh-Hans.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.zh-Hant.xlf
  src/Interactive/Host/Interactive/Core/InteractiveHost.cs
  src/VisualStudio/Core/Def/Interactive/VsInteractiveWindowProvider.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpInteractiveDirectives.cs
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InteractiveWindow_InProc.cs
Labels: Area-IDE, untriaged

#70122 Do not restrict to type argument list context when a name could resolve to a generic and a non-generic symbol
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs
Labels: Area-IDE, untriaged

#70056 Add Primary Constructor tests for some scenarios from Test Plan
  src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs
Labels: Area-Compilers, Test, New Feature - Primary Constructors

#70154 Ensure GetRelatedDocumentIds() only returns IDs for source documents
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
Labels: Area-IDE

#70133 [17.8] Disallow `RequiresLocationAttribute` in more places in source
  src/Compilers/CSharp/Portable/Symbols/Source/FieldSymbolWithAttributesAndModifiers.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/RefReadonlyParameterTests.cs
Labels: Area-Compilers, untriaged, New Feature - Ref Readonly Parameters
