Repository dotnet/roslyn, pull requests merged in 2023-01, with the labels that each got.

#66010 Fixes and improvements for Run Code Analysis command
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.AnalysisData.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.Executor.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_IncrementalAnalyzer.cs
  src/VisualStudio/Core/Def/Diagnostics/VisualStudioDiagnosticAnalyzerService.cs
Labels: Area-Analyzers

#65777 Emit and report missing `Decimal-` and `DateTimeConstantAttribute`
  src/Compilers/CSharp/Portable/Binder/Binder.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversions.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberFieldSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
Labels: Area-Compilers

#65810 Stop referencing packages that became inbox on modern .NET.
  src/Compilers/Core/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.csproj
  src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/Features/Lsif/Generator/Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.csproj
Labels: Area-Infrastructure, Community

#66114 Qualify `Task.FromResult` when removing `async` modifier
  src/EditorFeatures/CSharpTest/Diagnostics/RemoveAsyncModifier/RemoveAsyncModifierTests.cs
  src/Features/CSharp/Portable/MakeMethodAsynchronous/CSharpMakeMethodAsynchronousCodeFixProvider.cs
  src/Features/CSharp/Portable/MakeMethodSynchronous/CSharpMakeMethodSynchronousCodeFixProvider.cs
  src/Features/Core/Portable/MakeMethodAsynchronous/AbstractMakeMethodAsynchronousCodeFixProvider.KnownTypes.cs
  src/Features/Core/Portable/MakeMethodAsynchronous/AbstractMakeMethodAsynchronousCodeFixProvider.cs
  src/Features/Core/Portable/RemoveAsyncModifier/AbstractRemoveAsyncModifierCodeFixProvider.cs
  src/Features/VisualBasic/Portable/MakeMethodAsynchronous/VisualBasicMakeMethodAsynchronousCodeFixProvider.vb
  src/Features/VisualBasic/Portable/MakeMethodSynchronous/VisualBasicMakeMethodSynchronousCodeFixProvider.vb
Labels: Area-IDE, Community

#66197 Fix crash in find-refs with method with multiple declarations in different files
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.LocalSymbols.vb
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractMemberScopedReferenceFinder.cs
Labels: Area-IDE

#66198 Fix Enums not appearing in AIOSP
  src/VisualStudio/Core/Def/NavigateTo/RoslynSearchItemsSource.cs
Labels: Area-IDE

#66169 Adding ability for DeclarationModifiers class to support readonly structs and methods
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
  src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs
Labels: Area-IDE, Community

#66201 Adding ability to filter async modifiers for methods without a body in SyntaxGenerator
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
Labels: Area-IDE, Community

#66163 Add tests for extract on keyword
  src/EditorFeatures/CSharpTest/ExtractClass/ExtractClassTests.cs
  src/EditorFeatures/CSharpTest/PullMemberUp/CSharpPullMemberUpTests.cs
Labels: Area-IDE

#66205 Prevent stackoverflow in Json parsing
  src/EditorFeatures/CSharpTest2/EmbeddedLanguages/Json/CSharpJsonParserTests.cs
  src/EditorFeatures/CSharpTest2/EmbeddedLanguages/Json/CSharpJsonParserTests_BasicTests.cs
  src/Features/Core/Portable/EmbeddedLanguages/Json/JsonParser.cs
Labels: Area-IDE

#66183 Allow missing document in method debug info
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/CompileExpressionsTests.cs
  src/ExpressionEvaluator/Core/Source/ExpressionCompiler/PDB/MethodDebugInfo.Native.cs
  src/ExpressionEvaluator/Core/Source/ExpressionCompiler/PDB/MethodDebugInfo.Portable.cs
Labels: Area-Interactive

#66159 Prefer default over starred item
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/ItemManager.CompletionListUpdater.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/ItemManager.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_DefaultsSource.vb
Labels: Area-IDE

#66180 Remove DeclarationScope in favor of ScopedKind
  src/Compilers/CSharp/Portable/Binder/Binder.QueryUnboundLambdaState.cs
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_AnonymousTypes.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Lambda.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Query.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/BoundTree/VariablePendingInference.cs
  src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs
  src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.PlaceholderLocal.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeField.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeManager.Templates.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/PublicSymbols/AnonymousType.DelegatePublicSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.DelegateTemplateSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/DeclarationScope.cs
  src/Compilers/CSharp/Portable/Symbols/FunctionPointers/FunctionPointerParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/LocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/ParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/LocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/ParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/SignatureOnlyParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LambdaParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ParameterHelpers.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceClonedParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceLocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceSimpleParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ThisParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordBaseEquals.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordDeconstruct.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityOperatorBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEquals.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordObjEquals.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPrintMembers.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedAccessorValueParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedDelegateSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedIntrinsicOperatorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedLocal.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/TypeSubstitutedLocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/UpdatedContainingSymbolLocal.cs
  src/Compilers/CSharp/Portable/Symbols/Wrapped/WrappedParameterSymbol.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_LifetimeAnnotation.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EELocalSymbolBase.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EEMethodSymbol.cs
Labels: Area-Compilers

#66203 If you see parentheses simplify them
  src/EditorFeatures/CSharpTest/CodeActions/ConvertLinq/ConvertForEachToLinqQueryTests.cs
  src/Features/CSharp/Portable/ConvertLinq/ConvertForEachToLinqQuery/AbstractToMethodConverter.cs
  src/Features/CSharp/Portable/ConvertLinq/ConvertForEachToLinqQuery/CSharpConvertForEachToLinqQueryProvider.cs
  src/Features/CSharp/Portable/ConvertLinq/ConvertForEachToLinqQuery/ToToListConverter.cs
  src/Features/Core/Portable/ConvertLinq/ConvertForEachToLinqQuery/AbstractConvertForEachToLinqQueryProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ICompilationExtensions.cs
Labels: Area-IDE, Community

#66217 Update config file
  eng/Versions.props
  eng/config/PublishData.json
Labels: Area-Infrastructure

#66209 Allow rename on items also defined in SG
  src/EditorFeatures/Test2/Rename/InlineRenameTests.vb
  src/Features/Core/Portable/Rename/SymbolicRenameInfo.cs
Labels: Area-IDE

#66222 Add tests that verify options with language specific storage location…
  src/Features/LanguageServer/ProtocolUnitTests/Microsoft.CodeAnalysis.LanguageServer.Protocol.UnitTests.csproj
  src/Features/LanguageServer/ProtocolUnitTests/Options/LspOptionsTests.cs
Labels: Area-IDE

#66087 Account for SpecificDiagnosticOptions in analyzer driver checks for enabling a disabled by default rule
  src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs
Labels: Area-Analyzers, Area-Compilers

#64083 Deprecate public constructors of various diagnostic analysis context types
  src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs
Labels: Area-Analyzers, Area-Compilers

#66230 Fix race condition in PerformanceQueue.AnalyzerNumberAssigner
  src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/PerformanceQueue.cs
Labels: Area-Analyzers, Needs Shiproom Approval

#63500 Incremental Generators docs update
  docs/features/incremental-generators.md
Labels: Area-Compilers, Documentation, Community

#66234 Ensure solution is fully loaded before gathering semantic errors
  src/EditorFeatures/Core/Diagnostics/AbstractPushOrPullDiagnosticsTaggerProvider.SingleDiagnosticKindPullTaggerProvider.cs
Labels: Area-IDE

#66182 Skip implicit build optimization for false value of `OptimizeImplicitlyTriggeredBuild`
  src/Compilers/Core/MSBuildTask/Microsoft.Managed.Core.targets
  src/Compilers/Core/MSBuildTaskTests/TargetTests.cs
Labels: Area-Compilers, Community

#66054 Implement new lookup rules for Primary Constructor parameters
  src/Compilers/CSharp/Portable/Binder/BinderFactory.BinderFactoryVisitor.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Crefs.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Initializers.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Lambda.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/InMethodBinder.cs
  src/Compilers/CSharp/Portable/Binder/LookupOptions.cs
  src/Compilers/CSharp/Portable/Binder/WithPrimaryConstructorParametersBinder.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs
  src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/FlowAnalysisPass.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs
  src/Compilers/CSharp/Portable/Symbols/ConstantValueUtils.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordConstructor.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxFacts.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/LookupPositionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs
  src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs
Labels: Area-Compilers, New Feature - Primary Constructors

#66211 Remove usage of Workspace.Options from AutomationObject
  src/VisualStudio/CSharp/Impl/CSharpPackage.cs
  src/VisualStudio/CSharp/Impl/Options/AutomationObject/AutomationObject.cs
  src/VisualStudio/Core/Impl/Options/AbstractAutomationObject.cs
  src/VisualStudio/VisualBasic/Impl/LanguageService/VisualBasicPackage.vb
  src/VisualStudio/VisualBasic/Impl/Options/AutomationObject/AutomationObject.vb
Labels: Area-IDE

#66247 workaround tabular data control focus issue
  src/VisualStudio/Core/Def/EditorConfigSettings/Common/SettingsViewModelBase.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/Common/TableControlFocusFixer.cs
  src/VisualStudio/Core/Def/UnusedReferences/Dialog/UnusedReferencesTableProvider.cs
Labels: Area-IDE

#66242 Mitigate crash in navigate-to.
  src/EditorFeatures/Core.Wpf/NavigateTo/NavigateToItemProvider.Callback.cs
Labels: Area-IDE

#66241 Fix a couple of cases where feature options were not being hooked up.
  src/EditorFeatures/Test/Options/GlobalOptionsTests.cs
  src/Features/LanguageServer/Protocol/Features/Options/WorkspaceConfigurationOptionsStorage.cs
Labels: Area-IDE

#66256 Merge release/dev17.5 to release/dev17.5-vs-deps
  src/VisualStudio/Core/Def/EditorConfigSettings/Common/SettingsViewModelBase.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/Common/TableControlFocusFixer.cs
  src/VisualStudio/Core/Def/UnusedReferences/Dialog/UnusedReferencesTableProvider.cs
Labels: Area-Infrastructure, auto-merge

#66245 Fix potential invalid TextSpan when reporting FAR results
  src/EditorFeatures/Test2/Classification/ClassificationTests.vb
  src/Features/Core/Portable/ClassifiedSpansAndHighlightSpanFactory.cs
Labels: Area-IDE

#66261 Disable testing SequencePointsMultipleDocuments with DebugInformationFormat.Pdb
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/CompileExpressionsTests.cs
Labels: Area-Interactive, Test

#66269 Port #66241 to Dev17.5
  src/EditorFeatures/Test/Options/GlobalOptionsTests.cs
  src/Features/LanguageServer/Protocol/Features/Options/WorkspaceConfigurationOptionsStorage.cs
Labels: Area-IDE

#66259 [LSP] Temporarily report NFWs in `RangeToTextSpan`
  src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
Labels: Area-IDE

#66024 Report error implementing interface with `[UnscopedRef]` member
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Symbols/MethodSymbolExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ThisParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers, New Language Feature - Ref Fields

#66281 Include LSP loghub logs when collecting watson dumps for NFW
  src/VisualStudio/Core/Def/Watson/FaultReporter.cs
Labels: Area-IDE, LSP

#66238 Apply XAML template on AbstractCheckBoxViewModel instead of one specific subclass
  src/VisualStudio/Core/Impl/Options/OptionPreviewControl.xaml
Labels: Area-IDE, UX Review Not Required

#66267 Remove workarounds for fixed issues
  eng/targets/Imports.targets
Labels: Area-Infrastructure, Community

#66239 Avoid contract failures in PreviewSolutionCrawlerRegistrationService …
  src/EditorFeatures/Core/Shared/Preview/PreviewSolutionCrawlerRegistrationService.cs
  src/Workspaces/Core/Portable/SolutionCrawler/ISolutionCrawlerRegistrationService.cs
Labels: Area-IDE

#66293 Fix priorities being incorrect in the task list.
  src/EditorFeatures/CSharpTest/TaskList/NoCompilationTaskListTests.cs
  src/VisualStudio/Core/Def/TableDataSource/TaskList/VisualStudioBaseTaskListTable.cs
  src/VisualStudio/Core/Test/TaskList/TaskListTableDataSourceTests.vb
  src/Workspaces/Core/Portable/TaskList/TaskListItem.cs
  src/Workspaces/Core/Portable/TaskList/TaskListItemDescriptor.cs
Labels: Area-IDE

#66301 Change Signature + Add Parameter Dialogue Fixes
  src/VisualStudio/Core/Def/ChangeSignature/AddParameterDialog.xaml
  src/VisualStudio/Core/Def/ChangeSignature/ChangeSignatureDialog.xaml
Labels: Area-IDE, UX Review Not Required

#66280 (17.5) Copy all diagnostic info from derived classes when changing severity of a diagnostic
  src/Compilers/CSharp/Portable/Errors/CSDiagnosticInfo.cs
  src/Compilers/CSharp/Portable/Errors/DiagnosticInfoWithSymbols.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/UninitializedNonNullableFieldTests.cs
  src/EditorFeatures/CSharpTest/CodeActions/EnableNullable/EnableNullableTests.cs
Labels: Area-Compilers

#66277 If we hit an exception while indexing, say which document it was with and try to recover
  src/Features/Lsif/Generator/Generator.cs
  src/Features/Lsif/Generator/Program.cs
  src/Features/Lsif/GeneratorTest/Utilities/TestLsifOutput.vb
Labels: Area-IDE

#66297 Update publishData.json
  eng/config/PublishData.json
Labels: Area-Infrastructure

#66302 Log source differences to files even when apply changes are blocked
  src/Features/Core/Portable/EditAndContinue/DebuggingSession.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSessionId.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/Core/Portable/EditAndContinue/TraceLog.cs
Labels: Area-Interactive

#66250 Ensure that side effects of conditional access on an instance of a nullable type are not preserved in generic code
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs
  src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs
  src/Compilers/CSharp/Portable/Compiler/AnonymousTypeMethodBodySynthesizer.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ConditionalAccess.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_FixedStatement.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_NullCoalescingOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StringConcat.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_UnaryOperator.cs
  src/Compilers/CSharp/Portable/Lowering/MethodToClassRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenConditionalOperatorTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenShortCircuitOperatorTests.cs
  src/Compilers/VisualBasic/Portable/CodeGen/EmitExpression.vb
  src/Compilers/VisualBasic/Portable/Symbols/ConstraintsHelper.vb
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTests.vb
  src/Compilers/VisualBasic/Test/Semantic/Semantics/ConditionalAccessTests.vb
Labels: Area-Compilers

#66306 Merge release/dev17.5-vs-deps to main
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversions.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeDescriptor.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeField.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeManager.Templates.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/PublicSymbols/AnonymousType.DelegatePublicSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.DelegateTemplateSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/MethodSymbolExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ThisParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedDelegateSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedIntrinsicOperatorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Infrastructure

#66076 Support netmodules in `MetadataReference` factory methods
  src/Compilers/CSharp/Test/Symbol/Compilation/CompilationAPITests.cs
  src/Compilers/Core/CodeAnalysisTest/MetadataReferences/MetadataReferenceTests.cs
  src/Compilers/Core/Portable/MetadataReference/MetadataReference.cs
Labels: Area-Compilers

#66296 Fix 'protected internal' accessibility modifier keyword order
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
Labels: Area-IDE, Community

#66254 Handle capturing of primary constructor parameters within queries and in type-or-value scenarios
  src/Compilers/CSharp/Portable/Binder/Binder.QueryTranslationState.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Lambda.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Query.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/Binder/InMethodBinder.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs
  src/Compilers/CSharp/Portable/Binder/WithPrimaryConstructorParametersBinder.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordConstructor.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/QueryTests.cs
Labels: Area-Compilers, New Feature - Primary Constructors

#66333 Remove incorrect guids
  Roslyn.sln
Labels: Area-Infrastructure

#66251 Emit stackalloc block initializer for byte-sized enums
  src/Compilers/CSharp/Portable/CodeGen/EmitStackAllocInitializer.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenStackAllocInitializerTests.cs
Labels: Area-Compilers, Community

#66335 Improve VS settings integration test, fix deserialization of enum options from registry
  src/Compilers/Test/Core/Assert/AssertEx.cs
  src/VisualStudio/Core/Def/Options/FeatureFlagPersister.cs
  src/VisualStudio/Core/Def/Options/LocalUserRegistryOptionPersister.cs
  src/VisualStudio/Core/Def/Options/VisualStudioOptionPersister.cs
  src/VisualStudio/Core/Def/Options/VisualStudioOptionPersisterProvider.cs
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
  src/VisualStudio/Core/Def/Options/VisualStudioSettingsOptionPersister.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/Options/GlobalOptionsTest.cs
  src/Workspaces/Core/Portable/Options/GlobalOptionService.cs
  src/Workspaces/CoreTestUtilities/Options/OptionsTestHelpers.cs
Labels: Area-IDE

#66318 Improve logging of rude edits and write analysis log to disk
  src/EditorFeatures/Test/EditAndContinue/TraceLogTests.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/DocumentAnalysisResults.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/TraceLog.cs
Labels: Area-Interactive

#66311 Do not copy nullable value type receiver of a constrained call.
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/CodeGen/CodeGenerator.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitAddress.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs
  src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.PlaceholderLocal.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs
  src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs
  src/Compilers/CSharp/Portable/Symbols/LocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceLocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedLocal.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/TypeSubstitutedLocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/UpdatedContainingSymbolLocal.cs
  src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenCallTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/GenericConstraintTests.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EELocalSymbolBase.cs
Labels: Area-Compilers

#66332 Refactor GetCapturedParameters method into reusable and parameter specific classes.
  src/Compilers/CSharp/Portable/Binder/Binder.CapturedParametersFinder.cs
  src/Compilers/CSharp/Portable/Binder/Binder.IdentifierUsedAsValueFinder.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordConstructor.cs
Labels: Area-Compilers, New Feature - Primary Constructors

#66344 Fix cancellation in test
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
Labels: Area-IDE

#66202 Adjust assert to account for error scenarios
  src/Compilers/CSharp/Portable/FlowAnalysis/FlowAnalysisPass.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/StructConstructorTests.cs
Labels: Area-Compilers

#66294 Support task list priorities in LSP
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/TaskListDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/PullDiagnosticConstants.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
Labels: Area-IDE

#66174 Don't rely on unset values from BitVector in nullable state
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs
Labels: Area-Compilers

#63055 Move couple of tests to new testing library
  src/Analyzers/CSharp/Tests/Iterator/AddYieldTests.cs
  src/Analyzers/VisualBasic/Tests/AddRequiredParentheses/AddRequiredParenthesesTests.vb
  src/Analyzers/VisualBasic/Tests/Iterator/IteratorTests.vb
Labels: Area-IDE, Community

#66317 Added table of content to source-generators.cookbook.md
  docs/features/source-generators.cookbook.md
Labels: Area-Compilers, Documentation, Community

#64034 [EnC] Follow up on deleting properties and events etc.
  src/Compilers/Core/Portable/Emit/EditAndContinue/DeltaMetadataWriter.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/SymbolChanges.cs
Labels: Area-Compilers

#66349 Add a InternalsVisibleTo for Workspaces.MSBuild
  src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj
Labels: Area-IDE

#66303 Simplify and fix handing of references not yet added
  src/VisualStudio/Core/Impl/SolutionExplorer/DiagnosticItem/CpsDiagnosticItemSource.cs
Labels: Area-IDE

#65831 Add `ExternalAccess.RazorCompiler` project with host outputs API
  .github/CODEOWNERS
  Compilers.sln
  Compilers.slnf
  Roslyn.sln
  src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorState.cs
  src/Compilers/Core/Portable/SourceGeneration/IncrementalContexts.cs
  src/Compilers/Core/Portable/SourceGeneration/RunResults.cs
  src/Tools/ExternalAccess/RazorCompiler/GeneratorExtensions.cs
  src/Tools/ExternalAccess/RazorCompiler/HostOutputNode.cs
  src/Tools/ExternalAccess/RazorCompiler/InternalAPI.Shipped.txt
  src/Tools/ExternalAccess/RazorCompiler/InternalAPI.Unshipped.txt
  src/Tools/ExternalAccess/RazorCompiler/Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.csproj
  src/Tools/ExternalAccess/RazorCompiler/PublicAPI.Shipped.txt
  src/Tools/ExternalAccess/RazorCompiler/PublicAPI.Unshipped.txt
Labels: Area-Compilers

#66350 Reduce When New Rename Is Dismissed
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml.cs
Labels: Area-IDE

#66354 Fix issue where Solution-Explorer symbol nodes collapse after an edit.
  src/VisualStudio/Core/Def/Progression/GraphBuilder.cs
  src/VisualStudio/Core/Def/Progression/GraphProvider.cs
  src/VisualStudio/Core/Def/Progression/GraphQueryManager.cs
Labels: Area-IDE

#66334 Report telemetry event with LSP server capabilities
  src/Features/LanguageServer/Protocol/Handler/ServerLifetime/InitializeHandler.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-IDE, LSP

#66285 Report error referencing method from module with unrecognized RefSafetyRulesAttribute version
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_WellKnownAttributes.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/Compilers/Core/Portable/MetadataReader/PEModule.cs
  src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.vb
  src/ExpressionEvaluator/VisualBasic/Source/ExpressionCompiler/EvaluationContext.vb
Labels: Area-Compilers

#66386 Fix `SyntaxGenerator` when generating delegate declaration from symbol
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
  src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs
  src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs
  src/Workspaces/VisualBasicTest/CodeGeneration/SyntaxGeneratorTests.vb
Labels: Area-IDE, Community

#65874 Enable switch dispatch for is-expressions
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IsPatternOperator.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests3.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests5.cs
Labels: Area-Compilers, Community

#66264 Disallow more locals of restricted type in async methods
  src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/Binder/UsingStatementBinder.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/BindingAsyncTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SpanStackSafetyTests.cs
Labels: Area-Compilers

#66340 Adjust closure initialization for primary constructor
  src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs
Labels: Area-Compilers, New Feature - Primary Constructors

#66395 Move VisualStudioOptionsProcessor down alongside ProjectSystemProject
  src/VisualStudio/CSharp/Impl/ProjectSystemShim/CSharpProjectShim.ICSCompilerConfig.cs
  src/VisualStudio/CSharp/Impl/ProjectSystemShim/CSharpProjectShim.ICSInputSet.cs
  src/VisualStudio/CSharp/Impl/ProjectSystemShim/CSharpProjectShim.OptionsProcessor.cs
  src/VisualStudio/CSharp/Impl/ProjectSystemShim/CSharpProjectShim.cs
  src/VisualStudio/CSharp/Test/ProjectSystemShim/LegacyProject/AnalyzersTests.cs
  src/VisualStudio/Core/Def/ProjectSystem/Legacy/AbstractLegacyProject.cs
  src/VisualStudio/Core/Def/ProjectSystem/Legacy/AbstractLegacyProject_IAnalyzerHost.cs
  src/VisualStudio/Core/Def/ProjectSystem/Legacy/AbstractLegacyProject_ICompilerOptionsHostObject.cs
  src/VisualStudio/Core/Def/ProjectSystem/RuleSets/VisualStudioRuleSetManager.RuleSetFile.cs
  src/VisualStudio/Core/Def/ProjectSystem/RuleSets/VisualStudioRuleSetManager.cs
  src/VisualStudio/Core/Def/ProjectSystem/RuleSets/VisualStudioRuleSetManagerFactory.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs
  src/VisualStudio/Core/Test/ProjectSystemShim/MockRuleSetFile.vb
  src/VisualStudio/VisualBasic/Impl/ProjectSystemShim/VisualBasicProject.OptionsProcessor.vb
  src/VisualStudio/VisualBasic/Impl/ProjectSystemShim/VisualBasicProject.vb
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/IRuleSetFile.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/IRuleSetManager.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectOptionsProcessor.cs
Labels: Area-IDE

#66400 17.5: Fix issue where Solution-Explorer symbol nodes collapse after a…
  src/VisualStudio/Core/Def/Progression/GraphBuilder.cs
  src/VisualStudio/Core/Def/Progression/GraphProvider.cs
  src/VisualStudio/Core/Def/Progression/GraphQueryManager.cs
Labels: Area-IDE, OnDeckForQB

#66355 Handle compiler diagnostics reported in .cshtml files during build
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs
  src/VisualStudio/Core/Def/TableDataSource/AbstractRoslynTableDataSource.cs
  src/VisualStudio/Core/Def/TaskList/ExternalErrorDiagnosticUpdateSource.cs
Labels: Area-IDE, Needs Shiproom Approval, area-web-frameworks

#66396 Fix reading VB editor options from ISettingsManager (17.5)
  src/EditorFeatures/Core/Options/NavigationBarViewOptionsStorage.cs
  src/EditorFeatures/Core/Options/SignatureHelpViewOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/CompletionOptionsStorage.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/FormattingOptions2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Options/ClientSettingsStorageLocation.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Options/LocalClientSettingsStorageLocation.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Options/RoamingProfileStorageLocation.cs
Labels: Area-IDE, OnDeckForQB, OnDeckForServicing

#66073 Block `delegate*<void>...enum` constants in attributes
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/MessageProvider.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs
  src/Compilers/Core/Portable/Diagnostic/CommonMessageProvider.cs
  src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs
  src/Compilers/Core/Portable/PEWriter/TypeNameSerializer.cs
  src/Compilers/Test/Core/Mocks/TestMessageProvider.cs
  src/Compilers/VisualBasic/Portable/Errors/MessageProvider.vb
Labels: Area-Compilers

#66097 Move constants to RefSafetyAnalysis visitor
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs
Labels: Area-Compilers

#66392 Report double storage warning for primary constructor parameters
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Generated/ErrorFacts.Generated.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
Labels: Area-Compilers, New Feature - Primary Constructors

#66407 Revert "Do not copy nullable value type receiver of a constrained call."
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/CodeGen/CodeGenerator.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitAddress.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs
  src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.PlaceholderLocal.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs
  src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs
  src/Compilers/CSharp/Portable/Symbols/LocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceLocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedLocal.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/TypeSubstitutedLocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/UpdatedContainingSymbolLocal.cs
  src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenCallTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/GenericConstraintTests.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EELocalSymbolBase.cs
Labels: Area-Compilers

#66393 Add entry for RazorCompiler
  eng/config/PublishData.json
Labels: Area-Infrastructure

#66415 Update Language Feature Status.md
  docs/Language Feature Status.md
Labels: Area-Compilers

#66356 Improve our testing of DefaultAnalyzerAssemblyLoader
  src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs
  src/Compilers/Test/Core/Platform/CoreClr/AssemblyLoadContextUtils.cs
Labels: Area-Compilers

#66189 Emit defensive copy for constrained call on `in` parameter
  src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenInParametersTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenReadonlyStructTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenStructsAndEnum.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenCallTests.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/MeMyBaseMyClassTests.vb
Labels: Area-Compilers

#65802 Delete Compilers.sln and keep only Compilers.slnf
  Compilers.sln
  Compilers.slnf
  docs/contributing/Building, Debugging, and Testing on Windows.md
  docs/infrastructure/cross-platform.md
  docs/wiki/FAQ.md
  eng/build.sh
  src/Tools/IdeCoreBenchmarks/FindReferencesBenchmarks.cs
  src/Tools/IdeCoreBenchmarks/IncrementalSourceGeneratorBenchmarks.cs
Labels: Area-Infrastructure, Community

#66359 Allow multiple documents in method debug info
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/CompileExpressionsTests.cs
  src/ExpressionEvaluator/Core/Source/ExpressionCompiler/PDB/MethodDebugInfo.Native.cs
  src/ExpressionEvaluator/Core/Source/ExpressionCompiler/PDB/MethodDebugInfo.Portable.cs
Labels: Area-Interactive, Pending director approval

#66363 Add test showing incorrect sequence point placement
  src/Compilers/CSharp/Test/Emit/PDB/PDBLambdaTests.cs
Labels: Area-Compilers, Test

#66316 Allow specifying expected IL verification baseline
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncLocalsTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenDynamicTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenExprLambdaTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenRefReturnTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/UnsafeTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/DynamicAnalysis/DynamicInstrumentationTests.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_WellKnownAttributes.cs
  src/Compilers/CSharp/Test/Emit2/Emit/NumericIntPtrTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/Compilers/Test/Core/Assert/ConditionalFactAttribute.cs
  src/Compilers/Test/Core/CommonTestBase.cs
  src/Compilers/Test/Core/CompilationVerifier.cs
  src/Compilers/Test/Core/Platform/Desktop/DesktopRuntimeEnvironment.cs
  src/Compilers/Test/Utilities/CSharp/BasicCompilationUtils.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
  src/Compilers/Test/Utilities/VisualBasic/BasicTestBase.vb
  src/Compilers/VisualBasic/Test/Emit/Emit/CompilationEmitTests.vb
  src/Compilers/VisualBasic/Test/Emit/ExpressionTrees/CodeGenExprLambda.vb
Labels: Area-Compilers

#66263 Apply diagnostic filter to generator failure warnings
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs
Labels: Area-Compilers

#66437 Replace placeholder XXX SDK version
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md
Labels: Area-Compilers, Community

#66420 Fix DateTime item's description in different culture
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_DateAndTime.vb
  src/Features/Core/Portable/EmbeddedLanguages/DateAndTime/EmbeddedCompletionContext.cs
Labels: Area-IDE

#66422 Catch exceptions when doing I/O to read the generator file version
  src/Workspaces/Core/Portable/SourceGeneratorTelemetry/SourceGeneratorTelemetryCollectorWorkspaceService.cs
  src/Workspaces/CoreTest/SolutionTests/SourceGeneratorTelemetryCollectorWorkspaceServiceTests.cs
Labels: Area-IDE

#66399 Fix reading VB editor options from ISettingsManager (main)
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
Labels: Area-IDE

#66412 Initial syntax types for collection literals
  src/Compilers/CSharp/Portable/Generated/CSharp.Generated.g4
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Internal.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Main.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Syntax.Generated.cs
  src/Compilers/CSharp/Portable/GlobalSuppressions.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
  src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs
  src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.AllInOne.cs
  src/Compilers/CSharp/Test/Syntax/Generated/Syntax.Test.xml.Generated.cs
  src/EditorFeatures/CSharpTest/Diagnostics/DiagnosticAnalyzerDriver/DiagnosticAnalyzerDriverTests.cs
Labels: Area-Compilers

#66444 Support generating conversion-operators from SyntaxGenerator
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
  src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs
  src/Workspaces/VisualBasicTest/CodeGeneration/SyntaxGeneratorTests.vb
Labels: Area-IDE

#66390 Fix `this` and `params` modifiers generation
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
  src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
  src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb
  src/Workspaces/VisualBasicTest/CodeGeneration/SyntaxGeneratorTests.vb
Labels: Area-IDE, Community

#66366 Temporarily stop merging in main-vs-deps
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#66156 Optimize StringBuilder calculations for netcoreapp3.1 and newer
  src/Compilers/Core/Portable/InternalUtilities/Hash.cs
  src/Compilers/Core/Portable/InternalUtilities/StringTable.cs
Labels: Area-Compilers

#66443 Enable EnC file logging during VS Feedback recording and collect the logs
  eng/Versions.props
  src/EditorFeatures/Core/EditAndContinue/EditAndContinueLanguageService.cs
  src/EditorFeatures/Test/EditAndContinue/TraceLogTests.cs
  src/EditorFeatures/TestUtilities/EditAndContinue/MockEditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/Core/Portable/EditAndContinue/IEditAndContinueWorkspaceService.cs
  src/Features/Core/Portable/EditAndContinue/Remote/IRemoteEditAndContinueService.cs
  src/Features/Core/Portable/EditAndContinue/Remote/RemoteEditAndContinueServiceProxy.cs
  src/Features/Core/Portable/EditAndContinue/TraceLog.cs
  src/VisualStudio/Core/Def/EditAndContinue/EditAndContinueFeedbackDiagnosticFileProvider.cs
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/Workspaces/Remote/ServiceHub/Services/EditAndContinue/RemoteEditAndContinueService.cs
Labels: Area-Interactive

#66026 Support Go To Definition in Object Browser for metadata references
  src/VisualStudio/Core/Def/Library/ObjectBrowser/Lists/SymbolListItem.cs
Labels: Area-IDE, Community

#65274 Move some severity configurations to globalconfig
  .editorconfig
  eng/config/globalconfigs/Common.globalconfig
Labels: Area-Infrastructure, Community

#66477 Revert "Localized file check-in by OneLocBuild Task: Build definition ID 327: Build ID 2088372"
  src/ExpressionEvaluator/Core/Source/ResultProvider/Portable/xlf/Resources.ja.xlf
Labels: Area-Infrastructure

#66459 Create closed Razor file integration test
  src/VisualStudio/IntegrationTest/New.IntegrationTests/AbstractEditorTest.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/AbstractWebApplicationTest.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpErrorListWeb.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerInProcess.cs
  src/VisualStudio/IntegrationTest/TestUtilities/WellKnownProjectTemplates.cs
Labels: Area-IDE

#66467 Reduce NamingStylePreferences allocations for Default and Empty
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/Serialization/NamingStylePreferences.cs
Labels: Area-IDE

#66466 Avoid capturing allocation in GetOrCreateDescriptor
  src/Compilers/Core/Portable/Diagnostic/DiagnosticInfo.cs
Labels: Area-Analyzers

#66452 Fix doc comment on ForAttributeWithMetadataName
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs
Labels: Area-Compilers

#66367 Allow missing CommandLineArgsForDesignTimeEvaluation msbuild property
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProjectFactory.cs
Labels: Area-IDE

#66328 Treat `TypedReference` as managed
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md
  src/Compilers/CSharp/Portable/Symbols/BaseTypeAnalysis.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenMscorlib.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/StackAllocInitializerTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/UnsafeTests.cs
  src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs
Labels: Area-Compilers

#66357 Adding keyword recommendations after FileKeyword
  src/EditorFeatures/CSharpTest2/Recommendations/AbstractKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ClassKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ReadOnlyKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/RecordKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/RefKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/SealedKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/StaticKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/StructKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/UnsafeKeywordRecommenderTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/AbstractKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/ClassKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/InternalKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/PrivateKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/ProtectedKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/PublicKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/RecordKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/SealedKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/StaticKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/StructKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/UnsafeKeywordRecommender.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTreeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs
Labels: Area-IDE, Community

#66394 Ensure event handler generation and navigation in webforms works properly
  src/VisualStudio/Core/Def/Venus/ContainedDocument.cs
  src/VisualStudio/Core/Def/Venus/ContainedLanguage.IVsContainedLanguageCodeSupport.cs
Labels: Area-IDE

#66450 Fix stepping UI delays
  src/EditorFeatures/CSharpTest/EditAndContinue/ActiveStatementTrackingServiceTests.cs
  src/EditorFeatures/Core/EditAndContinue/ActiveStatementTrackingService.cs
  src/EditorFeatures/Core/EditAndContinue/EditAndContinueLanguageService.cs
  src/EditorFeatures/Core/EditAndContinue/IActiveStatementTrackingService.cs
  src/Workspaces/Core/Portable/Shared/TestHooks/FeatureAttribute.cs
Labels: Area-Interactive

#66458 Gracefully handle negative endLine and endColumn values for build errors
  src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicErrorListCommon.cs
Labels: Area-IDE, Needs Shiproom Approval

#66453 Add workaround for web-tools added design time documents
  src/Features/Core/Portable/EditAndContinue/Extensions.cs
Labels: Area-IDE

#66416 Ensure no extension method applies to System.Void
  src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/ExtensionMethodTests.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/ExtensionMethods/ExtensionMethodTests.vb
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs
  src/Workspaces/VisualBasic/Portable/Recommendations/VisualBasicRecommendationServiceRunner.vb
Labels: Area-Compilers

#66430 Use dictionary lookup while resolving assembly references
  src/Compilers/CSharp/Portable/Symbols/ReferenceManager.cs
  src/Compilers/Core/Portable/MetadataReference/AssemblyIdentityExtensions.cs
  src/Compilers/Core/Portable/ReferenceManager/AssemblyData.cs
  src/Compilers/Core/Portable/ReferenceManager/AssemblyDataForAssemblyBeingBuilt.cs
  src/Compilers/Core/Portable/ReferenceManager/CommonReferenceManager.Binding.cs
  src/Compilers/Core/Portable/ReferenceManager/CommonReferenceManager.Resolution.cs
  src/Compilers/VisualBasic/Portable/Symbols/ReferenceManager.vb
Labels: Area-Compilers

#66440 Preserve changes that are still relevant after revert of #66311
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/CodeGen/CodeGenerator.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs
  src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.PlaceholderLocal.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs
  src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs
  src/Compilers/CSharp/Portable/Symbols/LocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceLocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedLocal.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/TypeSubstitutedLocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/UpdatedContainingSymbolLocal.cs
  src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenCallTests.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EELocalSymbolBase.cs
Labels: Area-Compilers

#66488 Clean up some checks in FileChangeWatcher.Context.EnqueueWatchingFile
  src/VisualStudio/Core/Def/ProjectSystem/FileChangeWatcher.cs
Labels: Area-IDE

#66521 Update Collection Literal Team
  docs/Language Feature Status.md
Labels: Area-Compilers

#66508 Fix handling of Regex classification when splitting to multiple lines
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHelpers.cs
  src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/AbstractSemanticTokensTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/SemanticTokensRangeTests.cs
Labels: Area-IDE

#66421 Fix mismatched per-language option storages
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
  src/VisualStudio/Core/Test.Next/Options/VisualStudioOptionStorageTests.cs
Labels: Area-IDE

#64160 Solution services cleanup
  src/Features/Core/Portable/MetadataAsSource/DecompilationMetadataAsSourceFileProvider.cs
  src/Features/Core/Portable/MetadataAsSource/MetadataAsSourceGeneratedFileInfo.cs
  src/Features/LanguageServer/Protocol/Features/Options/WorkspaceConfigurationOptionsStorage.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Source.cs
  src/Workspaces/Core/Portable/Workspace/CommandLineProject.cs
  src/Workspaces/Core/Portable/Workspace/Host/LanguageServices.cs
  src/Workspaces/Core/Portable/Workspace/Host/SolutionServices.cs
  src/Workspaces/Core/Portable/Workspace/Solution/AdditionalDocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/AnalyzerConfigDocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/DocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/DocumentState_LinkedFileReuse.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Project.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState_Checksum.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.SkeletonReferenceCache.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratedDocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
Labels: Area-IDE

#66468 Inline diagnostics - fix multiple blank lines bug
  src/EditorFeatures/Core.Wpf/InlineDiagnostics/InlineDiagnosticsAdornmentManager.cs
Labels: Area-IDE

#66456 Update Microsoft.CodeAnalysis.Analyzers to 3.3.4
  eng/Versions.props
  eng/config/globalconfigs/Common.globalconfig
  eng/config/globalconfigs/NonShipping.globalconfig
  eng/targets/Settings.props
Labels: Area-Infrastructure, Community

#66535 Unused parameter analyzer shouldn't warn for methods that only throw
  src/Analyzers/CSharp/Analyzers/RemoveUnusedParametersAndValues/CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/RemoveUnusedParametersAndValues/RemoveUnusedParametersTests.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs
  src/Analyzers/VisualBasic/Analyzers/RemoveUnusedParametersAndValues/VisualBasicRemoveUnusedParametersAndValuesDiagnosticAnalyzer.vb
  src/Analyzers/VisualBasic/Tests/RemoveUnusedParametersAndValues/RemoveUnusedParametersTests.vb
Labels: Area-IDE

#66541 Prefer list-pattern for length-only counterexamples
  src/Compilers/CSharp/Portable/Binder/PatternExplainer.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests3.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests_ListPatterns.cs
Labels: Area-Compilers, Community

#66540 Optimizer.StackOptimizerPass1 - Remove redundant field initializer
  src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs
Labels: Area-Compilers, Community

#66329 Let LSP client know which diagnostics are build-only.
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/VisualBasic/Portable/Errors/ErrorFacts.vb
  src/EditorFeatures/CSharp/LanguageServer/CSharpLspBuildOnlyDiagnostics.cs
  src/EditorFeatures/CSharpTest/LanguageServer/CSharpLspBuildOnlyDiagnosticsTests.cs
  src/EditorFeatures/Core/LanguageServer/AlwaysActivateInProcLanguageClient.cs
  src/EditorFeatures/Core/LanguageServer/Diagnostics/ILspBuildOnlyDiagnostics.cs
  src/EditorFeatures/Core/LanguageServer/Diagnostics/ILspBuildOnlyDiagnosticsMetadata.cs
  src/EditorFeatures/Core/LanguageServer/Diagnostics/LspBuildOnlyDiagnosticsAttribute.cs
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLspBuildOnlyDiagnosticsTests.cs
  src/EditorFeatures/VisualBasic/LanguageServer/VisualBasicLspBuildOnlyDiagnostics.vb
  src/EditorFeatures/VisualBasicTest/LanguageServer/VisualBasicLspBuildOnlyDiagnosticsTests.vb
Labels: Area-IDE

#66543 Correctly emit accessibility when generating properties via `SyntaxGenerator`
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
  src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs
  src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb
  src/Workspaces/VisualBasicTest/CodeGeneration/SyntaxGeneratorTests.vb
Labels: Area-IDE, Community

#66136 Fix state for pattern declarations on subsequent iterations
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesVsPatterns.cs
Labels: Area-Compilers, New Language Feature - Pattern Matching, New Language Feature - Nullable Reference Types, New Feature - List Patterns

#66559 Don't overwrite binary logs
  azure-pipelines.yml
  eng/build.ps1
Labels: Area-Infrastructure

#66539 LocalRewriter.DecisionDagRewriter - Remove redundant field
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.DecisionDagRewriter.cs
Labels: Area-Compilers, Community

#66528 Make SymbolDisplay show nullable enum values as enums
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IArgument.cs
  src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs
  src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolDisplay/SymbolDisplayTests.vb
Labels: Area-Compilers

#66385 Report example of unanalyzed node in `NullableWalker`
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.DebugVerifier.cs
Labels: Area-Compilers

#66348 Add support for brace pair highlighting for C# and VB (F#/TS can add support as well if desired).
  eng/Versions.props
  src/EditorFeatures/CSharpTest/BracePairs/CSharpBracePairsTests.cs
  src/EditorFeatures/Core/BracePairs/BracePairsTaggerProvider.cs
  src/EditorFeatures/TestUtilities/BracePairs/AbstractBracePairsTests.cs
  src/EditorFeatures/VisualBasicTest/BracePairs/VisualBasicBracePairsTests.vb
  src/Features/CSharp/Portable/BracePairs/CSharpBracePairsService.cs
  src/Features/Core/Portable/BracePairs/IBracePairsService.cs
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/Features/VisualBasic/Portable/BracePairs/VisualBasicBracePairsService.vb
  src/Workspaces/Core/Portable/Shared/TestHooks/FeatureAttribute.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxKinds.vb
Labels: Area-IDE

#66562 Update capabilities for streaming references
  src/Features/LanguageServer/Protocol/DefaultCapabilitiesProvider.cs
Labels: Area-IDE

#66446 Support emitting type-parameter variance in syntax generator
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
  src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
  src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb
  src/Workspaces/VisualBasicTest/CodeGeneration/SyntaxGeneratorTests.vb
Labels: Area-IDE

#66546 Add an API for the parsed command line back from an OptionsProcessor
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectOptionsProcessor.cs
Labels: Area-IDE

#66445 Add support for generating ref-members in SyntaxGenerator
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
  src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
  src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb
Labels: Area-IDE

#66554 Complete interpolated raw string when more than one dollar sign
  src/EditorFeatures/CSharp/RawStringLiteral/RawStringLiteralCommandHandler_TypeChar.cs
  src/EditorFeatures/CSharpTest/RawStringLiteral/RawStringLiteralCommandHandlerTests.cs
Labels: Area-IDE

#66525 Disregard static abstract methods as entrypoint candidates
  src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
Labels: Area-Compilers, Community

#66551 Reduce delegate allocations in LanguageParser
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
Labels: Area-Compilers

#65924 Fix line breaks between members when a property has an initializer
  src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs
  src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs
Labels: Area-Compilers, Community

#66575 Avoid unnecessary parsing in brace-completion
  src/Features/CSharp/Portable/BraceCompletion/AbstractCurlyBraceOrBracketCompletionService.cs
Labels: Area-IDE

#66499 Test/implement some aspects of primary constructor parameter capturing.
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs
  src/Compilers/CSharp/Test/Emit2/FlowAnalysis/RegionAnalysisTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs
Labels: Area-Compilers, New Feature - Primary Constructors

#66351 Emit copy when calling non-readonly method with ref readonly field receiver
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers

#66576 Revert "Prefer list-pattern for length-only counterexamples (#66541)"
  src/Compilers/CSharp/Portable/Binder/PatternExplainer.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests3.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests_ListPatterns.cs
Labels: Area-Compilers

#66081 Length-based switch dispatch
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/BoundTree/LengthBasedStringSwitchData.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs
  src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.DecisionDagRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenLengthBasedSwitchTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests5.cs
  src/Compilers/Core/Portable/CodeGen/ILBuilderEmit.cs
  src/Compilers/Core/Portable/CodeGen/ITokenDeferral.cs
  src/Compilers/Core/Portable/CodeGen/SwitchStringJumpTableEmitter.cs
  src/Compilers/Test/Utilities/CSharp/TestOptions.cs
Labels: Area-Compilers

#66552 Introduce parser helper for parsing separated syntax lists.
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/AnonymousFunctionParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ExpressionParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/LambdaParameterParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ParserErrorMessageTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ParsingErrorRecoveryTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/RecordParsing.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs
Labels: Area-Compilers

#66580 Change the version number to preview 6
  eng/Versions.props
Labels: Area-Infrastructure
