Repository dotnet/roslyn, pull requests merged in 2023-12, with the labels that each got.

#70821 Switch IDE0005 from WarningLevel to AnalysisLevel
  src/Analyzers/Core/Analyzers/RemoveUnnecessaryImports/AbstractRemoveUnnecessaryImportsDiagnosticAnalyzer.cs
Labels: Area-Analyzers, untriaged

#71038 Properly escape ref path names that contain equals
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/Core/MSBuildTask/CommandLineBuilderExtension.cs
  src/Compilers/Core/MSBuildTask/Csc.cs
  src/Compilers/Core/MSBuildTaskTests/CscTests.cs
  src/Compilers/Core/MSBuildTaskTests/TestUtilities/SimpleTaskItem.cs
Labels: Area-Compilers, untriaged

#71051 Ensure we publish symbols for the BuildHost
  src/Workspaces/Core/MSBuild.BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj
Labels: Area-IDE, untriaged

#71026 Do not offer 'use collection expression' inside expression trees.
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/AbstractCSharpUseCollectionExpressionDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForArrayDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForBuilderDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForCreateDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForEmptyDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForFluentDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForStackAllocDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/UseCollectionExpressionHelpers.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionInitializer/CSharpUseCollectionInitializerDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseNullPropagation/CSharpUseNullPropagationDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseThrowExpression/CSharpUseThrowExpressionDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpUseCollectionExpressionForArrayCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpUseCollectionExpressionForBuilderCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpUseCollectionExpressionForFluentCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpUseCollectionExpressionForStackAllocCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForCreateTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForEmptyTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForFluentTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests_CollectionExpression.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/AbstractUseCollectionInitializerDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer_IfStatement.cs
  src/Analyzers/Core/Analyzers/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs
  src/Analyzers/VisualBasic/Analyzers/UseCollectionInitializer/VisualBasicUseCollectionInitializerDiagnosticAnalyzer.vb
  src/Analyzers/VisualBasic/Analyzers/UseNullPropagation/VisualBasicUseNullPropagationDiagnosticAnalyzer.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxNodeExtensions.cs
Labels: Area-IDE, untriaged

#71053 Offer use-primary-constructor on abtract types with protected constructors
  src/Analyzers/CSharp/Analyzers/UsePrimaryConstructor/CSharpUsePrimaryConstructorDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/UsePrimaryConstructor/UsePrimaryConstructorTests.cs
Labels: Area-IDE, untriaged

#71060 Allow ms time sums to be long instead of just int.
  src/VisualStudio/Core/Def/Telemetry/AggregatingTelemetryLog.cs
Labels: Area-IDE, untriaged

#71070 Give our analyzer loaders independent directories across hosts
  src/Workspaces/Core/Portable/Diagnostics/DefaultAnalyzerAssemblyLoaderService.cs
Labels: Area-Analyzers, untriaged

#71078 Add comments to the nuget search update system.
  src/Features/Core/Portable/SymbolSearch/Windows/SymbolSearchUpdateEngine.Update.cs
Labels: Area-IDE, untriaged

#71082 Revert "Ensure we publish symbols for the BuildHost"
  src/Workspaces/Core/MSBuild.BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj
Labels: Area-IDE, untriaged

#70851 Automatically detect missing NuGet packages and restore
  eng/Versions.props
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/ProjectDependencyHelper.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/ProjectTelemetry/ProjectLoadTelemetryReporter.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/LanguageServer/Handler/Restore/RestoreHandler.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/LanguageServer/Handler/Restore/RestoreParams.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/LanguageServerResources.resx
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Microsoft.CodeAnalysis.LanguageServer.csproj
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.cs.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.de.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.es.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.fr.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.it.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.ja.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.ko.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.pl.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.pt-BR.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.ru.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.tr.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.zh-Hans.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.zh-Hant.xlf
  src/Features/LanguageServer/Protocol/Features/Options/LanguageServerProjectSystemOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Handler/Configuration/DidChangeConfigurationNotificationHandler_OptionList.cs
  src/Features/LanguageServer/ProtocolUnitTests/Configuration/DidChangeConfigurationNotificationHandlerTest.cs
  src/VisualStudio/Core/Test.Next/Options/VisualStudioOptionStorageTests.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/Constants/ItemNames.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/Constants/MetadataNames.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/Extensions.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/PackageReference.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFileInfo.cs
Labels: Area-IDE, untriaged

#70934 Avoid redundant `HasValue` call in lifted custom binary operator
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperator.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOptimizedNullableOperators.cs
Labels: Area-Compilers, Code Gen Quality, untriaged

#71081 Avoid leaking text views on cancellation
  src/EditorFeatures/Core.Wpf/Preview/PreviewFactoryService.cs
  src/EditorFeatures/Core/Preview/AbstractPreviewFactoryService.cs
Labels: Area-IDE, untriaged

#71089 Disable ExtractMethod and VerifyTextSync after 17.9P1 failures
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpExtractMethod.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpRename.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicExtractMethod.cs
Labels: Area-Infrastructure

#70936 Utilize IVsAsyncFileChangeEx2
  src/VisualStudio/Core/Def/ProjectSystem/FileChangeTracker.cs
  src/VisualStudio/Core/Def/ProjectSystem/FileChangeWatcher.cs
  src/VisualStudio/Core/Def/ProjectSystem/FileChangeWatcherProvider.cs
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioRuleSetTests.vb
  src/VisualStudio/TestUtilities2/MockVsFileChangeEx.vb
Labels: Area-IDE, untriaged

#71098 Remove dead goto-def/peek/ctrl-click EA impls for TS. TS is now entirely on LSP for these experiences.
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/IVSTypeScriptGoToDefinitionService.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/IVSTypeScriptGoToDefinitionServiceFactoryImplementation.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptDefinitionLocationServiceFactory.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptNavigableItemsServiceFactory.cs
  src/Features/LanguageServer/Protocol/Handler/Definitions/AbstractGoToDefinitionHandler.cs
  src/Tools/ExternalAccess/OmniSharp/GoToDefinition/OmniSharpFindDefinitionService.cs
Labels: Area-IDE, untriaged

#71105 Fix use-collection-expr when it breaks type inference with arrays
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForArrayDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/UseCollectionExpressionHelpers.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs
Labels: Area-IDE, untriaged

#71127 Fix DevContainer File
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: Area-Infrastructure, untriaged

#71086 Add IVT from EA.Razor to MS.ANC.Razor.Test.Common.Tooling
  src/Tools/ExternalAccess/Razor/Microsoft.CodeAnalysis.ExternalAccess.Razor.csproj
Labels: Area-IDE, untriaged

#71130 Fix 'use pattern matching' with nullable types
  src/Analyzers/CSharp/Analyzers/UsePatternMatching/CSharpUseNotPatternDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/UsePatternMatching/CSharpUseNotPatternTests.cs
Labels: Area-IDE, untriaged

#70649 Support implicit indexer access in object initializers
  docs/Language Feature Status.md
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/CodeGen/ObjectAndCollectionInitializerTests.cs
  src/Compilers/CSharp/Test/Emit2/CodeGen/IndexAndRangeTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/InlineArrayTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IObjectCreationExpression.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
  src/Compilers/Test/Core/Compilation/ControlFlowGraphVerifier.cs
Labels: Area-Compilers, New Language Feature - Range, untriaged

#71151 Skip the signing step in integration tests
  eng/pipelines/test-integration-job.yml
Labels: Area-Infrastructure, untriaged

#71131 Use primary constructor pragmas
  src/Analyzers/CSharp/Analyzers/UsePrimaryConstructor/CSharpUsePrimaryConstructorDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/UsePrimaryConstructor/CSharpUsePrimaryConstructorCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UsePrimaryConstructor/CSharpUsePrimaryConstructorCodeFixProvider_DocComments.cs
  src/Analyzers/CSharp/Tests/UsePrimaryConstructor/UsePrimaryConstructorTests.cs
Labels: Area-IDE, untriaged

#71154 Block 'use collection expression' on certain types
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForFluentDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForFluentTests.cs
Labels: Area-IDE, untriaged

#71043 Set order of precedence for obsoletion attribute family
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_Experimental.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_WellKnownAttributes.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/ExperimentalAttributeTests.cs
  src/Compilers/Core/Portable/MetadataReader/PEModule.cs
  src/Compilers/Core/Portable/Symbols/Attributes/CommonEventEarlyWellKnownAttributeData.cs
  src/Compilers/Core/Portable/Symbols/Attributes/CommonFieldEarlyWellKnownAttributeData.cs
  src/Compilers/Core/Portable/Symbols/Attributes/CommonMethodEarlyWellKnownAttributeData.cs
  src/Compilers/Core/Portable/Symbols/Attributes/CommonPropertyEarlyWellKnownAttributeData.cs
  src/Compilers/Core/Portable/Symbols/Attributes/CommonTypeEarlyWellKnownAttributeData.cs
  src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests.vb
Labels: Area-Compilers, untriaged

#71161 Add QuickInfo for collection expression brackets
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
  src/Features/VisualBasic/Portable/QuickInfo/VisualBasicSemanticQuickInfoProvider.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
Labels: Area-IDE, untriaged, New Feature - Collection Expressions

#71168 Fix 'use primary constructor' when moving attribute with reference to member in that type.
  src/Analyzers/CSharp/CodeFixes/UsePrimaryConstructor/CSharpUsePrimaryConstructorCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UsePrimaryConstructor/UsePrimaryConstructorTests.cs
Labels: Area-IDE, untriaged

#71165 Ensure we publish symbols for the BuildHost
  src/Workspaces/Core/MSBuild.BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj
Labels: Area-IDE, untriaged

#71174 Add test for Use Collection Expression
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs
Labels: Area-IDE, untriaged

#71190 Remove dead code from unit testing codepaths
  src/Features/Core/Portable/ExternalAccess/UnitTesting/API/INewUnitTestingIncrementalAnalyzerImplementation.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/API/NewUnitTestingIncrementalAnalyzer.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/API/NewUnitTestingIncrementalAnalyzerProvider.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/API/UnitTestingInvocationReasons_Constants.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/API/UnitTestingPredefinedInvocationReasons.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/LegacySolutionEvents/UnitTestingLegacySolutionEventsListener.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/AbstractUnitTestingDocumentDifferenceService.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/DefaultUnitTestingDocumentTrackingService.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/ExportUnitTestingIncrementalAnalyzerProviderAttribute.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/IUnitTestingDocumentTrackingService.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/IUnitTestingIncrementalAnalyzer.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/IUnitTestingIncrementalAnalyzerProvider.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/IUnitTestingSolutionCrawlerRegistrationService.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/IUnitTestingSolutionCrawlerService.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/IUnitTestingWorkCoordinator.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingIncrementalAnalyzerProviderMetadata.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingSolutionCrawlerLogger.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingSolutionCrawlerRegistrationService.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingSolutionCrawlerService.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingSolutionCrawlerTimeSpan.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingWorkCoordinator.AbstractUnitTestingPriorityProcessor.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingWorkCoordinator.UnitTestingAsyncDocumentWorkItemQueue.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingWorkCoordinator.UnitTestingAsyncProjectWorkItemQueue.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingWorkCoordinator.UnitTestingAsyncWorkItemQueue.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingWorkCoordinator.UnitTestingHighPriorityProcessor.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingWorkCoordinator.UnitTestingIncrementalAnalyzerProcessor.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingWorkCoordinator.UnitTestingLowPriorityProcessor.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingWorkCoordinator.UnitTestingNormalPriorityProcessor.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingWorkCoordinator.UnitTestingWorkItem.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingWorkCoordinator.cs
  src/Features/Core/Portable/LegacySolutionEvents/ILegacySolutionEventsAggregationService.cs
  src/Features/Core/Portable/LegacySolutionEvents/ILegacySolutionEventsListener.cs
Labels: Area-IDE, untriaged

#71181 Convert type into a struct.
  src/Features/CSharp/Portable/BraceCompletion/CurlyBraceCompletionService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ListExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Context/FormattingContext.InitialContextFinder.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Context/FormattingContext.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Rules/Operations/SuppressOperation.cs
Labels: Area-IDE, untriaged

#69703 Update the C# syntax generator to use aliases to lower the amount of large qualified namespaces emitted to distinguish internal and public types.
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Internal.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Main.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Syntax.Generated.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/SourceWriter.cs
Labels: Area-Compilers, untriaged

#71173 Ensure the editorconfig for code-style analysis ("IDExxxx") rules is included
  src/CodeStyle/Tools/Program.cs
Labels: Area-Infrastructure, Community, untriaged

#71205 Generate protected constructors in abstract types
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpConstructorSnippetCompletionProviderTests.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractConstructorSnippetProvider.cs
Labels: Area-IDE, Community, untriaged

#71175 Remove Microsoft.SourceBuild.Intermediate from prebuilt baseline
  eng/SourceBuildPrebuiltBaseline.xml
Labels: Area-Infrastructure, untriaged

#71185 Remove unnecessary check of trailing trivia for directives.
  src/Compilers/Core/Portable/Syntax/SyntaxNodeOrToken.cs
Labels: Area-Compilers, untriaged

#71201 Ensure both parts of partial methods are analyzed when requesting analyzer diagnostics for a single file
  src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs
Labels: Area-Analyzers, Area-Compilers, untriaged

#71123 Remove TS impl of goto-def. The are entirely on LSP now
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/IVSTypeScriptGoToDefinitionService.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/IVSTypeScriptGoToDefinitionServiceFactoryImplementation.cs
Labels: Area-IDE, untriaged

#71178 Reduce size of source constructor symbol
  src/Compilers/CSharp/Portable/Lowering/SynthesizedMethodBaseSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceConstructorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceDelegateMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceDestructorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceEventAccessorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertyAccessorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedPrimaryConstructor.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordOrdinaryMethod.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedSimpleProgramEntryPointSymbol.cs
Labels: Area-Compilers, untriaged

#71213 Enable skipped tests (rename and extract methods)
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpExtractMethod.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpRename.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicExtractMethod.cs
Labels: Area-IDE, untriaged

#71222 Fix option code
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/IdeCodeStyleOptions.cs
Labels: Area-IDE, untriaged

#70975 Collection expressions: align ConversionsBase.GetCollectionExpressionTypeKind() with spec
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/CollectionExpressionTypeKind.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged

#71184 Remove navigation helpers based on line+offset
  src/EditorFeatures/Core.Wpf/Interactive/InteractiveDocumentNavigationService.cs
  src/EditorFeatures/Core/Navigation/IDocumentNavigationServiceExtensions.cs
  src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionTestsBase.vb
  src/EditorFeatures/Test2/NavigableSymbols/NavigableSymbolsTest.vb
  src/EditorFeatures/TestUtilities2/Utilities/GoToHelpers/MockDocumentNavigationService.vb
  src/EditorFeatures/TestUtilities2/Utilities/MockDocumentNavigationServiceProvider.vb
  src/Features/Core/Portable/Navigation/DefaultDocumentNavigationService.cs
  src/Features/Core/Portable/Navigation/IDocumentNavigationService.cs
  src/Tools/ExternalAccess/FSharp/Navigation/FSharpDocumentNavigationService.cs
  src/Tools/ExternalAccess/FSharp/Navigation/IFSharpDocumentNavigationService.cs
  src/VisualStudio/Core/Def/Workspace/VisualStudioDocumentNavigationService.cs
  src/VisualStudio/LiveShare/Test/AbstractLiveShareRequestHandlerTests.cs
  src/VisualStudio/LiveShare/Test/MockDocumentNavigationServiceFactory.cs
Labels: Area-IDE, untriaged

#71224 Fix infinite loop in tagging
  src/EditorFeatures/Core/Shared/Tagging/Utilities/TagSpanIntervalTree.cs
  src/EditorFeatures/Test/Tagging/AsynchronousTaggerTests.cs
Labels: Area-IDE, untriaged

#71212 Don't copy test results to helix upload root.
  src/Tools/Source/RunTests/TestRunner.cs
Labels: Area-Infrastructure, untriaged

#71232 Remove methods not used by F#
  src/Tools/ExternalAccess/FSharp/Navigation/FSharpDocumentNavigationService.cs
  src/Tools/ExternalAccess/FSharp/Navigation/IFSharpDocumentNavigationService.cs
Labels: Area-IDE, untriaged

#71193 Use file scoped namespaces
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Internal.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Main.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Syntax.Generated.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/SourceWriter.cs
Labels: Area-Compilers, untriaged

#71237 Restore using dotnet CLI to ensure NuGet environment variables are used
  azure-pipelines-pr-validation.yml
Labels: Area-Infrastructure, untriaged

#70819 Create a Razor language server cohosted in Roslyn
  src/EditorFeatures/Core/LanguageServer/AbstractInProcLanguageClient.cs
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/EditorFeatures/TestUtilities/Microsoft.CodeAnalysis.EditorFeatures.Test.Utilities.csproj
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/AbstractLanguageServer.cs
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/Microsoft.CommonLanguageServerProtocol.Framework.csproj
  src/Features/LanguageServer/Protocol/Extensions/Extensions.cs
  src/Features/LanguageServer/Protocol/Handler/ProjectContext/GetTextDocumentWithContextHandler.cs
  src/Features/LanguageServer/Protocol/Handler/RequestContext.cs
  src/Features/LanguageServer/Protocol/Microsoft.CodeAnalysis.LanguageServer.Protocol.csproj
  src/Features/LanguageServer/Protocol/ProtocolConstants.cs
  src/Features/LanguageServer/Protocol/WellKnownLspServerKinds.cs
  src/Features/LanguageServer/Protocol/Workspaces/LspWorkspaceManager.cs
  src/Features/LanguageServer/ProtocolUnitTests/Workspaces/LspWorkspaceManagerTests.cs
  src/Tools/ExternalAccess/Razor/Cohost/AbstractRazorCohostDocumentRequestHandler.cs
  src/Tools/ExternalAccess/Razor/Cohost/AbstractRazorLspService.cs
  src/Tools/ExternalAccess/Razor/Cohost/AbstractRazorRequestHandler.cs
  src/Tools/ExternalAccess/Razor/Cohost/Constants.cs
  src/Tools/ExternalAccess/Razor/Cohost/ExportRazorLspServiceFactoryAttribute.cs
  src/Tools/ExternalAccess/Razor/Cohost/ExportRazorStatelessLspServiceAttribute.cs
  src/Tools/ExternalAccess/Razor/Cohost/IRazorCohostCapabilitiesProvider.cs
  src/Tools/ExternalAccess/Razor/Cohost/IRazorCohostClientLanguageServerManager.cs
  src/Tools/ExternalAccess/Razor/Cohost/IRazorCohostLanguageClientActivationService.cs
  src/Tools/ExternalAccess/Razor/Cohost/IRazorCustomMessageTarget.cs
  src/Tools/ExternalAccess/Razor/Cohost/RazorCohostClientLanguageServerManagerFactory.cs
  src/Tools/ExternalAccess/Razor/Cohost/RazorCohostDidChangeEndpoint.cs
  src/Tools/ExternalAccess/Razor/Cohost/RazorCohostDidCloseEndpoint.cs
  src/Tools/ExternalAccess/Razor/Cohost/RazorCohostDidOpenEndpoint.cs
  src/Tools/ExternalAccess/Razor/Cohost/RazorCohostLanguageClient.cs
  src/Tools/ExternalAccess/Razor/Cohost/RazorCohostProjectContextEndpoint.cs
  src/Tools/ExternalAccess/Razor/Cohost/RazorCohostRequestContext.cs
  src/Tools/ExternalAccess/Razor/Cohost/RazorLspServiceProvider.cs
  src/Tools/ExternalAccess/Razor/Cohost/RazorLspWorkspaceManagerFactory.cs
  src/Tools/ExternalAccess/Razor/Cohost/RazorRequestExecutionQueueProvider.cs
  src/Tools/ExternalAccess/Razor/Cohost/RazorRequestTelemetryLoggerFactory.cs
  src/Tools/ExternalAccess/Razor/InternalAPI.Unshipped.txt
  src/Tools/ExternalAccess/Razor/Microsoft.CodeAnalysis.ExternalAccess.Razor.csproj
  src/Tools/ExternalAccess/RazorTest/Cohost/RazorCohostTests.cs
  src/Tools/ExternalAccess/RazorTest/Microsoft.CodeAnalysis.ExternalAccess.Razor.UnitTests.csproj
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
Labels: Area-IDE, untriaged

#71215 Fix BuildHost in Source Build
  eng/SourceBuildPrebuiltBaseline.xml
  eng/Version.Details.xml
  eng/Versions.props
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Utilities/TestOutputLogger.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Logging/LspLogMessageLogger.cs
  src/Features/Lsif/Generator/Logging/LsifFormatLogger.cs
  src/Features/Lsif/Generator/Logging/PlainTextLogger.cs
  src/Tools/BuildValidator/DemoLogger.cs
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
Labels: Area-Infrastructure, untriaged

#71104 Rename automatic restore requests to be more explicit
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/ProjectDependencyHelper.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/Extensions.cs
Labels: Area-IDE, untriaged

#71007 Fix building executables for language server
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Microsoft.CodeAnalysis.LanguageServer.csproj
Labels: Area-Infrastructure, untriaged

#71228 Params Collections: Implement language version check.
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ParameterHelpers.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit2/Semantics/ParamsCollectionTests.cs
Labels: Area-Compilers, untriaged, New Feature - ParamsCollections

#70647 Fix Crash in AbstractChangeImplementationCodeRefactoringProvider
  src/Features/CSharp/Portable/ImplementInterface/AbstractChangeImplementationCodeRefactoringProvider.cs
  src/Features/CSharpTest/ImplementInterface/ImplementImplicitlyTests.cs
  src/Features/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs
Labels: Area-IDE, untriaged

#71077 Fix Code Actions not applied when LSP editor is enabled
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionHelpers.cs
  src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionResolveData.cs
  src/Features/LanguageServer/ProtocolUnitTests/CodeActions/CodeActionsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/CodeActions/RunCodeActionsTests.cs
Labels: Area-IDE, untriaged

#71248 Fix infinite loop in tagging
  src/EditorFeatures/Core/Shared/Tagging/Utilities/TagSpanIntervalTree.cs
  src/EditorFeatures/Test/Tagging/AsynchronousTaggerTests.cs
Labels: Area-IDE, untriaged

#71164 Update status/details on implicit indexers in object initializers
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation

#71235 Pass in helixApiAccessToken when available
  eng/pipelines/test-unix-job.yml
  eng/pipelines/test-windows-job.yml
  src/Tools/Source/RunTests/TestRunner.cs
Labels: Area-Infrastructure, untriaged

#71253 Fix null ref exception in Symbol.CanBeReferencedByName for VB
  src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/DataFlowPass.vb
  src/Compilers/VisualBasic/Portable/Symbols/Symbol.vb
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenRefReturnTests.vb
Labels: Language-VB, Area-Compilers, untriaged

#71169 Add GetDeclaredSymbol overload for LocalFunctionStatementSyntax
  src/Compilers/CSharp/Portable/CSharpExtensions.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs
Labels: Area-Compilers, Community, untriaged

#71258 Do not report separate diagnostics just for fading
  src/Analyzers/CSharp/Analyzers/InvokeDelegateWithConditionalAccess/InvokeDelegateWithConditionalAccessAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/AbstractCSharpUseCollectionExpressionDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForArrayDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForBuilderDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForCreateDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForStackAllocDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/InvokeDelegateWithConditionalAccess/InvokeDelegateWithConditionalAccessCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpUseCollectionExpressionForEmptyCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseThrowExpression/UseThrowExpressionCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/InvokeDelegateWithConditionalAccess/InvokeDelegateWithConditionalAccessTests.cs
  src/Analyzers/CSharp/Tests/InvokeDelegateWithConditionalAccess/InvokeDelegateWithConditionalAccessTests_FixAllTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForBuilderTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForCreateTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForStackAllocTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests_CollectionExpression.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/AbstractUseCollectionInitializerDiagnosticAnalyzer.cs
  src/Analyzers/Core/CodeFixes/UseCoalesceExpression/UseCoalesceExpressionForNullableTernaryConditionalCheckCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseCoalesceExpression/UseCoalesceExpressionForTernaryConditionalCheckCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseNullPropagation/AbstractUseNullPropagationCodeFixProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/ForkingSyntaxEditorBasedCodeFixProvider.cs
Labels: Area-IDE, IDE-CodeStyle, untriaged

#71262 Add check for EffectiveAnalysisLevelStyle in code style targets
  src/CodeStyle/Tools/Program.cs
Labels: Area-Analyzers, untriaged

#71069 Update MSBuild ref dependency
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#70682 Update NuGet-packages.md for 17.8
  docs/wiki/NuGet-packages.md
Labels: Area-Infrastructure, untriaged

#71266 Revert "Restore using dotnet CLI to ensure NuGet environment variables are used"
  azure-pipelines-pr-validation.yml
Labels: Area-Infrastructure, untriaged

#71269 Revert "Merge pull request #71258 from mavasani/RemoveFadingDiagnostics"
  src/Analyzers/CSharp/Analyzers/InvokeDelegateWithConditionalAccess/InvokeDelegateWithConditionalAccessAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/AbstractCSharpUseCollectionExpressionDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForArrayDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForBuilderDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForCreateDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForStackAllocDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/InvokeDelegateWithConditionalAccess/InvokeDelegateWithConditionalAccessCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpUseCollectionExpressionForEmptyCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseThrowExpression/UseThrowExpressionCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/InvokeDelegateWithConditionalAccess/InvokeDelegateWithConditionalAccessTests.cs
  src/Analyzers/CSharp/Tests/InvokeDelegateWithConditionalAccess/InvokeDelegateWithConditionalAccessTests_FixAllTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForBuilderTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForCreateTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForStackAllocTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests_CollectionExpression.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/AbstractUseCollectionInitializerDiagnosticAnalyzer.cs
  src/Analyzers/Core/CodeFixes/UseCoalesceExpression/UseCoalesceExpressionForNullableTernaryConditionalCheckCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseCoalesceExpression/UseCoalesceExpressionForTernaryConditionalCheckCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseNullPropagation/AbstractUseNullPropagationCodeFixProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/ForkingSyntaxEditorBasedCodeFixProvider.cs
Labels: Area-IDE, untriaged

#71249 Localize 17.9 branch
  azure-pipelines-official.yml
Labels: Area-Infrastructure, untriaged

#69820 Cache ROS constructed from arrays of constants (remaining types)
  src/Compilers/CSharp/Portable/CodeGen/EmitArrayInitializer.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitConversion.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenReadOnlySpanConstructionTest.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
  src/Compilers/Core/Portable/CodeGen/ITokenDeferral.cs
  src/Compilers/Core/Portable/CodeGen/PrivateImplementationDetails.cs
  src/Compilers/Core/Portable/ConstantValue.cs
  src/Compilers/Core/Portable/CryptographicHashProvider.cs
  src/Compilers/Core/Portable/Emit/CommonPEModuleBuilder.cs
Labels: Area-Compilers, untriaged

#71264 Remove extra backslash from IBC script
  eng/build.ps1
Labels: Area-Infrastructure, Community, untriaged

#71140 Do not resolve diagnostics early during attribute binding
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/Binder/LockOrUsingBinder.cs
  src/Compilers/CSharp/Portable/Binder/MethodGroupResolution.cs
  src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs
  src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.PlaceholderLocal.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Symbols/ConstantValueUtils.cs
  src/Compilers/CSharp/Portable/Symbols/LocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceLocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedLocal.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/TypeSubstitutedLocalSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.SymbolAndDiagnostics.cs
  src/Compilers/CSharp/Portable/Symbols/UpdatedContainingSymbolLocal.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/ColorColorTests.cs
  src/Compilers/Core/Portable/Binding/BindingDiagnosticBag.cs
  src/Compilers/Core/Portable/Diagnostic/DiagnosticBag.cs
  src/Compilers/Test/Utilities/CSharp/Extensions.cs
  src/Compilers/Test/Utilities/VisualBasic/Extensions.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Conversions.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Delegates.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Invocation.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Lambda.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_WithBlock.vb
  src/Compilers/VisualBasic/Portable/BoundTree/BoundNodes.xml
  src/Compilers/VisualBasic/Portable/BoundTree/BoundTypeOrValueExpression.vb
  src/Compilers/VisualBasic/Portable/BoundTree/UnboundLambda.vb
  src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb
  src/Compilers/VisualBasic/Portable/Generated/BoundNodes.xml.Generated.vb
  src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_LateAddressOf.vb
  src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Query.vb
  src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb
  src/Compilers/VisualBasic/Portable/Semantics/OverloadResolution.vb
  src/Compilers/VisualBasic/Portable/Semantics/TypeInference/TypeArgumentInference.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/LocalSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceAssemblySymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceModuleSymbol.BoundImports.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceModuleSymbol.vb
  src/Compilers/VisualBasic/Test/Semantic/Binding/Binder_Expressions_Tests.vb
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EELocalSymbolBase.cs
Labels: Area-Compilers, untriaged

#71272 Simplify some MEF imports/exports
  src/EditorFeatures/Core/EditAndContinue/Contracts/ManagedHotReloadServiceBridge.cs
  src/EditorFeatures/Core/EditAndContinue/EditAndContinueLanguageService.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/ProjectInitializationHandler.cs
  src/Tools/ExternalAccess/Debugger/GlassTestsHotReloadService.cs
  src/VisualStudio/DevKit/Impl/EditAndContinue/ManagedHotReloadLanguageServiceBridge.cs
  src/VisualStudio/DevKit/Impl/Microsoft.VisualStudio.LanguageServices.DevKit.csproj
  src/Workspaces/Remote/Core/EditAndContinue/ManagedHotReloadLanguageService.cs
  src/Workspaces/Remote/Core/EditAndContinue/ManagedHotReloadServiceProxy.cs
  src/Workspaces/Remote/Core/EditAndContinue/SolutionSnapshotProviderProxy.cs
  src/Workspaces/Remote/Core/ServiceBrokerExtensions.cs
  src/Workspaces/Remote/Core/ServiceBrokerProvider.cs
Labels: Area-Interactive, untriaged

#71284 Fix issue when we report a missing default case in switch statements with patterns
  src/Analyzers/CSharp/Analyzers/PopulateSwitch/CSharpPopulateSwitchStatementDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/PopulateSwitch/CSharpPopulateSwitchStatementCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/PopulateSwitch/PopulateSwitchStatementTests.cs
  src/Analyzers/Core/Analyzers/PopulateSwitch/PopulateSwitchExpressionHelpers.cs
  src/Analyzers/Core/Analyzers/PopulateSwitch/PopulateSwitchStatementHelpers.cs
Labels: Area-IDE, untriaged

#71166 Split integration test build from test run
  azure-pipelines-integration-corehost.yml
  azure-pipelines-integration-lsp.yml
  azure-pipelines-integration-scouting.yml
  azure-pipelines-integration.yml
  eng/build.ps1
  eng/pipelines/test-integration-helix.yml
  src/Tools/PrepareTests/MinimizeUtil.cs
  src/Tools/PrepareTests/TestDiscovery.cs
  src/Tools/Source/RunTests/RunTests.csproj
Labels: Area-Infrastructure, untriaged

#71195 Collection expression spread optimization
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
Labels: Area-Compilers, untriaged

#71298 Rename generated AnalysisLevelStyle_xxx.editorconfig to AnalysisLevelStyle_xxx.globalconfig
  src/CodeStyle/Tools/Program.cs
Labels: Area-Infrastructure, Community, untriaged

#71271 Params Collections: Implement "Better function member" section of the proposal
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/ParamsCollectionTests.cs
Labels: Area-Compilers, untriaged, New Feature - ParamsCollections

#71134 Allow collection expressions with `CreateCompilation`
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs
  src/Compilers/Test/Core/CollectionBuilderAttribute.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestSource.cs
Labels: Area-Compilers, Test, untriaged

#71282 Do not call Unsubst if it is not available due to argument processing
  eng/build-utils.ps1
  eng/build.ps1
Labels: Area-Infrastructure, Community, untriaged

#71324 Fix simplify lambda expression with unrelated assignment in other method
  src/Analyzers/CSharp/Analyzers/RemoveUnnecessaryLambdaExpression/CSharpRemoveUnnecessaryLambdaExpressionDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/RemoveUnnecessaryLambdaExpression/RemoveUnnecessaryLambdaExpressionTests.cs
Labels: Area-IDE, untriaged

#71323 Do not checkout when running integration tests
  eng/pipelines/test-integration-helix.yml
Labels: Area-Infrastructure, untriaged

#71327 Make CodeAction.NestedActions public
  src/EditorFeatures/CSharpTest/Diagnostics/Configuration/ConfigureCodeStyle/MultipleCodeStyleOptionConfigurationTests.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/AbstractCodeActionOrUserDiagnosticTest.cs
  src/EditorFeatures/DiagnosticsTestUtilities/Diagnostics/AbstractSuppressionDiagnosticTest.cs
  src/EditorFeatures/Test2/Diagnostics/AbstractCrossLanguageUserDiagnosticTest.vb
  src/EditorFeatures/Test2/Rename/InlineRenameTests.vb
  src/EditorFeatures/VisualBasicTest/Diagnostics/Suppression/SuppressionTests.vb
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionBatchFixAllProvider.cs
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionCodeFixProvider.PragmaBatchFixHelpers.cs
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionCodeFixProvider.cs
  src/Features/LanguageServer/Protocol/Features/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs
  src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionHelpers.cs
  src/Tools/ExternalAccess/OmniSharp/CodeActions/OmniSharpCodeAction.cs
  src/Workspaces/Core/Portable/CodeActions/CodeAction.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
Labels: Area-IDE, untriaged

#71329 Cleanup overload resolution code used in signature help
  src/EditorFeatures/CSharpTest/SignatureHelp/InvocationExpressionSignatureHelpProviderTests.cs
  src/EditorFeatures/TestUtilities/SignatureHelp/AbstractSignatureHelpProviderTests.cs
  src/Features/CSharp/Portable/SignatureHelp/AbstractCSharpSignatureHelpProvider.LightweightOverloadResolution.cs
  src/Features/CSharp/Portable/SignatureHelp/ConstructorInitializerSignatureHelpProvider.cs
  src/Features/CSharp/Portable/SignatureHelp/InvocationExpressionSignatureHelpProvider.cs
  src/Features/CSharp/Portable/SignatureHelp/LightweightOverloadResolution.cs
  src/Features/CSharp/Portable/SignatureHelp/ObjectCreationExpressionSignatureHelpProvider.cs
Labels: Area-IDE, untriaged

#70230 Fix GetDocumentationComment returns unresolved doc reference for inheritdoc typeparamref
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
  src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs
Labels: Area-IDE, Community, untriaged

#71330 SynthesizedReadOnlyListTypeSymbol.Create - Check for MissingMetadataTypeSymbol
  src/Compilers/CSharp/Portable/Symbols/Synthesized/ReadOnlyListType/SynthesizedReadOnlyListTypeSymbol.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, Community, untriaged

#71367 Fix issue when using a collection expr within object/collection intializers
  src/Analyzers/CSharp/Analyzers/InvokeDelegateWithConditionalAccess/InvokeDelegateWithConditionalAccessAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionInitializer/CSharpUseCollectionInitializerCodeFixProvider_CollectionInitializer.cs
  src/Analyzers/CSharp/CodeFixes/UsePatternMatching/CSharpAsAndNullCheckCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/BreakKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/ContinueKeywordRecommender.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionValidator.cs
  src/Features/CSharp/Portable/ExtractMethod/Extensions.cs
  src/Features/CSharp/Portable/UseExpressionBodyForLambda/UseExpressionBodyForLambdaCodeRefactoringProvider.cs
  src/Workspaces/CSharp/Portable/Extensions/SyntaxNodeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CSharpCompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/MemberAccessExpressionSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxNodeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTokenExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/SpeculationAnalyzer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/TypeStyle/CSharpUseImplicitTypeHelper.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CSharpWorkspaceExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/CSharpSyntaxContext.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/StringExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/SyntaxNodeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/SyntaxTokenExtensions.cs
Labels: Area-IDE, untriaged

#71368 Simplify code for checking assignments
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionValidator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxNodeExtensions.cs
Labels: Area-IDE, untriaged

#71325 IOperation - drop synthesized conversion placed on top of params collections
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/ParamsCollectionTests.cs
Labels: Area-Compilers, untriaged, New Feature - ParamsCollections

#71013 Use new helper type for initializing a value type field only once, and in a threadsafe manner.
  src/Compilers/CSharp/Portable/Compilation/BuiltInOperators.cs
  src/Compilers/CSharp/Portable/Syntax/CSharpSyntaxTree.cs
  src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/SuppressMessageAttributeState.cs
Labels: Area-Compilers, untriaged

#71257 Extract compilation-tracker/SG-production code out of SolutionState to a new owner.
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensRefreshQueue.cs
  src/VisualStudio/Core/Test.Next/Remote/RemoteHostClientServiceFactoryTests.cs
  src/VisualStudio/Core/Test.Next/Remote/SerializationValidator.cs
  src/VisualStudio/Core/Test.Next/Services/AssetProviderTests.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/VisualStudio/Core/Test.Next/Services/SolutionAssetCacheTests.cs
  src/VisualStudio/Core/Test.Next/Services/SolutionServiceTests.cs
  src/Workspaces/Core/Portable/ExternalAccess/UnitTesting/Api/UnitTestingSolutionExtensions.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/DependentTypeFinder_ProjectIndex.cs
  src/Workspaces/Core/Portable/Remote/IRemoteKeepAliveService.cs
  src/Workspaces/Core/Portable/Remote/RemoteHostClient.cs
  src/Workspaces/Core/Portable/Remote/RemoteServiceConnection.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Project.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationAndGeneratorDriverTranslationAction.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationAndGeneratorDriverTranslationAction_Actions.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationPair.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.CompilationTrackerState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker_Generators.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.GeneratedFileReplacingCompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.ICompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.SkeletonReferenceCache.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.SkeletonReferenceSet.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.SymbolToProjectId.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.UnrootedSymbolSet.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState_Checksum.cs
  src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs
  src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentStates.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
  src/Workspaces/Remote/Core/BrokeredServiceConnection.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.Scope.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
  src/Workspaces/Remote/ServiceHub/Host/SolutionAssetCache.cs
  src/Workspaces/Remote/ServiceHub/Host/TestUtils.cs
  src/Workspaces/Remote/ServiceHub/Services/SourceGeneration/RemoteSourceGenerationService.cs
Labels: Area-IDE, untriaged

#71393 Remove unused enum values
  src/Workspaces/Core/Portable/Remote/WellKnownSynchronizationKind.cs
  src/Workspaces/Core/Portable/Serialization/SerializationExtensions.cs
Labels: Area-IDE, untriaged

#71395 Call GetURI when getting a URI for a document
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/Features/LanguageServer/ProtocolUnitTests/FoldingRanges/FoldingRangesTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Miscellaneous/LspMiscellaneousFilesWorkspaceTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Symbols/DocumentSymbolsTests.cs
  src/Tools/ExternalAccess/Razor/RazorUri.cs
Labels: Area-IDE, untriaged

#68804 Force public APIs to return complete results
  src/Features/Core/Portable/Completion/CompletionOptions.cs
  src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs
  src/Features/Core/Portable/Completion/CompletionService.cs
  src/Features/Core/Portable/Completion/CompletionService_GetCompletions.cs
  src/VisualStudio/Core/Def/LanguageService/AbstractCreateServicesOnTextViewConnection.cs
Labels: Area-IDE, untriaged

#68503 Update EA layer for ASP.NET
  src/Tools/ExternalAccess/AspNetCore/Microsoft.CodeAnalysis.ExternalAccess.AspNetCore.csproj
Labels: Area-Infrastructure, untriaged

#70305 Add line continuation tests for string concatenation
  src/Workspaces/CoreTest/CodeCleanup/RemoveUnnecessaryLineContinuationTests.cs
Labels: Area-IDE, untriaged

#70014 Allow switch arms to start a line with an open brace
  src/Workspaces/CSharpTest/Formatting/FormattingTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs
Labels: Area-IDE, untriaged

#70983 Use CPS for tests where saving documents needs to be reliable
  eng/Versions.props
  src/VisualStudio/IntegrationTest/New.IntegrationTests/AbstractIntegrationTest.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpImmediate.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/DebuggerInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditAndContinueResult.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/HotReloadAction.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/IHotReloadUIService.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/IVsMessageBoxService.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/MessageBoxInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/ScreenshotInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/ShellInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InfrastructureTests.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/Microsoft.VisualStudio.LanguageServices.New.IntegrationTests.csproj
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicEditAndContinue.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicImmediate.cs
  src/VisualStudio/IntegrationTest/TestSetup/Microsoft.VisualStudio.IntegrationTest.Setup.csproj
  src/VisualStudio/IntegrationTest/TestSetup/source.extension.vsixmanifest
Labels: Area-Infrastructure, untriaged

#71412 #66116 Long switch expression is duplicated in InferTypesWorker_DoNot…
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs
Labels: Area-IDE, Community, untriaged

#71220 Only apply one document info change for linked documents
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpRename.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerInProcess.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
Labels: Area-IDE, untriaged

#71288 Provide 'return' keyword in attribute context for accessor
  src/EditorFeatures/CSharpTest2/Recommendations/ReturnKeywordRecommenderTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/ReturnKeywordRecommender.cs
Labels: Area-IDE, untriaged

#71332 [Inline Rename] Update the UI related to Copilot
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyoutViewModel.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameUserInputTextBox.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameUserInputTextBox.xaml.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/IRenameUserInput.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/RenameUserInputPresenter.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameControl.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameControl.xaml.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameStatusControl.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameStatusControl.xaml.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameUserInputComboBox.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameUserInputComboBox.xaml.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameViewModel.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/InlineRenameInProcess.cs
Labels: Area-IDE, Community, untriaged
