Repository dotnet/roslyn, pull requests merged in 2023-10, with the labels that each got.

#70203 Delpoy ExternalAccess.RazorCompiler with compiler
  Compilers.slnf
  src/Compilers/CSharp/csc/CscCommandLine.projitems
  src/Compilers/Core/CodeAnalysisTest/AnalyzerAssemblyLoaderTests.cs
  src/Compilers/Core/CodeAnalysisTest/Microsoft.CodeAnalysis.UnitTests.csproj
  src/Compilers/Server/VBCSCompiler/VBCSCompilerCommandLine.projitems
  src/Compilers/VisualBasic/vbc/VbcCommandLine.projitems
  src/NuGet/Microsoft.Net.Compilers.Toolset/CoreClrCompilerArtifacts.targets
  src/NuGet/Microsoft.Net.Compilers.Toolset/DesktopCompilerArtifacts.targets
  src/NuGet/VisualStudio/VS.Tools.Roslyn.Package.csproj
  src/Tools/ExternalAccess/RazorCompiler/Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.csproj
Labels: Area-Compilers, untriaged

#70113 Handle constant `null`s in pointer pattern matching
  src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs
  src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests4.cs
Labels: Area-Compilers, New Language Feature - Pattern Matching, untriaged

#70193 Update 'use collection expression' analyzer/fixer to support conversion when a capacity argument is passed.
  src/Analyzers/CSharp/Analyzers/UseCollectionInitializer/CSharpUseCollectionInitializerAnalyzer.cs
  src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests_CollectionExpression.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/AbstractUseCollectionInitializerAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/AbstractUseCollectionInitializerDiagnosticAnalyzer.cs
  src/Analyzers/VisualBasic/Analyzers/UseCollectionInitializer/VisualBasicCollectionInitializerAnalyzer.vb
Labels: Area-IDE, untriaged

#70079 Semantic snippets: Follow user's preferred modifier order for type declaration snippets
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpClassSnippetCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpStructSnippetCompletionProviderTests.cs
  src/Features/CSharp/Portable/Snippets/AbstractCSharpTypeSnippetProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTokenExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTreeExtensions.cs
Labels: Area-IDE, Community, untriaged

#70207 Additional tests for 'use collection expression'.
  src/Analyzers/CSharp/Analyzers/UseCollectionInitializer/CSharpUseCollectionInitializerAnalyzer.cs
  src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests_CollectionExpression.cs
Labels: Area-IDE, untriaged

#70067 Implement support in the LSIF generator for logging to stderr
  src/Features/Lsif/Generator/Generator.cs
  src/Features/Lsif/Generator/Logging/LsifFormatLogger.cs
  src/Features/Lsif/Generator/Logging/PlainTextLogger.cs
  src/Features/Lsif/Generator/Program.cs
  src/Features/Lsif/Generator/Writing/LineModeLsifJsonWriter.cs
  src/Features/Lsif/GeneratorTest/LsifFormatLoggerTests.vb
  src/Features/Lsif/GeneratorTest/Utilities/TestLsifOutput.vb
Labels: Area-IDE, untriaged

#70156 Update default razor project cache file name
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/RazorWorkspaceListenerInitializer.cs
Labels: Area-Infrastructure, untriaged

#69259 Remove newly doc'd rules
  src/Features/RulesMissingDocumentation.md
Labels: Area-Infrastructure, Community, untriaged

#70189 Add Global prefix to VBCSCompiler mutex to make it visible on nix systems
  src/Compilers/Server/VBCSCompilerTests/BuildClientTests.cs
  src/Compilers/Shared/BuildServerConnection.cs
Labels: Area-Compilers, Community

#70216 Insert Roslyn 17.8 to VS 17.8
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#70215 Small piece of fallout from teh prior progress API pr.
  src/Analyzers/Core/CodeFixes/MatchFolderAndNamespace/AbstractChangeNamespaceToMatchFolderCodeFixProvider.CustomFixAllProvider.cs
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionBatchFixAllProvider.cs
  src/Features/Core/Portable/CodeRefactorings/AddMissingImports/IAddMissingImportsFeatureService.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
  src/Workspaces/Core/Portable/Shared/Utilities/ProgressTracker.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Progress/CodeAnalysisProgressExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Utilities/IProgressTracker.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Utilities/NoOpProgressTracker.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensions.projitems
Labels: Area-IDE, untriaged

#70219 Immunize System.Linq methods
  src/VisualStudio/Core/Def/Watson/FaultReporter.cs
Labels: Area-IDE, untriaged

#70220 Improve checksum perf
  src/Workspaces/Core/Portable/Workspace/Solution/Checksum.cs
Labels: Area-IDE, untriaged

#70223 Create and cache a singleton directive parser inside the lexer
  src/Compilers/CSharp/Portable/Parser/DirectiveParser.cs
  src/Compilers/CSharp/Portable/Parser/DocumentationCommentParser.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/Parser/Lexer.cs
  src/Compilers/CSharp/Portable/Parser/SyntaxParser.cs
Labels: Area-Compilers, untriaged

#70229 Add O# EA accessor for DocumentId.CreateFromSerialized
  src/Tools/ExternalAccess/OmniSharp/InternalAPI.Unshipped.txt
  src/Tools/ExternalAccess/OmniSharp/Workspace/OmniSharpDocumentId.cs
Labels: Area-Infrastructure, untriaged

#70237 Use stronger typing wrt to checksums and checksum trees
  src/Workspaces/Core/Portable/Serialization/SerializerService_ChecksumWithChildren.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Checksum.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ChecksumCollection.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ChecksumWithChildren.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Checksum_Factory.cs
  src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs
  src/Workspaces/Remote/ServiceHub/Host/ChecksumSynchronizer.cs
Labels: Area-IDE, untriaged

#70240 Load solutions out-of-proc
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/BuildHostProcessManager.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Microsoft.CodeAnalysis.LanguageServer.csproj
  src/Features/LanguageServer/Protocol/Features/Options/LanguageServerProjectSystemOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Handler/Configuration/DidChangeConfigurationNotificationHandler_OptionList.cs
  src/Features/LanguageServer/ProtocolUnitTests/Configuration/DidChangeConfigurationNotificationHandlerTest.cs
  src/VisualStudio/Core/Test.Next/Options/VisualStudioOptionStorageTests.cs
  src/Workspaces/Core/MSBuild.BuildHost/BuildHost.cs
  src/Workspaces/Core/MSBuild.BuildHost/IBuildHost.cs
Labels: Area-IDE, untriaged

#70202 fix missing space for numeric token #70135
  src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs
  src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs
Labels: Area-Compilers, Community

#70250 Fix incorrect isInsideDelimiters assumption in MoveCaretToSemicolonPosition
  src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs
  src/EditorFeatures/CSharpTest/CompleteStatement/CSharpCompleteStatementCommandHandlerTests.cs
  src/EditorFeatures/TestUtilities/CompleteStatement/AbstractCompleteStatementTests.cs
Labels: Area-IDE, untriaged

#70197 Collection expressions: optimize List<T> construction
  src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/CollectionExpressionTypeKind.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundCollectionExpression.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Portable/Symbols/TypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/Core/Portable/WellKnownTypes.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
Labels: Area-Compilers, untriaged, New Feature - Collection Expressions

#69956 Collection expressions: update rules for conversion to IEnumerable collection
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/CollectionExpressionTypeKind.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, New Feature - Collection Expressions

#70222 Collection expressions: ImmutableArray optimization
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/CollectionExpressionTypeKind.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/Core/Portable/WellKnownTypes.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
Labels: Area-Compilers, untriaged, New Feature - Collection Expressions

#70239 Fix checksum hierarchy
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensRefreshQueue.cs
  src/VisualStudio/Core/Test.Next/Remote/SerializationValidator.cs
  src/VisualStudio/Core/Test.Next/Remote/SnapshotSerializationTests.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo.cs
  src/Workspaces/Core/Portable/Remote/ISerializerService.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService_Asset.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService_ChecksumWithChildren.cs
  src/Workspaces/Core/Portable/Utilities/SpellChecker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Checksum.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ChecksumCollection.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ChecksumWithChildren.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Checksum_Factory.cs
  src/Workspaces/Core/Portable/Workspace/Solution/DocumentInfo.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectInfo.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs
  src/Workspaces/CoreTest/ChecksumTests.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.Scope.cs
  src/Workspaces/Remote/ServiceHub/Host/ChecksumSynchronizer.cs
  src/Workspaces/Remote/ServiceHub/Host/SolutionAssetCache.cs
  src/Workspaces/Remote/ServiceHub/Host/TestUtils.cs
Labels: Area-IDE, untriaged

#70158 Collection expressions: update better conversion from expression rule
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/CollectionExpressionTypeKind.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged, New Feature - Collection Expressions

#70255 Avoid returning checksums unnecessarily during OOP calls.
  src/Workspaces/CoreTestUtilities/Fakes/SimpleAssetSource.cs
  src/Workspaces/Remote/Core/ISolutionAssetProvider.cs
  src/Workspaces/Remote/Core/RemoteHostAssetSerialization.cs
  src/Workspaces/Remote/Core/SolutionAssetProvider.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.Scope.cs
  src/Workspaces/Remote/ServiceHub/Host/AssetProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/IAssetSource.cs
  src/Workspaces/Remote/ServiceHub/Host/SolutionAssetSource.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ImmutableArrayExtensions.cs
Labels: Area-IDE, untriaged

#70258 Use simpler PP directives in checksum factory
  src/Workspaces/Core/Portable/Workspace/Solution/Checksum_Factory.cs
Labels: Area-IDE, untriaged

#70192 Collection expressions: analyze nullability of element assignments
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged, New Feature - Collection Expressions

#70265 Merge stragglers from collection expressions into `main` branch
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/CollectionExpressionTypeKind.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundCollectionExpression.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Portable/Symbols/TypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/Core/Portable/WellKnownTypes.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
Labels: Area-Compilers, untriaged

#70186 Enable LSP pull diagnostics from Run Code Analysis command
  src/EditorFeatures/Test/CodeFixes/CodeFixServiceTests.cs
  src/EditorFeatures/Test2/Diagnostics/DiagnosticProviderTests.vb
  src/EditorFeatures/Test2/Diagnostics/DiagnosticServiceTests.vb
  src/EditorFeatures/TestUtilities/Diagnostics/MockDiagnosticAnalyzerService.cs
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/Core/Portable/Diagnostics/CodeAnalysisDiagnosticAnalyzerService.cs
  src/Features/Core/Portable/Diagnostics/ICodeAnalysisDiagnosticAnalyzerService.cs
  src/Features/Core/Portable/Diagnostics/IDiagnosticAnalyzerService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DiagnosticAnalyzerService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DiagnosticAnalyzerService_UpdateSource.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_IncrementalAnalyzer.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/AbstractProjectDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/AbstractWorkspaceDocumentDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/ProjectDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/WorkspaceDocumentDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
  src/VisualStudio/Core/Def/Diagnostics/VisualStudioDiagnosticAnalyzerService.cs
  src/VisualStudio/Core/Test/Diagnostics/ExternalDiagnosticUpdateSourceTests.vb
Labels: Area-IDE, Area-Analyzers, untriaged

#69873 Include implicit MyBase.New() call in IBlockOperation for VB Constructors
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IConstructorBodyOperation.cs
  src/Compilers/VisualBasic/Portable/Binding/Binder_Statements.vb
  src/Compilers/VisualBasic/Portable/Compilation/MethodCompiler.vb
  src/Compilers/VisualBasic/Test/Emit/ErrorHandling.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_IBlockStatement_MethodBlocks.vb
  src/Features/VisualBasicTest/InitializeParameter/AddParameterCheckTests.vb
  src/Features/VisualBasicTest/InitializeParameter/InitializeMemberFromParameterTests.vb
Labels: Area-Compilers, Feature - IOperation, untriaged

#70084 EnC: simplify SymbolMatcher
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/CSharpDefinitionMap.cs
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/CSharpSymbolMatcher.cs
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/EmitHelpers.cs
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/PEDeltaAssemblyBuilder.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/SymbolMatcherTests.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/DefinitionMap.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/DeltaMetadataWriter.cs
  src/Compilers/Core/Portable/Emit/NoPia/CommonEmbeddedMember.cs
  src/Compilers/Core/Portable/Emit/NoPia/CommonEmbeddedParameter.cs
  src/Compilers/Core/Portable/Emit/NoPia/CommonEmbeddedType.cs
  src/Compilers/Core/Portable/Emit/NoPia/CommonEmbeddedTypeParameter.cs
  src/Compilers/Core/Portable/Emit/NoPia/VtblGap.cs
  src/Compilers/Core/Portable/PEWriter/Core.cs
  src/Compilers/Core/Portable/Symbols/ISymbolInternal.cs
  src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/EmitHelpers.vb
  src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/PEDeltaAssemblyBuilder.vb
  src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/VisualBasicDefinitionMap.vb
  src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/VisualBasicSymbolMatcher.vb
  src/Compilers/VisualBasic/Portable/Symbols/Symbol.vb
  src/Compilers/VisualBasic/Test/Emit/Emit/EditAndContinue/EditAndContinueTestBase.vb
  src/Compilers/VisualBasic/Test/Emit/Emit/EditAndContinue/SymbolMatcherTests.vb
Labels: Area-Interactive, untriaged

#70191 Fix VB features impacted by IOperation change
  src/Features/Core/Portable/InitializeParameter/AbstractAddParameterCheckCodeRefactoringProvider.cs
  src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs
  src/Features/VisualBasicTest/InitializeParameter/AddParameterCheckTests.vb
  src/Features/VisualBasicTest/InitializeParameter/InitializeMemberFromParameterTests.vb
Labels: Area-Compilers, untriaged

#70260 Collection expressions: empty Span optimization
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged, New Feature - Collection Expressions

#70279 Simplify writing to asset buffer
  src/Workspaces/Remote/Core/SolutionAssetProvider.cs
Labels: Area-IDE, untriaged

#70271 Update VS version used for signed builds
  global.json
Labels: Area-Infrastructure, untriaged

#70273 [17.8] Collection expressions: merge changes for conversions and optimizations
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/CollectionExpressionTypeKind.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundCollectionExpression.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Portable/Symbols/TypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/Core/Portable/WellKnownTypes.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
Labels: Area-Compilers, untriaged

#70171 Avoid cycle caused by calculation of ObsoleteState/ExperimentalState.
  src/Compilers/CSharp/Test/Semantic/Semantics/BindingTests.cs
  src/Compilers/VisualBasic/Portable/Binding/Binder_Initializers.vb
  src/Compilers/VisualBasic/Test/Semantic/Binding/Binder_Expressions_Tests.vb
Labels: Area-Compilers, Tenet-Reliability, untriaged

#70320 Fix regression that caused us to sync data unnecessarily.
  src/Workspaces/Remote/ServiceHub/Host/AssetProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/ChecksumSynchronizer.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs
Labels: Area-IDE, untriaged

#70345 Fix .NET 8 RC1 version
  global.json
Labels: Area-Infrastructure, untriaged

#70301 Small bits of cleanup in sync'ing code.
  src/VisualStudio/Core/Test.Next/Remote/SerializationValidator.cs
  src/VisualStudio/Core/Test.Next/Remote/SnapshotSerializationTests.cs
  src/Workspaces/Core/Portable/Serialization/PooledList.cs
  src/Workspaces/Remote/Core/RemoteHostAssetSerialization.cs
  src/Workspaces/Remote/Core/SolutionAsset.cs
  src/Workspaces/Remote/Core/SolutionAssetProvider.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.Scope.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.cs
Labels: Area-IDE, untriaged

#70287 Update 'use collection expression' to support cases where an array was assigned to a span type.
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForArrayDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/UseCollectionExpressionHelpers.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForEmptyTests.cs
Labels: Area-IDE, untriaged

#70348 Remove recursion in part of Find-References algorithm
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferenceCache.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamespaceSymbolReferenceFinder.cs
Labels: Area-IDE, untriaged

#70278 Avoid taking a lock the vast majority of the time in GlobalOptionService.GetOption
  src/Workspaces/Core/Portable/Options/GlobalOptionService.cs
Labels: Area-IDE, untriaged

#70285 Short-circuit tagger usage of interval tree when tagging complete snapshot
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs
Labels: Area-IDE, untriaged

#70324 In most cases, remove the camel case matching for case sensitive matches
  src/Workspaces/Core/Portable/PatternMatching/PatternMatcher.cs
Labels: Area-IDE, untriaged

#70319 Reduce ImmutableDictionary allocations in CreateCompilationTrackerMap
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
Labels: Area-IDE, untriaged

#70261 Fix build race
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Microsoft.CodeAnalysis.LanguageServer.csproj
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/PackAllRids.targets
  src/Tools/BuildBoss/ProjectUtil.cs
Labels: Area-Infrastructure, untriaged

#70331 Pass along analyzer references to projects
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs
Labels: Area-IDE, untriaged

#70263 Add support for using Mono to load .NET Framework projects
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/BuildHostProcessManager.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/LanguageServerResources.resx
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.cs.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.de.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.es.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.fr.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.it.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.ja.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.ko.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.pl.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.pt-BR.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.ru.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.tr.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.zh-Hans.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.zh-Hant.xlf
  src/Workspaces/Core/MSBuild.BuildHost/BuildHost.cs
  src/Workspaces/Core/MSBuild.BuildHost/MonoMSBuildDiscovery.cs
Labels: Area-IDE, untriaged

#70302 Remove double tree traversal in checksum syncing.
  src/VisualStudio/Core/Test.Next/Remote/SerializationValidator.cs
  src/VisualStudio/Core/Test.Next/Remote/SnapshotSerializationTests.cs
  src/VisualStudio/Core/Test.Next/Remote/SolutionAsset.cs
  src/Workspaces/Core/Portable/Remote/WellKnownSynchronizationKind.cs
  src/Workspaces/Core/Portable/Serialization/PooledList.cs
  src/Workspaces/Core/Portable/Serialization/SerializationExtensions.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ChecksumCollection.cs
  src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs
  src/Workspaces/CoreTestUtilities/Fakes/SimpleAssetSource.cs
  src/Workspaces/Remote/Core/RemoteHostAssetSerialization.cs
  src/Workspaces/Remote/Core/SolutionAsset.cs
  src/Workspaces/Remote/Core/SolutionAssetProvider.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.Scope.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.cs
  src/Workspaces/Remote/ServiceHub/Host/SolutionAssetSource.cs
  src/Workspaces/Remote/ServiceHub/Host/TestUtils.cs
Labels: Area-IDE, untriaged

#70242 Avoid infinite cycle caused by an early binding of DefaultParameterValue attribute.
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_WellKnownAttributes.cs
  src/Compilers/VisualBasic/Portable/Binding/Binder_Expressions.vb
  src/Compilers/VisualBasic/Portable/Binding/EarlyWellKnownAttributeBinder.vb
  src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.vb
Labels: Area-Compilers, untriaged

#70286 More tests for an issue around constrained calls
  src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenCallTests.cs
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenCallTests.vb
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenRefReturnTests.vb
Labels: Area-Compilers, Test, untriaged

#70297 Replace Roslyn.Utilities.IReadOnlySet with System.Collections.Generic.IReadOnlySet
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncIteratorMethodToStateMachineRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncMethodToStateMachineRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/IteratorRewriter/IteratorMethodToStateMachineRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/MethodToStateMachineRewriter.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedPrimaryConstructor.cs
  src/Compilers/Core/Portable/Collections/IOrderedReadOnlySet.cs
  src/Compilers/Core/Portable/Collections/OrderedSet.cs
  src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs
  src/Compilers/Core/Portable/InternalUtilities/IReadOnlySet.cs
  src/Compilers/Core/Portable/InternalUtilities/SetWithInsertionOrder.cs
  src/Compilers/VisualBasic/Portable/Lowering/AsyncRewriter/AsyncRewriter.AsyncMethodToClassRewriter.vb
  src/Compilers/VisualBasic/Portable/Lowering/IteratorRewriter/IteratorRewriter.IteratorMethodToClassRewriter.vb
  src/Compilers/VisualBasic/Portable/Lowering/StateMachineRewriter/StateMachineRewriter.StateMachineMethodToClassRewriter.vb
  src/Compilers/VisualBasic/Portable/Lowering/StateMachineRewriter/StateMachineRewriter.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/ObjectPools/PooledHashSet.cs
Labels: Area-Compilers, untriaged

#70298 Remove hello service
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/ServiceBrokerFactory.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/Services/Descriptors.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/Services/HelloWorld/HelloWorldService.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/Services/HelloWorld/IHelloWorld.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/Services/HelloWorld/RemoteHelloWorldProvider.cs
Labels: Area-IDE, untriaged

#70289 Recommend `void` keyword in `using unsafe` directives
  src/EditorFeatures/CSharpTest2/Recommendations/VoidKeywordRecommenderTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/VoidKeywordRecommender.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTokenExtensions.cs
Labels: Area-IDE, Community, untriaged

#70341 Further checksum syncing cleanup work.
  src/VisualStudio/Core/Test.Next/Services/AssetProviderTests.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Checksum.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ChecksumCollection.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState_Checksum.cs
  src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs
  src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentState_Checksum.cs
  src/Workspaces/Remote/ServiceHub/Host/AssetProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/ChecksumSynchronizer.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs
  src/Workspaces/Remote/ServiceHub/Host/TestUtils.cs
Labels: Area-IDE, untriaged

#70039 Send batch events for DiagnosticsUpdatedArgs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptDiagnosticService.cs
  src/EditorFeatures/Core/Shared/Tagging/EventSources/TaggerEventSources.DiagnosticsChangedEventSource.cs
  src/EditorFeatures/Test/Diagnostics/DiagnosticAnalyzerServiceTests.cs
  src/EditorFeatures/Test/Diagnostics/DiagnosticServiceTests.cs
  src/EditorFeatures/Test/Diagnostics/MockDiagnosticService.cs
  src/EditorFeatures/Test/EditAndContinue/RemoteEditAndContinueServiceTests.cs
  src/EditorFeatures/TestUtilities/Squiggles/TestDiagnosticTagProducer.cs
  src/Features/Core/Portable/Diagnostics/AbstractHostDiagnosticUpdateSource.cs
  src/Features/Core/Portable/Diagnostics/IDiagnosticUpdateSource.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueDiagnosticUpdateSource.cs
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/Api/IVSTypeScriptDiagnosticService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DefaultDiagnosticAnalyzerService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DiagnosticAnalyzerService_UpdateSource.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DiagnosticService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DiagnosticService_UpdateSourceRegistrationService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_IncrementalAnalyzer.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/IDiagnosticService.cs
  src/VisualStudio/Core/Def/AnalyzerDependency/AnalyzerDependencyCheckingService.cs
  src/VisualStudio/Core/Def/AnalyzerDependency/AnalyzerFileWatcherService.cs
  src/VisualStudio/Core/Def/TableDataSource/VisualStudioBaseDiagnosticListTable.LiveTableDataSource.cs
  src/VisualStudio/Core/Def/TaskList/ExternalErrorDiagnosticUpdateSource.cs
  src/VisualStudio/Core/Def/TaskList/HostDiagnosticUpdateSource.cs
  src/VisualStudio/Core/Test/Diagnostics/DefaultDiagnosticUpdateSourceTests.vb
  src/VisualStudio/Core/Test/Diagnostics/DiagnosticTableDataSourceTests.vb
  src/VisualStudio/Core/Test/Diagnostics/ExternalDiagnosticUpdateSourceTests.vb
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioAnalyzerTests.vb
Labels: Area-IDE, untriaged

#70295 Preserve existing formatting when fully qualifying names
  src/Features/CSharp/Portable/FullyQualify/CSharpFullyQualifyService.cs
  src/Features/CSharpTest/FullyQualify/FullyQualifyTests.cs
  src/Features/VisualBasic/Portable/FullyQualify/VisualBasicFullyQualifyService.vb
  src/Features/VisualBasicTest/FullyQualify/FullyQualifyTests.vb
Labels: Area-IDE, untriaged

#70290 Enable recommender for `scoped` keyword
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Features/CSharp/Portable/Completion/CompletionProviders/KeywordCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/ScopedKeywordRecommender.cs
Labels: Area-IDE, Community, untriaged

#70342 Allow server to pass along a specific project-scope it wants to sync data for.
  src/VisualStudio/Core/Test.Next/Remote/SerializationValidator.cs
  src/VisualStudio/Core/Test.Next/Services/AssetProviderTests.cs
  src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs
  src/Workspaces/CoreTestUtilities/Fakes/SimpleAssetSource.cs
  src/Workspaces/Remote/Core/AbstractAssetProvider.cs
  src/Workspaces/Remote/Core/ISolutionAssetProvider.cs
  src/Workspaces/Remote/Core/SolutionAssetProvider.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.Scope.cs
  src/Workspaces/Remote/ServiceHub/Host/AssetProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/ChecksumSynchronizer.cs
  src/Workspaces/Remote/ServiceHub/Host/IAssetSource.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs
  src/Workspaces/Remote/ServiceHub/Host/SolutionAssetSource.cs
  src/Workspaces/Remote/ServiceHub/Host/TestUtils.cs
Labels: Area-IDE, untriaged

#70358 Fix 'fix all' support for code actions being broken
  src/EditorFeatures/Core.Wpf/Suggestions/FixAll/FixAllGetFixesService.cs
  src/Features/Core/Portable/CodeFixesAndRefactorings/AbstractFixAllGetFixesService.cs
  src/Features/Core/Portable/CodeFixesAndRefactorings/FeaturesFixAllGetFixesService.cs
Labels: Area-IDE, untriaged

#70266 Unskip working tests
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
Labels: Area-IDE, Community, untriaged

#70344 Rewrite captured field symbol during "materialization"
  src/Compilers/VisualBasic/Portable/Lowering/AsyncRewriter/AsyncRewriter.CapturedSymbolOrExpression.vb
  src/Compilers/VisualBasic/Portable/Lowering/MethodToClassRewriter/MethodToClassRewriter.vb
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenAsyncTests.vb
Labels: Area-Compilers, untriaged

#70377 Disable flakey integration tests
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpGoToDefinition.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicGoToDefinition.cs
Labels: Area-IDE, untriaged

#70370 Do not emit TypeDefinitionDocuments to EnC deltas.
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs
Labels: Area-Interactive, untriaged

#70328 Collection expressions: prefer ReadOnlySpan<T> over Span<T> in overload resolution
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged

#70264 Warn if collection expression to ref struct type incurs a heap allocation
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Errors/MessageProvider.cs
  src/Compilers/CSharp/Portable/Generated/ErrorFacts.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
Labels: Area-Compilers, untriaged

#70383 Suggest interfaces after generic type name
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ExplicitInterfaceTypeCompletionProviderTests.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceTypeCompletionProvider.cs
Labels: Area-IDE, Community, untriaged

#70343 Include project-id in sync'ed data to allow future calls to directly jump to that project.
  src/Workspaces/Core/Portable/Workspace/Solution/ChecksumCollection.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState_Checksum.cs
  src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs
  src/Workspaces/Remote/Core/AbstractAssetProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs
Labels: Area-IDE, untriaged

#70362 Ensure rValue receiver is properly captured if there is an await in call arguments
  src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/AbstractFlowPass.vb
  src/Compilers/VisualBasic/Portable/Analysis/IteratorAndAsyncAnalysis/IteratorAndAsyncCaptureWalker.vb
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenAsyncTests.vb
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenCallTests.vb
Labels: Area-Compilers, untriaged

#70346 Simplify checksum caching code.
  src/VisualStudio/Core/Test.Next/Remote/SerializationValidator.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Metadata.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ChecksumCollection.cs
  src/Workspaces/Core/Portable/Workspace/Solution/DocumentInfo.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectInfo.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState_Checksum.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionInfo.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState_Checksum.cs
  src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs
  src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentState_Checksum.cs
Labels: Area-IDE, untriaged

#70373 Simplify and improve performance of NameGenerator.EnsureUniqueness methods
  src/EditorFeatures/Test2/Diagnostics/ImplementInterface/ImplementInterfaceCrossLanguageTests.vb
  src/Workspaces/CoreTest/UtilityTest/NameGeneratorTests.cs
  src/Workspaces/CoreTest/WorkspaceTests/AdhocWorkspaceTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Utilities/NameGenerator.cs
Labels: Area-IDE, untriaged

#70384 Collection expressions - error when we can't emit good codegen for ImmutableArray
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged

#70371 Trying to fix integration tests
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicGoToDefinition.cs
Labels: Area-IDE, untriaged

#70385 Faster checksum syncing for documents.
  src/VisualStudio/Core/Test.Next/Remote/SerializationValidator.cs
  src/VisualStudio/Core/Test.Next/Remote/SnapshotSerializationTests.cs
  src/VisualStudio/Core/Test.Next/Services/AssetProviderTests.cs
  src/Workspaces/Core/Portable/Workspace/Solution/AssetHint.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ChecksumCollection.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ChecksumsAndIds.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState_Checksum.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState_Checksum.cs
  src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs
  src/Workspaces/CoreTestUtilities/Fakes/SimpleAssetSource.cs
  src/Workspaces/Remote/Core/AbstractAssetProvider.cs
  src/Workspaces/Remote/Core/ISolutionAssetProvider.cs
  src/Workspaces/Remote/Core/SolutionAssetProvider.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.Scope.cs
  src/Workspaces/Remote/ServiceHub/Host/AssetProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/ChecksumSynchronizer.cs
  src/Workspaces/Remote/ServiceHub/Host/IAssetSource.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs
  src/Workspaces/Remote/ServiceHub/Host/SolutionAssetSource.cs
  src/Workspaces/Remote/ServiceHub/Host/TestUtils.cs
Labels: Area-IDE, untriaged

#70367 Update Multiple Inheritance Lookup Ambuguity.md
  docs/compilers/CSharp/Multiple Inheritance Lookup Ambuguity.md
Labels: Area-Compilers, Community, untriaged

#70121 Document deviations from the C# standard
  docs/compilers/CSharp/Deviations from Standard.md
Labels: Area-Compilers, Documentation, untriaged

#70288 Collection expressions: synthesized list types should implement ICollection and IList
  src/Compilers/CSharp/Portable/Symbols/Synthesized/ReadOnlyListType/SynthesizedReadOnlyListTypeSymbol.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
Labels: Area-Compilers, untriaged, New Feature - Collection Expressions

#70365 Deprecate API and add NFW telemetry for it
  src/Compilers/CSharp/Portable/Syntax/CSharpSyntaxNode.cs
  src/Compilers/CSharp/Test/Syntax/Syntax/SerializationTests.cs
  src/Compilers/Core/Portable/InternalUtilities/FatalError.cs
  src/Compilers/Core/Portable/Syntax/SyntaxNode.cs
  src/Compilers/Server/VBCSCompiler/BuildServerController.cs
  src/Compilers/Shared/Csc.cs
  src/Compilers/Shared/Vbc.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestSource.cs
  src/Compilers/Test/Utilities/VisualBasic/BasicTestSource.vb
  src/Compilers/VisualBasic/Portable/Syntax/VisualBasicSyntaxNode.vb
  src/Compilers/VisualBasic/Test/Syntax/Syntax/SerializationTests.vb
  src/ExpressionEvaluator/Core/Source/ResultProvider/ResultProvider.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Logging/RoslynLogger.cs
  src/Interactive/HostProcess/InteractiveHostEntryPoint.cs
  src/Tools/IdeCoreBenchmarks/SerializationBenchmarks.cs
  src/VisualStudio/Core/Def/Interactive/VsInteractiveWindowPackage.cs
  src/VisualStudio/Core/Def/Watson/FaultReporter.cs
  src/Workspaces/CoreTest/SerializationTests.cs
Labels: Area-Compilers, untriaged

#70347 Add extra validation for Compilations having the expected trees
  src/Features/LanguageServer/Protocol/Features/Options/WorkspaceConfigurationOptionsStorage.cs
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
  src/Workspaces/Core/Portable/Workspace/IWorkspaceConfigurationService.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
Labels: Area-IDE, untriaged, OnDeckForServicing

#70109 Restore "Do source-generation only in our OOP process"
  eng/targets/Services.props
  src/Compilers/Test/Core/SourceGeneration/TestGenerators.cs
  src/Features/LanguageServer/Protocol/Features/Options/WorkspaceConfigurationOptionsStorage.cs
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/DiagnosticItem/SourceGeneratorItem.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/Workspaces/Core/Portable/SourceGeneration/IRemoteSourceGenerationService.cs
  src/Workspaces/Core/Portable/SourceGeneratorTelemetry/SourceGeneratorTelemetryCollectorWorkspaceService.cs
  src/Workspaces/Core/Portable/Workspace/IWorkspaceConfigurationService.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker_Generators.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratedDocumentIdentity.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratedDocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratorIdentity.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTestHelpers.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemostHostClient.cs
  src/Workspaces/CoreTestUtilities/WorkspaceTestUtilities.cs
  src/Workspaces/Remote/Core/RemoteHostAssetSerialization.cs
  src/Workspaces/Remote/Core/RemoteWorkspacesResources.resx
  src/Workspaces/Remote/Core/ServiceDescriptors.cs
  src/Workspaces/Remote/Core/SolutionAssetProvider.cs
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.cs.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.de.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.es.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.fr.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.it.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ja.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ko.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.pl.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.pt-BR.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ru.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.tr.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.zh-Hans.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.zh-Hant.xlf
  src/Workspaces/Remote/ServiceHub/Services/SourceGeneration/RemoteSourceGenerationService.cs
Labels: Area-IDE, untriaged

#70322 File types need to account for pathmap
  src/Compilers/CSharp/Portable/Binder/BinderFactory.cs
  src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.IncludeElementExpander.cs
  src/Compilers/CSharp/Portable/Symbols/FileIdentifier.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedSimpleProgramEntryPointSymbol.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/FileModifierTests.cs
  src/Compilers/Core/CommandLine/BuildProtocol.cs
  src/Compilers/Core/Portable/Syntax/SyntaxTree.cs
  src/Tools/BuildValidator/DemoLogger.cs
  src/Tools/TestDiscoveryWorker/Program.cs
Labels: Area-Compilers, untriaged

#70386 Add F1 help for `NameOf` keyword in Visual Basic
  src/VisualStudio/Core/Test/Help/HelpTests.vb
  src/VisualStudio/VisualBasic/Impl/Help/VisualBasicHelpContextService.Visitor.vb
Labels: Area-IDE, Community, untriaged

#70405 Fix 'Color Color' completion logic
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ExpressionSyntaxExtensions.cs
Labels: Area-IDE, untriaged

#70407 Fix lsp didChange processing.
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/LanguageServer/Protocol/Handler/DocumentChanges/DidChangeHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/DocumentChanges/DocumentChangesTests.cs
Labels: Area-IDE, untriaged

#70395 Collection expressions: prefer ReadOnlySpan<T> over Span<T> in overload resolution (#70328)
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged, New Feature - Collection Expressions

#70411 (17.8) Collection expressions - error when we can't emit good codegen for ImmutableArray
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged

#70304 Add support to the LSIF generator for document symbols
  src/Features/LanguageServer/Protocol/Microsoft.CodeAnalysis.LanguageServer.Protocol.csproj
  src/Features/Lsif/Generator/Generator.cs
  src/Features/Lsif/Generator/Graph/DefinitionRangeTag.cs
  src/Features/Lsif/Generator/Graph/DocumentSymbolResult.cs
  src/Features/Lsif/Generator/Graph/Range.cs
  src/Features/Lsif/Generator/Graph/RangeBasedDocumentSymbol.cs
  src/Features/Lsif/Generator/Graph/RangeTag.cs
  src/Features/Lsif/GeneratorTest/DocumentSymbolTests.vb
  src/Features/Lsif/GeneratorTest/OutputFormatTests.vb
  src/Features/Lsif/GeneratorTest/Utilities/TestLsifOutput.vb
Labels: Area-IDE

#70416 Fix classification layering
  src/EditorFeatures/Core.Wpf/Classification/ClassificationTypeFormatDefinitions.cs
  src/EditorFeatures/Core/Classification/Syntactic/SyntacticClassificationTaggerProvider.TagComputer.cs
  src/EditorFeatures/Core/Shared/Utilities/AbstractClassificationTypeMap.cs
  src/EditorFeatures/Core/Shared/Utilities/ClassificationTypeMap.cs
  src/EditorFeatures/Core/Shared/Utilities/SyntacticClassificationTypeMap.cs
Labels: Area-IDE, untriaged

#70432 Minor cleanup in extract-method code.
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodBase.cs
  src/EditorFeatures/Core/ExtractMethod/ExtractMethodCommandHandler.cs
  src/EditorFeatures/VisualBasicTest/ExtractMethod/ExtractMethodTests.vb
  src/Features/Core/Portable/CodeRefactorings/ExtractMethod/AbstractExtractMethodCodeRefactoringProvider.cs
  src/Features/Core/Portable/ExtractMethod/ExtractMethodResult.cs
  src/Features/Core/Portable/ExtractMethod/FailedExtractMethodResult.cs
  src/Features/Core/Portable/ExtractMethod/OperationStatus.cs
  src/Features/Core/Portable/ExtractMethod/SimpleExtractMethodResult.cs
Labels: Area-IDE, untriaged

#70435 Update breaking change docs
  docs/Breaking API Changes.md
Labels: Area-IDE, untriaged

#70440 Slight improvement to refactoring preview performance for InlineTemporaryCodeRefactoringProvider
  src/Features/CSharp/Portable/CodeRefactorings/InlineTemporary/InlineTemporaryCodeRefactoringProvider.cs
Labels: Area-IDE, untriaged

#69655 Rename Razor compiler assemblies
  src/Features/Core/Portable/Workspace/CompileTimeSolutionProvider.cs
  src/Tools/ExternalAccess/RazorCompiler/Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.csproj
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioProjectTests/AnalyzerReferenceTests.vb
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs
Labels: Area-IDE, untriaged

#70443 Refactor how Extract Method returns results.
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodBase.cs
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs
  src/EditorFeatures/Core/ExtractMethod/ExtractMethodCommandHandler.cs
  src/EditorFeatures/Core/ExtractMethod/ExtractMethodPresentationOptionsStorage.cs
  src/EditorFeatures/VisualBasicTest/ExtractMethod/ExtractMethodTests.vb
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.ExpressionResult.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.StatementResult.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionValidator.cs
  src/Features/CSharpTest/ExtractMethod/ExtractLocalFunctionTests.cs
  src/Features/CSharpTest/ExtractMethod/ExtractMethodTests.cs
  src/Features/Core/Portable/ExtractMethod/Enums.cs
  src/Features/Core/Portable/ExtractMethod/Extensions.cs
  src/Features/Core/Portable/ExtractMethod/ExtractMethodResult.cs
  src/Features/Core/Portable/ExtractMethod/InsertionPoint.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.TriviaResult.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.cs
  src/Features/Core/Portable/ExtractMethod/OperationStatus.cs
  src/Features/Core/Portable/ExtractMethod/OperationStatus_Statics.cs
  src/Features/Core/Portable/ExtractMethod/SelectionResult.cs
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicSelectionResult.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicSelectionValidator.vb
Labels: Area-IDE, untriaged

#70446 Ensure the VSCode server process runs on non-preview runtime
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Microsoft.CodeAnalysis.LanguageServer.csproj
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Program.cs
  src/Workspaces/Core/MSBuild.BuildHost/Program.cs
Labels: Area-IDE, untriaged

#70157 Bump MSBuild.StructuredLogger package version
  eng/Versions.props
  src/Features/Lsif/Generator/Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.csproj
Labels: Area-Infrastructure

#70425 Handle missing ISimplificationService implementation for non-C#/VB languages
  src/Features/LanguageServer/ProtocolUnitTests/VSTypeScriptHandlerTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Simplification/SimplifierOptions.cs
Labels: Area-IDE, Tenet-Reliability, untriaged

#70399 Add refactoring to convert a primary-constructor-parameter to a normal constructor.
  src/Analyzers/CSharp/Analyzers/UsePrimaryConstructor/CSharpUsePrimaryConstructorDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/UsePrimaryConstructor/CSharpUsePrimaryConstructorCodeFixProvider.cs
  src/Features/CSharp/Portable/CSharpFeaturesResources.resx
  src/Features/CSharp/Portable/ConvertPrimaryToRegularConstructor/ConvertPrimaryToRegularConstructorCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/ConvertPrimaryToRegularConstructor/ConvertPrimaryToRegularConstructorCodeRefactoringProvider_DocumentationComments.cs
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.cs.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.de.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.es.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.fr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.it.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ja.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ko.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pl.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.pt-BR.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ru.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.tr.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hans.xlf
  src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.zh-Hant.xlf
  src/Features/CSharpTest/ConvertPrimaryToRegularConstructor/ConvertPrimaryToRegularConstructorTests.cs
  src/Features/Core/Portable/CodeRefactorings/PredefinedCodeRefactoringProviderNames.cs
  src/Features/Core/Portable/ConvertAutoPropertyToFullProperty/AbstractConvertAutoPropertyToFullPropertyCodeRefactoringProvider.cs
Labels: Area-IDE, untriaged

#70451 Revert "[main] Update dependencies from dotnet/arcade"
  eng/Version.Details.xml
  eng/common/build.sh
  eng/common/cross/build-rootfs.sh
  eng/common/cross/riscv64/tizen/tizen.patch
  eng/common/cross/tizen-build-rootfs.sh
  eng/common/cross/tizen-fetch.sh
  eng/common/cross/toolchain.cmake
  eng/common/post-build/check-channel-consistency.ps1
  eng/common/sdk-task.ps1
  eng/common/templates/job/job.yml
  eng/common/tools.ps1
  global.json
Labels: Area-Infrastructure, untriaged

#70412 Clear 'run code analysis' results when a build completes
  src/Features/Core/Portable/Diagnostics/CodeAnalysisDiagnosticAnalyzerService.cs
  src/Features/Core/Portable/Diagnostics/ICodeAnalysisDiagnosticAnalyzerService.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.cs
Labels: Area-IDE, untriaged

#70262 Improve completion in the context of pattern expressions
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs
Labels: Area-IDE, Community, untriaged

#70448 Filter completion list only with text before cursor
  src/Features/LanguageServer/Protocol/Handler/Completion/AbstractLspCompletionResultCreationService.cs
  src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionFeaturesTests.cs
Labels: Area-IDE, untriaged

#70444 Fix TriggerOnTyping to not block explicit invoking completion
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/CompletionSource.cs
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/Helpers.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Features/Core/Portable/Completion/CompletionService.cs
  src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandler.cs
Labels: Area-IDE, untriaged

#70442 Update config file after 17.9 branch is created
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#70464 Fix incorrect contract in VB EnC analyzer
  src/EditorFeatures/VisualBasicTest/EditAndContinue/StatementEditingTests.vb
  src/EditorFeatures/VisualBasicTest/EditAndContinue/StatementMatchingTests.vb
  src/Features/VisualBasic/Portable/EditAndContinue/VisualBasicEditAndContinueAnalyzer.vb
Labels: Area-Interactive, untriaged

#70417 Collection expressions: spread elements are not expressions
  src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged

#70476 Fix issue where primary constructors were not being grouped across TFMs in the results window
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder.cs
Labels: Area-IDE, untriaged

#70199 Optimize `T? ?? <expr>` to `T.GetValueOrDefault(<expr>)` for a side-effectless `<expr>` where `T?` is a nullable value type
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_NullCoalescingOperator.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOperators.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenShortCircuitOperatorTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/Portable/SpecialMember.cs
  src/Compilers/Core/Portable/SpecialMembers.cs
  src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb
  src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_ConditionalExpressions.vb
  src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_LateBindingHelpers.vb
  src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_NullableHelpers.vb
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTests.vb
  src/Compilers/VisualBasic/Test/Semantic/Semantics/ConditionalAccessTests.vb
Labels: Area-Compilers, Community, untriaged

#70466 Front load extract-method syntax and semantic checks.
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodBase.cs
  src/EditorFeatures/Core/ExtractMethod/ExtractMethodCommandHandler.cs
  src/EditorFeatures/Core/ExtractMethod/ExtractMethodPresentationOptionsStorage.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.Analyzer.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.CallSiteContainerRewriter.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.ExpressionCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.MultipleStatementsCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.SingleStatementCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.cs
  src/Features/CSharpTest/ExtractMethod/ExtractLocalFunctionTests.cs
  src/Features/Core/Portable/CodeRefactorings/ExtractMethod/AbstractExtractMethodCodeRefactoringProvider.cs
  src/Features/Core/Portable/ExtractMethod/ExtractMethodResult.cs
  src/Features/Core/Portable/ExtractMethod/FailedExtractMethodResult.cs
  src/Features/Core/Portable/ExtractMethod/InsertionPoint.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.AnalyzerResult.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.TriviaResult.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.VariableInfo.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.VariableSymbol.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.cs
  src/Features/Core/Portable/ExtractMethod/SelectionResult.cs
  src/Features/Core/Portable/ExtractMethod/SelectionValidator.NullSelectionResult.cs
  src/Features/Core/Portable/ExtractMethod/SimpleExtractMethodResult.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.Analyzer.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.ExpressionCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.MultipleStatementsCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.SingleStatementCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicSelectionResult.vb
Labels: Area-IDE, untriaged

#70477 Defer extract method mutation computation till the point the code action is invoked.
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodBase.cs
  src/EditorFeatures/Core/ExtractMethod/ExtractMethodCommandHandler.cs
  src/EditorFeatures/VisualBasicTest/ExtractMethod/ExtractMethodTests.vb
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.ExpressionCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.MultipleStatementsCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.SingleStatementCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.cs
  src/Features/Core/Portable/CodeRefactorings/ExtractMethod/AbstractExtractMethodCodeRefactoringProvider.cs
  src/Features/Core/Portable/ExtractMethod/AbstractExtractMethodService.cs
  src/Features/Core/Portable/ExtractMethod/ExtractMethodResult.cs
  src/Features/Core/Portable/ExtractMethod/FailedExtractMethodResult.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.GeneratedCode.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.cs
  src/Features/Core/Portable/ExtractMethod/SimpleExtractMethodResult.cs
  src/Features/LanguageServer/Protocol/Features/Options/ExtractMethodOptionsStorage.cs
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.ExpressionCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.MultipleStatementsCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.SingleStatementCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.vb
  src/Workspaces/Core/Portable/ExtractMethod/ExtractMethodOptions.cs
  src/Workspaces/CoreTestUtilities/VBOptionsFactory.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/CodeActionOptions.cs
Labels: Area-IDE, untriaged

#70480 Tiny cleanup in SyntaxGenerator.
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
Labels: Area-IDE, untriaged

#70402 Mark diagnostics as being 'live' or not in LSP
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/AbstractDocumentDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/AbstractProjectDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/AbstractWorkspaceDocumentDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/DocumentDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/IDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/NonLocalDocumentDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/TaskListDiagnosticSource.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DocumentPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Public/PublicDocumentPullDiagnosticsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Public/PublicWorkspacePullDiagnosticsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
Labels: Area-IDE, untriaged

#70492 Shorten the namedpipe used to connect with C# extension
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Program.cs
Labels: Area-IDE, untriaged

#70485 Add IVT to a future unified razor test project
  src/Tools/ExternalAccess/RazorCompiler/Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.csproj
Labels: Area-Infrastructure, untriaged

#70397 Validate diagnostic ID in Experimental attribute
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEAssemblySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/ExperimentalAttributeTests.cs
  src/Compilers/Core/Portable/MetadataReader/PEModule.cs
  src/Compilers/VisualBasic/Portable/Errors/ErrorFacts.vb
  src/Compilers/VisualBasic/Portable/Errors/Errors.vb
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEAssemblySymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEModuleSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Symbol_Attributes.vb
  src/Compilers/VisualBasic/Portable/VBResources.resx
  src/Compilers/VisualBasic/Portable/xlf/VBResources.cs.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.de.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.es.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.fr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.it.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ja.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ko.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pl.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pt-BR.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ru.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.tr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hans.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hant.xlf
  src/Compilers/VisualBasic/Test/CommandLine/CommandLineTests.vb
  src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests.vb
Labels: Area-Compilers, untriaged

#70396 Allow invisible editor support to handle open aspx files.
  src/VisualStudio/Core/Def/ProjectSystem/InvisibleEditor.cs
Labels: Area-IDE, untriaged

#70510 Publish `EA.EditorConfigGenerator`
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#70151 Handle generic types as parameters of attributes in `MetadataDecoder`
  src/Compilers/CSharp/Portable/Symbols/ArrayTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AssemblySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Attributes/PEAttributeData.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEAssemblySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/MissingAssemblySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/ParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingAssemblySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceModuleSymbol.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MockAssemblySymbol.cs
  src/Compilers/Core/Portable/MetadataReader/MetadataDecoder.cs
  src/Compilers/Core/Portable/MetadataReader/MetadataTypeCodeExtensions.cs
  src/Compilers/Core/Portable/MetadataReader/PEModule.cs
  src/Compilers/Core/Portable/Symbols/Attributes/CommonAssemblyWellKnownAttributeData.cs
  src/Compilers/Core/Portable/Symbols/IArrayTypeSymbolInternal.cs
  src/Compilers/Core/Portable/Symbols/IMethodSymbolInternal.cs
  src/Compilers/Core/Portable/Symbols/IParameterSymbolInternal.cs
  src/Compilers/Test/Utilities/VisualBasic/Extensions.vb
  src/Compilers/Test/Utilities/VisualBasic/MockSymbols.vb
  src/Compilers/VisualBasic/Portable/Symbols/ArrayTypeSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/AssemblySymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Attributes/AttributeData.vb
  src/Compilers/VisualBasic/Portable/Symbols/Attributes/PEAttributeData.vb
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEAssemblySymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/MethodSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/MissingAssemblySymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/ParameterSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Retargeting/RetargetingAssemblySymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceAssemblySymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceModuleSymbol.vb
  src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests.vb
  src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/ExpressionCompilerTests.vb
Labels: Area-Compilers, untriaged

#70352 Utilize ConstantValueOne while emitting conditionals
  src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs
  src/Compilers/Core/CodeAnalysisTest/CorLibTypesTests.cs
  src/Compilers/Core/Portable/ConstantValue.cs
  src/Compilers/Core/Portable/ConstantValueSpecialized.cs
  src/Compilers/VisualBasic/Portable/CodeGen/EmitExpression.vb
Labels: Area-Compilers, Community, untriaged

#70512 Skip VerifyOverloadsUpdated integration tests
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpRename.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicRename.cs
Labels: Area-IDE, untriaged

#70420 Connect inline rename UI to editor smart rename session
  eng/Versions.props
  src/EditorFeatures/Core.Wpf/EditorFeaturesWpfResources.resx
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyoutViewModel.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Dashboard/RenameDashboard.xaml.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/InlineRenameAdornmentManager.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/InlineRenameAdornmentProvider.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameControl.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameControl.xaml.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameViewModel.cs
  src/EditorFeatures/Core.Wpf/Microsoft.CodeAnalysis.EditorFeatures.Wpf.csproj
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.cs.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.de.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.es.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.fr.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.it.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ja.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ko.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.pl.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.pt-BR.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ru.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.tr.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.zh-Hans.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.zh-Hant.xlf
  src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests.vb
  src/EditorFeatures/Test2/Rename/RenameViewModelTests.vb
  src/VisualStudio/CodeLens/ReferenceCodeLensProvider.cs
  src/Workspaces/Core/Portable/Shared/TestHooks/FeatureAttribute.cs
Labels: Area-IDE, untriaged

#70541 Cherry pick: Fix classification layering
  src/EditorFeatures/Core.Wpf/Classification/ClassificationTypeFormatDefinitions.cs
  src/EditorFeatures/Core/Classification/Syntactic/SyntacticClassificationTaggerProvider.TagComputer.cs
  src/EditorFeatures/Core/Shared/Utilities/AbstractClassificationTypeMap.cs
  src/EditorFeatures/Core/Shared/Utilities/ClassificationTypeMap.cs
  src/EditorFeatures/Core/Shared/Utilities/SyntacticClassificationTypeMap.cs
Labels: Area-IDE, untriaged

#70472 Ensure evaluation results are included in binlog
  src/Workspaces/Core/MSBuild.BuildHost/Build/ProjectBuildManager.cs
  src/Workspaces/MSBuildTest/NetCoreTests.cs
  src/Workspaces/MSBuildTest/Utilities/TestMSBuildLogger.cs
  src/Workspaces/MSBuildTest/VisualStudioMSBuildWorkspaceTests.cs
Labels: Area-IDE, untriaged

#70532 Attempt to work around GitHub Copilot breaking integration tests
  src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InProcComponent.cs
Labels: Area-IDE, untriaged

#70467 Ensure diagnostics are logged before proceeding with further project loading
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs
Labels: Area-IDE, untriaged

#70496 Skip elements with false conditions during evaluation
  src/Workspaces/Core/MSBuild.BuildHost/Build/ProjectBuildManager.cs
  src/Workspaces/MSBuildTest/VisualStudioMSBuildWorkspaceTests.cs
Labels: Area-IDE, untriaged

#70247 Fix character offset off-by-one error in enhanced line directives
  src/Compilers/CSharp/Portable/Syntax/CSharpLineDirectiveMap.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/LineSpanDirectiveTests.cs
  src/Compilers/Core/Portable/Syntax/LineDirectiveMap.LineMappingEntry.cs
  src/Compilers/Core/Portable/Syntax/LineDirectiveMap.cs
Labels: Area-Compilers, untriaged

#70543 Fix flakeyness in extract method test
  src/EditorFeatures/CSharpTest/ExtractMethod/MiscTests.cs
Labels: Area-IDE, untriaged

#70550 Ensure we cache both the last semantic and last embedded-lang classification for a document
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassification/RemoteSemanticClassificationService.Caching.cs
Labels: Area-IDE, untriaged

#70561 Apply the GitHub Copilot workaround to new-framework integration tests
  src/VisualStudio/IntegrationTest/New.IntegrationTests/AbstractIntegrationTest.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/WorkaroundsInProcess.cs
Labels: Area-IDE, untriaged

#70527 Resolve reference paths to absolute paths
  src/Compilers/Core/Portable/CommandLine/CommonCompiler.LoggingMetadataFileReferenceResolver.cs
  src/Compilers/Core/Portable/FileSystem/RelativePathResolver.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/WorkspaceProjectFactoryService.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/LanguageServerResources.resx
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.cs.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.de.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.es.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.fr.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.it.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.ja.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.ko.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.pl.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.pt-BR.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.ru.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.tr.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.zh-Hans.xlf
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.zh-Hant.xlf
  src/Scripting/Core/Hosting/Resolvers/RuntimeMetadataReferenceResolver.cs
  src/Scripting/Core/ScriptMetadataResolver.cs
Labels: Area-IDE, untriaged

#70571 Workaround issue #70570
  .editorconfig
  eng/config/globalconfigs/Common.globalconfig
Labels: Area-Analyzers, untriaged

#70563 Fix regression in definite assignment analysis for out parameters in presence of local functions.
  src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs
  src/Compilers/CSharp/Test/Emit2/FlowAnalysis/FlowTests.cs
  src/Compilers/CSharp/Test/Emit2/FlowAnalysis/LocalFunctions.cs
  src/Compilers/CSharp/Test/Emit2/FlowAnalysis/RegionAnalysisTests.cs
Labels: Area-Compilers, untriaged

#70567 Modify BKTree.Lookup to pass the threshold to GetEditDistance when there will not be a need for the actual edit distance
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/BKTree.cs
Labels: Area-IDE, untriaged

#70558 Handle authorization exceptions when reading files
  src/Compilers/Core/Portable/FileSystem/FileUtilities.cs
  src/Workspaces/Core/Portable/Workspace/Solution/FileTextLoader.cs
Labels: Area-Compilers, untriaged

#70583 Disable flaky tests
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpIntelliSense.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpReplIntellisense.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpSignatureHelp.cs
Labels: Area-Infrastructure, untriaged

#70556 Ensure errors are reported when compiler is unable to emit a required attribute.
  src/Compilers/CSharp/Portable/Emitter/NoPia/EmbeddedTypesManager.cs
  src/Compilers/CSharp/Portable/Symbols/Attributes/AttributeData.cs
  src/Compilers/CSharp/Portable/Symbols/Attributes/PEAttributeData.cs
  src/Compilers/CSharp/Portable/Symbols/Attributes/RetargetingAttributeData.cs
  src/Compilers/CSharp/Portable/Symbols/Attributes/SourceAttributeData.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SynthesizedAttributeData.cs
  src/Compilers/CSharp/Test/Emit/Emit/NoPiaEmbedTypes.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_Assembly.cs
  src/Compilers/Core/Portable/Emit/NoPia/CommonEmbeddedMember.cs
  src/Compilers/Core/Portable/Emit/NoPia/CommonEmbeddedMethod.cs
  src/Compilers/Core/Portable/Emit/NoPia/CommonEmbeddedParameter.cs
  src/Compilers/Core/Portable/Emit/NoPia/CommonEmbeddedType.cs
  src/Compilers/Core/Portable/Emit/NoPia/EmbeddedTypesManager.cs
  src/Compilers/Core/Portable/Symbols/CommonAttributeDataExtensions.cs
  src/Compilers/VisualBasic/Portable/Emit/NoPia/EmbeddedTypesManager.vb
  src/Compilers/VisualBasic/Portable/Symbols/Attributes/AttributeData.vb
  src/Compilers/VisualBasic/Portable/Symbols/Attributes/PEAttributeData.vb
  src/Compilers/VisualBasic/Portable/Symbols/Attributes/RetargetingAttributeData.vb
  src/Compilers/VisualBasic/Portable/Symbols/Attributes/SourceAttributeData.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceAssemblySymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/SynthesizedSymbols/SynthesizedAttributeData.vb
  src/Compilers/VisualBasic/Test/Emit/Attributes/AssemblyAttributes.vb
  src/Compilers/VisualBasic/Test/Emit/Emit/NoPiaEmbedTypes.vb
Labels: Area-Compilers, untriaged

#70589 Disable flaky test
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpInteractiveCommands.cs
Labels: Area-Interactive, untriaged

#70568 Bump Razor to 7.0.0-preview.23525.7
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#70539 Fix a couple of bugs found in "use collection expression"
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForArrayDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/UseCollectionExpressionHelpers.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpUseCollectionExpressionForArrayCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs
Labels: Area-IDE, untriaged

#70581 Make struct type into a record.
  src/Features/Core/Portable/DocumentIdSpan.cs
Labels: Area-IDE, untriaged

#70497 Add support for \e escape sequences in c# strings and characters
  docs/Language Feature Status.md
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Parser/Lexer_StringLiteral.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Syntax/LexicalAndXml/LexicalErrorTests.cs
  src/Compilers/CSharp/Test/Syntax/LexicalAndXml/LexicalTests.cs
  src/Compilers/CSharp/Test/Syntax/LexicalAndXml/RawStringLiteralLexingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/RawInterpolatedStringLiteralCompilingTests.cs
  src/Workspaces/CSharpTest/EmbeddedLanguages/VirtualChars/CSharpVirtualCharServiceTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/EmbeddedLanguages/VirtualChars/CSharpVirtualCharService.cs
Labels: Area-Compilers, untriaged

#70517 Run analyzer consistency checks on .NET Core
  .gitignore
  src/Compilers/Core/CodeAnalysisTest/Analyzers/AnalyzerFileReferenceAppDomainTests.cs
  src/Compilers/Core/CodeAnalysisTest/Analyzers/AnalyzerFileReferenceTests.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.Core.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.Desktop.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.cs
  src/Compilers/Server/VBCSCompiler/AnalyzerConsistencyChecker.cs
  src/Compilers/Server/VBCSCompiler/CompilerRequestHandler.cs
  src/Compilers/Server/VBCSCompilerTests/AnalyzerConsistencyCheckerTests.cs
  src/Compilers/Server/VBCSCompilerTests/TouchedFileLoggingTests.cs
Labels: Area-Analyzers, untriaged

#70522 Update the approach we use to layer classifications
  src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs
  src/EditorFeatures/CSharpTest/Classification/SyntacticTaggerTests.cs
  src/EditorFeatures/CSharpTest/Classification/TotalClassifierTests.cs
  src/EditorFeatures/Core/Classification/Semantic/EmbeddedLanguageClassificationViewTaggerProvider.cs
  src/EditorFeatures/Core/Classification/Semantic/SemanticClassificationViewTaggerProvider.cs
  src/EditorFeatures/Core/Classification/Syntactic/SyntacticClassificationTaggerProvider.TagComputer.cs
  src/EditorFeatures/Core/Classification/Syntactic/SyntacticClassificationTaggerProvider.Tagger.cs
  src/EditorFeatures/Core/Classification/Syntactic/SyntacticClassificationTaggerProvider.cs
  src/EditorFeatures/Core/Classification/TotalClassificationTaggerProvider.cs
  src/EditorFeatures/Core/Diagnostics/AbstractDiagnosticsTaggerProvider.cs
  src/EditorFeatures/Core/Shared/Utilities/AbstractClassificationTypeMap.cs
  src/EditorFeatures/Core/Shared/Utilities/ClassificationTypeMap.cs
  src/EditorFeatures/Core/Shared/Utilities/SyntacticClassificationTypeMap.cs
  src/EditorFeatures/Core/Tagging/AggregateTagger.cs
  src/EditorFeatures/Core/Tagging/AsynchronousViewportTaggerProvider.cs
  src/EditorFeatures/Test2/Classification/ClassificationTests.vb
  src/Features/CSharp/Portable/ConvertToRawString/ConvertInterpolatedStringToRawStringCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/ConvertToRawString/ConvertRegularStringToRawStringCodeRefactoringProvider.cs
  src/Workspaces/Core/Portable/Classification/Classifier.cs
  src/Workspaces/Core/Portable/Classification/ClassifierHelper.cs
Labels: Area-IDE, untriaged

#70531 Add external access code action operation for renaming after code actions
  src/EditorFeatures/Core/CodeActions/CodeActionEditHandlerService.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/VSTypeScriptRenameOperationProvider.cs
  src/Features/Core/Portable/Common/StartInlineRenameSessionOperation.cs
Labels: Area-IDE, Community, untriaged

#70593 Revert "[main] Update dependencies from dotnet/arcade (#70482)"
  azure-pipelines-official.yml
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/build.sh
  eng/common/cross/build-rootfs.sh
  eng/common/cross/riscv64/tizen/tizen.patch
  eng/common/cross/tizen-build-rootfs.sh
  eng/common/cross/tizen-fetch.sh
  eng/common/cross/toolchain.cmake
  eng/common/post-build/check-channel-consistency.ps1
  eng/common/sdk-task.ps1
  eng/common/templates/job/job.yml
  eng/common/tools.ps1
  eng/common/tools.sh
  global.json
Labels: Area-Infrastructure, untriaged

#70468 Add mapCode handler and ExternalAccess.Copilot
  Roslyn.sln
  eng/config/PublishData.json
  eng/targets/Settings.props
  src/EditorFeatures/Core/LanguageServer/RazorInProcLanguageClient.cs
  src/Features/Core/Portable/MapCode/IMapCodeService.cs
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/Features/LanguageServer/Protocol/Handler/MapCode/MapCodeHandler.cs
  src/Features/LanguageServer/Protocol/Handler/MapCode/MapCodeParams.cs
  src/Features/LanguageServer/ProtocolUnitTests/MapCode/MapCodeTests.cs
  src/NuGet/VisualStudio/VS.ExternalAPIs.Roslyn.Package.csproj
  src/Tools/ExternalAccess/.editorconfig
  src/Tools/ExternalAccess/Copilot/CodeMapper/ICSharpCopilotMapCodeService.cs
  src/Tools/ExternalAccess/Copilot/Internal/CodeMapper/CopilotCSharpMapCodeService.cs
  src/Tools/ExternalAccess/Copilot/InternalAPI.Shipped.txt
  src/Tools/ExternalAccess/Copilot/InternalAPI.Unshipped.txt
  src/Tools/ExternalAccess/Copilot/Microsoft.CodeAnalysis.ExternalAccess.Copilot.csproj
  src/Tools/ExternalAccess/Copilot/PublicAPI.Shipped.txt
  src/Tools/ExternalAccess/Copilot/PublicAPI.Unshipped.txt
  src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj
  src/VisualStudio/Setup/source.extension.vsixmanifest
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
Labels: Area-IDE, untriaged

#70584 Remove usage of CWT in syntactic classifier
  src/EditorFeatures/CSharpTest/Classification/SyntacticTaggerTests.cs
  src/EditorFeatures/Core/Classification/Syntactic/SyntacticClassificationTaggerProvider.TagComputer.cs
  src/EditorFeatures/Core/Classification/Syntactic/SyntacticClassificationTaggerProvider.cs
Labels: Area-IDE, untriaged

#70602 Watch project.assets.json files for nuget restore
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/Constants/PropertyNames.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFileInfo.cs
Labels: Area-IDE, untriaged

#70611 Fix binary compat break with typescript
  src/EditorFeatures/Core/Shared/Utilities/ClassificationTypeMap.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpAutomaticBraceCompletion.cs
Labels: Area-IDE, untriaged
