Repository dotnet/roslyn, pull requests merged in 2023-03, with the labels that each got.

#64983 Removed "sealed" from base class
  src/EditorFeatures/CSharpTest/ExtractClass/ExtractClassTests.cs
  src/Features/Core/Portable/ExtractClass/ExtractClassWithDialogCodeAction.cs
Labels: Area-IDE

#67106 link isexternalinit to avoid errors in O# about missing reference
  src/Tools/ExternalAccess/OmniSharp/Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.csproj
Labels: Area-IDE

#67112 Use CallStackWindow icon for StackTrace Explorer menu button
  src/VisualStudio/Core/Def/Commands.vsct
Labels: Area-IDE

#66158 Fix extraction inside anonymous function
  src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractLocalFunctionTests.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CodeGeneration/CSharpCodeGenerationService.cs
Labels: Area-IDE

#67109 Address remaining PROTOTYPE comments
  src/Compilers/CSharp/Portable/Binder/Binder.CapturedParametersFinder.cs
  src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedPrimaryConstructor.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/RecordTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/RecordParsing.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/TopLevelStatementsParsingTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/ExpressionCompilerTests.cs
  src/ExpressionEvaluator/CSharp/Test/ResultProvider/FullNameTests.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
Labels: Area-Compilers, New Feature - Primary Constructors

#67100 Avoid delegate allocations in IExtensionManagerExtensions
  src/Workspaces/Core/Portable/ExtensionManager/IExtensionManagerExtensions.cs
Labels: Area-IDE

#67129 Make the go-to search result preview-window editable.
  src/VisualStudio/Core/Def/NavigateTo/RoslynSearchResultPreviewPanel.cs
Labels: Area-IDE

#66798 Implement legacy options provider for code actions in workspace layer
  src/EditorFeatures/Core/Options/LegacyGlobalOptionsWorkspaceService.cs
  src/EditorFeatures/Core/Options/TextBufferOptionProviders.cs
  src/EditorFeatures/TestUtilities/Formatting/AbstractNewDocumentFormattingServiceTests.cs
  src/Features/Core/Portable/Completion/Providers/AbstractMemberInsertingCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractImportCompletionProvider.cs
  src/Features/LanguageServer/Protocol/Features/Options/AddImportPlacementOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/CodeCleanupOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/CodeGenerationOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/DocumentFormattingOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/GlobalCodeActionOptionsProvider.cs
  src/Features/LanguageServer/Protocol/Features/Options/LineFormattingOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/NamingStyleOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/OrganizeImportsOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/SimplifierOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/SyntaxFormattingOptionsStorage.cs
  src/VisualStudio/Core/Def/Venus/ContainedLanguageCodeSupport.cs
  src/Workspaces/Core/Portable/CodeActions/CodeAction.cs
  src/Workspaces/Core/Portable/Options/ILegacyGlobalCleanCodeGenerationOptionsWorkspaceService.cs
  src/Workspaces/Core/Portable/Options/ILegacyGlobalOptionsWorkspaceService.cs
  src/Workspaces/Core/Portable/Options/LegacyGlobalCodeActionOptionsWorkspaceService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/AddImport/AddImportPlacementOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeCleanup/CodeCleanupOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeGeneration/CodeGenerationOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/SyntaxFormattingOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Simplification/SimplifierOptions.cs
Labels: Area-IDE

#66925 Clean with authority
  eng/build-utils.ps1
Labels: Area-Infrastructure

#67127 Add RequiredCapabilities to WatchHotReloadService.Update
  src/Features/Core/Portable/ExternalAccess/Watch/Api/WatchHotReloadService.cs
Labels: Area-IDE

#67128 Fix completion off of nullable lambda parameter
  src/Compilers/Core/Portable/Collections/ImmutableArrayExtensions.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs
  src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs
Labels: Area-IDE

#67083 Sort unimported items from System.* ahead of other unimported items
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs
Labels: Area-IDE

#67139 Update find-refs to find references to nint/nuint
  src/EditorFeatures/Test2/ReferenceHighlighting/CSharpReferenceHighlightingTests.vb
  src/Workspaces/Core/Portable/FindSymbols/Shared/AbstractSyntaxIndex_Persistence.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/PredefinedTypeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/SpecialTypeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/PredefinedType.cs
Labels: Area-IDE

#67138 Update patch version for 17.5.2 release
  eng/Versions.props
Labels: Area-Infrastructure

#67116 Do not access Workspace.CurrentSolution when cleaning up a code-action's operations.
  eng/config/BannedSymbols.txt
  src/EditorFeatures/Core.Wpf/Suggestions/FixAll/FixAllGetFixesService.cs
  src/EditorFeatures/Core.Wpf/Suggestions/FixAll/FixMultipleOccurrencesService.cs
  src/EditorFeatures/Core.Wpf/Suggestions/PreviewChanges/PreviewChangesCodeAction.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActions/SuggestedAction.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/AbstractCodeActionOrUserDiagnosticTest.cs
  src/EditorFeatures/DiagnosticsTestUtilities/Diagnostics/AbstractSuppressionAllCodeTests.cs
  src/EditorFeatures/DiagnosticsTestUtilities/Diagnostics/AbstractUserDiagnosticTest_GenerateTypeDialog.cs
  src/EditorFeatures/DiagnosticsTestUtilities/MoveToNamespace/AbstractMoveToNamespaceTests.cs
  src/EditorFeatures/DiagnosticsTestUtilities/MoveType/AbstractMoveTypeTest.cs
  src/EditorFeatures/Test/CodeFixes/CodeFixServiceTests.cs
  src/EditorFeatures/Test/CodeRefactorings/CodeRefactoringServiceTest.cs
  src/EditorFeatures/TestUtilities/Diagnostics/GenerateType/GenerateTypeTestState.cs
  src/EditorFeatures/TestUtilities/ExtractInterface/ExtractInterfaceTestState.cs
  src/Features/Core/Portable/AddConstructorParametersFromMembers/AddConstructorParametersFromMembersCodeRefactoringProvider.cs
  src/Features/Core/Portable/AddImport/CodeActions/InstallPackageAndAddImportCodeAction.cs
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionBatchFixAllProvider.cs
  src/Features/Core/Portable/CodeFixesAndRefactorings/IFixAllGetFixesService.cs
  src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs
  src/Features/Core/Portable/Common/DocumentNavigationOperation.cs
  src/Features/Core/Portable/GenerateConstructorFromMembers/AbstractGenerateConstructorFromMembersCodeRefactoringProvider.GenerateConstructorWithDialogCodeAction.cs
  src/Features/Core/Portable/GenerateConstructorFromMembers/AbstractGenerateConstructorFromMembersCodeRefactoringProvider.cs
  src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndHashWithDialogCodeAction.cs
  src/Features/Core/Portable/SyncNamespaces/AbstractSyncNamespacesService.cs
  src/Features/LanguageServer/Protocol/Features/CodeCleanup/AbstractCodeCleanupService.cs
  src/Features/LanguageServer/Protocol/Features/CodeFixes/CodeFixService.cs
  src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionResolveHandler.cs
  src/Tools/AnalyzerRunner/CodeRefactoringRunner.cs
  src/Workspaces/Core/Portable/CodeActions/CodeAction.cs
  src/Workspaces/Core/Portable/CodeActions/CodeActionWithOptions.cs
  src/Workspaces/Core/Portable/CodeActions/Operations/ApplyChangesOperation.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs
Labels: Area-IDE

#67132 Fix exception when the list only contains a suggestion mode item
  src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionTests.cs
Labels: Area-IDE, LSP

#67144 Improve completion results when dotting of lambda parameter
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationService.cs
  src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs
  src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationService.cs
  src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs
  src/Workspaces/VisualBasic/Portable/Recommendations/VisualBasicRecommendationService.vb
  src/Workspaces/VisualBasic/Portable/Recommendations/VisualBasicRecommendationServiceRunner.vb
Labels: Area-IDE

#67141 Fix some null annotations on IDynamicFileInfoProvider
  src/Tools/ExternalAccess/Razor/IRazorDynamicFileInfoProvider.cs
  src/Tools/ExternalAccess/Razor/InternalAPI.Unshipped.txt
  src/Tools/ExternalAccess/Razor/RazorDynamicFileInfoProviderWrapper.cs
  src/Workspaces/Core/Portable/Workspace/Host/SourceFiles/DynamicFileInfo.cs
  src/Workspaces/Core/Portable/Workspace/Host/SourceFiles/IDynamicFileInfoProvider.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.BatchingDocumentCollection.cs
Labels: Area-IDE

#67087 Thread cancellationToken instead of capturing it in delegates
  src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.cs
  src/Compilers/Core/CodeAnalysisTest/Diagnostics/DiagnosticLocalizationTests.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.AnalyzerDiagnosticReporter.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs
  src/Compilers/Test/Core/Diagnostics/CommonDiagnosticAnalyzers.cs
  src/EditorFeatures/Test/Diagnostics/DiagnosticAnalyzerServiceTests.cs
  src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/DiagnosticComputer.cs
Labels: Area-Analyzers, Area-Compilers

#67148 Update versions to 17.6-preview3
  eng/Versions.props
  eng/config/PublishData.json
Labels: Area-Infrastructure

#67156 Fix bootstrap build
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
Labels: Area-Compilers

#66919 Use implicit/explicit extension as syntax
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Generated/CSharp.Generated.g4
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Internal.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Main.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Syntax.Generated.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/Parser/SyntaxParser.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
  src/Compilers/CSharp/Portable/Syntax/SyntaxFactory.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxKindFacts.cs
  src/Compilers/CSharp/Test/Syntax/Generated/Syntax.Test.xml.Generated.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ExtensionParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/RoleParsingTests.cs
  src/Compilers/Test/Core/TestResource.resx
  src/EditorFeatures/CSharpTest/Diagnostics/DiagnosticAnalyzerDriver/DiagnosticAnalyzerDriverTests.cs
Labels: Area-Compilers

#67137 Update feature status of "Primary Constructors"
  docs/Language Feature Status.md
Labels: Area-Compilers

#66531 Fix property initialization issue in KeyValueLogMessage
  src/Workspaces/Core/Portable/Log/KeyValueLogMessage.cs
Labels: Area-IDE

#66886 Fix workspace pull diagnostics
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Public/PublicWorkspacePullDiagnosticHandlerFactory.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Public/PublicWorkspacePullDiagnosticsHandler.cs
  src/Features/LanguageServer/Protocol/Workspaces/LspWorkspaceManager.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/AbstractPullDiagnosticTestsBase.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
Labels: Area-IDE

#67147 Show preview window for sync namespace
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/SyncNamespaces/SyncNamespacesCommandHandler.cs
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
Labels: Area-IDE

#67055 Fix crash of type snippets after accessibility modifier
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpClassSnippetCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpInterfaceSnippetCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpStructSnippetCompletionProviderTests.cs
  src/Features/CSharp/Portable/Snippets/AbstractCSharpTypeSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpClassSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpInterfaceSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpStructSnippetProvider.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractTypeSnippetProvider.cs
Labels: Community

#67146 Support 'go to base' on a constructor symbol
  src/EditorFeatures/CSharp/GoToBase/CSharpGoToBaseService.cs
  src/EditorFeatures/Test2/GoToBase/CSharpGoToBaseTests.vb
  src/EditorFeatures/Test2/GoToBase/VisuaBasicGoToBaseTests.vb
  src/EditorFeatures/VisualBasic/GoToBase/VisualBasicGoToBaseService.vb
  src/Features/Core/Portable/GoToBase/AbstractGoToBaseService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Extensions/StatementSyntaxExtensions.vb
Labels: Area-IDE

#67142 Prevent LegacyGlobalOptionService from GC rooting PreviewWorkspace
  src/Compilers/Test/Core/ObjectReference.cs
  src/EditorFeatures/Test/Preview/PreviewWorkspaceTests.cs
  src/Workspaces/Core/Portable/Options/LegacyWorkspaceOptionService.cs
  src/Workspaces/CoreTest/WorkspaceTests/AdhocWorkspaceTests.cs
  src/Workspaces/MSBuildTest/VisualStudioMSBuildWorkspaceTests.cs
Labels: Area-IDE

#67163 Multitarget O# external access projects to fix issues accessing prope…
  src/Tools/ExternalAccess/OmniSharp.CSharp/Completion/OmniSharpCompletionProviderNames.cs
  src/Tools/ExternalAccess/OmniSharp.CSharp/Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.CSharp.csproj
  src/Tools/ExternalAccess/OmniSharp/Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.csproj
Labels: Area-Infrastructure

#67173 Insert release/dev17.6 to VS rel/d17.6
  eng/config/PublishData.json
Labels: Area-Infrastructure

#67172 Add azdo marker for bootstrap failure message
  eng/test-build-correctness.ps1
Labels: Area-Infrastructure

#67149 Force solution-asset system to fail if it can't find an asset for a checksum
  src/Workspaces/Remote/Core/SolutionAsset.cs
  src/Workspaces/Remote/Core/SolutionAssetProvider.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.Scope.cs
Labels: Area-IDE

#67151 Fix issue with 'convert typeof(x) to nameof(x)' with 'nint'
  src/Analyzers/CSharp/CodeFixes/ConvertTypeOfToNameOf/CSharpConvertTypeOfToNameOfCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/ConvertTypeOfToNameOf/ConvertTypeOfToNameOfTests.cs
  src/Analyzers/Core/CodeFixes/ConvertTypeOfToNameOf/AbstractConvertTypeOfToNameOfCodeFixProvider.cs
  src/Analyzers/VisualBasic/CodeFixes/ConvertTypeOfToNameOf/VisualBasicConvertGetTypeToNameOfCodeFixProvider.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ITypeSymbolExtensions.ExpressionSyntaxGeneratorVisitor.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ITypeSymbolExtensions.cs
Labels: Area-IDE

#67140 Include parens in crefs when necessary to disambiguate items
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/CrefCompletionProviderTests.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/CrefCompletionProvider.cs
Labels: Area-IDE

#67097 Do not offer `string` (or other type-keywords) after `ref/readonly` inside namespace member declaration
  src/EditorFeatures/CSharpTest2/Recommendations/BoolKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ByteKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/CharKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/DecimalKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/DoubleKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/FloatKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/IntKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/LongKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ObjectKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/SByteKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ShortKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/StringKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/UIntKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ULongKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/UShortKeywordRecommenderTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/AbstractSpecialTypePreselectingKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/BoolKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/ByteKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/CharKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/DecimalKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/DoubleKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/FloatKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/IntKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/LongKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/ObjectKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/SByteKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/ShortKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/StringKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/UIntKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/ULongKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/UShortKeywordRecommender.cs
Labels: Area-IDE

#67196 Move to an expeditable delay to help out tests.
  src/Features/Core/Portable/DesignerAttribute/DesignerAttributeDiscoveryService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/TestHooks/IExpeditableDelaySource.cs
Labels: Area-IDE

#67190 Export to IVT for VS Mac regression
  src/EditorFeatures/CSharp/Microsoft.CodeAnalysis.CSharp.EditorFeatures.csproj
Labels: Area-IDE

#67197 Fix crash in highlight-refs in multi-language solutions where multiple documents of different languages are open.
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.vb
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine_FindReferencesInDocuments.cs
Labels: Area-IDE, OnDeckForServicing

#67105 Update PDB behavior for 'using alias to type', and add EE and PDB tests.
  src/Compilers/CSharp/Portable/Binder/ImportChain.cs
  src/Compilers/CSharp/Test/Emit/PDB/PDBUsingTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/DebuggerDisplayAttributeTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/ExpressionCompilerTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/UsingDebugInfoTests.cs
Labels: Area-Compilers, Area-Interactive

#67216 Make 'ID' optional in a WorkItem attribute
  src/Compilers/Test/Core/Assert/WorkItemAttribute.cs
Labels: Area-Compilers

#67221 Walk green tree in SyntaxFacts.HasYieldOperations to avoid excessive allocations in reported trace
  src/Compilers/CSharp/Portable/Syntax/SyntaxFacts.cs
Labels: Area-Compilers

#67225 Record completion of "alias any type" feature
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation

#67161 How to troubleshoot a build-time regression
  docs/wiki/Troubleshooting-tips.md
Labels: Area-Compilers, Documentation

#67224 Include containing type for nested types when showing goto-impl results
  src/Features/Core/Portable/FindUsages/FindUsagesHelpers.cs
Labels: Area-IDE

#67206 Use Content for non-TFM specific items
  src/NuGet/Microsoft.Net.Compilers.Toolset/AnyCpu/Microsoft.Net.Compilers.Toolset.Package.csproj
Labels: Area-Infrastructure

#67200 Fix issue with 'use range operator'
  src/Analyzers/CSharp/CodeFixes/UseIndexOrRangeOperator/CSharpUseRangeOperatorCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs
Labels: Area-IDE

#67227 Update 'make field readonly' to understand a special strict behaviour around generic assignment.
  src/Analyzers/CSharp/Tests/MakeFieldReadonly/MakeFieldReadonlyTests.cs
  src/Analyzers/Core/Analyzers/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs
  src/Analyzers/VisualBasic/Tests/MakeFieldReadonly/MakeFieldReadonlyTests.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ISymbolExtensions.cs
Labels: Area-IDE

#66876 Use next sibling in SyntaxNode.GetChildPosition() if available
  src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxListTests.cs
  src/Compilers/Core/Portable/Syntax/SyntaxList.SeparatedWithManyChildren.cs
  src/Compilers/Core/Portable/Syntax/SyntaxList.SeparatedWithManyWeakChildren.cs
  src/Compilers/Core/Portable/Syntax/SyntaxList.WithManyChildren.cs
  src/Compilers/Core/Portable/Syntax/SyntaxList.WithManyWeakChildren.cs
  src/Compilers/Core/Portable/Syntax/SyntaxList.WithThreeChildren.cs
  src/Compilers/Core/Portable/Syntax/SyntaxList.WithTwoChildren.cs
  src/Compilers/Core/Portable/Syntax/SyntaxNode.cs
  src/Compilers/Test/Core/Compilation/CompilationExtensions.cs
  src/Compilers/VisualBasic/Test/Syntax/Syntax/SyntaxListTests.vb
Labels: Area-Compilers

#67223 Infra fixes
  azure-pipelines.yml
  eng/build-utils.ps1
Labels: Area-Infrastructure

#66637 Automatically visit lambdas without conversion in nullable walker
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
Labels: Area-Compilers

#59491 Detect ref assemblies in rebuild
  src/Tools/BuildValidator/BuildValidator.csproj
  src/Tools/BuildValidator/Program.cs
  src/Tools/BuildValidator/Records.cs
  src/Tools/BuildValidator/Util.cs
Labels: Area-Infrastructure

#67246 Skip flaky integration tests
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpFormatting.cs
  src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpRename.cs
Labels: Area-Infrastructure

#67167 Primary Constructors - Don't report unused parameters
  src/Analyzers/CSharp/Analyzers/RemoveUnusedParametersAndValues/CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/RemoveUnusedParametersAndValues/RemoveUnusedParametersTests.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs
  src/Analyzers/VisualBasic/Analyzers/RemoveUnusedParametersAndValues/VisualBasicRemoveUnusedParametersAndValuesDiagnosticAnalyzer.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/IParameterSymbolExtensions.cs
Labels: Area-IDE

#67249 Compute PatternMatching result in parallel when refreshing completion list
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/ItemManager.CompletionListUpdater.cs
  src/EditorFeatures/Test2/IntelliSense/CompletionRulesTests.vb
  src/Features/Core/Portable/Completion/CommonCompletionService.cs
  src/Features/Core/Portable/Completion/CompletionContext.cs
  src/Features/Core/Portable/Completion/CompletionHelper.cs
  src/Features/Core/Portable/Completion/CompletionHelperServiceFactory.cs
  src/Features/Core/Portable/Completion/CompletionService.cs
  src/Features/Core/Portable/Completion/ICompletionHelperService.cs
  src/Features/Core/Portable/Completion/PatternMatchHelper.cs
  src/Features/Core/Portable/Completion/Providers/AbstractRecommendationServiceBasedCompletionProvider.cs
  src/Features/Core/Portable/Completion/SharedSyntaxContextsWithSpeculativeModel.cs
  src/Features/Core/Portable/Completion/Utilities.cs
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/Api/VSTypeScriptCompletionServiceWithProviders.cs
  src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandler.cs
Labels: Area-IDE

#67136 Add 'name' to option group
  src/Features/LanguageServer/Protocol/Features/Options/CompletionOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/HighlightingOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/ImplementTypeOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/MetadataAsSourceOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/QuickInfoOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/SymbolSearchOptionsStorage.cs
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
  src/VisualStudio/Core/Test.Next/Options/VisualStudioOptionStorageTests.cs
  src/Workspaces/CSharp/Portable/Formatting/CSharpFormattingOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeStyle/CSharpCodeStyleOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/CSharpFormattingOptions2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/CodeStyleOptions2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/VisualBasic/VisualBasicCodeStyleOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/FormattingOptions2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Options/OptionGroup.cs
Labels: Area-IDE

#67189 Enforce proper shadowing for locals and parameters in EE
  src/Compilers/CSharp/Portable/Binder/InMethodBinder.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpCompilationExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Binders/EEMethodBinder.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Rewriters/CapturedVariableRewriter.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EEMethodSymbol.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/ExpressionCompilerTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/LocalFunctionTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/LocalsTests.cs
Labels: Area-Compilers

#67251 Include faulty version number in version format diagnostic
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_Assembly.cs
Labels: Area-Compilers

#66915 Warn when taking address of local or parameter in async method
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Generated/ErrorFacts.Generated.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
Labels: Area-Compilers

#67135 Allow 'convert to interpolated string' to work in any API, instead of just a whitelisted set.
  src/EditorFeatures/CSharpTest/ConvertToInterpolatedString/ConvertPlaceholderToInterpolatedStringTests.cs
  src/EditorFeatures/VisualBasicTest/ConvertToInterpolatedString/ConvertPlaceholderToInterpolatedStringTests.vb
  src/Features/CSharp/Portable/ConvertToInterpolatedString/CSharpConvertPlaceholderToInterpolatedStringRefactoringProvider.cs
  src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs
  src/Features/VisualBasic/Portable/ConvertToInterpolatedString/VisualBasicConvertPlaceholderToInterpolatedStringRefactoringProvider.vb
Labels: Area-IDE

#67260 Update LSP protocol version
  eng/Versions.props
Labels: Area-Infrastructure

#67238 Make the import of IPasteTrackingService optional
  src/Features/CSharp/Portable/CodeRefactorings/AddMissingImports/CSharpAddMissingImportsRefactoringProvider.cs
  src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsRefactoringProvider.cs
  src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AddMissingImportsAnalysisResult.cs
  src/Features/VisualBasic/Portable/CodeRefactorings/AddMissingImports/VisualBasicAddMissingImportsRefactoringProvider.vb
Labels: Area-IDE

#67265 Refactor out the IVsCodeWindow interactions from our dropdown code
  src/EditorFeatures/Core/Extensibility/NavigationBar/INavigationBarPresenter.cs
  src/EditorFeatures/Core/NavigationBar/NavigationBarController.cs
  src/EditorFeatures/Test2/NavigationBar/MockNavigationBarPresenter.vb
  src/VisualStudio/Core/Def/NavigationBar/NavigationBarClient.cs
  src/VisualStudio/Core/Def/Utilities/VsCodeWindowViewTracker.cs
Labels: Area-IDE

#67284 [Infra] Create -vs-deps branches
  eng/config/PublishData.json
Labels: Area-Infrastructure

#67286 Add information to help us determine which misc workspace a file belongs to.
  src/Features/Core/Portable/Workspace/MiscellaneousFileUtilities.cs
  src/Features/LanguageServer/Protocol/Workspaces/LspMiscellaneousFilesWorkspace.cs
  src/VisualStudio/Core/Def/ProjectSystem/MiscellaneousFilesWorkspace.cs
Labels: Area-IDE

#67279 Change the LOC target branch to 17.6
  azure-pipelines-official.yml
Labels: Area-Infrastructure

#67240 Rebuild fixes
  Compilers.slnf
  src/Tools/BuildValidator/BuildValidator.csproj
  src/Tools/BuildValidator/CompilationDiff.cs
  src/Tools/BuildValidator/LocalReferenceResolver.cs
  src/Tools/BuildValidator/Program.cs
Labels: Area-Compilers

#67304 Update Language Feature Status.md
  docs/Language Feature Status.md
Labels: Area-Compilers

#67252 Improve EnC test helpers, add repro for #67243
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTest.GenerationInfo.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTest.GenerationVerifier.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTest.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTestBase.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/EditAndContinueTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/EditAndContinue/SemanticEditDescription.cs
  src/Compilers/Test/Core/MarkedSource/SourceWithMarkedNodes.cs
Labels: Area-Compilers, Area-Interactive

#67266 Implement support for captured Primary Constructor parameters in EE when portable PDB is used.
  src/Compilers/CSharp/Portable/Binder/Binder.CapturedParametersFinder.cs
  src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNameKind.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNameParser.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNames.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs
  src/Compilers/Core/Portable/CodeGen/MethodBody.cs
  src/Compilers/Core/Portable/Emit/EditAndContinue/DeletedMethodBody.cs
  src/Compilers/Core/Portable/Emit/NoPia/CommonEmbeddedMethod.cs
  src/Compilers/Core/Portable/PEWriter/Members.cs
  src/Compilers/Core/Portable/PEWriter/MetadataWriter.PortablePdb.cs
  src/Compilers/Core/Portable/PEWriter/RootModuleStaticConstructor.cs
  src/Compilers/VisualBasic/Portable/Compilation/MethodCompiler.vb
  src/Dependencies/CodeAnalysis.Debugging/PortableCustomDebugInfoKinds.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/ExpressionCompilerTestBase.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/ExpressionCompilerTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/LocalFunctionTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/LocalsTests.cs
  src/ExpressionEvaluator/CSharp/Test/ResultProvider/FullNameTests.cs
  src/ExpressionEvaluator/Core/Source/ExpressionCompiler/PDB/MethodDebugInfo.Native.cs
  src/ExpressionEvaluator/Core/Source/ExpressionCompiler/PDB/MethodDebugInfo.Portable.cs
  src/ExpressionEvaluator/Core/Source/ExpressionCompiler/PDB/MethodDebugInfo.cs
  src/ExpressionEvaluator/VisualBasic/Source/ExpressionCompiler/EvaluationContext.vb
Labels: Area-Compilers, New Feature - Primary Constructors

#67143 Switch integration CI to Preview queue
  azure-pipelines-integration.yml
Labels: Area-Infrastructure

#67315 Disable analyzer telemetry for all but lightbulb invocation path
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.Executor.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_IncrementalAnalyzer.cs
  src/Workspaces/Remote/ServiceHub/Services/ProcessTelemetry/RemoteProcessTelemetryService.PerformanceReporter.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-IDE

#67318 17.5 port of #67315 (Disable analyzer telemetry for all but lightbulb invocation path)
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.Executor.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_IncrementalAnalyzer.cs
  src/Workspaces/Remote/ServiceHub/Services/ProcessTelemetry/RemoteProcessTelemetryService.PerformanceReporter.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-IDE

#66561 Update BCL versions to .NET 7
  eng/Versions.props
  src/Dependencies/Collections/Microsoft.CodeAnalysis.Collections.Package.csproj
  src/VisualStudio/Setup.Dependencies/Roslyn.VisualStudio.Setup.Dependencies.csproj
Labels: Area-Infrastructure

#67120 Compute TextChange based on syntax instead of text
  src/EditorFeatures/CSharpTest/AutomaticCompletion/AutomaticBraceCompletionTests.cs
  src/Features/CSharp/Portable/BraceCompletion/AbstractCurlyBraceOrBracketCompletionService.cs
Labels: Area-IDE

#67309 Disable IDE0090 (use target typed new) in compiler layer
  src/Compilers/.editorconfig
Labels: Area-Compilers

#67322 Do not make cross-process calls to try to find references to local symbols
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_FindReferences_Current.cs
Labels: Area-IDE

#67314 Remove descendent node tracking from SyntaxEditor
  src/Features/Core/Portable/PullMemberUp/MembersPuller.cs
  src/Workspaces/Core/Portable/Editing/SyntaxEditor.cs
  src/Workspaces/CoreTest/Editing/SyntaxEditorTests.cs
Labels: Area-IDE

#66206 Framework compilers package for SDK consumption
  Compilers.slnf
  Roslyn.sln
  azure-pipelines.yml
  eng/build-utils.ps1
  eng/build.ps1
  eng/pipelines/build-bootstrap.yml
  eng/test-build-correctness.ps1
  src/NuGet/Microsoft.Net.Compilers.Toolset/Framework/Microsoft.Net.Compilers.Toolset.Framework.Package.csproj
  src/NuGet/Microsoft.Net.Compilers.Toolset/Framework/build/Microsoft.Net.Compilers.Toolset.Framework.Core.props
  src/NuGet/Microsoft.Net.Compilers.Toolset/Framework/build/Microsoft.Net.Compilers.Toolset.Framework.props
  src/NuGet/Microsoft.Net.Compilers.Toolset/Framework/build/Microsoft.Net.Compilers.Toolset.props
  src/NuGet/Microsoft.Net.Compilers.Toolset/Framework/buildMultiTargeting/Microsoft.Net.Compilers.Toolset.Framework.props
  src/NuGet/Microsoft.Net.Compilers.Toolset/README.md
  src/NuGet/Microsoft.Net.Compilers.Toolset/arm64/Microsoft.Net.Compilers.Toolset.Arm64.Package.csproj
  src/Tools/BuildBoss/CompilerNuGetCheckerUtil.cs
Labels: Area-Compilers

#67324 Improve perf of resolving local symbol keys
  src/Workspaces/CoreTest/SymbolKeyTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/SymbolKey/SymbolKey.BodyLevelSymbolKey.cs
Labels: Area-IDE

#67175 Implement 'Make field/property required' codefix
  src/Analyzers/CSharp/CodeFixes/CSharpCodeFixes.projitems
  src/Analyzers/CSharp/CodeFixes/CSharpCodeFixesResources.resx
  src/Analyzers/CSharp/CodeFixes/MakeMemberRequired/CSharpMakeMemberRequiredCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.cs.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.de.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.es.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.fr.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.it.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.ja.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.ko.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.pl.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.pt-BR.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.ru.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.tr.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.zh-Hans.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.zh-Hant.xlf
  src/Analyzers/CSharp/Tests/CSharpAnalyzers.UnitTests.projitems
  src/Analyzers/CSharp/Tests/MakeMemberRequired/MakeMemberRequiredTests.cs
  src/Analyzers/Core/CodeFixes/PredefinedCodeFixProviderNames.cs
  src/Compilers/Test/Core/Traits/Traits.cs
Labels: Area-IDE, Community

#65851 Removed 'AnalyzerOptions' reference related to 'AdditionalFiles'
  docs/features/source-generators.cookbook.md
Labels: Area-Compilers, Community

#67334 Search a smaller scope when looking for references to a local symbol
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractMemberScopedReferenceFinder.cs
Labels: Area-IDE

#67287 Do not use the Lsp-Misc workspace in VS scenarios
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/LanguageServer/Protocol/LspServices/LspServices.cs
  src/Features/LanguageServer/Protocol/RoslynLanguageServer.cs
  src/Features/LanguageServer/Protocol/Workspaces/LspWorkspaceManager.cs
  src/Features/LanguageServer/Protocol/Workspaces/LspWorkspaceManagerFactory.cs
  src/Features/LanguageServer/Protocol/Workspaces/LspWorkspaceRegistrationEventListener.cs
  src/Features/LanguageServer/Protocol/Workspaces/LspWorkspaceRegistrationService.cs
  src/VisualStudio/Core/Def/LanguageClient/VisualStudioLspWorkspaceRegistrationService.cs
Labels: Area-IDE

#67342 Remove roslyn-auth.yml
  azure-pipelines.yml
  eng/common/templates/steps/azure-public-roslyn-auth.yml
  eng/common/templates/steps/source-build.yml
  eng/pipelines/build-bootstrap.yml
  eng/pipelines/build-unix-job.yml
  eng/pipelines/build-windows-job.yml
  eng/pipelines/insert.yml
  eng/pipelines/test-integration-job.yml
  eng/pipelines/test-unix-job-single-machine.yml
  eng/pipelines/test-unix-job.yml
  eng/pipelines/test-windows-job-single-machine.yml
  eng/pipelines/test-windows-job.yml
Labels: Area-Infrastructure

#67282 Disallow pointers inside generic type-arguments unless in an unsafe context (in C#12 and beyond).
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/Symbols/AliasSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/FunctionPointerTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/UnsafeTests.cs
  src/Compilers/CSharp/Test/Symbol/Compilation/UsedAssembliesTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/GenericConstraintTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/BaseClassTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/ClsComplianceTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/UsingAliasTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs
Labels: Area-Compilers

#67255 [Lightbulb Perf] Analyzer driver fixes for span-based analysis
  src/Compilers/CSharp/Test/Emit2/Diagnostics/GetDiagnosticsTests.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisScope.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.GroupedAnalyzerActionsForAnalyzer.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs
  src/Compilers/Test/Core/Diagnostics/CommonDiagnosticAnalyzers.cs
Labels: Area-Analyzers, Area-Compilers

#67352 Fix CSharpMakeStructMemberReadOnlyDiagnosticAnalyzer to report local diagnostic
  src/Analyzers/CSharp/Analyzers/MakeStructMemberReadOnly/CSharpMakeStructMemberReadOnlyAnalyzer.cs
  src/Analyzers/CSharp/Tests/MakeStructMemberReadOnly/MakeStructMemberReadOnlyTests.cs
Labels: Area-IDE

#67345 Rename codefix predefined name
  src/Analyzers/CSharp/CodeFixes/MakeTypePartial/CSharpMakeTypePartialCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/PredefinedCodeFixProviderNames.cs
  src/Analyzers/VisualBasic/CodeFixes/MakeTypePartial/VisualBasicMakeTypePartialCodeFixProvider.vb
Labels: Area-IDE, Community

#67312 Add tests for local/non-local diagnostic classification for accessor block
  src/Compilers/CSharp/Test/Emit2/Diagnostics/GetDiagnosticsTests.cs
  src/Compilers/VisualBasic/Test/Semantic/Diagnostics/GetDiagnosticsTests.vb
Labels: Area-Analyzers, Area-Compilers

#67356 Move to new binary logger NuGet
  eng/Versions.props
Labels: Area-Infrastructure

#67337 Support generating records in syntax generator
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Syntax/RecordDeclarationSyntax.cs
  src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxFactoryTests.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
  src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs
  src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb
Labels: Area-IDE

#67340 Improve error recovery while parsing switch expressions.
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Syntax/Parsing/SwitchExpressionParsingTests.cs
Labels: Area-Compilers

#67360 Improve props in readonly struct
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/AbstractCSharpAutoPropertyCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpPropSnippetCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpPropgSnippetCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpPropiSnippetCompletionProviderTests.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/SpeculativeTCompletionProvider.cs
  src/Features/CSharp/Portable/Snippets/AbstractCSharpAutoPropertySnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpPropSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpPropgSnippetProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/CSharpSyntaxContext.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs
Labels: Area-IDE, Community

#67367 Move off of options for encoding ephemeral state in inline-hints
  src/EditorFeatures/Core.Wpf/InlineHints/InlineHintsKeyProcessorProvider.cs
  src/EditorFeatures/Core/InlineHints/IInlineHintKeyProcessor.cs
  src/EditorFeatures/Core/InlineHints/InlineHintKeyProcessorEventSource.cs
  src/EditorFeatures/Core/InlineHints/InlineHintsDataTaggerProvider.cs
  src/EditorFeatures/Core/InlineHints/InlineHintsGlobalStateOption.cs
  src/EditorFeatures/Core/Options/LegacyGlobalOptionsWorkspaceService.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.cs
  src/EditorFeatures/Test2/InlineHints/AbstractInlineHintsTests.vb
  src/Features/Core/Portable/InlineHints/AbstractInlineHintsService.cs
  src/Features/Core/Portable/InlineHints/AbstractInlineParameterNameHintsService.cs
  src/Features/Core/Portable/InlineHints/AbstractInlineTypeHintsService.cs
  src/Features/Core/Portable/InlineHints/IInlineHintsService.cs
  src/Features/Core/Portable/InlineHints/IInlineParameterNameHintsService.cs
  src/Features/Core/Portable/InlineHints/IInlineTypeHintsService.cs
  src/Tools/ExternalAccess/FSharp/Internal/InlineHints/FSharpInlineHintsService.cs
  src/Tools/ExternalAccess/OmniSharp/InlineHints/OmniSharpInlineHintsService.cs
  src/VisualStudio/Core/Test.Next/Options/VisualStudioOptionStorageTests.cs
  src/Workspaces/Core/Portable/Options/ILegacyGlobalOptionsWorkspaceService.cs
Labels: Area-IDE

#67377 Update codeowner for O# ExternalAccess
  .github/CODEOWNERS
Labels: Area-Infrastructure

#67375 Add new package to PublishData
  eng/config/PublishData.json
Labels: Area-Infrastructure

#67369 Do not capture project/solution/compilation data in designer-attribute-scanning.
  src/Features/Core/Portable/DesignerAttribute/DesignerAttributeDiscoveryService.cs
  src/VisualStudio/CSharp/Test/DesignerAttribute/DesignerAttributeServiceTests.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Metadata.cs
Labels: Area-IDE

#67378 revert nuget feed changes
  NuGet.config
Labels: Area-Infrastructure

#67379 Change CheckBoxOptionViewModel to AbstractCheckBoxViewModel
  src/VisualStudio/Core/Impl/Options/OptionPreviewControl.xaml.cs
Labels: Area-IDE

#67344 Code changes to allow 'using static unsafe'
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceNamespaceSymbol.AliasesAndUsings.cs
  src/Compilers/CSharp/Portable/Symbols/SymbolExtensions.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Semantic/Semantics/UnsafeTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/UsingDirectiveParsingTests.cs
Labels: Area-Compilers

#67343 Remove unused state form TypeofBinder and GetTypeBinder.
  src/Compilers/CSharp/Portable/Binder/TypeofBinder.cs
  src/Compilers/VisualBasic/Portable/Binding/GetTypeBinder.vb
Labels: Area-Compilers

#67376 Reduce allocations in diagnostic analyzer management system.
  src/Features/Core/Portable/Diagnostics/LiveDiagnosticUpdateArgsId.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.ProjectState.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.StateManager.HostStates.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.StateManager.ProjectStates.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.StateManager.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.StateSet.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.cs
Labels: Area-IDE

#67275 Fix up local/non-local diagnostic classification in analyzer driver
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/AbstractUseCollectionInitializerDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseObjectInitializer/AbstractUseObjectInitializerDiagnosticAnalyzer.cs
  src/Compilers/CSharp/Test/Emit2/Diagnostics/GetDiagnosticsTests.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisResultBuilder.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.AnalyzerDiagnosticReporter.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs
  src/Compilers/Test/Core/Diagnostics/CommonDiagnosticAnalyzers.cs
Labels: Area-IDE, Area-Analyzers

#67300 Port 66085 to 17.5 for servicing
  src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs
Labels: Area-Analyzers, Needs Shiproom Approval, servicing-approved

#67387 Add test
  .vscode/settings.json
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
Labels: Area-IDE

#67381 Fix 17.5 CI build
  eng/build.ps1
  src/Tools/BuildBoss/BuildBoss.csproj
Labels: Area-Infrastructure

#67390 Simplify diagnostic check
  src/Features/Core/Portable/Diagnostics/LiveDiagnosticUpdateArgsId.cs
Labels: Area-IDE

#67393 Display exception filters by `BoundNode.DumpSource()`
  src/Compilers/CSharp/Portable/BoundTree/BoundNode_Source.cs
Labels: Area-Compilers

#67423 Create a new solution folder for all things language-server related
  Roslyn.sln
Labels: Area-IDE

#67424 Remove assert in CheckParameterValEscape()
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
Labels: Area-Compilers

#67422 Update feature status
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation

#67420 Add warning wave doc for 'taking address of local or parameter in async method'
  docs/compilers/CSharp/Warnversion Warning Waves.md
Labels: Area-Compilers, Documentation

#67427 Remove abstract method that always returns the same value
  src/EditorFeatures/Core.Cocoa/Lsp/VSMacWorkspaceRegistrationService.cs
  src/EditorFeatures/TestUtilities/LanguageServer/TestWorkspaceRegistrationService.cs
  src/Features/LanguageServer/Protocol/Workspaces/LspWorkspaceManager.cs
  src/Features/LanguageServer/Protocol/Workspaces/LspWorkspaceRegistrationService.cs
  src/Features/LanguageServer/ProtocolUnitTests/Workspaces/LspWorkspaceManagerTests.cs
  src/Tools/ExternalAccess/Razor/RazorTestWorkspaceRegistrationService.cs
  src/VisualStudio/Core/Def/LanguageClient/VisualStudioLspWorkspaceRegistrationService.cs
Labels: Area-IDE

#67396 Enum base list completions
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/TypeImportCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/GlobalKeywordRecommenderTests.cs
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/SymbolCompletionProviderTests.vb
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/TypeImportCompletionProviderTests.vb
  src/EditorFeatures/VisualBasicTest/Recommendations/Types/BuiltInTypesKeywordRecommenderTests.vb
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/GlobalKeywordRecommender.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionService.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/TypeImportCompletionCacheEntry.cs
  src/Features/VisualBasic/Portable/Completion/KeywordRecommenders/Expressions/GlobalKeywordRecommender.vb
  src/Features/VisualBasic/Portable/Completion/KeywordRecommenders/Types/BuiltInTypesKeywordRecommender.vb
  src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs
  src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/CSharpSyntaxContext.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/ContextQuery/SyntaxContext.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/VisualBasicSyntaxContext.vb
  src/Workspaces/VisualBasic/Portable/Recommendations/VisualBasicRecommendationServiceRunner.vb
Labels: Area-IDE, Community

#67351 Exclude non-local diagnostics by default in legacy test framework for analyzer/code fix unit tests
  src/Analyzers/CSharp/Analyzers/InlineDeclaration/CSharpInlineDeclarationDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseLocalFunction/CSharpUseLocalFunctionDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UsePatternMatching/CSharpAsAndNullCheckDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UsePatternMatching/CSharpIsAndCastCheckDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/AbstractUseCollectionInitializerDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseObjectInitializer/AbstractUseObjectInitializerDiagnosticAnalyzer.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/AbstractCodeActionOrUserDiagnosticTest.cs
  src/EditorFeatures/DiagnosticsTestUtilities/Diagnostics/AbstractDiagnosticProviderBasedUserDiagnosticTest.cs
  src/EditorFeatures/DiagnosticsTestUtilities/Diagnostics/AbstractSuppressionDiagnosticTest.cs
  src/EditorFeatures/DiagnosticsTestUtilities/Diagnostics/AbstractUnncessarySuppressionDiagnosticTest.cs
  src/EditorFeatures/TestUtilities/Diagnostics/DiagnosticProviderTestUtilities.cs
  src/EditorFeatures/TestUtilities/Diagnostics/MockDiagnosticAnalyzerService.cs
  src/EditorFeatures/TestUtilities/Diagnostics/TestDiagnosticAnalyzerDriver.cs
  src/Features/Core/Portable/Diagnostics/IDiagnosticAnalyzerService.cs
  src/Features/LanguageServer/Protocol/Features/CodeFixes/CodeFixService.FixAllDiagnosticProvider.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DiagnosticAnalyzerService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DiagnosticAnalyzerService_UpdateSource.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs
  src/VisualStudio/Core/Test/Diagnostics/ExternalDiagnosticUpdateSourceTests.vb
Labels: Area-IDE

#67419 Do not use VS specific completion kinds in core LSP protocol layer
  src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/ProtocolConversionsTests.cs
Labels: Area-IDE

#67319 Implement LSP inlay hints
  eng/Versions.props
  src/EditorFeatures/Core/InlineHints/InlineHintsDataTaggerProvider.cs
  src/Features/Core/Portable/InlineHints/AbstractInlineHintsService.cs
  src/Features/Core/Portable/InlineHints/AbstractInlineParameterNameHintsService.cs
  src/Features/Core/Portable/InlineHints/AbstractInlineTypeHintsService.cs
  src/Features/Core/Portable/InlineHints/InlineHintsConstants.cs
  src/Features/LanguageServer/Protocol/DefaultCapabilitiesProvider.cs
  src/Features/LanguageServer/Protocol/Features/Options/InlineHintsOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Handler/InlayHint/InlayHintCache.cs
  src/Features/LanguageServer/Protocol/Handler/InlayHint/InlayHintCacheFactory.cs
  src/Features/LanguageServer/Protocol/Handler/InlayHint/InlayHintHandler.cs
  src/Features/LanguageServer/Protocol/Handler/InlayHint/InlayHintResolveData.cs
  src/Features/LanguageServer/Protocol/Handler/InlayHint/InlayHintResolveHandler.cs
  src/Features/LanguageServer/Protocol/Handler/InlayHint/InlayHintResolveHandlerFactory.cs
  src/Features/LanguageServer/Protocol/Microsoft.CodeAnalysis.LanguageServer.Protocol.csproj
  src/Features/LanguageServer/ProtocolUnitTests/InlayHint/AbstractInlayHintTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/InlayHint/CSharpInlayHintTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/InlayHint/VisualBasicInlayHintTests.cs
Labels: Area-IDE

#67437 Document handling on unused imports by GetUsedAssemblyReferences API.
  src/Compilers/Core/Portable/Compilation/Compilation.cs
Labels: Area-Compilers, Documentation

#67445 Update assert in EmitConversion to allow for pointer subtraction
  src/Compilers/CSharp/Portable/CodeGen/EmitConversion.cs
  src/Compilers/CSharp/Test/Emit2/Emit/NumericIntPtrTests.cs
Labels: Area-Compilers, untriaged

#66643 Track state table removal due to input separately from removal due to selection
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/StateTableTests.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs
Labels: Area-Compilers

#67450 Remove synchronous fire-and-forget mutation apis from TestWorkspace
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/OverrideCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/Suppression/SuppressionTests.cs
  src/EditorFeatures/Test/EditAndContinue/EditSessionActiveStatementsTests.cs
  src/EditorFeatures/Test/EditAndContinue/RemoteEditAndContinueServiceTests.cs
  src/EditorFeatures/Test/SolutionCrawler/WorkCoordinatorTests.cs
  src/EditorFeatures/Test2/Diagnostics/DiagnosticServiceTests.vb
  src/EditorFeatures/Test2/Simplification/AbstractSimplificationTests.vb
  src/EditorFeatures/Test2/Simplification/InitializerSimplificationTests.vb
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs
  src/VisualStudio/CSharp/Test/DocumentOutline/DocumentOutlineTestsBase.cs
Labels: Area-IDE, untriaged

#67467 Don't trigger completion in argument list
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractImportCompletionProvider.cs
  src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionTests.cs
Labels: Area-IDE, untriaged

#67454 Compute new brace-pair tags when the view is scrolled
  src/EditorFeatures/Core/BracePairs/BracePairsTaggerProvider.cs
  src/EditorFeatures/Core/Classification/Semantic/AbstractSemanticOrEmbeddedClassificationViewTaggerProvider.cs
  src/EditorFeatures/Core/InlineHints/InlineHintsDataTaggerProvider.cs
  src/EditorFeatures/Core/Tagging/AsynchronousViewTaggerProvider.cs
  src/VisualStudio/Core/Def/InheritanceMargin/InheritanceMarginTaggerProvider.cs
Labels: Area-IDE, untriaged

#67455 Add inline hints options to lsp
  src/Features/LanguageServer/Protocol/Handler/Configuration/DidChangeConfigurationNotificationHandler_OptionList.cs
Labels: Area-IDE, untriaged

#67475 Change inline hint to inline hints
  src/Features/LanguageServer/Protocol/Features/Options/InlineHintsOptionsStorage.cs
Labels: Area-IDE, untriaged

#67443 Add support in LSP code for hosting workspaces that don't keep an independent view of the current solution.
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace_ILspWorkspace.cs
  src/Features/LanguageServer/Protocol/Extensions/Extensions.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/Public/PublicWorkspacePullDiagnosticsHandler.cs
  src/Features/LanguageServer/Protocol/Workspaces/ILspWorkspace.cs
  src/Features/LanguageServer/Protocol/Workspaces/LspWorkspaceManager.cs
  src/Features/LanguageServer/Protocol/Workspaces/LspWorkspaceManagerFactory.cs
  src/Features/LanguageServer/ProtocolUnitTests/CodeActions/CodeActionResolveTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/CodeActions/CodeActionsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/CodeActions/RunCodeActionsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/CodeLens/CSharpCodeLensTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/CodeLens/VisualBasicCodeLensTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionResolveTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Configuration/DidChangeConfigurationNotificationHandlerTest.cs
  src/Features/LanguageServer/ProtocolUnitTests/Definitions/GoToDefinitionTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Definitions/GoToTypeDefinitionTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/AbstractPullDiagnosticTestsBase.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/AdditionalFileDiagnosticsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/WorkspaceProjectDiagnosticsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/DocumentChanges/DocumentChangesTests.LinkedDocuments.cs
  src/Features/LanguageServer/ProtocolUnitTests/DocumentChanges/DocumentChangesTests.WithFindAllReferences.cs
  src/Features/LanguageServer/ProtocolUnitTests/DocumentChanges/DocumentChangesTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/FoldingRanges/FoldingRangesTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Formatting/FormatDocumentOnTypeTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Formatting/FormatDocumentRangeTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Formatting/FormatDocumentTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Highlights/DocumentHighlightTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Hover/HoverTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/InlayHint/CSharpInlayHintTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/InlayHint/VisualBasicInlayHintTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/InlineCompletions/InlineCompletionsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/LanguageServerTargetTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Miscellaneous/LspMiscellaneousFilesWorkspaceTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/OnAutoInsert/OnAutoInsertTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Options/LspOptionsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Ordering/RequestOrderingTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/ProjectContext/GetTextDocumentWithContextHandlerTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/References/FindAllReferencesHandlerFeaturesTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/References/FindAllReferencesHandlerTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/References/FindImplementationsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Rename/RenameTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/SemanticTokensRangeTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/SignatureHelp/SignatureHelpTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/SpellCheck/SpellCheckTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Symbols/DocumentSymbolsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Symbols/WorkspaceSymbolsTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/VSTypeScriptHandlerTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/ValidateBreakableRange/ValidateBreakableRangeTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Workspaces/LspWorkspaceManagerTests.cs
  src/Features/LanguageServer/ProtocolUnitTests/Workspaces/LspWorkspaceRegistrationServiceTests.cs
  src/Tools/IdeBenchmarks/Lsp/LspCompletionBenchmarks.cs
  src/VisualStudio/LiveShare/Test/ProjectsHandlerTests.cs
  src/Workspaces/Core/Portable/Workspace/Solution/TextDocument.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
  src/Workspaces/Core/Portable/Workspace/Workspace_Editor.cs
Labels: Area-IDE, untriaged

#67470 Remove concept of metadata assemblies that we dump to recoverable storage.
  src/Features/LanguageServer/Protocol/Features/Options/WorkspaceConfigurationOptionsStorage.cs
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
  src/VisualStudio/Core/Def/ProjectSystem/MetadataReferences/VisualStudioMetadataReference.Snapshot.cs
  src/VisualStudio/Core/Def/ProjectSystem/MetadataReferences/VisualStudioMetadataReferenceManager.Factory.cs
  src/VisualStudio/Core/Def/ProjectSystem/MetadataReferences/VisualStudioMetadataReferenceManager.MetadataCache.cs
  src/VisualStudio/Core/Def/ProjectSystem/MetadataReferences/VisualStudioMetadataReferenceManager.RecoverableMetadataValueSource.cs
  src/VisualStudio/Core/Def/ProjectSystem/MetadataReferences/VisualStudioMetadataReferenceManager.cs
  src/Workspaces/Core/Portable/Serialization/ISupportTemporaryStorage.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService_Reference.cs
  src/Workspaces/Core/Portable/Workspace/IWorkspaceConfigurationService.cs
Labels: Area-IDE, untriaged

#67474 Remove automatic background compiling/parsing in roslyn.
  src/EditorFeatures/CSharpTest/Workspaces/WorkspaceTests_EditorFeatures.cs
  src/EditorFeatures/Test/SolutionCrawler/WorkCoordinatorTests.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs
  src/Features/Core/Portable/Workspace/BackgroundCompiler.cs
  src/Features/Core/Portable/Workspace/BackgroundParser.cs
  src/Features/LanguageServer/Protocol/Features/Options/WorkspaceConfigurationOptionsStorage.cs
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspace.cs
  src/Workspaces/Core/Portable/Workspace/IWorkspaceConfigurationService.cs
Labels: Area-IDE, untriaged

#67122 Preserve parent hoisted variables in nested async `catch`
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncExceptionHandlerRewriter.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs
Labels: Area-Compilers

#67236 [Lightbulb Perf] Run analyzers only for requested span
  src/EditorFeatures/Test2/Diagnostics/DiagnosticServiceTests.vb
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs
Labels: Area-Analyzers

#67453 Gracefully handle unexpected NullableWalker state
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
Labels: Area-Compilers

#67476 Remove unread field in the work coordinator.
  src/EditorFeatures/Test/SolutionCrawler/WorkCoordinatorTests.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.AsyncDocumentWorkItemQueue.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.AsyncProjectWorkItemQueue.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.HighPriorityProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.LowPriorityProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.WorkItem.cs
Labels: Area-IDE, untriaged

#67384 Trim away netframework targets in source-build
  eng/SourceBuild.props
Labels: Area-Infrastructure, Community

#67496 [Infra] Fix 17.6 build
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
Labels: Area-Compilers, untriaged

#67503 Include explicit BCL references for .NET 6 VS OOP
  src/Workspaces/Remote/ServiceHub.CoreComponents/Microsoft.CodeAnalysis.Remote.ServiceHub.CoreComponents.csproj
Labels: Area-IDE, untriaged

#67491 Limit walk during pragma directive analysis to subtrees containing directives
  src/Analyzers/CSharp/Analyzers/RemoveUnnecessarySuppressions/CSharpRemoveUnnecessaryPragmaSuppressionsDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/RemoveUnnecessarySuppressions/AbstractRemoveUnnecessaryPragmaSuppressionsDiagnosticAnalyzer.cs
  src/Analyzers/VisualBasic/Analyzers/RemoveUnnecessarySuppressions/VisualBasicRemoveUnnecessaryPragmaSuppressionsDiagnosticAnalyzer.vb
Labels: Area-IDE

#67498 Pass through document open/close information to the workspace in LSP scenarios.
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace_ILspWorkspace.cs
  src/Features/LanguageServer/Protocol/Workspaces/LspWorkspaceManager.cs
  src/Features/LanguageServer/ProtocolUnitTests/DocumentChanges/DocumentChangesTests.WithFindAllReferences.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
  src/Workspaces/Core/Portable/Workspace/Workspace_Editor.cs
Labels: Area-IDE, untriaged

#67504 Reorder workspace parameter for clarity
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
  src/Workspaces/Core/Portable/Workspace/Workspace_Editor.cs
Labels: Area-IDE, untriaged

#67514 Update lsp doc operation to be async.
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs
  src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace_ILspWorkspace.cs
  src/Features/LanguageServer/Protocol/Handler/DocumentChanges/DidCloseHandler.cs
  src/Features/LanguageServer/Protocol/Handler/DocumentChanges/DidOpenHandler.cs
  src/Features/LanguageServer/Protocol/Handler/IDocumentChangeTracker.cs
  src/Features/LanguageServer/Protocol/Handler/RequestContext.cs
  src/Features/LanguageServer/Protocol/Workspaces/ILspWorkspace.cs
  src/Features/LanguageServer/Protocol/Workspaces/LspWorkspaceManager.cs
  src/Workspaces/Core/Portable/Workspace/Workspace_Editor.cs
Labels: Area-IDE, untriaged

#67392 [Lightbulb Perf] Add support for prioritized diagnostic computation requests in OOP
  src/EditorFeatures/Test/Diagnostics/DiagnosticAnalyzerServiceTests.cs
  src/EditorFeatures/Test2/Diagnostics/DiagnosticServiceTests.vb
  src/EditorFeatures/TestUtilities/Diagnostics/MockDiagnosticAnalyzerService.cs
  src/Features/Core/Portable/Diagnostics/DiagnosticArguments.cs
  src/Features/Core/Portable/Diagnostics/IDiagnosticAnalyzerService.cs
  src/Features/LanguageServer/Protocol/Features/CodeFixes/CodeFixService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DefaultDiagnosticAnalyzerService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DiagnosticAnalyzerService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DocumentAnalysisExecutor.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.InProcOrRemoteHostAnalyzerRunner.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_IncrementalAnalyzer.cs
  src/VisualStudio/Core/Test/Diagnostics/ExternalDiagnosticUpdateSourceTests.vb
  src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/DiagnosticComputer.cs
  src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/RemoteDiagnosticAnalyzerService.cs
Labels: Area-Analyzers

#67506 Display inheritance margin's content of menu item in TextBlock
  src/VisualStudio/Core/Def/InheritanceMargin/MarginGlyph/InheritanceMarginContextMenu.xaml
Labels: Area-IDE, untriaged, Needs UX Triage

#64741 Clarify diagnostic when constant pattern has non-constant conversion to input type
  src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests3.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests4.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests5.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternSwitchTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IIsPatternExpression.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IPatternSwitchCase.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_ISwitchExpression.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_ISwitchOperation.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/ConstantTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/ImplicitObjectCreationTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SwitchTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/Utf8StringsLiteralsTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/ConversionTests.cs
Labels: Area-Compilers, Community

#67527 Skip the case when value from client is string.Empty
  src/Features/LanguageServer/Protocol/Handler/Configuration/DidChangeConfigurationNotificationHandler.cs
Labels: Area-IDE, untriaged

#67519 Minor memory optimizations in SourceText.ToString
  src/Compilers/Core/Portable/Text/SourceText.cs
Labels: Area-Compilers, untriaged

#67534 [Infra] Update for 17.6 P3 snap
  eng/Versions.props
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#67535 Fix issues with 'fixed size buffer' and 'make method readonly'
  src/Analyzers/CSharp/Analyzers/MakeStructMemberReadOnly/CSharpMakeStructMemberReadOnlyAnalyzer.cs
  src/Analyzers/CSharp/Tests/MakeStructMemberReadOnly/MakeStructMemberReadOnlyTests.cs
Labels: Area-IDE, untriaged

#67536 Remove support for synchronous lightbulbs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.State.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSourceProvider.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource_Async.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SyncSuggestedActionsSource.cs
  src/EditorFeatures/Core/Suggestions/SuggestionsOptionsStorage.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageStrings.vb
  src/Workspaces/CoreTest/Options/OptionSerializerTests.cs
Labels: Area-IDE, untriaged

#67547 Fix incorrect 'isExplicit' value in CodeFixService
  src/Features/LanguageServer/Protocol/Features/CodeFixes/CodeFixService.cs
Labels: Area-IDE

#67540 Remove existing sync lightbulb code
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource_Async.cs
Labels: Area-IDE, untriaged
