Repository dotnet/roslyn, pull requests merged in 2024-12, with the labels that each got.

#65773 Delete unneeded suppression for a fixed issue
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Engine/TokenStream.Changes.cs
Labels: Area-IDE, Community, VSCode

#65829 Make `SymbolAnnotation` static
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Simplification/SymbolAnnotation.cs
Labels: Area-IDE, Community, VSCode

#74623 Fix null encoding in new document in move type action
  src/Features/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpWinForms.cs
  src/Workspaces/Core/Portable/Workspace/Solution/DocumentState.cs
  src/Workspaces/MSBuildTest/VisualStudioMSBuildWorkspaceTests.cs
Labels: Area-IDE, Community, untriaged, VSCode

#76142 Format labeled statements when colon is typed
  src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs
  src/EditorFeatures/CSharpTest/Formatting/Indentation/SmartTokenFormatterFormatRangeTests.cs
  src/EditorFeatures/Core/Formatting/FormatCommandHandler.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/FormattingRangeHelper.cs
Labels: Area-IDE, untriaged, VSCode

#76143 Enable skipped test
  src/Workspaces/CoreTest/LinkedFileDiffMerging/LinkedFileDiffMergingTests.Features.cs
Labels: Area-IDE, untriaged, VSCode

#76144 Do a better job matching properties to implement against existing properties
  src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs
  src/Analyzers/Core/CodeFixes/ImplementInterface/ImplementInterfaceGenerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/SignatureComparer.cs
Labels: Area-IDE, untriaged, VSCode

#76128 Remove Navigate_asynchronously_exerimental option
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageStrings.vb
Labels: Area-IDE, untriaged, Needs UX Triage

#76148 REmove methods no longer in use
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/TaskExtensions.cs
Labels: Area-IDE, untriaged, VSCode

#76120 When converting to raw strings, do not change \r\n sequences if not explicitly requested by the user
  src/Features/CSharp/Portable/ConvertToRawString/CanConvertParams.cs
  src/Features/CSharp/Portable/ConvertToRawString/ConvertInterpolatedStringToRawStringCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/ConvertToRawString/ConvertRegularStringToRawStringCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/ConvertToRawString/ConvertStringToRawStringCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/ConvertToRawString/ConvertToRawKind.cs
  src/Features/CSharp/Portable/ConvertToRawString/ConvertToRawStringHelpers.cs
  src/Features/CSharpTest/ConvertToRawString/ConvertInterpolatedStringToRawString_FixAllTests.cs
  src/Features/CSharpTest/ConvertToRawString/ConvertRegularStringToRawString_FixAllTests.cs
Labels: Area-IDE, untriaged, VSCode

#76145 Infer better variable name when initializing from an anonymous type
  src/Features/CSharpTest/IntroduceVariable/IntroduceVariableTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SemanticModelExtensions.cs
Labels: Area-IDE, untriaged, VSCode

#76227 Update Language Feature Status.md
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation, untriaged

#76129 Update the patterns that 'use range operator' supports.
  src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseIndexOperatorDiagnosticAnalyzer.InfoCache.cs
  src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.InfoCache.cs
  src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.Result.cs
  src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/Helpers.cs
  src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/MemberInfo.cs
  src/Analyzers/CSharp/CodeFixes/UseIndexOrRangeOperator/CSharpUseRangeOperatorCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs
Labels: Area-IDE, untriaged, VSCode

#76150 Fix issue with explicit interface completion and static interface members
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ExplicitInterfaceTypeCompletionProviderTests.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceTypeCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs
Labels: Area-IDE, untriaged, VSCode

#76162 Use implicit initializer if present to generate type properties
  src/EditorFeatures/CSharpTest/CodeActions/GenerateType/GenerateTypeTests.cs
  src/Features/CSharp/Portable/CodeFixes/GenerateType/GenerateTypeCodeFixProvider.cs
  src/Features/CSharp/Portable/GenerateType/CSharpGenerateTypeService.cs
  src/Features/Core/Portable/GenerateType/AbstractGenerateTypeService.cs
  src/Features/VisualBasic/Portable/GenerateType/VisualBasicGenerateTypeService.vb
Labels: Area-IDE, untriaged, VSCode

#76152 Insert parens when hitting semicolon after 'new'
  src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs
  src/EditorFeatures/CSharpTest/CompleteStatement/CSharpCompleteStatementCommandHandlerTests.cs
Labels: Area-IDE, untriaged

#76124 Add a dedicated fixer to fixup code in expression trees that is now calling restricted apis
  src/Analyzers/CSharp/CodeFixes/CSharpCodeFixes.projitems
  src/Analyzers/CSharp/CodeFixes/CSharpCodeFixesResources.resx
  src/Analyzers/CSharp/CodeFixes/UseExplicitArrayInExpressionTree/CSharpUseExplicitArrayInExpressionTreeCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.cs.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.de.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.es.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.fr.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.it.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.ja.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.ko.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.pl.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.pt-BR.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.ru.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.tr.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.zh-Hans.xlf
  src/Analyzers/CSharp/CodeFixes/xlf/CSharpCodeFixesResources.zh-Hant.xlf
  src/Analyzers/CSharp/Tests/CSharpAnalyzers.UnitTests.projitems
  src/Analyzers/CSharp/Tests/UseExplicitArrayInExpressionTree/UseExplicitArrayInExpressionTreeTests.cs
  src/Analyzers/Core/CodeFixes/PredefinedCodeFixProviderNames.cs
  src/Compilers/Test/Core/Traits/Traits.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ICompilationExtensions.cs
Labels: Area-IDE, untriaged, VSCode

#76090 Set state of enumerator object to "after" during disposal
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 10.md
  docs/compilers/Visual Basic/Compiler Breaking Changes - DotNet 10.md
  src/Compilers/CSharp/Portable/Lowering/IteratorRewriter/IteratorMethodToStateMachineRewriter.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenDisplayClassOptimisationTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenIterators.cs
  src/Compilers/CSharp/Test/Emit2/Emit/EditAndContinue/EditAndContinueStateMachineTests.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/PrimaryConstructorTests.cs
  src/Compilers/Test/Core/CompilationVerifier.cs
  src/Compilers/VisualBasic/Portable/Lowering/IteratorRewriter/IteratorRewriter.IteratorMethodToClassRewriter.vb
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenIterators.vb
  src/Compilers/VisualBasic/Test/Emit/Emit/EditAndContinue/EditAndContinueStateMachineTests.vb
Labels: Area-Compilers

#76147 Update 'introduce using' to support expression statements
  src/Features/CSharp/Portable/IntroduceUsingStatement/CSharpIntroduceUsingStatementCodeRefactoringProvider.cs
  src/Features/CSharpTest/IntroduceUsingStatement/IntroduceUsingStatementTests.cs
  src/Features/Core/Portable/IntroduceUsingStatement/AbstractIntroduceUsingStatementCodeRefactoringProvider.cs
  src/Features/VisualBasic/Portable/IntroduceUsingStatement/VisualBasicIntroduceUsingStatementCodeRefactoringProvider.vb
  src/Features/VisualBasicTest/IntroduceUsingStatement/IntroduceUsingStatementTests.vb
Labels: Area-IDE, untriaged, VSCode

#76160 Support implicit/explicit var with inferred lambda types
  src/Analyzers/CSharp/Analyzers/UseImplicitOrExplicitType/CSharpTypeStyleDiagnosticAnalyzerBase.cs
  src/Analyzers/CSharp/Tests/UseImplicitOrExplicitType/UseExplicitTypeTests.cs
  src/Analyzers/CSharp/Tests/UseImplicitOrExplicitType/UseImplicitTypeTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/TypeStyle/CSharpUseImplicitTypeHelper.cs
Labels: Area-IDE, untriaged, VSCode

#76163 Clamp selections within a string literal so they do not go outside of it
  src/EditorFeatures/CSharp/TextStructureNavigation/CSharpTextStructureNavigatorProvider.cs
  src/EditorFeatures/CSharpTest/TextStructureNavigation/TextStructureNavigatorTests.cs
  src/EditorFeatures/Core/TextStructureNavigation/AbstractTextStructureNavigatorProvider.TextStructureNavigator.cs
  src/EditorFeatures/Core/TextStructureNavigation/AbstractTextStructureNavigatorProvider.cs
  src/EditorFeatures/VisualBasic/TextStructureNavigation/VisualBasicTextStructureNavigatorProvider.vb
Labels: Area-IDE, untriaged

#76161 Fix issue trying to generate fields/properties from a top level program
  src/Analyzers/CSharp/CodeFixes/GenerateVariable/CSharpGenerateVariableCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/GenerateVariable/AbstractGenerateVariableService.State.cs
  src/Analyzers/Core/CodeFixes/GenerateVariable/AbstractGenerateVariableService.cs
  src/Features/CSharpTest/GenerateVariable/GenerateVariableTests.cs
Labels: Area-IDE, untriaged, VSCode

#76167 Fix info for implicit objects in find-references
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.ConstructorSymbols.vb
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
Labels: Area-IDE, untriaged, VSCode

#76196 Update xunit
  eng/Directory.Packages.props
  src/Compilers/CSharp/Test/Emit3/FirstClassSpanTests.cs
  src/Compilers/Core/CodeAnalysisTest/AnalyzerAssemblyLoaderTests.cs
  src/EditorFeatures/CSharpTest/CodeActions/SyncNamespace/CSharpSyncNamespaceTestsBase.cs
  src/EditorFeatures/CSharpTest/Interactive/NavigateTo/InteractiveNavigateToTests.cs
  src/EditorFeatures/CSharpTest/NavigateTo/NavigateToTests.cs
  src/EditorFeatures/Test/Completion/CompletionServiceTests.cs
  src/EditorFeatures/Test/SymbolFinder/DependentTypeFinderTests.cs
  src/LanguageServer/ProtocolUnitTests/CodeActions/CodeActionsTests.cs
  src/Tools/TestDiscoveryWorker/Program.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
  src/Workspaces/MSBuildTest/VisualStudioMSBuildWorkspaceTests.cs
Labels: Area-Infrastructure, Community, untriaged, VSCode

#76170 Support name completion on generic types
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationName/DeclarationNameInfo.cs
Labels: Area-IDE, untriaged, VSCode

#76173 Disable 'use coalesce expression' when statements cross a PP boundary
  src/Analyzers/CSharp/Analyzers/UseCoalesceExpression/CSharpUseCoalesceExpressionForIfNullStatementCheckDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/UseCoalesceExpression/UseCoalesceExpressionForIfNullStatementCheckTests.cs
  src/Analyzers/Core/Analyzers/UseCoalesceExpression/AbstractUseCoalesceExpressionForIfNullCheckDiagnosticAnalyzer.cs
Labels: Area-IDE, untriaged, VSCode

#76172 Keep cast that prevents the compiler from warning about an unintentional implicit object cast.
  src/Analyzers/CSharp/Tests/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Simplification/Simplifiers/CastSimplifier.cs
Labels: Area-IDE, untriaged, VSCode

#76174 Update type inference in a primary constructor base type
  src/Analyzers/CSharp/Tests/GenerateMethod/GenerateMethodTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpTypeInferenceService.cs
Labels: Area-IDE, untriaged, VSCode

#76164 Add more tests for https://github.com/dotnet/roslyn/pull/76083
  src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs
Labels: Area-IDE, untriaged, VSCode

#76175 Fix wrapping issues in simplify conditional
  src/Analyzers/CSharp/Tests/SimplifyBooleanExpression/SimplifyConditionalTests.cs
  src/Analyzers/Core/CodeFixes/SimplifyBooleanExpression/SimplifyConditionalCodeFixProvider.cs
Labels: Area-IDE, untriaged, VSCode

#76176 Filter out certain compiler attributes when extracting an interface
  src/EditorFeatures/CSharpTest/ExtractInterface/ExtractInterfaceTests.cs
  src/EditorFeatures/TestUtilities/ExtractInterface/ExtractInterfaceTestState.cs
  src/Features/Core/Portable/ExtractInterface/AbstractExtractInterfaceService.cs
  src/Workspaces/Core/Portable/Shared/Extensions/IParameterSymbolExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CodeGeneration/MethodGenerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/IParameterSymbolExtensions.cs
Labels: Area-IDE, untriaged, VSCode

#76177 Update suggestion mode provider to support params collections
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SuggestionModeCompletionProviderTests.cs
  src/EditorFeatures/Test2/Diagnostics/ImplementInterface/ImplementInterfaceCrossLanguageTests.vb
  src/Features/CSharp/Portable/Completion/CompletionProviders/CSharpSuggestionModeCompletionProvider.cs
Labels: Area-IDE, untriaged, VSCode

#76179 Do not pass primary constructor parameters explicit when extracting methods
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
Labels: Area-IDE, untriaged, VSCode

#76228 fix flaky lsp diagnostic test
  src/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
Labels: Area-IDE, untriaged, VSCode

#76184 Do not duplicate directives when converting from property to methods
  src/Features/CSharp/Portable/ReplacePropertyWithMethods/CSharpReplacePropertyWithMethodsService.cs
  src/Features/CSharpTest/ReplacePropertyWithMethods/ReplacePropertyWithMethodsTests.cs
  src/Features/Core/Portable/ReplacePropertyWithMethods/ReplacePropertyWithMethodsCodeRefactoringProvider.cs
Labels: Area-IDE, untriaged, VSCode

#76181 Support nint/intptr conversion on c# 11 and up
  src/Analyzers/CSharp/Tests/ReplaceDefaultLiteral/ReplaceDefaultLiteralTests.cs
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs
  src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpPreferFrameworkTypeDiagnosticAnalyzer.cs
  src/Features/CSharpTest/PreferFrameworkType/PreferFrameworkTypeTests.cs
  src/Features/CSharpTest/SimplifyTypeNames/SimplifyTypeNamesTests.cs
  src/Workspaces/CSharp/Portable/Simplification/Simplifiers/AbstractCSharpSimplifier.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SemanticModelExtensions.cs
Labels: Area-IDE, untriaged, VSCode

#76045 Update Copilot rename telemetry
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameViewModel.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameViewModel_Telemetry.cs
  src/EditorFeatures/Core.Wpf/Lightup/ISmartRenameSessionWrapper.cs
Labels: Area-IDE, Community, untriaged

#76187 Have go-to-def flip between partial definition and implementation
  src/EditorFeatures/Core/Navigation/AbstractDefinitionLocationService.cs
  src/EditorFeatures/Test2/GoToDefinition/CSharpGoToDefinitionTests.vb
  src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionCommandHandlerTests.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
Labels: Area-IDE, untriaged, VSCode

#76108 Fix incorrect codespit of xml doc comments
  src/EditorFeatures/CSharp/DocumentationComments/DocumentationCommentCommandHandler.cs
  src/EditorFeatures/CSharpTest/DocumentationComments/DocumentationCommentTests.cs
  src/EditorFeatures/Core/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs
  src/Features/CSharp/Portable/DocumentationComments/CSharpDocumentationCommentSnippetService.cs
  src/Features/Core/Portable/DocumentationComments/AbstractDocumentationCommentSnippetService.cs
Labels: Area-IDE, untriaged, VSCode

#76186 Keep member bodies when converting DIM property to method
  src/Features/CSharpTest/ReplacePropertyWithMethods/ReplacePropertyWithMethodsTests.cs
  src/Features/Core/Portable/ReplacePropertyWithMethods/ReplacePropertyWithMethodsCodeRefactoringProvider.cs
Labels: Area-IDE, untriaged, VSCode

#75953 Fix switch indentation for list patterns
  src/Workspaces/CSharpTest/Formatting/CSharpFormattingTestBase.cs
  src/Workspaces/CSharpTest/Formatting/FormattingTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/IndentBlockFormattingRule.cs
Labels: Area-IDE, Community, untriaged, VSCode

#76127 VBOverloadResolutionPriority: clone remaining C# tests for the feature
  src/Compilers/CSharp/Test/Emit3/OverloadResolutionPriorityTests.cs
  src/Compilers/VisualBasic/Test/Semantic/Semantics/OverloadResolutionPriorityTests.vb
Labels: Area-Compilers, Feature - Overload Resolution Priority

#65830 Enable CA1052 (static holder types should be static)
  eng/config/globalconfigs/Common.globalconfig
  src/Analyzers/VisualBasic/Tests/GenerateMethod/GenerateConversionTests.vb
  src/Analyzers/VisualBasic/Tests/SimplifyLinqExpression/VisualBasicSimplifyLinqExpressionFixAllTests.vb
  src/Compilers/.editorconfig
  src/EditorFeatures/CSharpTest/Diagnostics/NamingStyles/EditorConfigNamingStyleParserTests.cs
  src/EditorFeatures/CSharpTest/Intents/IntentTestsBase.cs
  src/EditorFeatures/Test/EditorConfigSettings/Data/CodeStyleSettingsTest.cs
  src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionTestsBase.vb
  src/EditorFeatures/VisualBasicTest/ExtractMethod/ExtractMethodTests.ControlFlowAnalysis.vb
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/LanguageServerFatalError.cs
  src/Scripting/CoreTestUtilities/ScriptingTestHelpers.cs
  src/Test/PdbUtilities/Reader/Token2SourceLineExporter.cs
  src/Test/Perf/StackDepthTest/Program.cs
  src/Test/Perf/Utilities/TraceManager.cs
  src/Test/Perf/tests/helloworld/HelloWorld.cs
  src/Tools/BuildActionTelemetryTable/Program.cs
  src/Tools/IdeCoreBenchmarks/ProjectOperationBenchmarks.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/AutomationElementHelper.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/TestUtilities.cs
  src/Workspaces/CoreTest/EditorConfigStorageLocation/NamingStylePreferenceEditorConfigStorageLocationTests.cs
  src/Workspaces/CoreTestUtilities/NoCompilationConstants.cs
  src/Workspaces/CoreTestUtilities/SolutionUtilities.cs
Labels: Area-Infrastructure, Community, VSCode

#76231 Fix equivalence check for nint/IntPtr
  src/Analyzers/CSharp/Tests/ReplaceDefaultLiteral/ReplaceDefaultLiteralTests.cs
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs
  src/Features/CSharpTest/PreferFrameworkType/PreferFrameworkTypeTests.cs
  src/Features/CSharpTest/SimplifyTypeNames/SimplifyTypeNamesTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SemanticModelExtensions.cs
Labels: Area-IDE, untriaged, VSCode

#76118 Add support for 'find refs' finding references to 'dynamic'
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.DynamicTypeSymbol.vb
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/DependentProjectsFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/DynamicTypeSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ReferenceFinders.cs
Labels: Area-IDE, untriaged, VSCode

#76221 Update find-refs to find references to Dispose in a using-statement
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.OrdinaryMethodSymbols.vb
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/OrdinaryMethodReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/Shared/AbstractSyntaxIndex_Persistence.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Create.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE, untriaged, VSCode

#76223 Fix override implementation with generics and constraints
  src/Analyzers/CSharp/CodeFixes/ImplementAbstractClass/CSharpImplementAbstractClassCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/ImplementAbstractClass/ImplementAbstractClassTests.cs
  src/Analyzers/Core/CodeFixes/ImplementAbstractClass/AbstractImplementAbstractClassCodeFixProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CodeGeneration/MethodGenerator.cs
Labels: Area-IDE, untriaged, VSCode

#76131 Use new championed proposal and test plan for "extensions" feature
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation, Feature - Extension Everything

#76151 Support static members in extract interface
  src/EditorFeatures/CSharpTest/ExtractInterface/ExtractInterfaceTests.cs
  src/EditorFeatures/TestUtilities/ExtractInterface/AbstractExtractInterfaceTests.cs
  src/Features/Core/Portable/ExtractClass/ExtractClassWithDialogCodeAction.cs
  src/Features/Core/Portable/ExtractInterface/AbstractExtractInterfaceService.cs
  src/Features/Core/Portable/ExtractInterface/ExtractInterfaceCodeAction.cs
Labels: Area-IDE, untriaged, VSCode

#76240 Fix NFW thrown when refreshing source generated files
  src/LanguageServer/Protocol/Handler/SourceGenerators/SourceGeneratorRefreshQueue.cs
Labels: Area-IDE, untriaged, VSCode

#76220 Update FAR and Go to Def to work on indexers
  src/EditorFeatures/CSharp/InlineRename/CSharpEditorInlineRenameService.cs
  src/EditorFeatures/Core/Navigation/AbstractDefinitionLocationService.cs
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.IndexerSymbols.vb
  src/EditorFeatures/Test2/GoToDefinition/CSharpGoToDefinitionTests.vb
  src/EditorFeatures/Test2/ReferenceHighlighting/CSharpReferenceHighlightingTests.vb
  src/Features/CSharp/Portable/QuickInfo/CSharpSemanticQuickInfoProvider.cs
  src/Features/Core/Portable/FindUsages/AbstractFindUsagesService_FindReferences.cs
  src/Features/Core/Portable/GoToDefinition/AbstractGoToDefinitionSymbolService.cs
  src/Features/Core/Portable/GoToDefinition/IGoToDefinitionSymbolService.cs
  src/Features/Core/Portable/Navigation/AbstractNavigableItemsService.cs
  src/Features/Lsif/Generator/Generator.cs
  src/VisualStudio/Core/Test/GoToDefinition/GoToDefinitionApiTests.vb
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder.cs
  src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/SyntaxTreeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE, untriaged, VSCode

#76233 Add Color Scheme support for VS 2022 tinted themes.
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPage.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/ColorSchemes/ColorSchemeApplier.ClassificationVerifier.cs
  src/VisualStudio/Core/Def/ColorSchemes/ColorSchemeApplier.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPage.vb
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageStrings.vb
Labels: Area-IDE, UX Review Not Required

#76239 Skip CSharpWinForms.DeleteControl on 32 bit release
  src/Compilers/Test/Core/Assert/ConditionalFactAttribute.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpWinForms.cs
Labels: Area-IDE, untriaged

#76252 Report errors processing messages from the build host
  src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs
Labels: Area-IDE, untriaged, VSCode

#76253 Fix reproducibility of local builds
  .gitignore
  eng/test-determinism.ps1
  src/Dependencies/Collections/Microsoft.CodeAnalysis.Collections.projitems
Labels: Area-Infrastructure, untriaged

#76254 Inline Hints - Checks if names are equivalent in member access expression
  src/Features/CSharp/Portable/InlineHints/CSharpInlineParameterNameHintsService.cs
  src/Features/Core/Portable/InlineHints/AbstractInlineParameterNameHintsService.cs
  src/Features/VisualBasic/Portable/InlineHints/VisualBasicInlineParameterNameHintsService.vb
Labels: Area-IDE, untriaged, VSCode

#75224 Add option for LSP-based auto insert
  src/LanguageServer/Protocol/Handler/Configuration/DidChangeConfigurationNotificationHandler_OptionList.cs
  src/LanguageServer/Protocol/Handler/OnAutoInsert/OnAutoInsertHandler.cs
  src/LanguageServer/Protocol/LspOptionsStorage.cs
  src/LanguageServer/ProtocolUnitTests/Configuration/DidChangeConfigurationNotificationHandlerTest.cs
  src/VisualStudio/Core/Test.Next/Options/VisualStudioOptionStorageTests.cs
Labels: Area-IDE, untriaged, VSCode

#76270 Update filenames in file banners when moving a type to a new file.
  src/Analyzers/CSharp/Analyzers/FileHeaders/CSharpFileHeaderHelper.cs
  src/Analyzers/Core/Analyzers/FileHeaders/AbstractFileHeaderHelper.cs
  src/EditorFeatures/CSharpTest/CodeActions/MoveType/MoveTypeTests.MoveToNewFile.cs
  src/Features/CSharp/Portable/AddFileBanner/CSharpAddFileBannerCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/AddFileBanner/CSharpAddFileBannerNewDocumentFormattingProvider.cs
  src/Features/Core/Portable/AddFileBanner/AbstractAddFileBannerCodeRefactoringProvider.cs
  src/Features/Core/Portable/AddFileBanner/AbstractAddFileBannerNewDocumentFormattingProvider.cs
  src/Features/Core/Portable/AddFileBanner/AddFileBannerHelpers.cs
  src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.MoveTypeEditor.cs
  src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.cs
  src/Features/Core/Portable/CodeRefactorings/MoveType/MoveTypeCodeRefactoringProvider.cs
  src/Features/VisualBasic/Portable/AddFileBanner/VisualBasicAddFileBannerCodeRefactoringProvider.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpFileBannerFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/FileBannerFacts/AbstractFileBannerFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/FileBannerFacts/IFileBannerFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicFileBannerFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpFileBannerFactsService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/LanguageServices/VisualBasicFileBannerFactsService.vb
Labels: Area-IDE, untriaged, VSCode

#76271 Codeql suppression in SemanticSearchToolWindowImpl
  src/VisualStudio/CSharp/Impl/SemanticSearch/SemanticSearchToolWindowImpl.cs
Labels: Area-IDE, untriaged

#76258 Add "string literals in data section" feature status
  docs/Language Feature Status.md
Labels: Area-Compilers, untriaged, Feature - String Literals in Data Section as UTF8

#76050 Update Razor DynamicFile Provider
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/Razor/RazorDynamicFileChangedHandler.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/Razor/RazorDynamicFileChangedParams.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/Razor/RazorDynamicFileInfoProvider.TextChangesTextLoader.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/Razor/RazorDynamicFileInfoProvider.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/Razor/RazorInitializeHandler.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/Razor/RazorProvideDynamicFileParams.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/Razor/RazorProvideDynamicFileResponse.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/Razor/RazorRemoveDynamicFileParams.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/Razor/RazorWorkspaceListenerInitializer.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/Razor/ServerTextChange.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/Razor/ServerTextSpan.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/RazorDynamicFileInfoProvider.cs
Labels: Area-Infrastructure, untriaged, VSCode

#76149 Move off of specialized task methods
  src/EditorFeatures/CSharp/EventHookup/EventHookupCommandHandler_TabKeyCommand.cs
  src/EditorFeatures/CSharp/EventHookup/EventHookupSessionManager.cs
  src/EditorFeatures/CSharp/EventHookup/EventHookupSessionManager_EventHookupSession.cs
  src/EditorFeatures/TestUtilities/Notification/TestGlobalOperationNotificationService.cs
  src/VisualStudio/Core/Def/KeybindingReset/KeybindingResetDetector.cs
  src/VisualStudio/Core/Def/Notification/VisualStudioGlobalOperationNotificationService.cs
  src/Workspaces/Core/Portable/Notification/AbstractGlobalOperationNotificationService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/TaskExtensions.cs
Labels: Area-IDE, untriaged, VSCode

#76259 Use named pipes to connect to the BuildHost process.
  src/Workspaces/Core/MSBuild.BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj
  src/Workspaces/Core/MSBuild.BuildHost/Program.cs
  src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs
  src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj
  src/Workspaces/MSBuildTest/BuildHostProcessManagerTests.cs
Labels: Area-IDE, untriaged, VSCode

#76105 Update runtime async format to use methodimpl
  docs/compilers/CSharp/Runtime Async Design.md
Labels: Area-Compilers, Documentation, untriaged, Feature - Runtime Async

#76279 Update NuGet-packages.md
  docs/wiki/NuGet-packages.md
Labels: Area-Infrastructure, untriaged

#76185 Improve parsing recovery with 'file' keyword
  src/Analyzers/CSharp/Tests/ImplementAbstractClass/ImplementAbstractClassTests.cs
  src/Analyzers/Core/CodeFixes/ImplementAbstractClass/AbstractImplementAbstractClassCodeFixProvider.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/FileModifierParsingTests.cs
Labels: Area-Compilers, Feature - File-Local Types, VSCode

#76272 Emit multiple deltas for a project with multiple baselines
  src/Features/Core/Portable/EditAndContinue/DebuggingSession.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/Core/Portable/EditAndContinue/ProjectBaseline.cs
  src/Features/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
Labels: Area-Interactive, untriaged, VSCode

#76286 Remove OfferRemoveUnusedReferencesFlag
  src/EditorFeatures/Core/Shared/Options/FeatureOnOffOptions.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/UnusedReferences/RemoveUnusedReferencesCommandHandler.cs
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageStrings.vb
Labels: Area-IDE, untriaged, Needs UX Triage

#76291 Enable LSP go to definition on string literals
  src/LanguageServer/Protocol/Handler/Definitions/AbstractGoToDefinitionHandler.cs
  src/LanguageServer/ProtocolUnitTests/Definitions/GoToDefinitionTests.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder.cs
Labels: Area-IDE, untriaged, VSCode

#76285 Add support for getting debugger data tips through LSP.
  src/EditorFeatures/CSharpTest/Debugging/DataTipInfoGetterTests.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/VSTypeScriptDebugDataTipInfoWrapper.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptLanguageDebugInfoService.cs
  src/EditorFeatures/Core/LanguageServer/AlwaysActivateInProcLanguageClient.cs
  src/EditorFeatures/TestUtilities/Debugging/AbstractDataTipInfoGetterTests.cs
  src/EditorFeatures/VisualBasicTest/Debugging/DataTipInfoGetterTests.vb
  src/Features/CSharp/Portable/Debugging/CSharpLanguageDebugInfoService.cs
  src/Features/CSharp/Portable/Debugging/DataTipInfoGetter.cs
  src/Features/Core/Portable/Debugging/AbstractDataTipInfoGetter.cs
  src/Features/Core/Portable/Debugging/DebugDataTipInfo.cs
  src/Features/Core/Portable/Debugging/ILanguageDebugInfoService.cs
  src/Features/VisualBasic/Portable/Debugging/DataTipInfoGetter.vb
  src/Features/VisualBasic/Portable/Debugging/VisualBasicLanguageDebugInfoService.vb
  src/LanguageServer/Protocol/Handler/Breakpoints/ValidateBreakableRangeHandler.cs
  src/LanguageServer/Protocol/Handler/DataTips/DataTipRangeHandler.cs
  src/LanguageServer/Protocol/Protocol/Internal/VSInternalDataTips.cs
  src/LanguageServer/Protocol/Protocol/Internal/VSInternalMethods.cs
  src/LanguageServer/Protocol/Protocol/Internal/VSInternalServerCapabilities.cs
  src/LanguageServer/ProtocolUnitTests/DataTips/DataTipRangeHandlerTests.cs
  src/LanguageServer/ProtocolUnitTests/ValidateBreakableRange/ValidateBreakableRangeTests.cs
  src/VisualStudio/Core/Def/Implementation/AbstractVsTextViewFilter.cs
  src/VisualStudio/ExternalAccess/FSharp/Editor/Implementation/Debugging/FSharpDebugDataTipInfo.cs
  src/VisualStudio/ExternalAccess/FSharp/Internal/Editor/Implementation/Debugging/FSharpLanguageDebugInfoService.cs
Labels: Area-IDE, untriaged, VSCode

#76292 Use variable instead of value for parameter completion items
  src/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
Labels: Area-Infrastructure, untriaged, VSCode

#76238 Fix go-to-def on an abstract explicit impl of an interface method
  src/EditorFeatures/CSharpTest/CodeActions/ImplementInterface/ImplementImplicitlyTests.cs
  src/EditorFeatures/Test2/GoToDefinition/CSharpGoToDefinitionTests.vb
  src/Features/CSharp/Portable/ImplementInterface/AbstractChangeImplementationCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/ImplementInterface/CSharpImplementImplicitlyCodeRefactoringProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ISymbolExtensions.cs
Labels: Area-IDE, untriaged, VSCode

#76289 Fix broken strings in Unified Setting page
  src/VisualStudio/CSharp/Impl/Options/IntelliSenseOptionPageStrings.cs
  src/VisualStudio/CSharp/Impl/PackageRegistration.pkgdef
  src/VisualStudio/CSharp/Impl/UnifiedSettings/csharpSettings.registration.json
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/VisualBasic/Impl/PackageRegistration.pkgdef
  src/VisualStudio/VisualBasic/Impl/UnifiedSettings/visualBasicSettings.registration.json
Labels: Area-IDE, untriaged

#76293 Expose inline completion to Razor for cohosting
  src/LanguageServer/Protocol/Handler/InlineCompletions/InlineCompletionsHandler.cs
  src/LanguageServer/Protocol/Handler/InlineCompletions/XmlSnippetParser.cs
  src/LanguageServer/Protocol/Handler/RequestContext.cs
  src/Tools/ExternalAccess/Razor/Cohost/Handlers/Completion.cs
Labels: Area-IDE, untriaged, VSCode

#76275 Fix directive placement when removing nodes using syntax API.
  src/Compilers/CSharp/Portable/Syntax/SyntaxNodeRemover.cs
  src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNodeTests.cs
  src/Compilers/VisualBasic/Portable/Syntax/SyntaxNodeRemover.vb
  src/Compilers/VisualBasic/Test/Syntax/TestSyntaxNodes.vb
  src/EditorFeatures/CSharpTest/CodeActions/MoveType/MoveTypeTests.MoveToNewFile.cs
  src/EditorFeatures/DiagnosticsTestUtilities/MoveType/AbstractMoveTypeTest.cs
  src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.MoveTypeEditor.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/DirectiveSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE, untriaged, VSCode

#76302 Fix issue parsing a k:v pair element that starts with a keyword
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/CollectionExpressionParsingTests.cs
Labels: Area-Compilers, untriaged, Feature - Dictionary Expressions

#76294 Do not format nodes when only changing their namespace name.
  src/Analyzers/CSharp/Tests/MatchFolderAndNamespace/CSharpMatchFolderAndNamespaceTests.cs
  src/EditorFeatures/CSharpTest/CodeActions/SyncNamespace/SyncNamespaceTests_ChangeNamespace.cs
  src/EditorFeatures/CSharpTest/MoveToNamespace/MoveToNamespaceTests.cs
  src/EditorFeatures/DiagnosticsTestUtilities/MoveToNamespace/AbstractMoveToNamespaceTests.cs
  src/EditorFeatures/DiagnosticsTestUtilities/MoveType/AbstractMoveTypeTest.cs
  src/Features/CSharp/Portable/CodeRefactorings/MoveType/CSharpMoveTypeService.cs
  src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs
  src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.MoveTypeNamespaceScopeEditor.cs
  src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.cs
  src/Features/Core/Portable/CodeRefactorings/SyncNamespace/AbstractChangeNamespaceService.cs
  src/Features/Core/Portable/MoveToNamespace/AbstractMoveToNamespaceCodeAction.MoveItemsToNamespaceCodeAction.cs
  src/Features/Core/Portable/MoveToNamespace/AbstractMoveToNamespaceCodeAction.MoveTypeToNamespaceCodeAction.cs
  src/Features/Core/Portable/MoveToNamespace/AbstractMoveToNamespaceService.cs
  src/Features/Core/Portable/MoveToNamespace/MoveToNamespaceCodeAction.cs
  src/Features/Core/Portable/MoveToNamespace/MoveToNamespaceCodeActionProvider.cs
  src/Features/VisualBasic/Portable/CodeRefactorings/MoveType/VisualBasicMoveTypeService.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
Labels: Area-IDE, untriaged, VSCode

#76273 Update SystemTextJsonVersion
  eng/Versions.props
Labels: Area-Infrastructure, Community, untriaged

#76313 Allow moving static members between different type kinds
  src/Features/CSharp/Portable/CodeRefactorings/MoveStaticMembers/CSharpMoveStaticMembersRefactoringProvider.cs
  src/VisualStudio/Core/Def/MoveStaticMembers/VisualStudioMoveStaticMembersOptionsService.cs
  src/VisualStudio/Core/Test/MoveStaticMembers/MoveStaticMembersViewModelTest.vb
Labels: Area-IDE, untriaged, VSCode

#76311 Fix formatting of an empty statement on the same line as another statement
  src/Analyzers/CSharp/Analyzers/NewLines/EmbeddedStatementPlacement/EmbeddedStatementPlacementDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/NewLines/EmbeddedStatementPlacement/EmbeddedStatementPlacementTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/TokenBasedFormattingRule.cs
Labels: Area-IDE, untriaged, VSCode

#76295 Fix issue with vb's "move type" moving more than just the type requested.
  src/EditorFeatures/VisualBasicTest/CodeActions/MoveType/MoveTypeTests.MoveToNewFile.vb
  src/Features/CSharp/Portable/CodeRefactorings/MoveType/CSharpMoveTypeService.cs
  src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.Editor.cs
  src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.MoveTypeCodeAction.cs
  src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.MoveTypeEditor.cs
  src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.MoveTypeNamespaceScopeEditor.cs
  src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.RenameFileEditor.cs
  src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.RenameTypeEditor.cs
  src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.State.cs
  src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.cs
  src/Features/VisualBasic/Portable/CodeRefactorings/MoveType/VisualBasicMoveTypeService.vb
Labels: Area-IDE, untriaged, VSCode

#76309 Use TotalMilliseconds instead of TimeSpan in delay telemetry
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameViewModel_Telemetry.cs
Labels: Area-IDE, Community, untriaged

#76318 Change value tracking to verify a parameter is used when mapping from that parameter to it's callers
  src/EditorFeatures/Test/ValueTracking/CSharpValueTrackingTests.cs
  src/Features/Core/Portable/ValueTracking/ValueTracker.FindReferencesProgress.cs
  src/Features/Core/Portable/ValueTracking/ValueTracker.cs
Labels: Area-IDE, untriaged, VSCode

#76320 Do not remove parentheses when it would cause a parsing change in a 'when clause'
  src/Analyzers/CSharp/Tests/RemoveUnnecessaryParentheses/RemoveUnnecessaryExpressionParenthesesTests.cs
  src/Analyzers/CSharp/Tests/RemoveUnnecessaryParentheses/RemoveUnnecessaryPatternParenthesesTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs
Labels: Area-IDE, untriaged, VSCode

#76321 Handle trivial case in 'use null propagation'
  src/Analyzers/CSharp/Analyzers/UseNullPropagation/CSharpUseNullPropagationDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/UseNullPropagation/UseNullPropagationTests.cs
  src/Analyzers/Core/Analyzers/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs
  src/Analyzers/Core/CodeFixes/UseNullPropagation/AbstractUseNullPropagationCodeFixProvider.cs
Labels: Area-IDE, untriaged, VSCode

#76319 Preserve comment inside class body when switching to primary constructor
  src/Analyzers/CSharp/CodeFixes/UsePrimaryConstructor/CSharpUsePrimaryConstructorCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UsePrimaryConstructor/UsePrimaryConstructorTests.cs
Labels: Area-IDE, untriaged, VSCode

#76324 Update add/remove accessibility modifiers for interfaces
  src/Analyzers/CSharp/Analyzers/AddAccessibilityModifiers/CSharpAddAccessibilityModifiers.cs
  src/Analyzers/CSharp/Analyzers/AddAccessibilityModifiers/CSharpAddAccessibilityModifiersDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/AddAccessibilityModifiers/AddAccessibilityModifiersTests.cs
  src/Analyzers/Core/Analyzers/AddAccessibilityModifiers/AbstractAddAccessibilityModifiersDiagnosticAnalyzer.cs
  src/Analyzers/Core/CodeFixes/AddAccessibilityModifiers/AddAccessibilityModifiersHelpers.cs
Labels: Area-IDE, untriaged, VSCode

#76325 Attempt to reuse 'nameof' expressions in attributes when converting from a local function to a method
  src/Analyzers/CSharp/CodeFixes/UsePrimaryConstructor/CSharpUsePrimaryConstructorCodeFixProvider.cs
  src/Features/CSharpTest/ConvertLocalFunctionToMethod/ConvertLocalFunctionToMethodTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CodeGeneration/AttributeGenerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeGeneration/CodeGenerationHelpers.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/CodeGeneration/AttributeGenerator.vb
Labels: Area-IDE, untriaged, VSCode

#76326 Center the symbol being navigated to when navigating through doc-outline
  src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineView.xaml.cs
Labels: Area-IDE, untriaged

#76327 Add f1 item for global usings
  src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs
  src/VisualStudio/CSharp/Test/F1Help/F1HelpTests.cs
Labels: Area-IDE, untriaged

#76335 Fix issue with nameof(MemberGroup) caused us to consider all members used
  src/Analyzers/CSharp/Tests/RemoveUnusedMembers/RemoveUnusedMembersTests.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs
Labels: Area-IDE, untriaged, VSCode

#76332 Update 'sort usings' to always preserve the new-lines that were present in the document
  src/EditorFeatures/Core/Organizing/OrganizeDocumentCommandHandler.cs
  src/Workspaces/CSharp/Portable/OrganizeImports/CSharpOrganizeImportsService.Rewriter.cs
  src/Workspaces/CSharp/Portable/OrganizeImports/CSharpOrganizeImportsService.cs
  src/Workspaces/CSharpTest/OrganizeImports/OrganizeUsingsTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/UsingsAndExternAliasesOrganizer.cs
Labels: Area-IDE, untriaged, VSCode

#76328 Unify user experience with disparate 'generate constructor' features
  src/Analyzers/CSharp/Tests/GenerateDefaultConstructors/GenerateDefaultConstructorsTests.cs
  src/Analyzers/Core/CodeFixes/GenerateDefaultConstructors/IGenerateDefaultConstructorsService.cs
  src/EditorFeatures/CSharpTest/GenerateConstructors/GenerateConstructorsTests.cs
  src/EditorFeatures/VisualBasicTest/GenerateConstructors/GenerateConstructorsTests.vb
  src/Features/CSharp/Portable/GenerateConstructors/CSharpGenerateConstructorsCodeRefactoringProvider.cs
  src/Features/Core/Portable/AddConstructorParametersFromMembers/AddConstructorParametersFromMembersCodeRefactoringProvider.AddConstructorParametersCodeAction.cs
  src/Features/Core/Portable/AddConstructorParametersFromMembers/AddConstructorParametersFromMembersCodeRefactoringProvider.State.cs
  src/Features/Core/Portable/AddConstructorParametersFromMembers/AddConstructorParametersFromMembersCodeRefactoringProvider.cs
  src/Features/Core/Portable/CodeRefactorings/PredefinedCodeRefactoringProviderNames.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/GenerateConstructors/AbstractGenerateConstructorsCodeRefactoringProvider.ConstructorDelegatingCodeAction.cs
  src/Features/Core/Portable/GenerateConstructors/AbstractGenerateConstructorsCodeRefactoringProvider.FieldDelegatingCodeAction.cs
  src/Features/Core/Portable/GenerateConstructors/AbstractGenerateConstructorsCodeRefactoringProvider.GenerateConstructorWithDialogCodeAction.cs
  src/Features/Core/Portable/GenerateConstructors/AbstractGenerateConstructorsCodeRefactoringProvider.State.cs
  src/Features/Core/Portable/GenerateConstructors/AbstractGenerateConstructorsCodeRefactoringProvider.cs
  src/Features/Core/Portable/GenerateDefaultConstructors/GenerateDefaultConstructorsCodeRefactoringProvider.cs
  src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider.cs
  src/Features/Core/Portable/GenerateFromMembers/AbstractGenerateFromMembersCodeRefactoringProvider.SelectedMemberInfo.cs
  src/Features/Core/Portable/GenerateFromMembers/GenerateFromMembersHelpers.cs
  src/Features/Core/Portable/GenerateFromMembers/SelectedMemberInfo.cs
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Features/VisualBasic/Portable/GenerateConstructors/VisualBasicGenerateConstructorsCodeRefactoringProvider.vb
  src/Tools/ExternalAccess/Razor/RazorPredefinedCodeRefactoringProviderNames.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicGenerateConstructorDialog.cs
Labels: Area-IDE, untriaged, VSCode

#76330 Generate delegating constructor should make the implicit no-arg constructor explicit to preserve binary and source compat
  src/Analyzers/CSharp/Tests/GenerateDefaultConstructors/GenerateDefaultConstructorsTests.cs
  src/Analyzers/Core/CodeFixes/CodeFixes.projitems
  src/Analyzers/Core/CodeFixes/GenerateDefaultConstructors/AbstractGenerateDefaultConstructorsService.CodeAction.cs
  src/Analyzers/Core/CodeFixes/GenerateDefaultConstructors/AbstractGenerateDefaultConstructorsService.CodeActionAll.cs
  src/Analyzers/Core/CodeFixes/GenerateDefaultConstructors/AbstractGenerateDefaultConstructorsService.State.cs
  src/Analyzers/Core/CodeFixes/GenerateDefaultConstructors/AbstractGenerateDefaultConstructorsService.cs
  src/Analyzers/Core/CodeFixes/GenerateDefaultConstructors/GenerateDefaultConstructorsCodeAction.cs
Labels: Area-IDE, untriaged, VSCode

#76340 Clean up extract method tests
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodBase.cs
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodMiscellaneousTests.cs
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.LanguageInteraction.cs
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs
  src/EditorFeatures/CSharpTest/ExtractMethod/SelectionValidatorTests.cs
Labels: Area-IDE, untriaged

#76315 Improve formatting in 'convert anon type to tuple'
  src/Features/CSharp/Portable/ConvertAnonymousType/CSharpConvertAnonymousTypeToTupleCodeRefactoringProvider.cs
  src/Features/CSharpTest/ConvertAnonymousType/ConvertAnonymousTypeToTupleTests.cs
Labels: Area-IDE, untriaged, VSCode

#76331 Make it clearer when 'move declaration' might change semantics
  src/Analyzers/Core/CodeFixes/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs
  src/Features/CSharp/Portable/MoveDeclarationNearReference/CSharpMoveDeclarationNearReferenceCodeRefactoringProvider.cs
  src/Features/CSharpTest/MoveDeclarationNearReference/MoveDeclarationNearReferenceTests.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/MoveDeclarationNearReference/AbstractMoveDeclarationNearReferenceCodeRefactoringProvider.cs
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Features/VisualBasic/Portable/MoveDeclarationNearReference/VisualBasicMoveDeclarationNearRefactoringProvider.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/MoveDeclarationNearReference/AbstractMoveDeclarationNearReferenceService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/MoveDeclarationNearReference/IMoveDeclarationNearReferenceService.cs
Labels: Area-IDE, untriaged, VSCode

#76333 Fix formatting of accessor blocks in 'use block body'
  src/Analyzers/CSharp/Analyzers/UseExpressionBody/Helpers/UseExpressionBodyForAccessorsHelper.cs
  src/Analyzers/CSharp/Tests/UseExpressionBody/UseExpressionBodyForAccessorsAnalyzerTests.cs
Labels: Area-IDE, untriaged, VSCode

#76338 Clarify comment on SystemTextJsonVersion
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#76317 Fix broken 'convert if to switch' case with recursive analysis
  src/Features/CSharp/Portable/ConvertIfToSwitch/CSharpConvertIfToSwitchCodeRefactoringProvider.cs
  src/Features/CSharpTest/ConvertIfToSwitch/ConvertIfToSwitchTests.cs
  src/Features/Core/Portable/ConvertIfToSwitch/AbstractConvertIfToSwitchCodeRefactoringProvider.Analyzer.cs
Labels: Area-IDE, untriaged, VSCode

#76334 Indent expressions when converting to object initializer
  src/Analyzers/CSharp/CodeFixes/UseObjectInitializer/CSharpUseObjectInitializerCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseObjectInitializer/UseObjectInitializerTests.cs
  src/Analyzers/Core/CodeFixes/UseObjectInitializer/AbstractUseObjectInitializerCodeFixProvider.cs
  src/Analyzers/VisualBasic/CodeFixes/UseObjectInitializer/VisualBasicUseObjectInitializerCodeFixProvider.vb
  src/Analyzers/VisualBasic/Tests/UseObjectInitializer/UseObjectInitializerTests.vb
Labels: Area-IDE, untriaged, VSCode

#76336 Fix issue with remove unused members and ref-fields
  src/Analyzers/CSharp/Tests/RemoveUnusedMembers/RemoveUnusedMembersTests.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs
Labels: Area-IDE, untriaged, VSCode

#76343 Do not pull out 'using local decl' variables unnecessarily in extract method.
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.LanguageInteraction.cs
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.Analyzer.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.StatementResult.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Features/Core/Portable/ExtractMethod/SelectionResult.cs
Labels: Area-IDE, untriaged, VSCode

#76348 Remove unnecessary parentheses from spread elements
  src/Analyzers/CSharp/Tests/RemoveUnnecessaryParentheses/RemoveUnnecessaryExpressionParenthesesTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs
Labels: Area-IDE, untriaged, VSCode

#76353 Disable signing validation for the PR Val pipeline.
  azure-pipelines-pr-validation.yml
Labels: Area-Infrastructure, untriaged

#76337 Support adding package and reference assemblies from an import
  src/EditorFeatures/CSharpTest/CodeActions/AddUsing/AddUsingNuGetTests.cs
  src/EditorFeatures/VisualBasicTest/CodeActions/AddImport/AddImportTests_NuGet.vb
  src/Features/CSharp/Portable/AddImport/CSharpAddImportCodeFixProvider.cs
  src/Features/CSharp/Portable/AddImport/CSharpAddImportFeatureService.cs
  src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs
  src/Features/Core/Portable/AddImport/References/AssemblyReference.cs
  src/Features/Core/Portable/AddImport/References/PackageReference.cs
  src/Features/Core/Portable/AddImport/References/Reference.cs
  src/Features/Core/Portable/AddImport/References/SymbolReference.cs
  src/Features/Core/Portable/AddImport/Remote/AbstractAddImportFeatureService_Remote.cs
  src/Features/Core/Portable/AddImport/Remote/IRemoteMissingImportDiscoveryService.cs
  src/Features/Core/Portable/AddImport/Remote/RemoteMissingImportDiscoveryServiceCallbackDispatcher.cs
  src/Features/Core/Portable/AddImport/SymbolReferenceFinder.cs
  src/Features/Core/Portable/AddImport/SymbolReferenceFinder_PackageAssemblySearch.cs
  src/Features/Core/Portable/SymbolSearch/SymbolSearchUpdateNoOpEngine.cs
  src/Features/Core/Portable/SymbolSearch/Windows/SymbolSearchUpdateEngine.cs
  src/Features/Core/Portable/SymbolSearch/Windows/SymbolSearchUpdateEngineProxy.cs
  src/Features/VisualBasic/Portable/AddImport/VisualBasicAddImportFeatureService.vb
  src/VisualStudio/Core/Def/SymbolSearch/VisualStudioSymbolSearchService.cs
  src/Workspaces/Core/Portable/SymbolSearch/IRemoteSymbolSearchUpdateEngine.cs
  src/Workspaces/Core/Portable/SymbolSearch/ISymbolSearchService.cs
  src/Workspaces/Core/Portable/SymbolSearch/ISymbolSearchUpdateEngine.cs
  src/Workspaces/Remote/ServiceHub/Services/MissingImportDiscovery/RemoteMissingImportDiscoveryService.cs
  src/Workspaces/Remote/ServiceHub/Services/SymbolSearchUpdate/RemoteSymbolSearchUpdateService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/CompilationUnitSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpAddImportsService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/CompilationUnitSyntaxExtensions.vb
Labels: Area-IDE, untriaged, VSCode

#76001 Update the Copilot powered Inline Rename UX
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameViewModel.cs
Labels: Area-IDE, Community, untriaged

#76276 Cache the MEF composition in the Roslyn LSP.
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/ExportProviderBuilderTests.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/LspFileChangeWatcherTests.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/TelemetryReporterTests.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Utilities/AbstractLanguageServerHostTests.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Utilities/LanguageServerTestComposition.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/WorkspaceProjectFactoryServiceTests.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/ExportProviderBuilder.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Program.cs
Labels: Area-IDE, LSP, VSCode

#76359 Share more code between "Generate Constructor", "Add Parameter" and "Initialize Member from Parameter"
  src/Analyzers/CSharp/CodeFixes/AddParameter/CSharpAddParameterCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/GenerateConstructor/CSharpGenerateConstructorService.cs
  src/Analyzers/CSharp/Tests/AddParameter/AddParameterTests.cs
  src/Analyzers/Core/CodeFixes/AddParameter/AbstractAddParameterCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/AddParameter/AddParameterService.cs
  src/Analyzers/Core/CodeFixes/CodeFixes.projitems
  src/Analyzers/Core/CodeFixes/GenerateConstructor/AbstractGenerateConstructorService.State.cs
  src/Analyzers/Core/CodeFixes/GenerateConstructor/AbstractGenerateConstructorService.cs
  src/Analyzers/Core/CodeFixes/GenerateConstructor/Argument.cs
  src/Analyzers/Core/CodeFixes/GenerateConstructor/GenerateConstructorHelpers.cs
  src/Analyzers/Core/CodeFixes/GenerateParameterizedMember/AbstractGenerateParameterizedMemberService.MethodSignatureInfo.cs
  src/Analyzers/Core/CodeFixes/GenerateVariable/AbstractGenerateVariableService.GenerateParameterCodeAction.cs
  src/Analyzers/VisualBasic/CodeFixes/AddParameter/VisualBasicAddParameterCodeFixProvider.vb
  src/Analyzers/VisualBasic/CodeFixes/GenerateConstructor/VisualBasicGenerateConstructorService.vb
  src/EditorFeatures/CSharpTest/CodeActions/InitializeParameter/InitializeMemberFromParameterTests.cs
  src/Features/CSharp/Portable/InitializeParameter/CSharpAddParameterCheckCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/InitializeParameter/CSharpInitializeMemberFromParameterCodeRefactoringProvider.cs
  src/Features/Core/Portable/InitializeParameter/AbstractAddParameterCheckCodeRefactoringProvider.cs
  src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs
  src/Features/Core/Portable/InitializeParameter/AbstractInitializeParameterCodeRefactoringProvider.cs
  src/Features/Core/Portable/InitializeParameter/InitializeParameterHelpersCore.cs
  src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicAddParameterCheckCodeRefactoringProvider.vb
  src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicInitializeMemberFromParameterCodeRefactoringProvider.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeGeneration/Argument.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeGeneration/ParameterName.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/Naming/IdentifierNameParts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CSharpWorkspaceExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/SemanticModelExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/InitializeParameter/CSharpInitializeParameterService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/InitializeParameter/InitializeParameterHelpers.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/InitializeParameter/AbstractInitializerParameterService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/InitializeParameter/IInitializeParameterService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/InitializeParameter/InitializeParameterHelpersCore.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/SemanticModelExtensions.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/LanguageServices/InitializeParameter/InitializeParameterHelpers.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/LanguageServices/InitializeParameter/VisualBasicInitializeParameterService.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/VisualBasicWorkspaceExtensions.projitems
Labels: Area-IDE, untriaged, VSCode

#76362 Do not add imports automatically in extract method
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs
  src/Features/CSharpTest/ExtractMethod/ExtractMethodTests2.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.vb
Labels: Area-IDE, untriaged, VSCode

#76352 Initialize fields when possible when adding parameters to constructors.
  src/Analyzers/CSharp/CodeFixes/AddParameter/CSharpAddParameterCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/AddParameter/AddParameterTests.cs
  src/Analyzers/Core/CodeFixes/AddParameter/AbstractAddParameterCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/AddParameter/AddParameterService.cs
  src/Analyzers/Core/CodeFixes/GenerateVariable/AbstractGenerateVariableService.GenerateParameterCodeAction.cs
  src/Analyzers/VisualBasic/CodeFixes/AddParameter/VisualBasicAddParameterCodeFixProvider.vb
Labels: Area-IDE, untriaged, VSCode

#76366 Ensure that 'extract method' follows the user's 'use this/me' preference
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs
  src/EditorFeatures/VisualBasicTest/ExtractMethod/ExtractMethodTests.LanguageInteraction.vb
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.ExpressionCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.MultipleStatementsCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.SingleStatementCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.cs
  src/Features/CSharpTest/ExtractMethod/ExtractLocalFunctionTests.cs
  src/Features/CSharpTest/ExtractMethod/ExtractMethodTests2.cs
  src/Features/Core/Portable/CodeRefactorings/ExtractMethod/AbstractExtractMethodCodeRefactoringProvider.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.cs
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.ExpressionCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.MultipleStatementsCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.SingleStatementCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.vb
  src/Features/VisualBasicTest/ExtractMethod/ExtractMethodTests.vb
  src/Workspaces/Core/Portable/ExtractMethod/ExtractMethodOptions.cs
Labels: Area-IDE, untriaged, VSCode

#76339 Handle other object initializer kinds in ref safety analysis
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
Labels: Area-Compilers, Feature - Ref Fields

#76365 Reduce allocations in AbstractRecommendationServiceBasedCompletionProvider.GetSymbolsAsync
  src/Features/Core/Portable/Completion/Providers/AbstractRecommendationServiceBasedCompletionProvider.cs
Labels: Area-IDE, untriaged, VSCode

#76368 Reduce allocations in AbstractSymbolCompletionProvider.UnionSymbols
  src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs
Labels: Area-IDE, untriaged, VSCode

#76373 Reduce allocations in CompletionItem.GetEntireDisplayText
  src/Features/Core/Portable/Completion/CompletionItem.cs
Labels: Area-IDE, untriaged, VSCode

#76369 Reduce allocations in ProjectState's ctor
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState_Checksum.cs
Labels: Area-IDE, untriaged, VSCode

#76377 Language feature status: add dictionary expressions
  docs/Language Feature Status.md
Labels: Area-Compilers, untriaged, Feature - Dictionary Expressions

#76375 Remove an enumerator allocation in SymbolCompletionItem.CreateWorker
  src/Features/CSharp/Portable/Completion/CompletionProviders/AttributeNamedParameterCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/FunctionPointerUnmanagedCallingConventionCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/NamedParameterCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/TupleNameCompletionProvider.cs
  src/Features/Core/Portable/Completion/CommonCompletionUtilities.cs
  src/Features/Core/Portable/Completion/Providers/AbstractPartialTypeCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/SymbolCompletionItem.cs
  src/Features/Core/Portable/ExternalAccess/Pythia/Api/PythiaCompletionProviderBase.cs
  src/Features/Core/Portable/IntroduceUsingStatement/AbstractIntroduceUsingStatementCodeRefactoringProvider.cs
Labels: Area-IDE, untriaged, VSCode

#76347 Do not bail generating base type initializer in the presence of use site warnings
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Test/Emit3/Microsoft.CodeAnalysis.CSharp.Emit3.UnitTests.csproj
  src/Compilers/CSharp/Test/Emit3/Semantics/RecordTests.cs
Labels: Area-Compilers, untriaged

#76378 Switch code in extract method to using immutable arrays
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.AnalyzerResult.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs
Labels: Area-IDE, untriaged, VSCode

#76376 Implement editorconfig serializer for naming style preferences (17.12)
  src/EditorFeatures/CSharpTest/Diagnostics/NamingStyles/EditorConfigNamingStyleParserTests.cs
  src/Features/TestUtilities/Options/NamingStyleTestUtilities.cs
  src/LanguageServer/Protocol/Features/Options/SolutionAnalyzerConfigOptionsUpdater.cs
  src/LanguageServer/ProtocolUnitTests/Options/SolutionAnalyzerConfigOptionsUpdaterTests.cs
  src/VisualStudio/Core/Test.Next/Options/VisualStudioOptionStorageTests.cs
  src/Workspaces/CoreTestUtilities/Options/OptionsTestHelpers.cs
  src/Workspaces/CoreTestUtilities/OptionsCollection.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/FormattingOptions2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/EditorConfig/EditorConfigNamingStyleParser.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_NamingRule.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingRule.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyleOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/Serialization/NamingStylePreferencesEditorConfigSerializer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/Serialization/SerializableNamingRule.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/Serialization/SymbolSpecification.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Options/EditorConfigValueSerializer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Options/OptionDefinition.cs
Labels: Area-IDE, untriaged, VSCode

#76382 Share more code in extract method
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.vb
Labels: Area-IDE, untriaged, VSCode

#76370 Reduce allocations in WithUsingNamespacesAndTypesBinder.GetForwardedToAssemblyInUsingNamespaces
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/Binder/WithUsingNamespacesAndTypesBinder.cs
Labels: Area-Compilers

#76361 Reduce allocations from doing repeated adds into an ImmutableDictionary in SolutionCompilationState.ComputeFrozenSnapshot
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.cs
Labels: Area-IDE, untriaged, VSCode

#76360 Update 'add parameter' to assign to field/property when adding a parameter to a primary constructor.
  src/Analyzers/CSharp/Tests/AddParameter/AddParameterTests.cs
  src/Analyzers/Core/CodeFixes/AddParameter/AbstractAddParameterCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/AddParameter/AddParameterService.cs
  src/Analyzers/Core/CodeFixes/GenerateConstructor/GenerateConstructorHelpers.cs
  src/EditorFeatures/CSharpTest/CodeActions/InitializeParameter/InitializeMemberFromParameterTests.cs
  src/Features/CSharp/Portable/InitializeParameter/CSharpInitializeMemberFromParameterCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/InitializeParameter/CSharpInitializeMemberFromPrimaryConstructorParameterCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/InitializeParameter/CSharpInitializeMemberFromPrimaryConstructorParameterCodeRefactoringProvider_Update.cs
  src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs
  src/Features/Core/Portable/InitializeParameter/AbstractInitializeParameterCodeRefactoringProvider.cs
  src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicInitializeMemberFromParameterCodeRefactoringProvider.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/InitializeParameter/CSharpInitializeParameterService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/InitializeParameter/InitializeParameterHelpers.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/FindSymbols/LinkedFileReferenceLocationEqualityComparer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/InitializeParameter/AbstractInitializerParameterService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/InitializeParameter/IInitializeParameterService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/LanguageServices/InitializeParameter/VisualBasicInitializeParameterService.vb
Labels: Area-IDE, untriaged, VSCode

#76371 Add support for extract method in the PrimaryConstructor base list
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.Analyzer.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.CallSiteContainerRewriter.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.ExpressionCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionValidator.cs
  src/Features/CSharpTest/ExtractMethod/ExtractLocalFunctionTests.cs
  src/Features/CSharpTest/ExtractMethod/ExtractMethodTests2.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.Analyzer.vb
Labels: Area-IDE, untriaged, VSCode

#75930 Consider RefSafetyRules with UnscopedRef
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 10.md
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Generated/ErrorFacts.Generated.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ThisParameterSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
Labels: Area-Compilers, untriaged

#76383 Support returning tuples in extract method when ref/out are not possible.
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodBase.cs
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
  src/Features/CSharpTest/ExtractMethod/ExtractMethodTests2.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.AnalyzerResult.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/SelectionResult.cs
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE, untriaged, VSCode

#76344 Internally identify interceptions by content hash
  src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs
Labels: Area-Compilers, untriaged, Feature - Interceptors

#76194 Fix issue where structure tag could get stuck at the wrong location
  src/EditorFeatures/Core.Wpf/Structure/StructureTaggerProvider.cs
  src/EditorFeatures/Core/Structure/AbstractStructureTaggerProvider.cs
  src/EditorFeatures/Core/Structure/StructureTag.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.cs
Labels: Area-IDE, untriaged

#76402 Fix extract method in top level
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodBase.cs
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodMiscellaneousTests.cs
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs
  src/EditorFeatures/Core/ExtractMethod/ExtractMethodCommandHandler.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionValidator.cs
  src/Features/CSharpTest/ExtractMethod/ExtractLocalFunctionTests.cs
  src/Features/CSharpTest/ExtractMethod/ExtractMethodTests2.cs
Labels: Area-IDE, untriaged, VSCode

#76404 Do not offer 'use pattern matching' when it would change semantics
  src/Analyzers/CSharp/Analyzers/UsePatternMatching/CSharpAsAndNullCheckDiagnosticAnalyzer.Analyzer.cs
  src/Analyzers/CSharp/Analyzers/UsePatternMatching/CSharpAsAndNullCheckDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/UsePatternMatching/CSharpAsAndNullCheckTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/SemanticEquivalence.cs
Labels: Area-IDE, untriaged, VSCode

#76406 Fix issue with 'use pattern matching' innapropriately capturing variables across a lambda
  src/Features/CSharp/Portable/UsePatternMatching/CSharpIsAndCastCheckWithoutNameCodeFixProvider.cs
  src/Features/CSharp/Portable/UsePatternMatching/CSharpIsAndCastCheckWithoutNameDiagnosticAnalyzer.cs
  src/Features/CSharpTest/UsePatternMatching/CSharpIsAndCastCheckWithoutNameDiagnosticAnalyzerTests.cs
Labels: Area-IDE, untriaged, VSCode

#76357 Razor synchronize loader
  src/Tools/ExternalAccess/Razor/RazorAnalyzerAssemblyResolver.cs
  src/Tools/ExternalAccess/Razor/RazorProjectExtensions.cs
Labels: Area-Compilers

#76408 Update LOC branch to 17.13
  azure-pipelines-official.yml
Labels: Area-Infrastructure, untriaged

#76380 Cache the compilation states in compilation order to avoid recalculation
  src/Compilers/Core/Portable/InternalUtilities/EnumerableExtensions.cs
  src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentStates.cs
Labels: Area-Compilers, untriaged, VSCode

#76354 Fix TFM inconsistency in BuildHost
  eng/targets/TargetFrameworks.props
Labels: Area-Infrastructure, untriaged

#76399 Optimize ProjectDependencyGraph.DoesProjectTransitivelyDependOnProject
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectDependencyGraph.cs
Labels: Area-IDE, untriaged, VSCode

#76385 Report inappropriate OverloadResolutionPriority attribute applications
  src/Compilers/CSharp/Test/Emit3/OverloadResolutionPriorityTests.cs
  src/Compilers/VisualBasic/Portable/Errors/ErrorFacts.vb
  src/Compilers/VisualBasic/Portable/Errors/Errors.vb
  src/Compilers/VisualBasic/Portable/Parser/ParserFeature.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMethodSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceNamedTypeSymbol_ComClass.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourcePropertySymbol.vb
  src/Compilers/VisualBasic/Portable/VBResources.resx
  src/Compilers/VisualBasic/Portable/xlf/VBResources.cs.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.de.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.es.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.fr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.it.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ja.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ko.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pl.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.pt-BR.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.ru.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.tr.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hans.xlf
  src/Compilers/VisualBasic/Portable/xlf/VBResources.zh-Hant.xlf
  src/Compilers/VisualBasic/Test/Semantic/Semantics/OverloadResolutionPriorityTests.vb
Labels: Area-Compilers, untriaged, Feature - Overload Resolution Priority

#76400 Rename 'scopeOfTheContainingExpression' to 'localScopeDepth'
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
Labels: Area-Compilers, untriaged

#76407 Fix issue with 'use pattern matching' where it would cause a variable to not be considered assigned
  src/Analyzers/CSharp/CodeFixes/UsePatternMatching/CSharpAsAndMemberAccessCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UsePatternMatching/CSharpAsAndMemberAccessTests.cs
Labels: Area-IDE, untriaged, VSCode

#76312 Mark interceptors feature as stable and deprecate file path based attributes
  docs/features/interceptors.md
  src/Compilers/CSharp/Portable/CSharpExtensions.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Generated/ErrorFacts.Generated.cs
  src/Compilers/CSharp/Portable/PublicAPI.Shipped.txt
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs
  src/Compilers/CSharp/Portable/Utilities/InterceptableLocation.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/EndToEnd/EndToEndTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
  src/Compilers/Core/Portable/InternalUtilities/RoslynExperiments.cs
Labels: Area-Compilers, untriaged, Needs API Review, Feature - Interceptors

#76393 Small reduction in allocations in DateAndTimeLanguageDetector
  src/Features/Core/Portable/EmbeddedLanguages/DateAndTime/LanguageServices/DateAndTimeLanguageDetector.cs
Labels: Area-IDE, untriaged, VSCode

#76413 Add two more cases for 'simplify linq expression'.
  src/Analyzers/CSharp/Analyzers/CSharpAnalyzers.projitems
  src/Analyzers/CSharp/Analyzers/SimplifyLinqExpression/CSharpSimplifyLinqTypeCheckAndCastDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/CSharpCodeFixes.projitems
  src/Analyzers/CSharp/CodeFixes/SimplifyLinqExpression/CSharpSimplifyLinqTypeCheckAndCastCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/CSharpAnalyzers.UnitTests.projitems
  src/Analyzers/CSharp/Tests/SimplifyLinqExpression/CSharpSimplifyLinqTypeCheckAndCastTests.cs
  src/Analyzers/Core/Analyzers/EnforceOnBuildValues.cs
  src/Analyzers/Core/Analyzers/IDEDiagnosticIds.cs
  src/Analyzers/Core/CodeFixes/PredefinedCodeFixProviderNames.cs
  src/Compilers/Test/Core/Traits/Traits.cs
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs
  src/EditorFeatures/Test/Diagnostics/IDEDiagnosticIDConfigurationTests.cs
  src/Features/CSharpTest/ExtractMethod/ExtractMethodCodeRefactoringTests.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Features/RulesMissingDocumentation.md
Labels: Area-IDE, untriaged, VSCode

#76358 Change PR Val builds to be unsigned
  azure-pipelines-pr-validation.yml
  eng/Signing.props
Labels: Area-Infrastructure, untriaged

#76418 Slightly reduce allocations in SymbolCompletionItem.AddSymbolInfo
  src/Features/Core/Portable/Completion/Providers/SmallNumberFormatter.cs
  src/Features/Core/Portable/Completion/Providers/SymbolCompletionItem.cs
Labels: Area-IDE, untriaged, VSCode

#76428 Revert "Localized file check-in by OneLocBuild Task: Build definition ID 327: Build ID 2600919"
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged

#76421 Move code in extract method to shared location
  src/Analyzers/CSharp/CodeFixes/UseImplicitOrExplicitType/UseExplicitTypeCodeFixProvider.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.Analyzer.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ExpressionSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxKinds.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CSharpWorkspaceExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Utilities/NullableHelpers/NullableHelpers.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Simplification/AbstractSimplificationService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Utilities/NullableHelpers.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensions.projitems
Labels: Area-IDE, untriaged, VSCode

#76351 feat(lsp): add --pipe parameter
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Utilities/LanguageServerTestComposition.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Program.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/ServerConfigurationFactory.cs
Labels: Area-IDE, Community, untriaged, VSCode

#76417 Reduce allocations again in ComputeReverseReferencesMap
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectDependencyGraph.cs
Labels: Area-IDE, untriaged, VSCode
