Repository dotnet/roslyn, pull requests merged in 2024-08, with the labels that each got.

#74608 Reduce allocations during SourceText serialization
  src/Workspaces/Core/Portable/Shared/Extensions/SourceTextExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Serialization/ObjectWriter.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/BKTree.Serialization.cs
Labels: Area-IDE, untriaged, VSCode

#74628 Modify SyntaxNodeExtensions.GetMembers to instead execute a given lambda over the collection.
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxNodeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
Labels: Area-IDE, untriaged, VSCode

#74044 Avoid span conversion in delegate extension receiver
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Symbols/ReducedExtensionMethodSymbol.cs
  src/Compilers/CSharp/Test/Emit3/FirstClassSpanTests.cs
  src/Compilers/Core/CodeAnalysisTest/Collections/ImmutableSegmentedListTest.cs
Labels: Area-Compilers, untriaged, New Feature - First-class Span Types

#74610 Change SyntaxEquivalence.AreEquivalent to use a more appropriate pooling mechanism for the stack it uses to walk trees.
  src/Compilers/CSharp/Portable/Syntax/SyntaxEquivalence.cs
Labels: Area-Compilers, untriaged

#74622 Tag PRs where any file matches the specified patterns
  .github/policies/resourceManagement.yml
Labels: Area-Infrastructure, untriaged

#73947 Parse `field` as a contextual keyword
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Generated/CSharp.Generated.g4
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Internal.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Main.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Syntax.Generated.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/Parser/SyntaxFactoryContext.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs
  src/Compilers/CSharp/Portable/Syntax/InternalSyntax/CSharpSyntaxNode.cs
  src/Compilers/CSharp/Portable/Syntax/InternalSyntax/CSharpSyntaxNodeCache.cs
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
  src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenRefReturnTests.cs
  src/Compilers/CSharp/Test/Emit2/PDB/PDBDynamicLocalsTests.cs
  src/Compilers/CSharp/Test/Emit3/FieldKeywordTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/ExpressionBodiedPropertyTests.cs
  src/Compilers/CSharp/Test/Syntax/Generated/Syntax.Test.xml.Generated.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/FieldKeywordParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Syntax/FieldAndValueKeywordTests.cs
  src/Compilers/Core/Portable/Syntax/GreenNode.cs
  src/EditorFeatures/Test/Workspaces/ClassificationTypeNamesTests.cs
Labels: Area-Compilers, untriaged

#74587 Disallow span conversions between spans which are not structs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs
  src/Compilers/CSharp/Test/Emit3/FirstClassSpanTests.cs
Labels: Area-Compilers, untriaged, New Feature - First-class Span Types

#74289 Add Solution.WithProjectInfo API
  src/Features/Core/Portable/ExternalAccess/Watch/Api/WatchHotReloadService.cs
  src/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/VisualStudio/Core/Def/CodeLens/RemoteCodeLensReferencesService.cs
  src/VisualStudio/Core/Def/FindReferences/Contexts/AbstractTableDataSourceFindUsagesContext.cs
  src/VisualStudio/Core/Def/FindReferences/Entries/AbstractDocumentSpanEntry.cs
  src/VisualStudio/Core/Def/FindReferences/Entries/DocumentSpanEntry.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/Core/Def/Workspace/VisualStudioDocumentNavigationService.cs
  src/Workspaces/Core/Portable/Diagnostics/DiagnosticData.cs
  src/Workspaces/Core/Portable/Rename/Renamer.cs
  src/Workspaces/Core/Portable/Workspace/Solution/AdditionalDocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/AnalyzerConfigDocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/DocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Project.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.TranslationAction_Actions.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratedDocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/TextDocument.cs
  src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
  src/Workspaces/Core/Portable/WorkspacesResources.resx
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.cs.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.de.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.es.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.fr.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.it.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ja.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ko.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.pl.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.pt-BR.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ru.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.tr.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.zh-Hans.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.zh-Hant.xlf
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/AddImport/AddImportPlacementOptionsProviders.cs
Labels: Area-IDE, untriaged, VSCode

#74639 Include App.config item only for net472 builds
  src/Interactive/HostProcess/x64/InteractiveHost64.csproj
Labels: Area-Interactive, untriaged

#74640 Narrow EA dependency
  src/LanguageServer/ExternalAccess/CompilerDeveloperSDK/Microsoft.CodeAnalysis.ExternalAccess.CompilerDeveloperSDK.csproj
Labels: Area-IDE, untriaged

#74420 Implement remaining span conversions
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenReadOnlySpanConstructionTest.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/ForeachTest.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/InlineArrayTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PrimaryConstructorTests.cs
  src/Compilers/CSharp/Test/Emit3/FirstClassSpanTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RawInterpolationTests_Handler.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/StructConstructorTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/Utf8StringsLiteralsTests.cs
  src/Compilers/Core/Portable/Symbols/WellKnownMemberNames.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
  src/Compilers/Test/Utilities/CSharp/TestSources.cs
Labels: Area-Compilers, untriaged, New Feature - First-class Span Types

#74509 Avoid assert in emit layer when intercepted call implicitly captures receiver to temp
  docs/features/interceptors.md
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs
Labels: Area-Compilers, untriaged

#74648 Insert release/dev17.12 to VS rel/d17.12
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#74652 Fix PR collisions
  src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs
Labels: Area-IDE, untriaged, VSCode

#74526 EnC: Implement support for System.Threading.Lock
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_LockStatement.cs
  src/Compilers/CSharp/Test/Emit2/Emit/EditAndContinue/LocalSlotMappingTests.cs
  src/Compilers/Core/Portable/InternalUtilities/OneOrMany.cs
  src/Features/CSharp/Portable/EditAndContinue/CSharpEditAndContinueAnalyzer.cs
  src/Features/CSharpTest/EditAndContinue/ActiveStatementTests.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueDiagnosticDescriptors.cs
  src/Features/Core/Portable/EditAndContinue/RudeEditKind.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Features/VisualBasic/Portable/EditAndContinue/VisualBasicEditAndContinueAnalyzer.vb
  src/Features/VisualBasicTest/EditAndContinue/ActiveStatementTests.vb
  src/Test/PdbUtilities/EditAndContinue/EditAndContinueTest.GenerationVerifier.cs
Labels: Area-Compilers, untriaged, New Feature - Lock Type

#74576 Erase extension types eagerly during translation of type symbols to Cci entities.
  src/Compilers/CSharp/Portable/Binder/ImportChain.cs
  src/Compilers/CSharp/Portable/CodeGen/CodeGenerator.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitAddress.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitArrayInitializer.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/PEDeltaAssemblyBuilder.cs
  src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/AttributeDataAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/CustomModifierAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/EventSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/FieldSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/GenericMethodInstanceReference.cs
  src/Compilers/CSharp/Portable/Emitter/Model/GenericNestedTypeInstanceReference.cs
  src/Compilers/CSharp/Portable/Emitter/Model/GenericTypeInstanceReference.cs
  src/Compilers/CSharp/Portable/Emitter/Model/MethodReference.cs
  src/Compilers/CSharp/Portable/Emitter/Model/MethodSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/NamedTypeSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs
  src/Compilers/CSharp/Portable/Emitter/Model/ParameterSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/ParameterTypeInformation.cs
  src/Compilers/CSharp/Portable/Emitter/Model/PointerTypeSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/PropertySymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/SpecializedFieldReference.cs
  src/Compilers/CSharp/Portable/Emitter/Model/SpecializedGenericMethodInstanceReference.cs
  src/Compilers/CSharp/Portable/Emitter/Model/SpecializedGenericNestedTypeInstanceReference.cs
  src/Compilers/CSharp/Portable/Emitter/Model/SpecializedNestedTypeReference.cs
  src/Compilers/CSharp/Portable/Emitter/Model/TypeMemberReference.cs
  src/Compilers/CSharp/Portable/Emitter/Model/TypeParameterSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/NoPia/EmbeddedEvent.cs
  src/Compilers/CSharp/Portable/Emitter/NoPia/EmbeddedType.cs
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncMethodToStateMachineRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/MethodToStateMachineRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/StateMachineRewriter.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/PublicSymbols/AnonymousManager.TypeOrDelegatePublicSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/PublicSymbols/AnonymousType.DelegatePublicSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/PublicSymbols/AnonymousType.TypePublicSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/ExtensionTypeEraser.cs
  src/Compilers/CSharp/Test/Emit3/ExtensionTypeTests.cs
  src/Compilers/Core/Portable/Emit/CommonPEModuleBuilder.cs
  src/Compilers/Core/Portable/Emit/Context.cs
  src/Compilers/Core/Portable/IReferenceOrISignature.cs
  src/Compilers/Core/Portable/PEWriter/MetadataVisitor.cs
  src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs
  src/Compilers/Core/Portable/PEWriter/ReferenceIndexerBase.cs
  src/Compilers/Core/Portable/Symbols/Attributes/MarshalPseudoCustomAttributeData.cs
  src/Compilers/VisualBasic/Portable/Compilation/NamespaceScopeBuilder.vb
  src/Compilers/VisualBasic/Portable/Emit/SymbolTranslator.vb
  src/Dependencies/PooledObjects/ArrayBuilder.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/EEAssemblyBuilder.cs
Labels: Area-Compilers, untriaged, New Language Feature - Roles

#74553 Avoid optimizing away ref array access
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs
  src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenRefLocalTests.cs
Labels: Area-Compilers, untriaged

#74658 CodeQL fixes
  src/Compilers/Core/CodeAnalysisTest/Emit/EmitOptionsTests.cs
  src/Compilers/Core/Portable/CryptographicHashProvider.cs
  src/Compilers/Core/Portable/PEWriter/SigningUtilities.cs
  src/Compilers/Core/Portable/Text/SourceHashAlgorithms.cs
  src/Tools/BuildBoss/CompilerNuGetCheckerUtil.cs
Labels: Area-Compilers, untriaged

#74660 Exclude BuildValidator from VMR when building without tests
  src/Tools/BuildValidator/BuildValidator.csproj
Labels: Area-Infrastructure, untriaged

#74656 Unsubscribe from UIContext events when the LSP server exits
  src/EditorFeatures/Core/Shared/Utilities/IUIContextActivationService.cs
  src/Tools/ExternalAccess/Razor/Cohost/RazorDynamicRegistrationServiceFactory.cs
  src/VisualStudio/Core/Def/Implementation/VisualStudioUIContextActivationService.cs
Labels: Area-IDE, untriaged

#74629 Update 'use auto property' to support using the `field` keyword
  src/Analyzers/CSharp/Analyzers/UseAutoProperty/CSharpUseAutoPropertyAnalyzer.cs
  src/Analyzers/CSharp/Tests/CSharpAnalyzers.UnitTests.projitems
  src/Analyzers/CSharp/Tests/UseAutoProperty/UseAutoPropertyTests.cs
  src/Analyzers/CSharp/Tests/UseAutoProperty/UseAutoPropertyTests_Field.cs
  src/Analyzers/Core/Analyzers/Analyzers.projitems
  src/Analyzers/Core/Analyzers/UseAutoProperty/AbstractUseAutoPropertyAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseAutoProperty/AccessedFields.cs
  src/Analyzers/Core/Analyzers/UseAutoProperty/AnalysisResult.cs
  src/Analyzers/Core/Analyzers/UseAutoProperty/UseAutoPropertiesHelpers.cs
  src/Analyzers/VisualBasic/Analyzers/UseAutoProperty/VisualBasicUseAutoPropertyAnalyzer.vb
  src/Features/CSharp/Portable/UseAutoProperty/CSharpUseAutoPropertyCodeFixProvider.cs
  src/Features/CSharp/Portable/UseAutoProperty/SingleLinePropertyFormattingRule.cs
  src/Features/CSharp/Portable/UseAutoProperty/UseAutoPropertyRewriter.cs
  src/Features/Core/Portable/UseAutoProperty/AbstractUseAutoPropertyCodeFixProvider.cs
  src/Features/VisualBasic/Portable/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ExpressionSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ImmutableArrayExtensions.cs
Labels: Area-IDE, untriaged, VSCode

#74663 Unify on-the-fly docs settings with C++
  src/VisualStudio/CSharp/Impl/Options/CSharpVisualStudioCopilotOptionsService.cs
Labels: Area-IDE, Community, untriaged

#74669 Remove test dependency from BuildValidator
  src/Tools/BuildValidator/BuildValidator.csproj
  src/Tools/BuildValidator/IldasmUtilities.cs
Labels: Area-Infrastructure, untriaged

#74678 Update Microsoft.VisualStudio.Debugger.Contracts to 17.12.0-beta.24403.1
  eng/Directory.Packages.props
Labels: Area-Infrastructure, Community, untriaged

#74653 Fix CG issue for Microsoft.IO.Redist
  eng/Directory.Packages.props
  src/Workspaces/Core/MSBuild.BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj
Labels: Area-Infrastructure, untriaged

#74670 Reduce allocations in AbstractSymbolCompletionProvider.CreateItems
  src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs
Labels: Area-IDE, untriaged, VSCode

#74651 Remove razor source generator hack
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.RegularCompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.RegularCompilationTracker_Generators.cs
Labels: Area-IDE, untriaged, VSCode

#74688 Only report project load events for initial load in VSCode
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/ProjectToLoad.cs
Labels: Area-Infrastructure, untriaged, VSCode

#74689 Remove most usage of "new ArrayBuilder"
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/FilterSet.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/HoistedStateMachineLocalTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/LocalsTests.cs
  src/ExpressionEvaluator/Core/Test/ResultProvider/Debugger/Engine/DkmInspectionSession.cs
  src/Features/Core/Portable/SemanticSearch/AbstractSemanticSearchService.cs
  src/Features/TestUtilities/EditAndContinue/ActiveStatementsDescription.cs
  src/LanguageServer/Protocol/Handler/Configuration/DidChangeConfigurationNotificationHandler.cs
  src/LanguageServer/Protocol/Handler/Formatting/AbstractFormatDocumentHandlerBase.cs
  src/LanguageServer/Protocol/Handler/Formatting/FormatDocumentOnTypeHandler.cs
  src/LanguageServer/Protocol/Handler/SignatureHelp/SignatureHelpHandler.cs
  src/Scripting/CSharpTest/ObjectFormatterTests.cs
  src/VisualStudio/LiveShare/Impl/ProjectsHandler.cs
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/PerfMargin/DataModel.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Formatting/FormatDocumentOnTypeHandler.cs
  src/Workspaces/Core/Portable/Options/GlobalOptionService.cs
  src/Workspaces/CoreTest/UtilityTest/NameGeneratorTests.cs
Labels: Area-Infrastructure, untriaged, VSCode

#74696 Ensure that GetContentHash produces the same value on different endian machines
  src/Compilers/Core/Portable/Text/SourceText.cs
Labels: Area-Compilers, untriaged

#74690 Rewrite BulidSolution in Integration tests
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpBuild.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicBuild.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicErrorListCommon.cs
Labels: Area-IDE, untriaged

#74700 Fix issues with VSCode LSP EA causing handlers to fail to load
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/ExportProviderBuilder.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Microsoft.CodeAnalysis.LanguageServer.csproj
  src/Tools/ExternalAccess/Xaml/External/ExportXamlLspServiceFactoryAttribute.cs
  src/Tools/ExternalAccess/Xaml/InternalAPI.Unshipped.txt
Labels: Area-IDE, untriaged, VSCode

#74710 Remove an enumerator allocation during scrolling
  src/EditorFeatures/Core/Shared/Extensions/IBufferGraphExtensions.cs
Labels: Area-IDE, untriaged

#74064 Do not mark 2 first `int` parameters of an interpolated string handler constructor as unused
  src/Analyzers/CSharp/Tests/RemoveUnusedParametersAndValues/RemoveUnusedParametersTests.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs
  src/CodeStyle/CSharp/Tests/Microsoft.CodeAnalysis.CSharp.CodeStyle.UnitTests.csproj
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ICompilationExtensions.cs
Labels: Area-IDE, Community, untriaged, VSCode

#74618 Reduce allocations in SymbolKey.ResolveString
  src/Compilers/CSharp/Portable/Symbols/PublicModel/AssemblySymbol.cs
  src/Compilers/VisualBasic/Portable/Symbols/AssemblySymbol.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/SymbolKey/SymbolKey.ModuleSymbolKey.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/SymbolKey/SymbolKey.cs
Labels: Area-Compilers, untriaged, VSCode

#74707 Modify ISyntaxTreeFactoryService.CreateSyntaxTree to take in an optional SourceText.
  src/Workspaces/CSharp/Portable/Workspace/LanguageServices/CSharpSyntaxTreeFactoryService.cs
  src/Workspaces/Core/Portable/Workspace/Host/SyntaxTreeFactory/AbstractSyntaxTreeFactoryService.cs
  src/Workspaces/Core/Portable/Workspace/Host/SyntaxTreeFactory/ISyntaxTreeFactoryService.cs
  src/Workspaces/Core/Portable/Workspace/Solution/DocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/DocumentState_LinkedFileReuse.cs
  src/Workspaces/VisualBasic/Portable/Workspace/LanguageServices/VisualBasicSyntaxTreeFactoryService.vb
Labels: Area-IDE, untriaged, VSCode

#74719 Revise usage of `<code>` tag in `IOperation` docs
  src/Compilers/Core/Portable/Generated/FlowAnalysis.Generated.cs
  src/Compilers/Core/Portable/Generated/Operations.Generated.cs
  src/Compilers/Core/Portable/Operations/OperationInterfaces.xml
Labels: Area-Compilers, Community, untriaged

#73987 Disable targeted notifications in integration tests
  eng/build.ps1
Labels: Area-Infrastructure, untriaged

#74721 Make analyzer mvid part of our checksum
  src/Workspaces/Core/Portable/Serialization/SerializerService_Reference.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
Labels: Area-IDE, untriaged, VSCode

#74722 Reenable workspace pull diagnostics
  src/EditorFeatures/Core/LanguageServer/AlwaysActivateInProcLanguageClient.cs
Labels: Area-IDE, untriaged

#74720 Remove unused parameter in analyzer loading code
  src/EditorFeatures/Core/Workspaces/VSAnalyzerAssemblyLoaderProvider.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerWorkspaceFactory.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/VSCodeAnalyzerLoader.cs
  src/LanguageServer/Protocol/Features/AbstractAnalyzerAssemblyLoaderProvider.cs
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioAnalyzerTests.vb
  src/Workspaces/Core/Portable/Diagnostics/DefaultAnalyzerAssemblyLoaderService.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService_Reference.cs
  src/Workspaces/Core/Portable/Workspace/Host/Metadata/IAnalyzerAssemblyLoaderProvider.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteAnalyzerAssemblyLoaderService.cs
Labels: Area-IDE, untriaged, VSCode

#74724 Preserve document extension for the preview content we create
  src/EditorFeatures/Core/Preview/AbstractPreviewFactoryService.cs
Labels: Area-IDE, untriaged

#74646 Add span type inference
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
  src/Compilers/CSharp/Test/Emit3/FirstClassSpanTests.cs
  src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs
Labels: Area-Compilers, untriaged, New Feature - First-class Span Types

#74698 Modify MergedNamespaceDeclaration.MakeChildren to to allocate less
  src/Compilers/CSharp/Portable/Declarations/MergedNamespaceDeclaration.cs
  src/Compilers/Core/Portable/Collections/DictionaryExtensions.cs
Labels: Area-Compilers, untriaged

#74735 Rename file and wrap long parameter list
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectAnalyzerReference.cs
Labels: Area-IDE, untriaged, VSCode

#74727 Send a TextDocumentidentifier for razor dynamic file requests/responses
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/RazorDynamicFileInfoProvider.cs
Labels: Area-Infrastructure, untriaged, VSCode

#74743 Some minor renames/cleanup before an upcoming large refactoring
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectFactory.ProjectUpdateState.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectFactory.cs
Labels: Area-IDE, untriaged, VSCode

#74746 Fix URI comparisons for different casing
  src/LanguageServer/Protocol/Workspaces/LspWorkspaceManager.cs
  src/LanguageServer/ProtocolUnitTests/UriTests.cs
Labels: Area-IDE, untriaged, VSCode

#74741 Switch API to immutable-array from params-array
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/LspFileChangeWatcherTests.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DelegatingFileChangeWatcher.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/LspFileChangeWatcher.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/SimpleFileChangeWatcher.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs
  src/VisualStudio/Core/Def/ProjectSystem/FileChangeWatcher.cs
  src/VisualStudio/Core/Def/ProjectSystem/RuleSets/VisualStudioRuleSetManager.RuleSetFile.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/FileWatchedPortableExecutableReferenceFactory.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/IFileChangeWatcher.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.cs
Labels: Area-IDE, untriaged, VSCode

#74744 Avoid async void methods
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectFactory.cs
Labels: Area-IDE, untriaged, VSCode

#74709 Fix some small things with readme
  README.md
  docs/img/discord-mark-white.png
Labels: Area-Compilers, untriaged

#74748 Switch to primary constructor
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DelegatingFileChangeWatcher.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/FileWatchedPortableExecutableReferenceFactory.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectFactory.ProjectUpdateState.cs
Labels: Area-IDE, untriaged, VSCode

#74751 Disable build on test refresh
  .vscode/settings.json
Labels: Area-Infrastructure, untriaged

#74749 Use existing property to access services
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectFactory.cs
Labels: Area-IDE, untriaged, VSCode

#74712 Refactor semantic snippets
  src/EditorFeatures/Test/Snippets/RoslynLSPSnippetConvertTests.cs
  src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs
  src/Features/Core/Portable/Snippets/AbstractSnippetService.cs
  src/Features/Core/Portable/Snippets/RoslynLSPSnippetConverter.cs
  src/Features/Core/Portable/Snippets/SnippetChange.cs
  src/Features/Core/Portable/Snippets/SnippetData.cs
  src/Features/Core/Portable/Snippets/SnippetPlaceholder.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractSnippetProvider.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/ISnippetProvider.cs
Labels: Area-IDE, Community, untriaged, VSCode

#74626 Add support in DevKit for source link go to definition
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/Services/Descriptors.cs
  src/VisualStudio/Core/Def/PdbSourceDocument/AbstractSourceLinkService.cs
  src/VisualStudio/Core/Def/PdbSourceDocument/SourceLinkService.cs
  src/VisualStudio/DevKit/Impl/Microsoft.VisualStudio.LanguageServices.DevKit.csproj
  src/VisualStudio/DevKit/Impl/SourceLink/VSCodePdbSourceDocumentLogger.cs
  src/VisualStudio/DevKit/Impl/SourceLink/VSCodeSourceLinkService.cs
  src/Workspaces/Remote/Core/BrokeredServiceDescriptors.cs
Labels: Area-IDE, untriaged, VSCode

#74530 Cleanup LSP error reporting
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptRequestExecutionQueueProvider.cs
  src/LanguageServer/Protocol/Handler/AbstractRefreshQueue.cs
  src/LanguageServer/Protocol/RequestExecutionQueueProvider.cs
  src/LanguageServer/Protocol/RoslynRequestExecutionQueue.cs
  src/LanguageServer/ProtocolUnitTests/HandlerTests.cs
  src/LanguageServer/ProtocolUnitTests/TestConfigurableDocumentHandler.cs
Labels: Area-IDE, untriaged

#74630 Use manual `foreach` instead of `AddRange` method for certain collection expression spreads
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, Community, untriaged

#74759 Remove nonexistent folders from the solution explorer
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
Labels: Area-IDE, Community, untriaged

#74490 Fix nested nullability of collection expressions
  src/Compilers/CSharp/Portable/Binder/Semantics/BestTypeInferrer.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/NullablePublicAPITests.cs
Labels: Area-Compilers, untriaged

#74730 Expose document symbols to Razor cohosting
  src/LanguageServer/Protocol/Handler/Symbols/DocumentSymbolsHandler.cs
  src/LanguageServer/Protocol/Protocol/Internal/Converters/VSInternalExtensionUtilities.cs
  src/LanguageServer/ProtocolUnitTests/Symbols/DocumentSymbolsTests.cs
  src/Tools/ExternalAccess/Razor/Cohost/Handlers/DocumentSymbols.cs
Labels: VSCode

#74763 Remove net35 reference assemblies
  eng/Directory.Packages.props
  src/Compilers/CSharp/Test/Semantic/Semantics/UseSiteErrorTests.cs
  src/Compilers/Test/Core/Generate.ps1
  src/Compilers/Test/Core/Generated.cs
  src/Compilers/Test/Core/Generated.targets
  src/Compilers/Test/Core/Microsoft.CodeAnalysis.Test.Utilities.csproj
Labels: Area-Compilers, untriaged

#74706 Handle partial properties in struct field ordering warning
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/PartialPropertiesTests.cs
Labels: Area-Compilers, untriaged

#74767 Snippet refactoring 2
  src/Features/CSharp/Portable/Snippets/AbstractCSharpAutoPropertySnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/AbstractCSharpMainMethodSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/AbstractCSharpTypeSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpConsoleSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpConstructorSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpElseSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpForEachLoopSnippetProvider.cs
  src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs
  src/Features/Core/Portable/Snippets/AbstractSnippetService.cs
  src/Features/Core/Portable/Snippets/ISnippetService.cs
  src/Features/Core/Portable/Snippets/SnippetContext.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractInlineStatementSnippetProvider.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractSnippetProvider.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractStatementSnippetProvider.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/ISnippetProvider.cs
Labels: Area-IDE, Community, untriaged, VSCode

#74781 Fix Copilot option bug
  src/VisualStudio/CSharp/Impl/Options/CSharpVisualStudioCopilotOptionsService.cs
Labels: Area-IDE, untriaged

#73843 Use EnableCodeStyleSeverity instead of AnalysisLevel to control new diagnostic severity behavior
  src/Analyzers/CSharp/Tests/UseObjectInitializer/UseObjectInitializerTests.cs
  src/Analyzers/Core/Analyzers/Helpers/DiagnosticHelper.cs
  src/Analyzers/Core/Analyzers/UseObjectInitializer/AbstractUseObjectInitializerDiagnosticAnalyzer.cs
  src/Analyzers/VisualBasic/Tests/UseObjectInitializer/UseObjectInitializerTests.vb
  src/CodeStyle/Tools/Program.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/AnalyzerConfigOptionsExtensions.cs
Labels: Area-IDE, untriaged, VSCode

#74729 Report field diagnostic as warning, only report when ambiguous, and only with preview language version
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Generated/ErrorFacts.Generated.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit3/FieldKeywordTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/FieldKeywordParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Syntax/FieldAndValueKeywordTests.cs
Labels: Area-Compilers, untriaged

#74792 Expose trigger in argument list option to vscode
  src/LanguageServer/Protocol/Handler/Configuration/DidChangeConfigurationNotificationHandler_OptionList.cs
  src/LanguageServer/ProtocolUnitTests/Configuration/DidChangeConfigurationNotificationHandlerTest.cs
Labels: Area-IDE, untriaged, VSCode

#74791 Fix issue where output path set in construction never updated the project update state
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioProjectTests/ProjectSystemProjectFactoryTests.vb
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectFactory.cs
Labels: Area-IDE, untriaged, VSCode

#74745 Add file watchers for analyzer references
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileWatching/DelegatingFileChangeWatcher.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/FileWatchedPortableExecutableReferenceFactory.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.BatchingDocumentCollection.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectFactory.ProjectUpdateState.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectFactory.cs
Labels: Area-IDE, untriaged, VSCode

#74805 Prioritize original user symbol in FAR results above cascaded symbols.
  src/Features/Core/Portable/FindUsages/AbstractFindUsagesService.ProgressAdapter.cs
  src/Features/Core/Portable/FindUsages/AbstractFindUsagesService_FindReferences.cs
  src/VisualStudio/Core/Def/FindReferences/Contexts/AbstractTableDataSourceFindUsagesContext.cs
  src/VisualStudio/Core/Def/FindReferences/Contexts/WithReferencesFindUsagesContext.cs
  src/VisualStudio/Core/Def/FindReferences/Contexts/WithoutReferencesFindUsagesContext.cs
  src/VisualStudio/Core/Def/FindReferences/StreamingFindUsagesPresenter.cs
Labels: Area-IDE, untriaged, VSCode

#74806 Stylistic cleanup of some solution explorer code
  src/VisualStudio/Core/Impl/SolutionExplorer/AnalyzerItem/AnalyzerItem.BrowseObject.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/AnalyzerItemTracker.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/AnalyzersFolderItem/AnalyzersFolderItem.BrowseObject.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/AnalyzersFolderItem/AnalyzersFolderItem.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/AnalyzersFolderItem/AnalyzersFolderItemSource.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/AnalyzersFolderItem/AnalyzersFolderItemSourceProvider.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/DiagnosticItem/DiagnosticItem.BrowseObject.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/SourceGeneratedFileItems/NoSourceGeneratedFilesPlaceholderItem.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/SourceGeneratedFileItems/SourceGeneratedFileItem.BrowseObject.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/SourceGeneratedFileItems/SourceGeneratedFileItem.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/SourceGeneratedFileItems/SourceGeneratedFileItemSource.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/SourceGeneratedFileItems/SourceGeneratedFileItemSourceProvider.cs
Labels: Area-IDE, untriaged

#74802 Move to basic ref assemblies for net20
  eng/Directory.Packages.props
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLockTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs
  src/Compilers/CSharp/Test/Emit2/Emit/EditAndContinue/EditAndContinueStateMachineTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/ColorColorTests.cs
  src/Compilers/CSharp/Test/Symbol/Compilation/ReferenceManagerTests.cs
  src/Compilers/Server/VBCSCompilerTests/CompilerServerTests.cs
  src/Compilers/Test/Core/Generate.ps1
  src/Compilers/Test/Core/Generated.cs
  src/Compilers/Test/Core/Generated.targets
  src/Compilers/Test/Core/Microsoft.CodeAnalysis.Test.Utilities.csproj
  src/Compilers/Test/Core/TestBase.cs
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenSyncLock.vb
  src/Compilers/VisualBasic/Test/Emit/Emit/CompilationEmitTests.vb
  src/Compilers/VisualBasic/Test/Semantic/Compilation/ReferenceManagerTests.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Retargeting/RetargetingTests.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/StaticLocals.vb
Labels: Area-Compilers, untriaged

#74812 Only copy devkit assemblies for unit tests when doing a real build
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Microsoft.CodeAnalysis.LanguageServer.UnitTests.csproj
  src/VisualStudio/DevKit/Impl/Microsoft.VisualStudio.LanguageServices.DevKit.csproj
Labels: Area-Infrastructure, untriaged

#74817 Fix Typo in LSP protocol type
  src/LanguageServer/Protocol/Protocol/SemanticTokens/SemanticTokensRequestsFullSetting.cs
Labels: Area-Infrastructure, untriaged, VSCode

#74810 Communicate with OOP process to determine if an AnalyzerReference has analyzers or source generators.
  src/VisualStudio/Core/Impl/SolutionExplorer/AnalyzerItem/AnalyzerItem.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/AnalyzerItem/AnalyzerItemSource.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/AnalyzerItem/AnalyzerItemSourceProvider.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/AnalyzersFolderItem/AnalyzersFolderItem.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/AnalyzersFolderItem/AnalyzersFolderItemSource.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/AnalyzersFolderItem/AnalyzersFolderItemSourceProvider.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/DiagnosticItem/BaseDiagnosticAndGeneratorItemSource.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/SourceGeneratedFileItems/SourceGeneratedFileItemSource.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/SourceGeneratedFileItems/SourceGeneratedFileItemSourceProvider.cs
  src/VisualStudio/Core/Test/SolutionExplorer/AnalyzerItemTests.vb
  src/VisualStudio/Core/Test/SolutionExplorer/AnalyzerItemsSourceTests.vb
  src/VisualStudio/Core/Test/SolutionExplorer/AnalyzersFolderItemTests.vb
  src/VisualStudio/Core/Test/SolutionExplorer/AnalyzersFolderProviderTests.vb
  src/VisualStudio/Core/Test/SolutionExplorer/SourceGeneratorItemTests.vb
  src/Workspaces/Core/Portable/Shared/Extensions/AnalyzerReferenceExtensions.cs
  src/Workspaces/Core/Portable/SourceGeneration/IRemoteSourceGenerationService.cs
  src/Workspaces/Remote/ServiceHub/Services/SourceGeneration/RemoteSourceGenerationService.cs
Labels: Area-IDE, untriaged, VSCode

#74818 Clean inline rename session
  src/EditorFeatures/Core/ExtractMethod/ExtractMethodCommandHandler.cs
  src/EditorFeatures/Core/IInlineRenameSession.cs
  src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs
  src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb
  src/EditorFeatures/VisualBasicTest/LineCommit/CommitTestData.vb
Labels: Area-IDE, untriaged

#74822 Skip vsix crossgen targets when running design time build
  src/Workspaces/Remote/ServiceHub.CoreComponents/CoreComponents.Shared.targets
Labels: Area-IDE, untriaged

#74824 Rename type for clarity
  src/Workspaces/Core/Portable/Serialization/SerializedPortableExecutableReference.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService_Reference.cs
Labels: Area-IDE, untriaged, VSCode

#74829 Remove IChecksummedObject type.
  src/VisualStudio/Core/Def/ProjectSystem/MetadataReferences/VisualStudioMetadataReferenceManager.cs
  src/Workspaces/Core/Portable/Remote/ISerializerService.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService_Asset.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService_Reference.cs
  src/Workspaces/Core/Portable/TemporaryStorage/TemporaryStorageService.TemporaryStorageStreamHandle.cs
  src/Workspaces/Core/Portable/TemporaryStorage/TemporaryStorageService.cs
  src/Workspaces/Core/Portable/TemporaryStorage/TrivialTemporaryStorageService.cs
  src/Workspaces/Core/Portable/Workspace/Host/TemporaryStorage/ITemporaryStorageStreamHandle.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectOptionsProcessor.cs
  src/Workspaces/Core/Portable/Workspace/Solution/IChecksummedObject.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.SkeletonReferenceCache.cs
  src/Workspaces/CoreTest/WorkspaceServiceTests/TemporaryStorageServiceTests.cs
  src/Workspaces/CoreTestUtilities/Remote/TestSerializerService.cs
  src/Workspaces/CoreTestUtilities/TestGeneratorReference.cs
Labels: Area-IDE, untriaged, VSCode

#74790 Reduce allocations in CSharpSyntaxFacts.AppendMembers (again)
  src/Analyzers/Core/Analyzers/RemoveUnnecessarySuppressions/AbstractRemoveUnnecessaryPragmaSuppressionsDiagnosticAnalyzer.cs
  src/Compilers/Core/Portable/Collections/ImmutableArrayExtensions.cs
  src/Compilers/Core/Portable/InternalUtilities/EnumerableExtensions.cs
  src/EditorFeatures/Core/Editor/GoToAdjacentMemberCommandHandler.cs
  src/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.cs
  src/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer_MemberSpans.cs
  src/Workspaces/Core/Portable/SemanticModelReuse/AbstractSemanticModelReuseLanguageService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE, untriaged, VSCode

#74760 17.10: Cherry-pick fix for scenario where lightbulbs weren't being displayed
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs
  src/EditorFeatures/Test2/Diagnostics/DiagnosticServiceTests.vb
  src/EditorFeatures/TestUtilities/Diagnostics/MockDiagnosticAnalyzerService.cs
  src/Features/Core/Portable/CodeFixes/FirstFixResult.cs
  src/Features/Core/Portable/Diagnostics/IDiagnosticAnalyzerService.cs
  src/Features/LanguageServer/Protocol/Features/CodeFixes/CodeFixService.cs
  src/Features/LanguageServer/Protocol/Features/CodeFixes/ICodeFixService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DiagnosticAnalyzerService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs
  src/VisualStudio/Core/Test/Diagnostics/ExternalDiagnosticUpdateSourceTests.vb
Labels: Area-IDE, untriaged, VSCode

#74786 17.11 cherry-pick: fix bug with on-the-fly-docs option not working when clicked (#74781)
  src/VisualStudio/CSharp/Impl/Options/CSharpVisualStudioCopilotOptionsService.cs
Labels: Area-IDE, untriaged

#74814 Remove dependency on deprecated ref package
  eng/Directory.Packages.props
  src/Compilers/Test/Core/Generate.ps1
  src/Compilers/Test/Core/Generated.cs
  src/Compilers/Test/Core/Generated.targets
  src/Compilers/Test/Core/Microsoft.CodeAnalysis.Test.Utilities.csproj
  src/Compilers/Test/Core/TestBase.cs
  src/Workspaces/CoreTest/FindReferencesTests.cs
Labels: Area-Compilers, untriaged, VSCode

#74828 Retry design time build fix while also keeping FUTDC working
  eng/targets/Imports.targets
  src/Workspaces/Remote/ServiceHub.CoreComponents/CoreComponents.Shared.targets
Labels: Area-Infrastructure, untriaged

#74849 Set ScaleFactor for inheritance margin context menu
  src/VisualStudio/Core/Def/InheritanceMargin/MarginGlyph/DisambiguousTargetMenuItemViewModel.cs
  src/VisualStudio/Core/Def/InheritanceMargin/MarginGlyph/InheritanceMarginContextMenu.xaml
  src/VisualStudio/Core/Def/InheritanceMargin/MarginGlyph/InheritanceMarginContextMenu.xaml.cs
  src/VisualStudio/Core/Def/InheritanceMargin/MarginGlyph/InheritanceMarginGlyph.cs
Labels: Area-IDE, untriaged, Needs UX Triage

#74728 Reduce allocations from newline information allocated by ChangedText.GetLinesCore
  src/Compilers/Core/CodeAnalysisTest/Text/CompositeTextTests.cs
  src/Compilers/Core/CodeAnalysisTest/Text/TextChangeTests.cs
  src/Compilers/Core/Portable/Text/ChangedText.cs
  src/Compilers/Core/Portable/Text/CompositeText.cs
  src/Compilers/Core/Portable/Text/SubText.cs
Labels: Area-Compilers, untriaged

#74857 Move type to its own file
  src/Workspaces/Core/Portable/Serialization/SerializerService.cs
  src/Workspaces/Remote/Core/AbstractAssetProvider.cs
  src/Workspaces/Remote/Core/AbstractAssetProviderExtensions.cs
  src/Workspaces/Remote/ServiceHub/ExternalAccess/Pythia/Api/PythiaBrokeredServiceImplementation.cs
  src/Workspaces/Remote/ServiceHub/ExternalAccess/Razor/Api/RazorBrokeredServiceImplementation.cs
  src/Workspaces/Remote/ServiceHub/ExternalAccess/UnitTesting/Api/UnitTestingBrokeredServiceImplementation.cs
  src/Workspaces/Remote/ServiceHub/Host/IGlobalServiceBroker.cs
  src/Workspaces/Remote/ServiceHub/Host/ProcessExtensions.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteAnalyzerAssemblyLoader.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteDocumentDifferenceService.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteHostTestData.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.InFlightSolution.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspaceManager.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace_SolutionCaching.cs
  src/Workspaces/Remote/ServiceHub/Host/TestUtils.cs
  src/Workspaces/Remote/ServiceHub/Host/ThrowingTraceListener.cs
  src/Workspaces/Remote/ServiceHub/Services/AsynchronousOperationListener/RemoteAsynchronousOperationListenerService.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.FactoryBase.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.ServiceConstructionArguments.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs
  src/Workspaces/Remote/ServiceHub/Services/CodeLensReferences/RemoteCodeLensReferencesService.cs
  src/Workspaces/Remote/ServiceHub/Services/ConvertTupleToStructCodeRefactoringProvider/RemoteConvertTupleToStructCodeRefactoringService.cs
  src/Workspaces/Remote/ServiceHub/Services/DependentTypeFinder/RemoteDependentTypeFinderService.cs
  src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/DiagnosticComputer.cs
  src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/IPerformanceTrackerService.cs
  src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/PerformanceQueue.cs
  src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/PerformanceTrackerService.cs
  src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/RemoteDiagnosticAnalyzerService.cs
  src/Workspaces/Remote/ServiceHub/Services/DocumentHighlights/RemoteDocumentHighlightsService.cs
  src/Workspaces/Remote/ServiceHub/Services/EditAndContinue/RemoteEditAndContinueService.cs
  src/Workspaces/Remote/ServiceHub/Services/EncapsulateField/RemoteEncapsulateFieldService.cs
  src/Workspaces/Remote/ServiceHub/Services/ExtensionMethodImportCompletion/RemoteExtensionMethodImportCompletionService.cs
  src/Workspaces/Remote/ServiceHub/Services/FindUsages/RemoteFindUsagesService.cs
  src/Workspaces/Remote/ServiceHub/Services/FullyQualify/RemoteFullyQualifyService.cs
  src/Workspaces/Remote/ServiceHub/Services/InheritanceMargin/RemoteInheritanceMarginService.cs
  src/Workspaces/Remote/ServiceHub/Services/KeepAlive/RemoteKeepAliveService.cs
  src/Workspaces/Remote/ServiceHub/Services/LegacySolutionEvents/RemoteLegacySolutionEventsAggregationService.cs
  src/Workspaces/Remote/ServiceHub/Services/MissingImportDiscovery/RemoteMissingImportDiscoveryService.cs
  src/Workspaces/Remote/ServiceHub/Services/NavigateToSearch/RemoteNavigateToSearchService.cs
  src/Workspaces/Remote/ServiceHub/Services/ProcessTelemetry/RemoteProcessTelemetryService.cs
  src/Workspaces/Remote/ServiceHub/Services/ProcessTelemetry/RemoteWorkspaceConfigurationService.cs
  src/Workspaces/Remote/ServiceHub/Services/ProcessTelemetry/RemoteWorkspaceTelemetryService.cs
  src/Workspaces/Remote/ServiceHub/Services/Renamer/RemoteRenamerService.cs
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassification/RemoteSemanticClassificationService.Caching.cs
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassification/RemoteSemanticClassificationService.cs
  src/Workspaces/Remote/ServiceHub/Services/StackTraceExplorer/RemoteStackTraceExplorerService.cs
  src/Workspaces/Remote/ServiceHub/Services/SymbolFinder/RemoteSymbolFinderService.cs
  src/Workspaces/Remote/ServiceHub/Services/SymbolSearchUpdate/RemoteSymbolSearchUpdateService.cs
  src/Workspaces/Remote/ServiceHub/Services/TaskList/RemoteTaskListService.cs
  src/Workspaces/Remote/ServiceHub/Services/UnitTesting/RemoteUnitTestingSearchService.cs
  src/Workspaces/Remote/ServiceHub/Services/UnusedReferences/RemoteUnusedReferenceAnalysisService.cs
  src/Workspaces/Remote/ServiceHub/Services/ValueTracking/RemoteValueTrackingService.cs
Labels: Area-IDE, untriaged, VSCode

#74858 Hook up file watchers for analyzer references
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectFactory.ProjectUpdateState.cs
Labels: Area-IDE, untriaged, VSCode

#74864 Adds MicrosoftIdentityModelJsonWebTokensVersion to Versions.prop
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#74862 Fix error closing source link documents in VSCode
  src/EditorFeatures/CSharpTest/PdbSourceDocument/AbstractPdbSourceDocumentTests.cs
  src/Features/Core/Portable/PdbSourceDocument/PdbSourceDocumentMetadataAsSourceFileProvider.cs
Labels: Area-IDE, untriaged, VSCode

#74831 Skip ValidateVisualBasicTemplateProjects failing on CI due to AVE
  src/Workspaces/MSBuildTest/NewlyCreatedProjectsFromDotNetNew.cs
Labels: Area-Infrastructure, untriaged, VSCode

#74845 Expose disposing capability on IAssemblyLoaderInternal
  src/Compilers/Core/CodeAnalysisTest/Analyzers/AnalyzerFileReferenceTests.cs
  src/Compilers/Core/CodeAnalysisTest/InvokeUtil.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.Core.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.Desktop.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs
  src/Compilers/Core/Portable/InternalUtilities/FatalError.cs
  src/Compilers/Server/VBCSCompilerTests/AnalyzerConsistencyCheckerTests.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/VSCodeAnalyzerLoader.cs
  src/LanguageServer/Protocol/Features/AbstractAnalyzerAssemblyLoaderProvider.cs
  src/Workspaces/Core/Portable/Diagnostics/DefaultAnalyzerAssemblyLoaderService.cs
  src/Workspaces/Core/Portable/Workspace/Host/Metadata/IAnalyzerAssemblyLoaderProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteAnalyzerAssemblyLoaderService.cs
Labels: Area-IDE, untriaged, VSCode

#74877 Switch to just using paths as keys for file watching
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/FileWatchedPortableExecutableReferenceFactory.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectFactory.cs
Labels: Area-IDE, untriaged, VSCode

#74878 Extract local functions to make project updating simpler to understand.
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.cs
Labels: Area-IDE, untriaged, VSCode

#74841 Semantic snippets: don't provide snippets when dotting of a type name
  src/Features/CSharp/Portable/Snippets/CSharpDoWhileLoopSnippetProvider.cs
  src/Features/CSharpTest/Snippets/AbstractCSharpConditionalBlockSnippetProviderTests.cs
  src/Features/CSharpTest/Snippets/CSharpDoSnippetProviderTests.cs
  src/Features/CSharpTest/Snippets/CSharpForEachSnippetProviderTests.cs
  src/Features/CSharpTest/Snippets/CSharpForSnippetProviderTests.cs
  src/Features/CSharpTest/Snippets/CSharpReversedForSnippetProviderTests.cs
  src/Features/CSharpTest/Snippets/CommonSnippetTestData.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractInlineStatementSnippetProvider.cs
Labels: Area-IDE, Community, untriaged, VSCode

#74882 Pass along services object to make multiple service retrieval easier
  src/VisualStudio/Core/Test.Next/Services/AssetProviderTests.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/VisualStudio/Core/Test.Next/Services/SolutionServiceTests.cs
  src/Workspaces/Remote/ServiceHub/Host/AssetProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
Labels: Area-IDE, untriaged, VSCode

#74886 Move feature to only working when in 'Preview'
  src/Analyzers/CSharp/Analyzers/UseAutoProperty/CSharpUseAutoPropertyAnalyzer.cs
  src/Analyzers/CSharp/Tests/UseAutoProperty/UseAutoPropertyTests_Field.cs
Labels: Area-IDE, untriaged, VSCode

#74884 Switch to an async batching work queue in teh file change listener
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerWorkspaceFactory.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/FileWatchedPortableExecutableReferenceFactory.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectFactory.ProjectUpdateState.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectFactory.cs
Labels: Area-IDE, untriaged, VSCode

#74893 Semantic snippets: don't provide snippets when dotting of a type name (floow up)
  src/Features/CSharpTest/Snippets/AbstractCSharpConditionalBlockSnippetProviderTests.cs
  src/Features/CSharpTest/Snippets/CSharpDoSnippetProviderTests.cs
  src/Features/CSharpTest/Snippets/CSharpForEachSnippetProviderTests.cs
  src/Features/CSharpTest/Snippets/CSharpForSnippetProviderTests.cs
  src/Features/CSharpTest/Snippets/CSharpReversedForSnippetProviderTests.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractInlineStatementSnippetProvider.cs
Labels: Area-IDE, Community, untriaged, VSCode

#74876 Remove incorrect cast
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/ParamsCollectionTests.cs
Labels: Area-Compilers, untriaged

#74842 Workaround failure to declare GenerateManifests as a dependency of _CopyResolvedFilesToPublishPreserveNewest
  eng/targets/Imports.targets
Labels: Area-Infrastructure, untriaged

#74811 Update dartlab pipeline
  azure-pipelines-integration-dartlab.yml
Labels: Area-Infrastructure, untriaged

#74866 Fix handling default copilot option values
  src/VisualStudio/CSharp/Impl/Options/CSharpVisualStudioCopilotOptionsService.cs
Labels: Area-IDE, untriaged

#74895 Simplify and unify assembly loader provider
  src/EditorFeatures/Core/Workspaces/VSAnalyzerAssemblyLoaderProvider.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerWorkspaceFactory.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/VSCodeAnalyzerLoaderProviderFactory.cs
  src/LanguageServer/Protocol/Features/AbstractAnalyzerAssemblyLoaderProvider.cs
  src/Workspaces/Core/Portable/Diagnostics/DefaultAnalyzerAssemblyLoaderService.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService_Reference.cs
  src/Workspaces/Core/Portable/Workspace/Host/Metadata/IAnalyzerAssemblyLoaderProvider.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectFactory.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteAnalyzerAssemblyLoaderService.cs
Labels: Area-IDE, untriaged, VSCode

#74905 Double check document changes when dismiss rename
  src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs
Labels: Area-IDE, untriaged

#74471 Add explicit cast to UseCoalesceExpressionForIfNullStatementCheckCodeFixProvider
  src/Analyzers/CSharp/CodeFixes/CSharpCodeFixes.projitems
  src/Analyzers/CSharp/CodeFixes/UseCoalesceExpression/CSharpUseCoalesceExpressionForIfNullStatementCheckCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseCoalesceExpression/UseCoalesceExpressionForIfNullStatementCheckTests.cs
  src/Analyzers/Core/CodeFixes/CodeFixes.projitems
  src/Analyzers/Core/CodeFixes/UseCoalesceExpression/AbstractUseCoalesceExpressionForIfNullStatementCheckCodeFixProvider.cs
  src/Analyzers/VisualBasic/CodeFixes/UseCoalesceExpression/VisualBasicUseCoalesceExpressionForIfNullStatementCheckCodeFixProvider.vb
  src/Analyzers/VisualBasic/CodeFixes/VisualBasicCodeFixes.projitems
  src/Analyzers/VisualBasic/Tests/UseCoalesceExpression/UseCoalesceExpressionForIfNullStatementCheckTests.vb
Labels: Area-IDE, Community, untriaged, VSCode

#74780 Load analyzers and generators in isolated ALCs in our OOP process
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerWorkspaceFactory.cs
  src/VisualStudio/Core/Test.Next/Remote/SerializationValidator.cs
  src/VisualStudio/Core/Test.Next/Services/SolutionServiceTests.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService_Reference.cs
  src/Workspaces/Core/Portable/Workspace/Host/Metadata/IAnalyzerAssemblyLoaderProvider.cs
  src/Workspaces/Core/Portable/Workspace/IsolatedAnalyzerFileReference.cs
  src/Workspaces/Core/Portable/Workspace/IsolatedAnalyzerReferenceSet.Core.cs
  src/Workspaces/Core/Portable/Workspace/IsolatedAnalyzerReferenceSet.Desktop.cs
  src/Workspaces/Core/Portable/Workspace/IsolatedAnalyzerReferenceSet.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectFactory.cs
  src/Workspaces/CoreTest/Microsoft.CodeAnalysis.Workspaces.UnitTests.csproj
  src/Workspaces/CoreTest/Resources/Microsoft.CodeAnalysis.TestAnalyzerReference.dll.v1
  src/Workspaces/CoreTest/Resources/Microsoft.CodeAnalysis.TestAnalyzerReference.dll.v2
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
  src/Workspaces/CoreTestUtilities/Remote/TestSerializerService.cs
  src/Workspaces/Remote/Core/AbstractAssetProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteAnalyzerAssemblyLoaderService.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
  src/Workspaces/Remote/ServiceHub/Microsoft.CodeAnalysis.Remote.ServiceHub.csproj
  src/Workspaces/Remote/ServiceHub/Services/SourceGeneration/RemoteSourceGenerationService.cs
Labels: Area-IDE, untriaged, VSCode

#74865 Use InterceptorsNamespaces feature name instead of InterceptorsPreviewNamespaces
  docs/features/interceptors.md
  src/Compilers/CSharp/Portable/CSharpParseOptions.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/CommandLine/CSharpCommandLineParser.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceModuleSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/EndToEnd/EndToEndTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/CSharpParseOptionsTests.cs
  src/Compilers/Core/MSBuildTask/Csc.cs
  src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets
  src/Compilers/Core/MSBuildTaskTests/CscTests.cs
Labels: Area-Compilers, untriaged

#74904 update configs for snap
  eng/Versions.props
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#74844 Report nullable ctor warnings for struct primary constructors
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PrimaryConstructorTests.cs
Labels: Area-Compilers, untriaged

#74671 Update field keyword feature name and details
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation, Community, untriaged

#74750 Make host outputs public
  src/Compilers/CSharp/Portable/CommandLine/CSharpCompiler.cs
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs
  src/Compilers/Core/Portable/InternalUtilities/RoslynExperiments.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorState.cs
  src/Compilers/Core/Portable/SourceGeneration/IncrementalContexts.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/HostOutputNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/IIncrementalGeneratorOutputNode.cs
  src/Compilers/Core/Portable/SourceGeneration/RunResults.cs
  src/Compilers/VisualBasic/Portable/CommandLine/VisualBasicCompiler.vb
  src/Compilers/VisualBasic/Test/CommandLine/CommandLineTests.vb
  src/Tools/ExternalAccess/RazorCompiler/GeneratorExtensions.cs
Labels: Area-Compilers, Needs API Review

#74906 Initial work to create a service for returning related documents for copilot purposes.
  eng/targets/Services.props
  src/Features/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.Features.csproj
  src/Features/CSharp/Portable/RelatedDocuments/CSharpRelatedDocumentsService.cs
  src/Features/CSharpTest/RelatedDocuments/CSharpRelatedDocumentsTests.cs
  src/Features/Core/Portable/RelatedDocuments/AbstractRelatedDocumentsService.cs
  src/Features/Core/Portable/RelatedDocuments/IRelatedDocumentsService.cs
  src/Features/Core/Portable/RelatedDocuments/IRemoteRelatedDocumentsService.cs
  src/Features/TestUtilities/RelatedDocuments/AbstractRelatedDocumentsTests.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemostHostClient.cs
  src/Workspaces/Remote/Core/RemoteWorkspacesResources.resx
  src/Workspaces/Remote/Core/ServiceDescriptors.cs
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.cs.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.de.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.es.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.fr.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.it.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ja.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ko.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.pl.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.pt-BR.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.ru.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.tr.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.zh-Hans.xlf
  src/Workspaces/Remote/Core/xlf/RemoteWorkspacesResources.zh-Hant.xlf
  src/Workspaces/Remote/ServiceHub/Services/RelatedDocuments/RemoteRelatedDocumentsService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/ObjectPools/Extensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/ObjectPools/PooledObject.cs
Labels: Area-IDE, untriaged, VSCode

#74914 Avoid synthesizing incorrect `allows ref struct` delegate type parameters
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.DelegateTemplateSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.TemplateSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.TypeParameterSymbol.cs
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
Labels: Area-Compilers, untriaged, New Feature - RefStructInterfaces

#74921 Add tests validating a particular scenario
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs
Labels: Area-IDE, untriaged, VSCode

#74867 Fix copilot options default value handling
  src/VisualStudio/CSharp/Impl/Options/CSharpVisualStudioCopilotOptionsService.cs
Labels: Area-IDE, untriaged

#74889 Always take ownership from UIThreadContext when rename commit
  src/EditorFeatures/Core.Wpf/InlineRename/CommandHandlers/RenameCommandHandler.cs
  src/EditorFeatures/Core/ExtractMethod/ExtractMethodCommandHandler.cs
  src/EditorFeatures/Core/IInlineRenameSession.cs
  src/EditorFeatures/Core/InlineRename/CommandHandlers/AbstractRenameCommandHandler.cs
  src/EditorFeatures/Core/InlineRename/CommandHandlers/AbstractRenameCommandHandler_BackspaceDeleteHandler.cs
  src/EditorFeatures/Core/InlineRename/CommandHandlers/AbstractRenameCommandHandler_CutPasteHandler.cs
  src/EditorFeatures/Core/InlineRename/CommandHandlers/AbstractRenameCommandHandler_MoveSelectedLinesHandler.cs
  src/EditorFeatures/Core/InlineRename/CommandHandlers/AbstractRenameCommandHandler_OpenLineAboveHandler.cs
  src/EditorFeatures/Core/InlineRename/CommandHandlers/AbstractRenameCommandHandler_OpenLineBelowHandler.cs
  src/EditorFeatures/Core/InlineRename/CommandHandlers/AbstractRenameCommandHandler_RefactoringWithCommandHandler.cs
  src/EditorFeatures/Core/InlineRename/CommandHandlers/AbstractRenameCommandHandler_RenameHandler.cs
  src/EditorFeatures/Core/InlineRename/CommandHandlers/AbstractRenameCommandHandler_ReturnHandler.cs
  src/EditorFeatures/Core/InlineRename/CommandHandlers/AbstractRenameCommandHandler_SaveHandler.cs
  src/EditorFeatures/Core/InlineRename/CommandHandlers/AbstractRenameCommandHandler_TabHandler.cs
  src/EditorFeatures/Core/InlineRename/CommandHandlers/AbstractRenameCommandHandler_TypeCharHandler.cs
  src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs
  src/EditorFeatures/VisualBasicTest/LineCommit/CommitTestData.vb
Labels: Area-IDE, untriaged

#74932 Simplify equivalence comparers
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/SymbolEquivalenceComparer.EquivalenceVisitor.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/SymbolEquivalenceComparer.GetHashCodeVisitor.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/SymbolEquivalenceComparer.SignatureTypeSymbolEquivalenceComparer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/SymbolEquivalenceComparer.cs
Labels: Area-IDE, untriaged, VSCode

#74918 Add LSP handler for copilot related documents
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/Core/Portable/RelatedDocuments/AbstractRelatedDocumentsService.cs
  src/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/LanguageServer/Protocol/Handler/RelatedDocuments/RelatedDocumentsHandler.cs
  src/LanguageServer/Protocol/Protocol/Internal/VSInternalDocumentSpellCheckableParams.cs
  src/LanguageServer/Protocol/Protocol/Internal/VSInternalMethods.cs
  src/LanguageServer/Protocol/Protocol/Internal/VSInternalRelatedDocumentParams.cs
  src/LanguageServer/ProtocolUnitTests/RelatedDocuments/RelatedDocumentsTests.cs
  src/LanguageServer/ProtocolUnitTests/SpellCheck/SpellCheckTests.cs
Labels: Area-IDE, untriaged, VSCode

#74934 Update 'use collection expression' to support cases where switching to a collection expr will pick a ROS overload over an array one.
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForArrayDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForStackAllocDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/UseCollectionExpressionHelpers.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpUseCollectionExpressionForArrayCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpUseCollectionExpressionForStackAllocCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs
  src/EditorFeatures/Test/Utilities/SymbolEquivalenceComparerTests.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ITypeSymbolExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/AbstractSpeculationAnalyzer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/SymbolEquivalenceComparer.EquivalenceVisitor.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/SymbolEquivalenceComparer.cs
Labels: Area-IDE, untriaged, VSCode

#74939 Add IRelatedDocumentsService EA wrapper for Copilot
  src/EditorFeatures/ExternalAccess/Copilot/Internal/RelatedDocuments/CSharpCopilotRelatedDocumentsService.cs
  src/EditorFeatures/ExternalAccess/Copilot/InternalAPI.Unshipped.txt
  src/EditorFeatures/ExternalAccess/Copilot/RelatedDocuments/ICopilotRelatedDocumentsService.cs
Labels: Area-IDE, untriaged

#74942 Remove deleted folder from project file
  src/Workspaces/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.Workspaces.csproj
  src/Workspaces/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.Workspaces.vbproj
Labels: Area-IDE, untriaged

#74922 Field-backed properties: readonly backing field
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Test/Emit3/FieldKeywordTests.cs
Labels: Area-Compilers, untriaged

#74944 Wait for solution to be loaded before initializing remote telemetry
  src/EditorFeatures/Core/Remote/SolutionChecksumUpdater.cs
  src/VisualStudio/Core/Def/Remote/DefaultRemoteHostClientProvider.cs
  src/VisualStudio/Core/Def/Remote/VisualStudioRemoteHostClientProvider.cs
  src/VisualStudio/Core/Def/Telemetry/VisualStudioWorkspaceTelemetryService.cs
  src/Workspaces/Core/Portable/Remote/IRemoteHostClientProvider.cs
  src/Workspaces/Core/Portable/Remote/RemoteHostClient.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemoteHostClientProvider.cs
  src/Workspaces/Remote/Core/ServiceHubRemoteHostClient.cs
  src/Workspaces/Remote/ServiceHub/Services/ProcessTelemetry/RemoteProcessTelemetryService.cs
  src/Workspaces/Remote/ServiceHub/Services/ProcessTelemetry/RemoteWorkspaceTelemetryService.cs
Labels: Area-IDE, untriaged, VSCode

#74948 Ensure rename cancellation is synchronous
  src/EditorFeatures/Core/IInlineRenameSession.cs
  src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs
Labels: Area-IDE, untriaged

#74949 Collection expressions: check conversion to ICollection<T> for spread optimization
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged

#74956 Offer 'field' when within a property accessor.
  src/EditorFeatures/CSharpTest2/Recommendations/FieldKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/RecommenderTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/FieldKeywordRecommender.cs
Labels: Area-IDE, untriaged, VSCode

#74961 Update PublishData after vs snap
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#74963 Use ignore case to fix analyzer reloading in devkit
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectFactory.cs
Labels: Area-IDE, untriaged, VSCode

#74664 Add ProjectInfo.WithId public API
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectInfo.cs
  src/Workspaces/CoreTest/SolutionTests/ProjectInfoTests.cs
Labels: Area-IDE, untriaged, Needs API Review, VSCode

#74965 Add NFW tracking to Solution.RemoveProjectReference
  src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs
Labels: Area-IDE, untriaged, VSCode

#74958 Remove usages of `#if CODE_STYLE` where possible.
  src/Analyzers/Core/CodeFixes/GenerateConstructor/AbstractGenerateConstructorService.State.cs
  src/Analyzers/Core/CodeFixes/GenerateEnumMember/AbstractGenerateEnumMemberService.CodeAction.cs
  src/Analyzers/Core/CodeFixes/GenerateParameterizedMember/AbstractGenerateParameterizedMemberService.SignatureInfo.cs
  src/Analyzers/Core/CodeFixes/GenerateParameterizedMember/AbstractGenerateParameterizedMemberService.State.cs
  src/Analyzers/Core/CodeFixes/GenerateParameterizedMember/AbstractGenerateParameterizedMemberService.cs
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodBase.cs
  src/EditorFeatures/Test2/Expansion/AbstractExpansionTest.vb
  src/EditorFeatures/TestUtilities/Formatting/AbstractNewDocumentFormattingServiceTests.cs
  src/EditorFeatures/VisualBasicTest/CaseCorrecting/CaseCorrectionServiceTests.vb
  src/EditorFeatures/VisualBasicTest/ExtractMethod/ExtractMethodTests.vb
  src/Features/Core/Portable/FullyQualify/AbstractFullyQualifyService.cs
  src/Workspaces/Core/Portable/ExtractMethod/ExtractMethodOptions.cs
  src/Workspaces/Core/Portable/OrganizeImports/OrganizeImportsOptionsProviders.cs
  src/Workspaces/CoreTest/CodeCleanup/AddMissingTokensTests.cs
  src/Workspaces/CoreTest/CodeCleanup/CodeCleanupTests.cs
  src/Workspaces/CoreTest/CodeCleanup/FixIncorrectTokenTests.cs
  src/Workspaces/CoreTest/CodeCleanup/MockCodeCleanupProvider.cs
  src/Workspaces/CoreTest/CodeCleanup/NormalizeModifiersOrOperatorsTests.cs
  src/Workspaces/CoreTest/CodeCleanup/ReduceTokenTests.cs
  src/Workspaces/CoreTest/CodeCleanup/RemoveUnnecessaryLineContinuationTests.cs
  src/Workspaces/CoreTest/Remote/ServiceDescriptorTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeGeneration/CSharpCodeGenerationOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/CSharpFormattingOptions2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/AddImport/AddImportPlacementOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeCleanup/CodeCleanupOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeGeneration/CodeAndImportGenerationOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeGeneration/CodeGenerationOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/DocumentFormattingOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/SyntaxFormattingOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Indentation/IndentationOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/OrganizeImports/OrganizeImportsOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Simplification/SimplifierOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/IReferenceCountedDisposable.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/ReferenceCountedDisposable.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeCleanup/CodeCleanupOptionsProviders.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeGeneration/CleanCodeGenerationOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeGeneration/CodeAndImportGenerationOptionsProviders.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeGeneration/CodeGenerationOptionsProviders.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeGeneration/CodeGenerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/ProjectExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Formatting/DocumentFormattingOptionsProviders.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Formatting/SyntaxFormattingOptionsProviders.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Indentation/IndentationOptionsProviders.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Simplification/SimplifierOptionsProviders.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensions.projitems
Labels: Area-IDE, untriaged, VSCode
