Repository dotnet/roslyn, pull requests merged in 2024-05, with the labels that each got.

#72999 Partial properties: merging declarations and emit of simple cases
  src/Compilers/CSharp/Portable/Binder/BinderFactory.BinderFactoryVisitor.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Symbols/MemberSymbolExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertyAccessorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit2/Diagnostics/GetDiagnosticsTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/PartialPropertiesTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs
Labels: Area-Compilers, New Feature - Partial Properties

#73265 Require AddExplicitInterfaceImplementation for adding a type that implements member explicitly
  src/Features/CSharpTest/EditAndContinue/ActiveStatementTests.cs
  src/Features/CSharpTest/EditAndContinue/StatementEditingTests.cs
  src/Features/CSharpTest/EditAndContinue/TopLevelEditingTests.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueCapabilities.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueCapabilitiesGrantor.cs
  src/Features/Core/Portable/EditAndContinue/Utilities/Extensions.cs
  src/Features/Core/Portable/ExternalAccess/Watch/Api/WatchHotReloadService.cs
  src/Features/TestUtilities/EditAndContinue/EditAndContinueTestHelpers.cs
  src/Features/VisualBasicTest/EditAndContinue/ActiveStatementTests.vb
  src/Features/VisualBasicTest/EditAndContinue/StatementEditingTests.vb
  src/Features/VisualBasicTest/EditAndContinue/TopLevelEditingTests.vb
Labels: Area-Interactive, untriaged

#73266 Move test reference assemblies forward
  .vscode/tasks.json
  eng/Directory.Packages.props
  src/Compilers/CSharp/Test/CommandLine/CommandLineTestBase.cs
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/Compilers/Core/CodeAnalysisTest/Analyzers/AnalyzerFileReferenceAppDomainTests.cs
  src/Compilers/Server/VBCSCompilerTests/AnalyzerConsistencyCheckerTests.cs
  src/Compilers/Test/Core/AssemblyLoadTestFixture.cs
  src/Compilers/Test/Core/Platform/Desktop/TestHelpers.cs
  src/Compilers/Test/Core/TargetFrameworkUtil.cs
  src/Compilers/Test/Core/TestBase.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
  src/Compilers/VisualBasic/Test/Semantic/Semantics/RequiredMembersTests.vb
  src/EditorFeatures/Test/MetadataAsSource/AbstractMetadataAsSourceTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/LocalsTests.cs
  src/Scripting/CSharpTest/InteractiveSessionTests.cs
  src/Scripting/CoreTestUtilities/TestCompilationFactory.cs
Labels: Area-Compilers, untriaged

#73278 Document breaking change: Collection expression for type implementing `IEnumerable` must have elements implicitly convertible to `object`
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 8.md
Labels: Area-Compilers, untriaged

#73287 Move AsyncBatchingWorkQueue usage in telemetry to TelemetryLogging level
  src/Features/LanguageServer/Protocol/Handler/RequestTelemetryLogger.cs
  src/VisualStudio/Core/Def/Telemetry/Shared/AggregatingTelemetryLog.cs
  src/VisualStudio/Core/Def/Telemetry/Shared/AggregatingTelemetryLogManager.cs
  src/VisualStudio/Core/Def/Telemetry/Shared/TelemetryLogProvider.cs
  src/Workspaces/Core/Portable/Telemetry/TelemetryLogging.cs
Labels: Area-IDE, untriaged

#73294 Pull reading of last storage subsystem out of lock
  src/Tools/IdeBenchmarks/SQLitePersistentStorageBenchmark.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/AbstractPersistentStorageTests.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/SQLiteV2PersistentStorageTests.cs
  src/Workspaces/Core/Portable/Storage/AbstractPersistentStorageService.cs
  src/Workspaces/Core/Portable/Storage/LegacyPersistentStorageService.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorageService.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_SolutionSerialization.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/AbstractPersistentStorage.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/IChecksummedPersistentStorage.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/NoOpPersistentStorage.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/NoOpPersistentStorageService.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/SolutionKey.cs
Labels: Area-IDE, untriaged

#73190 Lower drop retention from 10 years to 3 months
  azure-pipelines-official.yml
Labels: Area-Infrastructure, untriaged

#73295 Pull reading of last storage subsystem out of lock (part2)
  src/EditorFeatures/Test/Preview/PreviewWorkspaceTests.cs
  src/Tools/AnalyzerRunner/IncrementalAnalyzerRunner.cs
  src/Tools/IdeBenchmarks/SQLitePersistentStorageBenchmark.cs
  src/Tools/IdeCoreBenchmarks/FindReferencesBenchmarks.cs
  src/Tools/IdeCoreBenchmarks/NavigateToBenchmarks.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/AbstractPersistentStorageTests.cs
  src/VisualStudio/CSharp/Test/PersistentStorage/SQLiteV2PersistentStorageTests.cs
  src/Workspaces/Core/Portable/FindSymbols/Shared/AbstractSyntaxIndex_Persistence.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolTree/SymbolTreeInfo_Serialization.cs
  src/Workspaces/Core/Portable/Storage/AbstractPersistentStorageService.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/AbstractPersistentStorageService+SQLiteTestAccessor.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/Interop/SqlConnection.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPool+PooledConnection.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLiteConnectionPoolService.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage+PooledConnection.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.Accessor.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorageService.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_FlushWrites.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_StringIds.cs
  src/Workspaces/Core/Portable/Storage/SQLite/v2/SQLitePersistentStorage_Threading.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/AbstractPersistentStorage.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/IPersistentStorage.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/NoOpPersistentStorage.cs
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassification/RemoteSemanticClassificationService.Caching.cs
Labels: Area-IDE, untriaged

#73046 Allow unsafe blocks in iterators
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 9.md
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/BinderFactory.BinderFactoryVisitor.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Flags.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Unsafe.cs
  src/Compilers/CSharp/Portable/Binder/ExecutableCodeBinder.cs
  src/Compilers/CSharp/Portable/Binder/LocalBinderFactory.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit2/Emit/NumericIntPtrTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NativeIntegerTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/UnsafeTests.cs
Labels: Area-Compilers, untriaged, New Feature - Ref/Unsafe in Iterators/Async

#73100 Ensure source paths are comparable with editorconfig directory paths
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/Core/CodeAnalysisTest/Analyzers/AnalyzerConfigTests.cs
  src/Compilers/Core/CodeAnalysisTest/FileSystem/PathUtilitiesTests.cs
  src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs
  src/Compilers/Core/Portable/FileSystem/PathUtilities.cs
Labels: Area-Compilers, untriaged

#73281 Handle ref safety analysis for type parameters with 'allows ref struct' constraint
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ConditionalAccess.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs
  src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
Labels: Area-Compilers, untriaged, New Feature - RefStructInterfaces

#73308 Replay updates
  src/Tools/Replay/README.md
  src/Tools/Replay/Replay.cs
Labels: Area-Infrastructure, untriaged

#73239 Resolve extension members in all non-invocation contexts
  src/Compilers/CSharp/Portable/Binder/Binder.IdentifierUsedAsValueFinder.cs
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Await.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_InterpolatedString.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Query.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/MethodGroupResolution.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversion.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionKind.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionKindExtensions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
  src/Compilers/CSharp/Test/Emit3/ExtensionTypeTests.cs
Labels: Area-Compilers, untriaged, New Language Feature - Roles

#73313 Move IsBuildOnlyDiagnostic to use a switch expression
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
Labels: Area-Compilers, untriaged

#73289 Expose some useful helper methods
  src/Tools/ExternalAccess/Razor/RazorUri.cs
  src/Tools/ExternalAccess/Razor/SolutionExtensions.cs
Labels: Area-IDE, untriaged

#73320 Switch to a producer/consumer queue to search for add-using results.
  src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs
Labels: Area-IDE, untriaged

#73322 Switch to a producer/consumer queue to search for computing refactorings
  src/Features/Core/Portable/CodeRefactorings/CodeRefactoringService.cs
Labels: Area-IDE, untriaged

#73323 Provide a ProducerConsumer helper for processing a sequence of items in parallel.
  src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs
  src/Features/Core/Portable/CodeRefactorings/CodeRefactoringService.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.CachedDocumentSearch.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.GeneratedDocumentSearch.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.NormalSearch.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs
  src/Workspaces/Core/Portable/Shared/Utilities/ProducerConsumer.cs
  src/Workspaces/Remote/Core/RemoteHostAssetWriter.cs
Labels: Area-IDE, untriaged

#73311 Add AutomationPeer for inheritance marign glyph
  src/VisualStudio/Core/Def/InheritanceMargin/MarginGlyph/InheritanceMarginGlyph.cs
Labels: Area-IDE, untriaged

#73324 Move more code over to ProducerConsumer model.
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.CachedDocumentSearch.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.GeneratedDocumentSearch.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.NormalSearch.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.cs
  src/Features/Core/Portable/NavigateTo/IRemoteNavigateToSearchService.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.DiagnosticProvider.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs
  src/Workspaces/Core/Portable/CodeFixesAndRefactorings/DocumentBasedFixAllProviderHelpers.cs
  src/Workspaces/Core/Portable/CodeRefactorings/FixAllOccurences/DocumentBasedFixAllProvider.cs
  src/Workspaces/Remote/ServiceHub/Services/NavigateToSearch/RemoteNavigateToSearchService.cs
Labels: Area-IDE, untriaged

#73305 Specially handle more scenarios for type parameters with 'allows ref struct' constraint
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/BinaryOperatorOverloadResolution.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitOperators.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ConditionalAccess.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectCreationExpression.cs
  src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
Labels: Area-Compilers, untriaged, New Feature - RefStructInterfaces

#73333 Add tests for extensions and Find-Refs
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.ExtensionTypeSymbols.vb
Labels: Area-Compilers, untriaged

#73332 Port runtime's Parallel.ForEachAsync so we can use it on NetFx.
  src/Workspaces/Core/Portable/Shared/Utilities/RoslynParallel.NetFramework.cs
  src/Workspaces/Core/Portable/Shared/Utilities/RoslynParallel.cs
Labels: Area-IDE, untriaged

#73331 Move more code over to producer/consumer model
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionBatchFixAllProvider.cs
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionCodeFixProvider.PragmaWarningBatchFixAllProvider.cs
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionCodeFixProvider.RemoveSuppressionCodeAction.BatchFixer.cs
  src/Features/Core/Portable/Completion/CompletionService_GetCompletions.cs
  src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractImportCompletionCacheServiceFactory.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/DefaultExtensionMethodImportCompletionCacheServiceFactory.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/DefaultTypeImportCompletionCacheServiceFactory.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/IImportCompletionCacheService.cs
  src/Features/Core/Portable/Diagnostics/CodeAnalysisDiagnosticAnalyzerService.cs
  src/Features/Core/Portable/NavigateTo/NavigateToSearcher.cs
  src/Features/Lsif/Generator/Generator.cs
  src/Workspaces/Core/Portable/Diagnostics/Extensions.cs
  src/Workspaces/Core/Portable/FindSymbols/FindLiterals/FindLiteralsSearchEngine.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/Shared/Utilities/ProducerConsumer.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Project.cs
Labels: Area-IDE, untriaged

#69865 Add tasks for running a new vscode instance with a specific language server
  .vscode/tasks.json
  docs/contributing/Building, Debugging, and Testing on Unix.md
Labels: Area-Infrastructure, untriaged

#73336 Add helper for common pattern of producing an array.
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionBatchFixAllProvider.cs
  src/Features/Core/Portable/CodeRefactorings/CodeRefactoringService.cs
  src/Features/Core/Portable/Completion/CompletionService_GetCompletions.cs
  src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.DiagnosticProvider.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs
  src/Workspaces/Core/Portable/CodeFixesAndRefactorings/DocumentBasedFixAllProviderHelpers.cs
  src/Workspaces/Core/Portable/CodeRefactorings/FixAllOccurences/DocumentBasedFixAllProvider.cs
  src/Workspaces/Core/Portable/Diagnostics/Extensions.cs
  src/Workspaces/Core/Portable/Shared/Extensions/IAsyncEnumerableExtensions.cs
  src/Workspaces/Core/Portable/Shared/Utilities/ProducerConsumer.cs
  src/Workspaces/Remote/ServiceHub/Services/NavigateToSearch/RemoteNavigateToSearchService.cs
Labels: Area-IDE, untriaged

#73341 Add additional diagnostic info
  src/Workspaces/Core/Portable/Serialization/SerializerService_Reference.cs
Labels: Area-IDE, untriaged

#73343 Switch to static local functions
  src/EditorFeatures/CSharpTest/Formatting/CodeCleanupTests.cs
  src/EditorFeatures/Core.Wpf/Lightup/LightupHelpers.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/AbstractCodeActionOrUserDiagnosticTest.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/MissingAssemblyTests.cs
  src/ExpressionEvaluator/Core/Test/ExpressionCompiler/ExpressionCompilerTestHelpers.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/PropertySubPatternCompletionProvider.cs
  src/Features/CSharpTest/GenerateComparisonOperators/GenerateComparisonOperatorsTests.cs
  src/Features/DiagnosticsTestUtilities/CodeActionsLegacy/AbstractCodeActionOrUserDiagnosticTest_NoEditor.cs
  src/Tools/BuildBoss/SolutionCheckerUtil.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/InteractiveWindowInProcess.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService_Reference.cs
  src/Workspaces/CoreTest/ObjectSerializationTests.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
Labels: Area-IDE, untriaged

#73329 Improve analyzer consistency check message
  src/Compilers/Core/CodeAnalysisTest/Analyzers/AnalyzerFileReferenceTests.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs
  src/Compilers/Server/VBCSCompiler/AnalyzerConsistencyChecker.cs
  src/Compilers/Server/VBCSCompilerTests/AnalyzerConsistencyCheckerTests.cs
Labels: Area-Compilers, untriaged

#73334 Add additional extension type tests
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/EditorFeatures/Test2/IntelliSense/CSharpSignatureHelpCommandHandlerTests.vb
  src/EditorFeatures/TestUtilities2/Intellisense/TestState.vb
  src/EditorFeatures/TestUtilities2/Intellisense/TestStateFactory.vb
Labels: Area-IDE, untriaged

#73001 Razor fallback changes
  src/Compilers/CSharp/Portable/Parser/Lexer.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Syntax/SyntaxFactory.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxTokenParser.cs
  src/Compilers/CSharp/Test/Syntax/LexicalAndXml/LexicalErrorTests.cs
  src/Compilers/CSharp/Test/Syntax/LexicalAndXml/LexicalTests.cs
  src/Compilers/CSharp/Test/Syntax/LexicalAndXml/SyntaxTokenParserTests.cs
  src/Compilers/Core/Portable/InternalUtilities/RoslynExperiments.cs
Labels: Area-Compilers, untriaged

#73350 Update 17.11 configs after VS snap
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#73352 Remove unused type
  src/VisualStudio/Core/Def/AnalyzerDependency/AnalyzerFileWatcherService.cs
  src/VisualStudio/Core/Def/LanguageService/AbstractLanguageService`2.cs
Labels: Area-IDE, untriaged

#73345 Fix issue producing metadata references in VS
  src/VisualStudio/Core/Def/ProjectSystem/MetadataReferences/VisualStudioMetadataReferenceManager.MetadataCache.cs
  src/VisualStudio/Core/Def/ProjectSystem/MetadataReferences/VisualStudioMetadataReferenceManager.NativeMethods.cs
  src/VisualStudio/Core/Def/ProjectSystem/MetadataReferences/VisualStudioMetadataReferenceManager.cs
  src/VisualStudio/Core/Def/ProjectSystem/MetadataReferences/VisualStudioMetadataReferenceManagerFactory.cs
  src/VisualStudio/Core/Def/ProjectSystem/MetadataReferences/VisualStudioMetadataReferenceProviderServiceFactory.cs
  src/VisualStudio/Core/Def/ProjectSystem/MetadataReferences/VisualStudioPortableExecutableReference.cs
  src/VisualStudio/Core/Test/ReferenceManager/VisualStudioMetadataReferenceManagerTests.vb
  src/VisualStudio/TestUtilities2/ProjectSystemShim/Framework/TestEnvironment.vb
Labels: Area-IDE, untriaged

#73351 Move to instantiating and setting up the language service on a bg thread
  src/VisualStudio/Core/Def/LanguageService/AbstractLanguageService`2.IVsLanguageDebugInfo.cs
  src/VisualStudio/Core/Def/LanguageService/AbstractLanguageService`2.cs
  src/VisualStudio/Core/Def/LanguageService/AbstractPackage`2.cs
Labels: Area-IDE, untriaged

#73349 Defer instantiating debugger related feature components until needed
  src/VisualStudio/Core/Def/LanguageService/AbstractLanguageService`2.cs
Labels: Area-IDE, untriaged

#73355 Turn on NRT for AbstractLanguageService
  src/VisualStudio/Core/Def/LanguageService/AbstractLanguageService`2.cs
Labels: Area-IDE, untriaged

#73358 Simplify progress scope code
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionBatchFixAllProvider.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs
Labels: Area-IDE, untriaged

#73359 Remove VersionStamp serialization
  src/Workspaces/Core/Portable/Workspace/Solution/VersionStamp.cs
  src/Workspaces/CoreTest/SerializationTests.cs
Labels: Area-IDE, untriaged

#73361 Expose a few things to Razor
  src/Tools/ExternalAccess/Razor/ChecksumWrapper.cs
  src/Tools/ExternalAccess/Razor/RazorUri.cs
  src/Tools/ExternalAccess/Razor/SolutionExtensions.cs
  src/Tools/ExternalAccess/Razor/TextDocumentExtensions.cs
Labels: Area-IDE, untriaged

#73360 Take MetadataAsSource out of Roslyn package startup path
  src/EditorFeatures/CSharpTest/PdbSourceDocument/AbstractPdbSourceDocumentTests.cs
  src/EditorFeatures/CSharpTest/PdbSourceDocument/PdbSourceDocumentTests.cs
  src/EditorFeatures/Test/MetadataAsSource/AbstractMetadataAsSourceTests.TestContext.cs
  src/Features/Core/Portable/MetadataAsSource/IMetadataAsSourceFileService.cs
  src/Features/Core/Portable/MetadataAsSource/MetadataAsSourceFileService.cs
  src/VisualStudio/Core/Def/Implementation/VisualStudioMetadataAsSourceFileSupportService.cs
  src/VisualStudio/Core/Def/RoslynPackage.cs
  src/Workspaces/CoreTestUtilities/Workspaces/TestWorkspace`1.cs
Labels: Area-IDE, untriaged

#73335 Add public API for ref like type parameters
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/BinaryOperatorOverloadResolution.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitOperators.cs
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/CSharpSymbolMatcher.cs
  src/Compilers/CSharp/Portable/Emitter/Model/TypeParameterSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/NoPia/EmbeddedTypeParameter.cs
  src/Compilers/CSharp/Portable/Lowering/Instrumentation/LocalStateTracingInstrumenter.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Members.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.TypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AssemblySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs
  src/Compilers/CSharp/Portable/Symbols/ErrorTypeSymbol.ErrorTypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/MemberSignatureComparer.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PETypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/TypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/TypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/CrefTypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/IndexedTypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/ReadOnlyListType/SynthesizedReadOnlyListTypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedInlineArrayTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/SynthesizedSimpleMethodTypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/Wrapped/WrappedTypeParameterSymbol.cs
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Core/Portable/RuntimeCapability.cs
  src/Compilers/Core/Portable/Symbols/ITypeParameterSymbol.cs
  src/Compilers/VisualBasic/Portable/Symbols/AssemblySymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/TypeParameterSymbol.vb
  src/Compilers/VisualBasic/Test/Symbol/Microsoft.CodeAnalysis.VisualBasic.Symbol.UnitTests.vbproj
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/RefStructInterfacesTests.vb
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EETypeParameterSymbol.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/SimpleTypeParameterSymbol.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeGeneration/Symbols/CodeGenerationTypeParameterSymbol.cs
Labels: Area-Compilers, untriaged, New Feature - RefStructInterfaces

#73356 Make fix-all code action more parallel
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs
  src/Workspaces/Core/Portable/CodeFixesAndRefactorings/DocumentBasedFixAllProviderHelpers.cs
  src/Workspaces/Core/Portable/CodeRefactorings/FixAllOccurences/DocumentBasedFixAllProvider.cs
  src/Workspaces/Core/Portable/WorkspacesResources.resx
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.cs.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.de.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.es.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.fr.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.it.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ja.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ko.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.pl.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.pt-BR.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ru.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.tr.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.zh-Hans.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.zh-Hant.xlf
Labels: Area-IDE, untriaged

#73250 Partial properties: diagnostics for mismatch between parts
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Generated/ErrorFacts.Generated.cs
  src/Compilers/CSharp/Portable/Symbols/MemberSymbolExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/PublicModel/MethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodOrUserDefinedOperatorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertyAccessorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs
  src/Compilers/CSharp/Test/Emit/PrivateProtected.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/RecordTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/BindingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/ReadOnlyStructsTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/TopLevelStatementsTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/PartialPropertiesTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/MethodTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ParserErrorMessageTests.cs
  src/Compilers/Test/Core/Assert/AssertEx.cs
Labels: Area-Compilers, New Feature - Partial Properties

#73370 Remove unnecessary project reference to System.Text.Json
  src/Workspaces/Core/MSBuild.BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj
Labels: Area-IDE, untriaged

#73086 Use a simple temp instead of InlineArray1
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/ParamsCollectionTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
Labels: Area-Compilers, untriaged

#73372 Have code action tests run in OOP mode by default
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/AbstractCodeActionOrUserDiagnosticTest.cs
  src/EditorFeatures/DiagnosticsTestUtilities/Diagnostics/AbstractDiagnosticProviderBasedUserDiagnosticTest.cs
  src/EditorFeatures/DiagnosticsTestUtilities/Diagnostics/AbstractUserDiagnosticTest.cs
  src/Features/CSharpTest/ConvertTupleToStruct/ConvertTupleToStructTests.cs
  src/Features/CSharpTest/Diagnostics/Suppression/SuppressionTests.cs
  src/Features/DiagnosticsTestUtilities/CodeActionsLegacy/AbstractCodeActionOrUserDiagnosticTest_NoEditor.cs
  src/Features/DiagnosticsTestUtilities/Diagnostics/AbstractDiagnosticProviderBasedUserDiagnosticTest_NoEditor.cs
  src/Features/DiagnosticsTestUtilities/Diagnostics/AbstractSuppressionDiagnosticTest_NoEditor.cs
  src/Features/DiagnosticsTestUtilities/Diagnostics/AbstractUnncessarySuppressionDiagnosticTest.cs
  src/Features/DiagnosticsTestUtilities/Diagnostics/AbstractUserDiagnosticTest_NoEditor.cs
  src/Features/VisualBasicTest/SimplifyTypeNames/SimplifyTypeNamesTests.vb
  src/Workspaces/Core/Portable/Serialization/SerializedMetadataReference.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService_Reference.cs
  src/Workspaces/CoreTest/FindAllDeclarationsTests.TestSolutionsAndProject.cs
  src/Workspaces/CoreTestUtilities/Remote/InProcRemostHostClient.cs
  src/Workspaces/CoreTestUtilities/Workspaces/TestWorkspace`1.cs
Labels: Area-IDE, untriaged

#73381 Have code refactoring tests run in OOP mode by default
  src/EditorFeatures/CSharpTest/CodeActions/InitializeParameter/AddParameterCheckTests.cs
  src/EditorFeatures/CSharpTest/CodeActions/InlineMethod/CSharpInlineMethodTests.cs
  src/EditorFeatures/VisualBasicTest/CodeActions/InlineMethod/VisualBasicInlineMethodTests.vb
  src/Features/CSharpTest/AddDebuggerDisplay/AddDebuggerDisplayTests.cs
  src/Features/CSharpTest/ConvertCast/ConvertDirectCastToTryCastTests.cs
  src/Features/CSharpTest/ConvertCast/ConvertTryCastToDirectCastTests.cs
  src/Features/CSharpTest/ConvertIfToSwitch/ConvertIfToSwitchTests.cs
  src/Features/CSharpTest/ConvertNamespace/ConvertNamespaceRefactoringTests.cs
  src/Features/CSharpTest/ConvertPrimaryToRegularConstructor/ConvertPrimaryToRegularConstructorTests.cs
  src/Features/CSharpTest/ConvertProgram/ConvertToProgramMainRefactoringTests.cs
  src/Features/CSharpTest/ConvertProgram/ConvertToTopLevelStatementsRefactoringTests.cs
  src/Features/CSharpTest/ConvertToInterpolatedString/ConvertConcatenationToInterpolatedStringTests.cs
  src/Features/CSharpTest/ConvertToRawString/ConvertInterpolatedStringToRawStringTests.cs
  src/Features/CSharpTest/ConvertToRawString/ConvertRegularStringToRawStringTests.cs
  src/Features/CSharpTest/ConvertTupleToStruct/ConvertTupleToStructTests.cs
  src/Features/CSharpTest/EnableNullable/EnableNullableTests.cs
  src/Features/CSharpTest/GenerateDefaultConstructors/GenerateDefaultConstructorsTests.cs
  src/Features/CSharpTest/GenerateFromMembers/AddConstructorParametersFromMembers/AddConstructorParametersFromMembersTests.cs
  src/Features/CSharpTest/ReplaceConditionalWithStatements/ReplaceConditionalWithStatementsTests.cs
  src/Features/CSharpTest/UseNamedArguments/UseNamedArgumentsTests.cs
  src/Features/CSharpTest/UseRecursivePatterns/UseRecursivePatternsRefactoringTests.cs
  src/Features/DiagnosticsTestUtilities/CodeActions/CSharpCodeRefactoringVerifier`1+Test.cs
  src/Features/DiagnosticsTestUtilities/CodeActions/VisualBasicCodeRefactoringVerifier`1+Test.cs
  src/Features/VisualBasicTest/AddConstructorParametersFromMembers/AddConstructorParametersFromMembersTests.vb
  src/Features/VisualBasicTest/AddDebuggerDisplay/AddDebuggerDisplayTests.vb
  src/Features/VisualBasicTest/ConvertCast/ConvertDirectCastToTryCastTests.vb
  src/Features/VisualBasicTest/ConvertCast/ConvertTryCastToDirectCastTests.vb
  src/Features/VisualBasicTest/ConvertToInterpolatedString/ConvertConcatenationToInterpolatedStringTests.vb
  src/Features/VisualBasicTest/GenerateDefaultConstructors/GenerateDefaultConstructorsTests.vb
  src/Features/VisualBasicTest/IntroduceParameter/IntroduceParameterTests.vb
  src/Features/VisualBasicTest/ReplaceConditionalWithStatements/ReplaceConditionalWithStatementsTests.vb
  src/Workspaces/Core/Portable/Serialization/SerializerService_Reference.cs
Labels: Area-IDE, untriaged

#73385 Share fix-all code
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs
  src/Workspaces/Core/Portable/CodeFixesAndRefactorings/DocumentBasedFixAllProviderHelpers.cs
  src/Workspaces/Core/Portable/CodeRefactorings/FixAllOccurences/DocumentBasedFixAllProvider.cs
Labels: Area-IDE, untriaged

#73364 EnC: Add asterisk based assembly version docs
  docs/wiki/EnC-Supported-Edits.md
Labels: Area-Infrastructure, untriaged

#73383 Do syntactic cleanup during the initial pass of producing fixed documents in fix-all.
  src/Analyzers/CSharp/CodeFixes/MakeMethodAsynchronous/CSharpMakeMethodAsynchronousCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/InvokeDelegateWithConditionalAccess/InvokeDelegateWithConditionalAccessTests_FixAllTests.cs
  src/Analyzers/CSharp/Tests/RemoveAsyncModifier/RemoveAsyncModifierTests.cs
  src/Analyzers/CSharp/Tests/UseCoalesceExpression/UseCoalesceExpressionForNullableTernaryConditionalCheckTests.cs
  src/EditorFeatures/VisualBasicTest/CodeActions/InlineMethod/VisualBasicInlineMethodTests.vb
  src/Features/CSharpTest/ConvertLinq/ConvertForEachToLinqQueryTests.cs
  src/Features/CSharpTest/InlineTemporary/InlineTemporaryTests.cs
  src/Features/CSharpTest/InvertIf/InvertIfTests.cs
  src/Features/Core/Portable/InlineMethod/AbstractInlineMethodRefactoringProvider.cs
  src/Workspaces/Core/Portable/CodeActions/CodeAction.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs
  src/Workspaces/Core/Portable/CodeFixesAndRefactorings/DocumentBasedFixAllProviderHelpers.cs
  src/Workspaces/Core/Portable/CodeRefactorings/FixAllOccurences/DocumentBasedFixAllProvider.cs
Labels: Area-IDE, untriaged

#73391 Fixup improper parenthesized expression in 'use pattern combinators'.
  src/Analyzers/CSharp/Analyzers/UsePatternCombinators/CSharpUsePatternCombinatorsDiagnosticAnalyzer.cs
  src/Features/CSharp/Portable/Debugging/DataTipInfoGetter.cs
  src/Features/CSharpTest/UsePatternCombinators/CSharpUsePatternCombinatorsDiagnosticAnalyzerTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeStyle/TypeStyle/TypeStyleHelper.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ExpressionSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs
Labels: Area-IDE, untriaged

#73392 Fix issue with improper formatting in introduce-variable
  src/Features/CSharpTest/IntroduceVariable/IntroduceVariableTests.cs
  src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.AbstractIntroduceVariableCodeAction.cs
  src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.CodeAction.cs
  src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.IntroduceVariableAllOccurrenceCodeAction.cs
  src/Features/Core/Portable/IntroduceVariable/IntroduceVariableCodeRefactoringProvider.cs
Labels: Area-IDE, untriaged

#73394 Provide solution methods to allow updating a bulk set of documents at once.
  src/VisualStudio/Core/Def/CodeCleanup/AbstractCodeCleanUpFixer.cs
  src/Workspaces/Core/Portable/CodeActions/CodeAction_Cleanup.cs
  src/Workspaces/Core/Portable/CodeFixesAndRefactorings/DocumentBasedFixAllProviderHelpers.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.CompilationTracker_Generators.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.GeneratedFileReplacingCompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.TranslationAction_Actions.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentStates.cs
Labels: Area-IDE, untriaged

#73395 Use null for diagnostic ExpandedMessage so the client falls back appropriately
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
Labels: Area-IDE, untriaged

#73396 Update features to fork solution once instead of forking once per changed document.
  src/Analyzers/Core/CodeFixes/MakeMethodSynchronous/AbstractMakeMethodSynchronousCodeFixProvider.cs
  src/EditorFeatures/Core/RenameTracking/RenameTrackingTaggerProvider.RenameTrackingCommitter.cs
  src/Features/CSharp/Portable/CodeRefactorings/EnableNullable/EnableNullableCodeRefactoringProvider.cs
  src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionBatchFixAllProvider.cs
  src/Features/Core/Portable/CodeRefactorings/SyncNamespace/AbstractChangeNamespaceService.cs
  src/Features/Core/Portable/IntroduceParameter/AbstractIntroduceParameterCodeRefactoringProvider.cs
  src/Features/Core/Portable/MoveToNamespace/AbstractMoveToNamespaceService.cs
  src/VisualStudio/Core/Def/CodeCleanup/AbstractCodeCleanUpFixer.cs
  src/Workspaces/Core/Portable/CodeActions/CodeAction_Cleanup.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs
  src/Workspaces/Core/Portable/CodeFixesAndRefactorings/DocumentBasedFixAllProviderHelpers.cs
  src/Workspaces/Core/Portable/LinkedFileDiffMerging/LinkedFileDiffMergingSession.cs
  src/Workspaces/Core/Portable/Remote/RemoteUtilities.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.cs
  src/Workspaces/Remote/ServiceHub/Services/ConvertTupleToStructCodeRefactoringProvider/RemoteConvertTupleToStructCodeRefactoringService.cs
Labels: Area-IDE, untriaged

#73373 Fix overload resolution regression around params parameters
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MemberAnalysisResult.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/ParamsCollectionTests.cs
Labels: Area-Compilers, untriaged, New Feature - ParamsCollections

#73366 EnC: workaround for empty display class
  src/Compilers/Core/Portable/Emit/EditAndContinue/DefinitionMap.cs
Labels: Area-Interactive, untriaged

#73276 Fix sorting of extensions from more specific to less
  src/Compilers/CSharp/Portable/Binder/BinderFlags.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Flags.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs
  src/Compilers/CSharp/Portable/Symbols/AliasSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/PublicSymbols/AnonymousManager.TypeOrDelegatePublicSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.TypeOrDelegateTemplateSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/ArrayTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/DynamicTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/ErrorTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/FunctionPointers/FunctionPointerTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/FunctionTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/NativeIntegerTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PointerTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ImplicitNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceExtensionTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceNamespaceSymbol.AliasesAndUsings.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceNonExtensionNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/SubstitutedNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/ReadOnlyListType/SynthesizedReadOnlyListEnumeratorTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/ReadOnlyListType/SynthesizedReadOnlyListTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedContainer.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedEmbeddedAttributeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedInlineArrayTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedPrivateImplementationDetailsType.cs
  src/Compilers/CSharp/Portable/Symbols/TypeParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/TypeUnification.cs
  src/Compilers/CSharp/Test/Emit3/ExtensionTypeTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MockNamedTypeSymbol.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EENamedTypeSymbol.cs
Labels: Area-Compilers, untriaged, New Language Feature - Roles

#73363 Specially handle more scenarios for type parameters with 'allows ref struct' constraint
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/InlineArrayTests.cs
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/ObjectAndCollectionInitializerTests.cs
Labels: Area-Compilers, untriaged, New Feature - RefStructInterfaces

#73016 Fix Double-to-Long overflow check
  src/Compilers/VisualBasic/Portable/Semantics/CompileTimeCalculations.vb
  src/Compilers/VisualBasic/Test/Semantic/Semantics/Conversions.vb
Labels: Area-Compilers, Community

#73399 Merge touch document actions
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.TranslationAction_Actions.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.cs
Labels: Area-IDE, untriaged

#73406 Fix http 401 in signed build pipeline
  azure-pipelines-official.yml
Labels: Area-Infrastructure, untriaged

#73405 Cherry pick fix for expanded message to 17.10
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
Labels: Area-IDE, untriaged

#73340 Improve C# grammar generator.
  src/Compilers/CSharp/Portable/Generated/CSharp.Generated.g4
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/Grammar/GrammarGenerator.cs
Labels: Area-Compilers, untriaged

#73185 Enable hosts to provide custom assembly resolution
  src/Compilers/Core/CodeAnalysisTest/AnalyzerAssemblyLoaderTests.cs
  src/Compilers/Core/CodeAnalysisTest/InvokeUtil.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.Core.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.Desktop.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/IAnalyzerAssemblyResolver.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/ShadowCopyAnalyzerAssemblyLoader.cs
  src/Tools/ExternalAccess/Razor/RazorAnalyzerAssemblyResolver.cs
  src/VisualStudio/Core/Test.Next/Remote/SnapshotSerializationTests.cs
  src/Workspaces/Core/Portable/Diagnostics/DefaultAnalyzerAssemblyLoaderService.cs
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
  src/Workspaces/Remote/ServiceHub/Host/RemoteAnalyzerAssemblyLoader.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteAnalyzerAssemblyLoaderService.cs
Labels: Area-Analyzers, Area-Compilers, untriaged

#73412 Improve fix-all progress bar experience
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActions/SuggestedAction.cs
  src/EditorFeatures/Core/CodeActions/IUIThreadOperationContextExtensions.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
  src/Workspaces/Core/Portable/WorkspacesResources.resx
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.cs.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.de.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.es.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.fr.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.it.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ja.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ko.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.pl.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.pt-BR.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ru.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.tr.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.zh-Hans.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.zh-Hant.xlf
Labels: Area-IDE, untriaged

#73419 Fix issues with JTF blocking in codemodel
  src/VisualStudio/Core/Impl/CodeModel/RootCodeModel.cs
Labels: Area-IDE, untriaged

#73418 Fix features with extension-types
  src/EditorFeatures/CSharpTest/NavigateTo/NavigateToTests.cs
  src/EditorFeatures/Core.Wpf/Classification/ClassificationTypeFormatDefinitions.cs
  src/EditorFeatures/Core.Wpf/NavigateTo/NavigateToItemProvider.Callback.cs
  src/EditorFeatures/Core/Classification/ClassificationTypeDefinitions.cs
  src/EditorFeatures/Core/EditorFeaturesResources.resx
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.cs.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.de.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.es.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.fr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.it.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ja.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ko.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pl.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pt-BR.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ru.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.tr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hans.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hant.xlf
  src/Features/CSharp/Portable/Completion/CompletionProviders/KeywordCompletionProvider.cs
  src/Features/Core/Portable/Common/SymbolDisplayPartKindTags.cs
  src/Features/Core/Portable/Common/TaggedText.cs
  src/Features/Core/Portable/Common/TextTags.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.InProcess.cs
  src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.cs
  src/Features/Core/Portable/NavigateTo/NavigateToItemKind.cs
  src/Features/Core/Portable/NavigateTo/RoslynNavigateToItem.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/CustomLspSemanticTokenNames.cs
  src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensSchema.cs
  src/Features/LanguageServer/Protocol/Handler/Symbols/WorkspaceSymbolsHandler.cs
  src/Features/Lsif/GeneratorTest/OutputFormatTests.vb
  src/Features/Lsif/GeneratorTest/SemanticTokensTests.vb
  src/VisualStudio/CSharp/Impl/Progression/CSharpProgressionLanguageService.cs
  src/VisualStudio/Core/Def/NavigateTo/RoslynNavigateToSearchCallback.cs
  src/VisualStudio/Core/Def/NavigateTo/RoslynSearchItemsSource.cs
  src/VisualStudio/Core/Def/Progression/GraphBuilder.cs
  src/VisualStudio/Core/Test/Progression/ContainsGraphQueryTests.vb
  src/Workspaces/CSharp/Portable/FindSymbols/CSharpDeclaredSymbolInfoFactoryService.cs
  src/Workspaces/Core/Portable/Classification/ClassificationTypeNames.cs
  src/Workspaces/Core/Portable/FindSymbols/TopLevelSyntaxTree/DeclaredSymbolInfo.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Project.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/MemberDeclarationSyntaxExtensions.cs
Labels: Area-IDE, untriaged

#73371 Remove IsCompatBreakingFeatureEnabled method
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/Parser/SyntaxParser.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ExtensionParsingTests.cs
Labels: Area-Compilers, untriaged, New Language Feature - Roles

#73378 Partial properties: basic indexer scenarios and signature mismatch diagnostics
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Symbols/PropertySymbolExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/ParamsCollectionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/PartialPropertiesTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs
Labels: Area-Infrastructure, untriaged

#73425 Avoid LOH allocation in text synchronization
  src/EditorFeatures/Core/Remote/SolutionChecksumUpdater.cs
Labels: Area-IDE, untriaged

#73440 Port tests of "Invert if" refactoring to `VerifyCS/VB`
  src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs
  src/Features/CSharpTest/InvertIf/InvertIfTests.Elseless.cs
  src/Features/CSharpTest/InvertIf/InvertIfTests.cs
  src/Features/VisualBasic/Portable/InvertIf/VisualBasicInvertIfCodeRefactoringProvider.MultiLine.vb
  src/Features/VisualBasic/Portable/InvertIf/VisualBasicInvertIfCodeRefactoringProvider.SingleLine.vb
  src/Features/VisualBasicTest/InvertIf/InvertMultiLineIfTests.vb
  src/Features/VisualBasicTest/InvertIf/InvertSingleLineIfTests.vb
Labels: Area-IDE, Community, untriaged

#73435 Make placement of raw string guide line independent of the space chars used
  src/EditorFeatures/Core.Wpf/StringIndentation/StringIndentationAdornmentManager.VisibleBlock.cs
Labels: Area-IDE, Community, untriaged

#73451 Improve memory allocs in interval trees
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/IntervalTree`1.cs
Labels: Area-IDE, untriaged

#73452 Produce less string allocs while formatting documents
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/BottomUpBaseIndentationFinder.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/FormattingExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/CommonFormattingHelpers.cs
Labels: Area-IDE, untriaged

#73456 Optimize suppress operations during formatting.
  src/Dependencies/PooledObjects/ArrayBuilder.cs
  src/Features/CSharp/Portable/BraceCompletion/CurlyBraceCompletionService.cs
  src/Features/Core/Portable/MetadataAsSource/AbstractMetadataAsSourceService+CompatAbstractMetadataFormattingRule.cs
  src/Workspaces/CSharp/Portable/Formatting/TypingFormattingRule.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/DefaultOperationProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/BaseFormattingRule.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/ElasticTriviaFormattingRule.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/QueryExpressionFormattingRule.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/SpacingFormattingRule.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/SuppressFormattingRule.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/WrappingFormattingRule.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Indentation/CSharpSmartTokenFormatter.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ListExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Context/FormattingContext.InitialContextFinder.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Context/FormattingContext.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Engine/AbstractFormatEngine.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Engine/ChainedFormattingRules.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Rules/AbstractFormattingRule.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Rules/CompatAbstractFormattingRule.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Rules/NextSuppressOperationAction.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Rules/Operations/FormattingOperations.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Indentation/SpecialFormattingOperation.vb
  src/Workspaces/VisualBasic/Portable/Formatting/DefaultOperationProvider.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Rules/ElasticTriviaFormattingRule.vb
Labels: Area-IDE, untriaged

#73458 Remove array allocations for formatting rules.
  src/Analyzers/Core/Analyzers/Formatting/FormatterHelper.cs
  src/Analyzers/Core/Analyzers/Formatting/FormattingAnalyzerHelper.cs
  src/Analyzers/Core/CodeFixes/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseConditionalExpression/AbstractUseConditionalExpressionCodeFixProvider.cs
  src/EditorFeatures/CSharp/AutomaticCompletion/AutomaticLineEnderCommandHandler.cs
  src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs
  src/EditorFeatures/Core/CommentSelection/AbstractCommentSelectionBase.cs
  src/EditorFeatures/TestUtilities/Formatting/CoreFormatterTestsBase.cs
  src/EditorFeatures/VisualBasic/LineCommit/CommitFormatter.vb
  src/EditorFeatures/VisualBasicTest/Formatting/VisualBasicFormatterTestBase.vb
  src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs
  src/Features/CSharp/Portable/DecompiledSource/CSharpDecompiledSourceService.cs
  src/Features/CSharp/Portable/MetadataAsSource/CSharpMetadataAsSourceService.cs
  src/Features/CSharp/Portable/UseAutoProperty/CSharpUseAutoPropertyCodeFixProvider.cs
  src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs
  src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/AbstractGenerateEqualsAndGetHashCodeService.cs
  src/Features/Core/Portable/MetadataAsSource/AbstractMetadataAsSourceService.cs
  src/Features/Core/Portable/UseAutoProperty/AbstractUseAutoPropertyCodeFixProvider.cs
  src/Features/LanguageServer/Protocol/Handler/Formatting/AbstractFormatDocumentHandlerBase.cs
  src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb
  src/Features/VisualBasic/Portable/MetadataAsSource/VisualBasicMetadataAsSourceService.vb
  src/Features/VisualBasic/Portable/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb
  src/Tools/ExternalAccess/OmniSharp/Formatting/OmniSharpFormatter.cs
  src/VisualStudio/Core/Def/LanguageService/AbstractLanguageService`2.IVsLanguageTextOps.cs
  src/VisualStudio/Core/Def/Venus/ContainedDocument.cs
  src/VisualStudio/Core/Def/Venus/ContainedLanguageCodeSupport.cs
  src/Workspaces/CSharp/Portable/Formatting/CSharpSyntaxFormattingService.cs
  src/Workspaces/Core/Portable/CodeCleanup/Providers/FormatCodeCleanupProvider.cs
  src/Workspaces/Core/Portable/Formatting/AbstractFormattingService.cs
  src/Workspaces/Core/Portable/Formatting/Formatter.cs
  src/Workspaces/CoreTestUtilities/Formatting/FormattingTestBase.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/CSharpSyntaxFormatting.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Engine/CSharpFormatEngine.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Indentation/CSharpSmartTokenFormatter.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/AbstractSyntaxFormatting.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Engine/AbstractFormatEngine.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Engine/ChainedFormattingRules.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/ISyntaxFormatting.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpRemoveUnnecessaryImportsService.cs
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/VisualBasicFormatEngine.vb
  src/Workspaces/VisualBasic/Portable/Formatting/VisualBasicSyntaxFormatting.vb
Labels: Area-IDE, untriaged

#73402 Test local functions with goto out of scope
  src/Compilers/CSharp/Test/Emit/CodeGen/GotoTest.cs
Labels: Area-Compilers, Test-Gap, untriaged

#73446 Add "First-class Span Types" feature status
  docs/Language Feature Status.md
Labels: Area-Compilers, untriaged

#73429 Recognize 'allows ref struct' constraint in VB compiler
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Types.cs
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
  src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/VisualBasicSymbolMatcher.vb
  src/Compilers/VisualBasic/Portable/Emit/NoPia/EmbeddedTypeParameter.vb
  src/Compilers/VisualBasic/Portable/Emit/TypeParameterSymbolAdapter.vb
  src/Compilers/VisualBasic/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousTypeOrDelegateTypeParameterSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/IndexedTypeParameterSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/InstanceErrorTypeSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PETypeParameterSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/MethodSignatureComparer.vb
  src/Compilers/VisualBasic/Portable/Symbols/ReducedExtensionMethodSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Retargeting/RetargetingTypeParameterSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/CrefTypeParameterSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceTypeParameterSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/SubstitutedTypeParameterSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/SynthesizedSymbols/SynthesizedClonedTypeParameterSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/TypeParameterSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Wrapped/WrappedTypeParameterSymbol.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/RefStructInterfacesTests.vb
  src/ExpressionEvaluator/VisualBasic/Source/ExpressionCompiler/Symbols/EETypeParameterSymbol.vb
  src/ExpressionEvaluator/VisualBasic/Source/ExpressionCompiler/Symbols/SimpleTypeParameterSymbol.vb
Labels: Area-Compilers, untriaged, New Feature - RefStructInterfaces

#73468 Stop overbuilding SemanticSearch.ReferenceAssemblies
  src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj
Labels: Area-Infrastructure, Community, untriaged

#73283 Update msbuild version to 17.3.4
  eng/Directory.Packages.props
  eng/SourceBuildPrebuiltBaseline.xml
  eng/Version.Details.xml
  eng/Versions.props
  src/Workspaces/Core/MSBuild.BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj
Labels: Area-IDE, Community, untriaged

#73433 Remove virtual from 'SourceMethodSymbolWithAttributes.SyntaxNode'
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs
Labels: Area-Compilers, untriaged

#73417 Update local deployment instructions
  docs/contributing/Building, Debugging, and Testing on Windows.md
Labels: Area-Compilers, Documentation

#73464 Properly dispose the SymbolSearchEngine
  src/Features/Core/Portable/SymbolSearch/SymbolSearchUpdateNoOpEngine.cs
  src/Features/Core/Portable/SymbolSearch/Windows/SymbolSearchUpdateEngine.cs
  src/VisualStudio/Core/Def/SymbolSearch/VisualStudioSymbolSearchService.cs
  src/Workspaces/Core/Portable/SymbolSearch/ISymbolSearchUpdateEngine.cs
Labels: Area-IDE, untriaged

#73471 Switch to cleaner patterns than explicit Task.Run
  src/EditorFeatures/Core.Wpf/InlineHints/InlineHintsTag.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActions/SuggestedAction.cs
  src/EditorFeatures/Core/GoToDefinition/AbstractGoToCommandHandler`2.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.SymbolComputer.cs
  src/Features/Core/Portable/ValueTracking/ValueTracker.OperationCollector.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Utilities/BrokeredServiceProxy.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/ProjectDependencyHelper.cs
  src/Features/LanguageServer/Protocol/Features/CodeFixes/CodeFixService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DiagnosticAnalyzerService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs
  src/Features/LanguageServer/Protocol/Features/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs
  src/VisualStudio/Core/Def/Library/ObjectBrowser/AbstractObjectBrowserLibraryManager.cs
  src/VisualStudio/Core/Def/NavigateTo/RoslynSearchItemsSource.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs
  src/Workspaces/Core/Portable/Simplification/AbstractSimplificationService.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.TranslationAction_Actions.cs
Labels: Area-IDE, untriaged

#73423 Net9 Reference Assemblies
  eng/Directory.Packages.props
  src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenSpanBasedStringConcatTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/InlineArrayTests.cs
  src/Compilers/CSharp/Test/Emit3/Microsoft.CodeAnalysis.CSharp.Emit3.UnitTests.csproj
  src/Compilers/Test/Core/TargetFrameworkUtil.cs
Labels: Area-Compilers, untriaged

#73475 Avoid enumeration allocations in formatting
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/SyntaxNodeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Engine/TokenData.cs
Labels: Area-IDE, untriaged

#73462 Use TextDocumentChangeRegistrationOptions for didChange registration
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/LanguageServer/RazorDynamicDocumentSyncRegistration.cs
  src/Features/LanguageServer/Protocol/Protocol/TextDocumentChangeRegistrationOptions.cs
Labels: Area-IDE, untriaged

#73481 Update bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: Area-Infrastructure, untriaged

#73407 Emit and roundtrip underlying instance field
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceExtensionTypeSymbol.cs
  src/Compilers/CSharp/Test/Emit3/ExtensionTypeTests.cs
  src/Compilers/Core/Portable/Symbols/WellKnownMemberNames.cs
Labels: Area-Compilers, untriaged, New Language Feature - Roles

#73444 Add more "ref in async" tests
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAwaitForeachTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAwaitUsingTests.cs
  src/Compilers/CSharp/Test/Emit2/Emit/NumericIntPtrTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/InlineArrayTests.cs
  src/Compilers/CSharp/Test/Emit3/RefUnsafeInIteratorAndAsyncTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefLocalsAndReturnsTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SpanStackSafetyTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/UnsafeTests.cs
Labels: Area-Compilers, untriaged, New Feature - Ref/Unsafe in Iterators/Async

#73487 Cache internal objects used by the formatting engine.
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Engine/CSharpFormatEngine.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Engine/CSharpStructuredTriviaFormatEngine.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Engine/Trivia/TriviaDataFactory.ComplexTrivia.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Engine/Trivia/TriviaDataFactory.FormattedComplexTrivia.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Engine/Trivia/TriviaDataFactory.ModifiedComplexTrivia.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Engine/Trivia/TriviaDataFactory.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Engine/AbstractTriviaDataFactory.AbstractComplexTrivia.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Engine/AbstractTriviaDataFactory.FormattedWhitespace.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Engine/AbstractTriviaDataFactory.ModifiedWhitespace.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Engine/AbstractTriviaDataFactory.Whitespace.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Engine/AbstractTriviaDataFactory.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Engine/TriviaData.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Engine/TriviaDataWithList.cs
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/Trivia/TriviaDataFactory.AbstractLineBreakTrivia.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/Trivia/TriviaDataFactory.ComplexTrivia.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/Trivia/TriviaDataFactory.FormattedComplexTrivia.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/Trivia/TriviaDataFactory.LineContinuationTrivia.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/Trivia/TriviaDataFactory.ModifiedComplexTrivia.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/Trivia/TriviaDataFactory.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/VisualBasicFormatEngine.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/VisualBasicStructuredTriviaFormatEngine.vb
Labels: Area-IDE, untriaged

#73477 Report external build errors using the platform's diagnostic brokered
  src/Features/Core/Portable/Diagnostics/BuildOnlyDiagnosticsService.cs
  src/Features/Core/Portable/Diagnostics/IBuildOnlyDiagnosticsService.cs
  src/Features/LanguageServer/Protocol/Features/CodeFixes/CodeFixService.cs
  src/Tools/ExternalAccess/FSharp/Internal/VisualStudio/FSharpProjectExternalErrorReporterFactory.cs
  src/VisualStudio/Core/Def/ProjectSystem/Legacy/AbstractLegacyProject.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/Core/Def/TableDataSource/Suppression/VisualStudioSuppressionFixService.cs
  src/VisualStudio/Core/Def/TaskList/ExternalErrorDiagnosticUpdateSource.cs
  src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs
  src/VisualStudio/Core/Test/Diagnostics/ExternalDiagnosticUpdateSourceTests.vb
Labels: Area-IDE, untriaged

#73495 Update attributes for STJ
  src/Features/LanguageServer/Protocol/Protocol/TextDocumentChangeRegistrationOptions.cs
Labels: Area-IDE, untriaged

#73493 Cache values in dependent project finder
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/DependentProjectsFinder.cs
Labels: Area-IDE, untriaged

#73494 Make getting a SourceText from an IDE parsed tree not hit the LOH.
  src/Workspaces/CSharp/Portable/Workspace/LanguageServices/CSharpSyntaxTreeFactoryService.ParsedSyntaxTree.cs
  src/Workspaces/Core/Portable/Shared/Extensions/SourceTextExtensions.cs
  src/Workspaces/Core/Portable/Workspace/Host/SyntaxTreeFactory/AbstractSyntaxTreeFactoryService.cs
  src/Workspaces/VisualBasic/Portable/Workspace/LanguageServices/VisualBasicSyntaxTreeFactoryService.ParsedSyntaxTree.vb
Labels: Area-IDE, untriaged

#73502 Follow up on merge of ref-unsafe-in-iterators-async feature
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
Labels: Area-Compilers, untriaged, New Feature - RefStructInterfaces

#73463 Implement keyword recommenders for `allows ref struct` constraint
  src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs
  src/EditorFeatures/CSharpTest/Classification/SyntacticClassifierTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/AllowsKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/RefKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/StructKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/WhereKeywordRecommenderTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/AllowsKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/RefKeywordRecommender.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/StructKeywordRecommender.cs
Labels: Area-Compilers, untriaged, New Feature - RefStructInterfaces

#73511 Switch to a sorted map to ensure that we produce the same value regardless of how it was constructed
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectId.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratorExecutionVersion.cs
  src/Workspaces/Core/Portable/Workspace/Workspace_SourceGeneration.cs
  src/Workspaces/CoreTest/SolutionTests/SourceGeneratorExecutionVersionMapTests.cs
Labels: Area-IDE, untriaged

#73512 Make the impl of SyntaxNode.GetText more efficient
  src/Compilers/Core/Portable/Syntax/SyntaxNode.cs
  src/Workspaces/CSharp/Portable/Workspace/LanguageServices/CSharpSyntaxTreeFactoryService.ParsedSyntaxTree.cs
  src/Workspaces/Core/Portable/Shared/Extensions/SourceTextExtensions.cs
  src/Workspaces/VisualBasic/Portable/Workspace/LanguageServices/VisualBasicSyntaxTreeFactoryService.ParsedSyntaxTree.vb
Labels: Area-Compilers, untriaged

#73461 Add runtime references to the devkit component output directory
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Microsoft.CodeAnalysis.LanguageServer.UnitTests.csproj
  src/VisualStudio/DevKit/Impl/Microsoft.VisualStudio.LanguageServices.DevKit.csproj
Labels: Area-Infrastructure, untriaged

#73518 Improve intense CPU hotspot in FAR (part 2)
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesDocumentState.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ConstructorSymbolReferenceFinder.cs
Labels: Area-IDE, untriaged

#73517 Improve intense CPU hotspot in FAR
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
Labels: Area-IDE, untriaged

#73437 Partial properties: attributes
  src/Compilers/CSharp/Portable/Symbols/Source/FieldSymbolWithAttributesAndModifiers.cs
  src/Compilers/CSharp/Portable/Symbols/Source/GlobalExpressionVariable.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceEnumConstantSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberFieldSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertyAccessorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedPrimaryConstructorParameterBackingFieldSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedBackingFieldSymbol.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_CallerInfoAttributes.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/PartialPropertiesTests.cs
  src/Compilers/Test/Utilities/CSharp/Extensions.cs
Labels: Area-Compilers, untriaged, New Feature - Partial Properties

#73521 Use nullable-disabled semantic model for obsoletion classification analysis
  src/Workspaces/Core/Portable/ObsoleteSymbol/AbstractObsoleteSymbolService.cs
Labels: Area-IDE, untriaged

#73516 Remove async from FindReferencesInDocument
  src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs
  src/Features/Core/Portable/ChangeSignature/DelegateInvokeMethodReferenceFinder.cs
  src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine_FindReferencesInDocuments.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractMemberScopedReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractTypeParameterSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ConstructorInitializerSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ConstructorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/DestructorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/EventSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ExplicitConversionSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ExplicitInterfaceMethodReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/FieldSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/IReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/LabelSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamedTypeSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamespaceSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/OperatorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/OrdinaryMethodReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ParameterSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/PropertyAccessorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/PropertySymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ReferenceFinders.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder.cs
Labels: Area-IDE, untriaged

#73524 Allow razor to override RazorDesignTimeTargets to ones shipped with tooling instead of the sdk
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Utilities/LanguageServerTestComposition.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Program.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/ServerConfigurationFactory.cs
Labels: Area-Infrastructure, untriaged

#73523 Improve performance of FAR
  src/Features/Core/Portable/FindUsages/AbstractFindUsagesService_FindReferences.cs
  src/Features/Core/Portable/FindUsages/IRemoteFindUsagesService.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferenceCache.cs
Labels: Area-IDE, untriaged

#73528 Convert from Newtonsoft to STJ in cohosting
  src/Tools/ExternalAccess/Razor/Cohost/RazorCohostLanguageClient.cs
  src/Tools/ExternalAccess/Razor/Cohost/RazorSemanticTokensRefreshQueueWrapper.cs
Labels: Area-IDE, untriaged

#73531 Update razor serialization
  eng/Directory.Packages.props
Labels: Area-Infrastructure, untriaged

#73490 Verify that ref-in-async errors are not downgraded to warnings in unsafe context
  src/Compilers/CSharp/Test/Emit3/RefUnsafeInIteratorAndAsyncTests.cs
Labels: Area-Compilers, untriaged, New Feature - Ref/Unsafe in Iterators/Async

#73532 Fix CPM in official builds (2)
  eng/InternalTools.props
  eng/common/internal/Directory.Build.props
  eng/common/internal/Tools.csproj
  global.json
Labels: Area-Infrastructure, untriaged

#73489 Update "ref in async" feature status
  docs/Language Feature Status.md
Labels: Area-Compilers, untriaged

#73485 Move AsyncBatchingWorkQueue usage in telemetry to TelemetryLogging level
  src/Features/LanguageServer/Protocol/Handler/RequestTelemetryLogger.cs
  src/VisualStudio/Core/Def/Telemetry/Shared/AggregatingTelemetryLog.cs
  src/VisualStudio/Core/Def/Telemetry/Shared/AggregatingTelemetryLogManager.cs
  src/VisualStudio/Core/Def/Telemetry/Shared/TelemetryLogProvider.cs
  src/VisualStudio/Core/Def/Telemetry/Shared/TelemetryLogger.cs
  src/VisualStudio/Core/Def/Telemetry/VisualStudioWorkspaceTelemetryService.cs
  src/VisualStudio/DevKit/Impl/Logging/VSCodeTelemetryLogger.cs
  src/Workspaces/Core/Portable/Telemetry/TelemetryLogging.cs
  src/Workspaces/Remote/ServiceHub/Services/ProcessTelemetry/RemoteWorkspaceTelemetryService.cs
Labels: Area-IDE, untriaged

#73533 Lower the amount of time FAR spends in classification by 4%
  src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.cs
  src/Workspaces/Core/Portable/Classification/SyntaxClassification/ISyntaxClassifier.cs
  src/Workspaces/Core/Portable/ExtensionManager/IExtensionManagerExtensions.cs
  src/Workspaces/VisualBasic/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.vb
Labels: Area-IDE, untriaged

#73525 Target net9.0 in tests and provide real implementation for RuntimeSupportsByRefLikeGenerics helper
  src/Compilers/CSharp/Portable/Symbols/AssemblySymbol.cs
  src/Compilers/CSharp/Test/Emit2/Emit/LocalStateTracing/LocalStateTracingTests.cs
  src/Compilers/CSharp/Test/Emit2/Microsoft.CodeAnalysis.CSharp.Emit2.UnitTests.csproj
  src/Compilers/CSharp/Test/Emit3/Microsoft.CodeAnalysis.CSharp.Emit3.UnitTests.csproj
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/Portable/SpecialMember.cs
  src/Compilers/Core/Portable/SpecialMembers.cs
  src/Compilers/VisualBasic/Portable/Symbols/AssemblySymbol.vb
  src/Compilers/VisualBasic/Test/Symbol/Microsoft.CodeAnalysis.VisualBasic.Symbol.UnitTests.vbproj
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/RefStructInterfacesTests.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
Labels: Area-Compilers, untriaged, New Feature - RefStructInterfaces

#73491 Fix assert in ref safety analysis around BoundConditionalReceiver node.
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
Labels: Area-Compilers, untriaged, New Feature - RefStructInterfaces

#73526 Install SDK in devcontainer based on global.json
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: Area-Infrastructure, untriaged

#73537 Fix up a couple places that create a buffer or sourcetext from strings
  src/EditorFeatures/Core.Wpf/Preview/PreviewFactoryService.cs
  src/EditorFeatures/Core/Preview/AbstractPreviewFactoryService.cs
  src/VisualStudio/Core/Def/Preview/FileChange.cs
  src/VisualStudio/Core/Impl/Options/AbstractOptionPreviewViewModel.cs
Labels: Area-IDE, untriaged

#73547 Avoid unnecessary allocations while finding token matches in a file
  src/Features/Core/Portable/FindUsages/DefinitionItemFactory.cs
Labels: Area-IDE, untriaged

#73515 Add a pinned pkcs entry
  eng/Directory.Packages.props
Labels: Area-Infrastructure, Community, untriaged

#73535 More classification perf fixes.
  src/Features/Core/Portable/EmbeddedLanguages/Classification/AbstractEmbeddedLanguageClassificationService.cs
  src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.cs
  src/Workspaces/Core/Portable/Classification/SyntaxClassification/AbstractNameSyntaxClassifier.cs
  src/Workspaces/VisualBasic/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.vb
Labels: Area-IDE, untriaged

#73562 Pack values for enum members
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenNullCoalescingAssignmentTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleEqualityTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/InlineArrayTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/RefReadonlyParameterTests.cs
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/BetterCandidates.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/IndexAndRangeTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OverloadResolutionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RawInterpolationTests_Handler.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SpanStackSafetyTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/StackAllocInitializerTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/StackAllocSpanExpressionsTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/Utf8StringsLiteralsTests.cs
Labels: Area-Compilers, untriaged, New Feature - RefStructInterfaces

#73561 Deal with some PROTOTYPE comments
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SpanStackSafetyTests.cs
  src/Compilers/Core/Portable/MetadataReader/MetadataHelpers.cs
Labels: Area-Compilers, untriaged, New Feature - RefStructInterfaces

#73546 Check language version for more scenarios
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/UsingStatementBinder.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
Labels: Area-Compilers, untriaged, New Feature - RefStructInterfaces

#73534 Batch FAR window update messages to lower refresh overhead.
  src/VisualStudio/Core/Def/FindReferences/Contexts/AbstractTableDataSourceFindUsagesContext.cs
Labels: Area-IDE, untriaged

#73565 Report EnC warning when entry point is changed
  src/Compilers/Test/Core/Assert/AssertEx.cs
  src/Features/CSharpTest/EditAndContinue/ActiveStatementTests.cs
  src/Features/CSharpTest/EditAndContinue/CSharpEditAndContinueAnalyzerTests.cs
  src/Features/CSharpTest/EditAndContinue/Helpers/EditAndContinueValidation.cs
  src/Features/CSharpTest/EditAndContinue/StatementEditingTests.cs
  src/Features/CSharpTest/EditAndContinue/TopLevelEditingTests.cs
  src/Features/CSharpTest/EditAndContinue/TrackingSpanTests.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSession.cs
  src/Features/Core/Portable/EditAndContinue/DocumentAnalysisResults.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueDiagnosticDescriptors.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/Core/Portable/EditAndContinue/RudeEditDiagnostic.cs
  src/Features/Core/Portable/EditAndContinue/RudeEditKind.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Features/TestUtilities/EditAndContinue/EditAndContinueTestHelpers.cs
  src/Features/TestUtilities/EditAndContinue/RudeEditDiagnosticDescription.cs
  src/Features/VisualBasicTest/EditAndContinue/ActiveStatementTests.vb
  src/Features/VisualBasicTest/EditAndContinue/TopLevelEditingTests.vb
  src/Features/VisualBasicTest/EditAndContinue/VisualBasicEditAndContinueAnalyzerTests.vb
Labels: Area-Interactive, untriaged

#73536 Disable nullable comparison optimization for decimals
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperator.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOptimizedNullableOperators.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenStructsAndEnum.cs
Labels: Area-Compilers, untriaged

#73571 Install .NET 9 Runtime on Single Machine CI
  eng/pipelines/test-windows-job-single-machine.yml
Labels: Area-Infrastructure, untriaged

#73573 Add the PR validation branch to publish data
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#73497 Remove dependency on all Roslyn assemblies from build host
  Roslyn.sln
  src/Compilers/Core/Portable/CaseInsensitiveComparison.cs
  src/Compilers/Core/Portable/Collections/ImmutableArrayExtensions.cs
  src/Compilers/Core/Portable/CommandLine/NoThrowStreamDisposer.cs
  src/Compilers/Core/Portable/Diagnostic/DiagnosticArrayExtensions.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AdditionalTextComparer.cs
  src/Compilers/Core/Portable/EncodedStringText.cs
  src/Compilers/Core/Portable/InternalUtilities/EncodingExtensions.cs
  src/Compilers/Core/Portable/InternalUtilities/EnumUtilties.cs
  src/Compilers/Core/Portable/InternalUtilities/TextKeyedCache.cs
  src/Compilers/Core/Portable/MetadataReference/AssemblyIdentityUtils.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratedCodeUtilities.cs
  src/Compilers/Core/Portable/SpecialTypeExtensions.cs
  src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor.cs
  src/Compilers/Core/Portable/Symbols/LanguageNames.cs
  src/Compilers/Core/Portable/Text/LargeText.cs
  src/Compilers/Core/Portable/Text/SourceText.cs
  src/Compilers/Core/Portable/Text/TextChangeRangeExtensions.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs
  src/Workspaces/Core/MSBuild.BuildHost/BuildHost.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/CSharp/CSharpProjectFile.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/Logging/DiagnosticLog.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/Logging/MSBuildDiagnosticLogItem.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/Logging/MSBuildDiagnosticLogger.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/CommandLineArgumentReader.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/Extensions.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/VisualBasic/VisualBasicProjectFile.cs
  src/Workspaces/Core/MSBuild.BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj
  src/Workspaces/Core/MSBuild.BuildHost/Rpc/Contracts/DiagnosticLogItem.cs
  src/Workspaces/Core/MSBuild.BuildHost/Rpc/Contracts/DocumentFileInfo.cs
  src/Workspaces/Core/MSBuild.BuildHost/Rpc/Contracts/IProjectFile.cs
  src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.Worker.cs
  src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs
  src/Workspaces/Core/MSBuild/Rpc/RemoteProjectFile.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ImmutableArrayExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/ConcatImmutableArray`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CodeGeneration/CSharpFlagsEnumGenerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeGeneration/AbstractFlagsEnumGenerator.cs
  src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicFlagsEnumGenerator.vb
Labels: Area-IDE, untriaged

#73572 [17.10] Disable nullable comparison optimization for decimals
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperator.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOptimizedNullableOperators.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenStructsAndEnum.cs
Labels: Area-Compilers, untriaged

#73588 Update Language Feature Status.md for Ref Struct Interfaces
  docs/Language Feature Status.md
Labels: Area-Compilers, untriaged

#73586 Check language version for more ref-struct-interfaces scenarios
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
Labels: Area-Compilers, untriaged, New Feature - RefStructInterfaces

#73587 Switch FAR data from an immutable dictionary to an immutable array
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/IVSTypeScriptFindUsagesContext.cs
  src/EditorFeatures/Core/LanguageServer/EditorLspReferencesResultCreationService.cs
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.vb
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/Api/VSTypeScriptDefinitionItemBase.cs
  src/Features/Core/Portable/FindUsages/DefinitionItem.DefaultDefinitionItem.cs
  src/Features/Core/Portable/FindUsages/DefinitionItem.DetachedDefinitionItem.cs
  src/Features/Core/Portable/FindUsages/DefinitionItem.cs
  src/Features/Core/Portable/FindUsages/IRemoteFindUsagesService.cs
  src/Features/Core/Portable/FindUsages/SourceReferenceItem.cs
  src/Features/Core/Portable/SemanticSearch/SearchCompilationFailureDefinitionItem.cs
  src/Features/Core/Portable/SemanticSearch/SearchExceptionDefinitionItem.cs
  src/Features/LanguageServer/Protocol/Handler/References/FindUsagesLSPContext.cs
  src/Features/LanguageServer/Protocol/Handler/References/ILspReferencesResultCreationService.cs
  src/Features/Test/FindUsages/DefinitionItemFactoryTests.cs
  src/VisualStudio/Core/Def/FindReferences/Contexts/AbstractTableDataSourceFindUsagesContext.cs
  src/VisualStudio/Core/Def/FindReferences/Entries/AbstractDocumentSpanEntry.cs
  src/VisualStudio/Core/Def/FindReferences/Entries/DocumentSpanEntry.cs
  src/VisualStudio/Core/Def/FindReferences/RoslynDefinitionBucket.cs
  src/VisualStudio/Core/Def/FindReferences/VisualStudioDefinitionsAndReferencesFactory.cs
  src/Workspaces/Core/Portable/Classification/IRemoteSemanticClassificationService.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/ReferenceLocation.cs
  src/Workspaces/Core/Portable/Remote/RemoteArguments.cs
Labels: Area-IDE, untriaged

#73221 Enable Arcade V3 publishing in PR Validation
  azure-pipelines-pr-validation.yml
  azure-pipelines.yml
  eng/Publishing.props
  eng/SymbolPublishingExclusionsFile.txt
  eng/build.ps1
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Microsoft.CodeAnalysis.LanguageServer.UnitTests.csproj
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Microsoft.CodeAnalysis.LanguageServer.csproj
Labels: Area-Infrastructure, untriaged

#70162 Include sqlite binaries to enable persistent storage in vscode
  eng/SymbolPublishingExclusionsFile.txt
  eng/build.ps1
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Microsoft.CodeAnalysis.LanguageServer.csproj
Labels: Area-IDE, untriaged

#73591 Revert "[main] Update dependencies from dotnet/arcade"
  eng/Version.Details.xml
  eng/common/internal/Directory.Build.props
  eng/common/internal/Tools.csproj
  global.json
Labels: Area-Infrastructure, untriaged

#73527 Partial properties: misc compiler layer work
  src/Compilers/CSharp/Portable/Binder/BinderFactory.BinderFactoryVisitor.cs
  src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.cs
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Test/Emit2/Diagnostics/GetDiagnosticsTests.cs
  src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/PartialPropertiesTests.cs
  src/Compilers/Test/Core/Assert/AssertEx.cs
  src/Compilers/Test/Utilities/CSharp/TestOptions.cs
Labels: Area-Compilers, untriaged, New Feature - Partial Properties

#73597 Comment out unused telemtry id
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-IDE, untriaged

#73601 Remove addOperationsScope as it wasn't being used anywhere
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource_Async.cs
  src/EditorFeatures/Test/CodeFixes/CodeFixServiceTests.cs
  src/EditorFeatures/TestUtilities/Diagnostics/MockDiagnosticAnalyzerService.cs
  src/Features/Core/Portable/CodeRefactorings/CodeRefactoringService.cs
  src/Features/Core/Portable/CodeRefactorings/ICodeRefactoringService.cs
  src/Features/Core/Portable/Diagnostics/IDiagnosticAnalyzerService.cs
  src/Features/LanguageServer/Protocol/Features/CodeCleanup/AbstractCodeCleanupService.cs
  src/Features/LanguageServer/Protocol/Features/CodeFixes/CodeFixService.FixAllDiagnosticProvider.cs
  src/Features/LanguageServer/Protocol/Features/CodeFixes/CodeFixService.cs
  src/Features/LanguageServer/Protocol/Features/CodeFixes/ICodeFixService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DiagnosticAnalyzerService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs
  src/Features/LanguageServer/Protocol/Features/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs
  src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionHelpers.cs
  src/VisualStudio/Core/Test/Diagnostics/ExternalDiagnosticUpdateSourceTests.vb
Labels: Area-IDE, untriaged

#73600 Only fetch options if needed
  src/VisualStudio/Core/Def/FindReferences/Contexts/AbstractTableDataSourceFindUsagesContext.cs
Labels: Area-IDE, untriaged

#73602 Update compiler version
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#73608 Add `AllowsKeywordRecommender` to `KeywordCompletionProvider`
  src/Features/CSharp/Portable/Completion/CompletionProviders/KeywordCompletionProvider.cs
Labels: Area-IDE, untriaged, New Feature - RefStructInterfaces

#73604 Fix issue where we might run code in the lightbulb post-disposal
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs
Labels: Area-IDE, untriaged

#73613 Move the remainder of FAR over to IAsyncEnumerable.
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptFindUsagesContext.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptFindUsagesService.cs
  src/EditorFeatures/Core/FindUsages/BufferedFindUsagesContext.cs
  src/EditorFeatures/Test2/FindReferences/FindReferencesCommandHandlerTests.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.vb
  src/EditorFeatures/TestUtilities/FindUsages/FindUsagesTestContext.cs
  src/EditorFeatures/TestUtilities/Microsoft.CodeAnalysis.EditorFeatures.Test.Utilities.csproj
  src/Features/Core/Portable/FindUsages/AbstractFindUsagesService.DefinitionTrackingContext.cs
  src/Features/Core/Portable/FindUsages/AbstractFindUsagesService.ProgressAdapter.cs
  src/Features/Core/Portable/FindUsages/FindUsagesContext.cs
  src/Features/Core/Portable/FindUsages/IFindUsagesContext.cs
  src/Features/Core/Portable/FindUsages/IRemoteFindUsagesService.cs
  src/Features/LanguageServer/Protocol/Features/FindUsages/SimpleFindUsagesContext.cs
  src/Features/LanguageServer/Protocol/Handler/References/FindUsagesLSPContext.cs
  src/Tools/ExternalAccess/FSharp/Internal/Editor/FindUsages/FSharpFindUsagesContext.cs
  src/VisualStudio/Core/Def/FindReferences/Contexts/AbstractTableDataSourceFindUsagesContext.cs
  src/Workspaces/Core/Portable/Shared/Extensions/IAsyncEnumerableExtensions.cs
  src/Workspaces/Remote/ServiceHub/Services/FindUsages/RemoteFindUsagesService.cs
Labels: Area-IDE, untriaged

#73616 Fix issue with add-import and cancellation
  src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs
Labels: Area-IDE, untriaged

#73609 Expose folding range functionality to Razor
  src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/Features/LanguageServer/Protocol/Handler/FoldingRanges/FoldingRangesHandler.cs
  src/Features/LanguageServer/Protocol/Microsoft.CodeAnalysis.LanguageServer.Protocol.csproj
  src/Features/LanguageServer/Protocol/Protocol/Converters/NaturalObjectConverter.cs
  src/Tools/ExternalAccess/Razor/Cohost/Handlers/FoldingRanges.cs
  src/Tools/ExternalAccess/Razor/RazorLanguageServerFactoryWrapper.cs
Labels: Area-IDE, untriaged
