Repository dotnet/roslyn, pull requests merged in 2024-09, with the labels that each got.

#74936 Move to the real System.ValueTuple ref
  eng/Directory.Packages.props
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_Tuples.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/CustomModifierCopyTests.cs
  src/Compilers/Test/Core/TargetFrameworkUtil.cs
  src/Compilers/Test/Core/TestBase.cs
  src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Tuples.vb
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTuples.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolDisplay/SymbolDisplayTests.vb
  src/EditorFeatures/Test/MetadataAsSource/AbstractMetadataAsSourceTests.cs
  src/EditorFeatures/Test/MetadataAsSource/MetadataAsSourceTests.CSharp.cs
  src/EditorFeatures/Test/MetadataAsSource/MetadataAsSourceTests.VisualBasic.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/MissingAssemblyTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/TupleTests.cs
  src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/MissingAssemblyTests.vb
  src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/TupleTests.vb
  src/Features/Test/FindUsages/DefinitionItemFactoryTests.cs
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
Labels: Area-Compilers, untriaged, VSCode

#74769 Optimize single spread collection expression for `List<T>`
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
Labels: Area-Compilers, Community, untriaged

#74969 Partial properties: duplicate `membersByName` before merging accessors
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
Labels: Area-Compilers, untriaged

#74978 Expose Go To Impl and Spell Check to Razor
  src/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/LanguageServer/Protocol/Handler/References/FindImplementationsHandler.cs
  src/LanguageServer/Protocol/Handler/SpellCheck/AbstractSpellCheckingHandler.cs
  src/Tools/ExternalAccess/Razor/Cohost/Handlers/DocumentSpellCheck.cs
  src/Tools/ExternalAccess/Razor/Cohost/Handlers/GoToImplementation.cs
Labels: Area-IDE, untriaged, VSCode

#74731 Add `Conversion.IsSpan` public API
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversion.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
Labels: Area-Compilers, untriaged, Needs API Review, New Feature - First-class Span Types

#74985 Revert "Load analyzers and generators in isolated ALCs in our OOP process"
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerWorkspaceFactory.cs
  src/VisualStudio/Core/Test.Next/Remote/SerializationValidator.cs
  src/VisualStudio/Core/Test.Next/Services/SolutionServiceTests.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService_Reference.cs
  src/Workspaces/Core/Portable/Workspace/Host/Metadata/IAnalyzerAssemblyLoaderProvider.cs
  src/Workspaces/Core/Portable/Workspace/IsolatedAnalyzerFileReference.cs
  src/Workspaces/Core/Portable/Workspace/IsolatedAnalyzerReferenceSet.Core.cs
  src/Workspaces/Core/Portable/Workspace/IsolatedAnalyzerReferenceSet.Desktop.cs
  src/Workspaces/Core/Portable/Workspace/IsolatedAnalyzerReferenceSet.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectFactory.cs
  src/Workspaces/CoreTest/Microsoft.CodeAnalysis.Workspaces.UnitTests.csproj
  src/Workspaces/CoreTest/Resources/Microsoft.CodeAnalysis.TestAnalyzerReference.dll.v1
  src/Workspaces/CoreTest/Resources/Microsoft.CodeAnalysis.TestAnalyzerReference.dll.v2
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
  src/Workspaces/CoreTestUtilities/Remote/TestSerializerService.cs
  src/Workspaces/Remote/Core/AbstractAssetProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteAnalyzerAssemblyLoaderService.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
  src/Workspaces/Remote/ServiceHub/Microsoft.CodeAnalysis.Remote.ServiceHub.csproj
  src/Workspaces/Remote/ServiceHub/Services/SourceGeneration/RemoteSourceGenerationService.cs
Labels: Area-IDE, untriaged

#73861 Ignore workspaces that do not have IEditAndContinueWorkspaceService
  src/LanguageServer/Protocol/Features/EditAndContinue/EditAndContinueDiagnosticSource_OpenDocument.cs
  src/LanguageServer/Protocol/Features/EditAndContinue/EditAndContinueDiagnosticSource_Workspace.cs
Labels: Area-Interactive, untriaged

#74986 Find first potential editorconfig when trying to synchronize
  src/VisualStudio/Core/Def/EditorConfigSettings/SettingsEditorControl.xaml.cs
Labels: Area-IDE, untriaged

#74994 Avoid BuildHost crash in Mono due to missing types
  src/Workspaces/Core/MSBuild.BuildHost/BuildHost.cs
Labels: Area-IDE, untriaged, VSCode

#74990 Remove toolset compiler workarounds
  Directory.Build.rsp
  eng/targets/Settings.props
Labels: Area-Infrastructure, untriaged

#74980 Re-enable double-to-integer conversion tests
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenExpression.vb
  src/Compilers/VisualBasic/Test/Emit/Microsoft.CodeAnalysis.VisualBasic.Emit.UnitTests.vbproj
  src/Compilers/VisualBasic/Test/Semantic/Semantics/Conversions.vb
Labels: Area-Compilers, untriaged

#74642 Fix typo in incremental-generators.cookbook.md
  docs/features/incremental-generators.cookbook.md
Labels: Area-Compilers, Community, untriaged

#74951 Fixup partial property API usage
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.Variables.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.cs
  src/Compilers/CSharp/Test/Emit2/Diagnostics/GetDiagnosticsTests.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs
Labels: Area-Compilers, untriaged, New Feature - Partial Properties

#74996 Remove debug-only assert method
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
Labels: Area-Compilers, untriaged

#75000 Fix exception case in compiler resolver
  src/Compilers/Core/CodeAnalysisTest/CompilerAnalyzerAssemblyResolverTests.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.Core.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs
Labels: Area-Compilers, untriaged

#75003 CodeQL suppressions
  src/Compilers/Core/Portable/CryptographicHashProvider.cs
  src/Compilers/Test/Core/Metadata/ILValidation.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
Labels: Area-Compilers, untriaged, VSCode

#74997 Fix IOperation debugging experience
  src/Compilers/Test/Core/Compilation/CompilationExtensions.cs
Labels: Area-Compilers, untriaged

#74999 Test attribute function pointer execution on net9
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs
  src/Compilers/CSharp/Test/Emit/Microsoft.CodeAnalysis.CSharp.Emit.UnitTests.csproj
Labels: Area-Compilers, untriaged

#75001 Remove the cancellation token from the calculation of InProgressState.LazyStaleCompilationWithGeneratedDocuments
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.CompilationTracker.CompilationTrackerState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.ICompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.RegularCompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.WithFrozenSourceGeneratedDocumentsCompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.cs
Labels: Area-IDE, untriaged, VSCode

#75007 Remove the cancellation token from the calculation of InProgressState…
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.CompilationTracker.CompilationTrackerState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.GeneratedFileReplacingCompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.ICompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.cs
Labels: Area-IDE, untriaged, VSCode

#75020 Fix typo in ProjectCodeModelFactory.ProcessNextDocumentBatchAsync
  src/VisualStudio/Core/Impl/CodeModel/ProjectCodeModelFactory.cs
Labels: Area-IDE, untriaged

#75027 Preserve trailing trivia when replacing method with property
  src/Features/CSharp/Portable/ReplaceMethodWithProperty/CSharpReplaceMethodWithPropertyService.cs
  src/Features/CSharpTest/ReplaceMethodWithProperty/ReplaceMethodWithPropertyTests.cs
Labels: Area-IDE, Community, untriaged, VSCode

#75016 Use numbered lists in `IOperation` documentation
  src/Compilers/Core/Portable/Generated/FlowAnalysis.Generated.cs
  src/Compilers/Core/Portable/Generated/Operations.Generated.cs
  src/Compilers/Core/Portable/Operations/OperationInterfaces.xml
Labels: Area-Compilers, Community, untriaged

#75030 Use ordinal ignore case for opening pdb source documents
  src/EditorFeatures/CSharpTest/PdbSourceDocument/AbstractPdbSourceDocumentTests.cs
  src/EditorFeatures/CSharpTest/PdbSourceDocument/PdbSourceDocumentTests.cs
  src/Features/Core/Portable/PdbSourceDocument/PdbSourceDocumentMetadataAsSourceFileProvider.cs
Labels: Area-IDE, untriaged, VSCode

#74899 Handle infinite cycles through params collection initializers
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/CollectionInitializerAddMethodBinder.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit2/Semantics/ParamsCollectionTests.cs
  src/Compilers/CSharp/Test/Emit3/RefReadonlyParameterTests.cs
  src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs
Labels: Area-Compilers, untriaged

#75011 Workaround for InvalidOperationException thrown from EmitSolutionUpdateResults.GetAllDiagnosticsAsync
  eng/targets/Settings.props
  src/Features/Core/Portable/EditAndContinue/EmitSolutionUpdateResults.cs
  src/Features/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/Features/TestUtilities/EditAndContinue/EditAndContinueWorkspaceTestBase.cs
Labels: Interactive-Debugging, Area-Interactive, Interactive-EnC, untriaged

#75033 Cherry-pick sourcelink casing fix
  src/EditorFeatures/CSharpTest/PdbSourceDocument/AbstractPdbSourceDocumentTests.cs
  src/EditorFeatures/CSharpTest/PdbSourceDocument/PdbSourceDocumentTests.cs
  src/Features/Core/Portable/PdbSourceDocument/PdbSourceDocumentMetadataAsSourceFileProvider.cs
Labels: Area-IDE, untriaged, VSCode

#75044 Expose sourcelink option to VSCode
  src/LanguageServer/Protocol/Handler/Configuration/DidChangeConfigurationNotificationHandler_OptionList.cs
  src/LanguageServer/ProtocolUnitTests/Configuration/DidChangeConfigurationNotificationHandlerTest.cs
Labels: Area-IDE, untriaged, VSCode

#74959 Field-backed properties: support partial properties with auto-implemented accessors and with initializers
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedBackingFieldSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit2/Semantics/PrimaryConstructorTests.cs
  src/Compilers/CSharp/Test/Emit3/FieldKeywordTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/PartialPropertiesTests.cs
Labels: Area-Compilers, untriaged, New Feature - Field Keyword

#75046 Fix issue where closing sourcelink document threw if not opened
  src/EditorFeatures/CSharpTest/PdbSourceDocument/PdbSourceDocumentTests.cs
  src/Features/Core/Portable/PdbSourceDocument/PdbSourceDocumentMetadataAsSourceFileProvider.cs
Labels: Area-IDE, untriaged, VSCode

#75037 Remove MS.CA.Test.Resources.Proprietary PackageReference
  eng/Directory.Packages.props
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/CommandLine/TouchedFileLoggingTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs
  src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenCallTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/ForEachTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs
  src/Compilers/CSharp/Test/WinRT/Metadata/WinMdDumpTest.cs
  src/Compilers/Core/CodeAnalysisTest/CryptoBlobParserTests.cs
  src/Compilers/Test/Core/Microsoft.CodeAnalysis.Test.Utilities.csproj
  src/Compilers/Test/Core/Mocks/Silverlight.cs
  src/Compilers/Test/Core/Mocks/StdOle.cs
  src/Compilers/Test/Core/Mocks/TestReferences.cs
  src/Compilers/Test/Core/Platform/Desktop/TestHelpers.cs
  src/Compilers/Test/Core/TestBase.cs
  src/Compilers/Test/Core/TestHelpers.cs
  src/Compilers/Test/Resources/Core/Microsoft.CodeAnalysis.Compiler.Test.Resources.csproj
  src/Compilers/Test/Resources/Core/NetFX/PortableProfile7/System.Runtime.dll
  src/Compilers/Test/Resources/Core/NetFX/PortableProfile7/mscorlib.dll
  src/Compilers/Test/Resources/Core/NetFX/WinRt/System.Runtime.WindowsRuntime.UI.Xaml.dll
  src/Compilers/Test/Resources/Core/NetFX/WinRt/System.Runtime.WindowsRuntime.dll
  src/Compilers/Test/Resources/Core/SymbolsTests/Metadata/BadDefaultParameterValue.dll
  src/Compilers/Test/Resources/Core/TestResources.cs
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTests.vb
  src/Compilers/VisualBasic/Test/Semantic/Semantics/ForeachTest.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Retargeting/NoPia.vb
  src/EditorFeatures/Test/SymbolFinder/DependentTypeFinderTests.cs
  src/Workspaces/CoreTest/FindReferencesTests.cs
Labels: Area-Compilers, untriaged, VSCode

#75047 Cherry pick changes to vscode release
  src/EditorFeatures/CSharpTest/PdbSourceDocument/PdbSourceDocumentTests.cs
  src/Features/Core/Portable/PdbSourceDocument/PdbSourceDocumentMetadataAsSourceFileProvider.cs
  src/LanguageServer/Protocol/Handler/Configuration/DidChangeConfigurationNotificationHandler_OptionList.cs
  src/LanguageServer/ProtocolUnitTests/Configuration/DidChangeConfigurationNotificationHandlerTest.cs
Labels: Area-IDE, untriaged, VSCode

#74966 Semantic snippets: handle case with inline statement snippets before member access expression
  src/Features/CSharp/Portable/Snippets/AbstractCSharpForLoopSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpDoWhileLoopSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpForEachLoopSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpIfSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpWhileLoopSnippetProvider.cs
  src/Features/CSharpTest/Snippets/AbstractCSharpConditionalBlockSnippetProviderTests.cs
  src/Features/CSharpTest/Snippets/CSharpDoSnippetProviderTests.cs
  src/Features/CSharpTest/Snippets/CSharpForEachSnippetProviderTests.cs
  src/Features/CSharpTest/Snippets/CSharpForSnippetProviderTests.cs
  src/Features/CSharpTest/Snippets/CSharpReversedForSnippetProviderTests.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractInlineStatementSnippetProvider.cs
Labels: Area-IDE, Community, untriaged, VSCode

#75053 Fix preview refresh on selection for enum flags checkboxes
  src/VisualStudio/Core/Impl/Options/OptionPreviewControl.xaml.cs
Labels: Area-IDE, untriaged

#75059 Configure release/vscode branch for nuget publishing
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#75057 Add a test observing lack of an issue.
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
Labels: Area-Compilers, untriaged, New Feature - RefStructInterfaces

#75038 docs: Correct SDK version in documentation to match global.json
  docs/contributing/Building, Debugging, and Testing on Unix.md
  docs/contributing/Building, Debugging, and Testing on Windows.md
Labels: Area-Infrastructure, Community, untriaged

#74881 Move build and test to an newer Ubuntu image with longer support
  azure-pipelines.yml
Labels: Area-Infrastructure, untriaged

#75042 Fix stack adjustment when emitting stackalloc
  src/Compilers/CSharp/Portable/CodeGen/EmitStackAllocInitializer.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenStackAllocInitializerTests.cs
Labels: Area-Compilers, untriaged

#75065 Lock translation of strings used to demonstrate identifier naming styles
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
Labels: Area-IDE, untriaged

#75086 Remove additional Gitter link
  README.md
Labels: Area-Infrastructure, untriaged

#75088 Localize 17.12 branch
  azure-pipelines-official.yml
Labels: Area-Infrastructure, untriaged

#75084 Log messages for Test Results
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/LanguageServerResources.resx
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Testing/TestRunner.TestRunHandler.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.cs.xlf
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.de.xlf
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.es.xlf
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.fr.xlf
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.it.xlf
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.ja.xlf
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.ko.xlf
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.pl.xlf
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.pt-BR.xlf
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.ru.xlf
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.tr.xlf
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.zh-Hans.xlf
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/xlf/LanguageServerResources.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged, VSCode

#75081 Remove buggy IsPublic method from TypeAttributesExtensions
  src/Compilers/Core/Portable/MetadataReader/TypeAttributesExtensions.cs
Labels: Area-Compilers, Community, untriaged

#75060 BindAttributeCore - use proper binder to avoid an attribute binding cycle
  src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
Labels: Area-Compilers, untriaged

#75092 Include initial filter node when searching for nodes to order modifiers
  src/Analyzers/CSharp/Tests/OrderModifiers/OrderModifiersTests.cs
  src/Analyzers/Core/Analyzers/OrderModifiers/AbstractOrderModifiersDiagnosticAnalyzer.cs
Labels: Area-IDE, untriaged, VSCode

#75056 Switch to new VMR control set
  eng/Directory.Packages.props
  eng/SourceBuild.props
  eng/Versions.props
  eng/build.ps1
  eng/build.sh
  eng/generate-vssdk-versions.csx
  eng/targets/DiaSymReaderNative.targets
  eng/targets/Imports.BeforeArcade.targets
  eng/targets/Imports.targets
  eng/targets/Settings.props
  eng/targets/TargetFrameworks.props
  src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/Interactive/csi/csi.csproj
  src/Interactive/vbi/vbi.vbproj
  src/NuGet/Microsoft.Net.Compilers.Toolset/DesktopCompilerArtifacts.targets
  src/NuGet/VS.Tools.Roslyn.Package/VS.Tools.Roslyn.Package.csproj
  src/Setup/DevDivVsix/CompilersPackage/CompilersPackage.targets
  src/Setup/Installer/Installer.Package.csproj
  src/Workspaces/Core/MSBuild.BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj
  src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
Labels: Area-Infrastructure, Community, untriaged

#75067 Adjust an assert in EmitArgument
  src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers, untriaged, New Language Feature - Ref Fields

#75050 Fix typo in RequestTelemetryLogger.UpdateTelemetryData
  src/LanguageServer/Protocol/Handler/RequestTelemetryLogger.cs
Labels: Area-Infrastructure, untriaged, VSCode

#75108 Use the latest version of ILasm and enable a test not supported by the old version
  eng/Directory.Packages.props
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
Labels: Area-Compilers, untriaged, New Feature - RefStructInterfaces

#75070 Keep try syntax in async exception rewriting
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncExceptionHandlerRewriter.cs
  src/Compilers/CSharp/Portable/Syntax/LambdaUtilities.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs
Labels: Area-Compilers, New Feature - Async Streams, untriaged

#75079 Test and document Span breaking changes
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 10.md
  src/Compilers/CSharp/Test/Emit3/FirstClassSpanTests.cs
  src/Compilers/Test/Utilities/CSharp/TestSources.cs
Labels: Area-Compilers, untriaged, New Feature - First-class Span Types

#75096 Remove some obsolete build properties
  azure-pipelines-official.yml
  azure-pipelines-pr-validation.yml
  azure-pipelines.yml
Labels: Area-Infrastructure, Community, untriaged

#75102 Allow Razor to get diagnostics for cohosting
  src/LanguageServer/Protocol/Extensions/ProtocolConversions.Diagnostics.cs
  src/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/LanguageServer/Protocol/Handler/Diagnostics/DocumentPullDiagnosticHandler.cs
  src/LanguageServer/Protocol/Handler/Diagnostics/Public/PublicDocumentPullDiagnosticsHandler.cs
  src/LanguageServer/Protocol/Handler/Diagnostics/Public/PublicWorkspacePullDiagnosticsHandler.cs
  src/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs
  src/Tools/ExternalAccess/Razor/Cohost/Handlers/Diagnostics.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
Labels: Area-IDE, untriaged, VSCode

#75138 Do not attempt to report EnC diagnostics for non-host workspaces
  src/LanguageServer/Protocol/Features/EditAndContinue/EditAndContinueDiagnosticSource_OpenDocument.cs
  src/LanguageServer/Protocol/Features/EditAndContinue/EditAndContinueDiagnosticSource_Workspace.cs
Labels: Area-Interactive, untriaged, VSCode

#75052 Fix SyntaxFactory.XmlSeeAlsoElement href overloads
  src/Compilers/CSharp/Portable/Syntax/SyntaxFactory.cs
  src/Compilers/CSharp/Test/Syntax/LexicalAndXml/XmlDocCommentTests.cs
  src/Compilers/VisualBasic/Portable/Syntax/SyntaxFactory.vb
  src/Compilers/VisualBasic/Test/Syntax/Parser/XmlDocComments.vb
Labels: Area-Compilers, Community, untriaged

#75100 Exclude identifiers in misplaced attributes from identifier map
  src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs
Labels: Area-Compilers, untriaged

#75066 Adjust IsMetadataVirtual assertion in MethodToClassRewriter
  src/Compilers/CSharp/Portable/Emitter/Model/MethodSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Lowering/IteratorRewriter/IteratorFinallyMethodSymbol.cs
  src/Compilers/CSharp/Portable/Lowering/MethodToClassRewriter.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.ConstructorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.EqualsMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.GetHashCodeMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.PropertyAccessorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.ToStringMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/ErrorMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/FunctionPointers/FunctionPointerMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/MethodSymbolExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs
  src/Compilers/CSharp/Portable/Symbols/ReducedExtensionMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/SignatureOnlyMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceDestructorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedDelegateSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedEntryPointSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedGlobalMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedImplementationMethod.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedInstanceConstructor.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedInteractiveInitializerMethod.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedIntrinsicOperatorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedSealedPropertyAccessor.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedStaticConstructor.cs
  src/Compilers/CSharp/Portable/Symbols/Wrapped/WrappedMethodSymbol.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs
  src/Compilers/Test/Utilities/CSharp/FunctionPointerUtilities.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EEMethodSymbol.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/PlaceholderMethodSymbol.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/SynthesizedContextMethodSymbol.cs
Labels: Area-Compilers, untriaged

#75151 Properly iterate through an inline array used as a spread element.
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged, New Feature - Collection Expressions

#75161 Check for source only properties before tool restore
  eng/build.sh
Labels: Area-Infrastructure, Community, untriaged

#75164 Remove unnecessary NETCOREAPP3_1
  src/Compilers/Core/Portable/InternalUtilities/NullableAttributes.cs
Labels: Area-Compilers, untriaged

#75104 Add `Enumerable.Reverse(this T[])` polyfill
  src/Compilers/Core/Portable/InternalUtilities/EnumerableExtensions.cs
  src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs
Labels: Area-Compilers, untriaged, VSCode, New Feature - First-class Span Types

#75163 Fix the OOM error in scripting tests
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/ForEachEnumeratorInfo.cs
  src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversion.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundDagEvaluation.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNode.cs
  src/Compilers/CSharp/Portable/BoundTree/Formatting.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitArrayInitializer.cs
  src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.DebugVerifier.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.SnapshotManager.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.Analysis.Tree.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/MethodToStateMachineRewriter.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceDelegateMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedGlobalMethodSymbol.cs
  src/Compilers/Core/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.csproj
  src/Compilers/Core/Portable/CodeGen/PrivateImplementationDetails.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs
  src/Compilers/Core/Portable/Emit/CommonPEModuleBuilder.cs
  src/Compilers/Core/Portable/InternalUtilities/Debug.cs
  src/Compilers/Core/Portable/InternalUtilities/StringTable.cs
  src/Compilers/Core/Portable/Operations/OperationMapBuilder.cs
  src/Compilers/Core/Portable/WellKnownTypes.cs
  src/ExpressionEvaluator/Core/Source/ResultProvider/Formatter.TypeNames.cs
  src/ExpressionEvaluator/Core/Source/ResultProvider/Portable/Microsoft.CodeAnalysis.ResultProvider.csproj
  src/ExpressionEvaluator/Core/Test/ResultProvider/Debugger/Engine/DkmClrType.cs
  src/ExpressionEvaluator/Core/Test/ResultProvider/Microsoft.CodeAnalysis.ResultProvider.Utilities.csproj
  src/Tools/Replay/Replay.csproj
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Context/FormattingContext.IndentationData.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/AbstractDocumentationCommentService.cs
Labels: Area-Compilers, untriaged, VSCode

#75171 Test allocations
  src/Compilers/CSharp/Test/Semantic/Semantics/NativeIntegerTests.cs
  src/Compilers/Test/Core/Platform/Desktop/Extensions.cs
  src/Compilers/Test/Core/TargetFrameworkUtil.cs
Labels: Area-Compilers, untriaged

#75175 Adding back code to handle LinePosition values correctly
  src/VisualStudio/Core/Def/LanguageServer/Handler/CustomMessage/CustomMessageHandler.cs
  src/VisualStudio/Core/Def/LanguageServer/Handler/CustomMessage/LinePositionReadConverter.cs
  src/VisualStudio/Core/Def/LanguageServer/Handler/CustomMessage/LinePositionWriteConverter.cs
Labels: Area-IDE, Community, untriaged

#74903 Support for per-file content exclusion in Rename Suggestions
  src/EditorFeatures/CSharp/InlineRename/CSharpEditorInlineRenameService.cs
  src/EditorFeatures/CSharpTest/Rename/CSharpInlineRenameServiceTests.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameViewModel.cs
  src/EditorFeatures/Core.Wpf/Lightup/ISmartRenameSessionWrapper.cs
  src/EditorFeatures/Core.Wpf/Lightup/LightupHelpers.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptEditorInlineRenameService.cs
  src/EditorFeatures/Core/InlineRename/AbstractEditorInlineRenameService.cs
  src/EditorFeatures/Core/InlineRename/IEditorInlineRenameService.cs
  src/VisualStudio/ExternalAccess/FSharp/Internal/Editor/FSharpEditorInlineRenameService.cs
  src/VisualStudio/Xaml/Impl/Features/InlineRename/XamlEditorInlineRenameService.cs
Labels: Area-IDE, Community, untriaged

#75173 Move Ref assemblies forward
  eng/Directory.Packages.props
Labels: Area-Infrastructure, untriaged

#75176 Remove ResultId from RelatedDocumentsHandler
  src/LanguageServer/Protocol/Handler/RelatedDocuments/RelatedDocumentsHandler.cs
  src/LanguageServer/Protocol/Protocol/Internal/VSInternalRelatedDocumentParams.cs
  src/LanguageServer/ProtocolUnitTests/RelatedDocuments/RelatedDocumentsTests.cs
Labels: Area-IDE, untriaged, VSCode

#74953 Add optional value to dart-lab yml
  azure-pipelines-integration-dartlab.yml
Labels: Area-Infrastructure, untriaged

#75177 More test allocation improvements
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs
  src/ExpressionEvaluator/Core/Test/ResultProvider/Debugger/Engine/DkmClrAppDomain.cs
  src/ExpressionEvaluator/Core/Test/ResultProvider/Debugger/Engine/DkmClrType.cs
Labels: Area-Interactive, untriaged

#75149 Yield before performing Go To Definition work
  src/EditorFeatures/Core/GoToDefinition/GoToDefinitionCommandHandler.cs
Labels: Area-IDE, untriaged

#75134 Fix the SmartRename button regressions
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameUserInputComboBox.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameViewModel.cs
Labels: Area-IDE, Community, untriaged, Needs UX Triage

#74993 Better Collection Expression Conversion From Expression
  docs/Language Feature Status.md
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 9.md
  docs/contributing/Compiler Test Plan.md
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/ParamsCollectionTests.cs
Labels: Area-Compilers, untriaged, New Feature - Collection Expressions, New Feature - ParamsCollections

#75188 Add more better conversions tests
  src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged

#75137 Include workspace kind in error message for easier diagnostics
  src/Workspaces/Core/Portable/Workspace/Host/HostLanguageServices.cs
  src/Workspaces/Core/Portable/Workspace/Host/HostWorkspaceServices.cs
  src/Workspaces/Core/Portable/WorkspacesResources.resx
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.cs.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.de.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.es.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.fr.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.it.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ja.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ko.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.pl.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.pt-BR.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ru.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.tr.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.zh-Hans.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.zh-Hant.xlf
Labels: Area-IDE, untriaged, VSCode

#75140 Test EnC document diagnostics in non-host workspace
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
  src/LanguageServer/ProtocolUnitTests/Workspaces/LspWorkspaceManagerTests.cs
  src/VisualStudio/CSharp/Test/DocumentOutline/DocumentOutlineTestsBase.cs
Labels: Area-Interactive, untriaged, VSCode

#75116 Field-backed properties: definite assignment
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNode.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PropertyAccess.cs
  src/Compilers/CSharp/Portable/Lowering/MethodToClassRewriter.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Test/Emit3/FieldKeywordTests.cs
Labels: Area-Compilers, untriaged

#75094 Fix null dereference in GetAssemblyReferenceAlias
  src/Compilers/CSharp/Test/Emit2/PDB/PDBUsingTests.cs
  src/Compilers/Core/Portable/NativePdbWriter/PdbWriter.cs
Labels: Area-Compilers, untriaged

#75075 Fix parser regressions of conditional expressions
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/AwaitParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ExpressionParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/NameParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/RecordParsing.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/StatementParsingTests.cs
Labels: Area-Compilers, Community, untriaged

#75156 Update Language Feature Status.md
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation, Community, untriaged

#75207 docs: fix C# 13 proposal link
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation, Community, untriaged

#75219 Field-backed properties: interface properties
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Test/Emit3/FieldKeywordTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs
Labels: Area-Compilers, untriaged

#75215 Allow <code> in DocComments to render as a block in Hover response
  src/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/LanguageServer/ProtocolUnitTests/Hover/HoverTests.cs
Labels: Area-Infrastructure, untriaged, VSCode

#75139 Use MSBuild globs to determine which file changes are relevant
  eng/Directory.Packages.props
  eng/Versions.props
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Microsoft.CodeAnalysis.LanguageServer.csproj
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs
  src/Workspaces/Core/MSBuild.BuildHost/Rpc/Contracts/FileGlobs.cs
  src/Workspaces/Core/MSBuild.BuildHost/Rpc/Contracts/ProjectFileInfo.cs
Labels: Area-IDE, untriaged, VSCode

#75235 Do not simplify type name to a type with the EditorBrowsable attribute on it.
  src/Features/CSharpTest/SimplifyTypeNames/SimplifyTypeNamesTests.cs
  src/Workspaces/CSharp/Portable/Simplification/Simplifiers/ExpressionSimplifier.cs
  src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Simplification/Simplifiers/AbstractSimplifier.cs
Labels: Area-IDE, untriaged, VSCode

#75236 Fix issue removing unnecessary cast in user defined interpolation handlers
  src/Analyzers/CSharp/Tests/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Simplification/Simplifiers/CastSimplifier.cs
Labels: Area-IDE, untriaged, VSCode

#75242 Fix crash in 'use collection initializer'
  src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CSharpCompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ForEachStatementSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SemanticModelExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/SpeculationAnalyzer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/AbstractSpeculationAnalyzer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Utilities/SpeculationAnalyzer.vb
Labels: Area-IDE, untriaged, VSCode

#75172 Updates content exclusion for on-the-fly-docs
  src/EditorFeatures/Core.Wpf/QuickInfo/OnTheFlyDocsView.xaml.cs
  src/EditorFeatures/Core.Wpf/QuickInfo/OnTheFlyDocsViewFactory.cs
  src/EditorFeatures/Core/EditorFeaturesResources.resx
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.cs.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.de.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.es.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.fr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.it.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ja.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ko.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pl.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pt-BR.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ru.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.tr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hans.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hant.xlf
  src/EditorFeatures/ExternalAccess/Copilot/Analyzer/IExternalCSharpCopilotCodeAnalysisService.cs
  src/EditorFeatures/ExternalAccess/Copilot/Internal/Analyzer/AbstractCopilotCodeAnalysisService.cs
  src/EditorFeatures/ExternalAccess/Copilot/Internal/Analyzer/CSharp/CSharpCopilotCodeAnalysisService.ReflectionWrapper.cs
  src/EditorFeatures/ExternalAccess/Copilot/Internal/Analyzer/CSharp/CSharpCopilotCodeAnalysisService.cs
  src/EditorFeatures/ExternalAccess/Copilot/InternalAPI.Unshipped.txt
  src/EditorFeatures/Test2/CodeFixes/CodeFixServiceTests.vb
  src/Features/CSharp/Portable/QuickInfo/CSharpSemanticQuickInfoProvider.cs
  src/Features/Core/Portable/Copilot/ICopilotCodeAnalysisService.cs
  src/Features/Core/Portable/QuickInfo/OnTheFlyDocsElement.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-IDE, untriaged, VSCode

#75261 Disable use-expression-body for lambdas with PP directives in them
  src/Analyzers/CSharp/Analyzers/UseExpressionBodyForLambda/UseExpressionBodyForLambdaHelpers.cs
  src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/UseExpressionBodyForLambda/UseExpressionBodyForLambdaCodeRefactoringProvider.cs
  src/Features/CSharpTest/UseExpressionBodyForLambda/UseExpressionBodyForLambdasRefactoringTests.cs
Labels: Area-IDE, untriaged, VSCode

#75068 Upgrade xUnit
  .editorconfig
  .vscode/tasks.json
  eng/Directory.Packages.props
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplay.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/BindingAsyncTasklikeTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
  src/Compilers/Server/VBCSCompilerTests/NamedPipeClientConnectionHostTests.cs
  src/Compilers/Test/Core/Assert/AssertEx.cs
  src/Compilers/VisualBasic/Test/Emit/Attributes/AssemblyAttributes.vb
  src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests.vb
  src/Compilers/VisualBasic/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.vb
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTuples.vb
  src/Compilers/VisualBasic/Test/Emit/Emit/CompilationEmitTests.vb
  src/Compilers/VisualBasic/Test/Emit/Emit/EditAndContinue/EditAndContinueStateMachineTests.vb
  src/Compilers/VisualBasic/Test/Semantic/Binding/BindingCollectionInitializerTests.vb
  src/Compilers/VisualBasic/Test/Semantic/Binding/LookupTests.vb
  src/Compilers/VisualBasic/Test/Semantic/Compilation/CompilationAPITests.vb
  src/Compilers/VisualBasic/Test/Semantic/Compilation/SemanticModelGetDeclaredSymbolAPITests.vb
  src/Compilers/VisualBasic/Test/Semantic/FlowAnalysis/FlowTestBase.vb
  src/Compilers/VisualBasic/Test/Semantic/Semantics/ForeachTest.vb
  src/Compilers/VisualBasic/Test/Semantic/Semantics/GotoTests.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/AnonymousTypes/AnonymousTypesSemanticsTests.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/BindingsTests.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/SourceSymbolTests.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/TypedConstantTests.vb
  src/Compilers/VisualBasic/Test/Syntax/Parser/XmlDocComments.vb
  src/EditorFeatures/CSharpTest/Debugging/ProximityExpressionsGetterTests.cs
  src/EditorFeatures/CSharpTest/EditorConfigSettings/Updater/SettingsUpdaterTests.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/AbstractCodeActionOrUserDiagnosticTest_TestAddDocument.cs
  src/Features/Test/FindUsages/DefinitionItemFactoryTests.cs
  src/LanguageServer/ProtocolUnitTests/CodeLens/CSharpCodeLensTests.cs
  src/LanguageServer/ProtocolUnitTests/Diagnostics/AdditionalFileDiagnosticsTests.cs
  src/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
  src/LanguageServer/ProtocolUnitTests/Diagnostics/WorkspaceProjectDiagnosticsTests.cs
  src/LanguageServer/ProtocolUnitTests/Metadata/LspMetadataAsSourceWorkspaceTests.cs
  src/LanguageServer/ProtocolUnitTests/SpellCheck/SpellCheckTests.cs
  src/LanguageServer/ProtocolUnitTests/Symbols/WorkspaceSymbolsTests.cs
  src/LanguageServer/ProtocolUnitTests/VSTypeScriptHandlerTests.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/InputInProcess.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
  src/Workspaces/CoreTest/UtilityTest/SpecializedTasksTests.cs
Labels: Area-Compilers, untriaged, VSCode

#75264 Support converting to collection expression when overloads would not change
  src/Analyzers/CSharp/Analyzers/UseCollectionInitializer/CSharpUseCollectionInitializerDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests_CollectionExpression.cs
Labels: Area-IDE, untriaged, VSCode

#75265 Add test demonstrating a scenario now works
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
Labels: Area-IDE, untriaged

#75246 Short term field keyword nullable analysis
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Generated/ErrorFacts.Generated.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit3/FieldKeywordTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
Labels: Area-Compilers, untriaged

#73869 Prevent IDE0290 (convert to primary constructor) in ref struct
  src/Analyzers/CSharp/Analyzers/UsePrimaryConstructor/CSharpUsePrimaryConstructorDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/UsePrimaryConstructor/UsePrimaryConstructorTests.cs
Labels: Area-IDE, Community, untriaged, VSCode

#75259 Preserve comment when converting to collection expression
  src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpUseCollectionExpressionForBuilderCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForBuilderTests.cs
Labels: Area-IDE, untriaged, VSCode

#75269 Add telemetry to track the rename option used.
  src/EditorFeatures/Core.Wpf/InlineRename/UI/InlineRenameAdornmentManager.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-IDE, untriaged, VSCode

#75266 Fix completion lists in primary constructor parameter lists
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/IntKeywordRecommender.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CSharpWorkspaceExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/CSharpSyntaxContextService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxNodeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs
Labels: Area-IDE, untriaged, VSCode

#75263 update configs for snap
  eng/Versions.props
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#75250 Do not load CodeStyle analyzers added by the SDK
  src/VisualStudio/Core/Test/ProjectSystemShim/VisualStudioProjectTests/AnalyzerReferenceTests.vb
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.cs
Labels: Area-IDE, untriaged, VSCode

#74090 Stabilize lsp workspace diagnostic test
  src/LanguageServer/Protocol/Handler/Diagnostics/AbstractWorkspacePullDiagnosticsHandler.cs
  src/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
Labels: Area-Analyzers, untriaged, VSCode

#75279 Revert "Updates content exclusion for on-the-fly-docs"
  src/EditorFeatures/Core.Wpf/QuickInfo/OnTheFlyDocsView.xaml.cs
  src/EditorFeatures/Core.Wpf/QuickInfo/OnTheFlyDocsViewFactory.cs
  src/EditorFeatures/Core/EditorFeaturesResources.resx
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.cs.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.de.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.es.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.fr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.it.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ja.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ko.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pl.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pt-BR.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ru.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.tr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hans.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hant.xlf
  src/EditorFeatures/ExternalAccess/Copilot/Analyzer/IExternalCSharpCopilotCodeAnalysisService.cs
  src/EditorFeatures/ExternalAccess/Copilot/Internal/Analyzer/AbstractCopilotCodeAnalysisService.cs
  src/EditorFeatures/ExternalAccess/Copilot/Internal/Analyzer/CSharp/CSharpCopilotCodeAnalysisService.ReflectionWrapper.cs
  src/EditorFeatures/ExternalAccess/Copilot/Internal/Analyzer/CSharp/CSharpCopilotCodeAnalysisService.cs
  src/EditorFeatures/ExternalAccess/Copilot/InternalAPI.Unshipped.txt
  src/EditorFeatures/Test2/CodeFixes/CodeFixServiceTests.vb
  src/Features/CSharp/Portable/QuickInfo/CSharpSemanticQuickInfoProvider.cs
  src/Features/Core/Portable/Copilot/ICopilotCodeAnalysisService.cs
  src/Features/Core/Portable/QuickInfo/OnTheFlyDocsElement.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-IDE, untriaged, VSCode

#75256 Fix crash when converting properties to methods
  src/Features/CSharpTest/ReplaceMethodWithProperty/ReplaceMethodWithPropertyTests.cs
  src/Features/CSharpTest/ReplacePropertyWithMethods/ReplacePropertyWithMethodsTests.cs
  src/Features/Core/Portable/ReplacePropertyWithMethods/ReplacePropertyWithMethodsCodeRefactoringProvider.cs
Labels: Area-IDE, untriaged, VSCode

#75254 Fix crash in encapsulate field with primary constructors
  src/EditorFeatures/Core/EncapsulateField/AbstractEncapsulateFieldCommandHandler.cs
  src/Features/CSharp/Portable/EncapsulateField/CSharpEncapsulateFieldService.cs
  src/Features/CSharpTest/EncapsulateField/EncapsulateFieldTests.cs
  src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs
  src/Features/Core/Portable/EncapsulateField/EncapsulateFieldRefactoringProvider.cs
  src/Features/Core/Portable/EncapsulateField/IEncapsulateFieldService.cs
  src/Features/VisualBasic/Portable/EncapsulateField/VisualBasicEncapsulateFieldService.vb
  src/Workspaces/Remote/ServiceHub/Services/EncapsulateField/RemoteEncapsulateFieldService.cs
Labels: Area-IDE, untriaged, VSCode

#75281 Enable Policheck
  azure-pipelines-official.yml
Labels: Area-Infrastructure, untriaged

#75284 Revert "Updates content exclusion for on-the-fly-docs (#75172)" (#75279)
  src/EditorFeatures/Core.Wpf/QuickInfo/OnTheFlyDocsView.xaml.cs
  src/EditorFeatures/Core.Wpf/QuickInfo/OnTheFlyDocsViewFactory.cs
  src/EditorFeatures/Core/EditorFeaturesResources.resx
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.cs.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.de.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.es.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.fr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.it.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ja.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ko.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pl.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pt-BR.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ru.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.tr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hans.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hant.xlf
  src/EditorFeatures/ExternalAccess/Copilot/Analyzer/IExternalCSharpCopilotCodeAnalysisService.cs
  src/EditorFeatures/ExternalAccess/Copilot/Internal/Analyzer/AbstractCopilotCodeAnalysisService.cs
  src/EditorFeatures/ExternalAccess/Copilot/Internal/Analyzer/CSharp/CSharpCopilotCodeAnalysisService.ReflectionWrapper.cs
  src/EditorFeatures/ExternalAccess/Copilot/Internal/Analyzer/CSharp/CSharpCopilotCodeAnalysisService.cs
  src/EditorFeatures/ExternalAccess/Copilot/InternalAPI.Unshipped.txt
  src/EditorFeatures/Test2/CodeFixes/CodeFixServiceTests.vb
  src/Features/CSharp/Portable/QuickInfo/CSharpSemanticQuickInfoProvider.cs
  src/Features/Core/Portable/Copilot/ICopilotCodeAnalysisService.cs
  src/Features/Core/Portable/QuickInfo/OnTheFlyDocsElement.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-IDE, untriaged, VSCode

#75283 Field-backed properties: additional tests
  src/Compilers/CSharp/Test/Emit3/FieldKeywordTests.cs
  src/Compilers/CSharp/Test/Syntax/Syntax/FieldAndValueKeywordTests.cs
Labels: Area-Compilers, untriaged

#75287 Use common helper method
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.ExpressionResult.cs
  src/Features/CSharp/Portable/ExtractMethod/Extensions.cs
Labels: Area-IDE, Community, untriaged, VSCode

#75290 Update LanguageServer references
  azure-pipelines-integration.yml
  azure-pipelines.yml
  src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/README.md
Labels: Area-Infrastructure, Community, untriaged

#74687 Fix `NETCOREAPP3_0_OR_GREATER` in `SegmentedArrayHelper`
  src/Dependencies/Collections/Internal/SegmentedArrayHelper.cs
Labels: Area-IDE, Community, untriaged

#75258 Add support for inlining declarations in top level code
  src/Analyzers/CSharp/Analyzers/InlineDeclaration/CSharpInlineDeclarationDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/InlineDeclaration/CSharpInlineDeclarationTests.cs
Labels: Area-IDE, untriaged, VSCode

#75294 don't mess with user caret in smart rename
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameUserInputComboBox.xaml.cs
Labels: Area-IDE, Community, untriaged

#75213 Collapse the rename UI when commit starts
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyoutViewModel.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Dashboard/RenameDashboard.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Dashboard/RenameDashboard.xaml.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Dashboard/RenameDashboardViewModel.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/InlineRenameAdornmentManager.cs
  src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs
  src/EditorFeatures/Test2/Rename/RenameViewModelTests.vb
Labels: Area-IDE, untriaged, Needs UX Triage

#75099 Disallow declaration of indexers in absence of proper DefaultMemberAttribute.
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 9.md
  src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/IndexerTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/InAttributeModifierTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IArgument.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InitOnlyMemberTests.cs
Labels: Area-Compilers, untriaged

#75267 Detect more fluent cases for converting collection expressions
  src/Analyzers/CSharp/Analyzers/CSharpAnalyzers.projitems
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForArrayDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForBuilderDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForFluentDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForStackAllocDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CollectionExpressionMatch.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/UseCollectionExpressionHelpers.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionInitializer/CSharpUseCollectionInitializerAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpCollectionExpressionRewriter.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpUseCollectionExpressionForArrayCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpUseCollectionExpressionForBuilderCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpUseCollectionExpressionForCreateCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpUseCollectionExpressionForFluentCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpUseCollectionExpressionForStackAllocCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionInitializer/CSharpUseCollectionInitializerCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionInitializer/CSharpUseCollectionInitializerCodeFixProvider_CollectionExpression.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionInitializer/CSharpUseCollectionInitializerCodeFixProvider_CollectionInitializer.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForFluentTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests_CollectionExpression.cs
  src/Analyzers/Core/Analyzers/Analyzers.projitems
  src/Analyzers/Core/Analyzers/UseCollectionExpression/CollectionExpressionMatch.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/AbstractObjectCreationExpressionAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/AbstractUseCollectionInitializerAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/AbstractUseCollectionInitializerDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/UpdateExpressionState.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/UseCollectionInitializerHelpers.cs
  src/Analyzers/Core/Analyzers/UseObjectInitializer/UseNamedMemberInitializerAnalyzer.cs
  src/Analyzers/Core/CodeFixes/UseCollectionInitializer/AbstractUseCollectionInitializerCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseObjectInitializer/AbstractUseObjectInitializerCodeFixProvider.cs
  src/Analyzers/VisualBasic/Analyzers/UseCollectionInitializer/VisualBasicCollectionInitializerAnalyzer.vb
  src/Analyzers/VisualBasic/CodeFixes/UseCollectionInitializer/VisualBasicUseCollectionInitializerCodeFixProvider.vb
Labels: Area-IDE, untriaged, VSCode

#75282 Bump razor for serialization changes
  eng/Directory.Packages.props
Labels: Area-Infrastructure, untriaged

#75306 Clarify the bug template to request a code snippet
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: Area-Compilers, untriaged

#75307 Fix TSA tooling
  eng/TSAConfig.gdntsa
Labels: Area-Infrastructure, untriaged

#75297 Switch caching file comparer to a threadstatic storage to prevent locks
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CachingFilePathComparer.cs
Labels: Area-IDE, untriaged, VSCode

#75302 Fix the path to the proposal
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md
Labels: Area-Compilers, Community, untriaged
