Repository dotnet/roslyn, pull requests merged in 2024-06, with the labels that each got.

#73817 Bump Razor to 9.0.0-preview.24281.3
  eng/Directory.Packages.props
Labels: Area-Infrastructure, untriaged

#73631 Always use a by-value temp to capture a reference type receiver
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs
  src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenCallTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RawInterpolationTests_Handler.cs
Labels: Area-Compilers, untriaged

#73812 Optimize helper we use to determine the relevant node of a particular kind the user is on.
  src/Compilers/Core/Portable/Collections/TemporaryArrayExtensions.cs
  src/Features/CSharp/Portable/CodeRefactorings/UseExplicitOrImplicitType/AbstractUseTypeCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/CodeRefactorings/UseExplicitOrImplicitType/UseExplicitTypeCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/CodeRefactorings/UseExplicitOrImplicitType/UseImplicitTypeCodeRefactoringProvider.cs
  src/Features/Core/Portable/CodeRefactoringHelpers.cs
  src/Features/Core/Portable/CodeRefactorings/AbstractRefactoringHelpersService.cs
  src/Features/Core/Portable/CodeRefactorings/CodeRefactoringContextExtensions.cs
  src/Features/Core/Portable/CodeRefactorings/IRefactoringHelpersService.cs
  src/Features/Core/Portable/ConvertTupleToStruct/AbstractConvertTupleToStructCodeRefactoringProvider.cs
Labels: Area-IDE, untriaged

#73831 Upgrade MicrosoftCodeAnalysisTestingVersion to 1.1.2-beta1.24121.1
  eng/Versions.props
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/CSharpCodeFixVerifier`2+Test.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/CSharpCodeRefactoringVerifier`1+Test.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/VisualBasicCodeRefactoringVerifier`1+Test.cs
  src/Features/CSharpTest/ConvertToRecord/ConvertToRecordCodeRefactoringTests.cs
  src/Features/CSharpTest/ExtractClass/ExtractClassTests.cs
  src/Features/CSharpTest/GenerateFromMembers/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersTests.cs
  src/Features/CSharpTest/MoveStaticMembers/CSharpMoveStaticMembersTests.cs
  src/Features/VisualBasicTest/MoveStaticMembers/VisualBasicMoveStaticMembersTests.vb
Labels: Area-IDE, untriaged

#73819 Build interval tree from sorted nodes
  src/EditorFeatures/Core/Shared/Tagging/Utilities/TagSpanIntervalTree.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs
  src/EditorFeatures/Test/Tagging/TagSpanIntervalTreeTests.cs
  src/Workspaces/Core/Portable/Shared/Collections/IntervalTree.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/IntervalTree`1.cs
Labels: Area-IDE, untriaged

#73833 Workaround issue with invalid diagnostics reported via TS workspace diagnostics
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractWorkspacePullDiagnosticsHandler.cs
Labels: Area-IDE, untriaged

#73834 Also include cshtml in file paths to ignore
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractWorkspacePullDiagnosticsHandler.cs
Labels: Area-IDE, untriaged

#73793 Reduce Linq usage in SymbolDisplayVisitor.CreateAliasMap
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor_Minimal.cs
Labels: Area-Compilers, untriaged

#73846 Interval tree refactorings.
  src/EditorFeatures/Core/Shared/Tagging/Utilities/TagSpanIntervalTree.cs
  src/EditorFeatures/Test/Collections/IntervalTreeTests.cs
  src/Features/CSharp/Portable/ConvertToRawString/ConvertInterpolatedStringToRawStringCodeRefactoringProvider.cs
  src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineViewModel.DocumentOutlineViewState.cs
  src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineViewModel.cs
  src/VisualStudio/Core/Def/InheritanceMargin/InheritanceGlyphManager.cs
  src/Workspaces/Core/Portable/Classification/ClassifierHelper.cs
  src/Workspaces/Core/Portable/CodeCleanup/AbstractCodeCleanerService.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/TextChangeMerger.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/IIntervalTree`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/IntervalTreeAlgorithms`2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/IntervalTree`1.Node.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/IntervalTree`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/SimpleIntervalTree.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/SimpleIntervalTree`2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/TextSpanIntervalIntrospector.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Context/FormattingContext.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/ContextIntervalTree.cs
Labels: Area-IDE, untriaged

#73818 Fix build host when only the .net 6 SDK is installed
  src/Tools/PrepareTests/TestDiscovery.cs
  src/Tools/TestDiscoveryWorker/Program.cs
  src/Workspaces/Core/MSBuild.BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj
Labels: Area-IDE, untriaged

#73839 Reduce project forks on solution open
  src/Workspaces/Core/Portable/CodeFixesAndRefactorings/DocumentBasedFixAllProviderHelpers.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
Labels: Area-IDE, untriaged

#73845 Update version for system.data.sqlclient to 4.8.6
  eng/Versions.props
  src/Tools/Source/RunTests/RunTests.csproj
Labels: Area-Infrastructure, untriaged

#73744 Code style options cleanup
  src/Analyzers/Core/Analyzers/AbstractBuiltInCodeStyleDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/NamingStyle/NamingStyleDiagnosticAnalyzerBase.cs
  src/EditorFeatures/Core/EditorConfigSettings/Data/CodeStyleSetting.cs
  src/EditorFeatures/Core/EditorConfigSettings/Data/CodeStyleSetting`1.cs
  src/EditorFeatures/Core/EditorConfigSettings/Updater/SettingsUpdateHelper.cs
  src/EditorFeatures/Test2/Diagnostics/NamingStyles/NamingStyleTests.vb
  src/Features/Core/Portable/CodeFixes/Configuration/ConfigurationUpdater.cs
  src/Features/Core/Portable/CodeFixes/Configuration/ConfigureCodeStyle/ConfigureCodeStyleOptionCodeFixProvider.cs
  src/VisualStudio/Core/Def/Options/VisualStudioSettingsOptionPersister.cs
  src/VisualStudio/Core/Impl/Options/AbstractOptionPreviewViewModel.cs
  src/VisualStudio/Core/Impl/Options/Style/NamingPreferences/NamingStyles/MutableNamingStyle.cs
  src/Workspaces/Core/Portable/CodeStyle/CodeStyleOption.cs
  src/Workspaces/Core/Portable/Options/OptionSet.cs
  src/Workspaces/CoreTestUtilities/Options/OptionsTestHelpers.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/CodeStyleOption2`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/Serialization/AccessibilityExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/Serialization/SymbolSpecification.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Options/OptionDefinition.cs
Labels: Area-IDE, untriaged

#73825 Add ability to rewrite symbol references in BoundTreeRewriter.
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/BoundTree/BoundTreeRewriter.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass_LocalFunctions.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForStatement.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_WhileStatement.cs
  src/Compilers/CSharp/Portable/Lowering/MethodToClassRewriter.cs
  src/Tools/Source/CompilerGeneratorTools/Source/BoundTreeGenerator/BoundNodeClassWriter.cs
Labels: Area-Compilers, untriaged, New Language Feature - Roles

#73855 Introduce an interval tree implementation backed by an array.
  src/EditorFeatures/Core/Shared/Tagging/Utilities/TagSpanIntervalTree.cs
  src/Features/CSharp/Portable/ConvertToRawString/ConvertInterpolatedStringToRawStringCodeRefactoringProvider.cs
  src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineViewModel.DocumentOutlineViewState.cs
  src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineViewModel.cs
  src/Workspaces/Core/Portable/Classification/ClassifierHelper.cs
  src/Workspaces/CoreTest/UtilityTest/IntervalTreeTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/FlatArrayIntervalTree`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/IIntervalTree`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/IntervalTree`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
Labels: Area-IDE, untriaged

#73859 Share the majority of code between the Binary and Flat-Array versions of our interval trees.
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/FlatArrayIntervalTree`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/IntervalTreeHelpers.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/IntervalTree`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
Labels: Area-IDE, untriaged

#73867 Fix serialization of capabilities in onautoinsert
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/ServerInitializationTests.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Utilities/AbstractLanguageServerHostTests.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/LanguageServer/LanguageServerHost.cs
  src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework.UnitTests/TestExampleLanguageServer.cs
  src/LanguageServer/Protocol/Protocol/Internal/Converters/VSCodeInternalExtensionUtilities.cs
Labels: Area-Infrastructure, LSP, untriaged

#73860 Rename the interval tree types.
  src/Analyzers/CSharp/Analyzers/RemoveUnnecessaryNullableDirective/CSharpRemoveUnnecessaryNullableDirectiveDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/RemoveUnnecessaryNullableDirective/NullableImpactingSpanWalker.cs
  src/Analyzers/Core/Analyzers/SimplifyTypeNames/SimplifyTypeNamesDiagnosticAnalyzerBase.cs
  src/EditorFeatures/Core/Shared/Tagging/Utilities/TagSpanIntervalTree.cs
  src/Features/CSharp/Portable/ConvertToRawString/ConvertInterpolatedStringToRawStringCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpSimplifyTypeNamesDiagnosticAnalyzer.cs
  src/Features/CSharp/Portable/Diagnostics/Analyzers/TypeSyntaxSimplifierWalker.cs
  src/Features/VisualBasic/Portable/Diagnostics/Analyzers/TypeSyntaxSimplifierWalker.vb
  src/Features/VisualBasic/Portable/Diagnostics/Analyzers/VisualBasicSimplifyTypeNamesDiagnosticAnalyzer.vb
  src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineViewModel.DocumentOutlineViewState.cs
  src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineViewModel.cs
  src/VisualStudio/Core/Def/InheritanceMargin/InheritanceGlyphManager.cs
  src/Workspaces/Core/Portable/Classification/ClassifierHelper.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/TextChangeMerger.cs
  src/Workspaces/Core/Portable/Editing/ImportAdderService.cs
  src/Workspaces/Core/Portable/Simplification/AbstractSimplificationService.cs
  src/Workspaces/CoreTest/UtilityTest/IntervalTreeTests.cs
  src/Workspaces/Remote/ServiceHub/Services/SemanticClassification/RemoteSemanticClassificationService.Caching.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/CSharpSyntaxFormatting.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Engine/AggregatedFormattingResult.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Engine/FormattingResult.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Engine/Trivia/TriviaRewriter.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/FlatArrayIntervalTree`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/IntervalTreeHelpers.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/IntervalTree`1.Node.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/IntervalTree`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/SimpleIntervalTree.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/SimpleIntervalTree`2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/TextSpanIntervalIntrospector.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/AbstractSyntaxFormatting.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Context/FormattingContext.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/ContextIntervalTree.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Engine/AbstractAggregatedFormattingResult.cs
  src/Workspaces/VisualBasic/Portable/CodeCleanup/Providers/AbstractTokensCodeCleanupProvider.vb
  src/Workspaces/VisualBasic/Portable/CodeCleanup/Providers/NormalizeModifiersOrOperatorsCodeCleanupProvider.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/AggregatedFormattingResult.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/FormattingResult.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Engine/Trivia/TriviaDataFactory.TriviaRewriter.vb
  src/Workspaces/VisualBasic/Portable/Formatting/VisualBasicSyntaxFormatting.vb
Labels: Area-IDE, untriaged

#73878 Disable automatic test discovery for Roslyn in DevKit
  .vscode/settings.json
Labels: Area-Infrastructure, untriaged

#73876 Fix recent break of interval tree efficiency
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/IntervalTreeHelpers.cs
Labels: Area-IDE, untriaged

#73852 Add tsx/jsx as recognized extensions for TS
  src/LanguageServer/Protocol/LanguageInfoProvider.cs
Labels: Area-IDE, untriaged

#73875 Merges/release/dev17.10 to release/dev17.11
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSourceProviders/WorkspaceDiagnosticSourceHelpers.cs
Labels: Area-IDE, untriaged

#73788 Fix exponential blowup parsing pathological files
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/OutVarTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/LambdaAttributeParsingTests.cs
Labels: Area-Compilers, untriaged

#73871 Remove unused package version: Microsoft.VisualStudio.Debugger.UI.Interfaces
  eng/Directory.Packages.props
Labels: Area-Infrastructure, untriaged

#73874 Update interval tree code for clarity
  src/Workspaces/Core/Portable/CodeCleanup/AbstractCodeCleanerService.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/TextChangeMerger.cs
  src/Workspaces/CoreTest/UtilityTest/IntervalTreeTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/ImmutableIntervalTree`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/MutableIntervalTree`1.Node.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/MutableIntervalTree`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/SimpleMutableIntervalTree.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/SimpleMutableIntervalTree`2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/TextSpanMutableIntervalTree.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/ContextMutableIntervalTree.cs
Labels: Area-IDE, untriaged

#73877 Add struct base enumerator for interval trees.
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/IIntervalTree`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/ImmutableIntervalTree`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/IntervalTreeAlgorithms`2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/IntervalTreeHelpers.Enumerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/IntervalTreeHelpers.NodeEnumerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/IntervalTreeHelpers.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/MutableIntervalTree`1.Node.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/MutableIntervalTree`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
Labels: Area-IDE, untriaged

#73880 Use separate async tracker for SG work instad of reusing workspace async tracker
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/WorkspaceInProcess.cs
  src/Workspaces/Core/Portable/Workspace/Host/TaskScheduler/IWorkspaceAsynchronousOperationListenerProvider.cs
  src/Workspaces/Core/Portable/Workspace/Host/TaskScheduler/WorkspaceAsynchronousOperationListenerProvider.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
  src/Workspaces/Core/Portable/Workspace/Workspace_SourceGeneration.cs
Labels: Area-IDE, untriaged

#73882 Change global option change notification to batch all option changes
  src/EditorFeatures/Core/Classification/Semantic/AbstractSemanticOrEmbeddedClassificationViewTaggerProvider.cs
  src/EditorFeatures/Core/InlineHints/InlineHintsDataTaggerProvider.cs
  src/EditorFeatures/Core/Shared/Tagging/EventSources/TaggerEventSources.OptionChangedEventSource.cs
  src/EditorFeatures/Core/Shared/Tagging/EventSources/TaggerEventSources.cs
  src/EditorFeatures/Core/Structure/AbstractStructureTaggerProvider.cs
  src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource.cs
  src/LanguageServer/Protocol/Features/Diagnostics/DiagnosticAnalyzerService.cs
  src/LanguageServer/Protocol/Handler/CodeLens/CodeLensRefreshQueue.cs
  src/LanguageServer/Protocol/Handler/Configuration/DidChangeConfigurationNotificationHandler.cs
  src/LanguageServer/Protocol/Handler/InlayHint/InlayHintRefreshQueue.cs
  src/VisualStudio/Core/Def/InheritanceMargin/InheritanceMarginTaggerProvider.cs
  src/VisualStudio/Core/Def/InheritanceMargin/InheritanceMarginViewMargin.cs
  src/VisualStudio/Core/Def/LanguageService/AbstractLanguageService`2.VsCodeWindowManager.cs
  src/VisualStudio/Core/Def/StackTraceExplorer/StackTraceExplorerCommandHandler.cs
  src/VisualStudio/Core/Def/Telemetry/FileLogger.cs
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/OptionPages/ForceLowMemoryMode.cs
  src/Workspaces/Core/Portable/Options/GlobalOptionService.cs
  src/Workspaces/Core/Portable/Options/OptionChangedEventArgs.cs
  src/Workspaces/CoreTest/WorkspaceServiceTests/GlobalOptionServiceTests.cs
Labels: Area-IDE, untriaged

#73895 [cherry-pick] Use separate async tracker for SG work instad of reusing workspace async tracker
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/WorkspaceInProcess.cs
  src/Workspaces/Core/Portable/Workspace/Host/TaskScheduler/IWorkspaceAsynchronousOperationListenerProvider.cs
  src/Workspaces/Core/Portable/Workspace/Host/TaskScheduler/WorkspaceAsynchronousOperationListenerProvider.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
  src/Workspaces/Core/Portable/Workspace/Workspace_SourceGeneration.cs
Labels: Area-IDE, untriaged

#73896 Apply editorconfig settings to moved ExternalAccess
  .editorconfig
  src/EditorFeatures/ExternalAccess/Copilot/.editorconfig
  src/Features/ExternalAccess/AspNetCore/.editorconfig
  src/Features/ExternalAccess/AspNetCore/EmbeddedLanguages/AspNetCoreCSharpRouteSyntaxDetector.cs
  src/Features/ExternalAccess/OmniSharp/.editorconfig
  src/Tools/ExternalAccess/.editorconfig
  src/VisualStudio/ExternalAccess/Apex/.editorconfig
  src/VisualStudio/ExternalAccess/FSharp/.editorconfig
Labels: Area-IDE, untriaged

#73913 Fix wrong sorting in `AbstractSpellCheckingHandler.cs`
  src/LanguageServer/Protocol/Handler/SpellCheck/AbstractSpellCheckingHandler.cs
Labels: Area-IDE, Community, untriaged

#73841 Update MicrosoftDevDivOptimizationDataPowerShellVersion to 1.0.803
  azure-pipelines-pr-validation.yml
  eng/Versions.props
  eng/build.ps1
  eng/pipelines/insert.yml
  src/Features/Lsif/Generator/Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.csproj
  src/Tools/BuildBoss/BuildBoss.csproj
  src/Tools/BuildBoss/Program.cs
Labels: Area-Compilers, untriaged

#73794 Reduce allocations in PENamespaceSymbol.GetMembers()
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamespaceSymbol.cs
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PENamespaceSymbol.vb
Labels: Area-Compilers, untriaged

#73907 Editorconfig options enumerator refactoring
  src/VisualStudio/CSharp/Impl/Options/Formatting/CodeStylePage.cs
  src/VisualStudio/Core/Test/Options/BasicEditorConfigGeneratorTests.vb
  src/VisualStudio/Core/Test/Options/CSharpEditorConfigGeneratorTests.vb
  src/VisualStudio/ExternalAccess/EditorConfigGenerator/EditorConfigGenerator.cs
  src/VisualStudio/VisualBasic/Impl/Options/Formatting/CodeStylePage.vb
  src/Workspaces/CSharp/Portable/CodeStyle/CSharpEditorConfigOptionsGenerator.cs
  src/Workspaces/CSharp/Portable/Options/CSharpEditorConfigOptionsEnumerator.cs
  src/Workspaces/Core/Portable/Options/EditorConfig/EditorConfigOptionsEnumerator.cs
  src/Workspaces/Core/Portable/Options/EditorConfig/EditorConfigOptionsEnumeratorAttribute.cs
  src/Workspaces/Core/Portable/Options/EditorConfig/IEditorConfigOptionsEnumerator.cs
  src/Workspaces/VisualBasic/Portable/CodeStyle/VisualBasicEditorConfigOptionsGenerator.vb
  src/Workspaces/VisualBasic/Portable/Options/VisualBasicEditorConfigOptionsEnumerator.vb
Labels: Area-IDE, untriaged

#73922 Fix NFWs due to BG SG system in non C#/VB languages
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.cs
Labels: Area-IDE, untriaged

#73924 Update TSAConfig.gdntsa
  eng/TSAConfig.gdntsa
Labels: Area-Infrastructure, untriaged

#73933 Fix typos in DiagnosticSuppressorDesign.md
  docs/analyzers/DiagnosticSuppressorDesign.md
Labels: Community, untriaged

#73886 Follow up on added ability to rewrite symbol references in BoundTreeRewriter.
  src/Compilers/CSharp/Portable/Binder/Binder.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/SwitchBinder_Patterns.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/BoundTree/BoundTreeRewriter.cs
  src/Compilers/CSharp/Portable/BoundTree/Constructors.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/FlowAnalysisPass.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/BoundTreeToDifferentEnclosingContextRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.cs
  src/Compilers/CSharp/Portable/Lowering/MethodToClassRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Tools/Source/CompilerGeneratorTools/Source/BoundTreeGenerator/BoundNodeClassWriter.cs
Labels: Area-Compilers, untriaged, New Language Feature - Roles

#73919 Improve EnC log messages
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/Core/Portable/EditAndContinue/EditSessionTelemetry.cs
  src/Features/Core/Portable/EditAndContinue/ProjectAnalysisSummary.cs
Labels: Area-Interactive, untriaged

#73829 Do not report warnings because there is non-array params candidate among applicable dynamic candidates.
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Generated/ErrorFacts.Generated.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit2/Semantics/ParamsCollectionTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
Labels: Area-Compilers, untriaged, New Feature - ParamsCollections

#73937 Cache the last string's hash we computed in our filepath map
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CachingFilePathComparer.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
Labels: Area-IDE, untriaged

#73940 Localize 17.11 branch
  azure-pipelines-official.yml
Labels: Area-Infrastructure, untriaged

#73925 Update NuGet-packages.md
  docs/wiki/NuGet-packages.md
Labels: Area-Infrastructure, untriaged

#73850 Delay reporting of pattern-based using diagnostics
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/UsingStatementBinder.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAwaitForeachTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAwaitUsingTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenUsingStatementTests.cs
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IUsingStatement.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/UsingStatementTests.cs
Labels: Area-Compilers, New Feature - Async Streams, untriaged

#73941 Change AsyncLazy from NonReentrantLock to a simple monitor enter
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/AsyncLazy`1.cs
Labels: Area-IDE, untriaged

#73945 Fix leak of assembly metadata instances
  src/VisualStudio/Core/Def/ProjectSystem/MetadataReferences/VisualStudioMetadataReferenceManager.cs
Labels: Area-IDE, untriaged

#73943 Backport #73852 to 17.10
  src/Features/LanguageServer/Protocol/LanguageInfoProvider.cs
Labels: Area-IDE, untriaged

#73948 Add Microsoft.IdentityModel.JsonWebTokens to InternalTools.props
  eng/InternalTools.props
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#73951 Update required VS to 17.8.
  global.json
Labels: Area-Infrastructure, untriaged

#73950 Add Microsoft.IdentityModel.JsonWebTokens to InternalTools.props and add restore source
  eng/InternalTools.props
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#73851 Use a serialization compatible marker
  src/Compilers/Core/Portable/InternalUtilities/FatalError.cs
  src/Workspaces/CoreTest/UtilityTest/ExceptionHelpersTests.cs
Labels: Area-Compilers, untriaged

#73963 Remove unused scripts
  scripts/README.md
  scripts/build_mono.sh
  scripts/edit-designers.ps1
  scripts/run_perf.ps1
  scripts/test-nuget-cache.ps1
Labels: Area-Infrastructure, untriaged

#73912 Add documentation to Values property in TypedConstant struct
  src/Compilers/Core/Portable/Symbols/TypedConstant.cs
Labels: Area-Compilers, Community, untriaged

#73965 Remove A/B option to disable recoverable texts
  src/LanguageServer/Protocol/Features/Options/WorkspaceConfigurationOptionsStorage.cs
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
  src/Workspaces/Core/Portable/Workspace/IWorkspaceConfigurationService.cs
  src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentState.cs
Labels: Area-IDE, untriaged

#73942 Expose Roslyn LSP types to XAML and add readme
  src/LanguageServer/Protocol/Microsoft.CodeAnalysis.LanguageServer.Protocol.csproj
  src/LanguageServer/Protocol/Protocol/LanguageServer.Protocol.csproj
  src/LanguageServer/Protocol/Protocol/LanguageServer.Protocol.ruleset
  src/LanguageServer/Protocol/Protocol/README.md
Labels: Area-IDE, untriaged

#73967 Add Microsoft.Identity.Client and System.IdentityModel.Tokens.Jwt to InternalTools.props
  eng/InternalTools.props
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#73971 Add another TS extension path
  src/Features/LanguageServer/Protocol/LanguageInfoProvider.cs
Labels: Area-Infrastructure, untriaged

#73972 Move VSExtensibility back to the nuget.org version
  eng/Directory.Packages.props
Labels: Area-Infrastructure, untriaged

#73968 Remove A/B option for enabling features in SG docs.
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/LanguageServer/Protocol/Features/Options/WorkspaceConfigurationOptionsStorage.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/Workspace/SourceGeneratedFileManager.cs
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpSourceGenerators.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/StateResetInProcess.cs
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageStrings.vb
  src/Workspaces/Core/Portable/Workspace/IWorkspaceConfigurationService.cs
  src/Workspaces/CoreTest/Options/OptionSerializerTests.cs
Labels: Area-IDE, untriaged

#73969 Remove option controlling which persistence DB to use.
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingWorkCoordinator.UnitTestingSemanticChangeProcessor.cs
  src/LanguageServer/Protocol/Features/Options/WorkspaceConfigurationOptionsStorage.cs
  src/Tools/AnalyzerRunner/IncrementalAnalyzerRunner.cs
  src/Tools/AnalyzerRunner/Options.cs
  src/Tools/IdeCoreBenchmarks/CSharpIdeAnalyzerBenchmarks.cs
  src/Tools/IdeCoreBenchmarks/IncrementalAnalyzerBenchmarks.cs
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
  src/Workspaces/Core/Portable/Storage/PersistentStorageExtensions.cs
  src/Workspaces/Core/Portable/Storage/StorageDatabase.cs
  src/Workspaces/Core/Portable/Utilities/Documentation/XmlDocumentationProvider.cs
  src/Workspaces/Core/Portable/Workspace/Host/Metadata/MetadataReferenceCache.cs
  src/Workspaces/Core/Portable/Workspace/IWorkspaceConfigurationService.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectDependencyGraph.cs
  src/Workspaces/CoreTest/Options/OptionSerializerTests.cs
Labels: Area-IDE, untriaged

#73840 Upgrade MicrosoftCodeAnalysisTestingVersion to 1.1.2-beta1.24121.1
  eng/Versions.props
  src/EditorFeatures/CSharpTest/ConvertToRecord/ConvertToRecordCodeRefactoringTests.cs
  src/EditorFeatures/CSharpTest/ExtractClass/ExtractClassTests.cs
  src/EditorFeatures/CSharpTest/GenerateFromMembers/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersTests.cs
  src/EditorFeatures/CSharpTest/MoveStaticMembers/CSharpMoveStaticMembersTests.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/CSharpCodeFixVerifier`2+Test.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/CSharpCodeRefactoringVerifier`1+Test.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/VisualBasicCodeRefactoringVerifier`1+Test.cs
  src/EditorFeatures/VisualBasicTest/MoveStaticMembers/VisualBasicMoveStaticMembersTests.vb
Labels: Area-IDE, untriaged

#73973 Move builds to 1ES PT
  azure-pipelines-official.yml
  azure-pipelines-pr-validation.yml
Labels: Area-Infrastructure, untriaged

#73975 Update version for system.data.sqlclient to 4.8.6
  eng/Versions.props
  src/Tools/Source/RunTests/RunTests.csproj
Labels: Area-Infrastructure, untriaged

#73577 Add standard implicit array-to-Span conversions
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversion.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionKind.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionKindExtensions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/UserDefinedImplicitConversions.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.AllInOne.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests_Scope.cs
  src/Compilers/CSharp/Test/Emit3/FirstClassSpanTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IConversionExpression.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LookupPositionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/VarianceTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/CodeAnalysisTest/Diagnostics/AnalysisContextInfoTests.cs
  src/Compilers/Core/Portable/InternalUtilities/ArrayExtensions.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/Test/Core/TargetFrameworkUtil.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
  src/Features/LanguageServer/Protocol/Handler/Hover/ILspHoverResultCreationService.cs
  src/Tools/GenerateRulesMissingDocumentation/Program.cs
  src/Workspaces/Core/Portable/CodeRefactorings/ExportCodeRefactoringProviderAttribute.cs
  src/Workspaces/Core/Portable/Workspace/Host/Mef/MefHostServices.cs
  src/Workspaces/MSBuildTest/NewlyCreatedProjectsFromDotNetNew.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/ArrayExtensions.cs
Labels: Area-Compilers, untriaged, New Feature - First-class Span Types

#73650 ChildSyntaxList.ItemInternal optimization
  src/Compilers/CSharp/Portable/Syntax/CSharpSyntaxWalker.cs
  src/Compilers/Core/Portable/Syntax/ChildSyntaxList.Enumerator.cs
  src/Compilers/Core/Portable/Syntax/ChildSyntaxList.cs
Labels: Area-Compilers, untriaged

#73976 Fix error in compile loop
  src/Tools/Replay/Replay.cs
Labels: Area-Infrastructure, untriaged

#73986 Add Microsoft.IdentityModel.JsonWebTokens to InternalTools.props in 17.6
  eng/InternalTools.props
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#73990 Cache metadata around until it is overwritten
  src/VisualStudio/Core/Def/ProjectSystem/MetadataReferences/VisualStudioMetadataReferenceManager.cs
Labels: Area-IDE, untriaged

#73902 Throw when there is a syntax version mismatch in codelens
  src/LanguageServer/Protocol/Handler/CodeLens/CodeLensResolveHandler.cs
  src/LanguageServer/ProtocolUnitTests/CodeLens/CSharpCodeLensTests.cs
Labels: Area-Infrastructure, untriaged

#73992 Support goto-def taking you from an interceptor method to the location being intercepted.
  src/EditorFeatures/Core/EditorFeaturesResources.resx
  src/EditorFeatures/Core/Navigation/AbstractDefinitionLocationService.cs
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.cs.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.de.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.es.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.fr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.it.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ja.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ko.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pl.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pt-BR.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ru.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.tr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hans.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hant.xlf
  src/EditorFeatures/Test2/GoToDefinition/CSharpGoToDefinitionTests.vb
  src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionTestsBase.vb
  src/Workspaces/Core/Portable/Workspace/Solution/DocumentState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Project.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState_Checksum.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/ObjectPools/Extensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Base64Utilities.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/ImmutableArrayComparer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/InterceptslocationUtilities.cs
Labels: Area-IDE, untriaged

#73765 Prefer implicit span conversions
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.AllInOne.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests_Scope.cs
  src/Compilers/CSharp/Test/Emit3/FirstClassSpanTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LookupPositionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/VarianceTests.cs
  src/Compilers/Core/CodeAnalysisTest/Collections/ImmutableSegmentedListTest.cs
  src/Compilers/Core/CodeAnalysisTest/Diagnostics/AnalysisContextInfoTests.cs
  src/Compilers/Core/Portable/InternalUtilities/ArrayExtensions.cs
  src/Compilers/Test/Core/TargetFrameworkUtil.cs
  src/Features/LanguageServer/Protocol/Handler/Hover/ILspHoverResultCreationService.cs
  src/Tools/GenerateRulesMissingDocumentation/Program.cs
  src/Workspaces/Core/Portable/CodeRefactorings/ExportCodeRefactoringProviderAttribute.cs
  src/Workspaces/Core/Portable/Workspace/Host/Mef/MefHostServices.cs
  src/Workspaces/MSBuildTest/NewlyCreatedProjectsFromDotNetNew.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/ArrayExtensions.cs
Labels: Area-Compilers, untriaged, New Feature - First-class Span Types

#73762 Consider extension receiver conversion when reducing
  src/Compilers/CSharp/Portable/Symbols/ReducedExtensionMethodSymbol.cs
  src/Compilers/CSharp/Test/Emit3/FirstClassSpanTests.cs
Labels: Area-Compilers, untriaged, New Feature - First-class Span Types

#73995 Fix project configuration telemetry for legacy csproj projects
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/ProjectTelemetry/ProjectLoadTelemetryReporter.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/Constants/PropertyNames.cs
  src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs
  src/Workspaces/Core/MSBuild.BuildHost/Rpc/Contracts/ProjectFileInfo.cs
Labels: Area-IDE, untriaged

#73989 Ensure source generated documents are up-to-date before analyzing EnC changes
  src/EditorFeatures/Core/EditAndContinue/ActiveStatementTrackingService.cs
  src/EditorFeatures/Core/EditAndContinue/EditAndContinueLanguageService.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSession.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueService.cs
  src/Features/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/Features/TestUtilities/EditAndContinue/EditAndContinueWorkspaceTestBase.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.GeneratedFileReplacingCompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.ICompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.cs
  src/Workspaces/Core/Portable/Workspace/Workspace_SourceGeneration.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/ISolutionExtensions.cs
Labels: Area-Interactive, untriaged

#73996 Fix the duplicate glyphs in Inheritance margin
  src/EditorFeatures/Test/InheritanceMargin/InheritanceMarginTests.cs
  src/Features/Core/Portable/InheritanceMargin/AbstractInheritanceMarginService_Helpers.cs
Labels: Area-IDE, untriaged

#74014 Fix flakiness in LSP references tests due to non-deterministic ordering
  src/LanguageServer/ProtocolUnitTests/DocumentChanges/DocumentChangesTests.WithFindAllReferences.cs
  src/LanguageServer/ProtocolUnitTests/References/FindAllReferencesHandlerFeaturesTests.cs
  src/LanguageServer/ProtocolUnitTests/References/FindAllReferencesHandlerTests.cs
Labels: Area-Infrastructure, untriaged

#74018 Do not offer to add default switch case when it handles `null` and an underlying value
  src/Analyzers/CSharp/Tests/PopulateSwitch/PopulateSwitchExpressionTests.cs
  src/Analyzers/CSharp/Tests/PopulateSwitch/PopulateSwitchStatementTests.cs
  src/Analyzers/Core/Analyzers/PopulateSwitch/AbstractPopulateSwitchDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/PopulateSwitch/AbstractPopulateSwitchExpressionDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/PopulateSwitch/AbstractPopulateSwitchStatementDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/PopulateSwitch/PopulateSwitchExpressionHelpers.cs
  src/Analyzers/Core/Analyzers/PopulateSwitch/PopulateSwitchStatementHelpers.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ITypeSymbolExtensions.cs
Labels: Area-IDE, Community, untriaged

#74015 Fix find refs doing too much work lookign for types that had an alias to them in one file.
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ConstructorSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamedTypeSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamespaceSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/Shared/AbstractSyntaxIndex_Persistence.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Create.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Forwarders.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Persistence.cs
Labels: Area-IDE, untriaged

#74022 Fix link in docs
  docs/contributing/README.md
Labels: Area-Infrastructure, untriaged

#73938 Include wrapping options in editorconfig formatting options
  src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpCollectionExpressionRewriter.cs
  src/Analyzers/Core/CodeFixes/UseConditionalExpression/AbstractUseConditionalExpressionCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseConditionalExpression/ForAssignment/AbstractUseConditionalExpressionForAssignmentCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseConditionalExpression/ForReturn/AbstractUseConditionalExpressionForReturnCodeFixProvider.cs
  src/EditorFeatures/TestUtilities/Utilities/VisualBasicCodeActionOptions.cs
  src/Features/CSharp/Portable/Wrapping/CSharpSyntaxWrappingOptions.cs
  src/Features/CSharpTest/Wrapping/AbstractWrappingTests.cs
  src/Features/Core/Portable/Wrapping/SyntaxWrappingOptions.cs
  src/Features/DiagnosticsTestUtilities/CodeActionsLegacy/AbstractCodeActionTest_NoEditor.cs
  src/Features/VisualBasic/Portable/Wrapping/VisualBasicSyntaxWrappingOptions.vb
  src/Features/VisualBasicTest/Wrapping/AbstractParameterWrappingTests.vb
  src/LanguageServer/Protocol/Features/Options/CodeActionOptionsStorage.cs
  src/VisualStudio/CSharp/Test/EditorConfigSettings/DataProvider/DataProviderTests.cs
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
  src/VisualStudio/Core/Impl/Options/GridOptionPreviewControl.xaml.cs
  src/VisualStudio/Core/Test.Next/Options/VisualStudioOptionStorageTests.cs
  src/Workspaces/CSharp/Portable/Options/CSharpEditorConfigOptionsEnumerator.cs
  src/Workspaces/Core/Portable/CodeStyle/CodeStyleOption.cs
  src/Workspaces/Core/Portable/Options/EditorConfig/EditorConfigFileGenerator.cs
  src/Workspaces/Core/Portable/Options/EditorConfig/EditorConfigOptionsEnumerator.cs
  src/Workspaces/Core/Portable/Options/EditorConfig/IEditorConfigOptionsEnumerator.cs
  src/Workspaces/CoreTest/Options/OptionKeyTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeStyle/CSharpCodeStyleOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/CSharpFormattingOptions2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/CSharpSyntaxFormattingOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/CodeStyleOption2`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/CodeStyleOptions2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/VisualBasic/VisualBasicCodeStyleOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Editing/GenerationOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/FormattingOptions2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/SyntaxFormattingOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Options/Option2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Options/OptionDefinition.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/CodeActionOptions.cs
  src/Workspaces/VisualBasic/Portable/Options/VisualBasicEditorConfigOptionsEnumerator.vb
Labels: Area-IDE, untriaged

#73997 Fix flaky test: LanguageServerCleansUpOnUnexpectedJsonRpcDisconnectAsync
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/AbstractLanguageServer.cs
Labels: Area-IDE, untriaged

#74029 Add brokered service for Hot Reload in VS Code: GenericHotReloadAgentManagerService
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/Services/Descriptors.cs
  src/Workspaces/Remote/Core/BrokeredServiceDescriptors.cs
Labels: Area-IDE, Community, untriaged

#74019 Do not treat text as json when passed to api that explicit says it is not
  src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs
  src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests_Json.cs
  src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests_TestMarkup.cs
  src/Features/Core/Portable/EmbeddedLanguages/AbstractLanguageDetector.cs
  src/Features/Core/Portable/EmbeddedLanguages/EmbeddedLanguageDetector.cs
  src/Features/Core/Portable/EmbeddedLanguages/Json/LanguageServices/JsonLanguageDetector.cs
  src/Workspaces/Core/Portable/FindSymbols/Shared/AbstractSyntaxIndex_Persistence.cs
Labels: Area-IDE, untriaged

#73994 Emit extension marker method as public
  src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Extensions/SynthesizedExtensionMarker.cs
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/Emit3/ExtensionTypeTests.cs
  src/Compilers/Test/Core/Metadata/MetadataReaderUtils.cs
Labels: Area-Compilers, untriaged, New Language Feature - Roles

#74037 Fix move static members when destination is in the same file
  src/EditorFeatures/CSharpTest/CodeActions/MoveStaticMembers/CSharpMoveStaticMembersTests.cs
  src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs
Labels: Area-IDE, untriaged

#74060 Correctly define versions for runtime dependencies
  eng/Directory.Packages.props
  eng/Version.Details.xml
  eng/Versions.props
  src/Tools/ExternalAccess/Xaml/Microsoft.CodeAnalysis.ExternalAccess.Xaml.csproj
Labels: Area-Infrastructure, Community, untriaged

#74036 Add LanguageServer.Protocol.Test.Utilities.csproj
  Roslyn.sln
  src/Compilers/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.csproj
  src/Compilers/Test/Core/Microsoft.CodeAnalysis.Test.Utilities.csproj
  src/Compilers/Test/Utilities/CSharp/Microsoft.CodeAnalysis.CSharp.Test.Utilities.csproj
  src/Compilers/Test/Utilities/VisualBasic/Microsoft.CodeAnalysis.VisualBasic.Test.Utilities.vbproj
  src/Compilers/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.vbproj
  src/EditorFeatures/TestUtilities/EditorTestCompositions.cs
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/EditorFeatures/TestUtilities/Microsoft.CodeAnalysis.EditorFeatures.Test.Utilities.csproj
  src/Features/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.Features.csproj
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/Features/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.Features.vbproj
  src/LanguageServer/Protocol.TestUtilities/LspTestCompositions.cs
  src/LanguageServer/Protocol.TestUtilities/Microsoft.CodeAnalysis.LanguageServer.Protocol.Test.Utilities.csproj
  src/LanguageServer/Protocol/Microsoft.CodeAnalysis.LanguageServer.Protocol.csproj
  src/LanguageServer/ProtocolUnitTests/Options/LspOptionsTests.cs
  src/LanguageServer/ProtocolUnitTests/References/FindAllReferencesHandlerFeaturesTests.cs
  src/VisualStudio/LiveShare/Test/LiveShareTestCompositions.cs
  src/VisualStudio/LiveShare/Test/Microsoft.VisualStudio.LanguageServices.LiveShare.UnitTests.csproj
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
  src/Workspaces/CoreTestUtilities/Microsoft.CodeAnalysis.Workspaces.Test.Utilities.csproj
  src/Workspaces/Remote/Core/Microsoft.CodeAnalysis.Remote.Workspaces.csproj
Labels: Area-Infrastructure, untriaged

#74062 Use separate feature IDs for ref struct interfaces and allows ref struct constraint.
  src/Compilers/CSharp/Portable/Binder/Binder_Constraints.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
Labels: Area-Compilers, untriaged, New Feature - RefStructInterfaces

#74063 Fix APIScan authentication
  azure-pipelines-compliance.yml
Labels: Area-Infrastructure, untriaged

#74084 Create new AsyncServiceProvider instead of using AsyncServiceProvider.GlobalProvider
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs
Labels: Area-IDE, untriaged

#74068 Add some missing LSP protocol definitions
  src/LanguageServer/Protocol/Protocol/CodeActionRegistrationOptions.cs
  src/LanguageServer/Protocol/Protocol/CompletionRegistrationOptions.cs
  src/LanguageServer/Protocol/Protocol/DefinitionRegistrationOptions.cs
  src/LanguageServer/Protocol/Protocol/DocumentFormattingRegistrationOptions.cs
  src/LanguageServer/Protocol/Protocol/DocumentOnTypeFormattingRegistrationOptions.cs
  src/LanguageServer/Protocol/Protocol/DocumentRangeFormattingRegistrationOptions.cs
  src/LanguageServer/Protocol/Protocol/FoldingRangeRegistrationOptions.cs
  src/LanguageServer/Protocol/Protocol/HoverRegistrationOptions.cs
  src/LanguageServer/Protocol/Protocol/Internal/VSInternalDocumentOnAutoInsertRegistrationOptions.cs
  src/LanguageServer/Protocol/Protocol/Internal/VSInternalDocumentOnAutoInsertResponseItem.cs
Labels: Area-IDE, untriaged

#74069 [LSP] Support "implementation" folding range kinds
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/Lsif/GeneratorTest/FoldingRangeTests.vb
  src/LanguageServer/Protocol/Handler/FoldingRanges/FoldingRangesHandler.cs
  src/LanguageServer/Protocol/Protocol/FoldingRangeKind.cs
  src/LanguageServer/Protocol/Protocol/Internal/VSFoldingRangeKind.cs
  src/LanguageServer/ProtocolUnitTests/FoldingRanges/FoldingRangesTests.cs
Labels: Area-Infrastructure, untriaged

#74072 Disallow `InlineArray` attribute on a record struct type.
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 9.md
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit2/Semantics/InlineArrayTests.cs
Labels: Area-Compilers, untriaged, New Feature - Inline Arrays

#74012 Enable end-to-end binding and emit for basic scenarios involving instance extension members.
  src/Compilers/CSharp/Portable/CodeGen/CodeGenerator.cs
  src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs
  src/Compilers/CSharp/Portable/Emitter/Model/NamedTypeSymbolAdapter.cs
  src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Lowering/InstanceExtensionMethodBodyRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/InstanceExtensionMethodReferenceRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Event.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PropertyAccess.cs
  src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/PublicSymbols/AnonymousManager.TypeOrDelegatePublicSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.TypeOrDelegateTemplateSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/ErrorTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Extensions/PEExtensionInstanceEventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Extensions/PEExtensionInstanceMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Extensions/PEExtensionInstancePropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Extensions/RewrittenExtensionEventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Extensions/RewrittenExtensionMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Extensions/RewrittenExtensionPropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Extensions/RewrittenLambdaOrLocalFunctionSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Extensions/RewrittenMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Extensions/RewrittenParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Extensions/SourceExtensionMetadataEventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Extensions/SourceExtensionMetadataMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Extensions/SourceExtensionMetadataPropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Extensions/SynthesizedExtensionThisParameterMetadataSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEEventSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEPropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/NativeIntegerTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/PropertySymbolExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ImplicitNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceExtensionTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceNonExtensionNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/SubstitutedNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/ReadOnlyListType/SynthesizedReadOnlyListEnumeratorTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/ReadOnlyListType/SynthesizedReadOnlyListTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedContainer.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedEmbeddedAttributeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedInlineArrayTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedPrivateImplementationDetailsType.cs
  src/Compilers/CSharp/Test/Emit3/ExtensionTypeTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MockNamedTypeSymbol.cs
  src/Compilers/Core/Portable/MetadataReader/MetadataDecoder.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/EENamedTypeSymbol.cs
Labels: Area-Compilers, untriaged, New Language Feature - Roles

#74097 Align implementation with latest LDM decisions around invocations in presence of dynamic arguments.
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit2/Semantics/ParamsCollectionTests.cs
Labels: Area-Compilers, untriaged, New Feature - ParamsCollections

#74051 Add type hints for collection expressions
  src/EditorFeatures/Core/InlineHints/InlineHintsDataTaggerProvider.cs
  src/Features/CSharp/Portable/InlineHints/CSharpInlineTypeHintsService.cs
  src/Features/Core/Portable/InlineHints/AbstractInlineTypeHintsService.cs
  src/Features/Core/Portable/InlineHints/InlineTypeHintsOptions.cs
  src/LanguageServer/Protocol/Features/Options/InlineHintsOptionsStorage.cs
  src/LanguageServer/Protocol/Handler/Configuration/DidChangeConfigurationNotificationHandler_OptionList.cs
  src/LanguageServer/Protocol/Handler/InlayHint/InlayHintRefreshQueue.cs
  src/LanguageServer/ProtocolUnitTests/Configuration/DidChangeConfigurationNotificationHandlerTest.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageStrings.cs
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
  src/VisualStudio/Core/Def/ServicesVSResources.resx
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.cs.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.de.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.es.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.fr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.it.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ja.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ko.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pl.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.ru.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.tr.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/ServicesVSResources.zh-Hant.xlf
Labels: Area-IDE, untriaged

#74075 Avoid allocations in AbstractSyntaxIndex<>.GetIndexAsync
  src/Workspaces/Core/Portable/FindSymbols/Shared/AbstractSyntaxIndex.cs
Labels: Area-IDE, untriaged

#74100 Query for the COM service provider instead of direct cast
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs
Labels: Area-IDE, untriaged

#74088 On the fly docs - add telemetry regarding documentation comments
  src/EditorFeatures/Core.Wpf/QuickInfo/OnTheFlyDocsView.xaml.cs
  src/EditorFeatures/Core.Wpf/QuickInfo/OnTheFlyDocsViewFactory.cs
  src/Features/CSharp/Portable/QuickInfo/CSharpSemanticQuickInfoProvider.cs
  src/Features/Core/Portable/Common/FeaturesSessionTelemetry.cs
  src/Features/Core/Portable/QuickInfo/OnTheFlyDocsElement.cs
  src/Features/Core/Portable/QuickInfo/OnTheFlyDocsLogger.cs
  src/Features/Core/Portable/QuickInfo/QuickInfoUtilities.cs
  src/VisualStudio/Core/Def/RoslynPackage.cs
Labels: Area-IDE, untriaged

#74024 Remove warning for `yield return` in `lock`
  docs/compilers/CSharp/Warnversion Warning Waves.md
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Generated/ErrorFacts.Generated.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit2/Emit/EditAndContinue/EditAndContinueStateMachineTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/LockTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/IteratorTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
Labels: Area-Compilers, untriaged, New Feature - Ref/Unsafe in Iterators/Async

#73206 Require AddExplicitInterfaceImplementation for adding a type that implements member explicitly
  src/Features/CSharpTest/EditAndContinue/ActiveStatementTests.cs
  src/Features/CSharpTest/EditAndContinue/StatementEditingTests.cs
  src/Features/CSharpTest/EditAndContinue/TopLevelEditingTests.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueCapabilities.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueCapabilitiesGrantor.cs
  src/Features/Core/Portable/EditAndContinue/Utilities/Extensions.cs
  src/Features/Core/Portable/ExternalAccess/Watch/Api/WatchHotReloadService.cs
  src/Features/TestUtilities/EditAndContinue/EditAndContinueTestHelpers.cs
  src/Features/VisualBasicTest/EditAndContinue/ActiveStatementTests.vb
  src/Features/VisualBasicTest/EditAndContinue/StatementEditingTests.vb
  src/Features/VisualBasicTest/EditAndContinue/TopLevelEditingTests.vb
Labels: Area-Interactive, untriaged

#73949 Add a cancellation on typing for SmartRename if user begins to type
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameViewModel.cs
Labels: Area-IDE, Community, untriaged

#74119 Update config for snap
  eng/Versions.props
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#74106 Make sure task completes on exception path
  src/Tools/Source/RunTests/ProcessRunner.cs
Labels: Area-Infrastructure, untriaged

#74136 Temporarily disable R2R
  src/Interactive/HostProcess/x64/InteractiveHost64.csproj
Labels: Area-Interactive, untriaged

#74128 Add overload resolution priority status
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation, untriaged

#74147 Mark partial properties feature as shipped
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation, untriaged

#74102 Enable some type test scenarios involving ref like type parameters
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
Labels: Area-Compilers, untriaged, New Feature - RefStructInterfaces

#74091 Handle unspecified anonymous type property in VisualBasicOperationFactory
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb
  src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb
  src/Compilers/VisualBasic/Test/IOperation/IOperation/IOperationTests_IAnonymousObjectCreationOperation.vb
Labels: Area-Compilers, untriaged

#74006 Support navigating to an interceptor location when on an intercepted method call.
  src/EditorFeatures/Core/EditorFeaturesResources.resx
  src/EditorFeatures/Core/Navigation/AbstractDefinitionLocationService.cs
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.cs.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.de.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.es.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.fr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.it.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ja.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ko.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pl.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pt-BR.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ru.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.tr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hans.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hant.xlf
  src/EditorFeatures/Test2/GoToDefinition/CSharpGoToDefinitionTests.vb
  src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionCommandHandlerTests.vb
  src/Features/Core/Portable/AddImport/SymbolReferenceFinder.cs
  src/Features/Core/Portable/FullyQualify/AbstractFullyQualifyService.cs
  src/Features/Core/Portable/GenerateType/AbstractGenerateTypeService.State.cs
  src/Features/Core/Portable/QuickInfo/CommonSemanticQuickInfoProvider.cs
  src/Workspaces/Core/Portable/FindSymbols/Shared/AbstractSyntaxIndex_Persistence.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex.ContextInfo.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Create.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Forwarders.cs
  src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Persistence.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Document.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState_Checksum.cs
  src/Workspaces/MSBuildTest/NewlyCreatedProjectsFromDotNetNew.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SemanticFacts/CSharpSemanticFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SemanticFacts/ISemanticFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFactsExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/InterceptsLocationUtilities.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SemanticFacts/VisualBasicSemanticFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/SemanticsFactsService/AbstractSemanticFactsService.cs
Labels: Area-IDE, untriaged

#74101 Reduce time spent in ConflictResolver.Session.GetNodesOrTokensToCheckForConflicts
  src/Workspaces/CSharp/Portable/Rename/CSharpRenameRewriterLanguageService.cs
  src/Workspaces/Core/Portable/Rename/ConflictEngine/ConflictResolver.Session.cs
Labels: Area-IDE, untriaged

#73844 Remove semantic model keep-alive code in completion
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/CommitManager.cs
  src/Features/Core/Portable/Completion/CompletionService.cs
  src/Features/Core/Portable/Completion/CompletionService_GetCompletions.cs
Labels: Area-IDE, untriaged

#74130 Add weak heuristics in our designer scanning code to improve experience during things like configuration switch.
  src/Features/Core/Portable/DesignerAttribute/DesignerAttributeDiscoveryService.cs
  src/VisualStudio/CSharp/Test/DesignerAttribute/DesignerAttributeServiceTests.cs
Labels: Area-IDE, untriaged

#74114 Use ITextDifferencingService.DiffSnapshotSpans instead of allocating full buffer text during codeaction previews
  src/EditorFeatures/Core/Preview/AbstractPreviewFactoryService.cs
  src/EditorFeatures/Core/TextDiffing/EditorTextDifferencingService.cs
  src/EditorFeatures/Core/TextDiffing/TextDifferencingServiceExtensions.cs
  src/EditorFeatures/Text/Extensions.SnapshotSourceText.cs
  src/VisualStudio/Core/Def/Preview/FileChange.cs
Labels: Area-IDE, untriaged

#74159 Remove GetTempPath copy
  src/Compilers/Core/MSBuildTask/ManagedCompiler.cs
  src/Compilers/Server/VBCSCompilerTests/CompilerServerTests.cs
  src/Compilers/Shared/BuildClient.cs
  src/Compilers/Shared/BuildServerConnection.cs
Labels: Area-Compilers, untriaged

#74165 Enable TSA
  azure-pipelines-official.yml
Labels: Area-Infrastructure, untriaged

#74110 Handle early attribute required members cycle
  src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs
  src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/RequiredMembersTests.cs
Labels: Area-Compilers, untriaged

#74083 Avoid re-running all codeaction requests at low priority.
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionPriorityProvider.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource_Async.cs
  src/EditorFeatures/Test/CodeFixes/CodeFixServiceTests.cs
  src/Features/Core/Portable/CodeFixesAndRefactorings/CodeActionRequestPriorityProvider.cs
  src/LanguageServer/Protocol/Features/CodeFixes/CodeFixService.cs
Labels: Area-IDE, untriaged

#74112 Reduce allocations in AbstractProjectExtensionProvider.FilterExtensions
  src/Features/Core/Portable/CodeRefactorings/CodeRefactoringService.cs
  src/Features/Core/Portable/Common/AbstractProjectExtensionProvider.cs
  src/LanguageServer/Protocol/Features/CodeFixes/CodeFixService.cs
  src/Workspaces/Core/Portable/CodeFixesAndRefactorings/EnumArrayConverter.cs
Labels: Area-IDE, untriaged

#74034 Ensure an empty run result doesn't throw when generators are present.
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorState.cs
  src/Compilers/Core/Portable/SourceGeneration/RunResults.cs
Labels: Bug, Area-Compilers, New Feature - Source Generators, untriaged

#74089 Fix error recovery for various nested conversion scenarios
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/UserDefinedConversionTests.cs
Labels: Area-Compilers, untriaged

#74103 Sign `VSSetup/Installer/Roslyn_Preview.zip`
  eng/Signing.props
Labels: Area-Infrastructure, untriaged

#74181 Avoid failing docs check on temporary network errors
  src/Tools/GenerateRulesMissingDocumentation/Program.cs
Labels: Area-Infrastructure, untriaged

#74149 UI improvements for the Copilot rename feature
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameStatusControl.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameUserInputComboBox.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameUserInputComboBox.xaml.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameViewModel.cs
  src/EditorFeatures/Core.Wpf/Lightup/ISmartRenameSessionWrapper.cs
Labels: Area-IDE, Community, untriaged

#74164 Report diagnostic for field and value in property accessors when used as primary expressions only
  src/Compilers/CSharp/Portable/Binder/Binder.QueryTranslationState.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Lambda.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs
  src/Compilers/CSharp/Test/Syntax/Syntax/FieldAndValueKeywordTests.cs
Labels: Area-Compilers, untriaged

#74132 Move PEPropertySymbol to use the same UncommonFields pattern that PEMethodSymbol uses
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEPropertySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PETypeParameterSymbol.cs
  src/Compilers/Core/Portable/Binding/UseSiteInfo.cs
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEMethodSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PETypeParameterSymbol.vb
Labels: Area-Compilers, untriaged

#74186 Cherry-pick 74149 to 17.11
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameStatusControl.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameUserInputComboBox.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameUserInputComboBox.xaml.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameViewModel.cs
  src/EditorFeatures/Core.Wpf/Lightup/ISmartRenameSessionWrapper.cs
Labels: Area-IDE, untriaged

#74134 Consume new Razor EA
  eng/Directory.Packages.props
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/RazorInitializeHandler.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/RazorWorkspaceListenerInitializer.cs
Labels: Area-Infrastructure, untriaged

#74174 Cherry pick #74034
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratorState.cs
  src/Compilers/Core/Portable/SourceGeneration/RunResults.cs
Labels: Area-Compilers, untriaged

#74151 Better detect equivalence in our strong name provider
  src/Compilers/CSharp/Test/Emit/Emit/DesktopStrongNameProviderTests.cs
  src/Compilers/Core/Portable/StrongName/DesktopStrongNameProvider.cs
  src/Compilers/Core/Portable/StrongName/StrongNameFileSystem.cs
Labels: Area-Compilers, untriaged

#74204 Merge CI fix #74181 into `roles` branch
  src/Tools/GenerateRulesMissingDocumentation/Program.cs
Labels: Area-Infrastructure, untriaged

#74191 Fix scenario where lightbulbs weren't being displayed
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs
  src/EditorFeatures/Test2/Diagnostics/DiagnosticServiceTests.vb
  src/EditorFeatures/TestUtilities/Diagnostics/MockDiagnosticAnalyzerService.cs
  src/Features/Core/Portable/CodeFixes/FirstFixResult.cs
  src/Features/Core/Portable/Diagnostics/IDiagnosticAnalyzerService.cs
  src/LanguageServer/Protocol/Features/CodeFixes/CodeFixService.cs
  src/LanguageServer/Protocol/Features/CodeFixes/ICodeFixService.cs
  src/LanguageServer/Protocol/Features/Diagnostics/DiagnosticAnalyzerService.cs
  src/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs
  src/VisualStudio/Core/Test/Diagnostics/ExternalDiagnosticUpdateSourceTests.vb
Labels: Area-IDE, untriaged

#74173 On-the-fly-docs update naming
  src/EditorFeatures/Core.Wpf/QuickInfo/OnTheFlyDocsView.xaml.cs
  src/EditorFeatures/Core/EditorFeaturesResources.resx
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.cs.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.de.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.es.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.fr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.it.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ja.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ko.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pl.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pt-BR.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ru.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.tr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hans.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hant.xlf
Labels: Area-IDE, untriaged

#74160 EnumerableConditionalWeakTable and WeakEvent
  src/EditorFeatures/CSharpTest/Workspaces/WorkspaceTests_EditorFeatures.cs
  src/EditorFeatures/Core/Shared/Tagging/EventSources/TaggerEventSources.OptionChangedEventSource.cs
  src/EditorFeatures/Test/Options/GlobalOptionsTests.cs
  src/LanguageServer/Protocol/Features/Diagnostics/DiagnosticAnalyzerService.cs
  src/LanguageServer/Protocol/Handler/CodeLens/CodeLensRefreshQueue.cs
  src/LanguageServer/Protocol/Handler/InlayHint/InlayHintRefreshQueue.cs
  src/Tools/ExternalAccess/Razor/RazorGlobalOptions.cs
  src/VisualStudio/Core/Def/InheritanceMargin/InheritanceMarginViewMargin.cs
  src/VisualStudio/Core/Def/LanguageService/AbstractLanguageService`2.VsCodeWindowManager.cs
  src/VisualStudio/Core/Def/StackTraceExplorer/StackTraceExplorerCommandHandler.cs
  src/VisualStudio/Core/Def/SymbolSearch/AbstractDelayStartedService.cs
  src/VisualStudio/Core/Def/Telemetry/FileLogger.cs
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/OptionPages/ForceLowMemoryMode.cs
  src/Workspaces/Core/Portable/Options/GlobalOptionService.cs
  src/Workspaces/Core/Portable/Options/IGlobalOptionService.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.TextTracker.cs
  src/Workspaces/CoreTest/UtilityTest/WeakEventTests.cs
  src/Workspaces/CoreTest/WorkspaceServiceTests/GlobalOptionServiceTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/EnumerableConditionalWeakTable.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/EventHandlerFactory.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/WeakEvent`1.cs
Labels: Area-IDE, untriaged

#74202 Update insertion config
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#74038 Add fallback options to solution snapshot
  src/Compilers/Core/Portable/Collections/TemporaryArrayExtensions.cs
  src/Compilers/Core/Portable/Collections/TemporaryArray`1.cs
  src/Compilers/Core/Portable/Compilation/SyntaxTreeOptionsProvider.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs
  src/Compilers/Core/Portable/InternalUtilities/EnumerableExtensions.cs
  src/Compilers/Core/Portable/SourceGeneration/GeneratedCodeUtilities.cs
  src/EditorFeatures/Core/EditorConfigSettings/DataProvider/SettingsProviderBase.cs
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueLanguageServiceTests.cs
  src/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_IncrementalAnalyzer.cs
  src/LanguageServer/Protocol/Features/Options/ClientFallbackAnalyzerConfigOptionsProvider.cs
  src/LanguageServer/Protocol/Features/Options/SolutionAnalyzerConfigOptionsUpdater.cs
  src/LanguageServer/ProtocolUnitTests/Options/SolutionAnalyzerConfigOptionsUpdaterTests.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/AnalyzersCommandHandler.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/DiagnosticItem/BaseDiagnosticAndGeneratorItemSource.cs
  src/VisualStudio/Core/Test.Next/Remote/SnapshotSerializationTests.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/VisualStudio/Core/Test.Next/Services/SolutionServiceTests.cs
  src/Workspaces/Core/Portable/Remote/WellKnownSynchronizationKind.cs
  src/Workspaces/Core/Portable/Serialization/SerializationExtensions.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService.cs
  src/Workspaces/Core/Portable/Workspace/Host/EventListener/IWorkspaceEventListenerProvider.cs
  src/Workspaces/Core/Portable/Workspace/Host/IFallbackAnalyzerConfigOptionsProvider.cs
  src/Workspaces/Core/Portable/Workspace/Solution/AnalyzerConfigData.cs
  src/Workspaces/Core/Portable/Workspace/Solution/AssetPath.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState.AnalyzerConfigOptionsCache.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionInfo.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState_Checksum.cs
  src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
  src/Workspaces/CoreTest/EditorConfigStorageLocation/NamingStylePreferenceEditorConfigStorageLocationTests.cs
  src/Workspaces/CoreTest/Options/DocumentOptionSetTests.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
  src/Workspaces/CoreTest/UtilityTest/ImmutableDictionaryExtensionsTests.cs
  src/Workspaces/CoreTestUtilities/Fakes/MockFallbackAnalyzerConfigOptionsProvider.cs
  src/Workspaces/CoreTestUtilities/Fakes/MockWorkspaceEventListenerProvider.cs
  src/Workspaces/CoreTestUtilities/MEF/FeaturesTestCompositions.cs
  src/Workspaces/Remote/Core/AbstractAssetProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/AssetProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Diagnostics/StructuredAnalyzerConfigOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/DiagnosticDescriptorExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/SyntaxTreeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/CompilerUtilities/ImmutableDictionaryExtensions.cs
Labels: Area-IDE, untriaged

#74053 Ide options
  src/Analyzers/CSharp/Tests/ValidateFormatString/ValidateFormatStringTests.cs
  src/Analyzers/Core/Analyzers/AnalyzerOptionsProvider.cs
  src/Analyzers/Core/Analyzers/Analyzers.projitems
  src/Analyzers/Core/Analyzers/UseSystemHashCode/UseSystemHashCodeDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/ValidateFormatString/AbstractValidateFormatStringDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/ValidateFormatString/FormatStringValidationOptionStorage.cs
  src/Analyzers/VisualBasic/Tests/RemoveUnusedMembers/RemoveUnusedMembersTests.vb
  src/EditorFeatures/Core/EditorConfigSettings/Updater/NamingStyles/SourceTextExtensions.cs
  src/Features/CSharp/Portable/Options/CSharpEditorConfigOptionsEnumerator.cs
  src/Features/CSharpTest/EmbeddedLanguages/ValidateJsonStringTests.cs
  src/Features/CSharpTest/EmbeddedLanguages/ValidateRegexStringTests.cs
  src/Features/Core/Portable/EmbeddedLanguages/Json/LanguageServices/AbstractJsonDetectionAnalyzer.cs
  src/Features/Core/Portable/EmbeddedLanguages/Json/LanguageServices/AbstractJsonDiagnosticAnalyzer.cs
  src/Features/Core/Portable/EmbeddedLanguages/Json/LanguageServices/JsonDetectionOptionsStorage.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/AbstractRegexDiagnosticAnalyzer.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexOptionsStorage.cs
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/Features/Core/Portable/Options/EditorConfig/EditorConfigFileGenerator.cs
  src/Features/Core/Portable/Options/EditorConfig/EditorConfigOptionsEnumerator.cs
  src/Features/Core/Portable/Options/EditorConfig/EditorConfigOptionsEnumeratorAttribute.cs
  src/Features/Core/Portable/Options/EditorConfig/IEditorConfigOptionsEnumerator.cs
  src/Features/DiagnosticsTestUtilities/CodeActions/CodeFixVerifierHelper.cs
  src/Features/DiagnosticsTestUtilities/Diagnostics/AbstractDiagnosticProviderBasedUserDiagnosticTest_NoEditor.cs
  src/Features/VisualBasic/Portable/Options/VisualBasicEditorConfigOptionsEnumerator.vb
  src/Features/VisualBasicTest/EmbeddedLanguages/ValidateJsonStringTests.vb
  src/Features/VisualBasicTest/EmbeddedLanguages/ValidateRegexStringTests.vb
  src/LanguageServer/Protocol/Features/Options/IdeAnalyzerOptionsStorage.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
  src/VisualStudio/CSharp/Test/EditorConfigSettings/DataProvider/DataProviderTests.cs
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
  src/VisualStudio/Core/Test/Options/BasicEditorConfigGeneratorTests.vb
  src/VisualStudio/Core/Test/Options/CSharpEditorConfigGeneratorTests.vb
  src/VisualStudio/VisualBasic/Impl/Options/AdvancedOptionPageControl.xaml.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/CodeStyleOptions2.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Diagnostics/IdeAnalyzerOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/Serialization/NamingStylePreferencesEditorConfigSerializer.cs
Labels: Area-IDE, untriaged
