Repository dotnet/roslyn, pull requests merged in 2024-01, with the labels that each got.

#71445 Snap for 17.9 P3
  eng/Versions.props
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#71416 Don't start the cohost server at all if Razor doesn't want to
  src/EditorFeatures/Core/LanguageServer/AbstractInProcLanguageClient.cs
  src/Tools/ExternalAccess/Razor/Cohost/RazorCohostLanguageClient.cs
Labels: Area-IDE, untriaged

#71461 Collection expressions: handle spread iterator item with no conversion in IOperation
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged

#71471 Purge line commit information upon projection span reset
  src/EditorFeatures/VisualBasic/LineCommit/CommitBufferManager.vb
Labels: Area-IDE, untriaged

#71265 Standardize use of prepareMachine for ci cleanup
  azure-pipelines-compliance.yml
  azure-pipelines-official.yml
  azure-pipelines-pr-validation.yml
  eng/build.ps1
  eng/cibuild.sh
  eng/test-rebuild.ps1
Labels: Area-Infrastructure, Community, untriaged

#71473 Fix snippet change text
  src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs
  src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionResolveTests.cs
Labels: Area-IDE, untriaged

#71472 Cleanup code with patterns
  src/Analyzers/CSharp/Analyzers/QualifyMemberAccess/CSharpQualifyMemberAccessDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/Helpers.cs
  src/EditorFeatures/Core/Diagnostics/DiagnosticsSquiggleTaggerProvider.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CSharpInstructionDecoder.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/NamedParameterCompletionProvider.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/SnippetCompletionProvider.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.PostProcessor.cs
  src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs
  src/Features/Core/Portable/Completion/Providers/AbstractObjectCreationCompletionProvider.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EmbeddedLanguages/Json/JsonNodes.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/RegexParser.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Features/Core/Portable/GoToBase/FindBaseHelpers.cs
  src/Features/LanguageServer/Protocol/Protocol/Converters/TextDocumentSyncConverter.cs
  src/VisualStudio/Core/Def/Library/ObjectBrowser/AbstractDescriptionBuilder.cs
  src/VisualStudio/Core/Def/Library/ObjectBrowser/AbstractListItemFactory.cs
  src/VisualStudio/Core/Def/Progression/GraphNodeIdCreation.cs
  src/VisualStudio/Core/Impl/CodeModel/RootCodeModel.cs
  src/Workspaces/Core/Portable/Rename/SymbolicRenameLocations.ReferenceProcessing.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/SemanticsFactsService/AbstractSemanticFactsService.cs
Labels: Area-IDE, untriaged

#71389 PR feedback and cleanup after solution-state/compilation-state refactoring.
  src/EditorFeatures/Test2/Diagnostics/DiagnosticServiceTests.vb
  src/Features/CSharp/Portable/QuickInfo/CSharpDiagnosticAnalyzerQuickInfoProvider.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSession.cs
  src/Features/Core/Portable/ExternalAccess/UnitTesting/SolutionCrawler/UnitTestingWorkCoordinator.cs
  src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.cs
  src/Features/Core/Portable/Workspace/CompileTimeSolutionProvider.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/DefaultDiagnosticAnalyzerService.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.Executor.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.StateManager.HostStates.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.StateManager.ProjectStates.cs
  src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.StateManager.cs
  src/Features/LanguageServer/Protocol/Handler/Diagnostics/BuildOnlyDiagnosticIdsHandler.cs
  src/VisualStudio/Core/Def/Diagnostics/VisualStudioDiagnosticAnalyzerService.cs
  src/VisualStudio/Core/Def/TaskList/ExternalErrorDiagnosticUpdateSource.cs
  src/VisualStudio/Core/Impl/CodeModel/ProjectCodeModelFactory.cs
  src/Workspaces/Core/Portable/Remote/IRemoteKeepAliveService.cs
  src/Workspaces/Core/Portable/Remote/RemoteHostClient.cs
  src/Workspaces/Core/Portable/Remote/RemoteServiceConnection.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/ProjectKey.cs
  src/Workspaces/Core/Portable/Workspace/Host/PersistentStorage/SolutionKey.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Project.cs
  src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.CompilationAndGeneratorDriverTranslationAction.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.CompilationAndGeneratorDriverTranslationAction_Actions.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.CompilationTracker.CompilationPair.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.CompilationTracker.CompilationTrackerState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.CompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.CompilationTracker_Generators.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.GeneratedFileReplacingCompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.ICompilationTracker.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.SkeletonReferenceCache.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.SkeletonReferenceSet.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.SymbolToProjectId.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.UnrootedSymbolSet.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState_Checksum.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs
  src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentStates.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
  src/Workspaces/CoreTest/SolutionTests/ProjectDependencyGraphTests.cs
  src/Workspaces/Remote/Core/BrokeredServiceConnection.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.Scope.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs
Labels: Area-IDE, untriaged

#71479 Update to new version of NuGetAuthenticate task as v0 is being deprecated
  azure-pipelines-official.yml
  azure-pipelines-pr-validation.yml
Labels: Area-Infrastructure, untriaged

#67748 Run Spanish tests on CoreClr
  azure-pipelines.yml
  docs/contributing/Bootstrap Builds.md
  docs/contributing/Localization In Compiler Tests.md
  docs/contributing/README.md
  docs/contributing/Target Framework Strategy.md
  src/Compilers/CSharp/Test/CommandLine/LocalizationInfraTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAwaitForeachTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenForEachTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenIncrementTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOperators.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/EmitMetadataTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/LocalStateTracing/LocalStateTracingTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternSwitchTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
  src/Compilers/CSharp/Test/Symbol/Compilation/CompilationAPITests.cs
  src/Compilers/Test/Core/FX/CappedStringWriter.cs
  src/Compilers/Test/Core/TestBase.cs
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenConstLocal.vb
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenRefReturnTests.vb
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTests.vb
Labels: Area-Infrastructure, untriaged

#71444 Upgrade BCL assembly to 8.0.0
  eng/Version.Details.xml
  eng/Versions.props
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenReadOnlySpanConstructionTest.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTryFinally.cs
  src/Compilers/Core/CodeAnalysisTest/Analyzers/AnalyzerFileReferenceAppDomainTests.cs
Labels: Area-Infrastructure, untriaged

#71482 Disable 'use collection expression' when it would introduce an allocation
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForArrayDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForBuilderDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForCreateDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForEmptyDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForFluentDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForStackAllocDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/UseCollectionExpressionHelpers.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionInitializer/CSharpUseCollectionInitializerDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForEmptyTests.cs
Labels: Area-IDE, untriaged

#71454 Respect line directives in SARIF logger
  src/Compilers/CSharp/Test/CommandLine/SarifV2ErrorLoggerTests.cs
  src/Compilers/Core/Portable/CommandLine/SarifV1ErrorLogger.cs
  src/Compilers/Core/Portable/CommandLine/SarifV2ErrorLogger.cs
Labels: Area-Compilers, untriaged

#71489 Fix accessibility checks when getting completion lists in patterns
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs
Labels: Area-IDE, untriaged

#71415 Change MapCode protocol to match it's form in VS
  src/EditorFeatures/Core/LanguageServer/RazorInProcLanguageClient.cs
  src/Features/LanguageServer/Protocol/Handler/MapCode/MapCodeHandler.cs
  src/Features/LanguageServer/Protocol/Handler/MapCode/MapCodeParams.cs
  src/Features/LanguageServer/Protocol/Protocol/Internal/VSInternalMapCodeMapping.cs
  src/Features/LanguageServer/Protocol/Protocol/Internal/VSInternalMapCodeParams.cs
  src/Features/LanguageServer/Protocol/Protocol/Internal/VSInternalMethods.cs
  src/Features/LanguageServer/Protocol/Protocol/Internal/VSInternalServerCapabilities.cs
  src/Features/LanguageServer/ProtocolUnitTests/MapCode/MapCodeTests.cs
Labels: Area-IDE, untriaged

#71478 [Inline Rename] Cosmetic improvements to Rename Suggestions
  src/EditorFeatures/Core.Wpf/EditorFeaturesWpfResources.resx
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameUserInputComboBox.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameUserInputComboBox.xaml.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameViewModel.cs
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.cs.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.de.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.es.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.fr.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.it.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ja.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ko.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.pl.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.pt-BR.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ru.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.tr.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.zh-Hans.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.zh-Hant.xlf
Labels: Area-IDE, Community, untriaged

#68214 Lazily calculate preview operations
  src/EditorFeatures/CSharpTest/CodeActions/PreviewExceptionTests.cs
  src/EditorFeatures/CSharpTest/CodeActions/PreviewTests.cs
  src/EditorFeatures/Core.Wpf/Suggestions/PreviewChanges/PreviewChangesCodeAction.cs
  src/EditorFeatures/Core.Wpf/Suggestions/PreviewChanges/PreviewChangesSuggestedAction.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionWithNestedFlavors.cs
  src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActions/SuggestedAction.cs
  src/EditorFeatures/VisualBasicTest/CodeActions/Preview/PreviewTests.vb
  src/Features/Core/Portable/CodeFixes/Configuration/ConfigurationUpdater.cs
Labels: Area-IDE, untriaged

#71495 [Port][Inline Rename] Cosmetic improvements to Rename Suggestions (#71478)
  src/EditorFeatures/Core.Wpf/EditorFeaturesWpfResources.resx
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameUserInputComboBox.xaml
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameUserInputComboBox.xaml.cs
  src/EditorFeatures/Core.Wpf/InlineRename/UI/SmartRename/SmartRenameViewModel.cs
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.cs.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.de.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.es.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.fr.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.it.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ja.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ko.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.pl.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.pt-BR.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.ru.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.tr.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.zh-Hans.xlf
  src/EditorFeatures/Core.Wpf/xlf/EditorFeaturesWpfResources.zh-Hant.xlf
Labels: Area-IDE, untriaged

#71501 Do not offer to make a member readonly if it potentially writes into an inline-array field.
  src/Analyzers/CSharp/Analyzers/MakeStructMemberReadOnly/CSharpMakeStructMemberReadOnlyAnalyzer.cs
  src/Analyzers/CSharp/Tests/MakeStructMemberReadOnly/MakeStructMemberReadOnlyTests.cs
Labels: Area-IDE, untriaged

#71503 Fix sorting of global aliases
  src/Workspaces/CSharpTest/OrganizeImports/OrganizeUsingsTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/UsingsAndExternAliasesDirectiveComparer.cs
Labels: Area-IDE, untriaged

#71514 Fix remove-unnecessary-cast with collection expressions.
  src/Analyzers/CSharp/Tests/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Simplification/Simplifiers/CastSimplifier.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ITypeSymbolExtensions.cs
Labels: Area-IDE, untriaged

#71334 Add handling of params collections for natural delegate types
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeField.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeManager.Templates.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/AnonymousTypeManager.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/PublicSymbols/AnonymousType.DelegatePublicSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/AnonymousTypes/SynthesizedSymbols/AnonymousType.DelegateTemplateSymbol.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/ParamsCollectionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs
Labels: Area-Compilers, untriaged, New Feature - ParamsCollections

#71496 Fix semantic model for target typed collection expression elements
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged

#71392 Remove WPF dependencies from Workspace and Features test layers
  src/EditorFeatures/TestUtilities/EditorTestCompositions.cs
  src/EditorFeatures/TestUtilities/Microsoft.CodeAnalysis.EditorFeatures.Test.Utilities.csproj
  src/EditorFeatures/TestUtilities/Threading/TaskJoinExtensions.cs
  src/EditorFeatures/TestUtilities/Threading/WpfDispatcherTaskJoiner.cs
  src/Features/CSharpTest/AddAwait/AddAwaitTests.cs
  src/Features/CSharpTest/Microsoft.CodeAnalysis.CSharp.Features.UnitTests.csproj
  src/Features/Test/Microsoft.CodeAnalysis.Features.UnitTests.csproj
  src/Features/TestUtilities/Microsoft.CodeAnalysis.Features.Test.Utilities.csproj
  src/Features/VisualBasicTest/Microsoft.CodeAnalysis.VisualBasic.Features.UnitTests.vbproj
  src/Workspaces/CoreTestUtilities/MEF/IDispatcherTaskJoiner.cs
  src/Workspaces/CoreTestUtilities/MEF/UseExportProviderAttribute.cs
  src/Workspaces/CoreTestUtilities/Microsoft.CodeAnalysis.Workspaces.Test.Utilities.csproj
  src/Workspaces/CoreTestUtilities/TestExportJoinableTaskContext.cs
Labels: Area-IDE, untriaged

#71492 Collection expressions: report specific error (if any) for explicit cast failure
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged

#71537 Update publishdata.json for VS snap
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#63472 IDE0220 (foreach cast): Consider T of IEnumerable<T> for weakly-typed GetEnumerator
  src/Analyzers/CSharp/Tests/ForEachCast/ForEachCastTests.cs
  src/Analyzers/Core/Analyzers/ForEachCast/AbstractForEachCastDiagnosticAnalyzer.cs
Labels: Area-IDE, Community

#71517 Remove unnecessary WpfFact usage
  src/Analyzers/CSharp/Tests/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs
  src/Analyzers/CSharp/Tests/UseImplicitOrExplicitType/UseExplicitTypeTests.cs
  src/Analyzers/CSharp/Tests/UseImplicitOrExplicitType/UseImplicitTypeTests.cs
  src/Analyzers/VisualBasic/Tests/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.vb
  src/Features/CSharpTest/CodeActions/ApplyChangesOperationTests.cs
  src/Features/CSharpTest/GenerateMethod/GenerateMethodTests.cs
  src/Features/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs
  src/Features/CSharpTest/IntroduceVariable/IntroduceVariableTests.cs
  src/Features/CSharpTest/InvertIf/InvertIfTests.cs
  src/Features/CSharpTest/MoveType/MoveTypeTests.ActionCountTests.cs
  src/Features/CSharpTest/MoveType/MoveTypeTests.MoveScope.cs
  src/Features/CSharpTest/MoveType/MoveTypeTests.RenameFile.cs
  src/Features/CSharpTest/MoveType/MoveTypeTests.RenameType.cs
  src/Features/CSharpTest/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests_AsTests.cs
  src/Features/CSharpTest/SyncNamespace/SyncNamespaceTests_ChangeNamespace.cs
  src/Features/CSharpTest/SyncNamespace/SyncNamespaceTests_MoveFile.cs
  src/Features/CSharpTest/SyncNamespace/SyncNamespaceTests_NoAction.cs
  src/Features/VisualBasicTest/EncapsulateField/EncapsulateFieldTests.vb
  src/Features/VisualBasicTest/GenerateVariable/GenerateVariableTests.vb
  src/Features/VisualBasicTest/ImplementInterface/ImplementInterfaceTests.vb
  src/Features/VisualBasicTest/InlineTemporary/InlineTemporaryTests.vb
  src/Features/VisualBasicTest/IntroduceVariable/IntroduceVariableTests.vb
  src/Features/VisualBasicTest/InvertIf/InvertMultiLineIfTests.vb
  src/Features/VisualBasicTest/InvertIf/InvertSingleLineIfTests.vb
Labels: Area-IDE, untriaged

#71246 Semantic snippets: fix inline statement snippets in a "qualified name" edge case
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/AbstractCSharpConditionalBlockSnippetCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpForEachSnippetCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpForSnippetCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpForrSnippetCompletionProviderTests.cs
  src/Features/CSharp/Portable/Snippets/AbstractCSharpForLoopSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpForEachLoopSnippetProvider.cs
  src/Features/Core/Portable/Snippets/InlineExpressionInfo.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractIfSnippetProvider.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractInlineStatementSnippetProvider.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractWhileLoopSnippetProvider.cs
Labels: Area-IDE, Community, untriaged

#71536 Improve Complete Statement behavior inside collection initializers and strings
  src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs
  src/EditorFeatures/CSharpTest/AutomaticCompletion/AutomaticLineEnderTests.cs
  src/EditorFeatures/CSharpTest/CompleteStatement/CSharpCompleteStatementCommandHandlerTests.cs
Labels: Area-IDE, untriaged

#71158 Collection expressions: tests for spreads of dynamic and non-generic IEnumerable collections
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged, New Feature - Collection Expressions

#71528 Fix issue where we were not offering 'use collection expression' in a nullable scenario.
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs
  src/EditorFeatures/Test/Utilities/SymbolEquivalenceComparerTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/AbstractSpeculationAnalyzer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/SymbolEquivalenceComparer.EquivalenceVisitor.cs
Labels: Area-IDE, untriaged

#71366 Add error logging to RequestContext
  src/Features/LanguageServer/Protocol/Handler/RequestContext.cs
Labels: Area-IDE, untriaged

#71423 Params Collections: misc chanages
  src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_InterpolatedString.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversions.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/ParamsCollectionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs
Labels: Area-Compilers, untriaged, New Feature - ParamsCollections

#71534 Support generic attributes in Attribute suffix simplification
  src/Features/CSharp/Portable/Diagnostics/Analyzers/TypeSyntaxSimplifierWalker.cs
  src/Features/CSharpTest/SimplifyTypeNames/SimplifyTypeNamesTests.cs
  src/Workspaces/CSharp/Portable/Simplification/Simplifiers/NameSimplifier.cs
Labels: Area-IDE, Community, untriaged

#71541 Fix unwrapping of null synchronization context during xunit test execution
  src/Workspaces/CoreTestUtilities/TestExportJoinableTaskContext.cs
Labels: Area-IDE, untriaged

#71385 Use IHotReloadLogger service to log message whenever EnC is disabled
  eng/Versions.props
  src/EditorFeatures/Core/EditAndContinue/Contracts/HotReloadLoggerProxy.cs
  src/EditorFeatures/Core/EditAndContinue/EditAndContinueLanguageService.cs
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/EditorFeatures/Test/EditAndContinue/Helpers/MockHotReloadLogger.cs
  src/EditorFeatures/Test/EditAndContinue/Helpers/MockServiceBroker.cs
  src/EditorFeatures/Test/EditAndContinue/Helpers/MockServiceBrokerProvider.cs
  src/Workspaces/Remote/Core/BrokeredServiceDescriptors.cs
  src/Workspaces/Remote/Core/Microsoft.CodeAnalysis.Remote.Workspaces.csproj
Labels: Area-Interactive, untriaged

#71443 Improve parsing performance with large collection expressions of numbers
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/CollectionExpressionParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ParsingErrorRecoveryTests.cs
Labels: Area-Compilers, untriaged

#71520 Remove string.Split calls during solution explorer search
  src/VisualStudio/Core/Impl/SolutionExplorer/DiagnosticItem/CpsDiagnosticItemSourceProvider.cs
Labels: Area-IDE, untriaged

#71549 Properly layer feature level code action tests
  Roslyn.sln
  src/CodeStyle/Core/Tests/Microsoft.CodeAnalysis.CodeStyle.UnitTestUtilities.csproj
  src/EditorFeatures/DiagnosticsTestUtilities/Microsoft.CodeAnalysis.EditorFeatures.DiagnosticsTests.Utilities.csproj
  src/Features/DiagnosticsTestUtilities/CodeActions/AnalyzerProperty.cs
  src/Features/DiagnosticsTestUtilities/CodeActions/CSharpCodeFixVerifier`2+Test.cs
  src/Features/DiagnosticsTestUtilities/CodeActions/CSharpCodeFixVerifier`2.cs
  src/Features/DiagnosticsTestUtilities/CodeActions/CSharpCodeRefactoringVerifier`1+Test.cs
  src/Features/DiagnosticsTestUtilities/CodeActions/CSharpCodeRefactoringVerifier`1.cs
  src/Features/DiagnosticsTestUtilities/CodeActions/CSharpVerifierHelper.cs
  src/Features/DiagnosticsTestUtilities/CodeActions/CodeFixVerifierHelper.cs
  src/Features/DiagnosticsTestUtilities/CodeActions/SharedVerifierState.cs
  src/Features/DiagnosticsTestUtilities/CodeActions/VisualBasicCodeFixVerifier`2+Test.cs
  src/Features/DiagnosticsTestUtilities/CodeActions/VisualBasicCodeFixVerifier`2.cs
  src/Features/DiagnosticsTestUtilities/CodeActions/VisualBasicCodeRefactoringVerifier`1+Test.cs
  src/Features/DiagnosticsTestUtilities/CodeActions/VisualBasicCodeRefactoringVerifier`1.cs
  src/Features/DiagnosticsTestUtilities/Microsoft.CodeAnalysis.Features.DiagnosticsTests.Utilities.csproj
  src/Workspaces/CoreTestUtilities/Microsoft.CodeAnalysis.Workspaces.Test.Utilities.csproj
Labels: Area-IDE, untriaged

#71397 Collection expressions: use iteration type for convertibility of element types
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/CollectionExpressionTypeKind.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversion.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, New Feature - Collection Expressions

#71551 Move tests back down to feature layer
  src/Features/CSharpTest/AddDebuggerDisplay/AddDebuggerDisplayTests.cs
  src/Features/CSharpTest/ConvertCast/ConvertDirectCastToTryCastTests.cs
  src/Features/CSharpTest/ConvertCast/ConvertTryCastToDirectCastTests.cs
  src/Features/CSharpTest/ConvertIfToSwitch/ConvertIfToSwitchTests.cs
  src/Features/CSharpTest/ConvertNamespace/ConvertNamespaceRefactoringTests.cs
  src/Features/CSharpTest/ConvertPrimaryToRegularConstructor/ConvertPrimaryToRegularConstructorTests.cs
  src/Features/CSharpTest/ConvertProgram/ConvertToProgramMainAnalyzerTests.cs
  src/Features/CSharpTest/ConvertProgram/ConvertToProgramMainRefactoringTests.cs
  src/Features/CSharpTest/ConvertProgram/ConvertToTopLevelStatementsAnalyzerTests.cs
  src/Features/CSharpTest/ConvertProgram/ConvertToTopLevelStatementsRefactoringTests.cs
  src/Features/CSharpTest/ConvertToInterpolatedString/ConvertConcatenationToInterpolatedStringTests.cs
  src/Features/CSharpTest/ConvertToRawString/ConvertInterpolatedStringToRawStringTests.cs
  src/Features/CSharpTest/ConvertToRawString/ConvertRegularStringToRawStringTests.cs
  src/Features/CSharpTest/ConvertTupleToStruct/ConvertTupleToStructTests.cs
  src/Features/CSharpTest/EmbeddedLanguages/JsonStringDetectorTests.cs
  src/Features/CSharpTest/EnableNullable/EnableNullableTests.cs
  src/Features/CSharpTest/GenerateComparisonOperators/GenerateComparisonOperatorsTests.cs
  src/Features/CSharpTest/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersTests.cs
  src/Features/CSharpTest/GenerateFromMembers/AddConstructorParametersFromMembers/AddConstructorParametersFromMembersTests.cs
  src/Features/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs
  src/Features/CSharpTest/ImplementInterface/ImplementInterfaceTests_FixAllTests.cs
  src/Features/CSharpTest/InitializeParameter/AddParameterCheckTests.cs
  src/Features/CSharpTest/MoveStaticMembers/CSharpMoveStaticMembersTests.cs
  src/Features/CSharpTest/ReplaceConditionalWithStatements/ReplaceConditionalWithStatementsTests.cs
  src/Features/CSharpTest/SimplifyPropertyPattern/SimplifyPropertyPatternTests.cs
  src/Features/CSharpTest/UseNamedArguments/UseNamedArgumentsTests.cs
  src/Features/CSharpTest/UseNameofInAttribute/UseNameofInAttributeTests.cs
  src/Features/CSharpTest/UseRecursivePatterns/UseRecursivePatternsRefactoringTests.cs
  src/Features/VisualBasicTest/AddConstructorParametersFromMembers/AddConstructorParametersFromMembersTests.vb
  src/Features/VisualBasicTest/AddDebuggerDisplay/AddDebuggerDisplayTests.vb
  src/Features/VisualBasicTest/ConvertCast/ConvertDirectCastToTryCastTests.vb
  src/Features/VisualBasicTest/ConvertCast/ConvertTryCastToDirectCastTests.vb
  src/Features/VisualBasicTest/ConvertToInterpolatedString/ConvertConcatenationToInterpolatedStringTests.vb
  src/Features/VisualBasicTest/ConvertTupleToStruct/ConvertTupleToStructTests.vb
  src/Features/VisualBasicTest/IntroduceParameter/IntroduceParameterTests.vb
  src/Features/VisualBasicTest/MoveStaticMembers/VisualBasicMoveStaticMembersTests.vb
  src/Features/VisualBasicTest/OverloadBase/OverloadBaseTests.vb
  src/Features/VisualBasicTest/RemoveSharedFromModuleMembers/RemoveSharedFromModuleMembersTests.vb
  src/Features/VisualBasicTest/ReplaceConditionalWithStatements/ReplaceConditionalWithStatementsTests.vb
Labels: Area-IDE, untriaged

#71552 Remove test construction dependencies on workspace
  src/EditorFeatures/CSharpTest/AddMissingImports/CSharpAddMissingImportsRefactoringProviderTests.cs
  src/EditorFeatures/CSharpTest/CodeActions/InlineMethod/CSharpInlineMethodTests_CrossLanguage.cs
  src/EditorFeatures/VisualBasicTest/AddMissingImports/VisualBasicAddMissingImportsRefactoringProviderTests.vb
  src/EditorFeatures/VisualBasicTest/CodeActions/InlineMethod/VisualBasicInlineMethodTests_CrossLanguage.vb
  src/Features/CSharp/Portable/CodeRefactorings/AddMissingImports/CSharpAddMissingImportsRefactoringProvider.cs
  src/Features/CSharp/Portable/CodeRefactorings/InlineMethod/CSharpInlineMethodRefactoringProvider.cs
  src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsRefactoringProvider.cs
  src/Features/VisualBasic/Portable/CodeRefactorings/AddMissingImports/VisualBasicAddMissingImportsRefactoringProvider.vb
  src/Features/VisualBasic/Portable/CodeRefactorings/InlineMethod/VisualBasicInlineMethodRefactoringProvider.vb
Labels: Area-IDE, untriaged

#71558 Enable some dynamic collection expression tests which were disabled during merge from 'main'.
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged, New Feature - Collection Expressions, New Feature - ParamsCollections

#71214 Collection expressions: method type re-inference
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged

#68069 Optimize nullable value type constant comparison codegen
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperator.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOptimizedNullableOperators.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenStructsAndEnum.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleEqualityTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs
Labels: Area-Compilers, Code Gen Quality, untriaged

#71556 Simplify how RunTests handles TFMs
  .vscode/launch.json
  eng/build.ps1
  eng/build.sh
  src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/InternalsVisibleToAndStrongNameTests.cs
  src/Compilers/Core/MSBuildTaskTests/CscTests.cs
  src/Compilers/VisualBasic/Portable/Emit/PEModuleBuilder.vb
  src/Tools/Source/RunTests/Options.cs
  src/Tools/Source/RunTests/Program.cs
Labels: Area-Infrastructure, untriaged

#71261 Use runtime helper `CreateSpan` for `stackalloc` of non-byte arrays
  src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs
  src/Compilers/CSharp/Portable/CodeGen/EmitStackAllocInitializer.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenStackAllocInitializerTests.cs
  src/Compilers/Core/Portable/CodeGen/ILBuilderEmit.cs
Labels: Area-Compilers, Code Gen Quality, untriaged

#71572 Add a test for 'Params Collections.'
  src/Compilers/CSharp/Test/Emit2/Semantics/ParamsCollectionTests.cs
Labels: Area-Compilers, untriaged, New Feature - ParamsCollections

#71564 Fork diag/code-action tests to ones without editor dep. 7/N
  Roslyn.sln
  src/Compilers/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.csproj
  src/Compilers/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.vbproj
  src/EditorFeatures/VisualBasicTest/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.UnitTests.vbproj
  src/Features/CSharpTest/Diagnostics/Configuration/ConfigureCodeStyle/BooleanCodeStyleOptionConfigurationTests.cs
  src/Features/CSharpTest/Diagnostics/Configuration/ConfigureCodeStyle/EnumCodeStyleOptionConfigurationTests.cs
  src/Features/CSharpTest/Diagnostics/Configuration/ConfigureCodeStyle/MultipleCodeStyleOptionConfigurationTests.cs
  src/Features/CSharpTest/Diagnostics/Configuration/ConfigureSeverity/AllAnalyzersSeverityConfigurationTests.cs
  src/Features/CSharpTest/Diagnostics/Configuration/ConfigureSeverity/CSharpCodeStyleOptionBasedSeverityConfigurationTests.cs
  src/Features/CSharpTest/Diagnostics/Configuration/ConfigureSeverity/CategoryBasedSeverityConfigurationTests.cs
  src/Features/CSharpTest/Diagnostics/Configuration/ConfigureSeverity/CodeStyleOptionBasedSeverityConfigurationTests.cs
  src/Features/CSharpTest/Diagnostics/Configuration/ConfigureSeverity/DotNetDiagnosticSeverityBasedSeverityConfigurationTests.cs
  src/Features/CSharpTest/Diagnostics/Configuration/ConfigureSeverity/MultipleCodeStyleOptionBasedSeverityConfigurationTests.cs
  src/Features/CSharpTest/Diagnostics/Configuration/ConfigureSeverity/VarForBuiltInTypesSeverityConfigurationTests.cs
  src/Features/CSharpTest/Diagnostics/Suppression/RemoveSuppressionTests.cs
  src/Features/CSharpTest/Diagnostics/Suppression/RemoveUnnecessaryPragmaSuppressionsTests.cs
  src/Features/CSharpTest/Diagnostics/Suppression/SuppressionAllCodeTests.cs
  src/Features/CSharpTest/Diagnostics/Suppression/SuppressionTest_FixAllTests.cs
  src/Features/CSharpTest/Diagnostics/Suppression/SuppressionTest_FixMultipleTests.cs
  src/Features/CSharpTest/Diagnostics/Suppression/SuppressionTests.cs
  src/Features/DiagnosticsTestUtilities/Diagnostics/AbstractSuppressionAllCodeTests.cs
  src/Features/DiagnosticsTestUtilities/Diagnostics/AbstractSuppressionDiagnosticTest_NoEditor.cs
  src/Features/DiagnosticsTestUtilities/Diagnostics/AbstractUnncessarySuppressionDiagnosticTest.cs
  src/Features/VisualBasicTest/Diagnostics/Configuration/ConfigureCodeStyle/BooleanCodeStyleOptionConfigurationTests.vb
  src/Features/VisualBasicTest/Diagnostics/Configuration/ConfigureSeverity/CodeStyleOptionBasedSeverityConfigurationTests.vb
  src/Features/VisualBasicTest/Diagnostics/Configuration/ConfigureSeverity/DotNetDiagnosticSeverityBasedSeverityConfigurationTests.vb
  src/Features/VisualBasicTest/Diagnostics/Configuration/ConfigureSeverity/MultipleCodeStyleOptionBasedConfigureSeverityTests.vb
  src/Features/VisualBasicTest/Diagnostics/Suppression/RemoveUnnecessaryPragmaSuppressionsTests.vb
  src/Features/VisualBasicTest/Diagnostics/Suppression/SuppressionAllCodeTests.vb
  src/Features/VisualBasicTest/Diagnostics/Suppression/SuppressionTests.vb
Labels: Area-IDE, untriaged

#71289 Speed up integration test build by only building required dependencies
  Roslyn.sln
  eng/pipelines/test-integration-helix.yml
  global.json
  src/Tools/BuildBoss/ProjectCheckerUtil.cs
  src/Tools/BuildBoss/ProjectUtil.cs
  src/VisualStudio/IntegrationTest/IntegrationTestBuildProject.csproj
Labels: Area-Infrastructure, untriaged

#71586 Correct change detection when projects not supporting EnC are added/removed
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
Labels: Area-Interactive, untriaged

#71480 Don't hard select promoted default item if there's filter text
  src/EditorFeatures/Core/IntelliSense/AsyncCompletion/ItemManager.CompletionListUpdater.cs
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_DefaultsSource.vb
Labels: Area-IDE, untriaged

#71574 Collection expressions: require [CollectionBuilder] target iteration type from GetEnumerator instance method
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/ForeachTest.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged

#71585 Small bits of project file cleanup.
  src/CodeStyle/CSharp/Analyzers/Microsoft.CodeAnalysis.CSharp.CodeStyle.csproj
  src/CodeStyle/CSharp/Tests/Microsoft.CodeAnalysis.CSharp.CodeStyle.UnitTests.csproj
  src/CodeStyle/Core/Analyzers/Microsoft.CodeAnalysis.CodeStyle.csproj
  src/CodeStyle/Core/CodeFixes/Microsoft.CodeAnalysis.CodeStyle.Fixes.csproj
  src/CodeStyle/VisualBasic/Analyzers/Microsoft.CodeAnalysis.VisualBasic.CodeStyle.vbproj
  src/CodeStyle/VisualBasic/Tests/Microsoft.CodeAnalysis.VisualBasic.CodeStyle.UnitTests.vbproj
  src/EditorFeatures/CSharp/Microsoft.CodeAnalysis.CSharp.EditorFeatures.csproj
  src/EditorFeatures/CSharpTest/Microsoft.CodeAnalysis.CSharp.EditorFeatures.UnitTests.csproj
  src/EditorFeatures/CSharpTest2/Microsoft.CodeAnalysis.CSharp.EditorFeatures2.UnitTests.csproj
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/EditorFeatures/TestUtilities/Microsoft.CodeAnalysis.EditorFeatures.Test.Utilities.csproj
  src/EditorFeatures/TestUtilities2/Microsoft.CodeAnalysis.EditorFeatures.Test.Utilities2.vbproj
  src/EditorFeatures/VisualBasic/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.vbproj
  src/EditorFeatures/VisualBasicTest/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.UnitTests.vbproj
  src/Features/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.Features.csproj
  src/Features/CSharpTest/Microsoft.CodeAnalysis.CSharp.Features.UnitTests.csproj
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/Features/DiagnosticsTestUtilities/Microsoft.CodeAnalysis.Features.DiagnosticsTests.Utilities.csproj
  src/Features/Test/Microsoft.CodeAnalysis.Features.UnitTests.csproj
  src/Features/TestUtilities/Microsoft.CodeAnalysis.Features.Test.Utilities.csproj
  src/Features/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.Features.vbproj
  src/Features/VisualBasicTest/Microsoft.CodeAnalysis.VisualBasic.Features.UnitTests.vbproj
Labels: Area-IDE, untriaged

#71587 Remove properties from DocumentSpan
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/IVSTypeScriptFindUsagesContext.cs
  src/EditorFeatures/Test2/Classification/ClassificationTests.vb
  src/Features/Core/Portable/ClassifiedSpansAndHighlightSpanFactory.cs
  src/Features/Core/Portable/DocumentSpan.cs
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/Api/VSTypeScriptDefinitionItemBase.cs
  src/Features/Core/Portable/FindUsages/AbstractFindUsagesService.ProgressAdapter.cs
  src/Features/Core/Portable/FindUsages/DefinitionItem.DefaultDefinitionItem.cs
  src/Features/Core/Portable/FindUsages/DefinitionItem.DetachedDefinitionItem.cs
  src/Features/Core/Portable/FindUsages/DefinitionItem.cs
  src/Features/Core/Portable/FindUsages/IDefinitionsAndReferencesFactory.cs
  src/Features/Core/Portable/FindUsages/IRemoteFindUsagesService.cs
  src/Features/Core/Portable/FindUsages/SourceReferenceItem.cs
  src/Features/Core/Portable/InheritanceMargin/AbstractInheritanceMarginService_Helpers.cs
  src/Features/LanguageServer/Protocol/Handler/References/FindUsagesLSPContext.cs
  src/Tools/ExternalAccess/FSharp/FSharpDocumentSpan.cs
  src/Tools/ExternalAccess/FSharp/FindUsages/FSharpDefinitionItem.cs
  src/Tools/ExternalAccess/FSharp/FindUsages/FSharpSourceReferenceItem.cs
  src/VisualStudio/Core/Def/FindReferences/Contexts/AbstractTableDataSourceFindUsagesContext.cs
  src/VisualStudio/Core/Def/FindReferences/Contexts/WithReferencesFindUsagesContext.cs
  src/VisualStudio/Core/Def/FindReferences/Contexts/WithoutReferencesFindUsagesContext.cs
  src/VisualStudio/Core/Def/FindReferences/VisualStudioDefinitionsAndReferencesFactory.cs
  src/VisualStudio/Core/Def/ValueTracking/ValueTrackedTreeItemViewModel.cs
Labels: Area-IDE, untriaged

#71566 Fix ref field load in assignment
  src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenRefLocalTests.cs
Labels: Area-Compilers, untriaged, New Language Feature - Ref Fields

#71579 Remove `ExternalAccess.RazorCompiler`
  .github/CODEOWNERS
  Compilers.slnf
  Roslyn.sln
  eng/config/PublishData.json
  src/Compilers/CSharp/csc/CscCommandLine.projitems
  src/Compilers/Core/CodeAnalysisTest/AnalyzerAssemblyLoaderTests.cs
  src/Compilers/Core/CodeAnalysisTest/Microsoft.CodeAnalysis.UnitTests.csproj
  src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj
  src/Compilers/Server/VBCSCompiler/VBCSCompilerCommandLine.projitems
  src/Compilers/Test/Core/Microsoft.CodeAnalysis.Test.Utilities.csproj
  src/Compilers/Test/Utilities/CSharp/Microsoft.CodeAnalysis.CSharp.Test.Utilities.csproj
  src/Compilers/VisualBasic/vbc/VbcCommandLine.projitems
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Microsoft.CodeAnalysis.LanguageServer.csproj
  src/Features/Lsif/Generator/Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.csproj
  src/NuGet/Microsoft.Net.Compilers.Toolset/CoreClrCompilerArtifacts.targets
  src/NuGet/Microsoft.Net.Compilers.Toolset/DesktopCompilerArtifacts.targets
  src/NuGet/VisualStudio/VS.Tools.Roslyn.Package.csproj
  src/Tools/ExternalAccess/RazorCompiler/GeneratorExtensions.cs
  src/Tools/ExternalAccess/RazorCompiler/HostOutputNode.cs
  src/Tools/ExternalAccess/RazorCompiler/InternalAPI.Shipped.txt
  src/Tools/ExternalAccess/RazorCompiler/InternalAPI.Unshipped.txt
  src/Tools/ExternalAccess/RazorCompiler/Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.csproj
  src/Tools/ExternalAccess/RazorCompiler/PublicAPI.Shipped.txt
  src/Tools/ExternalAccess/RazorCompiler/PublicAPI.Unshipped.txt
  src/Tools/ExternalAccess/RazorCompilerTest/HostOutputsTests.cs
  src/Tools/ExternalAccess/RazorCompilerTest/Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.UnitTests.csproj
  src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj
  src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj
  src/Workspaces/Remote/ServiceHub/Microsoft.CodeAnalysis.Remote.ServiceHub.csproj
Labels: Area-Infrastructure, untriaged

#71609 Fix build
  azure-pipelines-official.yml
  azure-pipelines-pr-validation.yml
Labels: Area-Infrastructure, untriaged

#71598 Params Collections: Add a bunch of PROTOTYPE comments and a couple of VB tests.
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversions.cs
  src/Compilers/CSharp/Portable/Binder/UsingStatementBinder.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_UsingStatement.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Members.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/CustomModifierUtils.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ExplicitInterfaceHelpers.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceConstructorSymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceParameterSymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs
  src/Compilers/VisualBasic/Portable/Binding/Binder_Delegates.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Invocation.vb
  src/Compilers/VisualBasic/Portable/Binding/Binder_Query.vb
  src/Compilers/VisualBasic/Portable/Semantics/OverloadResolution.vb
  src/Compilers/VisualBasic/Portable/Semantics/TypeInference/TypeArgumentInference.vb
  src/Compilers/VisualBasic/Portable/SymbolDisplay/SymbolDisplayVisitor.Members.vb
  src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEMethodSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/MethodSignatureComparer.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMethodSymbol.vb
  src/Compilers/VisualBasic/Portable/Symbols/Source/SourcePropertySymbol.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/ParamsCollectionTests.vb
Labels: Area-Compilers, untriaged, New Feature - ParamsCollections

#71576 Update MSBuild.StructuredLogger
  eng/Versions.props
Labels: Area-Infrastructure, Community, untriaged

#71615 Ignore the exception from IntraTextAdornmentTagger
  src/VisualStudio/IntegrationTest/TestSetup/TestExtensionErrorHandler.cs
Labels: Area-Infrastructure, untriaged

#71612 Revert "Merge pull request #71412 from vibeeshan025/main"
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs
Labels: Area-IDE, untriaged

#71544 Update ILVerify bits
  eng/Versions.props
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncSpillTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAwaitForeachTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenClosureLambdaTests.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenReadOnlySpanConstructionTest.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenStructsAndEnum.cs
  src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs
  src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenMethodGroupConversionCachingTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PatternMatchingTests_ListPatterns.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/RefReadonlyParameterTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/BetterCandidates.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/NativeIntegerTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OverloadResolutionTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/Utf8StringsLiteralsTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/ExtensionMethodTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs
  src/Compilers/Core/Portable/CodeGen/PrivateImplementationDetails.cs
  src/Compilers/Test/Core/CommonTestBase.cs
  src/Compilers/Test/Core/CompilationVerifier.cs
  src/Compilers/Test/Core/Platform/Desktop/DesktopRuntimeEnvironment.cs
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenAsyncTests.vb
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenDelegateCreation.vb
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenForeach.vb
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenNullable.vb
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTests.vb
  src/Compilers/VisualBasic/Test/Emit/ExpressionTrees/CodeGenExprLambda.vb
  src/Compilers/VisualBasic/Test/Emit/XmlLiteralTests.vb
  src/Compilers/VisualBasic/Test/Semantic/Semantics/ConditionalAccessTests.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/ExtensionMethods/AddressOf.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/SymbolErrorTests.vb
Labels: Area-Compilers, untriaged

#71497 Separate the process of creating an event accessor parameter and the process of figuring out its type.
  src/Compilers/CSharp/Portable/Symbols/Source/LambdaParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceEventAccessorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertyAccessorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceSimpleParameterSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedAccessorValueParameterSymbol.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/PrimaryConstructorTests.cs
Labels: Area-Compilers, untriaged, New Feature - Primary Constructors

#71595 Harden some codepaths from producing null
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpInteractiveDirectives.cs
  src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SemanticFacts/CSharpSemanticFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/SymbolInfoExtensions.cs
Labels: Area-IDE, untriaged

#71650 IDE0051: Consider a record's private constructor as used
  src/Analyzers/CSharp/Tests/RemoveUnusedMembers/RemoveUnusedMembersTests.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs
Labels: Area-IDE, Community, untriaged

#71531 Disallow `ref` to `in`/`ref readonly` method parameter conversion
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/RefReadonlyParameterTests.cs
Labels: Area-Compilers, untriaged, New Feature - Ref Readonly Parameters

#71622 Only use ReadyToRun on Release builds
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Microsoft.CodeAnalysis.LanguageServer.csproj
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/PackAllRids.targets
Labels: Area-Infrastructure, untriaged

#71652 Move EditAndContinue and PDB tests to Emit2
  src/Compilers/CSharp/Test/Emit2/Emit/EditAndContinue/AssemblyReferencesTests.cs
  src/Compilers/CSharp/Test/Emit2/Emit/EditAndContinue/EditAndContinueClosureTests.cs
  src/Compilers/CSharp/Test/Emit2/Emit/EditAndContinue/EditAndContinueDelegateCacheTests.cs
  src/Compilers/CSharp/Test/Emit2/Emit/EditAndContinue/EditAndContinuePdbTests.cs
  src/Compilers/CSharp/Test/Emit2/Emit/EditAndContinue/EditAndContinueStateMachineTests.cs
  src/Compilers/CSharp/Test/Emit2/Emit/EditAndContinue/EditAndContinueTest.cs
  src/Compilers/CSharp/Test/Emit2/Emit/EditAndContinue/EditAndContinueTestBase.cs
  src/Compilers/CSharp/Test/Emit2/Emit/EditAndContinue/EditAndContinueTests.cs
  src/Compilers/CSharp/Test/Emit2/Emit/EditAndContinue/LocalSlotMappingTests.cs
  src/Compilers/CSharp/Test/Emit2/Emit/EditAndContinue/SymbolMatcherTests.cs
  src/Compilers/CSharp/Test/Emit2/Emit/LocalStateTracing/LocalStateTracingTests.cs
  src/Compilers/CSharp/Test/Emit2/PDB/CSharpDeterministicBuildCompilationTests.cs
  src/Compilers/CSharp/Test/Emit2/PDB/CSharpPDBTestBase.cs
  src/Compilers/CSharp/Test/Emit2/PDB/CheckSumTest.cs
  src/Compilers/CSharp/Test/Emit2/PDB/PDBAsyncTests.cs
  src/Compilers/CSharp/Test/Emit2/PDB/PDBConstantTests.cs
  src/Compilers/CSharp/Test/Emit2/PDB/PDBDynamicLocalsTests.cs
  src/Compilers/CSharp/Test/Emit2/PDB/PDBEmbeddedSourceTests.cs
  src/Compilers/CSharp/Test/Emit2/PDB/PDBIteratorTests.cs
  src/Compilers/CSharp/Test/Emit2/PDB/PDBLambdaTests.cs
  src/Compilers/CSharp/Test/Emit2/PDB/PDBLocalFunctionTests.cs
  src/Compilers/CSharp/Test/Emit2/PDB/PDBSourceLinkTests.cs
  src/Compilers/CSharp/Test/Emit2/PDB/PDBTests.cs
  src/Compilers/CSharp/Test/Emit2/PDB/PDBTupleTests.cs
  src/Compilers/CSharp/Test/Emit2/PDB/PDBUsingTests.cs
  src/Compilers/CSharp/Test/Emit2/PDB/PDBWinMdExpTests.cs
  src/Compilers/CSharp/Test/Emit2/PDB/PortablePdbTests.cs
  src/Compilers/CSharp/Test/Emit2/PDB/TypeDefinitionDocumentTests.cs
Labels: Area-Compilers, untriaged

#71642 Verify SyntaxList length in SyntaxNodeCache.TryGetNode()
  src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNodeCacheTests.cs
  src/Compilers/Core/Portable/Syntax/GreenNode.cs
Labels: Area-Compilers, untriaged

#71614 Handle the 'WSL is not installed' error
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/DebuggerInProcess.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/MessageBoxInProcess.cs
Labels: Area-IDE, untriaged

#71597 Include buildhost deps.json
  src/Workspaces/Core/MSBuild.BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj
  src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs
  src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj
  src/Workspaces/MSBuildTest/NetCoreTests.cs
Labels: Area-IDE, untriaged

#71584 Unify how we pass and choose pools
  azure-pipelines.yml
  eng/pipelines/build-unix-job.yml
  eng/pipelines/build-windows-job.yml
  eng/pipelines/evaluate-changed-files.yml
  eng/pipelines/test-integration-helix.yml
  eng/pipelines/test-unix-job-single-machine.yml
  eng/pipelines/test-unix-job.yml
  eng/pipelines/test-windows-job-single-machine.yml
  eng/pipelines/test-windows-job.yml
Labels: Area-Infrastructure, untriaged

#71621 [cherry-pick] Fix build definition
  azure-pipelines-official.yml
  azure-pipelines-pr-validation.yml
Labels: Area-Infrastructure, untriaged

#71662 Revert "Remove properties from DocumentSpan"
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/IVSTypeScriptFindUsagesContext.cs
  src/EditorFeatures/Test2/Classification/ClassificationTests.vb
  src/Features/Core/Portable/ClassifiedSpansAndHighlightSpanFactory.cs
  src/Features/Core/Portable/DocumentSpan.cs
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/Api/VSTypeScriptDefinitionItemBase.cs
  src/Features/Core/Portable/FindUsages/AbstractFindUsagesService.ProgressAdapter.cs
  src/Features/Core/Portable/FindUsages/DefinitionItem.DefaultDefinitionItem.cs
  src/Features/Core/Portable/FindUsages/DefinitionItem.DetachedDefinitionItem.cs
  src/Features/Core/Portable/FindUsages/DefinitionItem.cs
  src/Features/Core/Portable/FindUsages/IDefinitionsAndReferencesFactory.cs
  src/Features/Core/Portable/FindUsages/IRemoteFindUsagesService.cs
  src/Features/Core/Portable/FindUsages/SourceReferenceItem.cs
  src/Features/Core/Portable/InheritanceMargin/AbstractInheritanceMarginService_Helpers.cs
  src/Features/LanguageServer/Protocol/Handler/References/FindUsagesLSPContext.cs
  src/Tools/ExternalAccess/FSharp/FSharpDocumentSpan.cs
  src/Tools/ExternalAccess/FSharp/FindUsages/FSharpDefinitionItem.cs
  src/Tools/ExternalAccess/FSharp/FindUsages/FSharpSourceReferenceItem.cs
  src/VisualStudio/Core/Def/FindReferences/Contexts/AbstractTableDataSourceFindUsagesContext.cs
  src/VisualStudio/Core/Def/FindReferences/Contexts/WithReferencesFindUsagesContext.cs
  src/VisualStudio/Core/Def/FindReferences/Contexts/WithoutReferencesFindUsagesContext.cs
  src/VisualStudio/Core/Def/FindReferences/VisualStudioDefinitionsAndReferencesFactory.cs
  src/VisualStudio/Core/Def/ValueTracking/ValueTrackedTreeItemViewModel.cs
Labels: Area-IDE, untriaged

#71611 Support producing a collection expression constructed from other spreaded collection expressions
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForFluentDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpCollectionExpressionRewriter.cs
  src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpUseCollectionExpressionForFluentCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForBuilderTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForFluentTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests_CollectionExpression.cs
Labels: Area-IDE, untriaged

#71663 Fix CompilerDeveloperSdk EA Layer
  src/Tools/ExternalAccess/CompilerDeveloperSDK/Extensions/ProtocolConversions.cs
  src/Tools/ExternalAccess/CompilerDeveloperSDK/Handler/AbstractCompilerDeveloperSdkLspServiceDocumentRequestHandler.cs
  src/Tools/ExternalAccess/CompilerDeveloperSDK/InternalAPI.Unshipped.txt
Labels: Area-IDE, untriaged

#71606 Ensure thread-safety in aggregated telemetry
  src/VisualStudio/Core/Def/Telemetry/AggregatingTelemetryLog.cs
Labels: Area-IDE, untriaged

#71456 Fixes nested code actions in LSP bug
  src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionHelpers.cs
  src/Features/LanguageServer/ProtocolUnitTests/CodeActions/CodeActionsTests.cs
Labels: Area-IDE, untriaged

#71670 Add publishdata for the Xaml LSP
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#71668 Use VSCode compatible buildhost
  src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj
Labels: Area-IDE, untriaged

#71626 Simplify how we add .editorconfigs to Solution Items
  src/Features/Core/Portable/CodeFixes/Configuration/ConfigurationUpdater.cs
  src/Features/Core/Portable/CodeFixes/Configuration/IAddSolutionItemService.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioAddSolutionItemService.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/Core/Def/RoslynPackage.cs
Labels: Area-IDE, untriaged

#71656 Turn off auto surround in integration tests
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpArgumentProvider.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/WorkaroundsInProcess.cs
Labels: Area-IDE, untriaged

#71493 Reduce allocations when creating CompositeText instances.
  src/Compilers/Core/Portable/Text/CompositeText.cs
  src/Dependencies/PooledObjects/ArrayBuilder.cs
Labels: Area-Compilers, untriaged

#71682 Fix build definition
  azure-pipelines-official.yml
  azure-pipelines-pr-validation.yml
Labels: Area-Infrastructure, untriaged

#71589 Preserve the whitespaces when rewriting an inheritdoc
  src/EditorFeatures/Test2/IntelliSense/IntellisenseQuickInfoBuilderTests_Inheritdoc.vb
  src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs
Labels: Area-IDE, Community, untriaged

#71674 Remove unused code
  src/Compilers/Core/CodeAnalysisTest/AssemblyUtilitiesTests.cs
  src/Compilers/Core/Portable/AssemblyUtilities.cs
Labels: Area-Compilers, untriaged

#71684 Fix language id mapping for TS/JS
  src/Features/LanguageServer/Protocol/LanguageInfoProvider.cs
Labels: Area-IDE, untriaged

#71688 Fix validation pipeline
  azure-pipelines-pr-validation.yml
Labels: Area-Infrastructure, untriaged

#71452 Collection expressions: update conversion tests for overload resolution failure
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, Test, untriaged

#71681 Fix rolling CI
  azure-pipelines.yml
  eng/pipelines/test-windows-job-single-machine.yml
Labels: Area-Infrastructure, untriaged

#71683 Update TeamFoundationServerClientVersion
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#71516 Update other BCL to 8.0.0
  eng/SourceBuildPrebuiltBaseline.xml
  eng/Version.Details.xml
  eng/Versions.props
  src/Compilers/VisualBasic/Test/Semantic/HasValidFonts.vb
  src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/Microsoft.CommonLanguageServerProtocol.Framework.csproj
Labels: Area-Infrastructure, untriaged

#71590 Target Workspace and Features layer tests to .NET
  src/Compilers/Test/Utilities/CSharp/Microsoft.CodeAnalysis.CSharp.Test.Utilities.csproj
  src/Compilers/Test/Utilities/VisualBasic/Microsoft.CodeAnalysis.VisualBasic.Test.Utilities.vbproj
  src/Features/CSharpTest/ConvertTupleToStruct/ConvertTupleToStructTests.cs
  src/Features/CSharpTest/GenerateComparisonOperators/GenerateComparisonOperatorsTests.cs
  src/Features/CSharpTest/Microsoft.CodeAnalysis.CSharp.Features.UnitTests.csproj
  src/Features/DiagnosticsTestUtilities/Microsoft.CodeAnalysis.Features.DiagnosticsTests.Utilities.csproj
  src/Features/Test/EditAndContinue/CompileTimeSolutionProviderTests.cs
  src/Features/Test/Microsoft.CodeAnalysis.Features.UnitTests.csproj
  src/Features/TestUtilities/EditAndContinue/RudeEditDiagnosticDescription.cs
  src/Features/TestUtilities/Microsoft.CodeAnalysis.Features.Test.Utilities.csproj
  src/Features/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.Features.vbproj
  src/Features/VisualBasicTest/ConvertTupleToStruct/ConvertTupleToStructTests.vb
  src/Features/VisualBasicTest/GenerateDefaultConstructors/GenerateDefaultConstructorsTests.vb
  src/Features/VisualBasicTest/ImplementInterface/ImplementInterfaceTests.vb
  src/Features/VisualBasicTest/Microsoft.CodeAnalysis.VisualBasic.Features.UnitTests.vbproj
  src/Workspaces/CSharpTest/Microsoft.CodeAnalysis.CSharp.Workspaces.UnitTests.csproj
  src/Workspaces/CoreTest/Microsoft.CodeAnalysis.Workspaces.UnitTests.csproj
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
  src/Workspaces/CoreTest/WorkspaceServiceTests/TemporaryStorageServiceTests.cs
  src/Workspaces/CoreTestUtilities/Microsoft.CodeAnalysis.Workspaces.Test.Utilities.csproj
  src/Workspaces/Remote/ServiceHubTest/Microsoft.CodeAnalysis.Remote.ServiceHub.UnitTests.csproj
  src/Workspaces/Remote/ServiceHubTest/RemoteAnalyzerAssemblyLoaderTests.cs
  src/Workspaces/VisualBasicTest/Microsoft.CodeAnalysis.VisualBasic.Workspaces.UnitTests.vbproj
Labels: Area-Infrastructure, untriaged

#71692 Fix Persistent Storage tests
  src/VisualStudio/CSharp/Test/PersistentStorage/AbstractPersistentStorageTests.cs
Labels: Area-IDE, untriaged

#71693 Ensure we find the right partial if we have multiple in one file
  src/Features/Lsif/Generator/Generator.cs
  src/Features/Lsif/GeneratorTest/DocumentSymbolTests.vb
Labels: Area-IDE, untriaged

#70667 Invoke code mapper via reflection
  src/Tools/ExternalAccess/Copilot/CodeMapper/ICSharpCopilotMapCodeService.cs
  src/Tools/ExternalAccess/Copilot/Internal/CodeMapper/CopilotCSharpMapCodeService.cs
  src/Tools/ExternalAccess/Copilot/InternalAPI.Unshipped.txt
Labels: Area-IDE, untriaged

#71699 Add EA.Razor.Compiler back to publishData.json
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#71686 Fix Spanish test
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenStackAllocInitializerTests.cs
Labels: Area-Compilers

#71671 [Razor Cohost] Pass TextDocuments to Razor for text sync LSP messages
  src/Tools/ExternalAccess/Razor/Cohost/IRazorCohostTextDocumentSyncHandler.cs
  src/Tools/ExternalAccess/Razor/Cohost/RazorCohostDidChangeEndpoint.cs
  src/Tools/ExternalAccess/Razor/Cohost/RazorCohostDidCloseEndpoint.cs
  src/Tools/ExternalAccess/Razor/Cohost/RazorCohostDidOpenEndpoint.cs
Labels: Area-IDE, untriaged

#71694 Include file names in the aggregate exception we create
  src/Features/Lsif/Generator/Generator.cs
Labels: Area-IDE, untriaged

#71707 Address UIDelays in AbstractGraphProvider.GetCommands
  src/VisualStudio/CSharp/Impl/Progression/CSharpGraphProvider.cs
  src/VisualStudio/Core/Def/Progression/GraphProvider.cs
  src/VisualStudio/Core/Test/Progression/GraphProviderTests.vb
  src/VisualStudio/VisualBasic/Impl/Progression/VisualBasicGraphProvider.vb
Labels: Area-IDE, untriaged

#71664 Switch CpsDiagnosticItemSourceProvider to use IProjectTree/ProjectTreeFlags
  src/Setup/DevDivInsertionFiles/DevDivInsertionFiles.csproj
  src/VisualStudio/Core/Impl/Microsoft.VisualStudio.LanguageServices.Implementation.csproj
  src/VisualStudio/Core/Impl/SolutionExplorer/DiagnosticItem/CpsDiagnosticItemSourceProvider.cs
Labels: Area-IDE, untriaged

#71706 Mac crash dumps
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
  src/Compilers/CSharp/Test/EndToEnd/EndToEndTests.cs
  src/Tools/Source/RunTests/TestRunner.cs
Labels: Area-Infrastructure, untriaged

#71722 Fixing typos
  docs/wiki/How-To-Write-a-C#-Analyzer-and-Code-Fix.md
Labels: Area-Compilers, Community, untriaged

#71655 Fix intercepting a struct or enum base method
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs
Labels: Area-Compilers, untriaged

#71700 Move projects to different directories
  Compilers.slnf
  Roslyn.sln
  src/CodeStyle/CSharp/Tests/Microsoft.CodeAnalysis.CSharp.CodeStyle.UnitTests.csproj
  src/CodeStyle/Core/Tests/LegacyTestFramework/Microsoft.CodeAnalysis.CodeStyle.LegacyTestFramework.UnitTestUtilities.csproj
  src/CodeStyle/Core/Tests/Microsoft.CodeAnalysis.CodeStyle.LegacyTestFramework.UnitTestUtilities.csproj
  src/CodeStyle/Core/Tests/Microsoft.CodeAnalysis.CodeStyle.UnitTestUtilities.csproj
  src/CodeStyle/Core/Tests/UnitTestUtilities/Microsoft.CodeAnalysis.CodeStyle.UnitTestUtilities.csproj
  src/CodeStyle/VisualBasic/Tests/Microsoft.CodeAnalysis.VisualBasic.CodeStyle.UnitTests.vbproj
  src/Interactive/HostProcess/x64/.editorconfig
  src/Interactive/HostProcess/x64/Core/CSharpInteractive.rsp
  src/Interactive/HostProcess/x64/Desktop/CSharpInteractive.rsp
  src/Interactive/HostProcess/x64/InteractiveHost64.csproj
  src/Interactive/HostProcess/x86/.editorconfig
  src/Interactive/HostProcess/x86/InteractiveHost32.csproj
  src/Interactive/HostTest/InteractiveHost.UnitTests.csproj
  src/NuGet/Microsoft.CodeAnalysis.Compilers.Package/Microsoft.CodeAnalysis.Compilers.Package.csproj
  src/NuGet/Microsoft.CodeAnalysis.EditorFeatures.Package/Microsoft.CodeAnalysis.EditorFeatures.Package.csproj
  src/NuGet/Microsoft.CodeAnalysis.Package/Microsoft.CodeAnalysis.Package.csproj
  src/NuGet/Microsoft.CodeAnalysis.Scripting.Package/Microsoft.CodeAnalysis.Scripting.Package.csproj
  src/NuGet/VS.ExternalAPIs.Roslyn.Package/VS.ExternalAPIs.Roslyn.Package.csproj
  src/NuGet/VS.Tools.Roslyn.Package/Directory.Build.props
  src/NuGet/VS.Tools.Roslyn.Package/Init.cmd
  src/NuGet/VS.Tools.Roslyn.Package/VS.Tools.Roslyn.Package.csproj
  src/Tools/BuildBoss/SolutionCheckerUtil.cs
  src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj
Labels: Area-Infrastructure, untriaged

#71608 TelemetryLogging.Log* methods should be calling free on the passed in KeyValueLogMessage
  src/VisualStudio/Core/Def/Telemetry/TimedTelemetryLogBlock.cs
  src/Workspaces/Core/Portable/Telemetry/TelemetryLogging.cs
Labels: Area-IDE, untriaged

#71618 Don't create the InheritanceMarginTagger for preview views.
  src/EditorFeatures/Core/Tagging/AsynchronousViewportTaggerProvider.cs
  src/VisualStudio/Core/Def/InheritanceMargin/InheritanceMarginTaggerProvider.cs
Labels: Area-IDE, untriaged

#71715 Update to MicroBuildSigningPlugin V4
  azure-pipelines-official.yml
  azure-pipelines-pr-validation.yml
  eng/Directory.Packages.props
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#71734 Another attempt at getting TelemetryLogger working in VSCode
  src/VisualStudio/Core/Def/Telemetry/Shared/AggregatingTelemetryLog.cs
  src/VisualStudio/Core/Def/Telemetry/Shared/AggregatingTelemetryLogManager.cs
  src/VisualStudio/Core/Def/Telemetry/Shared/TelemetryLogProvider.cs
  src/VisualStudio/Core/Def/Telemetry/Shared/TelemetryLogger.cs
  src/VisualStudio/Core/Def/Telemetry/Shared/TimedTelemetryLogBlock.cs
  src/VisualStudio/Core/Def/Telemetry/Shared/VisualStudioTelemetryLog.cs
  src/VisualStudio/Core/Def/Telemetry/Shared/VisualStudioTelemetryLogManager.cs
  src/VisualStudio/DevKit/Impl/Logging/VSCodeTelemetryLogger.cs
  src/VisualStudio/DevKit/Impl/Microsoft.VisualStudio.LanguageServices.DevKit.csproj
  src/Workspaces/Remote/ServiceHub/Microsoft.CodeAnalysis.Remote.ServiceHub.csproj
Labels: Area-IDE, untriaged

#71746 Allow Razor to register Json converters for functional tests
  src/Tools/ExternalAccess/Razor/IRazorLanguageServerFactory.cs
  src/Tools/ExternalAccess/Razor/IRazorTestCapabilitiesProvider.cs
  src/Tools/ExternalAccess/Razor/RazorLanguageServerFactoryWrapper.cs
  src/Tools/ExternalAccess/Razor/RazorSemanticTokensAccessor.cs
Labels: Area-IDE, untriaged

#71756 Fix bootstrap log publish
  eng/pipelines/build-bootstrap.yml
  eng/test-build-correctness.ps1
Labels: Area-Infrastructure, untriaged

#71759 Fix VSIX asset inclusion
  eng/targets/VisualStudio.targets
  src/Compilers/Extension/Roslyn.Compilers.Extension.csproj
  src/VisualStudio/Setup.Dependencies/Roslyn.VisualStudio.Setup.Dependencies.csproj
  src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj
Labels: Area-Infrastructure, untriaged

#71738 Add logging to track down a double dispose
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/FileWatchedPortableExecutableReferenceFactory.cs
Labels: Area-IDE, untriaged

#71396 Break Solution-checksums into a checksums for pure-state vs source-generator state
  src/VisualStudio/Core/Test.Next/Remote/SerializationValidator.cs
  src/VisualStudio/Core/Test.Next/Remote/SnapshotSerializationTests.cs
  src/Workspaces/Core/Portable/Remote/WellKnownSynchronizationKind.cs
  src/Workspaces/Core/Portable/Serialization/SerializationExtensions.cs
  src/Workspaces/Core/Portable/Serialization/SerializerService.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState_Checksum.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs
  src/Workspaces/Remote/Core/AbstractAssetProvider.cs
  src/Workspaces/Remote/Core/SolutionAssetStorage.Scope.cs
  src/Workspaces/Remote/ServiceHub/Host/ChecksumSynchronizer.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs
  src/Workspaces/Remote/ServiceHub/Host/TestUtils.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-IDE, untriaged

#71765 Update tests to be explicitly clear that they are testing push diagnostics.
  src/EditorFeatures/CSharpTest/InlineDiagnostics/InlineDiagnosticsTaggerProviderTests.cs
  src/EditorFeatures/CSharpTest/Squiggles/ErrorSquiggleProducerTests.cs
  src/EditorFeatures/CSharpTest/SuggestionTags/SuggestionTagProducerTests.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/AbstractCodeActionOrUserDiagnosticTest.cs
  src/EditorFeatures/Test/CodeFixes/CodeFixServiceTests.cs
  src/EditorFeatures/Test/Diagnostics/DiagnosticAnalyzerServiceTests.cs
  src/EditorFeatures/Test/Diagnostics/DiagnosticsClassificationTaggerProviderTests.cs
  src/EditorFeatures/Test/Diagnostics/DiagnosticsSquiggleTaggerProviderTests.cs
  src/EditorFeatures/Test/Preview/PreviewWorkspaceTests.cs
  src/EditorFeatures/Test2/Diagnostics/DiagnosticProviderTests.vb
  src/EditorFeatures/VisualBasicTest/Squiggles/ErrorSquiggleProducerTests.vb
  src/Features/LanguageServer/Protocol/Features/Options/DiagnosticModeExtensions.cs
  src/Features/LanguageServer/Protocol/Features/Options/DiagnosticOptionsStorage.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
Labels: Area-IDE, untriaged

#71764 Minor rename of internal property
  src/Features/LanguageServer/Protocol/Features/Options/DiagnosticModeExtensions.cs
  src/Features/LanguageServer/Protocol/Features/Options/DiagnosticOptionsStorage.cs
  src/Features/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
  src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs
Labels: Area-IDE, untriaged

#71761 Simplify test code
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs
Labels: Area-IDE, untriaged

#71766 Fix crash in 'convert to record'
  src/Analyzers/CSharp/CodeFixes/ConvertToRecord/ConvertToRecordEngine.cs
  src/Features/CSharp/Portable/ConvertToRecord/CSharpConvertToRecordRefactoringProvider.cs
  src/Features/CSharpTest/ConvertToRecord/ConvertToRecordCodeRefactoringTests.cs
Labels: Area-IDE, untriaged

#71751 Fix issue with 'use primary constructor' when an assignment uses a suppression operator
  src/Analyzers/CSharp/Analyzers/UsePrimaryConstructor/CSharpUsePrimaryConstructorDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/UsePrimaryConstructor/UsePrimaryConstructorTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ExpressionSyntaxExtensions.cs
Labels: Area-IDE, untriaged

#71713 Revert deadlock mitigation that causes other deadlocks
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.OpenFileTracker.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.cs
Labels: Area-IDE, untriaged

#71687 Restore "Remove properties from DocumentSpan"
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/IVSTypeScriptFindUsagesContext.cs
  src/EditorFeatures/Test2/Classification/ClassificationTests.vb
  src/Features/Core/Portable/ClassifiedSpansAndHighlightSpanFactory.cs
  src/Features/Core/Portable/DocumentSpan.cs
  src/Features/Core/Portable/ExternalAccess/VSTypeScript/Api/VSTypeScriptDefinitionItemBase.cs
  src/Features/Core/Portable/FindUsages/AbstractFindUsagesService.ProgressAdapter.cs
  src/Features/Core/Portable/FindUsages/DefinitionItem.DefaultDefinitionItem.cs
  src/Features/Core/Portable/FindUsages/DefinitionItem.DetachedDefinitionItem.cs
  src/Features/Core/Portable/FindUsages/DefinitionItem.cs
  src/Features/Core/Portable/FindUsages/IDefinitionsAndReferencesFactory.cs
  src/Features/Core/Portable/FindUsages/IRemoteFindUsagesService.cs
  src/Features/Core/Portable/FindUsages/SourceReferenceItem.cs
  src/Features/Core/Portable/InheritanceMargin/AbstractInheritanceMarginService_Helpers.cs
  src/Features/LanguageServer/Protocol/Handler/References/FindUsagesLSPContext.cs
  src/Tools/ExternalAccess/FSharp/FSharpDocumentSpan.cs
  src/Tools/ExternalAccess/FSharp/FindUsages/FSharpDefinitionItem.cs
  src/Tools/ExternalAccess/FSharp/FindUsages/FSharpSourceReferenceItem.cs
  src/VisualStudio/Core/Def/FindReferences/Contexts/AbstractTableDataSourceFindUsagesContext.cs
  src/VisualStudio/Core/Def/FindReferences/Contexts/WithReferencesFindUsagesContext.cs
  src/VisualStudio/Core/Def/FindReferences/Contexts/WithoutReferencesFindUsagesContext.cs
  src/VisualStudio/Core/Def/FindReferences/VisualStudioDefinitionsAndReferencesFactory.cs
  src/VisualStudio/Core/Def/ValueTracking/ValueTrackedTreeItemViewModel.cs
Labels: Area-IDE, untriaged

#71775 Make tests explicit that they are in push-diagnostics mode
  src/VisualStudio/Core/Test/Diagnostics/DefaultDiagnosticUpdateSourceTests.vb
  src/VisualStudio/Core/Test/Diagnostics/DiagnosticTableDataSourceTests.vb
Labels: Area-IDE, untriaged

#71776 Update source build version
  eng/Version.Details.xml
Labels: Area-Infrastructure, untriaged

#71760 Make syntax generator handle ref struct correctly
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
  src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs
Labels: Area-IDE, Community, untriaged

#71721 Use Regex source generator in compiler
  src/Compilers/Core/Portable/CommandLine/AnalyzerConfig.cs
Labels: Area-Compilers, untriaged

#69122 Implement extension indexer access
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/ExtensionTypeTests.cs
Labels: Area-Compilers, untriaged

#71207 Expose programmatic suppressions from SuppressionInfo
  src/Analyzers/Core/Analyzers/RemoveUnnecessarySuppressions/AbstractRemoveUnnecessaryPragmaSuppressionsDiagnosticAnalyzer.cs
  src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticSuppressorTests.cs
  src/Compilers/CSharp/Test/Emit2/Diagnostics/GetDiagnosticsTests.cs
  src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs
  src/Compilers/Core/Portable/CommandLine/SarifV2ErrorLogger.cs
  src/Compilers/Core/Portable/Diagnostic/Diagnostic.cs
  src/Compilers/Core/Portable/Diagnostic/ProgrammaticSuppressionInfo.cs
  src/Compilers/Core/Portable/Diagnostic/SuppressionInfo.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
Labels: Area-Analyzers, untriaged

#71769 Add native lock feature status
  docs/Language Feature Status.md
Labels: Area-Compilers, untriaged

#71778 Disable OSX queue
  azure-pipelines.yml
Labels: Area-Infrastructure, untriaged

#71777 Clean up the IntelliSense option pages
  src/VisualStudio/CSharp/Impl/Options/IntelliSenseOptionPageControl.xaml
  src/VisualStudio/CSharp/Impl/Options/IntelliSenseOptionPageControl.xaml.cs
  src/VisualStudio/VisualBasic/Impl/Options/IntelliSenseOptionPageControl.xaml
  src/VisualStudio/VisualBasic/Impl/Options/IntelliSenseOptionPageControl.xaml.vb
Labels: Area-IDE, untriaged

#71787 Don't reference S.R.C.Unsafe in net7.0 or newer
  src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj
Labels: Area-Compilers, Community, untriaged

#71796 Ban use-collection-expression in a particular case
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForFluentDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForFluentTests.cs
Labels: Area-IDE, untriaged

#71792 Handle unconverted collection expressions in nullable analysis
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged

#71697 Support lexing razor comments
  src/Compilers/CSharp/Portable/Parser/Lexer.cs
  src/Compilers/CSharp/Portable/Parser/Lexer_StringLiteral.cs
  src/Compilers/CSharp/Portable/Syntax/InternalSyntax/SyntaxFactory.cs
  src/Compilers/CSharp/Test/Syntax/LexicalAndXml/LexicalErrorTests.cs
  src/Compilers/CSharp/Test/Syntax/LexicalAndXml/LexicalTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ParsingErrorRecoveryTests.cs
Labels: Area-Compilers, untriaged

#71739 Fix SyntaxGenerator not generating event field modifiers correctly
  src/EditorFeatures/CSharpTest/CodeActions/PullMemberUp/CSharpPullMemberUpTests.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
Labels: Area-IDE, Community, untriaged

#71666 Upstream changes from Vertical Build PoC
  azure-pipelines.yml
  eng/SourceBuild.props
  eng/build.ps1
  eng/generate-compiler-code.ps1
  eng/validate-code-formatting.ps1
  src/Compilers/Test/Core/Microsoft.CodeAnalysis.Test.Utilities.csproj
  src/Compilers/Test/Resources/Core/Microsoft.CodeAnalysis.Compiler.Test.Resources.csproj
  src/Compilers/Test/Utilities/CSharp/Microsoft.CodeAnalysis.CSharp.Test.Utilities.csproj
  src/Compilers/Test/Utilities/VisualBasic/Microsoft.CodeAnalysis.VisualBasic.Test.Utilities.vbproj
  src/EditorFeatures/DiagnosticsTestUtilities/Microsoft.CodeAnalysis.EditorFeatures.DiagnosticsTests.Utilities.csproj
  src/EditorFeatures/TestUtilities/Microsoft.CodeAnalysis.EditorFeatures.Test.Utilities.csproj
  src/EditorFeatures/TestUtilities2/Microsoft.CodeAnalysis.EditorFeatures.Test.Utilities2.vbproj
  src/ExpressionEvaluator/Core/Test/ExpressionCompiler/Microsoft.CodeAnalysis.ExpressionCompiler.Utilities.csproj
  src/ExpressionEvaluator/Core/Test/ResultProvider/Microsoft.CodeAnalysis.ResultProvider.Utilities.csproj
  src/Features/DiagnosticsTestUtilities/Microsoft.CodeAnalysis.Features.DiagnosticsTests.Utilities.csproj
  src/Features/TestUtilities/Microsoft.CodeAnalysis.Features.Test.Utilities.csproj
  src/NuGet/VS.ExternalAPIs.Roslyn.Package/VS.ExternalAPIs.Roslyn.Package.csproj
  src/Scripting/CoreTestUtilities/Microsoft.CodeAnalysis.Scripting.TestUtilities.csproj
  src/Setup/DevDivVsix/CompilersPackage/CompilersPackage.targets
  src/Setup/Directory.Build.props
  src/Test/PdbUtilities/Roslyn.Test.PdbUtilities.csproj
  src/Tools/Directory.Build.props
  src/Tools/ExternalAccess/AspNetCore/Microsoft.CodeAnalysis.ExternalAccess.AspNetCore.csproj
  src/Tools/ExternalAccess/Razor/Microsoft.CodeAnalysis.ExternalAccess.Razor.csproj
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/CSharpSyntaxGenerator.csproj
  src/Tools/Source/RunTests/RunTests.csproj
  src/VisualStudio/Directory.Build.props
  src/VisualStudio/TestUtilities2/Microsoft.VisualStudio.LanguageServices.Test.Utilities2.vbproj
  src/Workspaces/CoreTestUtilities/Microsoft.CodeAnalysis.Workspaces.Test.Utilities.csproj
Labels: Area-Infrastructure, Community, untriaged

#71733 Prefer converting to ReadOnlySpan for spread optimization when we do not need to write
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs
Labels: Area-Compilers, untriaged

#71783 Reduce ImmutableArray allocations around AssemblyIdentity
  src/Compilers/CSharp/Portable/Symbols/ReferenceManager.cs
  src/Compilers/Core/Portable/Collections/ImmutableArrayExtensions.cs
  src/Compilers/Core/Portable/Compilation/Compilation.cs
  src/Compilers/Core/Portable/MetadataReader/PEAssembly.cs
  src/Compilers/Core/Portable/ReferenceManager/AssemblyDataForAssemblyBeingBuilt.cs
Labels: Area-Compilers, untriaged

#71748 Semantic snippets: Make postfix `for` and `forr` snippets available for types with `Length` or `Count` property
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpForSnippetCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/Snippets/CSharpForrSnippetCompletionProviderTests.cs
  src/Features/CSharp/Portable/Snippets/AbstractCSharpForLoopSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpForLoopSnippetProvider.cs
  src/Features/CSharp/Portable/Snippets/CSharpReversedForLoopSnippetProvider.cs
  src/Features/Core/Portable/Snippets/SnippetProviders/AbstractForLoopSnippetProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ITypeSymbolExtensions.cs
Labels: Area-IDE, Community, untriaged

#71102 Check Frame's VSFPROPID_IsDocDataInitialized before Getting DocData
  src/VisualStudio/Core/Def/Workspace/VisualStudioActiveDocumentTracker.cs
Labels: Area-IDE, Community, untriaged

#71782 Cleanup VSIX asset inclusion
  eng/Directory.Packages.props
  eng/generate-vssdk-versions.csx
  eng/targets/VisualStudio.targets
  sourcebuild.binlog
  src/Compilers/Extension/Roslyn.Compilers.Extension.csproj
  src/VisualStudio/Setup.Dependencies/Roslyn.VisualStudio.Setup.Dependencies.csproj
  src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj
Labels: Area-Infrastructure, untriaged

#71795 Remove dependency on IFindUsageContext from DefinitionItemExtensions
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptFindUsagesService.cs
  src/EditorFeatures/Core/FindReferences/FindReferencesCommandHandler.cs
  src/EditorFeatures/Core/FindUsages/BufferedFindUsagesContext.cs
  src/EditorFeatures/Core/GoToBase/GoToBaseCommandHandler.cs
  src/EditorFeatures/Core/GoToDefinition/AbstractGoToCommandHandler`2.cs
  src/EditorFeatures/Core/GoToImplementation/GoToImplementationCommandHandler.cs
  src/EditorFeatures/Test/FindReferences/FindReferencesCommandHandlerTests.cs
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.vb
  src/EditorFeatures/Test2/GoToBase/GoToBaseTestsBase.vb
  src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionTestsBase.vb
  src/EditorFeatures/Test2/GoToHelpers/GoToHelpers.vb
  src/EditorFeatures/Test2/GoToImplementation/GoToImplementationTests.vb
  src/EditorFeatures/TestUtilities2/Utilities/GoToHelpers/MockNavigableItemsPresenter.vb
  src/Features/Core/Portable/ConvertTupleToStruct/IRemoteConvertTupleToStructCodeRefactoringService.cs
  src/Features/Core/Portable/EncapsulateField/IRemoteEncapsulateFieldService.cs
  src/Features/Core/Portable/FindUsages/AbstractFindUsagesService.DefinitionTrackingContext.cs
  src/Features/Core/Portable/FindUsages/AbstractFindUsagesService.ProgressAdapter.cs
  src/Features/Core/Portable/FindUsages/AbstractFindUsagesService_FindImplementations.cs
  src/Features/Core/Portable/FindUsages/AbstractFindUsagesService_FindReferences.cs
  src/Features/Core/Portable/FindUsages/FindUsagesContext.cs
  src/Features/Core/Portable/FindUsages/FindUsagesOptions.cs
  src/Features/Core/Portable/FindUsages/IDefinitionsAndReferencesFactory.cs
  src/Features/Core/Portable/FindUsages/IFindUsagesContext.cs
  src/Features/Core/Portable/FindUsages/IFindUsagesLSPService.cs
  src/Features/Core/Portable/FindUsages/IFindUsagesService.cs
  src/Features/Core/Portable/FindUsages/IRemoteFindUsagesService.cs
  src/Features/Core/Portable/GoToBase/AbstractGoToBaseService.cs
  src/Features/Core/Portable/GoToBase/IGoToBaseService.cs
  src/Features/LanguageServer/Protocol/Features/FindUsages/SimpleFindUsagesContext.cs
  src/Features/LanguageServer/Protocol/Features/Options/ClassificationOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Features/Options/FindUsagesOptionsStorage.cs
  src/Features/LanguageServer/Protocol/Handler/References/FindAllReferencesHandler.cs
  src/Features/LanguageServer/Protocol/Handler/References/FindImplementationsHandler.cs
  src/Features/LanguageServer/Protocol/Handler/References/FindUsagesLSPContext.cs
  src/Features/LanguageServer/Protocol/Microsoft.CodeAnalysis.LanguageServer.Protocol.csproj
  src/Features/TestUtilities/Options/TestOptionsProvider.cs
  src/Tools/ExternalAccess/Debugger/DebuggerFindReferencesService.cs
  src/Tools/ExternalAccess/Debugger/InternalAPI.Unshipped.txt
  src/Tools/ExternalAccess/FSharp/Internal/Editor/FindUsages/FSharpFindUsagesService.cs
  src/VisualStudio/Core/Def/FindReferences/Contexts/AbstractTableDataSourceFindUsagesContext.cs
  src/VisualStudio/Core/Def/Library/ObjectBrowser/AbstractObjectBrowserLibraryManager.cs
  src/VisualStudio/Core/Test/GoToDefinition/GoToDefinitionApiTests.vb
  src/VisualStudio/Core/Test/Venus/DocumentService_IntegrationTests.vb
  src/Workspaces/Core/Portable/Remote/IRemoteOptionsCallback.cs
  src/Workspaces/Core/Portable/Rename/IRemoteRenamerService.cs
  src/Workspaces/CoreTestUtilities/Fakes/StubStreamingFindUsagesPresenter.cs
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs
  src/Workspaces/Remote/ServiceHub/Services/ClientOptionProviders.cs
  src/Workspaces/Remote/ServiceHub/Services/ClientOptionsProvider.cs
  src/Workspaces/Remote/ServiceHub/Services/ConvertTupleToStructCodeRefactoringProvider/RemoteConvertTupleToStructCodeRefactoringService.cs
  src/Workspaces/Remote/ServiceHub/Services/EncapsulateField/RemoteEncapsulateFieldService.cs
  src/Workspaces/Remote/ServiceHub/Services/FindUsages/RemoteFindUsagesService.cs
  src/Workspaces/Remote/ServiceHub/Services/Renamer/RemoteRenamerService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeCleanup/CodeCleanupOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeGeneration/CleanCodeGenerationOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Options/OptionsProvider.cs
Labels: Area-IDE, untriaged

#71809 Fix System.Data.SqlClient version alert
  eng/Directory.Packages.props
Labels: Area-Infrastructure, untriaged

#71807 Load Roslyn DevKit assemblies into the default ALC
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/TelemetryReporterTests.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Utilities/LanguageServerTestComposition.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/ExportProviderBuilder.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Program.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/ServerConfigurationFactory.cs
  src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Services/AssemblyLoadContextWrapper.cs
Labels: Area-IDE, untriaged

#71451 Do not throw exceptions when we can't make a doc id
  src/Analyzers/Core/Analyzers/RemoveUnnecessarySuppressions/AbstractRemoveUnnecessaryAttributeSuppressionsDiagnosticAnalyzer.cs
  src/Compilers/Core/CodeAnalysisTest/Symbols/DocumentationCommentIdTests.cs
  src/Compilers/Core/Portable/DocumentationCommentId.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Features/Core/Portable/DocumentationComments/AbstractDocumentationCommentFormattingService.cs
  src/Workspaces/Core/Portable/Editing/SymbolEditor.cs
  src/Workspaces/Core/Portable/Utilities/Documentation/DeferredDocumentationProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Simplification/SymbolAnnotation.cs
Labels: Area-Compilers, untriaged

#71815 Add additional tests suggested from code review
  src/Compilers/CSharp/Test/Syntax/LexicalAndXml/LexicalTests.cs
Labels: Area-Compilers, untriaged

#71799 Avoid unnecessary temporary builders when creating syntax lists.
  src/Compilers/Core/Portable/Syntax/SyntaxList`1.cs
  src/Compilers/Core/Portable/Syntax/SyntaxNodeOrTokenList.cs
  src/Compilers/Core/Portable/Syntax/SyntaxTokenList.cs
  src/Compilers/Core/Portable/Syntax/SyntaxTriviaList.cs
  src/Features/CSharp/Portable/Snippets/AbstractCSharpAutoPropertySnippetProvider.cs
  src/Features/Core/Portable/IntroduceUsingStatement/AbstractIntroduceUsingStatementCodeRefactoringProvider.cs
Labels: Area-IDE, untriaged
