Repository dotnet/roslyn, pull requests merged in 2025-01, with the labels that each got.

#76543 Ensure 'remove unnecessary using' shows up before 'convert to program-main style program'
  src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryImports/CSharpRemoveUnnecessaryImportsCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/RemoveUnnecessaryImports/AbstractRemoveUnnecessaryImportsCodeFixProvider.cs
  src/Features/CSharp/Portable/ConvertProgram/ConvertToProgramMainCodeFixProvider.cs
Labels: Area-IDE, untriaged, VSCode

#76549 Do not dismiss extract method when a notification is shown to the user
  src/EditorFeatures/Core/ExtractMethod/ExtractMethodCommandHandler.cs
Labels: Area-IDE, untriaged

#76576 Fix crash when classifying embedded test classifications
  src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests_TestMarkup.cs
  src/Features/CSharp/Portable/EmbeddedLanguages/CSharpTestEmbeddedLanguageClassifier.cs
Labels: Area-IDE, untriaged, VSCode

#62319 Prefix 'unmerged changes' with 'TODO'
  src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb
  src/Workspaces/Core/Portable/LinkedFileDiffMerging/AbstractLinkedFileMergeConflictCommentAdditionService.cs
  src/Workspaces/Core/Portable/WorkspacesResources.resx
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.cs.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.de.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.es.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.fr.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.it.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ja.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ko.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.pl.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.pt-BR.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.ru.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.tr.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.zh-Hans.xlf
  src/Workspaces/Core/Portable/xlf/WorkspacesResources.zh-Hant.xlf
  src/Workspaces/CoreTest/LinkedFileDiffMerging/LinkedFileDiffMergingTests.TextMerging.cs
Labels: Area-IDE, Community, VSCode

#65747 Add more test scenarios for symbol completion after scoped
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs
Labels: Area-IDE, Community, VSCode

#64094 Add F1 test for scoped
  src/VisualStudio/CSharp/Test/F1Help/F1HelpTests.cs
Labels: Area-IDE, Community

#76574 Language Feature Status.md: correct dictionary expressions entries
  docs/Language Feature Status.md
Labels: Area-Compilers, untriaged

#65490 Update few completion tests
  src/EditorFeatures/CSharpTest2/Recommendations/AbstractKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/CharKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/CheckedKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ClassKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/DecimalKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/DefaultKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/DelegateKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/DoKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/DoubleKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/DynamicKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/EnumKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/FalseKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/FloatKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ForEachKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ForKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/FromKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/GotoKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/IfKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/IntKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/InterfaceKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/InternalKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/LockKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/LongKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/NameOfKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/NullKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ObjectKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/PartialKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/PublicKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/RecordKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/SByteKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ScopedKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/SealedKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ShortKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/SizeOfKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/StaticKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/StringKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/StructKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/SwitchKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ThrowKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/TrueKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/TryKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/TypeOfKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/UIntKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/ULongKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/UShortKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/UncheckedKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/UnsafeKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/UsingKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/VarKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/VoidKeywordRecommenderTests.cs
  src/EditorFeatures/CSharpTest2/Recommendations/WhileKeywordRecommenderTests.cs
Labels: Area-IDE, Community

#76342 Introduce local variable supporting target-type new syntax
  src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs
  src/Features/CSharpTest/IntroduceVariable/IntroduceVariableTests.cs
  src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.IntroduceVariableCodeAction.cs
  src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.cs
  src/Features/VisualBasic/Portable/IntroduceVariable/VisualBasicIntroduceVariableService_IntroduceLocal.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Simplification/CSharpSimplifierOptions.cs
Labels: Area-IDE, Community, untriaged, VSCode

#76577 Continued Extract method cleanup
  src/EditorFeatures/CSharpTest/ExtractMethod/SelectionValidatorTests.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpExtractMethodService.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.Analyzer.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.ExpressionCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.MultipleStatementsCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.SingleStatementCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.TriviaResult.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.ExpressionResult.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.StatementResult.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionValidator.cs
  src/Features/Core/Portable/ExtractMethod/AbstractExtractMethodService.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.SymbolMapBuilder.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.AnalyzerResult.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.GeneratedCode.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.TriviaResult.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.TypeParameterCollector.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.VariableInfo.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.VariableSymbol.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.cs
  src/Features/Core/Portable/ExtractMethod/SelectionInfo.cs
  src/Features/Core/Portable/ExtractMethod/SelectionResult.cs
  src/Features/Core/Portable/ExtractMethod/SelectionValidator.cs
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicExtractMethodService.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.Analyzer.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.TriviaResult.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.ExpressionCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.MultipleStatementsCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.SingleStatementCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicSelectionResult.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicSelectionValidator.vb
Labels: Area-IDE, untriaged, VSCode

#76585 Continued Extract method cleanup (part 2)
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.ExpressionResult.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.StatementResult.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionValidator.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/SelectionInfo.cs
  src/Features/Core/Portable/ExtractMethod/SelectionResult.cs
  src/Features/Core/Portable/ExtractMethod/SelectionValidator.cs
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicSelectionResult.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicSelectionValidator.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SemanticModelExtensions.cs
Labels: Area-IDE, untriaged, VSCode

#76587 Cleanup Extract method code (part 3)
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodBase.cs
  src/EditorFeatures/CSharpTest/ExtractMethod/SelectionValidatorTests.cs
  src/EditorFeatures/VisualBasicTest/ExtractMethod/ExtractMethodTests.SelectionValidator.vb
  src/EditorFeatures/VisualBasicTest/ExtractMethod/ExtractMethodTests.vb
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.ExpressionResult.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.StatementResult.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionValidator.cs
  src/Features/Core/Portable/ExtractMethod/Enums.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.AnalyzerResult.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.VariableInfo.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.VariableSymbol.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.cs
  src/Features/Core/Portable/ExtractMethod/ParameterStyle.cs
  src/Features/Core/Portable/ExtractMethod/SelectionInfo.cs
  src/Features/Core/Portable/ExtractMethod/SelectionResult.cs
  src/Features/Core/Portable/ExtractMethod/SelectionValidator.cs
  src/Features/Core/Portable/ExtractMethod/VariableStyle.cs
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicSelectionResult.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicSelectionValidator.vb
Labels: Area-IDE, untriaged, VSCode

#76607 Change how tagging is done on PRs for 16.11
  azure-pipelines-official.yml
  azure-pipelines-pr-validation.yml
Labels: Area-Infrastructure, untriaged

#76615 Switch to more modern vb construct
  src/Analyzers/VisualBasic/Analyzers/ValidateFormatString/VisualBasicValidateFormatStringDiagnosticAnalyzer.vb
  src/Analyzers/VisualBasic/CodeFixes/AddAnonymousTypeMemberName/VisualBasicAddAnonymousTypeMemberNameCodeFixProvider.vb
  src/Analyzers/VisualBasic/CodeFixes/GenerateParameterizedMember/VisualBasicGenerateParameterizedMemberService.vb
  src/EditorFeatures/Test2/Expansion/AbstractExpansionTest.vb
  src/EditorFeatures/Test2/Simplification/AbstractSimplificationTests.vb
  src/EditorFeatures/TestUtilities2/Intellisense/TestState.vb
  src/EditorFeatures/VisualBasic/LineCommit/ContainingStatementInfo.vb
  src/EditorFeatures/VisualBasicTest/CodeActions/MoveType/BasicMoveTypeTestsBase.vb
  src/Features/VisualBasic/Portable/BraceCompletion/ParenthesisBraceCompletionService.vb
  src/Features/VisualBasic/Portable/Completion/CompletionProviders/InternalsVisibleToCompletionProvider.vb
  src/Features/VisualBasic/Portable/Completion/KeywordRecommenders/Declarations/ParameterModifiersKeywordRecommender.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.Analyzer.vb
  src/Features/VisualBasic/Portable/Highlighting/KeywordHighlighters/AccessorDeclarationHighlighter.vb
  src/Features/VisualBasic/Portable/Highlighting/KeywordHighlighters/ConstructorDeclarationHighlighter.vb
  src/Features/VisualBasic/Portable/Highlighting/KeywordHighlighters/MethodDeclarationHighlighter.vb
  src/Features/VisualBasic/Portable/Highlighting/KeywordHighlighters/OperatorDeclarationHighlighter.vb
  src/Features/VisualBasic/Portable/Highlighting/KeywordHighlighters/TryBlockHighlighter.vb
  src/Features/VisualBasic/Portable/Highlighting/KeywordHighlightingHelpers.vb
  src/Features/VisualBasicTest/Diagnostics/Suppression/SuppressionAllCodeTests.vb
  src/VisualStudio/VisualBasic/Impl/CodeModel/MethodXML/MethodXmlBuilder.vb
  src/VisualStudio/VisualBasic/Impl/CodeModel/VisualBasicCodeModelService.CodeModelEventCollector.vb
  src/VisualStudio/VisualBasic/Impl/CodeModel/VisualBasicCodeModelService.vb
  src/VisualStudio/VisualBasic/Impl/Help/VisualBasicHelpContextService.Visitor.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Extensions/SyntaxNodeExtensions.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SemanticFacts/VisualBasicSemanticFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/CodeGeneration/ExpressionGenerator.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/CodeGeneration/NamespaceGenerator.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ObjectCreationExpressionExtensions.vb
  src/Workspaces/VisualBasic/Portable/CodeCleanup/Providers/AddMissingTokensCodeCleanupProvider.vb
  src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb
  src/Workspaces/VisualBasic/Portable/Formatting/DefaultOperationProvider.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Rules/ElasticTriviaFormattingRule.vb
  src/Workspaces/VisualBasic/Portable/Formatting/Rules/NodeBasedFormattingRule.vb
  src/Workspaces/VisualBasic/Portable/Recommendations/VisualBasicRecommendationServiceRunner.vb
  src/Workspaces/VisualBasic/Portable/Simplification/Reducers/VisualBasicEscapingReducer.vb
  src/Workspaces/VisualBasic/Portable/Simplification/Reducers/VisualBasicExtensionMethodReducer.vb
  src/Workspaces/VisualBasic/Portable/Simplification/Reducers/VisualBasicVariableDeclaratorReducer.vb
  src/Workspaces/VisualBasic/Portable/Simplification/Simplifiers/AbstractVisualBasicSimplifier.vb
  src/Workspaces/VisualBasic/Portable/Simplification/Simplifiers/ExpressionSimplifier.vb
  src/Workspaces/VisualBasic/Portable/Simplification/Simplifiers/NameSimplifier.vb
  src/Workspaces/VisualBasic/Portable/Simplification/VisualBasicSimplificationService.Expander.vb
Labels: Area-IDE, untriaged, VSCode

#76614 Move schedule node in official yaml
  azure-pipelines-official.yml
Labels: Area-Infrastructure, untriaged

#76618 Update build task versions based on official build results
  azure-pipelines-official.yml
Labels: Area-Infrastructure, untriaged

#76611 Additional extract method cleanup.
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.Analyzer.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.ExpressionResult.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.StatementResult.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.cs
  src/Features/Core/Portable/ExtractMethod/InsertionPoint.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.SymbolMapBuilder.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.AnalyzerResult.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.GeneratedCode.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.TriviaResult.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.VariableInfo.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.VariableSymbol.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.cs
  src/Features/Core/Portable/ExtractMethod/SelectionResult.cs
  src/Features/Core/Portable/LanguageServices/SymbolDisplayService/AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.cs
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.Analyzer.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.ExpressionCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicSelectionResult.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/INamedTypeSymbolExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ITypeSymbolExtensions.SubstituteTypesVisitor.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ITypeSymbolExtensions.cs
Labels: Area-IDE, untriaged, VSCode

#76610 Reduce pooled array allocations in the SyntaxParser
  src/Compilers/CSharp/Portable/Parser/SyntaxParser.cs
Labels: Area-Compilers, untriaged

#76623 Ensure Location.None in additional locations can round trip correctly
  src/EditorFeatures/Test/Diagnostics/DiagnosticDataTests.cs
  src/Workspaces/Core/Portable/Diagnostics/DiagnosticData.cs
Labels: Area-Analyzers, Community, untriaged, VSCode

#76572 Document breaks due to preferring ReadOnlySpan over Span
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 10.md
Labels: Area-Compilers, Documentation, untriaged, Feature - First-class Span Types

#76296 Remove scope variance exceptions
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 10.md
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers

#76628 Use the target branch for bootstrap build documentation
  docs/contributing/Bootstrap Builds.md
  docs/contributing/README.md
  docs/contributing/bootstrap-builds.md
  eng/test-build-correctness.ps1
Labels: Area-Infrastructure, untriaged

#76619 Remove deprecated variable groups from 16.11
  azure-pipelines-official.yml
Labels: Area-Infrastructure, untriaged

#76638 Do not offer 'use auto prop' with ref-fields
  src/Analyzers/CSharp/Analyzers/UseAutoProperty/CSharpUseAutoPropertyAnalyzer.cs
  src/Analyzers/CSharp/Tests/UseAutoProperty/UseAutoPropertyTests.cs
  src/Analyzers/Core/Analyzers/UseAutoProperty/AbstractUseAutoPropertyAnalyzer.cs
  src/Analyzers/VisualBasic/Analyzers/UseAutoProperty/VisualBasicUseAutoPropertyAnalyzer.vb
Labels: Area-IDE, untriaged, VSCode

#76639 Update 'use compound expr' to support 'field keyword'
  src/Analyzers/CSharp/Analyzers/UseCompoundAssignment/CSharpUseCompoundAssignmentDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCompoundAssignment/CSharpUseCompoundCoalesceAssignmentDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/UseCompoundAssignment/UseCompoundAssignmentTests.cs
  src/Analyzers/CSharp/Tests/UseCompoundAssignment/UseCompoundCoalesceAssignmentTests.cs
  src/Analyzers/Core/Analyzers/UseCompoundAssignment/UseCompoundAssignmentUtilities.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFactsExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxKinds.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxKinds.vb
Labels: Area-IDE, untriaged, VSCode

#76629 Expose breakable range handler to Razor
  src/LanguageServer/Protocol/Handler/Breakpoints/ValidateBreakableRangeHandler.cs
  src/Tools/ExternalAccess/Razor/Cohost/Handlers/ValidateBreakableRange.cs
  src/Tools/ExternalAccess/Razor/ITextBufferExtensions.cs
Labels: Area-IDE, untriaged, VSCode

#76640 Make full source build pure NetCurrent
  docs/contributing/README.md
  docs/contributing/Target Framework Strategy.md
  docs/contributing/target-framework-strategy.md
  eng/targets/TargetFrameworks.props
Labels: Area-Infrastructure, untriaged

#76627 Remove need to pass generator parameter to helper methods
  src/Analyzers/CSharp/CodeFixes/AssignOutParameters/AbstractAssignOutParametersCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs
  src/Features/CSharp/Portable/CodeRefactorings/InlineMethod/CSharpInlineMethodRefactoringProvider.cs
  src/Features/CSharp/Portable/IntroduceParameter/CSharpIntroduceParameterCodeRefactoringProvider.cs
  src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs
  src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs
  src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CodeGeneration/AttributeGenerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CodeGeneration/CSharpFlagsEnumGenerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CodeGeneration/EnumMemberGenerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CodeGeneration/ExpressionGenerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CodeGeneration/FieldGenerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CodeGeneration/ParameterGenerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpSyntaxGeneratorInternal.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeGeneration/AbstractFlagsEnumGenerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/SyntaxGeneratorInternalExtensions/SyntaxGeneratorInternal.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/CodeGeneration/ExpressionGenerator.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/CodeGeneration/VisualBasicFlagsEnumGenerator.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/LanguageServices/VisualBasicSyntaxGeneratorInternal.vb
  src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb
Labels: Area-IDE, untriaged, Needs API Review, VSCode

#76599 Remove Edgio CDN usage to release/dev17.10
  eng/Directory.Packages.props
  src/Features/Core/Portable/SymbolSearch/Windows/SymbolSearchUpdateEngine.Update.cs
  src/VisualStudio/Core/Def/Storage/FileDownloader.cs
Labels: Area-IDE, untriaged, VSCode

#76642 Put WRN_InterceptsLocationAttributeUnsupportedSignature into .NET 9 warning wave
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs
  src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs
Labels: Area-Compilers, untriaged

#76644 Update configs for 17.13/17.14
  eng/Versions.props
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#76604 Remove Edgio CDN usage to release/dev17.8
  eng/Versions.props
  src/Tools/BuildBoss/BuildBoss.csproj
  src/VisualStudio/Core/Def/Storage/FileDownloader.cs
Labels: Area-IDE, untriaged

#76411 Simplify naming style preferences
  src/Analyzers/Core/CodeFixes/Naming/NamingExtensions.cs
  src/Compilers/Core/Portable/Collections/ImmutableArrayExtensions.cs
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/Microsoft.CodeAnalysis.CSharp.EditorFeatures.UnitTests.csproj
  src/EditorFeatures/Core/EditorConfigSettings/Data/NamingStyleSetting.cs
  src/EditorFeatures/Core/EditorConfigSettings/DataProvider/NamingStyles/NamingStyleSettingsProvider.cs
  src/EditorFeatures/Core/EditorConfigSettings/Updater/NamingStyles/EditorConfigNamingStylesExtensions.cs
  src/EditorFeatures/Core/EditorConfigSettings/Updater/NamingStyles/SourceTextExtensions.cs
  src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationName/DeclarationNameRecommender.cs
  src/Features/DiagnosticsTestUtilities/NamingStyles/NamingStylesTestOptionSets.cs
  src/LanguageServer/Protocol/Features/Options/SolutionAnalyzerConfigOptionsUpdater.cs
  src/LanguageServer/ProtocolUnitTests/Options/SolutionAnalyzerConfigOptionsUpdaterTests.cs
  src/VisualStudio/Core/Impl/Options/Style/NamingPreferences/NamingStyleOptionPageControl.xaml.cs
  src/VisualStudio/Core/Impl/Options/Style/NamingPreferences/NamingStyleOptionPageViewModel.cs
  src/Workspaces/CoreTest/EditorConfigParsing/EditorConfigFileParserTests.cs
  src/Workspaces/CoreTest/EditorConfigParsing/NamingStyleParserTests.cs
  src/Workspaces/CoreTest/Options/EditorConfigCodeStyleParserTests.cs
  src/Workspaces/CoreTest/Options/EditorConfigNamingStyleParserTests.cs
  src/Workspaces/CoreTest/Options/NamingStylePreferencesTests.cs
  src/Workspaces/CoreTestUtilities/Options/NamingStyleTestUtilities.cs
  src/Workspaces/CoreTestUtilities/OptionsCollection.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/EditorConfig/Parsing/EditorConfigOption.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/EditorConfig/Parsing/EditorConfigOption`1.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/EditorConfig/Parsing/EditorConfigParser.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/EditorConfig/Parsing/IEditorConfigOptionAccumulator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/EditorConfig/Parsing/NamingStyles/NamingStyleOptionAccumulator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/EditorConfig/EditorConfigNamingStyleParser.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_NamingRule.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_NamingStyle.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_SymbolSpec.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingRule.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/Serialization/NamingStylePreferences.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/Serialization/NamingStylePreferencesEditorConfigSerializer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/Serialization/SerializableNamingRule.cs
Labels: Area-IDE, untriaged, VSCode

#76606 Remove Edgio CDN usage to release/dev17.6
  eng/Versions.props
  src/Tools/BuildBoss/BuildBoss.csproj
  src/VisualStudio/Core/Def/Storage/FileDownloader.cs
Labels: Area-Infrastructure, untriaged

#76646 Do not offer to use expression body on a lambda if it would cause overload resolution to change.
  src/Analyzers/CSharp/Analyzers/UseExpressionBodyForLambda/UseExpressionBodyForLambdaDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseExpressionBodyForLambda/UseExpressionBodyForLambdaHelpers.cs
  src/Analyzers/CSharp/CodeFixes/UseExpressionBodyForLambda/UseExpressionBodyForLambdaCodeActionHelpers.cs
  src/Analyzers/CSharp/CodeFixes/UseExpressionBodyForLambda/UseExpressionBodyForLambdaCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/UseExpressionBodyForLambda/UseExpressionBodyForLambdasAnalyzerTests.cs
  src/Features/CSharp/Portable/UseExpressionBodyForLambda/UseExpressionBodyForLambdaCodeRefactoringProvider.cs
Labels: Area-IDE, untriaged, VSCode

#76652 Fix FAR/rename with method type parameters
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.MethodTypeParameterTypeSymbol.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.vb
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractTypeParameterSymbolReferenceFinder.cs
  src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/MethodTypeParameterSymbolReferenceFinder.cs
Labels: Area-IDE, untriaged, VSCode

#76648 Move to 1ES PT
  azure-pipelines-official.yml
  azure-pipelines-pr-validation.yml
  eng/TSAConfig.gdntsa
  eng/pipelines/insert.yml
Labels: Area-Infrastructure, untriaged

#76544 Reduce allocations in the C# lexer ctor
  src/Compilers/CSharp/Portable/Parser/Lexer.cs
  src/Compilers/CSharp/Portable/Parser/LexerCache.cs
  src/Compilers/Core/Portable/Syntax/InternalSyntax/SyntaxListBuilder.cs
Labels: Area-Compilers, untriaged

#76653 Switch to collection expressions
  src/Analyzers/CSharp/Analyzers/ConvertNamespace/ConvertToBlockScopedNamespaceDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/ConvertNamespace/ConvertToFileScopedNamespaceDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/ConvertProgram/ConvertToTopLevelStatementsDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/MakeLocalFunctionStatic/MakeLocalFunctionStaticDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/MakeStructMemberReadOnly/CSharpMakeStructMemberReadOnlyAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/MakeStructReadOnly/CSharpMakeStructReadOnlyDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/NewLines/ConstructorInitializerPlacement/ConstructorInitializerPlacementDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/RemoveConfusingSuppression/CSharpRemoveConfusingSuppressionDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/SimplifyPropertyPattern/CSharpSimplifyPropertyPatternDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForArrayDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForEmptyDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForFluentDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseImplicitObjectCreation/CSharpUseImplicitObjectCreationDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/NewLines/ConsecutiveStatementPlacement/AbstractConsecutiveStatementPlacementDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/NewLines/MultipleBlankLines/AbstractMultipleBlankLinesDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseCompoundAssignment/AbstractUseCompoundAssignmentDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseConditionalExpression/AbstractUseConditionalExpressionDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer_IfStatement.cs
  src/EditorFeatures/CSharpTest/EditAndContinue/ActiveStatementTrackingServiceTests.cs
  src/EditorFeatures/CSharpTest/Formatting/RazorLineFormattingOptionsTests.cs
  src/EditorFeatures/Test/Completion/FileSystemCompletionHelperTests.cs
  src/EditorFeatures/Test/Utilities/SymbolEquivalenceComparerTests.cs
  src/EditorFeatures/Text/Extensions.SnapshotSourceText.cs
  src/Features/CSharp/Portable/CodeRefactorings/EnableNullable/EnableNullableCodeRefactoringProvider.FixAllProvider.cs
  src/Features/Core/Portable/AddImport/CodeActions/InstallPackageAndAddImportCodeAction.cs
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionCodeFixProvider.FixAllProvider.cs
  src/Features/Core/Portable/SimplifyThisOrMe/AbstractSimplifyThisOrMeDiagnosticAnalyzer.cs
  src/Features/Core/Portable/SplitOrMergeIfStatements/AbstractMergeIfStatementsCodeRefactoringProvider.cs
  src/Features/Core/Portable/SplitOrMergeIfStatements/Consecutive/AbstractSplitIntoConsecutiveIfStatementsCodeRefactoringProvider.cs
  src/Features/Test/EditAndContinue/RemoteEditAndContinueServiceTests.cs
  src/Features/TestUtilities/EditAndContinue/EditAndContinueWorkspaceTestBase.cs
  src/LanguageServer/ProtocolUnitTests/Definitions/GoToDefinitionTests.cs
  src/LanguageServer/ProtocolUnitTests/References/FindImplementationsTests.cs
  src/Test/PdbUtilities/EditAndContinue/EditAndContinueTest.GenerationVerifier.cs
  src/VisualStudio/CSharp/Test/DocumentOutline/DocumentOutlineTests.cs
  src/VisualStudio/CSharp/Test/EditorConfigSettings/DataProvider/DataProviderTests.MockAnalyzerReference.cs
  src/VisualStudio/CSharp/Test/Interactive/Commands/ResetInteractiveTests.cs
  src/VisualStudio/CSharp/Test/ProjectSystemShim/CPS/AnalyzersTests.cs
  src/VisualStudio/CSharp/Test/ProjectSystemShim/CPS/CSharpCompilerOptionsTests.cs
  src/VisualStudio/CSharp/Test/ProjectSystemShim/TestEvaluationData.cs
  src/VisualStudio/Core/Def/EditAndContinue/EditAndContinueFeedbackDiagnosticFileProvider.cs
  src/VisualStudio/Core/Def/EditorConfigSettings/SettingsEditorPane.SearchFilter.cs
  src/VisualStudio/Core/Def/ErrorReporting/VisualStudioErrorReportingService.ExceptionFormatting.cs
  src/VisualStudio/Core/Def/NavigateTo/RoslynSearchResultViewFactory.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpNewDocumentFormatting.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/OptionPages/ForceLowMemoryModePage.cs
  src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs
  src/Workspaces/Core/Portable/Workspace/CommandLineProject.cs
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectDependencyGraph_AddProject.cs
  src/Workspaces/CoreTest/BatchFixAllProviderTests.cs
  src/Workspaces/CoreTest/WorkspaceTests/WorkspaceReferenceTests.cs
  src/Workspaces/CoreTestUtilities/Options/OptionsTestHelpers.cs
  src/Workspaces/CoreTestUtilities/Workspaces/TestHostDocument.cs
  src/Workspaces/Remote/Core/ExternalAccess/Pythia/Api/PythiaRemoteServiceCallbackDispatcherRegistry.cs
  src/Workspaces/Remote/Core/ExternalAccess/UnitTesting/Api/UnitTestingRemoteServiceCallbackDispatcherRegistry.cs
Labels: Area-IDE, untriaged, VSCode

#76655 [17.13] Revert "Remove scope variance exceptions"
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 10.md
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers, untriaged

#76658 Change SupportedPlatformData to use ImmutableArrays
  src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/SymbolCompletionItem.cs
  src/Features/Core/Portable/QuickInfo/CommonSemanticQuickInfoProvider.cs
  src/Features/Core/Portable/Shared/Utilities/SupportedPlatformData.cs
  src/Features/Core/Portable/SignatureHelp/AbstractSignatureHelpProvider.cs
Labels: Area-IDE, untriaged, VSCode

#76668 Add backport github action to backport a PR to a different branch
  .github/workflows/backport.yml
Labels: Area-Infrastructure, untriaged

#76670 Push task-ifying extract-method return type to the code gen stage.
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.ExpressionCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.StatementResult.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.AnalyzerResult.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.cs
  src/Features/Core/Portable/ExtractMethod/SelectionResult.cs
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.ExpressionCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.MultipleStatementsCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.SingleStatementCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicSelectionResult.vb
Labels: Area-IDE, untriaged, VSCode

#76667 Revert "Remove scope variance exceptions" (#76655)
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 10.md
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs
  src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers, untriaged

#76673 Share code in extract method
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/SelectionResult.cs
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.vb
Labels: Area-IDE, untriaged, VSCode

#76663 Clean up test discovery
  src/Tools/PrepareTests/MinimizeUtil.cs
  src/Tools/PrepareTests/TestDiscovery.cs
  src/Tools/TestDiscoveryWorker/Program.cs
  src/Tools/TestDiscoveryWorker/README.md
  src/Tools/TestDiscoveryWorker/TestDiscoveryWorker.csproj
Labels: Area-Infrastructure, untriaged

#76395 ResultProvider: Consume DkmClrModuleInstance.GetMetaDataImportHolder
  eng/Directory.Packages.props
  src/ExpressionEvaluator/Core/Source/ResultProvider/Formatter.cs
  src/ExpressionEvaluator/Core/Test/ResultProvider/Debugger/Engine/DkmClrModuleInstance.cs
  src/ExpressionEvaluator/Core/Test/ResultProvider/Debugger/Engine/DkmMetadataImportHolder.cs
Labels: Area-Interactive, Community, untriaged

#76636 Ensure VB parser is disposed
  src/Compilers/VisualBasic/Portable/Scanner/Directives.vb
  src/Compilers/VisualBasic/Portable/Scanner/XmlDocComments.vb
  src/Compilers/VisualBasic/Portable/Syntax/SyntaxNodeFactories.vb
  src/Compilers/VisualBasic/Portable/Syntax/VisualBasicSyntaxTree.vb
Labels: Area-Compilers, untriaged

#76684 Do not offer to to convert `new X(e)` to `[.. e]` when the type does not fullfill the collection expr pattern.
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForNewDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForNewTests.cs
  src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests_CollectionExpression.cs
Labels: Area-IDE, untriaged, VSCode

#76678 Classify the langword attribute value in DocComments
  src/EditorFeatures/CSharpTest/Classification/SyntacticClassifierTests.cs
  src/EditorFeatures/VisualBasicTest/Classification/SyntacticClassifierTests.vb
  src/Workspaces/CSharp/Portable/Classification/ClassificationHelpers.cs
  src/Workspaces/CSharp/Portable/Classification/Worker_DocumentationComments.cs
  src/Workspaces/VisualBasic/Portable/Classification/ClassificationHelpers.vb
  src/Workspaces/VisualBasic/Portable/Classification/Worker.DocumentationCommentClassifier.vb
Labels: Area-IDE, untriaged, VSCode

#75970 Unskip some integration tests
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicEditAndContinue.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicGoToDefinition.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/Workspace/WorkspaceBase.cs
Labels: Area-Infrastructure, untriaged

#76689 Remove unnecessary code from extract method
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.cs
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.vb
Labels: Area-IDE, untriaged, VSCode

#76696 Remove pointless xml doc comment tags
  src/Analyzers/CSharp/Analyzers/UseSystemThreadingLock/CSharpUseSystemThreadingLockDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/ConvertToRecord/ConvertToRecordHelpers.cs
  src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseAutoProperty/AbstractUseAutoPropertyAnalyzer.cs
  src/Analyzers/Core/CodeFixes/AddParameter/AddParameterService.cs
  src/Dependencies/PooledObjects/PooledStringBuilder.cs
  src/EditorFeatures/Core/InlineRename/IEditorInlineRenameService.cs
  src/EditorFeatures/Core/Shared/Extensions/ITextBufferEditExtensions.cs
  src/EditorFeatures/Core/Shared/Extensions/SpanExtensions.cs
  src/EditorFeatures/Test2/Peek/PeekTests.vb
  src/EditorFeatures/TestUtilities/Workspaces/EditorTestWorkspace.cs
  src/Features/CSharp/Portable/ConvertLinq/CSharpConvertLinqQueryToForEachProvider.cs
  src/Features/CSharp/Portable/ConvertLinq/ConvertForEachToLinqQuery/AbstractConverter.cs
  src/Features/CSharp/Portable/Copilot/CSharpCopilotCodeFixProvider.cs
  src/Features/Core/Portable/ChangeSignature/IChangeSignatureOptionsService.cs
  src/Features/Core/Portable/Completion/CharacterSetModificationRule.cs
  src/Features/Core/Portable/Completion/CompletionItem.cs
  src/Features/Core/Portable/Completion/CompletionItemRules.cs
  src/Features/Core/Portable/Completion/CompletionList.cs
  src/Features/Core/Portable/Copilot/ICopilotOptionsService.cs
  src/Features/Core/Portable/EmbeddedLanguages/StackFrame/StackFrameLexer.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Features/Core/Portable/ExtractMethod/SelectionResult.cs
  src/Features/Core/Portable/GenerateFromMembers/GenerateFromMembersHelpers.cs
  src/Features/Core/Portable/QuickInfo/IndentationHelper.cs
  src/LanguageServer/ExternalAccess/VisualDiagnostics/Contracts/IVisualDiagnosticsLanguageService.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/Services/BrokeredServiceBridgeManifest/IBrokeredServiceBridgeManifest.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/DotnetCliHelper.cs
  src/LanguageServer/Protocol/Extensions/Extensions.cs
  src/Scripting/Core/ScriptOptions.cs
  src/Test/Perf/Utilities/PerfTestBase.cs
  src/Test/Perf/Utilities/RelativeDirectory.cs
  src/Tools/BuildBoss/CompilerNuGetCheckerUtil.cs
  src/VisualStudio/Core/Def/CodeMarkers/ManagedCodeMarkers.cs
  src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspaceImpl.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/AutomationElementExtensions.cs
  src/VisualStudio/VisualBasic/Impl/Venus/ContainedLanguageStaticEventBinding.vb
  src/VisualStudio/Xaml/Impl/Features/InlineRename/IXamlRenameInfo.cs
  src/Workspaces/CSharp/Portable/Rename/CSharpRenameRewriterLanguageService.cs
  src/Workspaces/CSharp/Portable/Simplification/Simplifiers/NameSimplifier.cs
  src/Workspaces/Core/MSBuild/MSBuild/ProjectMap.cs
  src/Workspaces/Core/Portable/Editing/SymbolEditor.cs
  src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder.cs
  src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs
  src/Workspaces/Core/Portable/Rename/IRenameRewriterLanguageService.cs
  src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs
  src/Workspaces/Core/Portable/Utilities/Documentation/XmlDocumentationProvider.cs
  src/Workspaces/Core/Portable/Workspace/Host/HostWorkspaceServices.cs
  src/Workspaces/Core/Portable/Workspace/Solution/AssetPath.cs
  src/Workspaces/Core/Portable/Workspace/Solution/TextAndVersion.cs
  src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentStates.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTokenExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.DataFlowAnalyzer.FlowGraphAnalysisData.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/AbstractSpeculationAnalyzer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/SpecializedTasks.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions.cs
Labels: Area-IDE, untriaged, VSCode

#76686 Support Extracting method with complex flow control cosntructs in them.
  src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs
  src/EditorFeatures/CSharpTest/ExtractMethod/SelectionValidatorTests.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.Analyzer.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.ExpressionCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.cs
  src/Features/CSharpTest/ExtractMethod/ExtractMethodCodeRefactoringTests.cs
  src/Features/Core/Portable/ExtractMethod/ExtractMethodFlowControlInformation.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.AnalyzerResult.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.CodeGenerator.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.cs
  src/Features/Core/Portable/ExtractMethod/SelectionResult.cs
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.Analyzer.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicSelectionResult.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeGeneration/CSharpSyntaxTokens.cs
Labels: Area-IDE, untriaged, VSCode

#76701 Fix race generating Microsoft.Managed.Core.CurrentVersions.targets
  src/Compilers/Core/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.csproj
Labels: Area-Infrastructure, Community, untriaged

#76660 CodeGenerator.EmitStackAlloc - Avoid capturing blob array
  src/Compilers/CSharp/Portable/CodeGen/EmitStackAllocInitializer.cs
Labels: Area-Compilers, Community, untriaged

#76710 Add additional tests for string escape sequences
  src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests_StringEscapes.cs
Labels: Area-IDE, untriaged

#76437 Add option for choosing stdio as the LSP communication channel
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Utilities/LanguageServerTestComposition.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Program.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/ServerConfigurationFactory.cs
Labels: Area-Infrastructure, Community, untriaged, VSCode

#76711 Adding checks for mutable structs.
  src/Analyzers/CSharp/Analyzers/RemoveUnnecessaryLambdaExpression/CSharpRemoveUnnecessaryLambdaExpressionDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/RemoveUnnecessaryLambdaExpression/RemoveUnnecessaryLambdaExpressionTests.cs
Labels: Area-IDE, Community, untriaged, VSCode

#76703 Rework our Helix Process
  src/Tools/Source/RunTests/AssemblyScheduler.cs
  src/Tools/Source/RunTests/HelixTestRunner.cs
  src/Tools/Source/RunTests/Program.cs
  src/Tools/Source/RunTests/TestRunner.cs
Labels: Area-Infrastructure, untriaged

#76698 Always use .OriginalDefinition uniformly in the unread-members analyzer
  src/Analyzers/Core/Analyzers/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs
Labels: Area-Analyzers, untriaged, VSCode

#76724 Do not lift type parameters in extract method declared within the selected region
  src/Features/CSharpTest/ExtractMethod/ExtractMethodCodeRefactoringTests.cs
  src/Features/Core/Portable/ExtractMethod/MethodExtractor.Analyzer.cs
Labels: Area-IDE, untriaged, VSCode

#76723 Fix ExtractMethod in VB elseif blocks
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.CallSiteContainerRewriter.vb
  src/Features/VisualBasicTest/ExtractMethod/ExtractMethodTests.vb
Labels: Area-IDE, untriaged, VSCode

#76734 Properly simplify pattern when converting to pattern matching
  src/Analyzers/CSharp/CodeFixes/UsePatternCombinators/CSharpUsePatternCombinatorsCodeFixProvider.cs
  src/Features/CSharpTest/UsePatternCombinators/CSharpUsePatternCombinatorsDiagnosticAnalyzerTests.cs
Labels: Area-IDE, untriaged, VSCode

#76717 Disable extract class/interface to a new file when unsupported by the workspace.
  src/EditorFeatures/TestUtilities/ExtractInterface/TestExtractInterfaceOptions.cs
  src/Features/CSharpTest/ExtractClass/ExtractClassTests.cs
  src/Features/Core/Portable/ExtractClass/AbstractExtractClassRefactoringProvider.cs
  src/Features/Core/Portable/ExtractInterface/AbstractExtractInterfaceService.cs
  src/Features/Core/Portable/ExtractInterface/IExtractInterfaceOptionsService.cs
  src/Features/ExternalAccess/OmniSharp/Internal/ExtractInterface/OmniSharpExtractInterfaceOptionsService.cs
  src/Features/ExternalAccess/OmniSharp/Internal/Notification/OmniSharpNotificationService.cs
  src/VisualStudio/Core/Def/CommonControls/NewTypeDestinationSelection.xaml
  src/VisualStudio/Core/Def/CommonControls/NewTypeDestinationSelectionViewModel.cs
  src/VisualStudio/Core/Def/ExtractClass/ExtractClassViewModel.cs
  src/VisualStudio/Core/Def/ExtractClass/VisualStudioExtractClassOptionsService.cs
  src/VisualStudio/Core/Def/ExtractInterface/ExtractInterfaceDialogViewModel.cs
  src/VisualStudio/Core/Def/ExtractInterface/VisualStudioExtractInterfaceOptionsService.cs
  src/VisualStudio/Core/Test/CommonControls/NewTypeDestinationSelectionViewModelTests.vb
  src/VisualStudio/Core/Test/ExtractInterface/ExtractInterfaceViewModelTests.vb
Labels: Area-IDE, untriaged, UX Review Not Required, VSCode

#76737 Proffer CssVisualDiagnosticsService brokered service from C# DevKit to C# Extension
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/Services/Descriptors.cs
  src/Workspaces/Remote/Core/BrokeredServiceDescriptors.cs
Labels: Area-IDE, Community, untriaged, VSCode

#76675 Ensure unconverted elements are converted when on LHS
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
Labels: Area-Compilers, untriaged

#76744 Change partial keyword recommender to better handle partial member syntax
  src/EditorFeatures/CSharpTest2/Recommendations/PartialKeywordRecommenderTests.cs
  src/Features/CSharp/Portable/Completion/KeywordRecommenders/PartialKeywordRecommender.cs
Labels: Area-IDE, untriaged, VSCode

#76745 Fix ordering of 'params' vs 'scoped' in metadata as source
  src/EditorFeatures/Test/MetadataAsSource/AbstractMetadataAsSourceTests.TestContext.cs
  src/EditorFeatures/Test/MetadataAsSource/AbstractMetadataAsSourceTests.cs
  src/EditorFeatures/Test/MetadataAsSource/MetadataAsSourceTests.CSharp.cs
  src/EditorFeatures/Test/Microsoft.CodeAnalysis.EditorFeatures.UnitTests.csproj
  src/Workspaces/CoreTestUtilities/Workspaces/TestWorkspace_XmlConsumption.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpSyntaxGeneratorInternal.cs
Labels: Area-IDE, untriaged, VSCode

#76746 Hook brace-matching up to the 'responsive completion' editor option
  src/EditorFeatures/CSharp/AutomaticCompletion/CSharpBraceCompletionServiceFactory.cs
  src/EditorFeatures/Core/AutomaticCompletion/BraceCompletionSessionProvider.BraceCompletionSession.cs
  src/EditorFeatures/Core/AutomaticCompletion/BraceCompletionSessionProvider.cs
  src/Features/CSharp/Portable/BraceCompletion/LessAndGreaterThanBraceCompletionService.cs
  src/Features/Core/Portable/BraceCompletion/AbstractBraceCompletionService.cs
Labels: Area-IDE, untriaged, VSCode

#76750 Change ideal Helix execution time
  src/Tools/Source/RunTests/AssemblyScheduler.cs
Labels: Area-Infrastructure, untriaged

#76261 Consider silly cyclic assignment in scoped variance
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
Labels: Area-Compilers, untriaged, Feature - Ref Fields

#76300 Prefer ReadOnlySpan over Span as better conversion target
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Test/Emit3/FirstClassSpanTests.cs
Labels: Area-Compilers, untriaged, Feature - First-class Span Types

#76036 Emit opted-in string literals into data section as UTF8
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs
  src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit/Emit/EmitErrorTests.cs
  src/Compilers/CSharp/Test/Emit/Emit/EmitMetadataTests.cs
  src/Compilers/Core/Portable/CodeGen/PrivateImplementationDetails.cs
  src/Compilers/Core/Portable/Compilation/Compilation.cs
  src/Compilers/Core/Portable/Emit/CommonPEModuleBuilder.cs
  src/Compilers/Core/Portable/InternalUtilities/StringExtensions.cs
  src/Compilers/Core/Portable/PEWriter/Members.cs
  src/Compilers/Core/Portable/PEWriter/MethodDefinitionBase.cs
  src/Compilers/Core/Portable/PEWriter/ParameterDefinitionBase.cs
  src/Compilers/Core/Portable/PEWriter/ReturnValueParameter.cs
  src/Compilers/Core/Portable/PEWriter/RootModuleStaticConstructor.cs
  src/Compilers/Core/Portable/PEWriter/RootModuleType.cs
  src/Compilers/Core/Portable/PEWriter/StaticConstructor.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/Core/Portable/WellKnownTypes.cs
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
Labels: Area-Compilers, untriaged, Feature - String Literals in Data Section as UTF8

#76139 Add spec for the data section string literals feature
  docs/features/string-literals-data-section.md
Labels: Area-Compilers, Documentation, Feature - String Literals in Data Section as UTF8

#76760 Mark feature as complete: data section string literals
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation, untriaged, Feature - String Literals in Data Section as UTF8

#76761 Fixup 'add import on paste' to respect import ordering and grouping
  src/EditorFeatures/CSharp/AddImports/CSharpAddImportsPasteCommandHandler.cs
  src/EditorFeatures/CSharpTest/AddMissingImports/CSharpAddMissingImportsRefactoringProviderTests.cs
  src/EditorFeatures/Core/ExternalAccess/UnitTestGenerator/Api/UnitTestGeneratorAddMissingImportsFeatureServiceAccessor.cs
  src/EditorFeatures/VisualBasicTest/AddMissingImports/VisualBasicAddMissingImportsRefactoringProviderTests.vb
  src/Features/CSharp/Portable/AddImport/CSharpAddMissingImportsFeatureService.cs
  src/Features/CSharp/Portable/CodeRefactorings/AddMissingImports/CSharpAddMissingImportsRefactoringProvider.cs
  src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs
  src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsRefactoringProvider.cs
  src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AddMissingImportsAnalysisResult.cs
  src/Features/Core/Portable/CodeRefactorings/AddMissingImports/IAddMissingImportsFeatureService.cs
  src/Features/VisualBasic/Portable/AddImport/VisualBasicAddMissingImportsFeatureService.vb
  src/Features/VisualBasic/Portable/CodeRefactorings/AddMissingImports/VisualBasicAddMissingImportsRefactoringProvider.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/TypeSyntaxComparer.cs
Labels: Area-IDE, untriaged, VSCode

#76755 Bump Razor bits in C# extension
  eng/Directory.Packages.props
Labels: Area-Infrastructure, untriaged

#76749 Test layering fixes
  src/EditorFeatures/DiagnosticsTestUtilities/Microsoft.CodeAnalysis.EditorFeatures.DiagnosticsTests.Utilities.csproj
  src/EditorFeatures/Test2/GoToBase/GoToBaseTestsBase.vb
  src/EditorFeatures/Test2/GoToImplementation/GoToImplementationTests.vb
  src/EditorFeatures/TestUtilities/EditAndContinue/MockHotReloadLogger.cs
  src/EditorFeatures/TestUtilities/EditAndContinue/MockManagedHotReloadService.cs
  src/EditorFeatures/TestUtilities/FindUsages/StubStreamingFindUsagesPresenter.cs
  src/EditorFeatures/TestUtilities/Options/OptionSerializerTests.cs
  src/EditorFeatures/TestUtilities/Workspaces/EditorTestWorkspace.cs
  src/Features/DiagnosticsTestUtilities/Microsoft.CodeAnalysis.Features.DiagnosticsTests.Utilities.csproj
  src/Features/Test/FindUsages/DefinitionItemFactoryTests.cs
  src/Features/TestUtilities/Options/TestOptionsProvider.cs
  src/LanguageServer/Protocol.TestUtilities/Diagnostics/DiagnosticProviderTestUtilities.cs
  src/LanguageServer/Protocol.TestUtilities/Diagnostics/TestDiagnosticAnalyzerDriver.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
  src/Workspaces/CoreTest/UtilityTest/IntervalTreeTests.cs
  src/Workspaces/CoreTestUtilities/TestExportJoinableTaskContext+DenyExecutionSynchronizationContext.cs
  src/Workspaces/CoreTestUtilities/Workspaces/TestWorkspace`1.cs
Labels: Area-IDE, untriaged, VSCode

#75400 Support modifiers with simple lambda parameters.
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 10.md
  src/Compilers/CSharp/Portable/Binder/Binder_Lambda.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/LambdaConversionResult.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/ParameterHelpers.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit3/RefReadonlyParameterTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/SimpleLambdaParametersWithModifiersTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/Source/NullablePublicAPITests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationScopeParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/LambdaAttributeParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/LambdaParameterParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/LambdaReturnTypeParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ParserErrorMessageTests.cs
Labels: Area-Compilers, untriaged

#76770 Add feature to convert from an explicitly typed lambda to an implicitly typed one.
  src/Analyzers/CSharp/Analyzers/CSharpAnalyzers.projitems
  src/Analyzers/CSharp/Analyzers/CSharpAnalyzersResources.resx
  src/Analyzers/CSharp/Analyzers/CodeStyle/CSharpAnalyzerOptionsProvider.cs
  src/Analyzers/CSharp/Analyzers/UseImplicitlyTypedLambdaExpression/CSharpUseImplicitlyTypedLambdaExpressionDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.cs.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.de.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.es.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.fr.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.it.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.ja.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.ko.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.pl.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.pt-BR.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.ru.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.tr.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.zh-Hans.xlf
  src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.zh-Hant.xlf
  src/Analyzers/CSharp/CodeFixes/CSharpCodeFixes.projitems
  src/Analyzers/CSharp/CodeFixes/UseImplicitlyTypedLambdaExpression/CSharpUseImplicitObjectCreationCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/CSharpAnalyzers.UnitTests.projitems
  src/Analyzers/CSharp/Tests/UseImplicitlyTypedLambdaExpression/UseImplicitlyTypedLambdaExpressionTests.cs
  src/Analyzers/Core/Analyzers/EnforceOnBuildValues.cs
  src/Analyzers/Core/Analyzers/IDEDiagnosticIds.cs
  src/Analyzers/Core/CodeFixes/PredefinedCodeFixProviderNames.cs
  src/EditorFeatures/Test/Diagnostics/IDEDiagnosticIDConfigurationTests.cs
  src/Features/RulesMissingDocumentation.md
  src/VisualStudio/CSharp/Impl/CSharpVSResources.resx
  src/VisualStudio/CSharp/Impl/EditorConfigSettings/DataProvider/CodeStyle/CSharpCodeStyleSettingsProvider.cs
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.cs.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.de.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.es.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.fr.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.it.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.ja.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.ko.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.pl.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.pt-BR.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.ru.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.tr.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.zh-Hans.xlf
  src/VisualStudio/CSharp/Impl/xlf/CSharpVSResources.zh-Hant.xlf
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
  src/VisualStudio/Core/Test/Options/CSharpEditorConfigGeneratorTests.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeStyle/CSharpCodeStyleOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Simplification/CSharpSimplifierOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/SignatureComparer.cs
Labels: Area-Compilers, untriaged, VSCode

#76780 Update 'use nameof instead of typeof' to support generic types
  src/Analyzers/CSharp/Analyzers/ConvertTypeofToNameof/CSharpConvertTypeOfToNameOfDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/ConvertTypeOfToNameOf/CSharpConvertTypeOfToNameOfCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseUnboundGenericTypeInNameOf/CSharpUseUnboundGenericTypeInNameOfCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/ConvertTypeOfToNameOf/ConvertTypeOfToNameOfTests.cs
  src/Analyzers/Core/Analyzers/ConvertTypeofToNameof/AbstractConvertTypeOfToNameOfDiagnosticAnalyzer.cs
  src/Analyzers/Core/CodeFixes/ConvertTypeOfToNameOf/AbstractConvertTypeOfToNameOfCodeFixProvider.cs
  src/Analyzers/VisualBasic/Analyzers/ConvertTypeofToNameof/VisualBasicConvertTypeOfToNameOfDiagnosticAnalyzer.vb
  src/Analyzers/VisualBasic/CodeFixes/ConvertTypeOfToNameOf/VisualBasicConvertGetTypeToNameOfCodeFixProvider.vb
Labels: Area-IDE, untriaged, VSCode

#76671 Field-backed properties: report diagnostic for variable named field declared in accessor
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 10.md
  src/Compilers/CSharp/Portable/Binder/Binder.QueryTranslationState.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Lambda.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Syntax/Syntax/FieldAndValueKeywordTests.cs
Labels: Area-Compilers, untriaged, Feature - Field Keyword

#76753 Move impl of ILspWorkpace to EditorTestWorkspace/LspTestWorkspace
  src/EditorFeatures/Test/MetadataAsSource/AbstractMetadataAsSourceTests.TestContext.cs
  src/EditorFeatures/TestUtilities/Workspaces/EditorTestWorkspace.cs
  src/LanguageServer/Protocol.TestUtilities/Microsoft.CodeAnalysis.LanguageServer.Protocol.Test.Utilities.csproj
  src/LanguageServer/Protocol.TestUtilities/Workspaces/LspTestWorkspace.cs
  src/LanguageServer/ProtocolUnitTests/Options/SolutionAnalyzerConfigOptionsUpdaterTests.cs
  src/Workspaces/CoreTestUtilities/Workspaces/TestWorkspace.cs
  src/Workspaces/CoreTestUtilities/Workspaces/TestWorkspace_ILspWorkspace.cs
  src/Workspaces/CoreTestUtilities/Workspaces/TestWorkspace_XmlConsumption.cs
  src/Workspaces/CoreTestUtilities/Workspaces/TestWorkspace`1.cs
Labels: Area-IDE, untriaged, VSCode

#76588 Forbid unsafe types in records
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 10.md
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs
  src/Compilers/CSharp/Portable/Symbols/MemberSymbolExtensions.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberFieldSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEquals.cs
  src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/RecordTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/UnsafeTests.cs
Labels: Area-Compilers, Feature - Records

#76269 Update regex parsing to latest .Net core parsing (and diagnostic messages).
  src/EditorFeatures/CSharpTest2/EmbeddedLanguages/Json/CSharpJsonParserTests.cs
  src/EditorFeatures/CSharpTest2/EmbeddedLanguages/RegularExpressions/CSharpRegexParserTests.cs
  src/EditorFeatures/CSharpTest2/EmbeddedLanguages/RegularExpressions/CSharpRegexParserTests_BasicTests.cs
  src/EditorFeatures/CSharpTest2/EmbeddedLanguages/RegularExpressions/CSharpRegexParserTests_DotnetNegativeTests.cs
  src/EditorFeatures/CSharpTest2/EmbeddedLanguages/RegularExpressions/CSharpRegexParserTests_RealWorld.cs
  src/EditorFeatures/CSharpTest2/EmbeddedLanguages/RegularExpressions/CSharpRegexParserTests_ReferenceTests.cs
  src/EditorFeatures/CSharpTest2/Microsoft.CodeAnalysis.CSharp.EditorFeatures2.UnitTests.csproj
  src/EditorFeatures/CSharpTest2/Recommendations/KeywordRecommenderTests.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/IRegexNodeVisitor.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexClassifier.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/RegexKind.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/RegexLexer.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/RegexNodes.cs
  src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/RegexParser.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/EmbeddedLanguages/Common/EmbeddedDiagnostic.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/EmbeddedLanguages/Common/EmbeddedSyntaxToken.cs
Labels: Area-IDE, untriaged, VSCode

#76712 VB: Don't capture conditional access receiver into a temp local during lowering.
  src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/AbstractFlowPass.vb
  src/Compilers/VisualBasic/Portable/BoundTree/BoundLoweredConditionalAccess.vb
  src/Compilers/VisualBasic/Portable/BoundTree/BoundNodes.xml
  src/Compilers/VisualBasic/Portable/CodeGen/EmitAddress.vb
  src/Compilers/VisualBasic/Portable/CodeGen/EmitExpression.vb
  src/Compilers/VisualBasic/Portable/CodeGen/Optimizer/StackScheduler.Analyzer.vb
  src/Compilers/VisualBasic/Portable/CodeGen/Optimizer/StackScheduler.Rewriter.vb
  src/Compilers/VisualBasic/Portable/Generated/BoundNodes.xml.Generated.vb
  src/Compilers/VisualBasic/Portable/Lowering/AsyncRewriter/AsyncRewriter.AsyncMethodToClassRewriter.Expressions.vb
  src/Compilers/VisualBasic/Portable/Lowering/LambdaRewriter/LambdaRewriter.vb
  src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_ConditionalAccess.vb
  src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenAsyncTests.vb
  src/Compilers/VisualBasic/Test/Semantic/Semantics/ConditionalAccessTests.vb
Labels: Language-VB, Area-Compilers, untriaged

#76789 Keep comments on an 'else' keyword when converting to conditional expressions.
  src/Analyzers/CSharp/CodeFixes/UseConditionalExpression/CSharpUseConditionalExpressionForAssignmentCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseConditionalExpression/CSharpUseConditionalExpressionForReturnCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/UseConditionalExpression/CSharpUseConditionalExpressionHelpers.cs
  src/Analyzers/CSharp/Tests/UseConditionalExpression/UseConditionalExpressionForAssignmentTests.cs
  src/Analyzers/Core/CodeFixes/UseConditionalExpression/AbstractUseConditionalExpressionCodeFixProvider.cs
  src/Analyzers/VisualBasic/CodeFixes/UseConditionalExpression/VisualBasicUseConditionalExpressionForAssignmentCodeFixProvider.vb
Labels: Area-IDE, untriaged, VSCode

#76767 Make IServiceBrokerProvider available in all layers
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueLanguageServiceTests.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/ServiceBrokerProvider.cs
  src/VisualStudio/DevKit/Impl/Microsoft.VisualStudio.LanguageServices.DevKit.csproj
  src/Workspaces/Remote/Core/IServiceBrokerProvider.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteServiceBrokerProvider.cs
  src/Workspaces/Remote/ServiceHub/Microsoft.CodeAnalysis.Remote.ServiceHub.csproj
  src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.FactoryBase.cs
Labels: Area-IDE, untriaged, VSCode

#76786 Support target type completion tags in object creation contexts
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/SymbolCompletionProviderTests.vb
  src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/CSharpSyntaxContext.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/ContextQuery/SyntaxContext.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/VisualBasicSyntaxContext.vb
Labels: Area-IDE, untriaged, VSCode

#76795 Initialize naming style preferences when language is added to workspace
  src/Features/Core/Portable/Options/EditorConfig/EditorConfigFileGenerator.cs
  src/Features/Core/Portable/Options/EditorConfig/EditorConfigOptionsEnumerator.cs
  src/LanguageServer/Protocol/Features/Options/ClientFallbackAnalyzerConfigOptionsProvider.cs
  src/LanguageServer/Protocol/Features/Options/SolutionAnalyzerConfigOptionsUpdater.cs
  src/LanguageServer/ProtocolUnitTests/Options/SolutionAnalyzerConfigOptionsUpdaterTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyleOptions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Options/EditorConfigValueSerializer.cs
Labels: Area-IDE, untriaged, VSCode

#76791 Fix formatting when doing a 'fix all' with 'use auto prop'
  src/Analyzers/CSharp/Tests/UseAutoProperty/UseAutoPropertyTests_Field.cs
  src/Analyzers/VisualBasic/Tests/UseAutoProperty/UseAutoPropertyTests.vb
  src/Features/Core/Portable/UseAutoProperty/AbstractUseAutoPropertyCodeFixProvider.cs
  src/Workspaces/Core/Portable/CodeActions/CodeAction_Cleanup.cs
Labels: Area-IDE, untriaged, VSCode

#76583 Add EmbeddedAttribute API for source generators
  docs/features/incremental-generators.cookbook.md
  src/Compilers/CSharp/Portable/SourceGeneration/CSharpGeneratorDriver.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs
  src/Compilers/Core/Portable/SourceGeneration/IncrementalContexts.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/PostInitOutputNode.cs
  src/Compilers/VisualBasic/Portable/SourceGeneration/VisualBasicGeneratorDriver.vb
  src/Compilers/VisualBasic/Test/Semantic/SourceGeneration/GeneratorDriverTests.vb
Labels: Area-Compilers, untriaged, Needs API Review

#76802 Remove skip attributes from some MSBuildWorkspace tests
  src/Workspaces/MSBuildTest/NewlyCreatedProjectsFromDotNetNew.cs
Labels: Area-IDE, untriaged, VSCode

#76699 Convert a return value to return type even if it has errors
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IParenthesized.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/ImplicitObjectCreationTests.cs
  src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs
Labels: Area-Compilers, untriaged

#76798 Remove unnecessary cast in one conditional expression branch, based on the other branch and outer conversion.
  src/Analyzers/CSharp/Tests/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs
  src/Analyzers/CSharp/Tests/UseConditionalExpression/UseConditionalExpressionForAssignmentTests.cs
  src/Analyzers/CSharp/Tests/UseConditionalExpression/UseConditionalExpressionForReturnTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Simplification/Simplifiers/CastSimplifier.cs
Labels: Area-IDE, untriaged, VSCode

#76807 Do not offer use-conditional when it would cause name collisions
  src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForAssignmentDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseDeconstruction/CSharpUseDeconstructionDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/UseSimpleUsingStatement/UseSimpleUsingStatementDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/UseConditionalExpression/UseConditionalExpressionForAssignmentTests.cs
  src/Analyzers/CSharp/Tests/UseConditionalExpression/UseConditionalExpressionForReturnTests.cs
  src/Analyzers/Core/Analyzers/UseConditionalExpression/AbstractUseConditionalExpressionDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseConditionalExpression/ForAssignment/AbstractUseConditionalExpressionForAssignmentDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseConditionalExpression/ForAssignment/UseConditionalExpressionForAssignmentHelpers.cs
  src/Analyzers/Core/Analyzers/UseConditionalExpression/ForReturn/AbstractUseConditionalExpressionForReturnDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/UseConditionalExpression/ForReturn/UseConditionalExpressionForReturnHelpers.cs
  src/Analyzers/Core/Analyzers/UseConditionalExpression/UseConditionalExpressionHelpers.cs
  src/Analyzers/Core/CodeFixes/UseConditionalExpression/ForAssignment/AbstractUseConditionalExpressionForAssignmentCodeFixProvider.cs
  src/Analyzers/Core/CodeFixes/UseConditionalExpression/ForReturn/AbstractUseConditionalExpressionForReturnCodeFixProvider.cs
  src/Features/CSharp/Portable/UsePatternMatching/CSharpIsAndCastCheckWithoutNameDiagnosticAnalyzer.cs
  src/Features/Core/Portable/InlineMethod/AbstractInlineMethodRefactoringProvider.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/SemanticModelExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpSemanticFactsService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/SemanticsFactsService/AbstractSemanticFactsService.cs
Labels: Area-IDE, untriaged, VSCode

#76805 Use pattern matching for symbols.
  src/Analyzers/Core/Analyzers/UseCompoundAssignment/UseCompoundAssignmentUtilities.cs
  src/Analyzers/Core/Analyzers/UseExplicitTupleName/UseExplicitTupleNameDiagnosticAnalyzer.cs
  src/Analyzers/Core/CodeFixes/GenerateConstructor/AbstractGenerateConstructorService.State.cs
  src/Analyzers/Core/CodeFixes/GenerateConstructor/AbstractGenerateConstructorService.cs
  src/Analyzers/Core/CodeFixes/GenerateConstructor/GenerateConstructorHelpers.cs
  src/EditorFeatures/Core/RenameTracking/RenameTrackingTaggerProvider.TrackingSession.cs
  src/Features/CSharp/Portable/QuickInfo/CSharpSemanticQuickInfoProvider.cs
  src/Features/Core/Portable/Completion/Providers/AbstractRecommendationServiceBasedCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs
  src/VisualStudio/CSharp/Impl/CodeModel/CSharpCodeModelService.NodeNameGenerator.cs
  src/VisualStudio/CSharp/Impl/CodeModel/CSharpCodeModelService_Prototype.cs
  src/VisualStudio/CSharp/Impl/CodeModel/MethodXml/MethodXmlBuilder.cs
  src/VisualStudio/Core/Def/Implementation/VsRefactorNotifyService.cs
  src/VisualStudio/Core/Impl/CodeModel/ExternalElements/AbstractExternalCodeElement.cs
  src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs
  src/Workspaces/CSharp/Portable/Rename/CSharpRenameRewriterLanguageService.cs
  src/Workspaces/CSharp/Portable/Simplification/CSharpSimplificationService.Expander.cs
  src/Workspaces/CSharp/Portable/Simplification/Reducers/CSharpExtensionMethodReducer.cs
  src/Workspaces/Core/Portable/Classification/SyntaxClassification/AbstractNameSyntaxClassifier.cs
  src/Workspaces/Core/Portable/FindSymbols/ReferenceLocationExtensions.cs
  src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs
  src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs
  src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SemanticModelExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/INamedTypeSymbolExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ISymbolExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/SymbolKey/SymbolKey.SymbolKeyWriter.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/AbstractSpeculationAnalyzer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/NameSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/TypeSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeGeneration/AbstractFlagsEnumGenerator.cs
  src/Workspaces/VisualBasic/Portable/CodeCleanup/Providers/FixIncorrectTokensCodeCleanupProvider.vb
  src/Workspaces/VisualBasic/Portable/Recommendations/VisualBasicRecommendationServiceRunner.vb
Labels: Area-IDE, untriaged, VSCode

#76796 Escape Creator Helix argument
  src/Tools/Source/RunTests/HelixTestRunner.cs
Labels: Area-Infrastructure, untriaged

#74145 Fix 'invert if' refactor to properly enclose #region/#endregion blocks
  src/Features/CSharpTest/InvertIf/InvertIfTests.Elseless.cs
  src/Features/Core/Portable/InvertIf/AbstractInvertIfCodeRefactoringProvider.cs
Labels: Area-IDE, Community, untriaged, VSCode

#76821 Fix gen-method generating into top level.
  src/Analyzers/CSharp/Tests/GenerateMethod/GenerateMethodTests.cs
  src/Analyzers/Core/CodeFixes/GenerateParameterizedMember/AbstractGenerateParameterizedMemberService.CodeAction.cs
  src/EditorFeatures/Test2/Diagnostics/GenerateFromUsage/GenerateMethodCrossLanguageTests.vb
  src/Features/Core/Portable/PullMemberUp/MembersPuller.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeGeneration/AbstractCodeGenerationService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeGeneration/AbstractCodeGenerationService_FindDeclaration.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeGeneration/ICodeGenerationService.cs
Labels: Area-IDE, untriaged, VSCode

#76822 Do not offer to inline a decl into a switch arm when it is referenced outside of it.
  src/Analyzers/CSharp/Analyzers/InlineDeclaration/CSharpInlineDeclarationDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/InlineDeclaration/CSharpInlineDeclarationTests.cs
Labels: Area-IDE, untriaged, VSCode

#76825 Do no offer to make fields readonly if they are a struct and are written to through an indexer
  src/Analyzers/CSharp/Analyzers/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/MakeFieldReadonly/MakeFieldReadonlyTests.cs
  src/Analyzers/Core/Analyzers/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs
  src/Analyzers/VisualBasic/Analyzers/MakeFieldReadonly/VisualBasicMakeFieldReadonlyDiagnosticAnalyzer.vb
  src/Analyzers/VisualBasic/Tests/MakeFieldReadonly/MakeFieldReadonlyTests.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/OperationExtensions.cs
Labels: Area-IDE, untriaged, VSCode

#76827 Add support for outlining switch expressions
  src/EditorFeatures/CSharpTest/Structure/SwitchExpressionStructureTests.cs
  src/EditorFeatures/CSharpTest/Structure/SwitchStatementStructureTests.cs
  src/Features/CSharp/Portable/Structure/CSharpBlockStructureProvider.cs
  src/Features/CSharp/Portable/Structure/Providers/SwitchExpressionStructureProvider.cs
  src/Features/CSharp/Portable/Structure/Providers/SwitchStatementStructureProvider.cs
Labels: Area-IDE, untriaged, VSCode

#76830 Do not offer to simplify interpolations when using formattable strings
  src/Analyzers/CSharp/Analyzers/SimplifyInterpolation/CSharpSimplifyInterpolationDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Analyzers/SimplifyInterpolation/CSharpSimplifyInterpolationHelpers.cs
  src/Analyzers/CSharp/CodeFixes/SimplifyInterpolation/CSharpSimplifyInterpolationCodeFixProvider.cs
  src/Analyzers/CSharp/Tests/SimplifyInterpolation/SimplifyInterpolationTests.cs
  src/Analyzers/Core/Analyzers/SimplifyInterpolation/AbstractSimplifyInterpolationDiagnosticAnalyzer.cs
  src/Analyzers/Core/Analyzers/SimplifyInterpolation/AbstractSimplifyInterpolationHelpers.cs
  src/Analyzers/Core/CodeFixes/SimplifyInterpolation/AbstractSimplifyInterpolationCodeFixProvider.cs
  src/Analyzers/VisualBasic/Analyzers/SimplifyInterpolation/VisualBasicSimplifyInterpolationDiagnosticAnalyzer.vb
  src/Analyzers/VisualBasic/Analyzers/SimplifyInterpolation/VisualBasicSimplifyInterpolationHelpers.vb
  src/Analyzers/VisualBasic/CodeFixes/SimplifyInterpolation/VisualBasicSimplifyInterpolationCodeFixProvider.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ICompilationExtensions.cs
Labels: Area-IDE, untriaged, VSCode

#76823 Special case inlining a collection expr into a spreaded element
  src/Features/CSharp/Portable/CodeRefactorings/InlineTemporary/InlineTemporaryCodeRefactoringProvider.ReferenceRewriter.cs
  src/Features/CSharp/Portable/CodeRefactorings/InlineTemporary/InlineTemporaryCodeRefactoringProvider.cs
  src/Features/CSharpTest/InlineTemporary/InlineTemporaryTests.cs
Labels: Area-IDE, untriaged, VSCode

#76828 Change helix logging
  src/Tools/Source/RunTests/AssemblyScheduler.cs
  src/Tools/Source/RunTests/HelixTestRunner.cs
  src/Tools/Source/RunTests/TestHistoryManager.cs
  src/Tools/Source/RunTests/TestRunner.cs
Labels: Area-Infrastructure, untriaged

#76808 Load razor assembly directly:
  src/Compilers/Core/CodeAnalysisTest/AnalyzerAssemblyLoaderTests.cs
  src/Compilers/Core/CodeAnalysisTest/CompilerAnalyzerAssemblyResolverTests.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.Core.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.Desktop.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/IAnalyzerAssemblyResolver.cs
  src/Tools/ExternalAccess/Razor/RazorAnalyzerAssemblyResolver.cs
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspaceManager.cs
Labels: Area-Compilers, untriaged, VSCode

#76837 Improve collapsing of members followed by pp directives
  src/EditorFeatures/CSharpTest/Structure/ArrowExpressionClauseStructureTests.cs
  src/Features/CSharp/Portable/Structure/Providers/ArrowExpressionClauseStructureProvider.cs
Labels: Area-IDE, untriaged, VSCode

#76800 Initialize naming style preferences when language is added to workspace
  src/Features/Core/Portable/Options/EditorConfig/EditorConfigFileGenerator.cs
  src/LanguageServer/ProtocolUnitTests/Options/SolutionAnalyzerConfigOptionsUpdaterTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Options/EditorConfigValueSerializer.cs
Labels: Area-IDE, untriaged, VSCode

#76838 Use BaseOS instead of TargetRid when its available
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Microsoft.CodeAnalysis.LanguageServer.csproj
Labels: Area-Infrastructure, Source-Build, untriaged

#76848 Update telemetry function ids for clarity.
  src/VisualStudio/Core/Def/TableDataSource/Suppression/VisualStudioSuppressionFixService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs
Labels: Area-IDE, untriaged, VSCode

#76806 Support organizing imports as part of LSP document formatting
  src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/Features/TestUtilities/Microsoft.CodeAnalysis.Features.Test.Utilities.csproj
  src/LanguageServer/Protocol/Handler/Configuration/DidChangeConfigurationNotificationHandler_OptionList.cs
  src/LanguageServer/Protocol/Handler/Formatting/AbstractFormatDocumentHandlerBase.cs
  src/LanguageServer/Protocol/Handler/Formatting/FormatDocumentHandler.cs
  src/LanguageServer/Protocol/Handler/Formatting/FormatDocumentRangeHandler.cs
  src/LanguageServer/Protocol/LspOptionsStorage.cs
  src/LanguageServer/ProtocolUnitTests/Configuration/DidChangeConfigurationNotificationHandlerTest.cs
  src/LanguageServer/ProtocolUnitTests/Formatting/FormatDocumentTests.cs
  src/VisualStudio/Core/Test.Next/Options/VisualStudioOptionStorageTests.cs
  src/Workspaces/CSharp/Portable/OrganizeImports/CSharpOrganizeImportsService.cs
Labels: Area-IDE, untriaged, VSCode

#76850 Remove helper extension in diagnostics
  src/EditorFeatures/Test2/CodeFixes/CodeFixServiceTests.vb
  src/Features/CSharpTest/Diagnostics/Suppression/SuppressionTests.cs
  src/Features/Core/Portable/Diagnostics/IDiagnosticAnalyzerService.cs
  src/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/AbstractWorkspaceDocumentDiagnosticSource.cs
  src/Tools/ExternalAccess/Razor/Cohost/Handlers/Diagnostics.cs
Labels: Area-IDE, untriaged, VSCode

#76853 Use existing property over linq operator
  src/EditorFeatures/CSharpTest/Interactive/NavigateTo/InteractiveNavigateToTests.cs
  src/EditorFeatures/CSharpTest/LineSeparators/LineSeparatorTests.cs
  src/EditorFeatures/CSharpTest/NavigateTo/NavigateToTests.cs
  src/EditorFeatures/DiagnosticsTestUtilities/Diagnostics/AbstractUserDiagnosticTest_GenerateTypeDialog.cs
  src/EditorFeatures/Test/Tagging/TagSpanIntervalTreeTests.cs
  src/EditorFeatures/Test2/CodeFixes/CodeFixServiceTests.vb
  src/EditorFeatures/Test2/Diagnostics/DiagnosticServiceTests.vb
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.LinkedFiles.vb
  src/EditorFeatures/TestUtilities/NavigateTo/AbstractNavigateToTests.cs
  src/EditorFeatures/TestUtilities/SignatureHelp/AbstractSignatureHelpProviderTests.cs
  src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.PostProcessor.cs
  src/Features/DiagnosticsTestUtilities/Diagnostics/AbstractSuppressionAllCodeTests.cs
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.PostProcessor.vb
  src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicMethodExtractor.VisualBasicCodeGenerator.vb
  src/LanguageServer/Protocol/Features/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs
  src/VisualStudio/Core/Test/CodeModel/AbstractCodeElementTests`1.vb
  src/Workspaces/Core/Portable/Rename/SymbolicRenameLocations.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectFactory.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
  src/Workspaces/CoreTest/SymbolKeyTests.cs
Labels: Area-IDE, untriaged, VSCode

#76862 Use Assert.Empty
  src/EditorFeatures/Test/Collections/Immutable/Maps/MapTests.cs
  src/EditorFeatures/Test/Extensions/CollectionExtensionsTest.cs
  src/EditorFeatures/Test/MetadataAsSource/AbstractMetadataAsSourceTests.TestContext.cs
  src/EditorFeatures/Test2/CodeFixes/CodeFixServiceTests.vb
  src/EditorFeatures/Test2/Diagnostics/DiagnosticProviderTests.vb
  src/EditorFeatures/Test2/Diagnostics/DiagnosticServiceTests.vb
  src/EditorFeatures/TestUtilities/Rename/RenamerTests.cs
  src/EditorFeatures/VisualBasicTest/Recommendations/RecommendationTestHelpers.vb
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/LocalFunctionTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/LocalsTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/UsingDebugInfoTests.cs
  src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/LocalsTests.vb
  src/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
  src/LanguageServer/ProtocolUnitTests/RelatedDocuments/RelatedDocumentsTests.cs
  src/Scripting/CoreTest.Desktop/GlobalAssemblyCacheTests.cs
  src/VisualStudio/CSharp/Test/DocumentOutline/DocumentOutlineTests.cs
  src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs
  src/Workspaces/VisualBasicTest/CodeGeneration/SyntaxGeneratorTests.vb
Labels: Area-IDE, untriaged, VSCode

#76849 Push diagnostic suppression filtering flag to feature levels
  src/EditorFeatures/Core.Wpf/InlineDiagnostics/AbstractDiagnosticsTaggerProvider.SingleDiagnosticKindPullTaggerProvider.cs
  src/EditorFeatures/Test/CodeFixes/CodeFixServiceTests.cs
  src/EditorFeatures/Test/Diagnostics/DiagnosticAnalyzerServiceTests.cs
  src/EditorFeatures/Test2/CodeFixes/CodeFixServiceTests.vb
  src/EditorFeatures/Test2/Diagnostics/DiagnosticProviderTests.vb
  src/EditorFeatures/Test2/Diagnostics/DiagnosticServiceTests.vb
  src/EditorFeatures/TestUtilities/Diagnostics/MockDiagnosticAnalyzerService.cs
  src/Features/CSharpTest/Diagnostics/Suppression/SuppressionTests.cs
  src/Features/Core/Portable/Diagnostics/CodeAnalysisDiagnosticAnalyzerService.cs
  src/Features/Core/Portable/Diagnostics/DiagnosticArguments.cs
  src/Features/Core/Portable/Diagnostics/IDiagnosticAnalyzerService.cs
  src/LanguageServer/Protocol.TestUtilities/Diagnostics/TestDiagnosticAnalyzerDriver.cs
  src/LanguageServer/Protocol/Features/CodeCleanup/AbstractCodeCleanupService.cs
  src/LanguageServer/Protocol/Features/CodeFixes/CodeFixService.FixAllDiagnosticProvider.cs
  src/LanguageServer/Protocol/Features/CodeFixes/CodeFixService.cs
  src/LanguageServer/Protocol/Features/Diagnostics/DiagnosticAnalyzerService.cs
  src/LanguageServer/Protocol/Features/Diagnostics/DocumentAnalysisExecutor_Helpers.cs
  src/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.CompilationManager.cs
  src/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.Executor.cs
  src/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.InProcOrRemoteHostAnalyzerRunner.cs
  src/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs
  src/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs
  src/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_IncrementalAnalyzer.cs
  src/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/AbstractProjectDiagnosticSource.cs
  src/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/AbstractWorkspaceDocumentDiagnosticSource.cs
  src/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/DocumentDiagnosticSource.cs
  src/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/NonLocalDocumentDiagnosticSource.cs
  src/Tools/ExternalAccess/Razor/Cohost/Handlers/Diagnostics.cs
  src/VisualStudio/Core/Def/TableDataSource/Suppression/VisualStudioSuppressionFixService.cs
  src/VisualStudio/Core/Test/Diagnostics/ExternalDiagnosticUpdateSourceTests.vb
  src/VisualStudio/Core/Test/Venus/DocumentService_IntegrationTests.vb
  src/Workspaces/Core/Portable/Diagnostics/CompilationWithAnalyzersPair.cs
  src/Workspaces/Core/Portable/Diagnostics/Extensions.cs
  src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/DiagnosticComputer.cs
  src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/RemoteDiagnosticAnalyzerService.cs
Labels: Area-IDE, untriaged, VSCode

#76865 Initial work to collapse comments at the end of a block
  src/EditorFeatures/CSharpTest/Structure/BlockSyntaxStructureTests.cs
  src/Features/CSharp/Portable/Structure/CSharpStructureHelpers.cs
  src/Features/CSharp/Portable/Structure/Providers/BlockSyntaxStructureProvider.cs
  src/Features/CSharp/Portable/Structure/Providers/TypeDeclarationStructureProvider.cs
Labels: Area-IDE, untriaged, VSCode

#76748 Ensure we deploy the build hosts in Roslyn.VisualStudio.Setup
  src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj
Labels: Area-Infrastructure, untriaged

#76747 Ensure we deploy the build hosts in Roslyn.VisualStudio.Setup
  src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj
Labels: Area-Infrastructure, untriaged

#76866 Revert "Change PR Val builds to be unsigned (#76358)"
  azure-pipelines-pr-validation.yml
  eng/Signing.props
Labels: Area-Infrastructure, untriaged

#76736 Fix new document formatting
  src/VisualStudio/Core/Def/Implementation/AbstractEditorFactory.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpWinForms.cs
Labels: Area-IDE, untriaged

#76876 Update formatOnType handler to support formatting on NewLine
  src/LanguageServer/Protocol/Handler/Formatting/FormatDocumentOnTypeHandler.cs
  src/LanguageServer/ProtocolUnitTests/Formatting/FormatDocumentOnTypeTests.cs
Labels: Area-Infrastructure, untriaged, VSCode

#76835 Reduce work in ConversionsBase.AddUserDefinedConversionsToExplicitCandidateSet
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/UserDefinedExplicitConversions.cs
Labels: Area-Compilers, untriaged

#76879 Add feature status of Partial Events and Constructors
  docs/Language Feature Status.md
Labels: Area-Compilers, Documentation, untriaged, Feature - Partial Events and Constructors

#76042 Enc logging
  src/EditorFeatures/Core/EditAndContinue/EditAndContinueLanguageService.cs
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/Features/CSharp/Portable/EditAndContinue/CSharpEditAndContinueAnalyzer.cs
  src/Features/CSharpTest/EditAndContinue/CSharpEditAndContinueAnalyzerTests.cs
  src/Features/CSharpTest/EditAndContinue/Helpers/CSharpEditAndContinueTestVerifier.cs
  src/Features/CSharpTest/EditAndContinue/Helpers/EditAndContinueValidation.cs
  src/Features/CSharpTest/EditAndContinue/Helpers/EditingTestBase.cs
  src/Features/CSharpTest/EditAndContinue/StatementMatchingTests.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/CommittedSolution.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSession.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSessionId.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueDocumentAnalysesCache.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueService.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/Core/Portable/EditAndContinue/IEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/IEditAndContinueLogReporter.cs
  src/Features/Core/Portable/EditAndContinue/SolutionUpdate.cs
  src/Features/Core/Portable/EditAndContinue/TraceLog.cs
  src/Features/Core/Portable/EditAndContinue/Utilities/Extensions.cs
  src/Features/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/Features/Test/EditAndContinue/EditSessionActiveStatementsTests.cs
  src/Features/Test/EditAndContinue/TraceLogTests.cs
  src/Features/TestUtilities/EditAndContinue/EditAndContinueTestVerifier.cs
  src/Features/VisualBasic/Portable/EditAndContinue/VisualBasicEditAndContinueAnalyzer.vb
  src/Features/VisualBasicTest/EditAndContinue/Helpers/EditingTestBase.vb
  src/Features/VisualBasicTest/EditAndContinue/Helpers/VisualBasicEditAndContinueTestVerifier.vb
  src/Features/VisualBasicTest/EditAndContinue/VisualBasicEditAndContinueAnalyzerTests.vb
  src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs
  src/Workspaces/Remote/ServiceHub/Microsoft.CodeAnalysis.Remote.ServiceHub.csproj
  src/Workspaces/Remote/ServiceHub/Services/EditAndContinue/EditAndContinueLogReporter.cs
  src/Workspaces/Remote/ServiceHub/Services/EditAndContinue/HotReloadLoggerProxy.cs
Labels: Area-Interactive, untriaged, VSCode

#76884 Update Language Feature Status.md
  docs/Language Feature Status.md
Labels: Area-Compilers, untriaged

#76826 Remove workaround for old version of SRM.
  src/Compilers/Core/Portable/MetadataReference/ModuleMetadata.cs
Labels: Area-Compilers, Community, untriaged

#76768 Opt in MS.CA.LS.Protocol into using optprof training data
  src/LanguageServer/Protocol/Microsoft.CodeAnalysis.LanguageServer.Protocol.csproj
Labels: Area-Infrastructure, untriaged

#76878 Improve handling bad metadata in EE
  Roslyn.sln
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CSharpExpressionCompiler.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CSharpInstructionDecoder.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationExtensions.cs
  src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/EvaluationContext.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/ExpressionCompilerTestBase.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/ExpressionCompilerTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/HoistedStateMachineLocalTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/InstructionDecoderTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/LocalsTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/MethodContextReuseConstraintsTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/Microsoft.CodeAnalysis.CSharp.ExpressionCompiler.UnitTests.csproj
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/MissingAssemblyTests.cs
  src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/ReferencedModulesTests.cs
  src/ExpressionEvaluator/Core/Source/ExpressionCompiler/BadMetadataModuleException.cs
  src/ExpressionEvaluator/Core/Source/ExpressionCompiler/DkmUtilities.cs
  src/ExpressionEvaluator/Core/Source/ExpressionCompiler/ExpressionCompiler.cs
  src/ExpressionEvaluator/Core/Source/ExpressionCompiler/FrameDecoder.cs
  src/ExpressionEvaluator/Core/Source/ExpressionCompiler/LanguageInstructionDecoder.cs
  src/ExpressionEvaluator/Core/Source/ExpressionCompiler/MetadataBlock.cs
  src/ExpressionEvaluator/Core/Source/ExpressionCompiler/MetadataContextId.cs
  src/ExpressionEvaluator/Core/Source/ExpressionCompiler/MetadataUtilities.cs
  src/ExpressionEvaluator/Core/Source/ExpressionCompiler/MethodContextReuseConstraints.cs
  src/ExpressionEvaluator/Core/Source/ExpressionCompiler/ModuleId.cs
  src/ExpressionEvaluator/Core/Test/ExpressionCompiler/ExpressionCompilerTestHelpers.cs
  src/ExpressionEvaluator/Core/Test/ExpressionCompiler/Microsoft.CodeAnalysis.ExpressionCompiler.Test.Utilities.csproj
  src/ExpressionEvaluator/Core/Test/ExpressionCompiler/ModuleInstance.cs
  src/ExpressionEvaluator/VisualBasic/Source/ExpressionCompiler/CompilationExtensions.vb
  src/ExpressionEvaluator/VisualBasic/Source/ExpressionCompiler/EvaluationContext.vb
  src/ExpressionEvaluator/VisualBasic/Source/ExpressionCompiler/VisualBasicExpressionCompiler.vb
  src/ExpressionEvaluator/VisualBasic/Source/ExpressionCompiler/VisualBasicInstructionDecoder.vb
  src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/ExpressionCompilerTestBase.vb
  src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/ExpressionCompilerTests.vb
  src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/HoistedStateMachineLocalTests.vb
  src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/InstructionDecoderTests.vb
  src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/LocalsTests.vb
  src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/Microsoft.CodeAnalysis.VisualBasic.ExpressionCompiler.UnitTests.vbproj
  src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/MissingAssemblyTests.vb
  src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/ReferencedModulesTests.vb
  src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/StaticLocalsTests.vb
Labels: Area-Interactive, untriaged

#76877 On-the-fly-docs -- Add quota exceeded dialogue
  src/EditorFeatures/Core.Wpf/QuickInfo/OnTheFlyDocsView.xaml.cs
  src/EditorFeatures/Core.Wpf/QuickInfo/OnTheFlyDocsViewFactory.cs
  src/EditorFeatures/Core/EditorFeaturesResources.resx
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.cs.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.de.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.es.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.fr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.it.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ja.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ko.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pl.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pt-BR.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ru.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.tr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hans.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hant.xlf
  src/EditorFeatures/ExternalAccess/Copilot/Analyzer/IExternalCSharpCopilotCodeAnalysisService.cs
  src/EditorFeatures/ExternalAccess/Copilot/Internal/Analyzer/AbstractCopilotCodeAnalysisService.cs
  src/EditorFeatures/ExternalAccess/Copilot/Internal/Analyzer/CSharp/CSharpCopilotCodeAnalysisService.ReflectionWrapper.cs
  src/EditorFeatures/ExternalAccess/Copilot/Internal/Analyzer/CSharp/CSharpCopilotCodeAnalysisService.cs
  src/EditorFeatures/ExternalAccess/Copilot/InternalAPI.Unshipped.txt
  src/EditorFeatures/Test2/CodeFixes/CodeFixServiceTests.vb
  src/Features/Core/Portable/Copilot/ICopilotCodeAnalysisService.cs
Labels: Area-IDE, untriaged, VSCode

#76873 Testing time
  src/Tools/Source/RunTests/AssemblyScheduler.cs
Labels: Area-Infrastructure, untriaged

#76891 Do not offer the containing type when offering completion in teh base-list
  src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb
  src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/CSharpSyntaxContext.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/ContextQuery/SyntaxContext.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/VisualBasicSyntaxContext.vb
Labels: Area-IDE, untriaged, VSCode

#76769 Fix throw in generator comparer
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs
  src/Compilers/CSharp/Test/Semantic/SourceGeneration/StateTableTests.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/BatchNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/CombineNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/InputNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/PredicateSyntaxStrategy.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SourceOutputNode.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxReceiverStrategy.cs
  src/Compilers/Core/Portable/SourceGeneration/Nodes/TransformNode.cs
  src/Compilers/Core/Portable/SourceGeneration/UserFunction.cs
Labels: Area-Compilers, untriaged

#76003 Collection expression argument parsing (`[with(x, y, z), a, b, c]`).
  src/Compilers/CSharp/Portable/Generated/CSharp.Generated.g4
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Internal.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Main.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Syntax.Generated.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
  src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs
  src/Compilers/CSharp/Test/Emit3/Diagnostics/DiagnosticAnalyzerTests.AllInOne.cs
  src/Compilers/CSharp/Test/Syntax/Generated/Syntax.Test.xml.Generated.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/CollectionExpressionParsingTests.cs
  src/EditorFeatures/CSharpTest/Diagnostics/DiagnosticAnalyzerDriver/DiagnosticAnalyzerDriverTests.cs
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/SourceWriter.cs
Labels: Area-Compilers, untriaged, Needs API Review, Feature - Dictionary Expressions

#76900 Add support for converting an auto-prop to a field-backed property.
  src/Analyzers/CSharp/Analyzers/UseAutoProperty/CSharpUseAutoPropertyAnalyzer.cs
  src/Analyzers/CSharp/Tests/UseAutoProperty/UseAutoPropertyTests_Field.cs
  src/Analyzers/CSharp/Tests/UseImplicitlyTypedLambdaExpression/UseImplicitlyTypedLambdaExpressionTests.cs
  src/Analyzers/Core/Analyzers/UseAutoProperty/AbstractUseAutoPropertyAnalyzer.cs
  src/Analyzers/VisualBasic/Analyzers/UseAutoProperty/VisualBasicUseAutoPropertyAnalyzer.vb
  src/Features/CSharp/Portable/ConvertAutoPropertyToFullProperty/CSharpConvertAutoPropertyToFullPropertyCodeRefactoringProvider.cs
  src/Features/CSharpTest/ConvertAutoPropertyToFullProperty/ConvertAutoPropertyToFullPropertyTests.cs
  src/Features/Core/Portable/ConvertAutoPropertyToFullProperty/AbstractConvertAutoPropertyToFullPropertyCodeRefactoringProvider.cs
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Features/VisualBasic/Portable/ConvertAutoPropertyToFullProperty/VisualBasicConvertAutoPropertyToFullProperty.vb
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb
Labels: Area-IDE, untriaged, VSCode

#76905 Speed up 'fix all' for 'use auto prop' by running in parallel
  src/Features/Core/Portable/UseAutoProperty/AbstractUseAutoPropertyCodeFixProvider.cs
  src/Features/Core/Portable/UseAutoProperty/UseAutoPropertyFixAllProvider.cs
Labels: Area-IDE, untriaged, VSCode

#73966 Add generated semantic search API list
  src/Tools/SemanticSearch/BuildTask/GenerateFilteredReferenceAssembliesTask.cs
  src/Tools/SemanticSearch/ReferenceAssemblies/ApiSet/Microsoft.CodeAnalysis.CSharp.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/ApiSet/Microsoft.CodeAnalysis.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/ApiSet/System.Runtime.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Apis/Microsoft.CodeAnalysis.CSharp.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Apis/Microsoft.CodeAnalysis.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Apis/System.Collections.Immutable.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Apis/System.Collections.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Apis/System.Linq.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Apis/System.Runtime.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Baselines/Microsoft.CodeAnalysis.CSharp.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Baselines/Microsoft.CodeAnalysis.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Baselines/System.Collections.Immutable.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Baselines/System.Collections.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Baselines/System.Linq.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Baselines/System.Runtime.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/SemanticSearch.ReferenceAssemblies.csproj
  src/Tools/SemanticSearch/Tests/GenerateFilteredReferenceAssembliesTaskTests.cs
Labels: Area-Infrastructure, untriaged

#76718 Enable extract refactorings in LSP
  src/Features/Core/Portable/CodeRefactorings/ExtractMethod/AbstractExtractMethodCodeRefactoringProvider.cs
  src/Features/Core/Portable/ExtractClass/AbstractExtractClassRefactoringProvider.cs
  src/Features/Core/Portable/ExtractInterface/ExtractInterfaceCodeRefactoringProvider.cs
  src/Features/Core/Portable/InlineMethod/AbstractInlineMethodRefactoringProvider.cs
  src/Features/Core/Portable/InlineTemporary/AbstractInlineTemporaryCodeRefactoringProvider.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Microsoft.CodeAnalysis.LanguageServer.UnitTests.csproj
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Services/ExtractRefactoringTests.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Utilities/AbstractLanguageServerClientTests.TestLspClient.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Utilities/AbstractLanguageServerClientTests.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Utilities/AbstractLanguageServerHostTests.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Utilities/ILspClient.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Utilities/LanguageServerTestComposition.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Utilities/LspClientExtensions.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Utilities/TestPaths.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/OpenProjectsHandler.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/OpenSolutionHandler.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/ProjectDependencyHelper.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/ProjectInitializationHandler.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Services/LspExtractClassOptionsService.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Services/LspExtractInterfaceOptionsService.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/WindowsErrorReporting.cs
  src/LanguageServer/Protocol/Handler/CodeActions/CodeActionHelpers.cs
  src/Workspaces/Core/Portable/CodeRefactorings/CodeRefactoringKind.cs
  src/Workspaces/Core/Portable/CodeRefactorings/CodeRefactoringProvider.cs
Labels: Area-Infrastructure, untriaged, Needs UX Triage, VSCode

#76920 Do not offer to convert typeof to nameof on a generic type
  src/Analyzers/CSharp/Analyzers/ConvertTypeofToNameof/CSharpConvertTypeOfToNameOfDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/Tests/ConvertTypeOfToNameOf/ConvertTypeOfToNameOfTests.cs
  src/Analyzers/Core/Analyzers/ConvertTypeofToNameof/AbstractConvertTypeOfToNameOfDiagnosticAnalyzer.cs
  src/Analyzers/VisualBasic/Analyzers/ConvertTypeofToNameof/VisualBasicConvertTypeOfToNameOfDiagnosticAnalyzer.vb
Labels: Area-IDE, untriaged, VSCode

#76893 On-the-fly-docs -- Add quota exceeded dialogue (#76877)
  src/EditorFeatures/Core.Wpf/QuickInfo/OnTheFlyDocsView.xaml.cs
  src/EditorFeatures/Core.Wpf/QuickInfo/OnTheFlyDocsViewFactory.cs
  src/EditorFeatures/Core/EditorFeaturesResources.resx
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.cs.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.de.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.es.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.fr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.it.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ja.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ko.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pl.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.pt-BR.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.ru.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.tr.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hans.xlf
  src/EditorFeatures/Core/xlf/EditorFeaturesResources.zh-Hant.xlf
  src/EditorFeatures/ExternalAccess/Copilot/Analyzer/IExternalCSharpCopilotCodeAnalysisService.cs
  src/EditorFeatures/ExternalAccess/Copilot/Internal/Analyzer/AbstractCopilotCodeAnalysisService.cs
  src/EditorFeatures/ExternalAccess/Copilot/Internal/Analyzer/CSharp/CSharpCopilotCodeAnalysisService.ReflectionWrapper.cs
  src/EditorFeatures/ExternalAccess/Copilot/Internal/Analyzer/CSharp/CSharpCopilotCodeAnalysisService.cs
  src/EditorFeatures/ExternalAccess/Copilot/InternalAPI.Unshipped.txt
  src/EditorFeatures/Test2/CodeFixes/CodeFixServiceTests.vb
  src/Features/Core/Portable/Copilot/ICopilotCodeAnalysisService.cs
Labels: Area-IDE, untriaged, VSCode

#76918 Target test projects in Workspaces and Features layers to NetVSShared
  src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs
  src/Features/CSharpTest/Microsoft.CodeAnalysis.CSharp.Features.UnitTests.csproj
  src/Features/Test/Microsoft.CodeAnalysis.Features.UnitTests.csproj
  src/Features/TestUtilities/Microsoft.CodeAnalysis.Features.Test.Utilities.csproj
  src/Features/VisualBasicTest/Microsoft.CodeAnalysis.VisualBasic.Features.UnitTests.vbproj
  src/Tools/SemanticSearch/ReferenceAssemblies/Apis/System.Collections.Immutable.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Apis/System.Collections.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Apis/System.Linq.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Apis/System.Runtime.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/SemanticSearch.ReferenceAssemblies.csproj
  src/Workspaces/CSharpTest/Microsoft.CodeAnalysis.CSharp.Workspaces.UnitTests.csproj
  src/Workspaces/CoreTest/Microsoft.CodeAnalysis.Workspaces.UnitTests.csproj
  src/Workspaces/CoreTestUtilities/Microsoft.CodeAnalysis.Workspaces.Test.Utilities.csproj
  src/Workspaces/Remote/ServiceHubTest/Microsoft.CodeAnalysis.Remote.ServiceHub.UnitTests.csproj
  src/Workspaces/VisualBasicTest/Microsoft.CodeAnalysis.VisualBasic.Workspaces.UnitTests.vbproj
Labels: Area-IDE, untriaged, VSCode

#76924 Remove accidentally added files
  src/Tools/SemanticSearch/ReferenceAssemblies/Baselines/Microsoft.CodeAnalysis.CSharp.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Baselines/Microsoft.CodeAnalysis.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Baselines/System.Collections.Immutable.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Baselines/System.Collections.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Baselines/System.Linq.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Baselines/System.Runtime.txt
Labels: Area-Infrastructure, untriaged

#76933 Update rebuild test Semantic Search Refs exclusions
  eng/test-rebuild.ps1
Labels: Area-Infrastructure, untriaged

#76871 Move merging of partial members to an earlier phase of members construction.
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/PrimaryConstructorTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/PartialPropertiesTests.cs
Labels: Area-Compilers, untriaged

#76867 Extensions parsing
  docs/compilers/CSharp/Compiler Breaking Changes - DotNet 10.md
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Errors/MessageID.cs
  src/Compilers/CSharp/Portable/Generated/CSharp.Generated.g4
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Internal.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Main.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Syntax.Generated.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Syntax/ExtensionDeclarationSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/InternalSyntax/TypeDeclarationSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/ParameterDeclarationSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/SimpleLambdaExpressionSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
  src/Compilers/CSharp/Portable/Syntax/SyntaxFactory.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxKindFacts.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit3/Diagnostics/DiagnosticAnalyzerTests.AllInOne.cs
  src/Compilers/CSharp/Test/Syntax/Generated/Syntax.Test.xml.Generated.cs
  src/Compilers/CSharp/Test/Syntax/IncrementalParsing/IncrementalParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ExtensionsParsingTests.cs
  src/Compilers/Test/Core/Traits/CompilerFeature.cs
  src/EditorFeatures/CSharpTest/Diagnostics/DiagnosticAnalyzerDriver/DiagnosticAnalyzerDriverTests.cs
Labels: Area-Compilers, Feature - Extension Everything, untriaged, Needs API Review

#76939 add configs for net9 branch
  eng/config/PublishData.json
Labels: Area-Infrastructure, untriaged

#76935 Always specify Image width/height for glyphs sourced from IGlyphService
  src/VisualStudio/Core/Def/CommonControls/MemberSelection.xaml
  src/VisualStudio/Core/Def/MoveStaticMembers/StaticMemberSelection.xaml
  src/VisualStudio/Core/Def/PickMembers/PickMembersDialog.xaml
  src/VisualStudio/Core/Def/PullMemberUp/MainDialog/PullMemberUpDialog.xaml
  src/VisualStudio/Core/Def/ValueTracking/ValueTrackingTree.xaml
Labels: Area-IDE, untriaged, Needs UX Triage

#76894 Reduce CPU costs under AnalyzerExecutor.ExecuteSyntaxNodeActions
  src/Compilers/CSharp/Portable/Emitter/EditAndContinue/PEDeltaAssemblyBuilder.cs
  src/Compilers/Core/Portable/Collections/DictionaryExtensions.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.GroupedAnalyzerActions.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs
Labels: Area-Analyzers, Area-Compilers, untriaged

#71837 Update ICSharpCode.Decompiler to 8.2.0.7535
  eng/Directory.Packages.props
  src/EditorFeatures/Test/MetadataAsSource/AbstractMetadataAsSourceTests.cs
Labels: Area-IDE, Community
