Repository dotnet/roslyn, pull requests merged in 2025-05, with the labels that each got.

#78396 Additional tests to complete the test plan
  src/Compilers/CSharp/Test/Emit3/Symbols/UserDefinedCompoundAssignmentOperatorsTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_ICompoundAssignmentOperation.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IIncrementOrDecrementOperation.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs
Labels: Area-Compilers, untriaged, Feature-UserDefinedCompoundAssignmentOperators

#78407 Switch to non-scouting queue to unblock CI
  azure-pipelines-integration.yml
Labels: Area-Infrastructure, untriaged

#78310 Move runtime async method validation into initial binding
  src/Compilers/CSharp/Portable/Binder/Binder_Await.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs
  src/Compilers/CSharp/Portable/Binder/UsingStatementBinder.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundAwaitableInfo.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/RuntimeAsyncRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/ExtensionMethodReferenceRewriter.cs
  src/Compilers/CSharp/Portable/Lowering/MethodToClassRewriter.cs
  src/Compilers/CSharp/Portable/Symbols/AssemblySymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedEntryPointSymbol.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/CorLibrary/CorTypes.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs
  src/Compilers/Core/CodeAnalysisTest/Symbols/SpecialTypeTests.cs
  src/Compilers/Core/Portable/ExtendedSpecialType.cs
  src/Compilers/Core/Portable/InternalSpecialType.cs
  src/Compilers/Core/Portable/SpecialMember.cs
  src/Compilers/Core/Portable/SpecialMembers.cs
  src/Compilers/Core/Portable/SpecialTypes.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
  src/Compilers/Core/Portable/WellKnownTypes.cs
  src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs
  src/Compilers/VisualBasic/Portable/Symbols/AssemblySymbol.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/CorLibrary/CorTypes.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/WellKnownTypeValidationTests.vb
Labels: Area-Compilers, untriaged, Feature - Runtime Async

#78412 Skip generate analyzer documentation to unblock ci
  eng/targets/GenerateAnalyzerNuspec.targets
Labels: Area-Infrastructure, untriaged

#78343 Fix syntax tree creation when modifying source generated documents
  src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionCompilationState.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SourceGeneratedDocumentState.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionWithSourceGeneratorTests.cs
Labels: Area-IDE, untriaged, VSCode

#78405 Ensure hover markdown for supported platforms uses non-breaking spaces for indentation
  src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs
  src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs
  src/EditorFeatures/CSharpTest/SignatureHelp/AttributeSignatureHelpProviderTests.cs
  src/EditorFeatures/CSharpTest/SignatureHelp/ConstructorInitializerSignatureHelpProviderTests.cs
  src/EditorFeatures/CSharpTest/SignatureHelp/ElementAccessExpressionSignatureHelpProviderTests.cs
  src/EditorFeatures/CSharpTest/SignatureHelp/GenericNameSignatureHelpProviderTests.cs
  src/EditorFeatures/CSharpTest/SignatureHelp/InvocationExpressionSignatureHelpProviderTests.cs
  src/EditorFeatures/CSharpTest/SignatureHelp/ObjectCreationExpressionSignatureHelpProviderTests.cs
  src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/SymbolCompletionProviderTests.vb
  src/EditorFeatures/VisualBasicTest/SignatureHelp/InvocationExpressionSignatureHelpProviderTests.vb
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/Shared/Utilities/SupportedPlatformData.cs
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/LanguageServer/ProtocolUnitTests/Hover/HoverTests.cs
Labels: Area-IDE, untriaged, VSCode

#78437 Exclude EditorFeatures from rebuild check
  eng/test-rebuild.ps1
Labels: Area-Compilers, untriaged

#78399 Adjust LocalBinderFactory.VisitInvocationExpression to handle attributes on extension parameter
  src/Compilers/CSharp/Portable/Binder/LocalBinderFactory.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs
Labels: Area-Compilers, Feature - Extension Everything, untriaged

#78429 Move RestoreUseStaticGraphEvaluation setting inside repo
  Directory.Solution.props
  eng/Build.props
  eng/DotNetBuild.props
  eng/build.ps1
  eng/build.sh
  eng/targets/Settings.props
  eng/test-determinism.ps1
Labels: Area-Infrastructure, untriaged

#78401 Extract out an interface for our LSP miscellaneous files workspace
  src/LanguageServer/Protocol/RoslynLanguageServer.cs
  src/LanguageServer/Protocol/Workspaces/ILspMiscellaneousFilesWorkspaceProvider.cs
  src/LanguageServer/Protocol/Workspaces/ILspMiscellaneousFilesWorkspaceProviderFactory.cs
  src/LanguageServer/Protocol/Workspaces/LspMiscellaneousFilesWorkspace.cs
  src/LanguageServer/Protocol/Workspaces/LspMiscellaneousFilesWorkspaceProvider.cs
  src/LanguageServer/Protocol/Workspaces/LspMiscellaneousFilesWorkspaceProviderFactory.cs
  src/LanguageServer/Protocol/Workspaces/LspWorkspaceManager.cs
  src/LanguageServer/Protocol/Workspaces/LspWorkspaceManagerFactory.cs
  src/LanguageServer/ProtocolUnitTests/Miscellaneous/LspMiscellaneousFilesWorkspaceTests.cs
  src/LanguageServer/ProtocolUnitTests/UriTests.cs
  src/VisualStudio/Core/Def/LanguageClient/VisualStudioLspWorkspaceRegistrationService.cs
Labels: Area-IDE, VSCode

#78420 Enable analyzer doc validation in correctness runs
  eng/targets/GenerateAnalyzerNuspec.targets
  src/RoslynAnalyzers/Tools/GenerateDocumentationAndConfigFiles/GenerateDocumentationAndConfigFiles.csproj
  src/RoslynAnalyzers/Tools/GenerateDocumentationAndConfigFiles/Program.cs
Labels: Area-Infrastructure, untriaged

#78411 Disallow shebang in project-based programs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Parser/DirectiveParser.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Syntax/Parsing/IgnoredDirectiveParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ScriptParsingTests.cs
Labels: Area-Compilers, untriaged, Feature - Ignored Directives

#78438 Add WorkItem trait discoverer
  src/Compilers/Test/Core/Assert/WorkItemAttribute.cs
  src/Compilers/Test/Core/Traits/WorkItemTraitDiscoverer.cs
Labels: Area-Compilers, untriaged

#78434 Change `++`/`--` predefined operator names for instance operators
  src/Compilers/CSharp/Portable/Binder/Binder_Crefs.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/OperatorFacts.cs
  src/Compilers/CSharp/Portable/CSharpResources.resx
  src/Compilers/CSharp/Portable/Errors/ErrorCode.cs
  src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedConversionSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityOperatorBase.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxKindFacts.cs
  src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.es.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.fr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.it.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ja.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ko.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pl.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.pt-BR.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.ru.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.tr.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf
  src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hant.xlf
  src/Compilers/CSharp/Test/Emit3/Symbols/UserDefinedCompoundAssignmentOperatorsTests.cs
  src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IIncrementOrDecrementOperation.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/CheckedUserDefinedOperatorsTests.cs
  src/Compilers/CSharp/Test/Symbol/Symbols/StaticAbstractMembersInInterfacesTests.cs
  src/Compilers/Core/Portable/PublicAPI.Unshipped.txt
  src/Compilers/Core/Portable/Symbols/WellKnownMemberNames.cs
  src/EditorFeatures/Test/MetadataAsSource/MetadataAsSourceTests.CSharp.cs
  src/EditorFeatures/Test2/FindReferences/FindReferencesTests.OperatorSymbols.vb
  src/Tools/SemanticSearch/ReferenceAssemblies/Apis/Microsoft.CodeAnalysis.txt
Labels: Area-Compilers, untriaged, Needs API Review, Feature-UserDefinedCompoundAssignmentOperators

#78455 Add copilot tests IVT to ExternalAccess.Copilot
  src/Features/ExternalAccess/Copilot/Microsoft.CodeAnalysis.ExternalAccess.Copilot.csproj
Labels: Area-IDE, untriaged

#78454 Avoid buffering and dispatching all ProducerConsumer items in one go in recent copilot helper.
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/ProducerConsumer.cs
Labels: Area-IDE, untriaged, VSCode

#78470 Remove default impl of BackgroundWorkIndicator
  src/EditorFeatures/Core/BackgroundWorkIndicator/DefaultBackgroundWorkIndicatorFactory.cs
  src/EditorFeatures/Core/BackgroundWorkIndicator/WpfBackgroundWorkIndicatorFactory.cs
Labels: Area-IDE, untriaged

#78460 Update Language Feature Status.md and Update Compiler Test Plan.md for instance operators
  docs/Language Feature Status.md
  docs/contributing/Compiler Test Plan.md
Labels: Area-Compilers, Feature-UserDefinedCompoundAssignmentOperators

#78469 Update to platform background work pattern to make porting to their impl easier
  src/EditorFeatures/CSharp/EventHookup/EventHookupCommandHandler_TabKeyCommand.cs
  src/EditorFeatures/Core/BackgroundWorkIndicator/BackgroundWorkIndicatorContext.cs
  src/EditorFeatures/Core/BackgroundWorkIndicator/IBackgroundWorkIndicatorContext.cs
  src/EditorFeatures/Core/ExtractMethod/ExtractMethodCommandHandler.cs
  src/EditorFeatures/Core/GoToDefinition/GoToDefinitionCommandHandler.cs
  src/EditorFeatures/Core/Organizing/OrganizeDocumentCommandHandler.cs
Labels: Area-IDE, untriaged

#78402 Make compiler detection more resilient
  src/Compilers/Core/MSBuildTask/ManagedCompiler.cs
  src/Compilers/Core/MSBuildTask/ManagedToolTask.cs
  src/Compilers/Core/MSBuildTask/TaskTestHost.cs
  src/Compilers/Core/MSBuildTask/Utilities.cs
  src/Compilers/Core/MSBuildTaskTests/CscTests.cs
  src/Compilers/Core/MSBuildTaskTests/TestUtilities/TaskTestUtil.cs
  src/Compilers/Server/VBCSCompilerTests/CompilerServerApiTest.cs
  src/Compilers/Shared/BuildServerConnection.cs
  src/Compilers/Shared/RuntimeHostInfo.cs
Labels: Area-Compilers, untriaged

#78442 Extensions: resolve some follow-up comments on signature conflicts and betterness
  src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs
Labels: Area-Compilers, Feature - Extension Everything, untriaged

#78448 Fix razor redirect
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/HostDiagnosticAnalyzerProvider.cs
  src/Tools/ExternalAccess/Razor/Features/RazorAnalyzerAssemblyResolver.cs
Labels: Area-IDE, untriaged, VSCode

#78403 Reduce allocations during SourceGeneration
  src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/SourceGenerator.cs
Labels: Area-Compilers, untriaged

#78479 Remove now unused methods from IWorkspaceProjectContext
  src/VisualStudio/Core/Def/ProjectSystem/CPS/IWorkspaceProjectContext.cs
  src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs
Labels: Area-IDE, untriaged

#78493 Add directory targets from Rainer
  src/VisualStudio/Directory.Build.targets
Labels: Area-IDE, untriaged

#78497 Rectify status of dictionary expressions
  docs/Language Feature Status.md
Labels: Area-Compilers, untriaged

#78353 Add code for analzying copilot changes.
  src/EditorFeatures/Core.Wpf/Copilot/CopilotWpfTextCreationListener.cs
  src/EditorFeatures/TestUtilities/Diagnostics/DiagnosticTaggerWrapper.cs
  src/Features/Core/Portable/Copilot/CopilotChangeAnalysis.cs
  src/Features/Core/Portable/Copilot/CopilotChangeAnalysisUtilities.cs
  src/Features/Core/Portable/Copilot/CopilotOptions.cs
  src/Features/Core/Portable/Copilot/ICopilotChangeAnalysisService.cs
  src/Features/Core/Portable/Copilot/IRemoteCopilotChangeAnalysisService.cs
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
  src/VisualStudio/Core/Test.Next/Services/ServiceHubServicesTests.cs
  src/Workspaces/CoreTestUtilities/Logging/TestTelemetryLogger.cs
  src/Workspaces/CoreTestUtilities/Microsoft.CodeAnalysis.Workspaces.Test.Utilities.csproj
  src/Workspaces/Remote/ServiceHub/Services/Copilot/RemoteCopilotChangeAnalysisService.cs
  src/Workspaces/Remote/ServiceHubTest/Microsoft.CodeAnalysis.Remote.ServiceHub.UnitTests.csproj
  src/Workspaces/Remote/ServiceHubTest/TelemetryLoggerTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/Logger.LogBlock.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/Logger.cs
Labels: Area-IDE, untriaged, VSCode

#78496 Remove unused field
  src/EditorFeatures/Core/Suggestions/SuggestedActionsSource.cs
  src/EditorFeatures/Core/Suggestions/SuggestedActionsSourceProvider.cs
Labels: Area-IDE, untriaged

#78500 Use a project reference for M.CA.AnalyzerUtilities
  Roslyn.sln
  eng/Directory.Packages.props
  eng/Versions.props
  src/Compilers/Test/Core/Microsoft.CodeAnalysis.Test.Utilities.csproj
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/RoslynAnalyzers/Directory.Build.props
  src/RoslynAnalyzers/Microsoft.CodeAnalysis.AnalyzerUtilities/Microsoft.CodeAnalysis.AnalyzerUtilities.csproj
  src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.sarif
  src/RoslynAnalyzers/Microsoft.CodeAnalysis.BannedApiAnalyzers/Microsoft.CodeAnalysis.BannedApiAnalyzers.sarif
  src/RoslynAnalyzers/NuGet/Microsoft.CodeAnalysis.AnalyzerUtilities/Microsoft.CodeAnalysis.AnalyzerUtilities.Package.csproj
  src/RoslynAnalyzers/PerformanceSensitiveAnalyzers/Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers.sarif
  src/RoslynAnalyzers/PublicApiAnalyzers/Microsoft.CodeAnalysis.PublicApiAnalyzers.sarif
  src/RoslynAnalyzers/Roslyn.Diagnostics.Analyzers/Roslyn.Diagnostics.Analyzers.sarif
  src/RoslynAnalyzers/Text.Analyzers/RulesMissingDocumentation.md
  src/RoslynAnalyzers/Text.Analyzers/Text.Analyzers.sarif
  src/RoslynAnalyzers/assets/EULA.txt
  src/RoslynAnalyzers/assets/ThirdPartyNotices.txt
  src/RoslynAnalyzers/assets/install.ps1
  src/RoslynAnalyzers/assets/uninstall.ps1
  src/Setup/DevDivInsertionFiles/DevDivInsertionFiles.csproj
  src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj
Labels: Area-Infrastructure, untriaged

#78494 Merge EditorFeatures.Wpf entirely into EditorFeatures
  Ide.slnf
  Roslyn.sln
  eng/config/OptProf.json
  eng/test-rebuild.ps1
  src/EditorFeatures/CSharpTest/Microsoft.CodeAnalysis.CSharp.EditorFeatures.UnitTests.csproj
  src/EditorFeatures/Core.Wpf/Microsoft.CodeAnalysis.EditorFeatures.Wpf.csproj
  src/EditorFeatures/Core.Wpf/PublicAPI.Shipped.txt
  src/EditorFeatures/Core.Wpf/PublicAPI.Unshipped.txt
  src/EditorFeatures/Core/Copilot/CopilotWpfTextCreationListener.cs
  src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
  src/EditorFeatures/Core/Peek/IPeekableItemFactory.cs
  src/EditorFeatures/DiagnosticsTestUtilities/Microsoft.CodeAnalysis.EditorFeatures.DiagnosticsTests.Utilities.csproj
  src/EditorFeatures/Test/Microsoft.CodeAnalysis.EditorFeatures.UnitTests.csproj
  src/EditorFeatures/Test2/Microsoft.CodeAnalysis.EditorFeatures2.UnitTests.vbproj
  src/EditorFeatures/TestUtilities/Microsoft.CodeAnalysis.EditorFeatures.Test.Utilities.csproj
  src/EditorFeatures/Text/Microsoft.CodeAnalysis.EditorFeatures.Text.csproj
  src/EditorFeatures/VisualBasicTest/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.UnitTests.vbproj
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/Interactive/Host/Microsoft.CodeAnalysis.InteractiveHost.csproj
  src/LanguageServer/Protocol/Microsoft.CodeAnalysis.LanguageServer.Protocol.csproj
  src/NuGet/VS.ExternalAPIs.Roslyn.Package/VS.ExternalAPIs.Roslyn.Package.csproj
  src/Tools/IdeBenchmarks/IdeBenchmarks.csproj
  src/VisualStudio/CSharp/Test/Microsoft.VisualStudio.LanguageServices.CSharp.UnitTests.csproj
  src/VisualStudio/Core/Def/Microsoft.VisualStudio.LanguageServices.csproj
  src/VisualStudio/Core/Test.Next/Roslyn.VisualStudio.Next.UnitTests.csproj
  src/VisualStudio/Core/Test/Microsoft.VisualStudio.LanguageServices.UnitTests.vbproj
  src/VisualStudio/IntegrationTest/New.IntegrationTests/Microsoft.VisualStudio.LanguageServices.New.IntegrationTests.csproj
  src/VisualStudio/LiveShare/Test/Microsoft.VisualStudio.LanguageServices.LiveShare.UnitTests.csproj
  src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj
  src/VisualStudio/Setup/source.extension.vsixmanifest
  src/VisualStudio/TestUtilities2/Microsoft.VisualStudio.LanguageServices.Test.Utilities2.vbproj
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
Labels: Area-Infrastructure, untriaged, Needs API Review

#78446 Targeted perf changes to CommandLineParser
  src/Compilers/Core/Portable/CommandLine/CommandLineParser.cs
Labels: Area-Compilers, untriaged

#78484 Use lazy initialization for members in CodeFixService
  src/Features/Core/Portable/CodeFixes/Service/CodeFixService.cs
Labels: Area-IDE, untriaged, VSCode

#78426 Onboard the GitHub Action based Issue-Labeler
  .github/workflows/labeler-cache-retention.yml
  .github/workflows/labeler-predict-issues.yml
  .github/workflows/labeler-predict-pulls.yml
  .github/workflows/labeler-promote.yml
  .github/workflows/labeler-train.yml
  .github/workflows/labeler.md
Labels: Area-Infrastructure, untriaged

#78509 Exclude VS.ExternalAPIs.Roslyn.Package from source-build
  src/NuGet/VS.ExternalAPIs.Roslyn.Package/VS.ExternalAPIs.Roslyn.Package.csproj
Labels: Area-Infrastructure, untriaged

#78274 Dictionary expressions: extend support for key-value pairs to non-dictionary collections of `KeyValuePair<K, V>`
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/DictionaryExpressionTests.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
Labels: Area-Compilers, untriaged, Feature - Dictionary Expressions

#77088 Publish symbols manually to internal feeds for PR validation
  azure-pipelines-pr-validation.yml
Labels: Area-Infrastructure, untriaged

#78382 PooledObjects cleanup
  Roslyn.sln
  src/Analyzers/CSharp/Analyzers/ConvertSwitchStatementToExpression/ConvertSwitchStatementToExpressionDiagnosticAnalyzer.cs
  src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LoweredDynamicOperation.cs
  src/Compilers/Core/Portable/Collections/ArrayBuilderExtensions.cs
  src/Compilers/Core/Portable/Emit/NoPia/CommonEmbeddedMember.cs
  src/Compilers/Core/Portable/Emit/NoPia/CommonEmbeddedParameter.cs
  src/Compilers/Core/Portable/Emit/NoPia/CommonEmbeddedType.cs
  src/Compilers/Core/Portable/Text/CompositeText.cs
  src/Dependencies/PooledObjects/ArrayBuilder.cs
  src/Dependencies/PooledObjects/ArrayBuilderExtensions.cs
  src/Dependencies/PooledObjects/Microsoft.CodeAnalysis.PooledObjects.Package.csproj
  src/Dependencies/PooledObjects/Microsoft.CodeAnalysis.PooledObjects.projitems
  src/Dependencies/PooledObjects/PooledDictionary.cs
  src/Dependencies/PooledObjects/PooledHashSet.cs
  src/Dependencies/PooledObjects/PooledStringBuilder.cs
  src/ExpressionEvaluator/Core/Source/ResultProvider/Portable/Microsoft.CodeAnalysis.ResultProvider.csproj
  src/ExpressionEvaluator/Core/Test/ResultProvider/Microsoft.CodeAnalysis.ResultProvider.Utilities.csproj
  src/Features/Core/Portable/Structure/Syntax/AbstractBlockStructureProvider.cs
  src/Interactive/Host/Microsoft.CodeAnalysis.InteractiveHost.csproj
  src/Workspaces/MSBuild/BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/ObjectPools/PooledDictionary.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/ObjectPools/PooledHashSet.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/ObjectPools/PooledStringBuilder.cs
Labels: Area-Compilers, untriaged, VSCode

#78495 Delay loading of CodeRefactoringProvider's till absolutely needed
  src/EditorFeatures/Test/CodeRefactorings/CodeRefactoringServiceTest.cs
  src/Features/Core/Portable/CodeRefactorings/CodeRefactoringService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Workspace/Mef/CodeChangeProviderMetadata.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Workspace/Mef/OrderableLanguageDocumentMetadata.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensions.projitems
Labels: Area-IDE, Community, untriaged, VSCode

#78463 Don't unnecessarily create a document when only the document state is needed
  src/Workspaces/Core/Portable/Workspace/Solution/Checksum_Factory.cs
  src/Workspaces/Core/Portable/Workspace/Workspace.cs
  src/Workspaces/CoreTest/ChecksumTests.cs
Labels: Area-IDE, untriaged, VSCode

#78512 Extensions: handle extensions in VB SymbolDisplay
  src/Compilers/VisualBasic/Portable/SymbolDisplay/SymbolDisplayVisitor.Types.vb
  src/Compilers/VisualBasic/Test/Symbol/SymbolDisplay/SymbolDisplayTests.vb
Labels: Area-Compilers, Feature - Extension Everything, untriaged

#78521 Switch to non-scouting queue to unblock CI
  azure-pipelines-integration.yml
Labels: Area-Infrastructure, untriaged

#78499 Support consumption of unary extension operators.
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/Binder_TupleOperators.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/UnaryOperatorOverloadResolution.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionOperatorsTests.cs
  src/Compilers/VisualBasic/Portable/SymbolDisplay/SymbolDisplayVisitor.Types.vb
Labels: Area-Compilers, Feature - Extension Everything, untriaged

#78513 Switch to simple primary constructors for several DI types.
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptDidChangeHandler.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptDidCloseHandler.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptDidOpenHandler.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptLifeCycleManager.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptLspWorkspaceManagerFactory.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptProjectContextHandler.cs
  src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptRequestTelemetryLoggerFactory.cs
  src/LanguageServer/Protocol/Features/UnifiedSuggestions/UnifiedSuggestedActions/UnifiedSuggestedAction.cs
  src/LanguageServer/Protocol/Handler/Commands/ProvidesCommandAttribute.cs
  src/LanguageServer/Protocol/Handler/DocumentChanges/DidCloseHandler.cs
  src/LanguageServer/Protocol/Handler/DocumentChanges/DidOpenHandler.cs
  src/LanguageServer/Protocol/Handler/MethodAttribute.cs
  src/LanguageServer/Protocol/Handler/ProjectContext/GetTextDocumentWithContextHandler.cs
  src/LanguageServer/Protocol/Handler/Telemetry/RequestTelemetryLoggerFactory.cs
  src/LanguageServer/Protocol/LspServices/AbstractLspServiceProvider.cs
  src/LanguageServer/Protocol/LspServices/ExportCSharpVisualBasicLspServiceFactoryAttribute.cs
  src/LanguageServer/Protocol/LspServices/ExportCSharpVisualBasicStatelessLspServiceAttribute.cs
  src/LanguageServer/Protocol/LspServices/ExportLspServiceFactoryAttribute.cs
  src/LanguageServer/Protocol/LspServices/ExportStatelessLspServiceAttribute.cs
  src/LanguageServer/Protocol/LspServices/RoslynLspServiceProvider.cs
  src/LanguageServer/Protocol/Workspaces/LspWorkspaceManagerFactory.cs
  src/Tools/ExternalAccess/Xaml/External/XamlCommandAttribute.cs
  src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/CodeActions/CodeActionsHandlerProvider.cs
Labels: Area-IDE, untriaged, VSCode

#78526 Shorten log category name
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Utilities/AbstractLanguageServerHostTests.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/LanguageServer/LanguageServerHost.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Program.cs
Labels: Area-Infrastructure, VSCode

#78532 Fix test helper message to avoid NRE
  src/Workspaces/CoreTestUtilities/ObjectExtensions.cs
Labels: Area-IDE, VSCode

#78536 Switch MethodImplAttributes.Async to 0x2000
  docs/compilers/CSharp/Runtime Async Design.md
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs
Labels: Area-Compilers, Feature - Runtime Async

#78522 Fix information logs getting logged as debug in VSCode
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/LanguageServer/Handler/Restore/RestoreHandler.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Logging/LspServiceLogger.cs
  src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/AbstractLanguageServer.cs
  src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs
  src/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/LanguageServer/Protocol/Handler/CodeActions/CodeActionResolveHelper.cs
  src/LanguageServer/Protocol/Handler/Completion/CompletionResolveHandler.cs
  src/LanguageServer/Protocol/Handler/Diagnostics/AbstractDocumentPullDiagnosticHandler.cs
  src/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs
  src/LanguageServer/Protocol/Handler/Diagnostics/AbstractWorkspacePullDiagnosticsHandler.cs
  src/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSourceProviders/WorkspaceDiagnosticSourceHelpers.cs
  src/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticsPullCache.cs
  src/LanguageServer/Protocol/Handler/DocumentChanges/DidCloseHandler.cs
  src/LanguageServer/Protocol/Handler/DocumentChanges/DidOpenHandler.cs
  src/LanguageServer/Protocol/Handler/InlineCompletions/XmlSnippetParser.cs
  src/LanguageServer/Protocol/Handler/MapCode/MapCodeHandler.cs
  src/LanguageServer/Protocol/Handler/RelatedDocuments/RelatedDocumentsHandler.cs
  src/LanguageServer/Protocol/Handler/RequestContext.cs
  src/LanguageServer/Protocol/Handler/SpellCheck/AbstractSpellCheckingHandler.cs
  src/LanguageServer/Protocol/Handler/SpellCheck/DocumentSpellCheckHandler.cs
  src/LanguageServer/Protocol/Handler/SpellCheck/WorkspaceSpellCheckHandler.cs
  src/LanguageServer/Protocol/RoslynLanguageServer.cs
  src/LanguageServer/Protocol/Workspaces/LspWorkspaceManager.cs
  src/VisualStudio/Core/Def/LanguageClient/VisualStudioLogHubLoggerFactory.cs
Labels: Area-IDE, untriaged, VSCode

#78541 Extract helper to make it easier for other features to request copilot analysis
  src/EditorFeatures/Core/Copilot/CopilotWpfTextCreationListener.cs
  src/Features/Core/Portable/Copilot/CopilotChangeAnalysisUtilities.cs
Labels: Area-IDE, VSCode

#78540 Collect data about which code fixes end up making changes that conflict with other code fixes
  src/Features/Core/Portable/Copilot/CopilotChangeAnalysis.cs
  src/Features/Core/Portable/Copilot/CopilotChangeAnalysisUtilities.cs
  src/Features/Core/Portable/Copilot/ICopilotChangeAnalysisService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/IntervalTreeHelpers.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Collections/SimpleMutableIntervalTree`2.cs
Labels: Area-IDE, VSCode

#78507 Fix crash in 'introduce variable' on top-level statements
  src/Features/CSharpTest/IntroduceVariable/IntroduceVariableTests.cs
  src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.State.cs
Labels: Area-IDE, Community, untriaged, VSCode

#78542 Cache extension method import info per project ID
  src/Features/CSharp/Portable/Completion/CompletionProviders/ImportCompletion/ExtensionMethodImportCompletionProvider.cs
  src/Features/Core/Portable/Completion/Log/CompletionProvidersLogger.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractExtensionMethodImportCompletionProvider.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.SymbolComputer.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/IRemoteExtensionMethodImportCompletionService.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/SerializableUnimportedExtensionMethods.cs
  src/Workspaces/Remote/ServiceHub/Services/ExtensionMethodImportCompletion/RemoteExtensionMethodImportCompletionService.cs
Labels: Area-IDE, VSCode

#78525 Cancel running requests when the connection terminates
  src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/AbstractLanguageServer.cs
Labels: Area-IDE, VSCode

#78545 Use pattern matching
  src/Analyzers/CSharp/Analyzers/UseCollectionExpression/CSharpUseCollectionExpressionForBuilderDiagnosticAnalyzer.cs
  src/Analyzers/CSharp/CodeFixes/Iterator/CSharpChangeToIEnumerableCodeFixProvider.cs
  src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryLambdaExpression/CSharpRemoveUnnecessaryLambdaExpressionCodeFixProvider.cs
  src/Analyzers/Core/Analyzers/UseCollectionInitializer/UpdateExpressionState.cs
  src/Analyzers/Core/CodeFixes/PopulateSwitch/AbstractPopulateSwitchCodeFixProvider.cs
  src/EditorFeatures/CSharp/EventHookup/EventHookupSessionManager_EventHookupSession.cs
  src/Features/CSharp/Portable/SignatureHelp/PrimaryConstructorBaseTypeSignatureHelpProvider.cs
  src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ImportCompletionItem.cs
  src/Features/Core/Portable/Completion/Providers/Scripting/AbstractReferenceDirectiveCompletionProvider.cs
  src/Features/Core/Portable/GenerateComparisonOperators/GenerateComparisonOperatorsCodeRefactoringProvider.cs
  src/Features/Core/Portable/InlineMethod/AbstractInlineMethodRefactoringProvider.cs
  src/Features/Core/Portable/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs
  src/VisualStudio/Core/Def/Workspace/VisualStudioSymbolNavigationService.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/AnalyzersCommandHandler.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/ContextMenuController.cs
  src/VisualStudio/IntegrationTest/New.IntegrationTests/QuickInfoToStringConverter.cs
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/OptionPages/InternalOptionsControl.cs
  src/Workspaces/Core/Portable/Log/AggregateLogger.cs
  src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs
  src/Workspaces/Core/Portable/Utilities/Documentation/XmlDocumentationProvider.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
  src/Workspaces/Remote/ServiceHub/Services/EncapsulateField/RemoteEncapsulateFieldService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ISymbolExtensions_Accessibility.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ITypeSymbolExtensions.cs
Labels: Area-IDE, VSCode

#78537 Add VB ref assembly to semantic search
  eng/test-rebuild.ps1
  src/Tools/SemanticSearch/ReferenceAssemblies/ApiSet/Microsoft.CodeAnalysis.VisualBasic.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/Apis/Microsoft.CodeAnalysis.VisualBasic.txt
  src/Tools/SemanticSearch/ReferenceAssemblies/SemanticSearch.ReferenceAssemblies.csproj
Labels: Area-Infrastructure

#78201 Update `AbstractImplementAbstractClassCodeFixProvider.cs` source
  docs/analyzers/FixAllProvider.md
Labels: Area-Infrastructure, Community, untriaged

#78519 Introduce -productBuild and -sourceBuild switches
  eng/build.ps1
  eng/build.sh
Labels: Area-Infrastructure, untriaged

#78539 Document more steps in our C# release process
  src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs
Labels: Area-Compilers

#78319 Extensions: analyzer actions
  src/Compilers/CSharp/CSharpAnalyzerDriver/CSharpDeclarationComputer.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs
  src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticStartAnalysisScope.cs
Labels: Area-Compilers, Feature - Extension Everything, untriaged

#78553 Update field value for NavBar Integration Tests
  src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs
Labels: Area-IDE

#78475 Update GetFirstRelatedDocumentId to not return documents with the same path within the same project
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
Labels: Area-IDE, untriaged, VSCode

#78520 Gracefully handle span mapping failing
  src/Tools/ExternalAccess/Razor/Features/RazorMappingServiceWrapper.cs
Labels: Area-IDE, untriaged

#78428 Implement PDG.WithProjectsRemoved
  src/Workspaces/Core/Portable/Workspace/Solution/ProjectDependencyGraph_RemoveProject.cs
  src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs
Labels: Area-IDE, untriaged, VSCode

#78441 Selectively persist the commandline to temporary storage
  src/VisualStudio/CSharp/Impl/ProjectSystemShim/CSharpProjectShim.OptionsProcessor.cs
  src/VisualStudio/Core/Def/ProjectSystem/Legacy/AbstractLegacyProject.cs
  src/VisualStudio/Core/Def/ProjectSystem/Legacy/AbstractLegacyProjectSystemProjectOptionsProcessor.cs
  src/VisualStudio/VisualBasic/Impl/ProjectSystemShim/VisualBasicProject.OptionsProcessor.vb
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProjectOptionsProcessor.cs
Labels: Area-IDE, untriaged, VSCode

#78538 Fix checked/unchecked pair matching for extension unary operators during consumption
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/UnaryOperatorOverloadResolution.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionOperatorsTests.cs
Labels: Area-Compilers, Feature - Extension Everything

#78564 Update 'with' signature help based on latest LDM decisions
  src/EditorFeatures/CSharpTest/SignatureHelp/WithElementSignatureHelpProviderTests.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/CollectionExpressionUtilities.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ICompilationExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/WithElementSyntaxExtensions.cs
Labels: VSCode

#78436 Collection arguments: binding for interface target types
  src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs
  src/Compilers/CSharp/Portable/Symbols/CollectionArgumentsSignatureOnlyMethodSymbol.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionArgumentTests.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/DictionaryExpressionTests.cs
  src/Compilers/Core/Portable/WellKnownMember.cs
  src/Compilers/Core/Portable/WellKnownMembers.cs
Labels: Area-Compilers, untriaged, Feature - Dictionary Expressions

#78488 File based programs IDE support
  .vscode/tasks.json
  docs/features/file-based-programs-vscode.md
  src/Features/Core/Portable/Workspace/MiscellaneousFileUtilities.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/TelemetryReporterTests.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Utilities/AbstractLanguageServerHostTests.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/Utilities/LanguageServerTestComposition.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer.UnitTests/WorkspaceProjectFactoryServiceTests.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileBasedProgramsProjectSystem.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileBasedProgramsWorkspaceProviderFactory.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectLoader.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerWorkspace.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerWorkspaceFactory.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/ProjectToLoad.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/Razor/RazorDynamicFileInfoProvider.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/VirtualProject.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/WorkspaceProjectFactoryService.cs
  src/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/LanguageServer/Protocol/Features/Options/LanguageServerProjectSystemOptionsStorage.cs
  src/LanguageServer/Protocol/Handler/Configuration/DidChangeConfigurationNotificationHandler_OptionList.cs
  src/LanguageServer/Protocol/Workspaces/ILspMiscellaneousFilesWorkspaceProvider.cs
  src/LanguageServer/Protocol/Workspaces/LspMiscellaneousFilesWorkspaceProvider.cs
  src/LanguageServer/Protocol/Workspaces/LspWorkspaceManager.cs
  src/LanguageServer/ProtocolUnitTests/Configuration/DidChangeConfigurationNotificationHandlerTest.cs
  src/VisualStudio/Core/Test.Next/Options/VisualStudioOptionStorageTests.cs
Labels: Area-Infrastructure, untriaged, VSCode

#78483 Unset CompilerType from Csc
  src/Compilers/Core/MSBuildTask/ManagedCompiler.cs
  src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets
  src/Compilers/Core/MSBuildTask/Microsoft.VisualBasic.Core.targets
Labels: Area-Compilers, untriaged

#78388 Add Microsoft.CodeAnalysis.Extensions package
  Roslyn.sln
  eng/config/PublishData.json
  eng/test-rebuild.ps1
  src/CodeStyle/Core/Analyzers/Microsoft.CodeAnalysis.CodeStyle.csproj
  src/Compilers/Core/Portable/SpecialTypeExtensions.cs
  src/VisualStudio/CSharp/Test/DesignerAttribute/DesignerAttributeServiceTests.cs
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/CompilationExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/SpecialTypeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Compilation/CompilationExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Microsoft.CodeAnalysis.Extensions.Package.csproj
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Microsoft.CodeAnalysis.Extensions.projitems
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Microsoft.CodeAnalysis.Extensions.shproj
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/AccessibilityUtilities.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/IAssemblySymbolExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/IMethodSymbolExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/INamedTypeSymbolExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/INamespaceOrTypeSymbolExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/IParameterSymbolExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/IPropertySymbolExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/ISymbolExtensions.RequiresUnsafeModifierVisitor.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/ISymbolExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/ISymbolExtensions_Accessibility.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/ITypeGenerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/ITypeParameterSymbolExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/ITypeSymbolExtensions.AnonymousTypeRemover.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/ITypeSymbolExtensions.CollectTypeParameterSymbolsVisitor.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/ITypeSymbolExtensions.CompilationTypeGenerator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/ITypeSymbolExtensions.MinimalAccessibilityVisitor.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/ITypeSymbolExtensions.SubstituteTypesVisitor.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/ITypeSymbolExtensions.UnavailableTypeParameterRemover.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/ITypeSymbolExtensions.UnnamedErrorTypeRemover.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/ITypeSymbolExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/MethodKindExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/PredefinedOperator.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/PredefinedType.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/PredefinedTypeExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/SignatureComparer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/SymbolDisplayFormats.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/SymbolEquivalenceComparer.AssemblyComparers.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/SymbolEquivalenceComparer.EquivalenceVisitor.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/SymbolEquivalenceComparer.GetHashCodeVisitor.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/SymbolEquivalenceComparer.ParameterSymbolEqualityComparer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/SymbolEquivalenceComparer.SignatureTypeSymbolEquivalenceComparer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/SymbolEquivalenceComparer.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/SymbolVisibility.cs
Labels: Area-IDE, untriaged, VSCode

#78555 Update XAML EA to use DocumentUri instead of System.Uri
  src/Tools/ExternalAccess/Xaml/External/ConversionHelpers.cs
  src/Tools/ExternalAccess/Xaml/External/IResolveCachedDataService.cs
  src/Tools/ExternalAccess/Xaml/External/ResolveDataConversions.cs
  src/Tools/ExternalAccess/Xaml/External/XamlRequestContext.cs
  src/Tools/ExternalAccess/Xaml/External/XamlRequestHandlerBase.cs
  src/Tools/ExternalAccess/Xaml/External/XamlRequestHandlerFactoryBase.cs
  src/Tools/ExternalAccess/Xaml/InternalAPI.Unshipped.txt
Labels: Area-IDE

#78554 Fix MoveType to create debuggable documents
  eng/config/BannedSymbols.txt
  src/Analyzers/CSharp/Tests/MakeFieldReadonly/MakeFieldReadonlyTests.cs
  src/Analyzers/CSharp/Tests/UseAutoProperty/UseAutoPropertyTests.cs
  src/Analyzers/VisualBasic/Tests/UseAutoProperty/UseAutoPropertyTests.vb
  src/EditorFeatures/CSharpTest/ChangeSignature/AddParameterTests.Formatting.cs
  src/EditorFeatures/CSharpTest/ExtractInterface/ExtractInterfaceTests.cs
  src/EditorFeatures/CSharpTest/Interactive/NavigateTo/InteractiveNavigateToTests.cs
  src/EditorFeatures/CSharpTest/NavigateTo/NavigateToTests.cs
  src/EditorFeatures/CSharpTest/Rename/CSharpInlineRenameServiceTests.cs
  src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/AbstractCodeActionOrUserDiagnosticTest_TestAddDocument.cs
  src/EditorFeatures/DiagnosticsTestUtilities/Diagnostics/AbstractUserDiagnosticTest_GenerateTypeDialog.cs
  src/EditorFeatures/DiagnosticsTestUtilities/MoveType/AbstractMoveTypeTest.cs
  src/EditorFeatures/Test/MetadataAsSource/AbstractMetadataAsSourceTests.TestContext.cs
  src/EditorFeatures/Test2/Diagnostics/DiagnosticProviderTests.vb
  src/EditorFeatures/Test2/Diagnostics/DiagnosticServiceTests.vb
  src/EditorFeatures/Test2/NavigationBar/TestHelpers.vb
  src/EditorFeatures/Test2/NavigationBar/VisualBasicNavigationBarTests.vb
  src/EditorFeatures/Test2/Peek/PeekTests.vb
  src/EditorFeatures/Test2/Rename/RenameEngineTests.vb
  src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb
  src/EditorFeatures/Test2/SyncNamespaces/SyncNamespacesServiceTests.vb
  src/EditorFeatures/VisualBasicTest/NavigateTo/NavigateToTests.vb
  src/Features/CSharpTest/ExtractMethod/ExtractLocalFunctionTests.cs
  src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionCodeFixProvider.AbstractGlobalSuppressMessageCodeAction.cs
  src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.Editor.cs
  src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.MoveTypeEditor.cs
  src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersOptions.cs
  src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs
  src/Features/TestUtilities/Snippets/AbstractSnippetProviderTests.cs
  src/LanguageServer/Protocol.TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs
  src/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs
  src/VisualStudio/CSharp/Test/DocumentOutline/DocumentOutlineTestsBase.cs
  src/VisualStudio/Core/Test/CodeModel/CSharp/RootCodeModelTests.vb
  src/VisualStudio/Core/Test/CodeModel/VisualBasic/RootCodeModelTests.vb
  src/VisualStudio/Core/Test/MoveStaticMembers/MoveStaticMembersViewModelTest.vb
  src/VisualStudio/Core/Test/Progression/InheritsFromGraphQueryTests.vb
  src/VisualStudio/Core/Test/SolutionExplorer/CpsDiagnosticItemSourceTests.vb
  src/VisualStudio/Core/Test/Venus/DocumentService_IntegrationTests.vb
  src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs
  src/Workspaces/CoreTest/SolutionTests/SolutionTests.cs
  src/Workspaces/CoreTestUtilities/SolutionUtilities.cs
  src/Workspaces/CoreTestUtilities/Workspaces/TestHostDocument.cs
  src/Workspaces/CoreTestUtilities/Workspaces/TestWorkspace.cs
  src/Workspaces/CoreTestUtilities/Workspaces/TestWorkspace_XmlConsumption.cs
Labels: Area-IDE, VSCode

#78570 Support more consumption scenarios for unary extension operators
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs
  src/Compilers/CSharp/Portable/Binder/Binder_TupleOperators.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionOperatorsTests.cs
Labels: Area-Compilers, Feature - Extension Everything

#78576 Remove localized strings from Collections source package
  Roslyn.sln
  src/Dependencies/Collections/Internal/SR.cs
  src/Dependencies/Collections/Internal/Strings.resx
  src/Dependencies/Collections/Internal/xlf/Strings.cs.xlf
  src/Dependencies/Collections/Internal/xlf/Strings.de.xlf
  src/Dependencies/Collections/Internal/xlf/Strings.es.xlf
  src/Dependencies/Collections/Internal/xlf/Strings.fr.xlf
  src/Dependencies/Collections/Internal/xlf/Strings.it.xlf
  src/Dependencies/Collections/Internal/xlf/Strings.ja.xlf
  src/Dependencies/Collections/Internal/xlf/Strings.ko.xlf
  src/Dependencies/Collections/Internal/xlf/Strings.pl.xlf
  src/Dependencies/Collections/Internal/xlf/Strings.pt-BR.xlf
  src/Dependencies/Collections/Internal/xlf/Strings.ru.xlf
  src/Dependencies/Collections/Internal/xlf/Strings.tr.xlf
  src/Dependencies/Collections/Internal/xlf/Strings.zh-Hans.xlf
  src/Dependencies/Collections/Internal/xlf/Strings.zh-Hant.xlf
  src/Dependencies/Collections/Microsoft.CodeAnalysis.Collections.Package.csproj
  src/Dependencies/Collections/Microsoft.CodeAnalysis.Collections.projitems
  src/Dependencies/Collections/README.md
Labels: Area-IDE

#78588 Fix embedded language classification inside multi-line string
  src/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHelpers.cs
  src/LanguageServer/ProtocolUnitTests/SemanticTokens/AbstractSemanticTokensTests.cs
  src/LanguageServer/ProtocolUnitTests/SemanticTokens/SemanticTokensRangeTests.cs
Labels: Area-IDE, VSCode

#78596 Revert "Update XAML EA to use DocumentUri instead of System.Uri (#78555)"
  src/Tools/ExternalAccess/Xaml/External/ConversionHelpers.cs
  src/Tools/ExternalAccess/Xaml/External/IResolveCachedDataService.cs
  src/Tools/ExternalAccess/Xaml/External/ResolveDataConversions.cs
  src/Tools/ExternalAccess/Xaml/External/XamlRequestContext.cs
  src/Tools/ExternalAccess/Xaml/External/XamlRequestHandlerBase.cs
  src/Tools/ExternalAccess/Xaml/External/XamlRequestHandlerFactoryBase.cs
  src/Tools/ExternalAccess/Xaml/InternalAPI.Unshipped.txt
Labels: Area-IDE

#78582 Add a reference to the tracking bug for a workaround
  src/VisualStudio/Directory.Build.targets
Labels: Area-IDE

#78598 Rename LSP messages for VisualStudio.Extensibility integration
  src/LanguageServer/Protocol/Handler/Extensions/ActivateExtensionHandler.cs
  src/LanguageServer/Protocol/Handler/Extensions/ActivateExtensionParams.cs
  src/LanguageServer/Protocol/Handler/Extensions/ActivateExtensionResponse.cs
  src/LanguageServer/Protocol/Handler/Extensions/DeactivateExtensionHandler.cs
  src/LanguageServer/Protocol/Handler/Extensions/DeactivateExtensionParams.cs
  src/LanguageServer/Protocol/Handler/Extensions/DispatchDocumentExtensionMessageHandler.cs
  src/LanguageServer/Protocol/Handler/Extensions/DispatchDocumentExtensionMessageParams.cs
  src/LanguageServer/Protocol/Handler/Extensions/DispatchExtensionMessageResponse.cs
  src/LanguageServer/Protocol/Handler/Extensions/DispatchWorkspaceExtensionMessageHandler.cs
  src/LanguageServer/Protocol/Handler/Extensions/DispatchWorkspaceExtensionMessageParams.cs
Labels: Area-IDE, VSCode

#78599 Ensure we pass unique binlog paths to each BuildHost
  SpellingExclusions.dic
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/BinLogPathProvider.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileBasedProgramsProjectSystem.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/FileBasedProgramsWorkspaceProviderFactory.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectLoader.cs
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs
  src/Workspaces/MSBuild/Core/MSBuild/BuildHostProcessManager.cs
  src/Workspaces/MSBuild/Core/MSBuild/IBinLogPathProvider.cs
  src/Workspaces/MSBuild/Test/BuildHostProcessManagerTests.cs
Labels: Area-IDE, VSCode

#78552 Track used assemblies of data section string literals
  src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceModuleSymbol.cs
  src/Compilers/CSharp/Test/Emit/Emit/EmitMetadataTests.cs
Labels: Area-Compilers, Feature - String Literals in Data Section as UTF8

#78615 hotfix to fix restore and stop including bin/obj artifacts in directory with loose files
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/VirtualProject.cs
Labels: Area-IDE, VSCode

#78584 Give .NET Framework build task in sdk different identity
  Compilers.slnf
  Roslyn.sln
  src/Compilers/Core/MSBuildTask/Directory.Build.props
  src/Compilers/Core/MSBuildTask/Directory.Build.targets
  src/Compilers/Core/MSBuildTask/MSBuild/Microsoft.Build.Tasks.CodeAnalysis.csproj
  src/Compilers/Core/MSBuildTask/ManagedToolTask.cs
  src/Compilers/Core/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.csproj
  src/Compilers/Core/MSBuildTask/Microsoft.Managed.Core.targets
  src/Compilers/Core/MSBuildTask/README.md
  src/Compilers/Core/MSBuildTask/Sdk/Microsoft.Build.Tasks.CodeAnalysis.Sdk.csproj
  src/Compilers/Core/MSBuildTask/TaskTestHost.cs
  src/Compilers/Core/MSBuildTaskTests/CscTests.cs
  src/Compilers/Core/MSBuildTaskTests/MSBuildManagedToolTests.cs
  src/Compilers/Core/MSBuildTaskTests/Microsoft.Build.Tasks.CodeAnalysis.UnitTests.csproj
  src/Compilers/Core/SdkTaskTests/Microsoft.Build.Tasks.CodeAnalysis.Sdk.UnitTests.csproj
  src/Compilers/Core/SdkTaskTests/SdkManagedToolTests.cs
  src/Compilers/Extension/Roslyn.Compilers.Extension.csproj
  src/NuGet/Microsoft.Net.Compilers.Toolset/AnyCpu/Microsoft.Net.Compilers.Toolset.Package.csproj
  src/NuGet/Microsoft.Net.Compilers.Toolset/AnyCpu/build/Microsoft.Net.Compilers.Toolset.props
  src/NuGet/Microsoft.Net.Compilers.Toolset/DesktopCompilerArtifacts.targets
  src/NuGet/Microsoft.Net.Compilers.Toolset/Framework/Microsoft.Net.Compilers.Toolset.Framework.Package.csproj
  src/NuGet/Microsoft.Net.Compilers.Toolset/arm64/Microsoft.Net.Compilers.Toolset.Arm64.Package.csproj
  src/NuGet/VS.Tools.Roslyn.Package/VS.Tools.Roslyn.Package.csproj
  src/Setup/DevDivVsix/CompilersPackage/CompilersPackage.targets
  src/Tools/BuildBoss/CompilerNuGetCheckerUtil.cs
Labels: Area-Compilers

#78621 Fix angle brackets in generics in hover
  src/LanguageServer/Protocol/Extensions/ProtocolConversions.cs
  src/LanguageServer/ProtocolUnitTests/Hover/HoverTests.cs
Labels: Area-IDE, VSCode

#78594 Support consumption of binary extension operators
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/Binder/Binder_TupleOperators.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/BinaryOperatorOverloadResolution.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/UnaryOperatorOverloadResolution.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionOperatorsTests.cs
Labels: Area-Compilers, Feature - Extension Everything

#78633 Implement "non-generic method is better" rule in operator overload resolution
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/BinaryOperatorOverloadResolution.cs
  src/Compilers/CSharp/Portable/Binder/Semantics/Operators/UnaryOperatorOverloadResolution.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionOperatorsTests.cs
  src/Compilers/Test/Core/CompilationVerifier.cs
Labels: Area-Compilers, Feature - Extension Everything

#78644 LSP: Fix batch builds for file-based programs and fix `"dotnet.projects.binaryLogPath"` throwing an exception
  src/Workspaces/MSBuild/BuildHost/Build/ProjectBuildManager.cs
Labels: Area-IDE, VSCode

#78603 Ensure return local is the correct type for runtime async
  src/Compilers/CSharp/Portable/CodeGen/CodeGenerator.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs
  src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs
Labels: Area-Compilers, Feature - Runtime Async

#78629 Convert operand of `true`/`false` operator invoked as part of `&&`/`||`operator evaluation
  src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs
  src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml
  src/Compilers/CSharp/Portable/BoundTree/Constructors.cs
  src/Compilers/CSharp/Portable/BoundTree/NullabilityRewriter.cs
  src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs
  src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperator.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs
Labels: Area-Compilers

#78625 Extensions: rename syntax node
  src/Compilers/CSharp/CSharpAnalyzerDriver/CSharpDeclarationComputer.cs
  src/Compilers/CSharp/Portable/Binder/BinderFactory.BinderFactoryVisitor.cs
  src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs
  src/Compilers/CSharp/Portable/Declarations/DeclarationKind.cs
  src/Compilers/CSharp/Portable/Declarations/DeclarationTreeBuilder.cs
  src/Compilers/CSharp/Portable/Declarations/MergedTypeDeclaration.cs
  src/Compilers/CSharp/Portable/Declarations/SingleTypeDeclaration.cs
  src/Compilers/CSharp/Portable/Generated/CSharp.Generated.g4
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Internal.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Main.Generated.cs
  src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Syntax.Generated.cs
  src/Compilers/CSharp/Portable/Parser/LanguageParser.cs
  src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Extension.cs
  src/Compilers/CSharp/Portable/Syntax/ExtensionBlockDeclarationSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/InternalSyntax/TypeDeclarationSyntax.cs
  src/Compilers/CSharp/Portable/Syntax/Syntax.xml
  src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs
  src/Compilers/CSharp/Portable/Syntax/SyntaxKindFacts.cs
  src/Compilers/CSharp/Test/Emit3/Diagnostics/DiagnosticAnalyzerTests.AllInOne.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs
  src/Compilers/CSharp/Test/Syntax/Generated/Syntax.Test.xml.Generated.cs
  src/Compilers/CSharp/Test/Syntax/IncrementalParsing/IncrementalParsingTests.cs
  src/Compilers/CSharp/Test/Syntax/Parsing/ExtensionsParsingTests.cs
  src/Compilers/Core/Portable/Symbols/ITypeSymbol.cs
  src/EditorFeatures/CSharpTest/Diagnostics/DiagnosticAnalyzerDriver/DiagnosticAnalyzerDriverTests.cs
  src/Features/CSharp/Portable/ConvertPrimaryToRegularConstructor/ConvertPrimaryToRegularConstructorCodeRefactoringProvider.cs
  src/Features/CSharp/Portable/ConvertToExtension/ConvertToExtensionCodeRefactoringProvider.cs
  src/Tools/SemanticSearch/ReferenceAssemblies/Apis/Microsoft.CodeAnalysis.CSharp.txt
  src/Workspaces/CSharp/Portable/Classification/ClassificationHelpers.cs
  src/Workspaces/CSharp/Portable/FindSymbols/CSharpDeclaredSymbolInfoFactoryService.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/MemberDeclarationSyntaxExtensions.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Utilities/SyntaxKindSet.cs
Labels: Area-Compilers, Feature - Extension Everything, Needs API Review, VSCode

#78652 StaticLogMessage isn't pooling correctly
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/LogMessage.cs
Labels: Area-IDE, Community, VSCode

#78626 Extensions: disallow indexers
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs
Labels: Area-Compilers, Feature - Extension Everything

#78658 Add untriaged label to all new issues
  .github/policies/resourceManagement.yml
Labels: Area-Infrastructure

#78516 Hot Reload: Handle document deletes
  src/Compilers/Test/Core/FX/EncodingUtilities.cs
  src/EditorFeatures/Core/EditAndContinue/EditAndContinueLanguageService.cs
  src/EditorFeatures/Test/EditAndContinue/EditAndContinueLanguageServiceTests.cs
  src/Features/CSharp/Portable/EditAndContinue/CSharpEditAndContinueAnalyzer.cs
  src/Features/CSharpTest/EditAndContinue/CSharpEditAndContinueAnalyzerTests.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.ActiveMembersBuilder.cs
  src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/DebuggingSession.cs
  src/Features/Core/Portable/EditAndContinue/DocumentSemanticModel.cs
  src/Features/Core/Portable/EditAndContinue/DocumentWithRudeEdits.cs
  src/Features/Core/Portable/EditAndContinue/EditAndContinueDocumentAnalysesCache.cs
  src/Features/Core/Portable/EditAndContinue/EditSession.cs
  src/Features/Core/Portable/EditAndContinue/IEditAndContinueAnalyzer.cs
  src/Features/Core/Portable/EditAndContinue/IEditAndContinueSessionTracker.cs
  src/Features/Core/Portable/EditAndContinue/ProjectDocumentDifferences.cs
  src/Features/Core/Portable/EditAndContinue/RudeEditDiagnostic.cs
  src/Features/Core/Portable/EditAndContinue/SolutionUpdate.cs
  src/Features/Core/Portable/EditAndContinue/Utilities/Extensions.cs
  src/Features/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs
  src/Features/TestUtilities/EditAndContinue/EditAndContinueTestVerifier.cs
  src/Features/TestUtilities/EditAndContinue/EditAndContinueWorkspaceTestBase.cs
  src/Features/TestUtilities/EditAndContinue/Extensions.cs
  src/Features/VisualBasic/Portable/EditAndContinue/VisualBasicEditAndContinueAnalyzer.vb
  src/Features/VisualBasicTest/EditAndContinue/VisualBasicEditAndContinueAnalyzerTests.vb
Labels: Area-Interactive, untriaged, VSCode

#78668 Use SBRP version of M.CA for analyzers in the context of source build
  eng/Versions.props
Labels: Area-Infrastructure

#78671 Add IsPackable back to Microsoft.Build.Tasks.CodeAnalysis.csproj
  eng/Publishing.props
  src/Compilers/Core/MSBuildTask/MSBuild/Microsoft.Build.Tasks.CodeAnalysis.csproj
Labels: Area-Infrastructure

#78681 Add IsPackable to Microsoft.Build.Tasks.CodeAnalysis.Sdk.csproj
  src/Compilers/Core/MSBuildTask/Sdk/Microsoft.Build.Tasks.CodeAnalysis.Sdk.csproj
Labels: Area-Infrastructure

#78666 Use VerifyDiagnostics format to report CompileAndVerify diagnostics
  src/Compilers/Test/Core/Diagnostics/DiagnosticDescription.cs
  src/Compilers/Test/Core/ExceptionHelper.cs
Labels: Area-Compilers

#78687 Revert "Add IsPackable to Microsoft.Build.Tasks.CodeAnalysis.Sdk.csproj"
  src/Compilers/Core/MSBuildTask/Sdk/Microsoft.Build.Tasks.CodeAnalysis.Sdk.csproj
Labels: Area-Infrastructure

#78686 Revert "Add IsPackable back to Microsoft.Build.Tasks.CodeAnalysis.csproj"
  eng/Publishing.props
  src/Compilers/Core/MSBuildTask/MSBuild/Microsoft.Build.Tasks.CodeAnalysis.csproj
Labels: Area-Infrastructure

#78656 Compare symbols by metadata name when searching for eqivalent symbols in FAR engine
  src/EditorFeatures/CSharpTest/CodeLens/CSharpCodeLensTests.cs
  src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_Helpers.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/SymbolEquivalenceComparer.EquivalenceVisitor.cs
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Symbols/SymbolEquivalenceComparer.cs
Labels: Area-IDE, Community, VSCode

#78694 Add a test to verify that behavior is expected and bug no longer occurs
  src/EditorFeatures/CSharpTest/CodeLens/CSharpCodeLensTests.cs
Labels: Area-IDE, Community

#78691 Modify ABWQ.AddWork to take in a ROS instead of an IEnumerable
  src/Dependencies/Threading/AsyncBatchingWorkQueue`2.cs
  src/VisualStudio/Core/Def/DesignerAttribute/VisualStudioDesignerAttributeService.cs
Labels: Area-IDE

#78647 Update Workspace.MSBuild to reference Microsoft.Build.Framework.
  eng/Directory.Packages.props
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs
  src/LanguageServer/ProtocolUnitTests/Hover/HoverTests.cs
  src/Workspaces/MSBuild/BuildHost/BuildHost.cs
  src/Workspaces/MSBuild/BuildHost/Rpc/Contracts/IBuildHost.cs
  src/Workspaces/MSBuild/Core/MSBuild/MSBuildProjectLoader.cs
  src/Workspaces/MSBuild/Core/MSBuild/PathResolver.cs
  src/Workspaces/MSBuild/Core/MSBuild/SolutionFileReader.SolutionFilterReader.cs
  src/Workspaces/MSBuild/Core/MSBuild/SolutionFileReader.cs
  src/Workspaces/MSBuild/Core/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj
  src/Workspaces/MSBuild/Core/Rpc/RemoteBuildHost.cs
  src/Workspaces/MSBuild/Core/WorkspaceMSBuildResources.resx
  src/Workspaces/MSBuild/Core/xlf/WorkspaceMSBuildResources.cs.xlf
  src/Workspaces/MSBuild/Core/xlf/WorkspaceMSBuildResources.de.xlf
  src/Workspaces/MSBuild/Core/xlf/WorkspaceMSBuildResources.es.xlf
  src/Workspaces/MSBuild/Core/xlf/WorkspaceMSBuildResources.fr.xlf
  src/Workspaces/MSBuild/Core/xlf/WorkspaceMSBuildResources.it.xlf
  src/Workspaces/MSBuild/Core/xlf/WorkspaceMSBuildResources.ja.xlf
  src/Workspaces/MSBuild/Core/xlf/WorkspaceMSBuildResources.ko.xlf
  src/Workspaces/MSBuild/Core/xlf/WorkspaceMSBuildResources.pl.xlf
  src/Workspaces/MSBuild/Core/xlf/WorkspaceMSBuildResources.pt-BR.xlf
  src/Workspaces/MSBuild/Core/xlf/WorkspaceMSBuildResources.ru.xlf
  src/Workspaces/MSBuild/Core/xlf/WorkspaceMSBuildResources.tr.xlf
  src/Workspaces/MSBuild/Core/xlf/WorkspaceMSBuildResources.zh-Hans.xlf
  src/Workspaces/MSBuild/Core/xlf/WorkspaceMSBuildResources.zh-Hant.xlf
  src/Workspaces/MSBuild/Test/Resources/XmlSolutionFiles/CSharpXmlSolution.slnx
  src/Workspaces/MSBuild/Test/Resources/XmlSolutionFiles/InvalidXmlSolution.slnx
  src/Workspaces/MSBuild/Test/TestFiles/Resources.cs
  src/Workspaces/MSBuild/Test/VisualStudioMSBuildWorkspaceTests.cs
Labels: Area-IDE, VSCode

#78595 initial work to allow copilot to add imports when making recomendations.
  src/EditorFeatures/Core/ExternalAccess/UnitTestGenerator/Api/WrappedAddImportFixData.cs
  src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs
  src/Features/Core/Portable/AddImport/CodeActions/AddImportCodeAction.cs
  src/Features/Core/Portable/AddImport/IAddImportFeatureService.cs
  src/Features/Core/Portable/AddImport/SymbolReferenceFinder.cs
  src/Features/Core/Portable/AddImport/SymbolReferenceFinder_PackageAssemblySearch.cs
  src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs
  src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsRefactoringProvider.cs
  src/Features/Core/Portable/CodeRefactorings/AddMissingImports/IAddMissingImportsFeatureService.cs
  src/Features/Core/Portable/SymbolSearch/SymbolSearchOptions.cs
  src/VisualStudio/Core/Def/Options/VisualStudioOptionStorage.cs
Labels: Area-IDE, VSCode

#78665 Fixed crash in `CSharpConvertToRecordRefactoringProvider`
  src/Analyzers/CSharp/CodeFixes/ConvertToRecord/ConvertToRecordEngine.cs
  src/Features/CSharpTest/ConvertToRecord/ConvertToRecordCodeRefactoringTests.cs
Labels: Area-IDE, Community, VSCode

#78707 Handle error case: static ref field (No NullReferenceException)
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
Labels: Area-Compilers, Community

#78676 Mini Allocation-Reduction: avoid not needed compilationUnit clone
  src/Compilers/CSharp/Portable/Syntax/CSharpSyntaxTree.cs
Labels: Area-Compilers, Community

#78701 Fix crash with introduce local within a compilation unit
  src/Features/CSharp/Portable/CodeRefactorings/InlineMethod/CSharpInlineMethodRefactoringProvider.cs
  src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService.cs
  src/Features/CSharpTest/IntroduceVariable/IntroduceVariableTests.cs
  src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.cs
  src/Features/VisualBasic/Portable/IntroduceVariable/VisualBasicIntroduceVariableService.vb
Labels: Area-IDE, VSCode

#78712 Fix RS2007 not allowing table borders
  src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/ReleaseTrackingHelper.cs
  src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/ReleaseTrackingAnalyzerTests.cs
Labels: Area-Analyzers, Community

#78661 Update MicrosoftVisualStudioExtensibilityTestingVersion
  eng/Directory.Packages.props
  eng/Versions.props
  global.json
  src/Compilers/Extension/source.extension.vsixmanifest
  src/Deployment/source.extension.vsixmanifest
  src/ExpressionEvaluator/Package/source.extension.vsixmanifest
  src/VisualStudio/IntegrationTest/New.IntegrationTests/AbstractIntegrationTest.cs
  src/VisualStudio/IntegrationTest/TestSetup/source.extension.vsixmanifest
  src/VisualStudio/Setup.Dependencies/source.extension.vsixmanifest
  src/VisualStudio/Setup.ServiceHub/arm64/source.extension.vsixmanifest
  src/VisualStudio/Setup.ServiceHub/x64/source.extension.vsixmanifest
  src/VisualStudio/Setup/source.extension.vsixmanifest
  src/VisualStudio/VisualStudioDiagnosticsToolWindow/source.extension.vsixmanifest
Labels: Area-Infrastructure

#78722 Always log language server PID
  src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Program.cs
Labels: Area-IDE, VSCode

#78718 Add IsNull property to IAsyncToken
  src/Dependencies/Threading/TestHooks/IAsyncToken.cs
  src/Workspaces/Core/Portable/Shared/TestHooks/AsynchronousOperationListener+AsyncToken.cs
  src/Workspaces/Core/Portable/Shared/TestHooks/EmptyAsyncToken.cs
  src/Workspaces/Core/Portable/Shared/TestHooks/TaskExtensions.cs
Labels: Area-IDE, VSCode

#78646 Extensions: nullability analysis for property access
  Roslyn.sln
  src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs
  src/Compilers/CSharp/Portable/Emitter/Model/MostCommonNullableValueBuilder.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
  src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs
  src/Compilers/CSharp/Portable/Lowering/ExtensionMethodReferenceRewriter.cs
  src/Compilers/CSharp/Portable/Symbols/Extensions/SourceExtensionImplementationMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberMethodSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourceParameterSymbolBase.cs
  src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertyAccessorSymbol.cs
  src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedAccessorValueParameterSymbol.cs
  src/Compilers/CSharp/Test/Emit/Emit/DynamicAnalysis/DynamicInstrumentationTests.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs
  src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests2.cs
Labels: Area-Compilers, Feature - Extension Everything

#78645 Do not convert tuple expression with error to a bad expression too early
  src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs
  src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs
  src/Compilers/CSharp/Test/Semantic/Semantics/ValueTupleTests.cs
Labels: Area-Compilers, Community

#78742 Add direct IVTs to internal projects
  eng/targets/Settings.props
  src/Features/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.Features.csproj
  src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
  src/Workspaces/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.Workspaces.csproj
  src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
Labels: Area-IDE

#78748 Add numeric parameter checks refactoring
  Roslyn.sln
  src/EditorFeatures/CSharpTest/CodeActions/InitializeParameter/AddParameterCheckTests.cs
  src/EditorFeatures/VisualBasicTest/CodeActions/InitializeParameter/AddParameterCheckTests.vb
  src/Features/Core/Portable/FeaturesResources.resx
  src/Features/Core/Portable/InitializeParameter/AbstractAddParameterCheckCodeRefactoringProvider.cs
  src/Features/Core/Portable/xlf/FeaturesResources.cs.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.de.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.es.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.fr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.it.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ja.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ko.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pl.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.pt-BR.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.ru.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.tr.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hans.xlf
  src/Features/Core/Portable/xlf/FeaturesResources.zh-Hant.xlf
  src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Extensions/Compilation/CompilationExtensions.cs
Labels: Area-IDE, Community, VSCode

#78756 Add operator == and != for DocumentUri
  src/LanguageServer/Protocol/Protocol/DocumentUri.cs
  src/LanguageServer/ProtocolUnitTests/UriTests.cs
Labels: Area-IDE, VSCode

#78754 Update progression work to have context menu.
  src/EditorFeatures/Core/GoOrFind/AbstractGoOrFindCommandHandler.cs
  src/EditorFeatures/Core/GoOrFind/AbstractGoOrFindNavigationService.cs
  src/EditorFeatures/Core/GoOrFind/IGoOrFindNavigationService.cs
  src/VisualStudio/Core/Def/Commands.vsct
  src/VisualStudio/Core/Def/ID.RoslynCommands.cs
  src/VisualStudio/Core/Def/LanguageService/AbstractPackage.cs
  src/VisualStudio/Core/Def/PackageRegistration.pkgdef
  src/VisualStudio/Core/Def/xlf/Commands.vsct.cs.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.de.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.es.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.fr.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.it.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.ja.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.ko.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.pl.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.pt-BR.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.ru.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.tr.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.zh-Hans.xlf
  src/VisualStudio/Core/Def/xlf/Commands.vsct.zh-Hant.xlf
  src/VisualStudio/Core/Impl/SolutionExplorer/ContextMenuController.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/SymbolTree/RootSymbolTreeItemCollectionSource.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/SymbolTree/RootSymbolTreeItemSourceProvider.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/SymbolTree/SymbolItemContextMenuController.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/SymbolTree/SymbolTreeChildCollection.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/SymbolTree/SymbolTreeItem.cs
Labels: Area-IDE, VSCode

#78771 Move off of a linear walk in solution-explorer symbol tree updates.
  src/VisualStudio/Core/Impl/SolutionExplorer/SymbolTree/RootSymbolTreeItemCollectionSource.cs
  src/VisualStudio/Core/Impl/SolutionExplorer/SymbolTree/RootSymbolTreeItemSourceProvider.cs
Labels: Area-IDE

#78775 Don't refresh dynamic files under a lock
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.BatchingDocumentCollection.cs
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.cs
Labels: Area-IDE, VSCode

#78776 Fix cast before we unsubscribe
  src/VisualStudio/Core/Def/ProjectSystem/OpenTextBufferProvider.cs
Labels: Area-IDE

#78781 Switch return to continue
  src/Workspaces/Core/Portable/Workspace/ProjectSystem/ProjectSystemProject.BatchingDocumentCollection.cs
Labels: Area-IDE, VSCode
